[[opsi-script-cliparams]]
== Start und Aufrufparameter

Der _{opsi-script}_ enthält unter Windows seit Version 4.11.3 ein Manifest mit der Option: +
`<requestedExecutionLevel level="highestAvailable" />`. Dies bedeutet, dass unter NT6 als Administrator aufgerufen, versucht wird als 'elevated' Prozess zu arbeiten. Wird der _{opsi-script}_ mit User Rechten aufgerufen, so läuft er unter den Rechten dieses Users.

Wird der _{opsi-script}_ ohne Parameter  aufgrefufen, so startet er interaktiv.

_{opsi-script}_ kann ja nach Kontext und Verwendungszweck mit unterschiedlichen Parametern gestartet werden.

Es existieren eine Vielzahl von Optionen welche teilweise nur in Kombination und dann in der richtigen Reihenfolge verwendet werden können.

Note:: Unter Linux or macOS ist das Parameterzeichen nicht "/" sondern "-". Also statt unter Windows `opsi-script /help` unter Linux / macOS `opsi-script -help`.

Allgemeine Optionen:

* `/?` oder `/h`[elp] +
Hilfe aufrufen +

* `/silent` +
opsi-script ohne GUI ausführen +


Ausführung eines (oder mehrerer) Skripts: +
`opsi-script` <scriptfile>[;<scriptfile>]* [<logfile>] +
Dabei ist: +
<scriptfile> = Name der Scriptdatei inclusive Pfad +
<logfile> = Name der Logdatei inclusive Pfad +
Logpfade siehe auch: <<opsi-script-logpath>>

* `/parameter` <parameterstring> +
Einen String als (über die String-Funktion ParamStr) abfragbaren Parameter übergeben. +
Dabei ist <parameterstring> ein String der keine Leerzeichen enthält.

* `/logfile` <logfile>  +
Festlegen des Logfiles: +
Dabei ist: +
<logfile> = Name der Logdatei inclusive Pfad +
Logpfade siehe auch: <<opsi-script-logpath>>

* `/lang` <lang> +
Festlegen der Lokalisierung: +
Dabei ist: +
<lang> = Zwei Buchstaben Kurzbezeichnung der Sprache (de,en,fr,es,...)

* `/batch` +
Ausführen eines angegeben Scriptes mit Batchoberflache.
Die Batch-Oberfläche bietet keine Möglichkeiten für Benutzereingaben.In Kombination mit der Option `/silent` wird auch die Batch-Oberfläche ausgeblendet. Beim Aufruf ohne den Parameter `/batch` erscheint die Dialog-Oberfläche. Mit ihr ist die interaktive Auswahl von Skript- und Protokolldatei möglich (in erster Linie für Testzwecke gedacht).

* `/productid` <productId> +
Verwendung zusammen mit `/servicebatch` ; siehe dort.

* `/servicebatch` +
Ausführen eines angegeben Scriptes mit Batchoberflache und mit opsi-service Verbindung, so als würde das auch angegebene `/productid` auf 'setup' stehen. +
Dabei muß die Scriptdatei als erster Parameter angegeben sein. +
Dabei muß auch der Parameter `/opsiservice` und seine Zusatzparameter angegeben sein. +
Dabei muß auch der Parameter `/productid` angegeben sein. Dieser Parameter wird verwendet um in der Kommunikation mit dem opsi-Service das angegeben Script so auzuführen als wäre es das 'setup-script' des mit <productId> angegebenen opsi-produktes.

* `/logproductid` <productId> +
Bei der Erstellung der Logdatei soll <productId> als Quelle des Logs angegeben werden. +
Wird z.B. verwendet bei Scripten welche mit einem temporären user arbeiten und in dessem Kontext Scripte als Teil des Produktes <productId> ausgeführen.

* `/normalwindow` +
Schaltet im nicht interaktiven Modus die Maximierung der Batchoberfläche aus.

* `/usercontext` <[ domain\]username >  +
Wenn der angegebene user angemeldet ist, wird versucht
die Ermittlung von Konstanten wie `%CurrentAppdataDir%, %CurrentStartmenuDir%, %CurrentDesktopDir%, %CurrentStartupDir%, %CurrentProgramsDir%, %CurrentSendToDir%, %CurrentProfileDir%` im Kontext dieses Users auszuführen.
Meist verwendet im Zusammenhang mit der 'User Profile Management' Erweiterung.


* `/opsiservice` <opsiserviceurl> +
     `/clientid` <clientname> +
     `/username` <username> +
     `/password` <password> +
     [`/sessionid` <sessionid>] +
     [`/credentialfile` <credentialfile>] +
Angabe der Verbindungsdaten zum opsi-service: +
Dabei müssen entweder `/clientid` und `/username` und `/password`
sowie optional die `/sessionid` angegeben werden +
oder diese Daten werden in einem `/credentialfile` zur Verfügung gestellt.

Beeinflussung was im Kontext des `/opsiservice` getan werden soll: +

* Default (keine weiteren der folgenden Parameter): +
Abarbeitung der Aktionsanforderungen welche für den client auf dem opsi-server gespeichert sind.

* `/allloginscripts` oder `/loginscripts` +
Abarbeitung der Loginscripts der opsi-produkte. Dabei werden bei `/allloginscripts` alle dem opsi-server bekannten login-scripte ausgeführt und bei `/loginscripts` nur die Login-Scripte von Produkten welche auf dem Client installiert sind oder waren (es existiert für das Produkt ein productOnClient Objekt).

* `/productlist` <productid>[,<productid>]* +
Bearbeite die angegebene `/productlist` so, als würden für diese Produkte die Aktionsanforderung auf dem opsi-server auf 'setup' stehen. +
Üblicherweise verwendet vom `event_silent_install`.

* `/processproducts` <productid>[,<productid>]* +
Abarbeitung der Aktionsanforderungen welche für den client auf dem opsi-server gespeichert sind aber beschränkt auf die Liste welche mit `/processproducts` übergeben wurde.


////
(1) Ausführung eines Skripts:

`opsi-script` <scriptfile>
      [`/batch`] +
      [`/productid` <productid> ] +


(3) Ausführen einer Liste von Skripts:

`opsi-script` `/scriptfile` <scriptfile> [;<scriptfile>]* +
      [ `/logfile` <logfile> ] +
      [`/batch` | `/silent` ] +
      [`/usercontext` <[domain\]username> ] +

(4) Abarbeitung der Aktionsanforderungen auf dem opsi-server über den opsi Service (seit _{opsi-script}_ 4.11.2)

`opsi-script /opsiservice` <opsiserviceurl> +
     `/clientid` <clientname> +
     `/username` <username> +
     `/password` <password> +
     [`/sessionid` <sessionid>] +
     [`/credentialfile` <credentialfile>] +
     [`/depotpath` <credentialfile>] +
     [`/usercontext` <[domain\]username>] +
     [`/allloginscripts` | `/loginscripts`|  +
     `/productlist` <productid>[,<productid>]* | +
     `/processproducts` <productid>[,<productid>]* ] +

(4) Ausführung eines Skripts mit Verbindung zum opsi Service (seit _{opsi-script}_ 4.12.4.23)

`opsi-script /opsiservice` <opsiserviceurl> +
     `/clientid` <clientname> +
     `/username` <username> +
     `/password` <password> +
     [`/sessionid` <sessionid>] +
     [`/usercontext` <[domain\]username>] +
     [`/allloginscripts` | `/loginscripts`|  +
     `/productlist` <productid>[,<productid>]* | +
     `/processproducts` <productid>[,<productid>]* ] +
////

////

Generelle Erläuterungen:

* Default Name für die Logdatei ist unter Windows (ab 4.11.4) `C:\opsi.org\log\opsi-script.log`

* Der Parameterstring, angekündigt durch die Option "/parameter", wird an das jeweils aufgerufene _{opsi-script}_ Skript (über die String-Funktion ParamStr) übergeben.

Erläuterungen zu (2) und (3):

* Die Anwendung der Option `/batch` bewirkt, dass nur die Batch-Oberfläche angezeigt wird, die keine Möglichkeiten für Benutzereingaben bietet. Bei der Option `/silent` wird die Batch-Oberfläche ausgeblendet. Beim Aufruf ohne den Parameter `/batch` erscheint die Dialog-Oberfläche. Mit ihr ist die interaktive Auswahl von Skript- und Protokolldatei möglich (in erster Linie für Testzwecke gedacht).

* Wenn der Aufruf mit der Option `/usercontext <[domain\]username>` erfolgt, kann die Konfiguration für eine spezifizierten eingeloggten Nutzer erfolgen (besonders im Zusammenhang mit der 'User Profile Management' Erweiterung).


* Die Verwendung des Parameters `/histolist` gefolgt von opsi-scriptconfigfilepath bewirkt, dass in der Dialog-Oberfläche das Eingabefeld für den Skript-Dateinamen mit einer Historienliste erscheint und automatisch die zuletzt verwendete Datei erneut vorgeschlagen wird. Wenn opsi-scriptconfigfilepath nur ein Verzeichnis benennt (mit "\" abgeschlossen), wird als Dateiname 'WINST.INI' verwendet.

Erläuterungen zu (4):

* Default für clientid ist der full qualified Computername.

* Die Option `/allloginscripts` oder `/loginscripts` schaltet das Verhalten auf das Abarbeiten von 'userLoginScripts' um. +
Siehe hierzu im opsi-manual das Kapitel 'User Profile Management'.

* `/productlist` gefolgt von einer Liste von productIds, ignoriert die normale Abarbeitung von bestehenden Actionrequests. +
Vielmehr werden die in der Lists angegebenen Produkte so ausgeführt als hätten Sie den Actionrequest `setup`.

* `/processproducts` gefolgt von einer Liste von productIds, begrenzt die normale Abarbeitung von bestehenden Actionrequests +
auf die Produkte, welche in der Liste angegeben wurden. +
Achtung: Dadurch können evtl. bestehende Abhängigkeiten nicht aufgelöst werden.

* Die Option `/silent` schaltet die Batchoberfläche ab (keine Ausgaben).

Die Skripte werden per default im Batchmodus abgearbeitet.
////

[[opsi-script-logpath]]
=== Logging Dateien und Pfade

Die Default Logdatei heist `opsi-script.log`.
Es werden per default bis zu 8 Sicherungskopien angelegt: `opsi-script_0.log` bis `opsi-script_8.log`. +
Die Anzahl der Sicherungskopien kann per config <<opsi-script-configs_log_rotation_count>> geändert werden.

Die Logdateien werden im Encoding UTF-8 angelegt.

Die default Protokolldateien werden unter Windows in das Verzeichnis 'c:\opsi.org\log' geschrieben, welches der _{opsi-script}_ zu erstellen versucht. Wenn der _{opsi-script}_ nicht erfolgreich bei der Erstellung diese Protokollverzeichnisses ist, wird das Benutzer TEMP-Verzeichnis zum Speichern der Protokolldatei genutzt.

Logdateien unter Linux: +
Ausgeführt als root (default): `/var/log/opsi-script`
Ausgeführt als user: `/tmp`

Der Name der Protokolldatei und der Speicherort können durch eine spezifizierte Kommandozeile überschrieben werden.

In dem Fall, dass der _{opsi-script}_ ein Skript im `/batch` mode und mit einem spezifizierten (und funktionierenden) User Kontext aufgerufen wird, ist der voreingestellte Protokollpfad `opsi/tmp` in dem Anwendungsverzeichnis des Benutzers. Dieses wird überschreiben, wenn eine anderer Protokollpfad angegeben ist.

Zu weiteren Möglichkeiten das Logging zu beeinflussen: +
siehe auch: <<opsi-script-configs_writeProductLogFile>> +
siehe auch: <<opsi-script-configs_default_loglevel>> +
siehe auch: <<opsi-script-configs_force_min_loglevel>> +
siehe auch: <<opsi-script-configs_debug_lib>> +
siehe auch: <<opsi-script-configs_log_rotation_count>> +

Neben dem normalen Logfile wird auch eine `opsi-script.history` Logdatei geschrieben. Diese enthält für jeden Produktlauf seit der Installation eine Zeile nach dem Muster: +
`<timestamp> handled: <productid> Version: <version> Request: <request> Result: <result>` +
Beispiel: +
`2022-01-18 00:09  handled : gimp Version: 2.10.30-1 Request: setup Result: success` +


[[opsi-script-configs]]
=== Zentrale Konfiguration über opsi Configs (Host Parameter)

Über opsi Configs (`Host-Parameter`) kann das Logging beeinflusst werden:

anchor:opsi-script-configs_debug_prog[]

* `opsi-script.global.debug_prog` : boolean  +
Wenn false werden Logmeldungen welche zum Debuggen des opsi-script selber dienen
nicht ausgegeben, soweit es sich nicht um Warnungen oder Fehler handelt. +
Default: false +
Damit werden die Logdateien entlastet und nur noch Meldungen die Script relevant sind,
stehen in den Logdateien.
Die Umstellung der entsprechenden Logmeldungen im Quellcode des opsi-script,
ist noch nicht abgschlossen und wird bei ca. 1700 Log aufrufen auch noch etwas dauern.

anchor:opsi-script-configs_debug_lib[]

* `opsi-script.global.debug_lib` : boolean +
Wenn false, so werden Logmeldungen aus lokalen Funktionen welche aus Libraries importiert wurden, nur ausgegeben soweit es sich um Warnungen oder Fehler handelt. +
Default : false

anchor:opsi-script-configs_default_loglevel[]

* `opsi-script.global.default_loglevel` : intstr +
Setzt (überschreibt) den Standard defaultloglevel von opsi-script. +
Dieser Config hat keinen Einfluss auf Scripte bei denen der Loglevel per `setLogLevel` explizit gesetzt worden ist. +
Default :  '7' +
siehe auch <<SetLogLevel>> +
see also <<opsi-script-configs_force_min_loglevel>>


anchor:opsi-script-configs_force_min_loglevel[]

* `opsi-script.global.force_min_loglevel` : intstr +
Erzwingt einen minimalen Loglevel. +
Dies dient dazu bei der Entwicklung und/oder Fehlersuche gezielt und temporär für einzelne Clients den Loglevel zu erhöhen ohne hierzu Anpassungen am Script vornehmen zu müssen. +
Default: '0' +
siehe auch <<SetLogLevel>> +
see also <<opsi-script-configs_default_loglevel>>

anchor:opsi-script-configs_ScriptErrorMessages[]

* `opsi-script.global.ScriptErrorMessages` : boolean  +
Wenn false werden Syntax-Fehlermeldungen nicht interaktiv ausgegeben sondern nur in die Logdatei geschrieben. Im Produktivbetrieb ist es sinnvoll das dieser Parameter false ist.
Daher ist Default für diesen Config=false.
Der Default von opsi-script für diesen Parameter ist (aus historischen Gründen) true. Im Servicekontext überschreibt der Config den Default von opsi-script.
Ausserhalb des Servicekontext gilt der Default von opsi-script. Diese Default Werte können innerhalb eines scriptes mit der Anweisung `ScriptErrorMessages` überschrieben werden.
Default: false +
siehe auch : <<ScriptErrorMessages>>

anchor:opsi-script-configs_AutoActivityDisplay[]

* `opsi-script.global.AutoActivityDisplay` : boolean  +
Wenn true wird während des Laufs von externen Prozessen (winbatch,dosbatch,execwith Sektionen) ein (marquee) Fortschrittsbalken (der Endlos durch läuft) angezeigt. +
Default: true +
siehe auch : <<AutoActivityDisplay>>

anchor:opsi-script-configs_SupressSystemEncodingWarning[]

* `opsi-script.global.SupressSystemEncodingWarning` : boolean  +
Wenn true wird die Warnung: `Encoding=system makes the opsiscript not portable between different OS` unterdrückt. +
Default: false +
siehe auch : <<encoding>>

anchor:opsi-script-configs_ReverseProductOrderByUninstall[]

* `opsi-script.global.ReverseProductOrderByUninstall` : boolean  +
Wenn true wird die ProductListe umsortiert, so daß
uninstall Aktionen als erstes und in umgekehrter Reihenfolge der Installation durchgeführt werden. +
Default: false +

anchor:opsi-script-configs_log_rotation_count[]

* `opsi-script.global.log_rotation_count` : string (number) // seit 4.12.4.29 +
Gibt die Anzahl der lokal auf dem Client gesicherten Backups des `opsi-script.log` an. (`opsi-script_0.log, opsi-script_1.log, ...`) +
Default = 8 ; Maximal = 999 +

anchor:opsi-script-configs_writeProductLogFile[]

* `opsi-script.global.writeProductLogFile` : boolean   // seit 4.12.4.35 +
Wenn true wird auf dem Client im Unterverzeichnis `lastprodlogs` des opsi-script Logverzeichnisses ( z.B. `c:\opsi.org\log\lastprodlogs`) für jedes opsi-Produkt eine Logdatei eine Logdatei geschrieben. Der Name der Logdatei ist `<productId>.log`. Es existiert dann für jedes Prokt der Log des letzten Skript laufs. Im Fall, das ein Skript Reboots innerhalb des Skriptes beinhaltet so enthält dieses Log nur den Teil nach dem letzten Reboot. +
Default: false +


////
Removed by do 20210803)
anchor:opsi-script-configs_w10bitlockersuspendonreboot[]

* `opsi-script.global.w10bitlockersuspendonreboot` : boolean  +
Wenn true wird bei eine Rebootanforderung geprüft,
ob das Betriebssystem >= Windows 10 ist und Bitlocker auf der Systemlaufwerk z.B. C:) aktiv ist (encryption > 0%). Wenn dies der Fall ist, so wird per powershell ein `suspend-bitlocker` auf. +
(https://docs.microsoft.com/en-us/powershell/module/bitlocker/suspend-bitlocker?view=win10-ps) +
Dies sorgt dafür, das nach dem Reboot kein Bitlocker Passwort eingegeben werden muß. Das ist allerdings mit einem Sicherheitsverlust verbunden: +
"Suspension of BitLocker does not mean that BitLocker decrypts data on the volume. Instead, suspension makes key used to decrypt the data available to everyone in the clear." +
Default: false +
////

