////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype: book
:linclientmanual: opsi-linux-client-manual

include::common:partial$opsi_terms.adoc[]


[[opsi-script-configuration-options]]
= Weitere Konfigurationsoptionen

[[opsi-script-central-logging]]
== Zentrales Protokollieren von Fehlermeldungen

Wenn {opsi-script} im Kontext des opsi-service gestartet wird, werden die Protokoll-Informationen über den opsi-web-service an den opsi-server gesendet.

[[opsi-script-skins]]
== Skinnable '{opsi-script}' [W/L/M]

Ab Version 3.6 verfügt '{opsi-script}' einen veränderbare Oberfläche. Seine Elemente liegen im Unterverzeichnis winstskin des Verzeichnisses, in dem der ausgeführte _{opsi-script}_ liegt. Die editierbare Definitionsdatei ist skin.ini.

Seit Version 4.12.4.15 sucht der 'opsi-script' nach dem zu verwendenden Skin Verzeichnis in folgender Reihenfolge, wobei das erste Verzeichnis, welches eine skin.ini enthält verwendet wird:

*Windows*:

`%OpsiScriptDir% = C:\Program Files (X86)\opsi.org\opsi-client-agent\opsi-script`

. `%OpsiScriptDir%\..\custom\customskin`
. `%OpsiScriptDir%\skin`
. `%OpsiScriptDir%\winstskin`(for backward compatibility)

*Linux*:

`%OpsiScriptDir% = /opt/opsi-script`

. '/usr/share/opsi-script/skin'
. '/usr/share/opsi-script/customskin' (for backward compatibility)
. `%OpsiScriptDir%/skin`

siehe auch: <<opsi-script-linux-path, opsi-script-linux-path>>


*macOS*:

`%OpsiScriptDir% = /Applications/opsi-script/Contents/macOS`

. '/usr/share/opsi-script/skin'
. `%OpsiScriptDir%/../Resources/skin`

siehe auch: <<opsi-script-macos-path, opsi-script-macos-path>>

Mit dem Befehl `SetSkinDirectory` kann ein SkinDirectory auch im Script angegeben werden.
Wird bei diesem Befehl ein leerer oder ungültiger Pfad angegeben, so wird der Defaultpfad verwendet.

Beispiel:
[source,opsiscript]
----
SetSkinDirectory "%ScriptPath%\testskin"
sleepseconds 1
SetSkinDirectory ""
----

[[opsi-script-encoding]]
==  '{opsi-script}' encoding [W/L/M]


*Einige Hinweise zu den verwendeten Begriffen:*

* `ASCII, plain ASCII` +
ASCII ist eine Abkürzung von: American Standard Code for Information Interchange +
'plain ascii': 7 Bit pro Zeichen; kann 128 verschiedene Zeichen darstellen. Hier enthalten sind die arabischen Ziffern, die Zeichen des lateinischen Alphabetes in Groß- und Kleinschreibung sowie eine Reihe von Sonder- und Steuerzeichen. +
Diese 128 Zeichen finden sich auch in den nachfolgend beschriebenen Erweiterungen wieder.

* `ANSI, Codepages` +
Verwendet 8 Bit pro Zeichen (also ein Byte). Damit können
Die ersten (unteren) 128 Zeichen entsprechen plain ASCII. Die oberen 128 Zeichen sind für unterschiedliche Alphabete in unterschiedlichen 'Codepages' definiert.
Bekannte 'code pages': +
Windows-1252 = CP1252 = ISO 8851-1 = Western Europe code page. +
Die 256 Zeichen von CP1252 sind auch die Basis von Unicode UTF-16. +
'ANSI' ist eine Abkürzung von: American National Standards Institute: +
https://stackoverflow.com/questions/701882/what-is-ansi-format : +
'ANSI encoding is a slightly generic term used to refer to the standard code page on a system, ( ... )The name "ANSI" is a misnomer, since it does not correspond to any actual ANSI standard, but the name has stuck.' +
In Deutsch: +
'ANSI encoding ist ein verbreiteter Begriff um sich auf die Standard code page eines Systems zu beziehen. (....) Der Name "ANSI" ist allerdings falsch und irreführend, da es keinen entsprechenden ANSI-Standard gibt. Trotzdem ist der Begriff allgemein üblich.' +
Was ist dann mit dem Begriff ANSI encoding gemeint ? +
https://wiki.freepascal.org/Character_and_string_types#AnsiChar says: +
'A variable of type AnsiChar, also referred to as char, is exactly 1 byte in size, and contains one "ANSI" (local code page) character.' +
In Deutsch: +
'Ein ANSI Zeichen hat eine Länge von einem Byte und ist gemäß der lokalen code page definiert.' +
Die Probleme mit der Verwendung von Codepages sind: +
** Für unterschiedliche Regionen in der Welt müssen unterschiedliche Codepages verwendet werden. +
** Es können nur maximal 255 Zeichen dargestellt werden aber viele Alphabete haben deutlich mehr Zeichen.

* `Unicode, UTF-8` +
'Unicode' ist (wie 'ANSI') eine Encodingfamilie (nicht ein Encoding). +
Der bedeutenste Unterschied im Vergleich zu code pages ist, das um ein Zeichen zu codieren hier bis zu 4 Bytes verwendet werden. Damit können 'alle' Alphabete in einem Encoding untergebracht werden. +
Die wichtigsten Mitglieder der 'Familie' Unicode sind:

** `UTF-16-LE` (auch teilweisebezeichnet als  'Windows Unicode'): +
Hier wird für jedes Zeichen mindestens 2 Byte (bis zu 4 Byte) verwendet. Das 'LE' steht für 'Little Endian' und gibt Auskunft über die Reihenfolge der Bytes. (Zeichen 'n' : LE='6E 00', BE='00 6E').

** `UTF-8`: +
Verwendet für alle 'plain ASCII' Zeichen 1 Byte. Für alles was darüberhinaus geht werden 2 bis 4 Byte verwendet. +
Dies bedeutet auch, das eine Datei welche nur 'plain ASCII' Zeichen enthält es binär keinen Unterschied macht, ob diese nun als 'UTF-8' oder 'cp1252' abgespeichert worden ist.

** `BOM` +
Eine Datei mit einem 'Unicode' encoding kann (muß aber nicht) in den ersten 4 Byte eine Information über das verwendete (unicode-)Encoding enthalten - den 'BOM' ('Byte Order Mark'). opsi-script erkennt und verwendet einen 'BOM' so er vorhanden ist.

Das Default Encoding für ein Script ist das Encoding das Systems auf dem der _{opsi-script}_ läuft. D.h. auf einem Griechischen System wird das script mit unter Windows mit cp1253 interpertiert während das selbe Script auf einem deutschem Windows System mit cp1252 und auf einem Linux oder macOS System mit UTF-8 interpretiert wird.

TIP: Wir empfehlen dringend alle opsiscript Dateien in UTF-8 encoding zu erzeugen und die Zeile `encoding=utf8` in die Datei einzufügen. +
Dies macht Ihre Dateien besser portierbar. +
Siehe hierzu auch den nachfolgenden Abschnitt.

anchor:encoding[]

* `encoding=`<encoding> +
Seit Version 4.11.4.1 kann bei einem Script (egal ob Hauptscript, sub, include oder library) das encoding auch angegeben werden. Dazu gibt es den Befehl: +
`encoding=`<encoding> +
Dieser Befehl kann an einer beliebigen Stelle in der Scriptdatei stehen. +
Wird dieser Befehl nicht gefunden, so wird zunächst davon ausgegangen, das das Encoding der Datei dem Systemencoding des laufenden Betriebssystems entspricht. Unter Linux und macOS wäre dies UTF-8. Unter Windows ist dies ein cp* abhängig von der Lokalisierung. In Westeuropa z.B. cp1252. +
Wenn die einzulesende Datei Umlaute enthält (also nicht nur 'plain ASCII' ist), so führt das fehlen der Zeile `encoding=utf8` zu der Warnung: +
'Encoding=system makes the opsiscript not portable between different OS'. +
Diese Warnung kann unterdrückt werden durch den config (Hostparameter): +
`opsi-script.global.supresssystemencodingwarning = true`. +
siehe auch <<opsi-script-configs_supresssystemencodingwarning>> +
Wenn die einzulesende Datei Umlaute enthält (also nicht nur 'plain ASCII' ist) und es einen Widerspruch zwischen dem detectierten Encoding (z.B. über ein BOM) und dem impliziten Encoding `system` bzw. dem per `encoding=` angegebenen Encoding gibt, so wird folgende Warnung in das Log geschrieben: +
'Warning: Given encodingString <> is different from the expected encoding <>' +
 +
Bei der Verwendung von `encoding=`<encoding> +
kann <encoding> ist eines der folgenden Werte sein:

.Encodings
[options="header"]
|==========================
|encoding|erlaubter alias|Bemerkung
|system	|	|	verwende encoding des laufenden OS
|auto	|	|	versuche das encoding zu erraten.
|UTF-8      |   utf8	|
|UTF-8BOM   |   utf8bom	|
|Ansi       |   ansi     |			8 Bit Encoding mit Codepage
|CP1250     |   cp1250   |			Zentral- und osteuropäische Sprachen
|CP1251     |   cp1251   |			Kyrillisches Alphabet
|CP1252     |   cp1252   |			Westeuropäische Sprachen
|CP1253     |   cp1253   |			Griechisches Alphabet
|CP1254     |   cp1254   |			Türkisches Alphabet
|CP1255     |   cp1255   |			Hebräisches Alphabet
|CP1256     |   cp1256   |			Arabisches Alphabet
|CP1257     |   cp1257   |			Baltische Sprachen
|CP1258     |   cp1258   |			Vietnamesische Sprachen
|CP437      |   cp437    |			Die ursprüngliche Zeichensatztabelle des IBM-PC
|CP850      |   cp850    |			"Multilingual (DOS-Latin-1)", westeuropäische Sprachen
|CP852      |   cp852    |			Slawische Sprachen (Latin-2), zentraleuropäische und osteuropäische Sprachen
|CP866      |   cp866    |			Kyrillisches Alphabet
|CP874      |   cp874    |			Thai Alphabet
|CP932      |   cp932    |			Japanische Schreibsysteme (DBCS)
|CP936      |   cp936    |			GBK für chinesische Kurzzeichen (DBCS)
|CP949      |   cp949    |			Hangul/Koreanische Schriftzeichen (DBCS)
|CP950      |   cp950    |			Chinesische Langzeichen (DBCS)
|ISO-8859-1 |   iso8859-1|			Latin-1
|ISO-8859-2 |   iso8859-2|			Latin-2
|KOI-8      |   koi8     |			Kyrillisches Alphabet
|UCS-2LE    |   ucs2le, utf16le   |			(UTF-16-LE, Windows Unicode Standard)
|UCS-2BE    |   ucs2be, utf18be   |			(UTF-16-BE)
|==========================

siehe auch : <<reencodestr>> +
siehe auch : <<reencodestrlist>> +
siehe auch : <<strLoadTextFileWithEncoding>> +
siehe auch : <<loadUnicodeTextFile>> +
siehe auch : <<loadTextFileWithEncoding>> +

Quellen siehe auch:

https://de.wikipedia.org/wiki/Codepage

http://msdn.microsoft.com/en-us/library/windows/desktop/dd317752%28v=vs.85%29.aspx

http://msdn.microsoft.com/en-us/library/cc195054.aspx

https://de.wikipedia.org/wiki/ANSI-Zeichencode

https://de.wikipedia.org/wiki/UTF-8
