////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype:   book
:release:	testing

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]

[[opsi-4.2-releasenotes]]
= opsi Version 4.2 Release Notes

// Include common opsi copyright
include::../common/opsi_manual_copyright.asciidoc[]

[[opsi-4.2-releasenotes-overview]]
== Überblick über neue Features

*Schwerpunkte in diesem Release:*

* Wechsel zu Python 3
* Alle python Applikationen werden als ausführbare Binärdateien verteilt
* opsi server
** Komplette Neuimplementation vom opsiconfd mit Schwerpunkt auf Performance und Scalability
** opsiconfd ist nun auch in einem docker Container lauffähig
** Neue Abhängigkeit zu Redis Server >= 5 inklusive dem RedisTimeSeries Modul
** Grafana wird nun zur virtualisierung der Performancedaten genutzt
** python-opsi Interpreter für eigene Skripte
** Neuer Default in der acl

[[opsi-4.2-releasenotes-important]]
== Important considerations - Please pay attention

opsi 4.2 ist ein eigenständiges Release und hat seine eigenen repositories.
Diese müssen dem System hinzugefügt bzw. müssen diese mit die alten Repositories ersetzen, bevor die Installation/Upgrade durchgeführt werden.

Für ein Update von opsi 4.1 müssen die installierten Pakete auf dem letzten stable Stand aktualisiert sein. 
Andere Pakete - wie z.B. MySQL server - sollten ebenfalls auf einem aktuellen Stand sein. 
Andernfalls kann es zu Fehlern während dem Updateprozess führen. 

Es wird ebenfalls dringend empfohlen die Pakete 'opsi-winst', 'opsi-client-agent' oder 'opsi-linux-client-agent' auf den Clients auf den letzten Stand von opsi 4.1 aktualisiert werden, bevor das Update gestartet wird.

=== Python 3
opsi 4.2 basiert nun komplett auf Python 3.
Weiterhin werden nun alle Python-basierten Pakete als ausführbare Binärdateien verteilt.
Das Paket 'python-opsi' wird nicht mehr als installiertes Paket zur Verfügung gestellt.
Deshalb sind folgende Punkte wichtig zu klären:

==== Opsi-Pakete die Serverseitige Python Skripte enthalten
Bitte nutzen Sie den 'opsi-package-manager', um opsi Pakete neu zu installieren, die Python-Skripte für die Ausführung auf dem Server enthalten:

* +opsi-client-agent+: `opsi-deploy-client-agent`
* +win*+: `create_driver_links.py`, `show_drivers.py`

Das postinst Skript korrigiert dabei automatisch diese Skripte und setzt den neuen Interpreter.

Alternativ dazu kann man die Python Skripte auch manuell korrigieren.
Hierfür muss der Interpreter auf +opsi-python+ (Eintragung vpn `#!/usr/bin/opsi-python` als 'shebang') gesetzt werden.

==== Eigene Python-Skripte die python-opsi nutzen (import OPSI)
Sollten Skripte eingesetzt werden, die von python-opsi abhängen, müssen folgende Schritte ausgeführt werden:
* Konvertieren der Skripte auf Python 3 (dazu kann man das Pythoneigene `2to3` nutzen um dies zu erreichen).
* Umstellung auf `opsi-python`, welches `python-opsi` als eigenen interpreter zur Verfügung stellt (Eintragen von `#!/usr/bin/opsi-python` als 'shebang').

=== opsiconfd Konfiguration und Logs
Es gibt einige Änderung bei der Konfiguration und den Logs des 'opsiconfd'.

* Alle Konfigurationsoptionen sind im Hilfetext des opsiconfd dokumentiert ('opsiconfd --help').
* Alle Optionen starten mit '--' und können ebenfalls in der Konfigurations gesetzt werden (ohne '--').
* opsiconfd hat nun eine eingebaute Logrotation. Diese kann mit den Optionen 'max-log-size' und 'keep-rotated-logs' konfiguriert werden.
* Die Logdatei 'package.log' ist nun Bestandteil von der 'opsiconfd.log'.
* Die Logs beinhalten nun einen Kontext, welche für die Filterung der Logs genutzt werden können. Zum Beispiel kann man mit 'grep' nach diesen filtern oder dem opsiconfd beim Start die Option '--log-filter LOG_FILTER' mitgeben:

[source,prompt]
----
opsiconfd --log-filter instance=package_install
----

[source,prompt]
----
[6] [2020-09-07 14:41:17.864] [package_install] Running postinst script   (Depotserver.py:235)
[5] [2020-09-07 14:41:17.865] [package_install] Running package script 'postinst'   (Product.py:477)
...
----

[source,prompt]
----
opsiconfd --log-filter client_addr=10.100.7.5
----

[source,prompt]
----
[6] [2020-09-07 14:25:16.966] [10.100.7.5     ] Filtering objects by acls   (AccessControl.py:475)
...
----

==== Backend Erweiterungen (/etc/opsi/backendManager/extend.d)
Sollten Sie selbst die Konfigurationsdateien von `/etc/opsi/backendManager/extend.d` modifiziert oder neue hinzugefügt haben, müssen diese Änderung auf Python 3-Kompatibilität geprüft und gegebenfalls angepasst werden.

[[opsi-4.2-releasenotes-installation]]
== Installationshinweise

Wir empfehlen dringend for dem Update eine Sicherung der Backends mit {opsi-backup} zu erstellen:
[source,prompt]
----
opsi-backup create
----

Die Produkte welche im Rahmen dieses Releases veröffentlicht werden,
sind in etlichen Teilen voneinander abhängig.
Sie sollten daher nicht versuchen, nur Teile zu installieren.

Wir empfehlen zuerst den Server und danach die opsi-Produkte zu aktualisieren.

In einer Multi-Depot-Umgebung wird empfohlen die Aktualisierung auf dem Configserver zu beginnen und erst danach die Depots zu aktualisieren.

Wir empfehlen nach dem Update die Ausführung von `opsi-setup --set-rights`,
um sicher zu stellen, dass die Zugriffsberechtigungen korrekt gesetzt sind.
Die Ausführung des Befehls kann mehrere Minuten in Anspruch nehmen.


[[opsi-4.2-releasenotes-installation-systempackages]]
=== Hinweise zum Aktualisieren der Betriebssystem-Pakete

Bitte stellen Sie sicher, dass Sie zum Zeitpunkt der Aktualisierung die jeweils aktuellsten Pakete von opsi 4.1 aus dem Stable-Bereich verwenden!


[[opsi-4.2-releasenotes-installation-opsipackages]]
=== Hinweise zum Aktualisieren von opsi-Paketen

opsi-Pakete sind in der Regel kompatibel zu sowohl opsi 4.1 als auch opsi 4.2.

Die offiziellen opsi 4.2 Repositories auf _download.uib.de_ enthalten Pakete, welche mit opsi 4.1 kompatibel sind.
Bitte beachten Sie, dass diese Pakete nicht zwingend `4.2` als Version angegeben haben müssen, um kompatibel zu sein.


[[opsi-4.2-releasenotes-installation-migration]]
=== Migration eines opsi 4.1 Servers

Auf unterstützten Betriebsystemen ist es möglich eine bestehende opsi 4.1 Installation auf opsi 4.2 zu migrieren.

Falls die opsi-Server durch opsi gemanaged werden, so kann die Migration mit dem Paket `l-opsi-server-migrate` durchgeführt werden.

NOTE: Eine Aktualisierung von opsi 4.0 direkt auf opsi 4.2 wird nicht unterstützt. In diesen Fällen muss erst eine Aktualisierung auf opsi 4.1 durchgeführt werden, bevor eine Aktualisierung auf opsi 4.2 möglich ist.

[[opsi-4.2-releasenotes-installation-migration-prerequired]]
==== Vorbedingung für eine Migration

opsi braucht seit 4.2 zusätzlich Zugriff auf jeweils eine Redis- und Grafana-Instanz. Sollen diese Dienste ebenfalls auf dem opsi-Server bereitgestellt werden, empfehlen wir einen Umstieg auf das Paket 'opsi-server-full' während der Migration. Dieses Paket installiert und konfiguriert alles notwendige auf dem opsi-Server (im folgenden wird dies als Single-Server-Setup beschrieben). 

Bei beiden angesprochenen Installationsvarianten werden die Grafana-Repos benötigt:

===== Debian/Ubuntu:

[source,prompt]
----
sudo apt-get install -y apt-transport-https software-properties-common wget
wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
echo "deb https://packages.grafana.com/oss/deb stable main" > /etc/apt/sources.list.d/grafana.list
----

===== RHEL/CentOS:

[source,prompt]
----
yum install wget
cd /etc/yum.repos.d/
cat <<EOF > grafana.repo
[grafana]
name=grafana
baseurl=https://packages.grafana.com/oss/rpm
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://packages.grafana.com/gpg.key
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
EOF
----

[[opsi-4.2-releasenotes-installation-migration-repositories]]
==== Wechseln zu den neuen Repositories

Als erstes müssen die opsi 4.1 Repositories korrekt in die Paketquellen Ihres Betriebsystems eingetragen werden.

Die nachfolgenden Befehle fügen die neuen Repositories hinzu und fügen außerdem den Repository-Schlüssel hinzu, sofern benötigt.
Diese Befehle benötigen 'root'-Rechte.

*Ubuntu 20.04 LTS _Focal Fossa_:*
[source,prompt]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_20.04/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_20.04/Release.key | sudo apt-key add -
----

*Ubuntu 18.04 LTS _Bionic Beaver_:*
[source,prompt]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_18.04/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_18.04/Release.key | sudo apt-key add -
----

*Debian 10 _Buster_:*
[source,prompt]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.1:/{release}/Debian_10/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Debian_10/Release.key | sudo apt-key add -
----

*Debian 9 _Stretch_:*
[source,prompt]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Debian_9.0/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Debian_9.0/Release.key | sudo apt-key add -
----

*CentOS 8:*
[source,prompt]
[subs="attributes"]
----
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/CentOS_8/home:uibmz:opsi:4.2:{release}.repo
yum makecache
----

*RHEL 8:*
[source,prompt]
[subs="attributes"]
----
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/RHEL_8/home:uibmz:opsi:4.2:{release}.repo
yum makecache
----


[[opsi-4.2-releasenotes-installation-migration-migrate]]
==== Aktualisierung der Betriebssystem-Pakete

Nach dem Eintragen der neuen Paketquellen kann das System migriert werden.

IMPORTANT: Der default der acl `/etc/opsi/backendManager/acl.conf` hat sich mit opsi 4.2 aus Sicherheitsgründen verändert. Sollten Sie nicht genau Wissen was Sie tun, empfehlen wir Ihnen dringend die Standard acl Konfiguration zu benutzen.

IMPORTANT: Bei RPM-basierten Distributionen werden im Rahmen der Migration bereits vorhandene Konfigurationsdateien durch Neue ersetzt. Beachten Sie hierzu die Hinweise unter den entsprechenden Distributionen.



Debian und Ubuntu werden mit folgenden Befehlen auf opsi 4.2 aktualisiert:

*Single-Server-Setup:*
[source,prompt]
----
apt update
apt install opsi-server-full
----

*Manuelles Setup:*
[source,prompt]
----
apt update
apt install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
apt dist-upgrade
----

RedHat und CentOS werden mit folgenden Befehlen auf opsi 4.2 aktualisiert:

*Single-Server-Setup:*
[source,prompt]
----
yum makecache
yum install opsi-server-full
yum upgrade
----

*Manuelles Setup:*
[source,prompt]
----
yum makecache
yum install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
yum upgrade
----

OpenSUSE wird mit folgenden Befehlen auf opsi 4.2 aktualisiert:

*Single-Server-Setup:*
[source,prompt]
----
zypper refresh
zypper install opsi-server-full
----

*Manuelles Setup:*
[source,prompt]
----
zypper refresh
zypper install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
zypper dup --from home_uibmz_opsi_4.2_{release}
----

////
On UCS you can update with the following command:
[source,prompt]
----
univention-upgrade
----
////

[[opsi-4.2-releasenotes-installation-migration-opsi-packages]]
==== Aktualisierung der opsi-Pakete

Der letzte Schritt ist die Aktualisierung auf die neusten opsi-Pakete.

[[opsi-4.2-releasenotes-installation-migration-opsi-packages-standard]]
===== Verwendung der Standardkonfiguration

Wenn Sie keine Veränderungen gegenüber der Standard Auslieferung unter `/etc/opsi/package-updater.repos.d/` vorgenommen haben, können Sie die opsi-Pakete direkt über den aufgeführten Aufruf aktualisieren:

[source, prompt]
----
opsi-package-updater -v update
----

Nach diesen Schritten ist Ihr opsi 4.1 Server auf das Release 4.2 migriert und einsatzbereit.

[[opsi-4.2-releasenotes-installation-migration-cleanup]]
==== Optionale Aufräumarbeiten

After a migration it can be that some unrequired files still exist on the server.
The reason for this is that they either have been altered manually or that restoring a backup has brought these files back to the system.

The following files resp. folders can be removed:

* TBD


[[opsi-4.2-releasenotes-knownbugs]]
== Known Bugs / Known Problems

.KNOWN BUGS:

* opsi-admin: The interactive mode does not work with non-ASCII characters like special umlauts ö, ä, ü.

.KNOWN PROBLEMS:

* SLES und Univention UCS werden in diesem Release noch nicht unterstützt. Es wird aber daran gearbeitet.


[[opsi-4.2-releasenotes-eol]]
== Discontinuation

This chapters lists discontinuations.


[[opsi-4.2-releasenotes-eol_server]]
=== Abkündigung: Distributionen für opsi-server

Diese Distributionsversionen werden aus verschiedenen Gründen nicht weiter von opsi unterstützt.

* CentOS 7.x
* Debian 8.x
* RedHat Enterprise Linux 7.x
* Suse Linux Enterprise Server 12

Siehe auch gesondertes Kapitel: <<opsi-4.2-releasenotes-supportmatrix>>.


[[opsi-4.2-releasenotes-supportmatrix]]
== opsi Support Matrix

Im folgenden finden Sie eine Übersicht auf welchen Plattformen opsi
als Server läuft.

include::supportmatrix-server.asciidoc[]

Sollten Sie den opsi-server auf einer Betriebssystemversion einsetzen,
welche im vorigen Abschnitt nicht als Unterstützt aufgeführt ist,
so empfehlen wir Ihnen ein Betriebssystem-Update bevor Sie opsi 4.2 einspielen.


[[opsi-releasenotes-4.2-changes-changed-defaults]]
== Geänderte Standardeinstellungen

Mit opsi 4.2 wurden einige Standard-Einstellungen geändert, um Erfahrungen aus dem opsi-Betrieb wiederzuspiegeln.

Wichtig ist dies vorallem, wenn in einer bestehenden Umgebung neue opsi-Server installiert werden, da sich diese unter Umständen anders verhalten.

* Die geänderte acl.conf beachten.


[[opsi-releasenotes-4.2-changes-python]]
== Wechsel zu Python 3 und PyInstaller

Diese Version basiert auf Python 3.
Alle opsi Python Applikationen (opsiconfd, opsipxeconfd, opsiclientd, opsi-utils, ...) werden nun als ausführbare Dateien mit PyInstaller ausgeliefert.
Bitte nutzen Sie den `opsi-python` Interpreter für Ihre eigenen Skripte, welche Zugriff auf die python-opsi library benötigen.

[[opsi-releasenotes-4.2-changes-mysql-config]]
== MySQL backend: Limitierung der "connection lifetime"

Um die Fehlermeldungen: "mysql server has gone away" zu vermeiden, wurde die Standardkonfiguration des MySQL Backends geändert. Die Option `connectionPoolRecycling` hat nun als Standardwert: _28800_.
Diese Einstellung limitiert die Lebenszeit der Verbindungen im Connection Pool, welches für die Verbindungen zu MySQL (bzw. MariaDB) Server genutzt wird.


[[opsi-4.2-releasenotes-linux]]
== Linux Support

=== Support Matrix

include::supportmatrix-linclient.asciidoc[]

[[opsi-4.2-releasenotes-netboot-windows]]
== opsi Support Matrix Windows Clients

In the following graphic you will find on which Windows platforms opsi can be run as client.

include::supportmatrix-winclient.asciidoc[]


[[opsi-4.2-releasenotes-api-changes]]
== API changes

The API has received changes in opsi 4.2.

This affects the API of the webservice, `opsi-admin`, calls made through
`opsiServiceCall` in opsicript among others.


[[opsi-4.2-releasenotes-changed-api-methods]]
=== Changed API methods

 * `getClients_listOfHashes`: Method has been marked as deprecated during opsi 4.1. If called without parameters will return result from `getClients` in other cases an error will be returned.
 * `getClientIds_list`: Method has been marked as deprecated during opsi 4.1. If called without parameters will return result of `getClientIDs`. If called with parameter `depotIds` then the result of `getClientsOnDepot` will be returned. If called with parameters `productId` and optionally `installationStatus` the result of `getClientsWithProducts` will be returned.


[[opsi-4.2-releasenotes-deprecated-api-methods]]
=== Deprecation of API methods

The following methods are considered deprecated.
This means they will be removed with the next major or minor release.

 * `getClients_listOfHashes`
 * `getClientIds_list`


[[opsi-4.2-releasenotes-removed-api-methods]]
=== Removal of API methods

The following API methods have been removed:

* `backend_searchIdents`

These methods aren't available anymore.


[[opsi-4.2-releasenotes-misc]]
== Miscellaneous

* opsiwebservice does not support decompressing deflate-encoded data anymore.


[[opsi-4.2-releasenotes-packages]]
== List of packages

.Server packages:
* opsi4ucs 4.2...
* opsiconfd 4.2...
* opsipxeconfd 4.2...
* opsi-server 4.2...
* opsi-utils 4.2...
* opsi-linux-bootimage 

NOTE: The updated opsi packages are also made available for opsi 4.1 with this release. The exception for this are `l-opsi-server` and `l-opsi-server-migrate`.

// Changelogs
include::./opsi-v4.2-changelogs.asciidoc[]
