////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      11.01.2021
:doctype: book
:getstarted:  getting started

include::common:partial$opsi_terms.adoc[]

// = opsi Getting Started opsi-version 4.2




[[opsi-getting-started-introduction]]
= Introduction

These instructions explain in detail the installation and starting of an {opsi-server}. It starts from the provided installation package and leads to the test installation of a client.

The installation and commissioning of an {opsi-Server} is done in several steps:

. Basic installation of the server
. Configuration of the server (adaptation to network conditions, setting up users and passwords, installation of products to be distributed)
. Recording and integration of computers in opsi.
. Deploying Windows to Clients.
. Packaging and distribution of own software

Then an operating system including software can be automatically installed on a client and a hardware and software inventory can be performed.

Further features are described in the opsi manual.
There, you will also find explanations about the co-financed extensions and their setup.

The shown network configuration is exemplary and refers to a network without competing DHCP servers (e.g. an isolated test network in which the {opsi-Server} and its clients can be placed for the first tests).

We strongly suggest that you make your first tests with opsi in a test network that is separate from other DHCP servers, but which you can temporarily connect to your main network, e.g. to download updates and packages from the Internet.

For the integration into existing networks you can use link:https://uib.de/de/support-schulung/support/[consulting services by uib].


[[opsi-getting-started-convention]]
== Conventions of this document

Commands are highlighted separately:

[source,prompt]
----
this is a command
----

During installation and configuration, you can usually copy and execute the commands from these fields one after the other using _copy & paste_ from this document.


