////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      21.04.2023
:Revision:  4.2
:toclevels: 6
:doctype:   book
:icons: font
:xrefstyle: full
:chapter-label:

ifeval::["{mode}" == "antora"]
include::common:partial$opsi_terms.adoc[]
endif::[]

[[opsi-getting-started-introduction]]
= Introduction

This manual describes how to install an opsi server and how to operate it. Setting up an opsi server requires several steps:

. Installing the server
. Configuring the server (network, users and passwords, products)
. Setting up clients
. Importing existing products
. Packaging and distribution of your own software

TIP: For a detailed description of all features as well as descriptions of the paid extensions, please read xref:manual:introduction.adoc[opsi Components in Detail].

NOTE: For the first opsi experiments we recommend working in a test environment and in an isolated network--i.e. without competing DHCP servers. The test network needs internet access to install packages from remote sources and updates if necessary. If you need help integrating with existing networks, link:https://uib.de/de/support-schulung/support/[contact us].


