////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      21.04.2023
:Revision:  4.2
:toclevels: 6
:doctype:   book
:icons: font
:xrefstyle: full
:chapter-label:

ifeval::["{mode}" == "antora"]
include::common:partial$opsi_terms.adoc[]
endif::[]

[[opsi-getting-started-introduction]]
= Introduction

This manual describes how to install an opsi server and how to operate it. Setting up an opsi server requires several steps:

. Installing the server
. Configuring the server (network, users and passwords, products)
. Setting up clients
. Importing existing products
. Packaging and distribution of your own software

TIP: For a detailed description of all features as well as descriptions of the paid extensions, please read xref:manual:introduction.adoc[opsi Components in Detail].

NOTE: For the first opsi experiments we recommend working in a test environment and in an isolated network--i.e. without competing DHCP servers. The test network needs internet access to install packages from remote sources and updates if necessary. If you need help integrating with existing networks, link:https://uib.de/de/support-schulung/support/[contact us].

[[opsi-getting-started-introduction-term]]
== Working on the Command Line

Throughout the rest of the chapter (and also in the other chapters of this manual) we introduce commands which you enter on the command line. You can do this via a terminal application directly on the server, or you can access the opsi server from another computer via SSH. On Linux and macOS use the command `ssh` for this. On Windows you can use the program link:https://www.chiark.greenend.org.uk/~sgtatham/putty/[PuTTY]. As user name enter `root` and authenticate yourself with the root password entered during the installation.

On the opsi server there are different ways to open a terminal window:

* Double click the LXTerminal icon on the desktop background.

* Open the start menu and navigate to a terminal application (_System Tools_ menu).

* Press the key combination [Alt]+[F2]; on most desktops this opens a quick launcher. Type `terminal` to list any installed terminal programs, and then select the application you want.

TIP: We've formatted commands in this manual so that you can copy{nbsp}&{nbsp}paste them directly into a terminal window, if the terminal program supports it.

Example snippets from configuration files are formatted like this:
[source,configfile]
----
depoturl = smb://smbhost/sharename/path
----

Commands are formatted like this:
[source,shell]
----
cd /tmp
ls -l
----
