////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      20.03.2023
:Revision:  4.2
:toclevels: 6
:doctype: book
:getstarted:  getting started

ifeval::["{mode}" == "antora"]
include::common:partial$opsi_terms.adoc[]
endif::[]

// = opsi Getting Started opsi-version 4.2

[[opsi-getting-started-introduction]]
= Introduction

This manual describes how to install an opsi server with our packages and how to operate it. The guide also explains how to set up an opsi client for testing purposes.

To set up an opsi server, you have to carry out several steps:

. Installing the server
. Configuring the server (network, users and passwords, products)
. Setting up clients
. Importing existing products
. Packaging and distribution of your own software

TIP: For a detailed description of all features as well as descriptions of the paid extensions, please read the xref:introduction.adoc[opsi Manual].

NOTE: For the first opsi experiments we recommend working in a test environment and in an isolated network--i.e. without competing DHCP servers. The test network needs internet access to install packages from remote sources and updates if necessary. If you need help integrating with existing networks, link:https://uib.de/de/support-schulung/support/[contact us].

[[opsi-getting-started-convention]]
== Conventions and Notations

We use the following notations and highlighting in this manual:

* File and directory names appear in `proportional font`.
* Longer commands and listings are in separate boxes; you can conveniently copy{nbsp}&{nbsp}paste them: +
[source,prompt]
----
this is a command
----
* Menu items and button labels appear in _italics_.
* Keys and key combinations are enclosed in square brackets, e.g. [C], [Ctrl]+[C], etc.
