////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the German creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype:   book
:toc: left
:toclevels: 3
:numbered:
:icons: font
:xrefstyle: full
:chapter-label:
:gstarted:  getting started
:source-highlighter: rouge
:release:   stable

[[opsi-getting-started-firststeps-software-deployment-product-tests]]
== Rollout existing products

For the rollout of software on clients the 'opsi-client-agent' must be installed.
This can be deployed on <<opsi-getting-started-firststeps-software-deployment-client-integration,existing computers>>.
If an <<opsi-getting-started-firststeps-osinstall,operating system is installed>> via opsi, the 'opsi-client-agent' will be installed automatically.

Afterwards the management interface <<opsi-getting-started-firststeps-software-deployment-configed,{opsi-configed}>> is used to distribute software to clients.


[[opsi-getting-started-firststeps-software-deployment-product-tests-configed]]
=== Deploying opsi standard products: opsi-configed

One of the opsi standard products is the product `opsi-configed`, which installs the opsi Management Interface. This Application is a Java application, therefore a Java Runtime Engine is bundled with the product.

Using '{opsi-configed}', in the mode 'Configuration of clients', choose the appropriate client in the tab 'Clients'.

If you have not already done so, update the data of {opsi-configed} by using 'File / Reload all data' or click the reload icon.

Switch to the tab 'Product configuration', look for the line with the product `opsi-configed`. Click in the column 'Requested Action', and select the action 'setup'.

The check mark in the icon menu bar should change its color to red. If you click on it, the new settings will be transmitted to the {opsi-Server}, afterwards its color will be green again.

Reboot the client.
The opsi-client-agent should start and install the product +opsi-configed+.
After the installation you can find `opsi-configed` in the `start menu`.


[[opsi-getting-started-firststeps-software-deployment-product-tests-inventory]]
=== Hard- and Software Inventory with the localboot products hwaudit and swaudit

Using '{opsi-configed}', in the mode 'Configuration of clients', choose the appropriate client in the tab 'Clients'.

If you have not already done so, update the data of {opsi-configed} by using 'File / Reload all data' or click the reload icon.

Switch to the tab 'Product configuration', look for the line with the product +hwaudit+. Click in the column 'Requested Action', and select the action 'setup'. Repeat this for the product +swaudit+.

The check mark in the icon menu bar should change its color to red. If you click on it, the new settings will be transmitted to the {opsi-Server}, afterwards its color will be green again.

Reboot the client.
The opsi-client-agent should start and install the products +hwaudit+ and +swaudit+.
With +hwaudit+ and +swaudit+, hardware and software information is collected and transmitted to the {opsi-Server}.
The collected data is displayed under the 'Hardware information' or 'Software inventory' tabs.


[[opsi-getting-started-firststeps-software-deployment-product-tests-hwinvent]]
[[opsi-getting-started-firststeps-osinstall-tests-hwinvent]]
=== Hardware Inventory with the netboot product hwinvent

If the product 'hwinvent' is installed on your opsi server and you have added a client <<opsi-getting-started-firststeps-osinstall-create-client>> which is configured to boot over the network, you can do something else useful: Hardware inventory when there is no operating system installed.

Using '{opsi-configed}', in the mode 'Configuration of clients', choose the appropriate client in the tab 'Clients'.
If you have not already done so, update the data of {opsi-configed} by using 'File / Reload all data' or click the reload icon.
Switch to the tab 'Netboot products', look for the line with the product +hwinvent+. Click in the column 'Requested Action', and select the action 'setup'.
The check mark in the icon menu bar should change its color to red.
If you click on it, the new settings will be transmitted to the {opsi-Server}, afterwards its color will be green again.

Then reboot the client. It should now pull a Linux image over the network (via PXE), to scan the hardware of the PC and then reboot it. If the computer was not otherwise already set up, afterwards the message appears that no operating system is installed on the disk.

The results of the hardware scan have been transmitted to the {opsi-Server}. The results can be viewed under the 'Hardware information' tab.

NOTE: In case the screen remains black after booting the bootimage or if the network card does not work (correctly), the start parameters of the bootimage may have to be adjusted for this specific hardware. +
This can be achieved using '{opsi-configed}' in the 'Host parameters' tab by editing the entry 'opsi-linux-bootimage.append'. +
More information can be found in the opsi manual, in the chapter 'netboot products'.
