////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      11.01.2021
:doctype: book
:getstarted:  getting started

[[firststeps-software-deployment-product-tests]]
include::common:partial$opsi_terms.adoc[]



= Rollout existing products

For the rollout of software on clients the 'opsi-client-agent' must be installed.
This can be deployed on xref:adding-clients.adoc#opsi-getting-started-firststeps-software-deployment-client-integration[existing computers].
If an xref:os-installation.adoc#opsi-getting-started-firststeps-osinstall[operating system is installed] via opsi, the 'opsi-client-agent' will be installed automatically.

Afterwards the management interface xref:opsiconfiged.adoc#opsi-getting-started-firststeps-software-deployment-configed[{opsi-configed}] is used to distribute software to clients.

include::common:partial$firststeps-swdp-product-tests-configed.adoc[]

include::common:partial$firststeps-swdp-product-tests-inventory.adoc[]

include::common:partial$firststeps-hwinvent.adoc[]

