////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:xrefstyle: full
:doctype: book

include::common:partial$opsi_terms.adoc[]


= Schnittstellen

Der opsi-Server verfügt über mehrere Schnittstellen, die verschiedene Funktionen erfüllen.
Als Adminuser können alle Endpunkte über https://<opsi-server>:4447/docs eingesehen und sogar ausgeführt werden.

== JSON RPC

Die Daten des Server können über die JSON RPC Schnittstelle manipuliert werden. 
Eine genau Beschreibung der JSON RPC API finden Sie im nächsten Kapitel xref:interfaces/jsonrpc-api.adoc[JSON RPC API].

== Webgui Schnittstelle
Ist das opsiconfd Addon opsi-WebGui installiert, dann wird der Server um eine REST-API erweitert. 
Diese API ist speziell auf die Bedürfnisse der WebGui angepasst.
 

== Sonstige API Endpunkte

- */status* : Kann ohne Anmeldung verwendet werden und gibt einfache Statusausgabe für Monitoring-Werkzeuge aus.

[source,console]
----
status: ok
version: 4.3.0.104 [python-opsi-common=4.3.0.73]
date: 2023-11-10T15:50:48+01:00
node: opsi-acme-43_opsi-server_1
fqdn: opsi.acme.corp
redis-status: ok
redis-error: 
redis-mem: 32911240
redis-mem-total: 36806536
ssl-ca-valid-days: 713
ssl-cert-valid-days: 73
----

- */monitoring*: Endpunkt für die Erweiterung opsi-nagios-connector. Weiter Informationen finden Sie xref:opsi-modules:nagios-connector.adoc[hier].



