////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      17.04.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-macclient-introduction]]
= macOS Clients

This guide focuses on managing macOS clients in opsi environments, covering several key aspects:

* Adding and integrating macOS computers into opsi (installation of the xref:clients:macos-client/mac-client-agent.adoc[Client Agent])
* Deploying standard software on the opsi server
* Deploying standard software on macOS clients
* Creating opsi packages and packaging your own software
* Notes on macOS clients
    ** Special commands for macOS
    ** Directories you may use
    ** Pseudo account `opsisetupadmin`

NOTE: To manage macOS clients, it's essential to have an xref:server:overview.adoc[opsi Server] already installed and operational.

[[opsi-macclient-convention]]
include::ROOT:partial$conventions.adoc[]
