////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      25.04.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



[[opsi-manual-mac-client-agent]]
= Client Agent (macOS)

include::common:partial$opsi-client-agent.adoc[]

[[opsi-manual-client-agent-macos-directories]]
== Important Directories

The macOS client agent's components are located under `/usr/local/lib`. The executable opsi programs can be found in `/usr/local/bin`, which is included in the standard path. The configuration file `opsiclientd.conf` is located in the directory `/private/etc/opsi-client-agent/`; `root` privileges are required to read and edit it.

You can find Logfiles in the directories under `/private/var/log/`. `/private/var/log/opsi-client-agent` contains the logs from `opsiclientd` and `opsi-notifier`. `opsi-script` and the client agent store logs in `/private/var/log/opsi-script`.
