////
; Copyright (c) uib GmbH (uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      17.04.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



[[opsi-macclient-requirements]]
= Prerequisites

In this chapter, you’ll find the necessary details for managing macOS clients with opsi. First, a table presents the macOS versions supported by opsi 4.3, followed by details concerning the Arm-based Apple M1 processor.

NOTE: The macOS client agent is a xref:opsi-modules:modules.adoc[paid extension]. This means that you need a license file to unlock it. You will receive this file after you have purchased the extension. For evaluation purposes, we’re happy to provide you with a temporary license free of charge. Please contact us via mailto:info@uib.de[email].

== Supported macOS Versions

include::{version}@opsi-docs-en:common:partial$supportmatrix-macclient-core.adoc[]

CAUTION: Following the macOS updates officially released by Apple in December 2023, it has become necessary to grant full disk access to the opsiclientd process to facilitate normal functioning of the `opsi-mac-client-agent`. This adjustment can be made in the macOS system settings under _Privacy & Security_ or through an Apple MDM message using the type `PrivacyPreferencesPolicyControl`.

NOTE: This step is not necessary for operation in WAN mode. Therefore, as a further option, we generally recommend operating all Mac clients, i.e. even non-WAN clients, in WAN mode to avoid this problem.

== Mac Computers with Apple Chip

If your Mac features Apple's M1 Arm processor, you'll require the Rosetta framework to install the opsi-client-agent. Here’s how to install Rosetta:

[source,console]
----
softwareupdate --install-rosetta --agree-to-license
----

You can verify that the installation was successful using the `pkgutil` command. The output should look something like this, for example:

[source,console]
----
$ pkgutil --pkgs | grep Rosetta
com.apple.pkg.RosettaUpdateAuto
----

