////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      25.04.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-macclient-firststeps-software-deployment-product-tests]]
= Rolling out Existing Products


For the deployment of software to clients, the 'opsi-client-agent' must be installed on them.
This can be rolled out on xref:macos-client/adding-clients#opsi-macclient-firststeps-software-deployment-client-integration[existing-machines].


Subsequently, the xref:macos-client/rollout-products.adoc#opsi-macclient-firststeps-software-deployment-product-tests-configed[opsi-configed] management interface is used to deploy software to clients.

[[opsi-macclient-firststeps-software-deployment-product-tests-inventory]]
== Inventory with the localboot products hwaudit and swaudit.

In _opsi-script_, 'Client configuration' mode, under the 'Clients' tab, select the client under consideration.

If not already performed, update the opsi-configed's dataset using 'Reload File/Data' or clicking the corresponding icon.

Go to the 'Product configuration' tab, click in the 'Requested' column for the +hwaudit+ product, this will open a list/dropdown menu and there select the 'setup' action. Repeat this for the +swaudit+ product.

The check mark in the icon menu bar should change its color to red. If you click it, the new settings will be transmitted to the opsi-Server, afterwards its color will be green again.

Then restart the client.
It should now start the +opsi-client-agent+ and install the +hwaudit+ and +swaudit+ products.
With +hwaudit+ and +swaudit+, hardware and software information, respectively, is collected and transmitted to the opsi-Server.
The collected information is displayed under the 'Hardware Information' and 'Software Inventory' tabs, respectively.

[[opsi-macclient-firststeps-software-deployment-product-tests-homebrew]]
== Distribution of opsi standard products: m-homebrew.

This product installs the package management program `homebrew` which is used by several other opsi products for MacOS, e.g. to install Java.

See also: xref:macos-client/general-notes.adoc#opsi-macclient-hints-homebrew[The opsi product m-homebrew].

In _opsi-script_, 'Client configuration' mode, select the client in question under the 'Clients' tab.

Switch to the 'Product Configuration' tab, click in the 'Requested' column for the +m-homebrew+ product, this will open a list/dropdown menu and there select the 'setup' action.

The check mark in the icon menu bar should change its color to red. If you click on it, the new settings will be transmitted to the opsi-Server, afterwards its color will be green again.

Then restart the client or push the installation via 'on_demand'.
It should now start the +opsi-client-agent+ and install the +m-homebrew+ product.

[[opsi-macclient-firststeps-software-deployment-product-tests-java]]
== Distribution of opsi standard products: m-javavm

This product installs the Java Runtime Environment which is used by several other opsi products for MacOS, e.g. opsi-configed, opsi-logviewer.

In _opsi-script_, mode 'Client configuration', select the client under the tab 'Clients'.

Switch to the 'Product Configuration' tab, click in the 'Requested' column for the +m-javavm+ product, this will open a list/dropdown menu and there please select the 'setup' action.

The check mark in the icon menu bar should change its color to red. If you click on it, the new settings will be transmitted to the opsi-Server, afterwards its color will be green again.

Then restart the client or push the installation via 'on_demand'.
It should now start the +opsi-client-agent+ and install the +m-javavm+ product.

[[opsi-macclient-firststeps-software-deployment-product-tests-configed]]
== Distribution of opsi standard products: opsi-configed.

Attention: m-homebrew and m-javavm must be already installed!

To the standard products belongs the product `opsi-configed` which installs the opsi management interface as application on a computer.
Because this application is a Java application, a JavaRE is included.

In the _opsi-script_, mode 'Client configuration', under the tab 'Clients' select the concerning client.

If not already done, update the opsi-configed's dataset using 'Reload File/Data' by clicking the corresponding icon.

Switch to the 'Product configuration' tab, click in the 'Requested' column for the +opsi-configed+ product, this will open a list/dropdown menu and there select the 'setup' action.

The check mark in the icon menu bar should change its color to red. If you click it, the new settings will be transmitted to the opsi-Server, afterwards its color will be green again.

Then restart the client.
It should now start the +opsi-client-agent+ and install the +opsi-configed+ product.
After the installation is finished you should find the item `opsi-configed` under `Applications`.
