////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      28.02.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-macclient-softwintegration]]
= Integration of own software into the software distribution of opsi.

The installation of software in opsi is performed by the opsi-client-agent and specially by the script controlled setup program opsi-script. Therefore an opsi-script script must be created for each opsi product. Afterwards this script, as well as the installation files and metadata are packed into an opsi product, which can finally be installed on the opsi-Server.

[[opsi-macclient-softwintegration-tutorial]]
== Tutorial: Creating an *opsi-script* Script

include::common:partial$softwintegration-tutorial-introduction.adoc[]

[[opsi-macclient-softwintegration-tutorial-general]]
=== Methods of non-interactive software installation on macOS.

Apple (unlike Microsoft) standardized its software installation methods very early on. In essence, there are two methods:

* *application Directory*: +
This is a directory according to the pattern:
`<application name>.app` However, such a directory is not displayed in the _Finder_ as a directory, but as an 'application'. Inside this directory, according to a pattern, the files of the application must be located. A typical structure would be:

----
opsi-script.app
  |--Contents
       |-Info.plist
       |-PkgInfo
       |-MacOS
       |  |-opsi-script
       |  |-opsi-script-gui
       |
       |-Resources
          |- (....)
----

Such a directory must only be copied into the path `/Applications` for installation. Possible files in the directory `MacOS` must be made executable. +
Such *.app directories are usually offered packed for download.

* *PKG file*: +
These files contain software which need to be installed by a special command.

In both cases an _unattended_ (i.e. non-interactive) installation is not an issue.

Often macOS software is offered in packed formats like *.zip, *.dmg
or also *.tgz.

All variants mentioned so far can be installed directly by opsi-script, except *.tgz which must be unpacked before.

include::common:partial$softwintegration-tutorial-script-structure-opsi-script-basics.adoc[]

[[opsi-macclient-softwintegration-tutorial-macos-special-commands]]
== Special Commands for macOS

* `GetOS`: Returns the operating system, e.g. `Linux`, `Windows_NT` (Windows NT to Windows 11) or `macOS`.

* `getMacosVersionInfo`: Returns the macOS version.

* `getMacosVersionMap`: Returns a list of information, including the build version, kernel name, processor type, etc.

TIP: For more information on these string functions, see xref:opsi-script-manual:prim-section.adoc#opsi-script-string-functions-os[Determine string functions (operating system)].

// cspell: ignore uib_macosinstalllib

=== macOS Commands for Installation

NOTE: The following sections present special macOS commands for installing software. They are taken from the `opsi-script` library `uib_macosinstalllib`. This part of the documentation is in English because it was automatically generated from the source code.

:leveloffset: +2

include::{version}@opsi-docs-en:common:partial$os-lib-uib-macosinstalllib.adoc[]

:leveloffset: -2

[[opsi-macclient-softwintegration-tutorial-template]]
== Example: macOS template *m-opsi-template*

You can create this template with the `opsi-setup-detector` (see section <<opsi-macclient-softwintegration-tutorial-create-with-opsi-setup-detector>>).

// include docu: actual template for macOS
include::{version}@opsi-docs-en:common:partial$firststeps-opsi-template-mac.adoc[]

[[opsi-client-softwintegration-create-opsi-package]]
== Creating opsi Products

The following sections explain how to package software, i.e. create opsi products. The basic process looks like this:

1. you create the "shell" of a package with the `opsi-setup-detector` (see section <<opsi-macclient-softwintegration-tutorial-create-with-opsi-setup-detector>>).
2. then test the `opsi-script` script (see section <<opsi-softwintegration-tutorial-create-and-test-script>>).
3. use the opsi PackageBuilder (oPB) to create an opsi package from the raw form and store it on the opsi server.

// include docu: opsi-setup-detector installation
include::common:partial$setup-detector-installation.adoc[]

// include docu: opsi-logviewer installation
include::common:partial$opsi-logviewer-installation.adoc[]

// cspell: ignore Installer, Paketierung

[[opsi-macclient-softwintegration-tutorial-create-with-opsi-setup-detector]]
== *opsi-setup-detector*: Creating a Script

The following sections explain in detail how to use the `opsi-setup-detector` to analyze an opsi product setup file and create an opsi product.

// include docu: opsi-setup-detector
include::common:partial$setup-detector-use-start.adoc[]

include::common:partial$osd-tasks-macos.adoc[]

NOTE: The following screenshots show the procedures for Windows installer files, but they look similar on macOS if you use installer files like `.app`, `.dmg` or `.zip`.

// include docu: how to use the opsi-setup-detector
include::common:partial$osd-task-use-single-analyze-and-create.adoc[]

// include docu: The modify and test cycle
include::common:partial$softwintegration-tutorial-modify-test-cycle.adoc[]

[[opsi-winclient-softwintegration-tutorial-template-details]]
== Packaging: Notes on subtasks

The following sections show further configuration options of the `opsi-setup-detector`. They cover the use of a user-defined directory, the installation from a local temporary directory, the management of license keys and the customization of user profiles and desktop icons.

include::common:partial$osd-checkboxes-subtasks.adoc[]


