////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      29.04.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-macclient-softwintegration]]
= Integrating custom Software

The installation of software using opsi is managed either by the xref:clients:macos-client/mac-client-agent.adoc[Client Agent] or the setup program xref:opsi-script-manual:opsi-script-manual.adoc[*opsi-script*]. When packaging your own software for deployment through opsi, it’s necessary to create an `opsi-script` script for each product. This script, along with the installation files and metadata, should be packed. As a result, you’ll get an opsi product which is then installed on the opsi server (see the chapter xref:clients:macos-client/minimal-products.adoc[Adding Products (opsi Server)]).

[[opsi-macclient-softwintegration-tutorial]]
== Tutorial: Creating an *opsi-script* Script

include::common:partial$softwintegration-tutorial-introduction.adoc[]

[[opsi-macclient-softwintegration-tutorial-general]]
=== Non-interactive software installation (macOS)

Apple (unlike Microsoft) standardized its software installation methods very early on. In essence, there are two methods:

* *Application Directory*: +
The `/Applications` folder on macOS holds directories for programs, known as `<program>.app`. In Finder, these directories don’t appear as typical folders but are presented as program launchers. Each `<program>.app` directory contains the necessary data—files and subdirectories—for that particular application. To install, simply copy this directory into `/Applications`. You might also need to set the execution permissions for files within the `MacOS` subdirectory. Typically, these `.app` directories are compressed into packages for download, reflecting this common structure:

[source]
----
opsi-script-gui.app
  |--Contents
       |-Info.plist
       |-PkgInfo
       |-MacOS
       |  |-opsi-script-gui
       |  |-opsi-script
       |  |- […]
       |
       |-Resources
          |- […]
----

* *PKG File*: +
Apple's package format includes the software itself, the folder structure described earlier, installation scripts, and other resources.

Unattended installations can be conducted without user interaction for both types of packages.

NOTE: macOS software is frequently distributed in compressed formats like `.zip`, `.dmg`, or `.tgz`. `opsi-script` is capable of installing these applications as well. However, you must first unpack `.tgz` files.

include::common:partial$softwintegration-tutorial-script-structure-opsi-script-basics.adoc[]

[[opsi-macclient-softwintegration-tutorial-macos-special-commands]]
== Special Commands for macOS

* `GetOS`: Returns the operating system, e.g. `Linux`, `Windows_NT` (Windows NT to Windows 11) or `macOS`.

* `getMacosVersionInfo`: Returns the macOS version.

* `getMacosVersionMap`: Returns a list of information, including the build version, kernel name, processor type, etc.

TIP: For more information on these string functions, see the section xref:opsi-script-manual:prim-section.adoc#opsi-script-string-functions-os[String Functions which Return the OS Type].

// cspell: ignore uib_macosinstalllib

=== macOS Commands for Installation

NOTE: The following sections present special macOS commands for installing software. They are taken from the `opsi-script` library `uib_macosinstalllib`. This part of the documentation was automatically generated from the source code.

:leveloffset: +2

include::{version}@opsi-docs-en:common:partial$os-lib-uib-macosinstalllib.adoc[]

:leveloffset: -2

[[opsi-macclient-softwintegration-tutorial-template]]
== Example: macOS Template *m-opsi-template*

You can create this template with the `opsi-setup-detector` (see the section <<opsi-macclient-softwintegration-tutorial-create-with-opsi-setup-detector>>).

// include docu: actual template for macOS
include::{version}@opsi-docs-en:common:partial$firststeps-opsi-template-mac.adoc[]

[[opsi-client-softwintegration-create-opsi-package]]
== Creating opsi Products

The following sections explain how to package software, i.e., create opsi products. The basic process is outlined as follows:

1. Create the "shell" of a package using the `opsi-setup-detector` (see section <<opsi-macclient-softwintegration-tutorial-create-with-opsi-setup-detector>>).
2. Test the `opsi-script` script (see section <<opsi-softwintegration-tutorial-create-and-test-script>>).
3. Use the opsi PackageBuilder (oPB) to create an opsi package from the initial framework and store it on the opsi server.

// include docu: opsi-setup-detector installation
include::common:partial$setup-detector-installation.adoc[]

// include docu: opsi-logviewer installation
include::common:partial$opsi-logviewer-installation.adoc[]

// cspell: ignore Installer, Paketierung

[[opsi-macclient-softwintegration-tutorial-create-with-opsi-setup-detector]]
== *opsi-setup-detector*: Creating a Script

The following sections provide a detailed walkthrough on how to use the `opsi-setup-detector` for analyzing an opsi product setup file and creating an opsi product.

// include docu: opsi-setup-detector
include::common:partial$setup-detector-use-start.adoc[]

include::common:partial$osd-tasks-macos.adoc[]

NOTE: The screenshots included demonstrate the process for Windows installer files; however, the steps are similar on macOS when dealing with installer files such as `.app`, `.dmg`, or `.zip`.

// include docu: how to use the opsi-setup-detector
include::common:partial$osd-task-use-single-analyze-and-create.adoc[]

// include docu: The modify and test cycle
include::common:partial$softwintegration-tutorial-modify-test-cycle.adoc[]

[[opsi-winclient-softwintegration-tutorial-template-details]]
== Advanced Configuration with *opsi-setup-detector*

The following sections detail additional configuration options available in the `opsi-setup-detector`. They cover the use a user-defined directory, the installation from a local temporary directory, the management of license keys, and the customization of  user profiles and desktop icons.

include::common:partial$osd-checkboxes-subtasks.adoc[]


