////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      22.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

= opsi-Server

This chapter is about the opsi server, the central component of the client management system. The chapter xref:server:installation/installation.adoc[Installation] describes different possibilities to install an opsi server. In xref:server:components/components.adoc[Tools & Settings] it is then about the operation (tools and configuration).

[[opsi-manual-server-overview]]
== Server variants

Basically, there are two different server types that can be installed on the same or on different machines (see section xref:server:components/opsiconfd.adoc#server-components-opsiconfd-server-id-role[server-role]).

* *opsi configserver*:
The central control component of each opsi environment is the opsi configserver.
There is only one opsi configserver in each environment.
The opsi configserver provides the configuration and status data via an API.
All server, client and management components are coupled via this central API.
An opsi config server usually also takes over the role of an opsi depot server.

* *opsi depot server*:
An opsi depot server provides files of the software, operating systems and boot images to be distributed.
Additionally it can provide other needed services (e.{nbsp}B. DHCP server).
The opsi depot server is connected to the opsi config server via the opsi message bus and is controlled by it.
opsi depot servers are often used in remote offices to guarantee a performant access to files and services in the LAN.
