////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      15.12.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



= opsi Server

This chapter focuses on the opsi server, the central component of the client management system. For different methods to install an opsi server, refer to the chapter xref:server:installation/installation.adoc[Installation]. Following installation, the chapter xref:server:components/components.adoc[Tools & Settings] covers operational aspects, including tools and configuration.

[[opsi-manual-server-overview]]
== Server Variants

Basically, there are two different server types that can be installed on the same or on different machines (see section xref:server:components/opsiconfd.adoc#server-components-opsiconfd-server-id-role[Server Role]).

* *opsi Config Server*:
The opsi config server is the central control unit in every opsi environment. There is only one config server in each environment. It provides configuration and status data through an API. All server, client, and management components are interconnected through this central API. Typically, an opsi config server also assumes the role of an opsi depot server.

* *opsi Depot Server*:
The opsi depot server manages the distribution of files for software, operating systems, and boot images. Additionally, it may offer other necessary services (like a DHCP server). This server is connected to the opsi config server via the opsi message bus and is controlled by it. opsi depot servers are often deployed in remote offices to ensure efficient, high-performance access to files and services within the LAN.
