////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

////
;***************************************************************************
; Subversion:
; $Revision:  $ $Author: oertel $
; $Date: $
;***************************************************************************
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.0.7
:doctype:   book

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]

[[opsi-407-releasenotes]]
= opsi Version 4.0.7 Release Notes

// Include common opsi copyright
include::../common/opsi_manual_copyright.asciidoc[]

[[opsi-407-releasenotes-supportmatrix]]
== opsi Support Matrix

Im folgenden finden Sie eine Übersicht auf welchen Plattformen opsi
als Server läuft.

include::../common/opsi_manual_supportmatrix.asciidoc[]

////
Notizen:
#######################
Highlights:
* opsi auf xenial
* opsiclientd für xenial
* 15 Freistarts bei opsi-linux-client-agent
* Sortierreihenfolge
* Neuer KioskClient
* neuer opsi-winst
* opsi-clonezilla jetzt mit uefi support
* opsi-clonezilla ocs-live command geht wieder
-------------------------
Essential:

* opsi auf:
xenial
sles12sp1

* server pakete:
bootimage
opsiconfd
opsi-configed

* netboot:
opsi-clonezilla
** netboot pre published
nt6-netboot
linux-netboot
oli-netboot

localboot:
winst4.11.6
jedit
opsi-winst-test
opsi-client-agent
* Sortierreihenfolge
* Neuer KioskClient
opsi-wim-capture
opsi-configed

opsi-linux:
ubuntu16.04
opsi-linux-client-agent
l-opsi-server

##################################
Nice to have:

opsi auf:
sles11sp4
opensusel42.1

netboot:

opsi-linux:
ucs40
ucs41

////


Sollten Sie den opsi-server auf einer Betriebssystemversion einsetzen, +
welche im vorigen Abschnitt nicht als Unterstützt aufgeführt ist,
so empfehlen wir Ihnen ein Betriebssystem-Update bevor Sie opsi v4.0.7 einspielen.

[[opsi-407-releasenotes-overview]]
== Übersicht der Neuerungen

Schwerpunkte dieser Freigabe sind:

* Unterstützung Ubuntu 16.04 Xenial
* Neues opsi Bootimage
* Neue opsi-linux Netboot Produkte

Das opsi Service Release 4.0.7 weist eine Fülle von Neuerungen und Detailverbesserungen auf. Hier eine Übersicht:



* Neues opsi Bootimage
** Basiert auf Ubuntu 16.04 Xenial
** Kernel 


* opsi-configed:


* opsi-client-agent:
** Komplett neuer Build basierend auf python 2.7 und NT6 und OpenSSL 1.0.2h
** NT5: Der Support für NT5 wurde eingefrohren auf opsiclientd 4.0.83 (Mit OpenSSL 1.0.2f)
** Proxysupport für alle HTTP-Verbindung vom opsiclientd
** Gruppensteuerung für Produkte für die Events (Include und Exclude von Produkten pro Event)
** Unterstützung des neuen kioskmodes
** Fix für Synchronisation der Systemzeit mit der Uhrzeit vom Opsi-Webservice
** Unterstützung für Windows 10 im WAN-Modus für die mshotfix-Abopakete

* python-opsi:

** Zahlreiche Verbesserungen und Features in der Python-Library von opsi +
Siehe auch gesondertes <<opsi-407-releasenotes-python-opsi>>



* opsi-winst / opsi-script (4.11.6.1)





[[opsi-407-releasenotes-packages]]
== Paketliste

.Server-Pakete:
* opsi-depotserver
* opsi-linux-support
* opsi-utils
* opsiconfd
* python-opsi
* opsi-linux-bootimage
* opsi-configed

.opsi-Pakete (Localboot):
* opsi-client-agent
* opsi-configed
* config-win10

.opsi-Pakete (netboot):
* win* 
* opsi-clonezilla

.opsi-Pakete (opsi-linux):
* centos70_
* redhat70_
* debian7-
* debian8-
* Ubuntu14-04
* Ubuntu16-04
* opensuse13-2
* sles12

.opsi-Pakete (opsi-local-image):
* opsi-local-image-win* 
* opsi-local-image-capture
* opsi-local-image-capture-prepare


[[opsi-407-releasenotes-missing]]
== Was fehlt noch (und ist in Arbeit)

* opsi-client-agent:
** Die Möglichkeit im Rahmen 'User Profile Management' den opsi-winst komplett im Kontext des eingeloggten Users laufen zu lassen.
** Die Möglichkeit bei der Event-Ausführung dieses auf bestimmte Produkte +
einzuschränken oder aber Produkte auszuschließen. Dazu können Produktgruppen +
angegeben werden.

* opsi-linux-client-agent:
** Noch kein echter opsiclientd für folgende Distributionen:

* opsi-linux 4.0.7 Netboot Produkte: UEFI support

* opsi-clonezilla: UEFI Support


[[opsi-407-releasenotes-knownbugs]]
== Known Bugs / Known Problems


.KNOWN BUGS:

* ######

.KNOWN PROBLEMS:



* ######

[[opsi-407-releasenotes-eol]]
== Abkündigung

[[opsi-407-releasenotes-eol_server]]
=== Abkündigung: Distributionen für opsi-server

In diesem Kapitel werden die Abkündigungen aufgelistet.
Diese Distributionsversionen werden aus verschiedenen Gründen nicht weiter +
von opsi unterstützt.

* ######

Siehe auch gesondertes Kapitel: <<opsi-407-releasenotes-supportmatrix>>.

[[opsi-407-releasenotes-eol_winclient]]
=== Abkündigung Clients: Windows Versionen

Ab opsi v4.0.7 werden wir die Netbootpakete für

* ######


nicht weiter pflegen. Ebenso planen wir für diese Windowsversionen die +
Unterstützung in den Update Abo’s einzustellen. +
Falls Sie hierzu Fragen oder Probleme haben, melden Sie sich bitte bei uns.

Siehe auch gesondertes Kapitel: <<opsi-407-releasenotes-netboot-windows>>.

[[opsi-407-releasenotes-eol_linclient]]
=== Abkündigung Clients: Linux Versionen

Ab opsi v4.0.7 werden wir die Netbootpakete für

* ######

nicht weiter pflegen. +
Falls Sie hierzu Fragen oder Probleme haben, melden Sie sich bitte bei uns.



[[opsi-407-releasenotes-installation]]
== Hinweise zur Installation

Wir empfehlen vor der Installation des Updates eine Sicherung Ihres Backends +
mittels {opsi-backup} durchzuführen:
[source,prompt]
----
opsi-backup create
----

Die Produkte welche im Rahmen dieses Releases veröffentlicht werden, +
sind in etlichen Teilen voneinander abhängig. +
Sie sollten daher nicht versuchen, nur Teile zu installieren.

Wir empfehlen zuerst den Server und danach die opsi-Produkte zu aktualisieren.

Wir empfehlen nach dem Update die Ausführung von ``opsi-setup --set-rights``, +
um sicher zu stellen, dass die Zugriffsberechtigungen korrekt gesetzt sind. +
Die Ausführung des Befehls kann mehrere Minuten in Anspruch nehmen.


[[opsi-407-releasenotes-installation-opsipackages]]
=== Hinweise zum Aktualisieren von opsi-Paketen

////
Bitte nachstehenden Block bei release nicht löschen sondern auskommentieren
////


Zur Installation der testing Serverpakete müssen Sie das opsi Repository ändern von `opsi40` auf `opsi40-testing`. +
Zum Beispiel bei Ubuntu 14.04: +
`deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/opsi40/xUbuntu_14.04 ./` +
ersetzen durch: +
`deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/opsi40-testing/xUbuntu_14.04 ./`


Danach müssen Sie Ihre Pakete updaten. +


Zum Beispiel bei Ubuntu / Debian:
[source,prompt]
----
aptitude update
aptitude full-upgrade
----

Zur Installation der opsi Produkte:

fügen Sie in die Datei +
`/etc/opsi/opsi-product-updater.conf` +
folgende Sektion ein:


[source,prompt]
----
[repository_opsi_406_testing]
baseUrl = http://download.uib.de
dirs = opsi4.0/testing/opsi-v406/products/localboot, opsi4.0/testing/opsi-v406/products/netboot
active = true
username =
password =
autoInstall = false
autoUpdate = true
autoSetup = false
onlyDownload = false
----

Hängen Sie je nach Bedarf an die `dirs` Zeile noch an:

* `, opsi4.0/testing/opsi-v406/opsi-linux`

* `, opsi4.0/testing/opsi-v406/opsi-local-image`

////
[repository_opsi_406_experimental]
baseUrl = http://download.uib.de
dirs = opsi4.0/experimental/opsi-v406/products/localboot, opsi4.0/experimental/opsi-v406/products/netboot, opsi4.0/experimental/opsi-v406/products/opsi-linux
active = true
username =
password =
autoInstall = false
autoUpdate = true
autoSetup = false
onlyDownload = false
----
////

Setzen Sie in der Sektion `[repository_uib]` folgende Zeile:
[source,prompt]
----
active = false
----
Danach rufen sie den opsi-product-updater auf.


Um alle Pakete zu installieren:
[source,prompt]
----
opsi-product-updater -i -vv
----

Um nur Updates zu installieren:
[source,prompt]
----
opsi-product-updater -vv
----

////
Bitte vorstehenden Block bei release nicht löschen sondern auskommentieren
////

////
Die Installation erfordert keine besonderen Arbeiten. Sie erfolgt im Rahmen der normalen Updates ihres Servers und der opsi-Produkte.

Sie sollten dabei zuerst den Server updaten. Benutzen Sie dazu die Befehle entsprechend Ihrer Linux-Distribution. +

Wir empfehlen in der Datei `/etc/opsi/opsi-product-updater.conf`
in der Sektion `[repository_uib]` den Eintrag `excludes` wie folgt zu modifizieren, damit Sie auch Produkte bekommen welche mit `win*` anfangen::
[source,prompt]
----
excludes =
----

Wenn Sie die  opsi-linux Produkte benötigen so hängen Sie an den `dirs` Eintrag: +
den Pfad `opsi4.0/products/opsi-linux` an.

Wenn Sie die  opsi-local-image Produkte benötigen so hängen Sie an den  `dirs` Eintrag den Pfad `opsi4.0/products/opsi-local-image` an.

Danach die opsi-Produkte. Dies erledigt der opsi-product-updater:

[source,prompt]
----
opsi-product-updater -i -vv
----

Um nur Updates zu installieren:
[source,prompt]
----
opsi-product-updater -vv
----

Sollten Sie eine Multidepot Umgebung haben, so machen Sie zunächst das Upgrade auf Ihrem config-server, bevor Sie die Depots upgraden.

Falls Sie Produkt-IDs mit einer Länge von mehr als 32 Zeichen verwenden wollen und das MySQL-Backend einsetzen, so führen Sie bitte ein Update der Tabellen-Definition auf Ihrem Config-Server mittels opsi-setup durch:


[source,prompt]
----
opsi-setup --update-mysql
----
////



[[opsi-407-releasenotes-linux]]
== Linuxsupport

* 15 Freistarts

----
  * getLinuxVersionMap list.add ('SubRelease=' (patchlevel from SLES)
  * new bool function waitForPackageLock(<seconds timeout string>,<bool should we kill>) (Linux only)
----

////
include::../common/opsi_manual_linux.asciidoc[]
////


[[opsi-script]]
== opsi-script / opsi-winst 4.11.6

* Security Upgrade zu Windows SSL Libraries 1.0.2h (libeay32.dll, ssleay32.dll) +
Update des SSL Protokolls auf TLS autonegotiation

* Neue Dokumentationen:

** opsi-winst-refrence-card mit Themen bezogener Funktionsübersicht (by topic)

* Neue Stringlist Funktionen:

`setStringInListAtIndex(`<newstring>,<list>,<indexstr>`) : stringlist`   //since 4.11.6 [W/L]


* Neu: Funktionen zum Handling von JSON

[[opsi-winst-rc-json]]
=== opsiservicecall and json Related functions [W/L]

`jsonIsValid(`<jsonstr>`) : boolean`  //since 4.11.6: [W/L]

`jsonIsArray(`<jsonstr>`) : boolean`  //since 4.11.6: [W/L]

`jsonIsObject(`<jsonstr>`) : boolean`  //since 4.11.6: [W/L]

`jsonAsObjectHasKey(`<jsonstr>,<keystr>`) : boolean`  //since 4.11.6: [W/L]

`jsonAsArrayCountElements(`<jsonstr>`) : intstr`  //since 4.11.6: [W/L]

`jsonAsObjectCountElements(`<jsonstr>`) : intstr`  //since 4.11.6: [W/L]

`jsonAsArrayGetElementByIndex(`<jsonstr>, <indexstr>`) : jsonstring`  //since 4.11.6: [W/L]

`jsonAsObjectGetValueByKey(`<jsonstr>, <keystr>`) : valuestring`  //since 4.11.6: [W/L]

`jsonAsObjectSetValueByKey(`<jsonstr>, <keystr>,<valuestring>`) : jsonstring`  //since 4.11.6: [W/L]

`jsonAsObjectSetStringtypeValueByKey(`<jsonstr>, <keystr>,<valuestring>`) : jsonstring`  //since 4.11.6: [W/L]

`jsonAsArrayPutObjectByIndex(`<jsonstr>, <indexstr>, <objectstr>`) : jsonstring`  //since 4.11.6: [W/L]

`jsonAsArrayToStringList(`<jsonstr>`) : stringlist`  //since 4.11.6: [W/L]

`jsonStringListToJsonArray(`<strlist>`) : jsonstr`  //since 4.11.6: [W/L]

`jsonAsObjectGetKeyList(`<jsonstr>`) : stringlist`  //since 4.11.6: [W/L]

[[opsi-winst-rc-process]]
=== Process and Script Related functions [W/L]

`processIsRunning(`<process name>`) : boolean`  //since 4.11.6.1  [W/L]

`shellCall (`<command string>`) : stringlist (output)` //since 4.11.4.2 [W/L]

`shellCall (`<command string>`) : noresult` //since 4.11.6.1 [W/L]

`shellCall (`<command string>`) : string (exitcode)` //since 4.11.6.1 [W/L]

`startProcess(`<string>`) : string (exitcode)` //since 4.11.6.1 [W/L]

`waitForPackageLock(`<seconds timeout string>,<bool should we kill>`) : bool` //since 4.11.6.1 [L]

[[opsi-winst-rc-cryptfunc]]
=== Crypt / Hash related functions [W/L]

`encryptStringBlow(`<keystring>,<datastring>`) : string` [W/L]

`decryptStringBlow(`<keystring>,<datastring>`) : string` [W/L]

`md5sumFromFile(`<path to file>`) : string` [W/L]

[[opsi-winst-rc-timefunc]]
=== time / date related functions

`timeStampAsFloatStr : string` (Floating Number - format: 'days.decimal days') //since 4.11.6 [W/L]

[[opsi-winst-rc-misc]]
=== Misc news

* `getMSVersionMap` +
Has now a new key entry: `ReleaseID` which gives you the sub release of 'Windows 10' like e.g. '1511'.
The Value comes from the Registry: "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion" "ReleaseID"

* `getLinuxVersionMap` +
Has now a new key entry: `SubRelease` which gives you the sub release (patchlevel) of 'SLES 11' like e.g. '4'.

* `ShellBatch /showoutput` +
Shows the output of the called command in a seperate window. +
Now also available at Linux. +
Now moves the main Window to top/right and the ouptup window to left/down.

* `strLoadTextfile`  and `strLoadTextFileWithEncoding` +
Reads the firs line of the given file. Now without newline chars.

* repaired product ordering for `product_sort_algorithm 1` 

[[opsi-407-releasenotes-clientagent-configuration]]
== Konfiguration

Hier folgen die neuen Konfigurationsoptionen, die der 4.0.7 opsi-client-agent mitbringt.

[[opsi-407-releasenotes-clientagent-configuration-proxysupport]]
=== Proxysupport-Konfiguration

In der global Section gibt es jetzt die Möglichkeit, den opsi-client-agent einen Proxyserver mit zu geben.
Wenn ein Proxy konfiguriert wurde, dann werden alle HTTP-Verbindungen vom opsiclientd über diesen Proxy realisiert.

[source,ini]
----
# Use a proxy for connecting configservice
# proxy_mode:
#   'system' will try to check the system setting,
#   'static' to use proxyurl from configfile/hostparameter
# proxy_url usage: http://<user>:<password>@<proxy-url>:<proxy-port>
# Example: http://proxyuser:proxypass123@proxy.domain.local:8080
proxy_mode = static
proxy_url =
----

Die Proxyeinstellungen erlauben auch einen Proxy zu benutzen, der eine Authentifizierung erfordert. Dazu muss die Proxy_url wie oben im Beispiel angegeben werden.

WARNING: Der proxy_mode ist vorgesehen, dass bei der Einstellung system, der proxy aus dem laufenden Client-System ausgelesen werden. Dies ist im Moment nicht implementiert, deshalb funktioniert momentan nur die Einstellung 'static'.

[[opsi-407-releasenotes-clientagent-configuration-eventcontrol_over_productgroups]]
=== Steuerung der Produkte die ausgeführt werden pro Event

Mit diesem neuen Feature ist es über die Konfiguration möglich, die Liste der ab zu bearbeitenden Produkte über Produktgruppen zu steuern.

Dazu gibt es Grundsätzlich zwei Vorgehensweise:

Ausschliessen:

Mit der Option `exclude_product_group_ids` kann man nun eine Kommaseparierte Liste von Produktgruppen-Ids mitgeben, dessen Mitglieder vom aktuellen Event ausgeschlossen werden. Auch wenn Sie eigentich auf setup stehen. Diese Produkte werden zwar ignoriert, aber bleiben auf setup stehen.

Eine Liste angeben, die zur Bearbeitung freigegeben werden:

Mit der Option `include_product_group_ids`kann man nun eine Kommaseparierte Liste von Produktgruppen-Ids festlegen, dessen Mitglieder überhaupt bearbeitet werden dürfen, vorausgesetzt Sie eine Aktion ist auch gesetzt.

Diese Einstellung kann man entweder Global im Default-Event angeben, damit das für jedes Event gilt. Man kann diese Optionen aber auch Zum Beispiel nur im Event_on_demand einsetzen, somit kann man Pakete die auf setup stehen von Push-Installationen ausschliessen, obwohl Sie auf setup stehen. Bei einem normalen Restart mit aktiviertem gui_startup (default) würden diese Pakete trotzdem bearbeitet.

WARNING: Für Clients, die das Modul WAN/VPN aktiviert haben, muss man diese Optionen neben dem Sync-Event auch in der CacheService-Sektion mit aufgenommen werden, da der CacheService zwar vom Sync-Event getriggert wird, aber selbst keinen Zugriff auf das sync-Event hat.



[[opsi-407-releasenotes-python-opsi]]
== python-opsi 4.0.7.

###################

[[opsi-407-releasenotes-netboot-windows]]
== opsi Support Matrix Windows Clients

Im folgenden finden Sie eine Übersicht auf welchen Windows Plattformen opsi
als Client läuft.

include::../common/opsi_manual_supportmatrix-winclient.asciidoc[]




[[opsi-407-releasenotes-misc]]
== Sonstiges

[[opsi-407-releasenotes-misc-changelogs]]
=== Changelogs:


[[opsi-407-releasenotes-misc-changelogs-opsi-configed]]
==== Changelog opsi-configed

#############

[[opsi-407-releasenotes-misc-changelogs-opsi-client-agent]]
==== Changelog opsi-client-agent

###############

[[opsi-407-releasenotes-misc-changelogs-config-win10]]
###############

[[opsi-407-releasenotes-misc-changelogs-opsi-script]]
==== Changelog opsi-script / opsi-winst
###############


[[opsi-407-releasenotes-misc-changelogs-windows-netboot]]
==== Changelog windows netboot products
###############

[[opsi-407-releasenotes-misc-changelogs-linux-netboot]]
==== Changelog linux netboot products

###############

.centos70

###############


.debian7

###############


.debian8

###############


.opensuse13-2
###############

.sles12
###############

.redhat70
###############

.Ubuntu14-04
###############


[[opsi-407-releasenotes-misc-changelogs-opsi-local-image]]
==== Changelog opsi-local-image

###############


[[opsi-407-releasenotes-misc-changelogs-misc-netboot]]
==== Changelog misc netboot products

###############

[[opsi-407-releasenotes-misc-changelogs-python-opsi]]
==== Changelog python-opsi

###############

[[opsi-407-releasenotes-misc-changelogs-opsiconfd]]
==== Changelog opsiconfd

opsiconfd (4.0.6.14-1) stable; urgency=medium

  * Small improvements during statistics collections and display.
  * opsiconfd will log statistics at shutdown with level notice.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Fri, 01 Apr 2016 11:00:03 +0200

###############

[[opsi-407-releasenotes-misc-changelogs-opsi-utils]]
==== Changelog opsi-utils

opsi-utils (4.0.7.1-1) testing; urgency=medium

  * opsi-convert: If you are logging into a file the loglevel will be DEBUG.
  * opsi-product-updater: The notification mail will now have the DATE field
    in the header. The field is formatted as specified in RFC 5322.
  * opsi-package-manager: Setting -v now sets an implicit -q to show the
    output. If using '-p ask' no -q will be set to be able to still
    select the wanted properties.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 23 May 2016 14:31:10 +0200

opsi-utils (4.0.6.14-1) testing; urgency=medium

  * opsi-makeproductfile: Avoid reference to undefined 'incremental'.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Fri, 29 Apr 2016 12:21:49 +0200

opsi-utils (4.0.6.13-1) testing; urgency=medium

  * opsi-makeproductfile: now using argparse internally
  * opsi-admin got received a welcome message.
  * Fixed typo in German translation.
  * opsi-convert: show custom application name if used against webinterface
    of another server to be able to easily spot the corresponding requests.
  * opsi-product-updater: Attempts to close open connections now more reliable.
  * opsi-makeproductfile: use argparse instead of getopt.
  * opsi-product-updater: running with -p <productId> now implies -i.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Thu, 28 Apr 2016 12:29:16 +0200

opsi-utils (4.0.6.12-1) experimental; urgency=medium

  * opsi-package-manager: return error when trying to remove non installed
    package
  * opsi-package-manager: logs into package.log with LogLevel 4
  * Added logrotate config for /var/log/opsi/opsi-package-manager.log

 -- Mathias Radtke <m.radtke@uib.de>  Tue, 12 Apr 2016 15:56:31 +0200

opsi-utils (4.0.6.11-1) experimental; urgency=medium

  * opsi-backup: Warn during restore if no backends are given.
  * Various small changes for easier maintenance.
  * opsi-package-manager: only query for depot information if required.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 04 Apr 2016 17:00:33 +0200

###############

####################

[[opsi-407-releasenotes-misc-changelogs-opsi-linux-bootimage]]
==== Changelog opsi-linux-bootimage

###############

[[opsi-407-releasenotes-misc-changelogs-opsi-depotserver]]
==== Changelog opsi-depotserver

###############

####################

[[opsi-407-releasenotes-misc-changelogs-opsi-atftp]]
==== Changelog opsi-atftp


####################

[[opsi-407-releasenotes-misc-changelogs-opsipxeconfd]]
==== Changelog opsipxeconfd

opsipxeconfd (4.0.7.1-1) stable; urgency=medium

  * Refactored internal code for locking.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Thu, 19 May 2016 12:39:40 +0200

###############

[[opsi-407-releasenotes-misc-changelogs-opsi4ucs]]
==== Changelog opsi4ucs


####################

[[opsi-407-releasenotes-misc-changelogs-opsi-swaudit]]
==== Changelog opsi-swaudit
####################

 [[opsi-407-releasenotes-misc-changelogs-opsi-template]]
==== Changelog opsi-template
####################

