////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////

////
;***************************************************************************
; Subversion:
; $Revision$ 
; $Author$
; $Date$
;***************************************************************************
////


:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.0.6
:doctype:		book

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]


[[opsi-winst-rc]]
= opsi-winst / opsi-script reference card (4.11.6)

// Include common opsi copyright
include::../common/opsi_manual_copyright.asciidoc[]

[[opsi-winst-rc-const]]
== Global text constants

[[opsi-winst-rc-const-system1]]
=== System directories

[[opsi-winst-rc-const-system2]]
==== System directories [W]:

`%ProgramFilesDir%`:	'c:\program files'

`%ProgramFiles32Dir%`:	'c:\Program Files (x86)'	            //since 4.10.8

`%ProgramFiles64Dir%`:	'c:\program files'	                  //since 4.10.8

`%ProgramFilesSysnativeDir%` :	'c:\program files'	          //since 4.10.8

`%Systemroot%` :  	'c:\windows'

`%System%` :  	 	'c:\windows\system32'

`%Systemdrive%` :       	'c:'

`%ProfileDir%` :	        'c:\Documents and Settings'

[[opsi-winst-rc-const-common]]
=== Common (AllUsers) directories [W]:

`%AllUsersProfileDir%` or `%CommonProfileDir%` : 'c:\Documents and Settings\All Users'

`%CommonStartMenuPath%` or `%CommonStartmenuDir%` : 'c:\Documents and Settings\All Users\Startmenu'

`%CommonAppdataDir%` : 'c:\Documents and Settings\All Users\Application Data'

`%CommonDesktopDir%`

`%CommonStartupDir%`

`%CommonProgramsDir%`

[[opsi-winst-rc-const-default]]
=== Default User directories [W]:

`%DefaultUserProfileDir%`                          //since 4.11.1.1

[[opsi-winst-rc-const-current]]
=== Current user directories  [W]:
User is the logged in user or given by /usercontext.

`%AppdataDir%` or `%CurrentAppdataDir%` : 'c:\Documents and Settings\%USERNAME%\Application Data' //since 4.10.8.13

`%CurrentStartmenuDir%` //since 4.10.8.13 

`%CurrentDesktopDir%` //since 4.10.8.13

`%CurrentStartupDir%`                               //since 4.10.8.13

`%CurrentProgramsDir%`                              //since 4.10.8.13

`%CurrentSendToDir%`	                              //since 4.10.8.13

`%CurrentProfileDir%`                               //since 4.11.2.1

[[opsi-winst-rc-const-allntuser]]
=== /AllNtUserProfiles directory constants [W]:

`%UserProfileDir%` : 'c:\Documents and Settings\%USERNAME%' +
or +
`%CurrentProfileDir%`                               // since 4.11.2.1

[[opsi-winst-rc-const-winstpath]]
=== opsi-winst Path and Directories [W/L]:

`%ScriptPath% or %ScriptDir%`

`%ScriptDrive%`

`%WinstDir%`

`%WinstVersion%`                                     //4.10.8.3

`%Logfile%`

`%opsiScriptHelperPath%`  `%ProgramFiles32Dir%\opsi.org\opsiScriptHelper\lib` // since 4.11.3.2

`%opsiTmpDir%` : `c:\opsi.org\tmp` // since 4.11.4.3

`%opsiLogDir%` : `c:\opsi.org\log` // since 4.11.4.3

[[opsi-winst-rc-const-network]]
=== Network informations [W/L]:

`%Host%` :	value of environment variable HOST.

`%PCName%`:	value of environment variable PCNAME, or if absent of COMPUTERNAME.

`%Username%` :	Name of actual user.

`%IPAddress%` : may be the IP-Address of the machine. Use funktion `getMyIpByTarget()` instead.

[[opsi-winst-rc-const-service]]
=== Service Data [W/L]

`%HostID%` :	FQDN of the client

`%opsiserviceURL%`

`%opsiServer%`

`%opsiDepotId%`     //since 4.11.4

`%opsiserviceUser%`

`%opsiservicePassword%`

`%installingProdName%`: 	productid	 //since 4.10.8

`%installingProdVersion%`:	product version	 //since 4.10.8

`%installingProduct%` :	productid (deprecated)

[[opsi-winst-rc-primary-sections]]
== In Primary Sections

[[opsi-winst-rc-primary-sections-kind]]
=== Kinds of Primary Sections [W/L]:

`[Initial]`

`[Actions]`

`[sub`<identifier>`]`

`sub` <file name>

`[ProfileActions]` [W]

[[opsi-winst-rc-winst-control]]
=== Winst control [W/L]:

`encoding=`<encoding> // (default is system encoding) since 4.11.4.2

`LogLevel`  (deprecated)

`SetLogLevel` = <number> or `SetLogLevel` = <string> // (default=6)
[source,winst]
----
SetLogLevel = 7
SetLogLevel = "7"
----

`ExitOnError` = <boolean value> // (default=false)

`ScriptErrorMessages =` <boolean value> // (default=true)

`FatalOnSyntaxError =` <boolean value>  // (default=true) since 4.11.3.2

`FatalOnRuntimeError =` <boolean value>  // (default=false) since 4.11.3.2

`AutoActivityDisplay =` <boolean value>  // (default=false); if true shows a marquee (endless) progressbar while winbatch/dosbatch sections are running. //since 4.11.4.7

`Message` <string> or `Message` = <const string>

`ShowMessageFile` <string>

`ShowBitMap`  [<file name>] [<sub title>]

`comment` <string> or `comment` = <const string>

`LogError` <string> or `LogError` = <const string>

`LogWarning` <string> or `LogWarning` = <const string>

`includelog` <file name> <tail size>   //since 4.11.2.1 [W/L]

`includelog` <file name> <tail size> [<encoding>]  //since 4.11.4.1 [W/L]

[source,winst]
----
includelog "%Scriptpath%\test-files\10lines.txt" "5"
----

`SetConfidential` <secret string> //since 4.11.3.5 [W/L]

`Pause` <string> or `Pause` = <const string>

`Stop` <string> or `stop` = <const string>

`include_insert` <file name> // since 4.11.3

`include_append` <file name> // since 4.11.3

`NormalizeWinst` // (set normal window state) since 4.11.3

`IconizeWinst` // (set minimized window state)

`MaximizeWinst` // (set maximized window state) // since 4.11.5.1

`RestoreWinst` // (restore last window state)

`SetSkinDirectory` <path to skin.ini> // since 4.11.3.5

[[opsi-winst-rc-var]]
=== Variables [W/L]:

[[opsi-winst-rc-var-strings]]
==== Strings

`DefVar` <variable name>

`Set` <variable name> `=` <value>

[[opsi-winst-rc-var-stringlists]]
==== Stringlists

`DefstringList`  <variable name>

[[opsi-winst-rc-func]]
=== Functions

[[opsi-winst-rc-func-string]]
==== String functions

[[opsi-winst-rc-important]]
===== Important

`GetOS`  // 'Linux' or 'Windows_NT'   [W/L]

`getLinuxDistroType`  // 'debian' or 'redhat' or 'suse'  (see `getLinuxVersionMap`) [L]

`GetMsVersionInfo` //Windows Version Information [W]

`GetSystemType`    //OS Architecture ("64 Bit System" or "x86 System") [W/L]

`GetRegistrystringvalue (`"[key] var"`)` [W]

`GetRegistryStringValue32 (`"[key] var"`)`   //since 4.10.8 [W]

`GetRegistryStringValue64 (`"[key] var"`)`   //since 4.10.8 [W]

`GetRegistryStringValueSysNative (`"[key] var"`)`    //since 4.10.8 [W]

`GetvalueFromInifile (` file, section, key, default value `)` [W/L]
[source,winst]
----
GetValueFromInifile("myfile","mysec","mykey","")
----

`GetProductProperty (`<PropertyName>, <DefaultValue> `)` [W/L]

`GetConfidentialProductProperty (` <PropertyName>, <DefaultValue>`)` //since 4.11.5.2 [W/L]

`trim(`<string>`)` [W/L]

`lower(`<string>`)` [W/L]

`unquote(`<string>,<quote-string>`)`  //since 4.11.2.1  [W/L]

`unquote2(`<string>,<quote-string>`)`  //since 4.11.5.2  [W/L]

`stringReplace(`<string>, <oldPattern>, <newPattern>`)`  //since 4.11.3 [W/L]

`strLength(`<string>`)`  //since 4.11.3 [W/L]

`strPos(`<string>, <sub string>`)`  //since 4.11.3 [W/L]

`strPart(`<string>, <start pos>, <number of chars>`)`  //since 4.11.3 [W/L]

`getValue(`<key string>, <hash string list> `)` [W/L]

`getValueBySeparator(`<key string>,<separator string>,<hash string list> `)` //since 4.11.2.1 [W/L]

`getValueFromFile(`<key string>, <file name>`)` //since 4.11.4.4 [W/L]

`getValueFromFileBySeparator(`<key string>,<separator string>,<file name>`)` //since 4.11.4.4 [W/L]

`getLastExitCode` [W/L]

[[opsi-winst-rc-spec-license-management]]
===== Special: License Management

`DemandLicenseKey(` poolId [, productId [,windowsSoftwareId]] `)`
[source,winst]
----
set $mykey$ = DemandLicenseKey ("", "office2007")
----

`FreeLicense (`poolId [, productId [,windowsSoftwareId]]`)`
[source,winst]
----
set $result$ = FreeLicense("", "office2007")
----

[[opsi-winst-rc-spec-usercontext]]
===== Special: Usercontext / loginscripts [W]:

`GetUserSID(`<Windows Username>`)`

`GetLoggedInUser`   //since 4.11.1.2

`GetUsercontext`   //since 4.11.1.2

`GetScriptMode`  possible values 'Machine','Login' //since 4.11.2.1

`saveVersionToProfile` - save productversion-packageversion to local profile //since 4.11.2.1

`readVersionFromProfile` : string - read productversion-packageversion from local profile //since 4.11.2.1

`scriptWasExecutedBefore` : boolean - is true if saved and running productversion-packageversion are identical //since 4.11.2.1



[[opsi-winst-rc-other]]
===== Other

`GetHostsName (`<hostaddress> `)` [W/L]

`GetHostsAddr (`<hostname> `)` [W/L]

`ExtractFilePath (`<path>`)` [W/L]

`calculate(`<arithmetic string expression>`)` // since 4.11.3.5 : knows: `+-*/()` [W/L]

`DecStrToHexStr (` <decstring>, <hexlength>`)` [W/L]

`HexStrToDecStr (`<hexstring>`)` [W/L]

`base64EncodeStr(`<string>`)`  [W/L]

`base64DecodeStr(`<string>`)`  [W/L]

`convert2Jsonstr(`<string>`)`  //since 4.10.8.3

`RandomStr` [W/L]

`CompareDotSeparatedStrings(`<string1>, <string2>`)` [W/L]

`CompareDotSeparatedNumbers(`<string1>, <string2>`)` [W/L]

`EnvVar (`<environment variable>`)` [W/L]

`ParamStr` [W/L]

`getDiffTimeSec` (Time in seconds since last marktime) //since 4.11.3 [W/L]

`SidToName(`<well known sid>`)` //since 4.11.3: gives localized name of the sid [W]

`GetMyIpByTarget(`<target ip addr>`)` //since 4.11.3.2 [W]

`GetIpByName(`<ip addr / ip name>`)` //since 4.11.3.2 [W/L]

`reencodestr(`<str>, <from>, <to>`)` //since 4.11.4.2 [W/L]

`strLoadTextFile (` <filename> `)` //since 4.11.4.6 [W/L]

`GetShortWinPathName(<longpath string>)` //since 4.11.5.2 [W]

[[opsi-winst-rc-deprecated]]
===== Deprecated

`GetNtVersion`  [W]

`IniVar (`<key>`)` :	(deprecated; use GetProductProperty) [W]

`SubstringBefore (`<string1>, <string2>`)` [W/L]

[[opsi-winst-rc-func-stringlist]]
==== String list functions

===== Important

`splitString (`<string1>, <string2>`)` [W/L]
[source,winst]
----
set $list1$ = splitString ("\\server\share\dir","\")
----

`splitStringOnWhiteSpace (`<string>`)` [W/L]

`loadTextFile (`<file name>`)` [W/L]

`loadUnicodeTextFile (`<file name>`)` [W]

`loadTextFileWithEncoding(` <file name> `,` <encoding>`)` //since 4.11.5 [W/L]

`composeString (`<string list>, <Link>`)` [W/L]

`takeString (`<index>, <list>`)` [W/L]

`setStringInListAtIndex(`<newstring>,<list>,<indexstr>`) : list` //since 4.11.6  [W/L]

`takeFirstStringContaining(`<list>,<search string>`)` [W/L]

`getOutStreamFromSection (`<dos section name>`)` [W/L]
[source,winst]
----
set $list$= getOutStreamFromSection ('DosInAnIcon_try')
----

`shellCall (`<command string>`)` //since 4.11.4.2 [W/L]
[source,winst]
----
set $list$= shellCall('net start')
----

`getReturnListFromSection (`<xml section name>`)` [W/L]

`getListContaining(`<list>,<search string>`)` [W/L]

`getListContainingList(`<list1>,<list2>`)`  //since 4.11.3.7 [W/L]

`count (`<list>`)` [W/L]

`emptylist (`<list>`)`  //since 4.11.3.7 [W/L]

`for %`<identifier>`% in` <list> `do` <one statement | sub section> [W/L]
[source,winst]
----
for %s% in $list1$ do sub_test_string
----

`GetProcessList`   //since 4.11.1.2; gives list of exename;pid;dom/user [W/L]

`getProductPropertyList(`<propname>,<default value>`)`  //since 4.11.3 [W/L]

`getRegistryKeyList32(`<regkey>`)` //since 4.11.3 [W]

`getRegistryKeyList64(`<regkey>`)` //since 4.11.3 [W]

`getRegistryKeyListSysnative(`<regkey>`)` //since 4.11.3 [W]

`getRegistryVarList32(`<regkey>`)`  //since 4.11.3 [W]

`getRegistryVarList64(`<regkey>`)` //since 4.11.3 [W]

`getRegistryVarListSysnative(`<regkey>`)` //since 4.11.3 [W]

`getProfilesDirList` //since 4.11.3.2 [W/L]

===== Infomaps

`GetLocaleInfoMap` [W]

`GetMSVersionMap` [W]

`getLinuxVersionMap`  //since 4.11.4  [L] +
keys are (example):
[source,ini]
----  
Distributor ID=Ubuntu
Description=Ubuntu 12.04.2 LTS
Release=12.04
Codename=precise
kernel name=Linux
node name=detlefvm05
kernel release=3.2.0-40-generic-pae
kernel version=#64-Ubuntu SMP Mon Mar 25 21:44:41 UTC 2013
machine=i686
processor=athlon
hardware platform=i386
operating system=GNU/Linux
----

`getFileInfoMap(` <file name> `)` [W]

`getProductMap`  // since 4.11.2.4  [W/L] +
keys are: id, name, description, advice, productversion, packageversion, priority, installationstate, lastactionrequest, lastactionresult, installedversion, installedpackage, installedmodificationtime,actionrequest

`getRegistryVarMap32(`<regkey>`)`  //since 4.11.3 [W]

`getRegistryVarMap64(`<regkey>`)` //since 4.11.3 [W]

`getRegistryVarMapSysnative(`<regkey>`)` //since 4.11.3 [W]

`getHWBiosInfoMap`  //since 4.11.4  [W/L]

===== Other

`createStringList (`<string0>, <string1> ,... `)` [W/L]
[source,winst]
----
set $list1$ = createStringList ('a','b')
----

`reverse (`<list>`)` [W/L]

`getSectionNames(`<ini-file>`)` [W/L]

`retrieveSection (`<section name>`)` [W/L]

`getSubList (`<start index> : <end index>, <list>`)` [W/L]

`addtolist(`<list>,<string>`)`	 //since 4.10.8 [W/L]

`addListToList(`<dest list>,<src list>`)`	 //since 4.10.8 [W/L]

`reencodestrlist(`<list>, <from>, <to>`)` //since 4.11.4.2 [W/L]

`removeFromListByContaining(`<search string>`,` <target list>`)` //since 4.11.5.1 [W/L]

`removeFromListByContaining(`<search list>`,` <target list>`)` //since 4.11.5.1 [W/L


[[opsi-winst-rc-func-bool]]
==== Boolean operators and functions

<string1> `=` <string2> [W/L]

<bool1> `AND` <bool2> [W/L]

<bool1> `OR` <bool2> [W/L]

`NOT`(<bool3>) [W/L]

`FileExists (`<file name>`)` [W/L]

`FileExists32 (`<file name>`)` [W]

`FileExists64 (`<file name>`)` [W]

`FileExistsSysNative (`<file name>`)` [W]

`LineExistsIn (`<string>, <file name>`)` [W/L]

`LineBeginning_ExistsIn (`<string>, <file name>`)` [W/L]

`LineContaining_ExistsIn(` <string>, <file name> `)` //since 4.11.4.10: true: if a in <file name> contains <string> [W/L]

`XMLAddNamespace(`<XMLfilename>, <XMLelementname>, <XMLnamespace>`)` [W]

`XMLRemoveNamespace(`<XMLfilename>, <XMLelementname>, <XMLnamespace>`)` [W]

`HasMinimumSpace (`<drive letter>, <capacity>`)` [W]

Example:
[source,winst]
----
if not (HasMinimumSpace ("%SYSTEMDRIVE%", "500 MB"))
   LogError "Neede Space of 500 MB not available on %SYSTEMDRIVE%"
   isFatalError
endif
----

`opsiLicenseManagementEnabled` [W/L]

`runningAsAdmin`    //since 4.11.1.1 [W/L]

`isLoginScript`    //since 4.11.2.1 [W]

`contains(`<str>, <substr>`)`  //since 4.11.3: true if <substr> in <str> [W/L]

`isNumber(`<str>`)` //since 4.11.3: true if <str> represents an integer [W/L]

`runningOnUefi` //since 4.11.4.3: true: if the running OS was booted in UEFI mode [W]

`isDriveReady(`<drive letter>`)` //since 4.11.4.4: true: if the drive can be accessed [W]

`saveTextFile(`<list>, < filename>`)` //since 4.11.4.4: true: if list is succesfully written to file [W/L]

`CompareDotSeparatedNumbers(`<str1>,<relation str>,<str2>`)`  //since 4.11.5.2: [W/L]

`CompareDotSeparatedStrings(`<str1>,<relation str>,<str2>`)`  //since 4.11.5.2: [W/L]




[[opsi-winst-rc-func-misc]]
==== Misc functions

`Killtask` <process name> [W/L]

`requiredWinstVersion` <relation operator> <version> [W/L]
[source,winst]
----
requiredWinstVersion >= "4.10"
----

`UpdateEnvironment` //since 4.11.5 [W]: +
Subsequent calls of `winbatch` with the parameter `/RunElevated` will see the changed Environment (NT6 only).


[[opsi-winst-rc-flow-control]]
==== Flow control

'if - else - endif' [W/L]

Syntax:

`if` <condition> +
  ;statement(s) +
[`else` +
  ;statement(s)] +
`endif`

Example:
[source,winst]
----
Set $NTVer$ = GetMsVersionInfo
if ( $NTVer$ >= "6" )
     sub_install_win7
else
  if ( $NTVer$ = "5.1" )
    sub_install_winXP
  else
    stop "not a supported OS-Version"
  endif
endif
----

'for - to - do' Statement //since 4.11.5 [W/L]

`for` %<temporary string variable>% `=` <start string> `to` <end string> `do` <one statement> 


Example: 
[source,winst]
----
for %s% = "1" to "5" do sub_iteration_test
----

'Switch / Case' Statement //since 4.11.5 [W/L]

Syntax:
----
Switch <string expression> 
  Case <string const>
    <statement(s)> 
  EndCase
  [DefaultCase
    <statement(s)> 
   EndCase]
EndSwitch
----


Example:

[source,winst]
----
set $ConstTest$ = "5"
Switch $ConstTest$
	Case "1"
		set $CompValue$ = "1"
	EndCase
	Case "2"
		set $CompValue$ = "2"
	EndCase
	DefaultCase
		set $CompValue$ = "notexisting"
	EndCase
EndSwitch
----


`isFatalError` [W/L]

`isFatalError` <string>  //since 4.11.3.2 [W/L]

`isSuccess` //since 4.11.3.7 [W/L]

`isSuspended` //since 4.11.4.1 [W/L]

`noUpdateScript` //since 4.11.3.7 [W/L]

`ExitWindows /Reboot` [W/L]

`ExitWindows /ImmediateReboot` [W/L]

`ExitWindows /ImmediateLogout` [W]

`ExitWindows /ShutdownWanted` [W]

`ExitWindows /RebootWanted` (deprecated, acts like /Reboot) [W]

`sleepSeconds` <Integer> or <string> [W/L]

`ChangeDirectory` <directory>   //since 4.11.2.6 [W/L]

[[opsi-winst-rc-secondary-sections]]
== Secondary Sections

[[opsi-winst-rc-winbatch]]
=== Winbatch [W/L]

Function: execute programs via operating system API

`[WinBatch`<identifier>`]` 

Modifier:

`/LetThemGo`

`/WaitForProcessEnding` "<program.exe>"

`/TimeOutSeconds` <seconds>

`/WaitForWindowAppearing` <window title> ('does not work with 64 Bit programs') [W]

`/WaitForWindowVanish` <window title> ('does not work with 64 Bit programs') [W]

`/RunElevated` // since 4.11.3: only at >= NT6 ; no network access [W]

`/RunAsLoggedOnUser` // since 4.11.3.5 ; works only inside 'userLoginScripts' [W]

`/32Bit`	 //since 4.11.3.5  [W]

`/64Bit`	 //since 4.11.3.5  [W]

`/SysNative`	 //since 4.11.3.5 [W]

[[opsi-winst-rc-dosbatch]]
=== DosBatch and DosInAnIcon (ShellBatch and ShellInAnIcon) [W/L]

Function: Execute section via cmd.exe

`[DosBatch`<identifier>`]` <optional parameters> <winst <modifier>>

`[DosInAnIcon`<identifier>`]` <optional parameters> <winst <modifier>>

`[ShellBatch`<identifier>`]` <optional parameters> <winst <modifier>>

`[ShellInAnIcon`<identifier>`]` <optional parameters> <winst <modifier>>

Modifier:  //since 4.11.1.1

`/32Bit`  [W]

`/64Bit`  [W]

`/SysNative` [W]

`/showoutput` [W/L] // since 4.11.4.7

The modifiers has to be seperated by 'winst' from the parameters.
[source,winst]
----
DosInAnIcon_do_64bit_stuff winst /64Bit
----

Commands:
see manual

[[opsi-winst-rc-execwith]]
=== ExecWith [W/L]

Function: Execute section via any interpreter

`[ExecWith`<identifier>`]` <path to interpreter>

Modifier:

`/LetThemGo`

`/EscapeStrings`

`/32Bit`	 //since 4.11.3.5  [W]

`/64Bit`	 //since 4.11.3.5  [W]

`/SysNative`	 //since 4.11.3.5 [W]

The modifiers has to be seperated by 'winst' from the parameters. The following example call the 64Bit version of the powershell.exe.
[source,winst]
----
ExecWith_do_64bit_stuff "%System%\WindowsPowerShell\v1.0\powershell.exe" winst /64Bit
----

Commands:
see manual

[[opsi-winst-rc-files]]
=== Files [W/L]

Function: File Operations

`[Files`<identifier>`]` 

Modifier [W]:

`/AllNTUserProfiles`

`/AllNTUserSendTo` [W]

`/32Bit`	 //since 4.10.8 [W]

`/64Bit`	 //since 4.10.8  [W]

`/SysNative`	 //since 4.10.8 [W]

Commands:

`checkTargetPath =` <destination directory> [W/L]

`copy` [Options] <source file(s)> <destination directory> [W/L]

some options: 

`-s` rekursiv [W/L]

`-V` version control against targetdir [W]

`-v`  version control against targetdir, %systemroot% and %system% *(do not use it)*  [W]

`-c` continue without reboot even if it is needed [W]

`-d` date check [W]

`-u` update [W]

`-x` extract [W]

`-w` weak (do not overwrite protected files) [W]

`-n` no overwrite [W]

`-r` copy read only attribute [W]


`delete` [Options] <path[/mask]]  //  [W/L]

some options: `-s` rekursiv `-f` force 

Example (*do not forget the trailing Backslash*): +
`delete -sf c:\delete_this_dir\`

`del` [Options] <path[/mask]]   //since 4.11.2.1 [W/L]

Works like `delete` but on +
`del -s -f c:\not-exists` +
if +c:\not-exists+ not exists it do not search complete +c:\+ for +not-exits+  

Example (*you may forget the trailing Backslash*): +
`del -sf c:\delete_this_dir`

`chmod` <mask> <path>   //since 4.11.4.1 [L]

`hardlink` <existing file> <new file> // since 4.11.5 [W/L]

`symlink` <existing file> <new file> // since 4.11.5 [W/L] +
At Windows `symlink` is only available at NT6 and up.

`rename` <old filename> <new filename> // since 4.11.5 [W/L]

`move` <old filename> <new filename> // since 4.11.5 [W/L]



[[opsi-winst-rc-registry]]
=== Registry [W]

Function: edit Registry

Standard method call: +
`[Registry`<identifier>`]` +
works with the specified section.

Alternative method call: +
`Registry  loadUnicodeTextFile(`<.reg file>`) /regedit` +
import the specified <.reg file>.

Alternative method call (deprecated): +
`Registry  loadUnicodeTextFile(`<.addreg file>`) /addreg` +
import the specified <.addreg file>.

Modifier:

`/AllNTUserDats`

`/32Bit`	 //since 4.10.8 

`/64Bit`	 //since 4.10.8 

`/SysNative`	 //since 4.10.8

Commands:

`OpenKey` <Key>
[source,winst]
----
openkey [HKLM\Software\opsi.org]
----

`Set` <varname> `=` <registry type>:<value>

`Add` <varname> `=` <registry type>:<value>

Examples for registry types:
[source,winst]
----
set "var1" = "my string"
set "var2" = REG_SZ:"my string"
set "var3" = REG_EXPAND_SZ:"%ProgramFiles%"
set "var4" = REG_DWORD:123	(Decimal)
set "var5" = REG_DWORD:0x7b	(Hexadecimal)
set "var6" = REG_BINARY:00 01 02 0F 10
set "var7" = REG_MULTI_SZ:"A|BC|de"
----

`Supp` <varname> <list char> <supplement>
[source,winst]
----
supp "Path" ; "C:\utils; %JAVABIN%"
----

`GetMultiSZFromFile` <varname> <file name>

`SaveValueToFile` <varname> <file name>

`DeleteVar` <varname>

`DeleteKey` <registry key>  (does since 4.11.2.1 also work with /AllNTUserDats)

[[opsi-winst-rc-patches]]
=== Patches [W/L]

Function: edit Ini-files

`[Patches`<identifier>`]` <file name>

Modifier:

`/AllNTUserProfiles`  //since 4.11.3  [W]

Commands:

`add [`<section name>`]` <variable1> `=` <value1>

`set [`<section name>`]`<variable1> `=` <value1>

`addnew [`<section name>`]`<variable1> `=` <value1>

`change [`<section name>`]`<variable1> `=` <value1>

`del [`<section name>`]` <variable1> `=` <value1>

`del [`<section name>`]` <variable1>

`delsec [`<section name>`]`

`replace` <variable1>`=`<value1> <variable2>`=`<value2>

[[opsi-winst-rc-patchtextfile]]
=== PatchTextFile [W/L]

Function: edit text files

`[PatchTextFile`<identifier>`]` <file name>

Modifier:

`/AllNTUserProfiles`  //since 4.11.3.4 [W]

Commands:

`Set_Mozilla_Pref (`"<preference type>", "<preference key>", "<preference value>"`)` +
preference types are usally: +
`pref`, `user_pref`, `lock_pref`

`AddStringListElement_To_Mozilla_Pref (`"<preference type>", "<preference key>", "<add value>"`)`

`Set_Netscape_User_Pref (`"<key>", "<value>"`)`  ('deprecated')

`AddstringListElement_To_Netscape_User_Pref`  ('deprecated')

`FindLine` <search string>

`FindLine_StartingWith` <search string>

`FindLine_Containing` <search string>

`GoToTop`

`AdvanceLine` [<number of lines>]

`GoToBottom`

`DeleteTheLine`

`AddLine_` <line> 	or `Add_Line_` <line>

`InsertLine` <line>    	or `Insert_Line_` <line>

`AppendLine` <line> 	or `Append_Line` <line>

`Append_File` <file name>

`Subtract_File` <file name>

`SaveToFile` <file name>

`Sorted`

`setKeyValueSeparator` <separator char> //since 4.11.4.4 [W/L]

`setValueByKey` <keystr> <valuestr> //since 4.11.4.4 [W/L]

[[opsi-winst-rc-LinkFolder]]
=== LinkFolder [W/L]

Function: Startmenue + Desktop Icons

`[LinkFolder`<identifier>`]`

Commands:

`set_basefolder` <system folder>

`set_subfolder` <folder path> (at Linux set always "")

----
set_link
  name:            <link name>
  target:          <path and name of the program>
  parameters:      [command line arguments]
  working_dir:     [working directory]
  icon_file:       [path and name of icon file, default=target]
  icon_index:      [number of icon in icon file, default=0] [W]
  link_categories  [list of categories] [L]
end_link
----

`delete_element`   <link name>

`delete_subfolder` <folder path> [W]

The predefined virtual system folders which can be used are at Windows: +
`desktop, sendto, startmenu, startup, programs, desktopdirectory`, +
`common_startmenu, common_programs, common_startup, common_desktopdirectory` +
and at Linux: +
`common_programs`,`common_startup`,`desktop`, `startup`

Predefined `link_categories` for Linux: +
`AudioVideo`, `Audio`, `Video`, `Development`, `Education`, `Game`, `Graphics`, `Network`, `Office`, `Settings`, `System`, `Utility`

Examples
[source,winst]
----
set_basefolder common_desktopdirectory
set_subfolder ""
set_link
  name: opsi-winst
  target: "%ProgramFiles32Dir%\opsi.org\opsi-client-agent\opsi-winst\winst32.exe"
end_link
----

[source,winst]
----
[LinkFolder_configed_lin]
set_basefolder common_programs
set_subfolder ""

set_link
  name: opsi-configed-Local
  target: java 
  parameters: $parameter$
  icon_file: "$InstallDir$/opsi.png"
  link_categories: System;Utility;
end_link
----

The predefined virtual system folders: +
`desktop, sendto, startmenu, startup, programs, desktopdirectory` +
are pointing to the folders of the user that the script is running.
If you use it in a userLoginScript with the opsi 'User Profile Management' extension these virtual folders point to the folder of the user that just had logged in.

[[opsi-winst-rc-OpsiServiceCall]]
=== OpsiServiceCall [W/L]

Function: opsi-Service access

`[OpsiServiceCall`<identifier>`]`

Commands:
see manual

[[opsi-winst-rc-PatchHosts]]
=== PatchHosts [W/L]

Function: hosts-files bearbeiten

`[PatchHosts`<identifier>`]`

Commands:

`setaddr`  <hostname> <IPaddress>

`setname` <IPaddress> <hostname>

`setalias` <hostname> <alias>

`setalias` <IPadresse> <alias>

`delalias` <hostname> <alias>

`delalias` <IPaddress> <alias>

`delhost` <hostname>

`delhost` <ipadresse>

`setComment` <ident> <comment>

[[opsi-winst-rc-XMLPatch]]
=== XMLPatch [W]

Function: edit XML files

`[XMLPatch`<identifier>`]`

Commands:
see manual

[[opsi-winst-rc-ExecPython]]
=== ExecPython [W/L]

Function: Execute section via python interpreter

`[ExecPython`<identifier>`]`

Commands:
see manual

[[opsi-winst-rc-LdapSearch]]
=== LdapSearch [W]

Function: read from LDAP

`[LdapSearch`<identifier>`]`

Commands:
see manual

[[opsi-winst-rc-topic]]
== By Topic

[[opsi-winst-rc-json]]
=== opsiservicecall and json Related functions [W/L]

`jsonIsValid(`<jsonstr>`) : boolean`  //since 4.11.6: [W/L]

`jsonIsArray(`<jsonstr>`) : boolean`  //since 4.11.6: [W/L]

`jsonIsObject(`<jsonstr>`) : boolean`  //since 4.11.6: [W/L]

`jsonAsObjectHasKey(`<jsonstr>,<keystr>`) : boolean`  //since 4.11.6: [W/L]

`jsonAsArrayCountElements(`<jsonstr>`) : intstr`  //since 4.11.6: [W/L]

`jsonAsObjectCountElements(`<jsonstr>`) : intstr`  //since 4.11.6: [W/L]

`jsonAsArrayGetElementByIndex(`<jsonstr>, <indexstr>`) : jsonstring`  //since 4.11.6: [W/L]

`jsonAsObjectGetValueByKey(`<jsonstr>, <keystr>`) : valuestring`  //since 4.11.6: [W/L]

`jsonAsObjectSetValueByKey(`<jsonstr>, <keystr>,<valuestring>`) : jsonstring`  //since 4.11.6: [W/L]

`jsonAsObjectSetStringtypeValueByKey(`<jsonstr>, <keystr>,<valuestring>`) : jsonstring`  //since 4.11.6: [W/L]

`jsonAsArrayPutObjectByIndex(`<jsonstr>, <indexstr>, <objectstr>`) : jsonstring`  //since 4.11.6: [W/L]

`jsonAsArrayToStringList(`<jsonstr>`) : stringlist`  //since 4.11.6: [W/L]

`jsonAsObjectGetKeyList(`<jsonstr>`) : stringlist`  //since 4.11.6: [W/L]

`jsonStringListToJsonArray(`<strlist>`) : jsonstr`  //since 4.11.6: [W/L]

`convert2Jsonstr(`<string>`)`  //since 4.10.8.3

see also: OpsiServiceCall  <<opsi-winst-rc-OpsiServiceCall>>

[[opsi-winst-rc-process]]
=== Process and Script Related functions [W/L]

`Killtask` <process name> [W/L]

`ChangeDirectory` <directory>   : noresult //since 4.11.2.6 [W/L]

`GetProcessList :list`  //since 4.11.1.2; gives list of exename;pid;dom/user [W/L]

`processIsRunning(`<process name>`) :bool`  //since 4.11.6.1

`shellCall (`<command string>`)` : list //since 4.11.4.2 [W/L]

[source,winst]
----
set $list$= shellCall('net start')
----


`shellCall (`<command string>`)` : noresult //since 4.11.6.1 [W/L]

`getOutStreamFromSection (`<dos section name>`)` [W/L]
[source,winst]
----
set $list$= getOutStreamFromSection ('DosInAnIcon_try')
----

`getLastExitCode` [W/L]

`includelog` <file name> <tail size>   //since 4.11.2.1 [W/L]

`includelog` <file name> <tail size> [<encoding>]  //since 4.11.4.1 [W/L]


see also: ExecWith sections <<opsi-winst-rc-execwith>>

see also: ShellBatch sections <<opsi-winst-rc-dosbatch>>

see also: Winbatch sections <<opsi-winst-rc-winbatch>>

[[opsi-winst-rc-compare]]
=== Compare Related functions [W/L]

`CompareDotSeparatedStrings(`<string1>, <string2>`) : string` [W/L]

`CompareDotSeparatedNumbers(`<string1>, <string2>`) : string` [W/L]

`CompareDotSeparatedNumbers(`<str1>,<relation str>,<str2>`) : bool`  //since 4.11.5.2: [W/L]

`CompareDotSeparatedStrings(`<str1>,<relation str>,<str2>`) : bool`  //since 4.11.5.2: [W/L]



[[opsi-winst-rc-string-handling]]
=== Stringhandling functions [W/L]

`splitString (`<string1>, <string2>`)` [W/L]
[source,winst]
----
set $list1$ = splitString ("\\server\share\dir","\")
----

`splitStringOnWhiteSpace (`<string>`)` [W/L]

`composeString (`<string list>, <Link>`)` [W/L]

`takeString (`<index>, <list>`)` [W/L]

`setStringInListAtIndex(`<newstring>,<list>,<indexstr>`) : list` //since 4.11.6  [W/L]

`takeFirstStringContaining(`<list>,<search string>`)` [W/L]

`contains(`<str>, <substr>`)`  //since 4.11.3: true if <substr> in <str> [W/L]

`isNumber(`<str>`)` //since 4.11.3: true if <str> represents an integer [W/L]

`trim(`<string>`)` [W/L]

`lower(`<string>`)` [W/L]

`unquote(`<string>,<quote-string>`)`  //since 4.11.2.1  [W/L]

`unquote2(`<string>,<quote-string>`)`  //since 4.11.5.2  [W/L]

`stringReplace(`<string>, <oldPattern>, <newPattern>`)`  //since 4.11.3 [W/L]

`strLength(`<string>`)`  //since 4.11.3 [W/L]

`strPos(`<string>, <sub string>`)`  //since 4.11.3 [W/L]

`strPart(`<string>, <start pos>, <number of chars>`)`  //since 4.11.3 [W/L]

`getValue(`<key string>, <hash string list> `)` [W/L]

`getValueBySeparator(`<key string>,<separator string>,<hash string list> `)` //since 4.11.2.1 [W/L]

`getValueFromFile(`<key string>, <file name>`)` //since 4.11.4.4 [W/L]

`getValueFromFileBySeparator(`<key string>,<separator string>,<file name>`)` //since 4.11.4.4 [W/L]


[[opsi-winst-rc-stringlist-handling]]
=== Stringlist handling functions [W/L]

`getListContaining(`<list>,<search string>`)` [W/L]

`getListContainingList(`<list1>,<list2>`)`  //since 4.11.3.7 [W/L]

`count (`<list>`)` [W/L]

`emptylist (`<list>`)`  //since 4.11.3.7 [W/L]

`for %`<identifier>`% in` <list> `do` <one statement | sub section> [W/L]
[source,winst]
----
for %s% in $list1$ do sub_test_string
----

`createStringList (`<string0>, <string1> ,... `)` [W/L]
[source,winst]
----
set $list1$ = createStringList ('a','b')
----

`reverse (`<list>`)` [W/L]

`getSubList (`<start index> : <end index>, <list>`)` [W/L]

`addtolist(`<list>,<string>`)`	 //since 4.10.8 [W/L]

`addListToList(`<dest list>,<src list>`)`	 //since 4.10.8 [W/L]

`reencodestrlist(`<list>, <from>, <to>`)` //since 4.11.4.2 [W/L]

`removeFromListByContaining(`<search string>`,` <target list>`)` //since 4.11.5.1 [W/L]

`removeFromListByContaining(`<search list>`,` <target list>`)` //since 4.11.5.1 [W/L


[[opsi-winst-rc-regfunc]]
=== Registry related functions [W/L]

`GetRegistrystringvalue (`"[key] var"`)` [W]

`GetRegistryStringValue32 (`"[key] var"`)`   //since 4.10.8 [W]

`GetRegistryStringValue64 (`"[key] var"`)`   //since 4.10.8 [W]

`GetRegistryStringValueSysNative (`"[key] var"`)`    //since 4.10.8 [W]


`getProductPropertyList(`<propname>,<default value>`)`  //since 4.11.3 [W/L]

`getRegistryKeyList32(`<regkey>`)` //since 4.11.3 [W]

`getRegistryKeyList64(`<regkey>`)` //since 4.11.3 [W]

`getRegistryKeyListSysnative(`<regkey>`)` //since 4.11.3 [W]

`getRegistryVarList32(`<regkey>`)`  //since 4.11.3 [W]

`getRegistryVarList64(`<regkey>`)` //since 4.11.3 [W]

`getRegistryVarListSysnative(`<regkey>`)` //since 4.11.3 [W]

`getRegistryVarMap32(`<regkey>`)`  //since 4.11.3 [W]

`getRegistryVarMap64(`<regkey>`)` //since 4.11.3 [W]

`getRegistryVarMapSysnative(`<regkey>`)` //since 4.11.3 [W]

see also: <<opsi-winst-rc-registry>>

[[opsi-winst-rc-filefunc]]
=== File related functions [W/L]

`strLoadTextFile (`<file name>`)` [W/L]

`loadTextFile (`<file name>`)` [W/L]

`loadUnicodeTextFile (`<file name>`)` [W]

`loadTextFileWithEncoding(` <file name> `,` <encoding>`)` //since 4.11.5 [W/L]

`FileExists (`<file name>`)` [W/L]

`FileExists32 (`<file name>`)` [W]

`FileExists64 (`<file name>`)` [W]

`FileExistsSysNative (`<file name>`)` [W]

`LineExistsIn (`<string>, <file name>`)` [W/L]

`LineBeginning_ExistsIn (`<string>, <file name>`)` [W/L]

`LineContaining_ExistsIn(` <string>, <file name> `)` //since 4.11.4.10: true: if a in <file name> contains <string> [W/L]

`saveTextFile(`<list>, < filename>`)` //since 4.11.4.4: true: if list is succesfully written to file [W/L]

`getFileInfoMap(` <file name> `)` [W]

`ExtractFilePath (`<path>`)` [W/L]


see also: <<opsi-winst-rc-files>>

see also: <<opsi-winst-rc-patchtextfile>>

[[opsi-winst-rc-inifunc]]
=== Ini file related functions [W/L]

`GetvalueFromInifile (` file, section, key, default value `)` [W/L]
[source,winst]
----
GetValueFromInifile("myfile","mysec","mykey","")
----


`getSectionNames(`<ini-file>`)` [W/L]

`retrieveSection (`<section name>`)` [W/L]

`getValue(`<key string>, <hash string list> `)` [W/L]

`getValueBySeparator(`<key string>,<separator string>,<hash string list> `)` //since 4.11.2.1 [W/L]

`getValueFromFile(`<key string>, <file name>`)` //since 4.11.4.4 [W/L]

`getValueFromFileBySeparator(`<key string>,<separator string>,<file name>`)` //since 4.11.4.4 [W/L]



see also: <<opsi-winst-rc-patches>>

[[opsi-winst-rc-cryptfunc]]
=== Crypt / Hash related functions [W/L]

`DecStrToHexStr (` <decstring>, <hexlength>`)` [W/L]

`HexStrToDecStr (`<hexstring>`)` [W/L]

`base64EncodeStr(`<string>`)`  [W/L]

`base64DecodeStr(`<string>`)`  [W/L]

`RandomStr` [W/L]

encryptStringBlow(<keystring>,<datastring>)

decryptStringBlow(<keystring>,<datastring>)

md5sumFromFile(<path to file>)


[[opsi-winst-rc-numberfunc]]
=== Number related functions [W/L]

`isNumber(`<str>`) : string` //since 4.11.3: true if <str> represents an integer [W/L]

`CompareDotSeparatedNumbers(`<str1>,<relation str>,<str2>`) : bool`  //since 4.11.5.2: [W/L]

`CompareDotSeparatedNumbers(`<string1>, <string2>`) : string` [W/L]

`calculate(`<arithmetic string expression>`) : string` // since 4.11.3.5 : knows: `+-*/()` [W/L]

`DecStrToHexStr (` <decstring>, <hexlength>`) : string` [W/L]

`HexStrToDecStr (`<hexstring>`) : string` [W/L]

[[opsi-winst-rc-OSfunc]]
=== Operating System related functions [W/L]

`GetOS`  // 'Linux' or 'Windows_NT'   [W/L]

`getLinuxDistroType`  // 'debian' or 'redhat' or 'suse'  (see `getLinuxVersionMap`) [L]

`GetMsVersionInfo` //Windows Version Information [W]

`GetMSVersionMap` [W]

`getLinuxVersionMap`  //since 4.11.4  [L] +


`GetSystemType`    //OS Architecture ("64 Bit System" or "x86 System") [W/L]

`EnvVar (`<environment variable>`)` [W/L]

`getProfilesDirList` //since 4.11.3.2 [W/L]


[[opsi-winst-rc-networkfunc]]
=== network related functions [W/L]

`GetHostsName (`<hostaddress> `)` [W/L]

`GetHostsAddr (`<hostname> `)` [W/L]

`GetMyIpByTarget(`<target ip addr>`)` //since 4.11.3.2 [W]

`GetIpByName(`<ip addr / ip name>`)` //since 4.11.3.2 [W/L]

[[opsi-winst-rc-encodingfunc]]
=== encoding related functions [W/L]

`encoding=`<encoding> // (default is system encoding) since 4.11.4.2

`GetLocaleInfoMap` [W]

`reencodestr(`<str>, <from>, <to>`)` //since 4.11.4.2 [W/L]

`loadUnicodeTextFile (`<file name>`)` [W]

`loadTextFileWithEncoding(` <file name> `,` <encoding>`)` //since 4.11.5 [W/L]

`includelog` <file name> <tail size> [<encoding>]  //since 4.11.4.1 [W/L]



[[opsi-winst-rc-opsifunc]]
=== opsi related functions [W/L]

`getProductMap`  // since 4.11.2.4  [W/L] +
keys are: id, name, description, advice, productversion, packageversion, priority, installationstate, lastactionrequest, lastactionresult, installedversion, installedpackage, installedmodificationtime,actionrequest

`getProductPropertyList(`<propname>,<default value>`)`  //since 4.11.3 [W/L]

`GetProductProperty (`<PropertyName>, <DefaultValue> `)` [W/L]

`GetConfidentialProductProperty (` <PropertyName>, <DefaultValue>`)` //since 4.11.5.2 [W/L]


[[opsi-winst-rc-usercontext]]
=== Usercontext / loginscripts related functions[W]:

`GetUserSID(`<Windows Username>`)`

`GetLoggedInUser`   //since 4.11.1.2

`GetUsercontext`   //since 4.11.1.2

`GetScriptMode`  possible values 'Machine','Login' //since 4.11.2.1

`saveVersionToProfile` - save productversion-packageversion to local profile //since 4.11.2.1

`readVersionFromProfile` : string - read productversion-packageversion from local profile //since 4.11.2.1

`scriptWasExecutedBefore` : boolean - is true if saved and running productversion-packageversion are identical //since 4.11.2.1

[[opsi-winst-rc-license-management]]
=== License Management related functions [W/L]

`DemandLicenseKey(` poolId [, productId [,windowsSoftwareId]] `)`
[source,winst]
----
set $mykey$ = DemandLicenseKey ("", "office2007")
----

`FreeLicense (`poolId [, productId [,windowsSoftwareId]]`)`
[source,winst]
----
set $result$ = FreeLicense("", "office2007")
----

[[opsi-winst-rc-timefunc]]
=== time / date related functions

`getDiffTimeSec` (Time in seconds since last marktime) //since 4.11.3 [W/L]