site:
  title: opsi-Dokumentation
  url: https://gitlab.uib.gmbh/uib/opsidoc.git
  start_page: opsi-docs-de::index.adoc
asciidoc:
  attributes:
    source-highlighter: highlight.js
    REPO_KEY: REPO_KEY
    REPO_URL: REPO_URL
runtime:
  cache_dir: ./.cache/antora
  fetch: true
content:
  sources:
  - url: https://gitlab.uib.gmbh/uib/opsidoc.git
    branches: [CURRENT_BRANCH]
    edit_url: '{web_url}/-/edit/{refname}/{path}'
    start_path: docs/de
  - url: https://gitlab.uib.gmbh/uib/opsidoc.git
    branches: [CURRENT_BRANCH]
    start_path: docs/en
    edit_url: '{web_url}/-/edit/{refname}/{path}'
ui:
  bundle:
    url: antora-ui/build/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental_ui
output:
  dir: ./build/test/site
