site:
  title: opsi-Dokumentation
  url: https://gitlab.uib.gmbh/uib/opsidoc.git
  start_page: opsi-docs-de::index.adoc
# urls:
#   latest_version_segment_strategy: redirect:from
#   latest_version_segment: stable
#   latest_prerelease_version_segment: testing
#   redirect_facility: nginx
antora:
  extensions:
    - require: '@antora/lunr-extension'
      languages: [en, de]
asciidoc:
  attributes:
    source-highlighter: highlight.js
    doctype: book
runtime:
  cache_dir: ./.cache/antora
  fetch: false
content:
  sources:
  # - url: https://gitlab.uib.gmbh/uib/opsidoc.git
  - url: /workspaces/opsidoc
    branches: [HEAD]
    # edit_url: '{web_url}/-/edit/{refname}/{path}'
    start_path: docs/de
  # - url: https://gitlab.uib.gmbh/uib/opsidoc.git
  - url: /workspaces/opsidoc
    branches: [HEAD]
    start_path: docs/en
    # edit_url: '{web_url}/-/edit/{refname}/{path}'
ui:
  bundle:
    url: antora-ui/build/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental_ui


