site:
  title: opsi-Dokumentation
  url: https://gitlab.uib.gmbh/uib/opsidoc.git
  start_page: opsi-docs-de::index.adoc
antora:
  extensions:
    - require: '@antora/lunr-extension'
      languages: [en, de]
asciidoc:
  attributes:
    source-highlighter: ~
    doctype: book
runtime:
  cache_dir: ./.cache/antora
  fetch: false
content:
  sources:
  # - url: https://gitlab.uib.gmbh/uib/opsidoc.git
  - url: /workspaces/opsidoc
    branches: [HEAD]
    # edit_url: '{web_url}/-/edit/{refname}/{path}'
    start_path: docs/de
  # - url: https://gitlab.uib.gmbh/uib/opsidoc.git
  - url: /workspaces/opsidoc
    branches: [HEAD]
    start_path: docs/en
    # edit_url: '{web_url}/-/edit/{refname}/{path}'
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental_ui

