////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      16.05.2023
:Revision:  4.2
:toclevels: 6
:doctype:   book
:icons: font
:xrefstyle: full
:winclientmanual: opsi-windows-client-manual
:lang: de

include::common:partial$opsi_terms.adoc[]



[[opsi-winclient-installation-config-get-essential-products]]
= Minimale opsi-Produkte einspielen

Zur Verteilung von Software mit opsi stehen fertige Produkte zur Installation bereit. Zu diesen Produkten gehört auch der Client-Agent, der auf allen Clients installiert sein muss, damit die Verwaltung mit opsi möglich ist. Es gibt zwei Wege, wie Sie die opsi-Produkte unter Windows einspielen können:

* <<opsi-winclient-installation-config-get-essential-products-automatic>>
* <<opsi-winclient-installation-config-get-essential-products-manually>>

TIP: Wir empfehlen die erste Variante und das automatische Einspielen der opsi-Produkte.

[[opsi-winclient-installation-config-get-essential-products-automatic]]
== opsi-Produkte automatisch einspielen

Zur automatischen Installation der opsi-Produkte verwenden Sie das Werkzeug `opsi-package-updater`, das automatisch die aktuellen Pakete aus dem opsi-Repository herunterlädt und auf dem Server installiert. Den `opsi-package-updater` konfigurieren Sie über die folgenden Dateien:

* `/etc/opsi/opsi-package-updater.conf`: allgemeine Einstellungen, z.{nbsp}B. Ort für die heruntergeladenen Pakete, Logfile, Loglevel, Timeout, Verzeichnis für die Repositorys usw.
* `/etc/opsi/package-updater.repos.d/`: Verzeichnis für die Repositorys; zum Aktivieren eines Repositorys setzen Sie in der jeweiligen `.repo`-Datei den Eintrag `active = true` setzen.

.`/etc/opsi/package-updater.repos.d/uib-windows.repo`

[source,configfile]
----
; This repository provides products for deploying and managing Microsoft
; Windows clients with opsi.

[repository_uib_windows]
description = opsi Windows Support
active = true
baseUrl = http://download.uib.de
dirs = opsi4.2/stable/packages/windows/localboot/, opsi4.2/stable/packages/windows/netboot/
autoInstall = false
autoUpdate = true
autoSetup = false
; Set Proxy handler like: http://10.10.10.1:8080
proxy =
----

NOTE: Wenn der Internetzugriff über einen Proxy erfolgt, tragen Sie diesen in den `.repo`-Konfigurationsdateien im Verzeichnis `/etc/opsi/package-updater.repos.d/` als Wert für `proxy` ein. Ab `opsi-utils` >= 4.1.1.33 können Sie einen globalen Proxy in der Datei `/etc/opsi/opsi-package-updater.conf` konfigurieren.

Installieren Sie die Pakete auf dem Server mit dem folgenden Befehl (erfordert `root`-Rechte):

[source,shell]
----
opsi-package-updater -v --repo uib_windows install
----

TIP: Nach erfolgreicher Installation laden Sie alle Daten in der xref:common:partials/firststeps-configed.adoc[Management-Oberfläche `opsi-configed`] neu, damit die neuen Produkte dort sichtbar werden.

Sie können das Tool `opsi-package-updater` auch dazu verwenden, um installierte Pakete zu aktualisieren:

[source,shell]
----
opsi-package-updater -v update
----

Weitere Informationen zum `opsi-package-updater` finden Sie im Kapitel xref:server:components/opsi-package-updater.adoc[`opsi-package-updater`].

CAUTION: Beachten Sie, dass Produkte zur Betriebssystem-Installation wie z.{nbsp}B. {opsi-client-os} nach dem Einspielen nicht sofort einsatzbereit sind. Sie müssen noch durch die Installationsdateien des entsprechenden Installationsmediums ergänzt werden (siehe Kapitel xref:common:partials/firststeps-osinstall_win.adoc[Windows mit opsi installieren]).



[[opsi-winclient-installation-config-get-essential-products-manually]]
== opsi-Produkte von Hand einspielen

Es gibt auch die Möglichkeit manuell die Pakete herunter zu laden und zu installieren.

Holen Sie sich die aktuellen opsi-Pakete im `.opsi`-Paketformat.
Die Pakete finden Sie unter `https://download.uib.de/opsi4.2/stable/packages/windows/localboot` +
`https://download.uib.de/opsi4.2/stable/packages/windows/netboot`
bzw. unter
`https://download.uib.de/opsi4.2/testing/packages/windows/localboot` +
`https://download.uib.de/opsi4.2/testing/packages/windows/netboot`.

Wir empfehlen die .opsi-Dateien unter `/var/lib/opsi/repository` zu speichern.
Zum Sicherstellen, dass der Prozess `opsiconfd` auf die Dateien zugreifen kann, sollte `opsi-set-rights /var/lib/opsi/repository` ausgeführt werden.

Nach dem Download müssen Sie die Pakete auf dem Server mit dem Befehl `opsi-package-manager -i <paketname>.opsi` installieren.
