////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      10.05.2023
:Revision:  4.2
:toclevels: 6
:doctype:   book
:icons: font
:xrefstyle: full
:winclientmanual: opsi-windows-client-manual
:lang: de

// Include common opsi terms
ifeval::["{mode}" == "antora"]
include::common:partial$opsi_terms.adoc[]
endif::[]


// = opsi Windows client manual

// Include common opsi copyright
// include::common:partial$copyright.adoc[]


[[opsi-winclient-introduction]]
= Einführung

Diese Anleitung beschreibt den Betrieb von Windows-Clients in opsi.

NOTE: Voraussetzung ist, dass ein xref:server:overview.adoc[opsi-Server] bereits installiert und betriebsbereit ist.

Wesentliche Themen dieser Anleitung:

. Automatische OS-Installation
. Windows-Rechnern in opsi aufnehmen und einbinden
(Installation des xref:clients:client-agent/opsi-client-agent.adoc[Client-Agent])
. opsi-Standardsoftware für Windows auf dem opsi-Server bereitstellen
. Standardsoftware auf den Windows-Clients installieren
. opsi-Pakete erstellen und eigene Software paketieren
. Hinweise zu Windows-Clients
.. Spezielle Befehle für Windows
.. Verzeichnisse, die Sie verwenden dürfen

[[opsi-winclient-convention]]
include::ROOT:partial$conventions.adoc[]

