////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      29.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons: font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

// cspell: ignore paketieren

[[opsi-winclient-introduction]]
= Windows-Clients

Diese Anleitung beschreibt den Betrieb von Windows-Clients in opsi. Dabei geht es im Wesentlichen um die folgenden Themen:

* automatische OS-Installation
* Windows-Rechner in opsi aufnehmen und einbinden
(Installation des xref:clients:windows-client/windows-client-agent.adoc[Client-Agent])
* Windows-Standardsoftware auf dem opsi-Server bereitstellen
* Standardsoftware auf den Windows-Clients installieren
* opsi-Pakete erstellen und eigene Software paketieren
* Hinweise zu Windows-Clients
    ** spezielle Befehle für Windows
    ** Verzeichnisse, die Sie verwenden dürfen

NOTE: Voraussetzung für die Verwaltung von Windows-Clients ist, dass ein xref:server:overview.adoc[opsi-Server] bereits installiert und betriebsbereit ist.

[[opsi-winclient-convention]]
include::ROOT:partial$conventions.adoc[]

