////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      11.01.2021
:doctype: book

include::common:partial$opsi_terms.adoc[]

[[opsi-manual-opsiwebgui-instguide]]
= Installation guide
This chapter shows you two ways installing the {opsi-webgui} on your configserver: The installation through the opsi repository and through admininterface.

[[opsi-manual-opsiwebgui-requirements]]
== Requirements 
For a functional {opsi-webgui} the {opsiconfd} needs a MySQL activation (Read the xref:server/opsi-backends#opsi-manual-backends-mysql-configdata-overview[mysql backend] for configuration details).

[[opsi-manual-opsiwebgui-installation-opsirepo]]
== Installation from the opsi repository
For the {opsi-webgui} installation from the opsi repository you need to specify the correct repository branch. After the installation of the webgui with the systems packagemanager you can visit the {opsi-webgui} at https://<configserver-address>:4447/addons/webgui/app

NOTE: Currently {opsi-webgui} is only available from the experimental branch.



*Example for Debian / Ubuntu* +
We recommend setting up an exception for the {opsi-webgui} (unless you have set the experimental branch as the main branch in `/etc/apt/sources.list.d/opsi.list`). +

. Create a new file located in `/etc/apt/preferences.d/` e.g. `10-opsi-webexp` with following content:
+
--
[source]
----
# /etc/apt/preferences.d/10-opsi-webexp
Package: *
Pin: release l=home:uibmz:opsi:4.2:stable
Pin-Priority: 501

Package: opsi-webgui       
Pin: release l=home:uibmz:opsi:4.2:experimental
Pin-Priority: 502
---- 

The content tells the system to get all packages from the stable repository if available. For the {opsi-webgui}, the experimental repository also applies.

--


. Install the {opsi-webgui} with
+
--

[source, prompt]
----
sudo apt update
sudo apt install opsi-webgui
sudo opsiconfd restart
---- 

To update the {opsi-webgui} the following command can be used: 

[source, prompt]
----
sudo apt update
sudo apt upgrade opsi-webgui
----

--

[[opsi-manual-opsiwebgui-installation-admininterface]]
== Installation through admininterface using ZIP-file
The installation via the admin interface works regardless of the used system. However, since only _one_ installation is performed, updates usually have to be applied manually (unless the correct repository is set up). Therefore this variant is only recommended if special versions of the webgui are provided (for example for test purposes). 

. Download the latest version {opsi-webgui} (ZIP file) from https://download.uib.de/opsi4.2/experimental/opsiconfd-addons/ .
. Go to https://<configserver-address>:4447/admin/#addons. 
Upload the file and press the *[Install addon]* button.
