////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      11.01.2021
:doctype: book

include::common:partial$opsi_terms.adoc[]

[[opsi-manual-opsiwebgui-technology]]
= Technology stack

The {opsi-webgui} is built as an {opsiconfd} addon and it is stored in the directory `/var/lib/opsiconfd/addons/webgui` on the configserver.

The backend is built with FastAPI, a Python framework and is responsible for reading data from and writing it to the MySQL database.
It interacts directly with the database to improve performance. This is also the reason for the needed MySQL opsi-extension. 
The backend also communicates with {opsiconfd} for handling sessions and logging.

The frontend is developed with Nuxt, a Vue.js Framework. 
It makes web requests to the backend, fetches data and displays information.
