////
; Copyright (c) uib gmbh (uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      25.11.2024
:doctype: book



[[opsi-module-custom_ca]]
= Custom Certificate Authority

Das Custom-CA-Modul für OPSI ermöglicht es Ihnen, Ihre eigene Zertifizierungsstelle (CA) zu verwenden, um Zertifikate für den OPSI-Configserver auszustellen.
Die OPSI-CA wird in diesem Fall weiterhin verwendet um Zertifikate für OPSI-Clients und OPSI-Depotserver zu erzeugen.
Das Server-Zertifikat für den OPSI-Configserver wird jedoch von Ihrer eigenen CA ausgestellt.
Dies hat den Vorteil, dass Sie auch beim Zugriff auf den OPSI config-Server die Vertrauenskette Ihrer Organisation nutzen.
Die Browser akzeptieren das Zertifikat des OPSI-Configservers ohne Warnung.

Um die Verwendung eigener Zertifikate für OPSI zu konfigurieren, lesen Sie bitte xref:server:components/tls.adoc#server-components-tls-custom-ca[Verwendung einer eigenen Zertifizierungsstelle].

include::partial$paid-extension-note.adoc[]