////
; Copyright (c) uib gmbh (uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      25.11.2024
:doctype: book



[[opsi-module-letsencrpt]]
= Let's Encrypt

Die Let's Encrypt-Erweiterung für opsi ermöglicht es, SSL/TLS-Zertifikate für den opsi-Configserver über die Let's Encrypt-Zertifizierungsstelle automatisch zu beziehen und zu erneuern.
Die opsi-CA wird in diesem Fall weiterhin verwendet um Zertifikate für opsi-Clients und opsi-Depotserver zu erzeugen.
Das Server-Zertifikat für den opsi-Configserver wird jedoch von Let's Encrypt bezogen.
Die hat den Vorteil, dass das alle gängigen Browser das Zertifikat des opsi-Configservers ohne Warnung akzeptieren.

Um die Verwendung von Let's Encrypt für opsi zu konfigurieren, lesen Sie bitte xref:server:components/tls.adoc#server-components-tls-letsencrypt[Verwendung von Let's Encrypt].

include::partial$paid-extension-note.adoc[]