////
; Copyright (c) uib gmbh (uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:  uib gmbh
:Email:   info@uib.de
:Date:    13.03.2025
:doctype: book



[[opsi-module-message-of-the-day]]
= Message of the Day

Die Erweiterung *Message of the Day* ermöglicht das Anzeigen von Nachrichten für Benutzer, die sich an einem opsi-Client anmelden. Dabei wird zwischen zwei Nachrichtentypen unterschieden:

* *Geräte-Nachricht*: Wird vor der Benutzeranmeldung angezeigt.
* *Benutzer-Nachricht*: Erscheint nach der Anmeldung des Benutzers.

Jede Nachricht wird genau einmal angezeigt. Die Formatierung der Nachrichten erfolgt über Markdown. Benutzer-Nachrichten können Links enthalten, die im Standardbrowser des Nutzers geöffnet werden.

Sobald eine neue Nachricht hinterlegt wird, erscheint sie so bald wie möglich auf den Clients. Optional kann ein Ablaufdatum festgelegt werden, nach dem die Nachricht nicht mehr angezeigt wird.

Die definierten Nachrichten gelten für alle Benutzer und Geräte, die *Message of the Day* nutzen. Eine gezielte Zuweisung an einzelne Benutzer oder Geräte ist nicht möglich.

Um die Erweiterung zu aktivieren, muss der (xref:gui:configed/userguide-clients.adoc#opsi-manual-configed-hostproperties[Host-Parameter]) 'opsiclientd.global.message_of_the_day_enabled' gesetzt werden.

Die Verwaltung der Nachrichten erfolgt über *opsi-configed* unter _Extras_ => _Message of the Day_.


include::partial$paid-extension-note.adoc[]
