////
; Copyright (c) uib GmbH (uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      20.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



[[opsi-manual-scalability]]
= Skalierbarkeit

Standardmäßig wird der Dienst *opsiconfd* mit einem einzelnen Worker-Prozess gestartet.
Wie viele Clients von einem Worker-Prozess bedient werden können, hängt von verschiedenen Faktoren ab, beispielsweise Hardware, Netzwerk, Anzahl und Größe der OPSI-Pakete und weiteren Aspekten. Als grober Richtwert können etwa 600 Clients pro Worker-Prozess angenommen werden. Soll eine größere Anzahl von Clients performant bedient werden, muss die Anzahl der Worker-Prozesse erhöht werden. Die Anfragen werden dann auf die einzelnen Worker verteilt.

Mit dem OPSI-Modul *Scalability Light* können zwei Worker-Prozesse gestartet werden.
Mit dem OPSI-Modul *Scalability* ist die Anzahl der Worker-Prozesse beliebig konfigurierbar.

Die Anzahl der Worker-Prozesse wird über den Parameter `workers` in der Datei `/etc/opsi/opsiconfd.conf` festgelegt.
Beispiel:
[source,console]
----
workers = 2
----

Nach einer Änderung der Konfiguration genügt es, den Dienst *opsiconfd* anzuweisen, die Konfiguration neu zu laden:
[source,console]
----
opsiconfd reload
----

TIP: Da jeder Worker-Prozess Ressourcen benötigt und einen gewissen Overhead verursacht, sollte die Anzahl der Worker-Prozesse nicht zu hoch gewählt werden.

include::partial$paid-extension-note.adoc[]
