////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      25.11.2024
:doctype: book



[[opsi-module-sso]]
= Single Sign-On (SSO)

Die Single Sign-On (SSO)-Erweiterung für opsi ermöglicht die Authentifizierung von Benutzern bei einem zentralen Identity Provider.
Auf diese Weise können sich Administratoren mit ihren bestehenden Anmeldedaten bei opsi anmelden.
Mit SSO können Sie die bestehende Benutzerverwaltung Ihres Identity Providers nutzen und müssen die Benutzer nicht separat in opsi verwalten.
Das vereinfacht die Verwaltung der Benutzer und erhöht die Sicherheit.
Der Komfort und die Produktivität der Benutzer werden erhöht, da sie sich nur einmal anmelden müssen.

Die SSO-Erweiterung unterstützt derzeit link:https://www.microsoft.com/de-de/security/business/identity-access/microsoft-entra-id[Microsoft Entra ID] und link:https://www.keycloak.org/[Keycloak] über das SAML 2.0 Protokoll.

Um die SSO-Erweiterung für opsi zu konfigurieren, lesen Sie bitte xref:server:components/authorization.adoc#server-components-authorization-saml[Autorisierung über SAML].

NOTE: Dieses Modul ist momentan eine link:https://opsi.org/de/extensions/[kostenpflichtige Erweiterung]. Das heißt, dass Sie eine Freischaltdatei benötigen. Sie erhalten diese, nachdem Sie die Erweiterung gekauft haben. Zu Evaluierungszwecken stellen wir Ihnen kostenlos eine zeitlich befristete Freischaltung zur Verfügung. Bitte kontaktieren Sie uns dazu per mailto:info@uib.de[E-Mail].
