////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      20.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-manual-userroles]]
[[opsi-manual-configed-hostproperties-userroles]]
= Verwaltung von Benutzerrechten und -rollen

Ab Version 4.0.7.5 bietet der _opsi-configed_ die Userrollen-Funktion an.

WARNING: Zur Verwendung des Features muss _user roles_ in der _modules_-Datei freigeschaltet sein.

In der Oberfläche zeigt die Existenz der Kategorie _user_ in der Übersicht der Server-Hostparameter,
dass diese Funktion verfügbar (aber noch nicht unbedingt aktiv) ist.
Im Baum der Eigenschaften steht direkt in _user_  primär der boolesche Eintrag

[source,prompt]
----
user.{}.register
----


mit dem Defaultwert _false_.

Die anderen Einträge, die an dieser Stelle des Property-Baums stehen, sind die Defaultwerte für die auch userspezifisch mögliche Konfiguration der Server-Konsole
(vgl.  xref:gui:configed.adoc#opsi-manual-configed-serverconsole[opsiconfiged Server-Konsole]):


Zur Aktivierung der Userrollen-Funktionalität ist

1. der Wert von _user.{}.register_ auf _true_ zu setzen;
2. eine Modules-Datei einzuspielen, die das Feature _userroles_ temporär oder dauerhaft aktiviert hat.

Bei aktiver Userrollen-Funktionalität wird für den angemeldeten User ein Eintrag im Eigenschaftsbaum erzeugt.
Die dabei für die Rechteverwaltung verwendeten Defaulteinstellungen
entsprechend den "klassischen" Vorgaben für einen Adminitrator,
d.h. zunächst werden dem User keine Einschränkungen auferlegt. Z.B. für einen User _admindepot1_
werden die Einträge

[source,prompt]
----
user.{admindepot1}.privilege.host.all.registered_readonly	[false]
user.{admindepot1}.privilege.host.depotaccess.configured	[false]
user.{admindepot1}.privilege.host.depotaccess.depots		[]
user.{admindepot1}.privilege.host.opsiserver.write		[true]
----

generiert.

Die vier Einträge bedeuten:

- _admindepot1_ hat _nicht_ lediglich readonly-Zugriff auf den Server (ein reiner readonly-Zugriff wäre möglicherweise für einen Mitarbeiter aus dem Helpdesk-Bereich angemessen);
- Depotrestriktionen existieren nicht bzw. werden nicht berücksichtigt;
- entsprechend kann die Liste der für den User zugänglichen Depots leer bleiben
(aber auch wenn hier eine Auswahl aus den verfügbaren eingetragen ist, hat dies, solange _depotaccess.configured  false_, keine Wirkung);
- der User darf configserver-Einstellungen aller Art bearbeiten.

Soll künftig _admindepot1_ nur noch Zugriff auf die Rechner im Depotserver _depot1_ haben, ist folgendes einzustellen:

- _host.depotaccess.configured_ ist auf _true_ zu setzen;
- in die Liste _host.depotaccess.depots_ ist der Wert "depot1" einzutragen.

Nach einem (vollständigen) Datenreload sind für den User _admindepot1_ keine Clients aus anderen Depots mehr sichtbar
(und auch nur noch Depoteinstellungen für _depot1_ zugänglich).

WARNING:  _admindepot1_ kann alle Restriktionen selbst aufheben, solange er über das Privileg _host.opsiserver.write_ verfügt.

Um die Abriegelung komplett zu machen, ist daher für _admindepot1_ noch

- _host.opsiserver.write_ auf _false_ zu stellen.



WARNING: Die auf diese Weise gesetzten Privilegien beschränken ausschließlich die Funktionalität des _opsi-configed_.
Bei anderen Zugriffsmethoden auf das JSON-RPC-Interface des opsi-servers werden sie derzeit nicht wirksam.
