////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      20.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-manual-wan-faq]]
= FAQ zur Einrichtung und Verwendung der WAN-Erweiterung

[[opsi-faq-wan-manual-licenz]]
== Brauche ich eine Lizenz?

Ja die Erweiterung ist noch in der Kofinanzierung und somit kostenpflichtig. Zudem wird für den Betrieb der WAN-Erweiterung das MySql-Backend benötigt, welches ebenfalls kostenpflichtig ist. Sie können die Erweiterungen befristet kostenlos testen. Wenden Sie sich dazu per Mail an info@uib.de

[[opsi-faq-wan-manual-activate]]
== Wie aktiviere ich auf einem Client die WAN-Erweiterung?

Die Aktivierung der WAN-Erweiterung kann pro Client über das Kontrollkästchen in der Management-Console gesetzt werden. Die geänderte Konfiguration holt sich der Client bei der nächsten Verbindung zum opsi-Server. Aktiv wird sie dann nach dem nächsten Neustart des Client.

[[opsi-faq-wan-manual-activate-oca]]
== Muss für die Aktivierung der opsi-Client-Agent neu ausgerollt werden?

Nein, dass ist nicht notwendig, da der Client die Konfiguration bei der nächsten Verbindung zum opsi-Server automatisch bezieht. Das kann entweder der nächste Bootprozess oder ein "on_demand" Ereignis sein.

[[opsi-faq-wan-manual-activate-homeoffice]]
== Wie kann ich die Aktivierung bei Clients vornehmen die schon im Homeoffice sind?

Wenn die Clients sich auch im Homeoffice vom opsi-Server erreichen lassen, kann die Übertragung der Konfiguration über die Auslösung eines "on_demand" Events erfolgen. (Das funktioniert nur, wenn die Datenübertragung auf cifs eingestellt ist)

Für den Fall, dass sich die Clients im Homeoffice nicht vom opsi-Server erreichen lassen, können Sie über diesen opsi-admin Aufruf aktualisiert werden. (Das sollte auch bei Clients funktionieren die auf webdav umgestellt wurden)

Auf der Kommandozeile vom Server aus geht das mittels:

[source,shell]
----
opsi-admin -a https://<ClientIp>:4441/opsiclientd -u <user> -p <pass> method fireEvent "silent_install"

oder

opsi-admin -a https://<ClientIp>:4441/opsiclientd -u "<FQDN>" -p "<OpsiHostKey>" method fireEvent "silent_install"
----

Ersetzen Sie die Einträge entsprechend:

.  <ClientIp>    = IP-Adresse der Clients
.  <user>        = lokaler Administrator auf dem Client oder Mitglied der lokalen Administratorgruppe
.  <pass>        = Passwort des Administrators
.  <FQDN>        = FQDN des Clients
.  <OpsiHostKey> = opsi Hostkey des Clients

[[opsi-faq-wan-manual-cache]]
== Wie groß ist der Cache auf dem Client?

Der Cache auf dem Client ist im Standard auf 20 GB eingestellt. Hier werden die zu installierenden Programme und Updates gespeichert. Über einen sync-Prozess werden bei einem Update nur die geänderten Daten in das Cach-Verzeichnis kopiert. Die Größe des Caches sollte großzügig gewählt werden, damit auch umfangreiche Pakete gespeichert werden können.

[[opsi-faq-wan-manual-cachesize]]
== Wie kann ich die Größe vom Cache auf dem Client ändern?

Mit diesem Aufruf kann der Parameter an der Management-Console als Konfig eingetragen werden und anschließend der Wert für jeden Client individuell angepasst werden:

[source,shell]
----
opsi-admin -d method config_createUnicode "opsiclientd.cache_service.product_cache_max_size" "Maximum product cache size in bytes" "40000000000" "40000000000" "True" "False"
----

[[opsi-faq-wan-manual-time]]
== Wie kann ich die Zeit verlängern die der Client auf eine Rückantwort wartet, bevor er für eine Installation rebootet?

Mit diesem Aufruf kann der Parameter an der Management-Console als Konfig eingetragen werden und anschließend der Wert für jeden Client individuell angepasst werden:

[source,shell]
----
opsi-admin -d method config_createUnicode "opsiclientd.event_sync_completed{cache_ready_user_logged_in}.shutdown_warning_time" "Wie lange soll auf eine Antwort vor einem Reboot gewartet werden. Default 3600 Sekunden" "3600" "3600" "True" "False"
----

Wenn Sie die Zeit um 8 Stunden verschieben möchten tragen Sie hier 28000 Sekunden ein.

[[opsi-faq-wan-manual-ondemand]]
== Installationen "on_demand" im WAN Modus?

Die Installationen werden getriggert, als wäre es kein WAN-Client.

. Es wird direkt der Configserver angefragt.
. Die Installation startet ohne Caching direkt vom gemounteten Depot-Share.

[[opsi-faq-wan-manual-kiosk]]
== Funktioniert der Kiosk-Modus im WAN-Modus?

Der Kiosk funktioniert nur wenn der opsi-Konfigserver erreichbar ist. Auch im WAN-Modus arbeitet der Kiosk direkt auf dem opsi-Server.
Wenn die Anforderung zum Installieren eines Paketes nicht nur gespeichert, sondern auch direkt ausgeführt werden soll, erfolgt die Installation nach dem Standardmuster und nicht über den WAN-Modus, sprich die Pakete werden nicht gecached. Damit kann man den Kiosk schon auf einem WAN-Client nutzen, aber die eigentlichen WAN-Modus Kommponenten werden nicht genutzt.

[[opsi-faq-wan-manual-byshutdown]]
== Läßt sich der Install-by-shutdown-Modus mit dem WAN-Modus kombinieren?

Nein, das Installieren beim Herunterfahren des Rechners ist nicht mit der WAN-Erweiterung kompatibel.

[[opsi-faq-wan-manual-mshotfix]]
== Abo-Mshotfix und WAN-Modus

Grundsätzlich lassen sie die Mshotfix Pakete aus dem Abo auch auf WAN-Clients installieren. Es ist jedoch zu berücksichtigen, dass diese Standard-Pakete sehr groß (Bsp. Windows 10 64 Bit knapp 6GB) sind.

Aus diesem Grund werden für Windows 10 "modulare" Mshotfix-Pakete bereit gestellt, die nur die Patches für eine bestimmte ReleaseID beinhalten, wie z.B. mshotfix-win10-1809-x64-glb. Die Größe dieser "modularen" Pakete beträgt derzeit ca. 1 GB). Es wird daher angeraten diese "modularen" Pakete im WAN-Modus zu verwenden.

[[opsi-faq-wan-manual-cachedelete]]
== Wie kann ich den Cache auf dem Client löschen?

Im opsi-configed bei Clients über das Kontext-Menu "Wan-Clients Pakete Cache löschen", oder

[source,shell]
----
opsi-admin -a https://<ClientIp>:4441/opsiclientd -u "<FQDN des Client>" -p "OpsiHostKey" method "cacheService_deleteCache"
----

[[opsi-faq-wan-manual-user-login]]
== Können User-Login-Scripte im WAN-Modus verwendet werden?

Nein, das ergibt keinen Sinn, da diese im Moment des Login des Benutzers gestartet werden um Änderungen an roaming-Profiles vorzunehmen, die bei WAN-Clients nicht verwendet werden können. Der Eintrag im opsi-configed für opsiclientd.event_user_login.active sollte daher auf false gesetzt werden.
