////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      11.01.2021
:doctype: book

include::common:partial$opsi_terms.adoc[]

[[opsi-manual-opsiwebgui-instguide]]
= Installation guide

This chapter shows two ways to install the {opsi-webgui} on the config server: The installation via the opsi repository and via the admin interface. 
We recommend the first option, as it updates the webgui with every update of the installed system packages.

[[opsi-manual-opsiwebgui-installation-opsirepo]]
== Installation from the opsi repository

For the {opsi-webgui} installation from the opsi repository you need to specify the correct repository branch. 
After the installation of the webgui with the systems packagemanager you can visit the {opsi-webgui} at https://<configserver-address>:4447/addons/webgui/app

NOTE: Currently {opsi-webgui} is only available from the {release} or experimental branch.



*Example for Debian / Ubuntu* +
We recommend setting up an exception for the {opsi-webgui} (unless you have set the {release} branch as the main branch in `/etc/apt/sources.list.d/opsi.list`). +

. (Optional) Create a new file located in `/etc/apt/preferences.d/` e.g. `10-opsi-webexp` with following content:
+
--
[source]
----
# /etc/apt/preferences.d/10-opsi-webexp
Package: *
Pin: release l=home:uibmz:opsi:4.2:stable
Pin-Priority: 501

Package: opsi-webgui       
Pin: release l=home:uibmz:opsi:4.2:testing
Pin-Priority: 502
---- 

The content tells the system to get all packages from the stable repository if available. 
For the {opsi-webgui}, the testing repository also applies.

--


. Install the {opsi-webgui} with
+
--

[source, prompt]
----
sudo apt update
sudo apt install opsi-webgui
sudo opsiconfd restart
---- 

To update the {opsi-webgui} the following command can be used: 

[source, prompt]
----
sudo apt update
sudo apt upgrade opsi-webgui
----

--

[[opsi-manual-opsiwebgui-installation-admininterface]]
== Installation through admininterface using ZIP-file
Installation via the admin interface works regardless of the system used.
However, since there is only _one_ installation, updates have to be installed manually (unless the correct repository is set up).

To install with opsi-webgui.zip, proceed as follows: +

. Download the latest version {opsi-webgui} (ZIP file) from https://download.uib.de/opsi4.2/{release}/opsiconfd-addons/ .
. Go to https://<configserver-address>:4447/admin/#addons. 
. Upload the file and press the *[Install addon]* button.
