////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      11.01.2021
:doctype: book



[[opsi-manual-opsiwebgui-technology]]
= Technology stack

The opsi-webgui is built as an opsiconfd addon and it is stored in the directory `/var/lib/opsiconfd/addons/webgui` on the configserver.

The backend of the webgui is built using FastAPI, a Python framework, and is responsible for reading and writing data from the MySQL database.
To significantly improve performance, the backend interacts directly with the database, which requires the MySQL extension.
In addition, communication also takes place with the opsiconfd for session handling and logging.

The frontend is developed using Nuxt, a Vue.js framework.
It makes requests to the backend, retrieves and displays data.
