////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      04.07.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

[[opsi-manual-opsiwebgui-troubleshooting]]
= Troubleshooting

This chapter describes possible problems with the WebGUI and provides tips for solving them.

[[opsi-manual-opsiwebgui-troubleshooting-emptyconfigserver]]
== Empty opsi Config Server ID

If the top field remains empty and does not display the ID of the opsi config server, you may have lost access to the config server or the `opsiconfd` service.

Possible solutions:

* Open the admin page at `https://<opsi-server>:4447/admin` in your browser, log in, and verify/accept the SSL certificate if necessary.

* Restart the `opsiconfd` service, for example, with this command:

[source,console]
----
systemctl restart opsiconfd.service
----

TIP: For more information about the `opsiconfd` service, its command-line interface, and the admin page, see chapter xref:server:components/opsiconfd.adoc[*opsiconfd* Service].

== Blank Page Content

If the navigation bar on the left and top edge is visible, but the display remains otherwise blank, your session may have expired. Reload the page, e.g., with the key combination [Ctrl]{plus}[F5]; this will also clear the page cache. Alternatively, open a new tab in your browser and open the WebGUI there.
