////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

////
;***************************************************************************
; Subversion:
; $Revision:  $ $Author: oertel $
; $Date: $
;***************************************************************************
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.0.6
:doctype:   book

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]

= opsi Version 4.0.6 Release Notes

// Include common opsi copyright
include::../common/opsi_manual_copyright.asciidoc[]

[[opsi-406-releasenotes-overview]]
== Übersicht der Neuerungen

Das opsi Service Releases 4.0.6 weist eine Fülle von Neuerungen und Detailverbesserungen auf. Hier eine Übersicht:

* Ab opsi 4.0.6 werden (ausschließlich) folgende Distributionen als opsi-server unterstützt: +
** Ubuntu: 10.04 (Lucid), 12.04 (Precise), 14.04 (Trusty)
** Debian: 6.0 (Squeeze), 7.0 (Wheezy)
** UCS 3.2
** openSUSE 12.3, 13.1
** SLES 11SP3
** RHEL 6.6, 7
** CentOS 6.5, 7

Sollten Sie opsi auf einer Betriebssystemversion einsetzen, welche oben nicht aufgeführt ist,
so empfehlen wir Ihnen ein Betriebsystem-Update bevor Sie opsi v4.0.6 einspielen.


* opsi Serverkomponenten: +
Diverse Verbesserungen und Bugfixes in den Serverpaketen.

* Neues opsi-bootimage basierend auf Ubuntu Precise / Kernel 3.15.1 mit Unterstützung für aktuelle Hardware 

* Windows Netboot Produkte +
** winpe Partition jetzt NTFS formatiert

* opsi-winst / opsi-script (4.11.5.1): +

** Kommandos für Hardlinks, Symbolische Links, Rename und Move in Files Sektionen

** For-To Schleife

** Switch / Case Statement

** Neue Stringlistfunktionen: `removeFromList` und `removeListFromList`

** Upgrade der SSL Libraries auf 1.0.1L

** Neues Statement `UpdateEnvironment`. Aufruf von UpdateEnvironment fordert Windows auf die Umgebungsvariablen aus der Registry neu einzulesen

** Siehe auch gesondertes Kapitel.

* Linux Netboot Produkte:

** Die neue Generation der Linux Netbootprodukte arbeitet mit dem Orginal Installer der Distribution und einer entsprechenden Antwortdatei.

** Produkte auf dieser Basis gibt es für: SLES12, Ubuntu14-04, Debian7, Debian8

** Siehe auch gesondertes Kapitel.


* opsi-configed: +

** ########

* opsi-client-agent: +
** update auf opsi-winst 4.11.5


////
Für Details lesen Sie bitte das opsi-v405-releasenotes Handbuch bzw. die überarbeiteten opsi Handbücher.
////

[[opsi-406-releasenotes-knownbugs]]
== Known Bugs / Known Problems


.KNOWN BUGS:

* ######

.KNOWN PROBLEMS:

* ######

[[opsi-406-releasenotes-eol]]
== Abkündigung

In diesem Kapitel werden die Abkündigungen aufgelistet. Diese Distributionsversionen werden aus verschiedenen Gründen nicht mehr weiter von opsi unterstützt.

[[opsi-406-releasenotes-eol_windows]]
=== Abkündigung: Windows Versionen

Ab opsi v 4.0.5 werden wir die Netbootpakete für Windows Vista und Server 2008 nicht mehr weiter pflegen. Ebenso planen wir für diese Windowsversionen die Unterstützung in den Update Abo's einzustellen. Wer hierzu Fragen oder Probleme hat möge sich bei uns melden.

Windows XP / Server 2003 ist bekanntermaßen von Microsoft nicht mehr (bzw. Windows 2003 eingeschränkt) unterstützt. Wir werden, wegen der weiten Verbreitung, diese Pakete noch eine Zeitlang pflegen. Trotzdem kündigen wir auch hier an, diese Pflege in absehbarer Zeit einzustellen und empfehlen Ihnen dringend den Wechsel auf eine neuere Windows Version (oder Linux).

[[opsi-406-releasenotes-installation]]
== Hinweise zur Installation

Wir empfehlen vor der Installation des Updates (sicherheitshalber) mit opsi-backup eine Sicherung Ihres Backends durchzuführen:
[source,prompt]
----
opsi-backup create
----


Die Produkte welche im Rahmen dieses Releases veröffentlicht werden, sind in etlichen Teilen voneinander abhängig. Sie sollten daher nicht versuchen nur Teile zu installieren.

Sie sollten dabei zuerst den Server updaten und danach die opsi-Produkte.

Beim Update eines bestehenden opsi-Servers kann es vorkommen, dass eine neue Version `/etc/opsi/opsi.conf` eingespielt werden kann und der Paketmanager Ihres Systems Sie fragt, wie vorgegangen werden soll.
Falls eine solche Nachfrage kommt und Sie diese Datei nicht geändert haben, so können Sie diese Datei gefahrlos durch die neue Version ersetzen.
Falls Sie die Datei geändert haben oder sich unsicher sind, verweigern Sie das Ersetzen bitte.

Wie oben beschrieben könnte ebenso eine neue Version der `/etc/opsi/opsi-product-updater.conf` für ein Update vorgeschlagen werden. 
In der neuen Version kann jetzt ein Smtp-Benutzer mit Smtp-Passwort für die Authentifizierung eingetragen werden, falls dies benötigt wird. Zudem wurde der Eintrag
für die Exclude-Files entfernt (exclude = ^win* ), was dazu führen wird, dass die Windows-Netbootprodukte von der Aktualisierung nicht mehr ausgeschlossen werden. 

Wir empfehlen nach dem Update die Ausführung von ``opsi-setup --set-rights``, um sicher zu stellen, dass die Berechtigungen in den verwendeten Ordnern korrekt sind. Die Ausführung des Befehls kann mehrere Minuten in Anspruch nehmen.

[[opsi-406-releasenotes-aktualisierung-opsivm]]
=== Hinweise zur Aktualisierung der opsi server vm Version 4.0.4

Beim Aktualisieren des 'opsi-depotserver' Paketes kann es sein, dass Sie die Daten für das SSL-Zertifikat erneut eingeben müssen.

[[opsi-406-releasenotes-installation-rhel-centos]]
=== Hinweise zur Aktualisierung unter RHEL / CentOS

Ab Version 4.0.5 wird python-opsi keine Abhängigkeit mehr auf 'python-mysql' haben, sondern das in den Standard-Repositories befindliche 'MySQL-python' verwenden.

Bei der Aktualisierung von opsi kann es dadurch zu Konflikten kommen. Um das zu vermeiden, entfernen Sie bitte vorher 'python-mysql':

[source,prompt]
----
rpm -e --nodeps python-mysql
----


[[opsi-406-releasenotes-installation-opsipackages]]
=== Hinweise zum Aktualisieren von opsi-Paketen

////
Bitte nachstehenden Block bei release nicht löschen sondern auskommentieren
////

Zur Installation der testing Serverpakete müssen Sie das opsi Repository ändern von `opsi40` auf `opsi40-testing`. +
Zum Beispiel bei Ubuntu 12.04: +
`deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/opsi40/xUbuntu_12.04 ./` +
ersetzen durch: +
`deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/opsi40-testing/xUbuntu_12.04 ./`

Danach müssen Sie Ihre Pakete updaten. +
Zum Beispiel bei Ubuntu / Debian:
[source,prompt]
----
aptitude update
aptitude full-upgrade
----

Zur Installation der testing opsi Produkte
`/etc/opsi/opsi-product-updater.conf`

[source,prompt]
----
[repository_opsi_406_testing]
baseUrl = http://download.uib.de
dirs = dirs = opsi4.0/testing/opsi-v406/products/localboot, opsi4.0/testing/opsi-v406/products/netboot, opsi4.0/testing/opsi-v405/opsi-linux
active = true
username = 
password = 
autoInstall = false
autoUpdate = true
autoSetup = false
onlyDownload = false 
----

in der Sektion `[repository_uib]` folgende Zeile zu setzen:
[source,prompt]
----
active = false
----
Danach rufen sie den opsi-product-updater auf.
Um alle Pakete zu installieren:
[source,prompt]
----
opsi-product-updater -i -vv
----

Um nur Updates zu installieren:
[source,prompt]
----
opsi-product-updater -vv
----

////
Bitte vorstehenden Block bei release nicht löschen sondern auskommentieren
////

////
Die Installation erfordert keine besonderen Arbeiten. Sie erfolgt im Rahmen der normalen Updates ihres Servers und der opsi-Produkte.

Sie sollten dabei zuerst den Server updaten. Benutzen Sie dazu die Befehle entsprechend Ihrer Linux-Distribution. +

Wir empfehlen in der Datei `/etc/opsi/opsi-product-updater.conf` 
in der Sektion `[repository_uib]` den Eintrag `excludes` wie folgt zu modifizieren, damit Sie auch Produkte bekommen welche mit `win*` anfangen::
[source,prompt]
----
excludes =
----

Wenn Sie die  opsi-linux Produkte benötigen so hängen Sie an den  `dirs` Eintrag: +

[source,prompt]
----
dirs = opsi4.0/products/localboot, opsi4.0/products/netboot
----
den Pfad `opsi4.0/products/opsi-linux` an.

Wenn Sie die  opsi-local-image Produkte benötigen so hängen Sie an den  `dirs` Eintrag den Pfad `opsi4.0/products/opsi-local-image` an.

Danach die opsi-Produkte. Dies erledigt der opsi-product-updater:

[source,prompt]
----
opsi-product-updater -i -vv
----

Um nur Updates zu installieren:
[source,prompt]
----
opsi-product-updater -vv
----

Sollten Sie eine Multidepot Umgebung haben, so machen Sie zunächst das Upgrade auf Ihrem config-server, bevor Sie die Depots upgraden.

Falls Sie Produkt-IDs mit einer Länge von mehr als 32 Zeichen verwenden wollen und das MySQL-Backend einsetzen, so führen Sie bitte ein Update der Tabellen-Definition auf Ihrem Config-Server mittels opsi-setup durch:


[source,prompt]
----
opsi-setup --update-mysql
----
////

[[opsi-script]]
== opsi-script / opsi-winst 4.11.5.1

** In Files Sektionen:

*** `hardlink` <existing file> <new file> // since 4.11.5 [W/L]

*** `symlink` <existing file> <new file> // since 4.11.5 [W/L]

*** `rename` <old filename> <new filename> // since 4.11.5 [W/L]

*** `move` <old filename> <new filename> // since 4.11.5 [W/L]

Example: 
[source,winst]
----
[Files_link_move]
del "$HomeTestFiles$\files\hardlink.txt"
hardlink "$HomeTestFiles$\files\dummy.txt" "$HomeTestFiles$\files\hardlink.txt"
del "$HomeTestFiles$\files\symlink.txt"
symlink "$HomeTestFiles$\files\dummy.txt" "$HomeTestFiles$\files\symlink.txt"
del "$HomeTestFiles$\files\temp\rename.txt"
del "$HomeTestFiles$\files\temp\move.txt"
copy "$HomeTestFiles$\files\dummy2.txt" "$HomeTestFiles$\files\temp\"
rename "$HomeTestFiles$\files\temp\dummy2.txt" "$HomeTestFiles$\files\temp\rename.txt"
copy "$HomeTestFiles$\files\dummy2.txt" "$HomeTestFiles$\files\temp\"
move "$HomeTestFiles$\files\temp\dummy2.txt" "$HomeTestFiles$\files\temp\move.txt"
----

** For-To Schleife:

Syntax:

`for` %<temporary string variable>% `=` <start string> ` to ` <end string> `do` <one statement //since 4.11.5 [W/L]

Example: 
[source,winst]
----
for %s% = "1" to "5" do sub_iteration_test`
----

** Switch / Case Statement:

Syntax:

`Switch` <string expression> +
  `Case` <string const>
    <statement(s)> +
   `EndCase` +
   [`DefaulCase` +
    ;statement(s) +
       `EndCase` ] +
`EndSwitch`


Example:
[source,winst]
----
set $ConstTest$ = "5"
Switch $ConstTest$
	Case "1"
		set $CompValue$ = "1"
	EndCase
	Case "2"
		set $CompValue$ = "2"
	EndCase
	Case "3"
		set $CompValue$ = "3"
	EndCase
	Case "4"
		set $CompValue$ = "4"
	EndCase
	Case "5"
		set $CompValue$ = "5"
	EndCase
	Case "6"
		set $CompValue$ = "6"
	EndCase
	Case "7"
		set $CompValue$ = "7"
	EndCase
	DefaultCase
		set $CompValue$ = "notexisting"
	EndCase
EndSwitch
if ($ConstTest$ = $CompValue$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif
----.



[[opsi-configed]]
== opsi-configed 4.0.6.


[[opsi-406-releasenotes-bootimage]]
== opsi-linux-bootimage

include::../common/opsi_manual_linux.asciidoc[]


[[opsi-406-releasenotes-misc]]
== Sonstiges

[[opsi-406-releasenotes-misc-changelogs]]
=== Changelogs:


[[opsi-406-releasenotes-misc-changelogs-opsi-configed]]
==== Changelog opsi-configed
////
opsi-configed (4.0.5.1.2-1) testing; urgency=low
////

[[opsi-406-releasenotes-misc-changelogs-opsi-client-agent]]
==== Changelog opsi-client-agent

////
opsi-client-agent (4.0.5.1-8) stable; urgency=low
////

[[opsi-406-releasenotes-misc-changelogs-opsi-script]]
==== Changelog opsi-script / opsi-winst

////
opsi-winst/opsi-script (4.11.4.10) stable; urgency=low
////


[[opsi-406-releasenotes-misc-changelogs-windows-netboot]]
==== Changelog windows netboot products

////
windows (4.0.5-4) stable; urgency=low
////

[[opsi-406-releasenotes-misc-changelogs-linux-netboot]]
==== Changelog linux netboot products
////
*Debian*

debian-4.0.5-4 stable; urgency=low

*Ubuntu*

ubuntu-4.0.5-7 testing; urgency=low

*openSUSE*

opensuse13-1_13.01-6 stable; urgency=low

opensuse12-3_12.03-5 stable; urgency=low

*sles11sp3*

*centos65*

centos65_6.5-3 testing; urgency=low

*Fedora 20*

fedora_20_20-4 stable; urgency=low
////

[[opsi-406-releasenotes-misc-changelogs-opsi-local-image]]
==== Changelog opsi-local-image

////
*opsi-local-image-backup*

opsi-local-image-win* (4.0.5.1-3) stable; urgency=low

*opsi-local-image-capture*

opsi-local-image-capture (4.0.5.1-5) stable; urgency=low


*opsi-local-image-delimage*


*opsi-local-image-prepare*

opsi-local-image-win* (4.0.5.1-3) stable; urgency=low

*opsi-local-image-restore*

opsi-local-image-restore (4.0.5.1-2) stable; urgency=low

*opsi-local-image-sysprep*

opsi-local-image-sysprep (4.0.5.1-1) stable; urgency=low

*opsi-local-image-win**

opsi-local-image-win* (4.0.5.1-6) stable; urgency=low

*opsi-local-image-ubuntu*

opsi-local-image-ubuntu (4.0.5.1-1) stable; urgency=low
////

[[opsi-406-releasenotes-misc-changelogs-python-opsi]]
==== Changelog python-opsi

////
python-opsi (4.0.5.15-1) experimental; urgency=low
////

[[opsi-406-releasenotes-misc-changelogs-opsipxeconfd]]
==== Changelog opsipxeconfd
////
opsipxeconfd (4.0.5.3-6) experimental; urgency=low
////

[[opsi-406-releasenotes-misc-changelogs-opsiconfd]]
==== Changelog opsiconfd
////
opsiconfd (4.0.5.2-1) experimental; urgency=low
////

[[opsi-406-releasenotes-misc-changelogs-opsi-utils]]
==== Changelog opsi-utils
////
opsi-utils (4.0.5.6-2) experimental; urgency=low
////

[[opsi-406-releasenotes-misc-changelogs-opsi-linux-bootimage]]
==== Changelog opsi-linux-bootimage
////
opsi-linux-bootimage (20140919-2) stable; urgency=medium
////

[[opsi-406-releasenotes-misc-changelogs-opsi-depotserver]]
==== Changelog opsi-depotserver
////
opsi-depotserver (4.0.5.11-1) experimental; urgency=low
////

[[opsi-406-releasenotes-misc-changelogs-opsi-atftp]]
==== Changelog opsi-atftp
////
opsi-atftp (0.7.dfsg-4) stable; urgency=medium
////


[[opsi-406-releasenotes-misc-changelogs-opsi4ucs]]
==== Changelog opsi4ucs
////
opsi4ucs (4.0.5.5-4) experimental; urgency=low
////

[[opsi-406-releasenotes-misc-changelogs-opsi-swaudit]]
==== Changelog opsi-swaudit
////
swaudit (4.0.5-1) stable; urgency=low
////

 [[opsi-406-releasenotes-misc-changelogs-opsi-template]]
==== Changelog opsi-template
////
opsi-template (4.0.5-1) stable; urgency=low
////

