////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

////
;***************************************************************************
; Subversion:
; $Revision:  $ $Author: oertel $
; $Date: $
;***************************************************************************
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.0.6
:doctype:   book

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]

= opsi Version 4.0.6 Release Notes

// Include common opsi copyright
include::../common/opsi_manual_copyright.asciidoc[]

[[opsi-406-releasenotes-supportmatrix]]
== opsi Support Matrix

Im folgenden finden Sie eine Übersicht auf welchen Plattformen opsi
als Server läuft.

include::../common/opsi_manual_supportmatrix.asciidoc[]


Sollten Sie den opsi-server auf einer Betriebssystemversion einsetzen, welche im vorigen Abschnitt nicht als Unterstützt aufgeführt ist,
so empfehlen wir Ihnen ein Betriebssystem-Update bevor Sie opsi v4.0.6 einspielen.

[[opsi-406-releasenotes-overview]]
== Übersicht der Neuerungen

Schwerpunkte dieser Freigabe sind:

* Windows 10 Support
* Neues opsi bootimage
* Neue opsi-linux netboot Produkte

Das opsi Service Releases 4.0.6 weist eine Fülle von Neuerungen und Detailverbesserungen auf. Hier eine Übersicht:


* Windows Netboot Produkte +
** Windows 10 Produkte
** winpe Partition jetzt NTFS formatiert (auf nicht UEFI Systemen)
Siehe auch gesondertes Kapitel: <<opsi-406-releasenotes-win10notes>>.

* Neues opsi-bootimage basierend auf Ubuntu Trusty / Kernel 4.1.0 mit Unterstützung für aktuelle Hardware


* opsi-configed: 

** Der opsi-configed kann jetzt seine Tabellen auch als PDF-Exporte für einen PDF-Viewer zur Verfügung stellen oder als 
Datei exportieren.

** Auf der Seite Hardwareinformationen des opsi-configed wird ein automatisierter Weg für die PC-spezifische Treiberintegration angeboten. 
Der ByAudit-Treiberpfad wird entsprechend den Anforderungen des Bootimages erzeugt und auf Wunsch angelegt. Anschließend 
können die Treiberdateien auch mittels des opsi-configed direkt auf den Konfigserver kopiert werden, wo dann auch die Dateizugriffsrechte korrekt 
gesetzt werden.

** Es sind an diversen Stellen optimierte Datenzugriffe für das MySQL-Backend implementiert.

** Auf den Logging-Seiten ist die Suchfunktion in mehrfacher Hinsicht verbessert. Insbesondere startet die Suche jetzt an der Cursor-Position (und nicht bei jedem Aufruf von vorne), Suchstrings werden in einer Combobox zwischengespeichert.

** Auf der Software-Inventur-Seite wird jetzt eine Suchfunktion für die Tabelle angeboten. Außerdem kann gewählt werden, ob die MS-Updates ausgeblendet werden (Default Ausblendung).

** In der Lizenzstatistik war ein tief versteckter Bug, der unter gewissen Umständen dazu geführt hat, dass die Zählung der verfügbaren Lizenzen zu niedrig angesetzt war. Das ist behoben.

* opsi-client-agent: +

** Überarbeitetes Script `opsi-deploy-client-agent`. +
Damit es ist einfach möglich zur Verteilung mit einer IP-Adresse zu
arbeiten. +
Außerdem wurde die Möglichkeit zum Kopieren der Dateien auf `mount` zurück +
zu greifen wieder eingeführt. +
Das Script wird selbstständig ermitteln welche Art von Adresse übergeben
wird. Zur manuellen Bestimmung, stehen Parameter bereit.

** Feature zur Steuerung von den Paketen, die für die einzelnen Events freigeschaltet oder ausgeschlossen werden sollen, über den configed mit den Produktgruppen.

** Neues Property `depends_on_service`: +
Dies ist eine Liste von Diensten welche laufen müssen bevor der opsiclientd gestartet wird. Der Default ist: `Dhcp, Dnscache` +
Achtung: Änderungen an diesem Property können leicht dazu führen, dass der opsiclientd nicht mehr startet.

** Neues Property `setup_after_install`: +
Dies ist eine Liste von opsi Produkten welche auf setup gestellt werden wenn der opsi-client-agent installiert ist.

* python-opsi:

** Zahlreiche Verbesserungen und Features in der Python-Library von opsi +
Siehe auch gesondertes Kapitel: <<opsi-406-releasenotes-python-opsi>>

* Neuer optionaler config: `clientconfig.depot.user` zur Angabe von `domain\user` für pcpatch +
Siehe auch gesondertes Kapitel: <<opsi-manual-samba4>>.

* opsi-winst / opsi-script (4.11.5.13) (aus 4.0.5): +

** Files Kommandos für Hardlinks, Symbolische Links, Rename und Move in Files Sektionen

** For-To Schleife

** Switch / Case Statement

** Neue Stringlistfunktion: `removeFromListByContaining`

** Neue Stringlistfunktion: `LoadTextFileWithEncoding(` <file name> `,` <encoding>`)`

** Neue Stringfunktion `unquote2(<string>,<quote-string>)`

** Neue Stringfunktion `GetShortWinPathName(<longpath string>)`

** Neue Stringfunktion `GetConfidentialProductProperty (` <PropertyName>, <DefaultValue>`)`

** Neue boolean Funktion `CompareDotSeparatedNumbers(<str1>, <relationstr>, <str2>)`

** Neue boolean Funktion `CompareDotSeparatedStrings(<str1>, <relationstr>, <str2>)`

** Neues Statement `UpdateEnvironment`. Aufruf von `UpdateEnvironment` fordert Windows auf die Umgebungsvariablen aus der Registry neu einzulesen (NT6 only)

** Files Kommando `del`: ACHTUNG verändertes Verhalten: Ähnlich wie schon beim copy Befehl: +
Wenn eine Datei in Benutzung ist, kann sie im Rahmen eines Reboots gelöscht werden. Das '{opsi-winst}/opsi-script' default-Verhalten ist dabei, dass ein Datei in Benutzung zum Löschen beim nächsten Reboot markiert wird UND die '{opsi-winst}/opsi-script' Reboot Markierung gesetzt wird. Das Setzen der Option `-c` stellt den automatischen Reboot aus. Das Löschen wird in diesem Fall erst dann vervollständigt, wenn ein Reboot auf eine andere Weise ausgelöst wird.

** Upgrade der SSL Libraries auf 1.0.2d, update des SSL Protokolls auf TLS autonegotiation

** Siehe auch gesondertes Kapitel: <<opsi-script>>.

* Linux Netboot Produkte:

** Die neue Generation der Linux Netbootprodukte arbeitet mit dem Orginal Installer der Distribution und einer entsprechenden Antwortdatei.

** Produkte auf dieser Basis gibt es für: SLES12, openSuse13-2, Ubuntu14-04, Debian7, Debian8, CentOS70, Redhat70

** Siehe auch gesondertes Kapitel: <<opsi-manual-linux>>.

[[opsi-406-releasenotes-packages]]
== Paketliste

.Server-Pakete:

* opsi-depotserver_4.0.6.4-1
* opsi-linux-support_1.0-4
* opsi-utils_4.0.6.6-2
* opsiconfd_4.0.6.6-1
* python-opsi_4.0.6.15-1
* opsi-linux-bootimage_20150818-1


.opsi-Pakete (Localboot):
* opsi-client-agent (4.0.6.2-1)

.opsi-Pakete (netboot):
* win* 4.0.6.1-1 (inclusive Windows 10 Pakete)
* opsi-clonezilla (4.0.6-1)
* memtest86 5.01-1

.opsi-Pakete (opsi-linux):
* centos70_4.0.6.2-1
* redhat70_4.0.6.2-1
* debian7-4.0.6-1
* debian8-4.0.6-1
* Ubuntu14-04_4.0.6-2
* Ubuntu15-04_4.0.6-2
* opensuse13-2_4.0.6.2-2
* sles12_4.0.6.2-2
* opsi-linux-client-agent ??????

.opsi-Pakete (opsi-local-image):
* opsi-local-image-win* 4.0.6.1-1



[[opsi-406-releasenotes-missing]]
== Was fehlt noch (und ist in Arbeit)

* opsi-client-agent: +
Die Möglichkeit im Rahmen 'User Profile Management' den opsi-winst komplett im Kontext des eingeloggten Users laufen zu lassen.

* opsi-linux-client-agent: +
Ein echter opsiclientd der auch 'pusch Installationen' ermöglicht.

* opsi-linux netboot Produkt Fedora22

* opsi-linux 4.0.6 netboot Produkte: uefi support

* opsi-clonezilla: uefi support


[[opsi-406-releasenotes-knownbugs]]
== Known Bugs / Known Problems


.KNOWN BUGS:

* ######

.KNOWN PROBLEMS:

* ######

[[opsi-406-releasenotes-eol]]
== Abkündigung

[[opsi-406-releasenotes-eol_server]]
=== Abkündigung: Distributionen für opsi-server


In diesem Kapitel werden die Abkündigungen aufgelistet. Diese Distributionsversionen werden aus verschiedenen Gründen nicht mehr weiter von opsi unterstützt.

* Univention Corporate Server: Die Versionen 3.0 und 3.1 sind von Univention abgekündigt und werden nicht mehr unterstützt.

* Debian 6 Squeeze

* Ubuntu Lucid 10.04

* OpenSuse 12.3

Siehe auch gesondertes Kapitel: <<opsi-406-releasenotes-supportmatrix>>.

[[opsi-406-releasenotes-eol_winclient]]
=== Abkündigung Clients: Windows Versionen

Ab opsi v 4.0.6 werden wir die Netbootpakete für 

* Windows 8 und 
* Server 2003 

nicht mehr weiter pflegen. Ebenso
planen wir für diese Windowsversionen die Unterstützung in den Update Abo’s einzustellen. Wer hierzu Fragen oder Probleme hat möge sich bei uns melden.

Siehe auch gesondertes Kapitel: <<opsi-406-releasenotes-netboot-windows>>.

[[opsi-406-releasenotes-eol_linclient]]
=== Abkündigung Clients: Linux Versionen

Ab opsi v 4.0.6 werden wir die Netbootpakete für 

* openSuse 12.3 
* Fedora20
* Ubuntu 10.04 (Lucid)
* Debian 6 (Squeeze)

nicht mehr weiter pflegen. Ebenso
planen wir für diese Windowsversionen die Unterstützung in den Update Abo’s einzustellen. Wer hierzu Fragen oder Probleme hat möge sich bei uns melden.

Siehe auch gesondertes Kapitel: <<opsi-manual-linux>>.

[[opsi-406-releasenotes-installation]]
== Hinweise zur Installation

Wir empfehlen vor der Installation des Updates (sicherheitshalber) mit opsi-backup eine Sicherung Ihres Backends durchzuführen:
[source,prompt]
----
opsi-backup create
----


Die Produkte welche im Rahmen dieses Releases veröffentlicht werden, sind in etlichen Teilen voneinander abhängig. Sie sollten daher nicht versuchen nur Teile zu installieren.

Sie sollten dabei zuerst den Server updaten und danach die opsi-Produkte.

Beim Update eines bestehenden opsi-Servers kann es vorkommen, dass eine neue Version `/etc/opsi/opsi.conf` eingespielt werden kann und der Paketmanager Ihres Systems Sie fragt, wie vorgegangen werden soll.
Falls eine solche Nachfrage kommt und Sie diese Datei nicht geändert haben, so können Sie diese Datei gefahrlos durch die neue Version ersetzen.
Falls Sie die Datei geändert haben oder sich unsicher sind, verweigern Sie das Ersetzen bitte.

Wie oben beschrieben könnte ebenso eine neue Version der `/etc/opsi/opsi-product-updater.conf` für ein Update vorgeschlagen werden. 
In der neuen Version kann jetzt ein Smtp-Benutzer mit Smtp-Passwort für die Authentifizierung eingetragen werden, falls dies benötigt wird. Zudem wurde der Eintrag
für die Exclude-Files entfernt (exclude = ^win* ), was dazu führen wird, dass die Windows-Netbootprodukte von der Aktualisierung nicht mehr ausgeschlossen werden. 

Wir empfehlen nach dem Update die Ausführung von ``opsi-setup --set-rights``, um sicher zu stellen, dass die Berechtigungen in den verwendeten Ordnern korrekt sind. Die Ausführung des Befehls kann mehrere Minuten in Anspruch nehmen.


[[opsi-406-releasenotes-installation-opsipackages]]
=== Hinweise zum Aktualisieren von opsi-Paketen (Testing)

////
Bitte nachstehenden Block bei release nicht löschen sondern auskommentieren
////

Zur Installation der testing Serverpakete müssen Sie das opsi Repository ändern von `opsi40` auf `opsi40-testing`. +
Zum Beispiel bei Ubuntu 14.04: +
`deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/opsi40/xUbuntu_14.04 ./` +
ersetzen durch: +
`deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/opsi40-testing/xUbuntu_14.04 ./`

Danach müssen Sie Ihre Pakete updaten. +
Zum Beispiel bei Ubuntu / Debian:
[source,prompt]
----
aptitude update
aptitude full-upgrade
----

Zur Installation der testing opsi Produkte
fügen Sie in die Datei +
`/etc/opsi/opsi-product-updater.conf` +
folgende Sektion ein:

[source,prompt]
----
[repository_opsi_406_testing]
baseUrl = http://download.uib.de
dirs = opsi4.0/testing/opsi-v406/products/localboot, opsi4.0/testing/opsi-v406/products/netboot
active = true
username =
password =
autoInstall = false
autoUpdate = true
autoSetup = false
onlyDownload = false
----

Hängen Sie je nach Bedarf an die `dirs` Zeile noch an:

* `, opsi4.0/testing/opsi-v406/opsi-linux`

* `, opsi4.0/testing/opsi-v406/opsi-local-image`

////
[repository_opsi_406_experimental]
baseUrl = http://download.uib.de
dirs = opsi4.0/experimental/opsi-v406/products/localboot, opsi4.0/experimental/opsi-v406/products/netboot, opsi4.0/experimental/opsi-v406/products/opsi-linux
active = true
username =
password =
autoInstall = false
autoUpdate = true
autoSetup = false
onlyDownload = false
----
////

Setzen Sie in der Sektion `[repository_uib]` folgende Zeile:
[source,prompt]
----
active = false
----
Danach rufen sie den opsi-product-updater auf.
Um alle Pakete zu installieren:
[source,prompt]
----
opsi-product-updater -i -vv
----

Um nur Updates zu installieren:
[source,prompt]
----
opsi-product-updater -vv
----

////
Bitte vorstehenden Block bei release nicht löschen sondern auskommentieren
////

////
Die Installation erfordert keine besonderen Arbeiten. Sie erfolgt im Rahmen der normalen Updates ihres Servers und der opsi-Produkte.

Sie sollten dabei zuerst den Server updaten. Benutzen Sie dazu die Befehle entsprechend Ihrer Linux-Distribution. +

Wir empfehlen in der Datei `/etc/opsi/opsi-product-updater.conf`
in der Sektion `[repository_uib]` den Eintrag `excludes` wie folgt zu modifizieren, damit Sie auch Produkte bekommen welche mit `win*` anfangen::
[source,prompt]
----
excludes =
----

Wenn Sie die  opsi-linux Produkte benötigen so hängen Sie an den `dirs` Eintrag: +
den Pfad `opsi4.0/products/opsi-linux` an.

Wenn Sie die  opsi-local-image Produkte benötigen so hängen Sie an den  `dirs` Eintrag den Pfad `opsi4.0/products/opsi-local-image` an.

Danach die opsi-Produkte. Dies erledigt der opsi-product-updater:

[source,prompt]
----
opsi-product-updater -i -vv
----

Um nur Updates zu installieren:
[source,prompt]
----
opsi-product-updater -vv
----

Sollten Sie eine Multidepot Umgebung haben, so machen Sie zunächst das Upgrade auf Ihrem config-server, bevor Sie die Depots upgraden.

Falls Sie Produkt-IDs mit einer Länge von mehr als 32 Zeichen verwenden wollen und das MySQL-Backend einsetzen, so führen Sie bitte ein Update der Tabellen-Definition auf Ihrem Config-Server mittels opsi-setup durch:


[source,prompt]
----
opsi-setup --update-mysql
----
////

[[opsi-406-releasenotes-win10notes]]
== Hinweise zur Nutzung von Windows 10

[[opsi-406-releasenotes-win10notes-detect]]
=== Windows 10 Erkennung

Die opsi-winst Funktion `getMsVersionInfo` liefert bei Windows 8.1 den Wert 6.3
und bei Windows 10 den Wert '10.0'. Dies ist etwas verwirrend, zumal Windows 10 von der Architektur doch sehr nach NT6 aussieht. +
Wichtig ist dies aber vorallem bei der Unterscheidung zwischen NT5 und NT6.

Zum Vergleich von getMsVersionInfo mit einem String wie "6.0" dürfen Sie nicht einen Stringvergleich mit `<` oder `=` oder `>` verwenden, da der String "10" kleiner ist als der Sting "6" da 1 kleiner ist wie 6.

Richtig ist die Verwendung folgender Methode:

[source,winst]
----
if CompareDotSeparatedNumbers(getMsVersionInfo,"6.0") < "0"
  comment "We are on NT5"
else
  comment "We are on NT6"
endif
----

Ab opsi-winst 4.11.5 können Sie das auch lesbarer schreiben

[source,winst]
----
if CompareDotSeparatedNumbers(getMsVersionInfo, "<", "6.0")
  comment "We are on NT5"
else
  comment "We are on NT6"
endif
----

[[opsi-406-releasenotes-win10notes-helper]]
=== Windows 10 Hilfsprodukte

Zum Arbeiten mit Windows 10 insbesondere im Desktopbetrieb seien Ihnen folgende Produkte empfohlen:

* classic_shell: +
http://download.uib.de/opsi4.0/products/contribute/full-package/classic-shell_4.2.1-1.opsi

* config-win81-desktop: +
http://download.uib.de/opsi4.0/products/contribute/full-package/config-win81-desktop_4.0.5-3.opsi



include::../common/opsi_manual_samba4.asciidoc[]

include::../common/opsi_manual_linux.asciidoc[]

[[opsi-script]]
== opsi-script / opsi-winst 4.11.5

* Security Upgrade zu Windows SSL Libraries 1.0.2d (libeay32.dll, ssleay32.dll) +
Update des SSL Protokolls auf TLS autonegotiation

.In Files Sektionen:

* `hardlink` <existing file> <new file> // since 4.11.5 [W/L] +
Ein existierender <new file> wird überschrieben. +
`hardlink` funktioniert nur auf Filesystemen die Hardlinks unterstützen
wie NTFS und Standard Linux Filesysteme.

* `symlink` <existing file> <new file> // since 4.11.5 [W/L] +
Unter Windows ist `symlink` erst ab NT6 und aufwärts verfügbar ! +
Ein existierender <new file> wird überschrieben. +

* `rename` <old filename> <new filename> // since 4.11.5 [W/L] +
`move` <old filename> <new filename> // since 4.11.5 [W/L] +
Es gibt keine Unterschiede zwischen `rename` und `move`, es sind zwei Namen für die selbe Funktion +
Ein existierender <new file> wird überschrieben. +
 +
Windows: <new filename> darf in einem anderen Directory liegen oder auch in einem anderen Volume / Disk. Im zweiten Fall, wird die Datei kopiert und danach das Original gelöscht. +
Läßt sich das Ziel nicht erstellen (Datei in Verwendung) so wird die Operation beim nächsten Reboot fertiggestellt. Das funktioniert natürlich nur wenn das Zielfilesystem zum Reboot-Zeitpunkt verfügbar ist, also nicht auf Netzwerkshares. In diesem Fall wird auch automatisch ein Reboot nach dem Ende des Scriptes ausgelöst. Dies läst sich aber mit der Option `-c` (continue) unterdrücken. +
Die Erstellung von Junctions unter Windows wird noch nicht unterstützt. +
 +
Linux: <new filename> darf in einem anderen Directory liegen aber nicht in einem anderen Filesystem / Partition. Die Option `-c` wird unter Linux ignoriert. +
 +
Example: 
[source,winst]
----
[Files_link_move]
del "$HomeTestFiles$\files\hardlink.txt"
hardlink "$HomeTestFiles$\files\dummy.txt" "$HomeTestFiles$\files\hardlink.txt"
del "$HomeTestFiles$\files\symlink.txt"
symlink "$HomeTestFiles$\files\dummy.txt" "$HomeTestFiles$\files\symlink.txt"
del "$HomeTestFiles$\files\temp\rename.txt"
del "$HomeTestFiles$\files\temp\move.txt"
copy "$HomeTestFiles$\files\dummy2.txt" "$HomeTestFiles$\files\temp\"
rename "$HomeTestFiles$\files\temp\dummy2.txt" "$HomeTestFiles$\files\temp\rename.txt"
copy "$HomeTestFiles$\files\dummy2.txt" "$HomeTestFiles$\files\temp\"
move "$HomeTestFiles$\files\temp\dummy2.txt" "$HomeTestFiles$\files\temp\move.txt"
----

* Die Funktion `del` und `delete`  +
Windows: Läßt sich die Datei nicht löschen (Datei in Verwendung) so wird die Operation beim nächsten Reboot fertiggestellt. In diesem Fall wird auch automatisch ein Reboot nach dem Ende des Scriptes ausgelöst. Dies läst sich aber mit der Option `-c` (continue) unterdrücken. +
Linux: Die Option `-c` wird unter Linux ignoriert.

.For-To Schleife [W/L] 

* Zum mehrfachen Ausführen eines Befehls oder einer Subsektion.

* Syntax:

`for` %<temporary string variable>% `=` <start string> `to` <end string> `do` <one statement> //since 4.11.5 [W/L]

Die temporäre Variable %<temporary string variable>% muss nicht und darf nicht deklariert werden und ist in der aufgerufenen Subsektion als Konstante verfügbar.

* Example: 

Code from opsi-winst-test:
[source,winst]
----
message "for to loop"
set $ConstTest$ = "12345"
set $CompValue$ = ""
for %s% = "1" to "5" do sub_iteration_test
if ($ConstTest$ = $CompValue$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif

[sub_iteration_test]
set $CompValue$ = $CompValue$ + '%s%'
----

ergibt den Log:

[source,winst]
----
message for to loop
Set  $ConstTest$ = "12345"
  The value of the variable "$ConstTest$" is now: "12345"
Set  $CompValue$ = ""
  The value of the variable "$CompValue$" is now: ""

~~~~~~ Looping through:  '1', '2', '3', '4', '5'
  
  ~~~~~~~ Start Sub ~~~~~~~  sub_iteration_test
  Set  $CompValue$ = $CompValue$ + '1'
    The value of the variable "$CompValue$" is now: "1"
  
  ~~~~~~~ End Sub   ~~~~~~~  sub_iteration_test
  
  
  ~~~~~~~ Start Sub ~~~~~~~  sub_iteration_test
  Set  $CompValue$ = $CompValue$ + '2'
    The value of the variable "$CompValue$" is now: "12"
  
  ~~~~~~~ End Sub   ~~~~~~~  sub_iteration_test
  
  
  ~~~~~~~ Start Sub ~~~~~~~  sub_iteration_test
  Set  $CompValue$ = $CompValue$ + '3'
    The value of the variable "$CompValue$" is now: "123"
  
  ~~~~~~~ End Sub   ~~~~~~~  sub_iteration_test
  
  
  ~~~~~~~ Start Sub ~~~~~~~  sub_iteration_test
  Set  $CompValue$ = $CompValue$ + '4'
    The value of the variable "$CompValue$" is now: "1234"
  
  ~~~~~~~ End Sub   ~~~~~~~  sub_iteration_test
  
  
  ~~~~~~~ Start Sub ~~~~~~~  sub_iteration_test
  Set  $CompValue$ = $CompValue$ + '5'
    The value of the variable "$CompValue$" is now: "12345"
  
  ~~~~~~~ End Sub   ~~~~~~~  sub_iteration_test
  

~~~~~~ End Loop
If
  $ConstTest$ = $CompValue$   <<< result true
  ($ConstTest$ = $CompValue$)   <<< result true
Then
  comment: passed
Else
EndIf
----

.Switch / Case Statement [W/L] 

* Syntax:

----
Switch <string expression> 
  Case <string const>
    <statement(s)> 
  EndCase
  [DefaultCase
    <statement(s)> 
   EndCase]
EndSwitch
----

* Examples:

Code from opsi-winst-test:
[source,winst]
----
set $ConstTest$ = "5"
Switch $ConstTest$
	Case "1"
		set $CompValue$ = "1"
	EndCase
	Case "2"
		set $CompValue$ = "2"
	EndCase
	Case "3"
		set $CompValue$ = "3"
	EndCase
	Case "4"
		set $CompValue$ = "4"
	EndCase
	Case "5"
		set $CompValue$ = "5"
	EndCase
	Case "6"
		set $CompValue$ = "6"
	EndCase
	Case "7"
		set $CompValue$ = "7"
	EndCase
	DefaultCase
		set $CompValue$ = "notexisting"
	EndCase
EndSwitch
if ($ConstTest$ = $CompValue$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif
----

.
[source,winst]
----
[Sub_check_exitcode]
comment "Test for installation success via exit code"
set $ExitCode$ = getLastExitCode
; informations to exit codes see
; http://msdn.microsoft.com/en-us/library/aa372835(VS.85).aspx
; http://msdn.microsoft.com/en-us/library/aa368542.aspx
Switch $ExitCode$
	Case "0"
		comment "Looks good: setup program gives exitcode zero"
	EndCase
	Case "1605"
		comment "ERROR_UNKNOWN_PRODUCT	1605"
		comment "This action is only valid for products that are currently installed."
		comment "Uninstall of a not installed product failed - no problem"
	EndCase
	Case "1641"
		comment "looks good: setup program gives exitcode 1641"
		comment "ERROR_SUCCESS_REBOOT_INITIATED	164"	
		comment "The installer has initiated a restart." 
		comment "This message is indicative of a success."
		ExitWindows /Reboot
	EndCase
	Case "3010"
		comment "looks good: setup program gives exitcode 3010"
		comment "ERROR_SUCCESS_REBOOT_REQUIRED	3010"
		comment "A restart is required to complete the install."
		comment "This message is indicative of a success."
		ExitWindows /Reboot
	EndCase
	DefaultCase
		logError "Fatal: Setup program gives an unknown exitcode unequal zero: " + $ExitCode$
		isFatalError "Exit Code: "+ $ExitCode$
	EndCase
EndSwitch
----

.Parameter für Sektionen

* Bei `ShellBatch`, `ShellInAnIcon`, `DosBatch`, `DosInAnIcon`, `ExecWith` +
sind nun als Parameter neben Stringkonstanten auch Stringvariablen erlaubt (aber keine String Funktionen).

Example:

Code from opsi-winst-test:
[source,winst]
----
comment "Testing parameters for ShellBatch"
set $ConstTest$ = "Hello world"
set $list$ = getOutStreamFromSection('DosInAnIcon_with_parameter world')
set $CompValue$ = takeString(2,$list$)
if ($ConstTest$ = $CompValue$)
	comment "ShellBatch parameter passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "ShellBatch parameter failed"
endif

comment "Testing parameters for ShellBatch"
set $ConstTest$ = "Hello world"
set $tmp$ = "world"
set $list$ = getOutStreamFromSection('DosInAnIcon_with_parameter $tmp$')
set $CompValue$ = takeString(2,$list$)
if ($ConstTest$ = $CompValue$)
	comment "ShellBatch parameter passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "ShellBatch parameter failed"
endif
----

ergibt den Log:

[source,winst]
----
comment: Testing parameters for ShellBatch
Set  $ConstTest$ = "Hello world"
  The value of the variable "$ConstTest$" is now: "Hello world"
Set  $list$ = getOutStreamFromSection('DosInAnIcon_with_parameter world')
  
  DosInAnIcon_with_parameter
    c:\opsi.org\tmp\_opsiscript_Kj23Ej02.cmd saved back
    Executing "cmd.exe" /C c:\opsi.org\tmp\_opsiscript_Kj23Ej02.cmd world
    ExitCode 0
                
                output:
                --------------
                
                C:\Windows\system32>echo Hello world 
                Hello world
    
    The file: c:\opsi.org\tmp\_opsiscript_Kj23Ej02.cmd has been deleted
    retrieving strings from getOutStreamFromSection [switch to loglevel 7 for debugging]
        (string   0)
        (string   1)C:\Windows\system32>echo Hello world 
        (string   2)Hello world
        
Set  $CompValue$ = takeString(2,$list$)
    retrieving strings from $list$ [switch to loglevel 7 for debugging]
        (string   0)
        (string   1)C:\Windows\system32>echo Hello world 
        (string   2)Hello world
        
  The value of the variable "$CompValue$" is now: "Hello world"
If
  $ConstTest$ = $CompValue$   <<< result true
  ($ConstTest$ = $CompValue$)   <<< result true
Then
  comment: ShellBatch parameter passed
Else
EndIf

comment: Testing parameters for ShellBatch
Set  $ConstTest$ = "Hello world"
  The value of the variable "$ConstTest$" is now: "Hello world"
Set  $tmp$ = "world"
  The value of the variable "$tmp$" is now: "world"
Set  $list$ = getOutStreamFromSection('DosInAnIcon_with_parameter $tmp$')
  
  DosInAnIcon_with_parameter
    c:\opsi.org\tmp\_opsiscript_Kz50Gi50.cmd saved back
    Executing "cmd.exe" /C c:\opsi.org\tmp\_opsiscript_Kz50Gi50.cmd world
    ExitCode 0
                
                output:
                --------------
                
                C:\Windows\system32>echo Hello world 
                Hello world
    
    The file: c:\opsi.org\tmp\_opsiscript_Kz50Gi50.cmd has been deleted
    retrieving strings from getOutStreamFromSection [switch to loglevel 7 for debugging]
        (string   0)
        (string   1)C:\Windows\system32>echo Hello world 
        (string   2)Hello world
        
Set  $CompValue$ = takeString(2,$list$)
    retrieving strings from $list$ [switch to loglevel 7 for debugging]
        (string   0)
        (string   1)C:\Windows\system32>echo Hello world 
        (string   2)Hello world
        
  The value of the variable "$CompValue$" is now: "Hello world"
If
  $ConstTest$ = $CompValue$   <<< result true
  ($ConstTest$ = $CompValue$)   <<< result true
Then
  comment: ShellBatch parameter passed
Else
EndIf
----

.Funktionen und Aufrufe

* `UpdateEnvironment` [W]: +
Sendet Windows das Signal das Environment aus der Registry neu einzulesen.
Anzuwenden nachdem Umgebungsvariablen wie z.B. PATH in der Registry verändert, gesetzt oder gelöscht wurden. +
ABER: Normale DosBatch oder Winbatch Aufrufe erben trotzdem das 'alte' Environment. Daher danach `winbatch` mit dem Parameter `/RunElevated` verwenden. +
Daher funktioniert diese Funktion nur bei Windows >= NT6.

Example:
[source,winst]
----
comment "Set Environment Variables and check for it ...."
Registry_add_environment /sysnative
UpdateEnvironment

comment "This will not work because the environment is inherited from the running process"
set $list$ = shellCall('set opsi-script-test')

comment "This will work because this new started process will get a new environment"
winbatch_check_environment /RunElevated
if ("42" = getlastExitCode)
	comment "passed"
else
	comment "failed"
endif

[Registry_add_environment]
openkey [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment]
set "opsi-script-test"="deleteme"

[winbatch_check_environment]
"%system%\cmd.exe" /c "if %opsi-script-test%==deleteme exit 42"
----

* `sleepseconds` [W/L] +
Als Parameter für die Anzahl der Sekunden sind nun auch Stringausdrücke erlaubt,
also auch Stringvariablen und Stringfunktionen.

* `MaximizeWinst` [W/L] +
Vergrößert das opsi-script Fenster auf das Maximum.

* Suchpfad für `include_insert` und `include_append` ist um `%ScriptPath%/../lib` erweitert worden und gilt nun auch für externe `sub` -Sektionen.  +

Für alle Funktionen gilt: +
<file name> ist:

* Ein kompletter Pfad zu einer Datei. [W/L] 

* Eine Datei in `%ScriptPath%` [W/L]

* Eine Datei in `%opsiScriptHelperPath%\lib` [W] +
Entspricht: '%ProgramFiles32Dir%\opsi.org\opsiScriptHelper\lib'

* Eine Datei in `%ScriptPath%/../lib` [W/L]

* Eine Datei in `%WinstDir%\lib` [W]

Die Prüfung erfolgt in dieser Reihenfolge. Die erste Datei die gefunden wird, wird genommen.

* `getProductPropertyList(`<propname>,<default value>`)` [W/L] +
Diese Funktion ist seit 4.11.3 verfügbar mit <default value> als string expression. + 
`<default value>` kann bei `getProductPropertyList` (seit 4.11.5.6) sowohl ein Stringausdruck sein welcher das erste Element der einer Liste beschreibt oder eine Liste. Diese Liste wird zurückgegeben wenn der die aktuellen Werte des Servers nicht verfügbar sind.

* `LoadTextFileWithEncoding(` <file name> `,` <encoding>`)` [W/L] +
Liefert eine Stringliste mit dem Inhalt von <file name> welcher beim Einlesen von <encoding> in das laufende Encoding des Systems konvertiert wurde.

* `removeFromListByContaining(`<search string>`,` <target list>`)` [W/L] +
Liefert eine Kopie von <target list> bei der alle Zeilen entfernt sind in denen  
<search string> vorkommt. Der Vergleich ist case insensitiv.

* `removeFromListByContaining(`<search list>`,` <target list>`)` [W/L] +
Liefert eine Kopie von <target list> bei der alle Zeilen entfernt sind in denen ein String aus <search list> vorkommt. Der Vergleich ist case insensitiv.

Examples:

File "%Scriptpath%\test-files\encoding\10lines.txt" is:
----
line 1
line 2
line 3
line 4
line 5
line 6
line 7
line 8
line 9
line 10
----

Code from opsi-winst-test:

[source,winst]
----
comment ""
comment "-------------------------------------"
comment "Testing: "
message "removeFromListByContaining"
set $string1$ = "%Scriptpath%\test-files\encoding\10lines.txt"
set $list1$ = loadTextFileWithEncoding($string1$, "cp1252")
comment "search with string"
comment "search with string constant"
set $ConstTest$ = "9"
set $list2$ = removeFromListByContaining("line 5", $list1$)
set $CompValue$ = count($list2$)
if ($ConstTest$ = $CompValue$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif

set $ConstTest$ = "9"
set $list2$ = removeFromListByContaining("LINE 5", $list1$)
comment "the match is case insensitive"
set $CompValue$ = count($list2$)
if ($ConstTest$ = $CompValue$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif


set $ConstTest$ = "0"
set $list2$ = removeFromListByContaining("line", $list1$)
set $CompValue$ = count($list2$)
if ($ConstTest$ = $CompValue$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif

set $ConstTest$ = "8"
comment "searchstr 1 will found in 'line 1' and 'line 10'"
set $list2$ = removeFromListByContaining("1", $list1$)
set $CompValue$ = count($list2$)
if ($ConstTest$ = $CompValue$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif

comment "search with string function"
set $ConstTest$ = "9"
set $list2$ = removeFromListByContaining(trim(" line 5 "), $list1$)
set $CompValue$ = count($list2$)
if ($ConstTest$ = $CompValue$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif

comment "search with string variable"
set $string1$ = "line 5"
set $ConstTest$ = "9"
set $list2$ = removeFromListByContaining($string1$, $list1$)
set $CompValue$ = count($list2$)
if ($ConstTest$ = $CompValue$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif

comment "search with string list"
comment "search with string list variable"
set $list3$ = createStringList ('1', '2', '3', '4', '5')
comment "searchstr 1 will found in 'line 1' and 'line 10'"
set $ConstTest$ = "4"
set $list2$ = removeFromListByContaining($list3$, $list1$)
set $CompValue$ = count($list2$)
if ($ConstTest$ = $CompValue$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif

comment "search with string list variable"
comment "searchstr 1 will found in 'line 1' and 'line 10'"
set $ConstTest$ = "4"
set $list2$ = removeFromListByContaining(createStringList ('1', '2', '3', '4', '5'), $list1$)
set $CompValue$ = count($list2$)
if ($ConstTest$ = $CompValue$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif
----

* Stringfunktion `unquote2(<string>,<quote-string>)` [W/L] +
Funktioniert wie `unquote(<string>,<quote-string>)` mit folgenden Unterschieden: +
Wenn <quote-string> ein Zeichen lang ist, wird diese Zeichen als erwartetes 'Quote Zeichen' für den Anfang und das Ende von <string> genommen. Wenn <quote-string> zwei Zeichen lang ist, wird das erste Zeichen als erwartetes 'Quote Zeichen' für den Anfang und das zweite Zeichen als erwartetes 'Quote Zeichen' für den Ende von <string> genommen. Beispiel: `"()"` +
Die Funktion liefert <string> unverändert zurück, wenn nicht sowohl für Anfang und Ende die erwarteten 'Quote Zeichen' gefunden werden.

* Logging im `silent_install` Modus:
Wird opsi-script / opsi-winst aus einem `silent_install` Event gestartet (z.B für die Inventarisierung im Hintergrund), so werden die Logs immer im Append Mode an den Server gesendet als an den vorhandenen Log angehängt.

* Stringfunktion `GetShortWinPathName(<longpath string>)` [W] +
Liefert den Shortpath (8.3) von <longpath string>. Lässt sich für <longpath string> kein Shortpath finden, so liefert die Funktion einen leeren String. + Beispiel: `GetShortWinPathName("C:\Program Files (x86)")` liefert `"C:\PROGRA~2"`

* `GetConfidentialProductProperty (` <PropertyName>, <DefaultValue>`)` //since 4.11.5.2 +
verhält sich wie `GetProductProperty` nur das der resultierende Wert als confidential string behandelt und damit nicht gelogged wird. +
Sinnvoll um z.B. Passwörter aus einem Produktproperty abzufragen. Siehe auch `SetConfidential`

* Boolsche Funktion `CompareDotSeparatedStrings(`<str1>,<relation str>,<str2>`)`  //since 4.11.5.2: [W/L] +
vergleicht zwei Strings vom Typ <str>[.<str>[.<str>[.<str>]]] unter Verwendung des <relation str> der eins von den folgenden Werten haben darf: [<,<=,=,>=,>]. +
siehe auch: Stringfunktion `CompareDotSeparatedStrings(`<string1>, <string2>`)`

* Boolsche Funktion `CompareDotSeparatedNumbers(`<str1>,<relation str>,<str2>`)`  //since 4.11.5.2: [W/L] +
vergleicht zwei Strings vom Typ <zahl>[.<zahl>[.<zahl>[.<zahl>]]] unter Verwendung des <relation str> der eins von den folgenden Werten haben darf: [<,<=,=,>=,>]. +
siehe auch: Stringfunktion `CompareDotSeparatedNumbers(`<string1>, <string2>`)`

Example: +
The code:
[source,winst]
----
set $string1$ = "1.2.30.4.5"
set $string2$ = "1.20.30.4.5"
if CompareDotSeparatedNumbers($string1$, "<", $string2$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif
if CompareDotSeparatedNumbers($string1$, "<=", $string2$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif
if CompareDotSeparatedNumbers($string1$, "=<", $string2$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif
if CompareDotSeparatedNumbers($string1$, "=", $string2$)
	set $TestResult$ = "not o.k."
	LogWarning "failed"
else
	comment "passed"
endif
if CompareDotSeparatedNumbers($string1$, ">=", $string2$)
	set $TestResult$ = "not o.k."
	LogWarning "failed"
else
	comment "passed"
endif
if CompareDotSeparatedNumbers($string1$, "=>", $string2$)
	set $TestResult$ = "not o.k."
	LogWarning "failed"
else
	comment "passed"
endif
if CompareDotSeparatedNumbers($string1$, ">", $string2$)
	set $TestResult$ = "not o.k."
	LogWarning "failed"
else
	comment "passed"
endif
----
produce the log:
[source,winst]
----
Set  $string1$ = "1.2.30.4.5"
  The value of the variable "$string1$" is now: "1.2.30.4.5"
Set  $string2$ = "1.20.30.4.5"
  The value of the variable "$string2$" is now: "1.20.30.4.5"
If
    Checking if "1.2.30.4.5" is "<" than / as "1.20.30.4.5"
  CompareDotSeparatedNumbers($string1$, "<", $string2$)   <<< result true
Then
  comment: passed
Else
EndIf
If
    Checking if "1.2.30.4.5" is "<=" than / as "1.20.30.4.5"
  CompareDotSeparatedNumbers($string1$, "<=", $string2$)   <<< result true
Then
  comment: passed
Else
EndIf
If
    Checking if "1.2.30.4.5" is "=<" than / as "1.20.30.4.5"
  CompareDotSeparatedNumbers($string1$, "=<", $string2$)   <<< result true
Then
  comment: passed
Else
EndIf
If
    Checking if "1.2.30.4.5" is "=" than / as "1.20.30.4.5"
  CompareDotSeparatedNumbers($string1$, "=", $string2$)   <<< result false
Then
Else
  comment: passed
EndIf
If
    Checking if "1.2.30.4.5" is ">=" than / as "1.20.30.4.5"
  CompareDotSeparatedNumbers($string1$, ">=", $string2$)   <<< result false
Then
Else
  comment: passed
EndIf
If
    Checking if "1.2.30.4.5" is "=>" than / as "1.20.30.4.5"
  CompareDotSeparatedNumbers($string1$, "=>", $string2$)   <<< result false
Then
Else
  comment: passed
EndIf
If
    Checking if "1.2.30.4.5" is ">" than / as "1.20.30.4.5"
  CompareDotSeparatedNumbers($string1$, ">", $string2$)   <<< result false
Then
Else
  comment: passed
EndIf
----



.opsi-Linux Support:

* Winbatch Sektionen werden jetzt auch unter Linux unterstützt.

* LinkFolder Sektionen werden jetzt auch unter Linux unterstützt. +
Erlaubte BaseFolder sind: `common_programs`,`common_autostart`,`desktop`, `autostart` +
Subfolder ist immer "" (leer).
Die Link Option `icon_index` wird ignoriert. +
Als zusätzliche Link Option gibt es: `link_categories`. Hier sind folgende durch Semikolon getrennt und abgeschlossene Werte erlaubt: `AudioVideo`, `Audio`, `Video`, `Development`, `Education`, `Game`, `Graphics`, `Network`, `Office`, `Settings`, `System`, `Utility` +
Die LinkFolder Sektion unter Linux funktioniert für unterschiedliche Desktopsysteme.

* `shellCall` liefert jetzt den korrekten exitcode des aufgerufenen Befehls zurück. Technisch gesehen wird der übergebene Befehl durch ` || exit $?` ergänzt, so daß die aufgerufene shell (/bin/bash) den exitcode des eigentlichen Befehls zurück gibt.

[[opsi-406-releasenotes-python-opsi]]
== python-opsi 4.0.6.

Die von opsi verwendeten Python-Bibliotheken haben zahlreiche
Verbesserungen und Fehlerkorrekturen erhalten.

Weiterhin wurden einige Funktionalitäten von externen Scripten direkt in
die Library verlagert, damit diese bei geringerem Pflegeaufwand einfach
an unterschiedlichen Stellen verwendet werden können.

In diesem Rahmen gibt es die folgenden neuen Module:
`OPSI.Util.Task.Rights` beinhaltet Methoden zum Setzen von Ordner- und
Dateirechten.
OPSI.Util.Task.UpdateBackend.MySQL` beinhaltet Methoden zum
Aktualisieren des MySQL-Backends.

Die Funktion `OPSI.Types.forceList` erkennt nun Tupel und Generatoren
und wandelt diese in eine Liste um. Generatoren werden dabei
aufgebraucht.

Bei der Zertifikatserstellung mit Methoden aus dem Modul
`OPSI.Util.Task.Certificate` wird nun eine Seriennummer zufällig
erstellt, falls keine Seriennummer vorhanden ist.
Bei einer vorhandenen Seriennummer wird diese erhöht.
Dadurch wird der Beschreibung in RFC5820 gefolgt und vermieden, dass die
Seriennummer unterschiedlicher Zertifikate gleich ist.
Dies findet bei der Verwendung von `opsi-setup --renew-opsiconfd-cert`.

Die Arbeitsweise des Moduls `OPSI.SharedAlgorithm` wurde geändert, so
dass das Modul nun nicht mehr aus Strings besteht, die evaluiert werden,
da diese Möglichkeit von keiner offiziellen Komponente verwendet wurde.
Die Methode `backend_getSharedAlgorithm` wird bei Verwendung jetzt einen
Fehler werfen.

Die Methoden zur Bestimmung der Produktreihenfolge wurden überarbeitet. Wenn eine
zirkuläre Abhängigkeit erkannt wird, wird jetzt bei jeder Methode ein Fehler geworfen. 
Außerdem wird jetzt bei jeder Methode eine Warnung 
in die Logdatei geschrieben, wenn eine Produktabhängigkeit definiert ist, 
die im Widerspruch zu einer definierten Priorität steht und dann zu 
unvorhersehbaren Resultaten führen kann. 

Die Methode `OPSI.System.Windows.mount` akzeptiert durch einen
freundlicherweise von Markus Kötter eingereichten Patch nun als Ziel
den Wert `dynamic`. Dadurch wird es möglich, dass an einen
eigenständig ermittelten Punkt ein Laufwerk eingehangen wird.
Somit kann ein Rechner mit aktuellem opsi-client-agent selbst einen
freien Laufwerksbuchstaben ermitteln, an welchem der Depot-Share
eingehangen wird.
Um dieses Feature zu nutzen, muss das Property
`clientconfig.depot.drive` eines Clients auf den Wert `dynamic` gesetzt
werden. Die Ergänzung des Properties auf dem opsi-Server um diesen Wert
kann mittels `opsi-setup --init-current-config` angestoßen werden.
Dieses Feature benötigt den aktuellen `opsi-client-agent` auf dem Client.

Die Treiberintegration behandelt Ordner, die auf einen Unterstrich enden,
genau so wie Ordner, die auf einen Punkt enden. Dadurch werden Probleme
mit Dateisystembeschränkungen unter Windows vermieden.
Beispiel: Für ByAudit-Treiberintegration für einen Rechner vom Hersteller
`Dilbert Inc.` nennen Sie den Ordner `Dilbert Inc_`.

* opsi Serverkomponenten: +
Diverse Verbesserungen und Bugfixes in den Serverpaketen.

** Auf der Info-Page des opsi-Servers wird eine Statistik über die Anzahl +
der von außen aufgerufenen Methoden bereit gestellt.

** Die Kürzung der Logfiles durch den opsiconfd ist nun konfigurierbar.
Zuvor wurden die Logfiles auf ~5MB begrenzt, um zu verhindern, dass
durch große Mengen übertragener Logdateien die Festplatte des Servers
gefüllt wird.
Dieses Verhalten wird standardmaßig beibehalten, es kann jedoch über das
Attribut `max log size` in der Sektion `global` der Datei
`/etc/opsi/opsiconfd.conf` geändert oder deaktiviert werden.

Um dennoch ein einfaches Aufräumen der Logfiles zu ermöglichen, wird eine
erweiterte logrotate-Konfiguration ausgeliefert. Diese ist zu finden
`/etc/logrotate.d/opsiconfd`.
In dieser Datei findet sich auch ein Konfigurationsabschnitt für die Datei
`/var/log/opsi/package.log`. Bei dieser Datei fand in der Vergangenheit
keine Kürzung statt.

** Im MySQL-Backend haben nun alle Spalten, welche auf die ID eines
Hosts referenzieren die gleiche Länge - 255 Zeichen.
Neue Backends werden automatisch korrekt erstellt.
Um bestehende Backends anzupassen, führen Sie bitte
`opsi-setup --update-mysql` aus.

** Bei der Initialisierung des MySQL-Backends wird, wenn bei der
Initialisierung die Verbindung zur Datenbank nicht hergestellt werden
kann, 5 Sekunden gewartet, bevor ein weiterer Verbindungsversuch
unternommen werden kann.

** Die Werkzeuge `opsi-product-updater`, `opsi-newprod` und
`opsi-package-manager` nutzen jetzt alle die gleiche Funktion zum Setzen
der Datei-Zugriffsrechte, damit diese konsistent gesetzt sind.

** Ein freundlicherweise von Antoine Guevara eingereichter Patch
ermöglicht es einen beliebigen Betreff für durch das Werkzeug
`opsi-product-updater` versendete E-Mails anzugeben.
Der Betreff kann durch das Attribut `subject` in der Sektion
`notification` in der Datei `/etc/opsi/opsi-product-updater.conf`
festgelegt werden.

** Das Werkzeug `opsi-admin` hat einen neuen Task bekommen: +
setActionRequestWhereOutdatedWithDependencies
Dieser imitiert das Verhalte von setActionRequestWhereOutdated, arbeitet
aber auch mit den entsprechenden Dependencies des Produkt.
Vielen Dank an Daniel Koch für das Einsenden das Patches.

[[opsi-406-releasenotes-netboot-windows]]
== opsi Support Matrix Windows Clients

Im folgenden finden Sie eine Übersicht auf welchen Windows Plattformen opsi
als Client läuft.

include::../common/opsi_manual_supportmatrix-winclient.asciidoc[]




[[opsi-406-releasenotes-misc]]
== Sonstiges

[[opsi-406-releasenotes-misc-changelogs]]
=== Changelogs:


[[opsi-406-releasenotes-misc-changelogs-opsi-configed]]
==== Changelog opsi-configed

opsi-configed (4.0.6.3.5-1) TESTING; urgency=medium
 
  * logpane improved: search starting with caretPosition
  * logpane improved: search strings saved in combobox
  * Software page with search functionality
  * Software page with option to exclude MS updates from shown software
  * licence statistics counting repaired

-- roeder <roeder@uib.de>  Mon, 31 Aug 2015 10:07:04 +0200

opsi-configed (4.0.6.0.8-1) EXPERIMENTAL; urgency=medium

  * WAN config by checkbox

-- sucher <a.sucher@uib.de>  Tue, 31 Mar 2015 12:43:35 +0200

opsi-configed (4.0.6.0.7-1) experimental; urgency=medium

  * in case of querysavedsearch we omit any console output
  * with depot properties editing, a depot selection is kept when changing product
  * fixed that the connection state was not correctly identified which led to errors in file backend

-- roeder <r.roeder@uib.de>  Fri, 27 Mar 2015 16:30:35 +0100

opsi-configed (4.0.6.0.5-1) experimental; urgency=medium

  * removed exception of ReachableUpdate when updating the model
  * fix: on host refresh, a host configs refresh is necessary
  * configed default logdir for windows move to localappdata dir
  * hostparameter editor leaked and reached window handle maximum, fixed by multiton pattern
  * on authentication password corection was not observed

-- roeder <r.roeder@uib.de>  Thu, 19 Mar 2015 16:25:46 +0100
 
[[opsi-406-releasenotes-misc-changelogs-opsi-client-agent]]
==== Changelog opsi-client-agent

opsi-client-agent (4.0.6.2-1) testing; urgency=low

  * Avoid having a cmd window popup on shutdown.
  * update to opsi-winst 4.11.5.13 (do 28.8.)
  * Using LoadProductProperties to get Productproperties after network connection (do 10.7.)
  * new property: setup_after_install (do 15.7.) fixes  #1613
  * update to openssl 1.0.2d
  * service_setup.cmd: better handling of /u ; fixes #503

-- Niko Wenselowski <n.wenselowski@uib.de>  Fri, 10 Jul 2015 10:31:25 +0100

opsi-client-agent (4.0.6.1-2) experimental; UNRELEASED; urgency=low

  * fix in config.opsiscript: missing variable fo opsiclientd.conf
  * Update SSL DLLs from opsi-script to opsiclientd ; refrences #1491
  * integrate openssl to opsi-client-agent directory
  * no special uninstall for openssl anymore
  * No Environment vars for openssl
  * use http://indy.fulgan.com/SSL/ instead of shining light ssl
  * update to openssl 1.0.2c
  * Updated opsi-deploy-client-agent (niko)
  * OpsiLoginBlocker.dll logfile changes (loglevel first) (mm)
  * setup.opsiscript: changed Error message on copy failure
  * update to opsi-winst 4.11.5.6
  * *.opsiscript: for win10: change all '$INST_NTVersion$ < "6.0"' to CompareDotSeparatedNumbers
  * new property: depends_on_service : List of services that have to started before opsiclientd

-- Detlef Oertel <d.oertel@uib.de>  Tue, 17 Mar 2015 15:00:00 +0100

opsi-client-agent (4.0.6.1-1) experimental; urgency=low

  * openssl update to 1.0.1L  ; references #1027
  * Updated deployment script
  * scripts renamed from *.ins to *.opsiscript
  * scripts: c:\tmp replaced by %opsiTmpDir% or %opsiLogDir%
  * scripts: ALLUSERS=2 replaced by ALLUSERS=1
  * update to opsi-winst 4.11.5.1 (do)
  * cleanup unused files
  * get hostname from %pcname% ; references #1369
  * make silent_setup.cmd complete unattend ; references #503
  * icon for softwareOnDemand ; references #936
  * support for multiple clientconfig.configserver.url ; patch from <boris.synak@zobelsoft.de> ; references #1237
  * set also opsi-winst to installed ; references #1329
  * new update script files\opsi\config.opsiscript / subconfig.opsiscript for activate event_on_shutdown and LinkFolder_install_softwareOnDemand ; references #1329
  * associate *.opsiscript files with winst32.exe ; references #1045
  * start "%ScriptPath%\custom\custom.opsiscript" after sub_write_configuration ; references #458
  * uninstall: fixes for on_shutdown registry keys
  * postinst: for backward compatibiliy: create a setup.ins as hard link

-- Detlef Oertel <d.oertel@uib.de>  Mon, 26 Jan 2015 15:00:00 +0100


[[opsi-406-releasenotes-misc-changelogs-opsi-script]]
==== Changelog opsi-script / opsi-winst

opsi-winst/opsi-script (4.11.5.2) stable; urgency=low

  * upgrade to ssl Libraries 1.0.2a (libeay32.dll, ssleay32.dll)
  * files commands move / rename / hardlink / symlink now work with overwrite; fixes #1435
  * if move / rename fails (file is in use) we retry it with MOVEFILE_DELAY_UNTIL_REBOOT
    So the move will be done at the next reboot. Reboot will be set automatically if not Option -c is set.
  * file command del / delete now with option -c and retry to delete on next boot if file in use ; fixes # 788
  * osfunc: new function opsiunquotestr2
  * new string function unquote2(s1,s2): like unquote but:
        removes only quotes if they found at start and end
        s2 may be two chars long. Then the first char is the start mark
        and the second char is the end mark
  * osparser: GetString: new boolean switch requote
  * osparser: GetString requote=true: change double quoted (""str"") to alternative double quoted ('""');  references #1284
  * new string function: GetShortWinPathName(longpath) ; fixes #581
        Windows only
        Gives short path (8.3) from a long path e.g.
        GetShortWinPathName("C:\Program Files (x86)") gives "C:\PROGRA~2"
        In case of Error the result is an empty string
  * osfunc: startprocess_cp: translate windows showWindowFlag to TProcess TShowWindowOptions
  * osparser: doRegistryHack* : fix for not HKCU reg enties in loginscripts; fixes #1538
  * oswebservice: more log for "unexpected Result from webservice in retrieveJSONObject, number of lines: 0"
  * new string function: GetConfidentialProductProperty : like GetProductProperty but handles the result as confidential string ; fixes #462
  * fixes at GetNTVersion for Win10
  * new boolean function CompareDotSeparatedNumbers(<str1>,<relation str>,<str2>)
        <relation str> may be: one of [<,<=,=,>=,>]
  * new boolean function CompareDotSeparatedStrings(<str1>,<relation str>,<str2>)
        <relation str> may be: one of [<,<=,=,>=,>]
  * hide non visible processes (SW_HIDE) like winbatch or shellInAnIcon
  * (Security Update) oswebservice: use TLS1.2 instead of SSLv3

-- Detlef Oertel <d.oertel@uib.de>  Wed,  01 Apr 2015:15:00:00 +0200


opsi-winst/opsi-script (4.11.5.1) stable; urgency=low

  * osparser: commandline := 'cmd64.exe /c "reg delete ""'+key_completepath+'"" /f'; (fixes #1299)
  * port of the changes since 4.11.4.6 to Linux
  * osparser: New files commands hardlink, symlink, rename, move
  * osfunc: new tuibinstall methods: hardlink, symlink, rename (Linux / Windows ; fixes #1319, #362)
  * osparser: execDosBatch: The path to temporary file is only quoted if it contains spaces
  * osparser: execDosBatch: Variables are now allowed as Parameters (but no functions) fixes #1312
  * osparser: executeWith: Variables are now allowed as Parameters (but no functions)
  * osparser: doAktionen: Variables and functions are now allowed as sleepsecond Parameters; fixes #1193
  * osparser: %SriptPath%/../lib as additional Path in Search path for includes; fixes #1201
  * osparser: searchpath for includes are now works also for sub <file> ; fixes #1201
  * New loop statement: for %s% = $start$ to $stop$ do <statement> ;  references #407
      - $start$ and $stop$ has to be integer strings
      - $start$ < $stop$ is required
      - in fact a stringlist $start$ to $stop$ is generated over which we iterate while loop
  * osparser: tsLoopForTo  for %s% = $start$ to $stop$ do <statement>
  * osparser: activating winbatch for linux ; fixes #1170
  * replacing opsi-winst constants by opsi-script
  * osparser: produceStringList: New (overloaded) stringlist function (references #1110):
              - removeFromListByContaining(<search string>, <target list>) removes  <search string> from <target list>
              - removeFromListByContaining(<search list>, <target list>) removes  <search list> from <target list>
              - both functions search case insensitive for a matching substring
  * ospparser: fix for filexists* to detect symlinks
  * upgrade to ssl Libraries 1.0.1L (libeay32.dll, ssleay32.dll)
  * osmain: GetParameter + StartProgramModes: more try - except : port from 4.11.4.16
  * osparser: doOpsiServiceCall: more try - except : port from 4.11.4.16
  * osparser: doTextPatchMain: do not use CheckFileExists in SaveToFile ; references #171
  * HowToBuild.txt ; fixes #1372
  * oswebservice: finishOpsiConf: if runproductlist then Logg-Appendmode := true; references #1379
  * new Statement: UpdateEnvironment : Triggers Windows to reload Environment from Registry; Win only; references #1364
  * new Control Statement: Switch  ; references  #740
    - osparser: Switch <string expr ; normally variable>
                  Case <string expr; normally const>
                    statments
                  EndCase
                  [Defaultcase
                    statments
                  EndCase]
                EndSwitch
  * LinkFolder for Linux activated: No BaseFolder, No SubFolder, No Iconindex
      but link_categories: 'AudioVideo',
      'Audio', 'Video', 'Development', 'Education', 'Game', 'Graphics',  'Network',
      'Office', 'Settings', 'System', 'Utility'
      // from http://standards.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry
      changes in osparser, osfunclin and new unit oslindesktop
  * some more ExpandFilename calls to handle incorrect path delimiter
  * oswebservice: sendlog: replace old writeLog by new log_write method
  * New Statement: MaximizeWinst at osparser
  * Erweiterte Stinglisten Funktion `getProductPropertyList(`<propname>,<default value>`)` mit `<default value>` als String oder Stringliste.
  * New Functions LoadTextFileWithEncoding(file,encoding) strLoadTextFileWithEncoding(file,encoding) at osparser
  * osencoding: LoadFromFileWithEncoding
  * oswebservice: sendlog: at Linux do not convert logstrings to uft8
  * oslog: dependentadd: more try except
  * osparser: sleepseconds (tsSleep): more try except and more logging
  * osparser: winbatch: trim targetfilename
  * osparser: shellBatch: Parameter at Linux (wrong bash parameter)
  * osmain: User Profile Management (runloginscripts) is now free
  * osmain: do not switch opsi-script to setup (even if it is opsi-winst); references # 1437

-- Detlef Oertel <d.oertel@uib.de>  Thu,  22 Dec 2014:15:00:00 +0200

opsi-winst/opsi-script (4.11.4.14) stable; urgency=low

  * less (only 512 chars) debug output: oswebservice: retrieveJSONObject: log ResultLines.Strings[0] if Result = nil
  * oswebservice: retrieveJSONObject: FillChar(buffer^, 655360,' '); before read to buffer
  * manifest extended for win 10: <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>

-- Detlef Oertel <d.oertel@uib.de>  Thu,  04 Dec 2014:15:00:00 +0200


opsi-winst/opsi-script (4.11.4.13) stable; urgency=low

  * more debug output: oswebservice: retrieveJSONObject: log ResultLines.Strings[0] if Result = nil

-- Detlef Oertel <d.oertel@uib.de>  Wed,  12 Nov 2014:15:00:00 +0200


opsi-winst/opsi-script (4.11.4.12) stable; urgency=low

  * fix: osmain: StartProgramModes: correct Path to the opsiclientd.conf in batch mode
  * Logdevel while writing log to Service decreased
  * fix: command typo: ErrorsOccuredSinceMark is wrong, now also allowed: ErrorsOccurredSinceMark  fixes #1121
  * bakup files of log now are opsi-script.log.x where x is 0 - 8
  * do not run login scripts if user is 'opsisetupadmin' fixes #1248

-- Detlef Oertel <d.oertel@uib.de>  Fri,  24 Oct 2014:15:00:00 +0200


opsi-winst/opsi-script (4.11.4.11) stable; urgency=low

  * new unit: SystemCriticalU
  * osmain: in StartprogramModes set SystemCritical.IsCritical := true;
  * osmain: in BuildPC set SystemCritical.IsCritical := true;
  * osmain: in Terminateapp set SystemCritical.IsCritical := false;
  * osmain: in different execept set SystemCritical.IsCritical := false;

-- Detlef Oertel <d.oertel@uib.de>  Wed,  09 Oct 2014:15:00:00 +0200



[[opsi-406-releasenotes-misc-changelogs-windows-netboot]]
==== Changelog windows netboot products

windows (4.0.6.1-1) stable; urgency=low

  * change imagename values and defaults
  * update opsisetuplib.py
  * nt6.py: hw-inventory use createObjects # fixes #1540
  * nt6.py: check for bootmgr.* now case insensitive
  * 99_cleanup.cmd : switch for 32/64 Bit ; fixes #1488

-- Detlef Oertel <d.oertel@uib.de>  Tue,  04 Aug 2015:15:00:00 +0200

[[opsi-406-releasenotes-misc-changelogs-linux-netboot]]
==== Changelog linux netboot products

.centos70

centos70_4.0.6.2-1 stable; urgency=low

  * changes for nfs mount

-- Detlef Oertel <d.oertel@uib.de>  Wed,  26 Mar 2015:15:00:00 +0200

centos70_4.0.6-1 stable; urgency=low

  * ported from centos70_7.0-1 and sles12

-- Detlef Oertel <d.oertel@uib.de>  Tue,  27 Jan 2015:15:00:00 +0200


centos70_7.0-1 stable; urgency=low

  * ported from centos65_6.5-3 and Fedora20
  * removed property online_repository
  * network configuration with predictable network interface names (may fail on rule 2 (ESXi clients)
  * install net-tools
  * hpsa support

-- Detlef Oertel <d.oertel@uib.de>  Wed,  27 Aug 2014:15:00:00 +0200

.debian7

debian7-4.0.6-1 stable; urgency=low

  * initial derivated from debian-4.0.5-6 and sles12  

-- Detlef Oertel <d.oertel@uib.de>  Mon, 12 Jan 2015:15:00:00 +0200

.debian8

debian8-4.0.6-1 stable; urgency=low

  * initial derivated from debian7-4.0.6-1 

-- Detlef Oertel <d.oertel@uib.de>  Mon, 26 Jan 2015:15:00:00 +0200

.opensuse13-2

opensuse13-2_4.0.6.2-2  stable; urgency=low

  * changes for 4.0.6 bootimage (>= 20150707):
    * property for network interface name ignored
    * no kexec copy

-- Detlef Oertel <d.oertel@uib.de>  Mon,  13 Jul 2015:15:00:00 +0200

opensuse13-2_4.0.6.2-1  stable; urgency=low

  * changes for nfs mount
  * temporary property for network interface name

-- Detlef Oertel <d.oertel@uib.de>  Wed,  26 Mar 2015:15:00:00 +0200

opensuse13-2_4.0.6-1  stable; urgency=low

  * initial

-- Detlef Oertel <d.oertel@uib.de>  Mon,  09 Feb 2015:15:00:00 +0200

.sles12

sles12_4.0.6.2-2 testing; urgency=low

  * more changes for nfs mount: clientconfig.opsi_nfs_share
  * temporary property for network interface name

-- Detlef Oertel <d.oertel@uib.de>  Tue,  28 Apr 2015:15:00:00 +0200


sles12_4.0.6.2-1 testing; urgency=low

  * changes for nfs mount

-- Detlef Oertel <d.oertel@uib.de>  Wed,  26 Mar 2015:15:00:00 +0200


sles12_4.0.6.1-2 testing; urgency=low

  * changes for opsi-linux-client-agent 4.0.6

-- Detlef Oertel <d.oertel@uib.de>  Wed,  04 Mar 2015:15:00:00 +0200

.redhat70

redhat70_4.0.6.2-1 stable; urgency=low

  * ported from centos70_4.0.6.2-1

-- Detlef Oertel <d.oertel@uib.de>  Mon,  27 Apr 2015:15:00:00 +0200

.Ubuntu14-04

Ubuntu14-04_4.0.6-2 stable; urgency=low

  * changes for 4.0.6 bootimage (>= 20150707):
    * no kexec copy

-- Detlef Oertel <d.oertel@uib.de>  Tue, 14 Jul 2015:15:00:00 +0200


Ubuntu14-04_4.0.6-1 stable; urgency=low

  * initial derivated from debian7_4.0.6-1

-- Detlef Oertel <d.oertel@uib.de>  Mon, 26 Jan 2015:15:00:00 +0200

.Ubuntu15-04

Ubuntu15-04_4.0.6-2 stable; urgency=low

  * initial derivated from Ubuntu14-04_4.0.6-2

-- Detlef Oertel <d.oertel@uib.de>  Tue, 14 Jul 2015:15:00:00 +0200

[[opsi-406-releasenotes-misc-changelogs-opsi-local-image]]
==== Changelog opsi-local-image

opsi-local-image-win* (4.0.6.1-1) stable; urgency=low

  * change imagename values and defaults
  * update opsisetuplib.py
  * 99_cleanup.cmd : switch for 32/64 Bit ; fixes #1488

-- Detlef Oertel <d.oertel@uib.de>  Tue,  04 Aug 2015:15:00:00 +0200


[[opsi-406-releasenotes-misc-changelogs-misc-netboot]]
==== Changelog misc netboot products


opsi-clonezilla (4.0.6-1) stable; urgency=low

  * 4.0.6 bootimage support
  * clonezilla-3.10.11
  * partclone-0.2.69
  * postinst cleared

-- detlef oertel <d.oertel@uib.de>  Fri, 24 Jul 2015 16:01:53 +0200


memtest86 (5.01-1) stable; urgency=low

  * extracted http://www.memtest.org/download/5.01/memtest86+-5.01.zip
  * extension .bin has to be removed
  * see: http://www.gtkdb.de/index_7_2379.html

-- Detlef Oertel <d.oertel@uib.de>  Tue,  11 Aug 2015:15:00:00 +0200

[[opsi-406-releasenotes-misc-changelogs-python-opsi]]
==== Changelog python-opsi

////
python-opsi (4.0.5.15-1) experimental; urgency=low
////
####################

[[opsi-406-releasenotes-misc-changelogs-opsipxeconfd]]
==== Changelog opsipxeconfd
////
opsipxeconfd (4.0.5.3-6) experimental; urgency=low
////
####################

[[opsi-406-releasenotes-misc-changelogs-opsiconfd]]
==== Changelog opsiconfd
////
opsiconfd (4.0.5.2-1) experimental; urgency=low
////
####################

[[opsi-406-releasenotes-misc-changelogs-opsi-utils]]
==== Changelog opsi-utils
////
opsi-utils (4.0.5.6-2) experimental; urgency=low
////
####################

[[opsi-406-releasenotes-misc-changelogs-opsi-linux-bootimage]]
==== Changelog opsi-linux-bootimage

opsi-linux-bootimage (20150818-1) experimental; urgency=medium

  [ Mathias Radtke ]
  * Ubuntu 14.04 Trusty
  * Kernel 4.1.0
  * Python-OPSI 4.0.6.14-1
  * Syslinux 6.0.3

-- Mathias Radtke <m.radtke@uib.de>  Wed, 18 Aug 2015 14:26:47 +0200

  [ Niko Wenselowski ]
  * Updated packaging.

-- Niko Wenselowski <n.wenselowski@uib.de>  Wed, 19 Aug 2015 15:46:55 +0200
 
[[opsi-406-releasenotes-misc-changelogs-opsi-depotserver]]
==== Changelog opsi-depotserver
////
opsi-depotserver (4.0.5.11-1) experimental; urgency=low
////
####################

[[opsi-406-releasenotes-misc-changelogs-opsi-atftp]]
==== Changelog opsi-atftp
////
opsi-atftp (0.7.dfsg-4) stable; urgency=medium
////
####################

[[opsi-406-releasenotes-misc-changelogs-opsi4ucs]]
==== Changelog opsi4ucs
////
opsi4ucs (4.0.5.5-4) experimental; urgency=low
////
####################

[[opsi-406-releasenotes-misc-changelogs-opsi-swaudit]]
==== Changelog opsi-swaudit
////
swaudit (4.0.5-1) stable; urgency=low
////
####################

 [[opsi-406-releasenotes-misc-changelogs-opsi-template]]
==== Changelog opsi-template
////
opsi-template (4.0.5-1) stable; urgency=low
////
####################

