////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      07.11.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-components-dhcp-pxe]]
= DHCP-Server/PXE-Boot

A DHCP server (Dynamic Host Configuration Protocol) automatically sets up devices in a network. This includes the assignment of IP address, netmask, gateway, domain name server (DNS) and also the configuration of network boot (PXE). Preboot Execution Environment makes it possible to start computers via the network and load an operating system. Devices that have a PXE-capable network adapter access a boot image via the network that contains the operating system or other required boot files.

NOTE: PXE can be used with both BIOS (Basic Input/Output System) and UEFI (Unified Extensible Firmware Interface). PXE itself is independent of the computer's firmware. The boot loaders used differ from each other.

In this case, the opsi depot server acts as a boot server -- opsi therefore enables the execution of automated processes independently of an operating system installed on the client.

To enable PXE boot, a DHCP server must provide additional information to the network device. When using the TFTP protocol, this is as follows:

* *Boot server (DHCP option 66)*: IP address of the TFTP server (also called next server)
* *Boot filename (DHCP option 67)*: The path to the bootloader on the TFTP server. This option must be configured differently for UEFI and BIOS devices.

TIP: More information on TFTP (Trivial File Transfer Protocol) can be found in chapter xref:server:components/tftpd.adoc[TFTP server].

[[server-components-dhcp-on-opsi-server]]
== DHCP on the opsi Depot Server

An opsi depot server can serve as a DHCP server.
It is possible to manage the DHCP server configuration automatically with opsi.

To do this, install the ICS DHCP server on the opsi server. The name of the package depends on the Linux distribution used; it is called either `isc-dhcp-server` or `dhcp-server`. If in doubt, refer to the manual or the package sources of the Linux system.

NOTE: The preconfigured virtual machine (see chapter xref:server:installation/preconfigured-vm.adoc[Preconfigured virtual machine]) is already equipped with a DHCP server. It is configured so that it only assigns IP addresses to known clients (no free leases).

[[server-components-dhcp-on-opsi-server-autoconf]]
=== Automatic DHCP configuration

opsi can configure the DHCP server automatically if it is installed on the opsi server. In this case, opsi also creates and updates client entries. All you have to do is enter the MAC address and, if necessary, the IP address, for example if you create a client via the management interface *opsi-configed* (see chapter xref:gui:configed.adoc[Management interface *opsi-configed*]).

You configure the automatic DHCP configuration via opsi in the file `/etc/opsi/backends/dhcpd.conf` on the opsi config server, e.g. like this:

[source,toml]
----
# -*- coding: utf-8 -*-

module = 'DHCPD'

config = {
    "enabled":                 True,
    "dhcpdOnDepot":            True,
    "fixedAddressFormat":      "FQDN", # or IP
    "dhcpdConfigFile":         "/etc/dhcp/dhcpd.conf",
    "reloadConfigCommand":     "sudo service isc-dhcp-server restart",
    "defaultClientParameters": { "next-server": "10.11.12.13" }
}
----

The configuration parameters have the following meaning:

* `enabled`:
  ** `True`: The automatic configuration is enabled.
  ** `False`: The automatic configuration is deactivated.
* `dhcpdOnDepot`:
  ** `False`: The DHCP server on the opsi config server manages all clients.
  ** `True`: The clients are managed in the DHCP configuration of the assigned depot.
* `fixedAddressFormat`:
  ** `FQDN`: The FQDN is used as the address for the client entries.
  ** `IP`: The IP address is used for the client entries.
* `dhcpdConfigFile`: The path to the ISC DHCP configuration file; if this entry is missing, the path is determined automatically (recommended and default).
* `reloadConfigCommand`: The command that is executed after changes to the configuration file in order to activate it. If this entry is missing, the command is determined automatically (recommended and default).
* `defaultClientParameters`: Client configuration parameters to be set for each client; if this entry is missing, they are determined automatically (recommended and default).

[[server-components-external-dhcp-server]]
== External DHCP server

If you want to use the PXE boot functionality of the opsi server and there is already a DHCP server in your network that should also manage the opsi clients, you must adapt the configuration of this DHCP server:

* *Boot server (DHCP option 66)*: Enter the IP address of your opsi depot server for the boot server.
* *Boot filename (DHCP option 67)*: Configure your DHCP server to assign `opsi/opsi-linux-bootimage/loader/shimx64.efi.signed` as the boot filename to UEFI devices and `opsi/opsi-linux-bootimage/loader/opsi-netboot.bios` as the boot filename to legacy BIOS devices.

The following example shows a configuration of an ISC DHCP server:

[source,toml]
----
next-server 10.10.1.2;
if substring (option vendor-class-identifier, 19, 1) = "0" {
	filename "opsi/opsi-linux-bootimage/loader/opsi-netboot.bios";
}
else if substring (option vendor-class-identifier, 19, 1) = "7" {
	filename "opsi/opsi-linux-bootimage/loader/shimx64.efi.signed";
}
----
