////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      07.11.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-components-network]]
= Network configuration

The opsi server supports both protocols, IPv4 and IPv6.

NOTE: A dual-stack configuration is usually available for the server, i.e. it uses IPv4 and IPv6 addresses/routes in parallel in the network. This enables communication between devices and services that are capable of both IPv4 and IPv6.

[[server-components-network-ports]]
== Protocols and ports used

The opsi server requires internet access via HTTP and HTTPS, especially for accessing package repositories of the underlying Linux distribution (e.g. `download.opensuse.org`) and the opsi packages (`download.uib.de`), but also for accessing Grafana addons etc. 

TIP: If you are using a proxy server, please also read the section <<server-components-http-proxy>>.

The opsi server and its services also use these network protocols and ports:

* *53/tcp+udp*: DNS queries
* *4447/tcp*: for accessing the opsi config server to the opsi package sources of the depot server
*445/tcp* or *22/tcp*: Different protocols and ports are used for the deployment of the `opsi-deploy-client-agent`; these depend on the client's operating system. Windows clients require access via the CIFS protocol (*445/tcp*), Linux and macOS clients require access via SSH (*22/tcp*).
*4441/tcp*: Depending on the HostControl configuration (see section xref:server:components/opsiconfd.adoc#server-components-opsiconfd-host-control[HostControl]), the opsi server addresses the client agent via *4441/tcp*.
* *4447/tcp*: Standard port for the central opsi service `opsiconfd` (see chapter xref:server:components/opsiconfd.adoc[The service *opsiconfd*]); all clients, depot servers and admin devices require access to this port.
*445/tcp*: for accessing the opsi depot server via Samba/CIFS (see chapter xref:server:components/samba.adoc[Samba]); not required if the depot server is accessed via WebDAV

NOTE: For the use of Netboot via TFTP, access to additional ports is required (see chapter xref:server:components/tftpd.adoc[TFTP-Server]). To be able to reach the opsi server via SSH, access to *22/tcp* (incoming) must be possible.

[[server-components-http-proxy]]
== Proxy configuration

include::server:partial$http-proxy.adoc[]
