////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      10.01.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-components-network]]
= Network Configuration

The opsi server is compatible with both IPv4 and IPv6 protocols.

NOTE: The server typically operates with a dual-stack configuration, meaning it uses IPv4 and IPv6 addresses/routes simultaneously within the network. This dual capability facilitates communication between devices and services that support both IPv4 and IPv6.

[[server-components-network-ports]]
== Used Protocols and Ports

The opsi server requires internet access through HTTP and HTTPS, particularly for accessing package repositories of the underlying Linux distribution (such as https://download.opensuse.org/) and the opsi packages (https://opsipackages.43.opsi.org/), as well as for accessing Grafana addons and similar services.

TIP: If you are using a proxy server, please refer to the section <<server-components-http-proxy>> for more information.

The opsi server and its services also rely on the following network protocols and ports:

* **53/tcp+udp**: For DNS queries.
* **4447/tcp**: Used for accessing the opsi config server and the opsi package sources of the depot server.
* **445/tcp** or **22/tcp**: Different protocols and ports for deploying the `opsi-deploy-client-agent`, depending on the client's operating system. Windows clients need access via the CIFS protocol (**445/tcp**), while Linux and macOS clients require SSH access (**22/tcp**).
* **4441/tcp**: Depending on the HostControl configuration (refer to section xref:server:components/opsiconfd.adoc#server-components-opsiconfd-host-control[The *hostcontrol.conf* File]), the opsi server communicates with the client agent over **4441/tcp**.
* **4447/tcp**: This is the standard port for the central opsi service `opsiconfd` (see chapter xref:server:components/opsiconfd.adoc[*opsiconfd* Service]). All clients, depot servers, and admin devices need access to this port.
* **445/tcp**: For accessing the opsi depot server via Samba/CIFS (refer to chapter xref:server:components/samba.adoc[Samba]). This is not required if the depot server is accessed via WebDAV.

NOTE: For Netboot services using TFTP, access to additional ports is necessary (see chapter xref:server:components/tftpd.adoc[TFTP Server]). Additionally, to enable SSH access to the opsi server, incoming connections on **22/tcp** must be permitted.

[[server-components-http-proxy]]
== Proxy Configuration

include::server:partial$http-proxy.adoc[]
