////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      07.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]


[[server-components-opsipxeconfd]]
= *opsipxeconfd* service

The `opsipxeconfd` service creates named pipes on the opsi depot server for clients that start via PXE boot (see chapter xref:server:components/dhcp-server.adoc[DHCP server/PXE boot]). These named pipes are used to enable a unique configuration for the clients. When they are created, they are initially empty until a client makes a read request. Only then are the named pipes dynamically filled with the corresponding data. Once the data has been read, the named pipes are removed again.

NOTE: This method enables flexible and temporary configuration of the clients via named pipes without having to permanently save files or configuration information on the clients. 

[[server-components-opsipxeconfd-config]]
== Configuration

You can configure the `opsipxeconfd` via the file `/etc/opsi/opsipxeconfd.conf`, via environment variables or via command line parameters when calling it. The following sequence applies:

. Entries in the configuration file overwrite the default settings.
. Environment variables overwrite entries in the configuration file.
. Command line parameters overwrite environment variables.

TIP: You can obtain a list of all configuration options by entering the following command in a terminal window:

// cSpell:disable
[source,console]
----
opsipxeconfd --help
...
--pxe-conf-template PXECONFTEMPLATE
                              Location of the pxe config template. [env var:
                              OPSIPXECONFD_PXE_CONF_TEMPLATE] (default:
                              /tftpboot/opsi/opsi-linux-bootimage/cfg/install-x64)
...
----
// cSpell:enable

The name of the command line parameter (e.g. `--pxe-conf-template`) is followed by the corresponding environment variable in capital letters (here: `OPSIPXECONFD_PXE_CONF_TEMPLATE`). If you take a look at the configuration file, you will see that the option here is called (`pxe config template`).

* In the configuration file `/etc/opsi/opsipxeconfd.conf` you will find e.g.:

[source,toml]
----
pxe config template = /tftpboot/opsi/opsi-linux-bootimage/cfg/install-x64
----

* This is how it is set up via the environment variable:

[source,console]
----
OPSIPXECONFD_PXE_CONF_TEMPLATE=" /tftpboot/opsi/opsi-linux-bootimage/cfg/install-x64"
----

* The call on the command line looks like this:

[source,console]
----
opsipxeconfd --pxe-conf-template /tftpboot/opsi/opsi-linux-bootimage/cfg/install-x64
----

NOTE: You can usually apply changes to the configuration during operation using the command `opsipxeconfd reload`. 
[[server-components-opsipxeconfd-cli]]
== Commandline commands

In addition to the commands mentioned, `opsipxeconfd` knows a few more commands. For example, `opsipxeconfd status` checks connections. To update the boot configuration of a client, enter this command:

[source,console]
----
opsipxeconfd update <clientId>
----

To update the boot configuration of a client from a specific cache file:

[source,console]
----
opsipxeconfd update <clientID> <pfad-zur-cache-datei>
----

Normally, systemd takes care of starting and stopping the service. It is also possible to stop (`opsipxeconfd stop`) or start (`opsipxeconfd start`) the service manually.

