////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      07.11.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-components-redis]]
= Redis

//TODO: vervollständigen, gegenlesen

Since opsi 4.2, the opsi server requires access to a Redis server (port 6379). Redis (Remote Dictionary Server) is an in-memory database with a simple key-value data structure (Key Value Store), i.e. a non-relational database. opsi uses Redis primarily so that several worker processes on a system can communicate with each other. 

NOTE: If you have installed the `opsi-server-full` package during the server installation (see chapter xref:server:installation/installation.adoc[Installation and deploying]), the Redis server and the RedisTimeSeries module are automatically installed and set up on the opsi server. If you want to run Redis on a different server, you can install `opsi-server` or `opsi-server-expert` instead and then install the two packages `redis-server` or `redis-timeseries` on this other server.

The opsiconfd admin page displays Redis status information, executes Redis commands and clears the Redis cache (see section xref:server:components/opsiconfd.adoc#server-components-opsiconfd-admin-page-redis-interface[Redis-Interface]).

[[server-components-redis-config]]
== Configuration

The file `/etc/redis/redis.conf` contains the configuration for the Redis server customized by the opsi developers, which loads the RedisTimeSeries module, among other things. It is also set here that Redis runs as a service in the background and listens on port 6379 on all interfaces. The configuration also determines the log level (`notice`) and the log file (`/var/log/redis/redis-server.log`).

The file specifies that a database dump is written to the file `dump.rdb`, which is located in the directory `/var/lib/redis` (see also section xref:server:components/backup.adoc#server-components-backup-redis[Backup of the Redis database]).

