////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      07.11.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-components-samba]]
= Samba

The files of an opsi repository server are accessed via WebDAV or Samba. Samba is the standard -- except for Docker (see section xref:server:installation/docker.adoc[opsi as Docker container]), because the Docker container only supports WebDAV.

TIP: `opsiconfd setup` (see section xref:server:components/opsiconfd.adoc#server-components-opsiconfd-setup[*opsiconfd setup*]) makes some adjustments to the Samba configuration and automatically creates the following shares, among others:

* *opsi_depot* (`/var/lib/opsi/depot`): Access to the product depot (read-only)
* *opsi_depot_rw* (`/var/lib/opsi/depot`): Access to the product depot (read-write)
* *opsi_images* (`/var/lib/opsi/ntfs-images`): Access to storing NTFS images (read-write)
* *opsi_workbench* (`/var/lib/opsi/workbench`): Access to the product workbench (read-write)
* *opsi_repository* (`/var/lib/opsi/repository`): Access to the product repository (read-only)
* *opsi_logs* (`/var/log/opsi`): Access to the directory with log files (read-only)

[[server-components-samba-depot-user]]
== Access to the shares

By default, the opsi clients use the user `pcpatch` to access the `opsi_depot` share (see chapter xref:server:components/authorization.adoc[Authorizations]). To mount the depot shares, enter the domain and user name. To do this, use the host parameter `clientconfig.depot.user`:

[source,toml]
----
config: clientconfig.depot.user = opsiserver\pcpatch
----

Now the domain `opsiserver` and the user `pcpatch` are used for authentication when mounting the share.

NOTE: If the opsi server is a member of a Windows/Samba 4 domain and the user `pcpatch` is a domain user, then `<domain name>\pcpatch` or `<NetBIOS name of the opsi server>\pcpatch` is used here.

You can configure this either via the `opsi-configed` management interface (see section xref:gui:configed.adoc#opsi-manual-configed-hostproperties[Host parameters: Client and server configuration]) or on the command line with the `opsi-admin` tool (see section xref:server:components/commandline.adoc#server-components-opsi-admin[*opsi-admin*]):

[source,console]
----
opsi-admin -d method config_createUnicode clientconfig.depot.user "clientconfig.depot.user" opsiserver\pcpatch
----

