////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      06.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-components-samba]]
= Samba

Der Zugriff auf die Dateien eines opsi-Depotservers erfolgt über WebDAV oder Samba. Samba ist der Standard -- außer bei Docker (siehe Kapitel xref:server:installation/docker.adoc[opsi als Docker-Container]), denn der Docker-Container unterstützt ausschließlich WebDAV.

TIP: `opsiconfd setup` (siehe Abschnitt xref:server:components/opsiconfd.adoc#server-components-opsiconfd-setup[*opsiconfd setup*]) nimmt einige Anpassungen an der Samba-Konfiguration vor und legt unter anderem die folgenden Freigaben automatisch an:

* *opsi_depot* (`/var/lib/opsi/depot`): Zugriff auf das Produkt-Depot (read-only)
* *opsi_depot_rw* (`/var/lib/opsi/depot`): Zugriff auf das Produkt-Depot (read-write)
* *opsi_images* (`/var/lib/opsi/ntfs-images`): Freigabe zur Ablage von NTFS-Images (read-write)
* *opsi_workbench* (`/var/lib/opsi/workbench`): Zugriff auf die Produkt-Workbench (read-write)
* *opsi_repository* (`/var/lib/opsi/repository`): Zugriff auf das Produkt-Repository (read-only)
* *opsi_logs* (`/var/log/opsi`): Zugriff auf das Verzeichnis mit Logfiles (read-only)

[[server-components-samba-depot-user]]
== Zugriff auf die Freigaben

Die opsi-Clients verwenden für den Zugriff auf die Freigabe `opsi_depot` in der Voreinstellung den Benutzer `pcpatch` (siehe Kapitel xref:server:components/authorization.adoc[Berechtigungen]). Für das Mounten der Depot-Freigaben geben Sie den Domain- und Benutzernamen an. Dazu verwenden Sie den Host-Parameter `clientconfig.depot.user`:

[source,toml]
----
config: clientconfig.depot.user = opsiserver\pcpatch
----

Jetzt kommt beim Mounten der Freigabe zur Authentifizierung die Domain `opsiserver` und der Benutzer `pcpatch` zum Einsatz.

NOTE: Ist der opsi-Server Mitglied einer Windows-/Samba-4-Domäne und der Benutzer `pcpatch` ein Domänen-Benutzer, dann steht hier `<Name der Domäne>\pcpatch` oder `<NetBIOS-Name des opsi-Servers>\pcpatch`.

Die Konfiguration nehmen Sie entweder über die Managementoberfläche `opsi-configed` vor (siehe Abschnitt xref:configed:configed.adoc#opsi-manual-configed-hostproperties[Host-Parameter: Client- und Serverkonfiguration]) oder auf der Kommandozeile mit dem Tool `opsi-admin` vor (siehe Abschnitt xref:server:components/commandline.adoc#server-components-opsi-admin[*opsi-admin*]):

[source,console]
----
opsi-admin -d method config_createUnicode clientconfig.depot.user "clientconfig.depot.user" opsiserver\pcpatch
----

