////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      16.01.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-components-samba]]
= Samba

Files on an opsi repository server are accessed through WebDAV or Samba. Samba is the standard method, except in the case of Docker (refer to the section xref:server:installation/docker.adoc[opsi as Docker container]), as the Docker container supports only WebDAV.

TIP: The `opsiconfd setup` command (see section xref:server:components/opsiconfd.adoc#server-components-opsiconfd-setup[*opsiconfd setup*]) not only modifies the Samba configuration but also automatically creates several shares, including:

* *opsi_depot* (`/var/lib/opsi/depot`): Access to the product depot (read-only)
* *opsi_depot_rw* (`/var/lib/opsi/depot`): Access to the product depot (read-write)
* *opsi_images* (`/var/lib/opsi/ntfs-images`): Access to storing NTFS images (read-write)
* *opsi_workbench* (`/var/lib/opsi/workbench`): Access to the product workbench (read-write)
* *opsi_repository* (`/var/lib/opsi/repository`): Access to the product repository (read-only)
* *opsi_logs* (`/var/log/opsi`): Access to the directory with logfiles (read-only)

[[server-components-samba-depot-user]]
== Access to the Shares

By default, opsi clients access the `opsi_depot` share using the user `pcpatch` (for more details, see chapter xref:server:components/authorization.adoc[Authorizations]). To mount the depot shares, it's necessary to specify the domain and username. This is done using the host parameter `clientconfig.depot.user`:

[source,toml]
----
config: clientconfig.depot.user = opsiserver\pcpatch
----

With this configuration, the domain `opsiserver` and the user `pcpatch` are used for authentication when mounting the share.

NOTE: If the opsi server is part of a Windows/Samba 4 domain and the user `pcpatch` is a domain user, then you should use `<domain name>\pcpatch` or `<NetBIOS name of the opsi server>\pcpatch` for authentication.

This setting can be configured either through the `opsi-configed` management interface (refer to section xref:gui:configed.adoc#opsi-manual-configed-hostproperties[Host Parameters: Client and Server Configuration]) or via the command line using the `opsi-admin` tool (see section xref:server:components/commandline.adoc#server-components-opsi-admin[*opsi-admin*]):

[source,console]
----
opsi-admin -d method config_createUnicode clientconfig.depot.user "clientconfig.depot.user" opsiserver\pcpatch
----

