////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      07.11.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-components-tftpd]]
= TFTP-Server

The Trivial File Transfer Protocol is a simplified protocol for transferring files over a network. Unlike FTP or SFTP, TFTP only offers basic functions. TFTP is often used to transfer firmware updates, configuration files or startup files from a TFTP server to a TFTP client.

NOTE: As TFTP does not support authentication, encryption or compression of the transferred data, it is normally only used in closed and trusted networks.

The TFTP server provides opsi boot images for the opsi clients. The default TFTP server for opsi is called `opsi-tftpd-hpa`; the package is automatically installed as a dependency of the `opsi-server-full` package.

The `opsi-tftpd-hpa` starts automatically at system startup by default. To stop it, enter the command `sudo systemctl stop opsi-tftpd-hpa.service`; `sudo systemctl start opsi-tftpd-hpa.service` starts the service again.

The TFTP service usually starts with a verbose parameter, which provides detailed information in the log files. You can adjust the log level for troubleshooting or analysis. To do this, use the following command:

[source,console]
----
sudo systemctl edit --full opsi-tftpd-hpa.service
----

In the text editor, search for the line that begins with `ExecStart` and replace `-v` with `--verbosity <log-level>`, e.g. `--verbosity 7` for lots of details. Then restart the service:

[source,console]
----
sudo systemctl restart  opsi-tftpd-hpa.service
----

[[server-components-tftpd-ports-firewall]]
== TFTP ports and firewall configuration

The client initially connects to port 69 on the server.
However, the server does not send any packets via port 69. Instead, the client and server select so-called TIDs for further communication. A transaction identifier is an identifier used to uniquely identify transactions. The TIDs correspond to UDP ports and range from 1024 to 65535. All packets are then sent from the server's TID port to the client's TID port and vice versa.

The server firewall must therefore be configured to allow incoming connections on port 69/udp.
In addition, UDP communication between the TID ports must be permitted.
The easiest way to do this is via the kernel module `ip_conntrack_tftp` or `nf_conntrack_tftp`.
