////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      19.12.2022
:doctype: book

include::common:partial$opsi_terms.adoc[]

[[opsi-manual-abo-products-introduction]]
= opsi subscriptions

[[opsi-manual-abo-products-introduction-firststeps]]
== Initial Deployment of opsi subscriptions

To provide the required packages, you can download them manually or install all packages after editing the configuration of the `opsi-package-updater`.

[[opsi-manual-abo-products-introduction-third]]
== Configuration of the `opsi-package-updater` / updating the opsi subscriptions

For further operation it is recommended to save the repository configuration in '/etc/opsi/package-updater.repos.d/'.
You will receive a corresponding configuration file with your access data.

WARNING: If using a proxy, the access must be configured in these files!

It then offers to ony install the required packages from the new repositories:
[source,shell]
----
# Example: Install packages for mshotfix, OS Windows 10 x64 2009-22h2 / Server 2016 / 2019 / 2022 / Windows 11 22H2
opsi-package-updater --repo uib_abo_mshotfix install mshotfix mshotfix-win10-2009-x64-glb mshotfix-win10-1607-x64-glb mshotfix-win10-1809-x64-glb mshotfix-win2022 mshotfix-win11-22h2
# Example: Install packages for Office 2016
opsi-package-updater --repo uib_abo_msoffice install office_2016_hotfix
# Example: Install packages for the standard opsi products: firefox and libreoffice
opsi-package-updater --repo uib_abo_standard install firefox libreoffice
----

It is possible to install only required packages, e.g. only the packages to update Windows 1022h2 and Windows 11 22h2:
[source,shell]
----
opsi-package-updater -v install mshotfix mshotfix-win10-2009-x64-glb mshotfix-win11-22h2
----

To update the packages the usage of `opsi-package-updater` is recommended.

By executing `opsi-package-updater -v update` you can update the installed packages, for example via a cronjob.

An equivalent is to update the packages for each repository:
[source,shell]
----
# Updating packages for mshotfix
opsi-package-updater --repo uib_abo_mshotfix update
# Updating packages for msoffice
opsi-package-updater --repo uib_abo_msoffice update
# Updating packages for standard products
opsi-package-updater --repo uib_abo_standard update
----


[[opsi-manual-abo-products-introduction-second]]
== Configuration of default properties

When installing opsi packages non-interactively, the default properties of the packages are saved as default on a 'opsi-Configserver' or '{opsi-Server}'.

As of opsi version 4.0.5, the default properties of the '{opsi-Server}' can be set via the management interface '{opsi-Configed}'.

If you subsequently install a newer package version using `opsi-package-manager` or `opsi-package-updater`, the default properties of the depot will be retained.





[[opsi-manual-abo-products-mshotfix]]
== Subscription 'MS-Hotfixes'
Regular updates for the product MS-Hotfix (OS hotfixes for Windows 2012, Windows 8.1 / 2012-R2, Windows 10 / Windows 2016 / Windows 2019 / Windows 2022 / Windows 11).

WARNING: Versions no longer supported by Microsoft are displayed as "failed": 1507 "non"-LTSB, 1511 and 1607 "non"-LTSB except Education and Enterprise versions.

The updates will be available within three working days after the release of a patch that Microsoft considers to be important or critical.

https://www.microsoft.com/en-us/msrc/security-update-severity-rating-system
[options="header"]
|==========================
| Rating | Description
| Critical | A vulnerability whose exploitation could allow code execution without user interaction. These scenarios include self-propagating malware (e.g. network worms), or unavoidable common use scenarios where code execution occurs without warnings or prompts. This could mean browsing to a web page or opening email.
Microsoft recommends that customers apply Critical updates immediately.
| Important | A vulnerability whose exploitation could result in compromise of the confidentiality, integrity, or availability of user data, or of the integrity or availability of processing resources. These scenarios include common use scenarios where client is compromised with warnings or prompts regardless of the prompt's provenance, quality, or usability. Sequences of user actions that do not generate prompts or warnings are also covered.
Microsoft recommends that customers apply Important updates at the earliest opportunity.
| Moderate | Impact of the vulnerability is mitigated to a significant degree by factors such as authentication requirements or applicability only to non-default configurations.
Microsoft recommends that customers consider applying the security update.
| Low | Impact of the vulnerability is comprehensively mitigated by the characteristics of the affected component. Microsoft recommends that customers evaluate whether to apply the security update to the affected systems.
|==========================

The opsi-mshotfix package uses (like WSUS Offline Update http://forums.wsusoffline.net/viewtopic.php?f=7&t=172 coverage of WSUS Offline Update) to download Microsoft's update catalog file wsusscn2.cab, to identify the required patches.
This catalog file contains at least all the "critical" and "security-relevant" updates, but not necessarily all the "important" and "optional" updates.

The opsi mshotfix packages have a modular structure.
The basic package "mshotfix" contains only a script for installing the patches. The actual patches are contained in separate packages.

.mshotfix Client Requirements
|==========================================
|OS
|Windows 7 SP1 / Windows 2008 R2 SP1
|Windows 8 / Windows 2012
|Windows 8.1 / Windows 2012 R2
|Windows 10 / Windows 2016 / Windows 2019 / Windows 2022
|Windows 11
|==========================================


WARNING: WAN/VPN extension: The packages for Windows 11 / Server 2022 require opsi-client-agent >=  4.2.0.43-1  and opsiclientd >=  4.2.0.43-1

Structure of the subscription area on our download server:

[source,configfile]
----
mshotfix
  !-opsi4/
     !-glb/	Base-package mshotfix and global packages
     		mshotfix-win7-x86-glb
     		mshotfix-win7-win2008r2-x64-glb
     		mshotfix-win8-win2012-x64-glb
     		mshotfix-win81-x86-glb
		    mshotfix-win81-win2012r2-x64-glb
		    mshotfix-win10-win2016-x64-glb
		    mshotfix-win10-x86-glb
			mshotfix-win10-1507-x64-glb
		    mshotfix-win10-1507-x86-glb
		    mshotfix-win10-1607-x64-glb
		    mshotfix-win10-1607-x86-glb
		    mshotfix-win10-1809-x64-glb
		    mshotfix-win10-1809-x86-glb
		    mshotfix-win10-2009-x86-glb
		    mshotfix-win10-2009-x64-glb
			mshotfix-win2022
			mshotfix-win11-21h2
			mshotfix-win11-22h2

     !-misc/	various additional packages
     		dotnetfx
     		dotnetfx-hotfix
     		mshotfix-uninstall
     		ms-optional-fixes
----

The following table should help you choose the right packages:

.mshotfix Client-OS
|=======================
|OS | Arch | Patch-package
|Windows 7 | 32Bit | mshotfix-win7-x86-glb
|Windows 7 | 64Bit | mshotfix-win7-win2008r2-x64-glb
|Windows 2012 | 64Bit | mshotfix-win8-win2012-x64-glb
|Windows 8.1 | 32Bit | mshotfix-win81-x86-glb
|Windows 8.1 | 64Bit | mshotfix-win81-win2012r2-x64-glb
|Windows 2008 Server R2 | 64Bit | mshotfix-win7-win2008r2-x64-glb
|Windows 2012 R2 | 64Bit | mshotfix-win81-win2012r2-x64-glb
|Windows 10 | 32Bit | mshotfix-win10-x86-glb			or the matching modular package
|Windows 10 | 64Bit | mshotfix-win10-win2016-x64-glb	or the matching modular package
|Windows 2016 | 64Bit | mshotfix-win10-win2016-x64-glb	or mshotfix-win10-1607-x64-glb
|Windows 2019 | 64Bit | mshotfix-win10-win2016-x64-glb	or mshotfix-win10-1809-x64-glb
|Windows 10 1507 LTSB | 32/64Bit | mshotfix-win10-1507-x86-glb mshotfix-win10-1507-x64-glb
|Windows 10 1607 LTSB / Windows Server 2016 | 32/64Bit | mshotfix-win10-1607-x86-glb mshotfix-win10-1607-x64-glb
|Windows 10 1809 LTSC / Windows Server 2019 | 32/64Bit | mshotfix-win10-1809-x86-glb mshotfix-win10-1809-x64-glb
|Windows 10 2009/21h2/22h2 | 32/64Bit | mshotfix-win10-2009-x86-glb mshotfix-win10-2009-x64-glb
|Windows Server 2022 | 64Bit | mshotfix-win2022
|Windows 11 21h2 | 64Bit | mshotfix-win11-21h2
|Windows 11 22h2 | 64Bit | mshotfix-win11-22h2
|=======================

Installation:
[source,shell]
----
opsi-package-manager -i mshotfix_201008-1.opsi
----
To set to setup wherever the product is installed:
[source,shell]
----
opsi-package-manager -iS mshotfix_201008-1.opsi
----

In addition to the basic package, the patch packages are installed in the same way. However, since these packages do not contain any installation scripts, they can only be used together with the basic package, i.e. you cannot set them separately on setup.
The mshotfix basic package is responsible for the client installation.

Since package mshotfix 201304-1, a list of patches installed by mshotfix is stored locally in the file `C:\opsi.org\mshotfix\deployed.txt`.

Caution:: Since package mshotfix 201808-3, the current Servicing Stack is installed first, followed by an immediate reboot.

noreboot:: noreboot=on: Don't Reboot if possible  Warning will be logged if a reboot is required. Will be ignored for Servicing stacks
values: ["off", "on"]
default: ["off"]

force:: force=on: All Hotfixes will be forced installed
values: ["off", "on"]
default: ["off"]

excludes::  Commaseparated list with kb-numbers or ms-no, that will be excluded (Only Number without beginning kb and no spaces. Example: 123456,789011,976002

severity:: choose the severity that will be installed. Possible Entries are Critical, Important, Moderate, all
values: ["Critical", "Important", "Moderate", "all"]
default: ["Critical", "Important"]

excludelist-superseded.txt:: Use File ExcludeList-superseded.txt
values: ["", "ExcludeList-superseded.txt"]
default: [""]

monthly-updates::  Handle windows-7-and-windows-8-1 : security Only Quality Update vs Monthly Quality Rollup (see link:https://blogs.technet.microsoft.com/windowsitpro/2016/08/15/further-simplifying-servicing-model-for-windows-7-and-windows-8-1/[Further simplifying servicing models for Windows 7 and Windows 8.1], link:https://blogs.technet.microsoft.com/windowsitpro/2016/10/07/more-on-windows-7-and-windows-8-1-servicing-changes/[More on Windows 7 and Windows 8.1 servicing changes], link:https://blogs.msdn.microsoft.com/dotnet/2016/10/11/net-framework-monthly-rollups-explained/[.NET Framework Monthly Rollups Explained])
values: ["all", "monthly_quality_rollup", "security_only_quality_update"]
default: ["security_only_quality_update"]

=== misc mshotfix-uninstall

----
mshotfix-uninstall        201512-1                  MS Hotfix BasePackage
----

Removes patches that can be uninstalled via `wusa /uninstall  ...`.

excludes:: Commaseparated list with kb-numbers or ms-no, that will be excluded (Only Number without beginning kb and no spaces. Example: 2553154,ms14-082)

noreboot:: noreboot=on: Don't Reboot.  Warning will be logged if a reboot is required.
values: ["off", "on"]
default: ["off"]

removefromdeployed.txt:: Remove from deployed.txt
default: False

removekb:: Remove KBXXXXX, (Only Number without beginning kb and no spaces f.e. 3097877)
multivalue: True
default: [""]

=== misc dotnetfx

----
dotnetfx                  4.7.2-3                 .NET Framework
----

Package for installing NET Framework versions 4.5 and higher, especially on Windows 7 / 2008 R2 / 8.1 / 2012 R2 / 10
NET 3.5 can also be installed on Windows installations (newer than Windows 7).

version:: The Microsoft .NET Framework 4.8 is a highly compatible, in-place update to the Microsoft .NET Framework 4, 4.5, 4.5.1, 4.5.2, 4.6, 4.6.1, 4.6.2, 4.7 , 4.7.1 and 4.7.2 +
values: ["3.5", "4.0", "4.5", "4.5.1", "4.5.2", "4.6", "4.6.1", "4.6.2", "4.7", "4.7.1", "4.7.2", "latest", "latestAnd3.5"] +
default: ["latest"]

rerundotnethotfix::rerun dotnetfx-hotfix after installation if possible
values: ["false", "true"]
default: ["true"]

install_language_languagepack:: install_language_languagepack
values: ["auto", "de", "en", "fr"]
default: ["auto"]

os-package:: Here you can switch from which OS-Version to be install Dotnet3.5,
auto=win10 or opsi-local-image-win10 (default); other ProductID for netboot-product
values: ["auto", ]
default: ["auto"]

=== misc dotnetfx-hotfix

----
dotnetfx-hotfix           201808-1                  dotnetfx-hotfix
----

The 'MS-Hotfixes' update subscription only contains the hotfixes for 'Microsoft .NET Framework' that are applicable for the respective operating system.
E.g. Windows 7 came with "Microsoft .NET Framework 3.5.1"

(However, since October 2016 there have also been irregular "Monthly Rollups" for DotnetFramework, which are included in the mshotfix package.)

The dotnetfx-hotfix package contains the hotfixes from Microsoft for

- Microsoft .NET Framework 4 and higher for Windows 7

The package dotnetfx-hotfix is currently patching versions 4.x - if available - to the newest version of the series.

Please note:
"Support for .NET Framework 4, 4.5, and 4.5.1 ended on January 12, 2016"
(https://support.microsoft.com/en-us/lifecycle?p1=14380)

respectivly

https://support.microsoft.com/en-us/lifecycle#gp/Framework_FAQ

noreboot:: noreboot=on: Don't Reboot.  Warning will be logged if a reboot is required.
values: ["off", "on"]
default: ["off"]

force:: force=on: All Hotfixes will be installed forced
values: ["off", "on"]
default: ["off"]

severity:: choose the severity that will be installed.Possible Entries:Critical, Important, Moderate, all
values: ["Critical", "Important", "Moderate", "all"]
default: ["all"]


[[opsi-manual-abo-products-ms-Officehotfixes]]

==  Update subscription for 'MS-Office Hotfixes'
Regular updates for MS Office 2013/2016 32 bit/64 bit.

The updates will be available within three working days after the release of a patch that Microsoft considers to be important or critical.

.Office hotfix  Requirements
|===================================
|Office Version| required
|Office 2013 |Servicepack 1
|Office 2016 |
|===================================


[[opsi-manual-abo-products-office_2013_hotfix]]

=== Updates for MS Office 2013 32-bit international: office_2013_hotfix
----
office_2013_hotfix               201808-1                  Microsoft Office 2013 Hotfixes
----

Contains language-independent monthly Office 2013 hotfixes (including Visio 2013). Requires Service Pack 1.

Is tested with Office 2013 Professional

A list of patches installed by office_2013_hotfix is stored locally in the file `C:\opsi.org\mshotfix\office_2013_hotfix_deployed.txt`.

Since office_2013_hotfix 201503-1:

excludes:: Comma separated list with kb-numbers or ms-no, that will be excluded (Only Number without beginning kb and no spaces. Example: 2553154,ms14-082)

[[opsi-manual-abo-products-office_2016_hotfix]]
=== Updates for MS Office 2016 32-bit international: office_2016_hotfix
----
office_2016_hotfix               201808-1                  Microsoft Office 2016 Hotfixes
----

Contains language-independent monthly Office 2016 hotfixes (including Visio 2016).

Is tested with Office 2016 Professional

A list of patches installed by office_2016_hotfix is stored locally in the file `C:\opsi.org\mshotfix\office_2016_hotfix_deployed.txt`.

excludes:: Comma separated list with kb-numbers or ms-no, that will be excluded (Only Number without beginning kb and no spaces. Example: 2553154,ms14-082)

CAUTION:: If you want to install updates for MS Office 2016 32-bit and 64-bit, or only 64-bit:

Configure the repo uib_abo_msoffice update section: x3264 / x64

[[opsi-manual-abo-products-standard]]
== Update subscription for the opsi standard packages
Regular product updates for:

    Adobe Reader DC Classic / Continuous (international, 32 Bit)
    Apache OpenOffice.org (German, 32 Bit)
    Google Chromium for business (international, 32 Bit / 64 Bit)
    LibreOffice (international, 32 Bit / 64 Bit)
    Mozilla Firefox (German, English, French and Dutch, 32 Bit), respectivly as 32/64 Bit package since 201706
    Mozilla Thunderbird (German, English and French, 32 Bit)
    Java VM (javavm) based on Open JDK LTS 11 (international, 64 Bit)
    Java VM 8 (javavm8) based on Open JDK LTS 8 (international, 32 Bit / 64 Bit)
    Java VM (javavm-oracle-jdk) OpenJDK based on the actual open jdk implementation (international, 64 Bit)

Depending on contract, we also provide the following languages ​​as subscriptions:

    Mozilla Firefox (additionally in Czech, Danish, Italian, Norwegian or Spanish, 32 Bit)
    Mozilla Thunderbird (additionally in Italian, 32 Bit)

Other languages on request.

The update will be available within two working weeks after the release of an update of these products. For security updates classified as critical by the manufacturer within one working week.

=== Customizing with central configuration files

For the opsi-packages
----
adobe.reader.dc.classic
adobe.reader.dc.continuous
firefox
thunderbird
----

there is the possibility to create your own configurations and store them in the directory `custom`,
which can be selected via properties. (See below for details)

=== Customizing with preinst/postinst-scripts

For the opsi-packages
----
adobe.reader.dc.classic
firefox		(since 17.0.6esrorstandard-1)
google-chrome-for-business
javavm		(since 1.7.0.51-4 )
javavm8
javavm-oracle-jdk
libreoffice	(since 4.3.5or4.4.0-2)
ooffice		(since 4.1.1-2)
thunderbird	(since 17.0.6esrorstandard-1)
----

there is the possibility to store your own custom scripts in the directory `custom\scripts`.

Simple templates for the supported scripts can be found in the directory `opsi\scripts`.

[source,configfile]
----

custom.actions.post.setup
custom.actions.post.uninstall
custom.actions.pre.setup
custom.actions.pre.uninstall
custom.declarations
custom.sections

custom scripts will be included in
- setup-script
- uninstall-script

custom pre-scripts will be included in
- setup-script
- uninstall-script

custom post-scripts will be included in
- in setup-script
- uninstall-script

custom.declarations
; intended for declaration of custom Variables and Stringlist Variables
; will be included with "include_insert" at top of [actions]
; but after GetProductProperties

custom.sections
; intended for declaration of custom secondary sections
; will be included with "include_append" at top of [actions]
; but after GetProductProperties

custom.actions.pre.setup  (or custom.actions.pre.uninstall)
; will be included with "include_insert" at at top of [actions]
; (but after GetProductProperties)

custom.actions.post.setup (or custom.actions.post.uninstall)
; will be included with "include_insert" in case of successful installation before "endof_"actions"
; in setup-script ( or uninstall-script)

----

=== Adobe Acrobat Document Cloud Classic : adobe.reader.dc.classic
----
adobe.reader.dc.classic		20202000530418-1          Adobe Acrobat Reader DC classic
----

The adobe.reader.dc.classic-Package contains Adobe Acrobat Document Cloud Classic (MUI-Version)

Adaptation in the transform file *.mst
[source,shell]
----
cat transform.txt
Changes vs default the transform file *.mst

Personalization Options
Suppress Eula

Installation Options
acivated - Make Reader the default PDF viewer
IF REBOOT REQUIRED - suppress reboot

Shortcuts
deactivated - Destination Computer/Desktop/Adobe Reader XI (Icon)

Online and Acrobat.com Features
Online Features
activated - Disable product updates
Enable & Ask before Installing - Load trusted root certificates from Adobe

Online Services and Features
disable product updates
Load trusted root certificates from Adobe disable
DISABLE all Services
----

adobereader.mst::
The Adobe Reader package from uib uses a standard transform file created with the Adobe Customization Wizard.
Additionally, custom MST files can be stored in the directory `/var/lib/opsi/depot/adobe.reader.dc.classic/custom` on the share `opsi_depot`. These can be selected via this property (after reinstalling package using `opsi-package-manager -i <adobe-package>`).

When importing the adobe.reader.dc.classic package on the opsi server, the custom directory is retained using a preinst/postinst-script.

WARNING: opsi WAN/VPN extension: The package must be reinstalled with 'opsi-package-manager' after changes in the `custom` directory, so that the file `<productid>.files` is updated.

client_language::
The adobe.reader.dc.classic-package contains Adobe Acrobat Document Cloud Classic (MUI-Version)
"auto" tries to install the correct language. values: ["auto", "de", "en", "fr"] default: ["auto"]

classicversion::
description: https://helpx.adobe.com/acrobat/release-note/release-notes-acrobat-reader.html Classic Track (2015 Release) or (2017 Release)
values: ["2020"]
default: ["2020"]

disableadobeacrobatupdateservice::
Disable Adobe Acrobat Update Service and remove Adobe Acrobat Update Task
values: ["false", "true"]
default: ["false"]

removebeforesetup::
remove target version of adobe reader before install
values: ["false", "true"]
default: ["false"]

noreboot::
description: noreboot=true: Don't Reboot.  Warning will be logged if a reboot is required.
values: ["false", "true"]
default: ["false"]


=== Adobe Acrobat Document Cloud Continuous : adobe.reader.dc.continuous
----
adobe.reader.dc.continuous	201901020099-1							Adobe Acrobat Reader DC Continuous
----

The adobe.reader.dc.classic-Package contains Adobe Acrobat Document Cloud Continuous (MUI-Version)

Adaptation in the transform file *.mst
[source,shell]
----
cat transform.txt
Changes vs default the transform file *.mst

Personalization Options
Suppress Eula

Installation Options
acivated - Make Reader the default PDF viewer
IF REBOOT REQUIRED - suppress reboot

Shortcuts
deactivated - Destination Computer/Desktop/Adobe Reader (Icon)

Online and Acrobat.com Features
Online Features
activated - Disable product updates
Enable & Ask before Installing - Load trusted root certificates from Adobe

Online Services and Features
disable product updates
Load trusted root certificates from Adobe disable
DISABLE all Services
----

adobereader.mst::
The Adobe Reader package from uib uses a standard transform file created with the Adobe Customization Wizard.
Additionally, custom MST files can be stored in the directory `/var/lib/opsi/depot/adobe.reader.dc.continuous/custom` on the share `opsi_depot`. These can be selected via this property (after reinstalling package using `opsi-package-manager -i <adobe-package>`).

When importing the adobe.reader.dc.continuous package on the opsi server, the custom directory is retained using a preinst/postinst-script.

WARNING: opsi WAN/VPN extension: The package must be reinstalled with 'opsi-package-manager' after changes in the `custom` directory, so that the file `<productid>.files` is updated.

client_language::
The adobe.reader.dc.classic-package contains Adobe Acrobat Document Cloud Classic (MUI-Version)
"auto" tries to install the correct language. values: ["auto", "de", "en", "fr"] default: ["auto"]

disableadobeacrobatupdateservice::
Disable Adobe Acrobat Update Service and remove Adobe Acrobat Update Task
values: ["false", "true"]
default: ["false"]

removebeforesetup::
remove target version of adobe reader before install
values: ["false", "true"]
default: ["false"]

noreboot::
description: noreboot=true: Don't Reboot.  Warning will be logged if a reboot is required.
values: ["false", "true"]
default: ["false"]

[[opsi-manual-abo-products-standard-google-chrome]]
=== Google Chromium for Business
----
google-chrome-for-business	108.0.5359.125-1
----

This package contains the msi installer from Google (see Chrome for Business FAQ https://support.google.com/chrome/a/answer/188447?hl=en )

remarks:

The uninstallation and installation of google-chrome.msi sometimes fails.

Therefore there are different approaches in the opsi package to increase the reliability of the installation.

One customer reported a success rate of 100% for 40 installations with the following property settings:

* `install_architecture`: 32
* `reboot_on_retry`: True
* `reboot_after_uninstall`: True
* `timeout`: 240

In our internal tests we use:
* `install_architecture`: system specific
* `reboot_on_retry`: True
* `reboot_after_uninstall`: True
* `timeout`: notimeout


autoupdate:: !!! Will not work anymore!!!

https://support.google.com/chrome/a/answer/187207

ADM= use Policy based on Googles Template,
0=UpdatesDisabled,
1=UpdatesEnabled,
2=ManualUpdatesOnly,
3=AutomaticUpdatesOnly,
values: ["0", "1", "2", "3", "ADM"]
default: ["0"]

disablescheduledtaskgoogleupdatemachine::
Disable scheduled task GoogleUpdateTaskMachineCore and GoogleUpdateTaskMachineUA
values: ["false", "true"]
default: ["true"]

removeupdatehelper::
default: ["true"]

install_architecture::
description: which architecture (32/64 bit) has to be installed
values: ["32", "64", "system specific"]
default: ["system specific"]

reboot_on_retry::
description: If installation fails and (timeout > 0) then reboot before retry
default: False

reboot_after_uninstall::
description: reboot after uninstall old version
default: False

timeout::
description: TimeOutSeconds msi installs
values: ["240", "300", "600", "notimeout"]
default: ["notimeout"]

[[opsi-manual-abo-products-standard-openoffice]]
=== Apache OpenOffice : ooffice4
----
ooffice						4.1.13-1									Apache OpenOffice
----

The ooffice package contains Apache OpenOffice in German.

handle_excel_xls::
Should OpenOffice be used as the default for MS Excel documents?
  on = OpenOffice.org will be used as the default for MS Excel documents
  off = OpenOffice.org will not be used as the default for MS Excel documents

handle_powerpoint_ppt ::
Should OpenOffice be used as the default for MS Powerpoint documents?
  on = OpenOffice.org will be used as the default for MS Powerpoint documents
  off = OpenOffice.org will not be used as the default for MS Powerpoint documents

handle_word_doc ::
Should OpenOffice be used as the default for MS Word documents?
  on = OpenOffice.org will be used as the default for MS Word documents
  off = OpenOffice.org will not be used as the default for MS Word documents

[[opsi-manual-abo-products-standard-libreoffice]]
=== LibreOffice The Document Foundation  : libreoffice
----
libreoffice					7.3.7or7.4.3-1							LibreOffice
----

The libreoffice package contains LibreOffice international.

client_language ::
client_language - only for messages important, because libre office is international
values: ["auto", "de", "en", "fr"]

msoregister :: Open Microsoft Office documents with LibreOffice (true)
values: ["false", "true"]
default: ["false"]

libreoffice-version::
description: 'Stable' - is an Extended Support Release from LibreOffice for the conservative user - default version (7.3.7); 'Experimental' is a version for the experimental user from LibreOffice (7.4.3)
values: ["experimental", "stable"]
default: ["stable"]

hide_component::
description: Hide component base by removing desktoplink and exe file
values: ["base", "none"]
default: ["none"]

ui_languages::
description: which UI languages should be installed (comma separated), For example UI_LANGS=en_US,de,fr,hu will install English (US), German, French, and Hungarian.
default: ["auto"]

install_architecture:: which architecture (32/64 bit) has to be installed
values: ["32", "64", "system specific"]
default: ["32"]


[[opsi-manual-abo-products-standard-firefox]]
=== Mozilla Firefox : firefox
----
firefox						102.6.0esror108.0-2
----
The firefox-package contains Mozilla Firefox in German, Englisch, French and Dutch.

All by Mozilla supported versions are provided.

Firefox can be configured centrally
a) either via a central configuration file `mozilla.cfg` (see http://kb.mozillazine.org/Locking_preferences)
b) or via a `policies.json` (see https://github.com/mozilla/policy-templates/blob/master/README.md)

which must be placed in the following directory:

[source,shell]
----
/var/lib/opsi/depot/firefox/custom/
----

When the package is installed again using `opsi-package-manager -i <firefox-paket>`, the configuration files found are retained via the preinst/postinst-mechanism and can then be selected using the "mozillacfg" property.

- example:
+
[source,shell]
----
cat /var/lib/opsi/depot/firefox/custom/mozilla.cfg
//
lockPref("browser.startup.homepage", "http://www.uib.de");
lockPref("network.proxy.type", 1);
lockPref("network.proxy.http", "router.uib.local");
lockPref("network.proxy.http_port", 3128);
----

As an alternative to a mozilla.cfg, you can also integrate an autoconfig.zip created with the CCK2 using the property "mozillacfg".

WARNING: opsi WAN/VPN extension: The package must be reinstalled with 'opsi-package-manager' after changes in the `custom` directory, so that the file `<productid>.files` is updated.

client_language::
values: ["auto", "de", "en", "fr", "nl"]
default: ["auto"]

firefox-version :: Firefox 'esr' - Extended Support Release from Mozilla.org, standard is the newest version
values: ["esr", "standard"]
default: ["esr"]

commandlineoptions::
starts firefox with the supplied parameters. See https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options
values: ["", "-no-remote -Profile H:\\ProfileDir"]
default: [""]

pref_file::
in which file should the settings be made, user.js or prefs.js.
values: ["prefs", "user"]
default: ["prefs"]

noautoupdate:: (on/off): disable auto update. default=on

setproxy:: (off/direct/manual/file) proxy settings
* off= do nothing
* direct = direct connection to the internet
* manual = use proxy settings via property proxysetting
(<ip-address>:<port>) and property noproxy_hosts (host1,host2)
* file = use proxy settings via property proxysetting
(<path_to_proxyconf.pac>) and property noproxy_hosts (host1,host2)
* system
* default=off

proxysetting:: string for proxy setting (see: setproxy)

noproxy_hosts:: comma separated list of hosts

mozillacfg::
description: filename for mozilla.cfg in `%scriptpath%\custom`-directory, http://kb.mozillazine.org/Locking_preferences

profilemigrator:: enable or disable Profilemigrator on first run
values: ["off", "on"]
default: ["off"]

* *Known problems:* +
- Installation via "On Demand" may fail if Firefox is running.

[[opsi-manual-abo-products-standard-thunderbird]]
=== Mozilla Thunderbird : thunderbird
----
thunderbird					102.6.0-1
----
The thunderbird-package contains Mozilla Thunderbird in German, English and French.

All by Mozilla supported versions are provided.

Similar to the Firefox package, a central configuration file can be provided.

client_language::
values: ["auto", "de", "en", "fr"]
default: ["auto"]

thunderbird-version::
values: ["60.x"]
default: ["60.x"]

commandlineoptions::
starts thunderbird with the supplied parameters. See https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options
values: ["", "-no-remote -Profile H:\\ProfileDir"]
default: [""]

addonsactivation::
description: Enable/Disable AddOns (default = enable)
values: ["off", "on"]
default: ["on"]

https://developer.mozilla.org/en/Addons/Add-on_Manager/AddonManager

http://mike.kaply.com/2012/02/09/integrating-add-ons-into-firefox/

https://developer.mozilla.org/en/Thunderbird/Deploying_Thunderbird_in_the_Enterprise/Thunderbird_Preferences_Relevant_to_Enterprises
[source,shell]
----
Set_Netscape_User_Pref ("extensions.autoDisableScopes", 11)
Set_Netscape_User_Pref ("extensions.shownSelectionUI", true)
----

enigmail::
description: Install GnuPG-Plugin
values: ["off", "on"]
default: ["off"]

noautoupdate::
description: disable automatic updates
values: ["off", "on"]
default: ["on"]

mozillacfg::
description: filename for mozilla.cfg in `%scriptpath%\custom`-directory, http://kb.mozillazine.org/Locking_preferences

lightning::
description: Install calender plugin lightning
values: ["off", "on"]
default: ["off"]

* *Known problems:* +
- Installation via "On Demand" may fail if thunderbird is running.



[[opsi-manual-abo-products-standard-javavm]]
=== OpenJDK 11 LTS : javavm
----
javavm						11.0.17-1								JDK 11
----
The javavm-package contains the Open JDK 11 LTS implementations from SAP (SapMachine) and Amazon (Amazon Corretto) because Oracle no longer provides a freely available Java runtime (since early January 2019).

(Oracle announced "End Of Public Updates February 2019"  http://www.oracle.com/technetwork/java/eol-135779.html)


install_architecture::
description: which architecture (32/64 bit) has to be installed
values: ["64 only"]
default: ["64 only"]

javaversion::
which version has to be installed jdk Sapmachine or amazon corretto
values: ["jdkamazoncorretto", "jdksap"]
default: ["jdksap"]

keepversion::
description: Don't uninstall jre version
values: ["1.6.0_0", "1.6.0_1", "1.6.0_2", "1.6.0_3", "1.6.0_4", "1.6.0_5", "1.6.0_6", "1.6.0_7", "none"]
default: ["none"]

uninstalljava16::
description: Uninstall Java 1.6 "Patch in Place" Installations
default: True

uninstalljava17::
description: Uninstall Java 1.7 "Patch in Place" Installations
default: True

environment_set_java_home:: Set the environment variable JAVA_HOME
default: False


[[opsi-manual-abo-products-standard-javavm8]]
=== OpenJDK 8 LTS : javavm8
----
javavm8						1.8.0.352					JDK 8 LTS
----
The javam8 package contains the Open JDK 8 LTS implementations from Amazon (Amazon Corretto)

javaversion::
which version has to be installed amazon 212 or ojdkbuild 201
values: ["jdkamazoncorretto"]
default: ["jdkamazoncorretto"]

install_architecture::
which architecture (32/64 bit) has to be installed
values: ["32 only", "64 only", "both", "system specific"]
default: ["system specific"]

keepversion::
description: Don't uninstall jre version
values: ["1.6.0_0", "1.6.0_1", "1.6.0_2", "1.6.0_3", "1.6.0_4", "1.6.0_5", "1.6.0_6", "1.6.0_7", "none"]
default: ["none"]

uninstalljava16::
description: Uninstall Java 1.6 "Patch in Place" Installations
default: True

uninstalljava17::
description: Uninstall Java 1.7 "Patch in Place" Installations
default: True

environment_set_java_home:: Set the environment variable JAVA_HOME
default: False

[[opsi-manual-abo-products-standard-javavm-oracle-jdk]]
=== OpenJDK : javavm-oracle-jdk
----
javavm-oracle-jdk			19.0.1-2								Open JDK
----
The javavm-oracle-jdk-package contains the current Open JDK implementation from Oracle http://jdk.java.net/

install_architecture::
description: which architecture (32/64 bit) has to be installed
values: ["64 only"]
default: ["64 only"]

keepversion::
description: Don't uninstall jre version
values: ["1.6.0_0", "1.6.0_1", "1.6.0_2", "1.6.0_3", "1.6.0_4", "1.6.0_5", "1.6.0_6", "1.6.0_7", "none"]
default: ["none"]

uninstalljava16::
description: Uninstall Java 1.6 "Patch in Place" Installations
default: True

uninstalljava17::
description: Uninstall Java 1.7 "Patch in Place" Installations
default: True

environment_set_java_home:: Set the environment variable JAVA_HOME
default: False

