////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:Date:      17.04.2023
:doctype: book

= Welcome to opsi!

The client management system link:https://www.opsi.org/[opsi (Open System Integration)] manages Windows, Linux and macOS clients--from a dozen to several thousand computers. The core component is a Linux server which takes care of automatic installation of operating systems (Windows and Linux only), distribution of software, hardware and software inventory, and patch management on the clients. In addition, there are modules that extend the functionality. In summary, opsi has the following features:

* Automatic software distribution on the PCs (opsi client agent).
* Automatic operating system installation (using the opsi server).
* Hardware and software inventory.

opsi offers a single administration interface to manage all clients in multiple locations. The configuration is stored in a central place: on the opsi server. The depot servers for the clients (installation files of the software, operating systems to be distributed, boot images, etc.) can also be located in several places.

This manual has the following structure:

* xref:supportmatrix:supportmatrix.adoc[Supported Systems]
* xref:first-steps:first-steps.adoc[Quick Start]
* xref:server:overview.adoc[opsi-Server]
* xref:clients:opsi-clients.adoc[opsi-Clients]
* xref:gui:gui.adoc[User Interfaces]
* xref:opsi-products:products.adoc[opsi-Products]
* xref:opsi-modules:modules.adoc[opsi-Modules]
* xref:opsi-script-manual:opsi-script-manual.adoc[*opsi-script*]
* xref:troubleshooting:troubleshooting.adoc[Troubleshooting]
* xref:contribute:contribute.adoc[How to Contribute to opsi]
* xref:copyright:copyright.adoc[Copyright]

All manuals are available for download at link:https://download.uib.de/4.2/stable/documentation/[download.uib.de] in PDF, HTML, and Epub format. In addition, we have published manuals for the APIs link:https://docs.opsi.org/python-docs/python-opsi[python-opsi] and link:https://docs.opsi.org/python-docs/python-opsi-common[opsicommon].

TIP: To meet other opsi users, please visit our link:https://forum.opsi.org/index.php[opsi forum]. Here you can also find the link to our opsi Wiki.

[[opsi-intro-convention]]
== Conventions and Notations

We use the following notations and highlighting in this manual:

* File and directory names appear in `proportional font`.
* Longer commands and listings are in separate boxes; you can conveniently copy{nbsp}&{nbsp}paste them: +
[source,shell]
----
this is a command
----
* Replace the identifiers in `<angle brackets>` with their real names. For example, the file share with the opsi packages is called `<opsi-depot-share>`. On a real server it is usually located in `/var/lib/opsi/depot`, so the software package `<opsi-depot-share>/ooffice` is located in `/var/lib/opsi/depot/ooffice`.
* Menu items and button labels appear in _italics_.
* Keys and key combinations are enclosed in square brackets, e.g. [C], [Ctrl]+[C], etc.
