////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:Date:      17.04.2023
:doctype: book

= Welcome to opsi!

The client management system link:https://www.opsi.org/[opsi (Open System Integration)] manages Windows, Linux and macOS clients--from a dozen to several thousand computers. The core component is a Linux server which takes care of automatic installation of operating systems (Windows and Linux only), distribution of software, hardware and software inventory, and patch management on the clients. In addition, there are modules that extend the functionality. In summary, opsi has the following features:

* Automatic software distribution on the PCs (opsi client agent).
* Automatic operating system installation (using the opsi server).
* Hardware and software inventory.

opsi offers a single administration interface to manage all clients in multiple locations. The configuration is stored in a central place: on the opsi server. The depot servers for the clients (installation files of the software, operating systems to be distributed, boot images, etc.) can also be located in several places.

This manual has the following structure:

* xref:releasenotes:releasenotes[Release Notes]
* xref:supportmatrix:supportmatrix[Supported Systems]
* xref:getting-started[opsi Server]
* xref:windows-client-manual:windows-client-manual[Windows Client]
* xref:linux-client-manual:linux-client-manual[Linux Client]
* xref:macos-client-manual:mac-client-manual[macOS Client]
* xref:manual:introduction[opsi Components in Detail]
* xref:opsi-script-manual:opsi-script-manual[opsi-script Interpreter]
* xref:contribute:contribute[How to Contribute to opsi]
* xref:copyright:copyright[Copyright]

All manuals are available for download at link:https://download.uib.de/4.2/stable/documentation/[download.uib.de] in PDF, HTML, and Epub format. In addition, we have published manuals for the APIs link:https://docs.opsi.org/python-docs/python-opsi[python-opsi] and link:https://docs.opsi.org/python-docs/python-opsi-common[opsicommon].

TIP: To meet other opsi users, please visit our link:https://forum.opsi.org/index.php[opsi forum]. Here you can also find the link to our opsi Wiki.
