////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      11.12.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



= Welcome to opsi!

The client management system link:https://www.opsi.org/[opsi (Open System Integration)] manages Windows, Linux and macOS clients--from a dozen to several thousand computers. The core component is a Linux server which takes care of automatic installation of operating systems (Windows and Linux only), distribution of software, hardware and software inventory, and patch management on the clients. In addition, there are modules to extend opsi's capabilities. In summary, opsi has the following features:

* Automatically distribute software on PCs with the opsi client agent.
* Automatically install operating systems using the opsi server.
* Perform comprehensive hardware and software inventory.

opsi offers a single administration interface to manage all clients in multiple locations. The configuration is stored in a central place: on the opsi server. The depot servers for the clients (installation files of the software, operating systems to be distributed, boot images, etc.) can also be located in several places.

This manual has the following structure:

* xref:supportmatrix:supportmatrix.adoc[Supported Systems]
* xref:first-steps:first-steps.adoc[Quick Start]
* xref:server:overview.adoc[opsi Server]
* xref:clients:opsi-clients.adoc[opsi Clients]
* xref:gui:gui.adoc[User Interfaces]
* xref:opsi-products:products.adoc[opsi Products]
* xref:opsi-modules:modules.adoc[opsi Modules]
* xref:opsi-script-manual:opsi-script-manual.adoc[*opsi-script* Reference]
* xref:troubleshooting:troubleshooting.adoc[Troubleshooting]
* xref:contribute:contribute.adoc[How to Contribute to opsi]
* xref:copyright:copyright.adoc[Copyright]

For comprehensive technical details, please refer to our specialized API manuals: link:https://docs.opsi.org/python-docs/python-opsi[python-opsi] and link:https://docs.opsi.org/python-docs/python-opsi-common[python-opsi-common].

TIP: Engage with the opsi community at the link:https://forum.opsi.org/index.php[opsi forum], where you can also access the link to our opsi wiki.

include::partial$conventions.adoc[]
