////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      25.01.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-manual-versioning-releases]]
= Versioning and Release Strategy

The following paragraphs explain our scheme for package versions as well as our release strategy.

== Versioning

We refer to a major version as a set of versions of our components that are compatible with each other. The first two places of a version number represent this, like 4.2, 4.3, etc. For each Major-Version, we provide repositories - separate ones for the categories `stable`, `testing`, and `experimental`. For more on our public repositories, see <<opsi-manual-versioning-releases-repositories,Repositories for opsi 4.3>>.

The third place of a version number represents the feature version. When we build a new functionality into a component, we increment the third place. Updates that change the feature version are backward compatible.

The fourth and last place is the patch version. This is increased when we introduce minor changes, that do not contain a new feature (like fixing a bug).
Compatibility remains unchanged across patch versions.

== Release Strategy

New packages are published in the `experimental` category. These already passed basic tests. We use these packages for further integration tests.
You should not generally use these packages in production environments, except if you need a specific fix to a Problem that occured.
When all integration tests are passed successfully, we release it to `testing`. If it is important to you to receive new features, efficiency improvements, and the like early, use the packages from `testing`. Once a month, on the last Wednesday of the month, we release packages as `stable`. If the focus of your environment is on high stability, use the packages from `stable`. There is an exception in this release strategy. If there is a problem in `stable` that is critical to the functioning of the opsi environment or the security of the system, there is a so-called hotfix release, in which packages that fix the problem are released to `stable` without adhering to the normal `stable` release schedule. In this way, these errors can be corrected promptly.

[[opsi-manual-versioning-releases-repositories]]
== Repositories for opsi 4.3

We publish packages in repositories for every supported major version in the categories `stable`, `testing` and `experimental`.
Additionally there is the distinction between server packages (.deb/.rpm format for opsi depot servers), opsi packages (.opsi format for opsi clients)
and tools (executables for Windows, Linux and macOs)

`stable` repositories:

* server packages: https://build.opensuse.org/project/show/home:uibmz:opsi:4.3:stable
* opsi packages: https://opsipackages.43.opsi.org/stable/
* tools: https://tools.43.opsi.org/stable/

`testing` repositories:

* server packages: https://build.opensuse.org/project/show/home:uibmz:opsi:4.3:testing
* opsi packages: https://opsipackages.43.opsi.org/testing/
* tools: https://tools.43.opsi.org/testing/

The urls of the `experimental` repositories are analogous.

[[opsi-manual-versioning-releases-changelogs]]
== Changelogs

Changelogs of the packages we publish can be found at https://changelog.opsi.org.
