////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:toc: left
:toclevels: 3
:numbered:
:icons: font
:xrefstyle: full
:doctype:   book
:date:      26.05.2021
:winclientmanual: opsi-windows-client-manual
:lang: de

// Include common opsi terms
ifeval::["{mode}" == "antora"]
include::common:partial$opsi_terms.adoc[]
endif::[]


// = opsi Windows client manual

// Include common opsi copyright
// include::common:partial$copyright.adoc[]


[[opsi-winclient-introduction]]
= Einführung Windows Clients in opsi

Diese Anleitung beschreibt den Betrieb von Windows Clients in opsi.

Es wird voraus gesetzt, das die Installation und Inbetriebnahme eines {opsi-Server}s bereits erfolgt ist.

Wesentliche Themen dieser Anleitung:

. Automatische Windows OS-Installation
. Aufnahme und Einbindung von Windows-Rechnern in opsi
(Installation des opsi-client-agent)
. Bereitstellung von opsi Standardsoftware für Windows auf dem opsi-server
. Installation von Standard Software auf den Windows-Clients
. opsi-Standardsoftware für Windows unter opsi
. Paketierung eigener Software
. Erstellung von opsi-Paketen
. Hinweise zu Windows Clients
.. Spezielle Befehle für Windows
.. Directories die Sie verwenden dürfen


[[opsi-winclient-convention]]
== Konventionen dieses Dokuments

Befehle werden gesondert hervorgehoben:

[source,prompt]
----
dies ist ein Befehl
----

Im Rahmen der Installation und Konfiguration können Sie die Befehle aus diesen Feldern in der Regel der Reihe nach per _copy & paste_ aus diesem Dokument kopieren und ausführen.

Das ist ein {opsi-script} Code:

[source,winst]
----
Message "Installing "+ $ProductId$ +" ..."
----

Kapitel welche den Namen einer bestimmten Plattform enthalten sind spezifisch für diese Plattform. Die unterstützen Plattformen sind:

* *Windows*

* *Linux*

* *MacOS*

