////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      31.05.2023
:Revision:  4.3
:toclevels: 6

[[opsi_manual_opsi-client-agent_webapi]]
= opsi-client-agent web service

Der *opsiclientd* stellt unter `https://<client-addresse>:4441` eine web-Schnittstelle zur Verfügung. Darin sind verschiedene Möglichkeiten enthalten:

// cspell: ignore viewer
info:: zeigt in kompakter Form an, was der *opsiclientd* tut
log viewer:: ist ein Hilfsmittel zum Betrachten und Durchsuchen des *opsiclientd* logs
control interface:: stellt einen Weg dar, JSONRPC-Anfragen an den *opsiclientd* zu stellen

Die folgenden Abschnitte beleuchten einzelne JSONRPC-Anfragen, die getätigt werden können.

[[opsi_manual_opsi-client-agent_webapi_log_read]]
== Logdateien auslesen

// cspell: ignore opsi_loginblocker, notifier_block_login, notifier_event
Die JSONRPC-Anfrage `log_read` liest eine auf dem Client vorhandene opsi-Logdatei.
Parameter: `logType *extension *maxSize`
Mögliche `logType` Werte sind `opsiclientd`, `opsi-client-agent`, `opsi-script`, `opsi_loginblocker`, `notifier_block_login` und `notifier_event`.
Mit dem Parameter `extension` können rotierte Logdateien (_1.log, _2.log etc.) angezeigt werden.
Mögliche Werte sind 0-9.
Der Parameter `maxSize` limitiert die Ausgabe auf den angegebenen Wert in Bytes.

[[opsi_manual_opsi-client-agent_webapi_update_component]]
== Eine opsi-client-agent-Komponente aktualisieren
Die JSONRPC-Anfrage `updateComponent` kann eine *opsi-client-agent*-Komponente aktualisieren.
Parameter: `*component *url`
Mögliche Werte für `component` sind: `opsiclientd`.
Das Update wird von der angegebenen `url` geladen (mögliche Protokolle sind hierbei: `http`, `https` und `file`).
Das Update muss als Archiv (zip / tar / tar.gz / tar.bz2) bereitgestellt werden, das die Dateien der Komponente enthält.

Alternativ kann das Archiv auch über einen `POST`-Request auf `/upload/update/opsiclientd` hochgeladen werden.
Beispiel:
[source,bash]
----
curl --insecure --request POST \
	--user ':<opsi-client-host-key>' \
	--header 'Content-Disposition: filename=oca.zip' \
	--data-binary '@path/to/opsiclientd_windows_x86_<version>.zip' \
	https://<client-address>:4441/upload/update/opsiclientd
----
