////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib gmbh
:Email:     info@uib.de
:Date:      17.09.2021
:Revision:  4.2
:toclevels: 6

include::../common/opsi_terms.asciidoc[]


[[opsi-manual-ci]]
== Anpassen des opsi-client-agent an Corporate Identity (CI)

Die Anpassung des Erscheinungsbildes des 'opsi-client-agent' kann insbesondere bei der Einführung erheblich zur Akzeptanz beitragen. So kann z.B. durch das Einfügen eines bekannten Firmenlogos in die Hintergrundgrafiken die Verunsicherung der Anwender vermieden werden.

=== Anzupassende Elemente: opsi-script
Die Dateien die Sie beim opsi-script anpassen können finden Sie im Verzeichnis `/var/lib/opsi/depot/opsi-client-agent/files/opsi-script/skin`:

* `bg.png` +
Die Hintergrundgrafik des 'opsi-script' in welche dann zur Laufzeit Textmeldungen und Produktlogos eingeblendet werden.

* `skin.ini` +
Die Konfigurationsdatei in der festgelegt ist, an welcher Stelle, mit welchem Font und Farbe Textmeldungen eingeblendet werden.

=== Anzupassende Elemente: opsiclientd
Im Verzeichnis
`/var/lib/opsi/depot/opsi-client-agent/files/opsi-notifier`
finden sich die Dateien welche das Erscheinungsbild der unterschiedlichen Notifier bestimmen. Dabei gibt es für jeden Notifier eine Bild- und eine Konfigurationsdatei:

* `block_login.bmp` +
Hintergrundbild des notifiers der einen aktiven Loginblocker anzeigt.
* `block_login.ini` +
Konfigurationsdatei des Loginblocker notifiers.
* `event.bmp` +
Hintergrundbild des notifiers der einen aktives Event mit Connection zum opsi-server anzeigt.
* `event.ini` +
Konfigurationsdatei des Event notifiers.
* `action.bmp` +
Hintergrundbild des notifiers der eine anstehende Aktion (Softwareinstallation) anzeigt.
* `action.ini` +
Konfigurationsdatei des Action notifiers.
* `shutdown.bmp` +
Hintergrundbild des notifiers der einen anstehenden Shutdown oder Reboot anzeigt.
* `shutdown.ini` +
Konfigurationsdatei des Shutdown notifiers.
* `popup.bmp` +
Hintergrundbild des notifiers der eine vom Server gesendete Popup Nachricht anzeigt.
* `popup.ini` +
Konfigurationsdatei des Popup notifiers.
* `userlogin.bmp` +
Hintergrundbild des notifiers der ein aktives userlogin Event anzeigt.
* `userlogin.ini` +
Konfigurationsdatei des UserLogin notifiers.

=== Schutz Ihrer Änderungen vor Updates: Das custom Verzeichnis

Möchten Sie Änderungen welche Sie an den oben genannten Dateien durchgeführt haben, davor schützen, das selbige beim Einspielen einer neuen Version des opsi-client-agenten verloren gehen, so können Sie hierfür das `custom` Verzeichnis `/var/lib/opsi/depot/opsi-client-agent/files/custom` (früher `/var/lib/opsi/depot/opsi-client-agent/files/opsi/custom`) verwenden. Das komplette `custom` Verzeichnis wird bei der Installation einer neuen Version des opsi-client-agenten gesichert und wieder hergestellt, so das hier gemachte Änderungen nicht verloren gehen.

* `custom/opsi-script/skin/*.*` +
wird bei der Installation des opsi-client-agent auf dem Client nach `C:\Program Files (x86)\opsi.org\opsi-client-agent\opsi-script\skin` kopiert.

* `custom/opsi-notifier/*.*` +
wird bei der Installation des opsi-client-agent auf dem Client nach `C:\Program Files (x86)\opsi.org\opsi-client-agent\opsi-notifier` kopiert und überschreibt dabei die Defaults aus dem serverseitigen `files/opsi-notifier/` Verzeichnis.

* `custom/opsiclientd/opsiclientd.conf` +
wird bei der Installation des opsi-client-agent auf dem Client nach `C:\Program Files (x86)\opsi.org\opsi-client-agent\opsiclientd` kopiert und überschreibt dabei die Defaults aus dem serverseitigen `files/opsiclientd/` Verzeichnis. +
*Achtung:* +
Die Anpassung der opsiclientd.conf über diese Methode wird nicht empfohlen. Verwenden Sie zur Konfiguration Ihrer Clients Hostparameter/Configs wie im Kapitel zum opsi-client-agent beschrieben. Diese Methode ist nur bei extrem komplexen Anpassungen der opsiclientd.conf sinnvoll. Wenn Sie diese Methode anwenden, müssen Sie bei jedem Einspielen einer neuen opsi-client-agent Version auf dem Server überprüfen, ob in der Default Datei `files/opsiclientd/opsiclientd.conf` Änderungen eingeführt wurden, welche Sie in Ihrer Version nachpflegen müssen. Also: +
*Finger weg, es sei denn Sie wissen wirklich was Sie tun !*

