////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////


:Author:    uib gmbh
:Email:     info@uib.de
:Date:      14.03.2013
:Revision:  4.0.3
:doctype:		book

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]

= opsi Version 4.0.3 Release Notes

// Include common opsi copyright
include::../common/opsi_manual_copyright.asciidoc[]

[[opsi-403-releasenotes-overview]]
== Übersicht der Neuerungen

Das opsi Service Releases 4.0.3 weist eine Fülle von Neuerungen und Detailverbesserungen auf. Hier eine Übersicht:

* opsi Erweiterung: Install-on-shutdown

* opsi Erweiterung: Local-Image (Backup and Restore)

* Freigabe von opsi 4.0.3 für folgende Distributionen:

** 

* Freigabe einer aktualisierten vorkonfigurierten opsi-VM auf Basis von Ubuntu 12.04 und mit integriertem opsi-Nagios-Connector

Die entsprechenden Installationsanleitungen finden Sie wie immer im 'opsi-getting-started' Handbuch

* opsi-configed

** 

* Treiberintegration +
Automatische Zuordnung von Treiberpaketen zu Rechnern auf Basis von den Daten zu Vendor und Model aus der Hardware Inventarisierung. Beschreibung hierzu siehe unten.

* Windows Netboot Produkte

** Anpassung an die erweiterte Treiberintegration


* opsi-winst: +
Eine Fülle von Erweiterungen, welche weiter unten beschrieben sind.

[[opsi-403-releasenotes-installation]]
== Hinweise zur Installation

Die Produkte welche im Rahmen dieses Releases veröffentlicht werden, sind in etlichen Teilen voneinander abhängig. Sie sollten daher nicht versuchen nur Teile zu installieren.

Die Installation erfordert keine besonderen Arbeiten. Sie erfolgt im Rahmen der normalen Updates ihres Servers und der opsi-Produkte.

Sie sollten dabei zuerst den Server updaten und danach die opsi-Produkte. Dies erledigt der opsi-product-updater:

[source,prompt]
----
opsi-product-updater -i -vv
----

Sollten Sie eine Multidepot Umgebung haben, so machen Sie zunächst das Upgrade auf Ihrem config-server, bevor Sie die Depots upgraden.

include::../common/opsi_manual_on_shutdown.asciidoc[]
include::../common/opsi_manual_local_image.asciidoc[]

[[opsi-manual-configuration-tools-opsi-configed]]
== Werkzeug: Das Managementinterface '{opsi-configed}'

[[opsi-manual-configuration-tools-opsi-configed-client-selection-selecting]]
=== Auswahl von Clients

text

[[opsi-403-releasenotes-driverintegration]]
== Erweiterungen bei der Treiberintegration

text

[[opsi-getting-started-firststeps-osinstall-driverintegration]]
=== Vereinfachte Treiberintegration in die automatische Windowsinstallation
text

[[opsi-release-notes-402-opsi-linux-bootimage-dhclient]]
== Anpassungen am neuen opsi-linux-bootimage

text

[[opsi-release-notes-402-opsiconfd-all]]
== Anpassungen am opsiconfd

text


[[opsi-winst]]
== opsi-winst 4.11.3.5

text

[[opsi-winst-numbers]]
=== Umgang mit Zahlen

Es gibt im 'opsi-winst' keine speziellen Variablen für Zahlen. Es gibt allerdings einige Funktionen welche beim Umgang mit Zahlen helfen.

* `calculate(`<str>`)` +
Stringfunktion welch den arithmetischen Ausdruck im String <str> berechnet und als gerundeten integer string zurückgibt. +
Intern werden die Berechnungen mit reellen Zahlen durchgeführt. Die Funktion kennt derzeit die Operatoren `+`, `-`, `*`, `/` sowie Klammern `(`,`)`. +
Im Fehlerfall wird ein leerer String zurückgegeben und der Errorcounter um eins erhöht +
Seit 4.11.3.5
Beispiele:
[source,winst]
----
		set $ConstTest$ = "0"
		set $CompValue$ = calculate("-1+1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $ConstTest$ = "1"
		set $CompValue$ = calculate("0+1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $ConstTest$ = "2"
		set $CompValue$ = calculate("1+1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $ConstTest$ = "3"
		set $CompValue$ = calculate("2+1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $ConstTest$ = "10"
		set $CompValue$ = calculate("9+1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $ConstTest$ = "11"
		set $CompValue$ = calculate("10+1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		
		set $ConstTest$ = "10"
		set $CompValue$ = calculate("11-1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $ConstTest$ = "9"
		set $CompValue$ = calculate("10-1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $ConstTest$ = "2"
		set $CompValue$ = calculate("3-1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $ConstTest$ = "1"
		set $CompValue$ = calculate("2-1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $ConstTest$ = "0"
		set $CompValue$ = calculate("1-1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $ConstTest$ = "-1"
		set $CompValue$ = calculate("0-1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $string1$ = "5"
		set $string2$ = "5"
		set $ConstTest$ = "25"
		set $CompValue$ = calculate($string1$+"*"+$string2$)
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $string1$ = "5"
		set $string2$ = "5"
		set $ConstTest$ = "1"
		set $CompValue$ = calculate($string1$+"/"+$string2$)
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $string1$ = "5"
		set $string2$ = "0"
		set $ConstTest$ = ""
		comment " expecting devision by zero error and empty string result"
		set $CompValue$ = calculate($string1$+"/"+$string2$)
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $string1$ = "9"
		set $string2$ = "10"
		set $ConstTest$ = "1"
		comment "result 0.9 is rounded to 1 "
		set $CompValue$ = calculate($string1$+"/"+$string2$)
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $string1$ = "10"
		set $string2$ = "9"
		set $ConstTest$ = "1"
		comment "result 1.1111 is rounded to 1 "
		set $CompValue$ = calculate($string1$+"/"+$string2$)
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $string1$ = "5"
		set $string2$ = "5"
		set $ConstTest$ = "55"
		comment " rule * before +"
		set $CompValue$ = calculate($string1$+"+"+$string2$+"*10")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $string1$ = "5"
		set $string2$ = "5"
		set $ConstTest$ = "100"
		comment "brackets before  rule * before + "
		set $CompValue$ = calculate("("+$string1$+"+"+$string2$+")*10")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $string1$ = "5"
		set $string2$ = "five"
		set $ConstTest$ = ""
		comment " expecting converting error and empty string result"
		set $CompValue$ = calculate($string1$+"*"+$string2$)
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
----

[[opsi-winst-secsections]]
=== Sekundäre Sektionen

[[opsi-winst-patches]]
==== Patches-Sektionen


[[opsi-winst-patches-params]]
===== Aufrufparameter 

text

[[opsi-winst-linkfolder]]
=== LinkFolder-Sektionen

(...)

In einer LinkFolder-Sektion muss zuerst bestimmt werden, in welchem virtuellen Systemfolder die nachfolgenden Anweisungen arbeiten sollen. Dafür existiert die Anweisung +
`set_basefolder` '<virtueller Systemfolder>' 

Virtuelle Systemfolder, die angesprochen werden können, sind:

'desktop, sendto, startmenu, startup, programs, desktopdirectory, common_startmenu, common_programs, common_startup, common_desktopdirectory'

Die Folder sind virtuell, weil erst durch das Betriebssystem(-Version) bestimmt wird, an welchem physikalischen Ort des Dateisystems sie real existieren. 

Im Rahmen einer normalen 'Maschinen' Installation sind nur die `common*` Systemfolder relevant.

Die Systemfolder 'desktop, sendto, startmenu, startup, programs, desktopdirectory' können nur im Kontext eines eingloggten users bzw. in einem 'userLoginScript' im Rahmen der opsi-Erweiterung 'user Profile Management' verwendet werden.

[[opsi-winst-execwith]]
==== ExecWith Sektionen

[[opsi-winst-execwith-params]]
==== Aufrufparameter (Modifier)

(...)

Es sind folgende '{opsi-winst}'-Optionen verfügbar:

*  `/32Bit` +
Das ist der Default. Der angegebene Interpreterpfad wird als 32 Bit Pfad interpretiert. +
Beispiel: `c:\windows\system32\WindowsPowerShell\v1.0\powershell.exe` ruft (auch auf einem 64bit System) die 32 Bit 'powershell.exe' auf.

*  `/64Bit` +
Der angegebene Interpreterpfad wird als 64 Bit Pfad interpretiert. +
Beispiel: `c:\windows\system32\WindowsPowerShell\v1.0\powershell.exe` ruft (auf einem 64bit System) die 64 Bit 'powershell.exe' auf.

*  `/SysNative` +
Der angegebene Interpreterpfad wird gemäß der OS Architektur interpretiert. +
Beispiel: `c:\windows\system32\WindowsPowerShell\v1.0\powershell.exe` ruft auf einem 64bit System die 64 Bit 'powershell.exe' und auf einem 32bit System die 32 Bit 'powershell.exe'auf.

Seit Version 4.11.3.5 wird, wenn im angegebene Interpreterpfad 'powershell.exe' vorkommt, die temporäre Datei als `.ps1` gespeichert. 

[[opsi-winst-winbatch]]
==== WinBatch-Sektionen

[[opsi-winst-winbatch-params]]
===== Aufrufparameter (Modifier)

*  `/32Bit` +
Das ist der Default. Die in der Sektion angegebene Pfade werden als 32 Bit Pfade interpretiert. +
Beispiel: `c:\windows\system32\regedit.exe` ruft (auch auf einem 64bit System) die 32 Bit 'regedit.exe' auf.

*  `/64Bit` +
Die in der Sektion angegebene Pfade werden als 64 Bit Pfade interpretiert. +
Beispiel: `c:\windows\system32\regedit.exe` ruft (auf einem 64bit System) die 64 Bit 'regedit.exe' auf.

*  `/SysNative` +
Die in der Sektion angegebene Pfade werden gemäß der OS Architektur interpretiert. +
Beispiel: `c:\windows\system32\regedit.exe` ruft auf einem 64bit System die 64 Bit 'regedit.exe' und auf einem 32bit System die 32 Bit 'regedit.exe'auf.

Beispiel:
[source,winst]
----
Winbatch_add_reg winst /64Bit
[Winbatch_add_reg]
"c:\windows\system32\regedit.exe" /s "%scriptpath%\my64.reg"
----


* `/RunAsLoggedonUser` //seit 4.11.3.5 +
Nur im Kontext eines 'userLoginScripts' verfügbar. Startet das Programm als der user der sich gerade einlogt.
Dieser Modifier hat folgende Einschränkungen: +
** Unter NT6 wenig getestet und evtl. nur Eingeschränkt wirksam.



[[opsi-winst-misc]]
=== Sonstiges


[[opsi-403-releasenotes-misc]]
== Sonstiges

[[opsi-403-releasenotes-misc-changelogs]]
=== Changelogs:

[[opsi-403-releasenotes-misc-changelogs-configed]]
==== Changelog configed
text

[[opsi-403-releasenotes-misc-changelogs-opsi-winst]]
==== Changelog opsi-winst

opsi-winst (4.11.3.5) stable; urgency=low

  * del / delete will not delete if the given Filename starts with '\' (eg. '\Dummy')
  * danish localization added
  * italien localization added
  * extended LDAPSearch (username/password)
  * fix: do not store isfatalerror in registry if nor running as admin
  * execwith: winst (/32bit|/64bit|/sysnative) no allowed
  * execwith: if 'powershell.exe' is part of the interpreter string the script extension is '.ps1'
  * winbatch: /32bit|/64bit|/sysnative no allowed
  * wilog: replace ' -->' by ' ==>' because the opsi web service get in trouble because it is interpreted as xml comment, fixes #350
  * switch to Lazarus 1.0 / fpc 2.6.0
  * wisynt: doAktionen, fileActionsMain: do ApplyTextConstants for filesections in fileActionsMain.
      fixes wrong resolution of %CurrentProfileDir% in Files /AllNTuserProfiles
  * wisynt: doLinkFolderActions: fix: now comments allowed between set_link and end_link
  * wisynt: doLinkFolderActions: linkfolder section now  usable in userLoginScripts:
      the predefined basfolders:
      'desktop', 'sendto', 'startmenu', 'programs', 'startup', 'desktopdirectory'
      are pointing to the loggedin user directories if called from userLoginScript
  * wimain: ProcessNonZeroScript: fix: do not run update after setup if setup is failed, fixes #432
  * fix: widatamodul: opsidata4.initproduct now boolean function: false = error
  * new: new winst cli parameter '/productlist <productid>[,<productid>]* as sub parameter to /opsiservice
    try to run the setup-scripts of the given products, change installation states, send log files
  * new: string function calculate(<string expr>) ; calculates the mathematical expression and returns the result as string.
    on error the result is a empty string and the errorcounter is increased

-- Detlef Oertel <d.oertel@uib.de>  Thu,  05 Dec 2012:15:00:00 +0200


opsi-winst (4.11.3.4) stable; urgency=low

  * new winbatch parameter /RunAsLoggedOnUser
  * PatchTextFile sections may now called with  %userprofiledir% as part of the file name and /AllNTuserProfiles
     so it will run on all profiles.
     If running in Machine mode, the '/AllNTuserProfiles' is implizit in the [ProfileActions].
     If running in LoginScript mode, the '%userprofiledir%' is the %CurrentProfileDir%.
  * will now look for skins (more exactly: skin.ini) in the following sequence:
    1) by parameter
    2) new custom directory of opsi-client-agent ../custom/winstskin
    3) own winstskin: winstskin

-- Detlef Oertel <d.oertel@uib.de>  Thu,  26 Oct 2012:15:00:00 +0200


[[opsi-403-releasenotes-misc-changelogs-jedit]]
==== Changelog jedit

jedit_4.5.2-2 stable; urgency=low


[[opsi-403-releasenotes-misc-changelogs-opsi-adminutils]]
==== Changelog opsi-adminutils

opsi-adminutils (4.0.2.1-1) stable; urgency=low

[[opsi-403-releasenotes-misc-changelogs-opsi-template]]
==== Changelog opsi-template

opsi-template (4.0.2-2) stable; urgency=low

[[opsi-403-releasenotes-misc-changelogs-opsi-template-with-admin]]
==== Changelog opsi-template-with-admin

opsi-template-with-admin (4.0.2-2) stable; urgency=low

[[opsi-403-releasenotes-misc-changelogs-opsi-client-agent]]
==== Changelog opsi-client-agent

opsi-client-agent (4.0.2.1-2) stable; urgency=low

[[opsi-403-releasenotes-misc-changelogs-windows-netboot]]
==== Changelog windows netboot products

windows (4.0.2-1) stable; urgency=low


[[opsi-403-releasenotes-misc-changelogs-python-opsi]]
==== Changelog python-opsi

python-opsi (4.0.2.4-1) stable; urgency=low

[[opsi-403-releasenotes-misc-changelogs-opsipxeconfd]]
==== Changelog opsipxeconfd

opsipxeconfd (4.0.2.6-1) stable; urgency=low

[[opsi-403-releasenotes-misc-changelogs-opsiconfd]]
==== Changelog opsiconfd

opsiconfd (4.0.2.4-1) stable; urgency=low

[[opsi-403-releasenotes-misc-changelogs-opsi-utils]]
==== Changelog opsi-utils

opsi-utils (4.0.2.3-1) stable; urgency=low

[[opsi-403-releasenotes-misc-changelogs-opsi-linux-bootimage]]
==== Changelog opsi-linux-bootimage

opsi-linux-bootimage (20120728-1) stable; urgency=low

[[opsi-403-releasenotes-misc-changelogs-opsi-depotserver]]
==== Changelog opsi-depotserver

opsi-depotserver (4.0.2.3-1) stable; urgency=low

[[opsi-403-releasenotes-misc-changelogs-opsi4ucs]]
==== Changelog opsi4ucs

opsi4ucs (4.0.2.3-1) stable; urgency=low

[[opsi-403-releasenotes-misc-changelogs-opsi-atftp]]
==== Changelog opsi-atftp

opsi-atftp (0.7.dfsg-2.1) stable; urgency=low

