////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////


:Author:    uib gmbh
:Email:     info@uib.de
:Date:      14.03.2013
:Revision:  4.0.3
:doctype:		book

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]

= opsi Version 4.0.3 Release Notes

// Include common opsi copyright
include::../common/opsi_manual_copyright.asciidoc[]

[[opsi-403-releasenotes-overview]]
== Übersicht der Neuerungen

Das opsi Service Releases 4.0.3 weist eine Fülle von Neuerungen und Detailverbesserungen auf. Hier eine Übersicht:

* opsi Erweiterung: Install-on-shutdown

* opsi Erweiterung: Local-Image (Backup and Restore)

* Freigabe von opsi 4.0.3 für folgende Distributionen:

** 

* Freigabe einer aktualisierten vorkonfigurierten opsi-VM auf Basis von Ubuntu 12.04 und mit integriertem opsi-Nagios-Connector

Die entsprechenden Installationsanleitungen finden Sie wie immer im 'opsi-getting-started' Handbuch

* opsi-configed

** 

* Treiberintegration +
Automatische Zuordnung von Treiberpaketen zu Rechnern auf Basis von den Daten zu Vendor und Model aus der Hardware Inventarisierung. Beschreibung hierzu siehe unten.

* Windows Netboot Produkte

** Anpassung an die erweiterte Treiberintegration


* opsi-winst: +
Eine Fülle von Erweiterungen, welche weiter unten beschrieben sind.

[[opsi-403-releasenotes-installation]]
== Hinweise zur Installation

Die Produkte welche im Rahmen dieses Releases veröffentlicht werden, sind in etlichen Teilen voneinander abhängig. Sie sollten daher nicht versuchen nur Teile zu installieren.

Die Installation erfordert keine besonderen Arbeiten. Sie erfolgt im Rahmen der normalen Updates ihres Servers und der opsi-Produkte.

Sie sollten dabei zuerst den Server updaten und danach die opsi-Produkte. Dies erledigt der opsi-product-updater:

[source,prompt]
----
opsi-product-updater -i -vv
----

Sollten Sie eine Multidepot Umgebung haben, so machen Sie zunächst das Upgrade auf Ihrem config-server, bevor Sie die Depots upgraden.

include::../common/opsi_manual_on_shutdown.asciidoc[]
include::../common/opsi_manual_local_image.asciidoc[]

[[opsi-manual-configuration-tools-opsi-configed]]
== Werkzeug: Das Managementinterface '{opsi-configed}'

[[opsi-manual-configuration-tools-opsi-configed-client-selection-selecting]]
=== Auswahl von Clients

text

[[opsi-403-releasenotes-driverintegration]]
== Erweiterungen bei der Treiberintegration

text

[[opsi-getting-started-firststeps-osinstall-driverintegration]]
=== Vereinfachte Treiberintegration in die automatische Windowsinstallation
text

[[opsi-release-notes-402-opsi-linux-bootimage-dhclient]]
== Anpassungen am neuen opsi-linux-bootimage

text

[[opsi-release-notes-402-opsiconfd-all]]
== Anpassungen am opsiconfd

text


[[opsi-winst]]
== opsi-winst 4.11.3.5

text
[[opsi-winst-skins]]
=== Skinnable {opsi-winst}

Ab Version 3.6 verfügt '{opsi-winst}' einen veränderbare Oberfläche. Seine Elemente liegen im Unterverzeichnis winstskin des Verzeichnisses, in dem der ausgeführte '{opsi-winst}' liegt. Die editierbare Definitionsdatei ist skin.ini. 

Seit Version 4.11.3.5 sucht der 'opsi-winst' nach dem zu verwendenden Skin Verzeichnis in folgender Reihenfolge, wobei das erste Verzeichnis, welches eine skin.ini enthält verwendet wird:

. `%WinstDir%\..\custom\winstskin`
. `%WinstDir%\winstskin`

Mit dem Befehl `SetSkinDirectory` kann ein SkinDirectory auch im Script angegeben werden.
Wird bei diesem Befehl ein leerer oder ungültiger Pafd angegeben, so wird der Defaultpfad verwendet.

Beispiel:
[source,winst]
----
SetSkinDirectory "%ScriptPath%\testskin"
sleepseconds 1
SetSkinDirectory ""
----


[[opsi-winst-params-showmode]]
==== Fenster Modus / Skin

* `SetSkinDirectory` <skindir>+
Setzt das zu vwendende SkinDirectory und lädt den Skin 
Wird bei diesem Befehl ein leerer oder ungültiger Pafd angegeben, so wird der Defaultpfad verwendet.

Beispiel:
[source,winst]
----
SetSkinDirectory "%ScriptPath%\testskin"
sleepseconds 1
SetSkinDirectory ""
----


[[opsi-winst-numbers]]
=== Umgang mit Zahlen

Es gibt im 'opsi-winst' keine speziellen Variablen für Zahlen. Es gibt allerdings einige Funktionen welche beim Umgang mit Zahlen helfen.

* `calculate(`<str>`)` +
Stringfunktion welch den arithmetischen Ausdruck im String <str> berechnet und als gerundeten integer string zurückgibt. +
Intern werden die Berechnungen mit reellen Zahlen durchgeführt. Die Funktion kennt derzeit die Operatoren `+`, `-`, `*`, `/` sowie Klammern `(`,`)`. +
Im Fehlerfall wird ein leerer String zurückgegeben und der Errorcounter um eins erhöht +
Enthält der übergebene String Zeichen die keine Zahlen oder gültige Operatoren sind, so werden diese ignoriert. Fehlt der zweite Operator, so wird hierfür der erste verwendet: 5+ = 10 ; 5* = 25. Daher sollte beim Zusammensetzen
Seit 4.11.3.5
Beispiele:
[source,winst]
----
		set $ConstTest$ = "0"
		set $CompValue$ = calculate("-1+1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $ConstTest$ = "1"
		set $CompValue$ = calculate("0+1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $ConstTest$ = "2"
		set $CompValue$ = calculate("1+1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $ConstTest$ = "3"
		set $CompValue$ = calculate("2+1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $ConstTest$ = "10"
		set $CompValue$ = calculate("9+1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $ConstTest$ = "11"
		set $CompValue$ = calculate("10+1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		
		set $ConstTest$ = "10"
		set $CompValue$ = calculate("11-1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $ConstTest$ = "9"
		set $CompValue$ = calculate("10-1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $ConstTest$ = "2"
		set $CompValue$ = calculate("3-1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $ConstTest$ = "1"
		set $CompValue$ = calculate("2-1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $ConstTest$ = "0"
		set $CompValue$ = calculate("1-1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $ConstTest$ = "-1"
		set $CompValue$ = calculate("0-1")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $string1$ = "5"
		set $string2$ = "5"
		set $ConstTest$ = "25"
		set $CompValue$ = calculate($string1$+"*"+$string2$)
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $string1$ = "5"
		set $string2$ = "5"
		set $ConstTest$ = "1"
		set $CompValue$ = calculate($string1$+"/"+$string2$)
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $string1$ = "5"
		set $string2$ = "0"
		set $ConstTest$ = ""
		comment " expecting devision by zero error and empty string result"
		set $CompValue$ = calculate($string1$+"/"+$string2$)
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $string1$ = "9"
		set $string2$ = "10"
		set $ConstTest$ = "1"
		comment "result 0.9 is rounded to 1 "
		set $CompValue$ = calculate($string1$+"/"+$string2$)
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $string1$ = "10"
		set $string2$ = "9"
		set $ConstTest$ = "1"
		comment "result 1.1111 is rounded to 1 "
		set $CompValue$ = calculate($string1$+"/"+$string2$)
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $string1$ = "5"
		set $string2$ = "5"
		set $ConstTest$ = "55"
		comment " rule * before +"
		set $CompValue$ = calculate($string1$+"+"+$string2$+"*10")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $string1$ = "5"
		set $string2$ = "5"
		set $ConstTest$ = "100"
		comment "brackets before  rule * before + "
		set $CompValue$ = calculate("("+$string1$+"+"+$string2$+")*10")
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
		set $string1$ = "5"
		set $string2$ = "five"
		set $ConstTest$ = ""
		comment " expecting converting error and empty string result"
		set $CompValue$ = calculate($string1$+"*"+$string2$)
		if ($ConstTest$ = $CompValue$)
			comment "passed"
		else
			set $TestResult$ = "not o.k."
			LogWarning "failed"
		endif
----

[[opsi-winst-patchtextfile]]
=== PatchTextFile-Sektionen

[[opsi-winst-patchtextfile-params]]
==== Aufrufparameter

Der Name der zu patchenden Datei wird als Parameter übergeben.

Als optionalen Modifier gibt es:

* `/AllNTUserProfiles` +
Wird eine 'PatchTextFile' Sektion mit diesem Modifier aufgerufen und der Pfad zur zu patchenden Datei enthält die Konstante `%UserProfileDir%`, so wird diese Patchsektion für alle Profile ausgeführt. +
Eine 'PatchTextFile' Sektion welche in einer `[ProfileActions]` Sektion aufgerufen wird hat im 'Machine' Modus den Modifier `/AllNTUserProfiles` implizit. Im Loginscript Modus wird dann `%UserProfileDir%` als `%CurrentProfileDir%` interpretiert. +
(Seit Version 4.11.3.5)


[[opsi-winst-linkfolder]]
=== LinkFolder-Sektionen

(...)

In einer LinkFolder-Sektion muss zuerst bestimmt werden, in welchem virtuellen Systemfolder die nachfolgenden Anweisungen arbeiten sollen. Dafür existiert die Anweisung +
`set_basefolder` '<virtueller Systemfolder>' 

Virtuelle Systemfolder, die angesprochen werden können, sind:

'desktop, sendto, startmenu, startup, programs, desktopdirectory, common_startmenu, common_programs, common_startup, common_desktopdirectory'

Die Folder sind virtuell, weil erst durch das Betriebssystem(-Version) bestimmt wird, an welchem physikalischen Ort des Dateisystems sie real existieren. 

Im Rahmen einer normalen 'Maschinen' Installation sind nur die `common*` Systemfolder relevant.

Die Systemfolder 'desktop, sendto, startmenu, startup, programs, desktopdirectory' können nur im Kontext eines eingloggten users bzw. in einem 'userLoginScript' im Rahmen der opsi-Erweiterung 'user Profile Management' verwendet werden.

[[opsi-winst-execwith]]
=== ExecWith Sektionen

[[opsi-winst-execwith-params]]
==== Aufrufparameter (Modifier)

(...)

Es sind folgende '{opsi-winst}'-Optionen verfügbar:

*  `/32Bit` +
Das ist der Default. Der angegebene Interpreterpfad wird als 32 Bit Pfad interpretiert. +
Beispiel: `c:\windows\system32\WindowsPowerShell\v1.0\powershell.exe` ruft (auch auf einem 64bit System) die 32 Bit 'powershell.exe' auf.

*  `/64Bit` +
Der angegebene Interpreterpfad wird als 64 Bit Pfad interpretiert. +
Beispiel: `c:\windows\system32\WindowsPowerShell\v1.0\powershell.exe` ruft (auf einem 64bit System) die 64 Bit 'powershell.exe' auf.

*  `/SysNative` +
Der angegebene Interpreterpfad wird gemäß der OS Architektur interpretiert. +
Beispiel: `c:\windows\system32\WindowsPowerShell\v1.0\powershell.exe` ruft auf einem 64bit System die 64 Bit 'powershell.exe' und auf einem 32bit System die 32 Bit 'powershell.exe'auf.

Seit Version 4.11.3.5 wird, wenn im angegebene Interpreterpfad 'powershell.exe' vorkommt, die temporäre Datei als `.ps1` gespeichert. 

[[opsi-winst-winbatch]]
=== WinBatch-Sektionen

[[opsi-winst-winbatch-params]]
==== Aufrufparameter (Modifier)

*  `/32Bit` +
Das ist der Default. Die in der Sektion angegebene Pfade werden als 32 Bit Pfade interpretiert. +
Beispiel: `c:\windows\system32\regedit.exe` ruft (auch auf einem 64bit System) die 32 Bit 'regedit.exe' auf.

*  `/64Bit` +
Die in der Sektion angegebene Pfade werden als 64 Bit Pfade interpretiert. +
Beispiel: `c:\windows\system32\regedit.exe` ruft (auf einem 64bit System) die 64 Bit 'regedit.exe' auf.

*  `/SysNative` +
Die in der Sektion angegebene Pfade werden gemäß der OS Architektur interpretiert. +
Beispiel: `c:\windows\system32\regedit.exe` ruft auf einem 64bit System die 64 Bit 'regedit.exe' und auf einem 32bit System die 32 Bit 'regedit.exe'auf.

Beispiel:
[source,winst]
----
Winbatch_add_reg winst /64Bit
[Winbatch_add_reg]
"c:\windows\system32\regedit.exe" /s "%scriptpath%\my64.reg"
----

* `/RunAsLoggedonUser` //seit 4.11.3.5 +
Nur im Kontext eines 'userLoginScripts' verfügbar. Startet das Programm als der user der sich gerade einlogt.
Dieser Modifier hat folgende Einschränkungen: +
** Unter NT6 wenig getestet und evtl. nur Eingeschränkt wirksam.

[[opsi-winst-ldapsearch]]
=== LDAPsearch Sektion

[[opsi-winst-ldapsearch-syntax]]
==== LDAPsearch Sektion Syntax

Eine LDAPsearch Sektion beinhaltet die Spezifikationen:

(...)

*  `user:` +
Zu verwendender user Name. Seit 4.11.3.5

*  `password:` +
Zu verwendendes user Passwort. Seit 4.11.3.5

(...)

[[opsi-winst-ldapsearch-examples]]
==== Beispiele

(...)

Beispiel mit user / password
[source,winst]
----
comment ""
comment "-------------------------------------"
comment "Testing: "
comment "user / password"
Set $LdapHost$ = "vmix7.uib.local"
Set $LdapPort$ = "389"
Set $LdapUser$ = "cn=Administrator,cn=Users,dc=uib,dc=local"
Set $LdapPassword$ = "Linux123"
Set $LdapResultType$ = "objects"
Set $LdapSearchDn$ = "cn=Users,dc=uib,dc=local"
Set $LdapSearchAttributes$ = "name,objectClass"
Set $LdapFilter$ = "(&(objectclass=*))"

markErrorNumber
set $list1$ = getReturnListFromSection("ldapsearch_users /" + $LdapResultType$)
if errorsOccuredSinceMark > 0
	comment "failed while ldapsearch"
	set $TestResult$ = "not o.k."
else
	comment "passed"
endif

[ldapsearch_users]
targethost: $LdapHost$
targetport: $LdapPort$
user: $LdapUser$
password: $LdapPassword$
dn: $LdapSearchDn$
attributes: $LdapSearchAttributes$
filter: $LdapFilter$
----

[[opsi-403-releasenotes-misc]]
== Sonstiges

[[opsi-403-releasenotes-misc-changelogs]]
=== Changelogs:

[[opsi-403-releasenotes-misc-changelogs-configed]]
==== Changelog configed
text

[[opsi-403-releasenotes-misc-changelogs-opsi-winst]]
==== Changelog opsi-winst

opsi-winst (4.11.3.5) stable; urgency=low

  * del / delete will not delete if the given Filename starts with '\' (eg. '\Dummy')
  * danish localization added
  * italien localization added
  * extended LDAPSearch (username/password)
  * fix: do not store isfatalerror in registry if nor running as admin
  * execwith: winst (/32bit|/64bit|/sysnative) no allowed
  * execwith: if 'powershell.exe' is part of the interpreter string the script extension is '.ps1'
  * winbatch: /32bit|/64bit|/sysnative no allowed
  * wilog: replace ' -->' by ' ==>' because the opsi web service get in trouble because it is interpreted as xml comment, fixes #350
  * switch to Lazarus 1.0 / fpc 2.6.0
  * wisynt: doAktionen, fileActionsMain: do ApplyTextConstants for filesections in fileActionsMain.
      fixes wrong resolution of %CurrentProfileDir% in Files /AllNTuserProfiles
  * wisynt: doLinkFolderActions: fix: now comments allowed between set_link and end_link
  * wisynt: doLinkFolderActions: linkfolder section now  usable in userLoginScripts:
      the predefined basfolders:
      'desktop', 'sendto', 'startmenu', 'programs', 'startup', 'desktopdirectory'
      are pointing to the loggedin user directories if called from userLoginScript
  * wimain: ProcessNonZeroScript: fix: do not run update after setup if setup is failed, fixes #432
  * fix: widatamodul: opsidata4.initproduct now boolean function: false = error
  * new: new winst cli parameter '/productlist <productid>[,<productid>]* as sub parameter to /opsiservice
    try to run the setup-scripts of the given products, change installation states, send log files
  * new: string function calculate(<string expr>) ; calculates the mathematical expression and returns the result as string.
    on error the result is a empty string and the errorcounter is increased

-- Detlef Oertel <d.oertel@uib.de>  Thu,  05 Dec 2012:15:00:00 +0200


opsi-winst (4.11.3.4) stable; urgency=low

  * new winbatch parameter /RunAsLoggedOnUser
  * PatchTextFile sections may now called with  %userprofiledir% as part of the file name and /AllNTuserProfiles
     so it will run on all profiles.
     If running in Machine mode, the '/AllNTuserProfiles' is implizit in the [ProfileActions].
     If running in LoginScript mode, the '%userprofiledir%' is the %CurrentProfileDir%.
  * will now look for skins (more exactly: skin.ini) in the following sequence:
    1) by parameter
    2) new custom directory of opsi-client-agent ../custom/winstskin
    3) own winstskin: winstskin

-- Detlef Oertel <d.oertel@uib.de>  Thu,  26 Oct 2012:15:00:00 +0200


[[opsi-403-releasenotes-misc-changelogs-jedit]]
==== Changelog jedit

jedit_5.0.0-3 stable; urgency=low

   * opsi-winst.xml for version 4.11.3.5
   * code cleanup

-- detlef oertel <d.oertel@uib.de>  Fri, 15 Feb 2013 16:01:53 +0200

jedit_5.0.0-2 stable; urgency=low

   * jedit version with localization support

-- rupert röder <r.roeder@uib.de>  Tue, 27 Nov 2012 16:01:53 +0200

[[opsi-403-releasenotes-misc-changelogs-opsi-adminutils]]
==== Changelog opsi-adminutils

opsi-adminutils (4.0.3.-1) stable; urgency=low

  * change to 4.0.3

-- detlef oertel <d.oertel@uib.de>  15 Feb 2013


opsi-adminutils (4.0.2.1-5) stable; urgency=low

  * correct parameters for configed.jnlp URL

-- rupert roeder <r.roeder@uib.de>  10 Jan 2013

opsi-adminutils (4.0.2.1-4) stable; urgency=low

  * removed parameter from configed.jnlp URL
  * removed opsi-configed version from control file

-- detlef oertel <d.oertel@uib.de>  04 Jan 2013


opsi-adminutils (4.0.2.1-3) stable; urgency=low

  * regshot 1.8.3 (include 64-bit)
  * added kitty

-- detlef oertel <d.oertel@uib.de>  11 Oct 2012


opsi-adminutils (4.0.2.1-2) stable; urgency=low
  * swingx.jar
  * configed.jar 4.0.2.5.4
-- bardo wolf <b.wolf@uib.de>  04 Sep 2012


opsi-adminutils (4.0.2.1-1) stable; urgency=low

[[opsi-403-releasenotes-misc-changelogs-opsi-template]]
==== Changelog opsi-template

opsi-template (4.0.3-1) stable; urgency=low

	* default is now without property and 32 Bit

-- detlef oertel <d.oertel@uib.de>  Thu, 27 Sep 2012 16:01:53 +0200

[[opsi-403-releasenotes-misc-changelogs-opsi-client-agent]]
==== Changelog opsi-client-agent

opsi-client-agent (4.0.2.1-2) stable; urgency=low

[[opsi-403-releasenotes-misc-changelogs-windows-netboot]]
==== Changelog windows netboot products

windows (4.0.3-1) stable; urgency=low

  * do not copy winpe uefi boot files if not in uefi mode
  * code cleanup
  * new property winpe_partition_size
  * showdrivers.py:
      - Option -V for version output added.
      - byAudit: Translating model and vendor from hwinvent: characters <>?":|\/* will be translated to _

-- uib GmbH <info@uib.de>  Thu, 14 Feb 2013 15:19:15 +0000

windows (4.0.2-2) experimental; urgency=low

  * new property data_partition_create
  * detect if we are on uefi
  * if we are on uefi use gpt partitions
  * win8 (NT 6.2) support
  * new property use_raid1

-- uib GmbH <info@uib.de>  Mon, 27 Aug 2012 15:19:15 +0000

[[opsi-403-releasenotes-misc-changelogs-python-opsi]]
==== Changelog python-opsi

python-opsi (4.0.2.4-1) stable; urgency=low

[[opsi-403-releasenotes-misc-changelogs-opsipxeconfd]]
==== Changelog opsipxeconfd

opsipxeconfd (4.0.2.6-1) stable; urgency=low

[[opsi-403-releasenotes-misc-changelogs-opsiconfd]]
==== Changelog opsiconfd

opsiconfd (4.0.2.4-1) stable; urgency=low

[[opsi-403-releasenotes-misc-changelogs-opsi-utils]]
==== Changelog opsi-utils

opsi-utils (4.0.2.3-1) stable; urgency=low

[[opsi-403-releasenotes-misc-changelogs-opsi-linux-bootimage]]
==== Changelog opsi-linux-bootimage

opsi-linux-bootimage (20120728-1) stable; urgency=low

[[opsi-403-releasenotes-misc-changelogs-opsi-depotserver]]
==== Changelog opsi-depotserver

opsi-depotserver (4.0.2.3-1) stable; urgency=low

[[opsi-403-releasenotes-misc-changelogs-opsi4ucs]]
==== Changelog opsi4ucs

opsi4ucs (4.0.2.3-1) stable; urgency=low

[[opsi-403-releasenotes-misc-changelogs-opsi-atftp]]
==== Changelog opsi-atftp

opsi-atftp (0.7.dfsg-2.1) stable; urgency=low

