////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype: book
:macosclientmanual: opsi-macos-client-manual

include::common:partial$opsi_terms.adoc[]


= opsi MacOS client manual


[[opsi-macclient-introduction]]
== Introduction MacOS Clients in opsi

This manual describes the operation of MacOS clients in opsi.

It's assumed that the installation and startup of an {opsi server} has already been performed.

Essential topics of this manual:

. Adding and integrating Mac computers in opsi
(Installation of the opsi-mac-client-agent)
. Deployment of opsi standard software for Mac on the opsi-server .
. Installation of standard software on Mac clients
. opsi standard software for Mac under opsi
. Packaging of own software
. Creation of opsi packages
. Notes about Mac clients
.. Special commands for MacOS
.. Directories you may use
.. The pseudo user opsisetupadmin

[[opsi-macclient-convention]]
== Conventions of this document

Commands are highlighted separately:

[source,prompt]
----
this is a command
----

As part of the installation and configuration process, you can copy and execute the commands from these fields in order by _copy & paste_ from this document.

This is an opsi-script code:

[source,winst]
----
Message "Installing "+ $ProductId$ +" ..."
----

Chapters containing the name of a particular platform are specific to that platform. The supported platforms are:

* *Windows*

* *Linux*

* *MacOS*
