////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype: book
:macosclientmanual: opsi-macos-client-manual

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]




[[opsi-macclient-softwintegration]]
== Integration of own software into the software distribution of opsi.

The installation of software in opsi is performed by the {opsi-client-agent} and specially by the script controlled setup program {opsi-script}. Therefore an {opsi-script} script must be created for each opsi product. Afterwards this script, as well as the installation files and metadata are packed into an opsi product, which can finally be installed on the {opsi-server}.

[[opsi-macclient-softwintegration-tutorial]]
=== A small tutorial on how to create an {opsi-script} script.


include::../common/softwintegration-tutorial-introduction.asciidoc[]

[[opsi-macclient-softwintegration-tutorial-general]]
==== Methods of non-interactive software installation on macOS.

Apple (unlike Microsoft) standardized its software installation methods very early on. In essence, there are two methods:

* *application Directory*: +
This is a directory according to the pattern:
`<application name>.app` However, such a directory is not displayed in the `Finder` as a directory, but as an `application`. Inside this directory, according to a pattern, the files of the application must be located. A typical structure would be:

----
opsi-script-gui.app
  |--Contents
       |-Info.plist
       |-PkgInfo
       |-MacOS
       |  |-opsi-script-gui
       |
       |-Resources
          |- (....)
----

Such a directory must only be copied into the path `/Applications` for installation. Possible files in the directory `MacOS` must be made executable. +
Such *.app directories are usually offered packed for download.

* *PKG file*: +
These files contain software which need to be installed by a special command.

In both cases an `unattended` (i.e. non-interactive) installation is not an issue.

Often MacOS software is offered in packed formats like *.zip, *.dmg
or also *.tgz.

All variants mentioned so far can be installed directly by opsi-script, except *.tgz which must be unpacked before.

include::../common/softwintegration-tutorial-script-structure-opsi-script-basics.asciidoc[]
//
[[opsi-macclient-softwintegration-tutorial-macos-special-commands]]
===== Special commands for MacOS

* GetOS // returns: Linux or Windows_NT or macos [W/L/M]

* getMacosVersionInfo [M]

* getMacosVersionMap [M]

See also: +
https://download.uib.de/opsi_stable/doc/html/opsi-script-manual/opsi-script-manual.html#opsi-winst-macos-functions

In the following chapters special opsi MacOS commands to install software are presented, which come from the opsi-script library `uib_macosinstalllib`. This documentation is in English because it was automatically generated directly from the source code.

// http://www.methods.co.nz/asciidoc/userguide.html#X90
:leveloffset: 4

// Include os-lib_uib_macosinstalllib.asciidoc

include::../../en/common/os-lib_uib_macosinstalllib.asciidoc[]

:leveloffset: 0

[[opsi-macclient-softwintegration-tutorial-template]]
==== Third example: MacOS template 'm-opsi-template'.

You can create this template with the `opsi-setup-detector`.


.setup.opsiscript: Installationsscript
[source,winst]
----
; ----------------------------------------------------------------
; Copyright (c) uib gmbh (www.uib.de)
; This sourcecode is owned by uib
; and published under the Terms of the General Public License.
; ----------------------------------------------------------------
encoding=utf8

[Actions]
requiredWinstVersion >= "4.12.0.28"
ScriptErrorMessages = false

DefVar $ProductId$
DefVar $InstallDir$
DefVar $MinimumSpace$
DefVar $ExitCode$
DefVar $ErrorString$
DefVar $LicenseRequired$
DefVar $LicenseKey$
DefVar $LicensePool$
DefVar $OS$
DefVar $oldProgFound$
DefVar $installSuccess$


; import complete file !
importlib "uib_exitcode.opsiscript"
importlib "%scriptpath%\osd-lib.opsiscript"
importlib "%scriptpath%\uib_macosinstalllib.opsiscript"


; ----------------------------------------------------------------
; $ProductId$ is the name of the product in opsi, only lower letters, no umlauts, no white spaces, use '-' as a seperator
Set $ProductId$		 = "m-opsi-template"
Set $MinimumSpace$	 = "1 MB"
; the path were we find the product after the installation
;Set $InstallDir$		= "/Applications/<path to the product>"
Set $InstallDir$		= "/Applications/<productid.app>"
Set $LicenseRequired$ = "false"
Set $LicensePool$	  = ""
; ----------------------------------------------------------------

set $OS$ = GetOS

if not(($OS$ = "macos"))
	logError "Installation aborted: wrong OS version: only MacOS"
	isFatalError "wrong OS"
endif

comment "Show product picture"
ShowBitmap "%ScriptPath%\" + $ProductId$ + ".png" $ProductId$



if FileExists("%ScriptPath%\delsub.opsiscript")
	comment "Start uninstall sub section"
	Sub "%ScriptPath%\delsub.opsiscript"
endif

Message "Installing " + $ProductId$ + " ..."

if $LicenseRequired$ = "true"
	comment "Licensing required, reserve license and get license key"
	set $LicenseKey$ = get_licensekey_byPool($LicensePool$)
endif


comment "Start setup "
ChangeDirectory "%SCRIPTPATH%/files1"
;----------------------------------------------
set $installSuccess$ = install_macos_generic("%SCRIPTPATH%/files1/<my macos install file>")
;----------------------------------------------
Sub_check_installSuccess


comment "Copy files"
Files_install

[Sub_check_installSuccess]
if $installSuccess$  = "false"
	LogError "Installation failed"
	isfatalerror "Installation failed"
else
	Comment "Installation success"
endif


[Files_install]
; Example of recursively copying some files into the installation directory:
;
; copy -s "%ScriptPath%\files\*.*" "$InstallDir$"
----

.delsub.opsiscript: Ausgelagerte Deinstallations-Sub-Sektion
[source,winst]
----
; Copyright (c) uib gmbh (www.uib.de)
; This sourcecode is owned by uib gmbh
; and published under the Terms of the Affero General Public License v3.
; ----------------------------------------------------------------
encoding=utf8

Message "Check for existing installation of " + $ProductId$ + " ..."

comment "Start the Uninstall check:"
set $oldProgFound$ = "false"
if directoryExists($InstallDir$)
	set $oldProgFound$ = "true"
endif

if $oldProgFound$ = "true"
	Message "Uninstalling " + $ProductId$ + " ..."
	if not(($InstallDir$ = '') or ($InstallDir$ = 'unknown') or ($InstallDir$ = '/Applications/'))
		Files_uninstall
	endif
endif


[Files_uninstall]
del -sf "$InstallDir$\"

;-----------------------------------------------------

[Linkfolder_remove_desktop_icon]
; check delete_element
set_basefolder common_desktopdirectory
set_subfolder ""
delete_element $productId$

;-----------------------------------------------------
----

.uninstall.opsiscript: Deinstallations-Skript
[source,winst]
----
; ----------------------------------------------------------------
; Copyright (c) uib gmbh (www.uib.de)
; This sourcecode is owned by uib
; and published under the Terms of the Affero General Public License v3.
; ----------------------------------------------------------------
encoding=utf8


[Actions]
requiredWinstVersion >= "4.12.0.28"
ScriptErrorMessages = false

DefVar $ProductId$
DefVar $InstallDir$
DefVar $MinimumSpace$
DefVar $ExitCode$
DefVar $ErrorString$
DefVar $LicenseRequired$
DefVar $LicenseKey$
DefVar $LicensePool$
DefVar $OS$
DefVar $oldProgFound$


; import complete file !
importlib "uib_exitcode.opsiscript"
importlib "%scriptpath%\osd-lib.opsiscript"


; ----------------------------------------------------------------
; $ProductId$ is the name of the product in opsi, only lower letters, no umlauts, no white spaces, use '-' as a separator
Set $ProductId$		 = "m-opsi-template"
; the path were we find the product after the installation
;Set $InstallDir$	= "/Applications/<product.app>"
Set $InstallDir$	= "unknown"
Set $LicenseRequired$ = "False"
Set $LicensePool$	  = ""
; ----------------------------------------------------------------

set $OS$ = GetOS

if not(($OS$ = "macos"))
	logError "Installation aborted: wrong OS version: only macos"
	isFatalError "wrong OS"
endif


comment "Show product picture"
ShowBitmap "%ScriptPath%\" + $ProductId$ + ".png" $ProductId$



Message "Uninstalling " + $ProductId$ + " ..."

if FileExists("%ScriptPath%\delsub.opsiscript")
	comment "Start uninstall sub section"
	Sub "%ScriptPath%\delsub.opsiscript"
endif

if $LicenseRequired$ = "true"
	comment "Licensing required, free license used"
	Sub_free_license
endif

[Sub_free_license]
comment "License management is enabled and will be used"

comment "Trying to free license used for the product"
DefVar $result$
Set $result$ = FreeLicense($LicensePool$)
; If there is an assignment of a license pool to the product, it is possible to use
; Set $result$ = FreeLicense("", $ProductId$)
;
; If there is an assignment of a license pool to a windows software id, it is possible to use
; DefVar $WindowsSoftwareId$
; $WindowsSoftwareId$ = "..."
; set $result$ = FreeLicense("", "", $WindowsSoftwareId$)
----

[[opsi-macclient-softwintegration-create-opsi-package]]
=== Create an opsi product package

[[opsi-setup-detector-installation]]
==== Installation of the opsi-setup-detector, {opsi-package-builder} and opsi-logviewer

// include docu: opsi-setup-detector installation
include::../common/setup-detector-installation.asciidoc[]


// include docu: opsi-logviewer installation
include::../common/opsi-logviewer-installation.asciidoc[]



[[opsi-macclient-softwintegration-tutorial-create-with-opsi-setup-detector]]
==== The opsi-setup-detector program to create a MacOS script.

// include docu: opsi-setup-detector
include::../common/setup-detector-use-start.asciidoc[]

// include docu: macos specific tasks in opsi-setup-detector
include::../common/osd_tasks_macos.asciidoc[]

The following screenshots show the use of Windows installer files,
but they look similar when using MacOS installer files like *.app, *.dmg, *.zip.

// include docu: how to use the opsi-setup-detector
include::../common/osd-task-use-single-analyze-and-create.asciidoc[]

More details about the `opsi-setup-detector` can be found in the opsi-manual: +
https://download.uib.de/opsi4.1/documentation/html/opsi-manual-v4.1/opsi-manual-v4.1.html#opsi-setup-detector

// include docu: how to use the opsiPackagebuilder
include::../common/softwintegration-tutorial-packagebuilder-use.asciidoc[]

// include docu: The modify and test cycle
include::../common/softwintegration-tutorial-modify-test-cycle.asciidoc[]