////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      25.04.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-manual-configed]]
= Management Interface *opsi-configed*

The `opsi-configed` program is a graphical user interface that communicates with the opsi server via HTTPS. As such, it can be operated on any computer capable of connecting to the server through this protocol.

This chapter provides detailed guidance on the installation and initial setup of `opsi-configed`, including its startup parameters and the login process. It also covers the diverse functionalities of the program, such as client administration, depot management, and server configuration. Additionally, the chapter introduces the integrated server console and discusses the validation status of the various opsi modules.
