////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.1
:doctype:   book

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]

[[opsi-4.1-releasenotes]]
= opsi Version 4.1 Release Notes

// Include common opsi copyright
include::../common/opsi_manual_copyright.asciidoc[]

[[opsi-4.1-releasenotes-overview]]
== Overview of the new features

*Main aspects of this release are:*

* New tftpd: `opsi-tftp-hpa`
* New tool: `opsi-package-updater`
* Path to the workbench can now be configured
* `opsi-makeproductfile` has been renamed to `opsi-makepackage`
* `opsi-depotserver` has been renamed to `opsi-server`
* Python version 2.7 required
* systemd as the sole supported init system

[[opsi-4.1-releasenotes-important]]
== Important considerations - Please pay attention

opsi 4.1 is an independent release and thus has it's own package repositories.
These must be added into the system you want to update before installation.

For an update from opsi 4.0 the packages need to be the latest version available on the stable repositories.
Other packages - such as MySQL server - should also be up-to-date.
Otherwise problems are to be expected during the update.

It is also recommended that 'opsi-winst', 'opsi-client-agent' and 'opsi-linux-client-agent' are brought up-to-date on the clients before updating.


[[opsi-4.1-releasenotes-installation]]
== Installation notice

For your own safety, we strongly suggest to create a backup of your backends with +
{opsi-backup} before updating:
[source,prompt]
----
opsi-backup create
----

The products contained in this release depend on each other in many cases. +
Do not try to install just parts of this update.

We recommend to first update the server, and then update the opsi products.

To make sure that permissions are applied correctly +
we recommend to run ``opsi-setup --set-rights`` after the installation. +
Please be aware that the execution of latter can take several minutes.


[[opsi-4.1-releasenotes-installation-systempackages]]
=== Advice for Updating the operating system packages

Please make sure that at the time of the update you are using the latest packages from opsi 4.0 from the stable branch.

Due to the fact that this update also brings changes to the data structure on the backend
it is required to first migrate the backends after the update.

[source,prompt]
----
# If you are using the MySQL backend for data storage
opsi-setup --update-mysql
# If using you are the file backend for data storage
opsi-setup --update-file
----

As part of this release *opsi-depotserver* has been renamed to *opsi-server*.


For Debian-based machines there is a package for transition.
If you want to remove this package after the installation you first have to mark `opsi-server` as manually installed and then remove the transitional package.

This can be done through the following steps:

[source,prompt]
----
apt-get install opsi-server
apt-get remove opsi-depotserver
----

[[opsi-4.1-releasenotes-installation-opsipackages]]
=== Notes for updating opsi-packages

TBD


[[opsi-4.1-releasenotes-packages]]
== List of packages

.Server packages:
* opsi4ucs 4.1.1.4-9
* opsiconfd 4.1.1.10-1
* opsipxeconfd 4.1.1.4-2
* opsi-linux-bootimage 20171114-1
* opsi-server 4.1.1.4-5
* opsi-utils 4.1.1.14-1
* opsi-utils-deprecated 4.0.7.17-1
// * opsi-configed 4.1.x
* python-opsi 4.1.1.20-1

// .opsi packages (Windows):
// * opsi-client-agent 4.1.x
// * opsi-configed
// * opsi-winst
// * opsi-winst-test
// * jedit
// * TBD

.opsi packages (Linux):
* l-opsi-server 4.1.0.1-7
* l-opsi-server-migrate 4.1.1-2


[[opsi-4.1-releasenotes-knownbugs]]
== Known Bugs / Known Problems

.KNOWN BUGS:

None

.KNOWN PROBLEMS:

None

[[opsi-4.1-releasenotes-eol]]
== Discontinuation

This chapters lists discontinuations.


[[opsi-4.1-releasenotes-eol-opsi3]]
=== Discontinued: Support for opsi 3

With opsi 4.1 support for opsi 3 is discontinued.
This affects packages whose *control*-file still makes use of the opsi 3 syntax.

In addition some methods originating from opsi 3 that have never been ported to opsi 4 have been removed from the backend extension `20_legacy.conf`.
These methods could be spotted in opsi 4.0 because calling them would result in a _NotImplementedError_.

Affected methods can be taken from the changelog of python-opsi.


[[opsi-4.1-releasenotes-eol_server]]
=== Discontinuated: Distributions for opsi-server

These distributions will not be supported anymore for different reasons.

* CentOS 6.x
* Debian 7.x
* RedHat Enterprise Linux 6.x
* Suse Linux Enterprise Server 11
* Univention Corporate Server 3.x
* Univention Corporate Server 4.1

Also see separate chapter: <<opsi-4.1-releasenotes-supportmatrix>>.


[[opsi-4.1-releasenotes-eol_winclient]]
=== Discontinued Clients: Windows Versions

With opsi v4.1 the netboot packages

* TBD

will not be maintained anymore.
We also plan on discontinue the support for those Windows version from the update subscriptions.
If you have any questions or problems regarding this please get in contact with us.

See also separate chapter: <<opsi-4.1-releasenotes-netboot-windows>>.


[[opsi-4.1-releasenotes-eol_linclient]]
=== Discontinued Clients: Linux Versions

With opsi v4.1 the netboot products

* TBD

will not be maintained anymore.
If you have any questions or problems regarding this please get in contact with us.


[[opsi-4.1-releasenotes-supportmatrix]]
== opsi Support Matrix

An overview of the supported platforms for opsi 4.1 servers.

include::../common/opsi_manual_supportmatrix.asciidoc[]

If you are using an OS version which is not contained in the section above,
we recommend updating the OS before installing opsi v4.1.

[[opsi-4.1-releasenotes-migration]]
== Migration of an opsi 4.0 server

It is possible to migrate an existing opsi 4.0 installation on opsi 4.1 supported operating systems. Several steps are necessary to mirate.

First one needs to enter the opsi 4.1 package repositories into the systems package manager. The 'opsi-tftpd-hpa' package replaces the 'opsi-atftpd' package. Hereby the tftpd line from '/etc/inetd.conf' or '/etc/default/atftpd' needs to be deleted and the inetd service stopped.

Debian bases systems are updated to opsi 4.1 with the following steps:
[source,prompt]
----
update-inetd --remove tftp
apt install --yes --force-yes install opsi-tftpd-hpa
apt install --yes --force-yes dist-upgrade
apt --yes --force-yes install opsi-server
apt --yes --force-yes install opsi-configed
apt --yes --force-yes install opsi-linux-support
opsi-setup --auto-configure-samba
service opsiconfd restart
service opsipxeconfd restart
----

RedHat and CentOS systems need these steps to upgrade to opsi 4.1:
[source,prompt]
----
yum makecache
yum -y install opsi-server
yum -y install opsi-configed
yum -y install opsi-linux-support
chkconfig opsiconfd on
chkconfig opsipxeconfd on
opsi-setup --auto-configure-samba
service smb restart
service nmb restart
----

To migrate SLES and OpenSUSE please perform the following:
[source,prompt]
----
zypper --no-gpg-checks --non-interactive dup --from home_uibmz_opsi_4.1_stable
chkconfig opsiconfd on
chkconfig opsipxeconfd on
opsi-setup --auto-configure-samba
service smb restart
service nmb restart
----

After these steps your opsi 4.1 server is ready to continue.

[[opsi-releasenotes-4.1-changes-opsi-package-updater]]
== New tool 'opsi-package-updater'

In opsi 4.1 the tool `opsi-product-updater` that is known from previous versions will be replaced by `opsi-package-updater`.

The tasks of the tools are the same but the command line parameters changed and new options are now available.

The new tool opens the possibility to see the packages that will be updated before doing so or before installing any new packages.

An extended description of the new tool can be found in the manual.


[[opsi-releasenotes-4.1-changes-opsi-package-updater-quickstart]]
=== Quick introduction 'opsi-package-updater'

To show available updates use the following command:
[source,prompt]
----
opsi-package-updater list --updatable-products
----

To update the packages 'firefox' and 'javavm' use the following command:
[source,prompt]
----
opsi-package-updater -vv update firefox javavm
----

To update all available packages without any visible information use the following command:
[source,prompt]
----
opsi-package-updater update
----

To get an overview of all the packages available in the different repositories use the following command:
[source,prompt]
----
opsi-package-updater list --products
----

To install the package 'ubuntu' from the repository 'uib_linux' use the following command:
[source,prompt]
----
opsi-package-updater -vv --repo uib_linux install ubuntu
----


[[opsi-releasenotes-4.1-changes-opsi-package-updater-configfile]]
=== Using configuration of 'opsi-product-updater'

The configuration files of  `opsi-package-updater` and `opsi-product-updater` are nearly identical.
But only 'opsi-package-updater' understands new options.

It is possible to re-use a configuration created for `opsi-product-updater`.

For this call `opsi-package-updater` with the additional option `--config /etc/opsi/opsi-product-updater.conf`.


[[opsi-releasenotes-4.1-changes-opsi-makepackage]]
== New tool 'opsi-makepackage'

In opsi 4.1 the tool `opsi-makeproductfile` will be replaced through `opsi-makepackage`.

The name change makes the difference between a product and a package more clear.
The previously known command line parameters can still be used.

`opsi-makepackage` will create files containing checksums automatically when creating a package.
The switches `--no-md5` and `--no-zsync` respectively allow to disable this behavior.


[[opsi-releasenotes-4.1-changes-workbench]]
== New workbench path

The workbench directory will be placed at `/var/lib/opsi/workbench` per default during installation.
This brings a consistent directory structure across different systems and simplify the backup of whole opsi installations.

The depot attribute `workbenchLocalUrl` can be changed to adjust the used path.

Updating an existing installation will set this attribute to `/home/opsiproducts` for existing depots.
On SUSE-based systems `/var/lib/opsi/workbench` will be set.
Installations using a mix of different operating systems may need a manual adjustment after the update.

There will be no automatic move of existing directory contents from old to new workbench directory.


[[opsi-releasenotes-4.1-changes-python-27]]
== Python 2.7 as requirement

The use of Python 2.7 is required.
Older versions are not supported anymore.


[[opsi-releasenotes-4.1-changes-systemd]]
== systemd as init-system

opsi 4.1 will support only systemd as init-system.
Other init-systems will not be officially supported anymore.

[[opsi-releasenotes-4.1-changes-tftpd-hpa]]
== opsi-tftpd-hpa is the new tftpd daemon

opsi 4.1 now uses the opsi-tftpd-hpa. This tftpd daemon support `named pipes`, just as opsi-atftpd. In addition the opsi-tftpd-hpa allows to transfer larger files than 90 MiB.

[[opsi-releasenotes-4.1-changes-http-headers]]
== HTTP header 'content-type'

Communicating with an opsi 4.0 webservice leads to a HTTP header _content-type_ that does not match the used content encoding.
With opsi 4.0 a https://www.ietf.org/rfc/rfc2616.txt[RFC 2616] compatible behavior is the default.
This behaviour has been optional in opsi 4.0.


[[opsi-4.1-releasenotes-opsi-configed]]
== Improvements for '{opsi-configed}'

TBD

[[opsi-4.1-releasenotes-linux]]
== Linux Support

=== Support Matrix

include::../common/opsi_manual_supportmatrix-linclient.asciidoc[]

[[opsi-4.1-releasenotes-netboot-windows]]
== opsi Support Matrix Windows Clients

In the following graphic you will find on which Windows platforms opsi can be run as client.

include::../common/opsi_manual_supportmatrix-winclient.asciidoc[]

[[opsi-4.1-releasenotes-python-opsi]]
== Changes in python-opsi

=== Discontinuation of versions file

The file `/etc/opsi/version` will not be used anymore.

If Python is used then `OPSI.__version__` has the used version.
This can also be used to check for opsi 4.1 with the following command:

[source,prompt]
----
$ python -c "from OPSI import __version__ as v; print(v)"
----

If opsi 4.0 is used the exit code will be `1`. If opsi 4.1 is used the exit code will be `0`.

Furthermode the backend method 'backend_info' will return the version of the used Python library.

[source,prompt]
----
$ opsi-admin -d method backend_info | grep opsiVersion
"opsiVersion" : "4.1.1.6",
----


[[opsi-4.1-releasenotes-misc]]
== Miscellaneous

* `opsi-makeproductfile` becomes `opsi-makepackage`.

* `opsi-makepackage` will automatically create .md5 and .zsync-files during the creation of a new package. This can be suppressed through `--no-md5` and `--no-zsync` respectively.

* `opsi-newprod` will create empty files based on the filenames for the different actions as empty files.

[[opsi-4.1-releasenotes-misc-changelogs]]
=== Changelogs:

TBD
