////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.1
:doctype:   book

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]

[[opsi-4.1-releasenotes]]
= opsi Version 4.1 Release Notes

// Include common opsi copyright
include::../common/opsi_manual_copyright.asciidoc[]

[[opsi-4.1-releasenotes-overview]]
== Overview of the new features

*Main aspects of this release are:*

* opsi Server
** New tftpd: `opsi-tftp-hpa`
** New tool: `opsi-package-updater`
** Path to the workbench can now be configured
** The tool `opsi-makeproductfile` has been renamed to `opsi-makepackage`
** The package `opsi-depotserver` has been renamed to `opsi-server`
** Configurable ports for Wake-On-LAN
** Changed defaults
** Python version 2.7 required
** systemd as the sole supported init system
* Windows operating system installation (netboot products) (also for opsi 4.0)
** Multidiskmode: Supports the installation on systems with several hard disks drives
** Ability to install specifically on the the first SSD tray
** Assignment of Administrator password via property
* New opsi extension 'opsi-vhd-reset' which is designed for schools or other kinds of classrooms.
** This extension is available for opsi 4.0 as well as for opsi 4.1.
** Like the already known opsi-local-image extension, 'opsi-vhd-reset' also tackles the issue of fast recoveries on computers between two different training sessions.
** Installation of a windows 10 into a vhd container
** Snapshot of the original installation by creating a child vhd, which records any future changes.
** Fast recovery by replacing the old child vhd by a new empty one.
** This extension is liable to fees.
** Also it's bundled with 'opsi-local-image' which means that in order to use it you need an activation for the 'opsi-local-image'.
If you have one, you may use it without any additional costs.


[[opsi-4.1-releasenotes-important]]
== Important considerations - Please pay attention

opsi 4.1 is an independent release and thus has it's own package repositories.
These must be added into the system you want to update before installation.

For an update from opsi 4.0 the packages need to be the latest version available on the stable repositories.
Other packages - such as MySQL server - should also be up-to-date.
Otherwise problems are to be expected during the update.

The replacement of `opsi-product-updater` through `opsi-package-updater` brings along a new configuration file that has to be migrated.
The <<opsi-releasenotes-4.1-changes-opsi-package-updater-configfile,migration of the configuration>> is described lat-er in this document.

In the case that you want to automatize the `opsi-product-updater` - For example with a regular Cronjob - or execute a Script, make sure that you switch to `opsi-package-updater`

It is also recommended that 'opsi-winst', 'opsi-client-agent' or 'opsi-linux-client-agent' be updated to the latest version of opsi 4.0 before updating on the clients.

If after the migration a message appears in the form:"Your hostcontrol backend configuration uses the old format for broadcast addresses...", please check here which configuration adjustments are needed in this case: <<opsi-releasenotes-4.1-changes-wake-on-lan-ports, Configurable ports for Wake-On-LAN>>>

[[opsi-4.1-releasenotes-important-dispatch-and-acl.conf]]
=== New behavior of dispatch.conf and acl.conf

opsi 4.1 introduces also changes in the server configuration. In opsi 4.0.x the two files *dispatch.conf* and *acl.conf* had under /etc/opsi/backendManager a symbolic link to the *.default files.

[source,prompt]
----
cd /etc/opsi/backendManager
Is-la
dispatch.conf -> dispatch.conf.default
acl.conf -> acl.conf.default
----

With opsi 4.1 these two files are no longer created as symbolic links. The opsi 4.1 packages try to solve such situation automatically before the upgrade is performed.

If both or one of these files exists, the link is tracked and the target file is copied instead of the symbolic link.

Both *.default files have been renamed to *.example and are now always copied to the usual directory and should only be used as a reference. Otherwise they have no significance.

Thus, after upgrading to 4.1, the system should continue running without problems with the old *dispatch.conf* and *acl.conf* configuration. Nevertheless, we recommend to check these two files again after the upgrade is done.
