////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      30.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

= Quick Start

Dieses Kapitel bietet einen schnellen Einstieg in opsi. Als Erstes erklärt es, wie Sie einen opsi-Server mit Hilfe von docker oder der vorkonfigurierten virtuellen Maschine aufsetzen. Danach beschreiben weitere Unterkapitel, wie Sie neue opsi-Clients anlegen, vorhandene Rechner als opsi-Clients in die Umgebung integrieren und Produkte auf den Clients verteilen.


1. Installieren Sie einen opsi-Server. Entweder mit xref:server/server-installation-docker.adoc[docker] oder der vorgefertigten xref:server/server-installation-vm.adoc[VM].
2. Spielen Sie Produkte auf dem Server ein und verteilen Sie diese auf die Clients: xref:products/products.adoc[Produkte einspielen]. 
3. Registrieren Sie ein oder mehrere Clients am Server. Siehe hierzu xref:clients/client-installation.adoc[Clients hinzufügen].
4. xref:rollout/rollout.adoc[Verteilen] Sie Produkte auf die Clients.

NOTE: Eine ausführliche Beschreibung der Server-Installation mit allen Varianten finden Sie im Kapitel xref:server:overview.adoc[opsi-Server]. Die vollständigen Client-Handbücher finden Sie im Kapitel xref:clients:opsi-clients.adoc[opsi-Clients]. Dort liegen auch die Client-Handbücher für xref:clients:windows-client/windows-client-manual.adoc[Windows], xref:clients:linux-client/linux-client-manual.adoc[Linux], und xref:clients:macos-client/mac-client-manual.adoc[macOS].