////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      20.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

= Quick Start

Dieses Kapitel bietet einen schnellen Einstieg in opsi. Als Erstes erklärt es, wie Sie einen opsi-Server mit Hilfe von Docker oder der vorkonfigurierten virtuellen Maschine aufsetzen. Danach beschreiben weitere Kapitel, wie Sie neue opsi-Clients anlegen, vorhandene Rechner als opsi-Clients in die Umgebung integrieren und Produkte auf den Clients verteilen.

1. Installieren Sie einen opsi-Server, entweder mit xref:server/server-installation-docker.adoc[Docker] oder mit der vorgefertigten xref:server/server-installation-vm.adoc[virtuellen Maschine].
2. Laden Sie die Benutzeroberfläche xref:gui/configed.adoc[*opsi-configed*] herunter.
3. Stellen Sie Produkte auf dem Server bereit, indem Sie xref:products/products.adoc[opsi-Pakete einspielen].
4. Registrieren Sie ein oder mehrere Clients am Server (siehe xref:clients/client-installation.adoc[Clients hinzufügen]).
5. Rollen Sie die zuvor installierten xref:rollout/rollout.adoc[Produkte] auf den Clients aus.

NOTE: Eine ausführliche Beschreibung der Server-Installation mit allen Varianten finden Sie im Kapitel xref:server:overview.adoc[opsi-Server]. Die vollständigen Client-Handbücher finden Sie im Kapitel xref:clients:opsi-clients.adoc[opsi-Clients]. Dort liegen auch die Client-Handbücher für xref:clients:windows-client/windows-client-manual.adoc[Windows], xref:clients:linux-client/linux-client-manual.adoc[Linux], und xref:clients:macos-client/mac-client-manual.adoc[macOS].
