////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      21.04.2023
:Revision:  4.2
:toclevels: 6
:doctype:   book
:icons: font
:xrefstyle: full


ifeval::["{mode}" == "antora"]
include::common:partial$opsi_terms.adoc[]
endif::[]

[[opsi-getting-started-introduction]]
= Einführung

Diese Anleitung beschreibt, wie Sie einen {opsi-server} installieren. Die Inbetriebnahme eines {opsi-server}s erfolgt in mehreren Schritten:

. Installation des Servers
. Konfiguration des Servers (Netzwerk, Benutzer und Passwörter, {opsi-products})
. Einrichtung von Clients
. Einspielen vorhandener {opsi-products}
. Paketierung und Verteilung eigener Software

TIP: Für eine ausführliche Beschreibung der Features sowie Erklärungen zu den kostenpflichtigen Erweiterungen lesen Sie bitte xref:manual:introduction.adoc[opsi-Komponenten im Detail].

NOTE: Für die ersten Versuche mit opsi empfehlen wir, in einer Testumgebung und in einem isolierten Netzwerk zu arbeiten -- u.{nbsp}a. ohne konkurrierende DHCP-Server. Das Testnetz benötigt Internetzugriff, um bei Bedarf Pakete aus entfernten Quellen und Aktualisierungen zu installieren. Falls Sie bei der Einbindung in bestehende Netze Hilfe benötigen, link:https://uib.de/de/support-schulung/support/[kontaktieren Sie uns].

[[opsi-getting-started-introduction-term]]
== Auf der Kommandozeile arbeiten

Im weiteren Verlauf des Kapitels (und auch in den übrigen Kapiteln dieses Handbuchs) stellen wir Befehle vor, die Sie auf der Kommandozeile eingeben. Sie können das über eine Terminal-Anwendung direkt auf dem Server erledigen oder von einem anderen Rechner aus per SSH auf den {opsi-server} zugreifen. Unter Linux und macOS verwenden Sie dazu den Befehl `ssh`. Unter Windows können Sie das Programm link:https://www.chiark.greenend.org.uk/~sgtatham/putty/[PuTTY] verwenden. Als Benutzernamen geben Sie `root` ein authentifizieren sich mit dem bei der Installation angelegten root-Passwort.

Auf dem {opsi-server} gibt es unterschiedliche Möglichkeiten, ein Terminalfenster zu öffnen:

* Doppelklicken Sie das LXTerminal-Symbol in der grafischen Arbeitsoberfläche.

* Öffnen Sie das Startmenü und navigieren bis zu einer Terminal-Anwendung (Menü _Systemwerkzeuge_).

* Betätigen Sie die Tastenkombination [Alt]+[F2]; auf den meisten Desktops öffnet das einen Schnellstarter. Geben Sie `terminal` ein, um installierte Terminal-Programme aufzulisten, und wählen dann die gewünschte Anwendung aus.

TIP: Befehle aus diesem Handbuch sind so formatiert, dass Sie diese direkt per Copy{nbsp}&{nbsp}Paste in ein Terminalfenster übertragen können, sofern das Terminal-Programm das unterstützt.

Beispiele aus Konfigurationsdateien sind wie folgt formatiert:
[source,configfile]
----
depoturl = smb://smbhost/sharename/path
----

Befehle sind so formatiert:
[source,shell]
----
cd /tmp
ls -l
----
