////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      11.01.2021
:doctype: book

include::common:partial$opsi_terms.adoc[]

[[opsi-manual-dircon]]
= Collaboration with Directory Service (opsi-directory-connector)


[[opsi-manual-dircon-introduction]]
== Introduction

The opsi directory connector transfers data from an LDAP directory service to an opsi installation. This way it is no longer necessary to manage data on multiple systems--the automatic synchronisation reduces the administration effort. Since the directory connector uses LDAP in the background, it works with Active Directory as well as with Samba 4.


[[opsi-manual-dircon-preconditions]]
== Prerequisites

NOTE: This module is currently a link:https://www.opsi.org/product/extensions-of-opsi/[paid extension]. This means that you need an activation file to unlock it. You will receive this file after you have purchased the extension. For evaluation purposes, we're happy to provide you with a temporary license free of charge. Please contact us via mailto:info@uib.de[email].


ifdef::manual[]
For more details, please read <<opsi-manual-modules>>.
endif::manual[]


[[opsi-manual-dircon-preconditions-general]]
=== General Requirements

* The directory service on the machine serving as the source must implement the LDAP protocol.
* The target system must run opsi 4.0.7 or later. Older versions may work; however, we have not tested this.
* The machine running the directory connector must have network access to the machine running the directory service and to the {opsi-server}.

NOTE: You can run all components on the same machine. However, let's assume for now that there are multiple machines involved.

[[opsi-manual-dircon-requirements-hardware]]
=== Hardware Requirements

For a small environment with up to 500 opsi clients you need at least:

* 256{nbsp}MB free RAM
* Network Connections

NOTE: In larger environments, 256{nbsp}MB of RAM may not be sufficient. Adjust the hardware equipment of the machines if necessary.


[[opsi-manual-dircon-requirements-software]]
=== Software Requirements

Installation and operation of the Directory Connector is only supported on Linux. Support for Windows systems is not planned.

Since the extension uses standard protocols for communication over the network, no any additional opsi or directory service components are required.

[[opsi-manual-dircon-installation]]
== Installation

To install the Directory Connector, first add the opsi repository (see the chapter xref:getting-started:getting-started.adoc[Getting Started], sections on xref:getting-started:server/base-installation.adoc#opsi-getting-started-installation-base-deb[Debian/Ubuntu], xref:getting-started:server/base-installation.adoc#opsi-getting-started-installation-base-deb[openSUSE/SLES], and xref:getting-started:server/base-installation.adoc#opsi-getting-started-installation-base-centos-rhel[CentOS/RHEL]). Next, install the package `opsi-directory-connector` via the package manager of your distribution.

For example, on Debian-based systems, use this command:

[source,prompt]
----
apt-get install opsi-directory-connector
----

[[opsi-manual-dircon-configuration]]
== Configuration

The Directory Connector offers a wide range of settings to adapt it to very different environments. The configuration file `/etc/opsi/opsidirectoryconnector-custom.conf` is in JSON format and must contain valid JSON (key-value pairs). For boolean values use `true` or `false`; text is enclosed in double quotes (e.g. `"this is text"`).

TIP: Our package contains an example configuration. You can use the file `/usr/share/opsi-directory-connector/opsi-directory-connector.example.conf` as a template for your own configuration:

[source,prompt]
----
cp /usr/share/opsi-directory-connector/opsi-directory-connector.example.conf /etc/opsi/opsidirectoryconnector-custom.conf
----

[[opsi-manual-dircon-conf-dir]]
=== Connection to the Directory Service (`directory`)

In the `directory` section you configure the connection to the directory service. Here you can also limit the search scope to certain areas and objects.

[source,json]
----
{
    "directory": {
        "address": "ldap://192.168.12.34",
        "user": "DOMAIN\\opsiconnector",
        "password": "insertpasswordhere",
        "passwordFile": "",
        "search_base": "dc=testcompany,dc=local",
        "search_query_computers": "(objectClass=computer)",
        "identifying_attribute": "dn",
        "connection_options": {
            "paged_search_limit": 768
        }
    },
    …
}
----

Enter the address of the LDAP server after `address`. If the protocol `ldaps` or the port `636` is used, then the communication is SSL-encrypted:

[source,json]
----
        "address": "192.168.12.34:636",
----

In addition, enter the user name (`user`) and password (`password`) for authentication to the directory service.

TIP: To increase security, we recommend using a dedicated user account.

Instead of a password, you can enter the path to a file containing the password after `passwordFile`. The advantage of this is that the password is not stored in plain text in the configuration file. A password read from `passwordFile` overwrites any values set for `password`.

NOTE: The format of the user name depends on the directory service application in use and its configuration: +
*Down-Level Logon Name*: `DOMAIN\username` +
*User Principal Name (UPN)*: `user@domain` +
*Distinguished Name (DN)*: `uid=opsiconnect,cn=users,dc=test,dc=intranet`

Specify the point from which the connector looks for matching entries behind `search_base`.
The filter used to search for clients can be configured via `search_query_computers`.

From version 23, the optional key `identifying_attribute` specifies which attribute should be used for the unique identification of a client. The default setting is `dn`. A common alternative is `distinguishedName`, which is mainly used in the Microsoft's Active Directory.

The key `connection_options` defines additional options for the connection. For example, you can determine via `verify` whether or not the certificate is to be validated for an SSL connection. In addition, you can specify the path to a Certificate Authority (CA); enter the name of the file you want to use for verification here. If the connection is started via the unencrypted port 389, then `start_tls` determines whether a secure connection is started after the login. By default, `start_tls` is enabled for port 389, but the certificate is not checked.

If multiple queries are used to read the elements from the directory, then define the number behind the optional key `paged_search_limit`. The value must be an integer. The feature has been supported since version 20.

NOTE: Are you missing a connection option? If possible, we will implement further features on request. Please feel free to contact us via mailto:info@uib.de[email].

TIP: Since version 14 you can use the parameter `--check-directory` to test the connection to the directory without connecting to the {opsi-server}.

[[opsi-manual-dircon-conf-dir-ucs]]
=== Connection to Univention Corporate Server

For a connection to Univention Corporate Server (UCS), enter the _Distinguished Name_ (DN) as the user name. It has the following syntax:

[source]
----
uid=<username>,cn=users,dc=company,dc=mydomain
----

On UCS, LDAP is accessible via ports 7389 (unsecured) or 7636 (SSL-secured).
If Samba is also installed on the server and set up as an AD-compatible domain controller, it listens on ports 389 (unsecured) or 636 (SSL-secured).
To use the SSL-secured ports, set the `start_tls` connection option to `true`.

The two possible connections also differ as far as the login name is concerned:

* **LDAP**: `uid=…`
* **Samba**: `dn=…`

Normally, a search for computer objects takes place in the `computers` container.
The following command prints the matching value for `search_base`:

[source,prompt]
----
echo "cn=computers,$(ucr get ldap/base)"
----

To search for Windows clients, enter `(objectClass=univentionWindows)` as the value for `search_query_computers`.

TIP: The article https://help.univention.com/t/cool-solution-ldap-search-user-simple-authentication-account/11818[Cool Solution - LDAP search user / simple authentication account] in the Univention Knowledge Base explains how to create a user with _read-only_ access.


[[opsi-manual-dircon-conf-work]]
=== Behaviour Settings (`behaviour`)

These settings control the behaviour of the Directory Connector:

[source,json]
----
{
    …
    "behaviour": {
        "write_changes_to_opsi": true,
        "root_dir_in_opsi": "clientdirectory",
        "update_existing_clients": true,
        "prefer_location_from_directory": true,
        "group_handling": "dn",
        "group_description": "dn",
        "override_root_dir": true,
        "delete_empty_groups": false,
        "skip_adding_clients": false,
    },
    …
}
----

If you set `write_changes_to_opsi` to `false`, no data will be written to opsi. This is useful, for example, if you want to check the connection settings.

`root_dir_in_opsi` specifies which group in opsi should be used as root group. Make sure that this group exists.

NOTE: The management interface xref:../configed.adoc[opsi-configed] shows the group `clientdirectory` as `DIRECTORY`. So if clients or groups should appear directly below `DIRECTORY`, enter `clientdirectory` as the value for `root_dir_in_opsi`.

If you set `update_existing_clients` to `false`, then clients already existing in opsi will not be changed. If, on the other hand, this value is set to `true`, then any manually set data will be overwritten with the values from the directory service.

If `prefer_location_from_directory` is set to `true`, clients in opsi will be moved to the position they have in the directory service. Set the value to `false` to disable the behaviour.

Since version 31, the group handling is controlled by the optional key `group_handling`.
The default setting is `dn`. Groups are derived from the DN (Distinguished Name) of a computer and created accordingly as part of the opsi directory service. A client can only be a member of one single group.

If you activate `delete_empty_groups`, then groups which are empty after synchronisation are also deleted from the opsi directory service. Only groups below `root_dir_in_opsi` are considered in that case.

With `skip_adding_clients` you skip the creation of clients in opsi completely. You can use this option, for example, in conjunction with `prefer_location_from_directory` so that only existing clients are moved.

==== Settings for UCS@school

Set the key `group_handling` to `ucsatschool` to adapt the behaviour for link:https://www.univention.de/produkte/ucsschool/[UCS@school] environments. The Directory Connector then automatically searches for schools and determines their rooms. Afterwards, the synchronisation with opsi takes place.

For each school a group is created in opsi. In UCS@school, however, a computer can be a member in more than one room. Therefore, the Directory Connector does not create the groups as a group in the opsi directory service, but as a normal group. In this way, a client can also be in multiple groups in opsi.

If the UCS@school groups are to be created in the opsi directory service after all, set the key `override_root_dir` to `false`. The key `override_root_dir` is only available for `"group_handling": "ucsatschool"`. The default value is `true`.
If `override_root_dir` is set to `false`, then make sure that each school computer is only assigned to one room.

Via `group_description` you can customise the description of the opsi groups. The following values are possible:

* `dn`: The distinguished name of the group will be stored in opsi as the group description.
* `directory`: The group description is read from the field `description` of the directory service group.
* If the value is not set or is set differently, the name of the group is entered as the description.

[source,json]
----
…
 "behaviour": {
        "group_handling": "ucsatschool",
        …
        "group_not_in_directory": true,
        "opsi_clients_to_ignore": {
            "clients": ["win1.uib.local","win2.uib.local","win3.uib.local"],
            "groups": ["server"]
        }
 }
 …
----

If `group_not_in_directory` is set to `true`, then all clients which aren't available in the directory service are added to the group `not_in_directory`. This option is only available with the setting `"group_handling": "uscatschool"`. With the parameter `opsi_clients_to_ignore` you can exclude clients or whole groups from this rule.

TIP: A short description of all configuration options can also be found in the sample configuration file (`/usr/share/opsi-directory-connector`).


[[opsi-manual-dircon-conf-mapping]]
=== Mappings

With a system as flexible as a directory service, the connector needs information about which attributes in the directory should be matched to which attributes in opsi.

[source,json]
----
{
    …
    "mapping": {
        "client": {
            "id": "name",
            "description": "description",
            "notes": "",
            "hardwareAddress": "",
            "ipAddress": "",
            "inventoryNumber": "",
            "oneTimePassword": ""
        }
    },
    …
}
----

There is a mapping for client attributes.
The key of the mapping is the attribute in opsi and the value is the attribute from the directory service. If the value (in the mapping) is empty, no mapping will be done.

NOTE: If the value read from the directory for the ID of the client is not recognizable as a FQDN, a corresponding FQDN will be created.
The domain part for this is formed from the DC values of the element.

TIP: On Univention Corporate Server (UCS), the value for `hardwareAddress` can be set to `macAddress` if the connection is established via LDAP (port 7389 or 7636).

In the "mapping" area, the assignment of clients to depots can be defined. Currently there is only the mapping type "network"..
With the "network" type, a client is assigned to a depot if the ip address of the client matches the network address range ("networkAddress") of the depot.
Alternatively, a list of network ranges can be assigned to a depot.

[source,json]
----
{
    …
    "mapping": {
        …
        "depot": {
            "type": "network",
            "test-depot1.test.local": ["192.168.24.0/24","192.168.25.0/24"],
            "test-depot1.test.local": ["192.168.27.0/24","192.168.28.0/24"]
        }
    },
    …
}
----



[[opsi-manual-dircon-conf-mapping-groupnames]]
=== Manual assignment of group names

Group names can usually abe used without any major adjustments.
However, it can happen that group names exist which are invalid in opsi.

For these special cases, a manual assignment of group names can be made, which allows these cases to be handled.

To configure this, an entry `group_name` is created in `mapping`, which holds the mapping from the directory service to opsi.
The name is not changed for groups that do not appear in this assignment.
Group names are always processed in lower case letters, which is why the entries here must be made in lower case letters.
This is possible since version 23.

The following example maps the group `_server` originating from the directory service to the group `server` in opsi.

[source,json]
----
{
    …
    "mapping": {
        "client": {
            …
        },
        "group_name": {
            "_server": "server"
        }
    },
    …
}
----

WARNING: Please be careful with this feature as it may introduce undesirable side effects. Therefore, this option should only be used for special cases.


[[opsi-manual-dircon-conf-conect]]
=== opsi connection settings

This controls how the connector connects to opsi.

[source,json]
----
{
    …
    "opsi": {
        "address": "https://localhost:4447",
        "username": "syncuser",
        "password": "secret",
        "exit_on_error": false,
        "passwordFile": "",
        "connection_options": {
            "verify_certificate": true
        }
    }
}
----

Enter the address of the opsi server under `address`.
Do not forget to specify the port!

NOTE: A proxy for the connection can be set via the environment variable 'HTTPS_PROXY'.

`User` and `password` are used for authentication to the opsi server.
If a value is given for `passwordFile`, this is interpreted as the path to a file that contains the password.
The content of this file will be used as the password.
This means that the password does not have to be stored in plain text in the configuration file.
This will override the value set for `password`, if the file can be read.

TIP: We recommend using a dedicated user account. The creation of additional users is described in the _Getting Started_ manual.

If the parameter `exit_on_error` is set to `true`, then any problem when updating the data in opsi - this can also be triggered by submitting values that are invalid in opsi - results in a break.
If this is set to `false`, errors are logged, but the execution is not terminated.

Under `connection_options` options for the connection to the opsi server can be set.
The verification of the server certificate is controlled by means of `verify_certificate`.
This value should be set to `false` when using self-signed certificates.

Since version 14 it is possible to test the connection to the opsi server via the parameter `--check-opsi`, without establishing a connection to the directory service.


[[opsi-manual-dircon-run]]
== Running the connector

After the installation a binary called `opsi-directory-connector` will be present on the system.

It is required to pass an argument `--config` together with the path to the configuration file.

[source,prompt]
----
opsi-directory-connector --config /etc/opsi/opsi-directory-connector-custom.conf
----

NOTE: The user running the binary does not require any access to opsi as this is all stored in the configuration file.


[[opsi-manual-dircon-run-systemd]]
=== Example: recurring runs with systemd

The connector currently does one synchronisation run when executed, but the chances are good that you want to have a constant synchronisation of data.

It's easy to automate the execution of repetitive runs.

We will be using systemd for this.
In contrast to cronjobs, systemd will prevent simultaneous runs from occurring, which is why systemd is a good choice.

The following example will set up the connector to run five minutes after the machine starts, and every hour thereafter.

The following two files must be stored under `/etc/systemd/system/`, the directory for user-defined units.
One file is the timer, which calls our job repeatedly and the other is for the job itself.

Please fill the file `opsi-directory-connector.timer` with the following content:

[source,configfile]
----
[Unit]
Description=Start the opsi-directory-connector in regular intervals

[Timer]
OnBootSec=5min
OnUnitActiveSec=1hour

[Install]
WantedBy=timers.target
----

And this is the content of `opsi-directory-connector.service`:

[source,configfile]
----
[Unit]
Description=Sync clients from AD to opsi.
Wants=network.target

[Service]
Type=oneshot
ExecStart=/usr/bin/opsidirectoryconnector --config /etc/opsi/opsidirectoryconnector-custom.conf
----

To enable the timer and start it right away, the following commands can be used:

[source,prompt]
----
systemctl enable opsi-directory-connector.timer
systemctl start opsi-directory-connector.timer
----

If the timer does not get started, it will start to run the next time the machine is restarted.


[[opsi-manual-dircon-run-cronjob]]
=== Example: recurring runs as cronjob

It is easy to automate the execution of recurring runs through a crobjob.

Please note that simultaneous runs can take place, which is why it is best to choose a larger synchronisation interval.
To avoid this problem, it is recommended to use *systemd* instead of *cron*!

The cronjob file can usually be edited through `crontab -e`.
For a synchronisation that happens every hour the following can be used:

[source,prompt]
----
0 * * * * /usr/bin/opsidirectoryconnector --config /etc/opsi/opsidirectoryconnector-custom.conf
----

=== command line arguments

[source,prompt]
----
Usage: __main__.py [-h] [--version] [--log-level {0,1,2,3,4,5,6,7,8,9}]
                   [--log-level-stderr {0,1,2,3,4,5,6,7,8,9}]
                   [--log-level-file {0,1,2,3,4,5,6,7,8,9}]
                   [--log-file LOG_FILE]
                   [--max-log-size MAX_LOG_SIZE]
                   [--keep-rotated-logs KEEP_ROTATED_LOGS]
                   [--check-directory | --check-opsi | --delete-clients DELETE_CLIENTS [DELETE_CLIENTS …]]
                   [--dry-run] --config
                   CONFIG

If an arg is specified in more than one place, then commandline values override environment
variables which override defaults.

optional arguments:
  -h, --help
                              show this help message and exit
  --version
                              show program's version number and exit
  --log-level {0,1,2,3,4,5,6,7,8,9}
                              Sets how much information will be logged. [env var: OPDC_LOG_LEVEL]
                              (default: 4)
  --log-level-stderr {0,1,2,3,4,5,6,7,8,9}, -l {0,1,2,3,4,5,6,7,8,9}
                              Sets how much information will be logged. [env var:
                              ODC_LOG_LEVEL_STDERR] (default: 4)
  --log-level-file {0,1,2,3,4,5,6,7,8,9}
                              Sets how much information will be logged to the log file. [env var:
                              ODC_LOG_LEVEL_FILE] (default: 5)
  --log-file LOG_FILE
                              Sets log file path. [env var: ODC_LOG_FILE] (default:
                              /var/log/opsi/directory-connector.log)
  --max-log-size MAX_LOG_SIZE
                              Limit the size of logfiles to SIZE megabytes.Setting this to 0 will
                              disable any limiting. [env var: ODC_MAX_LOG_SIZE] (default: 5.0)
  --keep-rotated-logs KEEP_ROTATED_LOGS
                              Number of rotated log files to keep. [env var: ODC_KEEP_ROTATED_LOGS]
                              (default: 1)
  --check-directory
                              Check if a connection to the directory can be established and if items
                              will be received. (default: False)
  --check-opsi
                              Check if a connection to the opsi server can be established. (default:
                              False)
  --delete-clients DELETE_CLIENTS [DELETE_CLIENTS …]
                              Delete list of clients from directory. (default: None)
  --dry-run
                              Print what would be done. (default: False)
  --config CONFIG
                              Path to the config. (default: None)
----

Starting with version 39 the opsi-directory-connector uses the OPSI logger with loglevel 0-9. By default logs are written to `/var/log/opsi-directory-connector` and to `stderr`. With the parameters `--log-level-stderr`, `--log-level-file` the log level of the respective log can be set. `--log-file` defines the log file.

The log file is rotated after a specified size (default 5 MB) and by default one of these rotated log files is kept. The parameters `--max-log-size` and `--keep-rotated-logs` can be used to override the default values.

In addition to the command line parameters, the values can also be set in the configuration file or via environment variables. The following applies here:

- Parameters overwrite everything
- Environment variables overwrite configuration and default
- Configuration overwrites default

Example configuration:

[source,prompt]
----
{
…
    "log-level-stderr": 6,
    "log-level-file": 3,
    "keep-rotated-logs": 4
…
}
----

If the directory connector is started with the `--dry-run` option, the individual steps are output without making any changes in OPSI.
With `dry-run`, in contrast to the configuration parameter `write_changes_to_opsi: false`, the output is adjusted,
to give a better overview of the actions. Example output:

[source,prompt]
----
---------- opsi actions ----------
Creating client client1.opsidc.intranet.
Creating client ds-win-client-2.opsidc.intranet.
Creating client ds-win-client-1.opsidc.intranet.
Creating client mac-client-1.opsidc.intranet.
Creating client windows-client-1.opsidc.intranet.
Creating client raspberrypi-1.opsidc.intranet.
Adding mac-client-1.opsidc.intranet to opsitestschool-mac pool.
Adding windows-client-1.opsidc.intranet to opsitestschool-pc pool og1.
Adding ds-win-client-2.opsidc.intranet to depotschule-pool-1.
Adding ds-win-client-1.opsidc.intranet to depotschule-pool-1.
----------------------------------
---------- summary ---------------
Create  6 clients and 0 groups.
0 clients removed from group.
Adding 4 clients to a new group.
----------------------------------
----

== Delete Clients from the directory

In the standard case the opsi-directory-connector has only read access to the directory. With the start parameter `--delete-clients` an independent run is started, which tries to delete the given objects from the directory.
For example:

[source,prompt]
----
opsi-directory-connector --config config.conf --delete-clients client1
----

The objects can be specified more precisely:

[source,prompt]
----
opsi-directory-connector --config config.conf --delete-clients computers/test-clients/client1
----

This call would fit on object `cn=client1,ou=test-clients,ou=computers,dc=example,dc=org`, but not
`cn=client1,ou=clients,ou=computers,dc=example,dc=org`. So the first object will be deleted.

Multiple clients can also be specified:

[source,prompt]
----
opsi-directory-connector --config config.conf --delete-clients computers/clients/client1 client2 client3
----

WARNING: The `delete-clients` function should be used with caution.

TIP: The `dry-run` function can also be used with `delete-clients`.
