////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      18.04.2023
:Revision:  4.2
:toclevels: 3
:icons: font
:xrefstyle: full
:doctype:   book

// Include common opsi terms
ifeval::["{mode}" == "antora"]
include::common:partial$opsi_terms.adoc[]
endif::[]

[[opsi-4.2-releasenotes]]
= Version 4.2

TIP: Eine Liste mit aktuell unterstützten Linux-Distributionen für den opsi-Servern sowie für den opsi-Client (Windows, Linux und macOS) finden Sie im Kapitel xref:supportmatrix:supportmatrix.adoc[opsi-Support-Matrix].

[[opsi-4.2-releasenotes-overview]]
== Neue Features (Schwerpunkte)

* Wechsel zu Python 3
* Alle Python-Applikationen werden als ausführbare Binärdateien verteilt.
* opsi-python-Interpreter für eigene Skripte
* opsi-Server:
** Komplette Neuimplementierung des `opsiconfd` mit Schwerpunkt auf Performance und Scalability
** `opsiconfd` ist nun auch im Docker-Container lauffähig.
** Neue Abhängigkeit zu Redis-Server >= 5, inklusive dem RedisTimeSeries-Modul
** Grafana zur Visualisierung von Performancedaten
** Neue Default-ACLs für den API-Zugriff

[[opsi-4.2-releasenotes-important]]
== Wichtige Hinweise

opsi 4.2 ist ein eigenständiges Release und hat seine eigenen Repositorys.
Fügen Sie die neuen Repositorys hinzu und entfernen Sie die Repositorys der Vorgängerversion.
Erst danach können Sie die Installation bzw. die Aktualisierung durchführen.

TIP: Hinweise zur Aktualisierung von opsi 4.1 auf 4.2 finden Sie im Abschnitt <<opsi-4.2-releasenotes-installation-migration>>.

=== Python 3

opsi 4.2 basiert komplett auf Python 3.
Weiterhin werden alle Python-basierten Pakete als ausführbare Binärdateien verteilt.
Das Paket `python-opsi` steht nicht länger als installierbares Paket zur Verfügung.
Deshalb ist es wichtig, folgende Punkte zu beachten:

[[opsi-4.2-releasenotes-important-reinstall-opsi-packages]]
==== opsi-Pakete mit serverseitigen Python-Skripten

Nutzen Sie nach der Aktualisierung des opsi-Servers auf opsi 4.2 das Werkzeug `opsi-package-manager`, um die opsi-Pakete neu zu installieren, die Python-Skripte für die Ausführung auf dem Server enthalten:

* opsi-Client-Agent: `opsi-deploy-client-agent`
* Windows: `create_driver_links.py`, `show_drivers.py`

Das `postinst`-Skript korrigiert diese Skripte automatisch und setzt den neuen Interpreter `opsi-python`.

Alternativ dazu können Sie die Python-Skripte auch von Hand korrigieren.
Dazu tragen Sie den Interpreter `opsi-python` als Shebang in die erste Zeile des Skripts ein:

[source,prompt]
----
#!/usr/bin/opsi-python
----

==== Eigene Python-Skripte, die `python-opsi` nutzen

Setzen Sie in Ihrer Umgebung Skripte ein, die den alten Interpreter `python-opsi` nutzen, führen Sie folgende Schritte aus:

* Konvertieren Sie die Skripte auf Python 3 (z.{nbsp}B. mit dem Python-Tool `2to3`).
* Tragen Sie den neuen Interpreter `opsi-python` als Shebang in die erste Zeile des Skripts ein:

[source,prompt]
----
#!/usr/bin/opsi-python
----

==== Backend-Erweiterungen 

Falls Sie Konfigurationsdateien unter `/etc/opsi/backendManager/extend.d` verändert oder dort neue Dateien abgelegt haben, prüfen Sie diese, ob sie kompatibel mit Python 3 sind. Gegebenenfalls passen Sie diese an.

=== Gruppe `pcpatch` => `opsifileadmins`

Mit opsi 4.2 wurde der Standard-Name für die opsi-Datei-Admin-Gruppe von 'pcpatch' in 'opsifileadmins' geändert.
Bei einem Upgrade von opsi 4.1 wird jedoch der bisher verwendete Name weiterverwendet.
Der Name kann in der Konfigurations-Datei `/etc/opsi/opsi.conf` über Option `fileadmingroup` der Sektion `groups` angepasst werden.
Bei einem Wechsel auf die Gruppe 'opsifileadmins' ist zu beachten, dass auch der Benutzer 'pcpatch' dieser Gruppe hinzugefügt werden muss.


=== opsiconfd Konfiguration und Logs
Es gibt einige Änderung bei der Konfiguration und den Logs des 'opsiconfd'.

* Alle Konfigurationsoptionen sind im Hilfetext des opsiconfd dokumentiert ('opsiconfd --help').
* Diese Kommandozeilenparameter können auch in der Konfigurations-Datei `opsiconfd.conf` verwendet werden (ohne '--').
* Der opsiconfd hat nun eine eingebaute Log-Rotation. Diese kann mit den Optionen 'max-log-size' und 'keep-rotated-logs' konfiguriert werden.
* Die Logdatei 'package.log' ist nun Bestandteil der 'opsiconfd.log'.
* Die Logs beinhalten nun einen Kontext, welche für die Filterung der Logs genutzt werden können. Zum Beispiel kann man mit 'grep' nach diesen filtern oder dem opsiconfd beim Start die Option '--log-filter LOG_FILTER' mitgeben:

[source,prompt]
----
opsiconfd --log-filter instance=package_install
----

[source,prompt]
----
[6] [2020-09-07 14:41:17.864] [package_install] Running postinst script   (Depotserver.py:235)
[5] [2020-09-07 14:41:17.865] [package_install] Running package script 'postinst'   (Product.py:477)
...
----

[source,prompt]
----
opsiconfd --log-filter client_addr=10.100.7.5
----

[source,prompt]
----
[6] [2020-09-07 14:25:16.966] [10.100.7.5     ] Filtering objects by acls   (AccessControl.py:475)
...
----

=== Verifizierung der Server-Identität

Seit opsi 4.2 kann die Vertrauenswürdigkeit des opsi-server über TLS-Standard-Methoden sichergestellt werden.
Jeder opsi-configserver verwaltet eine Certificate Authority (CA), die opsi CA. Diese CA wird vom opsi-configserver
automatisch verwaltet. Jeder opsi-server, auch die opsi-depotserver erhalten vom opsi-configserver ein TLS-Zertifikat,
das von dieser CA signiert ist. Auch diese Zertifikate werden automatisch erstellt, verteilt und bei Bedarf aktualisiert.
Jeder Client, der der opsi CA vertraut, vertraut auch diesen Server-Zertifikaten.

Dies betrifft vor allem die Option 'verify_server_cert' und 'verify_server_cert_by_ca'. Für nähere Informationen bitte enstprechendes Kapitel im opsi-manual nachlesen.

=== Abkündigung vom opsi4ucs Paket

Im Rahmen von opsi 4.2 wurde der UCS-Support den anderen Distributionen angepasst. Die Funktion von opsi4ucs übernimmt ab opsi 4.2 das opsi-server Paket und dessen Varianten.
Das opsi4ucs Paket existiert in opsi 4.2 als Transitionpaket, um die Migration von opsi 4.1 Installationen zu vereinfachen. Während des Upgradeprozesses wird das opsi4ucs Paket automatisch durch die opsi-server Pakete ersetzt.


[[opsi-4.2-releasenotes-installation]]
== Installationshinweise

Wir empfehlen dringend for dem Update eine Sicherung der Backends mit {opsi-backup} zu erstellen:
[source,prompt]
----
opsi-backup create
----

Alle opsi-Komponenten, die im Rahmen dieses Releases veröffentlicht werden, sind an vielen Stellen voneinander abhängig.
Es sollten daher immer alle Komponenten aktualisiert werden.

Wir empfehlen zuerst den Server und danach die opsi-Pakete (Produkte) zu aktualisieren.

In einer Multi-Depot-Umgebung wird empfohlen die Aktualisierung auf dem Configserver zu beginnen und erst danach die Depots zu aktualisieren.

Wir empfehlen nach dem Update die Ausführung von `opsi-setup --set-rights`, um sicher zu stellen, dass die Zugriffsberechtigungen korrekt gesetzt sind.
Die Ausführung des Befehls kann mehrere Minuten in Anspruch nehmen.


[[opsi-4.2-releasenotes-installation-systempackages]]
=== Hinweise zum Aktualisieren der Betriebssystem-Pakete

Bitte stellen Sie sicher, dass Sie zum Zeitpunkt der Aktualisierung die jeweils aktuellsten Pakete von opsi 4.1 aus dem Stable-Bereich verwenden!


[[opsi-4.2-releasenotes-installation-opsipackages]]
=== Hinweise zum Aktualisieren von opsi-Paketen

opsi-Pakete sind in der Regel kompatibel zu sowohl opsi 4.1 als auch opsi 4.2.

Die offiziellen opsi 4.2-Repositorys auf _download.uib.de_ enthalten Pakete, welche mit opsi 4.1 kompatibel sind.
Bitte beachten Sie, dass diese Pakete nicht zwingend `4.2` als Version angegeben haben müssen, um kompatibel zu sein.


[[opsi-4.2-releasenotes-installation-migration]]
=== opsi-4.1-Server aktualisieren

Für ein Upgrade von opsi 4.1 müssen die installierten Pakete auf dem letzten opsi 4.1 stable Stand sein.
Andere Pakete - wie z.B. MySQL server - sollten ebenfalls aktuell sein.
Andernfalls kann es zu Fehlern im Upgrade-Prozess kommen.

Es wird ebenfalls dringend empfohlen vor dem Upgrade die Pakete 'opsi-winst', 'opsi-client-agent' bzw. 'opsi-linux-client-agent' auf allen Clients auf die aktuellsten opsi 4.1-Versionen zu aktualisieren.

Auf unterstützten Betriebsystemen ist es möglich eine bestehende opsi 4.1-Installation auf opsi 4.2 zu migrieren.

Falls die opsi-Server durch opsi verwaltet werden, kann die Migration über das Paket `l-opsi-server-migrate` durchgeführt werden.

NOTE: Eine Aktualisierung von opsi 4.0 direkt auf opsi 4.2 wird nicht unterstützt. In diesen Fällen muss erst eine Aktualisierung auf opsi 4.1 durchgeführt werden, bevor eine Aktualisierung auf opsi 4.2 möglich ist.

[[opsi-4.2-releasenotes-installation-migration-prerequired]]
==== Vorbedingung für eine Migration

Der opsi-Server benötigt ab Version 4.2 Zugriff auf eine Redis- und eine Grafana-Instanz.
Sollen diese Dienste ebenfalls auf dem opsi-Server bereitgestellt werden, empfehlen wir einen Umstieg auf das Paket 'opsi-server-full' während der Migration. Dieses Paket installiert und konfiguriert alles notwendige auf dem opsi-Server (im folgenden wird dies als Single-Server-Setup beschrieben).

Für die Installation von Grafana werden die Grafana-Repositorys benötigt:

===== Debian/Ubuntu:

[source,prompt]
----
sudo apt-get install -y apt-transport-https software-properties-common wget gnupg
wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
echo "deb https://packages.grafana.com/oss/deb stable main" > /etc/apt/sources.list.d/grafana.list
----

===== RHEL/CentOS:

[source,prompt]
----
yum install wget
cd /etc/yum.repos.d
cat <<EOF > grafana.repo
[grafana]
name=grafana
baseurl=https://packages.grafana.com/oss/rpm
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://packages.grafana.com/gpg.key
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
EOF
----

===== openSUSE:

[source,prompt]
----
zypper install wget
cd /etc/zypp/repos.d
cat <<EOF > grafana.repo
[grafana]
name=grafana
baseurl=https://packages.grafana.com/oss/rpm
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://packages.grafana.com/gpg.key
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
EOF
----


[[opsi-4.2-releasenotes-installation-migration-repositories]]
==== Wechseln zu den neuen Repositorys

Als erstes müssen die opsi 4.2-Repositorys in die Paketquellen Ihres Betriebsystems eingetragen werden.

Die nachfolgenden Befehle fügen die neuen Repositorys und, sofern benötigt, den Repository-Schlüssel hinzu.
Diese folgenden Befehle benötigen 'root'-Rechte.

*Ubuntu 20.04 LTS _Focal Fossa_:*
[source,prompt]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_20.04/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_20.04/Release.key | sudo apt-key add -
----

*Ubuntu 18.04 LTS _Bionic Beaver_:*
[source,prompt]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_18.04/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_18.04/Release.key | sudo apt-key add -
----

*Debian 11 _Bullseye_:*
[source,prompt]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Debian_11/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Debian_11/Release.key | sudo apt-key add -
----

*Debian 10 _Buster_:*
[source,prompt]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Debian_10/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Debian_10/Release.key | sudo apt-key add -
----

*CentOS 8:*
[source,prompt]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/CentOS_8/home:uibmz:opsi:4.2:{release}.repo
yum makecache
----

*RHEL 8:*
[source,prompt]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/RHEL_8/home:uibmz:opsi:4.2:{release}.repo
yum makecache
----

*openSUSE Leap 15.1:*
[source,prompt]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/openSUSE_Leap_15.1/home:uibmz:opsi:4.2:{release}.repo
zypper refresh
----

*openSUSE Leap 15.2:*
[source,prompt]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/openSUSE_Leap_15.2/home:uibmz:opsi:4.2:{release}.repo
zypper refresh
----

*SLES 15 SP 1:*
[source,prompt]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/SLE_15_SP1/home:uibmz:opsi:4.2:{release}.repo
zypper refresh
----

*SLES 15 SP 2:*
[source,prompt]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/SLE_15_SP1/home:uibmz:opsi:4.2:{release}.repo
zypper refresh
----

*Univention UCS 4.4:*
[source,prompt]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Univention_4.4/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Univention_4.4/Release.key | sudo apt-key add -
----


[[opsi-4.2-releasenotes-installation-migration-migrate]]
==== Aktualisierung der Betriebssystem-Pakete

Nach dem Eintragen der neuen Paketquellen kann das System migriert werden.

IMPORTANT: Die Standard-ACLs (`/etc/opsi/backendManager/acl.conf`) wurden mit opsi 4.2 aus Sicherheitsgründen verändert.
Wir empfehlen daher dringend die neue Version der Konfigurationsdatei zu verwenden.

IMPORTANT: Bei RPM-basierten Distributionen werden im Rahmen der Migration bereits vorhandene Konfigurationsdateien durch neue ersetzt. Beachten Sie hierzu die Hinweise unter den entsprechenden Distributionen.

Debian und Ubuntu werden mit folgenden Befehlen auf opsi 4.2 aktualisiert:

*Single-Server-Setup:*
[source,prompt]
----
apt update
apt install opsi-server-full
----

*Manuelles Setup:*
[source,prompt]
----
apt update
apt install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
apt dist-upgrade
----

RedHat und CentOS werden mit folgenden Befehlen auf opsi 4.2 aktualisiert:

*Single-Server-Setup:*
[source,prompt]
----
yum makecache
yum install opsi-server-full
yum upgrade
----

*Manuelles Setup:*
[source,prompt]
----
yum makecache
yum install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
yum upgrade
----

OpenSUSE bzw SUSE Linux Enterprise Server (SLES) wird mit folgenden Befehlen auf opsi 4.2 aktualisiert:

*Single-Server-Setup:*
[source,prompt]
----
zypper refresh
zypper install opsi-server-full
----

*Manuelles Setup:*
[source,prompt]
----
zypper refresh
zypper install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
zypper dup --from home_uibmz_opsi_4.2_{release}
----

Univention UCS wird mit folgenden Befehlen auf opsi 4.2 aktualisiert:

*Single-Server-Setup:*
[source,prompt]
----
univention-install opsi-server-full
----

*Manuelles Setup:*
[source,prompt]
----
univention-install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
univention-install opsi-server
----

[[opsi-4.2-releasenotes-installation-migration-opsi-packages]]
==== Aktualisierung der opsi-Pakete

Der letzte Schritt ist die Aktualisierung auf die neuesten opsi-Pakete.

[[opsi-4.2-releasenotes-installation-migration-opsi-packages-standard]]
===== Verwendung der Standardkonfiguration

Wenn Sie keine Veränderungen gegenüber der Standard-Auslieferung unter `/etc/opsi/package-updater.repos.d/` vorgenommen haben, können Sie die opsi-Pakete direkt über den aufgeführten Aufruf aktualisieren:

[source, prompt]
----
opsi-package-updater -v update
----

==== Opsi-Pakete die Server-seitige Python Skripte enthalten
Bitte installieren Sie opsi-Pakete neu, die Python-Skripte für die Ausführung auf dem Server enthalten.
Dies sind in der Regel `opsi-client-agent`, `opsi-linux-client-agent` und alle Pakete die Windows-Betriebssysteme installieren (`win*`).
Details hierzu sind an dieser Stelle zu finden: <<opsi-4.2-releasenotes-important-reinstall-opsi-packages>>.

Nach diesen Schritten ist Ihr opsi 4.1 Server auf das Release 4.2 migriert und einsatzbereit.

////
[[opsi-4.2-releasenotes-installation-migration-cleanup]]
==== Optionale Aufräumarbeiten

After a migration it can be that some unrequired files still exist on the server.
The reason for this is that they either have been altered manually or that restoring a backup has brought these files back to the system.

The following files resp. folders can be removed:

* TBD
////

[[opsi-4.2-releasenotes-installation-migration-4.0.7]]
===== Upgrade von opsi 4.0.7
Wenn Sie von einem opsi 4.0.7 kommen, sollten Sie opsi 4.1 überspringen und direkt auf opsi 4.2 aktualisieren.
* Aktualisieren Sie zunächst Ihr Serverbetriebssystem auf eine Version, die von opsi 4.0.7 und 4.2 unterstützt wird (z.B. Ubuntu 18.04).
* Dann aktualisieren Sie Ihren opsi-Server auf opsi 4.2 wie oben beschrieben.
* Zuletzt aktualisieren Sie den opsi-client-agent auf die letzte stabile Version 4.2.


[[opsi-4.2-releasenotes-knownbugs]]
== Known Bugs / Known Problems

.KNOWN BUGS:

* opsi-admin: Der interaktive Modus funktioniert nicht mit non-ASCII Zeichen wie Umlaute ö, ä, ü.


[[opsi-4.2-releasenotes-eol]]
== Abkündigung

In diesem Kapitel werden die Abkündigungen aufgelistet.

[[opsi-4.2-releasenotes-eol_opsi41]]
=== EOL: opsi 4.1 Q4/2021

Bisher haben wir den jeweiligen opsi-Vorgänger (oldstable) mindestens ein Jahr lang parallel zur aktuellen Version unterstützt. In diesem Fall haben wir uns aber entschieden, die Zeit auf die Hälfte zu verkürzen und opsi 4.1 für das 4. Quartal 2021 (30.11.2021) abzukündigen. Der Hauptgrund für die verkürzte EOL-Zeit: Nicht alle aktuellen Betriebssysteme unterstützen opsi 4.1, darunter z. B. Ubuntu 20.04.
opsi 4.1 basiert komplett auf Python 2, und diese Version hat bereit im April 2020 das EOL erreicht und erhält keine Updates mehr.

Über die https://www.uib.de/de/support-schulung/support[opsi-Supportverträge] unterstützen wir Sie gerne beim Update auf die neue opsi-Version. Auch nach dem EOL von opsi 4.1 sind wir für Sie da und helfen bei Migrationen – wir empfehlen aber dringend, die Zeit bis zum Ende von Q4/2021 zu nutzen und auf opsi 4.2 zu aktualisieren.

[[opsi-4.2-releasenotes-eol_server]]
=== Abkündigung: Distributionen für opsi-server

Diese Distributionsversionen werden aus verschiedenen Gründen nicht weiter von opsi unterstützt.

* CentOS 7.x
* Debian 8.x
* RedHat Enterprise Linux 7.x
* Suse Linux Enterprise Server 12

[[opsi-releasenotes-4.2-changes-changed-defaults]]
== Geänderte Standardeinstellungen

Mit opsi 4.2 wurden einige Standard-Einstellungen geändert, um Erfahrungen aus dem opsi-Betrieb wiederzuspiegeln.

Wichtig ist dies vorallem, wenn in einer bestehenden Umgebung neue opsi-Server installiert werden, da sich diese unter Umständen anders verhalten.

* Die geänderte acl.conf beachten.


[[opsi-releasenotes-4.2-changes-python]]
== Wechsel zu Python 3 und PyInstaller

Diese Version basiert auf Python 3.
Alle opsi Python Applikationen (opsiconfd, opsipxeconfd, opsiclientd, opsi-utils, ...) werden nun als ausführbare Dateien mit PyInstaller ausgeliefert.
Bitte nutzen Sie den `opsi-python` Interpreter für Ihre eigenen Skripte, welche Zugriff auf die python-opsi library benötigen.

[[opsi-releasenotes-4.2-changes-mysql-config]]
== MySQL backend: Limitierung der "connection lifetime"

Um die Fehlermeldungen: "mysql server has gone away" zu vermeiden, wurde die Standardkonfiguration des MySQL Backends geändert. Die Option `connectionPoolRecycling` hat nun als Standardwert: _28800_.
Diese Einstellung limitiert die Lebenszeit der Verbindungen im Connection Pool, welches für die Verbindungen zu MySQL (bzw. MariaDB) Server genutzt wird.


[[opsi-4.2-releasenotes-api-changes]]
== Änderung der API

Die API hat in opsi 4.2 Änderungen erhalten.

Betroffen hiervon sind u.A. die API des Webservices, opsi-admin und mittels opsiServiceCall getätigte Aufrufe in opsi-script.


[[opsi-4.2-releasenotes-changed-api-methods]]
=== Geänderte API-Methoden

* `getClients_listOfHashes`: Diese Methode wurde bei opsi 4.1 als "deprecated" markiert. Bei Aufruf ohne Parameter liefert diese Methode die Ausgabe von `getClients`. In allen anderen Fällen wird ein Fehler zurückgegeben.
* `getClientIds_list`: Diese Methode wurde bei opsi 4.1 als "deprecated" markiert. Bei Aufruf ohne Parameter liefert diese Methode die Ausgabe von `getClientIDs`. Wenn der Aufruf mit dem Parameter `depotIds` wird die Ausgabe von `getClientsOnDepot` zurückgegeben. Wenn der Parameter `productId` und optional `installationStatus` übergeben wird die Ausgabe von `getClientsWithProducts` zurückgegeben.


[[opsi-4.2-releasenotes-deprecated-api-methods]]
=== Veraltete API-Methoden

Die folgenden Methoden werden als veraltet angesehen. Sie werden mit dem nächsten Major oder Minor Release entfernt werden.

* `getClients_listOfHashes`
* `getClientIds_list`


[[opsi-4.2-releasenotes-removed-api-methods]]
=== Entfernung von API-Methoden

Die folgenden API-Methoden wurden entfernt:

* `backend_searchIdents`

Diese Methoden stehen nicht mehr zur Verfügung.


[[opsi-4.2-releasenotes-misc]]
== Sonstiges

* opsiwebservice unterstützt keine "deflate" kodierten Daten als Kompressionsverfahren.


[[opsi-4.2-releasenotes-packages]]
== List of packages

.Server packages:
* opsi4ucs 4.2...
* opsiconfd 4.2...
* opsipxeconfd 4.2...
* opsi-server 4.2...
* opsi-utils 4.2...
* opsi-linux-bootimage

NOTE: Die aktualisierten opsi-Pakete wurden auch für opsi 4.1 schon veröffentlicht. Die einzige Ausnahme davon sind `l-opsi-server` und `l-opsi-server-migrate`.

// Changelogs
include::changelogs.adoc[]
