////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      18.04.2023
:Revision:  4.2
:toclevels: 5
:icons: font
:xrefstyle: full
:doctype:   book

// Include common opsi terms
ifeval::["{mode}" == "antora"]
include::common:partial$opsi_terms.adoc[]
endif::[]

[[opsi-4.2-releasenotes]]
= Version 4.2

TIP: Eine Liste mit aktuell unterstützten Linux-Distributionen für den opsi-Servern sowie für den opsi-Client (Windows, Linux und macOS) finden Sie im Kapitel xref:supportmatrix:supportmatrix.adoc[opsi-Support-Matrix].

[[opsi-4.2-releasenotes-overview]]
== Neue Features (Schwerpunkte)

* Wechsel zu Python 3
* Alle Python-Applikationen werden als ausführbare Binärdateien verteilt.
* opsi-python-Interpreter für eigene Skripte
* opsi-Server:
** Komplette Neuimplementierung des `opsiconfd` mit Schwerpunkt auf Performance und Scalability
** `opsiconfd` ist nun auch im Docker-Container lauffähig.
** Neue Abhängigkeit zu Redis-Server >= 5, inklusive dem RedisTimeSeries-Modul
** Grafana zur Visualisierung von Performancedaten
** Neue Default-ACLs für den API-Zugriff

[[opsi-4.2-releasenotes-important]]
== Wichtige Hinweise

opsi 4.2 ist ein eigenständiges Release und hat seine eigenen Repositorys.
Fügen Sie die neuen Repositorys hinzu und entfernen Sie die Repositorys der Vorgängerversion.
Erst danach können Sie die Installation bzw. die Aktualisierung durchführen.

TIP: Hinweise zur Aktualisierung von opsi 4.1 auf 4.2 finden Sie im Abschnitt <<opsi-4.2-releasenotes-installation-migration>>.

[[opsi-releasenotes-4.2-changes-python]]
=== Python 3

opsi 4.2 basiert komplett auf Python 3. Alle Python-Applikationen in opsi (`opsiconfd`, `opsipxeconfd`, `opsiclientd`, `opsi-utils` usw.) werden nun als ausführbare Binärdateien mit PyInstaller ausgeliefert.
Das Paket `python-opsi` steht nicht länger als installierbares Paket zur Verfügung.

Deshalb ist es wichtig, folgende Punkte zu beachten:

[[opsi-4.2-releasenotes-important-reinstall-opsi-packages]]
==== opsi-Pakete mit serverseitigen Python-Skripten

Nutzen Sie nach der Aktualisierung des opsi-Servers auf opsi 4.2 das Werkzeug `opsi-package-manager`, um die opsi-Pakete neu zu installieren, die Python-Skripte für die Ausführung auf dem Server enthalten:

* opsi-Client-Agent: `opsi-deploy-client-agent`
* Windows: `create_driver_links.py`, `show_drivers.py`

Das `postinst`-Skript korrigiert diese Skripte automatisch und setzt den neuen Interpreter `opsi-python`.

Alternativ dazu können Sie die Python-Skripte auch von Hand korrigieren.
Dazu tragen Sie den Interpreter `opsi-python` als Shebang in die erste Zeile des Skriptes ein:

[source,shell]
----
#!/usr/bin/opsi-python
----

==== Eigene Python-Skripte, die `python-opsi` nutzen

Setzen Sie in Ihrer Umgebung Skripte ein, die den alten Interpreter `python-opsi` nutzen, führen Sie folgende Schritte aus:

* Konvertieren Sie die Skripte auf Python 3 (z.{nbsp}B. mit dem Python-Tool `2to3`).
* Tragen Sie den neuen Interpreter `opsi-python` als Shebang in die erste Zeile des Skriptes ein:

[source,shell]
----
#!/usr/bin/opsi-python
----

==== Backend-Erweiterungen

Falls Sie Konfigurationsdateien unter `/etc/opsi/backendManager/extend.d` verändert oder dort neue Dateien abgelegt haben, prüfen Sie diese, ob sie kompatibel mit Python 3 sind. Gegebenenfalls passen Sie diese an.

=== Gruppe `pcpatch` => `opsifileadmins`

opsi 4.2 führt einen neuen Namen für die Datei-Admin-Gruppe ein. Diese heißt nicht länger `pcpatch`, sondern `opsifileadmins`.
Wenn Sie opsi von Version 4.1 auf 4.2 aktualisieren, bleibt der bisher verwendete Name bestehen.
Sie können ihn in der Konfigurationsdatei `/etc/opsi/opsi.conf` im Abschnitt `groups`, Option `fileadmingroup` anpassen.

NOTE: Beachten Sie, dass Sie bei einem Gruppenwechsel den Benutzer `pcpatch` der Gruppe `opsifileadmins` hinzufügen müssen.

=== `opsiconfd`: Konfiguration und Logs

Es gibt einige Änderungen bei der Konfiguration und den Protokollen des `opsiconfd`:

* Alle Optionen zur Konfiguration sind in der Onlinehilfe dokumentiert, die Sie über `opsiconfd --help` aufrufen.
* Die in der Onlinehilfe gelisteten Parameter können Sie ohne `--` auch in der Konfigurationsdatei `opsiconfd.conf` verwenden.
* Der `opsiconfd` rotiert ab sofort seine Logs. Sie können das über die beiden Optionen `max-log-size` und `keep-rotated-logs` konfigurieren.
* Das Protokoll `package.log` ist jetzt Bestandteil von `opsiconfd.log`.
* Die Logs führen einen Kontext ein, den Sie zum Filtern nutzen können. Dazu verwenden Sie beispielsweise das Tool `grep` oder rufen `opsiconfd` mit der Option `--log-filter LOG_FILTER` auf:

[source,shell]
----
opsiconfd --log-filter instance=package_install
[...]
[6] [2020-09-07 14:41:17.864] [package_install] Running postinst script   (Depotserver.py:235)
[5] [2020-09-07 14:41:17.865] [package_install] Running package script 'postinst'   (Product.py:477)
[...]
----

[source,shell]
----
opsiconfd --log-filter client_addr=10.100.7.5
[...]
[6] [2020-09-07 14:25:16.966] [10.100.7.5     ] Filtering objects by acls   (AccessControl.py:475)
[...]
----

=== Verifizierung der Server-Identität

Ab opsi 4.2 können Sie die Vertrauenswürdigkeit des opsi-Servers über TLS-Standardmethoden sicherstellen.
Jeder opsi-Config-Server verwaltet dazu seine eigene Certificate Authority (CA), die opsi CA. Jeder opsi-Server (Config- oder Depot-Server) erhält vom opsi-Config-Server ein TLS-Zertifikat, das von der opsi CA signiert ist. Die Zertifikate werden automatisch erstellt, verteilt und bei Bedarf aktualisiert.
Jeder Client, welcher der opsi CA vertraut, vertraut auch diesen Server-Zertifikaten.

TIP: Sie steuern dieses Verhalten über die Optionen `verify_server_cert` und `verify_server_cert_by_ca` in der Datei `opsiclientd.conf` (siehe Abschnitt  xref:manual:security.adoc#opsi-manual-security-server2client[Security]).

[[opsi-4.2-releasenotes-installation]]
== opsi-Aktualisierung

WARNING: Wir empfehlen, alle Backends vor dem Upgrade zu sichern. Mehr Informationen dazu finden Sie im Kapitel xref:manual:server/opsi-backup.adoc[Das Werkzeug `opsi-backup`].

Alle opsi-Komponenten aus diesem Release hängen voneinander ab.
Daher sollten Sie immer alle Komponenten aktualisieren.

Wir empfehlen, zuerst den Server und danach die opsi-Pakete (Produkte) zu aktualisieren.

In einer Umgebung mit mehreren Depot-Servern aktualisieren Sie am besten erst den Config-Server und dann die Depots.

TIP: Führen Sie nach dem Upgrade das Kommando `opsi-setup --set-rights` aus. Es überprüft und korrigiert die Zugriffsberechtigungen. Die Ausführung des Befehls kann mehrere Minuten in Anspruch nehmen.

[[opsi-4.2-releasenotes-installation-systempackages]]
=== Betriebssystem-Pakete

Bitte stellen Sie sicher, dass Sie zum Zeitpunkt der Aktualisierung die jeweils aktuellsten Pakete von opsi 4.1 aus dem Stable-Bereich verwenden.

[[opsi-4.2-releasenotes-installation-opsipackages]]
=== opsi-Pakete

opsi-Pakete sind in der Regel kompatibel mit opsi 4.1 und opsi 4.2. Das gilt auch für die im 4.2-Repository angebotenen Pakete unter link:https://download.uib.de/[download.uib.de] angebotenen Pakete.

NOTE: Beachten Sie, dass die Pakete in unserem Downloadbereich nicht zwingend `4.2` als Versionsnummer haben müssen, um kompatibel zu sein.

[[opsi-4.2-releasenotes-installation-migration]]
=== opsi-4.1-Server migrieren

Um einen opsi-Server von Version 4.1 auf 4.2 zu aktualisieren, stellen Sie zunächst sicher, dass Sie die aktuellsten Pakete von opsi 4.1 aus dem Stable-Bereich verwenden. Auch andere Pakete, wie etwa der MySQL/MariaDB-Server, sollten auf dem neuesten Stand sein. Andernfalls kann es zu Problemen während des Upgrades kommen.

NOTE: Aktualisieren Sie vor dem Upgrade des opsi-Servers auf allen Clients die Pakete `opsi-winst`, `opsi-client-agent` (bzw. `opsi-linux-client-agent` und `opsi-mac-client-agent`).

Das Upgrade von opsi 4.1 auf Version 4.2 ist auf allen von opsi unterstützten Betriebssystemen möglich (siehe Kapitel xref:supportmatrix:supportmatrix.adoc[opsi-Support-Matrix]).

Falls opsi die opsi-Server verwaltet werden, können Sie die Migration mit dem Paket `l-opsi-server-migrate` durchführen.

WARNING: Ein Upgrade von opsi 4.0 direkt auf opsi 4.2 ist nicht möglich. In diesen Fällen müssen Sie zunächst auf opsi 4.1 aktualisieren und danach auf 4.2.

[[opsi-4.2-releasenotes-installation-migration-prerequired]]
==== Vorbereitungen

Ab Version 4.2 benötigt der opsi-Server Zugriff auf eine Redis- und eine Grafana-Instanz.
Sollen diese beiden Dienste auch auf dem opsi-Server laufen, empfehlen wir den Umstieg auf das Paket `opsi-server-full`, das alle notwendigen Anwendungen einspielt und konfiguriert. Im Folgenden bezeichnen wir das als Single-Server-Setup.

NOTE: Nutzen Sie zur Installation von Grafana die offiziellen Grafana-Repositorys. Wenn Sie eine Debian-basierte Distribution einsetzen, beachten Sie, dass die Repositorys im November 2022 von `packages.grafana.com` nach `apt.grafana.com` umgezogen sind. Die alten Adressen funktionieren noch, aber es kann bei der Installation oder Aktualisierung zu Warnungen auf dem System kommen.

Die Befehle führen Sie als Benutzer `root` aus.

===== *Debian/Ubuntu/UCS*

[source,shell]
----
sudo apt-get install -y apt-transport-https software-properties-common wget gpg
wget -q -O - https://apt.grafana.com/gpg.key | sudo apt-key add -
echo "deb https://apt.grafana.com/oss/deb stable main" > /etc/apt/sources.list.d/grafana.list
----

===== *SLES/openSUSE*

[source,shell]
----
zypper install wget
cd /etc/zypp/repos.d
cat <<EOF > grafana.repo
[grafana]
name=grafana
baseurl=https://rpm.grafana.com
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://rpm.grafana.com/gpg.key
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
EOF
----

===== *RHEL/AlmaLinux/Rocky Linux*

[source,shell]
----
yum install wget
cd /etc/yum.repos.d
cat <<EOF > grafana.repo
[grafana]
name=grafana
baseurl=https://rpm.grafana.com/
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://rpm.grafana.com/gpg.key
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
EOF
----

[[opsi-4.2-releasenotes-installation-migration-repositories]]
==== Neues Repository eintragen

Fügen Sie jetzt das Repository für opsi 4.2 hinzu. Dabei laden Sie auch (sofern benötigt) den GnuPG-Schlüssel des Repositorys herunter.

===== *Debian 11 _Bullseye_*

[source,shell]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Debian_11/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Debian_11/Release.key | sudo apt-key add -
----

===== *Debian 10 _Buster_*

[source,shell]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Debian_10/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Debian_10/Release.key | sudo apt-key add -
----

===== *Ubuntu 22.04 LTS _Jammy Jellyfish_*

[source,shell]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_22.04/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_22.04/Release.key | sudo apt-key add -
----

===== *Ubuntu 20.04 LTS _Focal Fossa_*

[source,shell]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_20.04/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_20.04/Release.key | sudo apt-key add -
----

===== *Ubuntu 18.04 LTS _Bionic Beaver_*

[source,shell]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_18.04/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_18.04/Release.key | sudo apt-key add -
----

===== *UCS 4.4*

[source,shell]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Univention_4.4/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Univention_4.4/Release.key | sudo apt-key add -
----

===== *UCS 5.0*

[source,shell]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Univention_5.0/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Univention_5.0/Release.key | sudo apt-key add -
----

===== *openSUSE Leap 15.4:*

[source,shell]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/openSUSE_Leap_15.4/home:uibmz:opsi:4.2:{release}.repo
zypper refresh
----

===== *SLES 15 SP 1:*

[source,shell]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/SLE_15_SP1/home:uibmz:opsi:4.2:{release}.repo
zypper refresh
----

===== *SLES 15 SP 2:*

[source,shell]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/SLE_15_SP2/home:uibmz:opsi:4.2:{release}.repo
zypper refresh
----

===== *SLES 15 SP 3:*

[source,shell]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/SLE_15_SP3/home:uibmz:opsi:4.2:{release}.repo
zypper refresh
----

===== *SLES 15 SP 4:*

[source,shell]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/SLE_15_SP4/home:uibmz:opsi:4.2:{release}.repo
zypper refresh
----

===== *AlmaLinux 8:*

[source,shell]
[subs="attributes"]
----
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/AlmaLinux_8/home:uibmz:opsi:4.2:{release}.repo
yum makecache
----

===== *AlmaLinux 9:*

[source,shell]
[subs="attributes"]
----
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/AlmaLinux_9/home:uibmz:opsi:4.2:{release}.repo
yum makecache
----

===== *Rocky Linux 8:*

[source,shell]
[subs="attributes"]
----
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/RockyLinux_8/home:uibmz:opsi:4.2:{release}.repo
yum makecache
----

===== *Rocky Linux 9:*

[source,shell]
[subs="attributes"]
----
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/RockyLinux_9/home:uibmz:opsi:4.2:{release}.repo
yum makecache
----

===== *RHEL 8:*

[source,shell]
[subs="attributes"]
----
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/RHEL_8/home:uibmz:opsi:4.2:{release}.repo
yum makecache
----

===== *RHEL 9:*

[source,shell]
[subs="attributes"]
----
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/RHEL_9/home:uibmz:opsi:4.2:{release}.repo
yum makecache
----

[[opsi-4.2-releasenotes-installation-migration-migrate]]
==== Betriebssystem aktualisieren

Nachdem Sie das Repository hinzugefügt haben, können Sie nun die Aktualisierung starten. Auf RPM-basierten Distributionen ersetzt der Paketmanager vorhandene Konfigurationsdateien durch neue. Beachten Sie hierzu die Hinweise zu den entsprechenden Distributionen.

IMPORTANT: Aus Sicherheitsgründen haben wir für opsi 4.2 die Standard-ACLs (`/etc/opsi/backendManager/acl.conf`) verändert. Wir empfehlen daher, die neue Version der Konfigurationsdatei zu verwenden.

Debian und Ubuntu aktualisieren Sie mit den folgenden Befehlen auf opsi 4.2:

*Single-Server-Setup:*
[source,shell]
----
apt update
apt install opsi-server-full
----

*Manuelles Setup:*
[source,shell]
----
apt update
apt install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
apt dist-upgrade
----

Univention Corporate Server (UCS) aktualisieren Sie mit den folgenden Befehlen auf opsi 4.2:

*Single-Server-Setup:*
[source,shell]
----
univention-install opsi-server-full
----

*Manuelles Setup:*
[source,shell]
----
univention-install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
univention-install opsi-server
----

openSUSE und SUSE Linux Enterprise Server (SLES) aktualisieren Sie mit den folgenden Befehlen auf opsi 4.2:

*Single-Server-Setup:*
[source,shell]
----
zypper refresh
zypper install opsi-server-full
----

*Manuelles Setup:*
[source,shell]
----
zypper refresh
zypper install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
zypper dup --from home_uibmz_opsi_4.2_{release}
----

RedHat Enterprise Linux (RHEL), AlmaLinux und Rocky Linux aktualisieren Sie mit den folgenden Befehlen auf opsi 4.2:

*Single-Server-Setup:*
[source,shell]
----
yum makecache
yum install opsi-server-full
yum upgrade
----

*Manuelles Setup:*
[source,shell]
----
yum makecache
yum install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
yum upgrade
----

[[opsi-4.2-releasenotes-installation-migration-opsi-packages]]
==== opsi-Pakete aktualisieren

Der letzte Schritt ist die Aktualisierung auf die neuesten opsi-Pakete.

[[opsi-4.2-releasenotes-installation-migration-opsi-packages-standard]]
===== Standardkonfiguration verwenden

Wenn Sie die Standardkonfiguration unter `/etc/opsi/package-updater.repos.d/` nicht verändert haben, dann Sie die opsi-Pakete so aktualisieren:

[source, shell]
----
opsi-package-updater -v update
----

NOTE: opsi-Pakete, die Python-Skripte auf dem Server ausführen, sollten Sie neu installieren. In der Regel sind das `opsi-client-agent`, `opsi-linux-client-agent` und alle Pakete, die Windows-Betriebssysteme installieren (`win*`). Mehr dazu lesen Sie im Abschnitt <<opsi-4.2-releasenotes-important-reinstall-opsi-packages>>.

[[opsi-4.2-releasenotes-eol]]
== End of Support

Die nächsten Abschnitte listen auf, welche Pakete, Betriebssysteme usw. opsi 4.2 nicht länger unterstützt.

=== Paket `opsi4ucs`

Bei der Veröffentlichung von opsi 4.2 haben wir den UCS-Support den anderen Distributionen angepasst. Die Funktion von `opsi4ucs` übernimmt ab 4.2 das Paket für den opsi-Server und dessen Varianten. Das Paket `opsi4ucs` ist in opsi 4.2 weiterhin als Übergangspaket enthalten, um die Migration von opsi 4.1 zu vereinfachen. Während des Upgrades von opsi 4.1 auf 4.2 ersetzt das Paketverwaltungstool `opsi4ucs` automatisch durch `opsi-server`.

[[opsi-4.2-releasenotes-eol_opsi41]]
=== End of Life: opsi 4.1 Q4/2021

Bisher haben wir den jeweiligen opsi-Vorgänger (Oldstable) mindestens ein Jahr lang parallel zur aktuellen Version unterstützt. In diesem Fall haben wir uns aber entschieden, die Zeit auf die Hälfte zu verkürzen und opsi 4.1 für das 4. Quartal 2021 (30.11.2021) abzukündigen. Der Hauptgrund für die verkürzte EOL-Zeit: Nicht alle aktuellen Betriebssysteme unterstützen opsi 4.1, darunter z.{nbsp}B. Ubuntu 20.04.
opsi 4.1 basiert komplett auf Python 2, und diese Version hat bereit im April 2020 den EOL erreicht und erhält keine Updates mehr.

TIP: Über den professionellen  https://www.uib.de/de/support-schulung/support[opsi-Support] unterstützen wir Sie gerne beim Wechsel auf die neue opsi-Version. Auch nach dem EOL von opsi 4.1 sind wir für Sie da und helfen bei Migrationen -- wir empfehlen aber dringend, die Zeit bis zum Ende von Q4/2021 zu nutzen und auf opsi 4.2 zu aktualisieren.

[[opsi-4.2-releasenotes-eol_server]]
=== Linux-Distributionen

Ab Version 4.2 bieten wir für die folgenden Systeme keine Pakete für den opsi-Server mehr an:

* CentOS 7.x
* Debian 8.x
* RedHat Enterprise Linux 7.x
* Suse Linux Enterprise Server 12

[[opsi-releasenotes-4.2-changes-changed-defaults]]
== Neue Standardeinstellungen

Mit opsi 4.2 haben wir einige Standard-Einstellungen geändert, um Erfahrungen aus dem opsi-Betrieb widerzuspiegeln.

Das ist besonders dann wichtig, wenn Sie in einer bestehenden Umgebung neue opsi-Server installieren. Diese verhalten sich unter Umständen anders.

NOTE: Bitte beachten Sie: Aus Sicherheitsgründen haben wir für opsi 4.2 die Standard-ACLs (`/etc/opsi/backendManager/acl.conf`) verändert.

[[opsi-releasenotes-4.2-changes-mysql-config]]
== MySQL-Backend: `connection lifetime`

Um die Fehlermeldung `mysql server has gone away` zu vermeiden, haben wir die Standardkonfiguration des MySQL-Backends geändert. Die Option `connectionPoolRecycling` hat nun als Standardwert `_28800`.

Die Option `connectionPoolRecycling` steuert auf MySQL-/MariaDB-Servern die Wiederverwendung von Verbindungen im Verbindungspool. MySQL gibt dann Verbindungen im Pool nach einer bestimmten Zeit aus, selbst wenn sie noch nicht geschlossen wurden. Dies kann dazu beitragen, dass der Pool von Verbindungen effizienter genutzt wird.

[[opsi-4.2-releasenotes-api-changes]]
== API-Änderungen

Auch die API hat in opsi 4.2 einige Änderungen erfahren. Betroffen sind unter anderem die API des Webservices, `opsi-admin` und mittels `opsiServiceCall` gemachte Aufrufe in `opsi-script`.

[[opsi-4.2-releasenotes-deprecated-api-methods]]
=== Veraltete API-Methoden

Die folgenden Methoden sind veraltet; wir werden sie mit dem nächsten Major oder Minor Release entfernen:

* `getClients_listOfHashes`: Diese Methode wurde bei opsi 4.1 als "deprecated" markiert. Ohne Parameter aufgerufen liefert die Methode die Ausgabe von `getClients` zurück. In allen anderen Fällen wird ein Fehler zurückgegeben.
* `getClientIds_list`: Diese Methode wurde bei opsi 4.1 als "deprecated" markiert. Ohne Parameter aufgerufen liefert diese Methode die Ausgabe von `getClientIDs` zurück. Beim Aufruf mit dem Parameter `depotIds` wird die Ausgabe von `getClientsOnDepot` zurückgegeben. Wenn `productId` und optional `installationStatus` übergeben werden, liefert die Methode die Ausgabe von `getClientsWithProducts` zurück.

[[opsi-4.2-releasenotes-removed-api-methods]]
=== Gelöschte API-Methoden

Die folgende API-Methode haben wir entfernt:

* `backend_searchIdents`

[[opsi-4.2-releasenotes-knownbugs]]
== Bekannte Probleme und Bugs

* `opsi-admin`: Der interaktive Modus funktioniert nicht mit Sonderzeichen/Umlauten wie ö, ä, ü usw.
* `opsiwebservice` unterstützt keine Deflate-Kompression.

[[opsi-4.2-releasenotes-packages]]
== Liste der Pakete

* `opsi4ucs` 4.2...
* `opsiconfd` 4.2...
* `opsipxeconfd` 4.2...
* `opsi-server` 4.2...
* `opsi-utils` 4.2...
* `opsi-linux-bootimage`

NOTE: Die aktualisierten opsi-Pakete haben wir auch für opsi 4.1 veröffentlicht. Ausgenommen sind `l-opsi-server` und `l-opsi-server-migrate`.

// Changelogs
include::changelogs.adoc[]
