////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype: book
:linclientmanual: opsi-linux-client-manual

// Include common opsi terms
include::common:partial$opsi_terms.adoc[]


include::common:partial$firststeps-adding-clients.adoc[leveloffset=-1]


[[firststeps-software-deployment-client-integration]]
== Integration of existing Linux clients into opsi.

To include existing Linux clients in opsi, the opsi-client-agent must be installed on them.
This can be performed in several ways.
After you have installed the {opsi-client-agent}, as described below, the client will also appear in the client list of the {opsi-configed}, in the case you had not already added it there previously.


Basically, is possible to <<firststeps-software-deployment-client-integration-service-setup,run on the client>> or <<firststeps-software-deployment-client-integration-opsi-deploy,from the server>> to trigger the installation of the agent.

Running the installation directly on the client is appropriate for individual machines.
For a mass deployment of the agent, the <<firststeps-software-deployment-client-integration-opsi-deploy,opsi-deploy-client-agent>> is generally more suitable.
If the necessary unlocks are available on the Linux clients.

If there is already another way to deploy software, it's also possible to deploy the opsi-client-agent and run the `silent_setup.sh` script included in the package.

Once the agent is installed, existing opsi products can be <<firststeps-software-deployment-product-tests,installed>> on these clients.

[[firststeps-software-deployment-client-integration-oca-installer]]
=== Using opsi-client-agent-installer on Linux

include::common:partial$firststeps-oca-installer.adoc[]



[[firststeps-software-deployment-client-integration-service-setup]]
=== Using service_setup.sh on Linux (outdated)

The method described over here is only for backward compatibility to
opsi 4.1 and the corresponding opsi-client-agent versions 4.1. Please use as possible
<<firststeps-software-deployment-client-integration-oca-installer,the opsi-client-agent Installer>>.


* Log in to the client.
* Start the terminal program
* For the following commands you need to replace the following placeholders:
** `<username>` with your login name.
** `<mnt>` with a directory name that does not exist yet e.g. 'mnt'.
** `<serviceuser>` with a username that is known on the opsi-server.
** `<servicepass>` with the password of the <serviceuser>. You can also omit `pass=<servicepass>`, then you will be prompt to input the password
** `<opsi-server>` the name or IP number of the opsi-server.


[source,shell]
----
sudo su
cd /mnt
mount.cifs //<opsi-server>/opsi_depot /mnt -o user=<serviceuser>
cd /mnt/opsi-linux-client-agent
./service_setup.sh
cd
umount /mnt
----

without password query

[source,shell]
----
sudo su
cd /mnt
mount.cifs //<opsi-server>/opsi_depot /mnt -o user=<serviceuser>, pass=<servicepass>
cd /mnt/opsi-linux-client-agent
./service_setup.sh
cd
umount /mnt
----

Example:

[source,shell]
----
sudo su
cd /mnt
mount.cifs //sepia/opsi_depot /mnt -o user=adminuser
cd /mnt/opsi-linux-client-agent
./service_setup.sh
cd
umount /mnt
----


. Start from the mounted share the script `opsi-linux-client-agent\service_setup.sh` +
Confirm with 2 x Enter
. The script copies the necessary files into a temporary local directory and then starts opsi-script for the actual installation.
. The script contacts the server via opsi webservice to create the client on the server side and to find out the pckey. This is done first with the user/password combination entered in `config.ini`. If this fails, a login window appears with service URL ({opsi-configserver}), user name and password. Here a user is needed which is a member of the group 'opsiadmin'. It is possible to also operate with a user which is only allowed to execute the method `host_createOpsiClient`.

WARNING: The client needs a reboot after the installation.


[[firststeps-software-deployment-client-integration-opsi-deploy]]
=== Using opsi-deploy-client-agent for Linux.

The `opsi-deploy-client-agent` script deploys the opsi-client-agent directly from the opsi-Server to the clients.
It's easy to integrate a large number of clients from the server into an opsi environment.
As a prerequisite for the clients is needed:

* an activated ssh access

The `opsi-deploy-client-agent` script can be found at `/var/lib/opsi/depot/opsi-client-agent` +
Run the script with 'root' privileges or as a user being part of the group "opsifileadmins"
If the script is not executable, you can fix this problem with the following command: +
`opsi-set-rights /var/lib/opsi/depot/opsi-client-agent/opsi-deploy-client-agent`

The script creates the client on the server side, copies the installation files and configuration information, such as the pckey, to the client and starts the installation there. +
The installation runs in the background without any interaction from user and transparently.

The command `opsi-deploy-client-agent` has several call parameters. +
All following examples assume that you have switched to the root directory of the opsi-client-agent product: +

[source,shell]
----
cd /var/lib/opsi/depot/opsi-linux-client-agent
----

Typical calls are:

* For a single client:

[source,shell]
----
./opsi-deploy-client-agent -v --user=root mylinuxclient.local
----

Results in the following output:

[source,ini]
----
Password is required for deployment.
Password:
[5] [2021-02-04 16:43:43.121] [               ] Starting deployment to host mylinuxclient.locall   (posix.py:84)
[5] [2021-02-04 16:43:43.121] [               ] Querying for ip address of host mylinuxclient.locall   (common.py:158)
[5] [2021-02-04 16:43:43.122] [               ] Got ip address 192.168.10.70 from syscall   (common.py:167)
[5] [2021-02-04 16:43:43.123] [               ] Pinging host 192.168.10.70 ...   (common.py:183)
[5] [2021-02-04 16:43:44.146] [               ] Host 192.168.10.70 is up   (common.py:194)
[5] [2021-02-04 16:43:44.153] [               ] Patching config.ini   (posix.py:91)
[5] [2021-02-04 16:43:44.157] [               ] Copying installation scripts...   (posix.py:107)
[5] [2021-02-04 16:43:48.316] [               ] Running installation script...   (posix.py:147)
[5] [2021-02-04 16:43:53.382] [               ] opsi-client-agent successfully installed on mylinuxclient.locall   (posix.py:176)
[5] [2021-02-04 16:43:53.395] [               ] Restarting opsiclientd service on computer: uib-mmini1   (posix.py:331)
[5] [2021-02-04 16:43:55.620] [               ] 1/1 deployments successfully   (__init__.py:210)
----

* For a list of clients:

[source,shell]
----
./opsi-deploy-client-agent -v --user=root --hosts-from-file HOSTFILE.TXT  --skip-existing-clients
----

Here HOSTFILE.TXT is a file with one client name (FQDN) per line. As long as the clients are not known to the opsi-server, it tries to install the `opsi-mac-client-agent` on this machine

* Display all command line parameters:

[source,shell]
----
./opsi-deploy-client-agent --help
----