////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////
:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:toc: left
:toclevels: 3
:numbered:
:icons: font
:xrefstyle: full
:doctype:   book
:date:      07.03.2022
:linclientmanual: opsi-linux-client-manual
:lang: en

include::common:partial$opsi_terms.adoc[]


// = opsi Linux client manual

// Include common opsi copyright
// include::../common/opsi_manual_copyright.asciidoc[]


[[opsi-linclient-introduction]]
= Introduction Linux cients in opsi

This manual describes the operation of Linux clients in opsi.

It's assumed that the installation and startup of an {opsi-server} has already been performed.

Essential topics of this manual:

. Automatic Linux OS installation
. Enrollment and integration of Linux computers in opsi
(Installation of the opsi-client-agent)
. Provision of the standard opsi software for Linux on the opsi server
. Installation of standard software on the Linux clients
. standard opsi software for Linux under opsi
. Packaging your own software
. Creation of opsi packages
. Notes on Linux clients
.. Special commands for Linux



[[opsi-linclient-convention]]
== Conventions of this document

Commands are highlighted separately:

[source,shell]
----
this is a command
----

As part of the installation and configuration process, you can copy and execute the commands from these fields in order by _copy & paste_ from this document.

Commands or file names will be highlighted as:  `opsi-set-rights` oder `/Applications/opsi-script`.

This is an {opsi-script} code:

[source,winst]
----
Message "Installing "+ $ProductId$ +" ..."
----

Chapters containing the name of a particular platform are specific to that platform. The supported platforms are:

* *Windows*

* *Linux*

* *macOS*
