////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype: book
:linclientmanual: opsi-linux-client-manual

// Include common opsi terms
include::common:partial$opsi_terms.adoc[]


[[opsi-linclient-installation-config-get-essential-products]]
= Installing the minimal Linux opsi products

To distribute software with opsi, ready-made products are available for installation.
These include the agent ('opsi-client-agent'), which must be installed on the clients for management.

There is an automated and a manual way to do this.
The automated option is recommended.


[[opsi-linclient-installation-config-get-essential-products-automatic]]
== Automatic installation of the minimal Linux opsi products

For the automatic installation of the opsi products there is the tool `opsi-package-updater`, which configured as in '/etc/opsi/opsi-package-updater.conf' or `/etc/opsi/package-updater.repos.d/`, automatically fetches the current packages from the opsi repository and installs them on the server.

The configuration of the opsi repository for Windows clients can be found in the directory `/etc/opsi/package-updater.repos.d/` in the file `uib-linux.repo`.

Activate the desired repository by setting the entry `active = true` in the desired *.repo file.

.`/etc/opsi/package-updater.repos.d/uib-linux.repo`

[source,configfile]
----
; This repository provides products for deploying and managing Linux
; clients with opsi.

[repository_uib_linux]
description = opsi Linux Support
active = true
baseUrl = http://download.uib.de
dirs = opsi4.2/stable/packages/linux/localboot/, opsi4.2/stable/packages/linux/netboot/
autoInstall = false
autoUpdate = true
autoSetup = false
; Set Proxy handler like: http://<address>:8080
proxy =

----

Install the packages on the server by running this command as root:

[source,prompt]
----
opsi-package-updater -v --repo uib_linux install
----


After a successful installation you have to reload all data in `opsi-configed` so that the new products are visible there.

If the connection to the Internet has to be routed via a proxy, this must be entered in the `.repo` configuration files in `/etc/opsi/package-updater.repos.d/` as the value for `proxy`.
From version 4.1.1.33 of opsi-utils a global proxy can be configured in `/etc/opsi/opsi-package-updater.conf`.


[source,configfile]
----
[repository_uib_linux]
…
proxy =
----

If the installed packages are to be updated later, this can be linuxed with the following command:
[source,prompt]
----
opsi-package-updater -v update
----


Further information on `opsi-package-updater` can be found in the manual.

////
NOTE: Please note that OS installation products such as {opsi-client-os} are not immediately ready for use after installation. The installation has to be supplemented by the installation files of the corresponding installation medium (see: <<firststeps-osinstall-fill-base-packages>>).

////


[[opsi-linclient-installation-config-get-essential-products-manually]]
== Manual installation of the Linux opsi products

There is also the option of downloading and installing the packages manually.

Get the current opsi packages in the `.opsi`-package format.
You can find the packages at `https://download.uib.de/opsi4.2/stable/packages/linux/localboot` +
and at `https://download.uib.de/opsi4.2/stable/packages/linux/netboot`.

We recommend saving the .opsi files under `/var/lib/opsi/repository`.
To ensure that the process `opsiconfd` can access the files, you should run `opsi-set-rights /var/lib/opsi/repository`.

After downloading you have to install the packages on the server with the command `opsi-package-manager -i <packagename>.opsi`.