////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      15.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]


[[server-components-authorization]]
= Berechtigungen

In diesem Kapitel geht es um die Benutzer- und Gruppenverwaltung auf dem opsi-Server. Es erklärt auch, wie Sie LDAP/Active Directory zur Authentifierung nutzen und eine Zwei-Faktor-Authentifizierung für den Server einrichten.

[[server-components-authorization-users-and-groups]]
== Benutzer und Gruppen

opsi verwendet die folgenden Benutzer- und Gruppenaccounts:

* `opsiconfd`: ein Konto für den gleichnamigen Systemdienst `opsiconfd` (siehe Kapitel xref:server:components/opsiconfd.adoc[Der Dienst *opsiconfd*]); Account muss Mitglied der Gruppen `opsiadmin` und `opsifileadmins` sein
* `pcpatch`: ein Account, den die opsi-Clients für den Zugriff via CIFS (Samba) auf das opsi-Depot verwenden; muss Mitglied in der Gruppe `opsifileadmins` sein (siehe Abschnitt <<server-components-authorization-pcpatch-password>>)

NOTE: Zum Verwalten lokaler Benutzer und Gruppena auf dem opsi-Server nutzen Sie die Linux-Standardwerkzeuge `useradd`, `usermod`, `groupadd`, `groupmod` usw. (siehe Abschnitt <<server-components-authorization-create-local-users>>). Alternativ binden Sie den opsi-Configserver an eine bestehende Windows-Domäne (siehe Abschnitt <<server-components-authorization-domain-join>>) oder an LDAP/Active Directory (siehe Abschnitt <<server-components-authorization-ldap-authentication>>) an.

Zum Steuern von Berechtigungen verwendet opsi die folgenden Gruppen:

* `opsiadmin`: Mitglieder dieser Gruppe können administrativ auf den opsi-Service zugreifen, das heißt, sie erhalten vollen Zugriff über die Management-Oberfläche `opsi-configed`, das opsi-WebGUI, die `opsiconfd`-Admin-Seite usw.
* `opsifileadmins`: Mitglieder dieser Gruppe können administrativ auf opsi-Dateien (Depot, Repository, Workbench) zugreifen.
* `opsireadonly`: Mitglieder dieser Gruppe können nur lesend auf den opsi-Service zugreifen.

Den Namen dieser Gruppen können Sie in der Konfigurationsdatei `/etc/opsi/opsi.conf` im Abschnitt `groups` ändern:

// cSpell:disable
[source,configfile]
----
[groups]
fileadmingroup = "opsifileadmins"
admingroup = "opsiadmin"
readonly = "opsireadonlys"
----
// cSpell:enable

[[server-components-authorization-pcpatch-password]]
=== Passwort für Benutzer *pcpatch*

Da die opsi-Clients diesen Account für die Authentifizierung verwenden, muss der opsi-Configserver das Passwort kennen. Zu diesem Zweck ist das Kennwort verschlüsselt in der Datei `/etc/opsi/passwd` abgelegt. Bei der Installation eines opsi-Configservers wird vollautomatsich ein Zufallskennwort gesetzt, das Sie in der Regel nicht ändern müssen.

Das Passwort können Sie mit dem Kommandozeilentool `opsi-admin` ändern (siehe Abschnitt xref:server:components/commandline.adoc#server-components-opsi-admin[*opsi-admin*]):

[source,console]
----
opsi-admin -d task setPcpatchPassword
----

Nach dem Drücken der Taste [Eingabe] erscheint ein Passwort-Prompt, und Sie können das Kennwort eintippen.

NOTE: Das Passwort wird zusätzlich für den lokalen Unix- und Samba-Account geändert. Handelt es sich um einen Domänen-Account, müssen Sie das neue Passwort dort ebenfalls von Hand neu setzen.

[[server-components-authorization-create-local-users]]
=== Admin-Account anlegen

Um lokale Benutzer und Gruppen auf dem opsi-Configserver anzulegen, nutzen Sie die Linux-Standardwerkzeuge. Das folgende Beispiel richtet einen neuen Benutzer namens `adminuser` ein und fügt diesen dann den beiden Gruppen `opsiadmin` und `opsifileadmins` hinzu. Damit erhält der Benutzer dann vollen administrativen Zugriff auf den opsi-Server.

NOTE: Bei der vorkonfigurierten virtuellen Maschine und in unserem Docker-Container gibt es den Account `adminuser` bereits. Sie können die hier gezeigten Schritte aber zum Hinzufügen weiterer Accounts verwenden.

Zuerst legen Sie das neue Konto über den Befehl `useradd` an:

[source,console]
----
sudo useradd -m -s /bin/bash adminuser
----

Anschließend setzen Sie für den neuen Account ein Unix-Passwort (System):

[source,console]
----
sudo passwd adminuser
----

Soll der Benutzer auch Dateizugriff per CIFS (Samba) erhalten, setzen Sie dafür ebenfalls ein Passwort:

[source,console]
----
sudo smbpasswd -a adminuser
----

WARNING: Verwenden Sie in den Passwörtern kein *§*-Zeichen!

Als Nächstes fügen Sie den neuen Benutzer den Gruppen `opsiadmin` und `opsifileadmins` hinzu:

[source,console]
----
usermod -aG opsiadmin adminuser opsifileadmins
----

Geben Sie den Befehl `id` ein, um zu überprüfen, dass der Account `adminuser` existiert und den beiden Gruppen angehört:

[source,console]
----
id adminuser
# uid=1000(adminuser) gid=1000(opsiadmin) groups=1000(opsiadmin),999(opsifileadmins)
----

[[server-components-authorization-domain-join]]
== opsi-Server in Windows-Domäne einbinden

Statt mit lokalen Unix- und Samba-Accounts zu arbeiten, können Sie einen opsi-Server auch in eine Windows- bzw. Samba-4-Domäne einbinden. Dazu legen Sie in der Domäne die beiden Gruppen `opsiadmin` und `opsifileadmins` an.

TIP: Wenn Sie die Gruppen anders nennen oder bestehende Gruppen verwenden möchten, dann ändern Sie die Namen auch in der Konfigurationsdatei `/etc/opsi/opsi.conf` entsprechend.

Außerdem legen Sie den Benutzer `pcpatch` als Mitglied der Gruppe `opsifileadmins` sowie den Benutzer `opsiconfd` als Mitglied der Gruppen `opsiadmin` und `opsifileadmins` an.

Entfernen Sie dann die beiden Gruppen `opsiadmin` und `opsifileadmins` aus den lokalen Unix-Gruppen (Befehl `groupdel`) und die lokalen Unix-Accounts `opsiconfd` und `pcpatch` (Befehl `userdel`).

Nehmen Sie dann den opsi-Server in die Windows-Domäne auf. Schlagen Sie in der Dokumentation der eingesetzten Linux-Distribution nach, welche Schritte dazu jeweils erforderlich sind.

Nach dem Domain Join führen Sie die folgenden zwei Befehle aus:

[source,console]
----
opsiconfd setup
opsi-set-rights
----

NOTE: Weitere Informationen zu den beiden Kommandos lesen Sie in den beiden Abschnitten xref:server:components/opsiconfd.adoc#server-components-opsiconfd-setup[*opsiconfd setup*] und xref:server:components/commandline.adoc#server-components-opsi-set-rights[*opsi-set-rights*].

Setzen Sie abschließend das Passwort für den Benutzer `pcpatch` neu (siehe Abschnitt <<server-components-authorization-pcpatch-password>>).

[[server-components-authorization-ldap-authentication]]
== Authentifizierung gegen LDAP/Active Directory

Für die Authentifizierung am opsi-Service wird standardmäßig*PAM*verwendet.
Das funktioniert mit lokalen Benutzern und Gruppen, aber auch wenn der opsi-Server in eine Domäne eingebunden ist.

Statt PAM für die Authentifizierung zu nutzen, ist es auch möglich einen LDAP-Server bzw. ein Active Directory zu verwenden.
Hierfür ist die xref:opsi-modules:modules.adoc[opsi-Erweiterung] *opsi directory connector* notwendig.

IMPORTANT: Die Samba-Authentifizierung ist hiervon unabhängig.
Das Verfahren eignet sich daher hauptsächlich für opsi-Umgebungen,
bei denen die opsi-Administratoren nicht per Samba, sondern per WebDAV, auf die opsi-Shares zugreifen.
Beim Betrieb eines opsi-Servers unter Docker ist das immer der Fall.

Die Konfiguration findet über die Datei `/etc/opsi/opsi.conf` statt.
In der Sektion *ldap_auth* muss hierfür die Option *ldap_url* gesetzt werden.
Die ldap_url besitzt dabei den folgenden Aufbau:
`ldap[s]://<Adresse-des-LDAP-Servers>[:port]/<base-dn>`

Zusätzlich kann die Option*username*verwendet werden.
Damit kann definiert welcher Benutzername bei der Authentifizierung am LDAP/AD übergeben werden soll. Hierbei können die Platzhalter *\{username\}* und *\{base\}* verwendet werden. Im Normalfall ist jedoch die Angabe der *ldap_url* ausreichend.

Beispiel zur Anbindung an ein Active Directory bzw. Samba 4:

[source,toml]
----
[ldap_auth]
ldap_url = "ldaps://ad.company.de/dc=ad,dc=company,dc=de"
----

Beispiel zur Anbindung an einen OpenLDAP:

[source,toml]
----
[ldap_auth]
ldap_url = "ldaps://ldap.company.org:636/dc=company,dc=org"
username = "uid={username},dc=Users,{base}"
----

Damit die Änderungen übernommen werden, muss der *opsiconfd* neu gestartet werden.

NOTE: Bitte beachten Sie, dass die in der Variable *admingroup* definierte Gruppe auch im AD/LDAP verfügbar ist.


[[server-components-authorization-multi-factor]]
== Multi-Faktor-Authentifizierung
Der opsi-Server unterstützt eine Zwei-Faktor-Authentifizierung mit dem Standard-Verfahren *Time-based One-time Password Algorithmus* (TOTP).
Hierbei wird bei der Anmeldung am opsi-Server zusätzlich eine Einmal-Passwort verwendet, das aus sechs Ziffern besteht.
Zur Freischaltung der Funktionalität ist die xref:opsi-modules:modules.adoc[opsi-Erweiterung] *WAN/VPN* notwendig.


=== Generelle Einrichtung
// cSpell:ignore multi-factor-auth, inactive, totp_optional, totp_mandatory
Zur Konfiguration der Zwei-Faktor-Authentifizierung existiert das xref:server:configuration/opsiconfd.adoc#server-configuration-opsiconfd-config
[opsiconfd Konfigurations-Attribut] `multi-factor-auth`.
Folgende Werte sind möglich:

inactive:: Die Multi-Faktor-Authentifizierung ist inaktiv (Standard). Das gilt auch für Benutzer mit konfiguriertem TOTP.
totp_optional:: Die Zwei-Faktor-Authentifizierung über TOTP ist optional. Benutzer mit aktiviertem TOTP, müssen dieses verwenden.
totp_mandatory:: TOTP ist zwingend erforderlich. Benutzer ohne aktiviertes TOTP können sich nicht mehr anmelden.


=== Benutzer-spezifische Einrichtung

Die Einrichtung erfolgt über die xref:server:components/opsiconfd.adoc#server-components-opsiconfd-admin-page[opsiconfd Admin-Seite] im Tab *Users*.
Über eine Klick auf den Button *Generate new secret and activate TOTP* wird Server-seitig ein Secret generiert und die Zwei-Faktor-Authentifizierung für den jeweiligen Benutzer aktiviert. Der angezeigte QR-Code kann in einer entsprechenden App, wie z.B. *2FA Authenticator (2FAS)* für Android und iOS, gescannt werden. Die App generiert daraufhin alle 30 Sekunden ein neues Einmal-Passwort. Das Passwort muss bei der Authentifizierung an das normale Kennwort angehängt werden.

IMPORTANT: Ein erneuter Klick auf den Button *Generate new secret and activate TOTP* erzeugt ein neues Secret.
Das bisherige Secret (QR-Code) des Benutzers verliert damit seine Gültigkeit.

Über einen Klick auf den Button *Deactivate MFA* wird die Zwei-Faktor-Authentifizierung für den jeweiligen Benutzer deaktiviert.
