////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      08.05.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]


[[server-components-backup]]
= Backup des opsi-Servers

Erstellen Sie regelmäßige Backups des opsi-Servers. Grundsätzlich können Sie dabei die gleiche Strategie verfolgen wie beim Sichern anderer Linux-Systeme. Dieses Kapitel erklärt die opsi-spezifischen Aspekte.

Beim opsi-Backup geht es im Wesentlichen um diese Komponenten:

* Sicherung der Dateien eines Depots
* Sicherung der Redis-Datenbank
* Sicherung der opsi-Datenbank

[[server-components-backup-depot-files]]
== Sicherung der Dateien

Auf opsi-Depotservern sollten Sie die folgenden Verzeichnisse sichern:

* `/etc/opsi`
* `/var/lib/opsi`
* `/tftpboot/opsi` bzw. `/var/lib/tftpboot/opsi`

NOTE: `opsiconfd backup` (siehe Abschnitt <<server-components-opsiconfd-backup>>) sichert lediglich die Konfigurationsdateien aus `/etc/opsi` -- um die anderen Verzeichnisse müssen Sie sich selbst kümmern.

Hier noch einige Anmerkungen zu den Daten im Verzeichnis `/var/lib/opsi`:

* `/var/lib/opsi/tmp`: Enthält temporäre Dateien, die Sie nicht sichern müssen.
* `/var/lib/opsi/depot`: Der Inhalt dieses Ordners lässt sich in vielen Fällen nicht komplett aus den opsi-Paketen wiederherstellen, denn hier liegen zusätzliche Dateien wie Custom-Files, Windows-Installationsdateien, WinPE und Treiber, die nicht in den opsi-Paketen enthalten sind.
* `/var/lib/opsi/repository`: Dieses Verzeichnis dient als Zwischenspeicher für opsi-Pakete; Sie können es daher vom Backup ausschließen. Beim Wiederherstellen kann es dann passieren, dass Sie erneut größere Datenmengen übertragen müssen.


[[server-components-backup-redis]]
== Sicherung der Redis-Datenbank

Redis ist eine In-Memory-Datenbank, die alle Daten im Arbeitsspeicher vorhält. Das macht die Datenbank zwar extrem schnell, aber auch anfällig für Datenverluste -- etwa wenn der Strom ausfällt oder der Redis-Server-Prozess abrupt beendet wird.

In der Regel ist der Redis-Server so konfiguriert,
dass die Daten in regelmäßigen Abständen auf die Festplatte geschrieben werden (RDB Snapshots) um Persistenz zu gewährleisten.
Auch beim Herunterfahren des Redis-Servers werden die Daten auf die Festplatte geschrieben und beim Start des Redis-Servers von dort wieder geladen.
Alternativ oder in Kombination kann auch AOF (Append Only File) genutzt werden.

Weitere Details zum Thema finden Sie in der link:https://redis.io/docs/management/persistence/[Redis persistence Dokumentation].

In der Regel kann Redis über das folgende Kommando angewiesen werden einen Datenbank-Dump zu erzeugen:

[source,shell]
----
redis-cli save
----

Der Pfad des Dump-Files ist konfigurierbar, in den meisten Fällen liegt dieser unter `/var/lib/redis/dump.rdb`.

Dieses Dump-File sollte mit in das Backup aufgenommen werden.

IMPORTANT: `opsiconfd backup` sichert keine Redis-Daten.


[[server-components-backup-opsi-database]]
== Sicherung der opsi-Datenbank
Opsi verwendet eine MySQL- bzw. MariaDB-Datenbank.
Diese kann mit dem Standard-Werkzeug `mysqldump` gesichert werden.

Zum Beispiel:

[source,shell]
----
mysqldump --single-transaction opsi | bzip2 > /var/backups/opsi.sql.bz2
----

Das Dump-File `/var/backups/opsi.sql.bz2` kann dann mit in das Backup aufgenommen werden.

Bei Verwendung von xref:server:components/backup.adoc#server-components-opsiconfd-backup[opsiconfd backup]
ist das Sichern der MySQL-Datenbank eigentlich nicht notwendig, bietet aber zusätzliche Sicherheit.


[[server-components-opsiconfd-backup]]
== opsiconfd backup

Mit dem opsiconfd backup können die opsi-Datenbank und die opsi-Konfigurationsdateien komfortabel gesichert werden.
Hierbei werden die Daten aus der opsi-Datenbank Objekt-basiert und nicht als Dump gesichert.
Dies erleichtert das Rückspielen des Backups in andere Umgebungen, andere MySQL-Versionen und zukünftige Datenbanken.

Beim Erstellen und Rückspielen des Backup wird der opsi-Configserver in den Maintenance-Mode versetzt.
Damit wird sichergestellt, dass im Zeitraum des Backups / Restores keine CLient-Aktivität stattfindet.

Die Backup-Datei kann auf Wunsch AES-verschlüsselt geschrieben werden.

Es gibt weitere Parameter mit denen das Backup / Restore gesteuert werden kann.
Die Liste aller Parameter und deren Bedeutung erhalten Sie mittels:

[source,shell]
----
opsiconfd backup --help
opsiconfd restore --help
----

Hier ein Beispiel für das Erstellen eines Backups im msgpack-Format mit LZ4-Kompression:

[source,shell]
----
opsiconfd backup --quiet --overwrite /var/backups/opsi-backup.msgpack.lz4
----

Das Backup kann über den folgenden Befehl wieder hergestellt werden:

[source,shell]
----
opsiconfd restore /var/backups/opsi-backup.msgpack.lz4
----

Beim Einspielen eines Backups kann die ID des opsi-Configservers geändert werden (`--server-id`).
