////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      05.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-components-network]]
= Netzwerk-Konfiguration

Der opsi-Server unterstützt beide Protokolle, IPv4 und IPv6.

NOTE: In der Regel ist für den Server eine Dual-Stack-Konfiguration vorhanden, er verwendet also IPv4- und IPv6-Adressen/-Routen parallel im Netzwerk. Das ermöglicht die Kommunikation zwischen Geräten und Diensten, die sowohl IPv4- als auch IPv6-fähig sind.

[[server-components-network-ports]]
== Verwendete Netzwerk-Protokolle und -Ports

Der opsi-Server benötigt Internetzugriff über HTTP und HTTPS, vor allem für den Zugriff auf Paket-Repositorys der zugrundeliegenden Linux-Distribution (z.{nbsp}B. download.opensuse.org) und die opsi-Pakete (download.uib.de), aber auch für den Zugriff auf Grafana-Addons usw. 

TIP: Falls Sie einen Proxyserver verwenden, lesen Sie auch den Abschnitt <<server-configuration-http-proxy>>.

Der opsi-Server und seine Dienste verwenden darüber hinaus diese Netzwerk-Protokolle und -Ports:

* *53/tcp+udp*: DNS-Abfragen
* *4447/tcp*: für den Zugriff des opsi-Configservers auf die opsi-Paketquellen des Depotservers
* *445/tcp* bzw. *22/tcp*: Für den Einsatz des `opsi-deploy-client-agent` kommen unterschiedliche Protokolle und Ports zum Einsatz; diese hängen vom Betriebssystem des Clients ab. Windows-Clients benötigen Zugriff per CIFS-Protokoll (*445/tcp*), Linux- und macOS-Clients Zugriff auf SSH (*22/tcp*).
* *4441/tcp*: Je nach HostControl-Konfiguration (siehe Abschnitt xref:server:components/opsiconfd.adoc:server-components-opsiconfd-host-control[HostControl]) spricht der opsi-Server den Client-Agent über *4441/tcp* an.
* *4447/tcp*: Standardport für den zentralen opsi-Service `opsiconfd` (siehe Kapitel xref:server:components/opsiconfd.adoc[Der Dienst *opsiconfd*]); alle Clients, Depotserver und Admin-Geräte benötigen Zugriff auf diesen Port.
* *445/tcp*: für den Zugriff auf den opsi-Depotserver per Samba/CIFS (siehe Kapitel xref:server:components/samba.adoc[Samba]); nicht erforderlich, falls per WebDAV auf den Depotserver zugegriffen wird

NOTE: Für den Einsatz von Netboot über TFTP ist der Zugriff auf weitere Ports nötig (siehe Kapitel xref:server:components/tftp.adoc[TFTP-Server]). Um den opsi-Server per SSH erreichen zu können, muss der Zugriff auf *22/tcp* (eingehend) möglich sein.

[[server-configuration-http-proxy]]
== Proxy-Einstellungen

include::server:partial$http-proxy.adoc[]
