////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      05.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-components-network]]
= Netzwerk-Konfiguration

Der opsi-Server unterstützt beide Protokolle, IPv4 und IPv6.

NOTE: In der Regel ist für den Server eine Dual-Stack-Konfiguration vorhanden, er verwendet also IPv4- und IPv6-Adressen/-Routen parallel im Netzwerk. Das ermöglicht die Kommunikation zwischen Geräten und Diensten, die sowohl IPv4- als auch IPv6-fähig sind.

[[server-components-network-ports]]
== Verwendete Netzwerk-Protokolle und -Ports

Der opsi-Server benötigt Internetzugriff über HTTP und HTTPS, vor allem für den Zugriff auf Paket-Repositorys der zugrundeliegenden Linux-Distribution (z.{nbsp}B. download.opensuse.org) und die opsi-Pakete (download.uib.de), aber auch für den Zugriff auf Grafana-Addons usw. 

TIP: Falls Sie einen Proxyserver verwenden, lesen Sie auch den Abschnitt <<server-configuration-http-proxy>>.

Der opsi-Server und seine Dienste verwenden darüber hinaus diese Netzwerk-Protokolle und -Ports:

* *53/tcp+udp*: DNS-Abfragen
* *4447/tcp*: für den Zugriff des opsi-Configservers auf die opsi-Paketquellen des Depotservers
* *445/tcp* bzw. *22/tcp*: Für den Einsatz des `opsi-deploy-client-agent` kommen unterschiedliche Protokolle und Ports zum Einsatz; diese hängen vom Betriebssystem des Clients ab. Windows-Clients benötigen Zugriff per CIFS-Protokoll (*445/tcp*), Linux- und macOS-Clients Zugriff auf SSH (*22/tcp*).

Je nach xref:server:configuration/opsiconfd.adoc#server-configuration-opsiconfd-host-control[HostControl-Konfiguration]
benötigt der opsi-Server Zugriff auf den opsi-client-agent (Port *4441/tcp*).

Standardmäßig verwendet der zentrale opsi-Service *opsiconfd* den Port *4447/tcp*.
Alle Clients, Depotserver und Admin-Geräte benötigen Zugang zu diesem Port.

Bei Verwendung von xref:server:configuration/samba.adoc#server-configuration-samba[Samba / CIFS]
als Depot-Protokoll benötigen die opsi-Clients Zugriff auf den Port *445/tcp*.
Wird hingegen *WebDAV* als Depot-Protokoll eingesetzt, ist dies nicht erforderlich.

Bei Verwendung von Netboot über TFTP werden xref:server:configuration/tftpd.adoc#server-configuration-tftpd-ports-firewall[zusätzliche Ports benötigt].

Soll der Zugriff auf den opsi-Server per SSH möglich sein, muss der Port *22/tcp* eingehend erlaubt sein.


[[server-configuration-http-proxy]]
== Proxy-Einstellungen

include::server:partial$http-proxy.adoc[]
