////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      08.05.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]


[[server-components-opsi-setup]]
== opsi-setup
Vor opsi 4.3 war*opsi-setup*ein zentrales Werkzeug für Konfigurations-Aufgaben auf dem {opsi-server}.
Mit opsi 4.3 wurden viele dieser Aufgaben automatisiert.
Andere Funktionalitäten sind in das xref:server:configuration/opsiconfd.adoc#opsiconfd-setup[opsiconfd setup] gewandert.

[[server-components-opsi-set-rights]]
== opsi-set-right

Mittels `opsi-set-rights` können die Datei- und Verzeichnisberechtigungen eines {opsi-server}s korrigiert werden.
Ohne weitere Parameter bearbeitet `opsi-set-rights` dabei alle Dateien und Verzeichnisse, die für opsi relevant sind.
Über die Angabe eines Pfades, kann die Verarbeitung auf ein bestimmtes Verzeichnis beschränkt werden.
