////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      17.09.2025
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full


[[server-components-opsipxeconfd]]
= Der Dienst *opsipxeconfd*

Der Dienst *opsipxeconfd* übernimmt die zentrale Verwaltung der PXE-Boot-Konfiguration für alle Clients, die per PXE-Boot starten (siehe auch Kapitel xref:server:components/dhcp-server.adoc[DHCP-Server/PXE-Boot]).
Die erforderlichen Konfigurationsdateien werden im Verzeichnis `/tftpboot/opsi/cfg` abgelegt und von *opsipxeconfd* automatisch auf Basis von Vorlagen und individuellen Einstellungen generiert.

Als Bootloader kommt aktuell *GRUB2* zum Einsatz – sowohl für UEFI- als auch für BIOS-basierte Geräte.
Die Vorlage für die GRUB-Konfiguration finden Sie unter `/usr/share/opsipxeconfd/grub.cfg`.

Aus dieser Vorlage erstellt der Dienst die allgemeine Konfigurationsdatei `/tftpboot/opsi/cfg/grub.cfg`, die immer dann verwendet wird, wenn keine Client-spezifische Konfiguration existiert.
Sobald für einen Client eine Aktion für ein Netboot-Produkt gesetzt wird, erzeugt *opsipxeconfd* automatisch eine individuelle Konfigurationsdatei.
Diese wird im selben Verzeichnis unter dem Namen `<System-UUID>.cfg` bzw. `<MAC-Adresse>.cfg` abgelegt.


[[server-components-opsipxeconfd-config]]
== Konfiguration
Die Konfiguration des *opsipxeconfd* kann auf drei Wegen erfolgen: über die Datei `/etc/opsi/opsipxeconfd.conf`, über Umgebungsvariablen oder direkt per Kommandozeilen-Parameter beim Start.
Die Reihenfolge der Priorität ist wie folgt:

1. Einträge in der Konfigurationsdatei überschreiben die Standardeinstellungen.
2. Umgebungsvariablen überschreiben Einträge in der Konfigurationsdatei.
3. Kommandozeilen-Parameter überschreiben Umgebungsvariablen.

Eine vollständige Übersicht aller Konfigurationsoptionen erhalten Sie mit folgendem Befehl:

[source,console]
----
opsipxeconfd --help
----

Jeder Kommandozeilenparameter hat eine zugehörige Umgebungsvariable (in Großbuchstaben).
In der Konfigurationsdatei sind alle Parameter ausführlich dokumentiert.

NOTE: Änderungen an der Konfiguration können meist direkt im laufenden Betrieb mit dem Befehl `opsipxeconfd reload` übernommen werden.

[[server-components-opsipxeconfd-status]]
== Status und Troubleshooting

Um den aktuellen Status des Dienstes sowie die Client-spezifischen Boot-Konfigurationen anzuzeigen, verwenden Sie:

[source,console]
----
opsipxeconfd status
----

Überprüfen Sie die Log-Datei unter `/var/log/opsi/opsipxeconfd/opsipxeconfd.log` auf mögliche Fehler oder Hinweise.
Das Log-Level können Sie in der Konfigurationsdatei anpassen.
