////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      08.05.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]


[[server-components-opsi-outdated-to-setup]]
== opsi-outdated-to-setup

Das Kommandozeilen-Werkzeug *opsi-outdated-to-setup* kann genutzt werden um ActionRequests für Clients zu setzen, die ein gewisses Produkte installiert haben und auf deren Depot eine neuere Version verfügbar ist.

Außerdem können damit ActionRequests gesetzt werden um fehlgeschlagene Installationen zu wiederholen, über das Flag `--add-failed`.

Die Parameter `--exclude-products`, `--include-products`, `--exclude-product-groups` und `--include-product-groups` schränken die zu behandelten Produkte ein.

Mit dem Parameter `--dry-run` kann ein Durchlauf simuliert werden, ohne tatsächlich etwas zu verändern.

Die Option `--uninstall-where-only-uninstall` setzt alle installierten Produkte auf *uninstall*, falls sie außer dem *uninstall-Skript* kein registriertes
Skript (*setup*, *always*, ...) beinhalten.

Um Clients auszuwählen, existieren es die Optionen `--clients`, `--client-groups` und `--exclude-client-groups`.

`--setup-on-action` ist eine besondere Option, welche genutzt werden kann, um für jeden Client für den etwas geändert wurde (also der ein nicht aktuelles Paket installiert hatte), ein Produkt auf *setup* zu setzen.
Das ist beispielsweise nützlich in Kombination mit *shutdownwanted* (um nach der installation einen shutdown anzufordern) oder für *swaudit* (um die Audit-Daten zu aktualisieren).
