////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      08.05.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]


[[server-components-opsi-makepackage]]
== opsi-makepackage (opsi-Pakete bauen)

Mit *opsi-makepackage* wird beim aus einer Paket-Quelle (*workbench*) ein opsi-Paket erstellt.
Hierfür wechselt man in das Quell-Verzeichnis und ruft den Befehl `opsi-makepackage` auf.

`opsi-makepackage` kennt einige Optionen, die sein Verhalten modifizieren.
Eine vollständige Liste der verfügbaren Parameter und ihrer Bedeutung erhalten Sie mittels `opsi-makepackage --help`.

NOTE: Ein so erstelltes Paket, können Sie auf beliebigen opsi-Depotservern mittels xref:server:components/opsi-package-manager.adoc[opsi-package-manager] installieren.
