////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      06.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-components-samba]]
= Samba

Der Zugriff auf die Dateien eines opsi-Depotservers erfolgt über WebDAV oder Samba. Samba ist der Standard -- außer bei Docker (siehe Kapitel xref:server:installation/docker.adoc[opsi als Docker-Container]), denn der Docker-Container unterstützt ausschließlich WebDAV.

TIP: `opsiconfd setup` (siehe Abschnitt xref:server:components/opsiconfd.adoc#server-components-opsiconfd-setup[*opsiconfd setup*]) nimmt einige Anpassungen an der Samba-Konfiguration vor und legt unter anderem die folgenden Freigaben automatisch an:

* *opsi_depot* (`/var/lib/opsi/depot`): Zugriff auf das Produkt-Depot (read-only).
* *opsi_depot_rw* (`/var/lib/opsi/depot`): Zugriff auf das Produkt-Depot (read-write).
* *opsi_images* (`/var/lib/opsi/ntfs-images`): Freigabe zur Ablage von NTFS-Images (read-write).
* *opsi_workbench* (`/var/lib/opsi/workbench`): Zugriff auf die Produkt-Workbench (read-write).
* *opsi_repository* (`/var/lib/opsi/repository`): Zugriff auf das Produkt-Repository (read-only).
* *opsi_logs* (`/var/log/opsi`): Zugriff auf das Log-Verzeichnis (read-only).


[[server-components-samba-depot-user]]
== Zugriff auf die Freigaben: clientconfig.depot.user

Die opsi-Clients verwenden für den Zugriff auf den *opsi_depot*-Freigabe den Benutzer *pcpatch* (siehe: xref:server:configuration/authorization.adoc#authorization-users-and-groups[]).

Der Zugriff sollte hierbei über den Domain-Namen und Benutzernamen erfolgen.
Die Konfiguration hierzu findet über den Host-Parameter *clientconfig.depot.user* statt.

Ist der opsi-Server Mitglied einer Windows-/Samba4-Domäne und der Benutzer *pcpatch* ein Domänen-Benutzer,
dann muss hier `<Name der Domäne>\pcpatch` verwendet werden. Ansonsten verwendet man `<NetBIOS-Name des opsi-Servers>\pcpatch`.
