////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      08.05.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]


[[server-components-tftpd]]
= TFTP-Server

Der TFTP-Server wird benötigt um opsi-Bootimages für die opsi-Clients per *TFTP*-Protokoll zur Verfügung zu stellen.
Der Standard-TFTP-Server in Verbindung mit opsi ist der *opsi-tftpd-hpa*.
Dieser wird als Abhängigkeit des *opsi-server-full* installiert.

Der *opsi-tftpd-hpa* ist standardmäßig so konfiguriert, dass er beim Systemstart gestartet wird.
Er kann über `systemctl stop opsi-tftpd-hpa.service` gestoppt und über `systemctl start opsi-tftpd-hpa.service` gestartet werden.

Für gewöhnlich startet der Dienst mit einem Verbose-Parameter.
Zur Fehlersuche oder zur weiteren Analyse kann das Log-Level des Dienstes angepasst werden.
Hierfür wird der folgender Befehl verwendet:

[source,shell]
----
systemctl edit --full opsi-tftpd-hpa.service
----
Nun kann der Parameter `-v` durch den Parameter `--verbosity <log-level>` (z.B. `--verbosity 7` für sehr viele Details) ersetzt werden.

Daraufhin wird der Dienst neu gestartet:
[source,shell]
----
service opsi-tftpd-hpa restart
----


[[server-components-tftpd-ports-firewall]]
== TFTP Ports und Firewall-Konfiguration
Der Client verbindet sich initial mit dem Server-Port 69.
Der Server sendet Pakete aber nicht mit Port 69 als Quellport.
Client und Server wählen für die weitere Kommunikation sogenannte TIDs aus.
Diese TIDs entsprechen UDP-Ports und liegen im Bereich von 1024 bis 65535.
Alle weiteren Pakete werden dann vom TID-Port des Servers zum TID-Port des Clients und umgekehrt gesendet.

Die Server-Firewall muss daher so konfiguriert werden, dass eingehende Verbindungen auf Port 69/udp erlaubt sind.
Zusätzlich muss die UDP-Kommunikation zwischen den TID-Ports erlaubt werden.
Das funktioniert am einfachsten über das Kernel-Modul `ip_conntrack_tftp` bzw. `nf_conntrack_tftp`.
