[[opsi-intro-convention]]
== Conventions and Notations

In this manual, we adhere to specific conventions for spelling and emphasis:

* File and directory names are presented in `proportional font`.
* Longer commands and listings are contained in separate boxes. These can be conveniently transferred using copy{nbsp}&{nbsp}paste: 

[source,console]
----
this is a command
----

* `opsi-script` code is displayed like this: 

[source,console]
----
Message "Installing "+ $ProductId$ +" ..."
----

* Elements in `<angle brackets>` indicate placeholders that you need to replace with their actual values. For instance, the file share containing opsi packages is referred to as `<opsi-depot-share>`. On an actual server, this is typically found at `/var/lib/opsi/depot`. Hence, the software package `<opsi-depot-share>/ooffice` would be located at `/var/lib/opsi/depot/ooffice`.
* Menu entries and button labels are formatted in _italics_.
* Keyboard keys and combinations are enclosed in square brackets, for example, [C], [Ctrl]{plus}[C], etc.
