////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

////
;***************************************************************************
; Subversion:
; $Revision:  $ $Author: oertel $
; $Date: $
;***************************************************************************
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.0.6
:doctype:   book

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]

[[opsi-406-releasenotes]]
= opsi Version 4.0.6 Release Notes

// Include common opsi copyright
include::../common/opsi_manual_copyright.asciidoc[]

[[opsi-406-releasenotes-supportmatrix]]
== opsi Support Matrix

This is an overview on which distributions and releases the opsi-server will run:

include::../common/opsi_manual_supportmatrix.asciidoc[]

If you are using an OS version which is not contained in the section above,
we recommend updating the OS before installing opsi v4.0.6.

[[opsi-406-releasenotes-overview]]
== Overview of the new features

The Highlights of this Release are:

* Windows 10 Support
* New opsi bootimage
* New opsi-linux netboot products

The opsi Service Release 4.0.6 comes with a whole bunch of new features and improvements.
Here is a summary:

* Windows netboot products +
** Windows 10 Products
** winpe Partition are now formatted with NTFS (on non UEFI Systems).
See special chapter: <<opsi-406-releasenotes-win10notes>>.



* New opsi-bootimage
** Uses Ubuntu Trusty 14.04 as base
** Kernel 4.1.0
** Syslinux 6.0.3 included
** 32-bit libraries included in 64-bit bootimage

CAUTION: The new pxelinux.0 does not draw points while loading the booimage anymore. So you have to wait for the start of the bootimage without visual feedback.
CAUTION: The new opsi-linux-bootimage (20150916) comes with Syslinux 6.0.3.
It may happen that Syslinux 6.0.3 is not compatible with older hardware.
For example it breaks PXE localboot for Dell Optiplex 790 devices. +
This package delivers the Syslinux binaries from the last stable opsi-linux-bootimage.
To use the old Syslinux binaries move the binaries from the syslinux folder into /tftpboot/linux/
(e.g. /var/lib/tftfboot/linux/ on SLES) +
This should overwrite the Syslinux 6.0.3 binaries and your PXE boot should use the old Syslinux version. +
Please Note: Future opsi-linux-bootimage updates will overwrite the downgraded syslinux version.
After installing a new opsi-linux-bootimage version please repeat the above steps.

* opsi-configed:

** opsi-configed now provides export of data tables as PDF files (or directly to a PDF viewer).

** The hardware inventory page now offers a convenience method for creating an automated PC specific driver integration. +
The byAudit driver path can be created such that the bootimage finds the drivers, and driver files can be copied to the {opsi-configserver} (if there is a connection to the opsi_depot share).
Finally, an opsi-set-rights command is executed for the driver files

** The performance is improved by a more direct access to the MySQL backend (if available).

** The usability of the logging pages is improved: The search starts now from the current cursor position. Search strings are saved in a combo box. Line counting has been introduced.

** The software inventory page now provides a String search. You can choose if Microsoft Windows updates (kb numbers) are excluded from the view (as now is default).

** A bug of the license statistics server function has been fixed. Under certain conditions, it had the effect that too less license options available were reported.


* opsi-client-agent: +

** Improved `opsi-deploy-client-agent` script. +
With the improved script also IP addresses can be used for deployment. +
Furthermore `mount` can be used again for copying data. +
The script automatically detects, what kind of address has been provided.
Also additional parameters are available to specify the parameter type.

** New property `depends_on_service`: +
This is a list of services that the opsiclientd depends upon. +
They must be running before the opsiclientd can start. +
The default is: `Dhcp, Dnscache` +

CAUTION: changing this property can result in the opsiclientd not starting anymore.

** New property `setup_after_install`: +
This is a list of opsi products, that are set to `setup` after installation of the opsi-client-agent.

* python-opsi:

** Many improvements, new features and bugfixes. +
See special chapter: <<opsi-406-releasenotes-python-opsi>>


* New optional config: `clientconfig.depot.user` to configure `domain\user` for pcpatch +
See special chapter: <<opsi-manual-samba4>>.


* opsi-winst / opsi-script (4.11.5.13) (from 4.0.5): +

** Files commands for hardlinks, symbolic links, Rename and Move in Files sections

** For-To Loop

** Switch / Case Statement

** New Stringlist function: `removeFromListByContaining`

** New Stringlist function: `LoadTextFileWithEncoding(` <file name> `,` <encoding>`)`

** New String function `unquote2(<string>,<quote-string>)`

** New String function `GetShortWinPathName(<longpath string>)`

** New String function `GetConfidentialProductProperty (` <PropertyName>, <DefaultValue>`)`

** New boolean function `CompareDotSeparatedNumbers(<str1>, <relationstr>, <str2>)`

** New boolean function `CompareDotSeparatedStrings(<str1>, <relationstr>, <str2>)`

** New statement `UpdateEnvironment`. The call of `UpdateEnvironment` forces Windows to reload the environment variables from the registry (NT6 only).

** Files command `del`: ATTENTION changed behaviour: Similar like it is implemented for the copy command: +
If a system file is in use, then it can be deleted only after a reboot. The '{opsi-winst}/opsi-script' default behaviour is therefore that a file in use will be marked for delete after the next reboot, AND the '{opsi-winst}/opsi-script' reboot flag is set. Setting the copy option `-c` turns the automatic reboot off. Instead normal processing continues, the deleting will be completed only when a reboot is otherwise triggered.

** Upgrade of the SSL libraries to 1.0.2d, update of the SSL protocol to TLS autonegotiation

** See special chapter: <<opsi-script>>


* Linux netboot products:

** The new generation of Linux netboot products is based on the orginal installer of the distribution, which is configured by an answer file.

** New generation netboot products are available for: SLES12, openSuse13-2, Ubuntu14-04, Debian7, Debian8, CentOS70, Redhat70

** See also the special linux chapter: <<opsi-manual-linux>>.

////
For details please refer to the opsi-v405-releasenotes manual and the revised opsi manuals.
////

[[opsi-406-releasenotes-packages]]
== list of packages

.server packages:
* opsi-depotserver_4.0.6.4-1
* opsi-linux-support_1.0-4
* opsi-utils_4.0.6.6-4
* opsiconfd_4.0.6.10-2
* python-opsi_4.0.6.23-1
* opsi-linux-bootimage_20150916-1
* opsi-configed_4.0.6.3.5-2

.opsi packages (localboot):
* opsi-client-agent_4.0.6.3-2
* opsi-configed_4.0.6.3.5-2
* windomain_1.0-8
* opsi-uefi-netboot_4.0.5-3
* config-win10_4.0.6-4.opsi
* opsi-template-with-admin_4.0.6-1
* opsi-setup-detector_4.0.5.131-1

.opsi packages (netboot):
* win* 4.0.6.1-2 (including Windows 10 Pakete)
* opsi-clonezilla (4.0.6-1)
* memtest86 5.01-1

.opsi packaages (opsi-linux):
* centos70_4.0.6.2-1
* redhat70_4.0.6.2-1
* debian7-4.0.6-1
* debian8-4.0.6-1
* Ubuntu14-04_4.0.6-2
* Ubuntu15-04_4.0.6-2
* opensuse13-2_4.0.6.2-2
* sles12_4.0.6.2-2

.opsi packages(opsi-local-image):
* opsi-local-image-win* 4.0.6.1-2
* opsi-local-image-capture 4.0.6.1-2


[[opsi-406-releasenotes-missing]]
== What is still missing (and under progress)

* opsi-client-agent: +
To execute opsi-winst scripts as the current user during logon 'User Profile Management'.

* opsi-linux-client-agent: +
A real service, that also provides 'push installations'.

* opsi-linux netboot product Fedora22

* opsi-linux 4.0.6 netboot products: uefi support

* opsi-clonezilla: uefi support



[[opsi-406-releasenotes-knownbugs]]
== Known Bugs / Known Problems

.KNOWN BUGS:

* opsi-configed                         4.0.5.8-1 vs opsi 4.0.6 opsi-server: +
Displaying Hardwareinformation and  Logfiles fails. Detection of connected opsi service shows "<3.4"

.KNOWN PROBLEMS:


* opsi-configed 	all versions +

The thumb bar in "long" listings is not displayed. This is a bug in Java version 8u60 which we reported to Oracle. It is listed at
https://bugs.openjdk.java.net/browse/JDK-8134829 and should be resolved in 8u71.


* (Not documented yet)

[[opsi-406-releasenotes-eol]]
== Discontinuation

[[opsi-406-releasenotes-eol_server]]
=== Discontinuation: Distributions for opsi-server

This chapter lists distributions that for several reasons are not supported by opsi anymore.

* Univention Corporate Server: the versions 3.0 und 3.1 are discontinued by Univention and are not supported anymore.

* Debian 6 Squeeze

* Ubuntu Lucid 10.04

* OpenSuse 12.3

See also the support matrix: <<opsi-406-releasenotes-supportmatrix>>.

[[opsi-406-releasenotes-eol_winclient]]
=== Discontinuation clients: Windows versions

With opsi v4.0.6 the netboot packages for

* Windows 8
* Server 2003

are not maintained anymore. +
Also in the near future the Update Abos will not support these Windows versions anymore. +
Please contact us in case of any questions or concerns.

See also the chapter: <<opsi-406-releasenotes-netboot-windows>>.

[[opsi-406-releasenotes-eol_linclient]]
=== Discontinuation clients: Linux versions

With opsi v4.0.6 the netboot packages for

* openSuse 12.3
* Fedora20
* Ubuntu 10.04 (Lucid)
* Debian 6 (Squeeze)

will not be maintained anymore. Please contact us in case of any questions or concerns.

See also chapter: <<opsi-manual-linux>>.

[[opsi-406-releasenotes-installation]]
== Installation notes

For safety reasons we recommend creating a backup of your backends with +
{opsi-backup} before updating:
[source,prompt]
----
opsi-backup create
----

The products contained in this release depend on each other in many cases. +
Do not try to install just parts of this update.

We recommend to first update the server and then the opsi products.

When upgrading an existing opsi server your package manager may ask you if you +
want to replace `/etc/opsi/opsi.conf` with a newer version.
If this question appears and you did not change the mentioned file you can replace the file with the new one.
If you changed the file or are unsure please deny the replacement.

As it was described above, a new version of `/etc/opsi/opsi-product-updater.conf` +
may be introduced during the update.
The new version gives also support for smtpusers with smtppasswords to systems +
that require this type of authentication.

To make sure that permissions are applied correctly +
we recommend to run ``opsi-setup --set-rights`` after the installation. +
Please be aware that the execution of latter can last for many minutes.


[[opsi-406-releasenotes-installation-opsipackages]]
=== Notes for updating opsi-packets (Testing)

////
Bitte nachstehenden Block bei release nicht löschen sondern auskommentieren
////

For installing the testing server packets the opsi repository has to be changed from `opsi40` to `opsi40-testing`.

In case of Ubuntu 14.04: +
`deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/opsi40/xUbuntu_14.04 ./` +
replace with: +
`deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/opsi40-testing/xUbuntu_14.04 ./`

Then the packages can be updated. +
For example Ubuntu / Debian:
[source,prompt]
----
aptitude update
aptitude full-upgrade
----

For installing the testing opsi products you should add to the file: +
`/etc/opsi/opsi-product-updater.conf` +
the following section

[source,prompt]
----
[repository_opsi_406_testing]
baseUrl = http://download.uib.de
dirs = opsi4.0/testing/opsi-v406/products/localboot, opsi4.0/testing/opsi-v406/products/netboot
active = true
username =
password =
autoInstall = false
autoUpdate = true
autoSetup = false
onlyDownload = false
----

You may append the `dirs` line by:

* `, opsi4.0/testing/opsi-v406/opsi-linux`

* `, opsi4.0/testing/opsi-v406/opsi-local-image`


Set in the section `[repository_uib]` the following line:
[source,prompt]
----
active = false
----
Then execute the opsi-product-updater.
To install all packets:
[source,prompt]
----
opsi-product-updater -i -vv
----

To install updates only:
[source,prompt]
----
opsi-product-updater -vv
----

////
Bitte vorstehenden Block bei release nicht löschen sondern auskommentieren
////

////
The installation does not require any special action. It is performed within the normal updates of your server and opsi products.

First update the server according to the update command of your Linux distribution. +

We recommend to set in `/etc/opsi/opsi-product-updater.conf`
in the section `[repository_uib]` the following to get all products even if they start with win* :
[source,prompt]
----
excludes =
----

If you need the opsi-linux products you should append the `dirs` entry: +

[source,prompt]
----
dirs = opsi4.0/products/localboot, opsi4.0/products/netboot
----
by the path `opsi4.0/products/opsi-linux`

If you need the opsi-local-image products you should append the `dirs` entry
by the path `opsi4.0/products/opsi-local-image`

Then execute the opsi-product-updater.

[source,prompt]
----
opsi-product-updater -i -vv
----

To install updates only:
[source,prompt]
----
opsi-product-updater -vv
----

In case of a multi depot installation first upgrade the config-server before upgrading the depots.


If you want to use product-ids with a length of more than 32 characters and are using the MySQL-backend please update the table definition on your configserver with the following command:

[source,prompt]
----
opsi-setup --update-mysql
----

[[opsi-405-releasenotes-update-java]]
=== Hints for updating the Java Runtime Environment

The '{opsi-configed}' now requires a Java Runtime Enviromnent (JRE) on the computer on which
it is run, at least in version 7 (internal version 1.7).

If you do not run the '{opsi-configed}' on the server, e.g. because the server does not offer
a graphical user interface, opsi does not require a Java installation on the server at all.

In the other case, you must get a Java Runtime Engine at least in version 7 active.
If there is still an older version active you should deinstall the old one and install the new one.
For Ubuntu the commands are


[source,prompt]
----
apt-get remove openjdk-6-jre
apt-get remove openjdk-6-jre-lib
apt-get install openjdk-7-jre
----

Thereafter the command


[source,prompt]
----
java -version
----

should indicate that a least version 1.7.0 is running.

////

[[opsi-406-releasenotes-win10notes]]
== Tips for using Windows 10

[[opsi-406-releasenotes-win10notes-detect]]
=== Windows 10 detection

The opsi-winst function `getMsVersionInfo` returns the value `6.3` on Windows 8.1, and returns the value `10.0` on Windows 10. Although, regarding opsi, the system architecture of Windows 10 is basically NT6. +
The function `getMsVersionInfo` is of special importance to distinguish NT5 (Windows XP) system architecture from NT6 (Vista and above). The `getMsVersionInfo` return value (like `6.3` or `10.0`) at first sight looks like a number, but actually it is a string. So never use string compare functions (like `<` or `=` or `>` or `<=` ...) to evaluate the result of `getMsVersionInfo`, for the string compare functions operate on alphabetic order.
In alphabetic order, the string `10.0` is less than `6.0` (for in alphabetic order `1..` comes before `6..`).

To evaluate the result of `getMsVersionInfo`, use the new function `CompareDotSeparatedNumbers`:

[source,winst]
----
if CompareDotSeparatedNumbers(getMsVersionInfo,"6.0") < "0"
  comment "We are on NT5"
else
  comment "We are on NT6"
endif
----

opsi-winst 4.11.5 and above provides a syntax, which is easier to understand:

[source,winst]
----
if CompareDotSeparatedNumbers(getMsVersionInfo, "<", "6.0")
  comment "We are on NT5"
else
  comment "We are on NT6"
endif
----

[[opsi-406-releasenotes-win10notes-helper]]
=== Windows 10 helper products

To work with Windows 10 (especially for desktops) we recommend the following products:

* classic_shell: +
http://download.uib.de/opsi4.0/products/contribute/full-package/classic-shell_4.2.1-1.opsi

* config-win10: +
http://download.uib.de/opsi4.0/products/contribute/full-package/config-win10_4.0.6-4.opsi +
This package can configure Windows 10 mostly in security and privacy related topics. +
Possible configurations:
** boot_to_desktop: Skip the Windows login screensaver.
** config_updates: Configure the Microsoft Windows 10 update behaviour with the following configurations:
*** AllowPeerToPeer: Your PC connects to Microsoft and also downloads available updates from internet peer-to-peer clients.
*** LocalPeerToPeer: Your PC connects to Microsoft and also downloads available updates from your local peer-to-peer clients.
*** MicrosoftOnly: With this configuration your PC download updates only from official Microsoft servers.
** disable_cortana: This property disables the Microsoft Cortana search assistant.
** disable_customer_experience: This configures the use of the customer experience program from Microsoft.
** disable_mrt: This confugures the use and download of the Malware Removal Tools (MRT).
** disable_telemetry: Configure if your PC gathers and sends information to Microsoft.
** force_login_Script: Re-run the opsi login script in case something on your PC changed.

include::../common/opsi_manual_samba4.asciidoc[]

include::../common/opsi_manual_linux.asciidoc[]

[[opsi-script]]
== opsi-script / opsi-winst 4.11.5

* Upgrade of the SSL libraries to 1.0.2c, update of the SSL protocol to TLS 1.2

.In Files sections:

* `hardlink` <existing file> <new file> // since 4.11.5 [W/L] +
A existing <new file> will be over written. +
`hardlink` works only on filesystems that support hard links like NTFS and standard Linux filesystems.

* `symlink` <existing file> <new file> // since 4.11.5 [W/L] +
A existing <new file> will be over written. +
At Windows is `symlink` only available since NT6 and up !

* `rename` <old filename> <new filename> // since 4.11.5 [W/L] +
`move` <old filename> <new filename> // since 4.11.5 [W/L] +
There is no difference between `rename` and `move`, that are just two names for the same function +
A existing <new file> will be over written. +
 +
Windows: <new filename> may be located in a differen directory or volume / disk. In the second case (different volume / disk) the file will be copied  and than the original file will be deleted. +
If it is not possible to create the target file becaus the file is in use, then it can be overwritten only after a reboot. The '{opsi-winst}/opsi-script' default behaviour is therefore that a file in use will be marked for overwriting after the next reboot, AND the '{opsi-winst}/opsi-script' reboot flag is set. Setting the copy option `-c` turns the automatic reboot off. Instead normal processing continues, the copying will be completed only when a reboot is otherwise triggered. +
Creating Junctions at Windows is not supported right now. +
 +
Linux: <new filename> may be located in a different directory but not in a different filesystem. The Option `-c` will be ignored at Linux. +
 +
Example:
[source,winst]
----
[Files_link_move]
del "$HomeTestFiles$\files\hardlink.txt"
hardlink "$HomeTestFiles$\files\dummy.txt" "$HomeTestFiles$\files\hardlink.txt"
del "$HomeTestFiles$\files\symlink.txt"
symlink "$HomeTestFiles$\files\dummy.txt" "$HomeTestFiles$\files\symlink.txt"
del "$HomeTestFiles$\files\temp\rename.txt"
del "$HomeTestFiles$\files\temp\move.txt"
copy "$HomeTestFiles$\files\dummy2.txt" "$HomeTestFiles$\files\temp\"
rename "$HomeTestFiles$\files\temp\dummy2.txt" "$HomeTestFiles$\files\temp\rename.txt"
copy "$HomeTestFiles$\files\dummy2.txt" "$HomeTestFiles$\files\temp\"
move "$HomeTestFiles$\files\temp\dummy2.txt" "$HomeTestFiles$\files\temp\move.txt"
----

* The function `del` and `delete`  +
ATTENTION changed behaviour: Similar like it is implemented for the copy command: +
If a system file is in use, then it can be deleted only after a reboot. The '{opsi-winst}/opsi-script' default behaviour is therefore that a file in use will be marked for delete after the next reboot, AND the '{opsi-winst}/opsi-script' reboot flag is set. Setting the copy option `-c` turns the automatic reboot off. Instead normal processing continues, the deleting will be completed only when a reboot is otherwise triggered. +
The Option `-c` will be ignored at Linux. .

.For-To Loop [W/L]

* Useful for multiple calls of a single command or of a sub-section

* Syntax:

`for` %<temporary string variable>% `=` <start string> `to` <end string> `do` <one statement> //since 4.11.5 [W/L]

The temporary varibale %<temporary string variable>% must not be declared and is
available in the called sub-section as constant.

* Example:

Code from opsi-winst-test:
[source,winst]
----
message "for to loop"
set $ConstTest$ = "12345"
set $CompValue$ = ""
for %s% = "1" to "5" do sub_iteration_test
if ($ConstTest$ = $CompValue$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif

[sub_iteration_test]
set $CompValue$ = $CompValue$ + '%s%'
----

produces the log:

[source,winst]
----
message for to loop
Set  $ConstTest$ = "12345"
  The value of the variable "$ConstTest$" is now: "12345"
Set  $CompValue$ = ""
  The value of the variable "$CompValue$" is now: ""

~~~~~~ Looping through:  '1', '2', '3', '4', '5'

  ~~~~~~~ Start Sub ~~~~~~~  sub_iteration_test
  Set  $CompValue$ = $CompValue$ + '1'
    The value of the variable "$CompValue$" is now: "1"

  ~~~~~~~ End Sub   ~~~~~~~  sub_iteration_test


  ~~~~~~~ Start Sub ~~~~~~~  sub_iteration_test
  Set  $CompValue$ = $CompValue$ + '2'
    The value of the variable "$CompValue$" is now: "12"

  ~~~~~~~ End Sub   ~~~~~~~  sub_iteration_test


  ~~~~~~~ Start Sub ~~~~~~~  sub_iteration_test
  Set  $CompValue$ = $CompValue$ + '3'
    The value of the variable "$CompValue$" is now: "123"

  ~~~~~~~ End Sub   ~~~~~~~  sub_iteration_test


  ~~~~~~~ Start Sub ~~~~~~~  sub_iteration_test
  Set  $CompValue$ = $CompValue$ + '4'
    The value of the variable "$CompValue$" is now: "1234"

  ~~~~~~~ End Sub   ~~~~~~~  sub_iteration_test


  ~~~~~~~ Start Sub ~~~~~~~  sub_iteration_test
  Set  $CompValue$ = $CompValue$ + '5'
    The value of the variable "$CompValue$" is now: "12345"

  ~~~~~~~ End Sub   ~~~~~~~  sub_iteration_test


~~~~~~ End Loop
If
  $ConstTest$ = $CompValue$   <<< result true
  ($ConstTest$ = $CompValue$)   <<< result true
Then
  comment: passed
Else
EndIf
----

.Switch / Case Statement [W/L]

* Syntax:

----
Switch <string expression>
  Case <string const>
    <statement(s)>
  EndCase
  [DefaultCase
    <statement(s)>
   EndCase]
EndSwitch
----

* Examples:

Code from opsi-winst-test:
[source,winst]
----
set $ConstTest$ = "5"
Switch $ConstTest$
	Case "1"
		set $CompValue$ = "1"
	EndCase
	Case "2"
		set $CompValue$ = "2"
	EndCase
	Case "3"
		set $CompValue$ = "3"
	EndCase
	Case "4"
		set $CompValue$ = "4"
	EndCase
	Case "5"
		set $CompValue$ = "5"
	EndCase
	Case "6"
		set $CompValue$ = "6"
	EndCase
	Case "7"
		set $CompValue$ = "7"
	EndCase
	DefaultCase
		set $CompValue$ = "notexisting"
	EndCase
EndSwitch
if ($ConstTest$ = $CompValue$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif
----

.
[source,winst]
----
[Sub_check_exitcode]
comment "Test for installation success via exit code"
set $ExitCode$ = getLastExitCode
; informations to exit codes see
; http://msdn.microsoft.com/en-us/library/aa372835(VS.85).aspx
; http://msdn.microsoft.com/en-us/library/aa368542.aspx
Switch $ExitCode$
	Case "0"
		comment "Looks good: setup program gives exitcode zero"
	EndCase
	Case "1605"
		comment "ERROR_UNKNOWN_PRODUCT	1605"
		comment "This action is only valid for products that are currently installed."
		comment "Uninstall of a not installed product failed - no problem"
	EndCase
	Case "1641"
		comment "looks good: setup program gives exitcode 1641"
		comment "ERROR_SUCCESS_REBOOT_INITIATED	164"
		comment "The installer has initiated a restart."
		comment "This message is indicative of a success."
		ExitWindows /Reboot
	EndCase
	Case "3010"
		comment "looks good: setup program gives exitcode 3010"
		comment "ERROR_SUCCESS_REBOOT_REQUIRED	3010"
		comment "A restart is required to complete the install."
		comment "This message is indicative of a success."
		ExitWindows /Reboot
	EndCase
	DefaultCase
		logError "Fatal: Setup program gives an unknown exitcode unequal zero: " + $ExitCode$
		isFatalError "Exit Code: "+ $ExitCode$
	EndCase
EndSwitch
----

.Parameter for sections

* Using `ShellBatch`, `ShellInAnIcon`, `DosBatch`, `DosInAnIcon`, `ExecWith` +
you may now use as parameter not only string constants but also string variables (but no string functions).

Example:

Code from opsi-winst-test:
[source,winst]
----
comment "Testing parameters for ShellBatch"
set $ConstTest$ = "Hello world"
set $list$ = getOutStreamFromSection('DosInAnIcon_with_parameter world')
set $CompValue$ = takeString(2,$list$)
if ($ConstTest$ = $CompValue$)
	comment "ShellBatch parameter passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "ShellBatch parameter failed"
endif

comment "Testing parameters for ShellBatch"
set $ConstTest$ = "Hello world"
set $tmp$ = "world"
set $list$ = getOutStreamFromSection('DosInAnIcon_with_parameter $tmp$')
set $CompValue$ = takeString(2,$list$)
if ($ConstTest$ = $CompValue$)
	comment "ShellBatch parameter passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "ShellBatch parameter failed"
endif
----

produces the log:

[source,winst]
----
comment: Testing parameters for ShellBatch
Set  $ConstTest$ = "Hello world"
  The value of the variable "$ConstTest$" is now: "Hello world"
Set  $list$ = getOutStreamFromSection('DosInAnIcon_with_parameter world')

  DosInAnIcon_with_parameter
    c:\opsi.org\tmp\_opsiscript_Kj23Ej02.cmd saved back
    Executing "cmd.exe" /C c:\opsi.org\tmp\_opsiscript_Kj23Ej02.cmd world
    ExitCode 0

                output:
                --------------

                C:\Windows\system32>echo Hello world
                Hello world

    The file: c:\opsi.org\tmp\_opsiscript_Kj23Ej02.cmd has been deleted
    retrieving strings from getOutStreamFromSection [switch to loglevel 7 for debugging]
        (string   0)
        (string   1)C:\Windows\system32>echo Hello world
        (string   2)Hello world

Set  $CompValue$ = takeString(2,$list$)
    retrieving strings from $list$ [switch to loglevel 7 for debugging]
        (string   0)
        (string   1)C:\Windows\system32>echo Hello world
        (string   2)Hello world

  The value of the variable "$CompValue$" is now: "Hello world"
If
  $ConstTest$ = $CompValue$   <<< result true
  ($ConstTest$ = $CompValue$)   <<< result true
Then
  comment: ShellBatch parameter passed
Else
EndIf

comment: Testing parameters for ShellBatch
Set  $ConstTest$ = "Hello world"
  The value of the variable "$ConstTest$" is now: "Hello world"
Set  $tmp$ = "world"
  The value of the variable "$tmp$" is now: "world"
Set  $list$ = getOutStreamFromSection('DosInAnIcon_with_parameter $tmp$')

  DosInAnIcon_with_parameter
    c:\opsi.org\tmp\_opsiscript_Kz50Gi50.cmd saved back
    Executing "cmd.exe" /C c:\opsi.org\tmp\_opsiscript_Kz50Gi50.cmd world
    ExitCode 0

                output:
                --------------

                C:\Windows\system32>echo Hello world
                Hello world

    The file: c:\opsi.org\tmp\_opsiscript_Kz50Gi50.cmd has been deleted
    retrieving strings from getOutStreamFromSection [switch to loglevel 7 for debugging]
        (string   0)
        (string   1)C:\Windows\system32>echo Hello world
        (string   2)Hello world

Set  $CompValue$ = takeString(2,$list$)
    retrieving strings from $list$ [switch to loglevel 7 for debugging]
        (string   0)
        (string   1)C:\Windows\system32>echo Hello world
        (string   2)Hello world

  The value of the variable "$CompValue$" is now: "Hello world"
If
  $ConstTest$ = $CompValue$   <<< result true
  ($ConstTest$ = $CompValue$)   <<< result true
Then
  comment: ShellBatch parameter passed
Else
EndIf
----

.Functions and Statements

* `UpdateEnvironment` [W]: +
Sends Windows the signal to reload the environment values from the registry.
This statement may be called after any rocess that may have changed the environment (e.g. Registry section or setup program).
Even if the program that runs after the opsi-script get the new environment, +
next process that is started (via DosBatch or Winbatch) from this opsi-script +
instance will still inherit the old environment. +
To start a subsequent process with the new environment you have to use +
`winbatch` with the `/RunElevated` parameter. Works only with NT6 and up.

Example:
[source,winst]
----
comment "Set Environment Variables and check for it ...."
Registry_add_environment /sysnative
UpdateEnvironment

comment "This will not work because the environment is inherited from the running process"
set $list$ = shellCall('set opsi-script-test')

comment "This will work because this new started process will get a new environment"
winbatch_check_environment /RunElevated
if ("42" = getlastExitCode)
	comment "passed"
else
	comment "failed"
endif

[Registry_add_environment]
openkey [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment]
set "opsi-script-test"="deleteme"

[winbatch_check_environment]
"%system%\cmd.exe" /c "if %opsi-script-test%==deleteme exit 42"
----

* `sleepseconds` [W/L] +
As parameter for the count of seconds you may now use not only string constants but also string variables or string functions.

* `MaximizeWinst` [W/L] +
Sets the '{opsi-winst}/opsi-script' window to the 'maximized' mode

* The search path for `include_insert` and `include_append` is extended by `%ScriptPath%/../lib` and works in the same way now also for external `sub` -section files.  +

The searche rule is: +
<file name> may be:

* A complete path to an existing file. [W/L]

* A existing file in `%ScriptPath%` [W/L]

* A file in `%opsiScriptHelperPath%\lib` [W] +
Is equivalent to: '%ProgramFiles32Dir%\opsi.org\opsiScriptHelper\lib'

* A existing file in `%ScriptPath%/../lib` [W/L]

* A existing file in `%WinstDir%\lib` [W]

The tests for the location of the <file name> are done in the order above. '{opsi-winst}/opsi-script' uses the first file it finds that has a matching name.

* `getProductPropertyList(`<propname>,<default value>`)` +
Is available since 4.11.3 with <default value> as string expression. +
Since 4.11.5.6 `<default value>` may also be a string list expression.

* `LoadTextFileWithEncoding(` <file name> `,` <encoding>`)` [W/L] +
reads the file <file name> and generates the string list, that contains all lines of the file. The string will be reencoded from <encoding> to system encoding.

* `removeFromListByContaining(`<search string>`,` <target list>`)` [W/L] +
Returns a copy of <target list> where all lines that contains <search string> are removed. The match to <search string> is case insensitiv.

* `removeFromListByContaining(`<search list>`,` <target list>`)` [W/L] +
Returns a copy of <target list> where all lines are removed that contains a string out of <search list>. The match to <search list> is case insensitiv.

Examples:

File "%Scriptpath%\test-files\encoding\10lines.txt" is:
----
line 1
line 2
line 3
line 4
line 5
line 6
line 7
line 8
line 9
line 10
----

Code from opsi-winst-test:

[source,winst]
----
comment ""
comment "-------------------------------------"
comment "Testing: "
message "removeFromListByContaining"
set $string1$ = "%Scriptpath%\test-files\encoding\10lines.txt"
set $list1$ = loadTextFileWithEncoding($string1$, "cp1252")
comment "search with string"
comment "search with string constant"
set $ConstTest$ = "9"
set $list2$ = removeFromListByContaining("line 5", $list1$)
set $CompValue$ = count($list2$)
if ($ConstTest$ = $CompValue$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif

set $ConstTest$ = "9"
set $list2$ = removeFromListByContaining("LINE 5", $list1$)
comment "the match is case insensitive"
set $CompValue$ = count($list2$)
if ($ConstTest$ = $CompValue$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif


set $ConstTest$ = "0"
set $list2$ = removeFromListByContaining("line", $list1$)
set $CompValue$ = count($list2$)
if ($ConstTest$ = $CompValue$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif

set $ConstTest$ = "8"
comment "searchstr 1 will found in 'line 1' and 'line 10'"
set $list2$ = removeFromListByContaining("1", $list1$)
set $CompValue$ = count($list2$)
if ($ConstTest$ = $CompValue$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif

comment "search with string function"
set $ConstTest$ = "9"
set $list2$ = removeFromListByContaining(trim(" line 5 "), $list1$)
set $CompValue$ = count($list2$)
if ($ConstTest$ = $CompValue$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif

comment "search with string variable"
set $string1$ = "line 5"
set $ConstTest$ = "9"
set $list2$ = removeFromListByContaining($string1$, $list1$)
set $CompValue$ = count($list2$)
if ($ConstTest$ = $CompValue$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif

comment "search with string list"
comment "search with string list variable"
set $list3$ = createStringList ('1', '2', '3', '4', '5')
comment "searchstr 1 will found in 'line 1' and 'line 10'"
set $ConstTest$ = "4"
set $list2$ = removeFromListByContaining($list3$, $list1$)
set $CompValue$ = count($list2$)
if ($ConstTest$ = $CompValue$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif

comment "search with string list variable"
comment "searchstr 1 will found in 'line 1' and 'line 10'"
set $ConstTest$ = "4"
set $list2$ = removeFromListByContaining(createStringList ('1', '2', '3', '4', '5'), $list1$)
set $CompValue$ = count($list2$)
if ($ConstTest$ = $CompValue$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif
----

* String function `unquote2(<string>,<quote-string>)` [W/L] +
Acts like `unquote(<string>,<quote-string>)` with the following differences: +
If <quote-string> contains only one char, so this char will be used as 'start quote char' and 'end quote char'. If <quote-string> contains two chars, so the first char will be used as 'start quote char' and the second char as 'end quote char'. Example: a <quote-string> like "()" will unquote a string like '(hello)'. +
The function returns the unchanged <string> if not ('start quote char' AND 'end quote char') is found.

* Logging in the `silent_install` mode:
If `opsi-script / opsi-winst` is started from a `silent_install` event (e.g. to run inventory scripts in the background), so any logs produced in this case will be written to the opsi-server in the append mode.

* String function `GetShortWinPathName(<longpath string>)` [W] +
Returns the short path (8.3) from <longpath string>. If ther is no short path for <longpath string>, so you will get an empty string. +
Example: `GetShortWinPathName("C:\Program Files (x86)")` returns `"C:\PROGRA~2"`

* `GetConfidentialProductProperty (` <PropertyName>, <DefaultValue>`)` //since 4.11.5.2 +
like `GetProductProperty` but handles the resulting value as confidential string. +
Useful for getting passwords without logging. see also `SetConfidential`

* Boolean function `CompareDotSeparatedStrings(`<str1>,<relation str>,<str2>`)`  //since 4.11.5.2: [W/L] +
compares two strings of the form <str>[.<str>[.<str>[.<str>]]] +
by the <relation str> which may be one of [<,<=,=,>=,>]. +
see also: string function `CompareDotSeparatedStrings(`<string1>, <string2>`)`

* Boolean function `CompareDotSeparatedNumbers(`<str1>,<relation str>,<str2>`)`  //since 4.11.5.2: [W/L] +
compares two strings of the form <number>[.<number>[.<number>[.<number>]]] +
by the <relation str> which may be one of [<,<=,=,>=,>]. +
see also: string function `CompareDotSeparatedNumbers(`<string1>, <string2>`)`

Example: +
The code:
[source,winst]
----
set $string1$ = "1.2.30.4.5"
set $string2$ = "1.20.30.4.5"
if CompareDotSeparatedNumbers($string1$, "<", $string2$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif
if CompareDotSeparatedNumbers($string1$, "<=", $string2$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif
if CompareDotSeparatedNumbers($string1$, "=<", $string2$)
	comment "passed"
else
	set $TestResult$ = "not o.k."
	LogWarning "failed"
endif
if CompareDotSeparatedNumbers($string1$, "=", $string2$)
	set $TestResult$ = "not o.k."
	LogWarning "failed"
else
	comment "passed"
endif
if CompareDotSeparatedNumbers($string1$, ">=", $string2$)
	set $TestResult$ = "not o.k."
	LogWarning "failed"
else
	comment "passed"
endif
if CompareDotSeparatedNumbers($string1$, "=>", $string2$)
	set $TestResult$ = "not o.k."
	LogWarning "failed"
else
	comment "passed"
endif
if CompareDotSeparatedNumbers($string1$, ">", $string2$)
	set $TestResult$ = "not o.k."
	LogWarning "failed"
else
	comment "passed"
endif
----
produce the log:
[source,winst]
----
Set  $string1$ = "1.2.30.4.5"
  The value of the variable "$string1$" is now: "1.2.30.4.5"
Set  $string2$ = "1.20.30.4.5"
  The value of the variable "$string2$" is now: "1.20.30.4.5"
If
    Checking if "1.2.30.4.5" is "<" than / as "1.20.30.4.5"
  CompareDotSeparatedNumbers($string1$, "<", $string2$)   <<< result true
Then
  comment: passed
Else
EndIf
If
    Checking if "1.2.30.4.5" is "<=" than / as "1.20.30.4.5"
  CompareDotSeparatedNumbers($string1$, "<=", $string2$)   <<< result true
Then
  comment: passed
Else
EndIf
If
    Checking if "1.2.30.4.5" is "=<" than / as "1.20.30.4.5"
  CompareDotSeparatedNumbers($string1$, "=<", $string2$)   <<< result true
Then
  comment: passed
Else
EndIf
If
    Checking if "1.2.30.4.5" is "=" than / as "1.20.30.4.5"
  CompareDotSeparatedNumbers($string1$, "=", $string2$)   <<< result false
Then
Else
  comment: passed
EndIf
If
    Checking if "1.2.30.4.5" is ">=" than / as "1.20.30.4.5"
  CompareDotSeparatedNumbers($string1$, ">=", $string2$)   <<< result false
Then
Else
  comment: passed
EndIf
If
    Checking if "1.2.30.4.5" is "=>" than / as "1.20.30.4.5"
  CompareDotSeparatedNumbers($string1$, "=>", $string2$)   <<< result false
Then
Else
  comment: passed
EndIf
If
    Checking if "1.2.30.4.5" is ">" than / as "1.20.30.4.5"
  CompareDotSeparatedNumbers($string1$, ">", $string2$)   <<< result false
Then
Else
  comment: passed
EndIf
----



.opsi-Linux support:

* Winbatch sections are now also available at Linux.

* LinkFolder sections are now also available at Linux.. +
Possible BaseFolder are: `common_programs`,`common_autostart`,`desktop`, `autostart` +
Subfolder is always "" (empty).
The Link Option `icon_index` is ignored. +
As additional link option we have: `link_categories`. Here you may use the following values, separated and terminated by a semikolon: `AudioVideo`, `Audio`, `Video`, `Development`, `Education`, `Game`, `Graphics`, `Network`, `Office`, `Settings`, `System`, `Utility` +
The LinkFolder sections at Linux work with different desktop system (so they work according to the freedesktop.org standards).

* `shellCall` will now give the correct exit code of the called command. +
Technical background: The called command is extended by ` || exit $?` so that it give the exit code of the called command.

[[opsi-406-releasenotes-python-opsi]]
== python-opsi 4.0.6.

The Python-library used by opsi has received a lot of improvements and
bugfixes.

Functionality used by external scripts have been moved into python-opsi
to reduce maintenance efforts and make the functionality usable in other
applications.

This process has resulted in the following new modules:
`OPSI.Util.Task.Rights` allows setting the rights for opsi on files and
directories.
`OPSI.Util.Task.UpdateBackend.MySQL` can be used to update the MySQL
backend.
`OPSI.Util.Task.Samba` can be used to configure Samba for the use with
opsi.

The sourcecode of the new modules was improved in many place to be
future-proof and more efficent.

The function `OPSI.Types.forceList` is now able to work with tuples and
generators. Generators will be consumed during this.

Typechecks inside many methods have been reworked so that not only the
baseclasses `dict` and `list` but also their subclasses are recognized.

We improved error messages to be more helpful when creating new objects
through the commandline.

The module `OPSI.Util.Task.Certificate` now follows RFC5820 and increases
existing serial numbers for certificates. If no serial number is found
a random number will be generated. This avoids problems caused by equal
serial numbers.
This feature gets used e.g. when running `opsi-setup --renew-opsiconfd-cert`.

`OPSI.SharedAlgorithm` now does not rely on evaluating strings anymore
because this wasn't used by any official component.

Alongside this change the methods for defining the ordering of products
for installation have been overhauled. Creating a circular dependency
will result in an error being thrown in any method.
In addition to this a logentry will be created for every product
depedency that is contrary to any product priority and would lead to
unforseeable results.

Calling `backend_getSharedAlgorithm` will now result in throwing an
exception. It will be removed in future versions.

For easier log interpretation many objects now have improved representations.

The method `OPSI.System.Windows.mount` now accepts `dynamic` as a mount
target. This makes it possible to let the agent find a free mountpoint
for the depot share.
To use this feature you need to set the property
`clientconfig.depot.drive` of a client to `dynamic`. Adding the property
on the opsi configserver can be achieved by running
`opsi-setup --init-current-config`.
Thanks to Markus Kötter for the initial patch.

Driver integration now handles directories with names ending in an
underscore as if they were ending with a dot. This fixes problems
regarding filesystem limitations on Windows.
As an example if you'd be using the integration of drivers via byAudit
for computers of a company called `Dilbert Inc.` you now would name the
folder `Dilbert Inc_`.

The cleanup of backends through `OPSI.Util.Task.CleanupBackend` has
received speed improvements. Mass operations will be split into smaller
parts to avoid performance bottlenecks.

Communicating with the webservice currently leads to a HTTP header
"content-type" that does not match the real content encoding.
It now is possible to activate a RFC 2616 compatible behaviour by
creating the file `/etc/opsi/opsi.header.fix.enable` and restarting the
service. This makes it easier to communicate with the client through
third party applications.
Because this new beheviour may lead to communication failures with clients
expecting the old behaviour this is disabled by default.
The client components provided with this release have been updated so
that they can work with both.

The packaging has been overhauled to follow current recommendations and +
requirements of the various disitributions. Users or groups will not be +
created with an specific ID anymore to avoid conflicts with the IDs +
being already in use.


* opsi server parts: +

There are many improvements and bugfixes.

** The info page for the opsi server now collects information about the +
amount of methods called and their average running time.

** Changed logrotate configuration file `/etc/logrotate.d/opsiconfd`.
This file contains a new configuration regarding `/var/log/opsi/package.log`.
The package log was not limited in size before.

** In the MySQL backend all columns referencing the ID of a host are now
the same size of 255 characters. Newly created backend automatically
receive this size. Old backends have to be adjusted manually through
running `opsi-setup --update-mysql`.

** If the connection to the databse fails during initialisating of the
MySQL backend there will be a 5 seconds wait with an additional try to
connect to the database.

** The tools `opsi-product-updater`, `opsi-newprod` and
`opsi-package-manager` now use the same function to set the rights
to avoid inconsistent permissions.

** A patch provided by Antoine Guevara allows to use arbitrary subjects
for e-mails sended by `opsi-product-updater`.
The subject can be set through the attribute `subject` in the section
`notification` in `/etc/opsi/opsi-product-updater.conf`.

** The tool `opsi-admin` gained a new task: +
setActionRequestWhereOutdatedWithDependencies`
It has similar behaviour like `setActionRequestWhereOutdated` but also +
takes any depedencies into account. +
Thanks for Daniel Koch for providing the patch.

** Running `opsi-admin` in non-interactive mode now will return exitcodes +
other than 0 if any problems occured. +
To keep the previous behaviour where any action would result in an
exitcode 0 you must supply `--exit-zero` to the call.


[[opsi-406-releasenotes-netboot-windows]]
== opsi Support Matrix Windows Clients

The following section is an overview, on which Windows platforms opsi is running as a client.

include::../common/opsi_manual_supportmatrix-winclient.asciidoc[]



[[opsi-406-releasenotes-misc]]
== Miscellaneous


[[opsi-406-releasenotes-misc-changelogs]]
=== Changelogs:


[[opsi-406-releasenotes-misc-changelogs-opsi-configed]]
==== Changelog opsi-configed

opsi-configed (4.0.6.3.5.1-2) TESTING; urgency=medium

  * fixed bug when missing swaudit entries
  * fixed NPE because of missing filter condition initialization

-- roeder <roeder@uib.de>  Thu, 17 Sep 2015 10:07:04 +0200

opsi-configed (4.0.6.3.5-1) TESTING; urgency=medium

  * logpane improved: search starting with caretPosition
  * logpane improved: search strings saved in combobox
  * Software page with search functionality
  * Software page with option to exclude MS updates from shown software
  * licence statistics counting repaired

-- roeder <roeder@uib.de>  Mon, 31 Aug 2015 10:07:04 +0200

opsi-configed (4.0.6.0.8-1) EXPERIMENTAL; urgency=medium

  * WAN config by checkbox

-- sucher <a.sucher@uib.de>  Tue, 31 Mar 2015 12:43:35 +0200

opsi-configed (4.0.6.0.7-1) experimental; urgency=medium

  * in case of querysavedsearch we omit any console output
  * with depot properties editing, a depot selection is kept when changing product
  * fixed that the connection state was not correctly identified which led to errors in file backend

-- roeder <r.roeder@uib.de>  Fri, 27 Mar 2015 16:30:35 +0100

opsi-configed (4.0.6.0.5-1) experimental; urgency=medium

  * removed exception of ReachableUpdate when updating the model
  * fix: on host refresh, a host configs refresh is necessary
  * configed default logdir for windows move to localappdata dir
  * hostparameter editor leaked and reached window handle maximum, fixed by multiton pattern
  * on authentication password corection was not observed

-- roeder <r.roeder@uib.de>  Thu, 19 Mar 2015 16:25:46 +0100

[[opsi-406-releasenotes-misc-changelogs-opsi-client-agent]]
==== Changelog opsi-client-agent

opsi-client-agent (4.0.6.3-3) testing; urgency=low

  * Integrated emergency fix for opsiclientd_shutdown_starter.exe: ignore allow_reboot property

-- Detlef Oertel <d.oertel@uib.de>  Fri,  18 Sep 2015:15:00:00 +0200

opsi-client-agent (4.0.6.3-2) testing; urgency=low

  * Integrated emergency fix for opsiclientd_shutdown_starter.exe

-- Detlef Oertel <d.oertel@uib.de>  Thu, 17 Sep 2015 15:00:00 +0100

opsi-client-agent (4.0.6.3-1) testing; urgency=low

  * New version of opsiclientd_shutdown_starter.exe (4.0.85) (port from 4.0.5.7-2)
  * update to opsi-winst 4.11.5.14
  * setup.opsiscript: Set $INST_Debug$ = "off"

-- Detlef Oertel <d.oertel@uib.de>  Thu, 10 Sep 2015 15:00:00 +0100

opsi-client-agent (4.0.6.2-1) testing; urgency=low

  * Avoid having a cmd window popup on shutdown.
  * update to opsi-winst 4.11.5.13 (do 28.8.)
  * Using LoadProductProperties to get Productproperties after network connection (do 10.7.)
  * new property: setup_after_install (do 15.7.) fixes  #1613
  * update to openssl 1.0.2d
  * service_setup.cmd: better handling of /u ; fixes #503
  * 50_opsi-client-agent.cmd: log goes to c:\opsi.org\log

-- Niko Wenselowski <n.wenselowski@uib.de>  Fri, 10 Jul 2015 10:31:25 +0100

opsi-client-agent (4.0.6.1-2) experimental; UNRELEASED; urgency=low

  * fix in config.opsiscript: missing variable fo opsiclientd.conf
  * Update SSL DLLs from opsi-script to opsiclientd ; refrences #1491
  * integrate openssl to opsi-client-agent directory
  * no special uninstall for openssl anymore
  * No Environment vars for openssl
  * use http://indy.fulgan.com/SSL/ instead of shining light ssl
  * update to openssl 1.0.2c
  * Updated opsi-deploy-client-agent (niko)
  * OpsiLoginBlocker.dll logfile changes (loglevel first) (mm)
  * setup.opsiscript: changed Error message on copy failure
  * update to opsi-winst 4.11.5.6
  * *.opsiscript: for win10: change all '$INST_NTVersion$ < "6.0"' to CompareDotSeparatedNumbers
  * new property: depends_on_service : List of services that have to started before opsiclientd

-- Detlef Oertel <d.oertel@uib.de>  Tue, 17 Mar 2015 15:00:00 +0100

opsi-client-agent (4.0.6.1-1) experimental; urgency=low

  * openssl update to 1.0.1L  ; references #1027
  * Updated deployment script
  * scripts renamed from *.ins to *.opsiscript
  * scripts: c:\tmp replaced by %opsiTmpDir% or %opsiLogDir%
  * scripts: ALLUSERS=2 replaced by ALLUSERS=1
  * update to opsi-winst 4.11.5.1 (do)
  * cleanup unused files
  * get hostname from %pcname% ; references #1369
  * make silent_setup.cmd complete unattend ; references #503
  * icon for softwareOnDemand ; references #936
  * support for multiple clientconfig.configserver.url ; patch from <boris.synak@zobelsoft.de> ; references #1237
  * set also opsi-winst to installed ; references #1329
  * new update script files\opsi\config.opsiscript / subconfig.opsiscript for activate event_on_shutdown and LinkFolder_install_softwareOnDemand ; references #1329
  * associate *.opsiscript files with winst32.exe ; references #1045
  * start "%ScriptPath%\custom\custom.opsiscript" after sub_write_configuration ; references #458
  * uninstall: fixes for on_shutdown registry keys
  * postinst: for backward compatibiliy: create a setup.ins as hard link

-- Detlef Oertel <d.oertel@uib.de>  Mon, 26 Jan 2015 15:00:00 +0100

[[opsi-406-releasenotes-misc-changelogs-config-win10]]
config-win10 (4.0.6-4) experimental; urgency=low

  * Added new property to change windows update behavior

 -- m.radtke <m.radtke@uib.de> Tue, 15 Sep 2015 14:33:00 + 0200

config-win10 (4.0.6-3) experimental; urgency=low

  * diverged disable_telemetry into more properties

 -- m.radtke <m.radtke@uib.de> Fri, 11 Sep 2015 15:31:00 + 0200

config-win10 (4.0.6-2) experimental; urgency=low

  * all reg entries change values
  * removed disable_charms property

 -- m.radtke <m.radtke@uib.de> Fri, 11 Sep 2015 11:10:00 + 0200

config-win10 (4.0.6-1) experimental; urgency=low

  * added all known windows 10 telemetry registry keys

 -- m.radtke <m.radtke@uib.de> Thu, 10 Sep 2015 17:06:00 + 0200

[[opsi-406-releasenotes-misc-changelogs-opsi-script]]
==== Changelog opsi-script / opsi-winst

opsi-winst/opsi-script (4.11.5.14) stable; urgency=low

  * oswebservice: assume opsiservice version=4 in retrieveJSON*
    to avoid access to opsidata which fails if we use local_opsidata
    fixes Access Violations in initial opsi-client-agent installation
  * osfunc: FuncSaveToFile / SaveToFile: logging content on Loglevel 9 ; references #1679
  * osfuncwin: fix broken Shellbatch /showoutput

-- Detlef Oertel <d.oertel@uib.de>  Thu,  10 Sep 2015:15:00:00 +0200

opsi-winst/opsi-script (4.11.5.13) stable; urgency=low

  * do not try to run non existing external sub sections

-- Detlef Oertel <d.oertel@uib.de>  Thu,  21 Aug 2015:15:00:00 +0200

opsi-winst/opsi-script (4.11.5.12) stable; urgency=low

  * Bugfix: osparser: doAktionen: fullfilename not initialized:
    causes causes double load of include or sub if searched file is not existing ; fixes #1656
  * Bugfix: osparser: Filexists*: do not check for existing file with dir/ls if trim(filename)=''
    fixes: https://forum.opsi.org/viewtopic.php?f=6&t=7697
    (FileExists auf leere Variable gibt wahr zurück)

-- Detlef Oertel <d.oertel@uib.de>  Thu,  20 Aug 2015:15:00:00 +0200

opsi-winst/opsi-script (4.11.5.11) stable; urgency=low

  * Bugfix: (FileExist call) changes (GetLastExitCode Result Value):
    (because it call execshellCall to detect symlinks correctly):
    osparser: new parameter for execshellCall: FetchExitCodePublic
    if false result is on FLastPrivateExitCode
    if false true is on FLastExitCodeOfExe (GetLastExitCode)

-- Detlef Oertel <d.oertel@uib.de>  Thu,  13 Aug 2015:15:00:00 +0200


opsi-winst/opsi-script (4.11.5.10) stable; urgency=low

  * oswebservice: retreiveJSONObject
     * start with (new) correct Mimetype and AcceptEncoding
       and fall back to old (wrong) parameters
  * osfunc: FileCopyWin: more log on file in use
  * osfunc: FileCopyWin: fix for Err 32 on setTimeForFile
  * osfunc: TuibRegistry.Create(myforce64: boolean; readonly: boolean);
  * osparser: GetRegistrystringvalue* works now with readonly registry ; fixes #1647
  * osmain: BuildPC: speed up: only ask for changed action request if there was one (uib#2015080710000015)

-- Detlef Oertel <d.oertel@uib.de>  Tue,  21 Jul 2015:15:00:00 +0200

opsi-winst/opsi-script (4.11.5.9) stable; urgency=low

  * osmain: initproduct before run update script: refresh getProductMap
  * osmain: but still use setup as lastaction even if was setup+update
  * oswebservice: new procedure TOpsi4Data.setActualProductActionRequest

-- Detlef Oertel <d.oertel@uib.de>  Fri,  17 Jul 2015:15:00:00 +0200

opsi-winst/opsi-script (4.11.5.8) stable; urgency=low

  * new statement LoadProductProperties <clientId> <productId> (re-loads productproperty list from Server if possible)
  * GetProductpropertyList: do not try to use also local_opsidata or opsidata
  * GetProductproperty: do not try to use also local_opsidata or opsidata

-- Detlef Oertel <d.oertel@uib.de>  Thu,  09 Jul 2015:15:00:00 +0200

opsi-winst/opsi-script (4.11.5.7) stable; urgency=low

  * GetProductproperty: try / except added

-- Detlef Oertel <d.oertel@uib.de>  Tue,  07 Jul 2015:15:00:00 +0200


opsi-winst/opsi-script (4.11.5.6) stable; urgency=low

  * GetProductpropertyList: also with list as second (default) parameter ; fixes #1602
  * GetProductpropertyList: try to use also local_opsidata, log using default
  * GetProductproperty: if empty try to use also local_opsidata or opsidata, log using default

-- Detlef Oertel <d.oertel@uib.de>  Thu,  02 Jul 2015:15:00:00 +0200


opsi-winst/opsi-script (4.11.5.5) stable; urgency=low

  * upgrade to ssl Libraries 1.0.2c (libeay32.dll, ssleay32.dll); fixes #1586
  * osfuncwin2: updateEnvironment: do not try to run updateEnvironment on windows < 6; fixes #1591
  * osmain: BuildPC: process product only if we have a original action request wich is still set

-- Detlef Oertel <d.oertel@uib.de>  Thu,  25 Jun 2015:15:00:00 +0200


opsi-winst/opsi-script (4.11.5.4) stable; urgency=low

  * Working with ssl protocol: sslvSSLv23 - auto negotation

-- Detlef Oertel <d.oertel@uib.de>  Tue,  02 Jun 2015:15:00:00 +0200


opsi-winst/opsi-script (4.11.5.3) stable; urgency=low

  * (Security Update) oswebservice: use TLS1.2 instead of SSLv3 and fallback downto SSLv3

-- Detlef Oertel <d.oertel@uib.de>  Mon,  01 Jun 2015:15:00:00 +0200


opsi-winst/opsi-script (4.11.5.2) stable; urgency=low

  * upgrade to ssl Libraries 1.0.2a (libeay32.dll, ssleay32.dll)
  * files commands move / rename / hardlink / symlink now work with overwrite; fixes #1435
  * if move / rename fails (file is in use) we retry it with MOVEFILE_DELAY_UNTIL_REBOOT
    So the move will be done at the next reboot. Reboot will be set automatically if not Option -c is set.
  * file command del / delete now with option -c and retry to delete on next boot if file in use ; fixes # 788
  * osfunc: new function opsiunquotestr2
  * new string function unquote2(s1,s2): like unquote but:
        removes only quotes if they found at start and end
        s2 may be two chars long. Then the first char is the start mark
        and the second char is the end mark
  * osparser: GetString: new boolean switch requote
  * osparser: GetString requote=true: change double quoted (""str"") to alternative double quoted ('""');  references #1284
  * new string function: GetShortWinPathName(longpath) ; fixes #581
        Windows only
        Gives short path (8.3) from a long path e.g.
        GetShortWinPathName("C:\Program Files (x86)") gives "C:\PROGRA~2"
        In case of Error the result is an empty string
  * osfunc: startprocess_cp: translate windows showWindowFlag to TProcess TShowWindowOptions
  * osparser: doRegistryHack* : fix for not HKCU reg enties in loginscripts; fixes #1538
  * oswebservice: more log for "unexpected Result from webservice in retrieveJSONObject, number of lines: 0"
  * new string function: GetConfidentialProductProperty : like GetProductProperty but handles the result as confidential string ; fixes #462
  * fixes at GetNTVersion for Win10
  * new boolean function CompareDotSeparatedNumbers(<str1>,<relation str>,<str2>)
        <relation str> may be: one of [<,<=,=,>=,>]
  * new boolean function CompareDotSeparatedStrings(<str1>,<relation str>,<str2>)
        <relation str> may be: one of [<,<=,=,>=,>]
  * hide non visible processes (SW_HIDE) like winbatch or shellInAnIcon
  * (Security Update) oswebservice: use TLS1.2 instead of SSLv3

-- Detlef Oertel <d.oertel@uib.de>  Wed,  01 Apr 2015:15:00:00 +0200


opsi-winst/opsi-script (4.11.5.1) stable; urgency=low

  * osparser: commandline := 'cmd64.exe /c "reg delete ""'+key_completepath+'"" /f'; (fixes #1299)
  * port of the changes since 4.11.4.6 to Linux
  * osparser: New files commands hardlink, symlink, rename, move
  * osfunc: new tuibinstall methods: hardlink, symlink, rename (Linux / Windows ; fixes #1319, #362)
  * osparser: execDosBatch: The path to temporary file is only quoted if it contains spaces
  * osparser: execDosBatch: Variables are now allowed as Parameters (but no functions) fixes #1312
  * osparser: executeWith: Variables are now allowed as Parameters (but no functions)
  * osparser: doAktionen: Variables and functions are now allowed as sleepsecond Parameters; fixes #1193
  * osparser: %SriptPath%/../lib as additional Path in Search path for includes; fixes #1201
  * osparser: searchpath for includes are now works also for sub <file> ; fixes #1201
  * New loop statement: for %s% = $start$ to $stop$ do <statement> ;  references #407
      - $start$ and $stop$ has to be integer strings
      - $start$ < $stop$ is required
      - in fact a stringlist $start$ to $stop$ is generated over which we iterate while loop
  * osparser: tsLoopForTo  for %s% = $start$ to $stop$ do <statement>
  * osparser: activating winbatch for linux ; fixes #1170
  * replacing opsi-winst constants by opsi-script
  * osparser: produceStringList: New (overloaded) stringlist function (references #1110):
              - removeFromListByContaining(<search string>, <target list>) removes  <search string> from <target list>
              - removeFromListByContaining(<search list>, <target list>) removes  <search list> from <target list>
              - both functions search case insensitive for a matching substring
  * ospparser: fix for filexists* to detect symlinks
  * upgrade to ssl Libraries 1.0.1L (libeay32.dll, ssleay32.dll)
  * osmain: GetParameter + StartProgramModes: more try - except : port from 4.11.4.16
  * osparser: doOpsiServiceCall: more try - except : port from 4.11.4.16
  * osparser: doTextPatchMain: do not use CheckFileExists in SaveToFile ; references #171
  * HowToBuild.txt ; fixes #1372
  * oswebservice: finishOpsiConf: if runproductlist then Logg-Appendmode := true; references #1379
  * new Statement: UpdateEnvironment : Triggers Windows to reload Environment from Registry; Win only; references #1364
  * new Control Statement: Switch  ; references  #740
    - osparser: Switch <string expr ; normally variable>
                  Case <string expr; normally const>
                    statments
                  EndCase
                  [Defaultcase
                    statments
                  EndCase]
                EndSwitch
  * LinkFolder for Linux activated: No BaseFolder, No SubFolder, No Iconindex
      but link_categories: 'AudioVideo',
      'Audio', 'Video', 'Development', 'Education', 'Game', 'Graphics',  'Network',
      'Office', 'Settings', 'System', 'Utility'
      // from http://standards.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry
      changes in osparser, osfunclin and new unit oslindesktop
  * some more ExpandFilename calls to handle incorrect path delimiter
  * oswebservice: sendlog: replace old writeLog by new log_write method
  * New Statement: MaximizeWinst at osparser
  * Erweiterte Stinglisten Funktion `getProductPropertyList(`<propname>,<default value>`)` mit `<default value>` als String oder Stringliste.
  * New Functions LoadTextFileWithEncoding(file,encoding) strLoadTextFileWithEncoding(file,encoding) at osparser
  * osencoding: LoadFromFileWithEncoding
  * oswebservice: sendlog: at Linux do not convert logstrings to uft8
  * oslog: dependentadd: more try except
  * osparser: sleepseconds (tsSleep): more try except and more logging
  * osparser: winbatch: trim targetfilename
  * osparser: shellBatch: Parameter at Linux (wrong bash parameter)
  * osmain: User Profile Management (runloginscripts) is now free
  * osmain: do not switch opsi-script to setup (even if it is opsi-winst); references # 1437

-- Detlef Oertel <d.oertel@uib.de>  Thu,  22 Dec 2014:15:00:00 +0200

opsi-winst/opsi-script (4.11.4.14) stable; urgency=low

  * less (only 512 chars) debug output: oswebservice: retrieveJSONObject: log ResultLines.Strings[0] if Result = nil
  * oswebservice: retrieveJSONObject: FillChar(buffer^, 655360,' '); before read to buffer
  * manifest extended for win 10: <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>

-- Detlef Oertel <d.oertel@uib.de>  Thu,  04 Dec 2014:15:00:00 +0200


opsi-winst/opsi-script (4.11.4.13) stable; urgency=low

  * more debug output: oswebservice: retrieveJSONObject: log ResultLines.Strings[0] if Result = nil

-- Detlef Oertel <d.oertel@uib.de>  Wed,  12 Nov 2014:15:00:00 +0200


opsi-winst/opsi-script (4.11.4.12) stable; urgency=low

  * fix: osmain: StartProgramModes: correct Path to the opsiclientd.conf in batch mode
  * Logdevel while writing log to Service decreased
  * fix: command typo: ErrorsOccuredSinceMark is wrong, now also allowed: ErrorsOccurredSinceMark  fixes #1121
  * bakup files of log now are opsi-script.log.x where x is 0 - 8
  * do not run login scripts if user is 'opsisetupadmin' fixes #1248

-- Detlef Oertel <d.oertel@uib.de>  Fri,  24 Oct 2014:15:00:00 +0200


opsi-winst/opsi-script (4.11.4.11) stable; urgency=low

  * new unit: SystemCriticalU
  * osmain: in StartprogramModes set SystemCritical.IsCritical := true;
  * osmain: in BuildPC set SystemCritical.IsCritical := true;
  * osmain: in Terminateapp set SystemCritical.IsCritical := false;
  * osmain: in different execept set SystemCritical.IsCritical := false;

-- Detlef Oertel <d.oertel@uib.de>  Wed,  09 Oct 2014:15:00:00 +0200

[[opsi-406-releasenotes-misc-changelogs-windomain]]
==== Changelog windomain

windomain (1.0-8) stable; urgency=low

	* win 10 compatibiliy

 -- detlef oertel <d.oertel@uib.de>  Fri,  28 Aug 2015 17:00:00 +0200

windomain (1.0-7) stable; urgency=low

	* Setting priority to 20 for an earlier execution.

 -- Niko Wenselowski <d.oertel@uib.de>  Tue,  20 Dec 2013 17:00:13 +0200

[[opsi-406-releasenotes-misc-changelogs-opsiuefinetboot]]
==== Changelog opsi-uefi-netboot

opsi-uefi-netboot (4.0.5-3) stable; urgency=low

	* added always action request (with no reboot) ; idea / patch by M. Salm <M.Salm@lmz-bw.de> 11.03.2015

-- detlef oertel <d.oertel@uib.de>  Thu, 09 Apr 2015 15:00:00 +0200

[[opsi-406-releasenotes-misc-changelogs-opsitemplatewithadmin]]
==== Changelog opsi-template-with-admin

opsi-template-with-admin (4.0.6-1) stable; urgency=low

	* extended rebootflag ; fixes #1652
	* changed *.ins to *.opsiscript
	* ScriptErrorMessages=off

-- detlef oertel <d.oertel@uib.de>  Wed, 02 Sep 2015 15:00:00 +0200

[[opsi-406-releasenotes-misc-changelogs-opsi-setup-detector]]
==== Changelog opsi-setup-detector

opsi-setup-detector (4.0.5.131-1) testing; urgency=low

 * InstallDir = %ProgramFilesDir%\opsi.org\
 * requiredWinstVersion >= "4.11.4.3"
 * msiexec option /qb-!
 * InstallShield detection less sharp
 * fixes redmine #1107 - manual packetBaseDir accepted
 * fixes redmine #1303 - %opsiLogDir% (opsi.org\log\opsiSetupDetector.log)

 -- Miriam Michaelis <m.michaelis@uib.de> Mon, 21 Sep 2015 10:35:00 +0100

[[opsi-406-releasenotes-misc-changelogs-windows-netboot]]
==== Changelog windows netboot products

windows (4.0.6.1-2) stable; urgency=low

  * new unattend.xml for win10
  * preinst: delete unchanged unattend.xml from custom
  * show_drivers now offers --help and --version (nw 10.9.)

-- Detlef Oertel <d.oertel@uib.de>  Tue,  10 Sep 2015:15:00:00 +0200

windows (4.0.6.1-1) stable; urgency=low

  * change imagename values and defaults
  * update opsisetuplib.py
  * nt6.py: hw-inventory use createObjects # fixes #1540
  * nt6.py: check for bootmgr.* now case insensitive
  * 99_cleanup.cmd : switch for 32/64 Bit ; fixes #1488

-- Detlef Oertel <d.oertel@uib.de>  Tue,  04 Aug 2015:15:00:00 +0200

[[opsi-406-releasenotes-misc-changelogs-linux-netboot]]
==== Changelog linux netboot products

.centos70

centos70_4.0.6.2-1 stable; urgency=low

  * changes for nfs mount

-- Detlef Oertel <d.oertel@uib.de>  Wed,  26 Mar 2015:15:00:00 +0200

centos70_4.0.6-1 stable; urgency=low

  * ported from centos70_7.0-1 and sles12

-- Detlef Oertel <d.oertel@uib.de>  Tue,  27 Jan 2015:15:00:00 +0200


centos70_7.0-1 stable; urgency=low

  * ported from centos65_6.5-3 and Fedora20
  * removed property online_repository
  * network configuration with predictable network interface names (may fail on rule 2 (ESXi clients)
  * install net-tools
  * hpsa support

-- Detlef Oertel <d.oertel@uib.de>  Wed,  27 Aug 2014:15:00:00 +0200

.debian7

debian7-4.0.6-1 stable; urgency=low

  * initial derivated from debian-4.0.5-6 and sles12

-- Detlef Oertel <d.oertel@uib.de>  Mon, 12 Jan 2015:15:00:00 +0200

.debian8

debian8-4.0.6-1 stable; urgency=low

  * initial derivated from debian7-4.0.6-1

-- Detlef Oertel <d.oertel@uib.de>  Mon, 26 Jan 2015:15:00:00 +0200

.opensuse13-2

opensuse13-2_4.0.6.2-2  stable; urgency=low

  * changes for 4.0.6 bootimage (>= 20150707):
    * property for network interface name ignored
    * no kexec copy

-- Detlef Oertel <d.oertel@uib.de>  Mon,  13 Jul 2015:15:00:00 +0200

opensuse13-2_4.0.6.2-1  stable; urgency=low

  * changes for nfs mount
  * temporary property for network interface name

-- Detlef Oertel <d.oertel@uib.de>  Wed,  26 Mar 2015:15:00:00 +0200

opensuse13-2_4.0.6-1  stable; urgency=low

  * initial

-- Detlef Oertel <d.oertel@uib.de>  Mon,  09 Feb 2015:15:00:00 +0200

.sles12

sles12_4.0.6.2-2 testing; urgency=low

  * more changes for nfs mount: clientconfig.opsi_nfs_share
  * temporary property for network interface name

-- Detlef Oertel <d.oertel@uib.de>  Tue,  28 Apr 2015:15:00:00 +0200


sles12_4.0.6.2-1 testing; urgency=low

  * changes for nfs mount

-- Detlef Oertel <d.oertel@uib.de>  Wed,  26 Mar 2015:15:00:00 +0200


sles12_4.0.6.1-2 testing; urgency=low

  * changes for opsi-linux-client-agent 4.0.6

-- Detlef Oertel <d.oertel@uib.de>  Wed,  04 Mar 2015:15:00:00 +0200

.redhat70

redhat70_4.0.6.2-1 stable; urgency=low

  * ported from centos70_4.0.6.2-1

-- Detlef Oertel <d.oertel@uib.de>  Mon,  27 Apr 2015:15:00:00 +0200

.Ubuntu14-04

Ubuntu14-04_4.0.6-2 stable; urgency=low

  * changes for 4.0.6 bootimage (>= 20150707):
    * no kexec copy

-- Detlef Oertel <d.oertel@uib.de>  Tue, 14 Jul 2015:15:00:00 +0200


Ubuntu14-04_4.0.6-1 stable; urgency=low

  * initial derivated from debian7_4.0.6-1

-- Detlef Oertel <d.oertel@uib.de>  Mon, 26 Jan 2015:15:00:00 +0200

.Ubuntu15-04

Ubuntu15-04_4.0.6-2 stable; urgency=low

  * initial derivated from Ubuntu14-04_4.0.6-2

-- Detlef Oertel <d.oertel@uib.de>  Tue, 14 Jul 2015:15:00:00 +0200

[[opsi-406-releasenotes-misc-changelogs-opsi-local-image]]
==== Changelog opsi-local-image

opsi-local-image-capture (4.0.6.1-2) stable; urgency=low

	* set empty image_description to "no description given"
	* new opsi-winst versions (32/64) 4.11.5.14 (do 10.9.)
	* update ssl Libraries (32/64)
	* getmsversion fix for win10
	* check for exitance of c:\tmp and c:\drv before remove ; fixes #1668
	* run chkdsk for drive to capture before capture
	* new property opsi_depot_rw_host: If not empty: the host from which we mount the opsi_depot_rw share.

-- detlef oertel <d.oertel@uib.de>  Wed, 02 Sep 2015 15:00:00 +0200

opsi-local-image-capture (4.0.6.1-1) stable; urgency=low

	* link opsisetuplib.py from os-products
	* update opsisetuplib.py

-- detlef oertel <d.oertel@uib.de>  Tue, 04 Aug 2015 15:00:00 +0200


windows (4.0.6.1-2) stable; urgency=low

  * new unattend.xml for win10
  * preinst: delete unchanged unattend.xml from custom
  * show_drivers now offers --help and --version (nw 10.9.)

-- Detlef Oertel <d.oertel@uib.de>  Tue,  10 Sep 2015:15:00:00 +0200

opsi-local-image-win* (4.0.6.1-1) stable; urgency=low

  * change imagename values and defaults
  * update opsisetuplib.py
  * 99_cleanup.cmd : switch for 32/64 Bit ; fixes #1488

-- Detlef Oertel <d.oertel@uib.de>  Tue,  04 Aug 2015:15:00:00 +0200


[[opsi-406-releasenotes-misc-changelogs-misc-netboot]]
==== Changelog misc netboot products


opsi-clonezilla (4.0.6-1) stable; urgency=low

  * 4.0.6 bootimage support
  * clonezilla-3.10.11
  * partclone-0.2.69
  * postinst cleared

-- detlef oertel <d.oertel@uib.de>  Fri, 24 Jul 2015 16:01:53 +0200


memtest86 (5.01-1) stable; urgency=low

  * extracted http://www.memtest.org/download/5.01/memtest86+-5.01.zip
  * extension .bin has to be removed
  * see: http://www.gtkdb.de/index_7_2379.html

-- Detlef Oertel <d.oertel@uib.de>  Tue,  11 Aug 2015:15:00:00 +0200

[[opsi-406-releasenotes-misc-changelogs-python-opsi]]
==== Changelog python-opsi

python-opsi (4.0.6.23-1) experimental; urgency=medium

  * Copy the following methods to 30_configed.conf: getDomain,
    getOpsiHWAuditConf, getPossibleMethods_listOfHashes, getServerIds_list
  * OPSI.Backend.Backend: Reading the default maximum logfile size from
    /etc/opsi/opsiconfd.conf.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Wed, 16 Sep 2015 11:59:33 +0200

python-opsi (4.0.6.22-1) experimental; urgency=medium

  * log_read: Removed append-feature for rotated logs.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Tue, 15 Sep 2015 14:23:46 +0200

python-opsi (4.0.6.21-1) experimental; urgency=medium

  * ExtendedConfigBackend: repr now works also with subclasses.
  * ConfigDataBackend: log_write does correctly limit the logsize.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Tue, 15 Sep 2015 12:38:36 +0200

python-opsi (4.0.6.20-1) experimental; urgency=medium

  * OPSI.Service.Worker: header parsing errors are now logged
    with loglevel 8.
  * Re-introduce 30_configed.conf

 -- Niko Wenselowski <n.wenselowski@uib.de>  Wed, 09 Sep 2015 09:15:14 +0200

python-opsi (4.0.6.19-2) experimental; urgency=medium

  * Translations updated and translations for es, it & ru added.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Thu, 03 Sep 2015 11:04:01 +0200

python-opsi (4.0.6.19-1) experimental; urgency=medium

  * OPSI.Backend.JSONRPC: refuse to enable deflate if we are talking to an
    old version of the service to avoid problems.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Thu, 03 Sep 2015 10:30:30 +0200

python-opsi (4.0.6.18-1) experimental; urgency=medium

  * OPSI.Backend.BackendManager: showing the used ACL only on log level debug
    or higher.
  * OPSI.SharedAlgorithm: small refactorings regarding iteration of lists
  * OPSI.Backend.JSONRPC: more reliable fix for working with deflate against
    older webservice versions. This works by disabling deflate to ensure
    proper encoding / decoding.
  * OPSI.Backend.JSONRPC: type check via isinstance instead of type.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Wed, 02 Sep 2015 16:34:26 +0200

python-opsi (4.0.6.17-1) experimental; urgency=medium

  * removed cpatureStderr=False fom execute of 'lsb-release -i' command

 -- Mathias Radtke <m.radtke@uib.de>  Wed, 02 Sep 2015 11:54:51 +0200

python-opsi (4.0.6.16-1) experimental; urgency=medium

  * OPSI.Backend.BackendManager: redirected lsb_release stderr and stdout output to /dev/null

 -- Mathias Radtke <m.radtke@uib.de>  Wed, 02 Sep 2015 09:33:16 +0200

python-opsi (4.0.6.15-1) experimental; urgency=medium

  * OPSI.Util.Task.Samba: add newline when adding repository.
  * RPM: Made the license machine-parseable.
  * OPSI.Util.WindowsDrivers: do not fail if Vendor or Model are None.
  * Create user / groups without explicit uid / gid.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Tue, 25 Aug 2015 11:02:44 +0200

python-opsi (4.0.6.14-1) experimental; urgency=medium

  [ Mathias Radtke ]
  * OPSI.System.Posix: removed unneded captureStderr flag

  [ Anna Sucher ]
  * OPSI.Util.Task.Rights: added opsi-deploy-client-agent-default to
    files that are made executable

  [ Niko Wenselowski ]
  * JSONRPCBackend: Better handling of JSON-RPC-response from an old service.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Tue, 11 Aug 2015 15:27:10 +0200

python-opsi (4.0.6.13-1) experimental; urgency=medium

  * Provide OPSI.System.Posix.shutdown.
  * Added function OPSI.Util.chunk.
  * OPSI.Util.Task.CleanupBackend: added chunking on mass-operations.
  * OPSI.Util.Task.CleanupBackend: Improving speed of operations.
  * OPSI.Backend.Replicator: Speed up membership test for productsOnDepot.
  * OPSI.System.Posix.execute now accepts list, set or tuple for ignoreExitCode
  * Debian: Remove dependency on python-support.
  * OPSI.System.Posix: removed unneded captureStderr flags from sfdisk calls

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 10 Aug 2015 15:22:38 +0200

python-opsi (4.0.6.12-1) experimental; urgency=medium

  [ Niko Wenselowski ]
  * Improving Python 3 compatibility.
  * hwaudit: Added translations for COMPUTER_SYSTEM.sku
  * tests: rename the domain of test objects from uib.local to test.invalid
  * OPSI.Service.Worker.WorkerOpsiJsonRpc: The header handling introduced
    with 4.0.6.8-1 must now be explicitely enabled by creating the file:
    /etc/opsi/opsi.header.fix.enable
    This makes sure that components get the same behaviour as before unless
    an change is done by an administrator.
  * 10_opsi.conf: Reintroduce setRights from the now remove 30_configed.conf
  * OPSI.Util.HTTP: the functions to decode/encode gzip/deflate now work
    better with unicode input and always return unicode.
  * OPSI.Service.Worker.WorkerOpsi: properly decode requests that have their
    content-encoding header set to "deflate".
  * log_read now also reads rotated logs.
  * OPSI.Util.Task.Rights: chown now correctly sets uid/gid on links.

  [ Mathias Radtke ]
  * new module OPSI Util task Samba
  * wrote tests for new module

 -- Niko Wenselowski <n.wenselowski@uib.de>  Wed, 29 Jul 2015 16:04:38 +0200

python-opsi (4.0.6.11-4) experimental; urgency=medium

  * Packaging fixes for Debian 8.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 29 Jun 2015 16:23:22 +0200

python-opsi (4.0.6.11-3) experimental; urgency=medium

  * RPM: do not link removed file.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 29 Jun 2015 16:11:06 +0200

python-opsi (4.0.6.11-2) experimental; urgency=medium

  * Removing remaining occurances of 30_configed.conf.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 29 Jun 2015 16:06:51 +0200

python-opsi (4.0.6.11-1) experimental; urgency=medium

  * Debian: Moving lintian-overrides into debian/source
  * 20_legacy.conf: Small refactoring of getClients_listOfHashes
  * 20_legacy.conf: Refactored getLicenseStatistics_hash
  * OPSI.Types: better error message if forceObjectClass fails because of an
    argument that is missing for the constructor
  * OPSI.Types: better error message if forceObjectClass fails because of an
    invalid type
  * 20_legacy.conf: some small bugfixes.
  * OPSI.Object: repr for ConfigState now includes values.
  * Moving getProductOrdering from 30_configed.conf to 10_opsi.conf.
  * Removing 30_configed.conf.
  * Removing the link from etc/opsi/backendManager/extend.d/20_legacy.conf to
    etc/opsi/backendManager/extend.d/configed/20_legacy.conf.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 29 Jun 2015 15:58:47 +0200

python-opsi (4.0.6.10-3) experimental; urgency=medium

  * Debian: Setting the package format to 1.0
  * RPM: creating folder for systemd templates before installation

 -- Niko Wenselowski <n.wenselowski@uib.de>  Tue, 16 Jun 2015 12:27:05 +0200

python-opsi (4.0.6.10-2) experimental; urgency=medium

  * RPM: supply %prep and %debug_package
  * Remove references to opsi-distutils

 -- Niko Wenselowski <n.wenselowski@uib.de>  Tue, 16 Jun 2015 10:57:43 +0200

python-opsi (4.0.6.10-1) experimental; urgency=medium

  * Added __repr__ for Backend and JSONRPCBackend.
  * OPSI.Backend.Replicator: Inserting objects should be a little faster.
  * OPSI.Backend: Only do a lookup for returnObjectsOnUpdateAndCreate once
    per method execution.
  * objectToBash, objectToHtml and objectToBeautifiedText now also correctly
    format subclasses of the lists / dicts.
  * 20_legacy.conf: Speed up _getProductStates_hash
  * FileBackend: Do not double the mapping list of LocalbootProduct and NetbootProduct.
  * FileBackend: allow products having ProductPropertyStates that are the same as the id of a product.
  * Some small refactorings to OPSI.Backend.SQL and OPSI.Backend.MySQL.
  * Supply new folder /etc/opsi/systemdTemplates

 -- Niko Wenselowski <n.wenselowski@uib.de>  Tue, 16 Jun 2015 10:45:21 +0200

python-opsi (4.0.6.9-1) experimental; urgency=medium

  * OPSI.Util.Task.Rights: reuse an existing depot URL if we found one before.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Wed, 10 Jun 2015 10:20:56 +0200

python-opsi (4.0.6.8-1) experimental; urgency=low

  * 20_legacy.conf: createLicenseContract now returns the complete
    license contract id instead of just the first character.
  * OPSI.Util.File: Avoid bloating dhcpd.conf with '%s'
  * OPSI.Util.Task.Rights: added 'service_setup.sh' to KNOWN_EXECUTABLES
  * OPSI.Util.Task.Rights: Fix setting rights on KNOWN_EXECUTABLES in
    the depot folder.
  * Refactored worker for the interface page.
  * OPSI.Backend.File: Convert errors to unicode before logging them.
  * 40_groupActions.conf: create method to rename groups: updateGroupname
  * __repr__ now gives even better results.
  * 20_legacy.conf: new method setHostInventoryNumber
  * 20_legacy.conf: refactored getAndAssignSoftwareLicenseKey
  * debian/format: removed
  * OPSI.Types: checking for classes is now implemented via isinstance and
    therefore also subclasses will be accepted.
  * OPSI.Util.Task.Certificate: Fix certificate creation on Debian 8.
  * OPSI.Util.HTTP: Workarround for Python versions that implement PEP0476
  * OPSI.Service.Worker.WorkerOpsiJsonRpc: now correctly stating the HTTP
    header field "content-type" if the content is compressed via deflate or
    gzip. To stay backwards compatible we return in the old style if the
    header field "Accept" of the request starts with "gzip-application".
  * OPSI.Util.HTTP: new functions deflateEncode, deflateDecode, gzipEncode
    and gzipDecode
  * OPSI.Backend.JSONRPC: various refactorings
  * OPSI.Backend.JSONRPC.JSONRPCBackend: correctly handle responses that are
    compressed via deflate or gzip. To stay backwards compatible it deflates
    the data if the HTTP header field "content-type" starts with "gzip".
  * The users opsiconfd / pcpatch are now added to the file admin group
    based on the groupname and not on the gid. This avoids adding these users
    to the wrong group if a group with gid 992 already exists.
  * RPM: if a group with gid 992 is already existing add the file admin group
    without giving a specific gid.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Tue, 09 Jun 2015 16:34:33 +0200

python-opsi (4.0.6.7-2) experimental; urgency=low

  * RHEL / CentOS 7: No indent to avoid confusing rpm.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Fri, 10 Apr 2015 14:23:46 +0200

python-opsi (4.0.6.7-1) experimental; urgency=low

  * Fix encoding problems in new __repr__.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Fri, 10 Apr 2015 13:40:21 +0200

python-opsi (4.0.6.6-1) experimental; urgency=low

  * OPSI.Util.Task.Rights: better ignoring of subfolders.
  * OPSI.Logger: some small refactorings.
  * OPSI.Util.Task.Sudoers: Do not duplicate existing entries.
  * OPSI.Logger.logWarnings: only log to the opsi-Logger.
  * CentOS / RHEL 7: depend on net-tools for ifconfig.
  * Added OPSI.System.Posix.getActiveConsoleSessionId

 -- Niko Wenselowski <n.wenselowski@uib.de>  Fri, 10 Apr 2015 10:31:29 +0200

python-opsi (4.0.6.5-1) experimental; urgency=low

  * Fix problem when working mit DHCP files.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Tue, 31 Mar 2015 11:38:41 +0200

python-opsi (4.0.6.4-1) experimental; urgency=low

  * OPSI.System.Posix.execute now accepts keyword arguments 'shell' and
    'waitForEnding' to have the same keyword arguments as on Windows.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 30 Mar 2015 15:38:39 +0200

python-opsi (4.0.6.3-1) experimental; urgency=low

  * OPSI.Util.Task.Rights: avoid duplicate path processing.
  * OPSI.Backend.MySQL.ConnectionPool: lower log-level for messages.
  * OPSI.Util.Task.Rights.setRights: show what path is given.
  * Fix various problems in OPSI.Backend.Replicator.
  * OPSI.Util.Task.Sudoers: Retrieve path to 'service' from the OS.
  * OPSI.Util.Task.Sudoers: Add single entry if missing.
  * Small changes in OPSI.Util.File.
  * Less wildcard imports.
  * Refactoring in OPSI.Util.Task.Rights
  * OPSI.Util.Task.Rights will fail without raising an error if chown
    is not possible.
  * OPSI.Backend.BackendManager: refactored reading groups of user to be
    faster for large environments.
  * Many objects now have proper representations.
  * OPSI.Util.Task.ConfigureBackend.ConfigurationData: Adding WAN
    configuration defaults if they are missing.
  * New extension 70_wan.conf for easy disabling/enabling of WAN configuration
  * 70_dynamic_depot.conf: getDepotSelectionAlgorithmByNetworkAddress
    makes use of OPSI.Util.ipAddressInNetwork instead of copying code.
  * OPSI.Util.Task.Rights: chown will only supply an uid if euid is 0 to
    avoid failures.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 30 Mar 2015 11:44:00 +0200

python-opsi (4.0.6.2-1) experimental; urgency=low

  * OPSI.Backend.MySQL: If connecting to DB fails during creation of the
    connection pool we wait 5 seconds before retrying to connect.
  * OPSI.Logger: Easier and faster check if syslog is present.
  * OPSI.Backend.Replicator: small refactorings.
  * OPSI.Backend.BackendManager: _dispatchMethod creats no more temp. list.
  * OPSI.Util.Task.Certificate: do not set the same serial number for
    every certificate.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 09 Mar 2015 10:56:28 +0100

python-opsi (4.0.6.1-1) experimental; urgency=low

  * OPSI.Util.Repository: correctly set number of retries for dynamic bandwith
  * setup.py: Exclude test folders.
  * objectToBeautifiedText: indent with only four spaces
  * OPSI/Object.py overhauled module
  * Added OPSI.System.Posix.runCommandInSession to have access to this
    function not only when running Windows.
  * OPSI.Backend.File: Various refactorings, not only to avoid unnecessary
    creation of temporary objects.
  * Backends: speed up option parsing during initalisation.
  * Make excessive use of List Comprehensions for faster processing.
  * OPSI.Backend.HostControl: Using the timeout-parameter available on
    httplib.HTTP(S)Connection in RpcThread and ConnectionThread
  * Improve speed of configState_getClientToDepotserver
  * OPSI.Backend.SQL: Refactored working with the hardware audit
  * Speed up OPSI.Backend.Backend.log_read
  * The size limit of log_write can now be controlled through
    opsiconfd.conf and the value of "max log size" in the section "global".
  * New module: OPSI.Util.Task.Rights
  * OPSI.System.Windows: function "mount" accepts "dynamic" as mountpoint to
    enable the automatic search for a free mountpoint on the system.
    Thanks to Markus Kötter for the initial patch!
  * OPSI.Util.Task.ConfigureBackend.ConfigurationData: add the possibility
    to enable the dynamic mountpoint selection.
  * OPSI.Backend.SQL: the columns referencing hostId are now of the same size
  * New module OPSI.Util.Task.UpdateBackend.MySQL
  * OPSI.Util.Task.UpdateBackend.MySQL: Fix too small hostId columns
  * OPSI.Backend.SQL: replacing duplicate code
  * Removed LDAP schema files and backend configuration.
  * OPSI.Backend.SQL: Functions getData and getRawData only allow SELECT
  * Making method backend_getSharedAlgorithm nonfunctional.
  * OPSI.SharedAlgorithm: No more working with code-as-text and evaluation
    of the text to get objects to work with. Now there are only the objects.
  * WindowsDrivers: Fallback if directories ends with "." or with whitespace.
  * OPSI.Types.forceList is now able to handle sets and generators
  * New function OPSI.System.Posix.getDHCPDRestartCommand
  * OPSI.SharedAlgorithm: Raising an error when a circular dependecy is
    detected between products.
  * OPSI.System.Posix.getNetworkDeviceConfig is now able to parse output
    from newer ifconfig versions like on CentOS 7.
  * OPSI.Backend.SQLite refactored query creation.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Thu, 05 Feb 2015 09:46:50 +0100

####################

[[opsi-406-releasenotes-misc-changelogs-opsiconfd]]
==== Changelog opsiconfd

opsiconfd (4.0.6.10-2) experimental; urgency=medium

  * Default logrotate configuration now only rotates package.log
    and opsiconfd.log.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Tue, 15 Sep 2015 14:13:18 +0200

opsiconfd (4.0.6.10-1) experimental; urgency=medium

  * Adjusting configuration for logrotate.
  * opsiconfd: Config 'maxLogSize' now is a number
  * opsiconfd.conf: change 'max log size' to 5MB

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 14 Sep 2015 15:18:36 +0200

opsiconfd (4.0.6.9-1) experimental; urgency=medium

  * Removed itext-pdf.jar from the configed JNLP template.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 14 Sep 2015 10:24:28 +0200

opsiconfd (4.0.6.8-1) experimental; urgency=medium

  * Info page: limit the length of average call duration.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Thu, 10 Sep 2015 14:47:00 +0200

opsiconfd (4.0.6.7-1) experimental; urgency=medium

  * Collect statistics about the average method call duration.
  * Info page: show the average call duration next to the most called functions

 -- Niko Wenselowski <n.wenselowski@uib.de>  Thu, 10 Sep 2015 14:11:35 +0200

opsiconfd (4.0.6.6-1) experimental; urgency=medium

  * Info page: show at what time an encoding error occured.
  * Infos about updated rrd now only are shown with loglevel 8
  * opsiconfd.workers: Query decoding now working similar to the one in
    OPSI.Service.Worker
  * CentOS / Red Hat 7: Fix requiring /bin/python instead of /usr/bin/python
  * RPM: License is now machine-parseable.
  * Create user / groups without explicit uid / gid.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Tue, 25 Aug 2015 10:52:46 +0200

opsiconfd (4.0.6.5-1) experimental; urgency=medium

  * Showing what the actual error was that was experienced when collecting statistics.
  * Showing the time of service start on the info page.
  * simplify logrotate config.
  * Showing uptime of the service on the info page.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 13 Jul 2015 10:37:04 +0200

opsiconfd (4.0.6.4-12) experimental; urgency=medium

  * Ignore error from pkg-config in postinst.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Wed, 17 Jun 2015 10:42:56 +0200

opsiconfd (4.0.6.4-11) experimental; urgency=medium

  * Correct name of service file.
  * More error resistant installation.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Wed, 17 Jun 2015 09:43:22 +0200

opsiconfd (4.0.6.4-10) experimental; urgency=medium

  * Improving the removal of the service files.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Tue, 16 Jun 2015 16:54:04 +0200

opsiconfd (4.0.6.4-9) experimental; urgency=medium

  * RPM: Removing debug package.
  * RPM: small fix in postinst-script.
  * RPM: removing service file on uninstall
  * RPM: require pkgconfig for RedHat family, pkg-config for suse family

 -- Niko Wenselowski <n.wenselowski@uib.de>  Tue, 16 Jun 2015 14:03:08 +0200

opsiconfd (4.0.6.4-8) experimental; urgency=medium

  * RPM: creating folder for systemd templates before installation

 -- Niko Wenselowski <n.wenselowski@uib.de>  Tue, 16 Jun 2015 13:21:03 +0200

opsiconfd (4.0.6.4-7) experimental; urgency=medium

  * Debian: lintian-override fix

 -- Niko Wenselowski <n.wenselowski@uib.de>  Tue, 16 Jun 2015 12:09:55 +0200

opsiconfd (4.0.6.4-6) experimental; urgency=medium

  * Debian: extending lintian-overrides for Debian 8

 -- Niko Wenselowski <n.wenselowski@uib.de>  Tue, 16 Jun 2015 12:02:16 +0200

opsiconfd (4.0.6.4-5) experimental; urgency=medium

  * Debian: changing package format to 1.0 so Jessy is happy.
  * Rewrote the way that the systemd unitfile is integrated.
  * Removed references to opsi-distutils.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 15 Jun 2015 14:59:18 +0200

opsiconfd (4.0.6.4-4) experimental; urgency=medium

  * Debian: Re-introduce dependency for python-support.
    As opposed to the Debian docs dh-python alone is not sufficent since
    Debian Squeeze.
  * Debian: ignoring lintians not-using-po-debconf.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 15 Jun 2015 14:45:17 +0200

opsiconfd (4.0.6.4-3) experimental; urgency=medium

  * Debian: Downgrade Standards-Version to 3.9.4
  * Debian: Removing the support for python-support in favor of dh_python2
  * Debian: bump minimum required python-version to 2.6.6-3~.
  * Debian: specify "Uploader" in control-file.
  * Debian: specify "3.0 (native)" as format.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 15 Jun 2015 14:17:54 +0200

opsiconfd (4.0.6.4-2) experimental; urgency=medium

  * Packaging adjustments to make lintian happy.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 15 Jun 2015 11:30:00 +0200

opsiconfd (4.0.6.4-1) experimental; urgency=low

  * opsiconfd.conf: Default log-level is 5.
  * fix in webstart implementation for configed
  * Failed RPDs now get logged as a warning.
  * Various small refactorings.
  * Supply a unit-file for systemd.
  * debian/format: removed file.
  * Various small refactorings in opsiconfd.workers

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 15 Jun 2015 11:18:06 +0200

opsiconfd (4.0.6.3-1) experimental; urgency=low

  * Logrotate config: client logs in opsiclientd require size >= 5MB
  * opsiconfd.conf: Added entry for "max sessions per ip"

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 09 Mar 2015 11:05:01 +0100

opsiconfd (4.0.6.2-1) experimental; urgency=low

  * Fix HTML table code.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Fri, 30 Jan 2015 10:14:10 +0100

opsiconfd (4.0.6.1-1) experimental; urgency=low

  * Info page: Show info about 15 most executed RPCs
  * Setting +x on /etc/init.d/opsiconfd for openSuse 13.2
  * Make it possible to set a limit for the size of logfiles.
  * Extending logrotate config to match more logtypes.
  * Added logrotate configuration for /var/log/opsi/package.log
  * Info page: show total number of calls.
  * RPC call statistics are stored in a deque for faster operation

 -- Niko Wenselowski <n.wenselowski@uib.de>  Fri, 30 Jan 2015 09:24:16 +0100


####################

[[opsi-406-releasenotes-misc-changelogs-opsi-utils]]
==== Changelog opsi-utils

opsi-utils (4.0.6.6-4) experimental; urgency=medium

  * Do not forget to add the directory for Danish translation.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Thu, 03 Sep 2015 16:36:04 +0200

opsi-utils (4.0.6.6-3) experimental; urgency=medium

  * Translations updated and translation for da added.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Thu, 03 Sep 2015 11:20:04 +0200

opsi-utils (4.0.6.6-2) experimental; urgency=medium

  * Debian: Updated description.
  * Debian: add missing install file.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Thu, 13 Aug 2015 15:36:30 +0200

opsi-utils (4.0.6.6-1) experimental; urgency=medium

  * opsi-admin: setPcpatchPassword fails on empty password.
  * opsi-admin: setPcpatchPassword hides password in output.
  * Update translation to fix typo.
  * opsi-product-updater: Do not delete old logfile.
  * opsi-package-manager: Do not delete old logfile.
  * Debian: overhauled packaging.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Thu, 13 Aug 2015 15:36:16 +0200

opsi-utils (4.0.6.5-2) experimental; urgency=medium

  * Packaging fixes for OBS.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 29 Jun 2015 15:50:40 +0200

opsi-utils (4.0.6.5-1) experimental; urgency=low

  * opsi-convert: Fix problem with conversion between backends.
  * opsi-admin: Convert errors to unicode before logging them.
  * Updated manpage.
  * opsi-convert: fix the possibility to convert between backends where
    one of the backends is given as the backend address.
  * opsi-convert: refactorings and cleanups.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Wed, 10 Jun 2015 11:22:40 +0200

opsi-utils (4.0.6.4-1) experimental; urgency=low

  * opsi-admin: Better handling of non-iterable results in direct access.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Tue, 31 Mar 2015 10:29:49 +0200

opsi-utils (4.0.6.3-1) experimental; urgency=low

  * opsi-product-updater: Only set the rights once on the package directory.
  * opsi-package-manager: Better error message if setting a locale fails.
  * opsi-newprod: Changed option-parsing to argparse library.
  * opsi-newprod: small refactorings.
  * opsi-newprod: new option --version
  * opsi-newprod: create postinst template again
  * opsi-admin: non-interactive mode: Errors during execution will
    result in an exit code of 1.
  * opsi-admin: non-interactive mode: new option --exit-zero that will
    let the script always exit with 0.
  * opsi-admin: non-interactive mode: If errors are detected as the
    result of a call it will result in an exit code of 2.
  * opsi-convert: Overhauled commandline argument parsing.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Fri, 27 Mar 2015 15:57:42 +0100

opsi-utils (4.0.6.2-1) experimental; urgency=low

  * Fixing call to unreferenced variable.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 09 Mar 2015 16:02:25 +0100

opsi-utils (4.0.6.1-5) experimental; urgency=low

  * Use correct path for logrotate configs during removal "su".

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 09 Mar 2015 14:05:11 +0100

opsi-utils (4.0.6.1-4) experimental; urgency=low

  * For .deb-packages we create the logrotate-folder.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 09 Mar 2015 13:51:35 +0100

opsi-utils (4.0.6.1-3) experimental; urgency=low

  * Do not forget to install the logrotate configs.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 09 Mar 2015 13:09:02 +0100

opsi-utils (4.0.6.1-2) experimental; urgency=low

  * Fix path to logrotate config on RPM-based machines.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 09 Mar 2015 11:29:55 +0100

opsi-utils (4.0.6.1-1) experimental; urgency=low

  * opsi-product-updater: Patch by Antione Guevara to make it possible to
    give a custom subject on notification emails.
  * opsi-product-updater, opsi-newprod and opsi-package-manager now use
    OPSI.Util.Task.Rights.setRights for setting consistent rights.
  * Added logrotate configuration vor /var/log/opsi/opsi-backup.log
  * Added logrotate configuration vor /var/log/opsi/opsi-product-updater.log
  * opsi-admin: Added new task "setActionRequestWhereOutdatedWithDependencies".
    Thanks to Daniel Koch for the patch!

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 09 Mar 2015 11:12:03 +0100

####################

[[opsi-406-releasenotes-misc-changelogs-opsi-linux-bootimage]]
==== Changelog opsi-linux-bootimage

opsi-linux-bootimage (20150916-1) experimental; urgency=medium

  * added fix for delayed UI crash on VSphere Clients

 -- Mathias Radtke <m.radtke@uib.de>  Wed, 16 Sep 2015 12:59:40 +0200

opsi-linux-bootimage (20150908-1) experimental; urgency=medium

  * missing elilo.efi in debian distributions fixed

 -- Mathias Radtke <m.radtke@uib.de>  Tue, 08 Sep 2015 10:57:47 +0200

opsi-linux-bootimage (20150907-1) experimental; urgency=medium

  * master.py: added fix to only use network adapters with link to an opsi server
  * dhclient timeout set to 15 seconds to prevent dhclient to stall system boot for 5 minutes, whenever a network adapter is not connected

 -- Mathias Radtke <m.radtke@uib.de>  Mon, 07 Sep 2015 12:41:14 +0200

opsi-linux-bootimage (20150903-1) experimental; urgency=medium

  [ Niko Wenselowski ]
  * Updated translations.

  [ Mathias Radtke ]
  * updated python-opsi

 -- Mathias Radtke <m.radtke@uib.de>  Thu, 03 Sep 2015 11:21:38 +0200

opsi-linux-bootimage (20150902-1) experimental; urgency=medium

  * added forgotten pxelinux.cfg templates
  * removed popping in stderr outputs
  * fixed error with missig gcc library

 -- Mathias Radtke <m.radtke@uib.de>  Wed, 02 Sep 2015 13:55:33 +0200

opsi-linux-bootimage (20150818-1) experimental; urgency=medium

  * Ubuntu 14.04 Trusty
  * kernel 4.1.0
  * Python-OPSI 4.0.6.14-1
  * Syslinux 6.0.3
  * Updated packaging.

 -- Mathias Radtke <m.radtke@uib.de>  Wed, 18 Aug 2015 14:26:47 +0200

[[opsi-406-releasenotes-misc-changelogs-opsi-depotserver]]
==== Changelog opsi-depotserver

opsi-depotserver (4.0.6.4-1) experimental; urgency=medium

  * Removed wildcard imports.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Wed, 19 Aug 2015 11:29:42 +0200

opsi-depotserver (4.0.6.3-6) experimental; urgency=medium

  * Debian: Removing  python:depends dependency.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Thu, 13 Aug 2015 11:24:59 +0200

opsi-depotserver (4.0.6.3-5) experimental; urgency=medium

  * Debian: Creating /home/opsiproducts in postinst

 -- Niko Wenselowski <n.wenselowski@uib.de>  Thu, 13 Aug 2015 11:07:27 +0200

opsi-depotserver (4.0.6.3-4) experimental; urgency=medium

  * Debian: Added dependency to Python >= 2.6
  * Debian: provide debian/install for opsi-depotserver-expert
  * Debian: try to fix warnings about invalid changelog entry.
  * Debian: postinst: added DEBHELPER token.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Wed, 12 Aug 2015 17:20:41 +0200

opsi-depotserver (4.0.6.3-3) experimental; urgency=medium

  * Debian: Overhauled installation

 -- Niko Wenselowski <n.wenselowski@uib.de>  Wed, 12 Aug 2015 17:16:48 +0200

opsi-depotserver (4.0.6.3-2) experimental; urgency=medium

  * Debian postinst: do not specify full path to opsi-setup.
  * Debian control: requiring Python

 -- Niko Wenselowski <n.wenselowski@uib.de>  Fri, 31 Jul 2015 11:55:17 +0200

opsi-depotserver (4.0.6.3-1) experimental; urgency=medium

  [ Mathias Radtke ]
  * refactored configureSamba function in python-opsi
  * replaced part of python-setup with new import

  [ Niko Wenselowski ]
  * Removed dead code.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Wed, 29 Jul 2015 15:28:02 +0200

opsi-depotserver (4.0.6.2-1) experimental; urgency=medium

  * Fix problem where no password would be obtained during user config.
  * Various packaging fixes for Debian 8.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Tue, 16 Jun 2015 14:52:38 +0200

opsi-depotserver (4.0.6.1-3) experimental; urgency=low

  * Another fix regarding detection of SLES 12.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Fri, 10 Apr 2015 12:48:45 +0200

opsi-depotserver (4.0.6.1-2) experimental; urgency=low

  * RPM: Improved check for SLES to also work on SLES 12.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Fri, 10 Apr 2015 10:38:54 +0200

opsi-depotserver (4.0.6.1-1) experimental; urgency=low

  * Using OPSI.Util.Task.UpdateBackend.MySQL
  * Using OPSI.Util.Task.Rights.setRights
  * Using OPSI.System.Posix.getDHCPDRestartCommand
  * Making sure /var/log/opsi/userlogin exists after installation

 -- Niko Wenselowski <n.wenselowski@uib.de>  Wed, 04 Feb 2015 17:08:13 +0100

####################

[[opsi-406-releasenotes-misc-changelogs-opsi-atftp]]
==== Changelog opsi-atftp
////
opsi-atftp (0.7.dfsg-4) stable; urgency=medium
////
####################

[[opsi-406-releasenotes-misc-changelogs-opsi4ucs]]
==== Changelog opsi4ucs

opsi4ucs (4.0.6.3-1) experimental; urgency=medium

  * Fix exception catching.
  * Less wildcard imports

 -- Niko Wenselowski <n.wenselowski@uib.de>  Wed, 19 Aug 2015 11:23:08 +0200

opsi4ucs (4.0.6.2-4) experimental; urgency=medium

  * Updated ignores.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Wed, 29 Jul 2015 16:51:58 +0200

opsi4ucs (4.0.6.2-3) experimental; urgency=medium

  * Another round of packaging improvements.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Wed, 29 Jul 2015 16:45:07 +0200

opsi4ucs (4.0.6.2-2) experimental; urgency=medium

  * Updated packaging information for Debian 8.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Wed, 29 Jul 2015 16:29:16 +0200

opsi4ucs (4.0.6.2-1) experimental; urgency=medium

  [ Mathias Radtke ]
  * refactored configureSamba in python-opsi
  * replaced configureSamba function in python-setup with import

  [ Niko Wenselowski ]
  * Removed unused code.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Wed, 29 Jul 2015 15:15:01 +0200

opsi4ucs (4.0.6.1-1) experimental; urgency=low

  * Using OPSI.Util.Task.UpdateBackend.MySQL
  * Using OPSI.Util.Task.Rights.setRights
  * Removed LDAP schema files.
  * Using OPSI.System.Posix.getDHCPDRestartCommand
  * Making sure /var/log/opsi/userlogin exists.
  * Fix problem where no password would be obtained during user config.

 -- Niko Wenselowski <n.wenselowski@uib.de>  Mon, 02 Feb 2015 16:57:31 +0100
