////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      11.01.2021
:doctype: book




[[opsi-script-introduction]]
= Introduction

The open source program _opsi-script_ (former at windows 'opsi-winst') serves in the context of opsi – open pc server integration (cf. www.opsi.org) – as the central function for initiating and performing the automatic software installation. It may also be used stand alone as a tool for setup programs for any piece of software.

_opsi-script_ is basically an interpreter for a specific, rather simple script language which can be used to express all relevant elements of a software installation.

A software installation that is described by a _opsi-script_ script and performed by executing the script has several advantages compared with installations that are managed by a group of shell commands (e. g. copy etc.):

* _opsi-script_ can log very thoroughly all operations of the installation process. The support team can check the logfiles, and then easily detect when errors occurred or other problematic circumstances unfold.

* Copy actions can be configured with a great variety of options if existing files should be overwritten

* Especially, it may be configured to copy files depending on their internal version.

* There are different modes to write to the Windows registry:
** overwrite existing values
** write only when no value exists
** append a value to an existing value.

* The Windows registry can be patched for all users which exist on a work station (including the default user, which is used as prototype for further users).

* There is a sophisticated syntax for an integrated patching of XML configuration files.


