////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      21.03.2023
:Revision:  4.2
:toclevels: 6
:doctype: book

include::common:partial$opsi_terms.adoc[]

[[opsi-getting-started-requirements]]
= Voraussetzungen

Dieses Kapitel beschreibt die Voraussetzungen für die Installation des opsi-Servers unter Linux. Eine Liste der unterstützten Distributionen finden Sie am Ende des Kapitels im Abschnitt <<opsi-getting-started-installation-linux-support>>.

[[opsi-getting-started-requirements-hardware]]
== Hardware

Das sind die Voraussetzungen für einen opsi-Server auf echter Hardware:

* x86-64- oder ARM64-System
* 2{nbsp}GByte RAM oder mehr
* 2 CPU-Kerne oder mehr

Wie viel Festplatten-Speicher der Server benötigt, hängt unter anderem von der Anzahl der installierten opsi-Pakete ab. Für Produktiv-Systeme gelten folgende Empfehlungen:

* Sorgen Sie dafür, dass im Verzeichnis `/tmp` immer mindestens 15{nbsp}GByte freier Speicherplatz zur Verfügung steht.
* Im Verzeichnis `/var/lib/opsi` benötigen Sie mindestens 60{nbsp}GByte; der Ordner muss flexibel erweiterbar sein.

Abhängig von der Konfiguration und den Tagesabläufen greifen unterschiedlich viele opsi-Clients auf einen opsi-Server zu. In großen Umgebungen mit vielen gleichzeitigen Client-Verbindungen können RAM- und CPU-Bedarf deutlich ansteigen.

TIP: Der zentrale opsi-Dienst `opsiconfd` benötigt pro Worker-Prozess ca. 250{nbsp}MByte RAM. Wir empfehlen, einen Worker-Prozess für 20 gleichzeitige Verbindungen einzuplanen. Die Anzahl der CPU-Kerne sollte in etwa der Hälfte der Anzahl der Worker-Prozess entsprechen. In der Standard-Konfiguration sollten Sie zusätzliche Ressourcen für Samba, MySQL und Redis einplanen.

[[opsi-getting-started-introduction-software-and-configuration-preconditions]]
== Konfiguration

Um opsi installieren zu können, sind bestimmte Netzwerk- und Sprach-Einstellungen erforderlich. Die nächsten Abschnitte erklären, welche Anforderungen in Bezug auf DNS (Domain Name System) und Lokalisierung erfüllt sein müssen.

[[opsi-getting-started-requirements-software-dns-domainname]]
=== Gültiger Domainname

Der Domainname muss mindestens aus einer Domain und einer Top-Level-Domain (TLD) bestehen, muss also mindestens aus dem Hostnamen, einem Punkt und einer Top-Level-Domain (zwei Zeichen) bestehen:

* Erlaubt sind beispielsweise `domain.local`, `uib.de`, `subdomain.domain.de`.
* *Nicht* erlaubt sind `mydomain.d` (TLD hat nur ein Zeichen) oder `mydomain` (TLD fehlt). 

TIP: Weitere Informationen finden Sie unter https://de.wikipedia.org/wiki/Domain. 

[[opsi-getting-started-requirements-software-dns-hostname]]
=== Gültiger Hostname

Der opsi-Server und auch die opsi-Clients müssen einen gültigen Hostnamen haben. Erlaubt sind Buchstaben (a bis z, A bis Z), Zahlen und der Bindestrich. Der Unterstrich und andere Sonderzeichen sind nicht erlaubt.

Unter Linux überprüfen Sie die Einstellungen mit dem Kommando `hostname`. Verwenden Sie den Parameter `-f`, um den Fully Qualified Domain Name (FQDN) anzuzeigen:

[source,prompt]
----
hostname -f
----

Die Ausgabe sollte einen FQDN zurückliefern, in dem mindestens zwei Punkte vorkommen, z.{nbsp}B. `opsiserver.domain.local`. Wenn das Ergebnis anders aussieht und Sie etwa `127.0.0.1` bzw. `localhost` als Antwort erhalten, korrigieren Sie zunächst die Datei `/etc/hosts` bzw. Ihre Namensauflösung (siehe nächster Abschnitt).

TIP: Weiterführende Informationen zu gültigen Hostnamen finden Sie hier: https://de.wikipedia.org/wiki/Hostname#Richtlinien

[[opsi-getting-started-requirements-software-dns-resolving]]
=== Korrekte Namensauflösung für den Server

Kontrollieren Sie den Eintrag für den opsi-Server in der Datei `/etc/hosts` oder geben Sie den folgenden Befehl auf der Kommandozeile ein:

[source,prompt]
----
getent hosts $(hostname -f)
----

Das Ergebnis sollte beispielsweise so aussehen:

[source,prompt]
----
192.168.1.1 server.domain.tld server
----

Dabei sollte die IP-Adresse der Netzwerkschnittstelle aufgeführt sein, zu der sich die Clients später verbinden sollen. Sehen Sie in der Datei `/etc/hosts` nur Einträge für `localhost`, `127.0.0.1` oder `127.0.0.2`, dann korrigieren Sie die Namensauflösung, bevor Sie fortfahren.

NOTE: Auch wenn die Namen den Vorgaben eines DNS-Systems entsprechen müssen, benötigen Sie keinen DNS-Server für den Betrieb von opsi. opsi setzt ebenfalls kein Active Directory o.{nbsp}Ä. voraus, auch wenn eine Integration in einen Verzeichnisdienst möglich ist.

[[opsi-getting-started-requirements-software-lang]]
=== Spracheinstellungen (`locale`)

opsi setzt voraus, dass auf dem Server die Sprache mittels `locale` gesetzt ist. Um die Spracheinstellungen zu überprüfen, können Sie beispielsweise das folgende Kommando eingeben:

[source,prompt]
----
test -e /etc/default/locale && echo "ok" || (echo "Check locales:" && locale)
----

Sehen Sie `ok` als Antwort, ist alles in Ordnung. Erscheint hingegen `check locales:`, dann setzen Sie die Einstellungen über die Umgebungsvariablen `LANG` oder `LC_ALL`.

TIP: Wir empfehlen eine Lokalisierung mit UTF-8-Unterstützung, z.{nbsp}B. `de_DE.UTF-8` für Deutsch.

Die folgenden Befehle zeigen beispielhaft, wie Sie die Einstellungen ändern können, sollte kein Wert oder ein unerwünschter Wert gesetzt sein:

[source,prompt]
----
sudo locale-gen de_DE.UTF-8
update-locale LANG=de_DE.UTF-8
----

Weitere Informationen entnehmen Sie bitte dem Handbuch der von Ihnen verwendeten Linux-Distribution.

[[opsi-getting-started-installation-config-ports]]
== Verwendete Netzwerk-Protokolle und -Ports

opsi und seine Dienste verwenden die folgenden Netzwerk-Protokolle und Ports:

* opsi-Server, Webservice: 4447/tcp +
Client zum Config- und Depot-Server, Depot-Server zum Config-Server, auch Verbindungen via `localhost` 
* opsi-Client, Webservice: 4441/tcp +
Config-Server zum Client, Verbindung vom Client zu sich selbst via `localhost`
* opsi-Client, Notifier: 45000/tcp bis 45099/tcp +
Verbindung vom Client zu sich selbst via `localhost`, Auswahl eines zufälligen Ports aus dem angegebenen Bereich
* TFTP: 69/udp +
Verbindung vom Client zum Depot-Server
* TFTP: 1024/udp bis 65535/udp +
Verbindung vom Depot-Server zum Client
* CIFS/SMB: 445/tcp +
Verbindung vom Client zum Depot-Server
* CIFS/SMB: 445/tcp +
Verbindung vom Depot-Server zum Client (nur notwendig, wenn `opsi-deploy-client-agent` (`winexe`, `smbclient`) für Windows-Clients verwendet wird)
* Grafana, Webservice: 3000/tcp +
Verbindung vom Client zum Config-Server (nur bei Zugriff vom Client auf die Management-Website des Config-Servers)
* SSH: 22/tcp +
Verbindung vom Client zum Config-Server und Depot-Server
* SSH: 22/tcp +
Verbindung vom Depot-Server zum Client (nur beim Einsatz von `opsi-deploy-client-agent` unter Linux und macOS)
* DNS: 53/tcp, 53/udp +
Alle Server und Clients müssen Ihren DNS-Dienst erreichen können.
* Wake-on-LAN (WoL): 7/udp, 9/udp, 12287/udp  +
Verbindung vom Config-Server zum Client; Ports sind konfigurierbar
* HTTP: 80/tcp +
Config- und Depot-Server ins Internet, um z.{nbsp}B. Server-Updates von http://download.opensuse.org zu laden
* HTTPS: 443/tcp +
Config- und Depot-Server ins Internet, um z.{nbsp}B. Pakete von https://download.uib.de zu laden (`opsi-package-updater`)

NOTE: Der Config-Server ist der zentrale opsi-Server zur Verwaltung aller Clients. Der Depot-Server ist der Server, der die Installationspakete der eingesetzten Software vorhält. Wenn es nur einen einzigen opsi-Server gibt, so übernimmt dieser beide Rollen.

[[opsi-getting-started-installation-config-proxy]]
== Proxy-Einstellungen

Wenn Sie einen HTTP-Proxy verwenden, dann konfigurieren Sie die Proxy-Einstellungen systemweit über Umgebungsvariablen (Datei `/etc/environment`). 

NOTE: Beachten Sie, dass die Namen der Umgebungsvariablen ausschließlich Kleinbuchstaben verwenden.

* `http_proxy`: konfiguriert den Proxy für HTTP-Verbindungen, setzt eine vollständige URL voraus (nicht nur Hostname und Port); falls Authentifizierung erforderlich ist, kann diese in der URL definiert werden: +
`http_proxy=http://<user>:<password>@<proxy-address>:<port>`
* `https_proxy`: wie `http_proxy`, nur für HTTPS-Verbindungen: +
`https_proxy=https://<proxy-address>:<port>`
* `no_proxy`: definiert, für welche Adressen kein Proxy verwendet werden soll; mehrere Adressen werden durch Kommata getrennt: +
`no_proxy=127.0.0.1,localhost,mydomain.example,hostname.domain.com:8080` +
Für die Adressen gelten die folgenden Regeln:
** Verwenden Sie nur Kleinbuchstaben.
** Notieren Sie nur IP-Adressen, wenn auch der Zugriff direkt auf die IP-Adresse erfolgt. Bei der Auswertung der Ausnahmen findet keine Namensauflösung statt.
** IP-Adressbereiche (CIDR-Matching, wie z.{nbsp}B. `192.168.0.0/24`) sind nicht zulässig.
** Sie müssen auch für lokale Adressen (`localhost`) und Loopback-Adressen (`127.0.0.1`) Ausnahmen definieren.
** Wildcards und reguläre Ausdrücke sind nicht erlaubt.
** Jeder Name wird als Suffix ausgewertet, `domain.com` definiert daher eine Ausnahme für alle Hostnamen die auf `domain.com` enden.
** Sie können für jede Adresse optional einen Port hinter einem Doppelpunkt angeben, für den die Ausnahme gilt.

[[opsi-getting-started-installation-linux-support]]
== Unterstützte Linux-Distributionen

Den opsi-Server können Sie unter vielen verschiedenen Linux-Distributionen installieren. Die nächste Tabelle listet die unterstützten Systeme genauer auf.

// Add the support matrix
include::common:partial$supportmatrix.adoc[]


