////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype: book

include::common:partial$opsi_terms.adoc[]


[[opsi-getting-started-requirements]]
= Voraussetzungen

Nachfolgend werden die Voraussetzungen für die Installation von opsi auf einem Server beschrieben.

// Add the support matrix
include::common:partial$supportmatrix.adoc[]


[[opsi-getting-started-requirements-hardware]]
== Hardwarevoraussetzungen

Für den {opsi-Server} in realer Hardware wird benötigt:

* Intel-x86-kompatibler PC

* mindestens 2GB RAM

* eine Festplatte mit mindestens 60 GB Kapazität
** Ein {opsi-Server} sollte im Betrieb im Verzeichnis '/var/lib/opsi' über mindestens 16 GB freien Speicher verfügen

Im Testbetrieb sind die Anforderungen an die Leistungsfähigkeit der Maschine nicht besonders hoch. Für den Produktivbetrieb kann es nötig werden die Anforderungen an den Server an zu passen.

Bei der Verwendung der virtuellen Maschine muss ein angemessener Wirtsrechner genutzt werden. Es sollte mindestens ein Dualcore Prozessor und 4GB RAM vorhanden sein.
Für eine Teststellung kann problemlos eine weitere virtuellen Maschine auf dem selben Wirtsrechner als Client dienen.


[[opsi-getting-started-introduction-hardware-requirements-hints]]
=== Hinweise zur Ermittlung von Hardware-Anforderungen

Die Anforderungen an die Hardware hängen stark von der Verwendung ab.
Daher hier ein paar Hinweise damit Sie das passende für sich kalkulieren können.


[[opsi-getting-started-introduction-hardware-requirements-ram]]
==== Arbeitsspeicher

Jede aktive Samba Connection macht einen eigenen Samba Prozess auf.
Für diesen sind je nach Quelle zwischen 800 kB und 4 MB zu kalkulieren.
Wieviele opsi-clients gleichzeitig auf einen opsi Server zugreifen, hängt stark von den Tagesabläufen in Ihrer Umgebung ab.

Für link:https://www.samba.org/samba/docs/man/Samba3-ByExample/secure.html[Samba 3] wurden folgende Werte empfohlen:

|==========================
| Prozess | 1 User | 130 User | 500 User
| smbd    | 4 MB   | 520 MB   | 2000 MB
|==========================

Da uns keine Werte für aktuelle Samba-Versionen vorliegen, können die vorgenannten Zahlen lediglich als grobe Schätzung angesehen werden und sollten mit einem Sicherheitszuschlag von 50% versehen werden.

Der Speicherverbrauch des opsiconfd hängt stark (aber nicht nur) von der Anzahl der Clients ab.
Aus bestehenden Installationen kann der folgende Minimalverbrauch abgeleitet werden.
Bei den angegebenen Userzahlen handelt es sich hierbei nicht um gleichzeitig aktive User, sondern um die Gesamtzahl.

|==========================
| Prozess   | 100 User | 2000 User | 4000 User
| opsiconfd | 500 MB   | 1000 MB   | 2000 MB
|==========================

Auch hier sollten Sie einen Sicherheitszuschlag haben.


[[opsi-getting-started-introduction-hardware-requirements-hints-cpu]]
==== CPU

Der opsiconfd nutzt derzeit nur einen Kern.
Dieser eine Kern wird auch nur dann ausgelastet, wenn viele opsi-clients (>100) exakt gleichzeitig auf den Server zugreifen.
Aber das Betriebsystem, Samba, die Datenbank usw. benötigen ebenfalls Rechenzeit.

D.h. bei 500 Clients sollten zwei CPU-Kerne hinreichend sein, bei 1000 Clients sollten sie vier CPU-Kerne zur Verfügung stellen.

Beachten Sie auch, dass opsi-Depots Last auf den opsi-Configserver bringen, die zudem deutlich größer ist, als die eines einzelnen Clients.


[[opsi-getting-started-introduction-software-and-configuration-preconditions]]
== Software und Konfigurationsvoraussetzungen

Folgende Voraussetzungen müssen erfüllt sein, damit Sie opsi installieren bzw. einsetzen können:


[[opsi-getting-started-requirements-software-dns-domainname]]
=== gültiger DNS Domainname

Ihr DNS Domainname muss mindestens aus einer Domain und einer Topleveldomain bestehen.
Anders ausgedrückt: der volle (Fully qualified) Domainname muss mindestens einen Punkt enthalten.  Weiterhin muss die Topleveldomain aus mindestens zwei Zeichen bestehen.

Erlaubt sind z.B.: 'domain.local', 'uib.de', 'subdomain.domain.de'. +
Nicht erlaubt ist z.B. 'mydomain.d', denn das wäre nur ein Zeichen in der Topleveldomain. +
Nicht erlaubt ist z.B. 'mydomain', denn das wäre nur eine Topleveldomain.

Siehe auch:

* https://de.wikipedia.org/wiki/Domain
* https://de.wikipedia.org/wiki/Hostname#Richtlinien


[[opsi-getting-started-requirements-software-dns-hostname]]
=== gültige DNS Hostnamen

Die Hostnamen (auch der Clients) müssen den Richtlinien entsprechen.
Dazu gehört auch, dass sie z.B. keine Unterstriche enthalten dürfen.

Kontrollieren Sie auf Ihrem {opsi-Server}, dass der folgende Befehl einen 'fully qualified domainname' zurück liefert, in dem mindestens zwei Punkte vorkommen, z.B. 'opsiserver.domain.local':

[source,prompt]
----
hostname -f
----

Sieht das Ergebnis nicht so aus (enthält z.B. '127.0.0.1' oder 'localhost') dann müssen Sie Ihre '/etc/hosts' oder Namensauflösung zunächst korrigieren.

Siehe auch:
* https://de.wikipedia.org/wiki/Hostname#Richtlinien


[[opsi-getting-started-requirements-software-dns-resolving]]
=== Korrekte Namensauflösung für den Server

Prüfen Sie den Eintrag für den {opsi-Server} in der Datei '/etc/hosts', oder aber die Ausgabe von:

[source,prompt]
----
getent hosts $(hostname -f)
----

Das Ergebnis sollte beispielsweise so aussehen: +
'192.168.1.1 server.domain.tld server'

Dabei sollte die IP-Adresse der Netzwerkschnittstelle aufgeführt sein, zu der sich die Clients später verbinden sollen.

Sieht das Ergebnis nicht so aus (enthält z.B. '127.0.0.1', '127.0.0.2' oder 'localhost'), dann müssen Sie die Datei `/etc/hosts` oder Ihre Namensauflösung korrigieren.

NOTE: Die Namen müssen den Vorgaben eines DNS-Systems entsprechen, aber ein DNS-Server wird für den Betrieb von opsi nicht benötigt.

NOTE: opsi benötigt kein _Active Directory_ oder ähnliches. Eine Integration ist möglich, wird aber nicht vorausgesetzt.


[[opsi-getting-started-requirements-software-lang]]
=== Gesetzte Spracheinstellungen

opsi setzt voraus, dass auf dem verwendeten Server Spracheinstellungen ('locale') gesetzt sind. +
Empfohlen wird die Verwendung einer UTF-8-kompatiblen Lokalisierung. +

Zur vereinfachten Prüfung kann folgender Befehl verwendet werden:
[source,prompt]
----
test -e /etc/default/locale && echo "ok" || (echo "Check locales:" && locale)
----

Wird _ok_ ausgegeben, so sind locales gesetzt.
Wird _check locales:_ ausgegeben, so prüfen Sie bitte, dass in der nachfolgend
ausgegebenen Liste für 'LANG' oder 'LC_ALL' ein Wert gesetzt ist, welcher der von Ihnen verwendeten Sprache entspricht.

Für Deutsch empfehlen wir `de_DE.UTF-8`.

Die folgenden Befehle zeigen beispielhaft wie die Einstellung geändert
werden kann, sollte kein oder ein ungewollte Wert gesetzt sein:

[source,prompt]
----
sudo locale-gen de_DE.UTF-8
update-locale LANG=de_DE.UTF-8
----

Zum systemweiten Anwenden der Spracheinstellung sollte der Server neu gestartet werden.

Weitere Informationen entnehmen Sie bitte dem Handbuch der von Ihnen verwendeten Linux-Distribution.


[[opsi-getting-started-installation-config-ports]]
== Benötigte Netzwerk-Ports

Dies ist eine Übersicht über verwendete Ports und Netzwerk-Protokolle.

* opsi-server Webservice: TCP 4447 +
Client zum Server, Depot zum Server (bidirektional, Verbindungen via localhost).

* opsi-client Webservice: TCP 4441 +
Server zum Client, Verbindung vom Client an sich selbst via localhost.

* opsi-client Webservice: TCP 4442 +
Verbindung vom Client an sich selbst via localhost.

* opsi-client Notifier: TCP 45000 - 65536 +
Verbindung vom Client an sich selbst via localhost. +
Ein zufälliger Port aus dem gegebenen Bereich wird ausgewählt.

* TFTP: UDP 69 +
Verbindung vom Client zum Server.

* CIFS/SMB: UDP 137 / UDP 138 (netbios) / TCP 139 / TCP 445 +
Client zu Server (bidirektional). +
Abhängig von der Version des Client-Betriebssystems.

* WEBDAV: TCP 80
* WINEXE: UDP 137 / UDP 138 (netbios) / TCP 139 / TCP 445
Server zu Client (bidirektional). +
Abhängig von der Version des Client-Betriebssystems.

* grafana Webservice (optional): TCP 3000 +
Verbindung vom Client zum opsi-server.

* SSH (optional): TCP 22

* DNS: TCP 53

* WakeOnLan (WOL): UDP 7 / UDP 9 / UDP 12287 +
Verbindung vom Server zum Client. Diese Ports sind konfigurierbar.

* HTTP: TCP 80 +
Um Server-Updates z.B. von http://download.opensuse.org/ zu laden.

* HTTPS: TCP 443 +
Um Server-Updates z.B. von https://download.uib.de zu laden (opsi-package-updater).