////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      08.05.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]


[[server-configuration-authorization]]
== Autorisierung

[[server-configuration-authorization-users-and-groups]]
=== Benutzer und Gruppen
Für die Steuerung von Berechtigungen verwendet opsi die folgenden Gruppen:

* opsiadmin: Mitglieder dieser Gruppe können administrativ auf den opsi-Service zugreifen.
Mitglieder dieser Gruppe erhalten daher Vollzugriff über opsi-configed, opsi-WebGUI, opsiconfd-Admin-Interface, etc. +
Standardmäßig ist der Name dieser Gruppe *opsiadmin*.
* opsifileadmins: Mitglieder dieser Gruppe können administrativ auf opsi-Dateien (Depot, Repository, Workbench) zugreifen. +
Standardmäßig ist der Name dieser Gruppe *opsifileadmins*.
* opsireadonly: Mitglieder dieser Gruppe können nur lesend auf den opsi-Service zugreifen. +
Standardmäßig ist der Name dieser Gruppe *opsireadonlys*.

Die Namen dieser Gruppen können in der Konfigurationsdatei `/etc/opsi/opsi.conf` im Abschnitt `groups` geändert werden.

Beispiel:
// cSpell:disable
[source,toml]
----
[groups]
fileadmingroup = "opsifileadmins"
admingroup = "opsiadmin"
readonly = "opsireadonlys"
----
// cSpell:enable

Die folgenden Benutzer werden von opsi verwendet:

* opsiconfd: Ein Service-Benutzer unter dessen Account der zentrale opsi-Service *opsiconfd* läuft.
Der Benutzer muss Mitglied der opsi-Admin-Gruppe und opsi-Fileadmin-Gruppe sein.
* pcpatch: Bei Verwendung von CIFS (Samba) für den Zugriff auf das opsi-Depot verwenden die opsi-Clients diesen Account für die Authentifizierung. Der Benutzer muss Mitglied der Gruppe opsi-Fileadmin-Gruppe sein.

Standardmäßig werden auf einem opsi-Server lokale Benutzer und Gruppen verwendet.
Diese werden mit den Linux-Standard-Werkzeugen, wie *useradd*, *usermod*, *groupadd*, *groupmod*, etc., verwaltet.

Es besteht jedoch auch die Möglichkeit der Anbindung eines opsi-Configservers an eine zentrale Authentifizierung.

Weitere Informationen hierzu finden Sie unter
xref:server:configuration/authorization.adoc#authorization-domain-join[]
und
xref:server:configuration/authorization.adoc#authorization-ldap-authentication[].


[[server-configuration-authorization-pcpatch-password]]
=== Passwort für den Benutzer pcpatch

Da der Benutzer von den opsi-Clients für die Authentifizierung verwendet wird,
muss das Passwort dem opsi-Configserver bekannt sein.
Für diesen Zweck wird das Kennwort auf dem opsi-Configserver verschlüsselt abgelegt.

Das Passwort kann über `opsi-admin` geändert werden:

[source,shell]
----
opsi-admin -d task setPcpatchPassword
----

Nach dem Betätigen von [Eingabe] erscheint ein Passwort-Prompt, und Sie können das Kennwort eintippen.

Hierbei wird das Kennwort zusätzlich für den lokalen *opsi-admin* Unix- und Samba-Account geändert.
Sollten der Account kein lokaler, sondern ein Domänen-Account sein, muss das Kennwort zusätzlich manuell in der Domäne neu gesetzt werden.

NOTE: Im Zuge der Grund-Installation eines opsi-Configservers wird bereits vollautomatsich ein Zufalls-Kennwort gesetzt,
das nicht geändert werden muss.


[[server-configuration-authorization-create-local-users]]
=== Anlegen von Admin-Konten auf dem opsi-Configserver

Bei Verwendung von lokalen Benutzen und Gruppen auf dem opsi-Configserver,
müssen Benutzer, die Zugriff auf den opsi-Server erhalten sollen, über die Linux-Standard-Werkzeugen angelegt werden:

Im folgenden Beispiel wird ein neuer Benutzer *adminuser* angelegt, der Vollzugriff auf den opsi-Server erhält.

NOTE: Sowohl auf der vorkonfigurierten virtuellen Maschine, als auch im Docker-Container existiert der Account `adminuser` bereits`. Sie können jedoch mit dem selben Verfahren weitere Benutzer hinzufügen.

Legen Sie das neue Benutzer-Konto über den Befehl `useradd` an:
[source,shell]
----
sudo useradd -m -s /bin/bash adminuser
----

Anschließend setzen Sie für den neuen Account ein Unix-Passwort (System):

[source,shell]
----
sudo passwd adminuser
----

Soll der Benutzer auch Datei-Zugriff per CIFS (Samba) erhalten, muss auch hier ein Passwort gesetzt werden:

[source,shell]
----
sudo smbpasswd -a adminuser
----

WARNING: Verwenden Sie in den Passwörtern kein *§*-Zeichen!

Als Nächstes fügen Sie den neuen Benutzer den Gruppen *opsiadmin* und *opsifileadmins* hinzu:

[source,shell]
----
usermod -aG opsiadmin adminuser opsifileadmins
----

Mit dem Befehl `id` können Sie, zur Überprüfung, den Benutzer inklusive Gruppenzugehörigkeiten anzeigen lassen:

[source,shell]
----
id adminuser
# uid=1000(adminuser) gid=1000(opsiadmin) groups=1000(opsiadmin),999(opsifileadmins)
----


[[server-configuration-authorization-domain-join]]
=== Einbindung eines opsi-Servers in eine Windows-Domäne

Statt mit lokalen Unix- und Samba-Accounts zu arbeiten, kann ein opsi-Server auch in eine Windows- bzw. Samba4-Domäne eingebunden werden.

In der Domäne müssen die opsi-Admin-Gruppe und opsi-Fileadmin-Gruppe angelegt werden.
Es können an dieser Stelle auch andere Gruppen-Namen oder bestehende Gruppen verwendet werden.
Die Namen der Gruppen müssen dann in der Konfigurations-Datei `/etc/opsi/opsi.conf` entsprechend angepasst werden.

Weiterhin muss der Benutzer *pcpatch* als Mitglied der opsi-Fileadmin-Gruppe
und der Benutzer *opsiconfd* als Mitglied der opsi-Admin-Gruppe und opsi-Fileadmin-Gruppe in der Domäne angelegt werden.

Die opsi-Admin-Gruppe und opsi-Fileadmin-Gruppe müssen aus den lokalen Unix-Gruppen entfernt werden:

Auch die lokalen Unix-Benutzer *opsiconfd* und *pcpatch* müssen entfernt werden.

Danach nehmen Sie den opsi-Server, gemäß der Dokumentation der verwendeten Linux-Distribution, in die Windows-Domäne ein.

Führen Sie nach dem Domain-Join die folgenden Befehle aus:

[source,shell]
----
opsiconfd setup
opsi-set-rights
----

Setzen Sie dann dann das Passwort des Benutzers `pcpatch` neu, wie im Abschnitt xref:server:configuration/authorization.adoc#authorization-pcpatch-password[] beschrieben.


[[server-configuration-authorization-ldap-authentication]]
=== Authentifizierung gegen LDAP/Active Directory

Für die Authentifizierung am opsi-Service wird standardmäßig*PAM*verwendet.
Das funktioniert mit lokalen Benutzern und Gruppen, aber auch wenn der opsi-Server in eine Domäne eingebunden ist.

Statt PAM für die Authentifizierung zu nutzen, ist es auch möglich einen LDAP-Server bzw. ein Active Directory zu verwenden.
Hierfür ist die xref:opsi-modules:modules.adoc[opsi-Erweiterung] *opsi directory connector* notwendig.

IMPORTANT: Die Samba-Authentifizierung ist hiervon unabhängig.
Das Verfahren eignet sich daher hauptsächlich für opsi-Umgebungen,
bei denen die opsi-Administratoren nicht per Samba, sondern per WebDAV, auf die opsi-Shares zugreifen.
Beim Betrieb eines opsi-Servers unter Docker ist das immer der Fall.

Die Konfiguration findet über die Datei `/etc/opsi/opsi.conf` statt.
In der Sektion *ldap_auth* muss hierfür die Option *ldap_url* gesetzt werden.
Die ldap_url besitzt dabei den folgenden Aufbau:
`ldap[s]://<Adresse-des-LDAP-Servers>[:port]/<base-dn>`

Zusätzlich kann die Option*username*verwendet werden.
Damit kann definiert welcher Benutzername bei der Authentifizierung am LDAP/AD übergeben werden soll. Hierbei können die Platzhalter *\{username\}* und *\{base\}* verwendet werden. Im Normalfall ist jedoch die Angabe der *ldap_url* ausreichend.

Beispiel zur Anbindung an ein Active Directory bzw. Samba 4:

[source,toml]
----
[ldap_auth]
ldap_url = "ldaps://ad.company.de/dc=ad,dc=company,dc=de"
----

Beispiel zur Anbindung an einen OpenLDAP:

[source,toml]
----
[ldap_auth]
ldap_url = "ldaps://ldap.company.org:636/dc=company,dc=org"
username = "uid={username},dc=Users,{base}"
----

Damit die Änderungen übernommen werden, muss der *opsiconfd* neu gestartet werden.

NOTE: Bitte beachten Sie, dass die in der Variable *admingroup* definierte Gruppe auch im AD/LDAP verfügbar ist.


[[server-configuration-authorization-multi-factor]]
=== Multi-Faktor-Authentifizierung
Der opsi-Server unterstützt eine Zwei-Faktor-Authentifizierung mit dem Standard-Verfahren *Time-based One-time Password Algorithmus* (TOTP).
Hierbei wird bei der Anmeldung am opsi-Server zusätzlich eine Einmal-Passwort verwendet, das aus sechs Ziffern besteht.
Zur Freischaltung der Funktionalität ist die xref:opsi-modules:modules.adoc[opsi-Erweiterung] *WAN/VPN* notwendig.


==== Generelle Einrichtung
// cSpell:ignore multi-factor-auth, inactive, totp_optional, totp_mandatory
Zur Konfiguration der Zwei-Faktor-Authentifizierung existiert das xref:server:configuration/opsiconfd.adoc#server-configuration-opsiconfd-config
[opsiconfd Konfigurations-Attribut] `multi-factor-auth`.
Folgende Werte sind möglich:

inactive:: Die Multi-Faktor-Authentifizierung ist inaktiv (Standard). Das gilt auch für Benutzer mit konfiguriertem TOTP.
totp_optional:: Die Zwei-Faktor-Authentifizierung über TOTP ist optional. Benutzer mit aktiviertem TOTP, müssen dieses verwenden.
totp_mandatory:: TOTP ist zwingend erforderlich. Benutzer ohne aktiviertes TOTP können sich nicht mehr anmelden.


==== Benutzer-spezifische Einrichtung

Die Einrichtung erfolgt über die xref:server:components/opsiconfd.adoc#server-components-opsiconfd-admin-page[opsiconfd Admin-Seite] im Tab *Users*.
Über eine Klick auf den Button *Generate new secret and activate TOTP* wird Server-seitig ein Secret generiert und die Zwei-Faktor-Authentifizierung für den jeweiligen Benutzer aktiviert. Der angezeigte QR-Code kann in einer entsprechenden App, wie z.B. *2FA Authenticator (2FAS)* für Android und iOS, gescannt werden. Die App generiert daraufhin alle 30 Sekunden ein neues Einmal-Passwort. Das Passwort muss bei der Authentifizierung an das normale Kennwort angehängt werden.

IMPORTANT: Ein erneuter Klick auf den Button *Generate new secret and activate TOTP* erzeugt ein neues Secret.
Das bisherige Secret (QR-Code) des Benutzers verliert damit seine Gültigkeit.

Über einen Klick auf den Button *Deactivate MFA* wird die Zwei-Faktor-Authentifizierung für den jeweiligen Benutzer deaktiviert.
