////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      08.05.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]


[[authorization]]
== Autorisierung

[[authorization-users-and-groups]]
=== Benutzer und Gruppen
Für die Steuerung von Berechtigungen verwendet opsi die folgenden Gruppen:

* {opsi-admin-group}: Mitglieder dieser Gruppe können administrativ auf den {opsi-service} zugreifen.
Mitglieder dieser Gruppe erhalten daher Vollzugriff über {opsi-configed}, {opsi-WebGUI}, opsiconfd-Admin-Interface, etc. +
Standardmäßig ist der Name dieser Gruppe `opsiadmin`.
* {opsi-file-admin-group}: Mitglieder dieser Gruppe können administrativ auf opsi-Dateien (Depot, Repository, Workbench) zugreifen. +
Standardmäßig ist der Name dieser Gruppe `opsifileadmins`.
* {opsi-read-only-group}: Mitglieder dieser Gruppe können nur lesend auf den {opsi-service} zugreifen. +
Standardmäßig ist der Name dieser Gruppe `opsireadonlys`.

Die Namen dieser Gruppen können in der Konfigurationsdatei `/etc/opsi/opsi.conf` im Abschnitt `groups` geändert werden.

Beispiel:
[source,toml]
----
[groups]
fileadmingroup = "opsifileadmins"
admingroup = "opsiadmin"
readonly = "opsireadonlys"
----

Die folgenden Benutzer werden von opsi verwendet:

* opsionfd: Ein Service-Benutzer unter dessen Account der zentrale opsi-Service `opsiconfd` läuft.
Der Benutzer muss Mitglied der {opsi-admin-group} und {opsi-file-admin-group} sein.
* pcpatch: Bei Verwendung von CIFS (Samba) für den Zugriff auf das {opsi-depot} verwenden die {opsi-clients} diesen Account für die Authentifizierung. Der Benutzer muss Mitglied der Gruppe {opsi-file-admin-group} sein.

Standardmäßig werden auf einem {opsi-server} lokale Benutzer und Gruppen verwendet.
Diese werden mit den Linux-Standard-Werkzeugen, wie `useradd`, `usermod`, `groupadd`, `groupmod`, etc., verwaltet.

Es besteht jedoch auch die Möglichkeit der Anbindung eines {opsi-configserver}s an eine zentrale Authentifizierung.

Weitere Informationen hierzu finden Sie unter
xref:server:configuration/authorization.adoc#authorization-domain-join[]
und
xref:server:configuration/authorization.adoc#authorization-ldap-authentication[].


[[authorization-pcpatch-password]]
=== Passwort für den Benutzer pcpatch

Da der Benutzer von den {opsi-clients} für die Authentifizierung verwendet wird,
muss das Passwort dem {opsi-configserver} bekannt sein.
Für diesen Zweck wird das Kennwort auf dem {opsi-configserver} verschlüsselt abgelegt.

Das Passwort kann über `opsi-admin` geändert werden:

[source,shell]
----
opsi-admin -d task setPcpatchPassword
----

Nach dem Betätigen von [Eingabe] erscheint ein Passwort-Prompt, und Sie können das Kennwort eintippen.

Hierbei wird das Kennwort zusätzlich für den lokalen `opsi-admin` Unix- und Samba-Account geändert.
Sollten der Account kein lokaler, sondern ein Domänen-Account sein, muss das Kennwort zusätzlich manuell in der Domäne neu gesetzt werden.

NOTE: Im Zuge der Grund-Installation eines {opsi-configserver}s wird bereits vollautomatsich ein Zufalls-Kennwort gesetzt,
das nicht geändert werden muss.


[[authorization-create-local-users]]
=== Anlegen von Admin-Konten auf dem {opsi-configserver}

Bei Verwendung von lokalen Benutzen und Gruppen auf dem {opsi-configserver},
müssen Benutzer, die Zugriff auf den {opsi-server} erhalten sollen, über die Linux-Standard-Werkzeugen angelegt werden:

Im folgenden Beispiel wird ein neuer Benutzer `adminuser` angelegt, der Vollzugriff auf den {opsi-server} erhält.

NOTE: Sowohl auf der vorkonfigurierten virtuellen Maschine, als auch im Docker-Container existiert der Account `adminuser` bereits`. Sie können jedoch mit dem selben Verfahren weitere Benutzer hinzufügen.

Legen Sie das neue Benutzer-Konto über den Befehl `useradd` an:
[source,shell]
----
sudo useradd -m -s /bin/bash adminuser
----

Anschließend setzen Sie für den neuen Account ein Unix-Passwort (System):

[source,shell]
----
sudo passwd adminuser
----

Soll der Benutzer auch Datei-Zugriff per CIFS (Samba) erhalten, muss auch hier ein Passwort gesetzt werden:

[source,shell]
----
sudo smbpasswd -a adminuser
----

WARNING: Verwenden Sie in den Passwörtern kein `§`-Zeichen!

Als Nächstes fügen Sie den neuen Benutzer den Gruppen `opsiadmin` und `opsifileadmins` hinzu:

[source,shell]
----
usermod -aG opsiadmin adminuser opsifileadmins
----

Mit dem Befehl `id` können Sie, zur Überprüfung, den Benutzer inklusive Gruppenzugehörigkeiten anzeigen lassen:

[source,shell]
----
id adminuser
# uid=1000(adminuser) gid=1000(opsiadmin) groups=1000(opsiadmin),999(opsifileadmins)
----


[[authorization-domain-join]]
=== Einbindung eines {opsi-server}s in eine Windows-Domäne

Statt mit lokalen Unix- und Samba-Accounts zu arbeiten, kann ein {opsi-server} auch in eine Windows- bzw. Samba4-Domäne eingebunden werden.

In der Domäne müssen die {opsi-admin-group} und {opsi-file-admin-group} angelegt werden.
Es können an dieser Stelle auch andere Gruppen-Namen oder bestehende Gruppen verwendet werden.
Die Namen der Gruppen müssen dann in der Konfigurations-Datei `/etc/opsi/opsi.conf` entsprechend angepasst werden.

Weitehin muss der Benutzer `pcpatch` als Mitglied der {opsi-file-admin-group}
und der Benutzer `opsiconfd` als Mitglied der {opsi-admin-group} und {opsi-file-admin-group} in der Domäne angelegt werden.

Die {opsi-admin-group} und {opsi-file-admin-group} müssen aus den lokalen Unix-Gruppen entfernt werden:

Auch die loaklen Unix-Benutzer `opsiconfd` und `pcpatch` müssen entfernt werden.

Danach nehmen Sie den {opsi-server}, gemäß der Dokumentation der verwendeten Linux-Distribution, in die Windows-Domäne ein.

Führen Sie nach dem Domain-Join die folgenden Befehle aus:

[source,shell]
----
opsiconfd setup
opsi-set-rights
----

Setzen Sie dann dann das Passwort des Benutzers `pcpatch` neu, wie im Abschnitt xref:server:configuration/authorization.adoc#authorization-pcpatch-password[] beschrieben.


[[authorization-ldap-authentication]]
=== Authentifizierung gegen LDAP/Active Directory

Für die Authentifizierung am opsi-Service wird standardmäßig _PAM_ verwendet.
Das funktioniert mit lokalen Benutzern und Gruppen, aber auch wenn der {opsi-server} in eine Domäne eingebunden ist.

Statt PAM für die Authentifizierung zu nutzen, ist es auch möglich einen LDAP-Server bzw. ein Active Directory zu verwenden.
Hierfür ist die link:https://www.uib.de/de/opsi-erweiterungen/erweiterungen[kostenpflichtige opsi Erweiterung] 'opsi directory connector' notwendig.

IMPORTANT: Die Samba-Authentifizierung ist hiervon unabhängig.
Das Verfahren eignet sich daher hauptsächlich für opsi-Umgebungen,
bei denen die opsi-Administratoren nicht per Samba, sondern per WebDAV, auf die opsi-Shares zugreifen.
Beim Betrieb eines {opsi-server}s unter Docker ist das immer der Fall.

Die Konfiguration findet über die Datei `/etc/opsi/opsi.conf` statt.
In der Sektion 'ldap_auth' muss hierfür die Option _ldap_url_ gesetzt werden.
Die ldap_url besitzt dabei den folgenden Aufbau:
`ldap[s]://<adresse-des-ldap-servers>[:port]/<base-dn>`

Zusätzlich kann die Option _username_ verwendet werden.
Damit kann definiert welcher Benutzername bei der Authentifizierung am LDAP/AD übergeben werden soll. Hierbei können die Platzhalter _\{username\}_ und _\{base\}_ verwendet werden. Im Normalfall ist jedoch die Angabe der _ldap_url_ ausreichend.

Beispiel zur Anbindung an ein Active Directory bzw. Samba 4:

[source,toml]
----
[ldap_auth]
ldap_url = "ldaps://ad.company.de/dc=ad,dc=company,dc=de"
----

Beispiel zur Anbindung an einen OpenLDAP:

[source,toml]
----
[ldap_auth]
ldap_url = "ldaps://ldap.company.org:636/dc=company,dc=org"
username = "uid={username},dc=Users,{base}"
----

Damit die Änderungen übernommen werden, muss der {opsiconfd} neu gestartet werden.

NOTE: Bitte beachten Sie, dass die in der Variable admingroup definierte Gruppe auch im AD/LDAP verfügbar ist.
