////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      08.05.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]


[[server-configuration-mysql]]
== MySQL

Der {opsi-configserver} benötigt Zugriff auf einen MySQL-Server.
Läuft der MySQL-Server auf der gleichen Maschine,
erfolgt die Konfiguration des MySQL-Servers in der Regel automatisch über das xref:server:configuration/opsiconfd.adoc#server-configuration-opsiconfd-setup[opsiconfd setup]. Auch Datenbank-Migrationen und Cleanup werden darüber durchgeführt.

Sollte die automatische Konfiguration nicht funktionieren oder soll ein externer MySQL-Server verwendet werden,
dann kann die Konfiguration manuell vorgenommen werden.

Hierfür kann der folgende Befehl verwendet werden:

[source,shell]
----
opsiconfd setup --configure-mysql
----

Das Programm fragt dann nach den Details zu der MySQL-Verbindung interaktiv ab.
Dann wird die opsi-Datenbank auf dem MySQL-Server angelegt und ein Benutzer-Account für den Zugriff erstellt.

Alternativ kann die MySQL-Konfiguration auch direkt in der Konfigurationsdatei `/etc/opsi/backends/mysql.conf` vorgenommen werden.
Nach der Anpassung der Konfigurationsdatei muss dann der Befehl `opsiconfd setup` ausgeführt werden,
der die opsi-Datenbank auf dem MySQL-Server erstellt oder aktualisiert.

