////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      08.05.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]


[[server-configuration-network]]
== Netzwerk-Konfiguration
Der opsi-Server ist IPv4- und IPv6-kompatibel.
In der Regel wir der opsi-Server mit einer Dual-Stack-Netzwerkkonfiguration (IPv4 und IPv6) betrieben.


[[server-configuration-network-ports]]
== Verwendete Netzwerk-Protokolle und -Ports

Der opsi-Server benötigt und seine Dienste verwenden eine Reihe von Netzwerk-Protokollen und Ports.

Allgemein benötigt ein opsi-Server die Möglichkeit DNS-Anfragen an Port *53/tcp+udp* zu versenden.

Ein opsi-Server benötigt Zugriff auf das Internet über HTTP und HTTPS.
In der Hauptsache für den Zugriff auf Distributions-Pakete (z.B. download.opensuse.org) und opsi-Pakete (download.uib.de).
Aber auch für einige andere Dinge wie Zugriff auf Grafana-Addons, etc.
Der Zugriff kann auch über einen xref:server:configuration/network.adoc#server-configuration-http-proxy[systemweit konfigurierten HTTP-Proxy] erfolgen.

Für den Zugriff des opsi-Configservers auf die opsi-Paket-Repositories der opsi-Depotserver muss die Verbindung auf den Port *4447/tcp* ermöglicht werden.

Für den Einsatz von `opsi-deploy-client-agent` sind die verwendete Ports anhängig vom Client-Betriebssystem.
Für Windows-Clients wird Zugriff auf den Client per CIFS-Protokoll (*445/tcp*) benötigt, für Linux- und MacOS-Clients über SSH (*22/tcp*).

Je nach xref:server:configuration/opsiconfd.adoc#server-configuration-opsiconfd-host-control[HostControl-Konfiguration]
benötigt der opsi-Server Zugriff auf den opsi-client-agent (Port *4441/tcp*).

Standardmäßig verwendet der zentrale opsi-Service *opsiconfd* den Port *4447/tcp*.
Alle Clients, Depotserver und Admin-Geräte benötigen Zugang zu diesem Port.

Bei Verwendung von xref:server:configuration/samba.adoc#server-configuration-samba[Samba / CIFS]
als Depot-Protokoll benötigen die opsi-Clients Zugriff auf den Port *445/tcp*.
Wird hingegen *WebDAV* als Depot-Protokoll eingesetzt, ist dies nicht erforderlich.

Bei Verwendung von Netboot über TFTP werden xref:server:configuration/tftpd.adoc#server-configuration-tftpd-ports-firewall[zusätzliche Ports benötigt].

Soll der Zugriff auf den opsi-Server per SSH möglich sein, muss der Port *22/tcp* eingehend erlaubt sein.


[[server-configuration-http-proxy]]
=== Proxy-Einstellungen

include::server:partial$http-proxy.adoc[]
