

Weiterhin gliedert der opsiconfd die Logs in Kanäle und Kontexte.
Damit lassen sich die Meldungen filtern, um nur die gewünschten Informationen im benötigten Detail-Grad zu erhalten.

Mit den Parameter *log-levels* lassen sich Log-Level pro Kanal setzen.
Über `.*:4,opsiconfd\.headers:8` werden generell nur Warnungen protokolliert,
Meldungen im Kanal *opsiconfd.headers* jedoch mit Log-Level *trace*.

Die Filterung nach Kontexten erfolgt über den Parameter *log-filter*.
Im opsiconfd wird im Wesentlichen der Kontext `client_address` verwendet.
Mittels `client_address=192.168.1.1,192.168.1.2` kann beispielsweise so gefiltert werden,
dass nur Meldungen angezeigt werden, die im Zusammenhang mit den Clients mit den IP-Adressen
192.168.1.1 und 192.168.1.2 stehen.

Ein direkter Zugriff auf das aktuelle Logging kann zum Beispiel über das opsiconfd-Admin-Interface erfolgen.

Auf der Kommandozeile können die Logs über den Befehl `opsiconfd log-viewer` direkt auf dem Terminal ausgegeben werden.
Zum Beispiel:

[source,shell]
----
opsiconfd log-viewer -l 6 --log-filter="client_address=192.168.1.1"
----

IMPORTANT: Der opsiconfd verwendet Redis um die Logs zu schreiben.
Über den Parameter *log-level* wird gesteuert bis zu welchem Log-Level Meldungen in den Redis-Stream übertragen werden.
Da `opsiconfd log-viewer` den Log-Stream direkt aus Redis liest, erfolgt auch die Log-Ausgabe maximal bis zur Stufe *log-level*.


[[server-configuration-opsiconfd-setup]]
== opsiconfd setup

include::server:partial$opsiconfd-setup.adoc[]


[[server-configuration-opsiconfd-host-control]]
== opsiconfd HostControl-Konfiguration

Über die HostControl-Funktionalität könne opsi-Clients gesteuert werden.

Seit opsi 4.3 wird das bevorzugt über den opsi-Message-Bus ausgeführt.
Es existiert jedoch weiterhin das bisherige Verfahren,
wobei der opsi-Configserver eine Verbindung zum opsi-client-agent aufbaut und über diese Verbindung Kommandos ausführt.

Weiterhin können Wake-On-LAN-Pakete im Netzwerk versendet werden um Clients bei Bedarf zu Starten.

// cSpell:ignore hostcontrol
Die HostControl-Konfiguration wird über die Konfigurationsdatei `/etc/opsi/backends/hostcontrol.conf` vorgenommen.

Konfigurations-Parameter sind hierbei:

* *useMessagebus*: +
Über diesen Parameter wird gesteuert, wie der opsi-Message-Bus für HostControl verwendet wird.
Hierbei sind folgende Werte möglich:
** *False*: Der opsi-Message-Bus wird nicht verwendet. +
Für jedes Kommando wird eine Verbindung zum opsi-client-agent aufgebaut. +
** *True*: Es wird ausschließlich der opsi-Message-Bus verwendet. +
Wenn ein Client nicht mit dem opsi-Message-Bus verbunden ist, gilt er als nicht erreichbar und das Kommando wird nicht ausgeführt.
Wenn alle Clients so konfiguriert sind, dass sie den opsi-Message-Bus verwenden, ist das die bevorzugte Einstellung.
** *hybrid* (Standardwert): Der opsi-Message-Bus wird verwendet, wenn der Client eine aktive Message-Bus-Verbindung hat. +
Falls nicht, wird eine Verbindung zum opsi-client-agent aufgebaut.

* *opsiclientdPort*: +
Netzwerk-Port für die Verbindungsaufnahme zu einem opsi-client-agent.

* *hostRpcTimeout*: +
Timeout in Sekunden bei der Verbindungsaufnahme zu einem opsi-client-agent.

* *resolveHostAddress*: +
Steht dieser Parameter auf *True*, wird bei einem Verbindungsaufbau vom opsi-Configserver zu opsi-client-agent die IP-Adresse des opsi-Clients bevorzugt über die Namensauflösung ermittelt.
Um die im Backend von opsi hinterlegte IP-Adresse zu bevorzugen ist dieser Parameter auf *False* zu setzen.

* *maxConnections*: +
Die maximale Anzahl simultaner Verbindungen zu opsi-client-agents.

* *broadcastAddresses*: +
Wake-On-LAN-Pakete werden an Netzwerk-Broadcast-Adressen gesendet. +
Über diesen Parameter findet eine Zuordnung von Netzwerk-Adressen zu Broadcast-Adressen in der folgende Form statt: +
`{ "<network-address>": { "<broadcast-address>": <port-list> } }` +
Einer Netzwerk-Adresse können mehrere Broadcast-Adressen zugeordnet werden.
Für jede Broadcast-Adresse können unterschiedliche Ports konfiguriert werden.
Die passenden Broadcast-Adressen werden auf Basis der, im opsi-Backend hinterlegten, IP-Adresse eines Clients ermittelt.
Ist die IP-Adresse hierbei Teil mehrerer Netzwerke, wird der spezifischste Eintrag verwendet. +
Beispiel: +
[source,shell]
----
"broadcastAddresses": {
		"0.0.0.0/0": {
			"255.255.255.255": [7, 9, 12287]
		},
		"10.10.0.0/16": {
			"10.10.1.255": [12287],
			"10.10.2.255": [12287]
		},
		"10.10.3.0/24": {
			"10.10.3.255": [12287]
		},
		"192.168.1.0/24": {
			"192.168.1.255": [12287, 9, 12287]
		}
	}
----
