////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      08.05.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-configuration-opsiconfd]]
= opsiconfd
Der *opsiconfd* ist der zentrale Dienst auf jedem {opsi-server}.


[[server-configuration-opsiconfd-server-id-role]]
== Server-Rolle
Ein opsi-Server kann die Rolle eines opsi-Configservers oder die eines opsi-Depotservers übernehmen.
Dies wird über die Konfigurationsdatei `/etc/opsi/opsi.conf` gesteuert.
Auch die ID des Servers wird seit opsi 4.3 hier konfiguriert.

NOTE: Beim Betrieb des opsi-Servers auf Docker, findet die Konfiguration über Umgebungsvariablen statt.

Beispiel für einen opsi-Configserver:

[source,toml]
----
[host]
id = "opsi.domain.tld"
key = "5b4324721a114195098bdaf3fab54a9f"
server-role = "configserver"

[service]
url = "https://localhost:4447"
----


Beispiel für einen opsi-Depotserver:
[source,toml]
----
[host]
id = "opsi-depot.domain.tld"
key = "a1b5098fabcaf315b13249cba1a24d17"
server-role = "depotserver"

[service]
url = "https://opsi.domain.tld:4447"
----

NOTE: Mit opsi 4.3 wurde dir `/etc/opsi/backends/jsonrpc.conf` durch die `/etc/opsi/opsi.conf` abgelöst.


[[server-configuration-opsiconfd-config]]
== opsiconfd Konfiguration

Die Konfiguration des opsiconfd kann über Umgebungsvariablen, Konfigurationsdatei (`/etc/opsi/opsiconfd.conf`) und Kommandozeilen-Parameter erfolgen.

Eine Liste der möglichen Konfigurations-Parameter erhalten Sie über den folgenden Befehl:

// cSpell:disable
[source,shell]
----
opsiconfd --help
----
// cSpell:enable

Im Hilfetext werden auch die Namen der Umgebungsvariablen ausgegeben, die verwendet werden können.
In der Konfigurationsdatei werden die Optionen ohne das vorangestellte `--` verwendet.

Listen werden in Umgebungsvariablen und Konfigurationsdatei als Komma-getrennte Werte in eckigen Klammern angegeben,
auf der Kommandozeile aber durch Leerzeichen getrennt.

Ein Beispiel:

// cSpell:disable
[source,configfile]
----
$ opsiconfd --help
...
--admin-networks ADMIN_NETWORKS [ADMIN_NETWORKS ...]
		A list of network addresses from which administrative connections are allowed.
		[env var: OPSICONFD_ADMIN_NETWORKS]
		(default: ['0.0.0.0/0', '::/0'])
...
----
// cSpell:enable

*Konfigurationsdatei* (`/etc/opsi/opsiconfd.conf`):
[source,configfile]
----
admin-networks = [10.1.1.0/24,192.168.1.0/24]
----

*Umgebungsvariable*:
[source,shell]
----
OPSICONFD_ADMIN_NETWORKS="[10.1.1.0/24,192.168.1.0/24]"
----

*Kommandozeilenparameter*:
[source,shell]
----
opsiconfd --admin-networks 10.1.1.0/24 192.168.1.0/24
----


Werden die einzelnen Ansätze miteinander kombiniert, gilt die folgende Reihenfolge:

. Einträge in der Konfigurationsdatei überschreiben die Defaults
. Umgebungsvariablen überschreiben Einträge in der Konfigurationsdatei
. Kommandozeilen-Parameter überschreiben Umgebungsvariablen


Änderungen an der Konfiguration können in der Regel über den Befehl `opsiconfd reload` in einen laufenden opsiconfd übernommen werden.

NOTE: Einige Konfigurations-Parameter werden nur über einen Neustart des opsiconfd aktiv.


[[server-configuration-opsiconfd-logs]]
== opsiconfd Logs
// cSpell:ignore log-viewer
Das Logging des opsiconfd findet normalerweise über Redis statt.
Zusätzlich werden im Verzeichnis `/var/log/opsi/opsiconfd` Log-Dateien abgelegt.

NOTE: Wenn Probleme mit dem Zugriff auf Redis bestehen, findet daher auch kein Logging statt.
Um in diesem Fall an Log-Meldungen zu kommen, kann das Logging über den Parameter `log-mode` auf `local` gestellt werden.

Opsi unterscheidet 10 verschiedene Log-Level:

0 - nothing:: Logging komplett deaktiviert
1 - essential:: Sehr wichtige Meldungen
2 - critical:: Kritische Fehler
3 - error:: Fehler
4 - warning:: Warnungen
5 - notice:: Wichtige Hinweise
6 - info:: Weitere Informationen
7 - debug:: Meldungen zur Fehlersuche
8 - trace:: Sehr hohe Details wie Kommunikationsmitschnitte
9 - secret:: Vertrauliche Informationen

Das Log-Level wird über die folgenden Parameter gesteuert:

log-level:: Allgemeines Log-Level in Richtung Redis
log-level-stderr:: Level der Ausgaben auf dem Terminal (stderr)
log-level-file:: Log-Level der Logdateien

Weiterhin gliedert der opsiconfd die Logs in Kanäle und Kontexte.
Damit lassen sich die Meldungen filtern, um nur die gewünschten Informationen im benötigten Detail-Grad zu erhalten.

Mit den Parameter *log-levels* lassen sich Log-Level pro Kanal setzen.
Über `.*:4,opsiconfd\.headers:8` werden generell nur Warnungen protokolliert,
Meldungen im Kanal *opsiconfd.headers* jedoch mit Log-Level *trace*.

Die Filterung nach Kontexten erfolgt über den Parameter *log-filter*.
Im opsiconfd wird im Wesentlichen der Kontext `client_address` verwendet.
Mittels `client_address=192.168.1.1,192.168.1.2` kann beispielsweise so gefiltert werden,
dass nur Meldungen angezeigt werden, die im Zusammenhang mit den Clients mit den IP-Adressen
192.168.1.1 und 192.168.1.2 stehen.

Ein direkter Zugriff auf das aktuelle Logging kann zum Beispiel über das opsiconfd-Admin-Interface erfolgen.

Auf der Kommandozeile können die Logs über den Befehl `opsiconfd log-viewer` direkt auf dem Terminal ausgegeben werden.
Zum Beispiel:

[source,shell]
----
opsiconfd log-viewer -l 6 --log-filter="client_address=192.168.1.1"
----

IMPORTANT: Der opsiconfd verwendet Redis um die Logs zu schreiben.
Über den Parameter *log-level* wird gesteuert bis zu welchem Log-Level Meldungen in den Redis-Stream übertragen werden.
Da `opsiconfd log-viewer` den Log-Stream direkt aus Redis liest, erfolgt auch die Log-Ausgabe maximal bis zur Stufe *log-level*.


[[server-configuration-opsiconfd-setup]]
== opsiconfd setup

include::server:partial$opsiconfd-setup.adoc[]


[[server-configuration-opsiconfd-host-control]]
== opsiconfd HostControl-Konfiguration

Über die HostControl-Funktionalität könne opsi-Clients gesteuert werden.

Seit opsi 4.3 wird das bevorzugt über den opsi-Messagebus ausgeführt.
Es existiert jedoch weiterhin das bisherige Verfahren,
wobei der opsi-Configserver eine Verbindung zum opsi-client-agent aufbaut und über diese Verbindung Kommandos ausführt.

Weiterhin können Wake-On-LAN-Pakete im Netzwerk versendet werden um Clients bei Bedarf zu Starten.

// cSpell:ignore hostcontrol
Die HostControl-Konfiguration wird über die Konfigurationsdatei `/etc/opsi/backends/hostcontrol.conf` vorgenommen.

Konfigurations-Parameter sind hierbei:

* *useMessagebus*: +
Über diesen Parameter wird gesteuert, wie der opsi-Messagebus für HostControl verwendet wird.
Hierbei sind folgende Werte möglich:
** *False*: Der opsi-Messagebus wird nicht verwendet. +
Für jedes Kommando wird eine Verbindung zum opsi-client-agent aufgebaut. +
** *True*: Es wird ausschließlich der opsi-Messagebus verwendet. +
Wenn ein Client nicht mit dem opsi-Messagebus verbunden ist, gilt er als nicht erreichbar und das Kommando wird nicht ausgeführt.
Wenn alle Clients so konfiguriert sind, dass sie den opsi-Messagebus verwenden, ist das die bevorzugte Einstellung.
** *hybrid* (Standardwert): Der opsi-Messagebus wird verwendet, wenn der Client eine aktive Messagebus-Verbindung hat. +
Falls nicht, wird eine Verbindung zum opsi-client-agent aufgebaut.

* *opsiclientdPort*: +
Netzwerk-Port für die Verbindungsaufnahme zu einem {opsi-client-agent}.

* *hostRpcTimeout*: +
Timeout in Sekunden bei der Verbindungsaufnahme zu einem {opsi-client-agent}.

* *resolveHostAddress*: +
Steht dieser Parameter auf *True*, wird bei einem Verbindungsaufbau vom opsi-Configserver zu opsi-client-agent die IP-Adresse des opsi-Clients bevorzugt über die Namensauflösung ermittelt.
Um die im Backend von opsi hinterlegte IP-Adresse zu bevorzugen ist dieser Parameter auf *False* zu setzen.

* *maxConnections*: +
Die maximale Anzahl simultaner Verbindungen zu opsi-client-agents.

* *broadcastAddresses*: +
Wake-On-LAN-Pakete werden an Netzwerk-Broadcast-Adressen gesendet. +
Über diesen Parameter findet eine Zuordnung von Netzwerk-Adressen zu Broadcast-Adressen in der folgende Form statt: +
`{ "<network-address>": { "<broadcast-address>": <port-list> } }` +
Einer Netzwerk-Adresse können mehrere Broadcast-Adressen zugeordnet werden.
Für jede Broadcast-Adresse können unterschiedliche Ports konfiguriert werden.
Die passenden Broadcast-Adressen werden auf Basis der, im opsi-Backend hinterlegten, IP-Adresse eines Clients ermittelt.
Ist die IP-Adresse hierbei Teil mehrerer Netzwerke, wird der spezifischste Eintrag verwendet. +
Beispiel: +
[source,shell]
----
"broadcastAddresses": {
		"0.0.0.0/0": {
			"255.255.255.255": [7, 9, 12287]
		},
		"10.10.0.0/16": {
			"10.10.1.255": [12287],
			"10.10.2.255": [12287]
		},
		"10.10.3.0/24": {
			"10.10.3.255": [12287]
		},
		"192.168.1.0/24": {
			"192.168.1.255": [12287, 9, 12287]
		}
	}
----