////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      02.05.2023
:Revision:  4.2
:toclevels: 6
:doctype:   book
:icons: font
:xrefstyle: full

[[opsi-create-client-intro]]
= Einführung

Damit opsi Rechner verwalten kann, müssen diese Clients dem System bekannt sein. Außerdem muss auf den Client-Rechnern ein Agent laufen, damit eine Kommunikation zwischen Server und Client möglich ist. Je nachdem, wie Ihre Umgebung aufgebaut ist, gibt es unterschiedliche Vorgehensweisen zum Hinzufügen von Clients:

* Existieren bereits Clients mit installiertem Betriebssystem, die opsi ab sofort verwalten soll, integrieren Sie diese (siehe Kapitel xref:windows-client:adding-clients.adoc[Vorhandene Clients integrieren]).

* Alternativ statten Sie einen Rechner über opsi zunächst mit einem neuen Betriebssystem aus. Dabei wird der benötigte Agent automatisch installiert (siehe Kapitel xref:windows-client:os-installtion.adoc[Neue Clients hinzufügen]).
