////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype: book
:winclientmanual: opsi-windows-client-manual

include::common:partial$opsi_terms.adoc[]


[[firststeps-software-deployment-product-tests]]
== Rollout of existing products

For the rollout of software on clients, the 'opsi-client-agent' must be installed on them.
This can be rolled out to <<firststeps-software-deployment-client-integration,existing computers>>.
With an <<firststeps-osinstall,operating system installation>> via opsi, the 'opsi-client-agent' is installed automatically.

In the following, the <<firststeps-software-deployment-configed,{opsi-configed}>> management interface is used to distribute software to clients.


The following products are provided by opsi for Windows as standard:

* `opsi-linux-client-agent`
* `swaudit`
* `hwaudit`
* `l-system-update`
* `opsi-configed`
* `opsi-logviewer`
* `opsi-auto-update`
* `opsi-linux-client-kiosk`
* `opsi-setup-detector`
* ``



//TODO 
// include::../common/firststeps-swdp-product-tests-configed.asciidoc[]

// include::../common/firststeps-swdp-product-tests-inventory.asciidoc[]


////
[[firststeps-software-deployment-client-integration]]
== Integration vorhandener Windows-Clients in opsi

Um vorhandene Windows-Clients in opsi aufzunehmen, muss auf diesen der {opsi-client-agent} installiert werden.
Dies kann auf mehrere Arten durchgeführt werden.
Nachdem Sie, wie im Folgenden beschrieben, den {opsi-client-agent} installiert haben, erscheint der Client auch in der Client-Liste des {opsi-configed}, sofern Sie ihn dort noch nicht hinzugefügt hatten.


Grundsätzlich gibt es die Möglichkeit die Installation des Agenten <<firststeps-software-deployment-client-integration-service-setup,auf dem Client auszuführen>> oder <<firststeps-software-deployment-client-integration-opsi-deploy,vom Server aus>> die Installation anzustoßen.

Das Ausführen der Installation direkt auf dem Client eignet sich für einzelne Rechner.
Für einen Massen-Rollout des Agenten eignet sich grundsätzlich der <<firststeps-software-deployment-client-integration-opsi-deploy,opsi-deploy-client-agent>>
besser, wenn die dazu nötigen Freischaltungen auf den Windows-Clients vorhanden sind.

Falls bereits eine andere Möglichkeit existiert Software zu verteilen, so ist es ebenfalls möglich darüber den opsi-client-agent zu verteilen und das im Paket mitgelieferte Script `silent_setup.sh` auszuführen.

Sobald der Agent installiert ist, können vorhandene opsi-Produkte auf diesen Clients <<firststeps-software-deployment-product-tests,installiert>> werden.




[[firststeps-software-deployment-client-integration-service-setup]]
=== Verwendung von service_setup.sh auf Windows


[[firststeps-software-deployment-client-integration-service-setup1]]
==== Verwendung von service_setup.sh auf Windows (Erst- oder Reperaturinstallation)


* Loggen Sie sich auf dem Client ein.
* Starten Sie das Terminal-Programm
* Für die folgenden Befehle müssen Sie die folgenden Platzhalter ersetzen:
**  `<username>` mit Ihrem login Namen
** `<mnt>` durch ein Verzeichnisnamen der noch nicht existiert z.B. 'mnt'
** `<serviceuser>` durch einen Usernamen der auf dem opsi-server bekannt ist.
** `<servicepass>` durch das Passwort des <serviceuser>. Sie können `:<servicepass>` zusammen mit der mount-Option `-N` auch weglassen, dann werden Sie nach dem Passwort gefragt
** `<opsi-server>` durch den Namen oder die IP-Nummer des opsi-servers

[source,prompt]
----
sudo su
cd /mnt
mount.cifs //<opsi-server>/opsi_depot /mnt -o user=<serviceuser>
cd /mnt/opsi-linux-client-agent
./service_setup.sh
cd
umount /mnt
----

bzw. ohne Passwortabfrage

[source,prompt]
----
sudo su
cd /mnt
mount.cifs //<opsi-server>/opsi_depot /mnt -o user=<serviceuser>, pass=<servicepass>
cd /mnt/opsi-linux-client-agent
./service_setup.sh
cd
umount /mnt
----

Beispiel:

[source,prompt]
----
sudo su
cd /mnt
mount.cifs //sepia/opsi_depot /mnt -o user=adminuser
cd /mnt/opsi-linux-client-agent
./service_setup.sh
cd
umount /mnt
----


. Starten Sie von dem gemounteten share das Script `opsi-linux-client-agent\service_setup.sh` +
Bestätigen Sie mit 2 x Enter
. Das Skript kopiert die notwendigen Dateien in ein temporäres lokales Verzeichnis und startet dann zur eigentlichen Installation opsi-script.
. Das Skript nimmt per opsi-Webservice Kontakt zum Server auf um serverseitig den Client zu erzeugen und den pckey zu erfahren. Dies erfolgt zunächst mit der in der config.ini eingetragenen user/password Kombination. Schlägt dies fehl, so erscheint ein Login-Fenster mit Service-URL ({opsi-configserver}), Benutzername und Passwort. Hier wird ein Benutzer benötigt, der Mitglied der Gruppe 'opsiadmin' ist. Möglich ist auch ein Benutzer, welcher nur die Methode `host_createOpsiClient` ausführen darf.

CAUTION: Der Client benötigt nach der Installation ein Reboot um aktiv zu werden. +
Der Reboot wird *nicht* automatisch ausgelöst.


[[firststeps-software-deployment-client-integration-opsi-deploy]]
=== Verwendung von opsi-deploy-client-agent für Windows

Das `opsi-deploy-client-agent` Skript verteilt den {opsi-client-agent} direkt vom {opsi-server} auf die Clients.
Es ist hiermit einfach möglich eine große Menge an Clients vom Server aus in eine opsi-Umgebung zu integrieren.
Voraussetzung hierfür sind bei den Clients:

* ein aktivierter ssh Zugang
* Administrativer User mit Passwort


Das `opsi-deploy-client-agent` Skript findet sich unter `/var/lib/opsi/depot/opsi-client-agent` +
Führen Sie das Script mit 'root' Rechten aus.
Falls das Script nicht ausführbar ist, so können Sie dieses Problem mit dem folgenden Befehl beheben: +
`opsi-set-rights /var/lib/opsi/depot/opsi-client-agent/opsi-deploy-client-agent`

Das Skript erzeugt serverseitig den Client, kopiert die Installations-Dateien und Konfigurationsinformationen, wie bspw. den pckey, auf den Client und startet dort die Installation. +
Die Installation läuft im Hintergrund ohne das ein User davon etwas bemerken muß.

Der Befehl `opsi-deploy-client-agent` hat eine Fülle von Aufrufparametern. +
Bei allen nachfolgenden Beispielen wird davon ausgegangen, das Sie in das Stammverzeichnis des opsi-client-agent Produktes gewechselt sind: +

[source,prompt]
----
cd /var/lib/opsi/depot/opsi-linux-client-agent
----

Typische Aufrufe sind:

* Für einen einzelnen Client:

[source,prompt]
----
./opsi-deploy-client-agent -v --user=uib uib-mmini1
----

Ergibt folgende Ausgabe:

[source,ini]
----
Password is required for deployment.
Password:
[5] [2021-02-04 16:43:43.121] [               ] Starting deployment to host uib-mmini1.uib.local   (posix.py:84)
[5] [2021-02-04 16:43:43.121] [               ] Querying for ip address of host uib-mmini1.uib.local   (common.py:158)
[5] [2021-02-04 16:43:43.122] [               ] Got ip address 192.168.10.70 from syscall   (common.py:167)
[5] [2021-02-04 16:43:43.123] [               ] Pinging host 192.168.10.70 ...   (common.py:183)
[5] [2021-02-04 16:43:44.146] [               ] Host 192.168.10.70 is up   (common.py:194)
[5] [2021-02-04 16:43:44.153] [               ] Patching config.ini   (posix.py:91)
[5] [2021-02-04 16:43:44.157] [               ] Copying installation scripts...   (posix.py:107)
[5] [2021-02-04 16:43:48.316] [               ] Running installation script...   (posix.py:147)
[5] [2021-02-04 16:43:53.382] [               ] opsi-client-agent successfully installed on uib-mmini1.uib.local   (posix.py:176)
[5] [2021-02-04 16:43:53.395] [               ] Restarting opsiclientd service on computer: uib-mmini1   (posix.py:331)
[5] [2021-02-04 16:43:55.620] [               ] 1/1 deployments successfully   (__init__.py:210)
----

* Für eine Liste von Clients:

[source,prompt]
----
./opsi-deploy-client-agent -v --user=uib --hosts-from-file HOSTFILE.TXT  --skip-existing-clients
----

Hier ist HOSTFILE.TXT eine Datei mit einem Clientnamen (FQDN) pro Zeile. Soweit die Clients dem opsi-server noch nicht bekannt sind, wird versucht den `opsi-linux-client-agent` auf dieser Maschine zu installieren

* Anzeigen alle Kommandozeilen Parameter:

[source,prompt]
----
./opsi-deploy-client-agent --help
----


[[firststeps-software-deployment-product-tests]]
== Rollout existierender Produkte auf Windows

Für den Rollout von Software auf Clients muss auf diesen der 'opsi-client-agent' installiert sein.
Dieser kann auf <<firststeps-software-deployment-client-integration,bestehende Rechner>> ausgerollt werden.


Nachfolgend wird die Management-Oberfläche <<firststeps-software-deployment-product-tests-configed,{opsi-configed}>> verwendet, um Software auf Clients zu verteilen.


Folgende Produkte werden von opsi für Windows als Standard zur Verfügung gestellt:

* `opsi-linux-client-agent`
* `swaudit`
* `hwaudit`
* `l-system-update`
* `opsi-configed`
* `opsi-logviewer`
* `opsi-auto-update`
* `opsi-linux-client-kiosk`
* `opsi-setup-detector`
* ``



include::../common/firststeps-swdp-product-tests-configed.asciidoc[]

include::../common/firststeps-swdp-product-tests-inventory.asciidoc[]
////

////
[[opsi-winclient-std-netboot-packages]]
=== opsi-netboot Pakete zur OS Installation von Windows durch opsi
////
