////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype: book
:winclientmanual: opsi-windows-client-manual

include::common:partial$opsi_terms.adoc[]



[[firststeps-software-deployment-product-tests]]
= Rollout existierender Produkte

Für den Rollout von Software auf Clients muss auf diesen der _opsi-client-agent_ installiert sein.
Dieser kann auf xref:adding-clients.adoc#firststeps-software-deployment-client-integration[bestehende Rechner] ausgerollt werden.
Bei einer xref:os-installation.adoc#firststeps-osinstall[Betriebssysteminstallation] über opsi wird der _opsi-client-agent_ automatisch installiert.

Nachfolgend wird die Management-Oberfläche xref:opsiconfiged.adoc#firststeps-software-deployment-configed[{opsi-configed}] verwendet, um Software auf Clients zu verteilen.


Folgende Produkte werden von opsi für Windows als Standard zur Verfügung gestellt:

* `opsi-linux-client-agent`
* `swaudit`
* `hwaudit`
* `l-system-update`
* `opsi-configed`
* `opsi-logviewer`
* `opsi-auto-update`
* `opsi-linux-client-kiosk`
* `opsi-setup-detector`
* ``


include::common:partial$firststeps-swdp-product-tests-configed.adoc[leveloffset=-1]

include::common:partial$firststeps-swdp-product-tests-inventory.adoc[leveloffset=-1]
