////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      02.10.2023
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

= Wichtige Hinweise

opsi 4.3 ist ein eigenständiges Release und hat seine eigenen Repositorys. Diese neuen Paketquellen tragen Sie in den entsprechenden Konfigurationsdateien Ihrer Systeme ein; entfernen Sie außerdem die Respoitorys der Vorgängerversion. Erst danach können Sie das Upgrade durchführen.

Für ein Upgrade von opsi 4.2 auf 4.3 müssen die installierten Pakete auf dem letzten Stand der 4.2-Version sein. Andere Pakete (wie z.{nbsp}B. der MySQL-Server) sollten ebenfalls aktuell sein -- andernfalls kann es beim Upgrade zu Fehlern kommen.

IMPORTANT: Achten Sie unbedingt darauf, dass Sie vor dem Upgrade die Pakete `opsi-script`, `opsi-client-agent`, `opsi-linux-client-agent` bzw. `opsi-mac-client-agent` auf allen Clients auf den aktuellen Stand bringen!

== Betriebssystem-Pakete aktualisieren

Stellen Sie sicher, dass Sie zum Zeitpunkt der Aktualisierung die jeweils aktuellsten Pakete von opsi 4.2 aus dem Stable-Bereich verwenden!

== opsi-Pakete aktualisieren

opsi-Pakete sind in der Regel kompatibel zu opsi 4.2 und opsi 4.3.

Die offiziellen link:https://opsipackages.43.opsi.org[4.3-Repositorys] enthalten Pakete, die zu opsi 4.3 kompatibel sind.

NOTE: Beachten Sie, dass die dort angebotenen Pakete nicht zwingend die Versionsnummer `4.3` im Namen haben müssen, damit sie unter opsi 4.3 lauffähig sind!

== Backend-Erweiterungen 

Die bisher in `/etc/opsi/backendManager/extend.d` hinterlegten Methoden zur Erweiterung sind jetzt fest implementiert im `opsiconfd`. Daher ist das Verzeichnis `/etc/opsi/backendManager/extend.d` in der Voreinstellung leer -- beim Upgrade wird es verschoben.

Sie können den Extend-Mechanismus aber weiterhin verwenden. Eigene Methoden zur Erweiterung verschieben Sie daher nach dem Upgrade auf opsi 4.3 wieder ins Verzeichnis `/etc/opsi/backendManager/extend.d`.

== Workbench, Depot und Repository

opsi 4.3 verwendet jetzt feste Verzeichnisse für Workbench, Depot und Repository unterhalb von `/var/lib/opsi`. Dynamische Zuweisungen über `depotLocalUrl`, `repositoryLocalUrl` und `workbenchLocalUrl` werden nicht mehr ausgewertet.

Wenn die Verzeichnisse Workbench, Depot und Repository an anderer Stelle liegen, dann verschieben Sie diese nach `/var/lib/opsi` oder legen Symlinks zu `/var/lib/opsi/workbench`, `/var/lib/opsi/depot` und `/var/lib/opsi/repository` an.

== opsi-Linux-Bootimage

Die Bootloader im opsi-Linux-Bootimage liegen jetzt unter `<TFTP-ROOT>/opsi/opsi-linux-bootimage/loader`. Sie heißen so:

* `opsi-netboot.bios`: Legacy-BIOS
* `opsi-netboot.efi`: UEFI-BIOS
* `shimx64.efi.signed`: UEFI Secure Boot

Bei Verwendung von Netboot/PXE muss die DHCP-Server-Konfiguration unter Umständen manuell angepasst werden (Option 67/ BootFile Name).

== Sortier-Algorithmus

Es existiert nur noch ein (neuer) Sortier-Algorithmus für Produkt-Aktionen; eine Unterscheidung von `algorithm1/algorithm2` entfällt. Der neue Algorithmus produziert weitestgehend die gleichen Ergebnisse wie der Vorgänger `algorithm1`.

== opsi-Tools

Die Werkzeuge `opsi-configed`, `opsi-setup-detector-setup`, das WebGUI und andere stehen jetzt unter https://tools.43.opsi.org/ zur Verfügung.

== Wichtige Neuerungen

* Direkter Datenbank-Zugriff nur noch über den `opsiconfd`; alle anderen Komponenten verwenden die API.
* Upgrade und Bereinigung der Datenbank erfolgen vollautomatisch.
* `opsiconfd` bietet jetzt einen Maintenance-Modus.
* IPv6-Unterstützung funktioniert nun für alle Komponenten.
* Produkt-Abhängigkeiten jetzt für jede Aktion definierbar.
* `/etc/opsi/opsi.conf` jetzt im TOML-Format. Vollautomatische Erstellung und Migration der `opsi.conf`. Sobald die Datei existiert, verwendet opsi den FQDN der Maschine nicht mehr.
* Server-Zertifikats-Prüfung ist in der Voreinstellung für alle Komponenten aktiviert, aber es erfolgt keine automatische Aktivierung beim Upgrade.
* Grafana fungiert jetzt in der Voreinstellung hinter `opsiconfd` als Reverse-Proxy.
* Neue Metriken im Grafana: _Worker Connections_, _Messagebus Messages sent_, _Messagebus Messages received_
* Repository-Meta-Dateien (`packages.json`) zur Verwendung durch `opsi-package-updater`
* opsi-Pakete werden standardmäßig im tar.zstd-Format erzeugt.
* Clients erben die Einstellungen des zugeordneten Depots.
* Das Standardverzeichnis für temporäre Dateien ist jetzt `/var/lib/opsi/tmp`.
* `opsi-configed` kann Clients kopieren.
* Wechsel zu Python 3.11
* `hostControl_`-Methoden werden bevorzugt über den opsi-Messagebus ausgeführt (Konfiguration über `useMessagebus` in `/etc/opsi/backends/hostcontrol.conf`).
* `opsi-setup` wurde durch `opsiconfd setup` ersetzt.
* `opsi-backup` wurde durch `opsiconfd backup`/`opsiconfd restore` ersetzt.
