////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      02.10.2023
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

= Upgrade von opsi 4.2 auf 4.3

Auf xref:supportmatrix:supportmatrix.adoc[unterstützten Betriebsystemen] ist es möglich, eine bestehende opsi-4.2-Installation auf opsi 4.3 zu aktualisieren.

NOTE: Ein Wechsel von opsi 4.1 direkt auf opsi 4.3 wird nicht unterstützt. Sie müssen erst auf opsi 4.2 aktualisieren, bevor Sie das Upgrade auf opsi 4.3 durchführen können.

TIP: Falls Sie Ihre opsi-Server mit opsi selbst verwalten, können Sie das Upgrade mit dem Localboot-Produkt `l-opsi-server-migrate` durchführen.

== Backup erstellen

Erstellen Sie vor dem Upgrade unbedingt eine Sicherung:

[source,console]
----
opsi-backup create
----

TIP: Ab opsi 4.3 übernimmt der `opsiconfd` das Backup und die Wiederherstellung (`opsiconfd backup` / `opsiconfd restore`). Lesen Sie dazu auch das Kapitel xref:server:components/backup.adoc[Backup des opsi-Servers].


== Neue Repositorys eintragen

Als Erstes tragen Sie die opsi-4.3-Repositorys in die Konfigurationsdateien Ihres Betriebssystems ein. Fügen Sie außerdem den GPG-Schlüssel des Repositorys hinzu. Dazu benötigen Sie Root-Rechte.

So sehen die Befehle für die unterstützten Betriebssysteme aus:

*Debian 11 _Bookworm_:*
[source,console]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_12/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_12/Release.key | sudo apt-key add -
----

*Debian 11 _Bullseye_:*
[source,console]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_11/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_11/Release.key | sudo apt-key add -
----

*Debian 10 _Buster_:*
[source,console]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_10/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_10/Release.key | sudo apt-key add -
----

*Ubuntu 22.10 LTS _Kinetic Kudu:*
[source,console]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/xUbuntu_22.10/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/xUbuntu_22.10/Release.key | sudo apt-key add -
----

*Ubuntu 22.04 LTS _Jammy Jellyfish_:*
[source,console]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/xUbuntu_22.04/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/xUbuntu_22.04/Release.key | sudo apt-key add -
----

*Ubuntu 20.04 LTS _Focal Fossa_:*
[source,console]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/xUbuntu_20.04/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/xUbuntu_20.04/Release.key | sudo apt-key add -
----

*RHEL 9:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/RHEL_9/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*RHEL 8:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/RHEL_8/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*AlmaLinux 9:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/AlmaLinux_9/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*AlmaLinux 8:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/AlmaLinux_8/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*Rocky Linux 9:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/RockyLinux_9/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*Rocky Linux 8:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/RockyLinux_8/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*SLES 15 SP 1:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3{release}/SLE_15_SP1/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*SLES 15 SP 2:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/SLE_15_SP1/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*SLES 15 SP 3:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/SLE_15_SP3/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*SLES 15 SP 4:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/SLE_15_SP3/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*openSUSE Leap 15.4:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/openSUSE_Leap_15.4/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*Univention UCS 5.0:*
[source,console]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Univention_5.0/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Univention_5.0/Release.key | sudo apt-key add -
----

== Betriebssystem-Pakete aktualisieren

Nachdem Sie die neuen Paketquellen eingetragen haben, können Sie jetzt das Upgrade beginnen. Dazu benötigen Sie ebenfalls Root-Rechte.

IMPORTANT: Bei RPM-basierten Distributionen werden während des Upgrades vorhandene Konfigurationsdateien durch neue ersetzt. Beachten Sie hierzu die Hinweise für die entsprechenden Distributionen.

=== Debian und Ubuntu

*Single-Server-Setup:*
[source,console]
----
apt update
apt install opsi-server-full
----

*Manuelles Setup:*
[source,console]
----
apt update
apt install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
apt dist-upgrade
----

=== RHEL, AlmaLinux und Rocky Linux

*Single-Server-Setup:*
[source,console]
----
yum makecache
yum install opsi-server-full
yum upgrade
----

*Manuelles Setup:*
[source,console]
----
yum makecache
yum install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
yum upgrade
----

=== SLES und openSUSE Leap

*Single-Server-Setup:*
[source,console]
----
zypper refresh
zypper install opsi-server-full
----

*Manuelles Setup:*
[source,console]
----
zypper refresh
zypper install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
zypper dup --from home_uibmz_opsi_4.3_{release}
----

=== Univention Corporate Server (UCS)

*Single-Server-Setup:*
[source,console]
----
univention-install opsi-server-full
----

*Manuelles Setup:*
[source,console]
----
univention-install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
univention-install opsi-server
----

== Konfiguration anpassen

Diese beiden Änderungen sind optional aber empfohlen:

* Setzen Sie `opsiclientd.config_service.permanent_connection = true`, um die Kommunikation von Clients und Server über den opsi-Messagebus zu aktivieren.

* Setzen Sie `opsiclientd.global.verify_server_cert = true`, damit die opsi-Clients die SSL-Serverzertifikate der Server überprüfen.

[[opsi-4.3-releasenotes-installation-migration-opsi-packages-standard]]
== opsi-Pakete aktualisieren

Der letzte Schritt ist die Aktualisierung auf die neuesten opsi-Pakete.

Wenn Sie die Standardeinstellungen unter `/etc/opsi/package-updater.repos.d/` nicht verändert haben, führen Sie das Upgrade der opsi-Pakete mit diesem Kommando durch:

[source,console]
----
opsi-package-updater -v update
----

Ihr opsi-4.2-Server ist nun auf Version 4.3 aktualisiert worden und einsatzbereit.
