////
; Copyright (c) uib GmbH (uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      02.10.2023
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



= OPSI-Upgrade

Dieses Kapitel beschreibt, wie Sie OPSI aktualisieren -- konkret geht es um das Upgrade von OPSI 4.2 auf OPSI 4.3.

NOTE: Auf Serverseite ist die Unterstützung der Linux-Distributionen fast genauso wie unter OPSI 4.2. Eine genaue Aufstellung der unterstützten Linux-Distributionen für den OPSI-Server bietet unsere xref:supportmatrix:supportmatrix.adoc[OPSI-Support-Matrix].

Die einzelnen OPSI-Komponenten hängen an vielen Stellen voneinander ab.
Sie sollten daher immer das komplette System auf die neue Version aktualieren.

Wir empfehlen, zuerst den Server und danach die OPSI-Pakete (Produkte) zu aktualisieren.
In einer Multi-Depot-Umgebung muss das Upgrade erst auf dem Configserver und danach auf den Depots ausgeführt werden.

OPSI 4.3 verwendet nur noch, das jetzt freie, MySQL-Backend.
Die Migration von einem File-Backend erfolgt automatisch beim Upgrade der Serverpakete.

== Vorbereitungen

Bevor Sie mit dem Upgrade Ihrer OPSI-Umgebung beginnen, sollten Sie einen Upgrade-Check ausführen, der Ihnen Hinweise auf potenzielle Probleme gibt:

[source,console]
----
opsiconfd health-check --upgrade-check
----

Beheben Sie möglichst alle angezeigten Probleme, bevor Sie mit das Upgrade durchführen.
