////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      02.10.2023
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

= opsi-Upgrade

Dieses Kapitel beschreibt, wie Sie opsi aktualisieren -- konkret geht es um das Upgrade von opsi 4.2 auf opsi 4.3.

NOTE: Auf Serverseite ist die Unterstützung der Linux-Distributionen fast genauso wie unter opsi 4.2.

Eine genaue Aufstellung der unterstützten Linux-Distributionen für den opsi-Server bietet unsere xref:supportmatrix:supportmatrix.adoc[opsi-Support-Matrix].

Die einzelnen opsi-Komponenten hängen an vielen Stellen voneinander ab.
Sie sollten daher immer das komplette System auf die neue Version aktualieren.

Wir empfehlen, zuerst den Server und danach die opsi-Pakete (Produkte) zu aktualisieren.
In einer Multi-Depot-Umgebung muss das Upgrade erst auf dem Configserver und danach auf den Depots ausgeführt werden.

opsi 4.3 verwendet nur noch, das jetzt freie, MySQL-Backend.
Die Migration von einem File-Backend erfolgt automatisch beim Upgrade der Serverpakete.

== Vorbereitungen

Bevor Sie mit dem Upgrade Ihrer opsi-Umgebung beginnen, sollten Sie einen Upgrade-Check ausführen, der Ihnen Hinweise auf potentielle Probleme gibt.

[source,console]
----
opsiconfd health-check --upgrade-check
----

Beheben Sie möglichst alle angezeigten Probleme bevor Sie mit das Upgrade durchführen.
