////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      29.09.2023
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

= Upgrade von opsi 4.2 auf 4.3

Auf unterstützten Betriebsystemen ist es möglich, eine bestehende opsi 4.2-Installation auf opsi 4.3 zu migrieren.

Falls die opsi-Server durch opsi verwaltet werden, kann die Migration über das Paket `l-opsi-server-migrate` durchgeführt werden.

NOTE: Eine Aktualisierung von opsi 4.1 direkt auf opsi 4.3 wird nicht unterstützt. In diesen Fällen muss erst eine Aktualisierung auf opsi 4.2 durchgeführt werden, bevor eine Aktualisierung auf opsi 4.3 möglich ist.



== Wechseln zu den neuen Repositories

Als erstes müssen die opsi 4.3-Repositories in die Paketquellen Ihres Betriebsystems eingetragen werden.

Die nachfolgenden Befehle fügen die neuen Repositories und, sofern benötigt, den Repository-Schlüssel hinzu.
Diese folgenden Befehle benötigen 'root'-Rechte.


*Ubuntu 22.04 LTS _ Jammy Jellyfish_:*
[source,prompt]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/xUbuntu_22.04/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/xUbuntu_22.04/Release.key | sudo apt-key add -
----

*Ubuntu 20.04 LTS _Focal Fossa_:*
[source,prompt]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/xUbuntu_20.04/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/xUbuntu_20.04/Release.key | sudo apt-key add -
----

*Debian 11 _Bullseye_:*
[source,prompt]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_11/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_11/Release.key | sudo apt-key add -
----

*Debian 10 _Buster_:*
[source,prompt]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_10/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_10/Release.key | sudo apt-key add -
----


*AlmaLinux 9:*
[source,prompt]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/AlmaLinux_9/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*AlmaLinux 8:*
[source,prompt]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/AlmaLinux_8/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*RockyLinux_9:*
[source,prompt]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/RockyLinux_9/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*RockyLinux_8:*
[source,prompt]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/RockyLinux_8/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*RHEL 8:*
[source,prompt]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/RHEL_8/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*openSUSE Leap 15.4:*
[source,prompt]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/openSUSE_Leap_15.4/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----


*SLES 15 SP 1:*
[source,prompt]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3{release}/SLE_15_SP1/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*SLES 15 SP 2:*
[source,prompt]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/SLE_15_SP1/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*SLES 15 SP 3:*
[source,prompt]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/SLE_15_SP3/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*SLES 15 SP 4:*
[source,prompt]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/SLE_15_SP3/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*Univention UCS 5.0:*
[source,prompt]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Univention_5.0/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Univention_5.0/Release.key | sudo apt-key add -
----

*Univention UCS 4.4:*
[source,prompt]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Univention_4.4/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Univention_4.4/Release.key | sudo apt-key add -
----



== Aktualisierung der Betriebssystem-Pakete

Nach dem Eintragen der neuen Paketquellen kann das System migriert werden.

IMPORTANT: Bei RPM-basierten Distributionen werden im Rahmen der Migration bereits vorhandene Konfigurationsdateien durch neue ersetzt. Beachten Sie hierzu die Hinweise unter den entsprechenden Distributionen.

Debian und Ubuntu werden mit folgenden Befehlen auf opsi 4.3 aktualisiert:

*Single-Server-Setup:*
[source,prompt]
----
apt update
apt install opsi-server-full
----

*Manuelles Setup:*
[source,prompt]
----
apt update
apt install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
apt dist-upgrade
----

RedHat, AlmaLinux und RockyLinux werden mit folgenden Befehlen auf opsi 4.3 aktualisiert:

*Single-Server-Setup:*
[source,prompt]
----
yum makecache
yum install opsi-server-full
yum upgrade
----

*Manuelles Setup:*
[source,prompt]
----
yum makecache
yum install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
yum upgrade
----

OpenSUSE bzw SUSE Linux Enterprise Server (SLES) wird mit folgenden Befehlen auf opsi 4.3 aktualisiert:

*Single-Server-Setup:*
[source,prompt]
----
zypper refresh
zypper install opsi-server-full
----

*Manuelles Setup:*
[source,prompt]
----
zypper refresh
zypper install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
zypper dup --from home_uibmz_opsi_4.3_{release}
----

Univention UCS wird mit folgenden Befehlen auf opsi 4.3 aktualisiert:

*Single-Server-Setup:*
[source,prompt]
----
univention-install opsi-server-full
----

*Manuelles Setup:*
[source,prompt]
----
univention-install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
univention-install opsi-server
----


== Konfiguration 

* Optional: Die Konfiguration opsiclientd.config_service.permanent_connection = true setzen, um die Kommunikation von Clients und Server über den opsi-Messagebus zu aktivieren.

* Optional: Die Konfiguration opsiclientd.global.verify_server_cert = true setzen, um die Server-Zertifikats-Prüfung der Clients zu aktivieren.

== Aktualisierung der opsi-Pakete

Der letzte Schritt ist die Aktualisierung auf die neuesten opsi-Pakete.

[[opsi-4.3-releasenotes-installation-migration-opsi-packages-standard]]
=== Verwendung der Standardkonfiguration

Wenn Sie keine Veränderungen gegenüber der Standard-Auslieferung unter `/etc/opsi/package-updater.repos.d/` vorgenommen haben, können Sie die opsi-Pakete direkt über den aufgeführten Aufruf aktualisieren:

[source, prompt]
----
opsi-package-updater -v update
----


Nach diesen Schritten ist Ihr opsi 4.2 Server auf das Release 4.3 migriert und einsatzbereit.


