////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      02.10.2023
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

= Upgrade von opsi 4.2 auf 4.3

Auf xref:supportmatrix:supportmatrix.adoc[unterstützten Betriebsystemen] ist es möglich, eine bestehende opsi-4.2-Installation auf opsi 4.3 zu aktualisieren.

NOTE: Ein Wechsel von opsi 4.1 direkt auf opsi 4.3 wird nicht unterstützt. Sie müssen erst auf opsi 4.2 aktualisieren, bevor Sie das Upgrade auf opsi 4.3 durchführen können.

TIP: Falls Sie Ihre opsi-Server mit opsi selbst verwalten, können Sie das Upgrade mit dem Localboot-Produkt `l-opsi-server-migrate` durchführen.

== Backup erstellen

Erstellen Sie vor dem Upgrade unbedingt eine Sicherung:

[source,console]
----
opsi-backup create
----

TIP: Ab opsi 4.3 übernimmt der `opsiconfd` das Backup und die Wiederherstellung (`opsiconfd backup` / `opsiconfd restore`). Lesen Sie dazu auch das Kapitel xref:server:components/backup.adoc[Backup des opsi-Servers].


== Neue Repositorys eintragen


Als Erstes tragen Sie die opsi-4.3-Repositorys in die Konfigurationsdateien Ihres Betriebssystems ein. Fügen Sie außerdem den GPG-Schlüssel des Repositorys hinzu. Dazu benötigen Sie Root-Rechte.

Stellen Sie sicher, dass das Verzeichnis `/usr/local/share/keyrings` existiert:

[source,console]
----
sudo mkdir -p /usr/local/share/keyrings
----

So sehen die Befehle für die unterstützten Betriebssysteme aus:

*Debian 12 _Bookworm_:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_12
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" > /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----

*Debian 11 _Bullseye_:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_11
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" > /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----

*Debian 10 _Buster_:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_10
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" > /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----


*Ubuntu 22.04 LTS, _Jammy Jellyfish_:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/xUbuntu_22.04
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" > /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----

*Ubuntu 20.04 LTS _Focal Fossa_:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/xUbuntu_20.04
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" > /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----

*RHEL 9:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/RHEL_9/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*RHEL 8:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/RHEL_8/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*AlmaLinux 9:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/AlmaLinux_9/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*AlmaLinux 8:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/AlmaLinux_8/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*Rocky Linux 9:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/RockyLinux_9/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*Rocky Linux 8:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/RockyLinux_8/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*SLES 15 SP 1:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3{release}/SLE_15_SP1/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*SLES 15 SP 2:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/SLE_15_SP1/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*SLES 15 SP 3:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/SLE_15_SP3/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*SLES 15 SP 4:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/SLE_15_SP3/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*openSUSE Leap 15.4:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/openSUSE_Leap_15.4/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*Univention UCS 5.0:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Univention_5.0
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" > /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----

== Betriebssystem-Pakete aktualisieren

Nachdem Sie die neuen Paketquellen eingetragen haben, können Sie jetzt das Upgrade beginnen. Dazu benötigen Sie ebenfalls Root-Rechte.

IMPORTANT: Bei RPM-basierten Distributionen werden während des Upgrades vorhandene Konfigurationsdateien durch neue ersetzt. Beachten Sie hierzu die Hinweise für die entsprechenden Distributionen.

=== Debian und Ubuntu

[source,console]
----
apt update
apt dist-upgrade
----


=== RHEL, AlmaLinux und Rocky Linux

[source,console]
----
yum makecache
yum upgrade
----


=== SLES und openSUSE Leap

*Single-Server-Setup:*
[source,console]
----
zypper refresh
zypper update
----


=== Univention Corporate Server (UCS)


[source,console]
----
univention-upgrade
----


== Konfiguration anpassen

Diese beiden Änderungen sind optional aber empfohlen:

* Setzen Sie `opsiclientd.config_service.permanent_connection = true`, um die Kommunikation von Clients und Server über den opsi-Messagebus zu aktivieren.

* Setzen Sie `opsiclientd.global.verify_server_cert = true`, damit die opsi-Clients die SSL-Serverzertifikate der Server überprüfen.

[[opsi-4.3-releasenotes-installation-migration-opsi-packages-standard]]
== opsi-Pakete aktualisieren

Der letzte Schritt ist die Aktualisierung auf die neuesten opsi-Pakete.

Wenn Sie die Standardeinstellungen unter `/etc/opsi/package-updater.repos.d/` nicht verändert haben, führen Sie das Upgrade der opsi-Pakete mit diesem Kommando durch:

[source,console]
----
opsi-package-updater -v update
----

Ihr opsi-4.2-Server ist nun auf Version 4.3 aktualisiert worden und einsatzbereit.
