////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      06.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

= Produkte auf Clients ausrollen

Als Nächstes führen wir das Produkt **hwaudit** auf allen Clients aus, das eine Hardware-Inventarisierung jedes Geräts erstellt.
In dieser Anleitung verwenden wir dazu die xref:gui:configed.adoc[Management-Oberfläche *opsi-configed*]. Alternativ können Sie das Produkt auch über das xref:gui:webgui.adoc[opsi-WebGUI] ausrollen.

TIP: Eine ausführliche Beschreibung zu Produkten, zum Ausrollen auf den Clients und mehr finden Sie in den xref:clients:opsi-clients.adoc[Client-Handbüchern].

In der Oberfläche wählen Sie zunächst einen oder mehrere Clients aus und wechseln dann zum Tab _Localboot-Produkte_.
Hier wählen Sie in der Liste das Produkt **hwaudit** aus und klicken in die Spalte _Angefordert_.
Aus dem sich öffnenden Drop-down-Menü wählen Sie den Eintrag _setup_.

Öffnen Sie das Kontextmenü mit der rechten Maustaste und wählen Sie den Eintrag _Speichern und jetzt ausführen_.
Das Produkt wird nun auf den selektierten Clients ausgeführt.
Sobald der Status auf _installed_ wechselt können Sie das Ergebnis der Inventarisierung im Tab _Hardware-Informationen_ einsehen.

Sie können nun weitere Produkte auf dem Server installieren und dann auf die Clients verteilen.

NOTE: Statt Produkte sofort auszuführen, können Sie auch bis zum nächsten Systemstart warten.
Beim Systemstart arbeiten die Clients die ausstehende Aktionen vor dem Benutzer-Login automatisch ab.
