////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      30.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

# Produkte auf die Clients ausrollen

Als nächstes führen wir das Produkt **hwaudit** auf allen Clients aus. Hierfür wird einer der zwei opsi-Benutzeroberflächen verwendet.
In dieser Anleitung verwenden wir den xref:gui:configed.adoc[opsi-configed]. Ein Beschreibung der {opsi-webgui} finden Sie im Kapitel xref:gui:webgui.adoc[opsi-webgui]

## opsi-configed herunterladen

Eine portable Version der opsi-configed Anwendung finden Sie unter: link:https://tools.43.opsi.org/{release}/[]
Laden Sie den configed herunter und führen Sie das Programm aus.

## Produkte verteilen

In der Oberfläche wählen Sie zunächst einen oder mehrere Clients aus und wechseln dann zum Tab **Localboot-Produkte**. 
Hier wählen Sie in der Liste das Produkt **hwaudit** aus und klicken in die Spalte **Angefordert**. Es öffnet sich ein Kontextmenü.
Hier wählen Sie **setup** aus. 

In der oberen Linken Ecke gibt es jetzt einen roten Haken. Die Einstellung wird durch Klicken des Hakens gespeichert.
Jetzt wird das Produkt **hwaudit** beim nächsten Systemstart der Clients installiert.

NOTE: Sie können die Installation auf laufenden Clients auch direkt starten. Hierfür klicken Sie über der Tabelle auf den Play-Button. Alternativ kann über das Rechtsklick-Menü `Jetzt (on demand) ausführen` gewählt werden.

NOTE: Eine genauere Beschreibung finden Sie im Kapitel xref:clients:windows-clients/rollout-products.adoc[opsi-Clients]
