////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      06.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

= Produkte auf Clients ausrollen

Als Nächstes installieren wir das Produkt `hwaudit` auf allen Clients. In dieser Anleitung verwenden wir dazu die xref:gui:configed.adoc[Management-Oberfläche *opsi-configed*]. Alternativ können Sie das Produkt auch über das xref:gui:webgui.adoc[opsi-WebGUI] ausrollen.

TIP: Eine ausführliche Beschreibung zu Produkten, zum Ausrollen auf den Clients und mehr finden Sie in den xref:clients:opsi-clients.adoc[Client-Handbüchern].

== Produkte verteilen

In der Oberfläche wählen Sie zunächst einen oder mehrere Clients aus und wechseln dann zum Tab _Localboot-Produkte_. 
Hier wählen Sie in der Liste das Produkt `hwaudit` aus und klicken in die Spalte _Angefordert_. Aus dem sich öffnenden Drop-down-Menü wählen Sie den Eintrag _setup_.

In der oberen linken Ecke gibt es jetzt einen roten Haken. Klicken Sie auf diesen, um die Einstellungen zu speichern. Beim nächsten Systemstart wird das Produkt `hwaudit` auf den Clients installiert.

NOTE: Sie können die Installation auf laufenden Clients auch direkt starten. Dazu klicken Sie über der Tabelle auf den Play-Button. Alternativ wählen Sie aus dem Kontextmenü der rechten Maustaste den Eintrag _Jetzt (on demand) ausführen_.

