////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      30.05.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-installation-deb]]
= Installation unter Debian/Ubuntu

Dieses Kapitel beschreibt die paketbasierte Installation eines opsi-Servers unter Debian und Ubuntu.

include::server:partial$package-based-start.adoc[]

== Konfiguration der Paketquellen

Installieren Sie zunächst die folgenden Pakete:

[source,console]
----
sudo apt --yes install host apt-transport-https software-properties-common curl gpg
----

Stellen Sie sicher, dass das Verzeichnis `/usr/local/share/keyrings` existiert:

[source,console]
----
sudo mkdir -p /usr/local/share/keyrings
----

Fügen Sie das Grafana-Repository zu den Paketquellen hinzu:

[source,console]
----
REPO_URL=https://apt.grafana.com
REPO_KEY=/usr/local/share/keyrings/grafana.gpg
curl -fsSL ${REPO_URL}/gpg.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL} stable main" > /etc/apt/sources.list.d/grafana.list
----

Fügen Sie das zu Ihrer Distribution passende opsi-Repository zu den Paketquellen hinzu:

*Debian 12, _Bookworm_:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/stable/Debian_12
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" > /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----

*Debian 11, _Bullseye_:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/stable/Debian_11
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" > /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----

*Debian 10, _Buster_:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/stable/Debian_10
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" > /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----

*Ubuntu 22.10, _Kinetic Kudu_:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/stable/xUbuntu_22.10/
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" > /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----

*Ubuntu 22.04 LTS, _Jammy Jellyfish_:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/stable/xUbuntu_22.04
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" > /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----

*Ubuntu 20.04 LTS, _Focal Fossa_:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/stable/xUbuntu_20.04
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" > /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----

Prüfen Sie, ob der Import des GnuPG-Schlüssels erfolgreich war:

[source,console]
----
gpg /usr/local/share/keyrings/opsi.gpg 2>/dev/null
----

In der Ausgabe sollten unter anderem folgende Zeilen auftauchen:

[source,console]
----
pub   rsa2048 2017-09-30 [SC] [expires: 2025-11-19]
      2E98F7B5A5B2C8FE7F609705D1F933E6D8361F81
uid           home:uibmz:opsi OBS Project <home:uibmz:opsi@build.opensuse.org>
----

== Installation der Pakete

Installieren Sie das Paket `opsi-server-full`:

[source,console]
----
sudo apt update
sudo apt --yes install opsi-server-full
----

include::server:partial$package-based-end.adoc[]

Der opsi-Server ist jetzt bereit für die xref:server:installation/next-steps.adoc[nächsten Schritte].
