////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      24.05.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-installation]]
= Installation und Inbetriebnahme


[[server-installation-hardware-requirements]]
== Hardware-Anforderungen

Sie können einen opsi-Server direkt auf Hardware, in einer virtuellen Maschine oder als Docker-Container betreiben.
Die Hardware-Anforderungen variieren stark. Je nach Größe Ihrer Umgebung sollten Sie die Ausstattung entsprechend planen. Um eine reibungslose Funktion zu gewährleisten, sollten folgende Minimalanforderungen erfüllt sein:

* x86-64- oder ARM64-System
* 2{nbsp}GByte RAM
* 2 CPU-Kerne

Ein opsi-Depotserver ist im Wesentlichen ein File-Server, der Dateien für die Clients zur Verfügung stellt.
Dementsprechend sind performante Massenspeicher und eine ausreichend schnelle Netzwerkanbindung wichtig.

Die Größe des benötigten Massenspeichers hängt hauptsächlich von der Anzahl der installierten opsi-Pakete ab.
Für Produktivsysteme gilt die folgende Empfehlung: Im Verzeichnis `/var/lib/opsi` benötigen Sie mindestens 60{nbsp}GByte Speicherplatz; der Ordner muss flexibel erweiterbar sein.

Abhängig von der Konfiguration und den Tagesabläufen greifen unterschiedlich viele opsi-Clients auf einen opsi-Server zu. In großen Umgebungen mit vielen gleichzeitigen Client-Verbindungen können RAM- und CPU-Bedarf deutlich ansteigen.

TIP: Der zentrale opsi-Dienst `opsiconfd` benötigt pro Worker-Prozess ca. 250{nbsp}MByte RAM. Wir empfehlen, einen Worker-Prozess für 20 gleichzeitige Verbindungen einzuplanen. Die Anzahl der CPU-Kerne sollte in etwa der Hälfte der Anzahl der Worker-Prozess entsprechen. In der Standard-Konfiguration sollten Sie zusätzliche Ressourcen für Samba, MySQL und Redis einplanen.


[[server-installation-options]]
== Installation des {opsi-server}s

Für die Installation eines {opsi-server}s stehen Ihnen verschiedene Möglichkeiten zur Verfügung, die wir in verschiedenen Anleitungen beschreiben:

* xref:server:installation/preconfigured-vm.adoc[Vorkonfigurierte virtuelle Maschine]
* xref:server:installation/docker.adoc[opsi als Docker-Container]
* xref:server:installation/deb.adoc[Installation unter Debian/Ubuntu]
* xref:server:installation/redhat.adoc[Installation unter RHEL/AlmaLinux/Rocky Linux]
* xref:server:installation/suse.adoc[Installation unter SLES/openSUSE Leap]
* xref:server:installation/ucs.adoc[Installation unter Univention Corporate Server (UCS)]
* xref:server:installation/quickinstall.adoc[Installation unter Linux mit opsi-QuickInstall]


[[server-installation-next-steps]]
== Nächste Schritte
// TODO

Soll der opsi-Server die Rolle eines opsi-Configservers oder eines opsi-Depotservers übernehmen? Davon hängen die nächsten Schritte ab.

=== opsi-Configserver

* Wenn Sie kostenpflichtige xref:opsi-modules:modules.adoc[opsi-Erweiterungen] einsetzen wollen, xref:server:components/opsiconfd.adoc#server-components-opsiconfd-admin-page-licensing[spielen Sie jetzt Ihre Lizenz-Dateien ein].
* Nehmen Sie die xref:server:configuration/configuration.adoc#opsi-server-configuration-base-configuration[Grundkonfiguration des {opsi-server}s] vor.
* xref:server:components/opsi-package-updater.adoc#server-components-opsi-package-updater-install-default-products[Spielen Sie die opsi-Standard-Produkte ein].
* Starten Sie die xref:configed:configed.adoc[Management-Oberfläche *opsi-configed*].
* xref:server:components/backup.adoc[Richten Sie ein Backup des {opsi-server}s ein].


=== opsi-Depotserver
Soll der Server die Rolle eines opsi-Depotservers übernehmen, dann muss der opsi-Depotserver nun auf dem opsi-Configserver registriert werden.

NOTE: Beim Betrieb des opsi-Depotservers als Docker-Container entfällt dieser Schritt, denn Umgebungsvariablen steuern dieses Verhalten.

Führen Sie dazu den folgenden Befehl auf dem opsi-Depotserver aus:

[source,shell]
----
opsiconfd setup --register-depot
----


[[server-installation-support]]
== Hilfe und Support

Bei Problemen finden Sie Hilfe im link:https://forum.opsi.org[opsi-Forum].

TIP: Wenn Sie einen Support-Vertrag haben, können Sie sich mit Ihren Fragen auch direkt an den link:https://www.uib.de/de/support-schulung/support[uib-Support] wenden.
