////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      08.05.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-installation]]
= Installation und Inbetriebnahme eines {opsi-server}s


[[server-installation-hardware-requirements]]
== Hardware-Anforderungen

Ein {opsi-server} kann direkt auf Hardware, in einer virtuellen Maschine oder als Docker-Container betrieben werden.
Die Hardware-Anforderungen variieren stark mit der Größe der Umgebung.
Folgende minimal-Anforderungen sollten erfüllt sein:

* x86-64- oder ARM64-System
* 2 GByte RAM
* 2 CPU-Kerne

Ein {opsi-depotserver} ist im Wesentlichen ein File-Server, der Dateien für die Clients zur Verfügung stellt.
Dementsprechend sind performante Massenspeicher und Netzwerk-Anbindung wichtig.

Die Größe des benötigten Massenspeichers hängt hauptsächlich von der Anzahl der installierten opsi-Pakete ab.
Für Produktiv-Systeme gelten folgende Empfehlungen:

* Im Verzeichnis `/var/lib/opsi` benötigen Sie mindestens 60{nbsp}GByte Speicherplatz; der Ordner muss flexibel erweiterbar sein.

Abhängig von der Konfiguration und den Tagesabläufen greifen unterschiedlich viele opsi-Clients auf einen {opsi-server} zu. In großen Umgebungen mit vielen gleichzeitigen Client-Verbindungen können RAM- und CPU-Bedarf deutlich ansteigen.

TIP: Der zentrale opsi-Dienst `opsiconfd` benötigt pro Worker-Prozess ca. 250{nbsp}MByte RAM. Wir empfehlen, einen Worker-Prozess für 20 gleichzeitige Verbindungen einzuplanen. Die Anzahl der CPU-Kerne sollte in etwa der Hälfte der Anzahl der Worker-Prozess entsprechen. In der Standard-Konfiguration sollten Sie zusätzliche Ressourcen für Samba, MySQL und Redis einplanen.


[[server-installation-options]]
== Installation des {opsi-server}s

Es stehen mehrere Möglichkeiten zur Installation eines {opsi-server}s zur Verfügung.
Führen Sie die Anleitung nach einer der folgenden Anleitungen durch:

* xref:server:installation/preconfigured-vm.adoc[Inbetriebnahme der vorkonfigurierten opsi-VM]
* xref:server:installation/docker.adoc[Inbetriebnahme unter Docker]
* xref:server:installation/deb.adoc[Installation auf Debian / Ubuntu]
* xref:server:installation/redhat.adoc[Installation auf RHEL / AlmaLinux / Rocky Linux]
* xref:server:installation/suse.adoc[Installation auf SLES / openSUSE Leap]
* xref:server:installation/quickinstall.adoc[Installation auf Linux mittels opsi-QuickInstall]


[[server-installation-next-steps]]
== Nächste Schritte
// TODO
Nach der Installation ist der {opsi-server}s nun bereit für die nächsten Schritte.
Diese unterscheiden sich, je nachdem ob der {opsi-server}s die Rolle eines {opsi-configserver}s oder eines {opsi-depotserver}s übernehmen soll.

=== {opsi-configserver}
Sollten Sie kostenpflichtige opsi-Erweiterungen einsetzen wollen, müssen Sie die entsprechenden Lizenz-Dateien nun einspielen.

Danach können Sie die xref:getting-started:server/configuration.adoc#opsi-getting-started-installation-config-update-opsi-product[opsi-Standard-Produkte einspielen].


=== {opsi-depotserver}
// TODO: Als partial und dann bei den Tools nochmal aufführen?
Soll der Server die Rolle eines {opsi-depotserver}s übernehmen, dann muss der {opsi-depotserver} nun am {opsi-configserver} registriert werden.

NOTE: Beim Betrieb des {opsi-depotserver}s als Docker-Container wir dies über Umgebungsvariablen gesteuert und dieser Schritt entfällt.

Führen Sie dazu den folgenden Befehl auf dem {opsi-depotserver} aus:

[source,prompt]
----
opsiconfd setup --register-depot
----


[[server-installation-support]]
== Hilfe und Support

Bei Problemen finden Sie Hilfe im link:https://forum.opsi.org[opsi-Forum].

TIP: Wenn Sie einen Support-Vertrag haben, können Sie sich mit Ihren Fragen auch direkt an den link:https://www.uib.de/de/support-schulung/support[uib-Support] wenden.
