////
; Copyright (c) uib GmbH (uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      22.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



[[server-installation-next-steps]]
= Nächste Schritte

Soll der opsi-Server die Rolle eines OPSI-Configservers oder eines OPSI-Depotservers übernehmen? Davon hängen die nächsten Schritte ab.

== OPSI-Configserver

* Wenn Sie kostenpflichtige xref:opsi-modules:modules.adoc[opsi-Erweiterungen] einsetzen wollen, xref:server:components/opsiconfd.adoc#server-components-opsiconfd-admin-page-licensing[spielen Sie jetzt Ihre Lizenz-Dateien ein].
* Konfigurieren Sie den Server und seine Komponenten (siehe Kapitel xref:server:components/components.adoc[Tools & Settings]).
* Installieren Sie weitere Software (siehe Abschnitt xref:server:components/commandline.adoc#server-components-opsi-package-updater-install-default-products[Standard-Produkte einspielen]).
* Starten Sie die xref:gui:configed.adoc[Management-Oberfläche *opsi-configed*].
* Richten Sie ein xref:server:components/backup.adoc[Backup des opsi-Servers] ein.

== OPSI-Depotserver

Soll der Server die Rolle eines OPSI-Depotservers übernehmen, dann registrieren Sie diesen nun auf dem OPSI-Configserver.
Führen Sie dazu den folgenden Befehl auf dem OPSI-Depotserver aus:

[source,console]
----
opsiconfd setup --register-depot
----

NOTE: Wenn Sie den OPSI-Depotserver als Docker-Container betreiben, entfällt dieser Schritt. In dem Fall steuern Umgebungsvariablen dieses Verhalten.
