////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      30.05.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-installation-next-steps]]
= Nächste Schritte

Soll der opsi-Server die Rolle eines opsi-Configservers oder eines opsi-Depotservers übernehmen? Davon hängen die nächsten Schritte ab.

=== opsi-Configserver

* Wenn Sie kostenpflichtige xref:opsi-modules:modules.adoc[opsi-Erweiterungen] einsetzen wollen, xref:server:components/opsiconfd.adoc#server-components-opsiconfd-admin-page-licensing[spielen Sie jetzt Ihre Lizenz-Dateien ein].
* Nehmen Sie die xref:server:configuration/configuration.adoc#opsi-server-configuration-base-configuration[Grundkonfiguration des opsi-Servers] vor.
* xref:server:components/opsi-package-updater.adoc#server-components-opsi-package-updater-install-default-products[Spielen Sie die opsi-Standard-Produkte ein].
* Starten Sie die xref:configed:configed.adoc[Management-Oberfläche *opsi-configed*].
* xref:server:components/backup.adoc[Richten Sie ein Backup des opsi-Servers ein].

=== opsi-Depotserver
Soll der Server die Rolle eines opsi-Depotservers übernehmen, dann muss der opsi-Depotserver nun auf dem opsi-Configserver registriert werden.

NOTE: Wenn Sie den opsi-Depotserver als Docker-Container betreiben, entfällt dieser Schritt. In dem Fall steuern Umgebungsvariablen dieses Verhalten.

Führen Sie dazu den folgenden Befehl auf dem opsi-Depotserver aus:

[source,console]
----
opsiconfd setup --register-depot
----

