////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      18.12.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-installation-redhat]]
= Installation unter RHEL/AlmaLinux/Rocky Linux

Dieses Kapitel beschreibt die paketbasierte Installation eines opsi-Servers unter Red Hat Enterprise Linux (RHEL), AlmaLinux und Rocky Linux.

include::server:partial$package-based-start.adoc[]

== Vorbereitungen

Wenn Sie Red Hat Enterprise Linux einsetzen, müssen Sie sich beim Red Hat Network registrieren, um Zugriff auf alle benötigten Pakete zu haben:

[source,console]
----
sudo subscription-manager register
sudo subscription-manager attach --auto
----

Installieren Sie Samba und MariaDB:

[source,console]
----
sudo yum install mariadb-server samba samba-client
----

Starten und konfigurieren Sie Samba und MariaDB:

[source,console]
----
sudo systemctl start smb.service
sudo systemctl start nmb.service
sudo systemctl start mariadb.service
sudo systemctl enable smb.service
sudo systemctl enable nmb.service
sudo systemctl enable mariadb.service
sudo mysql_secure_installation
----

NOTE: Soll die Maschine auch als DHCP-Server eingesetzt werden, muss der Daemon `dhcpd` installiert und konfiguriert sein.

== Repositorys konfiguration

Fügen Sie das Grafana-Repository hinzu:

[source,console]
----
sudo cat <<EOF | sudo tee /etc/yum.repos.d/grafana.repo
[grafana]
name=grafana
baseurl=https://rpm.grafana.com
repo_gpgcheck=1
enabled=1
gpgcheck=1
exclude=*beta*
gpgkey=https://rpm.grafana.com/gpg.key
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
EOF
----

Fügen Sie das zu Ihrer Distribution passende opsi-Repository hinzu:

*RHEL 9:*
[source,console]
[subs="attributes"]
----
sudo cd /etc/yum.repos.d/
sudo wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:stable/RHEL_9/home:uibmz:opsi:4.3:stable.repo
sudo yum makecache
----

*RHEL 8:*
[source,console]
[subs="attributes"]
----
sudo cd /etc/yum.repos.d/
sudo wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:stable/RHEL_8/home:uibmz:opsi:4.3:stable.repo
sudo yum makecache
----

*AlmaLinux 9:*
[source,console]
[subs="attributes"]
----
sudo cd /etc/yum.repos.d/
sudo wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:stable/AlmaLinux_9/home:uibmz:opsi:4.3:stable}.repo
sudo yum makecache
----

*AlmaLinux 8:*
[source,console]
[subs="attributes"]
----
sudo cd /etc/yum.repos.d/
sudo wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:stable}/AlmaLinux_8/home:uibmz:opsi:4.3:stable.repo
sudo yum makecache
----

*Rocky Linux 9:*
[source,console]
[subs="attributes"]
----
sudo cd /etc/yum.repos.d/
sudo wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:stable/RockyLinux_9/home:uibmz:opsi:4.3:stable.repo
sudo yum makecache
----

*Rocky Linux 8:*
[source,console]
[subs="attributes"]
----
sudo cd /etc/yum.repos.d/
sudo wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:stable/RockyLinux_8/home:uibmz:opsi:4.3:stable.repo
sudo yum makecache
----


== Pakete installieren

Installieren Sie das Paket `opsi-server-full`:

[source,console]
----
sudo yum install opsi-server-full
----

Wenn Sie beim Importieren des GnuPG-Schlüssels des Repositorys eine solche Meldung sehen, geben Sie `y` ein und drücken [Eingabe], um das Hinzufügen des Schlüssels zu bestätigen:

[source,console]
[subs="attributes"]
----
Importing GPG key 0xD8361F81 "home:uibmz OBS Project <home:uibmz@build.opensuse.org>" from http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/stable/distribution/repodata/repomd.xml.key
Is this ok [y/N]: y
----

include::server:partial$package-based-end.adoc[]

Der opsi-Server ist jetzt bereit für die xref:server:installation/next-steps.adoc[nächsten Schritte].

