////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      08.05.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]


[[server-installation-suse]]
== Installation auf SLES / openSUSE Leap

Dieses Kapitel beschreibt die Paket-basierte Installation eines {opsi-server}s auf einem SLES und openSUSE Leap.

include::server:partial$package-based-start.adoc[]

=== Konfiguration der Paketquellen

Fügen Sie das Grafana-Repository zu den Paketquellen hinzu:

[source,bash]
----
sudo zypper addrepo https://rpm.grafana.com grafana
----

Fügen Sie das, zu Ihrer Distribution passende, opsi-Repository zu den Paketquellen hinzu:

*openSUSE Leap 15.4:*
[source,prompt]
[subs="attributes"]
----
sudo zypper addrepo https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/openSUSE_Leap_15.4/home:uibmz:opsi:4.3:{release}.repo
----

*SLES 15 SP4:*
[source,prompt]
[subs="attributes"]
----
sudo zypper addrepo http://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/SLE_15_SP4/home:uibmz:opsi:4.3:{release}.repo
----

*SLES 15 SP3:*
[source,prompt]
[subs="attributes"]
----
sudo zypper addrepo http://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/SLE_15_SP3/home:uibmz:opsi:4.3:{release}.repo
----

*SLES 15 SP2:*
[source,prompt]
[subs="attributes"]
----
sudo zypper addrepo http://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/SLE_15_SP2/home:uibmz:opsi:4.3:{release}.repo
----

*SLES 15 SP1:*
[source,prompt]
[subs="attributes"]
----
sudo zypper addrepo http://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/SLE_15_SP1/home:uibmz:opsi:4.3:{release}.repo
----


=== Installation der Pakete
Installieren Sie das Paket `opsi-server-full`:

[source,prompt]
----
sudo zypper refresh
  Wollen Sie den Schlüssel (a)bweisen, ihm (t)emporär oder (i)mmer vertrauen? [a/t/i/?] (a): i
sudo zypper -v install opsi-server-full
----

include::server:partial$package-based-end.adoc[]

Der {opsi-server} ist jetzt bereit für die xref:server:installation/installation.adoc#server-installation-next-steps[nächsten Schritte].