////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      24.04.2023
:Revision:  4.2
:toclevels: 6
:doctype:   book
:icons: font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-getting-started-installation-base-ucs]]
== Installation unter Univention Corporate Server (UCS)

Unter Univention Corporate Server (UCS) gibt es zwei Möglichkeiten, den {opsi-server} zu installieren:

* <<opsi-getting-started-installation-base-ucs-appcenter>> (nur UCS 5.0 oder neuer)
* <<opsi-getting-started-installation-base-ucs-manually>> über die uib-Repositorys (UCS 4.4 und 5.0)

Beide Varianten führen zu einem funktionierenden opsi-Server, sollten aber nicht zusammen auf einem Server laufen. Entscheiden Sie im Vorfeld, welche Installation zu Ihrer Umgebung passt. Wenn Sie opsi über das Univention App Center beziehen, dann kann es sein, dass Sie länger auf Aktualisierungen warten müssen. Der Wechsel auf eine neue UCS-Version (etwa von 4.4 auf 5.0) ist erst dann möglich, wenn alle installierten Apps unter der neuen UCS-Version zur Verfügung stehen. Entscheiden Sie sich für die Installation über die uib-Repositorys, erhalten Sie zeitnah Updates.


[[opsi-getting-started-installation-base-ucs-appcenter]]
==== Installation über das Univention App Center

Im link:https://www.univention.de/produkte/univention-app-center/app-katalog/opsi/[Univention App Center Katalog] finden Sie opsi für die UCS-Version 5.0. Bei der Installation spielt der Paketmanager automatisch weitere Pakete ein: `opsi-tftpd-hpa` und `univention-mariadb`.

NOTE: Der erste {opsi-server} einer UCS-Umgebung konfiguriert einen vorhandenen MariaDB-Server als Backend. Alle weiteren {opsi-server} registriert opsi als Depots. Gibt es also bei der Installation bereits einen {opsi-server} in der UCS-Umgebung, so wird das Tool `opsi-package-updater` so konfiguriert, dass es die Pakete von diesem Server bezieht.

[[opsi-getting-started-installation-base-ucs-manually]]
==== Manuelle Installation

Bevor Sie den {opsi-server} unter Univention Corporate Server von Hand installieren, treffen Sie ein paar Vorbereitungen:

* Samba muss installiert und konfiguriert sein. Ist der UCS-Server Mitglied einer AD-Domäne, installieren Sie `univention-samba`, das Samba als Mitgliedsserver ohne Domänen-Controller-Funktionalität einrichtet und konfiguriert. Das Paket `univention-samba4` hingegen richtet Samba als AD-Domänen-Controller ein.

* Ein MariaDB-Server muss installiert und konfiguriert sein. Installieren Sie dazu `univention-mariadb`; das Paket `univention-mysql` ist seit UCS 4.3 ein Metapaket, das den MariaDB-Server installiert.

* Soll der UCS-Rechner auch als DHCP-Server dienen, konfigurieren Sie vor der opsi-Installation den DHCP-Daemon und starten ihn.

Grundsätzlich ist die Installation auf Servern mit den UCS-Rollen Primary Directory Node, Backup Directory Node, Replica Directory Node und Managed Node möglich.

WARNING: Wenn Sie den {opsi-server} nicht auf einem Primary Directory Node, sondern auf einem Rechner mit einer anderen UCS-Systemrolle installieren, muss der UCS-Server vorher der Domäne beitreten.

Die Konfigurationsdatei `/etc/opsi/opsi.conf` definiert die Gruppe für den Samba-Zugriff auf die Freigaben; der Name ist `opsifileadmins`. Alle Anwender, die Zugriffsrechte für die Freigaben von opsi erhalten sollen (opsi-Paketierer), müssen dementsprechend Mitglied der Gruppe `opsifileadmins` sein.

So fügen Sie das opsi-Repository hinzu:

*Univention UCS 4.4:*
[source,bash]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Univention_4.4
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" > /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----

*Univention UCS 5.0:*
[source,bash]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Univention_5.0
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" > /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----

Nach dem Hinzufügen der Repositorys können Sie die Installation starten:

*Single-Server-Setup:*
[source,bash]
----
univention-install opsi-server-full
----


Wenn der {opsi-server} auf einer anderen UCS-Systemrolle als Primary Directory Node laufen soll, führen Sie zusätzlich den Befehl `univention-run-join-scripts` aus.

Benutzer müssen Mitglied der Gruppe `opsi-admin-group` sein, um den `opsi-configed` verwenden zu können. Während der Installation, wird der Benutzer `Administrator` automatisch zu dieser Gruppe hinzugefügt. Andere Accounts fügen Sie über das UMC-Modul _Benutzerverwaltung_ , Reiter _Gruppen_ hinzu.

Um sicherzustellen, dass alle opsi-Einstellungen korrekt übernommen wurden, führen Sie abschließend die folgenden Befehle aus:

[source,bash]
----
opsi-setup --init-current-config
opsi-set-rights
systemctl restart opsiconfd.service
systemctl restart opsipxeconfd.service
----