////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      11.01.2021
:doctype: book

include::common:partial$opsi_terms.adoc[]
[[opsi_manual_opsi-client-agent_webapi]]
= {opsi-client-agent} web service

[[opsi_manual_opsi-client-agent_webapi_log_read]]
== Reading log files

* `log_read` +
Reads an opsi log file available on the client. +
Parameters: `logType *extension *maxSize` +
Possible logType values are 'opsiclientd', 'opsiclientdguard', 'opsi-client-agent', 'opsi-script', 'opsi_loginblocker', 'notifier_block_login' and 'notifier_event'. +
Rotated log files (log.1, log.2, _1.log, _2.log etc.) can be selected with the parameter 'extension'. +
Possible values are 0-9. +
The 'maxSize' parameter limits the output to the specified value in bytes. +

[[opsi_manual_opsi-client-agent_webapi_update_component]]
== Updating a {opsi-client-agent} component
* `updateComponent` +
Update a {opsi-client-agent} component from an URL. +
Parameters: `*component *url` +
Possible values for `component` are: 'opsiclientd'. +
The update will be loaded from the specified `url` (possible protocols are: 'http', 'https' and 'file').
The update has to be packaged as an archive (zip / tar / tar.gz / tar.bz2) containing the files of the component.

Alternatively, it is possible to upload the archive via a POST request to `/upload/update/opsiclientd`. +
For example:
[source,bash]
----
curl --insecure --request POST \
	--user ':<opsi-client-host-key>' \
	--header 'Content-Disposition: filename=oca.zip' \
	--data-binary '@path/to/opsiclientd_windows_x86_<version>.zip' \
	https://<client-address>:4441/upload/update/opsiclientd
----
