////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      21.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[firststeps-osinstall-create-client]]
= Clients hinzufügen

Dieses Kapitel erklärt, wie Sie Windows-Clients in die opsi-Umgebung integrieren. Eine Ausführliche Anleitung finden Sie im Kapitel xref:clients:opsi-clients.adoc[opsi-Clients].

TIP: Mit opsi können Sie auch Linux- und macOS-Clients verwalten. Details dazu finden Sie in den beiden Kapiteln xref:clients:linux-client/linux-client-manual.adoc[Linux-Clients] und xref:clients:macos-client/mac-client-manual.adoc[macOS-Clients].

[[firststeps-software-deployment-client-integration]]
== Vorhandene Clients integrieren

Um vorhandene Clients mit bereits installiertem Betriebssystem in opsi aufzunehmen, installieren Sie auf dem jeweiligen Rechner den Client-Agent. Danach erscheint der Client auch in der Client-Liste der Management-Oberfläche, sofern Sie ihn dort noch nicht hinzugefügt hatten.

NOTE: Nachdem der Client-Agent installiert ist, können Sie opsi-Produkte auf dem Client einspielen (siehe Kapitel xref:clients:windows-client/rollout-products.adoc[Rollout existierender Produkte]).

[[opsi-create-client-integrating-clients]]
include::common:partial$firststeps-client-installer.adoc[leveloffset+1]

Jetzt sollten Sie im `opsi-configed` den oder die neuen Clients sehen. Im nächsten Schritt installieren wir das Produkt `hwaudit` auf den Clients.
