////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype: book
:macosclientmanual: opsi-macos-client-manual

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]



[[opsi-macclient-requirements]]

== Requirements for MacOS Clients

In the following the requirements for the management of MacOS clients under opsi are described.

The opsi-mac-client-agent is a
http://uib.de/de/opsi-erweiterungen/erweiterungen/[co-funded opsi extension]. +
This means that you need an unlock file to use it. You get this unlock file when you buy the extension. For evaluation purposes we also provide a time limited unlock file for free ( -> mail to info@uib.de). +
Further details can be found in +
https://download.uib.de/opsi_stable/doc/html/opsi-manual/opsi-manual.html#opsi-manual-modules

Technical requirements is an opsi-server with opsi 4.1. or higher.

Supported macOS versions:

include::../common/opsi_manual_supportmatrix-macclient-core.asciidoc[]


When using the arm64 architecture (Apple Silicon, M1), it's currently necessary to install the opsi-client-agent of the 'Dynamic Binary Translators' called `rosetta2`. You can install this with: +
`softwareupdate --install-rosetta --agree-to-license`
You can verify the successful installation with: +
`pkgutil --pkgs | grep Rosetta` +
`com.apple.pkg.RosettaUpdateAuto`.

Native support for the arm64 architecture (Apple silicon) is planned. The necessary reference devices have been ordered for this purpose. To disclose when the deployment for this platform will take place cannot be made at this time (April 2022).
