////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype: book
:macosclientmanual: opsi-macos-client-manual

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]


[[opsi-macclient-firststeps-software-deployment-product-tests]]
== Rollout of existing products to MacOS.

For the deployment of software to clients, the _opsi-client-agent_ must be installed on them.
This can be rolled out on <<opsi-macclient-firststeps-software-deployment-client-integration,existing-machines>>.


Subsequently, the <<firststeps-software-deployment-product-tests-configed,{opsi-configed}>> management interface is used to deploy software to clients.

include::../common/firststeps-swdp-product-tests-inventory.asciidoc[]

[[opsi-macclient-firststeps-software-deployment-product-tests-homebrew]]
=== Distribution of opsi standard products: m-homebrew.

This product installs the package management program `homebrew` which is used by several other opsi products for MacOS, e.g. to install Java.

See also: <<opsi-macclient-hints-homebrew, The opsi product m-homebrew>>.

In _{opsi-configed}_, _Client configuration_ mode, select the client in question under the _Clients_ tab.

Switch to the _Product Configuration_ tab, click in the _Requested_ column for the _m-homebrew_ product, this will open a list/dropdown menu and there select the _setup_ action.

The check mark in the icon menu bar should change its color to red. If you click on it, the new settings will be transmitted to the {opsi-server}, afterwards its color will be green again.

Then restart the client or push the installation via _on_demand_.
It should now start the +opsi-client-agent+ and install the +m-homebrew+ product.

[[opsi-macclient-firststeps-software-deployment-product-tests-java]]
=== Distribution of opsi standard products: m-javavm

This product installs the Java Runtime Environment which is used by several other opsi products for MacOS, e.g. opsi-configed, opsi-logviewer.

In _{opsi-configed}_, mode _Client configuration_, select the client under the tab _Clients_.

Switch to the _Product Configuration_ tab, click in the _Requested_ column for the _m-javavm_ product, this will open a list/dropdown menu and there please select the _setup_ action.

The check mark in the icon menu bar should change its color to red. If you click on it, the new settings will be transmitted to the {opsi-server}, afterwards its color will be green again.

Then restart the client or push the installation via _on_demand_.
It should now start the +opsi-client-agent+ and install the +m-javavm+ product.

[[opsi-macclient-firststeps-software-deployment-product-tests-configed]]
=== Distribution of opsi standard products: opsi-configed.

Attention: m-homebrew and m-javavm must be already installed!

To the standard products belongs the product `opsi-configed` which installs the opsi management interface as application on a computer.
Because this application is a Java application, a JavaRE is included.

In the _{opsi-configed}_, mode _Client configuration_, under the tab _Clients_ select the concerning client.

If not already done, update the {opsi-configed}'s dataset using _Reload File/Data_ by clicking the corresponding icon.

Switch to the _Product configuration_ tab, click in the _Requested_ column for the _opsi-configed_ product, this will open a list/dropdown menu and there select the _setup_ action.

The check mark in the icon menu bar should change its color to red. If you click it, the new settings will be transmitted to the {opsi-server}, afterwards its color will be green again.

Then restart the client.
It should now start the _opsi-client-agent_ and install the _opsi-configed_ product.
After the installation is finished you should find the item `opsi-configed` under `Applications`.