////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      24.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-manual-configed]]
= Management-Oberfläche *opsi-configed*

Das Programm `opsi-configed` ist ein grafisches Interface, das per HTTPS mit dem opsi-Server kommuniziert und daher auf jedem Rechner läuft, der über dieses Protokoll Verbindung zum Server aufnehmen kann. 

[[opsi-manual-configed-preconditions]]
== Voraussetzungen

Die Management-Oberfläche `opsi-configed` benötigt `opsiconfd` 4.1 oder neuer (siehe Abschnitt xref:server:components/opsiconfd.adoc[Der Dienst *opsiconfd*]). Wenn Sie anstelle des opsi-Paketes die portable Java-Anwendung einsetzen möchten, ist eine aktuelle Java-Laufzeitumgebung erforderlich.

TIP: Wenn Sie eine virtuelle Maschine verwenden, achten Sie auf eine ausreichende Auflösung des virtuellen Bildschirms. `opsi-configed` benötigt mindestens eine Bildschirmauflösung von 1024{nbsp}x{nbsp}768 Pixeln. Für eine bessere Grafik und Bildschirmauflösung bzw. Maus- und Tastaturintegration installieren Sie am besten die VMware Tools oder die VirtualBox Gast-Erweiterungen.

//Voraus. verschieben, hier stattdessen Aufzählung, was kommen soll?
