////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      20.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-manual-opsiwebgui]]
= opsi-WebGUI

Das opsi-WebGUI ist eine moderne, grafische Benutzeroberfläche zur Administration von opsi im Webbrowser. Es vereinfacht viele Aufgaben und bietet schnellen Zugriff auf alle opsi-Komponenten, ohne dass Sie eine eigene Anwendung installieren müssen. Über die webbasierte Benutzeroberfläche können Sie von ganz unterschiedlichen Geräten aus den opsi-Server konfigurieren, neue opsi-Clients einrichten, Produkte verteilen und Logdateien einsehen.

[[opsi-manual-opsiwebgui-technology]]
== Technologie-Stack

Das opsi-WebGUI ist ein `opsiconfd`-Addon (siehe Kapitel xref:server:components/opsiconfd.adoc[Der Dienst *opsiconfd*]). Nach der Installation befindet sich die Erweiterung auf dem opsi-Configserver im Verzeichnis `/var/lib/opsiconfd/addons/webgui`. Das WebGUI nutzt die folgenden Technologien:

* https://fastapi.tiangolo.com/id/[FastAPI]: Das Backend ist mit diesem Python-Framework erstellt. Es dient zum Lesen und Schreiben von Daten aus der MySQL-Datenbank.
* 

https://bonifax.uib.gmbh/opsidoc/antora/opsi-docs-de/4.3/server/components/mysql.html?q=MySQL
