////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      20.11.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-manual-opsiwebgui]]
= opsi-WebGUI

Das opsi-WebGUI ist eine moderne, grafische Benutzeroberfläche zur Administration von opsi im Webbrowser. Es bietet schnellen Zugriff auf alle opsi-Komponenten, ohne dass Sie eine eigene Anwendung installieren müssen. Über die webbasierte Benutzeroberfläche können Sie von ganz unterschiedlichen Geräten aus den opsi-Server konfigurieren, neue opsi-Clients einrichten, Produkte verteilen und Logdateien einsehen.

[[opsi-manual-opsiwebgui-technology]]
== Technologie-Stack

Das opsi-WebGUI ist ein `opsiconfd`-Addon (siehe Kapitel xref:server:components/opsiconfd.adoc[Der Dienst *opsiconfd*]). Nach der Installation befindet sich die Erweiterung auf dem opsi-Configserver im Verzeichnis `/var/lib/opsiconfd/addons/webgui`. Das WebGUI nutzt die folgenden Technologien:

* link:https://fastapi.tiangolo.com/id/[FastAPI]: Das Backend ist mit diesem Python-Framework erstellt. Es dient zum Lesen und Schreiben von Daten aus der MySQL-Datenbank.
* link:https://nuxt.com/[Nuxt]: Das Frontend basiert auf diesem link:https://vuejs.org/[Vue.js]-Framework. Es stellt Anfragen an das Backend, ruft Daten ab und zeigt diese in geeigneten Formaten an.

Um die Performance zu verbessern, interagiert das Backend direkt mit der Datenbank. Bis opsi 4.2 ist die MySQL-Erweiterung eine kostenpflichtige Erweiterung; ab opsi 4.3 ist sie das Standard-Backend (siehe Kapitel xref:server:components/mysql.adoc[MySQL-Server]). Außerdem findet eine Kommunikation mit dem `opsiconfd` für das Session-Handling und Logging statt.

