////
; Copyright (c) uib GmbH (uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      23.09.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

[[rename-clients]]
= Clients umbenennen

Beim Umbenennen von Clients stellt sich die Frage, wo die Änderung überall greifen soll. Möchten Sie nur den Namen im opsi-Backend anpassen, oder betrifft die Änderung auch den Verzeichnisdienst (wie Active Directory oder LDAP) sowie den Namen auf dem Client selbst? Sie haben grundsätzlich zwei Möglichkeiten, diese Anpassung vorzunehmen: vollautomatisch mit dem Localboot-Produkt `opsi-rename-client` oder Schritt für Schritt.

== Das Localboot-Produkt `opsi-rename-client`

//Link nachtragen, wenn Kapitel geschrieben ist
Mit diesem Produkt benennen Sie Clients auf verschiedenen Ebenen (Betriebssystem, opsi, Domain) und nach individuellen Regeln um. Eine detaillierte Anleitung zu den verschiedenen Möglichkeiten finden Sie *hier* im Handbuch. Auch größere Gruppen von Clients können Sie schnell und unkompliziert nach bestimmten Namensmustern umbenennen.

== Schritt für Schritt

Die nächsten Abschnitte beschreiben, wie Sie Clients umbenennen und die Konfiguration anpassen – egal ob über `opsi-configed`, das WebGUI oder direkt über die API und Konfigurationsdatei des Client-Agent.

=== Client-ID in Datenbank ändern

Sie können eine der grafischen Oberflächen (`opsi-configed` oder WebGUI) verwenden, um einen Client umzubenennen:

* Im `opsi-configed` wählen Sie den gewünschten Client aus und öffnen aus dem Menü _Client_ den Eintrag _Client umbenennen_.
* Im WebGUI finden Sie die Funktion über die Abteilung _Clients_: Wählen Sie einen Client in der Tabelle aus und öffnen Sie aus dem Menü _Aktionen_ den Eintrag _Umbenennen_. (Alternativ finden Sie die Funktion auch im Kontextmenü der rechten Maustaste.)

WARNING: Clients authentifizieren sich beim Server mit ihrem FQDN und dem opsi Host Key; der FQDN ist der Primärschlüssel im Datenbank-Backend. Der FQDN stimmt nach der Umbenennung aber nicht mehr mit dem in der Datenbank überein, und der Client wird sich noch mit seinem alten Namen melden, daher sind weitere Anpassungen notwendig.

=== `opsiconfd`-Konfiguration anpassen

Der `opsiconfd` (siehe Kapitel xref:server:components/opsiconfd.adoc[Der Dienst *opsiconfd*]) bietet eine Option, welche die Überprüfung der Client-ID deaktiviert. Danach authentifizieren sich Clients ausschließlich mit ihrem Host Key. Sie können die Option in der Konfigurationsdatei, über eine Umgebungsvariable oder per Kommandozeilen-Parameter setzen:

* `/etc/opsi/opsiconfd.conf`: Setzen Sie `allow-host-key-only-auth = true`.
* Umgebungsvariable: `export ALLOW_HOST_KEY_ONLY_AUTH=true`
* Kommandozeilen-Parameter: `--allow-host-key-only-auth=true`

Laden Sie nach der Änderung die Konfiguration neu ein:

[source,console]
----
opsiconfd reload
----

Anschließend akzeptiert der opsi-Server auch Client-Anfragen mit einer unbekannten Host-ID. Wird ein Client nur über seinen Host Key identifiziert, passt das System seinen Namen automatisch in der Datei `opsiclientd.conf` an. Künftig meldet sich der Client dann unter seinem neuen Namen.

NOTE: Sobald sich alle Clients einmal gemeldet haben und der Client-Agent die Informationen aktualisiert hat, können Sie die `opsiconfd`-Option wieder deaktivieren.

TIP: Wenn Sie nur einen oder ein paar wenige Clients umbenennen möchten, können Sie die Anpassung direkt in der jeweiligen `opsiclientd.conf`-Datei vornehmen. Achten Sie darauf, dass Ihr Texteditor die UTF-8-Kodierung unterstützt.

[source,toml]
----
[global]
# Client id.
host_id = neuer_clientname.xyz.local
----

Die Einrichtungsdatei finden Sie jeweils hier:

* Windows: `C:\Program Files (x86)\opsi.org\opsi-client-agent\opsiclientd\opsiclientd.conf`
* Linux: `/etc/opsi-client-agent/opsiclientd.conf`
* macOS: `/private/etc/opsi-client-agent/opsiclientd.conf`
