
[[rename-clients]]
= Clients umbenennen

Beim Umbenennen von Clients ist immer zu Berücksichtigen an welchen Stellen sich diese Auswirken soll. Betrifft die Änderung nur den Namen im opsi-Backend oder auch den Namen im AD/LDAP oder auf dem Client selber. Grundsätzlich gibt es zwei Wege das umzusetzen:

== 1. Das Produkt opsi-rename-client
Mit diesem Produkt können Clients auf unterschiedlichen Ebenen (windows / opsi / Domain)
und nach unterschiedlichen Regeln umbenannt werden. 
Eine genaue Anleitung der verschiedenen Optionen befindet sich *hier* im Handbuch. Mit diesem Produkt lassen sich auch größere Gruppen von Clients nach bestimmten Namensmustern umbenennen.

== 2. Grafische Management-Oberfläche `opsi-configed`
Soll der Name im opsi-Backend angepasst werden, kann dies über den opsi-Configed im Menü Client "Client umbenennen" erfolgen. Hierbei ist jedoch zu beachten, dass der Client sich nach der Umbenennung nicht mehr am opsi-Server melden kann, weil der Client sich noch unter seinem alten Namen melden wird, den es im opsi Backend nicht mehr gibt. Das heißt es ist zudem auch noch eine der hier aufgeführten Anpassungen notwendig:

* Durch Setzen des Configs `allow-host-key-only-auth = true` in der `/etc/opsi/opsiconfd.conf` akzeptiert der opsi-Server auch Client-Anfragen mit einer unbekannten `host-id`. Wenn dann ein Client nur über seinen host-key identifiziert wurde, wird sein Name automatisch in der clientd.conf angepasst. Das heißt zukünftig würde er sich unter seinem geänderten Namen melden.

Nach einer Änderung in der opsiconfd.conf muss der Dienst opsiconfd neu gestartet werden.

Diese Änderung ist auch für eine größere Anzahl von Umbenennungen praktikabel. Aus Sicherheitsgründen sollte die Einstellung nach einer Zeit wieder zurück genommen  werden. 


* Wenn es sich nur um einige Clients handelt können Sie den Namen auch local auf dem Client in der opsiclientd.conf anpassen.

Unter Windows: `C:\Program Files (x86)\opsi.org\opsi-client-agent\opsiclientd\opsiclientd.conf`

[source,console]
----
[global]
# Client id.
host_id = neuer_clientname.xyz.local
----



