[[opsi-conventions]]
== Konventionen und Schreibweisen

Wir verwenden in diesem Handbuch die folgenden Schreibweisen und Hervorhebungen:

* Datei- und Verzeichnisnamen erscheinen in `Proportionalschrift`.
* Längere Befehle und Listings stehen in eigenen Kästen; Sie können diese bequem per Copy{nbsp}&{nbsp}Paste übertragen: +

[source,console]
----
dies ist ein Befehl
----

* So sieht `opsi-script`-Code aus: +

[source,console]
----
Message "Installing "+ $ProductId$ +" ..."
----

* In `<spitzen Klammern>` stehen Bezeichnungen, die Sie durch ihre Bedeutung ersetzen müssen. So heißt die Dateifreigabe mit den opsi-Paketen z.{nbsp}B. `<opsi-depot-share>`. Auf einem realen Server liegt sie in der Regel in `/var/lib/opsi/depot`. Das Softwarepaket `<opsi-depot-share>/ooffice` befindet sich also unter `/var/lib/opsi/depot/ooffice`.
* Menüeinträge und Beschriftungen von Schaltflächen erscheinen _kursiv_.
* Tasten und Tastenkombinationen stehen in eckigen Klammern, z.{nbsp}B. [C], [Strg]{plus}[C] usw.

