////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      30.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

= Produkte Installieren

Zur Verteilung von Software mit opsi stehen fertige Produkte zur Installation bereit. Zu diesen Produkten gehört auch der xref:clients:windows-client/windows-client-agent.adoc[Client-Agent (Windows)], der auf allen Clients installiert sein muss, damit die Verwaltung mit opsi möglich ist.


// cspell: ignore updater
Um die Pakete auf dem Server zu installieren führen Sie folgenden Befehl auf der Kommandozeile aus:

[source,console]
----
opsi-package-updater -v  install opsi-client-agent hwaudit
----

Note: Wie Sie den opsi-package-updater konfigurieren oder Pakete manuell installieren finden Sie im Kapitel xref:clients:windows-client/minimal-products.adoc[Produkte bereitstellen (Server)]. Wenn Sie eigene opsi Pakete erstellen möchten, dann finden Sie unter xref:clients:windows-client/softwareintegration.adoc[Eigene Software einbinden] eine ausführliche Anleitung.