////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      11.01.2021
:doctype: book

include::common:partial$opsi_terms.adoc[]


[[opsi-script-cliparams]]
= Start and Command Line Options

Since version 4.11.3, the _{opsi-script}_ program contains at Windows a manifest with the statement: +
`<requestedExecutionLevel level="highestAvailable" />`. This means that if _{opsi-script}_ is called on an NT6 OS by an Administrator, then it will run as an 'elevated' process. If _{opsi-script}_ is called with normal user privileges, then it will run with the privileges of this user.

If you start _{opsi-script}_ without any parameter, it will start in the interactive mode.

_{opsi-script}_ can be started with different sets of parameters depending on context and purpose of use.

Note:: At Linux or macOS the parameter char is not "/" as here decribed for Windows but "-". So instaed of using  `opsi-script /help` as we do on Windows, we use at Linux / macOS `opsi-script -help`.

Generic Options:

* `/?` or `/h`[elp] +
Show help +

* `/silent` +
Run opsi-script without GUI +


Execute one (or more) scripts: +
`opsi-script` <scriptfile>[;<scriptfile>]* [<logfile>] +
where: +
<scriptfile> = Name of the script file (incl. path). +
<logfile> = Name of the log file (incl. path).
Paths to log files see also: <<opsi-script-logpath>>

* `/parameter` <parameterstring> +
A string that can be passed to the executed script and can be retrevaled by the command `Paramstr`. +
Hereby is <parameterstring> a string without whitespaces.

* `/logfile` <logfile>  +
Define the log file: +
Hereby is: +
<logfile> = Name of the log file (incl. path).
Paths to log files see also: <<opsi-script-logpath>>

* `/lang` <lang> +
Define the localization: +
Hereby is: +
<lang> = The two char language abbreviation (de,en,fr,es,...)

* `/batch` +
Execute the given script with the batch GUI. The batch GUI has no possibility for user interaction. In combination with the option `/silent` there will be no GUI at all. If you call _opsi-script_ without the option `/batch` the interactive GUI ist started, which is designed for development end testing purposes.

* `/productid` <productId> +
For the use together with `/servicebatch` ; see overthere.

* `/servicebatch` +
Execute the given script with the batch GUI and with a connection to the opsi web service. Thereby the given script will be executed as it would be if the opsi product given by the option `/productid` had the action request 'setup'. +
The script file has to be the first option. +
The option `/opsiservice` and its sub options has to be given. +
The option `/productid` has to be given. This one is used for the communication with the opsi web service to run the given script as it would be the 'setup-script' of the opsi product given with this option.

* `/logproductid` <productId> +
While creating the log file the given <productId> should be used to note it as source of the log file.

* `/normalwindow` +
Switches off the maximize if of the GUI in the not interactive mode.

* `/usercontext` < [domain\]username > +
If the given user is loged in then _opsi-script_ will try to resolve the constants like `%CurrentAppdataDir%, %CurrentStartmenuDir%, %CurrentDesktopDir%, %CurrentStartupDir%, %CurrentProgramsDir%, %CurrentSendToDir%, %CurrentProfileDir%` from the context of the given user. +
Mostly used together with the'User Profile Management' opsi extension.


* `/opsiservice` <opsiserviceurl> +
     `/clientid` <clientname> +
     `/username` <username> +
     `/password` <password> +
     [`/sessionid` <sessionid>] +
     [`/credentialfile` <credentialfile>] +
Give the connection data to connect to the opsi web service: +
Hereby you have to give either `/clientid` and `/username` and `/password`
and also optional the `/sessionid` +
or you have to give this data via a
 `/credentialfile`.

Declare what should be done in the context of the connected  `/opsiservice` +

* Default (none of the following parameters): +
Process the action requests as they stored for this client on the opsi-server.

* `/allloginscripts` or `/loginscripts` +
Process the login scripts of the opsi products. Using  `/allloginscripts` all login scripts that are known to the opsi-server will be processed, no matter iftheses products are known to the client or not. Using `/loginscripts` only these login scripts will be precessed that belong to products that are installed or were installed and then removed (technical: there is an existing productOnClient object).

* `/productlist` <productid>[,<productid>]* +
Process the given `/productlist` in a way as it would normally done if there are the action request 'setup' is stored at the opsi-server. +
Usally used by the `event_silent_install`.

* `/processproducts` <productid>[,<productid>]* +
Process the action requests as they stored for this client on the opsi-server but limited to the list of products given by `/processproducts`.



////
There are the following syntactical schemata:

(1) Show usage:

`opsi-script /?` +
`opsi-script /h`[elp]

(2 ) Execute a script

`opsi-script` <script file> +
      [`/logfile` <log file> ] +
      [`/batch` | `/histolist` <opsi-script config file path>] +
      [`/usercontext` <[domain\]user name> ] +
      [`/parameter` parameter string]

(3) Execute a list of scripts (separated by semicolons) one by one:

`opsi-script` `/scriptfile` <scriptfile> [;<script file>]* [ `/logfile` <log file> ] +
      [`/batch` | `/silent` ] +
      [`/usercontext` <[domain\]user name> ] +
      [`/parameter` <parameter string>] +

4) Process the action requests stored on the opsi-server using the opsi service (since _{opsi-script}_ 4.11.2)

`opsi-script /opsiservice` <opsiserviceurl> +
     `/clientid` <clientname> +
     `/username` <username> +
     `/password` <password> +
     [`/sessionid` <sessionid>] +
     [`/usercontext` <[domain\]username>] +
     [`/allloginscripts` | `/loginscripts`|  +
     `/productlist` <productid>[,<productid>]* | +
     `/processproducts` <productid>[,<productid>]* ] +
     [`/silent`]

Note:: At Linux or macOS the parameter delimiter is not "/" but "-". So instead of using `opsi-script /help` like you would do at Windows you should use at Linux / macOS `opsi-script -help`.

Some explanations:

* Default name of the log file is an Windows `c:\opsi.org\log\opsi-script.log`

* The parameter string, which is marked by the option `/parameter`, is accessible for every called _{opsi-script}_ script (via the string function `ParamStr`).


Explanations to (2) and (3) :

* If option `/batch` is used, then _{opsi-script}_ shows only its "batch surface" offering no user dialogs. By option `/silent` event the batch surface is suppressed. Without using option `/batch` we get into the interactive mode where script file and log file can be chosen interactively (mainly for testing purposes).

* The `winstconfigfilepath` parameter which is designated by `/histofile` refers to a file in ini file format that holds the (in interactive mode) last used script file names. The dialogue surface presents a list box that presents these file names for choosing the next file to interpret. If `winstconfigfilepath` ends with "\" it is assumed to be a directory name and `WINST.INI` serves as file name.

Explanations to (4):

* The default for `clientid` is the full qualified computer name

* When called with option `/allloginscripts` or `/loginscripts` _{opsi-script}_ can do configurations for the logged in user (particularly in a Roaming Profile context). This is a cofunding feature - you need to buy it in order to use it. +
See at the opsi-manual for more information about 'User Profile Management'.

* `/productlist` followed by a list of productIds ignores the normal handling of action request +
but forces to handle the given productIds like there were the action request `setup`.

* `/processproducts` followed by a list of productIds limit the normal handling of action request +
to these products that are given by the list of productIds. +
Attention: This may break existing dependencies.

* By option `/silent` the batch surface is suppressed.


The not interactive mode is implied.
////

[[opsi-script-logpath]]
== Log File and Paths

The default log file name is `opsi-script.log`.
You may find (by default) up to 8 backup copys of old log files: from `opsi-script_0.log` until `opsi-script_8.log`. + 
The default number of backups may be overwritten by using the config: <<opsi-script-configs_log_rotation_count>>

The log file encoding is UTF-8.

By default log files are written at Windows into the directory `c:\opsi.org\log` which _{opsi-script}_ tries to create. If _{opsi-script}_ has no access to this directory it uses the user-TEMP directory.

At Linux:
If running as `root` (default): `/var/log/opsi-script`
If running as any other user: `/tmp`

The log file name and location will be overwritten via the specific command line option.

In the case, that _{opsi-script}_ executes a script in `/batch` mode and with a specified (and working) usercontext, the default logging path is the `opsi/tmp` in the appdata directory of the user. This will be overwritten by an explicit given log path.

More possibilities to configure the logging: +
see also: <<opsi-script-configs_writeProductLogFile>> +
see also: <<opsi-script-configs_default_loglevel>> +
see also: <<opsi-script-configs_force_min_loglevel>> +
see also: <<opsi-script-configs_debug_lib>> +
see also: <<opsi-script-configs_log_rotation_count>> +

Beside the normal log file there is also a log file named `opsi-script.history`. This log file contains one line for every run of a product script since the first run.
These lines have the pattern: + 
`<timestamp> handled: <productid> Version: <version> Request: <request> Result: <result>` +
Example: +
`2022-01-18 00:09  handled : gimp Version: 2.10.30-1 Request: setup Result: success` +

[[opsi-script-configs]]
== Central configuration via opsi Configs (Host Parameter)

Using opsi Configs (`Host-Parameter`) you may now change the logging:

anchor:opsi-script-configs_debug_prog[]

* `opsi-script.global.debug_prog` : boolean  +
If false log messages that are only relevant for debugging the opsi-script program it self are not written excepting Warnings and Errors. +
Default: false +
This will keep the log files smaller because you will find only messages that are relevant for understanding what your script is doing. +
The adjustment of all log messages to this new way is in progress and will be take a while since all (about 1700) log calls inside the code are reviewed.

anchor:opsi-script-configs_debug_lib[]

* `opsi-script.global.debug_lib` : boolean +
If false log messages from defined functions that are imported from external library files will be suppressed excepting Warnings and Errors. +
Default: false

anchor:opsi-script-configs_default_loglevel[]

* `opsi-script.global.default_loglevel` : intstr +
Sets (overrides) the default log level that is imlemented inside the opsi-script code. This config has no effect on scripts where the loglevel is explicit set by a `setLogLevel` statement. +
Default:  '6' +
see also xref:prim-section.adoc#SetLogLevel[SetLogLevel] +
see also <<opsi-script-configs_force_min_loglevel>>

anchor:opsi-script-configs_force_min_loglevel[]

* `opsi-script.global.force_min_loglevel` : intstr +
Forces a minimal log level. +
This can be used while debugging or development to set temporary and for selected clients a higher log level wthout changing the script.
Default: '0' +
see also xref:prim-section.adoc#SetLogLevel[SetLogLevel] +
see also <<opsi-script-configs_default_loglevel>>

anchor:opsi-script-configs_ScriptErrorMessages[configs_ScriptErrorMessages]

* `opsi-script.global.ScriptErrorMessages` : boolean  +
This config overwrites the opsi-script internal default value for `ScriptErrorMessages` if opsi-script is running in the context of the opsi web service.
If the value is true, syntactical errors trigger a pop up window with some informations on the error. This is in productive environments no good idea. Therefore the default value for this config is 'false'. +
Inside a script the statement `ScriptErrorMessages` may be used to set this different from the defaults. +
Default: false +
see also : xref:prim-section.adoc#ScriptErrorMessages[ScriptErrorMessages]

anchor:opsi-script-configs_AutoActivityDisplay[configs_AutoActivityDisplay]

* `opsi-script.global.AutoActivityDisplay` : boolean  +
If true shows a marquee (endless) progressbar while external processes (winbatch/dosbatch sections) are running. +
Default: true +
see also : xref:prim-section.adoc#AutoActivityDisplay[AutoActivityDisplay]

anchor:opsi-script-configs_SupressSystemEncodingWarning[]

* `opsi-script.global.SupressSystemEncodingWarning` : boolean  +
If true the warning: `Encoding=system makes the opsiscript not portable between different OS` will be supressed. +
Default: false +
see also: xref:configuration-options#encoding[encoding]

anchor:opsi-script-configs_ReverseProductOrderByUninstall[]

* `opsi-script.global.ReverseProductOrderByUninstall` : boolean  +
If true the product list is reordered so that
uninstall actions will be conducted first and in reverse order as the prodcuts were installed  +
Default: false +

anchor:opsi-script-configs_log_rotation_count[]

* `opsi-script.global.log_rotation_count` : string (number) // seit 4.12.4.29 +
Defines the number of opsi-script.log backups that will be stored in the log directory on the client. (`opsi-script_0.log, opsi-script_1.log, ...`) +
Default = 8 ; Max = 999 +

anchor:opsi-script-configs_writeProductLogFile[]

* `opsi-script.global.writeProductLogFile` : boolean   // seit 4.12.4.35 +
If true logs for every single opsi product will be created. You will find these log in the sub directory `lastprodlogs` of the opsi-script log directory (E.g. `c:\opsi.org\log\lastprodlogs`). The name of these log files is `<productId>.log`. There is always only the last log for every product. If the product script contains reboots in (not after) the script, the log contains only the part after the last reboot. +
Default: false +


////
Removed by do 20210803)

anchor:opsi-script-configs_w10bitlockersuspendonreboot[]

* `opsi-script.global.w10bitlockersuspendonreboot` : boolean  +
If this config is true and the script has a reboot request it will be checked
if the Operating System is Windows >= 10 and bitlocker is active (encryption > 0%) on the system drive (e.g. c:). If all these conditions are given, opsi-scrpt calls via powershell a `suspend-bilocker`. +
(https://docs.microsoft.com/en-us/powershell/module/bitlocker/suspend-bitlocker?view=win10-ps) +
This causes, that after the reboot no password input is needed. This method leads to a loss of security: +
"Suspension of BitLocker does not mean that BitLocker decrypts data on the volume. Instead, suspension makes key used to decrypt the data available to everyone in the clear." +
Default: false +
////

