////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      11.01.2021
:doctype: book

include::common:partial$opsi_terms.adoc[]



[[opsi-script-configuration-options]]
= Additional Configurations

[[opsi-script-central-logging]]
== Central Logging of Error Messages

If the '{opsi-script}' running in opsi web service mode, it sends the log file via opsi web service to the opsi server.

[[opsi-script-skins]]
== Skinnable '{opsi-script}' [W/L/M]

Since version 3.6 the '{opsi-script}' GUI can be customized. The elements for customizing are to be found in the winstskin subdirectory of the '{opsi-script}' directory. The configuration file for customization is skin.ini.

Since version 4.12.4.15 the 'opsi-script' searches the skin directory in the following order (directory with the first skin.ini to be found wins):

*Windows*:

`%OpsiScriptDir% = C:\Program Files (X86)\opsi.org\opsi-client-agent\opsi-script`

. `%OpsiScriptDir%\..\custom\customskin`
. `%OpsiScriptDir%\skin`
. `%OpsiScriptDir%\winstskin`(for backward compatibility)

*Linux*:

`%OpsiScriptDir% = /opt/opsi-script`

. '/usr/share/opsi-script/skin'
. '/usr/share/opsi-script/customskin' (for backward compatibility)
. `%OpsiScriptDir%/skin`

see also: xref:linux-macos.adoc#opsi-script-linux-path[opsi-script-linux-path]

*macOS*:

`%OpsiScriptDir% = /Applications/opsi-script/Contents/macOS`

. '/usr/share/opsi-script/skin'
. `%OpsiScriptDir%/../Resources/skin`

see also: xref:linux-macos.adoc#opsi-script-macos-path[opsi-script-macos-path]

With the Command `SetSkinDirectory` the SkinDirectory to be used can be defined in the script. If the path specified is empty or not valid, the default path will be used.

Example:
[source,opsiscript]
----
SetSkinDirectory "%ScriptPath%\testskin"
sleepseconds 1
SetSkinDirectory ""
----

[[opsi-script-encoding]]
==  '{opsi-script}' encoding [W/L/M]

*Some technical notes about the wording:*

* `ASCII, plain ASCII` +
ASCII stands for: American Standard Code for Information Interchange +
'plain ascii': 7 Bit / per char for 128 different chars.
This will be found as base of the following.

* `ANSI, Codepages` +
Using 8 Bit (Byte) / per char for 255 different chars.
Lower 128 chars = ASCII, Upper 128 Chars according to selected 'Code page'.
Well known 'code pages': +
Windows-1252 = CP1252 = ISO 8851-1 = Western Europe code page. +
The first 256 Chars of CP1252 are also part of Unicode. +
'ANSI' stands for American National Standards Institute: +
https://stackoverflow.com/questions/701882/what-is-ansi-format : +
'ANSI encoding is a slightly generic term used to refer to the standard code page on a system, ( ... )The name "ANSI" is a misnomer, since it does not correspond to any actual ANSI standard, but the name has stuck.' +
So what is an an ANSI-String ? +
https://wiki.freepascal.org/Character_and_string_types#AnsiChar says: +
'A variable of type AnsiChar, also referred to as char, is exactly 1 byte in size, and contains one "ANSI" (local code page) character.' +
The problems with using code pages are: +
** You have to use different encoding in different places of the world.
** Maximum 255 Chars can be coded, but some languages have a lot more characters.

* `Unicode, UTF-8` +
'Unicode' is (like 'ANSI') a encoding family (and not a encoding).
The most important difference to using code pages is, that here we use to encode one char (possibly) more than one byte (exactly: up to 4 bytes). +
The most important members of the Unicode family are:

** `UTF-16-LE` (also some times called 'Windows Unicode'): +
Uses a minimum length of 2 Bytes per char up to 4 Bytes. The 'LE' stands for 'Little Endian' and tell us that the most significant byte of a char is the last one. (char 'n' : LE='6E 00', BE='00 6E')

** `UTF-8`: +
Uses for the chars out of 'plain ASCII' one byte but for every thing else 2 up to 4 bytes. +
So in fact: a file that uses only plain ASCII is the same binary wether you save it in cp1252 or utf8.

** `BOM` +
A file with 'Unicode' encoding may contain in the first 4 Bytes the information about the used (unicode-)encoding. This is the 'BOM' ('Byte Order Mark'). If there is a 'BOM', opsi-script will detect and use it.

The default encoding for a script is the encoding of the running operating system. So for example one script will be interpreted on a Greek windows system as encoded with cp1253 on a German windows system as cp1252 and under Linux as UTF-8.

TIP: We strongly recommend to create all your opsiscript files in UTF-8 encoding and add the line `encoding=utf8` to the file. +
This makes your files portabel. +
See also below.

anchor:encoding[]

* `encoding=`<encoding> +
Since Version 4.11.4.1 it is possible to define the encoding in the script. This may be done in the main script and in the sub scripts, includes and libraries as well. You have to give the command: +
`encoding=`<encoding> +
This command can be at any position in the code (Even before [actions]). +
If the command `encoding=` is missing, than the expected encoding is the system encoding of the running operating system. At Linux and macOS this would be UTF-8. At Windows the system encoding a cp* and depends on the localization. In Western Europe for example z.B. cp1252. +
If the input file contains umlauts (is not pure 'plain ASCII') and there is no line: `encoding=utf8`, then you will get a warning: +
'Encoding=system makes the opsiscript not portable between different OS'. +
This Warning may be suppressed by the config (Host Parameter): +
`opsi-script.global.supresssystemencodingwarning = true`. +
siehe auch xref:cli-params.adoc#opsi-script-configs_supresssystemencodingwarning[opsi-script.global.ScriptErrorMessages] +
 +
If the input file contains umlauts (is not pure 'plain ASCII') and there is a discrepancy between the detected encoding (c.f. by a BOM) and the implicit encoding 'system' or the given encoding by `encoding=`, then you will get the following warning: +
'Warning: Given encodingString <> is different from the expected encoding <>' +
 +
Using the command: `encoding=`<encoding> +
the <encoding> may be one of the following values:

.Encodings
[options="header"]
|==========================
|encoding|allowed alias|Remark
|system	|	|	use the encoding of the running OS
|auto	|	|	try to guess the encoding
|UTF-8      |   utf8	|
|UTF-8BOM   |   utf8bom	|
|Ansi       |   ansi     |		8 Bit encoding with Codepage
|CP1250     |   cp1250   |		Central and East European Latin
|CP1251     |   cp1251   |		Cyrillic
|CP1252     |   cp1252   |		West European Latin
|CP1253     |   cp1253   |		Greek
|CP1254     |   cp1254   |		Turkish
|CP1255     |   cp1255   |		Hebrew
|CP1256     |   cp1256   |		Arabic
|CP1257     |   cp1257   |		Baltic
|CP1258     |   cp1258   |		Vietnamese
|CP437      |   cp437    |		Original IBM PC hardware code page
|CP850      |   cp850    |		"Multilingual (Latin-1)" (Western European languages)
|CP852      |   cp852    |		"Slavic (Latin-2)" (Central and Eastern European languages)
|CP866      |   cp866    |		Cyrillic
|CP874      |   cp874    |		Thai
|CP932      |   cp932    |		Japanese (DBCS)
|CP936      |   cp936    |		GBK Supports Simplified Chinese (DBCS)
|CP949      |   cp949    |		Supports Korean (DBCS)
|CP950      |   cp950    |	Supports Traditional Chinese (DBCS)
|ISO-8859-1 |   iso8859-1|		Latin-1
|ISO-8859-2 |   iso8859-2|		Latin-2
|KOI-8      |   koi8     |		Kyrillisches Alphabet
|UCS-2LE    |   ucs2le   |		(UTF-16-LE, Windows Unicode Standard)
|UCS-2BE    |   ucs2be   |		(UTF-16-BE)
|==========================

see also : xref:prim-section.adoc#reencodestr[reencodestr] +
see also : xref:prim-section.adoc#reencodestrlist[reencodestrlist] +
see also : xref:prim-section.adoc#strLoadTextFileWithEncoding[strLoadTextFileWithEncoding] +
see also : xref:prim-section.adoc#loadUnicodeTextFile[loadUnicodeTextFile] +
see also : xref:prim-section.adoc#loadTextFileWithEncoding[loadTextFileWithEncoding] +

Sources see: +
https://en.wikipedia.org/wiki/Code_page

http://msdn.microsoft.com/en-us/library/windows/desktop/dd317752%28v=vs.85%29.aspx

http://msdn.microsoft.com/en-us/library/cc195054.aspx

https://en.wikipedia.org/wiki/ANSI_character_set

https://en.wikipedia.org/wiki/UTF-8
