////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      02.05.2023
:Revision:  4.2
:toclevels: 6
:doctype:   book
:icons: font
:xrefstyle: full

[[opsi-create-client-intro]]
= Introduction

For opsi to be able to manage computers, these clients must be known to the system. In addition, an agent must run on the client computers, so that the server and the client can communicate with each other. Depending on how your enviroment, there are different ways to add clients:

* Existing clients with an operating system can be managed by opsi from now on if you integrate them (see chapter xref:create-client:integrating-clients.adoc[Integrating existing Clients]).

* Alternatively, you can use opsi to install an operating system on a client which automatically installs the required agent (see chapter xref:create-client:adding-clients.adoc[Adding new Clients]).

