////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      08.05.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]



= {opsi-server}

[[opsi-manual-server-overview]]
==  Überblick

*{opsi-configserver}*
Die zentrale Steuerungs-Komponente jeder opsi-Umgebung ist der {opsi-configserver}.
Es gibt in jeder Umgebung nur einen {opsi-configserver}.
Der {opsi-configserver} stellt die Konfigurations- und Statusdaten über eine API zur Verfügung.
Alle Server-, Client- und Management-Komponenten sind über diese zentrale API gekoppelt.
Ein {opsi-configserver} übernimmt in der Regel auch zusätzlich die Rolle eines {opsi-depotserver}s.

*{opsi-depotserver}*
Ein {opsi-depotserver} stellt Dateien der zu verteilenden Software, Betriebssysteme und Bootimages zur Verfügung.
Zusätzlich kann er weitere benötigte Dienste (z.B. DHCP-Server) zur Verfügung stellen.
Der {opsi-depotserver} ist über den opsi-Messagebus mit dem {opsi-configserver} verbunden und wird von diesem gesteuert.
{opsi-depotserver} kommen oft in Außenstellen zum Einsatz um einen performanten Zugriff auf Dateien und Services im LAN zu gewährleisten.


Hier finden Sie weitere Informationen:

* xref:server:installation/installation.adoc[Installation und Inbetriebnahme eines {opsi-server}s]
