////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      22.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



= opsi-Server

In diesem Kapitel geht es um den opsi-Server, die zentrale Komponente des Client-Management-Systems. Das Kapitel xref:server:installation/installation.adoc[Installation] beschreibt verschiedene Möglichkeiten, einen opsi-Server zu installieren. In xref:server:components/components.adoc[Tools & Settings] geht es dann um den Betrieb (Werkzeuge und Konfiguration).

[[opsi-manual-server-overview]]
== Server-Varianten

Grundsätzlich gibt es zwei verschiedene Serverarten, die auf derselben oder auf unterschiedlichen Rechnern installiert sein können (siehe Abschnitt xref:server:components/opsiconfd.adoc#server-components-opsiconfd-server-id-role[Server-Rolle]).

* *opsi-Configserver*:
Die zentrale Steuerungs-Komponente jeder opsi-Umgebung ist der opsi-Configserver.
Es gibt in jeder Umgebung nur einen opsi-Configserver.
Der opsi-Configserver stellt die Konfigurations- und Statusdaten über eine API zur Verfügung.
Alle Server-, Client- und Management-Komponenten sind über diese zentrale API gekoppelt.
Ein opsi-Configserver übernimmt in der Regel auch zusätzlich die Rolle eines opsi-Depotservers.

* *opsi-Depotserver*:
Ein opsi-Depotserver stellt Dateien der zu verteilenden Software, Betriebssysteme und Boot-Images zur Verfügung.
Zusätzlich kann er weitere benötigte Dienste (z.{nbsp}B. DHCP-Server) zur Verfügung stellen.
Der opsi-Depotserver ist über den opsi-Message-Bus mit dem opsi-Configserver verbunden und wird von diesem gesteuert.
opsi-Depotserver kommen oft in Außenstellen zum Einsatz, um einen performanten Zugriff auf Dateien und Services im LAN zu gewährleisten.
