////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      24.04.2023
:Revision:  4.2
:toclevels: 6
:doctype:   book
:icons: font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

////
TODO: In andere Kapitel eingliedern

[[opsi-getting-started-requirements]]
= Voraussetzungen

Dieses Kapitel beschreibt die Voraussetzungen für die Installation des {opsi-server}s unter Linux. Eine Liste der unterstützten Distributionen finden Sie im Kapitel xref:supportmatrix:supportmatrix.adoc[Unterstützte Systeme].


[[opsi-getting-started-requirements-software-dns-resolving]]
=== Korrekte Namensauflösung für den Server

Kontrollieren Sie den Eintrag für den {opsi-server} in der Datei `/etc/hosts` oder geben Sie den folgenden Befehl auf der Kommandozeile ein:

[source,shell]
----
getent hosts $(hostname -f)
----

Das Ergebnis sollte beispielsweise so aussehen:

[source,shell]
----
192.168.1.1 server.domain.tld server
----

Dabei sollte die IP-Adresse der Netzwerkschnittstelle aufgeführt sein, zu der sich die Clients später verbinden sollen. Sehen Sie in der Datei `/etc/hosts` nur Einträge für `localhost`, `127.0.0.1` oder `127.0.0.2`, dann korrigieren Sie die Namensauflösung, bevor Sie fortfahren.

NOTE: Auch wenn die Namen den Vorgaben eines DNS-Systems entsprechen müssen, benötigen Sie keinen DNS-Server für den Betrieb von opsi. opsi setzt ebenfalls kein Active Directory o.{nbsp}Ä. voraus, auch wenn eine Integration in einen Verzeichnisdienst möglich ist.

[[opsi-getting-started-requirements-software-lang]]
=== Spracheinstellungen (`locale`)

opsi setzt voraus, dass auf dem Server die Sprache mittels `locale` gesetzt ist. Um die Spracheinstellungen zu überprüfen, können Sie beispielsweise das folgende Kommando eingeben:

[source,shell]
----
test -e /etc/default/locale && echo "ok" || (echo "Check locales:" && locale)
----

Sehen Sie `ok` als Antwort, ist alles in Ordnung. Erscheint hingegen `check locales:`, dann setzen Sie die Einstellungen über die Umgebungsvariablen `LANG` oder `LC_ALL`.

TIP: Wir empfehlen eine Lokalisierung mit UTF-8-Unterstützung, z.{nbsp}B. `de_DE.UTF-8` für Deutsch.

Die folgenden Befehle zeigen beispielhaft, wie Sie die Einstellungen ändern können, sollte kein Wert oder ein unerwünschter Wert gesetzt sein:

[source,shell]
----
sudo locale-gen de_DE.UTF-8
update-locale LANG=de_DE.UTF-8
----

Weitere Informationen entnehmen Sie bitte dem Handbuch der von Ihnen verwendeten Linux-Distribution.

[[opsi-getting-started-installation-config-ports]]
== Verwendete Netzwerk-Protokolle und -Ports

opsi und seine Dienste verwenden die folgenden Netzwerk-Protokolle und Ports:

* opsi-Server, Webservice: 4447/tcp +
Client zum Config- und Depot-Server, Depot-Server zum Config-Server, auch Verbindungen via `localhost`
* opsi-Client, Webservice: 4441/tcp +
Config-Server zum Client, Verbindung vom Client zu sich selbst via `localhost`
* opsi-Client, Notifier: 45000/tcp bis 45099/tcp +
Verbindung vom Client zu sich selbst via `localhost`, Auswahl eines zufälligen Ports aus dem angegebenen Bereich
* TFTP: 69/udp +
Verbindung vom Client zum Depot-Server
* TFTP: 1024/udp bis 65535/udp +
Verbindung vom Depot-Server zum Client
* CIFS/SMB: 445/tcp +
Verbindung vom Client zum Depot-Server
* CIFS/SMB: 445/tcp +
Verbindung vom Depot-Server zum Client (nur notwendig, wenn `opsi-deploy-client-agent` (`winexe`, `smbclient`) für Windows-Clients verwendet wird)
* Grafana, Webservice: 3000/tcp +
Verbindung vom Client zum Config-Server (nur bei Zugriff vom Client auf die Management-Website des Config-Servers)
* SSH: 22/tcp +
Verbindung vom Client zum Config-Server und Depot-Server
* SSH: 22/tcp +
Verbindung vom Depot-Server zum Client (nur beim Einsatz von `opsi-deploy-client-agent` unter Linux und macOS)
* DNS: 53/tcp, 53/udp +
Alle Server und Clients müssen Ihren DNS-Dienst erreichen können.
* Wake-on-LAN (WoL): 7/udp, 9/udp, 12287/udp  +
Verbindung vom Config-Server zum Client; Ports sind konfigurierbar
* HTTP: 80/tcp +
Config- und Depot-Server ins Internet, um z.{nbsp}B. Server-Updates von http://download.opensuse.org zu laden
* HTTPS: 443/tcp +
Config- und Depot-Server ins Internet, um z.{nbsp}B. Pakete von https://download.uib.de zu laden (`opsi-package-updater`)

NOTE: Der Config-Server ist der zentrale {opsi-server} zur Verwaltung aller Clients. Der Depot-Server ist der Server, der die Installationspakete der eingesetzten Software vorhält. Wenn es nur einen einzigen {opsi-server} gibt, so übernimmt dieser beide Rollen.

////