////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author: uib gmbh
:Email: info@uib.de
:Revision: 4.1
:website: http://opsi.org

include::../common/opsi_terms.asciidoc[]


[[opsi-manual-glossary]]
== Glossar

////
Asciidoc unterstützt die Erstellung von Glossar-Einträgen, wenn sie im
folgenden Format geschrieben werden:

Begriff::
  Eingerückte Beschreibung

////


Action-Request::
  Die nächste geplante Aktion auf einem Client. Typische Actionrequests sind 'setup', 'uninstall' oder 'update'.


Backend::
  opsi unterstützt unterschiedliche Arten der Datenhaltung, bspw. Dateibasiert oder in einer Datenbank. Diese werden als Backends bezeichnet.


client Id::
  Eindeutige Bezeichnung eines Clients durch Verwendung des 'fully qualified domain name' (FQDN).


Config-Server::
  Server, welcher für die Bereitstellung von Management- und Konfigurationsdaten in einer opsi-Umgebung zuständig ist.


Depot-Server::
  Server, welcher Installationsdateien und Ablaufsteuerungsdaten über einen Samba-Share für Clients zur Installation bereit stellt.


DHCP (Dynamic Host Configuration Protocol)::
  Ein Protokoll, welches die dynamische Vergabe von IP-Adressen ermöglicht.


FQDN (Fully Qualified Domain Name)::
  Vollständiger Name eines Computers in einem Netzwerk, welcher aus IP-Name und Domain besteht,
  z.B. 'fritzlaptop.uib.local'.


GUI (Graphical User Interface)::
  Grafische Schnittstelle zum Anwender.


host Id::
  Eindeutige Bezeichnung eines Hosts (umfasst sowohl Client als auch Server) durch Verwendung des 'fully qualified domain name' (FQDN).


JSON (JavaScript Object Notation)::
  JSON ist ein kompaktes Computer-Format in für Mensch und Maschine einfach lesbarer Textform zum Zweck des Datenaustauschs zwischen Anwendungen.


Last seen::
  Zeitstempel wann ein Client sich zuletzt am opsi-Server gemeldet hat.


Localboot-Produkt::
  Ein opsi-Produkt, welches bei laufendem Betriebssystem auf diesem installiert wird.


MAC-Adresse (Media Access Control-Adresse)::
  Mit der MAC-Adresse bezeichnet man eine weltweit eindeutige Nummer der Netzwerk­karte, die bei jeder Datenübertragung mitgesendet wird. Anhand dieser Adresse kann man einen Computer (genauer: dessen Netzwerkkarte) eindeutig identifizieren, um bspw. eine IP-Nummer automatisch zu verteilen o.ä..
  Die Nummer setzt sich aus 6 zweistelligen Hexadezimalzahlen zusammen, die durch einen Doppelpunkt voneinander getrennt sind.


Netboot-Produkt::
  Ein opsi-Produkt, welches beim Start über das Netzwerk gestartet wird.
  Oftmals verwendet zur Betriebssysteminstallation auf einem Computer.


opsi::
  open pc server intergration


opsi-client-agent::
  Agent der auf einem Windows-Client installiert ist und dort zentral gesteuert Software installiert.


opsi-server::
  Ein Server der im Rahmen von opsi benötigte Dienste bereitstellt. Üblicherweise 'Config-Server' und 'Depot-Server'.


opsiconfd::
  Server-Dienst, welcher die opsi-Konfigurations-API als Webservice zur Verfügung stellt.


Product Properties::
  Zusätzliche Einstellungen zu einem opsi-Produkt die clientspezifisch gesetzt werden können und bei der Installation ausgewertet werden.


Produkt-ID::
  Eindeutiger Bezeichner eines opsi-Produkts.
  Kann aus a-z, Zahlen und Bindestrichen bestehen.
  Darf keine Leerzeichen oder Sonderzeichen (außer Bindestrich enthalten).
  Beispiel für eine Product-ID: 'acroread'


Produktname::
  Klartextname eines Produktes. Beispiel für einen Produktnamen: 'Adobe Acrobat Reader'


PXE (Preboot eXecution Environment)::
  Standard für den Boot einer Software über das Netzwerk. Wird in der Regel im Zusammenspiel mit 'DHCP' eingesetzt.


SAMBA::
  Freie Software, um unter Linux Dienste für das von Microsoft-Clients verwendet Protokoll 'SMB' anzubieten.


SMB	(Server Message Block)::
  Protokoll von Microsoft, um Netzwerklaufwerke und Authentifizierung anzubieten.
  Ein Dialekt von SMB ist 'CIFS' (Common Internet File System).


tftp (Trivial File Transfer Protocol)::
  Ein tftp-Dienst ('tftpd') erlaubt das Übertragen von Dateien von und zu anderen Rechnern im Netzwerk ohne Login-Prozedur, allerdings mit restriktiven Zugangsbeschränkungen.
  So dürfen nur solche Dateien gelesen oder geschrieben werden, die aufgrund ihrer Zugriffsrechte von allen Benutzern les- oder beschreibbar sind und in einem speziellen Verzeichnis liegen.
