////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////

////
;***************************************************************************
; Subversion:
; $Revision$ $Author$
; $Date$
;***************************************************************************
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      20.08.2014
:Revision:  4.0.5
:toclevels: 6


include::../common/opsi_terms.asciidoc[]

[[opsi-manual-uefi]]
== opsi mit UEFI / GPT


[[opsi-manual-uefi-preconditions]]
=== Vorbedingungen für das Arbeiten mit UEFI / GPT

Dieses Modul ist momentan eine
http://www.uib.de/www/kofinanziert/index.html[kofinanzierte opsi Erweiterung]. +
Es sind eine Reihe von Vorbedingungen nötig, um dieses Modul einsetzen
zu können. Das bedeutet, das Sie zum Einsatz eine Freischaltdatei benötigen. Diese Freischaltung erhalten Sie wenn Sie die Erweiterung kaufen. Zu Evaluierungszwecken stellen wir Ihnen auch eine zeitlich befristete Freischaltung kostenlos zur Verfügung ( -> mail an info@uib.de). +
////
Weitere Details hierzu finden Sie in <<opsi-manual-modules>>.
////

Technische Voraussetzungen sind opsi 4.0.5 mit den Paketständen:

.Benötigte Pakete
[options="header"]
|==========================
|opsi-Paket|Version
|Netbootprodukte|>=4.0.5
|opsi Server Pakete|>=4.0.5
|==========================


[[opsi-manual-uefi-introduction]]
=== Einführung

Neue PC's, Tablets und Server enthalten meist ein UEFI BIOS. Häufig kann dieses in einen Legacy Mode umgestellt werden, um das bisherige Verhalten und die Unterstützung eines PXE Boots zu bekommen. Es tauchen aber auch zunehmend Geräte mit UEFI-only BIOS auf (besonders bei den Tablets). Diese lassen sich in einer bisherigen opsi Umgebung nicht per netboot verwalten.

Um auch diese Geräte in opsi integrieren bzw. die Vorteile von UEFI nutzen zu können, entwickelt die uib gmbh die opsi Erweiterung UEFI Support.

[[opsi-manual-uefi-whatisuefi]]
=== Was ist Uefi und was ist hier anders ?

UEFI steht für 'Unified Extensible Firmware Interface' und ist der Nachfolger des klassischen PC-BIOS (auch MBR-BIOS genannt).

Für Detailierte Informationen zum Thema UEFI finden sich unten einige Links.

UEFI ist ungleich mächtiger als das herkömmliche BIOS. Im Prinzip ist UEFI ein eigenes kleines Mini-Betriebssystem. Hier sollen aber nur Punkte erwähnt werden, welche für den Systemverwalter von besonderer Bedeutung sind:

* Die derzeitige (Stand Januar 2014) Umsetzung von UEFI in den BIOSen der Hardware Hersteller ist weit von dem Entfernt was man einen Standard nennen könnte. Vielmehr herrscht ein großes durcheinander wenn von einem anderen Medium geboot werden soll wie der Festplatte. UEFI und klassisches BIOS existieren teilweise Parallel, lassen sich mal einzeln deaktivieren mal nicht. UEFI ist mal mit Compatibility Support Module (CSM) implementiert mal ohne. Netboot geht oder auch nicht. +
Gerade der letzte Punkt (Netboot) ist natürlich für ein strukturiertes Client Management von großer Bedeutung.

* Im PC-BIOS ist das BIOS und dessen Einstellungen vom OS (in aller Regel) getrennt. D.h. BIOS Einstellungen wie z.B. die Bootreihenfolge sind statisch und können vom Betriebssystem nicht geändert werden. +
Dies ist bei UEFI anders. Das Betriebssystem kann die Bootreihenfolge ändern (und macht davon in der Regel auch Gebrauch). Auch dies hat wiederum Auswirkungen auf die Anbindung der Rechner an das Clientmanagement durch den Netboot. 

* Das UEFI-Bios enthält einen eigenen Bootmanager der nicht nur (siehe oben) in seiner Reihenfolge durch das Betriebsystem veränderbar ist, sondern auch die Starteinträge der Betriebssysteme selbst enthält. Damit wird ein nebeneinander von Unterschiedlichen Betriebssystemen vereinfacht weil die Bootloader unterschiedlicher Betriebssysteme sich nicht mehr überschreiben.

* Das UEFI BIOS ist in 32 oder 64 Bit implementiert. Damit ist dann auch die 'Bitigkeit' des Betriebssystems vorgegeben. D.h. kein 32 Bit OS auf einem 64 Bit UEFI System.

* Secureboot (von opsi noch nicht unterstützt)

* Partitionierung mit GPT und zusätzliche Partitionen für die Bootloader:

** 1. Partition: EFI System Partition (ESP) 100 - 260 MByte ; VFAT
** 2. Partition: Microsoft Reserved (MSR) 32 - 128 MB; NTFS
** Ab hier kommen jetzt die eigentlichen OS Partitionen



Links : 

http://de.wikipedia.org/wiki/Unified_Extensible_Firmware_Interface

[[opsi-manual-uefi-whatisgpt]]
=== Was ist anders an GPT

GPT (GUID Partition Table) ersetzen die bisherigen MBR Partitionstabellen. GPT ist Bestandteil der UEFI Spezifikation. 

Wesentliche Merkmale für den Sysadmin sind:

* Wegfall der 2 Terabyte Grenze (jetzt 8 Zebibyte)

* 'Beliebig' viele primäre Partitionen

* Geänderte Partitionstypen / GUIDs

* Neu: Partitions-GUIDs

* Neu: Partitions-Attribute (Hidden, Read only, ...)

* Andere Werkzeuge zur Bearbeitung: gdisk

Prinzipiell lässt sich GPT auch ohne UEFI verwenden. UEFI funktioniert aber nur mit GPT. Wird UEFI verwendet, 
so kommen ein bis zwei zusätzliche Partitionen hinzu:

. Die EFI System Partition (ESP) - hier liegen die Bootloader

. MS Reserved (MSR)

Links : 

http://de.wikipedia.org/wiki/GUID_Partition_Table

[[opsi-manual-uefi-uefiboot]]
=== UEFI Boot

Im Gegensatz zu herkömmlichen BIOSen kann hier die Bootreihenfolge nicht nur für Geräte, sondern auch für unterschiedliche Bootloader auf der EFI System Partition eingetragen werden. Darüberhinaus ist diese Reihenfolge auch von einem laufenden Betriebssystem manipulierbar. Wenn Sie also den Netboot als oberste Priorität festlegen, so wird dies die erste OS-Installation nicht überleben.

[[opsi-manual-uefi-uefinetboot]]
=== UEFI Netboot

Leider unterstützen viele frühe UEFI BIOSe noch kein Netboot, aber die Unterstützung wird zunehmend besser. 

Es gibt inzwischen schon eine ganze Reihe von UEFI Bootloadern (wie z.B. grub2, elilo), leider unterstützen die wenigsten davon einen Netboot. 

Die uib gmbh stellt mit der opsi-Erweiterung UEFI Support eine funktionierende Unterstützung für die Anbindung eines Clients über einen UEFI-Netboot an opsi vor. Gleichzeitig erwarten wir, dass im Rahmen der technischen Weiterentwicklung diese opsi-Erweiterung in den nächsten Jahren noch deutlich umgebaut werden wird.

[[opsi-manual-uefi-opsiuefinetboot]]
=== Opsi Unterstützung für UEFI Netboot

Die opsi Unterstützung für UEFI ist im Rahmen einer Reihe von Teilkomponenten umgesetzt:

* Anpassung des netbootfähigen UEFI Bootloaders ELILO an die opsi / Client-Management Bedürfnisse.

* Neuer opsipxeconfd, welcher neben Konfigurationsdateien für das bisherige PXE nun auch Konfigurations­dateien für den opsi-ELILO bereitstellt.

* Bereitstellung neuer (64Bit) opsi-linux-bootimages mit den Werkzeugen für UEFI- und GPT-Management

* Umbau aller Netbootprodukte zur Betriebssysteminstallation (Windows/Linux) auf die zusätzliche Unterstützung von UEFI/GPT. Hiervon sind natürlich jene Betriebssysteme ausgenommen welche von sich aus keine UEFI Unterstüztung haben.

* Speicherung der Einstellung ob ein Client als UEFI Client behandelt werden soll auf dem opsi-server (clientconfig.dhcpd.filename=linux/pxelinux.cfg/elilo.efi)

* Unterstützung einer Software gesteuerten Umschaltung auf UEFI-Netboot. +
Soweit das BIOS dies ermöglicht (es also einen aktivierbaren Netbooteintrag im Bios gibt) wird das Label des UEFI-Netboot Eintrages des Bios auf dem opsi-server gespeichert (clientconfig.uefinetbootlabel). Dies ermöglicht es opsi-produkten gezielt für den nächsten boot das Bios auf Netboot umzustellen. Diese Technik ist in verschiedenen opsi-Produkten implementiert. Ein wichtiges Beispiel ist das Produkt `opsi-uefi-netboot`: +
Dieses Produkt versucht das Bios auf netboot umzustellen und dann einen reboot auszulösen. Wird kein gespeichertes `uefinetbootlabel` gefunden oder handelt es sich nicht um einen UEFI Rechner wird nur ein reboot ausgelöst. +
Diese Produkt funktioniert sowohl unter Windows wie auch unter Linux.

[[opsi-manual-uefi-install]]
=== Installation

Alle notwendigen Pakete sind ab der opsi Version 4.0.5 automatisch installiert.

[[opsi-manual-uefi-dhcpd]]
=== Konfiguration des DHCP Servers

Beispiel aus einer Konfiguration eines Linux isc-dhcp-server:

----
filename "linux/pxelinux.0";

# Das ist die UEFI Detection:
if substring (option vendor-class-identifier , 19,1 ) = "0" {
        log (info, "pxe client");
        filename "linux/pxelinux.0";
}
else if substring (option vendor-class-identifier , 19,1 ) = "6" {
        log (info, "efi32 client");
        filename "linux/pxelinux.cfg/elilo32.efi";
}
else if substring (option vendor-class-identifier , 19,1 ) = "7" {
        log (info, "efi64 client");
        filename "linux/pxelinux.cfg/elilo.efi";
}
else {
        log (info, concat ( "Unhandled vendor class Arch: ", substring (option vendor-class-identifier , 19,1 )));
}
----

http://docs.fedoraproject.org/en-US/Fedora/17/html/Installation_Guide/s1-netboot-pxe-config.html

[[opsi-manual-uefi-goodbios]]
=== Kriterien für ein 'gutes' BIOS

Ob ein UEFI BIOS für die Anforderungen eines Client-Management-Systems wie opsi geeignet ist, hängt von verschiedenen Kriterien ab. Diese Kriterien sagen nichts  über die Qualität des Gerätes als solches aus, sondern nur über seine Wartbarkeit per Netboot-Anbindung. Es geht hier also um die BIOS-Funktionen zum UEFI Netboot. Hier ein beispielhafter Vergleich :

.Beispiele für UEFI BIOS Unterschiede
[options="header"]
|==========================
||Lenovo Twist|MS-Surface|Dell Venue 11
|UEFI pur|√|√|√
|UEFI + CSM|√|x|√
|Legacy|√|x|√
|Both|√|x|x
|UEFI Netboot|√|√|√
|Aktivierbarer Eintrag|√|x|√
|Netboot ohne Interaktion|√|x|√
|==========================

Unter 'Aktivierbarer Eintrag' verstehen wir, das sich per Standard-Software ein Netboot für den nächsten Reboot aktivieren läßt. 'Netboot ohne Interaktion' bedeutet, dass ein aktivierter Netboot-Eintrag beim Reboot ausgeführt wird und dazu keine Interaktion (drücken von Tastenkombinationen, F12-Taste, ...) nötig sind. Sind diese Vorausetzungen gegeben, können bestimmte opsi Produkte einen Netboot auslösen. Dies ist für die automatisierung von Abläufen von großer Bedeutung. Ein Produkt in dem dies implementiert ist ist das Localbootprodukt für Windows und Linux `opsi-uefi-netboot`.

[[opsi-manual-uefi-technical]]
=== Technisches

Die folgenden Unterkapitel dienen als Wissensbasis zu dem händigen oder gescripteten Umgang mit UEFI / GPT. Zum Verständnis wie opsi mit UEFI/GPT arbeitet sind sie nicht erforderlich.

[[opsi-manual-uefi-technical-uefi]]
==== Technisches zu UEFI

Manipulation der UEFI Bootloader Einträge passiert unter Linux mit dem Programm `efibootmgr`. +
Liste der Booteinträge:

[source,prompt]
----
efibootmgr -v
BootCurrent: 000D
Timeout: 0 seconds
BootOrder: 0012,0011,000D,0010,000B,0009,0007,0008,000A,000C
Boot0000  Setup	
Boot0001  Boot Menu	
(..)
Boot0007* USB CD	030a2400d23878bc820f604d8316c068ee79d25b86701296aa5a7848b66cd49dd3ba6a55
Boot0008* USB FDD	030a2400d23878bc820f604d8316c068ee79d25b6ff015a28830b543a8b8641009461e49
Boot0009* ATA HDD0	030a2500d23878bc820f604d8316c068ee79d25b91af625956449f41a7b91f4f892ab0f600
Boot000D* PCI LAN	030a2400d23878bc820f604d8316c068ee79d25b78a84aaf2b2afc4ea79cf5cc8f3d3803
Boot0010* ubuntu	HD(1,800,31801,faffb7b9-bdf9-4767-b475-0b8aee68d3ac)File(\EFI\ubuntu\grubx64.efi)
Boot0011* opsitempwinpe	HD(4,3c72800,7cf801,dc1cea68-a296-4fb8-a97a-263227ed86f4)File(\EFI\boot\bootx64.efi)
Boot0012* Windows Boot Manager	HD(1,800,31801,5e4ffde2-3e25-42dd-b0f7-fcb7ee5d2b20)File(\EFI\Microsoft\Boot\bootmgfw.efi)WINDOWS.........x...B.C.D.O.B.J.E.C.T.=.{.9.d.e.a.8.6.2.c.-.5.c.d.d.-.4.e.7.0.-.a.c.c.1.-.f.3.2.b.3.4.4.d.4.7.9.5.}...a................
----

Manipulation der UEFI Bootloader Einträge passiert unter Windows mit dem Programm `bcdedit`. +
Liste der Booteinträge:


[source,prompt]
----
bcdedit /enum firmware 

Start-Manager für Firmware
- - - - - - - - - - - - - - -
Bezeichner              {fwbootmgr}
displayorder            {bootmgr}
                        {99a9f9be-9a98-11e3-b22f-806e6f6e6963}
                        {11a8b97e-99df-11e3-ae5c-b888e3e3cbb4}
                        {11a8b986-99df-11e3-ae5c-b888e3e3cbb4}
Windows-Start-Manager
- - - - - - - - - - - - - - -
Bezeichner              {bootmgr}
device                  partition=\Device\HarddiskVolume1
path                    \EFI\Microsoft\Boot\bootmgfw.efi
Firmwareanwendung (101fffff)
- - - - - - - - - - - - - - -
Bezeichner              {11a8b971-99df-11e3-ae5c-b888e3e3cbb4}
description             Setup
Firmwareanwendung (101fffff)
- - - - - - - - - - - - - - -
Bezeichner              {11a8b972-99df-11e3-ae5c-b888e3e3cbb4}
description             Boot Menu
(...)
Firmwareanwendung (101fffff)
- - - - - - - - - - - - - - -
Bezeichner              {11a8b978-99df-11e3-ae5c-b888e3e3cbb4}
description             USB CD
Firmwareanwendung (101fffff)
- - - - - - - - - - - - - - -
Bezeichner              {11a8b979-99df-11e3-ae5c-b888e3e3cbb4}
description             USB FDD
Firmwareanwendung (101fffff)
- - - - - - - - - - - - - - -
Bezeichner              {11a8b97a-99df-11e3-ae5c-b888e3e3cbb4}
description             ATA HDD0
Firmwareanwendung (101fffff)
- - - - - - - - - - - - - - -
Bezeichner              {11a8b97e-99df-11e3-ae5c-b888e3e3cbb4}
description             PCI LAN
Firmwareanwendung (101fffff)
- - - - - - - - - - - - - - -
Bezeichner              {99a9f9be-9a98-11e3-b22f-806e6f6e6963}
device                  partition=X:
path                    \EFI\boot\bootx64.efi
description             opsitempwinpe
----

Mit beiden Programmen lassen sich Einträge erstellen, löschen, der 'nextboot' setzen und die Reihenfolge manipulieren.

Beispiel: Eintrag für den nächsten Boot setzen:

Linux
[source,prompt]
----
efibootmgr /bootnext <hexId>
----

Windows
[source,prompt]
----
bcdedit /set {fwbootmgr} bootsequence <GUID>
----

[[opsi-manual-uefi-technical-gpt]]
==== Technisches GPT

GPT Partitionen kennen 'neue' Partitionstypen. Diese sind an die bisher bekannten angelehnt. So wird aus dem Partitionstyp für NTFS `07` unter GPT `0700`. Analog wird aus den Linux Partitionstypen `82` und `83` entsprechend `8200` und `8300`.

Die Liste der bekannten Partitionstypen kann man sich anzeigen lassen:
[source,prompt]
----
# sgdisk -L
0700 Microsoft basic data  0c01 Microsoft reserved    2700 Windows RE
4100 PowerPC PReP boot     4200 Windows LDM data      4201 Windows LDM metadata
7501 IBM GPFS              7f00 ChromeOS kernel       7f01 ChromeOS root
7f02 ChromeOS reserved     8200 Linux swap            8300 Linux filesystem
8301 Linux reserved        8302 Linux /home           8400 Intel Rapid Start
8e00 Linux LVM             a500 FreeBSD disklabel     a501 FreeBSD boot
a502 FreeBSD swap          a503 FreeBSD UFS           a504 FreeBSD ZFS
a505 FreeBSD Vinum/RAID    a580 Midnight BSD data     a581 Midnight BSD boot
a582 Midnight BSD swap     a583 Midnight BSD UFS      a584 Midnight BSD ZFS
a585 Midnight BSD Vinum    a800 Apple UFS             a901 NetBSD swap
a902 NetBSD FFS            a903 NetBSD LFS            a904 NetBSD concatenated
a905 NetBSD encrypted      a906 NetBSD RAID           ab00 Apple boot
af00 Apple HFS/HFS+        af01 Apple RAID            af02 Apple RAID offline
af03 Apple label           af04 AppleTV recovery      af05 Apple Core Storage
be00 Solaris boot          bf00 Solaris root          bf01 Solaris /usr & Mac Z
bf02 Solaris swap          bf03 Solaris backup        bf04 Solaris /var
bf05 Solaris /home         bf06 Solaris alternate se  bf07 Solaris Reserved 1
bf08 Solaris Reserved 2    bf09 Solaris Reserved 3    bf0a Solaris Reserved 4
bf0b Solaris Reserved 5    c001 HP-UX data            c002 HP-UX service
ea00 Freedesktop $BOOT     eb00 Haiku BFS             ed00 Sony system partitio
ef00 EFI System            ef01 MBR partition scheme  ef02 BIOS boot partition
fb00 VMWare VMFS           fb01 VMWare reserved       fc00 VMWare kcore crash p
fd00 Linux RAID
----

Tatsächlich sind diese hier gezeigten Partitionstypen nur 'Abkürzungen' für die eigentlich verwendeten GUID's welche dem Partitionierungsschema den Namen gegeben haben.

Also:
`0700` steht für `Microsoft basic data` und für die GUID `EBD0A0A2-B9E5-4433-87C0-68B6B72699C7`

Eine Liste der GUID's findet sich z.B. bei Wikipedia:

https://de.wikipedia.org/wiki/GUID_Partition_Table#Partitionstyp-GUIDs

https://en.wikipedia.org/wiki/GUID_Partition_Table#Partition_type_GUIDs

Weiterhin kennt das Werkzeug gdisk (und sgdisk, ...) eine interne Ersetzungstabelle für unbekannte Partitionstypen. So gibt es für den 'alten' Partionstyp für vfat32 `0b` keine Entsprechung als `0b00`. Übergibt man aber trotzdem `0b00` als Typ an sgdisk so wird ohne jede Meldung hieraus `0700`. Dies passiert wohl nach der Überlegung: vfat32 - das wird schon eine Microsoft Daten Partition sein... 

GPT Partitionen kennen Attribute.

Liste der z.Zt. bekannten Attribute

|==========================
|Wert|Beschreibung|Attributwert (sgdisk --info / diskpart gpt attribute)
|nix|nix																						|0000000000000000
|0 	|Systempartition (system partition)             |0000000000000001
|1 	|Verstecke die Partition vor EFI (hide from EFI)|0000000000000002
|2 	|Legacy Bootflag (legacy BIOS bootable)         |0000000000000004
|60 |Nur lesen (read-only)                          |1000000000000000
|62 |Versteckt (hidden)                             |4000000000000000
|63 |Nicht Einhängen (do not automount)             |8000000000000000
|==========================

Die attribute werden unter Linux bei sgdisk über die Option `-A, --attributes` unter Verwendung der Kurzform  und unter Windows über diskpart mit dem Befehl `gpt attributes` unter Verwendung der Langform gesetzt.

Beispiele:
[source,prompt]
----
select disk 0
select partition 1
gpt attributes=0x0000000000000000
----

[source,prompt]
----
sgdisk -t 1:0700 --attributes 1:clear:63 --attributes 1:set:62 -p /dev/sda
----

Anzeigen der Partitionstabelle mit `-p , --print`:
[source,prompt]
----
sgdisk -p /dev/sda
----

Anzeigen der Detailinfos zu einer Partition (1) mit `--info=`:
[source,prompt]
----
sgdisk --info=1 /dev/sda
----

[[opsi-manual-uefi-roadmap]]
==== opsi UEFI/GPT Roadmap

* UEFI 32 Bit Unterstützung

* Andere netbootfähige UEFI Bootloader (grub2)

* Secureboot

