////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      05.12.2019
:Revision:  4.0.1
:toclevels: 6

include::../common/opsi_terms.asciidoc[]

[[opsi_manual_opsi-client-agent_webapi]]
=== opsi-client-agent web service

[[opsi_manual_opsi-client-agent_webapi_log_read]]
==== Logdateien auslesen

* `log_read` +
Liest eine auf dem Client vorhandene opsi-Logdatei. +
Parameter: `logType *extension *maxSize` +
Mögliche logType Werte sind 'opsiclientd', 'opsiclientdguard', 'opsi-client-agent', 'opsi-script', 'opsi_loginblocker', 'notifier_block_login' und 'notifier_event'. +
Mit dem Parameter 'extension' können rotierte Logdateien (log.1, log.2, _1.log, _2.log etc.) angezeigt werden. +
Mögliche Werte sind 0-9. +
Der Parameter 'maxSize' limit die Ausgabe auf den angegebenen Wert in Bytes. +

[[opsi_manual_opsi-client-agent_webapi_update_component]]
==== Eine opsi-client-agent-Komponente aktualisieren
* `updateComponent` +
Eine opsi-client-agent-Komponente aktualisieren. +
Parameter: `*component *url` +
Mögliche Werte für `component` sind: 'opsiclientd'. +
Das Update wird von der angegebenen `url` geladen (mögliche Protokolle sind hierbei: 'http', 'https' und 'file').
Das Update muss als Archiv (zip / tar / tar.gz / tar.bz2) bereitgestellt werden, das die Dateien der Komponente enthält.

Alternativ kann das Archiv auch über einen POST-Request auf `/upload/update/opsiclientd` hochgeladen werden. +
Beispiel:
[source,bash]
----
curl --insecure --request POST \
	--user ':<opsi-client-host-key>' \
	--header 'Content-Disposition: filename=oca.zip' \
	--data-binary '@path/to/opsiclientd_windows_x86_<version>.zip' \
	https://<client-address>:4441/upload/update/opsiclientd
----
