//// 
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; Until we found a better license:
; All rights reserved.
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      05.05.2011
:Revision:  4.0.01
:toclevels: 6

include::../common/opsi_terms.asciidoc[]


[[opsi-manual-ci]]
== Anpassen des opsi-client-agent an Corporate Identity (CI)

Die Anpassung des Erscheinungsbildes des '{opsi-client-agent}' kann insbesondere bei der Einführung erheblich zur Akzeptanz beizutragen und eine mögliche Verunsicherung der Anwender durch das Auftreten von bisher ungewohnten Fenstern zu vermeiden.

Der '{opsi-winst}' lässt sich über eine Manipulation der Grafik `bg.png` im Unterverzeichnis `winstskin` frei anpassen. Nach einer Veränderung der `bg.png` unter `/opt/pcbin/install/opsi-client-agent/files/opsi/opsi-winst/winstskin` setzen Sie mit dem Befehl 
[source,prompt]
----
touch /opt/pcbin/install/opsi-client-agent/files/opsi/opsi-winst/winst32.exe 
----
das Datum des '{opsi-winst}' neu. 
In der Folge wird beim nächsten Start des '{opsi-client-agent}' der '{opsi-winst}' mit der veränderten `bg.png` automatisch auf den Client geladen.

Weiterhin finden Sie im Verzeichnis
`/opt/pcbin/install/opsi-client-agent/files/opsi/dist/notifier`
 die Dateien `action.bmp` und `event.bmp` welche Sie auch an Ihre Bedürfnisse anpassen können. Diese Dateien werden bei einer Installation des '{opsi-client-agent}' übertragen.
 
Diese Dateien werden beim Einspielen von Updates des Produktes '{opsi-client-agent}' nicht überschrieben wenn Sie diese verändert haben.

Weiterhin können Sie die Orte, Farbe, Schrift an denen Text in diese Grafiken eingeblendet wird über die entsprechenden Ini-Dateien (`action.ini, event.ini, shutdown.ini`) ebenfalls anpassen. (CAUTION: Diese Dateien sind im Moment nicht gegen ein Update geschützt).

Die erforderlichen Anpassungen lassen sich auch in einem '{opsi-winst}'-script durchführen, welches als eigenes Produkt oder als 'Update'-Script in den '{opsi-client-agent}' eingebunden wird.

Hier ein Beispiel:
[source,winst]
----
[Actions]
requiredWinstVersion >= "4.10.8.0"
Message "opsi-client-agent update"
ShowBitmap "%scriptpath%\opsi.png" "opsi-client-agent"


DefVar $INST_BaseDir$
DefVar $INST_NotifierDir$
DefVar $INST_OpsiclientdDir$
DefVar $INST_OpsiclientdConf$
DefVar $INST_WinstDir$
DefVar $OLB_LoginBlockerStart$
DefVar $block_login$
DefVar $winst_skin_color$
DefVar $action_color$
DefVar $count_event_abort$
DefVar $warning_before_event_sec$

Set $INST_BaseDir$   = "%ProgramFilesDir%\opsi.org\opsi-client-agent"
Set $INST_OpsiclientdDir$   = $INST_BaseDir$+"\opsiclientd"
Set $INST_OpsiclientdConf$ = $INST_OpsiclientdDir$+"\opsiclientd.conf"
Set $INST_WinstDir$   = $INST_BaseDir$+"\opsi-winst"
Set $INST_NotifierDir$ = $INST_BaseDir$+"\notifier"
;set $winst_skin_color$ = "$00E7E7E7"
set $winst_skin_color$ = "$00202020"
set $action_color$ = "32,32,32"
;Set $OLB_LoginBlockerStart$          	    = GetProductProperty ("LoginBlockerStart","off")
set $count_event_abort$ = "2"
set $warning_before_event_sec$ = "20"

;if $OLB_LoginBlockerStart$ = "on"
;	set $block_login$ = "true"
;else
	set $block_login$ = "false"
;endif

;	if FileExists("%ScriptPath%\custom.ins")
;		comment "Start uninstall sub section"
;		Sub "%ScriptPath%\custom.ins"
;	endif

Files_copy_images
Patches_action_ini $INST_NotifierDir$+"\action.ini"
Patches_event_ini $INST_NotifierDir$+"\event.ini"
Patches_shutdown_ini $INST_NotifierDir$+"\shutdown.ini"
Patches_winst_skin $INST_WinstDir$+"\winstskin\skin.ini"
Patches_opsiclientd_conf $INST_OpsiclientdConf$
 
[Files_copy_images]
copy "%SCRIPTPATH%\notifier\*.*" "$INST_NotifierDir$"
copy "%SCRIPTPATH%\winstskin\*.*" "$INST_WinstDir$\winstskin"

[Patches_action_ini]
set [Form] Hidden = false
delsec [ProgressBarCurrentProgress]
delsec [ProgressBarOverallProgress]
set [LabelTitle] FontColor = $action_color$
set [LabelOpsiclientdInfo] FontColor = $action_color$
set [LabelActionProcessorInfo] FontColor = $action_color$
set [LabelStatus] FontColor = $action_color$
set [LabelDetail] FontColor = $action_color$
set [LabelConfigServiceUrl] FontColor = $action_color$
set [LabelClientId] FontColor = $action_color$

[Patches_event_ini]
set [LabelMessage] FontSize = 12
set [LabelMessage] FontBold = true
set [LabelMessage] Top = 95
set [LabelMessage] FontBold = true
set [LabelStatus] Left = 25
set [LabelStatus] Top = 55

[Patches_shutdown_ini]
set [LabelMessage] FontSize = 12
set [LabelMessage] FontBold = true
set [LabelMessage] Top = 95
set [LabelMessage] FontBold = true
set [LabelMessage] Left = 25
set [LabelMessage] Top = 55

[Patches_opsiclientd_conf]
set [event_gui_startup] message[de] = Darf jetzt Software / Updates installiert werden ?  Sie können diese Aktion insgesamt %user_cancelable% mal abbrechen. Die Aktion wurde bereits %cancel_counter% mal abgebrochen.
set [event_gui_startup] action_notifier_desktop = winlogon
set [event_gui_startup] action_processor_desktop = winlogon
set [event_gui_startup] user_cancelable = $count_event_abort$
set [event_gui_startup] block_login = $block_login$
set [event_gui_startup] warning_time = $warning_before_event_sec$
set [event_gui_startup] shutdown_user_cancelable = 2
set [event_gui_startup] shutdown_warning_message[de] = Ein Neustart wird benötigt um die Software-Installationen abzuschliessen. Sie können diesen Neustart insgesamt %shutdown_user_cancelable% mal verschieben. Der Neustart wurde bereits %shutdown_cancel_counter% mal verschoben.
set [event_gui_startup] shutdown_warning_repetition_time = 3600
set [event_gui_startup] shutdown_warning_time = 300
set [event_gui_startup] shutdown_notifier_command = %opsiclientd_notifier.command% -s notifier\\shutdown.ini
set [event_gui_startup] shutdown_notifier_desktop = current


[Patches_winst_skin]
set [LabelVersion] FontColor = $winst_skin_color$
set [LabelProduct] FontColor = $winst_skin_color$
set [LabelProduct] FontSize = 22
set [LabelInfo] FontColor = $winst_skin_color$
set [LabelDetail] FontColor = $winst_skin_color$
set [LabelCommand] FontColor = $winst_skin_color$
set [LabelProgress] FontColor = $winst_skin_color$
set [ProgressBar] BarColor = $winst_skin_color$
set [ProgressBar] StartColor = $winst_skin_color$
set [ProgressBar] FinalColor = $winst_skin_color$
set [ProgressBar] ShapeColor = $winst_skin_color$
;set [Form] Color = $00FFB359
set [Form] Color = $00E7E7E7
----
