////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      27.01.2014
:Revision:  4.0.4
:toclevels: 6


include::../common/opsi_terms.asciidoc[]

[[opsi-manual-uefi]]
== opsi mit UEFI / GPT


[[opsi-manual-uefi-preconditions]]
=== Vorbedingungen für das Arbeiten mit UEFI / GPT

Dieses Modul ist momentan eine
http://www.uib.de/www/kofinanziert/index.html[kofinanzierte opsi Erweiterung]. +
Es sind eine Reihe von Vorbedingungen nötig, um dieses Modul einsetzen
zu können. Das bedeutet, das Sie zum Einsatz eine Freischaltdatei benötigen. Diese Freischaltung erhalten Sie wenn Sie die Erweiterung kaufen. Zu Evaluierungszwecken stellen wir Ihnen auch eine zeitlich befristete Freischaltung kostenlos zur Verfügung ( -> mail an info@uib.de). +
Weitere Details hierzu finden Sie in <<opsi-manual-modules>>.

Technische Voraussetzungen sind opsi 4.0.5 mit den Paketständen:

.Benötigte Pakete
[options="header"]
|==========================
|opsi-Paket|Version
|Netbootprodukte|>=4.0.5
|opsi Server Pakete|>=4.0.5
|==========================


[[opsi-manual-uefi-introduction]]
=== Einführung

Neue PC's, Tablets und Server enthalten meist ein UEFI BIOS. Häufig kann dieses in einen Legacy Mode umgestellt werden, um das bisherige Verhalten und die Unterstützung eines PXE Boots zu bekommen. Es tauchen aber auch zunehmend Geräte mit UEFI-only BIOS auf (besonders bei den Tablets). Diese lassen sich in einer bisherigen opsi Umgebung nicht per netboot verwalten.

Um auch diese Geräte in opsi integrieren bzw. die Vorteile von UEFI nutzen zu können, entwickelt die uib gmbh die opsi Erweiterung UEFI Support.

[[opsi-manual-uefi-whatisuefi]]
=== Was ist Uefi und was ist hier anders ?

UEFI steht für 'Unified Extensible Firmware Interface' und ist der Nachfolger des klassischen PC-BIOS (auch MBR-BIOS genannt).

Für Detailierte Informationen zum Thema UEFI finden sich Unten einige Links.

UEFI ist ungleich mächtiger als das herkömmliche BIOS. Im Prinzip ist UEFI ein eigenes kleines Mini-Betriebssystem. Hier sollen aber nur Punkte erwähnt werden, welche für den Systemverwalter von besonderer Bedeutung sind:

* Die derzeitige (Stand Januar 2014) Umsetzung von UEFI in den BIOSen der Hardware Hersteller ist weit von dem Entfernt was man einen Standard nennen könnte. Vielmehr herrscht ein großes durcheinander wenn von einem anderen Medium geboot werden soll wie der Festplatte. UEFI und klassisches BIOS existieren teilweise Parallel, lassen sich mal einzeln deaktivieren mal nicht. UEFI ist mal mit Compatibility Support Module (CSM) implementiert mal ohne. Netboot geht oder auch nicht. +
Gerade der letzte Punkt (Netboot) ist natürlich für ein strukturiertes Client Management von großer Bedeutung.

* Im PC-BIOS ist das BIOS und dessen Einstellungen vom OS (in aller Regel) getrennt. D.h. BIOS Einstellungen wie z.B. die Bootreihenfolge sind statisch und können vom Betriebssystem nicht geändert werden. +
Dies ist bei UEFI anders. Das Betriebssystem kann die Bootreihenfolge ändern (und macht davon in der Regel auch Gebrauch). Auch dies hat wiederum Auswirkungen auf die Anbindung der Rechner an das Clientmanagement durch den Netboot. 

* Das UEFI BIOS ist in 32 oder 64 Bit implementiert. Damit ist dann auch die 'Bitigkeit' des Betriebssystems vorgegeben. D.h. kein 32 Bit OS auf einem 64 Bit UEFI System.

* Secureboot (von opsi noch nicht unterstützt)

* Partitionierung mit GPT und zusätzliche Partitionen für die Bootloader:

** 1. Partition: EFI System Partition (ESP) 100 - 260 MByte ; VFAT
** 2. Partition: Microsoft Reserved (MSR) 32 - 128 MB; NTFS
** Ab hier kommen jetzt die eigentlichen OS Partitionen



Links : 

http://de.wikipedia.org/wiki/Unified_Extensible_Firmware_Interface

[[opsi-manual-uefi-whatisgpt]]
=== Was ist anders an GPT

GPT (GUID Partition Table) ersetzen die bisherigen MBR Partitionstabellen. GPT ist Bestandteil der UEFI Spezifikation. 

Wesentliche Merkmale für den Sysadmin sind:

* Wegfall der 2 Terabyte Grenze (jetzt 8 Zebibyte)

* 'Beliebig' viele primäre Partitionen

* Geänderte Partitionstypen

* Neu: Partitions-GUIDs

* Neu: Partitions-Attribute (Hidden, Read only, ...)

* Andere Werkzeuge zur Bearbeitung: gdisk

Prinzipiell lässt sich GPT auch ohne UEFI verwenden. UEFI funktioniert aber nur mit GPT. Wird UEFI verwendet, 
so kommen ein bis zwei zusätzliche Partitionen hinzu:

. Die EFI System Partition (ESP) - hier liegen die Bootloader

. MS Reserved (MSR)

Links : 

http://de.wikipedia.org/wiki/GUID_Partition_Table

[[opsi-manual-uefi-uefiboot]]
=== UEFI Boot

Im Gegensatz zu herkömmlichen BIOSen kann hier die Bootreihenfolge nicht nur für Geräte, sondern auch für unterschiedliche Bootloader auf der EFI System Partition eingetragen werden. Darüberhinaus ist diese Reihenfolge auch von einem laufenden Betriebssystem manipulierbar. Wenn Sie also den Netboot als oberste Priorität festlegen, so wird dies die erste OS-Installation nicht überleben.

[[opsi-manual-uefi-uefinetboot]]
=== UEFI Netboot

Leider unterstützen viele frühe UEFI BIOSe noch kein Netboot, aber die Unterstützung wird zunehmend besser. 

Es gibt inzwischen schon eine ganze Reihe von UEFI Bootloadern (wie z.B. grub2, elilo), leider unterstützen die wenigsten davon einen Netboot. 

Die uib gmbh stellt mit der opsi-Erweiterung UEFI Support eine funktionierende Unterstützung für die Anbindung eines Clients über einen UEFI-Netboot an opsi vor. Gleichzeitig erwarten wir, dass im Rahmen der technischen Weiterentwicklung diese opsi-Erweiterung in den nächsten Jahren noch deutlich umgebaut werden wird.

[[opsi-manual-uefi-opsiuefinetboot]]
=== Opsi Unterstützung für UEFI Netboot

Die opsi Unterstützung für UEFI ist im Rahmen einer Reihe von Teilkomponenten umgesetzt:

* Anpassung des netbootfähigen UEFI Bootloaders ELILO an die opsi / Client-Management Bedürfnisse.

* Neuer opsipxeconfd, welcher neben Konfigurationsdateien für das bisherige PXE nun auch Konfigurations­dateien für den opsi-ELILO bereitstellt.

* Bereitstellung neuer (64Bit) opsi-linux-bootimages mit den Werkzeugen für UEFI- und GPT-Management

* Umbau aller Netbootprodukte zur Betriebssysteminstallation auf die zusätzliche Unterstützung von UEFI/GPT

[[opsi-manual-uefi-install]]
=== Installation

Alle notwendigen Pakete sind ab der opsi Version 4.0.5 automatisch installiert.


[[opsi-manual-uefi-dhcpd]]
=== Konfiguration des DHCP Servers

Beispiel aus einer Konfiguration eines Linux isc-dhcp-server:

----
filename "linux/pxelinux.0";

# Das ist die UEFI Detection:
if substring (option vendor-class-identifier , 19,1 ) = "0" {
        log (info, "pxe client");
        filename "linux/pxelinux.0";
}
else if substring (option vendor-class-identifier , 19,1 ) = "6" {
        log (info, "efi32 client");
        filename "linux/pxelinux.cfg/elilo32.efi";
}
else if substring (option vendor-class-identifier , 19,1 ) = "7" {
        log (info, "efi64 client");
        filename "linux/pxelinux.cfg/elilo.efi";
}
else {
        log (info, concat ( "Unhandled vendor class Arch: ", substring (option vendor-class-identifier , 19,1 )));
}
----

http://docs.fedoraproject.org/en-US/Fedora/17/html/Installation_Guide/s1-netboot-pxe-config.html

[[opsi-manual-uefi-goodbios]]
=== Kriterien für ein 'gutes' BIOS

Ob ein UEFI BIOS für die Anforderungen eines Client-Management-Systems wie opsi geeignet ist, hängt von verschiedenen Kriterien ab. Diese Kriterien sagen nichts  über die Qualität des Gerätes als solches aus, sondern nur über seine Wartbarkeit per Netboot-Anbindung. Es geht hier also um die BIOS-Funktionen zum UEFI Netboot. Hier ein beispielhafter Vergleich :

.Beispiele für UEFI BIOS Unterschiede
[options="header"]
|==========================
||Lenovo Twist|MS-Surface
|UEFI pur|√||√
|UEFI + CSM|√|x
|Legacy|√|x
|Both|√|x
|UEFI Netboot|√|√
|Aktivierbarer Eintrag|√|x
|Netboot ohne Interaktion|√|x
|==========================

Unter 'Aktivierbarer Eintrag' verstehen wir, das sich per Standard-Software ein Netboot für den nächsten Reboot aktivieren läßt. 'Netboot ohne Interaktion' bedeutet, dass ein aktivierter Netboot-Eintrag beim Reboot ausgeführt wird und dazu keine Interaktion (drücken von Tastenkombinationen, F12-Taste, ...) nötig sind.
Netboot Produkte mit UEFI/GPT Support
Alle opsi Netboot Produkte sind für die Verwendung mit UEFI/GPT erweitert worden. Konkret wird automatisch erkannt, ob das opsi-linux-bootimage im UEFI Mode läuft oder nicht. Je nachdem wird dann automatisch das Partitionierungs­schema und die Installationsart angepasst.
Roadmap
UEFI 32 Bit Unterstützung
Andere netbootfähige UEFI Bootloader (grub2)
Secureboot




