////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////


:Author:    uib gmbh
:Email:     info@uib.de
:Date:      04.07.2011
:Revision:  4.0.1
:toclevels: 6

include::../common/opsi_terms.asciidoc[]


[[opsi-manual-registryentries]]
== Registryeinträge 

[[opsi-manual-registryentries-opsiclientd]]
=== Registryeinträge des opsiclientd

[[opsi-manual-registryentries-opsiclientd-general]]
==== opsi.org/general
* `bootmode= <bkstd | reins>` +
Beschreibt ob der Rechner gerade aus einer Reinstallation kommt.

[[opsi-manual-registryentries-opsiclientd-preloginloader]]
==== opsi.org/opsi-client-agent und opsi.org/preloginloader
Schlüssel [HKEY_LOCAL_MACHINE\SOFTWARE\opsi.org\opsi-client-agent]
Schlüssel [HKEY_LOCAL_MACHINE\SOFTWARE\opsi.org\preloginloader]

Diese beiden Keys sind identisch, wobei der zweite (preloginloader) abgekündigt ist und nur der Rückwärtskompatibilität dient.

* `"RemoveMsginaOnDeinst"=dword:00000001`
		- bei Reinstallation msgina deinstallieren
* `"WinstRegKey"="SOFTWARE\\opsi.org\\winst"`
		- hier wird geschaut, ob der '{opsi-winst}' rebooten möchte
* `"LoginBlockerStart"=dword:00000001`
		- opsigina wartet auf READY aus der Named Pipe
* `"LoginBlockerTimeoutConnect"=dword:00000005`
		- Timeout in Minuten für ein Pipe-Connect zum opsi-client-agent
		- nur wenn LoginBlockerStart auf 1 steht
* `"LoginBlockerLogLevel"=reg_dword:006`
		- Loglevel des Loginblockers
* `"OpsiServiceType"=dword:00000002`
		- Soll sich die opsigina mit dem prelogin (1) oder opsiclientd (2) unterhalten
* `"NextGina"="msgina.dll"`
		- die nächste gechainte gina.dll
		
[[opsi-manual-registryentries-opsiclientd-shareinfo]]		
==== opsi.org/shareinfo
* `depoturl` +
 <Url die zu den Softwarepaketen verweist. Muster: protokoll:\\server\share\dir>
+
Beispiel: + 
'smb:\\schleppi\opsi_depot'

* `depotdrive` +
 <Laufwerksbuchstaben auf den depoturl gemountet wird>
+
Beispiel: `P:` (mit Doppelpunkt)

[[opsi-manual-registryentries-winst]]
=== Registryeinträge des {opsi-winst}

[[opsi-manual-registryentries-winst-winst]]
==== opsi.org/winst
Diese Registry Einträge werden vom Winst selbst verwaltet und sollten nicht verändert werden.
[source,ini]
----
"LastLogFilename"="C:\\TMP\\syslogin.log"
"ContinueLogFile"=dword:00000000
"RebootRequested"=dword:00000000
"SendLogToService"=dword:00000001
"NumberOfErrors"=dword:00000000
"ShutdownRequested"=dword:00000000
----

[[opsi-manual-registryentries-winst-syslog]]
==== Steuerung des Logging per syslog-Protokoll

Schlüssel HKLM\Software\opsi.org\syslogd

DWord-Variable remoteerrorlogging wird nach folgendem Schema ausgewertet: +
RemoteErrorLogging = (trel_none, trel_filesystem, trel_syslog); +
// in registry values 0, 1, 2

Falls das Logging mittels dem syslog-Protokoll erfolgt ("remoteerrorlogging"=dword:00000002), so gibt die String-Variable sysloghost den IP-Namen des LogHost an.
DWORD-Variable syslogfacility gibt an, was als Quelle der syslog-Nachricht übergeben wird. Der default ist  ID_SYSLOG_FACILITY_LOCAL0
Bedeutungen:
[source,ini]
----
  ID_SYSLOG_FACILITY_KERNEL     = 0;  // kernel messages
  ID_SYSLOG_FACILITY_USER       = 1;  // user-level messages
  ID_SYSLOG_FACILITY_MAIL       = 2;  // mail system
  ID_SYSLOG_FACILITY_SYS_DAEMON = 3;  // system daemons
  ID_SYSLOG_FACILITY_SECURITY1  = 4;  // security/authorization messages (1)
  ID_SYSLOG_FACILITY_INTERNAL   = 5;  // messages generated internally by syslogd
  ID_SYSLOG_FACILITY_LPR        = 6;  // line printer subsystem
  ID_SYSLOG_FACILITY_NNTP       = 7;  // network news subsystem
  ID_SYSLOG_FACILITY_UUCP       = 8;  // UUCP subsystem
  ID_SYSLOG_FACILITY_CLOCK1     = 9;  // clock daemon (1)
  ID_SYSLOG_FACILITY_SECURITY2  = 10; // security/authorization messages (2)
  ID_SYSLOG_FACILITY_FTP        = 11; // FTP daemon
  ID_SYSLOG_FACILITY_NTP        = 12; // NTP subsystem
  ID_SYSLOG_FACILITY_AUDIT      = 13; // log audit
  ID_SYSLOG_FACILITY_ALERT      = 14; // log alert
  ID_SYSLOG_FACILITY_CLOCK2     = 15; // clock daemon (2)
  ID_SYSLOG_FACILITY_LOCAL0     = 16; // local use 0  (local0)
  ID_SYSLOG_FACILITY_LOCAL1     = 17; // local use 1  (local1)
  ID_SYSLOG_FACILITY_LOCAL2     = 18; // local use 2  (local2)
  ID_SYSLOG_FACILITY_LOCAL3     = 19; // local use 3  (local3)
  ID_SYSLOG_FACILITY_LOCAL4     = 20; // local use 4  (local4)
  ID_SYSLOG_FACILITY_LOCAL5     = 21; // local use 5  (local5)
  ID_SYSLOG_FACILITY_LOCAL6     = 22; // local use 6  (local6)
  ID_SYSLOG_FACILITY_LOCAL7     = 23; // local use 7  (local7)
----
