////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////
:Author:    uib gmbh
:Email:     info@uib.de
:Date:      10.04.2014
:Revision:  4.0.4
:toclevels: 6
:doctype:   book

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]

[[opsi-manual-abo-products-introduction]]
== opsi Abo Produkte

[[opsi-manual-abo-products-introduction-firststeps]]
=== Initiale Bereitstellung von Paketen aus dem Abobereich

Zur Bereitstellung der benötigten Pakete können Sie diese manuell herunterladen oder aber alle Pakete nach Anpassung der '/etc/opsi/opsi-product-updater.conf' mittels `opsi-product-updater -ivv` in einem Rutsch installieren.


[[opsi-manual-abo-products-introduction-second]]
=== Festlegung von Default-Properties

Bei der nichtinteraktiven Installation von opsi-Paketen werden auf einem '{opsi-configserver}' bzw. einem '{opsi-Server}' die Paket default-Properties als default festgelegt.

Falls Sie hiervon abweichende default Properties festlegen wollen so installieren Sie die Pakete einmalig mittels `opsi-package-manager -p ask -i <paketname>.opsi`

Bei einer anschliessenden Installation einer neueren Paketversion mittels  `opsi-package-manager` oder `opsi-product-updater` bleiben die eingestellten depot default Properties erhalten.

[[opsi-manual-abo-products-introduction-third]]
=== Aktualisierung der Abo-Pakete / Konfiguration des `opsi-product-updater` 

Für die Aktualisierung der Pakete wird der `opsi-product-updater` empfohlen.

Editieren Sie hierzu die Datei  '/etc/opsi/opsi-product-updater.conf' und tragen Sie in der Sektion 
 
[source,configfile]
----
[repository_uib]
----

die Werte ein für 'username' bwz. 'password' und ergänzen Sie den Eintrag 'dirs = '  


[source,configfile]
----
dirs =  opsi4.0/products/localboot, opsi4.0/products/netboot, < abo-package--url >
----

Mittels dem Aufruf `opsi-product-updater -vv` können dann z.B. per Cronjob die installierten Pakete aktualisiert werden.

[[opsi-manual-abo-products-mshotfix]]
=== Update-Abo 'MS-Hotfixes'
Regelmäßige Updates des Produktes mshotfix (Hotfixes für Windows XP Professional bis 2008-R2).

Das Update erscheint jeweils innerhalb von 3 Arbeitstagen nach dem Erscheinen eines von Microsoft als wichtig oder kritisch eingeschätzten Patches.

http://technet.microsoft.com/de-de/security/gg309177.aspx


http://technet.microsoft.com/en-us/security/gg309177.aspx
[source,prompt]
----

Bewertung	Beschreibung
Kritisch	

Eine Schwachstelle, deren Ausnutzung ohne Eingreifen des Benutzers Codeausführung ermöglichen kann. Dies umfasst Szenarien wie sich selbst verbreitende Malware (z. B. Würmer) oder nicht zu vermeidende gebräuchliche Anwendungsszenarien, in denen Codeausführung ohne Warnungen oder Eingabeaufforderungen erfolgt. Dies könnte das Abrufen einer Webseite oder das Öffnen einer E-Mail bedeuten.

Microsoft empfiehlt, dass Kunden kritische Updates unverzüglich installieren.
Hoch	

Eine Schwachstelle, deren Ausnutzung die Vertraulichkeit, Integrität oder Verfügbarkeit von Benutzerdaten oder anderen Ressourcen gefährden kann. Dies umfasst gebräuchliche Anwendungsszenarien, in denen der Kunde durch Warnungen oder Eingabeaufforderungen unabhängig von deren Herkunft, Qualität oder Nutzbarkeit geschädigt wird. Abfolgen von Nutzerhandlungen, die keine Eingabeaufforderungen oder Warnungen hervorrufen, sind ebenfalls abgedeckt.

Microsoft empfiehlt, dass Kunden Updates mit hohem Risiko so frühzeitig wie möglich installieren.
Mittel	

Die Auswirkungen der Schwachstelle sind durch Faktoren wie Authentifizierungsanforderungen oder die Anwendbarkeit nur auf Nicht-Standardkonfigurationen erheblich eingeschränkt.

Microsoft empfiehlt, dass Kunden die Anwendung des Sicherheitsupdates in Erwägung zieht.
Niedrig	Die Auswirkungen der Schwachstelle sind aufgrund von Eigenschaften der betroffenen Komponente umfassend eingeschränkt. Microsoft empfiehlt, dass Kunden erwägen, ob sie das Sicherheitsupdate auf die betroffenen Systeme anwenden.

Rating	Definition
Critical	

A vulnerability whose exploitation could allow code execution without user interaction. These scenarios include self-propagating malware (e.g. network worms), or unavoidable common use scenarios where code execution occurs without warnings or prompts. This could mean browsing to a web page or opening email.

Microsoft recommends that customers apply Critical updates immediately.
Important	

A vulnerability whose exploitation could result in compromise of the confidentiality, integrity, or availability of user data, or of the integrity or availability of processing resources. These scenarios include common use scenarios where client is compromised with warnings or prompts regardless of the prompt's provenance, quality, or usability. Sequences of user actions that do not generate prompts or warnings are also covered.

Microsoft recommends that customers apply Important updates at the earliest opportunity.
Moderate	

Impact of the vulnerability is mitigated to a significant degree by factors such as authentication requirements or applicability only to non-default configurations.

Microsoft recommends that customers consider applying the security update.
Low	Impact of the vulnerability is comprehensively mitigated by the characteristics of the affected component. Microsoft recommends that customers evaluate whether to apply the security update to the affected systems.

----

Das opsi-mshotfix Paket verwendet (wie WSUS Offline Update http://forums.wsusoffline.net/viewtopic.php?f=7&t=172 Abdeckung des / Coverage of WSUS Offline Update ) für den Download Microsoft's Update-Katalogdatei wsusscn2.cab, um die erforderlichen Patches zu ermitteln. 
Diese Katalogdatei enthält mindestens alle als „kritisch“ und „sicherheitsrelevant“ eingestuften Updates, aber nicht notwendigerweise alle „wichtigen“ und „optionalen“.

Die opsi mshotfix-Pakete sind modular aufgebaut.
Das Basis-Paket „mshotfix“ beinhaltet nur ein Skript zum Installieren der Patches. Die eigentlichen Patches sind gesondert in separaten Paketen enthalten 

.mshotfix Client-Betriebssystem Voraussetzung
|===================================
|OS|
|Windows XP|Service Pack 3
|Windows 2003 / Windows XP 64bit|Service Pack 2
|Windows Vista / Windows 2008 |Service Pack 2
|Windows 7 / Windows 2008 R2|Servicepack 1
|Windows 8 / Windows 2012|
|Windows 8.1 / Windows 2012 R2|
|====================================

CAUTION: Die Pakete für Windows 8  / Window 2012 in Zusammenhang mit dem Wan/VPN Modul benötigen opsi-client-agent >= opsi-client-agent_4.0.4.4-1.opsi

CAUTION: Die Paket für Windows 8 / 8.1 / Windows 2012 / 2012 R2 benötigen opsi-winst >= opsi-winst_4.11.3.11-1.opsi und opsi-client-agent >= opsi-client-agent_4.0.4.4-1.opsi

Auf unserem Download-Server ist die Struktur des Abo verzeichnisses


[source,configfile]
----
mshotfix
  !-opsi4/
     !-glb/	Basis-Paket mshotfix sowie globale Patchpakete 
     		mshotfix-vista-win2008-x86-glb, 
     		mshotfix-vista-win2008-x64-glb , 
     		mshotfix-win7-x86-glb, 
     		mshotfix-win7-win2008r2-x64-glb
     		mshotfix-win8-x86-glb
     		mshotfix-win81-x86-glb
     		mshotfix-win8-win2012-x64-glb
     		mshotfix-win81-win2012r2-x64-glb
     !-deu/	Sprachspezifische Patch-Pakete 
     		mshotfix-winxp-x86-deu , 
     		mshotfix-win2003-x86-deu
     !-enu/	
     !-fra/
     !-ita/
----

Nur für  winxp und win2003 gibt es zusätzlich sprachspezifische Patches, die heruntergeladen werden müssen.

Folgende Tabelle soll bei der Auswahl der richtigen Pakete helfen:

.mshotfix Client-Betriebssystem
|=======================
|OS|Arch. Sprache|Patch-Paket
|Windows XP SP3 |  32Bit Deutsch | mshotfix-winxp-x86-deu
|Windows XP SP2 | 64Bit Englisch | mshotfix-win2003-winxp-x64-enu
|Windows 2003 SP2 | 32Bit Deutsch | mshotfix-win2003-x86-deu
|Windows 2003 SP2 | 64Bit Englisch | mshotfix-win2003-winxp-x64-enu
|Windows Vista SP2 | 32Bit | mshotfix-vista-win2008-x86-glb
|Windows Vista SP2 | 64Bit | mshotfix-vista-x64-glb
|Windows 7 | 32Bit | mshotfix-win7-x86-glb
|Windows 7 | 64Bit | mshotfix-win7-win2008r2-x64-glb
|Windows 8 | 32Bit | mshotfix-win8-x86-glb
|Windows 8 | 64Bit | mshotfix-win8-win2012-x64-glb
|Windows 8.1 | 32Bit | mshotfix-win81-x86-glb
|Windows 8.1 | 64Bit | mshotfix-win81-win2012r2-x64-glb
|Windows 2008 Server | 32Bit | mshotfix-vista-win2008-x86-glb
|Windows 2008 Server | 64Bit | mshotfix-vista-win2008-x64-glb
|Windows 2008 Server R2 | 64Bit | mshotfix-win7-win2008r2-x64-glb
|Windows 2012 | 64Bit | mshotfix-win8-win2012-x64-glb
|Windows 2012 R2 | 64Bit | mshotfix-win81-win2012r2-x64-glb
|=======================

Installation:
opsi-package-manager -i mshotfix_201008-1.opsi
zum Scharfschalten (überall auf setup stellen, wo das Produkt auf installed steht):
opsi-package-manager -iS mshotfix_201008-1.opsi

Zusätzlich zum Basis-Paket werden die Patch-Pakete auf die gleiche Weise installiert. Da diese Pakete aber keine Installationsskripte enthalten, sind sie nur zusammen mit dem Basis-Paket einzuspielen, d.h.  man kann diese nicht separat auf setup stellen.  
Für die Client-Installation ist komplett das mshotfix-Basispaket zuständig.

Seit Paket  mshotfix 201304-1 werden sich durch mshotfix installiertePatches in der Datei

`C:\opsi.org\mshotfix\deployed.txt`

lokal gemerkt.

noreboot:: noreboot=on: Don't Reboot.  Warning will be logged if a reboot     is required.  Should be "on" for Server.
values: ["off", "on"]
default: ["off"]


force:: force=on: All Hotfixes will be installed forced
values: ["off", "on"]
default: ["off"]

excludes::  Commaseperated list with kb-numbers, that will be excluded (Only Number without beginning kb and no spaces. Example: 123456,789011,2222)
 Browser Choice update (KB976002)

severity:: choose the severity that will be installed. Possible Entries are Critical, Important, Moderate, all
values: ["Critical", "Important", "Moderate", "all"]
default: ["Critical", "Important"]


=== Update-Abo 'MS-Office Hotfixes'
Regelmäßige Updates für MS-Office 2003 und 2007 deutsch sowie MS-Office 2010 32 Bit

Das Update erscheint jeweils innerhalb von 3 Arbeitstagen nach dem Erscheinen eines von Microsoft als wichtig oder kritisch eingeschätzten Patches.

.Office hotfix  Voraussetzung
|===================================
|Office Version| required 
|Office 2003|Service Pack 3 | 
|Office 2007|Service Pack 3
|Office 2010 32-bit|Service Pack 1
|Office 2013 32-bit|
|====================================



[[opsi-manual-abo-products-office_2003_hotfix]]

==== Updates für MS Office 2003 deutsch : office_2003_hotfix
----
office_2003_hotfix               201312-1                  Microsoft Office 2003 Hotfixes
----

Monatliche Office 2003 Hotfixes. Setzt Servicepack 3 voraus.

Wird getestet gegen Office 2003 Professional und Standard.

[[opsi-manual-abo-products-office_2007_hotfix]]

==== Updates für MS Office 2007 deutsch : office_2007_hotfix
----
office_2007_hotfix               201312-1                  Microsoft Office 2007 Hotfixes
----

Monatliche Office 2007 Hotfixes. Setzt Servicepack 3 voraus.

Wird getestet gegen Office 2007 Enterprise.

Seit Paket office_2007_hotfix 201310-1 werden sich durch office_2007_hotfix installierte Patches in der Datei

`C:\opsi.org\mshotfix\office_2007_hotfix_deployed.txt`

lokal gemerkt.


[[opsi-manual-abo-products-office_2010_hotfix]]

==== Updates für MS Office 2010 32-bit international: office_2010_hotfix
----
office_2010_hotfix               201312-1                  Microsoft Office 2010 Hotfixes
----

Enthält sprachunabhängige monatliche Office 2010 Hotfixes (inclusive Visio und Project 2010) . Setzt Servicepack 1 voraus.

Wird getestet gegen Office 2010 Professional und Standard.

Seit Paket office_2010_hotfix 201305-2 werden sich durch office_2010_hotfix installierte Patches in der Datei

`C:\opsi.org\mshotfix\office_2010_hotfix_deployed.txt`

lokal gemerkt.

[[opsi-manual-abo-products-office_2013_hotfix]]

==== Updates für MS Office 2013 32-bit international: office_2013_hotfix
----
office_2013_hotfix               201401-1                  Microsoft Office 2013 Hotfixes
----

Enthält sprachunabhängige monatliche Office 2013 Hotfixes (inclusive Visio 2013) .

Wird getestet gegen Office 2013 Professional

Durch office_2013_hotfix installierte Patches in der Datei

`C:\opsi.org\mshotfix\office_2013_hotfix_deployed.txt`

lokal gemerkt.

[[opsi-manual-abo-products-standard]]
=== Update-Abo 'opsi Standardprodukte'
Regelmäßige Updates der Produkte:

    Adobe Acrobat Reader (deutsch, englisch und französisch / 32 Bit)
    Adobe Flashplayer (international / 32 Bit / 64 Bit)
    Apache OpenOffice.org (deutsch / 32 Bit)
    Google Chromium for business ( international 32 Bit )
    LibreOffice (international / 32 Bit)
    Mozilla Firefox (deutsch, englisch, französisch und niederländisch. / 32 Bit)
    Mozilla Thunderbird (deutsch, englisch und französisch / 32 Bit)
    Oracle Java VM (international / 32 Bit / 64 Bit)
    
    Je nach Vertrag stellen wir noch folgende Sprachen im Abo zur Verfügung:
    
        Adobe Acrobat Reader (zusätzlich italienisch und niederländisch / 32 Bit)
        Adobe Acrobat Reader XI (zusätzlich dänisch, italienisch, niederländisch und spanisch / 32 Bit)
        Mozilla Firefox (zusätzlich dänisch, italienisch oder spanisch / 32 Bit)
        Mozilla Thunderbird (zusätzlich italienisch / 32 Bit)
        
     weitere Sprachen auf Anfrage.
    
    

Das Update erscheint jeweils innerhalb von 2 Arbeitswochen nach dem Erscheinen eines Updates dieser Produkte; bei vom Hersteller als kritisch eingestuften Security-Updates innerhalb von 1 Arbeitswoche.

==== Customizing der Pakete durch zentrale Konfigurationen

Für die Pakete
----
acroread
acroread11
firefox
javavm
thunderbird
----

gibt es die Möglichkeit eigene Konfigurationen zu erstellen und im Verzeichnis `custom` zu hinterlegen,
die über Properties auswählbar sind. (Näheres siehe unten)

==== Customizing der Pakete durch preinst/postinst-scripts

Für die Pakete
----
acroread11 	(ab 11.0.3-1)
firefox		(ab 17.0.6esrorstandard-1)
flashplayer	(ab 13.0.0.182or11.7.700.275-1)
google-chrome-for-business
javavm		(ab javavm_1.7.0.51-5 )
thunderbird	(ab 17.0.6esrorstandard-1)
----

besteht die Möglichkeit eigene custom-Scripte einzubauen im Verzeichnis `custom\scripts`

Einfache Templates für die unterstützen Scripte finden sich im Verzeichnis `opsi\scripts`

[source,configfile]
----

custom.actions.post.setup
custom.actions.post.uninstall
custom.actions.pre.setup
custom.actions.pre.uninstall
custom.declarations
custom.sections

custom scripts will be included at
- setup-script 
- uninstall-script

custom pre-scripts will be included in
- setup-script 
- uninstall-script

custom post-scripts will be included in
- in setup-script
- uninstall-script

custom.declarations
; intended for declaration of custom Variables and Stringlist Variables
; will be included with "include_insert" at top of [actions] 
; but after GetProductProperties

custom.sections
; intended for declaration of custom secondary sections
; will be included with "include_append" at top of [actions]
; but after GetProductProperties

custom.actions.pre.setup  (or custom.actions.pre.uninstall)
; will be included with "include_insert" at at top of [actions]
; (but after GetProductProperties)

custom.actions.post.setup (or custom.actions.post.uninstall)
; will be included with "include_insert" in case of successfull installation before "endof_"actions"
; in setup-script ( or uninstall-script)

----

==== Adobe Acrobat Reader XI : acroread11
----
acroread11                11.0.5-1                  Adobe Reader 11
----

Das acroread11-Paket beinhaltet Acrobat Reader XI in den Sprachen deutsch, englisch und französisch.

Adaptation in the transform file *.mst
[source,prompt]
----
Installation Options
acivated - Make Reader the default PDF viewer


Shortcuts
deactivated - Destination Computer/Desktop/Adobe Reader XI (Icon)


Online and Acrobat.com Features
Online Features
activated - Disable product updates
Enable & Ask before Installing - Load trustet root certificates from Adobe

Adobe Online Service Integration
activated - Disable all Adobe online services based workflows an entry points
----

adobereader.mst::

Das Adobe Reader Paket von uib verwendet eine Standard-transform-Datei 
die mit dem Adobe Customization Wizard erstellt ist.
Abweichend davon können im Share `opsi_depot` im Verzeichnis 
`/opt/pcbin/install/acroread11/custom` eigene MST-Dateien abgelegt werden, die über diese 
Property ausgewählt werden können.
Beim Einspielen des acroread11-Pakets auf dem opsi-Server wird das Verzeichnis
custom ueber ein preinst/postinst-Script
gesichert.

CAUTION: Bei Einsatz des Wan/VPN Moduls muss nach Änderungen im Verzeichnis `custom` das Paket neu eingespielt werden, damit die Datei
* `<productid>.files` +
neu erzeugt wird

client_language::

Das acroread-Paket beinhaltet Acrobat Reader X in den Sprachen deutsch, englisch und französisch.
Ist der Wert auf "auto" gesetzt, so wird anhand der Systemsprache automatisch die Sprache erkannt. values: ["auto", "de", "en", "fr" ]  default: ["auto"]


protectedmode::

Enable Adobe Reader Protected Mode values: ["off", "on", "userchoice"] default: ["on"]

misc::

Bereitstellung zusätzlicher Fonts
* AdbeRdrSD11000_all.msi : Adobe Reader XI Spelling Dictionary Pack

* FontPack11000_XtdAlf_Lang.msi: Adobe Reader XI Font Packs - Asian and Extended Language Pack

values: ["AdbeRdrSD11000_all.msi", "FontPack11000_XtdAlf_Lang.msi", "none"]
default: ["none"]

noreboot:: 

description: noreboot=true: Don't Reboot.  Warning will be logged if a reboot is required.
values: ["false", "true"]
default: ["false"]



[[opsi-manual-abo-products-standard-acroread]]
==== Adobe Acrobat Reader X : acroread
----
acroread                  10.1.8-1                  Adobe Reader 10
----

Das acroread-Paket beinhaltet Acrobat Reader X in den Sprachen deutsch, englisch und französisch.

Adaptation in the transform file *.mst
[source,prompt]
----
Installation Options
acivated - Make Reader the default PDF viewer

Shortcuts
deactivated - Destination Computer/Desktop/Adobe Reader X (Icon)

Online and Acrobat.com Features
Online features
activated - Disable all updates

Acrobat.com Features
activated - Disable only Upload and Share documents to Acrobat.com
----

adobereader.mst::

Das Adobe Reader Paket von uib verwendet eine Standard-transform-Datei 
die mit dem Adobe Customization Wizard erstellt ist.
Abweichend davon können im Share `opsi_depot` im Verzeichnis 
`/opt/pcbin/install/acroread/custom` eigene MST-Dateien abgelegt werden, die über diese 
Property ausgewählt werden können.
Beim Einspielen des acroread-Pakets auf dem opsi-Server wird das Verzeichnis
custom ueber ein preinst/postinst-Script
gesichert.

CAUTION: Bei Einsatz des Wan/VPN Moduls muss nach Änderungen im Verzeichnis `custom` das Paket neu eingespielt werden, damit die Datei
* `<productid>.files` +
neu erzeugt wird

client_language::

Das acroread-Paket beinhaltet Acrobat Reader X in den Sprachen deutsch, englisch und französisch.
Ist der Wert auf "auto" gesetzt, so wird anhand der Systemsprache automatisch die Sprache erkannt. values: ["auto", "de", "en", "fr" ]  default: ["auto"]



desctopicon::

Soll ein Icon auf dem Desktop angelegt werden. values: ["off", "on"] default: ["off"]

protectedmode::

Enable Adobe Reader Protected Mode values: ["off", "on", "userchoice"] default: ["on"]

misc::

Bereitstellung zusätzlicher Fonts
* AdbeRdrSD1000_all.msi : Adobe Reader X Spelling Dictionary Pack 
(http://www.adobe.com/support/downloads/detail.jsp?ftpID=4859)
* FontPack1000_Xtd_Lang.msi: Adobe Reader X Font Packs - extended 
languages (http://www.adobe.com/support/downloads/detail.jsp?ftpID=4885)
                This Font Pack supports Hebrew, Arabic, Thai, and 
Vietnamese as well as the Eastern and Central European languages 
(including Cyrillic and Greek scripts)
* FontPack1000_ja_JP.msi: Adobe Reader X Font Packs - Japanese 
(http://www.adobe.com/support/downloads/detail.jsp?ftpID=4881).

values: ["AdbeRdrSD1000_all.msi", "FontPack1000_Xtd_Lang.msi", 
"FontPack1000_ja_JP.msi", "FontPack1000_ko_KR.msi", 
"FontPack1000_zh_CN.msi", "FontPack1000_zh_TW.msi", "none"]
default: ["none"]

[[opsi-manual-abo-products-standard-flashplayer]]
==== Adobe Flashplayer : flashplayer
----
flashplayer                      13.0.0.231-1 Adobe Flashplayer
----
Das flashplayer-Paket beinhaltet Adobe Flashplayer in den von Adobe unterstützten Versionen standard und esr ( Extended Support Release http://blogs.adobe.com/flashplayer/2014/03/upcoming-changes-to-flash-players-extended-support-release.html )

flashplayer-version:: Flashplayer standard as default or Extended Support Release (esr) http://blogs.adobe.com/flashplayer/2014/03/upcoming-changes-to-flash-players-extended-support-release.html
values: esr, standard
default: standard

mms.cfg::

Die zentrale Konfigurationsdatei mms.cfg

wird bei jedem neu "auf setup" setzen

neu erstellt und gemaess den Produktproperties angepasst.

Bei leeren Werten werden keine Eintraege gemacht.

Weitere Hinweise siehe

.Adobe Flashplayer Admin Guide:

[source,prompt]
----

flash_player_11_1_admin_guide.pdf (flash_player_admin_guide.pdf)

#####################################
Chapter 4: Administration

You can create and place files on the end user’s machine to manage 
features related to security, privacy, use of disk
space, and so on.

Privacy and security settings (mms.cfg)

As a network administrator, you can install Flash Player across the 
enterprise while enforcing some common global
security and privacy settings (supported with installation-time 
configuration choices). To do this, you install a file
named mms.cfg on each client machine.

The mms.cfg file is a text file. When Flash Player starts, it reads its 
settings from this file, and uses them to manage
functionality as described in the following sections.

mms.cfg file location

Assuming a default Windows installation, Flash Player looks for the 
mms.cfg file in the following system directories:

32-bit Windows - %WINDIR%\System32\Macromed\Flash

64-bit Windows - %WINDIR%\SysWow64\Macromed\Flash

Note: The %WINDIR% location represents the Windows system directory, 
such as C:\WINDOWS.

----

assetcachesize::
description: hard limit, in MB, on the amount of local storage that Flash Player uses for the storage of common Flash components
values: ["20"]
default: ["20"]

autoupdatedisable::
description: Lets you prevent Flash Player from automatically checking for and installing updated versions.
values: ["0", "1"]
default: ["1"]

autoupdateinterval::
description: (without meaning if AutoUpdateDisable=1) how often to check for an updated version of Flash Player

avhardwaredisable::
description: Lets you prevent SWF files from accessing webcams or microphones
values: ["0", "1"]
default: ["1"]

disabledevicefontenumeration::
description: Lets you prevent information on installed fonts from being displayed.
values: ["0", "1"]
default: ["1"]

fullscreendisable::
description: Lets you disable SWF files playing via a browser plug-in from being displayed in full-screen mode
values: ["0", "1"]
default: ["1"]

localfilereaddisable::
description: Lets you prevent local SWF files from having read access to files on local hard drives
values: ["0", "1"]
default: ["0"]

filedownloaddisable::
description: Lets you prevent the ActionScript FileReference API from performing file downloads
values: ["0", "1"]
default: ["0"]

fileuploaddisable::
description: Lets you prevent the ActionScript FileReference API from performing file uploads
values: ["0", "1"]
default: ["0"]

disableproductdownload::
description: Lets you prevent native code applications that are digitally signed and delivered by Adobe from being downloaded
values: ["0", "1"]
default: ["1"]

disablesockets::
description: enable or disable the use of the Socket.connect() and XMLSocket.connect() methods
values: ["0", "1"]
default: ["1"]

enablesocketsto::
description: Lets you create a whitelist of servers to which socket connections are allowed

enforcelocalsecurityinactivexhostapp::
description: Lets you enforce local security rules for a specified application.

legacydomainmatching::
description: Lets you specify whether SWF files produced for Flash Player 6 and earlier can execute an operation that has been restricted in a newer version of Flash Player
values: ["0", "1"]
default: ["0"]

localfilelegacyaction::
description: Lets you specify how Flash Player determines whether to execute certain local SWF files that were originally produced for Flash Player 7 and earlier
values: ["0", "1"]
default: ["0"]

allowuserlocaltrust::
description: Lets you prevent users from designating any files on local file systems
values: ["0", "1"]
default: ["0"]

localstoragelimit::
description: Lets you specify a hard limit on the amount of local storage that Flash Player uses (per domain) for persistent shared objects.
values: ["3"]
default: ["3"]

overridegpuvalidation::
description: Overrides validation of the requirements needed to implement GPU compositing
values: ["0", "1"]
default: ["0"]

rtmfpp2pdisable::
description: Specifies how the NetStream constructor connects to a server when a value is specified for peerID, the second parameter passed to the constructor
values: ["0", "1"]
default: ["1"]

disablenetworkandfilesysteminhostapp::
description: 1 (Acrobat.exe,Acroread.exe,WINWORD.EXE,EXCEL.EXE,POWERPNT.EXE,PPTVIEW.EXE,OUTLOOK.EXE,MSACCESS.EXE,VISIO.EXE,thunderbird.exe)
values: ["0", "1"]
default: ["1"]

* *Bekannte Probleme* +

- Beim Einspielen "On Demand" kann die Installation aufgrund geöffneter
Browser fehlschlagen!

[[opsi-manual-abo-products-standard-google-chrome]]
==== Google Chromium for Business
----
google-chrome-for-business 31.0.1650.63-2                         3.4-2                     Apache OpenOffic
----

Das Paket beinhaltet den msi-Installer von Google (Häufig gestellte 
Fragen  Chrome for Business https://support.google.com/a/answer/188447).

autoupdate::

vgl.
https://support.google.com/chrome/a/answer/187207

gibt es 0,1,2,3 als Wert für
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Update\UpdateDefault

bzw ADM falls Gruppenrichtlinien verwendet werden

ADM= use Policy based on Googles Template,
0=UpdatesDisabled,
1=UpdatesEnabled,
2=ManualUpdatesOnly,
3=AutomaticUpdatesOnly,
values: ["0", "1", "2", "3", "ADM"]
default: ["0"]

removeupdatehelper::
default: ["true"]


[[opsi-manual-abo-products-standard-openoffice]]
==== Apache OpenOffice : ooffice3
----
ooffice3                         3.4-2                     Apache OpenOffic
----

Das ooffice3-Paket beinhaltet Apache OpenOffice in deutsch.

handle_excel_xls::

Soll OpenOffice.org fuer MS-Excel-Dokumente registriert werden
 on  = OpenOffice.org wird fuer MS-Exceldokumente registriert
 off = OpenOffice.org wird nicht fuer MS-Exceldokumente registriert

handle_powerpoint_ppt ::

Soll OpenOffice.org fuer MS-PowerPoint-Dokumente registriert werden
 on  = OpenOffice.org wird fuer MS-PowerPointdokumente registriert
 off = OpenOffice.org wird nicht fuer MS-PowerPointdokumente registriert

handle_word_doc ::

Soll OpenOffice.org fuer MS-Word-Dokumente registriert werden
 on  = OpenOffice.org wird fuer MS-Worddokumente registriert
 off = OpenOffice.org wird nicht fuer MS-Worddokumente registriert

remove_ooo2 ::

Soll OpenOffice.org 2 deinstalliert werden
 true  = OpenOffice.org 2 wird bei der Installation von OpenOffice.org 3 entfernt
 false = OpenOffice.org 2 bleibt bei der Installation von OpenOffice.org 3 erhalten


[[opsi-manual-abo-products-standard-libreoffice]]
==== LibreOffice 3 The Document Foundation  : libreoffice
----
libreoffice               3.6.7-3                   libreoffice
----

Das libreoffice-Paket beinhaltet LibreOffice 3 international.

client_language ::

client_language - only for messages important, cause libre office is international
values: ["auto", "de", "en", "fr"]

msoregister :: Open Microsoft Office documents with LibreOffice (true)
values: ["false", "true"]
default: ["false"]

[[opsi-manual-abo-products-standard-firefox]]
==== Mozilla Firefox : firefox
----
firefox                          17.0.9esror24.0esrorstandard-1
---- 
Das firefox-Paket beinhaltet Mozilla Firefox in den Sprachen deutsch, englisch, französisch und niederländisch.

Es werden alle von Mozilla unterstützten Versionen bereitgestellt.

Eine zentrale Konfigurationsdatei (vgl. http://kb.mozillazine.org/Locking_preferences) kann bereitgestellt werden im Verzeichnis  
[source,prompt]
----
/opt/pcbin/install/firefox/custom/
----

Bei erneutem Einspielen des Pakets werden die gefundenen Konfigurationsdateien über preinst-/postinst-Mechanismus erhalten und dann über die Property "mozillacfg" auswählbar.

- Beispiel 

[source,prompt]
----
cat /opt/pcbin/install/firefox/custom/mozilla.cfg
//
lockPref("browser.startup.homepage", "http://www.uib.de");
lockPref("network.proxy.type", 1);
lockPref("network.proxy.http", "router.uib.local");
lockPref("network.proxy.http_port", 3128);
----

CAUTION: Bei Einsatz des Wan/VPN Moduls muss nach Änderungen im Verzeichnis `custom` das Paket neu eingespielt werden, damit die Datei
* `<productid>.files` +
neu erzeugt wird


client_language::
      values: ["auto", "de", "en", "fr", "nl"]
      default: ["auto"]

firefox-version :: Firefox '17.0esr' - is the Extended Support Release from Mozilla.org (17.0.9esr) as default version; Firefox '24.0esr' - is the new Extended Support Release from Mozilla.org (24.0esr); 'standard' (24.0) is the Mozilla.org standard version
values: ["17.0esr", "24.0esr", "standard"]
default: ["17.0esr"]

pref_file:: (user/prefs)= in welcher Datei sollen die Einstellungen
gemacht werden user.js oder prefs.js. values: ["prefs", "user"]
default: ["prefs"]

noautoupdate:: (on/off): auto update ausschalten. default=on

setproxy:: (off/direct/manual/file) proxy einstellungen verändern
*  off= tue nichts
*  direct = direkte Verbindung zum Internet
*  manual = Proxyeinstellungen über property proxysetting
(<ip-numme>:<port>) und property noproxy_hosts (host1,host2)
*  file = Proxyeinstellungen über property proxysetting
(<path_to_proxyconf.pac>) und property noproxy_hosts (host1,host2)
* system
* default=off

proxysetting:: string für proxy Einstellung (siehe: setproxy)

noproxy_hosts:: Komma separierte Liste von hosts

mozillacfg::
description: filename for mozilla.cfg in `%scriptpath%\custom`-directory, http://kb.mozillazine.org/Locking_preferences

profilemigrator:: enable or disable Profilemigrator on first run
values: ["off", "on"]
default: ["off"]

* *Bekannte Probleme* +
- Beim Einspielen "On Demand" kann die Installation aufgrund geöffneter Programme fehlschlagen!

[[opsi-manual-abo-products-standard-thunderbird]]
==== Mozilla Thunderbird : thunderbird
----
thunderbird               17.0.9esrorstandard-1
----
Das thunderbird-Paket beinhaltet Mozilla Thunderbird in den Sprachen deutsch, englisch und französisch.

Es werden alle von Mozilla unterstützten Versionen bereitgestellt.

Analog dem Firefox-Paket kann zentrale Konfigurationsdatei bereitgestellt werden.

client_language::
values: ["auto", "de", "en", "fr"]
default: ["auto"]

thunderbird-version:: Thunderbird '17.0esr' - is the Extended Support Release from Mozilla.org (17.0.9esr)(default); 'standard' (24.0) is the Mozilla.org standard version
values: ["17.0esr", "standard"]
default: ["17.0esr"]

addonsactivation::
description: Enable/Disable AddOns (default = enable)
values: ["off", "on"]
default: ["on"]

https://developer.mozilla.org/en/Addons/Add-on_Manager/AddonManager

http://mike.kaply.com/2012/02/09/integrating-add-ons-into-firefox/

https://developer.mozilla.org/en/Thunderbird/Deploying_Thunderbird_in_the_Enterprise/Thunderbird_Preferences_Relevant_to_Enterprises
[source,prompt]
----
Set_Netscape_User_Pref ("extensions.autoDisableScopes", 11)
Set_Netscape_User_Pref ("extensions.shownSelectionUI", true)
----


enigmail::
description: Install GnuPG-Plugin
values: ["off", "on"]
default: ["off"]
----
Thunderbird 17.0-27.0 Enigmail 1.5.2
----


noautoupdate::
description: disable automatic updates
values: ["off", "on"]
default: ["on"]

mozillacfg::
description: filename for mozilla.cfg in `%scriptpath%\custom`-directory, http://kb.mozillazine.org/Locking_preferences


lightning::
description: Install calender plugin lightning
values: ["off", "on"]
default: ["off"]
----
Thunderbird 17.0.  Lightning 1.9.1
Thunderbird 24.0.  Lightning 2.6
----

* *Bekannte Probleme* +
- Beim Einspielen "On Demand" kann die Installation aufgrund geöffneter Programme fehlschlagen!

[[opsi-manual-abo-products-standard-javavm]]
==== Oracle Jre : javavm
----
javavm              1.7.65-1          Oracle Java Run
----
Das javavm-Paket beinhaltet die Oracle Jre 7.x und Jre 8.x

( Für Jre 1.6.x ist das Ende der "Public Updates" für in 2013 angekündigt, http://www.oracle.com/technetwork/java/eol-135779.html )

Die Oracle JRE wird dabei mit "Patch-in-place configuration" installiert (seit jre 1.6.0_10 ) 

http://www.oracle.com/technetwork/java/javase/jre-install-137694.html

Vor der Installation werden bestehen "Patch-in-place" Jre-Versionen 1.6.x, 7.x und 1.8xdeinstalliert.

- Vorhandene Oracle JRE mit "Static configuration" werden nicht deinstalliert.
- Eventuell vorhandene Oracle JRE (version 1.6.0 - version 1.6.7) werden deinstalliert, es sei denn Sie werden explizit über die property "keepversion" ausgeschlossen oder aber
die Property uninstalljava16=false gesetzt.

Eine zentrale Konfigurationsdatei deployment.properties (vgl. http://docs.oracle.com/javase/6/docs/technotes/guides/deployment/deployment-guide/properties.html
http://docs.oracle.com/javase/7/docs/technotes/guides/deployment/deployment-guide/properties.html) kann bereitgestellt werden im Verzeichnis  
[source,prompt]
----
/opt/pcbin/install/javavm/custom/
----

Bei erneutem Einspielen des Pakets werden die gefundenen Konfigurationsdateien über preinst-/postinst-Mechanismus erhalten und dann über die Property "deployment.properties" auswählbar.

- Beispiel 

[source,prompt]
----
cat /opt/pcbin/install/javavm/custom/deployment.properties
//
#deployment.properties
#Tue Dec 18 12:36:01 CET 2012
deployment.javaws.autodownload=NEVER
deployment.javaws.autodownload.locked=
deployment.security.validation.ocsp=true
deployment.security.validation.ocsp.locked=
deployment.security.validation.crl=true
deployment.security.validation.crl.locked=

----

CAUTION: Bei Einsatz des Wan/VPN Moduls muss nach Änderungen im Verzeichnis `custom` das Paket neu eingespielt werden, damit die Datei
* `<productid>.files` +
neu erzeugt wird




install_architecture::
description: which architecture (32/64 bit) has to be installed
values: ["32 only", "64 only", "both", "system specific"]
default: ["both"]

javaversion::
description: which version has to be installed (JRE 1.8.x or JRE 7 = 1.7.x)
values: ["jre8", "jre7"]
default: ["jre7"]

keepversion::
description: Dont uninstall jre version
values: ["1.6.0_0", "1.6.0_1", "1.6.0_2", "1.6.0_3", "1.6.0_4", "1.6.0_5", "    1.6.0_6", "1.6.0_7", "none"]
default: ["none"]

webjava::
description: TESTING: http://java.com/en/download/help/silent_install.xml WEB_JAVA=0, if used, disables any Java application from running in the browser
values: ["0", "1", "none"]
default: ["none"]

CAUTION: WEB_JAVA=0 liefert missverständliche Meldungen im Browser("fehlendes plugin")

deployment.properties::
description: filename for deployment.properties in %scriptpath%\custom-directory, http://docs.oracle.com/javase/7/docs/technotes/guides/deployment/deployment-guide/properties.html saved by pre- postinstscript

uninstalljava16:: Uninstall Java 1.6 "Patch in Place" Installations
default: True

startmenuentry:: Create Entry for java in common startmenu aboutJava,CheckForUpdates,ConfigureJava,GetHelp,VisitJava.com
default: False

timeout:: TimeOutSeconds msi installs
values: ["180", "240", "300", "notimeout"]
default: ["300"]


* *Bekannte Probleme* +
- Beim Einspielen "On Demand" kann die Installation aufgrund geöffneter Programme fehlschlagen!
