////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; Until we found a better license:
; All rights reserved.
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      25.09.2013
:Revision:  1.0
:toclevels: 6


include::../common/opsi_terms.asciidoc[]

[[opsi-setup-detector]]
== opsi Setup Detector

[[opsi-setup-detector-introduction]]
=== Einführung

Der opsi Setup Detector ist ein opsi Werkzeug zur integrierten Unterstützung der Software-Paketierung. Von seiner grafischen Benutzeroberfläche können alle Schritte von der Auswahl der Setup-Datei über das Erstellen der Installationsverzeichnisse auf der opsi Workbench bis zur Paketierung und Installation auf dem opsi Server durchgeführt werden. Hierzu arbeitet der Setup Detector mit dem opsi Package Builder zusammen. 
Der opsi Setup Detector erkennt beim Öffnen einer Setup-Datei, ob es sich um einen bekanneten Installer-Typ handelt und ermittelt automatisch die verfügbaren Informationen aus der Setup-Datei. 
Mit der Zeit wird durch weitere Erfahrungen mit verschiedenen Installer-Typen und Rückmeldungen der Benutzer die Fähigkeit der automatischen Detektierung sicher noch weiter wachsen.

[[opsi-setup-detector-prerequires]]
=== Vorbedingungen für die Benutzung des opsi Setup Detectors

Der opsi Setup Detector läuft auf Windows-Systemen ab Windows XP und benötigt, falls die Pakete auch gepackt und installiert werden sollen, das Community Projekt opsi Package Builder, welches auf dem gleichen Windows-Rechner zu installieren ist. 
Weitere Informationen zum opsi Package Builder finden Sie im opsi Forum bei den opsi Community Projekten:
https://forum.opsi.org/viewforum.php?f=22

Für die Erzeugung der Pakete ist ein Samba-Share mit Schreibberechtigung auf die opsi Workbench notwendig.
Ausserdem ist zu beachten, dass manche Software-Pakete (z.B. manche Software für 64bit Windows7) eine entsprechenden Window-System voraussetzen. Das heißt, ein Setup für eine 64bit Windows7 Software kann eventuell nicht auf einem 32bit WindowsXP paketiert werden. Das hängt im Einzelfall von dem jeweiligen Setup und verwendeten Installer-Typ ab. 

Hier nochmal die Voraussetzungen als Liste:

* Windows-Rechner ab Windows XP
* opsi Setup Detector installieren
* opsi package Builder installieren
* Samba-Share mit Schreibrechten zur opsi Workbench eintragen

[[opsi-setup-detector-activate]]
=== Inbetriebnahme des opsi Setup Detectors

Der opsi Setup Detector ist ein mit Lazarus entwickeltes fertig compiliertes Windows-Programm und kann direkt verwendet werden. Lediglich der Samba-Share auf die opsi Workbench ist als Basisverzeichnis einzutragen und schon kann mit Datei öffnen eine Setup-Datei geöffnet werden, die dann automatisch analysiert wird.

==== Sprachunterstützung

Beim Start des Programmes wird ermittelt, unter welcher Sprache das Windows System läuft. Von Haus aus unterstützt der opsi Setup Detector Deutsch und Englisch. Weitere Sprachen können recht einfach über eine entsprechend übersetzte Sprachdatei unterstützt werden. 

[[opsi-setup-detector-analyze]]
=== Automatische Analyse eines Setup-Paketes

Nach dem Öffnen einer Setup-Datei mit Datei öffnen wird diese automatisch analysiert und, falls es sich um einen bekannten Installer-Typ handelt, automatisch auf den entsprechenden Tab gewechselt.
Falls der Installer-Typ nicht erkannt wird, bleibt weiterhin das Anaysiere Tab stehen. Auch wenn der Installer-Typ erkannt wurde, kann jederzeit auf das Analysiere Tab zurück gewechselt werden um zu sehen, was bei der automatischen Analyse gefunden wurde.

Bei der Analyse einer MSI-Datei ist bereits durch die Endung MSI bekannt, dass es sich um ein MSI-Paket handelt. Einer EXE-Datei sieht man es aber nicht an der Endung an, mit welchem Installer-Typ sie erstellt wurde. Deshalb wird die EXE-Datei vom opsi Setup Detector automatisch nach bestimmten Stichworten durchsucht und die gefundenen Zeilen werden ausgegeben. Darin sind auch Strings enthalten, die das Setup-Programm in bestimmten Fällen, z.B. bei aufgetretenen Fehlern während der Installation ausgeben möchte. Dadurch können z.B. kryptische Zeilen und auf den ersten Blick alarmierende Zeilen erscheinen  wie:

----
o@dejDs@s@t@t@du@u@<v@w@w@lx@Hy@x@x{@X|@|@@@@L@x@@Inno Setup Setup Data
Das Setup hat einen schwerwiegenden Fehler erkannt und wird abgebrochen
----

Dies besagt aber nur, dass diese Zeichen innerhalb des Setups gefunden wurden und im Analysiere Tab angezeigt werden, da sie einem der verwendeten Suchmuster entsprechen. Diese Ausgaben können normalerweise ignoriert werden und sind nur von Interesse, falls kein bekannter oder ein falscher Setup-Typ detektiert wurde. In diesem Fall geben diese Angaben eventuell einen Hinweis, um welchen 
Installer-Typ es sich handeln könnte.
Alle Angaben auf dem Analysiere Tab, die eingeleitet werden von:

----
Analyzing: F:\<setup.exe>
xxxxxxxxxxxxxxxxxxxxxxxxx
default grep started:
----

und abgeschlossen werden mit:

----
default grep finished.
xxxxxxxxxxxxxxxxxxxxxxxxx
----

entstammen dieser automatischen Analyse und können im Normalfall unbeachtet bleiben.
Falls der Setup-Typ erkannt wurde, steht dieser unterhalb von "default grep finished". Dass ein bekannter Setup Typ erkannt wurde  merkt man auch daran, dass automatisch auf den entsprechenden Tab gewechselt wurde. 

Je nach dem gefundenen Installer-Typ sind im Analysiere Tab noch weitere Informationen zu finden zur weiteren Analyse des Setups. Diese werden in den Kapiteln der entsprechenden Installer-Typen behandelt.

Der Inhalt des Analysiere Tabs wird vor einer neuen Analyse gelöscht und enthält dementsprechend nur Informationen zu dem aktuellen Setup.

[[opsi-setup-detector-type]]
=== Unterstützte Installer-Typen

Die einzelnen Installer-Typen sind sehr unterschiedlich bezüglich ihrer standardisierten Struktur und automatisierten Zugänglichkeit. Bei einem MSI-Paket oder einem auf Inno-Setup basierenden Setup kann eine Menge nützlicher Informationen detektiert werden, während andere Installer-Typen, wie z.B. NSIS, keine internen Informationen des Setups zugreifbar machen. In vielen Fällen bringt die automatisierte Analyse gute Ergebnisse, aber es kann auch immer wieder Ausnahmen geben, bei denen die Standard Vorgehensweise nicht funktioniert.

Die Tabs der einzelnen Installer-Typen sind alphabetisch angeordnet.

[[opsi-setup-detector-type-msi]]
==== Installer-Typ MSI

Setups vom Installer-Typ MSI sind bereits an der Endung MSI als solche zu erkennen. Das Paketformat ist weitgehend standardisiert, so dass automatisch weitere Informationen aus dem Paket ausgelesen werden können und im MSI Tab, auf den automatisch gewechselt wird, angezeigt werden. Die im Analysiere Tab angezeigten Informationen sehen bei einem MSI-Paket z.B. so aus: 

----
Analyzing MSI: F:\Setups\MSI\7-zip\7-Zip.msi

Microsoft (R) Windows Script Host, Version 5.8
Copyright (C) Microsoft Corporation 1996-2001. Alle Rechte vorbehalten.

MSI file: F:\uib\setupdetector\Setups\MSI\7-zip\7-Zip.msi
Manufacturer: Igor Pavlov
ProductName: 7-Zip 4.57
ProductVersion: 4.57.00.0
ProductCode: {23170F69-40C1-2701-0457-000001000000}
UpgradeCode: {23170F69-40C1-2701-0000-000004000000}
MSI file size is: 0,9 MB
Estimated required space is: 5,2 MB

get_MSI_info finished
----

Diese Informationen werden aus dem MSI-Paket gelesen und automatisch in die einzelnen Felder des MSI Tabs übernommen. Diese Angaben werden benötigt zum patchen der opsi Installations-Scripte:

* MSI Datei: Name der geöffneten MSI Datei
* opsi Product ID: dies ist der Name des zu erzeugenden opsi Paketes und wird aus dem weiter unten stehenden Produkt Namen erzeugt, wobei Leerzeichen und andere ungültigen Zeichen durch ein '_' ersetzt werden. Die vorgeschlagene opsi Product ID kann natürlich geändert werden.
* Produkt Name: der aus dem MSI Paket ausgelesene Name der zu installierenden Software. Diesen Namen möchte man wahrscheinlich im Normalfall beibehalten.
* Produkt Version: die ausgelesene Version der zu installierenden Software. Auch diese Angabe möchte man wohl im Normalfall beibehalten.
* MSI Produkt Code: der aus dem Paket ausgelesene Produkt-Code, welcher für das Deinstallations-Script benötigt wird. Vorsicht: falls das MSI-Paket z.B. getrennte Versionen für 32bit und 64bit enthält, haben diese wahrscheinlich einen jeweils unterschiedlichen Produkt Code.
* erforderlich: dieser vorgeschlagene Wert stammt nicht aus dem MSI-Paket, sondern ist geschätzt als sechsmal die Größe der MSI-Datei und sollte gegebenfalls angepasst werden.
Größe MSI: die ermittelte Größe des MSI-Paketes.
* MST Datei: wird im gleichen Verzeichnis (also dort, wo das MSI-Paket liegt) eine MST-Datei gefunden, wird diese eingetragen und beim Aufruf des Setup verwendet.


[[opsi-setup-detector-logfile]]
==== Lokale Logdatei

Es wird eine lokale Logdatei erzeugt, die den Inhalt des Analysiere-Tabs enthält. Diese Logdatei wird für jedes Setup neu erzeugt und enthält also nur Informationen zu dem zuletzt aufgerufenen Setup.


