////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////


:Author:    uib gmbh
:Email:     info@uib.de
:Date:      13.04.2011
:Revision:  4.0
:toclevels: 6

include::../common/opsi_terms.asciidoc[]


[[opsi-manual-overview]]
== Überblick opsi

Werkzeuge zur automatischen Softwareverteilung und Betriebssysteminstallation sind bei größeren PC-Netz-Installationen ein wichtiges Werkzeug zur Standardisierung, Wartbarkeit und Kosteneinsparung. Während die Verwendung solcher Werkzeuge für gewöhnlich mit erheblichen Lizenzkosten einher geht, bietet opsi als Opensource-Werkzeug deutliche Kostenvorteile. Hier fallen nur die Kosten an, die von Ihnen durch tatsächlich angeforderte Dienstleistungen, wie Beratung, Schulung und Wartung, entstehen bzw. soweit kostenpflichtige Module benutzen wollen geringe Kofinanzierungsbeiträge.

Auch wenn Software und Handbücher kostenlos sind, ist es die Einführung eines Softwareverteilungswerkzeuges nie. Um die Vorteile ohne Rückschläge und langwierige Lernkurven nutzen zu können, ist die Schulung und Beratung der Systemadministratoren durch einen erfahrenen Partner dringend geboten. Hier bietet Ihnen uib seine Dienstleistungen rund um opsi an.

Das von uib entwickelte System basiert auf Linux-Servern, über die das Betriebssystem und Software-Pakete auf den PC-Clients installiert und gewartet  werden (PC-Server-Integration). Es basiert weitestgehend auf frei verfügbaren Werkzeugen (GNU-tools, SAMBA etc.). Dieses opsi (Open PC-Server-Integration) getaufte System ist durch seine Modularität und Konfigurierbarkeit in großen Teilen eine interessante Lösung für die Probleme der Administration eines großen PC-Parks.

[[opsi-manual-overview-experience]]
=== Erfahrung

opsi ist die Fortschreibung eines Konzepts, das seit Mitte der 90er Jahre bei einer Landesverwaltung auf über 2000 Clients in verschiedenen Lokationen kontinuierlich im Einsatz ist und stetig weiterentwickelt wurde. Als Produkt opsi ist es nun auch einem breiten Kreis von Interessenten zugänglich.

Eine Übersicht registrierter opsi-Installationen finden Sie unter: http://www.opsi.org/map/

[[opsi-manual-overview-features]]
=== Features von opsi

Die wesentlichen Features von opsi sind:

* automatische Softwareverteilung
* Automatische Betriebssysteminstallation
* Hard- und Softwareinventarisierung
* Komfortable Steuerung über das opsi Managementinterface
* Unterstützung von mehreren Standorten mit Depotservern


[[opsi-manual-overview-extensions]]
=== opsi Erweiterungen

* Lizenzmanagement
* MySQL-Backend
* Nagios Connector
* dynamische Depotzuweisung
* Software on Demand
* WAN Erweiterung (Einbindung von Clients hinter langsamen Leitungen)
* User Profile Management: User Profile z.B. in einer Roamig-Profile Umgebung können modifiziert werden.
* OTRS::ITSM Connector (von unserem Partner Cape-IT)


