////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      01.02.2013
:Revision:  4.0.3
:toclevels: 6


include::../common/opsi_terms.asciidoc[]

[[opsi-manual-localimage]]
== opsi Erweiterung 'opsi local image'


[[opsi-manual-localimage-preconditions]]
=== Vorbedingungen für die opsi Erweiterung 'opsi local image'

Dieses Modul ist momentan eine
http://www.uib.de/www/kofinanziert/index.html[kofinanzierte opsi Erweiterung]. +
Es sind eine Reihe von Vorbedingungen nötig, um dieses Modul einsetzen
zu können. Das bedeutet, das Sie zum Einsatz eine Freischaltdatei benötigen. Diese Freischaltung erhalten Sie wenn Sie die Erweiterung kaufen. Zu Evaluierungszwecken stellen wir Ihnen auch eine zeitlich befristete Freischaltung kostenlos zur Verfügung ( -> mail an info@uib.de). +

////
Weitere Details hierzu finden Sie in <<opsi-manual-modules>>.
////

IMPORTANT: Diese kofinanzierte Erweiterung kann bis auf weiteres nur von der öffentlichen Hand (z.B. Schulen / Unis) erworben werden.

Technische Voraussetzungen sind opsi 4.0.3 mit den Paketständen:

.Benötigte Pakete
[options="header"]
|==========================
|opsi-Paket|Version
|opsi-linux-bootimage|>= 20130207-1
|==========================


[[opsi-manual-localimage-introduction]]
=== Einführung

Opsi bietet eine gute Basis, um automatisiert Windows Rechner zu installieren und zu pflegen - auch und gerade, wenn es sich um heterogene Hardware handelt. Die von opsi unterstützte Technik der Paket basierten Installation ist aber nicht schnell genug, um in Schulungsräumen Rechner innerhalb von kurzer Zeit wie z.B. in einer Pause zwischen zwei Kursen wieder in einen definierten Zustand zu versetzen. Daher wird hier ein Konzept vorgestellt, bei dem die paketbasiert durch geführte Installation lokal auf einer zweiten Partition als Imagekopie gesichert wird und von dort eine schnelle Wiederherstellung möglich ist.

. Initiale Installation mit abschließender lokaler Image-Sicherung
. Schnelle Wiederherstellung auf Basis unterschiedlicher Techniken
. Systempflege mit abschließender lokaler Image-Sicherung
. Integration von Linuxclients in das Backup/Restore Verfahren.

[[opsi-manual-localimage-concept]]
=== Konzept

Die Anforderungen edukativer Computernetze unterscheiden sich teilweise von denen anderer Netzwerke. Eine wesentliche Anforderung, die im Folgenden diskutiert wird, ist die schnelle Wiederherstellung von Rechnern in einen definierten Zustand, den Sie im Rahmen einer temporären Nutzung verloren haben. Konkret geht es um die Bereitstellung von Rechnern in schulischen Computerräumen, wobei die Problemlage auch auf kommerzielle Computerräume oder universitäre Computerpools zutrifft. 

Die Wiederherstellung muss zwingend innerhalb von kurzer Zeit (15 Minuten / Große Pause) erfolgen und sollte soweit möglich einen Rechner nicht nur 'zurücksetzen' sondern auf eine andere Basisinstallation (z.B. Win XP / Win 7 / Linux) umschalten können. Weiterhin muss es möglich sein, dass eine kontinuierliche Pflege der Systeme mit Sicherheitsupdates gewährleistet ist.

opsi ist ein Client-Management-System, das seine Stärken in der paketbasierten Installation und Pflege von Windows-Systemen hat. Dabei gibt es im Umgang mit heterogener Hardware deutliche Vorteile gegenüber rein imagebasierten Systemen. Die damit einhergehenden Installationszeiten von etwa 2 Stunden sind aber weit von den oben angegebenen Anforderungen entfernt. imagebasierte Lösungen sind hier prinzipiell schneller. Aber auch rein imagebasierte Systeme können bei dem Versuch, für einen ganzen Klassenraum ein Image herunterzuladen, zu Netzwerkproblemen führen. Dieses Problem kann durch lokal gepufferte Images gelöst werden. Ein solcher Ansatz wird z.B. vom Linux basierten System LinBo (Quelle http://linbo.sourceforge.net/) verfolgt. Doch auch mit lokal gepufferten Images kann es, abhängig von der verwendeten Hardware (Stichwort Festplatten- Performance), zu Zeitproblemen kommen, wenn versucht wird, komplette Images innerhalb von 15 Minuten wiederherzustellen.

Eine weitere mögliche Problemlösung, das Einfrieren eines Betriebssystems und Umlenken sämtlicher Schreibzugriffe in einen externen Container, der bei einem Neustart einfach verworfen werden kann, ist eine möglicher Ansatzpunkt. Für Linux existieren Ansatzpunkte z.B. über FUSE Filesysteme. Für Windows gibt es eingeführte kommerzielle Produkte wie z.B. 'Deep Freeze', welche sich auch über die Kommandozeile (und damit per opsi) steuern ließen. Uns sind allerdings für den Windows Bereich keine entsprechenden Open Source Produkte bekannt. Da wir aber eine Open Source Lösung schaffen wollen, findet dieser Lösungsansatz hier keine weitere Betrachtung.

Der im Folgenden untersuchte Ansatz versucht die Vorteile der jeweiligen Ansätze zu kombinieren, ihre Nachteile zu vermeiden und für eine unterschiedliche Hardware-Ausstattung (langsame / schnelle Rechner) angepasste Möglichkeiten zu bieten. Die Grundidee kann in den folgenden Stichpunkten zusammengefasst werden:

* Initiale Windowsinstallation per PXE-Boot paketbasiert mit individueller Treiberintegration unter Verwendung des opsi-Linux-Bootimage

* Sicherung dieser initialen Installation in einem Sicherungsimage auf einer 2. Partition auf der lokalen Festplatte des Rechners unter Verwendung des opsi-Linux-Bootimage

* Schnelle Wiederherstellung der Produktiv-Installation aus dem lokalen Image unter Verwendung des opsi-Linux-Bootimage

* Pflege der lokalen Installation (Sicherheitsupdates) über die opsi Softwareverteilung und Sicherung des aktualisierten Systems auf das lokale Backup-Image unter Verwendung des opsi-Linux-Bootimage

[[opsi-manual-localimage-concept-technical]]
=== Technisches Konzept

Der Schulungsrechner wird mit einer statischen Partitionstabelle verwendet:

* Partition 1 (System) +
Hier findet sich das aktuell verwendete Betriebssystem (Windows / Linux) +
Die Größe dieser Partition wird bei der Partitionierung über das Produkt `opsi-local-image-repartition` über ein Property gesteuert.

* Partition 2 (winpe / swap) +
Die Größe dieser Partition ist statisch auf 4GB festgelegt. +
Unter Windows XP wird dies Partition nicht verwendet. +
Unter NT6 (Windows 7) wird diese Partition für das bei der Installation notwendige winpe verwendet und ist im Betrieb nicht sichtbar. +
Unter Linux wird diese Partition als Swap verwendet.

* Partition 3 (data) +
Diese Partition dient zur Speicherung der gesicherten Images und ihrer Metadaten. +
Die Größe dieser Partition ergibt sich aus dem nach Erstellung der anderen Partitionen noch vorhandenen freien Platz.

Die Netbootprodukte zur Betriebssystem Installation verwenden die ersten beiden Partitionen (XP nur die erste) und lassen die Partition 3 unberührt. Somit bleiben die auf der Partition 3 liegenden Images auch bei der Installation eines neuen Betriebssystems erhalten.


[[opsi-manual-localimage-components]]
=== Komponenten

Das Paket 'opsi-local-image' besteht aus mehreren Komponenten:

Den Netbootprodukten

* `opsi-local-image-repartition`
* `opsi-local-image-winxp`
* `opsi-local-image-win7`
* `opsi-local-image-win7-x64`
* `opsi-local-image-ubuntu32`
* `opsi-local-image-backup`
* `opsi-local-image-restore`
* `opsi-local-image-delete`

Dem Lokalbootprodukt:

* `opsi-local-image-backup-starter`

Einer Erweiterung der opsi Service Methoden.

[[opsi-manual-localimage-components-part]]
==== Netboot Produkte zur Partitionierung
 
* `opsi-local-image-repartition` +
Erstellung der statischen Partitionierung der Festplatte für alle anderen Produkte. +
Über das Property `system_partition_size` wird die Größe der Partition 1 angegeben (Default = 30G) +
Bei der Installation dieses Produkts werden beim Produkt `opsi-local-image-restore` die Produktproperties 'imagefile' und 'imagefiles_list' gelöscht, da durch die Neupartitionierung diese Daten ungültig geworden sind.

[[opsi-manual-localimage-components-win]]
==== Netboot Produkte zur Installation von Windows

Die Netbootprodukte zur Installation von Windows sind Abkömmlinge der opsi Standardprodukte zur Windowsinstallation. Das bedeutet konkret, das sie bezüglich des Aufbaus und der Treiberintegration identisch sind. Entsprechende Anleitungen finden sich im 'opsi-getting-started' Handbuch.

* `opsi-local-image-winxp` +
Installation von Windows XP. Verwendet nur die erste Partition.
Administrator Passwort ist leer.

* `opsi-local-image-win7` +
Installation von Windows  7 32 Bit.
Administrator Passwort = `nt123`.

* `opsi-local-image-win7-x64` +
Installation von Windows  7 64 Bit.
Administrator Passwort = `nt123`.

Diese Produkte haben als 'opsi-local-image' spezifisches Property die Einstellung 'backup_after_install' mit der default Wert 'true'. Dies bedeutet in diesem Fall, das nach der OS Installation zunächst die Anwendungssoftware installiert wird und abschließend eine Imagesicherung der Installation durchgeführt wird.

[[opsi-manual-localimage-components-linux]]
==== Netboot Produkte zur Installation von Linux

* `opsi-local-image-ubuntu32` +
Installation von Ubuntu Linux 12.04 (Precise) 32 Bit. +
Das installierte System kennt 2 user: `root` und `user`. Für 'root' wird das im Produktproperty `root_password` festgelegte Passwort gesetzt (Default: `linux123`). Für 'user' wird das im Produktproperty `user_password` festgelegte Passwort gesetzt (Default: `linux123`).
Da bisher es noch keinen opsi-client-agent für Linux gibt, enthält diese Installation eine statische über die Produktproperties gesteuerte Softwareausstattung. Die wesentlichen
 Produktproperties sind dabei: 
** `desktop` +
Hierbei wird mit dem default Wert `none` keine grafische Oberfläche installiert. Weiterhin gibt es die Auswahl zwischen `kde`, `gnome`, `unity` und `xfce4`.
** `additional_packages` +
Hier kann eine Liste von Ubuntu Paketen angegeben werden, welche ebenfalls installiert werden.
** `language` +
steuert in welcher Sprache (und Tastaturlayout) der desktop installiert wird.
** `online_repository` +
gibt an aus welchem online Repository die Pakete installiert werden sollen. Der Default ist 'http://de.archive.ubuntu.com/ubuntu' . Zur Entlastung der Internetverbindung, kann hier ein eigener 'Paket Proxy' angegeben werden (siehe unten ).
** `backup_after_install` +
('true'/'false') Default = 'true'. Nach der Installation wird sofort eine Imagesicherung der Installation durchgeführt.

[[opsi-manual-localimage-components-backuprestore]]
==== Netboot Produkte zum Backup und Restore

* `opsi-local-image-backup` +
Diese Produkt sichert das aktuell auf Partition 1 installierte Betriebssystem in einer Imagedatei auf Partition 3. Als Image Namen wird der im Property gesetzte Name verwendet. Wenn dieser leer ist, so wird der Name des opsi Netbootproduktes verwendet, welcher aktuell auf 'installed' steht (z.B. `opsi-local-image-winxp`). Dieser Name wird beim Produkt `opsi-local-image-restore` als Produktproperty 'imagefile' gesetzt, so daß ein nachfolgender Aufruf von `opsi-local-image-restore` per default genau dieses Image wiederherstellt. Dieser Name wird beim Produkt `opsi-local-image-restore` dem Produktproperty 'imagefiles_list' hinzugefügt. Damit enthält dieses Property die Liste aller verfügbaren Images. Weiterhin werden (für die Windows-Produkte) die aktuellen opsi-Produktstände zusammen mit dem Image gesichert, damit auch diese im Rahmen des restores wiederhergestellt werden können. +
Als Sicherungsmethode wird partclone verwendet. +
Properties:
** `imagefile` +
Name der zu erstellenden Imagdatei (default = leer = automatische Namenswahl)

* `opsi-local-image-restore` +
Diese Produkt spielt das im Produktproperty 'imagefile' angegebene Image wieder auf der Partition 1 ein und sorgt dafür, das es gebootet werden kann. Weiterhin werden (für die Windows-Produkte) die für das Image gesicherten opsi-Produktstände zusammen mit dem Image wiederhergestellt. +
Properties:
** `imagefile` +
Name des Images welches restored werden soll. Der wert dieses Properties wird automatisch durch das letzte Backup gesetzt. Die Liste der verfügbaren Images findet sich im Property `imagefiles_list`.
** `imagefiles_list` +
Liste der verfügbaren Images. Wird duch das Backup Produkt gepflegt.
** `method` +
Methode des Imagerestores. Mögliche Methoden sind `partclone-image-restore` und `rsync-partclone-image`. Der default ist `partclone-image-restore`. Die Methode `rsync-partclone-image` ist nur möglich wenn sich auf der Partition 1 das Betriebsystem befindet, von dem das bei `imagefile` angegebene Image erstellt wurde. D.h. mit dieser Methode können kleine Änderungen rückgängig gemacht werden aber es kann kein Wechsel zwischen Betriebssystemen durchgeführt werden.
** `update_and_backup` +
('true'/'false') Default = 'false'. Bei 'true' wird nach dem restore dafür gesorgt das alle Localboot Produkte die auf dem Server im einer abweichenden Version vorhanden sind auf Setup gestellt werden und das Produkt `opsi-local-image-backup-starter` auf `once` gesetzt wird. Dies führt dazu, das alle Vorhandenen Update eingespielt und nach den Updates automatisch wieder eine Sicherung durchgeführt wird.

* `opsi-local-image-delete` +
Diese Produkt löscht das im Produktproperty 'imagefile' angegebene Image von der Backup Partition +
** `imagefile` +
Name des zu löschenden Images (default = leer = Fehler)

[[opsi-manual-localimage-components-helper]]
==== Localboot Produkt zur Ablaufsteuerung

* `opsi-local-image-backup-starter` +
Dieses Localbootprodukt stellt das Netbootprodukt `opsi-local-image-backup` aus 'setup' und rebootet den Rechner dann. Diese Produkt hat eine sehr niedrige 'Priorität' von -98. Dies bedeutet das alle 'normalen' Localboot Produkte vorher abgearbeitet werden. Dies kann zu folgendem genutzt werden: +
Wird für einen Rechner folgende Produkte auf setup gestellt: +
* `opsi-local-image-restore`
* Alle Localboot Produkte die nicht mehr aktuell sind
* `opsi-local-image-backup-starter`

so führt dies zu folgendem Ablauf: +
. Restore des Images
. Update des restoreten Betriebssystems
. Backup des upgedateten Betriebssystems

[[opsi-manual-localimage-service-methods]]
=== Erweiterte opsi Service Methoden

Im Rahmen dieser Erweiterung können die Rechner eines Schulungsraums in einer opsi-client Gruppe zusammengefasst werden. Um möglichst komfortable Aktionen für alle Rechner eines Schulungsraums auszulösen sind folgende Erweiterungen der opsi-service Methoden vorgesehen:

* `setProductActionRequest4Group` +
Parameter: `productId actionRequest groupId` +
Ermöglicht für alle Mitglieder einer Gruppe (z.B. Rechner eines Schulungsraums) eine bestimmte Aktion zu starten (z.B. Retstore des Images).

* `setProductProperty4Group` +
Parameter: `productId propertyId propertyValue groupId` +
Ermöglicht für alle Mitglieder einer Gruppe (z.B. Rechner eines Schulungsraums) für ein betimmtes Produkt einen Propertywert zusetzen (z.B. welches Image restored werden soll).

* `getPossibleImagefileValuse4group` +
Parameter: `groupId` +
Liefert die Liste der Imagefile Namen welche das `opsi-local-image-backup` auf allen Mitgliedern der Gruppe angelegt hat. Wenn ein bestimmtes Image (z.B. `opsi-local-image-winxp`) auf einem oder mehreren Rechnern nicht vorhanden ist, so ist es nicht Bestandteil der Rückgabeliste.


[[opsi-manual-localimage-proceedings]]
=== Abläufe

[[opsi-manual-localimage-proceedings-initial]]
==== Initiale Installation

Über das Produkt `opsi-local-image-repartition` wird zunächst die notwendige statische Partitionierung erzeugt.

Anschließend können über die Produkte `opsi-local-image-winxp`, `opsi-local-image-win7`, `opsi-local-image-win7-x64`und `opsi-local-image-ubuntu32` verschiedene Betriebssysteme mit unterschiedlicher Ausstattung an Anwendungssoftware installiert werden. Diese werden per default nach Ihrer Installation automatisch als Image gesichert.

[[opsi-manual-localimage-proceedings-restore]]
==== Restore eines Images

Der einfache Aufruf des Produktes `opsi-local-image-restore` stellt automatisch das letzte erstellte Image wieder her. Soll ein anderes Image wieder hergestellt werden, so muß dies im Property `imagefile` angegeben werden.

[[opsi-manual-localimage-proceedings-update]]
==== Update eines Images

Durch den Aufruf des Produktes `opsi-local-image-restore` mit der Propertyeinstellung `update_and_backup` = 'true' wird das angegebene Image restored, alle Anwendungssoftware upgedated (soweit Updates auf dem Server vorhanden) und anschließend automatisch wieder eine Sicherung durch geführt.

[[opsi-manual-localimage-proceedings-delete]]
==== Löschen eines Images

Durch den Aufruf des Produktes `opsi-local-image-delete` wird das im Property `imagefile` angegebene Image gelöscht.



[[opsi-manual-localimage-backuppartition]]
=== Backuppartition

Die Backuppartion ist die dritte Partition der 1. Festplatte. +
Dort finden sich:
* Die Datei `master.log` mit Informationen über alle durchgeführten Image Operationen. Diese Logdatei wird in die bootimage logs übernommen.
* Die Image Verzeichnisse +
Die Imageverzeichnisse haben den selben Namen wie das Image und enthalten neben dem Image noch die Metadaten den Images. +
Zur Orientierung hier Beispielhaft die Größen von unterschiedlichen Imageverzeichnissen mit OS und Standardsoftware (Libreoffice, Adobereader, firefox, thunderbird, javavm, flashplayer): 
* `opsi-local-image-ubuntu32`: 3.6G
* `opsi-local-image-winxp`: 6.4G
* `opsi-local-image-win7`: 9.4G
* `opsi-local-image-win7-x64`: 13G




[[opsi-manual-localimage-ubuntumirror]]
=== Erstellen eines eigenen Ubuntu 'Proxy'
Eine brauchbare Anleitung zur Erstellung eines eigenen Ubuntu Proxy finden Sie hier:

http://wiki.ubuntuusers.de/Lokale_Paketquellen/Apt-Cacher-ng

http://www.gambaru.de/blog/2011/10/26/apt-cacher-ng-ein-proxy-server-fur-debian-und-ubuntu/










