////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      27.01.2014
:Revision:  4.0.4
:toclevels: 6


include::../common/opsi_terms.asciidoc[]

[[opsi-manual-uefi]]
== opsi mit UEFI / GPT


[[opsi-manual-uefi-preconditions]]
=== Vorbedingungen für das Arbeiten mit UEFI / GPT

Dieses Modul ist momentan eine
http://www.uib.de/www/kofinanziert/index.html[kofinanzierte opsi Erweiterung]. +
Es sind eine Reihe von Vorbedingungen nötig, um dieses Modul einsetzen
zu können. Das bedeutet, das Sie zum Einsatz eine Freischaltdatei benötigen. Diese Freischaltung erhalten Sie wenn Sie die Erweiterung kaufen. Zu Evaluierungszwecken stellen wir Ihnen auch eine zeitlich befristete Freischaltung kostenlos zur Verfügung ( -> mail an info@uib.de). +
Weitere Details hierzu finden Sie in <<opsi-manual-modules>>.

Technische Voraussetzungen sind opsi 4.0.4 mit den Paketständen:

.Benötigte Pakete
[options="header"]
|==========================
|opsi-Paket|Version
|Netbootprodukte|>=4.0.4.2
|==========================


[[opsi-manual-uefi-introduction]]
=== Einführung


[[opsi-manual-uefi-whatisuefi]]
=== Was ist Uefi

UEFI steht für 'Unified Extensible Firmware Interface' und ist der Nachfolger des klassischen PC-BIOS.

Für Detailierte Informationen zum Thema UEFI finden sich Unten einige Links.

Hier an dieser Stelle nur einige opsi relevante Anmerkungen:

* Die derzeitige (Stand Januar 2014) Umsetzung von UEFI in den BIOSen der Hardware Hersteller ist weit von dem Entfernt was man einen Standard nennen könnte. Vielmehr herrscht ein großes durcheinander wenn von einem anderen Medium geboot werden soll wie der Festplatte. UEFI und klassisches BIOS existieren teilweise Parallel, lassen sich mal einzeln deaktivieren mal nicht. UEFI ist mal mit Compatibility Support Module (CSM) implementiert mal ohne. Netboot geht oder auch nicht. +
Gerade der letzte Punkt (Netboot) ist natürlich für ein strukturiertes Client Management von großer Bedeutung.

* Im PC-BIOS ist das BIOS und dessen Einstellungen vom OS (in aller Regel) getrennt. D.h. BIOS Einstellungen wie z.B. die Bootreihenfolge sind statisch und können vom Betriebssystem nicht geändert werden. +
Dies ist bei UEFI anders. Das Betriebssystem kann die Bootreihenfolge ändern (und macht davon in der Regel auch Gebrauch). Auch dies hat wiederum Auswirkungen auf die Anbindung der Rechner an das Clientmanagement durch den Netboot. 

* UEFI verlangt ein anderes Partionierungsschema:

** 1. Partition: EFI System Partition (ESP) 100 - 260 MByte ; VFAT
** 2. Partition: Microsoft Reserved (MSR) 32 - 128 MB; NTFS
** Ab hier kommen jetzt die eigentlichen OS Partitionen

Links : 

http://de.wikipedia.org/wiki/Unified_Extensible_Firmware_Interface

[[opsi-manual-uefi-whatisgpt]]
=== Was ist GPT

GPT steht für 'GUID Partition Table' und ist der Nachfolger der  Master-Boot-Record (MBR)-Partitionstabellen.

Während die MBR-Partitionen keine Platten größer 2 TB verwalten konnten, liegt bei GPT die Grenze bei 8 Zettabyte (genauer Zebibyte 1024 * 1024 * 1024 Terabyte).
Eine MBR-Partitiontabelle kann maximal 4 primäre Partitionen verwalten, GPT 'beliebig' viele.

Links : 

http://de.wikipedia.org/wiki/GUID_Partition_Table

[[opsi-manual-uefi-relationuefigpt]]
=== Was verbindet UEFI und GPT

[[opsi-manual-uefi-relationuefios]]
=== UEFI und Betriebssysteme



