////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

////
;***************************************************************************
; Subversion:
; $Rev$ $Author$
; $Date$
;***************************************************************************
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      28.08.2015
:Revision:  4.0.6
:toclevels: 6


include::../common/opsi_terms.asciidoc[]

[[opsi-manual-linux]]
=== opsi Linux Support


include::../common/opsi_manual_supportmatrix-linclient.asciidoc[]

[[opsi-manual-linux-preconditions]]
==== Vorbedingungen für den opsi Linux Support


Technische Voraussetzungen sind opsi 4.0.5 mit den Paketständen:

.Benötigte Pakete
[options="header"]
|==========================
|opsi-Paket|Version
|opsi-linux-bootimage|>= 20140805-1
|==========================

Der opsi Support für Linux besteht aus einem Teil der von Anfang an Opensource ist (den Netbootprodukten)
und einem kofinanzierten Teil (dem Agent für die Clients).

Dieser opsi-linux-client-agent ist eine
http://uib.de/de/opsi-erweiterungen/erweiterungen/[kofinanzierte opsi Erweiterung]. +
Das bedeutet, dass Sie zum Einsatz eine Freischaltdatei benötigen. Diese Freischaltung erhalten Sie wenn Sie die Erweiterung kaufen. Zu Evaluierungszwecken stellen wir Ihnen auch eine zeitlich befristete Freischaltung kostenlos zur Verfügung ( -> mail an info@uib.de). +
Weitere Details zum Umgang mit Modulen finden Sie im opsi manual.

[[opsi-manual-linux-freestart]]
==== opsi-linux-client-agent: 15 Freistarts

Seit opsi 4.0.7 beinhaltet der opsi-linux-client-agent 15 Freistarts bei denen der Agent auch ohne Freischaltung verwendet werden kann.

Genauer formuliert: Nach der initalen Installation des opsi-linux-client-agent kann der der opsi-script 15 mal im Servicekontext gestartet werden ohne eine Freischaltung zu fordern. +
Dies gibt Ihnen die Möglichkeit einen Linuxrechner aufzusetzen und mit den entsprechenden opsi-Produkten für den geplanten Einsatz zu konfigurieren.
Beispielsweise können Sie nach der Installation das Produkt `l-opsi-server` aufrufen um aus dem frisch installierten Rechner einen opsi-server zu machen.

Für eine dauerhafte Pflege des installierten Linuxrechners über diese 15 Freistarts hinaus benötigen Sie aber eine Freischaltung dieses Features.

[[opsi-manual-linux-getit]]
==== Einspielen der Produkte

Die Linux bezogenen Localboot und Netbootproukte können über den opsi-product-updater geladen werden. +
Dazu muss sichergestellt sein, dass in der `/etc/opsi/opsi-product-updater.conf` auch die entsprechenden Verzeichnisse eingetragen sind. Am einfachsten ist es, wenn sich folgende Sektion in der Konfigurationsdatei findet: +
[source,ini]
----
[repository_uib_linux]
active = true
baseUrl = http://download.uib.de
dirs = opsi4.0/products/opsi-linux
autoInstall = false
autoUpdate = true
autoSetup = false
; Set Proxy handler like: http://10.10.10.1:8080
proxy =
----

Dann können Sie mit dem folgenden Aufruf die opsi-linux Produkte einspielen:
[source,prompt]
----
opsi-product-updater -i -vv
----

[[opsi-manual-linux-introduction]]
==== Einführung

*Ein Management-Werkzeug für Windows und Linux*

Ziel der Erweiterung von opsi um die Unterstützung von Linux-Systemen ist die Schaffung eines Managementsystems für heterogene Umgebungen. Der Fokus liegt dabei auf der möglichst vollständigen Integration beider Welten in die gleichen Management-Vorgänge und Werkzeuge.

Dies bedeutet, dass eine Linux-Installation auf die gleiche Weise angestoßen wird wie eine Windows-Installation. +
Der opsi-client-agent unter Linux basiert auf dem selben Code wie der unter Windows und ist (soweit sinnvoll) befehlskompatibel.

*Linux-Distributionsübergreifend*

Der Linux-Support von opsi ist distributionsübergreifend angelegt. +
Die folgenden Distributionen werden gleichwertig unterstützt:

* Debian
* Ubuntu
* OpenSuse / SLES (Suse Linux Enterprise Server)
* RHEL (RedHat Enterprise Linux)
* CentOS
* UCS


[[opsi-manual-linux-netboot-v406]]
==== Linux Netboot Produkte v4.0.6 auf Basis des Distributionseigenen Installers

Bei den mit opsi v4.0.5 veröffentlichten Linux-Netboot-Produkte wurden die Installationen des gewählten Betriebssystems weitgehend vom Netboot-Produkt gesteuert.
Die entsprechenden Produkte setzen ab v4.0.6 auf den distributionseigenen Installer.

Dies ist ein grundsätzlicher Umbau, der dazu führt, das sowohl Aufbau als auch Verhalten der Produkte unterschiedlich zu den bisherigen Produkten sind. +
Hier eine Übersicht:

* Ähnlich wie bei der Windows-Installation wird für den Installer eine Antwortdatei bereit gestellt, welche vom Installer zur nichtinteraktiven Installation genutzt wird.

* Der distributionseigene Installer ist nicht wie bei Windows ein Programm das aufgerufen wird, sondern in einer Kombination aus distributionseigenem Kernel und initrd implementiert.

* Die gesamte Grundinstallation - inklusive Partitionierung, LVM, Basissoftware, etc. - liegt in der Hand des Installers und wird nicht mehr durch das bootimage durchgeführt.

* Bei den Suse- und RedHat-artigen Distributionen werden die Installationsquellen von Ihnen bereitgestellt, in dem Sie die Installations-DVD als ISO-Datei auf dem Depotshare ablegen. Dieses Verfahren ähnelt der Situation unter Windows, nur dass der Ablageort ein anderer ist und dass Sie bei Windows den Inhalt der Installations-DVD ablegen anstatt einer ISO-Datei.

* Bei den Debian-artigen werden die Installationsquellen aus dem Netz verwendet. Auf dem Depotshare liegen nur die Netboot Versionen von Distributionskernel und dazugehörigem initrd. Da diese Dateien nicht groß sind, werden sie im opsi-Paket mitgeliefert. +
Ab opsi 4.0.7 können für bestimmte Netbootprodukte hier auch lokale http Repositories bereit gestellt werden.

* Zur weiteren Pflege der Installation kann der opsi-linux-client-agent im Rahmen der Basisinstalltion mit installiert werden.

Abläufe der neuen Installationsmimik:

. Das opsi-linux-bootimage wird gebootet, löscht die Partitionstabelle und erstellt eine kleine temporäre Hilfsparition.

. Das opsi-linux-bootimage holt sich das distributionseigene initrd und entpackt es auf der Hilfspartition.

. Das opsi-linux-bootimage holt sich die generische Vorlage für die Antwortdatei, patcht (personalisiert) diese und legt sie dann in das initrd Verzeichnis.

. Das opsi-linux-bootimage erstellt weitere Hilfscripte und Konfigurationsdateien (z.B. zur Installation des opsi-linux-client-agent) und legt sie dann in das initrd Verzeichnis.

. Das opsi-linux-bootimage packt das gepatchte initrd Verzeichnis wieder zusammen.

. Das opsi-linux-bootimage bootet den Distributions-Kernel mit dem gepatchten initrd per kexec.

. Das so geladene System installiert das Zielsystem unattended und installiert abschließend den opsi-linux-client-agent.

Die Vorteile dieses Vorgehens sind:

* Die Installation findet exakt gemäß den Anforderungen des Distributors statt. Dies ist immer ein Vorteil, aber natürlich im Unternehmensumfeld als Ausgangsbedingung für Supportverträge besonders wichtig.

* Die Integration neuer Releases in opsi wird einfacher und dadurch schneller.

* Bei den Suse- und RedHat-artigen Distributionen findet die Installation aus auf dem opsi-Server liegenden Installationsquellen statt und ist damit schneller und unempfindlicher gegen Störungen als beim Zugriff auf Repositories aus dem Internet.

Es ergeben sich aber auch folgende Nachteile:

* Im Moment noch keine Unterstützung für UEFI-Rechner. Die Informationen über die UEFI-Umgebung gehen aktuell beim Boot per kexec verloren. Wir hoffen, dass wir dieses Problem in Zukunft mit einem neueren Bootimage beheben können.

[[opsi-manual-linux-netboot-v406-prepare]]
===== Bereitstellung und der Installationsmedien auf dem Server

Die Bereitstellung der Installationsmedien für die Suse- und RedHat-artigen Distributionen erfolgt auf einem nfs share: `opsi_nfs_share`.

Zur Einrichtung des shares muß ein NFS-Server auf dem opsi-server installiert und konfiguriert sein.

Seit opsi v4.0.6 wird dies über ein gesondertes Paket `opsi-linux-support` erfolgen. Dieses Paket wird nicht per default installiert und muss einmalig nachinstalliert werden.

Auf Debian-artigen Betriebssystemen kann das durch den folgenden Befehl erreicht werden:

[source,prompt]
----
apt-get install opsi-linux-support
----

Beim Einsatz einer Firewall auf Ihrem Server muss diese noch so konfiguriert
werden, dass TCP-Verbindungen auf Port 80 akzeptiert werden.
Bitte konsultieren Sie hierzu das entsprechende Handbuch.

Was dieses Paket macht ist (als händige Anleitung) im folgenden Beschrieben:

* Auf dem opsi-server muß das entsprechende NFS-Server-Paket installiert sein. Auf Debian, Ubuntu, Suse ist dies das Paket: `nfs-kernel-server`. Auf Centos, Redhat ist es das Paket `nfs-utils`.

* Der Export `opsi_nfs_share` muß angelegt und exportiert werden:

** Verzeichnis erzeugen: +
`mkdir -p /var/lib/opsi/depot/opsi_nfs_share`

** In der Datei `/etc/exports` den Eintrag: +
`/var/lib/opsi/depot/opsi_nfs_share *(ro,no_root_squash,insecure,async,subtree_check)` +
erzeugen.

** Das Aktivieren des Exports wird mit dem folgenden Befehl ausgelöst: +
`exportfs -r`

** Zur Kontrolle des erfolgreichen Exports den folgenden Befehl aufrufen: +
`showmount -e localhost` +
Die Ausgabe sollte sein: +
`Export list for localhost: +
/var/lib/opsi/depot/opsi_nfs_share *`

* Der share `opsi_nfs_share` hat folgenden Verzeichnisaufbau: +
`opsi_nfs_share/<productId>/<arch>/<dvd>.iso` +
zum Beispiel: +
`opsi_nfs_share/opensuse13-2/64/openSUSE-13.2-DVD-x86_64.iso` +
Die Installationsdatei muß als Dateiendung `.iso` haben, der Rest ist egal. Liegen in einem Verzeichnis mehrere `.iso` Dateien so ist nicht definiert welche verwendet wird.

* Kopieren Sie die Installations-DVD an den entsprechenden Platz im `opsi_nfs_share` und führen Sie aus: +
`opsi-set-rights /var/lib/opsi/depot/opsi_nfs_share` +
WICHTIG: Verwenden Sie die Standard Installations-DVD's der Distribution. Modifizierte Installations DVD's haben eventuell einen anderen Aufbau und funktionieren nicht.

* Sollten Sie aus irgendwelchen Gründen das Verzeichnis `/var/lib/opsi/depot/opsi_nfs_share` nicht vom opsi-server aus per NFS exportieren können (z.B. weil der Depotshare vom opsiserver per NFS von einem NAS eingebunden ist), so kann der zu verwendende NFS-share über ein Serverweites config angegeben werden. Z.B. `clientconfig.opsi_nfs_share=172.16.166.1:/var/lib/opsi/depot/opsi_nfs_share`

Die opsi v4.0.6 Netbootprodukte für Debian und Ubuntu beziehen Ihre Installations-Dateien nicht aus einem ISO-File. Vielmehr werden diese von uns mit dem Standard Netboot-Kernel und initrd ausgeliefert. Alle weiteren benötigten Pakete werden über das Internet bezogen. Zur Entlastung Ihrer Netzwekverbindung kann bei vielen Installationen daher die Verwendung eines lokalen apt-cache sinnvoll sein. +
Die Pakete debian8 und ubuntu16-04 können auch auf ein lokales http-Repository zugreifen. +
Siehe auch Kapitel <<opsi-manual-linux-debproxy>>

Siehe auch Kapitel <<opsi-manual-linux-netboot-v406-local-http-deb-repo>>

[NOTE]
.Startreihenfolge beteiligter Dienste unter SLES 11
===================================================

Es kann vorkommen, dass der `showmount`-Befehl mit einer Fehlermeldung wie nachfolgend abbricht:

[source,prompt]
----
# showmount -e localhost
clnt_create: RPC: Program not registered
----

Bitte stellen Sie sicher, dass nach der Installation des NFS-Servers ein
Neustart stattgefunden hat.
Anschließend müssen die Dienste 'rpcbind' und 'nfsserver' in genau dieser Reihenfolge gestartet werden.

Ein Neustart der Dienste kann wie folgt durchgeführt werden:
[source,prompt]
----
# service rpcbind restart
# service nfsserver restart
----

Anschließend liefert showmount das gewünschte Ergebnis:

[source,prompt]
----
# showmount -e localhost
Export list for localhost:
/var/lib/opsi/depot/opsi_nfs_share *
----

===================================================

[[opsi-manual-linux-netboot-v406-generalproperties]]
===== Allgemeine Properties der opsi v4.0.6 Linux Netboot Produkte

Die folgenden Properties finden Sie zur Steuerung der Linuxinstallation in allen v406 Netbootprodukten:

* `askbeforeinst`: +
Soll das Starten der Installation am Client bestätigt werden müssen?  (Default='true')

* `architecture`: +
Mit welcher Architektur soll das Zielsystem installiert werden? +
Beeinflusst außerdem das verwendete Bootimage.  (Default='64bit')

* `language` oder `locale`: +
Welche Sprache / locale soll installiert werden.  (Default=Distributionsabhängig / 'de')

* `console_keymap`: +
Zu installierendes Tastaturlayout.  (Default=Distributionsabhängig / 'de')

* `timezone`: +
Welche Zeitzone soll verwendet werden?. (Default='Europe/Berlin')

* `root_password`: +
Passwort für root.  (Default='linux123')

* `user_password`: +
Passwort für user.  (Default='linux123')

* `proxy`: +
Proxystring (wenn benötigt) in der Form: `http://<ip>:<port>`. (Default=pass:[''])

* `install_opsi-client-agent`: +
Installiere den opsi-client-agent für Linux (Kofinanzierungsprojekt: Sie benötigen eine Aktivierung durch die /etc/opsi/modules). (Default='true')

* `setup_after_install`: +
Welche opsi-Produkte sollen zum Abschluss der Betriebssysteminstallation auf *setup* gestellt werden. (Default='')


[[opsi-manual-linux-netboot-v406-special-ubuntu14-04]]
===== Die Produkte: debian7 , debian8 und ubuntu14-04, ubuntu16-04

Die Basis-Installation erfolgt direkt aus dem Netz. Bei debian8 und ubuntu16-04 ist auch eine Installation von einem lokalen Repository möglich.

Das Produkt hat produktiven Status.

Das Produkt hat folgende zusätzliche Properties:

* `online_repository`: +
Repository der Distribution für die Installation. (Nur bei Debian/Ubuntu Produkten) (Default=Distributionsabhängig)

* `encrypt_password`: +
Passwort für die Festplattenverschlüsselung (nur verwendet wenn encrypt_logical_volumes=true) +
Example: `linux123` Default: `linux123`

* `partition_disk`: +
Zu verwendende Festplatte: `first` oder kompletter device path
Examples: "first", "/dev/sda", "/dev/sdb" +
Default: `first`

* `partition_method`: +
Methode zur Partitionierung der Festplatte: +
`regular`: Standard Partionierung / `lvm`: LVM's anlegen / `crypto`: In einer verschlüsselten Partition LVM's anlegen
Possible: "regular", "lvm", "crypto" +
Default: `lvm`

* `partition_recipe`: +
Die Art der verwendeten Partitionierung: +
`atomic`: Alles in einer Partition / `home`: eigene /home Partition / `multi`: eigene /home, /usr, /var, und /tmp Partitionen
Possible: "atomic", "home", "multi" +
Default: `atomic`


* `desktop_package`: +
Zu installierendes desktop package (standard = kein desktop)
Possible: "standard", "ubuntu-desktop", "kubuntu-desktop", "lubuntu-desktop", "xubuntu-desktop", "ubuntu-gnome-desktop" +
Default: `standard`


* `language_packs`: +
Possible: "ar", "bg", "by", "cf", "de", "dk", "en", "es", "et", "fa", "fi", "fr", "gr", "il", "it", "kg", "kk", "lt", "mk", "nl", "no", "pl", "ro", "ru", "sg","sr", "ua", "uk", "us", "wo" +
Default: `de`


.Videos (Zeitraffer)

Folgende Videos zeigen jeweils eine Installation. +
Sie sind mit einem Frame pro Sekunde aufgenommen und dadurch schneller anzusehen als die Installation eigentlich dauert.

* http://download.uib.de/press-infos/videos/opsi-linux/debian7_406_1fps.mp4

* http://download.uib.de/press-infos/videos/opsi-linux/debian8_406_1fps.mp4

* http://download.uib.de/press-infos/videos/opsi-linux/ubuntu14-04_406_1fps.mp4

[[opsi-manual-linux-netboot-v407-special-ucs41]]
===== Das Produkt ucs41 und ucs420

Die Basis-Installation bezieht ihre Pakete von den offiziellen UCS Repositories. Eine Installation mit lokalen Paketquellen ist ebenfalls möglich.

Dieses produkt hat einen produktiven Status.

Mit diesem Produkt ist es möglich einen Master-, Slave-, Backup, und einen Member-Server zu installieren.
Wir empfehlen das l-opsi-server Produkt um aus einer UCS Maschine auch einen opsi-Server zu machen.
Dieses Produkt ermöglicht es auch Clients über einen Member-Server zu installieren, hierfür werden einige Besonderheiten durchgeführt.

Das Produkt hat über die oben genannten Properties eines z.B debian8 Produktes noch die folgenden zusätzlichen UCS spezifischen Properties:

* `dns_domain`: +
Der DNS Domain Name: +
Example: `example.com` Default: `ucs.test`

* `ldap_base`: +
ldap base. 
Example: `dc=example,dc=com` Default: `dc=ucs,dc=test`

* `ucs_code_name`: +
Der Codename der UCS-Version welche im onlien Repository bereit gestellt wird. +
Example: `ucs414` Default: `ucs414`

* `organisation`: +
Der Name der Organisation der bei der UCS Installation verwendet wird. +
Example: `uib gmbh` Default: `uib gmbh`

* `windomain`: +
Der Name der Samba/Windows Domain. +
Example: `MYDOMAIN` Default: `MYDOMAIN`

* `external_nameserver`: +
Welcher externe Nameserver soll bei der Installation verwendet werden ? +
Example: `10.11.12.13` Default: `auto` = the name server given by dhcp

* `ucs_master_ip`: +
Die IP-Nummer des UCS Domain Controller (wird beim joinen von anderen Rollen verwendet) ? +
Example: `10.10.10.10` Default: `10.10.10.10`

* `ucs_master_admin_password`: +
Das Administrator Passwort des UCS Domain Controller (wird beim joinen von anderen Rollen verwendet) ? +
Example: `linux123` Default: `linux123`

* `ucs_role`: +
Welche UCS Rolle soll installiert werden ? +
Possible: "domaincontroller_master", "domaincontroller_backup", "domaincontroller_slave", "memberserver", "base" +
Default: `domaincontroller_master`


[[opsi-manual-linux-netboot-v406-local-http-deb-repo]]
===== Einrichtung eines lokalen deb http Repository

Mit dem debian8, ubuntu16-04 und ucs41 Paket ist es nun möglich von einem lokalen Apache2 Repository zu installieren. +
Dazu müssen bei dem Produkt im Property 'online_repository' die entsprechende Adresse angeben nach dem Muster `http://<opsi-server>/opsi/<productId>` z.B `http://opsiserver/opsi/debian8` +
Weiterhin muss das lokale Repository natürlich erstellt werden. +
Stellen Sie dazu sicher, dass das Produkt `opsi-linux-support` auf Ihrem opsi-server installiert ist. Dieses Paket installiert die
hierfür benötigten Distributions-Pakete (apache2) und erstellt auch die benötigten Ordner. Dieser muss danach mit einem passenden distributions Repository gefüllt werden. +
Hierfür gibt es zwei Möglichkeiten:

. Einfach: Sie laden sich ein von uns gebautes und getestetes Repository herunter und packen aus
. Aufwendiger: Sie bauen es sich selbst.


Einfach: +
Führen Sie das nachfolgende Script als 'root' aus. +
Beachten Sie das der Pfad zum Apache2 `DocumentRoot` zum einen Distributiontypisch unterschiedliche Defaults hat und darüberhinaus abweichend vom Default konfiguriert sein kann. +
Daher müssen Sie evtl. die zweite Zeile des Scriptes anpassen !

===== debian8

[source,prompt]
----
#! /bin/bash
DOCUMENTROOT=/var/www/html
URL=http://download.uib.de/opsi4.0/products/opsi-linux
FILE=debian8.tgz
mkdir -p ${DOCUMENTROOT}/opsi
cd ${DOCUMENTROOT}/opsi
wget ${URL}/${FILE}
tar xzf ${FILE}
opsi-set-rights .
----


===== ubuntu16-04

[source,prompt]
----
#! /bin/bash
DOCUMENTROOT=/var/www/html
URL=http://download.uib.de/opsi4.0/products/opsi-linux
FILE=ubuntu16-04.tgz
mkdir -p ${DOCUMENTROOT}/opsi
cd ${DOCUMENTROOT}/opsi
wget ${URL}/${FILE}
tar xzf ${FILE}
opsi-set-rights .
----

===== ucs41

[source,prompt]
----
#! /bin/bash
DOCUMENTROOT=/var/www/html
URL=http://download.uib.de/opsi4.0/products/opsi-linux/univention-repository/
FILE=univention-repository-4.1.tgz
mkdir -p ${DOCUMENTROOT}/opsi
cd ${DOCUMENTROOT}/opsi
wget ${URL}/${FILE}
tar xzf ${FILE}
opsi-set-rights .
----

Bitte beachten Sie die Datei: +
http://download.uib.de/opsi4.0/products/opsi-linux/univention-repository/opsi-ucs-repository-readme.txt

Aufwendiger: +
Sie können das Repository auch selbst erstellen:


[source,prompt]
----
#! /bin/bash
set -x
BASE_DIR=/var/www/opsi
DVD_PATH=UCSISOMOUNTPOINT
UCS_VERSION=4.1
UCS_SUBVERSION=4
UCS_REPODIR=univention-repository/mirror
UCS_REPODIR2=${UCS_VERSION}/maintained/${UCS_VERSION}-${UCS_SUBVERSION}
UCS_RELEASE_PATH=dists/ucs414/main/binary-amd64/Release

cd ${BASE_DIR}
mkdir -p ${UCS_REPODIR}
cd ${UCS_REPODIR}
pwd
ln -s . univention-repository
mkdir -p ${UCS_REPODIR2}
cd ${UCS_REPODIR2}
pwd
cp -r ${DVD_PATH}/all .
cp -r ${DVD_PATH}/amd64 .
cp -r ${DVD_PATH}/dists .
mkdir -p i386
cd all
dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
dpkg-scanpackages . /dev/null > Packages.gz
cd ..
cd amd64
dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
dpkg-scanpackages . /dev/null > Packages.gz
cd ..
cd i386
dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
dpkg-scanpackages . /dev/null > Packages.gz
cd ..
echo "Archive: stable" > ${UCS_RELEASE_PATH}
echo "Origin: Univention" >> ${UCS_RELEASE_PATH}
echo "Label: Univention" >> ${UCS_RELEASE_PATH}
echo "Version: ${UCS_VERSION}.${UCS_SUBVERSION}" >> ${UCS_RELEASE_PATH}
echo "Component: main" >> ${UCS_RELEASE_PATH}
echo "Architecture: amd64" >> ${UCS_RELEASE_PATH}
cat  ${UCS_RELEASE_PATH}
cd ${BASE_DIR}
chown -R www-data:www-data univention-repository
echo "all done"
----


[[opsi-manual-linux-netboot-v406-special-opensuse13-02]]
===== Das Produkt opensuse13-2

Das Produkt hat folgende zusätzliche Properties:

----
name: install_unattended
description: If false then do interactive installation
default: True
----

Das Property:
----
name: networkdevice
multivalue: False
editable: True
description: interface to conigure (vbox:enp0s3 / esxi:ens32)
values: ["eno1", "ens1", "ens32", "enp0s1","enp0s2","enp0s3"]
default: ["enp0s3"]
----
existiert nur aus Gründen der Rückwärtskompatibilität zu alten bootimages
und wird bei dem Betrieb mit einem aktuellen bootimage ( >= 20150818) ignoriert,
da hier die automatische Erkennung der 'predictable network interface names' funktioniert.

.Installationsquelle
Installations DVD hier herunterladen:
http://download.opensuse.org/distribution/13.2/iso/openSUSE-13.2-DVD-x86_64.iso
ISO-File kopieren nach `/var/lib/opsi/depot/opsi_nfs_share/opensuse13-02/64/`
Ausführung von `opsi-set-rights` nicht vergessen.

.Videos (Zeitraffer)

Folgendes Video zeigt eine Installation. +
Es ist mit einem Frame pro Sekunde aufgenommen und dadurch schneller anzusehen als die Installation eigentlich dauert.

[[opsi-manual-linux-netboot-v406-special-opensusel42-1]]
===== Das Produkt opensusel42-1

Das Produkt hat folgende zusätzliche Properties:

----
name: install_unattended
description: If false then do interactive installation
default: True
----

.Installationsquelle
Installations DVD hier herunterladen:
http://download.opensuse.org/distribution/leap/42.2/iso/openSUSE-Leap-42.2-DVD-x86_64.iso
ISO-File kopieren nach `/var/lib/opsi/depot/opsi_nfs_share/opensusel42-2/64/`
Ausführung von `opsi-set-rights` nicht vergessen.

[[opsi-manual-linux-netboot-v406-special-sles]]
===== Die Produkte sles11sp4, sles12, sles12sp1

Das Produkt hat folgende zusätzliche Properties:

----
name: productkey
multivalue: False
editable: True
description: email:regcode-sles for suse_register. Is only used if the  host parameter  `license-management.use` is set to  false . If it set to  True  the license key will be get from the license management module. / La clé de licence pour l'installation. Est utilisée uniquement si dans "Réseau et paramètres supplémentaires" `license-management.use` est défini à false (faux) . Si c'est réglé sur True (vrai) la clé de licence sera obtenue du module de gestion des licences.
values: ["", "myemail@example.com:xxxxxxxxxxxxxx"]
default: [""]

name: suse_register
description: set to false, if you don't want to register your system online, if you set this to false you have to give local repositories
default: True

name: local_repositories
multivalue: True
editable: True
description: list of local repositories to use. Syntax: "repository description", example entry: "http://sles.example.com/suse/repo NameForRepo"
values: [""]
default: [""]

name: install_unattended
description: If false then do interactive installation
default: True
----

.Installationsquelle
Zum herunterladen der Installations DVD brauchen Sie einen Account bei SUSE.
Installations DVD sollte heissen (mit einer Datei dieses Namens haben wir getestet):
sles11sp4: SLES-11-SP4-DVD-x86_64-GM-DVD1.iso
sles12: SLE-12-Server-DVD-x86_64-GM-DVD1.iso
sles12sp1: SLE-12-SP1-Server-DVD-x86_64-GM-DVD1.iso
ISO-File kopieren nach `/var/lib/opsi/depot/opsi_nfs_share/opensusel42-1/64/`
Ausführung von `opsi-set-rights` nicht vergessen.


.Videos (Zeitraffer)

Folgendes Video zeigt eine Installation. +
Es ist mit einem Frame pro Sekunde aufgenommen und dadurch schneller anzusehen als die Installation eigentlich dauert.

http://download.uib.de/press-infos/videos/opsi-linux/sles12_406_1fps.mp4


[[opsi-manual-linux-netboot-v406-special-redhat70]]
===== Die Produkte redhat70 und centos70

Das Produkt hat folgende zusätzliche Properties:

----
name: install_unattended
description: If false then do interactive installation
default: True

name: selinux_mode
multivalue: False
editable: False
description: In which mode should SELinux run ?
values: ["enforcing", "permissive", "disabled"]
default: ["permissive"]

name: partition_method
multivalue: False
editable: False
description: plain: Regular partitions with no LVM or Btrfs. / lvm: The LVM partitioning scheme. / btrfs: The Btrfs partitioning scheme. / thinp: The LVM Thin Provisioning partitioning scheme.
values: ["plain", "lvm", "btrfs", "thinp"]
default: ["lvm"]

name: productkey
multivalue: False
editable: True
description: email:regcode for subscription_register. Is only used if the  host parameter  `license-management.use` is set to  false . If it set to  True  the license key will be get from the license management module. / La clé de licence pour l'installation. Est utilisée uniquement si dans "Réseau et paramètres supplémentaires" `license-management.use` est défini à false (faux) . Si c'est réglé sur True (vrai) la clé de licence sera obtenue du module de gestion des licences.
values: ["", "myemail@example.com:xxxxxxxxxxxxxx"]
default: [""]

name: subscription_register
description: set to false, if you don't want to register your system online, if you set this to false you have to give local repositories
default: True
----

.Installationsquelle CentOS
Installations DVD hier herunterladen:
z.B.: +
http://isoredirect.centos.org/centos/7/isos/x86_64/CentOS-7-x86_64-DVD-1511.iso
ISO-File kopieren nach `/var/lib/opsi/depot/opsi_nfs_share/centos70/64/`
Ausführung von `opsi-set-rights` nicht vergessen.

.Installationsquelle RedHat
Zum herunterladen der Installations DVD brauchen Sie einen Account bei RedHat.
Installations DVD sollte heissen (mit einer Datei dieses Namens haben wir getestet): +
rhel-server-7.0-x86_64-dvd.iso
ISO-File kopieren nach `/var/lib/opsi/depot/opsi_nfs_share/redhat70/64/`
Ausführung von `opsi-set-rights` nicht vergessen.


.Videos (Zeitraffer)

Folgende Videos zeigen eine Installation. +
Sie sind mit einem Frame pro Sekunde aufgenommen und dadurch schneller anzusehen als die Installation eigentlich dauert.

* http://download.uib.de/press-infos/videos/opsi-linux/centos70_406_1fps.mp4

* http://download.uib.de/press-infos/videos/opsi-linux/redhat70_406_1fps.mp4



[[opsi-manual-linux-netboot-405]]
==== Linux Netboot Produkte v4.0.5 ohne Distributionseigenen Installer

*Basis-Installation des OS per Netboot*

Für die Installation eines Linux Basissystems wird zunächst per Netboot das Standard opsi-linux-bootimage gebootet (welches auch für die Windows-Installationen zum Einsatz kommt). +
Von diesem Bootimage aus wird die Ziel-Festplatte partitioniert (/ und swap) und formatiert. Nun folgt die Installation des Grundsystems (mit Netzwerkkonfiguration und ssh aber ohne X11). Die Abläufe dieser Grundinstallation unterscheiden sich naturgemäß zwischen den unterschiedlichen Distributionen erheblich. Gemeinsam ist, dass die Installation direkt aus den Originalpaketen der Distribution erfolgt.

Auf diese Basisinstallation können optional die opsi-Pakete installiert werden, um aus dem System einen opsi-Server (z.B. neuen Depotserver) zu machen. +
Ebenfalls optional kann nun der opsi-client-agent für Linux installiert werden. Dieser ist dann für die Installation und Konfiguration weiterer Software zuständig.

Die opsi-Netboot-Produkte zur Linuxinstallation sind bereits als Open Source freigegeben.

Bedingt dadurch, dass die Basisinstallation aus dem Standard opsi-linux-bootimage erfolgt, gibt es distributionsabhängig unterschiedlich bestimmte Dinge, welche sich erst in der Umgebung nach dem ersten Boot des Systems konfigurieren bzw. installieren lassen. Beispiele hierfür sind die SELinux-Installation bei den 'RedHat artigen' bzw. die Konfiguration der Tastatur bei den 'Debian artigen'. Hierfür gibt es ein Standard Localbootprodukt `l-os-postinst` welches diese Aufgaben übernimmt.

[[opsi-manual-linux-netboot-generalproperties-405]]
===== Allgemeine Properties der v4.0.5 Linux Netboot Produkte

Die folgenden Properties finden Sie zur Steuerung der Linuxinstallation in allen Netbootprodukten:

* `askbeforeinst`: +
Soll das Starten der Installation am Client bestätigt werden müssen?  (Default='true')

* `architecture`: +
Mit welcher Architektur soll das Zielsystem installiert werden? +
Beeinflusst die Auswahl des bootimages und die Installationsarchitektur.  (Default='64bit')

* `system_partition_size`: +
Größe der Systempartition. Die Größe kann in Prozent der Festplattengröße oder als absoluter Wert (G=Gigabyte) angegeben werden. Wenn Sie einen kleineren Wert als 100% angeben, wird der verbleibende Rest als Datenpartition verwendet (wenn das Property data_partion_create = true).  (Default='100%')

* `swap_partition_size`: +
Größe der Swappartition.  (Default='2000M')

* `data_partition_create`: +
Verwende freien Plattenplatz zur Erstellung einer Datenpartition. (true/false).  (Default='true')

* `data_partition_preserve`: +
Soll eine existierende Datenpartition erhalten werden ? +
*always* = Installation abbrechen wenn der Erhalt einer gefundenen Partition mit dem Label 'data' mit den angegebenen Partitionierungsdaten nicht möglich ist. +
*if_possible* = Wird eine Partition mit dem Label 'data' gefunden und der Erhalt dieser Partition ist gemäß der angegebenen Partionierungsdaten nicht möglich so wird die Partition gelöscht. +
*never* = Die gesamte Partitionstabelle wird immer neu geschrieben.  (Default='never')

* `language`: +
Welche Sprache / locale soll installiert werden.  (Default='de')

* `console_keymap`: +
Zu installierendes Tastaturlayout.  (Default=Distributionsabhängig / 'de')

* `timezone`: +
Welche Zeitzone soll verwendet werden?. (Default='Europe/Berlin')

* `root_password`: +
Passwort für root.  (Default='linux123')

* `user_password`: +
Passwort für user.  (Default='linux123')

* `install_opsi_server`: +
Installiere die opsi-server Pakete. (Default='false')

* `online_repository`: +
Repository der Distribution für die Installation. (Nicht bei SLES) (Default=Distributionsabhängig)

* `opsi_online_repository`: +
Repository der opsi-server Pakete. (Default=Distributionsabhängig)

* `proxy`: +
Proxystring (wenn benötigt) in der Form: `http://<ip>:<port>`. (Default=pass:[''])

* `additional_packages`: +
Welche zusätzlichen Pakete sollen installiert werden? Angabe der Pakete Leerzeichen separiert. (Default=pass:[''])

* `wget_and_execute`: +
Url (http) einer Datei welche am Ende der Installation geholt und ausgeführt wird. (Default=pass:[''])

* `install_opsi-client-agent`: +
Installiere den Linux opsi-client-agent (Kofinanzierungsprojekt: Sie benötigen eine Aktivierung durch die /etc/opsi/modules) . (Default='false')

* `release`: +
(nur Debian und Ubuntu) +
Welches Release der Distribution soll installiert werden. (Default=Distributionsabhängig)

* `setup_after_install`: +
Welche opsi Produkte sollen zum Abschluss der Betriebssysteminstallation auf setup gestellt werden. (Default='l-os-postinst')


[[opsi-manual-linux-netboot-special-ubuntu]]
===== ubuntu

Die Basis Installation erfolgt per debootstrap direkt aus dem Netz.

Das Produkt hat produktiven Status.

Das Produkt ist UEFI/GPT kompatibel (getestet für release=trusty).

Es gibt für diese Produkt passende opsi-server Pakete welche über 'install_opsi_server=true' installiert werden können.

[[opsi-manual-linux-netboot-special-debian]]
===== debian

Die Basis Installation erfolgt per debootstrap direkt aus dem Netz.

Das Produkt hat produktiven Status.

Das Produkt ist UEFI/GPT kompatibel (getestet für release=wheezy).

Es gibt für diese Produkt passende opsi-server Pakete welche über 'install_opsi_server=true' installiert werden können.


[[opsi-manual-linux-clientagent]]
==== opsi-linux-client-agent

Der opsi-client-agent für Linux ist Bestandteil des Kofinanzierungsprojektes 'Linux Agent' und derzeit kostenpflichtig.

CAUTION: Ein Rechner kann *nicht* gleichzeitig am selben '{opsi-config-server}' Client *und* Server (z.B. '{opsi-depot}' / '{opsi-config-server}') sein. +
Dies ist ein Problem mit der derzeitigen Datenstruktur in opsi und wird zu einem späteren Zeitpunkt gelöst. +
Ein '{opsi-config-server}' kann sich also auch nicht selbst als Client haben. Es ist aber durchaus möglich einen Linuxclient als opsi-Server zu installieren der dann selber als '{opsi-config-server}' agiert oder als '{opsi-depot}' für einen anderen '{opsi-config-server}'. Wenn sie auf diese Weise einen opsi-Server aufgesetzt haben und wollen diesen als Depotserver an dem '{opsi-config-server}' registrieren an dem diese Maschine auch Client ist, müssen Sie den Rechner als Client vorher löschen.

Der opsi-client-agent für Windows besteht im Kern aus den Komponenten:

. dem Service `opsiclientd`

. dem Hilfsprogramm `opsiscriptstarter`

. dem Actionprocessor `opsi-script / opsi-script-nogui`

Der opsi-client-agent für Linux basiert auf einer Portierung des Windows-Clientagenten nach Linux.

Der `opsiclientd` ist derzeit nicht für alle unterstützten Distributionen verfügbar und ist deshalb für alle anderen Distributionen zunächst durch das Programm `opsiscriptstarter` ersetzt

Der `opsiclientd` steht auf folgenden Distributionen / Releases zur Verfügung:

* Debian 7 / 8
* Ubuntu 12.04 / 14.04 / 16.04
* openSuse 13.2 / 42.1
* SLES 12 / 12SP1
* UCS 4.0 / 4.1

Steht kein opsiclientd zur Verfügung, wird der `opsiscriptstarter` so installiert, das er die Aufgaben des `opsiclientd` beim Systemstart übernimmt:

* Kontakt mit dem opsi-Server: Prüfen ob Aktionen gesetzt sind
* Mounten des Depot Shares
* Starten des Actionprocessors
* Unmount des Depot Shares
* Senden der Logdatei an den Server

Der Actionprocessor heißt unter Linux opsi-script und ist aus den selben Quellen gebaut wie der opsi-winst unter Windows. Damit steht unter Linux die gleiche Scriptsyntax zur Verfügung wie unter Windows. Weiterhin sind alle nicht plattformspezifischen Funktionen umgesetzt wie z.B:

* File handling
* String und Stringlisten Funktionen
* Ausführen von externen Scripten und Programmen
* Kommunikation mit dem opsi-Server
* Patchen von Konfigurationsdateien

Natürlich gibt es unter Linux keine Funktionen zum Patchen der Registry, dafür aber neue linuxspezifische Funktionen wie z.B.:

* getLinuxDistroType
* getLinuxVersionMap

Das Logging des opsi-script ist analog zur dem des opsi-winst unter Windows.

Anders als bei Windows gibt es den opsi-script neben einer grafischen Version für die Arbeit unter X-Windows zusätzlich in einer Version 'no-gui' für Systeme ohne grafische Oberfläche


[[opsi-manual-linux-clientagent-installation-servicesetup]]
===== opsi-linux-client-agent: Installation: service_setup.sh

Diese Methode dient zur Installation auf einzelnen Rechnern. Für ein Massen-Rollout siehe weiter unten.

. Loggen Sie sich mit `root` Rechten auf dem Client ein.
. Mounten Sie den share `//<opsiserver>/opsi_depot` an eine beliebige Stelle.
. Wechseln Sie in das Verzeichnis `opsi-linux-client-agent` auf dem gemounteten share
. Starten Sie dort das Script `./service_setup.sh`

Das Skript nimmt per opsi-Webservice Kontakt zum Server auf um serverseitig den Client zu erzeugen und den pckey zu erfahren. Dies erfolgt zunächst mit der in der config.ini eingetragenen user/password Kombination. Schlägt dies fehl, so erscheint ein Login mit der Frage nach Service-URL, user und password. Dort kann die Operation mit dem Accountdaten eines Mitglieds der Gruppe {opsiadmin} autorisiert werden.

CAUTION: Der Client rebootet nach der Installation.


[[opsi-manual-linux-clientagent-installation-opsideploy]]
===== opsi-linux-client-agent: Installation: opsi-deploy-client-agent

Das `opsi-deploy-client-agent` Skript verteilt den opsi-client-agent direkt vom {opsi-server} auf die Clients. Voraussetzung hierfür sind bei den Clients:

* ssh Zugang als root oder als user der sudo ohne Passwort-Eingabe ausführen darf

Das Skript erzeugt serverseitig den Client, kopiert die Installations-Dateien und Konfigurationsinformationen, wie bspw. den pckey, auf den Client und startet dort die Installation.


Mit dem `opsi-deploy-client-agent` Skript kann auch eine ganze Liste von Clients bearbeitet werden.
Dazu können entweder beliebig viele Clients als letzter Parameter übergeben werden oder mit der Option '-f' die Clients aus einer Datei eingelesen werden.
Bei der Verwendung einer Datei, muss in jeder Zeile ein Client stehen.

Das Script kann mit IP-Adressen, Hostnamen und FQDNs arbeiten. Es wird versuchen automatisch zu erkennen welche Art von Adresse übergeben wurde.

Mit dem `opsi-deploy-client-agent` Skript kann auch eine ganze List von Clients bearbeitet werden. Das Skript findet sich unter '/var/lib/opsi/depot/opsi-linux-client-agent' +
Führen Sie das Script mit 'root' Rechten aus.


[source,prompt]
----
bonifax:/var/lib/opsi/depot/opsi-linux-client-agent# ./opsi-deploy-client-agent  --help
usage: opsi-deploy-client-agent [-h] [--version] [--verbose]
                                [--debug-file DEBUGFILE] [--username USERNAME]
                                [--password PASSWORD]
                                [--use-fqdn | --use-hostname | --use-ip-address]
                                [--ignore-failed-ping]
                                [--reboot | --shutdown | --start-opsiclientd]
                                [--hosts-from-file HOSTFILE]
                                [--skip-existing-clients]
                                [--threads MAXTHREADS]
                                [--keep-client-on-failure | --remove-client-on-failure]
                                [host [host ...]]

Deploy opsi client agent to the specified clients. The clients must be
accessible via SSH. The user must be allowed to use sudo non-interactive.

positional arguments:
  host                  The hosts to deploy the opsi-client-agent to.

optional arguments:
  -h, --help            show this help message and exit
  --version, -V         show program's version number and exit
  --verbose, -v         increase verbosity (can be used multiple times)
  --debug-file DEBUGFILE
                        Write debug output to given file.
  --username USERNAME, -u USERNAME
                        username for authentication (default: root). Example
                        for a domain account: -u "<DOMAIN>\\<username>"
  --password PASSWORD, -p PASSWORD
                        password for authentication
  --use-fqdn, -c        Use FQDN to connect to client.
  --use-hostname        Use hostname to connect to client.
  --use-ip-address      Use IP address to connect to client.
  --ignore-failed-ping, -x
                        try installation even if ping fails
  --reboot, -r          reboot computer after installation
  --shutdown, -s        shutdown computer after installation
  --start-opsiclientd, -o
                        start opsiclientd service after installation
  --hosts-from-file HOSTFILE, -f HOSTFILE
                        File containing list of clients (one hostname per
                        line). If there is a space followed by text after the
                        hostname this will be used as client description for
                        new clients.
  --skip-existing-clients, -S
                        skip known opsi clients
  --threads MAXTHREADS, -t MAXTHREADS
                        number of concurrent deployment threads
  --keep-client-on-failure
                        If the client was created in opsi through this script
                        it will not be removed in case of failure. (DEFAULT)
  --remove-client-on-failure
                        If the client was created in opsi through this script
                        it will be removed in case of failure.
----

[[opsi-manual-linux-clientagent-installation-netboot]]
===== opsi-linux-client-agent: Installation: Durch die opsi netbootprodukte

Wenn Sie ein Linux über die opsi-Netboot-Produkte installieren, wird der opsi-linux-client-agent automatisch mit installiert, wenn das Property `install_opsi-client-agent` auf 'true' steht.

[[opsi-manual-linux-clientagent-opsiclientd-configuration]]
===== opsi-linux-client-agent: opsiclientd Konfiguration

Der `opsiclientd` für Linux ist eine Portierung des opsiclientd für Windows und arbeitet mit einer analogen Konfigurations Datei: `/etc/opsi-client-agent/opsiclientd.conf`.

Eine ausführliche Beschreibung dieser Konfiguration findet sich im Kapitel zum opsi-client-agent: <<opsi-manual-clientagent-configuration>>

Dabei sind nicht alle Features und Events auch unter Linux verfügbar. +
Verfügbar sind:

* Start beim Systemstart (bzw. start des `opsiclientd`) unter Linux ist der Name des Events `opsiclientd_start` (und nicht `gui_startup`)

* `event_on_demand`
* Das `event_timer` aber nur mit der Einstellung: `super = default`


Nicht verfügbar sind (derzeit):

* Alles was mit dem lokalen Cache ('WAN-Erweiterung') zu tun hat.
* Die Modifikation der Events durch Preconditions
* Der opsiclientd Notifier
* Das `event_net_connection`
* Das `event_on_shutdown`
* Das `event_silent_install`

[[opsi-manual-linux-clientagent-places]]
===== opsi-linux-client-agent: Pfade

Der opsi-linux-client-agent legt Dateien an folgenden Orten ab:

Die Binaries:

`/usr/bin/opsi-script` (X11)

`/usr/bin/opsi-script-nogui` (ohne X11)

`/usr/bin/opsiscriptstarter` (Hilfsprogramm bzw. opsiclientd Ersatz)

`/usr/bin/opsiclientd`

Die Hilfsdateien für den opsi-script finden sich in:

`/usr/share/opsi-client-agent/opsi-script/skin`

`/usr/share/locale/`<LANG>`/LC_MESSAGES/opsi-script.po`

Die Konfigurationen:

`/etc/opsi-client-agent/opsiclientd.conf` (Konfiguration des opsiscriptstarter / opsiclientd)

`/etc/opsi-client-agent/opsi-script.conf` (in Vorbereitung)

Logdateien sind zu finden unter:

`/var/log/opsi-client-agent`

`/var/log/opsi-client-agent/opsiclientd`

`/var/log/opsi-client-agent/opsi-script`

[[opsi-manual-linux-clientagent-knownbugs]]
===== opsi-linux-client-agent: Known Bugs

Das Kopieren von vielen Dateien von einem Samba3-Share ist abhängig von der Samba-Version fehlerhaft. Es werden nicht alle Dateien kopiert.
Das Problem wurde bei Samba4 Shares bisher nicht beobachtet.

Als Workaround kann statt:
[source,winst]
----
[Files_copy_netboot]
copy -s "%scriptPath%/installfiles/*" "$target$/installfiles/"
----
das folgende verwendet werden:
[source,winst]
----
[ShellInAnIcon_opsi_copy_netboot]
set -x
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
cd "%scriptPath%"
tar cf - installfiles | ( cd "$target$/installfiles/" ; tar xf - )
----


[[opsi-manual-linux-scriptexample]]
==== Beispiel Scriptteile

Unter Windows gilt für die Softwareverteilung: Die Installation von Software ist genauso wichtig wie die anschließende Konfiguration der Software. +
Unter Linux stehen die meisten Pakete über die Repositories der Distribution zur Verfügung. Dadurch wird der Installationsanteil kleiner, der Konfigurationsanteil aber bleibt. Weiterhin gibt es auch Applikationen, welche nicht über die Standardrepositories verfügbar sind. +
Hier müssen unter Umständen zunächst weitere Repositories dem System hinzugefügt werden bzw. Installationsquellen dem Paket zugefügt werden. +
Wichtig ist, dass alle Installations- und Konfigurationsarbeiten zentral vom opsi-Server gesteuert und dort auch geloggt werden.

Im folgenden finden Sie Beispiele für folgende Aufgaben in einem beispielhaften Script für den opsi-linux-client-agent:

* Beenden wenn es nicht unter Linux läuft
* Feststellen des Distributionstyps zur Entscheidung zwischen `apt-get`, `zypper` und `yum`
* Feststellen der genauen Linux Version
* Installation eines Paketes
* Hinzufügen eines Repositories

Beispiel: Beenden wenn es nicht unter Linux läuft:

[source,winst]
----
[Actions]
requiredWinstVersion >= "4.11.4.1"
ScriptErrorMessages=off

DefVar $OS$

set $OS$ = GetOS

if not($OS$ = "Linux")
	LogError "Wrong OS: Product: " + $ProductId$ + " is only for Linux"
	isFatalError "Wrong OS"
endif
----

Beispiel: Feststellen des Distributionstyps:

[source,winst]
----
[Actions]
requiredWinstVersion >= "4.11.4.1"
ScriptErrorMessages=off

DefVar $distrotype$

set $distrotype$ = getLinuxDistroType

if $distrotype$ = 'debian'
	Message "Try to get Package Lock..."
	if waitForPackageLock("60","false")
		comment "we got the package lock."
	else
		LogError "could not get Package Lock"
		isFatalError "package lock failed"
	endif
	ShellInAnIcon_Upgrade_deb
else
	LogError "Wrong Distro: This Product is for Debian/Ubuntu only"
	isFatalError "Wrong distro"
endif

if not("0" = getLastExitCode)
	Message "failed ShellInAnIcon_Upgrade"
	LogError "failed ShellInAnIcon_Upgrade"
	isFatalError "failed Upgrade"
endif


[ShellInAnIcon_Upgrade_deb]
set -x
export DEBIAN_FRONTEND=noninteractive
apt-get --yes install aptitude
apt-get update
apt-get --yes dist-upgrade
exit $?
----


Beispiel: Feststellen der genauen Linux Version und Installation eines Paketes:

[source,winst]
----
[Actions]
requiredWinstVersion >= "4.11.4.1"
ScriptErrorMessages=off

DefVar $distCodeName$
DefVar $distroName$
DefVar $distRelease$
DefVar $desktop$

DefStringList $linuxInfo$

set $linuxInfo$ = getLinuxVersionMap
set $distCodeName$ = getValue("Codename", $linuxInfo$)
set $distRelease$ = getValue("Release", $linuxInfo$)
set $distroName$  = getValue("Distributor ID", $linuxInfo$)

set $desktop$ = GetProductProperty("desktop", "kde")


if $distrotype$ = 'suse'
	if $desktop$ = "unity"
		Message " No Unity on SUSE - fallback to KDE ..."
		set $desktop$ = "kde"
	endif ; unity

	Message "Try to get Package Lock..."
	if waitForPackageLock("60","false")
		comment "we got the package lock."
	else
		LogError "could not get Package Lock"
		isFatalError "package lock failed"
	endif

	if $desktop$ = "kde"
		if ($distroName$ = 'openSUSE project')
			ShellInAnIcon_kde_suse
		endif
		if ("SUSE LINUX" = $distroName$) and ($distRelease$ = "11")
			ShellInAnIcon_kde_sles11
		endif
		if not("0" = getLastExitCode)
			LogError "failed ShellInAnIcon"
			Message "failed kde"
			isFatalError "failed kde"
		endif
	endif ; kde
endif; suse type

[ShellInAnIcon_kde_suse]
set -x
zypper --no-gpg-checks --non-interactive install patterns-openSUSE-kde4 patterns-openSUSE-kde4_basis
zypper --no-gpg-checks --non-interactive install splashy-branding-openSUSE
exit $?

[ShellInAnIcon_kde_sles11]
set -x
zypper --no-gpg-checks --non-interactive install --auto-agree-with-licenses -t pattern kde
exit $?
----


Beispiel: Hinzufügen eines Repositories:
[source,winst]
----
[Actions]
requiredWinstVersion >= "4.11.4.1"
ScriptErrorMessages=off

DefVar $distCodeName$
DefVar $distroName$
DefVar $distRelease$
DefVar $desktop$

DefStringList $linuxInfo$

set $linuxInfo$ = getLinuxVersionMap
set $distCodeName$ = getValue("Codename", $linuxInfo$)
set $distRelease$ = getValue("Release", $linuxInfo$)
set $distroName$  = getValue("Distributor ID", $linuxInfo$)

set $desktop$ = GetProductProperty("desktop", "kde")


if $distroName$ = 'Ubuntu'

	if $desktop$ = "cinnamon"
		set $desktopPackage$ = $desktop$
		Message "Try to get Package Lock..."
		if waitForPackageLock("60","false")
			comment "we got the package lock."
		else
			LogError "could not get Package Lock"
			isFatalError "package lock failed"
		endif
		ShellInAnIcon_ubuntu_cinnamon
		if not("0" = getLastExitCode)
			Message "failed ShellInAnIcon_ubuntu_cinnamon"
			LogError "failed ShellInAnIcon_ubuntu_cinnamon"
			isFatalError "failed cinnamon"
		endif
	endif ; cinnamon
endif; ubuntu

[ShellInAnIcon_ubuntu_cinnamon]
set -x
export DEBIAN_FRONTEND=noninteractive
# we need to get the add-apt-repository command
apt-get --yes --force-yes install python-software-properties
# the cinnamon repository
add-apt-repository ppa:gwendal-lebihan-dev/cinnamon-stable
apt-get update
apt-get --yes install ubuntu-desktop
exit $?
----

[[opsi-manual-linux-localboot]]
==== Linux Localboot Produkte

Hier einige Lokalbootprodukte welche zum Standardumfang des opsi Linuxsupports gehören.

[[opsi-manual-linux-localboot-l-opsi-server]]
===== Das Produkt l-opsi-server

Das Produkt 'l-opsi-server' dient dazu automatisiert auf einer Linuxmaschine per opsi-linux-client-agent
einen opsi-server zu installieren. Dies kann dazu dienen um schnell einen neuen opsi-depot-server zu installieren
oder z.B. ein opsi Testsystem.

CAUTION: Derzeit kann eine Maschine nicht gleichzeitig am selben opsi-config-server
opsi-client und opsi-depot-server sein. +
Sie haben derzeit zwei Möglichkeiten mit dieser Beschränkung umzugehen: +
1. Verwendung von einem opsi-config-server: Wenn also ein per 'l-opsi-server' installierter opsi-server zum Depotserver an seinem Config-Server werden soll, so müssen Sie vorher im configed die Maschine als Client löschen. +
2. Verwendung von zwei opsi-config-servern: Sie setzen für die Verwaltung Ihrer opsi-server einen zweiten, unabhängigen
opsi-config-server auf, welcher nur dazu dient die anderen opsi-server zu installieren und zu pflegen. Dieser zweite opsi-config-server kennt die anderen opsi-server also nur als Clients, während der bisherige (erste) opsi-config-server die anderen opsi-server nur als Depots (oder garnicht) kennt. +
In UCS Umgebungen wird Methode 2 empfohlen und der zweite opsi-config-server darf keine UCS Maschine sein.

Das Produkt 'l-opsi-server' hat folgende Properties:

* `opsi_online_repository`: +
(Basis-) Repository für die opsi-server installation. +
(Default="http://download.opensuse.org/repositories/home:/uibmz:/opsi:/opsi40") +
siehe auch 'repo_kind'

* `opsi_noproxy_online_repository`: +
(Basis-) Repository für die opsi-server installation (ohne cache proxy). +
(Default="http://download.opensuse.org/repositories/home:/uibmz:/opsi:/opsi40") +
Sollten Sie bei `opsi_online_repository` einen Proxy oder deb-cacher mit angegeben haben
(z.B. 'http://mydeb-cacher:9999/download.opensuse.org/repositories/home:/uibmz:/opsi:/opsi40"),
dann geben Sie hier die URL nochmal ohne den Proxy an. Ansonsten geben Sie hier das selbe an wie bei `opsi_noproxy_online_repository`.

* `repo_kind`: +
Welche Repository Art ["experimental", "stable", "testing"] soll zur Installation verwendet werden ?. (Default='stable') +
Aus dem Client OS, 'opsi_online_repository' und 'repo_kind' wird die URL zusammengebaut welche verwendet
um dem Client ein opsi Repository hinzuzufügen.

* `backend`: +
Welches Backend soll installiert werden ? (Die Auswahl `mysql` benötigt die Hinterlegung einer gültigen Freischaltdatei). (Default='file') +
Eine modules Datei mit den benötigten Freischaltungen kann im custom Verzeichnis des Produktes abgelegt werden.
Wird dort eine modules gefunden so wird diese verwendet.

* `opsi_admin_user_name`: +
Unter welchen Namen soll ein opsi_admin_user erzeugt werden (empty= kein user wird erzeugt). (Default='adminuser') +
Wird hier ein user angegeben, so wird dieser angelegt, wird Mitglied der Gruppen 'opsiadmin', 'pcpatch'/'opsifileadmin'
und bekommt als unix- und samba Passwort den Wert von `opsi_admin_user_password`

* `opsi_admin_user_password`: +
Was ist das Passwort für den opsi_admin_user (empty= nicht erlaubt). (Default='linux123') +
siehe `opsi_admin_user_name`

* `setup_after_install`: +
Welche opsi Produkte sollen nach der Installation von l-opsi-server installiert werden ?. (Default="")

* `allow_reboot`: +
Darf die Maschine nach der Installation von l-opsi-server rebootet werden ?. (Default='true')

* `myipname`: +
Soll ein abweichender IP-Name (FQDN) bei der Installation verwendet werden ? ('auto'= use standard) (Default='auto') +
siehe `install_and_configure_dhcp`

* `myipnumber`: +
Soll eine abweichende IP-Nummer bei der Installation verwendet werden ? ('auto'= use standard) (Default='auto')+
siehe `install_and_configure_dhcp`

* `install_and_configure_dhcp`: +
Soll ein DHCP-Server auf der Maschine installiert und konfiguriert werden ?. (Default='False') +
Wenn dieses Property 'false' ist, so werden die Properties: 'netmask', 'network','dnsdomain','nameserver' und 'gateway' nicht beachtet, da diese nur der DHP Konfiguration dienen.

* `netmask`: +
Netmask  (für dhcp). (Default="255.255.0.0") +
Nicht verwendet wenn 'install_and_configure_dhcp=false'

* `network`: +
Netzwek Adresse (für dhcp). (Default="192.168.0.0") +
Nicht verwendet wenn 'install_and_configure_dhcp=false'

* `dnsdomain`: +
DNS domain (for dhcp). (Default="uib.local") +
Nicht verwendet wenn 'install_and_configure_dhcp=false'

* `nameserver`: +
Primary nameserver (für dhcp). (Default="192.168.1.245") +
Nicht verwendet wenn 'install_and_configure_dhcp=false'

* `gateway`: +
gateway (option routers for dhcp). (Default="192.168.1.245") +
Nicht verwendet wenn 'install_and_configure_dhcp=false'

* `ucs_master_admin_password`: +
Passwort des users 'Administrators' auf dem UCS-Master. +
Wird nur für UCS-Server benötigt und hier nur für alle Rollen ausser 'Master'. (Default='linux123')

* `update_test`: +
Nicht verwenden: Internal Debuging. (Default='False')

Das Produkt hat eine 'setup required before' Abhängigkeit zu dem Produkt 'l-system-update'.
D.h. wenn Sie 'l-opsi-server' auf 'setup' stellen wird automatisch 'l-system-update' auch auf setup
gestellt und vorher installiert.

In dem Verzeichnis `custom` des Produktes `l-opsi-server` kann eine Freischaltdatei (`modules`) abgelegt werden, welche bei der Installation durch das Produkt `l-opsi-server` verwendet wird und beim Einspielen einer neuen Version des Produktes erhalten bleibt.



[[opsi-manual-linux-localboot-l-os-postinst]]
===== l-os-postinst für v4.0.5 Netboot installationen

Dieses Produkt übernimmt jene Teile der Basisinstallation welche sich vom Bootimage nicht korrekt ausführen lassen.

Dies ist für die unterschiedlichen Distributionen:

* CentOS:

** Installation von SELinux


Das Produkt hat eine Abhängigkeit zu dem Produkt 'l-system-update' welches vor dem Lauf von 'l-os-postinst' aufgerufen wird. +
Das Produkt hat eine hohe Priorität, d.h. es wird vor 'normalen' Produkten ausgeführt.

[[opsi-manual-linux-localboot-l-desktop]]
===== l-desktop

Das Produkt l-desktop installiert einen Desktop auf dem Rechner.

Über das Property `desktop` kann der zu installierende Desktop ausgewählt werden. Dabei ist zu beachten, das nicht alle Desktops auf allen Distributionen verfügbar sind. So gibt es z.B. 'Unity' nur unter Ubuntu. Wird ein nicht verfügbarer Desktop gewählt so wird ein Distributionsspezifischer Defaultdesktop installiert. Weiterhin haben die Desktop Pakete einen unterschiedlichen Umfang welcher abhängig von Distribution und Desktop sich auf die eigentliche Desktop Software beschränken kann oder auch Basisprodukte wie libreoffice, firefox, PDF-Reader usw. enthalten kann.

Das Property `desktop` hat folgende Werte:

* Gnome +
Default für Debian, CentOS, RHEL +
Verfügbar auf allen Distributionen.

* KDE +
Default für SLES, OpenSuse
Verfügbar auf allen Distributionen.

* Unity +
verfügbar nur für Ubuntu

* Cinnamon +
verfügbar nur für Ubuntu

* xfce4 +
Verfügbar auf Ubuntu, Debian.

* lxde +
Verfügbar auf Ubuntu, Debian.


[[opsi-manual-linux-localboot-l-system-update]]
===== l-system-update
Dieses Produkt aktualisiert das System.

[[opsi-manual-linux-localboot-l-swaudit]]
===== l-swaudit
Softwareinventarisierung auf Basis des Paketmanagers

[[opsi-manual-linux-localboot-l-hwaudit]]
===== l-hwaudit

Hardwareinventarisierung. +
Die Hardwareinventarisierung basiert zur Zeit auf der in Python implementierten Methode wie sie auch vom bootimage verwendet wird. Dazu muß das Paket `python-opsi` aus dem opsi-Repository der Distribution installiert werden. Ist für die Distribution kein opsi-Repository verfügbar, so scheitert auch die Hardwareinventarisierung.

[[opsi-manual-linux-localboot-l-jedit]]
===== l-jedit

Java-basierter Editor mit Syntaxhighlighting für opsi-script.
Ist noch kein Java installiert, so wird dieses automatisch installiert.


[[opsi-manual-linux-inventory]]
==== Inventarisierung

Zur Inventarisierung werden die Daten durch den Clientagenten erhoben und an den Server gesendet. Die Hardwareinventarisierung basiert auf den schon im Bootimage implementierten Methoden.

Die Softwareinventarisierung basiert auf den Daten des Paketmanagements der verwendeten Distribution.

[[opsi-manual-linux-uefi]]
==== UEFI / GPT Unterstützung

Einige der opsi v4.0.5 Linuxprodukte sind UEFI/GPT kompatibel. Details siehe hierzu in der obigen Auflistung der Netbootprodukte.

Die opsi v4.0.6 Linuxprodukte sind leider noch nicht UEFI/GPT kompatibel.
Die Informationen über die UEFI Umgebung gehen im Moment noch bei dem kexec Boot verloren. Wir hoffen, das wir dieses Problem mit einem neueren bootimage irgendwann beheben können.

[[opsi-manual-linux-roadmap]]
==== Roadmap

Die Linux Unterstützung von opsi ist neu. Das bedeutet auch, dass wir im ersten Release noch nicht alle Features verwirklicht haben. +
Weitere Features werden folgen wie:

* Frei konfigurierbare Partitionierung
* Logical Volume Management
* Patchen von XML-Dateien
* Patchen von hierarchischen Konfigurationsdateien wie dhcpd.conf


[[opsi-manual-linux-debproxy]]
==== Proxy für deb Pakete einrichten und verwenden

Eine brauchbare Anleitung zur Erstellung eines eigenen Ubuntu Proxy finden Sie hier:

http://wiki.ubuntuusers.de/Lokale_Paketquellen/Apt-Cacher-ng

http://www.gambaru.de/blog/2011/10/26/apt-cacher-ng-ein-proxy-server-fur-debian-und-ubuntu/
