////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      022.10.2013
:Revision:  4.0.4
:toclevels: 6


include::../common/opsi_terms.asciidoc[]

[[opsi-manual-linux]]
== opsi Linux Support


[[opsi-manual-linux-preconditions]]
=== Vorbedingungen für den opsi Linux Support


Technische Voraussetzungen sind opsi 4.0.4 mit den Paketständen:

.Benötigte Pakete
[options="header"]
|==========================
|opsi-Paket|Version
|opsi-linux-bootimage|>= 20130207-1
|==========================

Der opsi Support für Linux besteht aus einem Teil der von Anfang an Open Source ist (den Netbootprodukten)
und einem kofinanzierten Teil (dem client-agenten)

Dieses opsi-linux-client-agent ist
http://www.uib.de/www/kofinanziert/index.html[kofinanzierte opsi Erweiterung]. +
Das bedeutet, das Sie zum Einsatz eine Freischaltdatei benötigen. Diese Freischaltung erhalten Sie wenn Sie die Erweiterung kaufen. Zu Evaluierungszwecken stellen wir Ihnen auch eine zeitlich befristete Freischaltung kostenlos zur Verfügung ( -> mail an info@uib.de). +
Weitere Details hierzu finden Sie in <<opsi-manual-modules>>.


[[opsi-manual-linux-introduction]]
=== Einführung

[[opsi-manual-linux-netboot]]
=== Linux Netboot Produkte


[[opsi-manual-linux-clientagent]]
=== opsi-linux-client-agent


