////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////
:Author:    uib gmbh
:Email:     info@uib.de
:Date:      29.08.2018
:Revision:  4.1
:toclevels: 6
:doctype:   book

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]

[[opsi-manual-abo-products-introduction]]
=== opsi Abo Produkte

[[opsi-manual-abo-products-introduction-firststeps]]
==== Initiale Bereitstellung von Paketen aus dem Abobereich

Zur Bereitstellung der benötigten Pakete können Sie diese manuell herunterladen oder aber alle Pakete nach Anpassung der Konfiguration des `opsi-package-updater` über diesen installieren.


[[opsi-manual-abo-products-introduction-third]]
==== Konfiguration des `opsi-package-updater` / Aktualisierung der Abo-Pakete

Für den weiteren Betrieb ist es empfohlen die Repository-Konfiguration in '/etc/opsi/package-updater.repos.d/' abzulegen.
Eine entsprechende Konfigurationsdatei erhalten Sie mit Ihren Zugangsdaten.

CAUTION: Bei Bedarf muß in diesen Dateien noch der Zugang über einen Proxy konfiguriert werden!

Es bietet sich anschließend an gezielt nur die benoetigten Pakete aus den neuen Repositories zu installieren:
[source,prompt]
----
# Beispiel: Pakete fuer mshotfix, Plattform Windows 7 x64 / Server 2008 und Windwos 10 / 2016 / 2019 x64  installieren
opsi-package-updater --repo uib_abo_mshotfix install install mshotfix mshotfix-win7-win2008r2-x64-glb mshotfix-win10-win2016-x64-glb 
# Beispiel: Pakete fuer msoffice Office 2016 installieren
opsi-package-updater --repo uib_abo_msoffice install office_2016_hotfix
# Beispiel: Pakete fuer standard produkte firefox und libreoffice installieren
opsi-package-updater --repo uib_abo_standard install firefox libreoffice
----

Es ist möglich gezielt benötigte Pakete zu installieren, bspw. nur die Pakete für das Update von Windows 7:
[source,prompt]
----
opsi-package-updater -v install mshotfix mshotfix-win7-x86-glb mshotfix-win7-win2008r2-x64-glb
----

Für die Aktualisierung der Pakete wird der `opsi-package-updater` empfohlen.

Mittels dem Aufruf `opsi-package-updater -v update` können dann z.B. per Cronjob die installierten Pakete aktualisiert werden.

Eine gleichwertige Variante ist für jedes Repository die Pakete gezielt zu aktualisieren.
[source,prompt]
----
# Pakete fuer mshotfix aktualisieren
opsi-package-updater --repo uib_abo_mshotfix update
# Pakete fuer msoffice aktualisieren
opsi-package-updater --repo uib_abo_msoffice update
# Pakete fuer standard produkte aktualisieren
opsi-package-updater --repo uib_abo_standard update
----


[[opsi-manual-abo-products-introduction-second]]
==== Festlegung von Default-Properties

Bei der nichtinteraktiven Installation von opsi-Paketen werden auf einem '{opsi-configserver}' bzw. einem '{opsi-Server}' die Paket default-Properties als default festgelegt.

Ab opsi Version 4.0.5 können die '{opsi-Server}'-default-Properties über das Managementinterface '{opsi-Configed}' festgelegt werden.

Bei einer anschliessenden Installation einer neueren Paketversion mittels `opsi-package-manager` oder `opsi-package-updater` bleiben die eingestellten depot default Properties erhalten.





[[opsi-manual-abo-products-mshotfix]]
==== Update-Abo 'MS-Hotfixes'
Regelmäßige Updates des Produktes mshotfix (Hotfixes für Windows 7 / 2008-R2, Windows 8.1 / 2012-R2, Windows 10 / Windows 2016).

CAUTION: Von Microsoft nicht mehr unterstützte Versionen werden als "failed" angezeigt: 1507 "non"-ltsb, 1511 und 1607 "non"-ltsb ausser Education und
Enterprise

Das Update erscheint jeweils innerhalb von 3 Arbeitstagen nach dem Erscheinen eines von Microsoft als wichtig oder kritisch eingeschätzten Patches.

http://technet.microsoft.com/de-de/security/gg309177.aspx


http://technet.microsoft.com/en-us/security/gg309177.aspx
[source,prompt]
----

Bewertung	Beschreibung
Kritisch

Eine Schwachstelle, deren Ausnutzung ohne Eingreifen des Benutzers Codeausführung ermöglichen kann. Dies umfasst Szenarien wie sich selbst verbreitende Malware (z. B. Würmer) oder nicht zu vermeidende gebräuchliche Anwendungsszenarien, in denen Codeausführung ohne Warnungen oder Eingabeaufforderungen erfolgt. Dies könnte das Abrufen einer Webseite oder das Öffnen einer E-Mail bedeuten.

Microsoft empfiehlt, dass Kunden kritische Updates unverzüglich installieren.
Hoch

Eine Schwachstelle, deren Ausnutzung die Vertraulichkeit, Integrität oder Verfügbarkeit von Benutzerdaten oder anderen Ressourcen gefährden kann. Dies umfasst gebräuchliche Anwendungsszenarien, in denen der Kunde durch Warnungen oder Eingabeaufforderungen unabhängig von deren Herkunft, Qualität oder Nutzbarkeit geschädigt wird. Abfolgen von Nutzerhandlungen, die keine Eingabeaufforderungen oder Warnungen hervorrufen, sind ebenfalls abgedeckt.

Microsoft empfiehlt, dass Kunden Updates mit hohem Risiko so frühzeitig wie möglich installieren.
Mittel

Die Auswirkungen der Schwachstelle sind durch Faktoren wie Authentifizierungsanforderungen oder die Anwendbarkeit nur auf Nicht-Standardkonfigurationen erheblich eingeschränkt.

Microsoft empfiehlt, dass Kunden die Anwendung des Sicherheitsupdates in Erwägung zieht.
Niedrig	Die Auswirkungen der Schwachstelle sind aufgrund von Eigenschaften der betroffenen Komponente umfassend eingeschränkt. Microsoft empfiehlt, dass Kunden erwägen, ob sie das Sicherheitsupdate auf die betroffenen Systeme anwenden.

Rating	Definition
Critical

A vulnerability whose exploitation could allow code execution without user interaction. These scenarios include self-propagating malware (e.g. network worms), or unavoidable common use scenarios where code execution occurs without warnings or prompts. This could mean browsing to a web page or opening email.

Microsoft recommends that customers apply Critical updates immediately.
Important

A vulnerability whose exploitation could result in compromise of the confidentiality, integrity, or availability of user data, or of the integrity or availability of processing resources. These scenarios include common use scenarios where client is compromised with warnings or prompts regardless of the prompt's provenance, quality, or usability. Sequences of user actions that do not generate prompts or warnings are also covered.

Microsoft recommends that customers apply Important updates at the earliest opportunity.
Moderate

Impact of the vulnerability is mitigated to a significant degree by factors such as authentication requirements or applicability only to non-default configurations.

Microsoft recommends that customers consider applying the security update.
Low	Impact of the vulnerability is comprehensively mitigated by the characteristics of the affected component. Microsoft recommends that customers evaluate whether to apply the security update to the affected systems.

----

Das opsi-mshotfix Paket verwendet (wie WSUS Offline Update http://forums.wsusoffline.net/viewtopic.php?f=7&t=172 Abdeckung des / Coverage of WSUS Offline Update ) für den Download Microsoft's Update-Katalogdatei wsusscn2.cab, um die erforderlichen Patches zu ermitteln.
Diese Katalogdatei enthält mindestens alle als „kritisch“ und „sicherheitsrelevant“ eingestuften Updates, aber nicht notwendigerweise alle „wichtigen“ und „optionalen“.

Die opsi mshotfix-Pakete sind modular aufgebaut.
Das Basis-Paket „mshotfix“ beinhaltet nur ein Skript zum Installieren der Patches. Die eigentlichen Patches sind gesondert in separaten Paketen enthalten

.mshotfix Client-Betriebssystem Voraussetzung
|==========================================
|OS|
|Windows 7 / Windows 2008 R2|Servicepack 1
|Windows Windows 2012
|Windows 8.1 / Windows 2012 R2|
|Windows 10 / Windows 2016 / Windows 2019|
|==========================================



CAUTION: Wan/VPN Modul Die Pakete für Windows 8.1 / 2012 R2 benötigen opsi-winst >= opsi-winst_4.11.3.11-1.opsi und opsi-client-agent >= opsi-client-agent_4.0.4.4-1.opsi

CAUTION: Wan/VPN Modul Die Pakete für Windows 10  /2016 benötigen  opsi-client-agent >= 4.0.7.9-2

CAUTION: Wan/VPN Modul Die modularen Pakete für Windows 10  /2016 / 2019 benötigen  opsi-client-agent >= opsi-client-agent 4.1.0.0-27 bzw. opsiclientd  >= 4.0.95

Auf unserem Download-Server ist die Struktur des Abo verzeichnisses


[source,configfile]
----
mshotfix
  !-opsi4/
     !-glb/	Basis-Paket mshotfix sowie globale Patchpakete
     		mshotfix-win7-x86-glb,
     		mshotfix-win7-win2008r2-x64-glb
     		mshotfix-win8-win2012-x64-glb
     		mshotfix-win81-x86-glb
     		mshotfix-win81-win2012r2-x64-glb
 		    mshotfix-win10-win2016-x64-glb
		    mshotfix-win10-x86-glb
		    
		    mshotfix-win10-1507-x64-glb 	(seit 201904-1)                                                                                                                          
		    mshotfix-win10-1507-x86-glb 	(seit 201904-1)                                                                                                                                           
		    mshotfix-win10-1607-x64-glb 	(seit 201904-1)                                                                                                                          
		    mshotfix-win10-1607-x86-glb 	(seit 201904-1)                                                                                                                                           
		    mshotfix-win10-1703-x64-glb 	(seit 201904-1)                                                                                                                          
		    mshotfix-win10-1703-x86-glb 	(seit 201904-1)                                                                                                                                           
		    mshotfix-win10-1709-x64-glb 	(seit 201904-1)                                                                                                                          
		    mshotfix-win10-1709-x86-glb 	(seit 201904-1)                                                                                                                                           
		    mshotfix-win10-1803-x64-glb 	(seit 201904-1)                                                                                                                          
		    mshotfix-win10-1803-x86-glb 	(seit 201904-1)                                                                                                                                           
		    mshotfix-win10-1809-x64-glb 	(seit 201904-1)                                                                                                                          
		    mshotfix-win10-1809-x86-glb 	(seit 201904-1)
		    mshotfix-win10-1903-x86-glb 	(seit 201904-1)
		    mshotfix-win10-1903-x64-glb 	(seit 201904-1)
     !-misc/	diverse zusätzliche Pakete
     		dotnetfx,
     		dotnetfx-hotfix,
     		mshotfix-uninstall,
     		ms-ie11,
     		ms-optional-fixes,
     		silverlight
----

Folgende Tabelle soll bei der Auswahl der richtigen Pakete helfen:

.mshotfix Client-Betriebssystem
|=======================
|OS|Arch. Sprache|Patch-Paket
|Windows 7 | 32Bit | mshotfix-win7-x86-glb
|Windows 7 | 64Bit | mshotfix-win7-win2008r2-x64-glb
|Windows 2012 | 64Bit | mshotfix-win8-win2012-x64-glb
|Windows 8.1 | 32Bit | mshotfix-win81-x86-glb
|Windows 8.1 | 64Bit | mshotfix-win81-win2012r2-x64-glb
|Windows 2008 Server R2 | 64Bit | mshotfix-win7-win2008r2-x64-glb
|Windows 2012 R2 | 64Bit | mshotfix-win81-win2012r2-x64-glb
|Windows 10 | 32Bit | mshotfix-win10-x86-glb			oder das passende modulare Paket
|Windows 10 | 64Bit | mshotfix-win10-win2016-x64-glb 	oder das passende modulare Paket
|Windows 2016 | 64Bit | mshotfix-win10-win2016-x64-glb 	oder mshotfix-win10-1607-x64-glb
|Windows 2019 | 64Bit | mshotfix-win10-win2016-x64-glb 	oder mshotfix-win10-1809-x64-glb 
|=======================

Installation:
opsi-package-manager -i mshotfix_201008-1.opsi
zum Scharfschalten (überall auf setup stellen, wo das Produkt auf installed steht):
opsi-package-manager -iS mshotfix_201008-1.opsi

Zusätzlich zum Basis-Paket werden die Patch-Pakete auf die gleiche Weise installiert. Da diese Pakete aber keine Installationsskripte enthalten, sind sie nur zusammen mit dem Basis-Paket einzuspielen, d.h.  man kann diese nicht separat auf setup stellen.
Für die Client-Installation ist komplett das mshotfix-Basispaket zuständig.

Seit Paket mshotfix 201304-1 werden sich durch mshotfix installiertePatches in der Datei `C:\opsi.org\mshotfix\deployed.txt` lokal gemerkt.

Caution:: Seit Paket mshotfix 201808-3 wird zuerst das aktuelle ServingStack installiert mit einem sofortigen Neustart

noreboot:: noreboot=on: Don't Reboot if possible  Warning will be logged if a reboot is required. Will be ignored for Servicing stacks
values: ["off", "on"]
default: ["off"]


force:: force=on: All Hotfixes will be installed forced
values: ["off", "on"]
default: ["off"]

excludes::  Commaseparated list with kb-numbers or ms-no, that will be excluded (Only Number without beginning kb and no spaces. Example: 123456,789011,2222)
 Browser Choice update? (KB976002)

severity:: choose the severity that will be installed. Possible Entries are Critical, Important, Moderate, all
values: ["Critical", "Important", "Moderate", "all"]
default: ["Critical", "Important"]

excludelist-superseded.txt:: Use File ExcludeList-superseded.txt
values: ["", "ExcludeList-superseded.txt"]
default: [""]

monthly-updates::  Handle windows-7-and-windows-8-1 : security Only Quality Update vs Monthly Quality Rollup (see link:https://blogs.technet.microsoft.com/windowsitpro/2016/08/15/further-simplifying-servicing-model-for-windows-7-and-windows-8-1/[Further simplifying servicing models for Windows 7 and Windows 8.1], link:https://blogs.technet.microsoft.com/windowsitpro/2016/10/07/more-on-windows-7-and-windows-8-1-servicing-changes/[More on Windows 7 and Windows 8.1 servicing changes], link:https://blogs.msdn.microsoft.com/dotnet/2016/10/11/net-framework-monthly-rollups-explained/[.NET Framework Monthly Rollups Explained])
values: ["all", "monthly_quality_rollup", "security_only_quality_update"]
default: ["security_only_quality_update"]

===== misc mshotfix-uninstall

----
mshotfix-uninstall        201512-1                  MS Hotfix BasePackage
----

Entfernt Patches mittels `wusa /uninstall  ...` die sich mit dieser Methode deinstallieren lassen.

excludes:: Commaseparated list with kb-numbers or ms-no, that will be excluded (Only Number without beginning kb and no spaces. Example: 2553154,ms14-082)

noreboot:: noreboot=on: Don't Reboot.  Warning will be logged if a reboot is required.
values: ["off", "on"]
default: ["off"]

removefromdeployed.txt:: Remove from deployed.txt
default: False

removekb:: Remove KBXXXXX, (Only Number without beginning kb and no spaces f.e. 3097877)
multivalue: True
default: [""]

===== misc dotnetfx

----
dotnetfx                  4.7.2-3                 .NET Framework
----

Paket zur Installation der Dotnet Framework Versionen 4.5 und höher insbesondere auf Windows 7 /2008 R2 / 8.1 / 10 / 2012 R2
Auf Windows Versionen (neuer Windows 7) kann auch Dotnet 3.5 installiert werden.

version:: The Microsoft .NET Framework 4.8 is a highly compatible, in-place update to the Microsoft .NET Framework 4, 4.5, 4.5.1, 4.5.2, 4.6, 4.6.1, 4.6.2, 4.7 , 4.7.1 and 4.7.2 +
values: ["3.5", "4.0", "4.5", "4.5.1", "4.5.2", "4.6", "4.6.1", "4.6.2", "4.7", "4.7.1", "4.7.2", "latest", "latestAnd3.5"] +
default: ["latest"]

rerundotnethotfix:: rerun dotnetfx-hotfix after installation if possible +
values: ["false", "true"] +
default: ["true"]

install_language_languagepack:: install_language_languagepack
values: ["auto", "de", "en", "fr"]
default: ["auto"]

os-package:: Here you can switch from which OS-Version to be install Dotnet3.5,
auto=win10 or opsi-local-image-win10 (default); other ProductID for netboot-product
values: ["auto", ]
default: ["auto"]

===== misc dotnetfx-hotfix

----
dotnetfx-hotfix           201808-1                  dotnetfx-hotfix
----

Im Update-Abo 'MS-Hotfixes' sind die Hotfixes für 'Microsoft .NET
Framework' nur enthalten, falls es passend zum jeweiligen Betriebssystem
ist.

Also z.B. bei Windows 7 "Microsoft .NET Framework 3.5.1"

( Allerdings gibt es seit Oktober 2016 unter Umständen auch "Monthly Rollups"
für DotnetFramework, die im mshotfix-Paket enthalten sind.)

Das Paket dotnetfx-hotfix
beinhaltet die Hotfixes von Microsoft für

- Microsoft .NET Framework 4 und höher für Windows 7

Das Paket dotnetfx-hotfix patcht zur Zeit - so vorhanden - die Versionen
4.x auf den jeweils letzten Stand der Reihe.

Bitte beachten Sie:
"Support for .NET Framework 4, 4.5, and 4.5.1 ended on January 12, 2016"
(https://support.microsoft.com/en-us/lifecycle?p1=14380)

bzw.
https://support.microsoft.com/en-us/gp/framework_faq/de

noreboot:: noreboot=on: Don't Reboot.  Warning will be logged if a reboot is required.
values: ["off", "on"]
default: ["off"]

force:: force=on: All Hotfixes will be installed forced
values: ["off", "on"]
default: ["off"]

severity:: choose the severity that will be installed.Possible Entries:Critical, Important, Moderate, all
values: ["Critical", "Important", "Moderate", "all"]
default: ["all"]

===== misc ms-ie11

----
ms-ie11                   11.0-11                   Internet Explorer 11
----

Win7 Internet Explorer 11

rerunmshotfix:: rerun mshotfix after installation
values: ["false", "true"]
default: ["true"]

client_language::
values: ["auto", "de", "en", "fr"]
default: ["auto"]

===== misc ms-optional-fixes

----
ms-optional-fixes         201808-1                  MS optional fixes
----

Gedacht als Ergänzung zu mshotfix und basiert auf mshotfix

Enthält:

kb2999226 für win7-win8.1

message_language:: Language for messages while installing
values: ["auto", "de", "en", "fr"]
default: ["auto"]

noreboot:: noreboot=on: Don't Reboot if possible  Warning will be logged if a reboot is required. Will be ignored for Servicing stacks
values: ["off", "on"]
default: ["off"]

excludes:: Commaseparated list with kb-numbers or ms-no, that will be excluded (Only Number without beginning kb and no spaces. Example: 123456,789011,2222)
 49  Browser Choice update? (KB976002)
 50 values: []
 51 default: []


rerunmshotfix:: rerun mshotfix after installation
values: ["false", "true"]
default: ["true"]

client_language::
values: ["auto", "de", "en", "fr"]
default: ["auto"]


===== misc silverlight

----
silverlight               5.1.50918.0-1             Microsoft Silverlight
----


==== Update-Abo 'MS-Office Hotfixes'
Regelmäßige Updates für MS-Office 2010/2013/2016 32 Bit sowie MS-Office 64 Bit

Das Update erscheint jeweils innerhalb von 3 Arbeitstagen nach dem Erscheinen eines von Microsoft als wichtig oder kritisch eingeschätzten Patches.

.Office hotfix  Voraussetzung
|===================================
|Office Version| required
|Office 2010 32-bit|Service Pack 2
|Office 2013 32-bit|Servicepack 1
|Office 2016 |
|====================================


[[opsi-manual-abo-products-office_2010_hotfix]]

===== Updates für MS Office 2010 32-bit international: office_2010_hotfix
----
office_2010_hotfix               201808-1                  Microsoft Office 2010 Hotfixes
----

Enthält sprachunabhängige monatliche Office 2010 Hotfixes (inclusive Visio und Project 2010) . Setzt Servicepack 2 voraus.

Wird getestet gegen Office 2010 Professional und Standard.

Seit Paket office_2010_hotfix 201305-2 werden sich durch office_2010_hotfix installierte Patches in der Datei `C:\opsi.org\mshotfix\office_2010_hotfix_deployed.txt` lokal gemerkt.

Seit office_2010_hotfix 201503-1:

excludes:: Commaseparated list with kb-numbers or ms-no, that will be excluded (Only Number without beginning kb and no spaces. Example: 2553154,ms14-082)

[[opsi-manual-abo-products-office_2013_hotfix]]

===== Updates für MS Office 2013 32-bit international: office_2013_hotfix
----
office_2013_hotfix               201808-1                  Microsoft Office 2013 Hotfixes
----

Enthält sprachunabhängige monatliche Office 2013 Hotfixes (inclusive Visio 2013) . Setzt Servicepack 1 voraus.

Wird getestet gegen Office 2013 Professional

Durch office_2013_hotfix installierte Patches in der Datei `C:\opsi.org\mshotfix\office_2013_hotfix_deployed.txt` lokal gemerkt.

Seit office_2013_hotfix 201503-1:

excludes:: Commaseparated list with kb-numbers or ms-no, that will be excluded (Only Number without beginning kb and no spaces. Example: 2553154,ms14-082)


[[opsi-manual-abo-products-office_2016_hotfix]]

===== Updates für MS Office 2016 32-bit international: office_2016_hotfix

----
office_2016_hotfix               201808-1                  Microsoft Office 2016 Hotfixes
----

Enthält sprachunabhängige monatliche Office 2016 Hotfixes (inclusive Visio 2016) .

Wird getestet gegen Office 2016 Professional

Durch office_2016_hotfix installierte Patches in der Datei

`C:\opsi.org\mshotfix\office_2016_hotfix_deployed.txt`

lokal gemerkt.

excludes:: Commaseparated list with kb-numbers or ms-no, that will be excluded (Only Number without beginning kb and no spaces. Example: 2553154,ms14-082)

CAUTION:: Falls Sie Updates für MS Office 2016 32-bit und 64-Bit oder aber nur 64-Bit einsetzen wollen:

Passen Sie das repo uib_abo_msoffice update an: x3264 / x64

[[opsi-manual-abo-products-standard]]
==== Update-Abo 'opsi Standardprodukte'
Regelmäßige Updates der Produkte:

    Adobe Reader DC Classic / Continuous (international / 32 Bit)
    Adobe Flashplayer (international / 32 Bit / 64 Bit)
    Apache OpenOffice.org (deutsch / 32 Bit)
    Google Chromium for business ( international 32 Bit / 64 Bit )
    LibreOffice ( international 32 Bit / 64 Bit )
    Mozilla Firefox (deutsch, englisch, französisch und niederländisch. / 32 Bit) bzw. 32/64-Bit Pakete seit 201706
    Mozilla Thunderbird (deutsch, englisch und französisch / 32 Bit)
    Java VM (javavm) basierend auf Open JDK LTS 11 (international 64 Bit)
    Java VM 8 (javavm8) basierend auf Open JDK LTS 8 (international 32 Bit / 64 Bit)
    Java VM (javavm-oracle-jdk) OpenJDK basierend auf der aktuellen open jdk implementation (international 64 Bit) 

    Je nach Vertrag stellen wir noch folgende Sprachen im Abo zur Verfügung:

        Mozilla Firefox (zusätzlich dänisch, italienisch, spanisch, tschechisch und norwegisch / 32 Bit)
        Mozilla Thunderbird (zusätzlich italienisch / 32 Bit)

     weitere Sprachen auf Anfrage.



Das Update erscheint jeweils innerhalb von 2 Arbeitswochen nach dem Erscheinen eines Updates dieser Produkte; bei vom Hersteller als kritisch eingestuften Security-Updates innerhalb von 1 Arbeitswoche.

===== Customizing der Pakete durch zentrale Konfigurationen

Für die Pakete
----
adobe.reader.dc.classic
adobe.reader.dc.continuous
firefox
flashplayer
thunderbird
----

gibt es die Möglichkeit eigene Konfigurationen zu erstellen und im Verzeichnis `custom` zu hinterlegen,
die über Properties auswählbar sind. (Näheres siehe unten)

===== Customizing der Pakete durch preinst/postinst-scripts

Für die Pakete
----
adobe.reader.dc.classic
firefox		(ab 17.0.6esrorstandard-1)
flashplayer	(ab 13.0.0.182or11.7.700.275-1)
google-chrome-for-business
javavm		(ab javavm_1.7.0.51-5 )
javavm8
javavm-oracle-jdk
libreoffice	(ab libreoffice_4.3.5or4.4.0-2)
ooffice		(ab ooffice_4.1.1-2)
thunderbird	(ab 17.0.6esrorstandard-1)
----

besteht die Möglichkeit eigene custom-Scripte einzubauen im Verzeichnis `custom\scripts`

Einfache Templates für die unterstützen Scripte finden sich im Verzeichnis `opsi\scripts`

[source,configfile]
----

custom.actions.post.setup
custom.actions.post.uninstall
custom.actions.pre.setup
custom.actions.pre.uninstall
custom.declarations
custom.sections

custom scripts will be included at
- setup-script
- uninstall-script

custom pre-scripts will be included in
- setup-script
- uninstall-script

custom post-scripts will be included in
- in setup-script
- uninstall-script

custom.declarations
; intended for declaration of custom Variables and Stringlist Variables
; will be included with "include_insert" at top of [actions]
; but after GetProductProperties

custom.sections
; intended for declaration of custom secondary sections
; will be included with "include_append" at top of [actions]
; but after GetProductProperties

custom.actions.pre.setup  (or custom.actions.pre.uninstall)
; will be included with "include_insert" at at top of [actions]
; (but after GetProductProperties)

custom.actions.post.setup (or custom.actions.post.uninstall)
; will be included with "include_insert" in case of successful installation before "endof_"actions"
; in setup-script ( or uninstall-script)

----

===== Adobe Acrobat Document Cloud Classic : adobe.reader.dc.classic
----
adobe.reader.dc.classic                              20151500630493or20171701130138-1 Adobe acrobat reader dc classic
----

Das adobe.reader.dc.classic-Paket beinhaltet Adobe Acrobat Document Cloud Classic ( MUI-Version )

Adaptation in the transform file *.mst
[source,prompt]
----
cat transform.txt
Changes vs default the transform file *.mst


Personalisation Options
Suppress Eula

Installation Options
acivated - Make Reader the default PDF viewer
IF REBOOT REQUIRED - suppress reboot


Shortcuts
deactivated - Destination Computer/Desktop/Adobe Reader XI (Icon)


Online and Acrobat.com Features
Online Features
activated - Disable product updates
Enable & Ask before Installing - Load trustet root certificates from Adobe

Online Services and Features
disable product updates
Load trusted root certificates from Adobe disable
DISABLE all Services
----

adobereader.mst::

Das Adobe Reader Paket von uib verwendet eine Standard-transform-Datei
die mit dem Adobe Customization Wizard erstellt ist.
Abweichend davon können im Share `opsi_depot` im Verzeichnis
`/var/lib/opsi/depot/adobe.reader.dc.classic/custom` eigene MST-Dateien abgelegt werden, die über dieses
Property ausgewählt werden können(nach erneutem Einspielen des Pakets mittels  `opsi-package-manager -i <adobe-paket>`).

Beim Einspielen des adobe.reader.dc.classic-Pakets auf dem opsi-Server wird das Verzeichnis
custom ueber ein preinst/postinst-Script
gesichert.
+
CAUTION: Bei Einsatz des Wan/VPN Moduls muss nach Änderungen im Verzeichnis `custom` das Paket neu eingespielt werden, damit die Datei `<productid>.files` neu erzeugt wird.

client_language::

Das adobe.reader.dc.classic-Paket als MUI
Ist der Wert auf "auto" gesetzt, so wird anhand der Systemsprache automatisch die Sprache erkannt. values: ["auto", "de", "en", "fr" ]  default: ["auto"]

classicversion::
 
siehe https://helpx.adobe.com/acrobat/release-note/release-notes-acrobat-reader.html Classic Track (2015 Release) or (2017 Release)
values: ["2015", "2017"]
default: ["2015"]

disableadobeacrobatupdateservice::

Disable Adobe Acrobat Update Service and remove Adobe Acrobat Update Task
values: ["false", "true"]
default: ["false"]
 
removebeforesetup::

remove target version of adobe reader before install
values: ["false", "true"]
default: ["false"]

noreboot::

description: noreboot=true: Don't Reboot.  Warning will be logged if a reboot is required.
values: ["false", "true"]
default: ["false"]


===== Adobe Acrobat Document Cloud Continuous : adobe.reader.dc.continuous
----
adobe.reader.dc.continuous                           201901020099-1            Adobe acrobat reader dc continuos
----

Das adobe.reader.dc.continuous-Paket beinhaltet Adobe Acrobat Document Cloud Continuous ( MUI-Version )

Adaptation in the transform file *.mst
[source,prompt]
----
cat transform.txt
Changes vs default the transform file *.mst


Personalisation Options
Suppress Eula

Installation Options
acivated - Make Reader the default PDF viewer
IF REBOOT REQUIRED - suppress reboot


Shortcuts
deactivated - Destination Computer/Desktop/Adobe Reader (Icon)


Online and Acrobat.com Features
Online Features
activated - Disable product updates
Enable & Ask before Installing - Load trustet root certificates from Adobe

Online Services and Features
disable product updates
Load trusted root certificates from Adobe disable
DISABLE all Services
----

adobereader.mst::

Das Adobe Reader Paket von uib verwendet eine Standard-transform-Datei
die mit dem Adobe Customization Wizard erstellt ist.
Abweichend davon können im Share `opsi_depot` im Verzeichnis
`/var/lib/opsi/depot/adobe.reader.dc.continuous/custom` eigene MST-Dateien abgelegt werden, die über diese
Property ausgewählt werden können (nach erneutem Einspielen des Pakets mittels  `opsi-package-manager -i <adobe-paket>`)
Beim Einspielen des adobe.reader.dc.continuous-Pakets auf dem opsi-Server wird das Verzeichnis
custom ueber ein preinst/postinst-Script
gesichert.
+
CAUTION: Bei Einsatz des Wan/VPN Moduls muss nach Änderungen im Verzeichnis `custom` das Paket neu eingespielt werden, damit die Datei `<productid>.files` neu erzeugt wird.

client_language::

Das adobe.reader.dc.continuous-Paket als MUI
Ist der Wert auf "auto" gesetzt, so wird anhand der Systemsprache automatisch die Sprache erkannt. values: ["auto", "de", "en", "fr" ]  default: ["auto"]


disableadobeacrobatupdateservice::

Disable Adobe Acrobat Update Service and remove Adobe Acrobat Update Task
values: ["false", "true"]
default: ["false"]
 
removebeforesetup::

remove target version of adobe reader before install
values: ["false", "true"]
default: ["false"]


noreboot::

description: noreboot=true: Don't Reboot.  Warning will be logged if a reboot is required.
values: ["false", "true"]
default: ["false"]


[[opsi-manual-abo-products-standard-flashplayer]]
===== Adobe Flashplayer : flashplayer
----
flashplayer                      32.0.0.171-1 Adobe Flashplayer
----
Das flashplayer-Paket beinhaltet Adobe Flashplayer in den von Adobe unterstützten Version 

flashplayer-version:: Flashplayer standard as default
values: esr, standard
default: standard


Die zentrale Konfigurationsdatei mms.cfg

wird bei jedem neu "auf setup" setzen

neu erstellt und gemaess den Produktproperties angepasst (Ausnahme: Verwendung einer custom mms.cfg)

Bei leeren Werten werden keine Eintraege gemacht.

Seit Version 13.0.0.250-2 besteht die Möglichkeit abweichend davon eine custom mms.cfg bereitzustellen


mms.cfg::
`/var/lib/opsi/depot/flashplayer/custom` eigene mms.cfg -Dateien abzulegen,  die über diese Property ausgewählt werden können (nach erneutem Einspielen des Pakets mittels  `opsi-package-manager -i <flashplayer-paket>`).


Beim Einspielen des flashplayer-Pakets auf dem opsi-Server wird das Verzeichnis
custom ueber ein preinst/postinst-Script
gesichert.
+
CAUTION: Bei Einsatz des Wan/VPN Moduls muss nach Änderungen im Verzeichnis      `custom` das Paket neu eingespielt werden, damit die Datei `<productid>.files` neu erzeugt wird.

Weitere Einstellungen ausser Verwendung der Property
autoupdatedisable::

werden dann nicht verwendet

Weitere Hinweise siehe

.Adobe Flashplayer Admin Guide:

[source,prompt]
----

flash_player_11_1_admin_guide.pdf (flash_player_admin_guide.pdf)

#####################################
Chapter 4: Administration

You can create and place files on the end user’s machine to manage
features related to security, privacy, use of disk
space, and so on.

Privacy and security settings (mms.cfg)

As a network administrator, you can install Flash Player across the
enterprise while enforcing some common global
security and privacy settings (supported with installation-time
configuration choices). To do this, you install a file
named mms.cfg on each client machine.

The mms.cfg file is a text file. When Flash Player starts, it reads its
settings from this file, and uses them to manage
functionality as described in the following sections.

mms.cfg file location

Assuming a default Windows installation, Flash Player looks for the
mms.cfg file in the following system directories:

32-bit Windows - %WINDIR%\System32\Macromed\Flash

64-bit Windows - %WINDIR%\SysWow64\Macromed\Flash

Note: The %WINDIR% location represents the Windows system directory,
such as C:\WINDOWS.

----

assetcachesize::
description: hard limit, in MB, on the amount of local storage that Flash Player uses for the storage of common Flash components
values: ["20"]
default: ["20"]

autoupdatedisable::
description: Lets you prevent Flash Player from automatically checking for and installing updated versions.
values: ["0", "1"]
default: ["1"]

autoupdateinterval::
description: (without meaning if AutoUpdateDisable=1) how often to check for an updated version of Flash Player

avhardwaredisable::
description: Lets you prevent SWF files from accessing webcams or microphones
values: ["0", "1"]
default: ["1"]

disabledevicefontenumeration::
description: Lets you prevent information on installed fonts from being displayed.
values: ["0", "1"]
default: ["1"]

fullscreendisable::
description: Lets you disable SWF files playing via a browser plug-in from being displayed in full-screen mode
values: ["0", "1"]
default: ["1"]

localfilereaddisable::
description: Lets you prevent local SWF files from having read access to files on local hard drives
values: ["0", "1"]
default: ["0"]

filedownloaddisable::
description: Lets you prevent the ActionScript FileReference API from performing file downloads
values: ["0", "1"]
default: ["0"]

fileuploaddisable::
description: Lets you prevent the ActionScript FileReference API from performing file uploads
values: ["0", "1"]
default: ["0"]

disableproductdownload::
description: Lets you prevent native code applications that are digitally signed and delivered by Adobe from being downloaded
values: ["0", "1"]
default: ["1"]

disablesockets::
description: enable or disable the use of the Socket.connect() and XMLSocket.connect() methods
values: ["0", "1"]
default: ["1"]

enablesocketsto::
description: Lets you create a whitelist of servers to which socket connections are allowed

enforcelocalsecurityinactivexhostapp::
description: Lets you enforce local security rules for a specified application.

legacydomainmatching::
description: Lets you specify whether SWF files produced for Flash Player 6 and earlier can execute an operation that has been restricted in a newer version of Flash Player
values: ["0", "1"]
default: ["0"]

localfilelegacyaction::
description: Lets you specify how Flash Player determines whether to execute certain local SWF files that were originally produced for Flash Player 7 and earlier
values: ["0", "1"]
default: ["0"]

allowuserlocaltrust::
description: Lets you prevent users from designating any files on local file systems
values: ["0", "1"]
default: ["0"]

localstoragelimit::
description: Lets you specify a hard limit on the amount of local storage that Flash Player uses (per domain) for persistent shared objects.
values: ["3"]
default: ["3"]

overridegpuvalidation::
description: Overrides validation of the requirements needed to implement GPU compositing
values: ["0", "1"]
default: ["0"]

rtmfpp2pdisable::
description: Specifies how the NetStream constructor connects to a server when a value is specified for peerID, the second parameter passed to the constructor
values: ["0", "1"]
default: ["1"]

disablenetworkandfilesysteminhostapp::
description: 1 (Acrobat.exe,Acroread.exe,WINWORD.EXE,EXCEL.EXE,POWERPNT.EXE,PPTVIEW.EXE,OUTLOOK.EXE,MSACCESS.EXE,VISIO.EXE,thunderbird.exe)
values: ["0", "1"]
default: ["1"]

* *Bekannte Probleme* +

- Beim Einspielen "On Demand" kann die Installation aufgrund geöffneter
Browser fehlschlagen!

[[opsi-manual-abo-products-standard-google-chrome]]
===== Google Chromium for Business
----
google-chrome-for-business 73.0.3683.103-1
----

Das Paket beinhaltet den msi-Installer von Google (Häufig gestellte
Fragen  Chrome for Business https://support.google.com/a/answer/188447).

Bemerkungen:

Die Deinstallation und Installation des google-chrome.msi schlägt manchmal fehl.

Daher gibt es verschiedene Ansätze im opsi-Paket, um die
Zuverlässigkeit der Installation zu erhöhen.

Ein Kunde berichtete von einer Erfolsquote von 100% bei 40 Installationen mit folgender Einstellung der Properties:

* `install_architecture`: 32
* `reboot_on_retry`: True
* `reboot_after_uninstall`: True
* `timeout`: 240

Intern verwenden wir für Tests:
* `install_architecture`: system specific
* `reboot_on_retry`: True
* `reboot_after_uninstall`: True
* `timeout`: notimeout


autoupdate:: !Property wirkt nicht mehr!

vgl.
https://support.google.com/chrome/a/answer/187207

gibt es 0,1,2,3 als Wert für
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Update\UpdateDefault

bzw ADM falls Gruppenrichtlinien verwendet werden

ADM= use Policy based on Googles Template,
0=UpdatesDisabled,
1=UpdatesEnabled,
2=ManualUpdatesOnly,
3=AutomaticUpdatesOnly,
values: ["0", "1", "2", "3", "ADM"]
default: ["0"]

disablescheduledtaskgoogleupdatemachine::
 
Disable scheduled task GoogleUpdateTaskMachineCore and GoogleUpdateTaskMachineUA
values: ["false", "true"]
default: ["true"]

removeupdatehelper::
default: ["true"]

install_architecture::
description: which architecture (32/64 bit) has to be installed
values: ["32", "64", "system specific"]
default: ["system specific"]

reboot_on_retry::
description: If installation fails and (timeout > 0) then reboot before retry
default: False

reboot_after_uninstall::
description: reboot after uninstall old version
default: False

timeout::
description: TimeOutSeconds msi installs
values: ["240", "300", "600", "notimeout"]
default: ["notimeout"]

[[opsi-manual-abo-products-standard-openoffice]]
===== Apache OpenOffice : ooffice4
----
ooffice                         4.1.1-6                  Apache OpenOffice
----

Das ooffice-Paket beinhaltet Apache OpenOffice in deutsch.

handle_excel_xls::

Soll OpenOffice.org fuer MS-Excel-Dokumente registriert werden
 on  = OpenOffice.org wird fuer MS-Exceldokumente registriert
 off = OpenOffice.org wird nicht fuer MS-Exceldokumente registriert

handle_powerpoint_ppt ::

Soll OpenOffice.org fuer MS-PowerPoint-Dokumente registriert werden
 on  = OpenOffice.org wird fuer MS-PowerPointdokumente registriert
 off = OpenOffice.org wird nicht fuer MS-PowerPointdokumente registriert

handle_word_doc ::

Soll OpenOffice.org fuer MS-Word-Dokumente registriert werden
 on  = OpenOffice.org wird fuer MS-Worddokumente registriert
 off = OpenOffice.org wird nicht fuer MS-Worddokumente registriert

[[opsi-manual-abo-products-standard-libreoffice]]
===== LibreOffice The Document Foundation  : libreoffice
----
libreoffice               6.0.6or6.1.0-2                   libreoffice
----

Das libreoffice-Paket beinhaltet LibreOffice 6 international.

client_language ::

client_language - only for messages important, cause libre office is international
values: ["auto", "de", "en", "fr"]

msoregister :: Open Microsoft Office documents with LibreOffice (true)
values: ["false", "true"]
default: ["false"]

libreoffice-version::
description: 'Stable' - is an Extended Support Release from LibreOffice for the conservative user - default version (6.0.6)'Experimentell' is a version for the experimentell user from LibreOffice (6.1.0)
values: ["experimentell", "stable"]
default: ["stable"]

hide_component::
description: Hide component base by removing desctoplink and exe file
values: ["base", "none"]
default: ["none"]

ui_languages::
description: which UI languages should be installed (comma separated), For example UI_LANGS=en_US,de,fr,hu will install English (US), German, French, and Hungarian.
default: ["auto"]

install_architecture:: which architecture (32/64 bit) has to be installed
values: ["32", "64", "system specific"]
default: ["32"]


[[opsi-manual-abo-products-standard-firefox]]
===== Mozilla Firefox : firefox
----
firefox                          60.6.1esror66.0.3-1
----
Das firefox-Paket beinhaltet Mozilla Firefox in den Sprachen deutsch, englisch, französisch und niederländisch.

Es werden alle von Mozilla unterstützten Versionen bereitgestellt.

Firefox kann zentral konfiguriert werden 
a) entweder über eine zentrale Konfigurationsdatei `mozilla.cfg` (vgl. http://kb.mozillazine.org/Locking_preferences) 
b) oder über eine `policies.json` (vgl. https://github.com/mozilla/policy-templates/blob/master/README.md)

die in folgendem Verzeichnis abzulegen ist:

[source,prompt]
----
/var/lib/opsi/depot/firefox/custom/
----

Bei erneutem Einspielen des Pakets mittels  `opsi-package-manager -i <firefox-paket>` werden die gefundenen Konfigurationsdateien über preinst-/postinst-Mechanismus erhalten und dann über das Property "mozillacfg" auswählbar.

- Beispiel:
+
[source,prompt]
----
cat /var/lib/opsi/depot/firefox/custom/mozilla.cfg
//
lockPref("browser.startup.homepage", "http://www.uib.de");
lockPref("network.proxy.type", 1);
lockPref("network.proxy.http", "router.uib.local");
lockPref("network.proxy.http_port", 3128);
----

Alternativ zu einer mozilla.cfg kann man auch eine mit dem CCK2 erstellte autoconfig.zip über das Property "mozillacfg" einbinden.

CAUTION: Bei Einsatz des Wan/VPN Moduls muss nach Änderungen im Verzeichnis `custom` das Paket neu eingespielt werden, damit die Datei `<productid>.files` neu erzeugt wird.


client_language::
      values: ["auto", "de", "en", "fr", "nl"]
      default: ["auto"]

firefox-version :: Firefox 'esr' - Extended Support Release from Mozilla.org, standard ist die aktuelle Firefox-Version

values: ["esr", "standard"]
default: ["esr"]

commandlineoptions::

started Firefox mit den angegebenen Optionen. vgl.: https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options
values: ["", "-no-remote -Profile H:\\ProfileDir"]
default: [""]

pref_file:: (user/prefs)= in welcher Datei sollen die Einstellungen
gemacht werden user.js oder prefs.js. values: ["prefs", "user"]
default: ["prefs"]

noautoupdate:: (on/off): auto update ausschalten. default=on

setproxy:: (off/direct/manual/file) proxy einstellungen verändern
*  off= tue nichts
*  direct = direkte Verbindung zum Internet
*  manual = Proxyeinstellungen über property proxysetting
(<ip-numme>:<port>) und property noproxy_hosts (host1,host2)
*  file = Proxyeinstellungen über property proxysetting
(<path_to_proxyconf.pac>) und property noproxy_hosts (host1,host2)
* system
* default=off

proxysetting:: string für proxy Einstellung (siehe: setproxy)

noproxy_hosts:: Komma separierte Liste von hosts

mozillacfg::
description: filename for mozilla.cfg in `%scriptpath%\custom`-directory, http://kb.mozillazine.org/Locking_preferences

profilemigrator:: enable or disable Profilemigrator on first run
values: ["off", "on"]
default: ["off"]

* *Bekannte Probleme* +
- Beim Einspielen "On Demand" kann die Installation aufgrund geöffneter Programme fehlschlagen!

[[opsi-manual-abo-products-standard-thunderbird]]
===== Mozilla Thunderbird : thunderbird
----
thunderbird               60.6.1-1
----
Das thunderbird-Paket beinhaltet Mozilla Thunderbird in den Sprachen deutsch, englisch und französisch.

Es werden alle von Mozilla unterstützten Versionen bereitgestellt.

Analog dem Firefox-Paket kann zentrale Konfigurationsdatei bereitgestellt werden.

client_language::
values: ["auto", "de", "en", "fr"]
default: ["auto"]

thunderbird-version::
values: ["60.x"]
default: ["60.x"]

commandlineoptions::

starte thunderbird mit den angegebenen Parametern, vgl.:  https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options
values: ["", "-no-remote -Profile H:\\ProfileDir"]
default: [""]

addonsactivation::
description: Enable/Disable AddOns (default = enable)
values: ["off", "on"]
default: ["on"]

https://developer.mozilla.org/en/Addons/Add-on_Manager/AddonManager

http://mike.kaply.com/2012/02/09/integrating-add-ons-into-firefox/

https://developer.mozilla.org/en/Thunderbird/Deploying_Thunderbird_in_the_Enterprise/Thunderbird_Preferences_Relevant_to_Enterprises
[source,prompt]
----
Set_Netscape_User_Pref ("extensions.autoDisableScopes", 11)
Set_Netscape_User_Pref ("extensions.shownSelectionUI", true)
----


enigmail::
description: Install GnuPG-Plugin
values: ["off", "on"]
default: ["off"]

noautoupdate::
description: disable automatic updates
values: ["off", "on"]
default: ["on"]

mozillacfg::
description: filename for mozilla.cfg in `%scriptpath%\custom`-directory, http://kb.mozillazine.org/Locking_preferences


lightning::
description: Install calender plugin lightning
values: ["off", "on"]
default: ["off"]

* *Bekannte Probleme* +
- Beim Einspielen "On Demand" kann die Installation aufgrund geöffneter Programme fehlschlagen!

[[opsi-manual-abo-products-standard-javavm]]
===== OpenJDK 11 LTS : javavm
----
javavm              11.0.3-1                  JDK 11
----
Das javam Paket enthält die Open JDK 11 LTS Implementationen von SAP (SapMachine) und Amazon (Amazon Corretto) da Oracle keine frei verfügbare JAVA-Runtime mehr zur Verfügung stellt (seit Anfang Januar 2019

(Oracle announced "End Of Public Updates Februar 2019"  http://www.oracle.com/technetwork/java/eol-135779.html)


install_architecture::
description: which architecture (32/64 bit) has to be installed
values: ["64 only"]
default: ["64 only"]

javaversion::
 
which version has to be installed jdk Sapmachine or amazon corretto
values: ["jdkamazoncorretto", "jdksap"]
default: ["jdksap"]

keepversion::
description: Don't uninstall jre version
values: ["1.6.0_0", "1.6.0_1", "1.6.0_2", "1.6.0_3", "1.6.0_4", "1.6.0_5", "    1.6.0_6", "1.6.0_7", "none"]
default: ["none"]

uninstalljava16::
description: Uninstall Java 1.6 "Patch in Place" Installations
default: True

uninstalljava17::
description: Uninstall Java 1.7 "Patch in Place" Installations
default: True

environment_set_java_home:: Set the environment variable JAVA_HOME
default: False


[[opsi-manual-abo-products-standard-javavm8]]
===== OpenJDK 8 LTS : javavm8
----
javavm8              1.8.0.212or1.8.0.201-1		JDK 8 LTS
----
Das javam8 Paket enthält die Open JDK 8 LTS Implementationen von und Amazon (Amazon Corretto) und ojdkbuild (https://github.com/ojdkbuild/ojdkbuild).
Letzteres enthlt eine auf Iced-Tea basierende Webstart-Komponente.


javaversion::

which version has to be installed amazon 212 or ojdkbuild 201
values: ["jdkamazoncorretto", "ojdkbuild"]
default: ["jdkamazoncorretto"]
 
install_architecture::

which architecture (32/64 bit) has to be installed
values: ["32 only", "64 only", "both", "system specific"]
default: ["system specific"]


keepversion::
description: Don't uninstall jre version
values: ["1.6.0_0", "1.6.0_1", "1.6.0_2", "1.6.0_3", "1.6.0_4", "1.6.0_5", "    1.6.0_6", "1.6.0_7", "none"]
default: ["none"]

uninstalljava16::
description: Uninstall Java 1.6 "Patch in Place" Installations
default: True

uninstalljava17::
description: Uninstall Java 1.7 "Patch in Place" Installations
default: True

environment_set_java_home:: Set the environment variable JAVA_HOME
default: False

[[opsi-manual-abo-products-standard-javavm-oracle-jdk]]
===== OpenJDK : javavm-oracle-jdk
----
javavm-oracle-jdk         12.0.1-1                  Open JDK 
----
Das javavm-oracle-jdk Paket enthält die aktuelle Open JDK Implementation von Oracle http://jdk.java.net/  

install_architecture::
description: which architecture (32/64 bit) has to be installed
values: ["64 only"]
default: ["64 only"]

keepversion::
description: Don't uninstall jre version
values: ["1.6.0_0", "1.6.0_1", "1.6.0_2", "1.6.0_3", "1.6.0_4", "1.6.0_5", "    1.6.0_6", "1.6.0_7", "none"]
default: ["none"]

uninstalljava16::
description: Uninstall Java 1.6 "Patch in Place" Installations
default: True

uninstalljava17::
description: Uninstall Java 1.7 "Patch in Place" Installations
default: True

environment_set_java_home:: Set the environment variable JAVA_HOME
default: False

