////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      29.09.2023
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

= Migration zu opsi 4.3

In diesem Kapitel wird der Umstieg von opsi 4.2 nach opsi 4.3 beschrieben.
Serverseitig werden so gut wie alle Distributionen wie für opsi 4.2 unterstützen. Nicht mehr unterstütz werden folgende Systeme:

* debian 9
* ubuntu 18.04
* openSUSE Leap 15.3

Vergleiche xref:supportmatrix:supportmatrix.adoc[]

Wir empfehlen dringend for dem Upgrade eine Sicherung der Backends mit opsibackup zu erstellen:

[source,bash]
----
opsi-backup create
----

Alle opsi-Komponenten, die im Rahmen dieses Releases veröffentlicht werden, sind an vielen Stellen voneinander abhängig. Es sollten daher immer alle Komponenten aktualisiert werden.

Wir empfehlen zuerst den Server und danach die opsi-Pakete (Produkte) zu aktualisieren.
In einer Multi-Depot-Umgebung wird empfohlen die Aktualisierung auf dem Configserver zu beginnen und erst danach die Depots zu aktualisieren.

opsi 4.3 verwendet nur noch das freie MySQL-Backend. 
Die Migration von einem file-Backend erfolgt automatisch beim Upgarde der Server-Paketen.