////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      29.09.2023
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

= Wichtige Hinweise

opsi 4.3 ist ein eigenständiges Release und hat seine eigenen Repositories. Diese neuen Repositories müssen dem System hinzugefügt und die Repositories der Vorgängerversion entfernt werden. Erst danach kann die Installation / das Upgrade durchgeführt werden.

Für ein Upgrade von opsi 4.2 müssen die installierten Pakete auf dem letzten opsi 4.2 stable Stand sein. Andere Pakete - wie z.B. MySQL server - sollten ebenfalls aktuell sein. Anderenfalls kann es zu Fehlern im Upgrade-Prozess kommen.

Es wird ebenfalls dringend empfohlen vor dem Upgrade die Pakete, 'opsi-script' und `{opsi-client-agent}`, `opsi-linux-client-agent` bzw. `opsi-mac-client-agent` auf allen Clients auf die aktuellsten opsi 4.2-Versionen zu aktualisieren.

== Aktualisieren der Betriebssystem-Pakete

Bitte stellen Sie sicher, dass Sie zum Zeitpunkt der Aktualisierung die jeweils aktuellsten Pakete von opsi 4.2 aus dem Stable-Bereich verwenden!


== Aktualisieren von opsi-Paketen

opsi-Pakete sind in der Regel kompatibel zu sowohl opsi 4.2 als auch opsi 4.3.

Die offiziellen opsi 4.3-Repositories auf link:https://opsipackages.43.opsi.org enthalten Pakete, welche mit opsi 4.3 kompatibel sind.
Bitte beachten Sie, dass diese Pakete nicht zwingend `4.3` als Version angegeben haben müssen, um kompatibel zu sein.


== Backend Erweiterungen (/etc/opsi/backendManager/extend.d)

Die bisherigen Extender-Methoden sind jetzt in opsiconfd hardcodiert; /etc/opsi/backendManager/extend.d wird daher jetzt leer ausgeliefert und beim Upgrade verschoben.
Der Extender-Mechanismus kann aber weiter verwendet werden.
Eigene Extender-Methoden, die weiter verwendet werden sollen, müssen nach dem Upgrade auf 4.3 dann wieder in den Ordner `/etc/opsi/backendManager/extend.d` gelegt werden.

== Workbench, Depot und Repository

opsi 4.3 verwendet jetzt feste Verzeichnisse für Workbench, Depot und Repository unterhalb von `/var/lib/opsi`. Die Depot-Konfigurationen _depotLocalUrl_, _repositoryLocalUrl_, _workbenchLocalUrl_ werden nicht mehr ausgewertet. 
Wenn die Verzeichnisse an anderer Stelle liegen, müssen sie manuell verschoben oder Symlinks angelegt werden.

== opsi-Linux-Bootimage

Die Bootloader im opsi-Linux-Bootimage liegen jetzt unter `<TFTP-ROOT>/opsi/opsi-linux-bootimage/loader`. 
Die Namen der Bootloader sind jetzt opsi-netboot.bios (Legacy-BIOS) und opsi-netboot.efi (UEFI-BIOS), shimx64.efi.signed (UEFI-Secureboot). 
Bei Verwendung von Netboot/PXE muss die DHCP-Server-Konfiguration unter Umständen manuell angepasst werden (Option 67/ BootFile Name).

== Sortier-Algorithmus

Es existiert nur noch ein (neuer) Sortier-Algorithmus für Produkt-Aktionen, eine Unterscheidung von `algorithm1/algorithm2` entfällt. Der neue Algorithmus produziert weitestgehend die gleichen Ergebnisse wie der alte `algorithm1`.

== opsi Tools

Die Anwendungen opsi-configed, opsi-webGui, opsi-setup-detector-setup und weitere stehen jetzt unter  link:https://tools.43.opsi.org/ zur Verfügung.

== Sonstiges

* Direkter Datenbank-Zugriff nur noch über den opsiconfd; alle anderen Komponenten verwenden die API.
* Upgrade und Cleanup der Datenbank erfolgen vollautomatisch.
* opsiconfd bietet jetzt einen Maintenance-Modus.
* IPv6-Unterstützung funktioniert nun für alle Komponenten.
* Produkt-Abhängigkeiten jetzt für jede Aktion definierbar.
* /etc/opsi/opsi.conf jetzt im TOML-Format. Vollautomatische Erstellung und Migration der opsi.conf. Sobald die Datei existiert, verwendet opsi den FQDN der Maschine nicht mehr.
* Server-Zertifikats-Prüfung ist in der Voreinstellung für alle Komponenten aktiviert, aber es erfolgt keine automatische Aktivierung beim Upgrade.
* Grafana fungiert jetzt in der Voreinstellung hinter opsiconfd als Reverse-Proxy.
* Neue Metriken im Grafana: Worker Connections, Messagebus Messages sent, Messagebus Messages received
* Repository-Meta-Dateien (packages.json) zur Verwendung durch opsi-package-updater
* opsi-Pakete werden standardmäßig im tar.zstd-Format erzeugt.
* Clients erben die Konfigurations-Einstellungen des zugeordneten Depots.
* Das Standardverzeichnis für temporäre Dateien ist jetzt /var/lib/opsi/tmp.
* opsi-configed kann Clients kopieren.
* Wechsel zu Python 3.11
* hostControl_-Methoden werden bevorzugt über den opsi-Messagebus ausgeführt (Konfiguration über useMessagebus in /etc/opsi/backends/hostcontrol.conf).
* opsi-setup wurde durch opsiconfd setup ersetzt.
* opsi-backup wurde durch opsiconfd backup/opsiconfd restore ersetzt.
