////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      24.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

= Installation

Das Programm steht unter https://download.uib.de/ in der jeweils aktuellsten Version als opsi-Paket zur lokalen Installation für Windows, Linux und macOS zur Verfügung. Dieses setzt voraus, dass auf dem Rechner bereits der Client-Agent installiert ist, damit Sie dort das Localboot-Produkt `opsi-configed` einspielen können.

Alternativ gibt es für alle drei Betriebssysteme unter link:https://tools.43.opsi.org/{release}/[] eine portable Anwendung, die ohne Installation läuft. Laden Sie den `opsi-configed` für Ihr Betriebssystem herunter: `opsi-configed-windows.exe` für Windows, `opsi-configed-linux.run` für Linux und `opsi-configed-macos` für macOS.

TIP: Sie können die zum Betriebssystem passende Version auch über den Webbrowser herunterladen: Geben Sie die Adresse \`https://<opsidepotserver>:4447/` ein, wechseln Sie zum Reiter _Links_ und klicken auf den Download-Link.

