////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      24.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-manual-configed-clients]]
= Clients

Einl.

[[opsi-manual-configed-client-selection]]
== Client-Auswahl

Nachdem Sie sich erfolgreich angemeldet haben, ist in der Mitte des Hauptfensters der Reiter _Clients_ aktiviert. Dort sehen Sie eine Liste der Clients

in der Voreinstellung die _Client-Konfiguration_. In der linken Seitenleiste ist die Liste der Clients aufgeklappt (siehe Abschnitt <<opsi-manual-configed-treeview>>). In der Mitte des Hauptfensters ist der Reiter _Clients_ aktiviert.




Nach erfolgreichem Login zeigt sich das Hauptfenster mit dem aktiviertem Karteireiter Clients zur Auswahl von Clients. Das Hauptfenster zeigt die Liste der Clients, wie sie durch die Depotwahl gegeben bzw. im 'Treeview' - s. Baumansicht - bestimmt ist.

Der opsi-configed speichert lokal auf dem Rechner, auf dem er läuft userbezogen die zuletzt getätigte Gruppenauswahl und aktiviert sie beim nächsten Start wieder.


das Kapitel hier beschreibt alles, was die Schaltfläche _Client-Konfiguration_ auch einblendet

Clients
Localboot-Produkte
Netboot-Produkte
Host-Parameter (Link zu Server-Konfiguration, Hinweis, dass bestimmte Parameter serverseitig gesetzt werden können)
Hardware-Informationen
Software-Informationen
Logdateien

Clients selbst bearbeiten
Außerdem befinden sich auf der rechten Seite Eigenschaften von dem ausgewählten Client, die bei Auswahl eines Clients editierbar sind.

Auflistung: clientspezifische Operationen (Kontextmenü, Menü _OpsiClient_:


Unter diesem Karteireiter erhalten Sie die letzten - entweder durch das Bootimage oder durch das Localboot-Produkt hwaudit erhobenen - Hardwareinformationen zum ausgewählten Client.

[[opsi-manual-configed-treeview]]
== Baumansicht 



