////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      24.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-manual-configed-client-selection]]
= Client-Auswahl

Nachdem Sie sich erfolgreich angemeldet haben, zeigt das Hauptfenster in der Voreinstellung die _Client-Konfiguration_. In der linken Seitenleiste ist die Liste der Clients aufgeklappt (siehe Abschnitt <<opsi-manual-configed-treeview>>).

das Kapitel hier beschreibt alles, was die Schaltfläche _Client-Konfiguration_ auch einblendet

Clients
Localboot-Produkte
Netboot-Produkte
Host-Parameter (Link zu Server-Konfiguration, Hinweis, dass bestimmte Parameter serverseitig gesetzt werden können)
Hardware-Informationen
Software-Informationen
Logdateien

Clients selbst bearbeiten
Außerdem befinden sich auf der rechten Seite Eigenschaften von dem ausgewählten Client, die bei Auswahl eines Clients editierbar sind.

Auflistung: clientspezifische Operationen (Kontextmenü, Menü _OpsiClient_:


Unter diesem Karteireiter erhalten Sie die letzten - entweder durch das Bootimage oder durch das Localboot-Produkt hwaudit erhobenen - Hardwareinformationen zum ausgewählten Client.

[[opsi-manual-configed-treeview]]
== Baumansicht 



