////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Revision:  4.3
:doctype: book


[[opsi-macclient-hints]]
= Allgemeine Hinweise zu macOS

[[opsi-macclient-hints-keyboard]]
== Das Keyboard unter macOS

include::mac-keyboard-hint.adoc[]

[[opsi-macclient-hints-homebrew]]
== Das opsi Produkt m-homebrew

// cspell: ignore macport, fink, brew, xcode

Es gibt für macOS eine Reihe von Paketverwaltungsprogrammen, welche es erlauben gängige Unix Programme unter macOS bereitzustellen. Typische Vertreter dieser Paketverwaltungsprogramme sind:

* _homebrew_ (https://brew.sh/)

* _macport_ (https://www.macports.org/)

* _fink_ (https://finkproject.org/)

Das opsi Produkt _m-homebrew_ installiert das _homebrew_ System auf einem macOS System.

_homebrew_ installiert den Befehl `brew` auf dem System mit dem sich dann aus dem Internet Programme herunterladen lassen. Dabei wird entweder direkt ein Binary installiert oder die Quellen heruntergeladen und das Programm auf der Maschine kompiliert. Daher braucht _homebrew_ auch die Entwicklungs-Kommandozeilen-Werkzeuge, um Programme zu kompilieren (`xcode-select --install`)

// cspell: ignore opsisetupadmin

_homebrew_ ist aus Sicherheitsgründen so konzipiert, das es *nicht als root* aufgerufen werden darf, sondern nur mit user Rechten. Um dies im opsi Kontext zu gewährleisten wird bei der Installation des _opsi-client-agent_ ein 'hidden user' Namens `opsisetupadmin` erzeugt (siehe auch <<opsi-macclient-hints-opsisetupadmin, Der macOS pseudo user opsisetupadmin>>).
Diesem user gehört das ganze _homebrew_ System auf der Maschine und daher sollte auch nur dieser user verwendet werden um über den Befehl `brew` Software auf der Maschine zu installieren.
D.h. Der Befehl `brew` sollte wie folgt als root aufgerufen werden:

[source,shell]
----
sudo -H -u opsisetupadmin /usr/local/bin/brew
----

// cspell: ignore javavm, winst, sapmachine, cask

Die Installation von Java im Produkt _m-javavm_ ist z.B. wie folgt implementiert:

[source,winst]
----
[ShellInAnIcon_brew_install_java]
; https://github.com/SAP/SapMachine/wiki/Installation
EXITCODE=0
sudo -H -u opsisetupadmin /usr/local/bin/brew tap sap/sapmachine
EC=$?; if [ $EC -ne 0 ]; then EXITCODE=$EC; fi
sudo -H -u opsisetupadmin /usr/local/bin/brew install --cask sapmachine-jdk
EC=$?; if [ $EC -ne 0 ]; then EXITCODE=$EC; fi
exit $EXITCODE
----

Um herauszufinden, ob die Installation eines gewünschten Produktes per _homebrew_ unterstützt wird, verwenden Sie am besten die folgende Webseite:
https://formulae.brew.sh/

Hilfreiche Links zu _homebrew_:

https://docs.brew.sh/

https://devhints.io/homebrew


[[opsi-macclient-hints-opsisetupadmin]]
== Der macOS Pseudo-user opsisetupadmin

Bei der Installation des _opsi-client-agent_ ein 'hidden user' namens _opsisetupadmin_ erzeugt. Dieser user hat kein Passwort und kann nicht für ein Login verwendet werden.

Das Heimatverzeichnis dieses Users ist `/var/opsisetupadmin`

Dieser User dient zu folgenden Zwecken:

* Bedienung des _homebrew_ Systems (siehe <<opsi-macclient-hints-homebrew, Das opsi Produkt m-homebrew>>)

// cspell: ignore depot, mounted, notifier, Library, daemons, systray

* Das Verzeichnis `/var/lib/opsisetupadmin/opsi_depot` ist der Einhängepunkt auf dem der opsiclientd den Depot-share mounted.

Dies wir so gemacht weil ein Zugriff auf Network-shares welche nicht in einem Nutzerverzeichnis gemountet werden stark eingeschränkt ist.

[[opsi-macclient-hints-opsi-files-dirs]]
== Die opsi Verzeichnisse auf macOS

Wesentliche opsi Verzeichnisse und Dateien auf dem macOS-Client

* /var/log/opsi-script (Log-Dateien des *opsi-script*)

* /var/log/opsi-client-agent (sonstige opsi Log-Dateien)

* /usr/local/bin/opsi*  (Kommandozeilen-Programme)

* /Applications/opsi-script-gui.app (App-Verzeichnis des *opsi-script*)

* /Applications/opsi-notifier.app (App-Verzeichnis des *opsi-notifier*)

* /etc/opsi-client-agent (Konfiguration *opsi-mac-client-agent*)

* /etc/opsi-script (Konfiguration *opsi-script*)

* /usr/local/lib (Hilfs-Bibliotheken z.B. ssl)

* /usr/local/lib/opsiclientd

* /usr/local/bin/locale (locale *opsi-script*)

* /usr/local/share/opsi-client-agent

* /usr/local/share/opsi-script

* /usr/local/share/notifier.d

* /var/opsisetupadmin (Heimatverzeichnis `opsisetupadmin`)

* /var/lib/opsi-client-agent

* /Library/LaunchDaemons/ (Start Konfiguration für opsi daemons)

* /Library/LaunchAgents/ (Start Konfiguration für *opsi-systray*)






[[opsi-macclient-hints-directories]]
== macOS Directory Struktur mit 'go' und 'nogo'

macOS basiert auf BSD-Unix und hat damit eine typische Unix Filesystemstruktur.
Es gibt aber aus Sicherheitsgründen etliche Bereich die ausschließlich Apple vorbehalten sind und noch ein paar weiter Spezifika welche für den Paketierer wichtig sind:

* `/Applications`

Das ist das Verzeichnis in dem die grafischen Anwendungen liegen. Eine Anwendung besteht dabei aus eine Verzeichnis <Application name>.app. Ein solches Verzeichnis wird aber im `Finder` nicht als Verzeichnis angezeigt, sondern als 'Anwendung'. Innerhalb dieses Verzeichnisses müssen sich nach einem bestimmten Muster die Dateien der Anwendung befinden.

* `/sbin`, `/bin`, `/usr/bin`, `/usr/share`, `/usr/lib`

Dies sind 'apple only' Verzeichnisse in die sonst niemand etwas reinkopieren darf. Verwenden Sie stattdessen die `local` Varianten:
`/usr/local/bin`, `/usr/local/share`, `/usr/local/lib`