////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      11.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-macclient-hints]]
= Allgemeine Hinweise zu macOS

[[opsi-macclient-hints-keyboard]]
== Apple-Tastaturen

include::mac-keyboard-hint.adoc[]

[[opsi-macclient-hints-homebrew]]
== Das opsi-Produkt *m-homebrew*

// cspell: ignore macport, fink, brew, xcode

Es gibt eine Reihe von Paketverwaltungs-Programmen für macOS, mit denen Sie gängige Open-Source-Anwendungen unter macOS installieren können:

* link:https://brew.sh/[Homebrew]

* link:https://www.macports.org/[MacPorts]

* link:https://finkproject.org/[Fink]

Wir stellen ein eigenes Localboot-Produkt zur Verfügung, das Homebrew auf macOS-Clients installiert: `m-homebrew`. Nach der Installation steht unter macOS der neue Befehl `brew` bereit, mit dem Sie aus dem Internet Programme herunterladen und installieren können. Die Paketverwaltung installiert entweder fertig kompilierte Binarys oder lädt die Quellen herunter und baut das Programm dann auf dem Rechner. 

NOTE: Homebrew benötigt die Kommandozeilen-Werkzeuge für Entwickler. Das Paket `m-homebrew` hängt daher vom opsi-Paket `m-xcode-tools` ab, das automatisch installiert wird. 

// cspell: ignore opsisetupadmin

Homebrew ist aus Sicherheitsgründen so konzipiert, dass der Befehl `brew` *nicht als Benutzer `root`* aufgerufen werden darf. Aus diesem Grund wird bei der Installation des Client-Agent ein ausgeblendeter Account („hidden user“) namens `opsisetupadmin` erzeugt (siehe Abschnitt <<opsi-macclient-hints-opsisetupadmin>>). Dem Account `opsisetupadmin` „gehört“ das gesamte Homebrew-System, und daher sollte dieser Account auch verwendet werden, um mit `brew` Software auf dem Rechner zu installieren.

So rufen Sie das `brew`-Kommando als Benutzer `opsisetupadmin` mit `root`-Rechten auf:

[source,console]
----
sudo -H -u opsisetupadmin /usr/local/bin/brew
----

// cspell: ignore javavm, winst, sapmachine, cask

Dieses Vorgehen nutzt auch das Produkt `m-javavm` zur Installation der Java-Laufzeitumgebung:

[source,ini]
----
[ShellScript_brew_install_java]
; https://github.com/SAP/SapMachine/wiki/Installation
EXITCODE=0
sudo -H -u opsisetupadmin /usr/local/bin/brew tap sap/sapmachine
EC=$?; if [ $EC -ne 0 ]; then EXITCODE=$EC; fi
sudo -H -u opsisetupadmin /usr/local/bin/brew install --cask sapmachine-jdk
EC=$?; if [ $EC -ne 0 ]; then EXITCODE=$EC; fi
exit $EXITCODE
----

=== Homebrew: Tipps und Tricks

Im Folgenden haben wir ein paar Links zum Thema zusammengestellt:

* https://formulae.brew.sh/: Finden Sie heraus, ob die Installation eines gewünschten Produktes per Homebrew unterstützt wird.

* https://docs.brew.sh/: Homebrew-Handbuch (in englischer Sprache)

* https://devhints.io/homebrew: Homebrew-Cheatsheet


[[opsi-macclient-hints-opsisetupadmin]]
== Der macOS-Account *opsisetupadmin*

// cspell: ignore depot, mounted, notifier, Library, daemons, systray

Wie erwähnt, wird bei der Installation des Client-Agent ein ausgeblendeter Account („hidden user“) namens `opsisetupadmin` erzeugt. Dieser Benutzer hat kein Passwort, und Sie können ihn nicht für einen Login verwenden. Das Home-Verzeichnis des Accounts ist `/var/opsisetupadmin`. Der Account `opsisetupadmin` darf den `brew`-Befehl aufrufen. Das Verzeichnis `/var/opsisetupadmin/opsi_depot` ist der Einhängepunkt, auf dem der `opsiclientd` die Depot-Freigabe mountet.

NOTE: Die Freigabe ist unterhalb vom Home-Verzeichnis des Benutzers `opsisetupadmin` gemountet, da Zugriffe auf Freigaben, die nicht in einem Benutezrverzeichnis eingehängt sind, stark eingeschränkt sind.

[[opsi-macclient-hints-fulldiskaccess]]
== Vollständigen Festplattenzugriff gewähren

Mit den im Dezember 2023 von Apple offiziell veröffentlichten Updates für macOS ist es notwendig, dem Prozess `opsiclientd` vollen Festplattenzugriff zu gewähren, um den normalen Betrieb des `opsi-mac-client-agent` zu ermöglichen. Diese Einstellung können Sie in den macOS-Systemeinstellungen unter _Datenschutz & Sicherheit_ oder per Apple-MDM-Nachricht vom Typ `PrivacyPreferencesPolicyControl` vornehmen. Für den Betrieb im WAN-Modus ist dieser Schritt nicht erforderlich.

[[opsi-macclient-hints-opsi-files-dirs]]
== opsi-Verzeichnisse unter macOS

Auf einem macOS-Client gibt es folgende wichtige opsi-Verzeichnisse:

* `/var/log/opsi-script`: `opsi-script`-Logdateien

* `/var/log/opsi-client-agent`: sonstige opsi-Logdateien

* `/usr/local/bin/opsi*`: ausführbare opsi-Programme

* `/Applications/opsi-script.app`: Programmverzeichnis von `opsi-script` 

* `/etc/opsi-client-agent`: Konfigurationsdateien des macOS-Client-Agent

* `/etc/opsi-script`: `opsi-script`-Konfigurationsdateien

* `/usr/local/lib`: Hilfs-Bibliotheken, z.{nbsp}B. für SSL, Ncurses usw.

* `/usr/local/share/opsi-client-agent`: Client-Agent

* `/usr/local/share/opsi-script`: `opsi-script`

* `/var/opsisetupadmin`: Home-Verzeichnis des Accounts `opsisetupadmin`

* `/var/lib/opsi-client-agent/opsiclientd`: SQLite-Datenbank für die Timeline auf der `opsiclientd`-Infoseite (siehe Abschnitt xref:clients:macos-client/mac-client-agent.adoc#opsi-manual-clientagent-infopage[*opsiclientd*-Infoseite])

* `/Library/LaunchDaemons`: Konfiguration für opsi-Dienste

* `/Library/LaunchAgents`: Konfiguration für das Systray-Programm


// cspell: ignore Paketierer, apple

[[opsi-macclient-hints-directories]]
== Besonderheiten für Paketierer

macOS basiert auf BSD-Unix und hat damit eine typische Unix-Dateisystem-Struktur. Aus Sicherheitsgründen gibt es Bereiche, die ausschließlich Apple vorbehalten sind. Für das Erzeugen von macOS-opsi-Produkten sind folgende Hinweise wichtig:

* `/Applications`: Hier liegen die grafischen Anwendungen. Jedes Programm hat seinen eigenen Ordner in `/Applications`; die Verzeichnisse heißen `<Programm>.app`. Der Finder zeigt solche Verzeichnisse allerdings nicht als Ordner an, sondern als Programmstarter für die jeweilige Anwendung. Die `<Programm>.app`-Verzeichnisse folgen einem bestimmten Aufbau.

* Die Verzeichnisse `/sbin`, `/bin`, `/usr/bin`, `/usr/share` und `/usr/lib` sind Apple vorbehalten. Für eigene Anpassungen verwenden Sie die Verzeichnisse `/usr/local/bin`, `/usr/local/share` und `/usr/local/lib`.
