////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      09.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-macclient-introduction]]
= macOS-Clients
// cspell: ignore paketieren, opsisetupadmin

Diese Anleitung beschreibt den Betrieb von macOS-Clients in opsi-Umgebungen. Dabei geht es im Wesentlichen um die folgenden Themen:

* macOS-Rechner in opsi aufnehmen und einbinden
(Installation des xref:clients:macos-client/macos-client-agent.adoc[Client-Agent])
* Standardsoftware auf dem opsi-Server bereitstellen
* Standardsoftware auf den macOS-Clients installieren
* opsi-Pakete erstellen und eigene Software paketieren
* Hinweise zu macOS-Clients
    ** spezielle Befehle für macOS
    ** Verzeichnisse, die Sie verwenden dürfen
    ** Pseudo-Account `opsisetupadmin`

NOTE: Voraussetzung für die Verwaltung von macOS-Clients ist, dass ein xref:server:overview.adoc[opsi-Server] bereits installiert und betriebsbereit ist.

[[opsi-winclient-convention]]
include::ROOT:partial$conventions.adoc[]
