////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      30.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-manual-mac-client-agent]]
= Client-Agent (macOS)

include::common:partial$opsi-client-agent.adoc[]

[[opsi-manual-client-agent-macos-directories]]
== Wichtige Verzeichnisse

Die Bestandteile des macOS-Client-Agent liegen unter `/usr/local/lib`. Die ausführbaren opsi-Programme finden Sie in `/usr/local/bin`; das Verzeichnis ist im Standardpfad enthalten. Die Konfigurationsdatei `opsiclientd.conf` liegt im Verzeichnis `/private/etc/opsi-client-agent/`; zum Lesen und Bearbeiten sind `root`-Rechte erforderlich.

Logfiles finden Sie in den Verzeichnissen unterhalb von `/private/var/log/`. `/private/var/log/opsi-client-agent` enthält die Protokolle von `opsiclientd` und `opsi-notifier`. `opsi-script` und der Client-Agent legen die Logs in `/private/var/log/opsi-script` ab.
