////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      16.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons: font
:xrefstyle: full
:lang: de


[[opsi-macclient-introduction]]
= Einführung

Diese Anleitung beschreibt den Betrieb von macOS-Clients in opsi.

NOTE: Voraussetzung ist, dass ein xref:server:overview.adoc[opsi-Server] bereits installiert und betriebsbereit ist.

Wesentliche Themen dieser Anleitung:

// cspell: ignore paketieren, opsisetupadmin

. macOS-Rechner in opsi aufnehmen und einbinden
(Installation des xref:clients:client-agent/opsi-client-agent.adoc[Client-Agent])
. opsi-Standardsoftware für macOS auf dem opsi-Server bereitstellen
. Standardsoftware auf den macOS-Clients installieren
. opsi-Pakete erstellen und eigene Software paketieren
. Hinweise zu macOS-Clients
.. Spezielle Befehle für macOS
.. Verzeichnisse, die Sie verwenden dürfen
.. Der Pseudo-Account `opsisetupadmin`

[[opsi-winclient-convention]]
include::ROOT:partial$conventions.adoc[]
