////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype: book
:macosclientmanual: opsi-macos-client-manual

include::common:partial$opsi_terms.adoc[]



[[opsi-macclient-installation-config-get-essential-products]]
= Einspielen der minimalen macOS {opsi-products}

Zur Verteilung von Software mit opsi stehen fertige Produkte zur Installation bereit.
Diese beinhalten unter anderem den Agent ('opsi-client-agent'), welcher für das Management auf Clients installiert werden muss.

Es gibt eine automatische und manuelle Möglichkeit dies zu tun.
Der automatisierte Weg wird empfohlen.

[[opsi-macclient-std-packages]]
== opsi-Standardsoftware für macOS unter opsi

Folgende Produkte werden von opsi für macOS als Standard zur Verfügung gestellt:

* `opsi-mac-client-agent`
* `swaudit`
* `hwaudit`
* `m-homebrew` (siehe auch: xref:general-notes#opsi-macclient-hints-homebrew[Das opsi Produkt m-homebrew])
* `m-system-update`
* `opsi-configed`
* `opsi-logviewer`
* `opsi-auto-update`
* `m-javavm`
* `opsi-setup-detector`
* `windomain`

////
* `opsi-client-kiosk`

* ``
////


[[opsi-macclient-installation-config-get-essential-products-automatic]]
== Automatisches Einspielen der minimalen macOS {opsi-products}

Zur automatischen Installation der {opsi-products} gibt es das Werkzeug `opsi-package-updater`, welches wie in '/etc/opsi/opsi-package-updater.conf' bzw. `/etc/opsi/package-updater.repos.d/` konfiguriert, automatisch die aktuellen Pakete vom opsi Repository holt und auf dem Server installiert.

Die Konfiguration der opsi Repositories für Mac-Clients findet sich im Verzeichnis `/etc/opsi/package-updater.repos.d/` in den Dateien `uib-mac-testing.repo` und `uib-mac.repo`.

Aktivieren Sie die gewünschten repos in dem Sie in der gewünschten *.repo Datei den Eintrag `active = true` setzen.

.`/etc/opsi/package-updater.repos.d/uib-mac-testing.repo`

[source,configfile]
----
; This repository provides testing opsi products for managing macOS
; clients with opsi.

[repository_uib_macos_testing]
description = opsi macOS packages in testing
active = true
baseUrl = http://download.uib.de
dirs = opsi4.2/testing/packages/macos/localboot/
autoInstall = false
autoUpdate = true
autoSetup = false
; Set Proxy handler like: http://10.10.10.1:8080
proxy =
----


.`/etc/opsi/package-updater.repos.d/uib-mac.repo`

[source,configfile]
----
; This repository provides table opsi roducts for managing macOS
; clients with opsi.

[repository_uib_macos_stable]
description = opsi macOS packages in stable
active = true
baseUrl = http://download.uib.de
dirs = opsi4.2/stable/packages/macos/localboot/
autoInstall = false
autoUpdate = true
autoSetup = false
; Set Proxy handler like: http://10.10.10.1:8080
proxy =
----

Installieren Sie die Pakete auf dem Server durch die Ausführung des Befehls als root:

[source,shell]
----
opsi-package-updater -v --repo uib_macos_stable install
----

bzw.

[source,shell]
----
opsi-package-updater -v --repo uib_macos_testing install
----

Nach erfolgreicher Installation müssen Sie beim _opsi-configed_ ein erneutes laden aller Daten ausführen, damit die neuen Produkte dort sichtbar werden.

Muss für den Zugriff auf das Internet die Verbindung über einen Proxy geleitet werden, so muss dieser in den `.repo`-Konfigurationsdateien unter `/etc/opsi/package-updater.repos.d/` als Wert für `proxy` eingetragen werden.
Ab Version 4.1.1.33 von opsi-utils kann ein globaler Proxy in `/etc/opsi/opsi-package-updater.conf` konfiguriert werden.

[source,configfile]
----
[repository_uib_macos_stable]
…
proxy =
----

Sollen später installierte Pakete aktualisiert werden, so kann dies mit dem folgenden Befehl gemacht werden:
[source,shell]
----
opsi-package-updater -v update
----

Weitere Informationen zum `opsi-package-updater` können im Handbuch gefunden werden.



[[opsi-macclient-installation-config-get-essential-products-manually]]
== Manuelles Einspielen der macOS {opsi-products}

Es gibt auch die Möglichkeit manuell die Pakete herunter zu laden und zu installieren.

Holen Sie sich die aktuellen opsi-Pakete im `.opsi`-Paketformat.
Die Pakete finden Sie unter https://download.uib.de/opsi4.2/stable/packages/macos/localboot bzw. unter `https://download.uib.de/opsi4.2/testing/packages/macos/localboot`.

Wir empfehlen die .opsi-Dateien unter `/var/lib/opsi/repository` zu speichern.
Zum Sicherstellen, dass {opsiconfd} auf die Dateien zugreifen kann, sollte `opsi-set-rights /var/lib/opsi/repository` ausgeführt werden.

Nach dem Download müssen Sie die Pakete auf dem Server mit dem Befehl `opsi-package-manager -i <paketname>.opsi` installieren.