////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:toc: left
:toclevels: 3
:numbered:
:icons: font
:xrefstyle: full
:doctype:   book
:date:      01.04.2022
:lang: de

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]


= opsi macOS client manual

// Include common opsi copyright
include::../common/opsi_manual_copyright.asciidoc[]


[[opsi-macclient-introduction]]
== Einführung macOS Clients in opsi

Diese Anleitung beschreibt den Betrieb von macOS Clients in opsi.

Es wird voraus gesetzt, das die Installation und Inbetriebnahme eines {opsi-Server}s bereits erfolgt ist.

Wesentliche Themen dieser Anleitung:

. Aufnahme und Einbindung von Mac-Rechnern in opsi
(Installation des opsi-mac-client-agent)
. Bereitstellung von opsi Standardsoftware für Mac auf dem opsi-server
. Installation von Standard Software auf den Mac-Clients
. opsi-Standardsoftware für Mac unter opsi
. Paketierung eigener Software
. Erstellung von opsi-Paketen
. Hinweise zu Mac Clients
.. Spezielle Befehle für macOS
.. Directories die Sie verwenden dürfen
.. Der pseudo user opsisetupadmin

[[opsi-macclient-convention]]
== Konventionen dieses Dokuments

Befehle werden gesondert hervorgehoben:

[source,shell]
----
dies ist ein Befehl
----

Im Rahmen der Installation und Konfiguration können Sie die Befehle aus diesen Feldern in der Regel der Reihe nach per _copy & paste_ aus diesem Dokument kopieren und ausführen.

Einzelne Befehle oder Dateinamen werden so hervorgehoben: `opsi-set-rights` oder `/Applications/opsi-script`.

Das ist ein opsi-script Code:

[source,winst]
----
Message "Installing "+ $ProductId$ +" ..."
----

Kapitel welche den Namen einer bestimmten Plattform enthalten sind spezifisch für diese Plattform. Die unterstützen Plattformen sind:

* *Windows*

* *Linux*

* *macOS*


include::requirements.adoc[]

include::minimal-products.adoc[]

include::adding-clients.adoc[]

include::rollout-products.adoc[]

include::softwareintegration.adoc[]

include::general-notes.adoc[]

include::more.adoc[]
