////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      16.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons: font
:xrefstyle: full
:lang: de

[[opsi-macclient-requirements]]
= Voraussetzungen für macOS Clients

Nachfolgend werden die Voraussetzungen für das Management von macOS Clients unter opsi beschrieben.

Der opsi-mac-client-agent ist eine
http://uib.de/de/opsi-erweiterungen/erweiterungen/[opsi Erweiterung]. +
Das bedeutet, dass Sie zum Einsatz eine Freischaltdatei benötigen. Diese Freischaltung erhalten Sie wenn Sie die Erweiterung kaufen. Zu Evaluierungszwecken stellen wir Ihnen auch eine zeitlich befristete Freischaltung kostenlos zur Verfügung ( -> mail an info@uib.de). +
//Weitere Details hierzu finden Sie in xref:opsi-modules:macos.adoc[opsi-modules MacOS]
//TODO: macos modules Kapitel fehlt?

Unterstützte macOS Versionen:

include::4.3@opsi-docs-en:common:partial$supportmatrix-macclient-core.adoc[]

// cspell: ignore Translators, rosetta, agree, pkgs, apple

Bei Verwendung der arm64 Architektur (Apple Silicium, M1) ist derzeit die Installation des opsi-client-agent der 'Dynamic Binary Translators' namens `rosetta2` notwendig. Diesen können Sie Installieren mit: +
`softwareupdate --install-rosetta --agree-to-license`
Die erfolgreiche Installation können Sie Überprüfen mit: +
`pkgutil --pkgs | grep Rosetta` +
`com.apple.pkg.RosettaUpdateAuto`.

Die native Unterstützung der arm64 Architektur (Apple Silicium) ist in Planung. Hierzu sind die notwendigen Referenz Geräte bestellt. Aussagen wann die Bereitstellung für diese Plattform erfolgt können im Moment (Januar 2021) noch nicht getroffen werden.
