////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      09.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-macclient-requirements]]
= Voraussetzungen

Dieses Kapitel beschreibt die Voraussetzungen für das Management von macOS-Clients unter opsi. Als Erstes listet eine Tabelle die unterstützten macOS-Versionen für opsi 4.3 auf; danach geben wir Hinweise zum Arm-basierten Prozessor Apple M1.

NOTE: Der macOS-Client-Agent ist eine link:http://uib.de/de/opsi-erweiterungen/erweiterungen/[kostenpflichtige Erweiterung]. Das heißt, dass Sie eine Freischaltdatei benötigen. Sie erhalten diese, nachdem Sie die Erweiterung gekauft haben. Zu Evaluierungszwecken stellen wir Ihnen kostenlos eine zeitlich befristete Freischaltung zur Verfügung. Bitte kontaktieren Sie uns dazu per mailto:info@uib.de[E-Mail].

== Unterstützte macOS-Versionen

include::{version}@opsi-docs-en:common:partial$supportmatrix-macclient-core.adoc[]

== Mac-Computer mit Apple-Chip
// cspell: ignore Translators, rosetta, agree, pkgs, apple

Wenn Sie einen Mac mit dem M1-Arm-Prozessor von Apple haben, benötigen Sie zur Installation des opsi-Client-Agent das Rosetta-Framework. Eine Möglichkeit, Rosetta zu installieren:

[source,console]
----
softwareupdate --install-rosetta --agree-to-license
----

Das die Installation erfolgreich war, können Sie mit dem `pkgutil`-Kommando überprüfen. Sie sollten beispielsweise eine Ausgabe wie diese sehen:

[source,console]
----
$ pkgutil --pkgs | grep Rosetta
com.apple.pkg.RosettaUpdateAuto
----

NOTE: Eine native Unterstützung für Geräte mit M1-Arm-Prozessor ist geplant und die notwendige Test-Hardware bestellt. Wann die native Unterstützung fertig implementiert ist, können wir derzeit (Stand: Januar 2021) nicht genau sagen.
