////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      09.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-macclient-requirements]]
= Voraussetzungen

Dieses Kapitel beschreibt die Voraussetzungen für das Management von macOS-Clients unter opsi. Als Erstes listet eine Tabelle die unterstützten macOS-Versionen für opsi 4.3 auf; danach geben wir Hinweise zum Arm-basierten Prozessor Apple M1.

NOTE: Der macOS-Client-Agent ist eine link:http://uib.de/de/opsi-erweiterungen/erweiterungen/[kostenpflichtige Erweiterung]. Das heißt, dass Sie eine Freischaltdatei benötigen. Sie erhalten diese, nachdem Sie die Erweiterung gekauft haben. Zu Evaluierungszwecken stellen wir Ihnen kostenlos eine zeitlich befristete Freischaltung zur Verfügung. Bitte kontaktieren Sie uns dazu per mailto:info@uib.de[E-Mail].

== Unterstützte macOS-Versionen

include::{version}@opsi-docs-en:common:partial$supportmatrix-macclient-core.adoc[]

== Mac-Computer mit Apple-Chip
// cspell: ignore Translators, rosetta, agree, pkgs, apple

Bei Verwendung der arm64 Architektur (Apple Silicium, M1) ist derzeit die Installation des opsi-client-agent der 'Dynamic Binary Translators' namens `rosetta2` notwendig. Diesen können Sie Installieren mit: +
`softwareupdate --install-rosetta --agree-to-license`
Die erfolgreiche Installation können Sie Überprüfen mit: +
`pkgutil --pkgs | grep Rosetta` +
`com.apple.pkg.RosettaUpdateAuto`.

Die native Unterstützung der arm64 Architektur (Apple Silicium) ist in Planung. Hierzu sind die notwendigen Referenz Geräte bestellt. Aussagen wann die Bereitstellung für diese Plattform erfolgt können im Moment (Januar 2021) noch nicht getroffen werden.
