////
; Copyright (c) uib GmbH (uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      09.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



[[opsi-macclient-requirements]]
= Voraussetzungen

Dieses Kapitel beschreibt die Voraussetzungen für das Management von macOS-Clients unter opsi. Als Erstes listet eine Tabelle die unterstützten macOS-Versionen für opsi 4.3 auf; danach geben wir Hinweise zum Arm-basierten Prozessor Apple M1.

NOTE: Der macOS-Client-Agent ist eine xref:opsi-modules:modules.adoc[kostenpflichtige Erweiterung]. Das heißt, dass Sie eine Lizenz-Datei benötigen. Sie erhalten diese, nachdem Sie die Erweiterung gekauft haben. Zu Evaluierungszwecken stellen wir Ihnen kostenlos eine zeitlich befristete Lizenz zur Verfügung. Bitte kontaktieren Sie uns dazu per mailto:info@uib.de[E-Mail].

== Unterstützte macOS-Versionen

include::{version}@opsi-docs-en:common:partial$supportmatrix-macclient-core.adoc[]

CAUTION: Mit den im Dezember 2023 von Apple offiziell veröffentlichten Updates für macOS ist es notwendig, dem Prozess `opsiclientd` vollen Festplattenzugriff zu gewähren, um den normalen Betrieb des `opsi-mac-client-agent` zu ermöglichen. Diese Einstellung können Sie in den macOS-Systemeinstellungen unter _Datenschutz & Sicherheit_ oder per Apple-MDM-Nachricht vom Typ `PrivacyPreferencesPolicyControl` vornehmen.

NOTE: Für den Betrieb im WAN-Modus ist dieser Schritt nicht erforderlich. Daher empfehlen wir als weiter Möglichkeit generell alle Mac-Clients, d.h. auch eigentlich nicht WAN-Clients, im WAN-Modus zu betreiben um diese Problematik zu umgehen.


== Mac-Computer mit Apple-Chip
// cspell: ignore Translators, rosetta, agree, pkgs, apple

Wenn Sie einen Mac mit dem M1-Arm-Prozessor von Apple haben, benötigen Sie zur Installation des OPSI-Client-Agent das Rosetta-Framework. So installieren Sie Rosetta:

[source,console]
----
softwareupdate --install-rosetta --agree-to-license
----

Das die Installation erfolgreich war, können Sie mit dem `pkgutil`-Kommando überprüfen. Sie sollten beispielsweise eine Ausgabe wie diese sehen:

[source,console]
----
$ pkgutil --pkgs | grep Rosetta
com.apple.pkg.RosettaUpdateAuto
----

