////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      09.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-macclient-installation-config-get-essential-products]]
= Rollout existierender Produkte

Um Software auf Clients bereitzustellen, muss auf den Clients der xref:clients:macos-client/macos-client-agent.adoc[Client-Agent] installiert sein.

Dieses Kapitel erklärt, wie Sie Software über die xref:clients:macos-client/opsiconfiged.adoc[Management-Oberfläche *opsi-configed*] auf Clients verteilen. Zu den Standard-Produkten für macOS-Clients gehören unter anderem diese:

// cspell: ignore swaudit, hwaudit, javavm, windomain

* `opsi-mac-client-agent`
* `swaudit`
* `hwaudit`
* `m-homebrew` (siehe auch xref:clients:macos-client/general-notes.adoc#[Das opsi-Produkt *m-homebrew*])
* `m-system-update`
* `opsi-configed`
* `opsi-auto-update`
* `m-javavm`
* `opsi-setup-detector`
* `windomain`

:leveloffset: +1

[[firststeps-software-deployment-product-tests]]

include::common:partial$firststeps-swdp-product-tests-inventory.adoc[]

:leveloffset: -1


[[opsi-macclient-firststeps-software-deployment-product-tests-homebrew]]
== Verteilung von opsi Standard Produkten: m-homebrew

Dieses Produkt installiert das Paketverwaltungsprogramm `homebrew` welches von verschiedenen anderen opsi-Produkten für macOS verwendet wird, z.B. zur Installation von Java.

Siehe auch: xref:macos-client:general-notes.adoc#opsi-macclient-hints-homebrew[Das opsi Produkt m-homebrew]

Wählen Sie im *opsi-configed*, Modus _Client-Konfiguration_, unter dem Reiter _Clients_ den betreffenden Client aus.

Wechseln Sie zum Reiter _Produktkonfiguration_, klicken Sie in die Spalte _Angefordert_ für das Produkt _m-homebrew_, daraufhin öffnet sich eine Liste/Dropdown-Menü und dort wählen Sie die Aktion _setup_.

Der Haken in der Icon-Menüleiste sollte seine Farbe auf Rot wechseln. Wenn Sie ihn anklicken, werden die neuen Einstellungen zum *opsi-Server* übermittelt, im Anschluss ist seine Farbe wieder grün.

Starten Sie dann den Client (neu) oder pushen Sie die Installation per _on_demand_
Er sollte jetzt den _opsi-client-agent_ starten und das Produkt _m-homebrew_ installieren.

[[opsi-macclient-firststeps-software-deployment-product-tests-java]]
== Verteilung von opsi Standard Produkten: m-javavm

Dieses Produkt installiert die Java Runtime Umgebung welche von verschiedenen anderen opsi-Produkten für macOS verwendet wird, z.B. *opsi-configed*.

Wählen Sie im *opsi-configed*, Modus _Client-Konfiguration_, unter dem Reiter _Clients_ den betreffenden Client aus.

Wechseln Sie zum Reiter _Produktkonfiguration_, klicken Sie in die Spalte _Angefordert_ für das Produkt _m-javavm_, daraufhin öffnet sich eine Liste/Dropdown-Menü und dort wählen Sie die Aktion _setup_.

Der Haken in der Icon-Menüleiste sollte seine Farbe auf Rot wechseln. Wenn Sie ihn anklicken, werden die neuen Einstellungen zum {opsi-Server} übermittelt, im Anschluss ist seine Farbe wieder grün.

Starten Sie dann den Client (neu) oder pushen Sie die Installation per _on_demand_
Er sollte jetzt den *opsi-mac-client-agent* starten und das Produkt _m-javavm_ installieren.


[[firststeps-software-deployment-product-tests-configed]]
== Verteilung von opsi Standard Produkten: opsi-configed

Achtung: `m-homebrew` und `m-javavm` müssen bereits installiert sein!

Zu den Standard-Produkten gehört das Produkt *opsi-configed* welches das opsi Management Interface als Anwendung auf einem Rechner installiert.
Da diese Anwendung eine Java-Anwendung ist, wird ein JavaRE mitgeliefert.

Wählen Sie im *opsi-configed*, Modus _Client-Konfiguration_, unter dem Reiter _Clients_ den betreffenden Client aus.

Wenn noch nicht geschehen, aktualisieren Sie den Datenbestand des *opsi-configed* mittels _Datei/Daten neu laden_ bzw. Anklicken des entsprechenden Icons.

Wechseln Sie zum Reiter _Produktkonfiguration_, klicken Sie in die Spalte _Angefordert_ für das Produkt *opsi-configed*, daraufhin öffnet sich eine Liste/Dropdown-Menü und dort wählen Sie die Aktion _setup_.

Der Haken in der Icon-Menüleiste sollte seine Farbe auf Rot wechseln. Wenn Sie ihn anklicken, werden die neuen Einstellungen zum {opsi-Server} übermittelt, im Anschluss ist seine Farbe wieder grün.

Starten Sie dann den Client (neu).
Er sollte jetzt den *opsi-mac-client-agent* starten und das Produkt *opsi-configed* installieren.
Nach Abschluss der Installation sollten Sie unter `Applications` den Punkt *opsi-configed* finden.
