////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////
:Author:    uib GmbH
:Email:     info@uib.de
:Revision:  4.3
:doctype: book

[[opsi-macclient-softwintegration]]
= Einbindung eigener Software in die Softwareverteilung von opsi

Die Installation von Software erfolgt bei opsi durch den *opsi-client-agent* und insbesondere durch das Script gesteuerte Setup Programm *opsi-script*. Daher muss zu jedem opsi-Produkt ein *opsi-script*-Script erstellt werden. Danach werden dieses Script, die Installationsdateien und die Metadaten zu einem opsi-Produkt gepackt, welches sich schließlich auf dem opsi-Server installieren lässt.

[[opsi-macclient-softwintegration-tutorial]]
== Ein kleines Tutorial zur Erstellung eines opsi-script Scripts


include::common:partial$softwintegration-tutorial-introduction.adoc[leveloffset=-1]

[[opsi-macclient-softwintegration-tutorial-general]]
=== Methoden der nicht interaktiven Softwareinstallation bei MacOS

Apple hat (im Gegensatz zu Microsoft) sehr früh die Methoden zur Software Installation standardisiert. Im Kern gibt es zwei Methoden:

* *application Directory*: +
Es handelt sich um ein Verzeichnis nach dem Muster:
`<Application name>.app` Ein solches Verzeichnis wird aber im `Finder` nicht als Verzeichnis angezeigt, sondern als 'Anwendung'. Innerhalb dieses Verzeichnisses müssen sich nach einem bestimmten Muster die Dateien der Anwendung befinden. Ein typischer Aufbau wäre:

----
opsi-script-gui.app
  |--Contents
       |-Info.plist
       |-PkgInfo
       |-MacOS
       |  |-opsi-script-gui
       |
       |-Resources
          |- (....)
----

Ein solches Verzeichnis muss zur Installation nur in das Verzeichnis `/Applications` kopiert werden. Evtl. müssen noch Dateien im Verzeichnis `MacOS` ausführbar gemacht werden. +
Solche *.app Verzeichnisse werden zum Download zumeist gepackt angeboten.

* *PKG file*: +
Diese Dateien enthalten Software die über einen speziellen Befehl installiert werden müssen.

In beiden Fällen ist eine `unattended` (also nicht interaktive) Installation kein Problem.

Häufig wird macOS Software in gepackten Formaten angeboten wie *.zip, *.dmg
oder auch *.tgz.

Alle bisher genannten Varianten können per opsi-script direkt installiert werden, außer *.tgz welches vorher ausgepackt werden muss.

include::common:partial$softwintegration-tutorial-script-structure-opsi-script-basics.adoc[leveloffset=-1]


[[opsi-macclient-softwintegration-tutorial-macos-special-commands]]
==== Spezielle Kommandos für macOS

* GetOS   // liefert: Linux or Windows_NT or macos [W/L/M]

* getMacosVersionInfo [M]

* getMacosVersionMap [M]

Siehe auch: +
https://docs.opsi.org/opsi-docs-de/4.2/opsi-script-manual/reference-card.html#opsi-script-rc-macos-specific

// cspell: ignore uib_macosinstalllib

In den folgenden Kapiteln werden spezielle opsi MacOS Befehle zur Installation von Software vorgestellt welche aus der opsi-script-Bibliothek `uib_macosinstalllib` stammen. Diese Dokumentation ist in Englisch, da sie direkt aus dem Quellcode automatisch generiert wurde.

// http://www.methods.co.nz/asciidoc/userguide.html#X90


include::opsi-docs-en:common:partial$os-lib-uib-macosinstalllib.adoc[leveloffset=4]


[[opsi-macclient-softwintegration-tutorial-template]]
=== Beispiel: MacOS-Template _m-opsi-template_

Dieses Template können Sie sich mit dem `opsi-setup-detector` erstellen.

// include docu: actual template for macOS
include::opsi-docs-en:common:partial$firststeps-opsi-template-mac.adoc[]


[[opsi-client-softwintegration-create-opsi-package]]
== Erstellen eines opsi-Produkt-Paketes


include::common:partial$setup-detector-installation.adoc[]


include::common:partial$opsi-logviewer-installation.adoc[]

// cspell: ignore Installer, Paketierung

[[opsi-macclient-softwintegration-tutorial-create-with-opsi-setup-detector]]
=== Das Programm opsi-setup-detector zum Erstellen eines macOS Scripts

include::common:partial$setup-detector-use-start.adoc[]

include::common:partial$osd-tasks-macos.adoc[]

Die nun folgenden Screenshots zeigen zwar die Verwendung von Windows-Installer Dateien,
sie sehen aber analog aus bei der Verwendung von MacOS Installer Dateien wie *.app, *.dmg, *.zip.

include::common:partial$osd-task-use-single-analyze-and-create.adoc[]

Mehr Details zum `opsi-setup-detector` finden Sie im opsi-manual: +
https://docs.opsi.org/opsi-docs-de/4.2/manual/modules/setup-detector.html

include::common:partial$softwintegration-tutorial-packagebuilder-use.adoc[leveloffset=-1]

include::common:partial$softwintegration-tutorial-modify-test-cycle.adoc[leveloffset=-1]


[[opsi-winclient-softwintegration-tutorial-template-details]]
== Hinweise zu den Teilaufgaben in der Paketierung

include::common:partial$osd-checkboxes-subtasks.adoc[leveloffset=-1]
