////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      10.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-macclient-softwintegration]]
= Eigene Software einbinden

Für die Installation von Software ist bei opsi der xref:clients:macos-client/macos-client-agent.adoc[Client-Agent] bzw. das Setup-Programm xref:opsi-script-manual:opsi-script-manual.adoc[*opsi-script*] zuständig. Wenn Sie also eigene Software paketieren, müssen Sie zu jedem Produkt auch ein `opsi-script`-Skript erstellen. Dieses packen Sie anschließend zusammen mit den Installationsdateien und den Metadaten zu einem opsi-Produkt, das Sie auf dem opsi-Server installieren (siehe Kapitel xref:clients:macos-client/minimal-products.adoc[Produkte auf opsi-Server bereitstellen]).

[[opsi-macclient-softwintegration-tutorial]]
== Tutorial: *opsi-script*-Skript erstellen

include::common:partial$softwintegration-tutorial-introduction.adoc[]

[[opsi-macclient-softwintegration-tutorial-general]]
=== Nicht-interaktive Software-Installation (macOS)

Apple hat (im Gegensatz zu Microsoft) sehr früh die Methoden zur Software-Installation standardisiert. Im Wesentlichen gibt es diese zwei Methoden:

* *Programm-Verzeichnis*: +
Im Ordner `/Applications` liegen Verzeichnisse für macOS-Programme; sie heißen `<Programm>.app`. Der Finder zeigt solche Verzeichnisse allerdings nicht an, sondern stellt sie als Starter im Ordner _Programme_ dar. In einem solchen `<Programm>.app`-Verzeichnis befinden sich Daten (Dateien und Unterverzeichnisse) für die jeweilige Anwendung. Zur Installation muss ein solches Verzeichnis nur in den Ordner `/Applications` kopiert werden. Unter Umständen müssen Sie Dateien im Unterverzeichnis `MacOS` ausführbar machen. Solche `.app`-Verzeichnisse werden meist gepackt zum Download angeboten. Ein typischer Aufbau sieht so aus: 

[source]
----
opsi-script-gui.app
  |--Contents
       |-Info.plist
       |-PkgInfo
       |-MacOS
       |  |-opsi-script-gui
       |  |-opsi-script
       |  |- […]
       |
       |-Resources
          |- […]
----
 
* *PKG-Datei*: +
Apples Paketformat; solche Dateien enthalten die Software und die vorher beschriebene Ordnerstruktur, Installations-Skripte und andere Ressourcen.

Für beide Varianten ist eine Unattended-Installation ohne Interaktion der Benutzer problemlos möglich.

NOTE: macOS-Software steht häufig in gepackten Formaten als `.zip`-, `.dmg`- oder `.tgz`-Datei zur Verfügung. `opsi-script` kann diese Applikationen ebenfalls installieren. `.tgz`-Dateien müssen Sie vorher entpacken.

include::common:partial$softwintegration-tutorial-script-structure-opsi-script-basics.adoc[]

[[opsi-macclient-softwintegration-tutorial-macos-special-commands]]
===== Spezielle macOS-Kommandos

* `getOS : string`: Gibt das Betriebssystem aus, z.{nbsp}B. `Linux`, `Windows_NT` (Windows NT bis Windows 11) oder `macOS`.

* `getMacosVersionInfo  : string`: Gibt die macOS-Version aus.

* `getMacosVersionMap : stringlist`: Gibt eine Liste von Informationen aus, darunter die Build-Version, den Kernel-Namen, Prozessortyp usw.

TIP: Weiterführende Informationen zu diesen String-Funktionen lesen Sie im Abschnitt xref:opsi-script-manual:prim-section.adoc#opsi-script-string-functions-os[String-Funktionen (Betriebssystem ermitteln)].

// cspell: ignore uib_macosinstalllib

===== macOS-Befehle zur Installation

NOTE: Die nächsten Abschnitte stellen spezielle macOS-Befehle zur Installation von Software vor. Sie stammen aus der `opsi-script`-Bibliothek `uib_macosinstalllib`. Dieser Teil der Dokumentation ist in Englisch, da er automatisch aus dem Quellcode generiert wurde.

// http://www.methods.co.nz/asciidoc/userguide.html#X90

:leveloffset: +4

include::{version}@opsi-docs-en:common:partial$os-lib-uib-macosinstalllib.adoc[]

:leveloffset: -4

[[opsi-macclient-softwintegration-tutorial-template]]
=== Beispiel: MacOS-Template _m-opsi-template_

Dieses Template können Sie sich mit dem `opsi-setup-detector` erstellen.

// include docu: actual template for macOS
include::{version}@opsi-docs-en:common:partial$firststeps-opsi-template-mac.adoc[]


[[opsi-client-softwintegration-create-opsi-package]]
== Erstellen eines opsi-Produkt-Paketes


include::common:partial$setup-detector-installation.adoc[]


include::common:partial$opsi-logviewer-installation.adoc[]

// cspell: ignore Installer, Paketierung

[[opsi-macclient-softwintegration-tutorial-create-with-opsi-setup-detector]]
=== Das Programm opsi-setup-detector zum Erstellen eines macOS Scripts

include::common:partial$setup-detector-use-start.adoc[]

include::common:partial$osd-tasks-macos.adoc[]

Die nun folgenden Screenshots zeigen zwar die Verwendung von Windows-Installer Dateien,
sie sehen aber analog aus bei der Verwendung von MacOS Installer Dateien wie *.app, *.dmg, *.zip.

include::common:partial$osd-task-use-single-analyze-and-create.adoc[]

Mehr Details zum `opsi-setup-detector` finden Sie im opsi-manual: +
https://docs.opsi.org/opsi-docs-de/4.2/manual/modules/setup-detector.html

include::common:partial$softwintegration-tutorial-packagebuilder-use.adoc[leveloffset=-1]

include::common:partial$softwintegration-tutorial-modify-test-cycle.adoc[leveloffset=-1]


[[opsi-winclient-softwintegration-tutorial-template-details]]
== Hinweise zu den Teilaufgaben in der Paketierung

include::common:partial$osd-checkboxes-subtasks.adoc[leveloffset=-1]
