////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      10.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-macclient-softwintegration]]
= Eigene Software einbinden

Für die Installation von Software ist bei opsi der xref:clients:macos-client/macos-client-agent.adoc[Client-Agent] bzw. das Setup-Programm xref:opsi-script-manual:opsi-script-manual.adoc[*opsi-script*] zuständig. Wenn Sie also eigene Software paketieren, müssen Sie zu jedem Produkt auch ein `opsi-script`-Skript erstellen. Dieses packen Sie anschließend zusammen mit den Installationsdateien und den Metadaten zu einem opsi-Produkt, das Sie auf dem opsi-Server installieren (siehe Kapitel xref:clients:macos-client/minimal-products.adoc[Produkte auf opsi-Server bereitstellen]).

[[opsi-macclient-softwintegration-tutorial]]
== Tutorial: *opsi-script*-Skript erstellen

include::common:partial$softwintegration-tutorial-introduction.adoc[]

[[opsi-macclient-softwintegration-tutorial-general]]
=== Nicht-interaktive Software-Installation (macOS)

Apple hat (im Gegensatz zu Microsoft) sehr früh die Methoden zur Software-Installation standardisiert. Im Wesentlichen gibt es diese zwei Methoden:

* *Programm-Verzeichnis*: +
Im Ordner `/Applications` liegen Verzeichnisse für macOS-Programme; sie heißen `<Programm>.app`. Der Finder zeigt solche Verzeichnisse allerdings nicht als Ordner an, sondern stellt sie als Programmstarter im Verzeichnis _Programme_ dar. In einem solchen `<Programm>.app`-Verzeichnis befinden sich Daten (Dateien und Unterverzeichnisse) für die jeweilige Anwendung. Zur Installation muss ein solches Verzeichnis nur in den Ordner `/Applications` kopiert werden. Unter Umständen müssen Sie Dateien im Unterverzeichnis `MacOS` ausführbar machen. Solche `.app`-Verzeichnisse werden meist gepackt zum Download angeboten. Ein typischer Aufbau sieht so aus: 

[source]
----
opsi-script-gui.app
  |--Contents
       |-Info.plist
       |-PkgInfo
       |-MacOS
       |  |-opsi-script-gui
       |  |-opsi-script
       |  |- […]
       |
       |-Resources
          |- […]
----
 
* *PKG-Datei*: +
Apples Paketformat; solche Dateien enthalten die Software und die vorher beschriebene Ordnerstruktur, Installations-Skripte und andere Ressourcen.

Für beide Varianten ist eine Unattended-Installation ohne Interaktion der Benutzer problemlos möglich.

NOTE: macOS-Software steht häufig in gepackten Formaten als `.zip`-, `.dmg`- oder `.tgz`-Datei zur Verfügung. `opsi-script` kann diese Applikationen ebenfalls installieren. `.tgz`-Dateien müssen Sie vorher entpacken.

include::common:partial$softwintegration-tutorial-script-structure-opsi-script-basics.adoc[]

[[opsi-macclient-softwintegration-tutorial-macos-special-commands]]
== Spezielle macOS-Kommandos

* `GetOS`: Gibt das Betriebssystem aus, z.{nbsp}B. `Linux`, `Windows_NT` (Windows NT bis Windows 11) oder `macOS`.

* `getMacosVersionInfo`: Gibt die macOS-Version aus.

* `getMacosVersionMap`: Gibt eine Liste von Informationen aus, darunter die Build-Version, den Kernel-Namen, Prozessortyp usw.

TIP: Weiterführende Informationen zu diesen String-Funktionen lesen Sie im Abschnitt xref:opsi-script-manual:prim-section.adoc#opsi-script-string-functions-os[String-Funktionen (Betriebssystem ermitteln)].

// cspell: ignore uib_macosinstalllib

=== macOS-Befehle zur Installation

NOTE: Die nächsten Abschnitte stellen spezielle macOS-Befehle zur Installation von Software vor. Sie stammen aus der `opsi-script`-Bibliothek `uib_macosinstalllib`. Dieser Teil der Dokumentation ist in Englisch, da er automatisch aus dem Quellcode generiert wurde.

// http://www.methods.co.nz/asciidoc/userguide.html#X90

:leveloffset: +2

include::{version}@opsi-docs-en:common:partial$os-lib-uib-macosinstalllib.adoc[]

:leveloffset: -2

[[opsi-macclient-softwintegration-tutorial-template]]
== Beispiel: macOS-Template *m-opsi-template*

Dieses Template können Sie mit dem `opsi-setup-detector` erstellen (siehe Abschnitt <<opsi-macclient-softwintegration-tutorial-create-with-opsi-setup-detector>>).

// include docu: actual template for macOS
include::{version}@opsi-docs-en:common:partial$firststeps-opsi-template-mac.adoc[]

[[opsi-client-softwintegration-create-opsi-package]]
== opsi-Produkte erstellen

Die nächsten Abschnitte erklären, wie Sie Software paketieren, also opsi-Produkte erstellen. Der grundlegende Ablauf sieht so aus:

1. Den "Rohbau" eines Paketes erstellen Sie mit dem `opsi-setup-detector` (siehe Abschnitt <<opsi-macclient-softwintegration-tutorial-create-with-opsi-setup-detector>>).
2. Danach testen Sie das `opsi-script`-Skript (siehe Abschnitt <<opsi-softwintegration-tutorial-create-and-test-script>>).
3. Mit dem opsi PackageBuilder (oPB) erstellen Sie aus der Rohform ein opsi-Paket und hinterlegen es auf dem opsi-Server.

// include docu: opsi-setup-detector installation
include::common:partial$setup-detector-installation.adoc[]

// include docu: opsi-logviewer installation
include::common:partial$opsi-logviewer-installation.adoc[]

// cspell: ignore Installer, Paketierung

[[opsi-macclient-softwintegration-tutorial-create-with-opsi-setup-detector]]
== *opsi-setup-detector*: Skript erstellen

Die folgenden Abschnitte erklären detailliert, wie Sie mit dem `opsi-setup-detector` ein opsi-Produkt eine Setup-Datei analysieren und ein opsi-Produkt erstellen.

// include docu: opsi-setup-detector
include::common:partial$setup-detector-use-start.adoc[]

include::common:partial$osd-tasks-macos.adoc[]

NOTE: Die folgenden Screenshots zeigen die Abläufe für Windows-Installer Dateien, sie sehen unter macOS aber ähnlich aus, wenn Sie Installer-Dateien wie `.app`, `.dmg` oder `.zip` verwenden.

// include docu: how to use the opsi-setup-detector
include::common:partial$osd-task-use-single-analyze-and-create.adoc[]

// include docu: The modify and test cycle
include::common:partial$softwintegration-tutorial-modify-test-cycle.adoc[]

[[opsi-winclient-softwintegration-tutorial-template-details]]
== Paketierung: Hinweise zu Teilaufgaben

Die folgenden Abschnitte zeigen weitere Konfigurationsmöglichkeiten des `opsi-setup-detector`. Sie behandeln die Verwendung eines benutzerdefinierten Verzeichnisses, die Installation aus einem lokalen temporären Verzeichnis, die Verwaltung von Lizenzschlüsseln und die Anpassung von Benutzerprofilen und Desktopsymbolen.

include::common:partial$osd-checkboxes-subtasks.adoc[]
