////
; Copyright (c) uib gmbh (uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      25.11.2024
:doctype: book



[[opsi-module-custom_ca]]
= Custom Certificate Authority

The custom CA module for opsi allows you to use your own certificate authority (CA) to issue certificates for the opsi config server.
In this case, the opsi CA is still used to generate certificates for opsi clients and opsi depot servers.
However, the server certificate for the opsi config server is obtained from your own CA.
This has the advantage that they also use their organization's chain of trust when accessing the opsi config server.
The browsers accept the certificate of the opsi config server without warning.

To configure the use of custom certificates for opsi, please read xref:server:components/tls.adoc#server-components-tls-custom-ca[Use of a custom certification authority].

include::partial$paid-extension-note.adoc[]
