////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      25.11.2024
:doctype: book



[[opsi-module-letsencrpt]]
= Let's Encrypt

The Let's Encrypt extension for opsi makes it possible to automatically obtain and renew SSL/TLS certificates for the opsi config server via the Let's Encrypt certification authority.
In this case, the opsi CA is still used to generate certificates for opsi clients and opsi depot servers.
However, the server certificate for the opsi config server is obtained from Let's Encrypt.
This has the advantage that all common browsers accept the certificate of the opsi config server without warning.

To configure the use of Let's Encrypt for opsi, please read xref:server:components/tls.adoc#server-components-tls-letsencrypt[Using Let's Encrypt].

NOTE: This module is a link:https://opsi.org/en/extensions/[paid extension]. This means that you need an activation file to unlock it. You will receive this file after you have purchased the extension. For evaluation purposes, we're happy to provide you with a temporary license free of charge. Please contact us via mailto:info@uib.de[email].
