////
; Copyright (c) uib gmbh (uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      25.11.2024
:doctype: book



[[opsi-module-letsencrpt]]
= Let's Encrypt

The Let's Encrypt extension for opsi makes it possible to automatically obtain and renew SSL/TLS certificates for the OPSI config server via the Let's Encrypt certification authority.
In this case, the OPSI CA is still used to generate certificates for OPSI clients and OPSI depot servers.
However, the server certificate for the OPSI config server is obtained from Let's Encrypt.
This has the advantage that all common browsers accept the certificate of the OPSI config server without warning.

To configure the use of Let's Encrypt for opsi, please read xref:server:components/tls.adoc#server-components-tls-letsencrypt[Using Let's Encrypt].

include::partial$paid-extension-note.adoc[]
