////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      11.01.2021
:doctype: book

include::common:partial$opsi_terms.adoc[]

[[opsi-manual-linux]]
= opsi Linux Support

include::common:partial$supportmatrix-linclient.adoc[leveloffset=-2]

[[opsi-manual-linux-preconditions]]
== Preconditions for using the opsi Linux Support


Technical precondition is opsi 4.0.5 with following packet versions:

.Required packets
[options="header"]
|==========================
|opsi packet|version
|opsi-linux-bootimage|>= 20140805-1
|==========================

The opsi support for Linux is based on a free Open Source component (the netboot products) and a co-funded component (the client-agent).

The opsi-linux-client-agent is a
link:https://www.opsi.org/product/extensions-of-opsi/[co-funded opsi extension module]. +
In order to use the opsi Linux extension module, an activation file is required, this file can be acquired by buying the extension module. To obtain a temporary activation file for evaluation, please email us at info@uib.de. +
For further details on handling extension modules please refer to the opsi manual.

[[opsi-manual-linux-freestart]]
== opsi-linux-client-agent: 15 Free starts

The opsi-linux-client-agent includes 15 free starts by which the agent can be used without any activation

In detail: After the initial Install from the opsi-linux-client-agent the opsi-script can be started 15 times in service context without the need of activation. +
This gives you the possibility to set a Linux computer with the corresponding opsi-products for the configuration needed.
For example, after the installation of the system you could use the product `l-opsi-server` to make of the newly installed computer an opsi-server.

For a long lasting maintenance of the installed Linux computers after the 15 free starts, it is recommended the activation of the feature, in order to continue taking advantage of its benefits.

[[opsi-manual-linux-getit]]
== Installation of the packages

The Linux-related packages can be loaded over the `opsi-package-updater`.
By default it already has the repository for the linux packages activated.

You can use the following command to install the packages:
[source,shell]
----
opsi-package-updater -v --repo uib_linux install
----


[[opsi-manual-linux-introduction]]
== Introduction

*A single management tool for Windows and Linux*

The objective of the opsi Linux extension module is to provide an homogenous management system for heterogenous environments. The focus is on integrating both worlds into the same management processes and tools

This means, that a Linux installation is triggered the same way as a Windows installation. The Linux opsi-client-agent is based on the same source code as the Windows client and provides (when applicable) the same opsiscript instruction sets.

*Independent from Linux distribution*

The opsi Linux Support is designed to be independent from any special Linux distribution. +
The following distributions are supported:

* Debian
* Ubuntu
* Linux Mint
* OpenSuse / SLES (Suse Linux Enterprise Server)
* RHEL (RedHat Enterprise Linux)
* AlmaLinux 8
* Rocky Linux 8
* CentOS
* UCS

Please keep in mind that you need at least 4GB of RAM in the machine or VM if you want to install Linux Mint.

include::common:partial$firststeps-osinstall-lin.adoc[leveloffset=2]


[[opsi-manual-linux-clientagent]]
== opsi-linux-client-agent

The opsi-client-agent for Linux is part of the cofunding project 'Linux Agent', which is liable to pay costs.

The opsi-client-agent for Windows is based on two components:

. the service `opsiclientd`

. the action processor `opsi-script / opsi-script-nogui`

The opsi-client-agent for Linux is based on the Linux port of the Windows client agent.

The `opsiclientd` is  not ported to all supported Linux distributions.

Tasks of the `opsiclientd` at startup are:
* connect to the opsi-server: check whether actions are to be performed
* mount the depot share
* update the action processor if necessary
* start the action processor
* unmount the depot share
* transfer the logfile to the server

The Linux action processor is named opsi-script and is built from the same sources as for Windows. So on Linux the same scripting syntax is available as on Windows. All common features, that are not Windows specific, are available, as there are e.g.:

* file handling
* string and stringlist functions
* executing external scripts and programs
* communication with the opsi-Server
* patching config files

Of course Windows specific features (like patching the Windows registry) are not available on Linux, but there are some additional Linux specific functions like e.g.:

* getLinuxDistroType
* getLinuxVersionMap

Logging of the opsi-script ist available (like on Windows).

Linux opsi-script is available as a graphical version for working with X-Windows and a noGUI version for systems without graphical user interface.

[[opsi-manual-linux-clientagent-installation-servicesetup]]
== opsi-linux-client-agent: Installation: service_setup.sh

This method is the first choice for installations on a single computer.  service_setup.sh can also be used for maintenance or repair of a client. For mass roll-out, see the chapter below.

. login to the Linux client with root privileges
. mount the shared directory on the opsi server at //<opsiserver>/opsi_depot to any mount point
. change to directory `opsi-linux-client-agent` at the mountpoint
. start at this place the script `./service_setup.sh`

The script connects to the opsi-Webservice in order to create the server side client information and to get the pckey. The connection requires the user/password combination which it tries to retrieve from various configuration files. If that fails, a login window pops up (or commandline questions), where the user can fill in a URL, user, and password. The provided user has to be a member of the group 'opsiadmin'.


[[opsi-manual-linux-clientagent-installation-opsideploy]]
=== opsi-linux-client-agent: Installation: opsi-deploy-client-agent

The `opsi-deploy-client-agent` installs the opsi-client-agent directly from the opsi-Server to the clients.

Requirements for the clients are:

* ssh access as root or as a user that has the possibility to run sudo

The program creates the client on the server, then copies the installation files and the configuration information including the pckey to the client.  After copying the necessary information, `opsi-deploy-client-agent` starts the installation on the client.


With `opsi-deploy-client-agent` a whole list of clients can be processed.
These can include any number of clients that can be passed as the last parameter, or with the option '-f' by which the clients can be read from a file.
When using a file, on each line a client must be present.

The program can work with IP addresses, host names and FQDNs. It will automatically try to recognize what kind of Address was passed.

The program can be found at '/var/lib/opsi/depot/opsi-linux-client-agent' +
Run the program with root privileges or as a user being part of the "opsifileadmins" group. +

[source,shell]
----
bonifax:/var/lib/opsi/depot/opsi-linux-client-agent# ./opsi-deploy-client-agent  --help
usage: opsi-deploy-client-agent [-h] [--version] [--verbose]
                                [--debug-file DEBUGFILE] [--username USERNAME]
                                [--password PASSWORD]
                                [--use-fqdn | --use-hostname | --use-ip-address]
                                [--ignore-failed-ping]
                                [--reboot | --shutdown | --start-opsiclientd | --no-start-opsiclientd]
                                [--hosts-from-file HOSTFILE]
                                [--skip-existing-clients]
                                [--threads MAXTHREADS] [--depot DEPOT]
                                [--group GROUP] [--smbclient | --mount]
                                [--keep-client-on-failure | --remove-client-on-failure]
                                [host [host ...]]

Deploy opsi client agent to the specified clients. The c$ and admin$ must be
accessible on every client. Simple File Sharing (Folder Options) should be
disabled on the Windows machine.

positional arguments:
  host                  The hosts to deploy the opsi-client-agent to.

optional arguments:
  -h, --help            show this help message and exit
  --version, -V         show program's version number and exit
  --verbose, -v         increase verbosity (can be used multiple times)
  --debug-file DEBUGFILE
                        Write debug output to given file.
  --username USERNAME, -u USERNAME
                        username for authentication (default:
                        Administrator).Example for a domain account: -u
                        <DOMAIN>\\<username>
  --password PASSWORD, -p PASSWORD
                        password for authentication
  --use-fqdn, -c        Use FQDN to connect to client.
  --use-hostname        Use hostname to connect to client.
  --use-ip-address      Use IP address to connect to client.
  --ignore-failed-ping, -x
                        try installation even if ping fails
  --reboot, -r          reboot computer after installation
  --shutdown, -s        shutdown computer after installation
  --start-opsiclientd, -o
                        Start opsiclientd service after installation
                        (default).
  --no-start-opsiclientd
                        Do not start opsiclientd service after installation.
  --hosts-from-file HOSTFILE, -f HOSTFILE
                        File containing addresses of hosts (one per line).If
                        there is a space followed by text after the address
                        this will be used as client description for new
                        clients.
  --skip-existing-clients, -S
                        skip known opsi clients
  --threads MAXTHREADS, -t MAXTHREADS
                        number of concurrent deployment threads
  --depot DEPOT         Assign new clients to the given depot.
  --group GROUP         Assign fresh clients to an already existing group.
  --smbclient           Mount the client's C$-share via smbclient.
  --mount               Mount the client's C$-share via normal mount on the
                        server for copying the files. This imitates the
                        behaviour of the 'old' script.
  --keep-client-on-failure
                        If the client was created in opsi through this script
                        it will not be removed in case of failure. (DEFAULT)
  --remove-client-on-failure
                        If the client was created in opsi through this script
                        it will be removed in case of failure.
----

[[opsi-manual-linux-clientagent-installation-netboot]]
=== opsi-linux-client-agent: Installation: Via opsi netboot product

If you install a Linux via opsi netboot product, you only have to switch the property `install_opsi-client-agent` to 'true' (which is the default) in order to install the opsi-linux-client-agent.

[[opsi-manual-linux-clientagent-opsiclientd-configuration]]
=== opsi-linux-client-agent: opsiclientd configuration

The `opsiclientd` for Linux is a port of the `opsiclientd` for Windows.
So it works withe similar configuration file which is located at:
`/etc/opsi-client-agent/opsiclientd.conf`.

A detailed description of this file you will find at the chapter for the opsi-client-agent for Windows:  xref:client/opsi-client-agent.adoc#opsi-manual-clientagent-configuration[opsi-client configuration]

At the moment there are not all of the features and events available on Linux. +
Available are:

* Start at boot time (or via explicit start of the service `opsiclientd`). At Linux is the name of this event `opsiclientd_start` (not `gui_startup`)
* `event_on_demand`
* The `event_timer` but only with the configuration: `super = default`


Not available are:

* Everything that is related to local caching ('WAN-Extension').
* The `event_net_connection`
* The `event_on_shutdown`
* The `event_silent_install`


[[opsi-manual-linux-clientagent-places]]
=== opsi-linux-client-agent: installation paths

As usual on Linux, the linux-opsi-client-agent is spread to several directories:

The binaries (or symlinks to binaries):

`/usr/bin/opsi-script`

`/usr/bin/opsiclientd`

Auxiliary files:

Skin files: +
`/opt/opsi-script/skin`
custom : `/usr/share/opsi-script/customskin`

opsi-script Library: +
`/opt/opsi-script/lib`

Translation files:
`/opt/opsi-script/locale/opsi-script.po`


Config files:

`/etc/opsi-client-agent/opsiclientd.conf` (configuration of the opsiclientd)

`/etc/opsi-script/opsi-script.conf` (configuration of opsi-script)

Logfiles / temporary files:

`/var/log/opsi-client-agent`

`/var/log/opsi-client-agent/opsiclientd`

`/var/log/opsi-script/`

[[opsi-manual-linux-clientagent-knownbugs]]
== opsi-linux-client-agent: Known Bugs

Copy a bundle of files via Files section from a smb share may fail according to the Samba version
This problem was reported from some samba3 Versions but seems to be vanished in samba4.

Workaround:
Instead of:
[source,winst]
----
[Files_copy_netboot]
copy -s "%scriptPath%/installfiles/*" "$target$/installfiles/"
----
you may use:
[source,winst]
----
[ShellInAnIcon_opsi_copy_netboot]
set -x
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
cd "%scriptPath%"
tar cf - installfiles | ( cd "$target$/installfiles/" ; tar xf - )
----

[[opsi-manual-linux-scriptexample]]
== Script examples

For software deployment on Windows clients there can be said: the installation of software itself is as important as the subsequent configuring of the software. +
On Linux most packets are available from the distribution repositories. So the installation part is less, but the configuration part stays the same. Also there are applications, that are not available from the standard repositories.
In this case special repositories or installation sources have to be added to the system. The important feature is, that all installation and configuration settings can be managed and logged on the opsi-server.

Here are some example snippets for an opsi-linux-client-agent opsi-script:

* exit in case the script detects a non Linux system
* detecting the distribution type (to use `apt`, `zypper` or `yum`)
* detecting the Linux version
* installing a packet
* adding a repository

Example: exit in case the script detects a non Linux system:

[source,winst]
----
[Actions]
requiredWinstVersion >= "4.11.4.1"
ScriptErrorMessages=off

DefVar $OS$

set $OS$ = GetOS

if not($OS$ = "Linux")
	LogError "Wrong OS: Product: " + $ProductId$ + "is only for Linux"
	isFatalError "Wrong OS"
endif
----

Example: detecting the distribution type:

[source,winst]
----
[Actions]
requiredWinstVersion >= "4.11.4.1"
ScriptErrorMessages=off

DefVar $distrotype$

set $distrotype$ = getLinuxDistroType

if $distrotype$ = 'debian'
	Message "Try to get Package Lock..."
	if waitForPackageLock("60","false")
		comment "we got the package lock."
	else
		LogError "could not get Package Lock"
		isFatalError "package lock failed"
	endif
	ShellInAnIcon_Upgrade_deb
else
	LogError "Wrong Distro: This Product is for Debian/Ubuntu only"
	isFatalError "Wrong distro"
endif

if not("0" = getLastExitCode)
	Message "failed ShellInAnIcon_Upgrade"
	LogError "failed ShellInAnIcon_Upgrade"
	isFatalError "failed Upgrade"
endif


[ShellInAnIcon_Upgrade_deb]
set -x
export DEBIAN_FRONTEND=noninteractive
apt update
apt --yes dist-upgrade
exit $?
----


Example: detecting the Linux version and installing a packet:

[source,winst]
----
[Actions]
requiredWinstVersion >= "4.11.4.1"
ScriptErrorMessages=off

DefVar $distCodeName$
DefVar $distroName$
DefVar $distRelease$
DefVar $desktop$

DefStringList $linuxInfo$

set $linuxInfo$ = getLinuxVersionMap
set $distCodeName$ = getValue("Codename", $linuxInfo$)
set $distRelease$ = getValue("Release", $linuxInfo$)
set $distroName$  = getValue("Distributor ID", $linuxInfo$)

set $desktop$ = GetProductProperty("desktop", "kde")


if $distrotype$ = 'suse'
	if $desktop$ = "unity"
		Message " No Unity on SUSE - fallback to KDE ..."
		set $desktop$ = "kde"
	endif ; unity

	Message "Try to get Package Lock..."
	if waitForPackageLock("60","false")
		comment "we got the package lock."
	else
		LogError "could not get Package Lock"
		isFatalError "package lock failed"
	endif

	if $desktop$ = "kde"
		if ($distroName$ = 'openSUSE project')
			ShellInAnIcon_kde_suse
		endif
		if ("SUSE LINUX" = $distroName$) and ($distRelease$ = "11")
			ShellInAnIcon_kde_sles11
		endif
		if not("0" = getLastExitCode)
			LogError "failed ShellInAnIcon"
			Message "failed kde"
			isFatalError "failed kde"
		endif
	endif ; kde
endif; suse type

[ShellInAnIcon_kde_suse]
set -x
zypper --no-gpg-checks --non-interactive install patterns-openSUSE-kde4 patterns-openSUSE-kde4_basis
zypper --no-gpg-checks --non-interactive install splashy-branding-openSUSE
exit $?

[ShellInAnIcon_kde_sles11]
set -x
zypper --no-gpg-checks --non-interactive install --auto-agree-with-licenses -t pattern kde
exit $?
----


Example: adding a repository:
[source,winst]
----
[Actions]
requiredWinstVersion >= "4.11.4.1"
ScriptErrorMessages=off

DefVar $distCodeName$
DefVar $distroName$
DefVar $distRelease$
DefVar $desktop$

DefStringList $linuxInfo$

set $linuxInfo$ = getLinuxVersionMap
set $distCodeName$ = getValue("Codename", $linuxInfo$)
set $distRelease$ = getValue("Release", $linuxInfo$)
set $distroName$  = getValue("Distributor ID", $linuxInfo$)

set $desktop$ = GetProductProperty("desktop", "kde")


if $distroName$ = 'Ubuntu'

	if $desktop$ = "cinnamon"
		set $desktopPackage$ = $desktop$
		Message "Try to get Package Lock..."
		if waitForPackageLock("60","false")
			comment "we got the package lock."
		else
			LogError "could not get Package Lock"
			isFatalError "package lock failed"
		endif
		ShellInAnIcon_ubuntu_cinnamon
		if not("0" = getLastExitCode)
			Message "failed ShellInAnIcon_ubuntu_cinnamon"
			LogError "failed ShellInAnIcon_ubuntu_cinnamon"
			isFatalError "failed cinnamon"
		endif
	endif ; cinnamon
endif; ubuntu

[ShellInAnIcon_ubuntu_cinnamon]
set -x
export DEBIAN_FRONTEND=noninteractive
# we need to get the add-apt-repository command
apt --yes install python-software-properties
# the cinnamon repository
add-apt-repository ppa:gwendal-lebihan-dev/cinnamon-stable
apt update
apt --yes install ubuntu-desktop
exit $?
----

Many of these as well as some other functions are available in the opsi-script standard library uib_lin_install.opsiscript.

[[opsi-manual-linux-localboot]]
== Linux localboot products

Here some localboot products that are part of the standard opsi Linux support.

[[opsi-manual-linux-localboot-l-opsi-server]]
=== The Product `l-opsi-server`

The product 'l-opsi-server' serves to install on a Linux computer an opsi-Server via opsi-linux-client-agent
in an automated way. This can serve to install quickly a new opsi-depot-server
or e.G. an opsi Test system.

WARNING: Currently for a opsi-config server an other maschine can't be a opsi-linux-client and a opsi-depot-server at the same time. +
To work around this limitation, you have two possibilities: +
1. Using one opsi-config-server: After the installation of opsi via 'l-opsi-server' and before you register this maschine as opsi-depot-server, you have to delete it as client in the configed. +
2. Using two opsi-config-servers: Setup a second independent opsi-config-server, which is only used to administrate (install and mantain) your opsi-servers. So this second opsi-config-server knows the other opsi-servers only as linux-clients. Your other (first) opsi-config-server know theses other opsi-servers as depots. +
In a UCS environment method 2 is recommended and the second opsi-config server must not be a UCS Server.


The product 'l-opsi-server' has the following Properties:

* `opsi_online_repository`: +
(Base-) Repository for opsi-Server installation. +
(Default="https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/") +
see also 'repo_kind'

* `opsi_noproxy_online_repository`: +
(Base-) Repository for opsi-Server installation (without any cache proxy). +
(Default="https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/") +
Should you require on `opsi_online_repository` to introduce a Proxy or deb-cacher
(e.G. 'http://mydeb-cacher:9999/download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/"),
than introduce the URL without Proxy. Otherwise introduce the same as `opsi_noproxy_online_repository`.

* `repo_kind`: +
Which kind of repository ["experimental", "stable", "testing"] should be installed ?. (Default='stable') +
With the Client OS, 'opsi_online_repository' and 'repo_kind' the URL will be built and the client
will be added to an opsi repository.

* `backend`: +
Which backend should be installed ? (mysql needs a valid activation file). (Default='file') +
A modules file with the require Activations can be stored in the custom directory of the product.
If a modules file is found there, then will this one used.

* `opsi_admin_user_name`: +
The name of the opsi_admin_user to create (empty= nothing created). (Default='adminuser') +
If a user is introduced here, it will applied, also it will be added to the group 'opsiadmin', 'pcpatch'/'opsifileadmin'
and become as unix and samba password the value `opsi_admin_user_password`

* `opsi_admin_user_password`: +
What is the password of the opsi_admin_user to create (empty= not allowed). (Default='linux123') +
see `opsi_admin_user_name`

* `setup_after_install`: +
Which opsi product(s) should we switch to setup after l-opsi-server installation is done ?. (Default="")

* `allow_reboot`: +
May the server reboot if script is finished ?. (Default='true')

* `install_and_configure_dhcp`: +
Should we run the dhcp server on this machine ?. (Default='False') +
If this property is 'false' then the following properties: 'netmask', 'network',
'dnsdomain','nameserver' and 'gateway' are meaningless because they are only used for
dhcp configuration.

* `myipname`: +
Set a different IP name (FQDN) ('auto'= use standard) (Default='auto') +
Meaningless if 'install_and_configure_dhcp=false'

* `myipnumber`: +
Set a different IP number ('auto'= use standard) (Default='auto') +
Meaningless if 'install_and_configure_dhcp=false'

* `netmask`: +
Netmask  (for dhcp). (Default="255.255.0.0") +
Meaningless if 'install_and_configure_dhcp=false'

* `network`: +
network address (for dhcp). (Default="192.168.0.0") +
Meaningless if 'install_and_configure_dhcp=false'

* `dnsdomain`: +
DNS domain (for dhcp). (Default="uib.local") +
Meaningless if 'install_and_configure_dhcp=false'

* `nameserver`: +
Primary nameserver (for dhcp). (Default="192.168.1.245") +
Meaningless if 'install_and_configure_dhcp=false'

* `gateway`: +
gateway (option routers for dhcp). (Default="192.168.1.245") +
Meaningless if 'install_and_configure_dhcp=false'

* `ucs_master_admin_password`: +
Only needed for opsi installation on UCS Server with other Roles than Role 'Master'. (Default='linux123')

* `update_test`: +
Do not use: Internal Debugging. (Default='False')

* `ucs_master_admin_password`: +
On a UCS machine  the roles Slave, Backup and Member have to be joined correctly with the Mas
ter. This property takes the password to perform the join.

The product has 'setup required before' dependency to the product 'l-system-update'.
That means when you set 'l-opsi-server' on 'setup' it will also automatically set 'l-system-update' also on setup
and installed before.

In the directory `custom` of the product `l-opsi-server` the activated file (`modules`) is stored, which is used in the Installation of the product `l-opsi-server` and will be preserved in the case of a new version of the product.


[[opsi-manual-linux-localboot-l-os-postinst]]
=== l-os-postinst

This product installs and configures those parts of the base installation, that cannot be done from the bootimage in a proper way.

This is for the different distributions:

* CentOS:

** installation of SELinux


This product has a dependency to the product 'l-system-update' which is executed before running 'l-os-postinst'. +
This product has a high priority, so it is executed before common products.

[[opsi-manual-linux-localboot-l-desktop]]
=== l-desktop

The product l-desktop installs a desktop packet on the computer.

The property `desktop` selects the desktop to be installed. Not all of the desktops are available for every distribution. For instance 'Unity' is available for Ubuntu only. If the selected desktop is not available, the distribution specific default desktop will be installed. Furthermore the scope of the desktop packets differs according to the distribution and the selected desktop. It can be just the actual desktop software, or might also contain some base products like libreoffice, firefox, PDF Reader etc.

The property `desktop` can have the following values:

* Gnome +
Default for Debian, CentOS, RHEL. +
Available for all distributions.

* KDE +
Default für SLES, OpenSuse.
Available for all distributions.

* Unity +
Available for Ubuntu only.

* Cinnamon +
Available for Ubuntu only.

* xfce4 +
Available for Ubuntu, Debian.

* lxde +
Available for Ubuntu, Debian.


[[opsi-manual-linux-localboot-l-system-update]]
=== l-system-update
This product updates the system.

[[opsi-manual-linux-localboot-l-swaudit]]
=== swaudit
Software inventory, based on the packet manager

[[opsi-manual-linux-localboot-hwaudit]]
=== hwaudit

Hardware inventory. +
The hardware inventory currently is based on the Python implemented method as also used by the bootimage.

[[opsi-manual-linux-localboot-l-jedit]]
=== l-jedit

Java based editor with syntax highlighting for opsi-script. If Java is missing on the system, it will be installed automatically.


[[opsi-manual-linux-inventory]]
== Inventory

To create an inventory, the data are collected on the client and sent to the server. The hardware inventory is based on the methods implemented in the bootimage.

The software inventory is based on the data from the packet management of the deployed Linux distribution.

[[opsi-manual-linux-uefi]]
== UEFI / GPT support

Most of the opsi 4.1 / opsi 4.2 Linux netboot products are UEFI/GPT compatible.


[[opsi-manual-linux-debproxy]]
== Proxy for '.deb'-packages

Instructions for installation and use of servers for local caching of  debian packages:

* link:https://help.ubuntu.com/community/Apt-Cacher-Server[Ubuntu help: Apt-Cacher-Server]

* link:http://xmodulo.com/apt-caching-server-ubuntu-debian.html[How to set up Apt caching server on Ubuntu or Debian]
