////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:  uib gmbh
:Email:   info@uib.de
:Date:    13.03.2025
:doctype: book



[[opsi-module-message-of-the-day]]
= Message of the Day

The extension *Message of the Day* enables the display of messages for users who log on to an opsi client. A distinction is made between two message types:

* *device message*: Displayed before the user logs in.
* *User message*: Appears after the user logs in.

Each message is displayed exactly once. Messages are formatted using Markdown. User messages can contain links that are opened in the user's default browser.

As soon as a new message is stored, it appears on the clients as soon as possible. Optionally, an expiration date can be set after which the message is no longer displayed.

The defined messages apply to all users and devices that use *Message of the Day*. Specific assignment to individual users or devices is not possible.

To activate the extension, the (xref:gui:configed/userguide-clients.adoc#opsi-manual-configed-hostproperties[Host-Parameter]) 'opsiclientd.global.message_of_the_day_enabled' must be set.

The messages are managed via *opsi-configed* under _Extras_ => _Message of the Day_.


include::partial$paid-extension-note.adoc[]
