////
; Copyright (c) uib gmbh (uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      11.01.2021
:doctype: book


[[opsi-manual-scalability]]
= Scalability

By default, the *opsiconfd* service starts with a single worker process.
How many clients can be served by one worker process depends on various factors, such as hardware, network, number and size of opsi packages, and other aspects. As a rough guideline, about 600 clients per worker process can be assumed. If a larger number of clients needs to be served efficiently, the number of worker processes must be increased. Requests are then distributed among the individual workers.

With the opsi module *Scalability Light*, two worker processes can be started.
With the opsi module *Scalability*, the number of worker processes can be configured without limitation.

The number of worker processes is set via the `workers` parameter in the `/etc/opsi/opsiconfd.conf` file.
Example:
[source,console]
----
workers = 2
----

After changing the configuration, it is sufficient to instruct the *opsiconfd* service to reload the configuration:
[source,console]
----
opsiconfd reload
----

TIP: Since each worker process requires resources and causes some overhead, the number of worker processes should not be set too high.

include::partial$paid-extension-note.adoc[]
