////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      25.11.2024
:doctype: book



[[opsi-module-sso]]
= Single Sign-On (SSO)

The Single Sign-On (SSO) extension for opsi allows you to authenticate users with a central identity provider.
In this way, administrators can log in to opsi with their existing credentials.
With SSO, you can use the existing user management of your identity provider and do not have to manage users in opsi separately.
This simplifies the administration of users and increases security.
User convenience and productivity are increased as they only have to log in once.

The SSO extension currently supports link:https://www.microsoft.com/en-us/security/business/identity-access/microsoft-entra-id[Microsoft Entra ID] and link:https://www.keycloak.org/[Keycloak] via the SAML 2.0 protocol.

To configure the SSO extension for opsi, please refer to xref:server:components/authorization.adoc#server-components-authorization-saml[authorization via SAML].

NOTE: This module is a link:https://opsi.org/en/extensions/[paid extension]. This means that you need an activation file to unlock it. You will receive this file after you have purchased the extension. For evaluation purposes, we're happy to provide you with a temporary license free of charge. Please contact us via mailto:info@uib.de[email].
