////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.3
:Date:      31.01.2024
:doctype: book



[[opsi-manual-userroles]]
[[opsi-manual-configed-hostproperties-userroles]]
= Managing User Rights and Roles

Starting with version 4.0.7.5 the 'opsi-configed' includes the user roles function.

WARNING: In order to use this feature  the module _user roles_ must be activated in the modules_-file.

In the interface, in the overview of the server host parameters, the category _user_
shows the availability of the function (not necessarily active).
The _user_ branch of the properties tree starts with a boolean entry

[source,prompt]
----
user.{}.register
----

with default value _false_.

The other entries at this location represent the default values for the user-specific configurations of the server console.

To activate the user role extension you need to:

1. Set the value of _user. {}.register_ to _true_.
2. Load a modules file that has the _userroles_ extension temporarily or permanently activated.

When the user-role extension is activated, an entry is created in the properties tree for the logged-in user.
The default settings used for the administration of rights are like the "classic" requirements for an administrator,
that means, that this user has no restriction whatsoever. E.g., for a user named _admindepot1_ the following entries are generated:

[source,prompt]
----
user.{admindepot1}.privilege.host.all.registered_readonly	[false]
user.{admindepot1}.privilege.host.depotaccess.configured	[false]
user.{admindepot1}.privilege.host.depotaccess.depots		[]
user.{admindepot1}.privilege.host.opsiserver.write 		[true]
----


These four items mean:

- _admindepot1_ is _not_ restricted to read-only access to the server (a pure read-only access might be appropriate for a help desk staff member);
- depot restrictions do not exist or are not taken into account;
- consequently, the list of depots available to the user can stay empty
(and if some depots are entered, this has no effect);
- the user is allowed to edit config server settings of all kinds.

In the case that the access of _admindepot1_ is to be restricted to the computers in the depot server _depot1_, the following should be set:

- _host.depotaccess.configured_ is to be set to _true_;
- the value "depot1" is to be put into the list _host.depotaccess.depots_.

After a complete data reload, clients from other depots are not more visible to _admindepot1_
(and also only the depot settings for _depot1_ are accessible).

WARNING: _admindepot1_ him/herself can change this settings as long as she/he owns the privilege _host.opsiserver.write_

In order to complete the restriction, it therefore is required to set

- _host.opsiserver.write_ to _false_.


WARNING: The privileges which are set in this way restrict only the functionality of the 'opsi-configed'.
Until further notice, they have no effect if the JSON-RPC interface of the opsi-server is accessed by other means.
