////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      11.01.2021
:doctype: book



[[opsi-manual-wan-faq]]
= FAQ for setup and application of the WAN extension

[[opsi-faq-wan-manual-licenz]]
== Do I need a license?

Yes, the extension is still part of the cofinancing scheme and therefore subject to a fee.
You can test the extensions free of charge for a limited amount of time. In order to do so please contact sales@uib.de.

[[opsi-faq-wan-manual-activate]]
== How do I activate the WAN extension on a client?

The activation of the WAN extension can be performed per client via the checkbox on the management console. The client will receive the specific configuration change the next time it connects to the opsi server. It then becomes active the next time the client is restarted.

[[opsi-faq-wan-manual-activate-oca]]
== Must the opsi client agent be deployed once again for the activation?

No, that is not necessary since the client can get the configuration automatically at the next connection to the opsi server. That can be at the next boot process or after an "on_demand" event.

[[opsi-faq-wan-manual-activate-homeoffice]]
== How can I activate clients that are already in Home Office?

If the clients can be reached by the opsi server in home office, the change of the configuration can be performed by triggering an "on_demand" event. (This only works if the data transfer is set to cifs)

In the event that the clients in the home office cannot be reached by the opsi server, they can be updated via this opsi-admin call. (This should also work for clients that have been switched to webdav)

On the command line of the server this can be done using:

[source,shell]
----
opsi-admin -a https://<ClientIp>:4441/opsiclientd -u <user> -p <pass> method fireEvent "on_demand"

or

opsi-admin -a https://<ClientIp>:4441/opsiclientd -u "<FQDN>" -p "<OpsiHostKey>" method fireEvent "on_demand"
----

Replace the corresponding entries:

.  <ClientIp>    = IP address of the clients
.  <user>        = local administrator on the client or a member of the local administrator group
.  <pass>        = password of the administrator
.  <FQDN>        = FQDN of the client
.  <OpsiHostKey> = opsi hostkey of the client


[[opsi-faq-wan-manual-cache]]
== How big is the cache on the client?

The cache on the client is set to 20 GB by default. The programs and updates to be installed are stored here. During an update, only the changed data is copied to the cache directory via a sync process. The size of the cache should be chosen generously so that large packages can also be saved.

[[opsi-faq-wan-manual-cachesize]]
== How can I change the size of the cache on the client?

With this command, this parameter will be created in the management console. The value can then be individually adjusted for each client:

[source,shell]
----
opsi-admin -d method config_createUnicode "opsiclientd.cache_service.product_cache_max_size" "Maximum product cache size in bytes" "40000000000" "40000000000" "True" "False"
----

[[opsi-faq-wan-manual-time]]
== How can I increase the time the client waits for a response before rebooting for an installation?

With this command, this parameter will be created in the management console. The value can then be individually adjusted for each client:

[source,shell]
----
opsi-admin -d method config_createUnicode "opsiclientd.event_sync_completed{cache_ready_user_logged_in}.shutdown_warning_time" "How long should to wait for an answer before a reboot. The default is 3600 seconds." "3600" "3600" "True" "False"
----

If you want to increase the time by 8 hours enter 28000 seconds here.

[[opsi-faq-wan-manual-ondemand]]
== "on_demand" installations in WAN mode?

The installations are triggered as if the client would not be a WAN client.

. The config server is requested directly.
. The installation starts without caching directly from the mounted depot share.

[[opsi-faq-wan-manual-kiosk]]
== Does the kiosk mode work in WAN mode?

The kiosk mode works only if the opsi config server is available. Also in WAN-mode the kiosk connects directly to the opsi server.
If the request to install a package is not only saved but also executed directly, the installation is performed the standard way and not in WAN mode, which means the packages are not cached. You can use the kiosk on a WAN client, but the actual WAN mode components are not used.

[[opsi-faq-wan-manual-byshutdown]]
== Can the Install by shutdown mode be combined with the WAN mode?

No, Install by shutdown mode is not compatible with WAN extension.

[[opsi-faq-wan-manual-mshotfix]]
== Subscription MSHotfix and WAN mode

Basically you can deploy the Mshotfix packages from your subscription on your WAN clients. However, it should be noted that these standard packages are very large in size(e.g. Windows 10 64 bits is around 6GB).

For this reason "modular" Mshotfix packages are provided for Windows 10 that only contain the patches for a certain ReleaseID, e.g. mshotfix-win10-1809-x64-glb. The size of these "modular" packages is currently about 1 GB). Therefore we strongly suggest to use these "modular" packages in WAN mode.

[[opsi-faq-wan-manual-cachedelete]]
== How can I clear the cache on a client?

In configed on the clients-tab via the OpsiClient-menu "On WAN-clients: Delete package caches", or

[source,shell]
----
opsi-admin -a https://<ClientIp>:4441/opsiclientd -u "<FQDN of the client>" -p "OpsiHostKey" method "cacheService_deleteCache"
----

[[opsi-faq-wan-manual-user-login]]
== Can user-login-scripts be used in WAN mode?

No, that makes no sense because these are started when the user logs in to make changes to roaming profiles that cannot be used with WAN clients. The entry in opsi-configed for opsiclientd.event_user_login.active should therefore be set to false.
