

include::common:partial$opsi_terms.adoc[]

[[firststeps-software-deployment-product-tests-configed]]
=== Verteilung von opsi Standard Produkten: {opsi-configed}

Zu den Standard-Produkten gehört das Produkt _opsi-configed_ welches das opsi Management Interface als Anwendung auf einem Rechner installiert.
Da diese Anwendung eine Java-Anwendung ist, wird ein JavaRE mitgeliefert.

Wählen Sie im _{opsi-configed}_, Modus _Client-Konfiguration_, unter dem Reiter _Clients_ den betreffenden Client aus.

Wenn noch nicht geschehen, aktualisieren Sie den Datenbestand des {opsi-configed}s mittels _Datei/Daten neu laden_ bzw. Anklicken des entsprechenden Icons.

Wechseln Sie zum Reiter _Produktkonfiguration_, klicken Sie in die Spalte _Angefordert_ für das Produkt _opsi-configed_, daraufhin öffnet sich eine Liste/Dropdown-Menü und dort wählen Sie die Aktion _setup_.

Der Haken in der Icon-Menüleiste sollte seine Farbe auf Rot wechseln. Wenn Sie ihn anklicken, werden die neuen Einstellungen zum {opsi-Server} übermittelt, im Anschluss ist seine Farbe wieder grün.

Starten Sie dann den Client (neu).
Er sollte jetzt den _opsi-client-agent_ starten und das Produkt _opsi-configed_ installieren.
Nach Abschluß der Installation sollten Sie im _Startmenü_ den Punkt _opsi-configed_ finden.
