

include::common:partial$opsi_terms.adoc[]

[[firststeps-software-deployment-product-tests-inventory]]
=== Inventarisierung mit dem localboot-Produkten hwaudit und swaudit

Wählen Sie im _opsi-configed_, Modus _Client-Konfiguration_, unter dem Reiter _Clients_ den betreffenden Client aus.

Wenn noch nicht geschehen, aktualisieren Sie den Datenbestand des opsi-configeds mittels _Datei/Daten neu laden_ bzw. Anklicken des entsprechenden Icons.

Wechseln Sie zum Reiter _Produktkonfiguration_, klicken Sie in die Spalte _Angefordert_ für das Produkt _hwaudit_, daraufhin öffnet sich eine Liste/Dropdown-Menü und dort wählen Sie die Aktion _setup_. Wiederholen Sie das für das Produkt _swaudit_.

Der Haken in der Icon-Menüleiste sollte seine Farbe auf Rot wechseln. Wenn Sie ihn anklicken, werden die neuen Einstellungen zum {opsi-Server} übermittelt, im Anschluss ist seine Farbe wieder grün.

Starten Sie dann den Client (neu).
Er sollte jetzt den +opsi-client-agent+ starten und die Produkte _hwaudit_ und _swaudit_ installieren.
Bei _hwaudit_ und _swaudit_ werden Hard- bzw. Softwareinformationen erhoben und zum {opsi-Server} übermittelt.
Die gesammelten Informationen werden unter den Tabs _Hardwareinformationen_ bzw. _Software-Inventarisierung_ angezeigt.
