

include::common:partial$opsi_terms.adoc[]

[[firststeps-software-deployment-product-tests-hwinvent]]
[[firststeps-osinstall-tests-hwinvent]]
=== Hardware-Inventarisierung mit dem netboot-Produkt hwinvent

Sofern auf Ihrem opsi-Server das Produkt _hwinvent_ bereits installiert ist und Sie einen Client xref:adding-clients.adoc#firststeps-osinstall-create-client[aufgenommen] haben, welcher für den Boot über das Netzwerk konfiguriert ist, können Sie etwas weiteres Nützliches tun: Hardware-Inventarisierung ohne installiertes Betriebssystem.

Wählen Sie im {opsi-configed}, Modus _Client-Konfiguration_, unter dem Reiter Client-Auswahl den betreffenden Client aus.
Wenn noch nicht geschehen, aktualisieren Sie den Datenbestand des {opsi-configed}s mittels +Datei/Daten neu laden+ bzw. Anklicken des entsprechenden Icons.
Wechseln Sie zum Reiter 'Netboot-Produkte', gehen Sie in das Feld +Anstehende Aktion+ des Produkts +hwinvent+ und wählen Sie in der dort angebotenen Liste die Aktion 'setup'.
Der Haken in der Icon-Menüleiste sollte seine Farbe auf Rot wechseln.
Wenn Sie ihn anklicken, werden die neuen Einstellungen zum {opsi-Server} übermittelt und die Farbe des Hakens wechselt im Anschluss wieder zu grün.

Starten Sie dann den Client (neu). Er sollte jetzt per PXE über das Netz ein Linux-Image ziehen, das die Hardware des PCs scannt und dann den Rechner rebootet. Wenn der Rechner nicht ansonsten schon eingerichtet war, kommt im Anschluss korrekterweise die Meldung, dass auf der Platte kein Betriebssystem installiert ist.

Das Ergebnis des Hardware-Scans hat der PC zum {opsi-Server} übermittelt. Es ist unter dem Reiter "Hardware-Informationen" einzusehen.

NOTE: Sollte nach dem Laden des bootimages der Bildschirm schwarz bleiben oder die Netzwerkkarte nicht (korrekt) funktionieren, so muss für diese konkrete Hardware evtl. die Startparameter des bootimages angepasst werden. +
Dies können Sie im '{opsi-configed}' im Tab 'Hostparameter' am Eintrag 'opsi-linux-bootimage.append' tun. +
Details hierzu finden Sie im opsi Handbuch im Kapitel 'Netboot Produkte'.
