include::common:partial$opsi_terms.adoc[]

[[firststeps-software-deployment-configed]]
== Management-Oberfläche `opsi-configed`

Opsi bietet mit dem {opsi-configed} ein komfortables Management Interface.
Es kommuniziert über HTTPS mit dem opsi-Server und kann daher auf jedem Rechner verwendet werden, der eine entsprechende Verbindung aufbauen kann.


TIP: Achten Sie bei Verwendung einer virtuellen Maschine auf eine ausreichende Auflösung des virtuellen Bildschirms.
Für den {opsi-configed} wird mindestens eine Auflösung von 1024x768 Pixeln benötigt.
Für die Verbesserung der Graphik- und Maustreiberintegration bei einer höheren Auflösung, hilft es, die 'VMware Tools' bei einer VMware-Maschine bzw. die Gasterweiterungen bei einer VirtualBox-Maschine zu installieren.


[[firststeps-software-deployment-configed-installation]]
=== Installation der Management-Oberfläche {opsi-configed}

Das Management Interface wird als lokale Anwendung auf den Administrations-PCs installiert.
Rufen Sie in Ihrem Browser die Adresse `https://<opsidepotserver>:4447/` auf.
Dort finden Sie Links zu Installern für unterschiedliche Betriebssysteme.

Alternativ finden Sie entsprechende Installer unter link:https://download.uib.de/opsi4.2/misc/helper/[].

IMPORTANT: Der Windows-Installer muss mit administrativen Rechten ausgeführt werden.
Dazu öffnen Sie mit Rechtsclick das Contextmenü des Installers und wählen dort 'Als Administrator ausführen'.

Ist erstmal ein PC mit dem Management Interface ausgestattet, so können weitere PCs später einfach über das Localboot-Produkt *opsi-configed* mit dem Interface 
ifdef::gstarted[xref:getting-started:server/minimal-products.adoc#firststeps-software-deployment-product-tests-configed[ausgestattet werden]]
, sofern auf diesen bereits der
ifdef::gstarted[xref:getting-started:adding-clients.adoc#firststeps-adding-clients[opsi Agent]]
installiert ist.



[[firststeps-software-deployment-configed-start]]
=== Start der Management-Oberfläche {opsi-configed}

Starten Sie {opsi-configed} über die Verknüpfung in Ihrem Startmenü.

Loggen Sie sich als ein User ein, der Mitglied der Gruppe {opsi-admin-group} ist.

Die Bedienung des Management-Interfaces ist weitgehend selbsterklärend.
Sie finden eine ausführliche Anleitung im opsi-Handbuch.

NOTE: Änderungen im opsi-Management Interface müssen gespeichert werden, bevor Sie wirksam werden und Veränderungen der Daten müssen vom Server über 'Daten neu laden' geholt werden.

