////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      09.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[firststeps-osinstall]]
= Linux mit opsi installieren

Dieses Kapitel beschreibt, wie Sie verschiedene Linux-Distributionen auf einem bisher nicht mit einem Betriebssystem ausgestatteten Computer per opsi installieren. Als Client-Rechner eignen sich physische Computer oder virtuelle Rechner mit den folgenden Voraussetzungen:

* 2{nbsp}GByte RAM oder mehr
* Netzwerkkarte mit Netzboot-Unterstützung (Unterstützung des PXE-Protokolls zum Laden von Bootmedien via Netzwerk)

NOTE: Überprüfen Sie die Einstellungen im BIOS. Netzboot muss aktiviert sein und an erster Stelle der Bootoptionen stehen, damit Sie Linux per opsi installieren können.


Installation eines neuen Linux PC über opsi (OS-Installation)


[[firststeps-osinstall-netboot-distro]]
== Netboot-Produkte (Installer der Distribution)

auf Basis des Distributionseigenen Installers


* Ähnlich wie bei der Windows-Installation wird für den Installer eine Antwortdatei bereit gestellt, welche vom Installer zur nichtinteraktiven Installation genutzt wird.

* Der distributionseigene Installer ist nicht wie bei Windows ein Programm das aufgerufen wird, sondern in einer Kombination aus distributionseigenem Kernel und initrd implementiert.

* Die gesamte Grundinstallation - inklusive Partitionierung, LVM, Basissoftware, etc. - liegt in der Hand des Installers und wird nicht mehr durch das bootimage durchgeführt.

* Bei den Suse- und RedHat-artigen Distributionen werden die Installationsquellen von Ihnen bereitgestellt, in dem Sie die Installations-DVD als ISO-Datei auf dem Depotshare ablegen. Dieses Verfahren ähnelt der Situation unter Windows, nur dass der Ablageort ein anderer ist und dass Sie bei Windows den Inhalt der Installations-DVD ablegen anstatt einer ISO-Datei.

* Für eine Linux Mint Installation in Version 4.2.0.1-6 und früher wird der Inhalt der offiziellen Installations Medien über einen NFS Server benötigt. Ab Version 4.2.0.2-1 wird ein ISO Image in das Produktunterverzeichnis `iso` gespeichert.

* Bei den Debian-artigen werden die Installationsquellen aus dem Netz verwendet. Auf dem Depotshare liegen nur die Netboot Versionen von Distributionskernel und dazugehörigem initrd. Da diese Dateien nicht groß sind, werden sie im opsi-Paket mitgeliefert. +
Das Paket `ubuntu22-04` erwartet ein ISO Image im Produktunterverzeichnis `iso` und liefert selbst keinen Distributionskernel und dazugehöriges Initrd mehr mit.

* Zur weiteren Pflege der Installation kann der opsi-linux-client-agent im Rahmen der Basisinstallation mit installiert werden.

Abläufe der neuen Installationsmimik:

. Das opsi-linux-bootimage wird gebootet, löscht die Partitionstabelle und erstellt eine kleine temporäre Hilfsparition.

. Das opsi-linux-bootimage holt sich das distributionseigene initrd und entpackt es auf der Hilfspartition.

. Das opsi-linux-bootimage holt sich die generische Vorlage für die Antwortdatei, patcht (personalisiert) diese und legt sie dann in das initrd Verzeichnis.

. Das opsi-linux-bootimage erstellt weitere Hilfscripte und Konfigurationsdateien (z.B. zur Installation des opsi-linux-client-agent) und legt sie dann in das initrd Verzeichnis.

. Das opsi-linux-bootimage packt das gepatchte initrd Verzeichnis wieder zusammen.

. Das opsi-linux-bootimage bootet den Distributions-Kernel mit dem gepatchten initrd per kexec.

. Das so geladene System installiert das Zielsystem unattended und installiert abschließend den opsi-linux-client-agent.

Die Vorteile dieses Vorgehens sind:

* Die Installation findet exakt gemäß den Anforderungen des Distributors statt. Dies ist immer ein Vorteil, aber natürlich im Unternehmensumfeld als Ausgangsbedingung für Supportverträge besonders wichtig.

* Die Integration neuer Releases in opsi wird einfacher und dadurch schneller.

* Bei den Suse- und RedHat-artigen, Linux Mint Distributionen und Ubuntu 22-04 findet die Installation aus auf dem opsi-Server liegenden Installationsquellen statt und ist damit schneller und unempfindlicher gegen Störungen als beim Zugriff auf Repositories aus dem Internet.

[[firststeps-osinstall-netboot-distro-prepare]]
=== Installations-Medien per NFS

Bereitstellung und der Installationsmedien auf dem Server per NFS

Dies betrifft die RedHar-artigen Distributionen vor Version 4.2.0.3-1, die SLES-artigen Distributionen vor Version 4.2.0.2-1 und Linux Mint vor 4.2.0.2-1. Im Anschluss an die NFS-Server Variante, wird die neuartige Variante erklärt.

Die Bereitstellung der Installationsmedien für die Suse-, RedHat und Linux Mint-artigen Distributionen erfolgt auf einem nfs share: `opsi_nfs_share`.

Zur Einrichtung des shares muss ein NFS-Server auf dem opsi-server installiert und konfiguriert sein.

Seit opsi v4.0.6 wird dies über ein gesondertes Paket `opsi-linux-support` erfolgen. Dieses Paket wird nicht per default installiert und muss einmalig nachinstalliert werden.

Auf Debian-artigen Betriebssystemen kann das durch den folgenden Befehl erreicht werden:

[source,shell]
----
apt install opsi-linux-support
----

Beim Einsatz einer Firewall auf Ihrem Server muss diese noch so konfiguriert
werden, dass TCP-Verbindungen auf Port 80 akzeptiert werden.
Bitte konsultieren Sie hierzu das entsprechende Handbuch.

Was dieses Paket macht, ist (als händige Anleitung) im Folgenden beschrieben:

* Auf dem opsi-server muss das entsprechende NFS-Server-Paket installiert sein. Auf Debian, Ubuntu, Suse ist dies das Paket: `nfs-kernel-server`. Auf Centos, Redhat ist es das Paket `nfs-utils`.

* Der Export `opsi_nfs_share` muss angelegt und exportiert werden:

** Verzeichnis erzeugen: +
`mkdir -p /var/lib/opsi/depot/opsi_nfs_share`

** In der Datei `/etc/exports` den Eintrag: +
`/var/lib/opsi/depot/opsi_nfs_share *(ro,no_root_squash,insecure,async,subtree_check)` +
erzeugen.

** Das Aktivieren des Exports wird mit dem folgenden Befehl ausgelöst: +
`exportfs -r`

** Zur Kontrolle des erfolgreichen Exports den folgenden Befehl aufrufen: +
`showmount -e localhost` +
Die Ausgabe sollte sein: +
`Export list for localhost: +
/var/lib/opsi/depot/opsi_nfs_share *`

* Der share `opsi_nfs_share` hat folgenden Verzeichnisaufbau: +
`opsi_nfs_share/<productId>/<arch>/<dvd>.iso` +
zum Beispiel: +
`opsi_nfs_share/opensuse53-2/64/openSUSE-15.2-DVD-x86_64.iso` +
Die Installationsdatei muss als Dateiendung `.iso` haben, der Rest ist egal. Liegen in einem Verzeichnis mehrere `.iso` Dateien so ist nicht definiert welche verwendet wird. +
Eine Ausnahme hierzu bildet das Netboot Produkt mint20-X. Hierfür ist es nötig den gesamten Inhalt, auch versteckte Verzeichnisse, in den entsprechenden `opsi_nfs_share` Unterordner zu kopieren.

* Kopieren Sie die Installations-DVD an den entsprechenden Platz im `opsi_nfs_share` und führen Sie aus: +
`opsi-set-rights /var/lib/opsi/depot/opsi_nfs_share` +
WICHTIG: Verwenden Sie die Standard Installations-DVD's der Distribution. Modifizierte Installations DVD's haben eventuell einen anderen Aufbau und funktionieren nicht.

* Sollten Sie aus irgendwelchen Gründen das Verzeichnis `/var/lib/opsi/depot/opsi_nfs_share` nicht vom opsi-server aus per NFS exportieren können (z.B. weil der Depotshare vom opsiserver per NFS von einem NAS eingebunden ist), so kann der zu verwendende NFS-share über ein Serverweites config angegeben werden. Z.B. `clientconfig.opsi_nfs_share=172.16.166.1:/var/lib/opsi/depot/opsi_nfs_share`

* Beim Produkt `ubuntu22-04` muss die .iso Datei im Produktverzeichnis im Unterverzeichnis `iso` hinterlegt werden.

=== Installations-Medien per WebDAV

Bereitstellung und der Installationsmedien auf dem Server per opsifond WebDAV

Dies betrifft die RedHar-artigen Distributionen ab Version 4.2.0.3-1, die SLES-artigen Distributionen ab Version 4.2.0.2-1 und Linux Mint ab 4.2.0.2-1.

Die RedHat- und SUSE-artigen Distributionen, sowie Linux Mint und Ubuntu22-04 nutzen seit den oben genannten Versionen keinen NFS-Server mehr zur Verteilung der Installationsmedien. Vielmehr gibt es in den jeweiligen Produktverzeichnissen ein Unterverzeichnis `iso` bzw. `isocontent`.

In das `iso` Verzeichnis wird das ISO Image abgelegt. Das `isocontent` Verzeichnis beinhaltet den Inhalt eines ISO Images, analog zum `installfiles` Verzeichnis eines Windows-Netboot-Paketes.

Hier ein Beispiel anhand des SLES15-3 Produktes.

[source,shell]
----
mount SLE-15-SP3-Full-x86_64-GM-Media1.iso /mnt
cp -r /mnt/* /var/lib/opsi/depot/sles15-3/isocontent/
cp /mnt/.treeinfo /var/lib/opsi/depot/sles15-3/isocontent/
cp /mnt/.discinfo /var/lib/opsi/depot/sles15-3/isocontent/
umount /mnt
----

Hinweis: Die Datei `.discinfo` ist nicht bei allen Distributionen vorhanden und kann dementsprechend fehlen.


[[firststeps-osinstall-netboot-distro-generalproperties]]
=== Allgemeine Propertys

der opsi Linux Netboot Produkte mit distributions Installer

Die folgenden Properties finden Sie zur Steuerung der Linuxinstallation in allen v406 Netbootprodukten:

* `askbeforeinst`: +
Soll das Starten der Installation am Client bestätigt werden müssen?  (Default='true')

* `architecture`: +
Mit welcher Architektur soll das Zielsystem installiert werden? +
Beeinflusst außerdem das verwendete Bootimage.  (Default='64bit')

* `language` oder `locale`: +
Welche Sprache / locale soll installiert werden.  (Default=Distributionsabhängig / 'de')

* `console_keymap`: (nicht unter ubuntu22-04!) +
Zu installierendes Tastaturlayout.  (Default=Distributionsabhängig / 'de')

* `timezone`: +
Welche Zeitzone soll verwendet werden?. (Default='Europe/Berlin')

* `root_password`: +
Passwort für root.  (Default='linux123')

* `user_password`: +
Passwort für user.  (Default='linux123')

* `proxy`: +
Proxystring (wenn benötigt) in der Form: 'http://<ip>:<port>'. (Default=pass:[''])

* `install_opsi-client-agent`: +
Installiere den opsi-client-agent für Linux (Kofinanzierungsprojekt: Sie benötigen eine Aktivierung durch die /etc/opsi/modules). (Default='true')

* `setup_after_install`: +
Welche opsi-Produkte sollen zum Abschluss der Betriebssysteminstallation auf *setup* gestellt werden. (Default='')


[[firststeps-osinstall-netboot-distro-special-ubuntu14-04]]
=== Produkte: Debian, Ubuntu und Linux Mint

 debian10, debian11 und ubuntu18-04, ubuntu20-04, ubuntu22-04 und mint20-1, mint20-2, mint20-3, mint21

Die Basis-Installation erfolgt direkt aus dem Netz, mit Ausnahme vom Netboot Paket ubuntu22-04. Hier muss zusätzlich im Produktverzeichnis im Unterverzeichnis iso ein ISO abbild hinterlegt werden. Bei ubuntu16-04 ist auch eine Installation von einem lokalen Repository möglich.

Bedingt durch den Wechsel des verwendeten Installers sind nicht alle aufgeführten Properties im Netboot Paket ubuntu22-04 (und neuer) enthalten. Die entsprechenden Properties haben jeweils einen Hinweis auf das Fehlen im Netboot Paket ubunut22-04

Das Produkt hat produktiven Status.

Das Produkt hat folgende zusätzliche Properties:

* `online_repository`: +
Repository der Distribution für die Installation. (Nur bei Debian/Ubuntu Produkten) (Default=Distributionsabhängig)

* `encrypt_password`: (nicht unter ubuntu22-04!) +
Passwort für die Festplattenverschlüsselung (nur verwendet wenn encrypt_logical_volumes=true) +
Example: `linux123` Default: `linux123`

* `installation_method`: +
Methode zur Installation des Installers. Funktioniert nur mit der UEFI Erweiterung: +
`reboot`: Es wird eine kleine Partition angelegt und nach einem Reboot wird der Installer von dieser Partition gestartet. / `kexec`: Das opsi-linux-bootimage startet den Installer direkt per kexec, es erfolg kein Reboot.
Possible: "reboot", "kexec" +
Default: `kexec`

* `partition_disk`: (nicht unter ubuntu22-04!) +
Zu verwendende Festplatte: `first` oder kompletter device path (nicht unter ubuntu22-04!)
Examples: "first", "/dev/sda", "/dev/sdb" +
Default: `first`

* `preseed`: (unter ubuntu20-04 `autoinstall`) +
Zu verwendende Autonstallationsdatei. Diese muss sich im Produktverzeichnis im Unterordner `custom` befinden.
Examples: "auto", "raid.cfg", "raid.yml" (ubuntu22-04 +
Default: `auto`

* `partition_method`: +
Methode zur Partitionierung der Festplatte: +
`regular`: Standard Partionierung (unter ubuntu22-04: `direct`)/ `lvm`: LVM's anlegen / `crypto`: In einer verschlüsselten Partition LVM's anlegen (nicht unter ubuntu22-04!) +
Possible: "regular" oder "direct", "lvm", "crypto" +
Default: `lvm`

* `partition_recipe`: (nicht unter ubuntu22-04!)+
Die Art der verwendeten Partitionierung: +
`atomic`: Alles in einer Partition / `home`: eigene /home Partition / `multi`: eigene /home, /usr, /var, und /tmp Partitionen
Possible: "atomic", "home", "multi" +
Default: `atomic`

* `desktop_package`: +
Zu installierendes desktop package (standard = kein desktop) (Nur bei Debian/Ubuntu Produkten).
Possible: "standard", "ubuntu-desktop", "kubuntu-desktop", "lubuntu-desktop", "xubuntu-desktop", "ubuntu-gnome-desktop" +
Default: `standard`

* `language_packs`: (nicht unter ubuntu22-04!)+
Possible: "ar", "bg", "by", "cf", "de", "dk", "en", "es", "et", "fa", "fi", "fr", "gr", "il", "it", "kg", "kk", "lt", "mk", "nl", "no", "pl", "ro", "ru", "sg","sr", "ua", "uk", "us", "wo" +
Default: `de`


.Videos (Zeitraffer)

Folgende Videos zeigen jeweils eine Installation. +
Sie sind mit einem Frame pro Sekunde aufgenommen und dadurch schneller anzusehen als die Installation eigentlich dauert.

* link:http://download.uib.de/press-infos/videos/opsi-linux/debian8_406_1fps.mp4[Debian 8]

[[firststeps-osinstall-netboot-distro-special-ucs]]
=== Produkte: Univention Corporate Server (UCS)

Die Basis-Installation bezieht ihre Pakete von den offiziellen UCS Repositories. Eine Installation mit lokalen Paketquellen ist ebenfalls möglich.

Dieses Produkt hat einen produktiven Status.

Mit diesem Produkt ist es möglich, einen Master-, Slave-, Backup, und einen Member-Server zu installieren.
Wir empfehlen das l-opsi-server Produkt, um aus einer UCS Maschine auch einen opsi-Server zu machen.
Dieses Produkt ermöglicht es auch Clients über einen Member-Server zu installieren, hierfür werden einige Besonderheiten durchgeführt.

Das Produkt hat über die oben genannten Properties eines z.B debian8 Produktes noch die folgenden zusätzlichen UCS spezifischen Properties:

* `dns_domain`: +
Der DNS Domain Name: +
Example: `example.com` Default: `ucs.test`

* `ldap_base`: +
ldap base.
Example: `dc=example,dc=com` Default: `dc=ucs,dc=test`

* `ucs_code_name`: +
Der Codename der UCS-Version, welche im onlien Repository bereit gestellt wird. +
Example: `ucs414` Default: `ucs414`

* `organisation`: +
Der Name der Organisation der bei der UCS Installation verwendet wird. +
Example: `uib gmbh` Default: `uib gmbh`

* `windomain`: +
Der Name der Samba/Windows Domain. +
Example: `MYDOMAIN` Default: `MYDOMAIN`

* `external_nameserver`: +
Welcher externe Nameserver soll bei der Installation verwendet werden ? +
Example: `10.11.12.13` Default: `auto` = the name server given by dhcp

* `ucs_master_ip`: +
Die IP-Nummer des UCS Domain Controller (wird beim joinen von anderen Rollen verwendet) ? +
Example: `10.10.10.10` Default: `10.10.10.10`

* `ucs_master_admin_password`: +
Das Administrator Passwort des UCS Domain Controller (wird beim joinen von anderen Rollen verwendet) ? +
Example: `linux123` Default: `linux123`

* `ucs_role`: +
Welche UCS Rolle soll installiert werden ? +
Possible: "domaincontroller_master", "domaincontroller_backup", "domaincontroller_slave", "memberserver", "base" +
Default: `domaincontroller_master`


[[firststeps-osinstall-netboot-distro-special-sles]]
=== Die Produkte: SLES und opsnSUSE

 sles12sp3, sles12sp4, sles12sp5, sles15-1, sles15-2, sles15-3, sles15-4 und opensusel15-3, opensusel15-4

Das Produkt hat folgende zusätzliche Properties:

----
name: productkey
multivalue: False
editable: True
description: email:regcode-sles for suse_register. Is only used if the  host parameter  `license-management.use` is set to  false . If it set to  True  the license key will be get from the license management module. / La clé de licence pour l'installation. Est utilisée uniquement si dans "Réseau et paramètres supplémentaires" `license-management.use` est défini à false (faux) . Si c'est réglé sur True (vrai) la clé de licence sera obtenue du module de gestion des licences.
values: ["", "myemail@example.com:xxxxxxxxxxxxxx"]
default: [""]

name: suse_register
description: set to false, if you don't want to register your system online, if you set this to false you have to give local repositories
default: True

name: local_repositories
multivalue: True
editable: True
description: list of local repositories to use. Syntax: "repository description", example entry: "http://sles.example.com/suse/repo NameForRepo"
values: [""]
default: [""]

name: install_unattended
description: If false then do interactive installation
default: True
----

.Installationsquelle
Zum herunterladen der Installations DVD brauchen Sie einen Account bei SUSE.
Vor Version 4.2.0.2-1:
ISO-File kopieren nach `/var/lib/opsi/depot/opsi_nfs_share/sles15-3/64/`
Nach Version 4.2.0.2-1
ISO Inhalt kopieren nach `/var/lib/opsi/depot/sles15-3/isocontent/`
Ausführung von `opsi-set-rights` nicht vergessen.


.Videos (Zeitraffer)

Folgendes Video zeigt eine Installation. +
Es ist mit einem Frame pro Sekunde aufgenommen und dadurch schneller anzusehen als die Installation eigentlich dauert.

* link:http://download.uib.de/press-infos/videos/opsi-linux/sles12_406_1fps.mp4[Suse Linux Enterprise Server 12]


[[firststeps-osinstall-netboot-distro-special-redhat70]]
=== Die Produkte: RHEL, AlmaLinux und Rocky Linux

 redhat8, redhat9 und rocky8, rocky9 und alma8, alma9

Das Produkt hat folgende zusätzliche Properties:

----
name: install_unattended
description: If false then do interactive installation
default: True

name: selinux_mode
multivalue: False
editable: False
description: In which mode should SELinux run ?
values: ["enforcing", "permissive", "disabled"]
default: ["permissive"]

name: partition_method
multivalue: False
editable: False
description: plain: Regular partitions with no LVM or Btrfs. / lvm: The LVM partitioning scheme. / btrfs: The Btrfs partitioning scheme. / thinp: The LVM Thin Provisioning partitioning scheme.
values: ["plain", "lvm", "btrfs", "thinp"]
default: ["lvm"]

name: productkey
multivalue: False
editable: True
description: email:regcode for subscription_register. Is only used if the  host parameter  `license-management.use` is set to  false . If it set to  True  the license key will be get from the license management module. / La clé de licence pour l'installation. Est utilisée uniquement si dans "Réseau et paramètres supplémentaires" `license-management.use` est défini à false (faux) . Si c'est réglé sur True (vrai) la clé de licence sera obtenue du module de gestion des licences.
values: ["", "myemail@example.com:xxxxxxxxxxxxxx"]
default: [""]

name: subscription_register
description: set to false, if you don't want to register your system online, if you set this to false you have to give local repositories
default: True
----

.Installationsquelle von AlmaLinux
Laden sie das ISO Image bitte herunter, z.B. hier link:https://repo.almalinux.org/almalinux/8/isos/x86_64/[here].
Vor Version 4.2.0.3-1
ISO Datei hierhin kopieren `/var/lib/opsi/depot/opsi_nfs_share/alma8/64/`
Nach Version 4.2.0.3-1
Den Inhalt der ISO kopieren nach `/var/lib/opsi/depot/alma8/isocontent/`
Bitte nicht vergessen `opsi-set-rights` auszuführen.

.Installationsquelle von RedHat
Zum Download der ISO benötigen sie einen RedHat Account.
Vor Version 4.2.0.3-1
ISO Datei hierhin kopieren `/var/lib/opsi/depot/opsi_nfs_share/redhat8/64/`
Nach Version 4.2.0.3-1
Den Inhalt der ISO kopieren nach `/var/lib/opsi/depot/redhat8/isocontent/`
Bitte nicht vergessen `opsi-set-rights` auszuführen.

.Instalaltionsquelle von RockyLinux
Laden sie das ISO Image bitte herunter, z.B. hier link:https://rockylinux.org/download/[here].
Vor Version 4.2.0.3-1
ISO Datei hierhin kopieren `/var/lib/opsi/depot/opsi_nfs_share/rocky8/64/`
Nach Version 4.2.0.3-1
Den Inhalt der ISO kopieren nach `/var/lib/opsi/depot/rocky8/isocontent/`
Bitte nicht vergessen `opsi-set-rights` auszuführen.


.Videos (Zeitraffer)

Folgende Videos zeigen eine Installation. +
Sie sind mit einem Frame pro Sekunde aufgenommen und dadurch schneller anzusehen als die Installation eigentlich dauert.

* link:http://download.uib.de/press-infos/videos/opsi-linux/centos70_406_1fps.mp4[CentOS 7]

* link:http://download.uib.de/press-infos/videos/opsi-linux/redhat70_406_1fps.mp4[RedHat 7]


[[firststeps-osinstall-netboot-gen]]
== Netboot-Produkte (generischer Installer)

*Basis-Installation des OS per Netboot*

Für die Installation eines Linux Basissystems wird zunächst per Netboot das Standard opsi-linux-bootimage gebootet (welches auch für die Windows-Installationen zum Einsatz kommt). +
Von diesem Bootimage aus wird die Ziel-Festplatte partitioniert (/ und swap) und formatiert. Nun folgt die Installation des Grundsystems (mit Netzwerkkonfiguration und ssh aber ohne X11). Die Abläufe dieser Grundinstallation unterscheiden sich naturgemäß zwischen den unterschiedlichen Distributionen erheblich. Gemeinsam ist, dass die Installation direkt aus den Originalpaketen der Distribution erfolgt.

Optional kann nun der opsi-client-agent für Linux installiert werden. Dieser ist dann für die Installation und Konfiguration weiterer Software zuständig.

Die opsi-Netboot-Produkte zur Linuxinstallation sind bereits als Open Source freigegeben.

Bedingt dadurch, dass die Basisinstallation aus dem Standard opsi-linux-bootimage erfolgt, gibt es distributionsabhängig unterschiedlich bestimmte Dinge, welche sich erst in der Umgebung nach dem ersten Boot des Systems konfigurieren bzw. installieren lassen. Beispiele hierfür sind die SELinux-Installation bei den 'RedHat artigen' bzw. die Konfiguration der Tastatur bei den 'Debian artigen'. Hierfür gibt es ein Standard Localbootprodukt `l-os-postinst` welches diese Aufgaben übernimmt.

[[firststeps-osinstall-netboot-generalproperties-gen]]
=== Allgemeine Propertys

der Linux Netboot Produkte mit generic Installer

Die folgenden Properties finden Sie zur Steuerung der Linuxinstallation in allen Netbootprodukten:

* `askbeforeinst`: +
Soll das Starten der Installation am Client bestätigt werden müssen?  (Default='true')

* `architecture`: +
Mit welcher Architektur soll das Zielsystem installiert werden? +
Beeinflusst die Auswahl des bootimages und die Installationsarchitektur.  (Default='64bit')

* `system_partition_size`: +
Größe der Systempartition. Die Größe kann in Prozent der Festplattengröße oder als absoluter Wert (G=Gigabyte) angegeben werden. Wenn Sie einen kleineren Wert als 100% angeben, wird der verbleibende Rest als Datenpartition verwendet (wenn das Property data_partion_create = true).  (Default='100%')

* `swap_partition_size`: +
Größe der Swappartition.  (Default='2000M')

* `data_partition_create`: +
Verwende freien Plattenplatz zur Erstellung einer Datenpartition. (true/false).  (Default='true')

* `data_partition_preserve`: +
Soll eine existierende Datenpartition erhalten werden ? +
*always* = Installation abbrechen wenn der Erhalt einer gefundenen Partition mit dem Label 'data' mit den angegebenen Partitionierungsdaten nicht möglich ist. +
*if_possible* = Wird eine Partition mit dem Label 'data' gefunden und der Erhalt dieser Partition ist gemäß der angegebenen Partionierungsdaten nicht möglich, so wird die Partition gelöscht. +
*never* = Die gesamte Partitionstabelle wird immer neu geschrieben.  (Default='never')

* `language`: +
Welche Sprache / locale soll installiert werden.  (Default='de')

* `console_keymap`: +
Zu installierendes Tastaturlayout.  (Default=Distributionsabhängig / 'de')

* `timezone`: +
Welche Zeitzone soll verwendet werden?. (Default='Europe/Berlin')

* `root_password`: +
Passwort für root.  (Default='linux123')

* `user_password`: +
Passwort für user.  (Default='linux123')

* `online_repository`: +
Repository der Distribution für die Installation. (Nicht bei SLES) (Default=Distributionsabhängig)

* `proxy`: +
Proxystring (wenn benötigt) in der Form: 'http://<ip>:<port>'. (Default=pass:[''])

* `additional_packages`: +
Welche zusätzlichen Pakete sollen installiert werden? Angabe der Pakete Leerzeichen separiert. (Default=pass:[''])

* `wget_and_execute`: +
Url (http) einer Datei welche am Ende der Installation geholt und ausgeführt wird. (Default=pass:[''])

* `install_opsi-client-agent`: +
Installiere den Linux opsi-client-agent (Kofinanzierungsprojekt: Sie benötigen eine Aktivierung durch die /etc/opsi/modules) . (Default='false')

* `release`: +
(nur Debian und Ubuntu) +
Welches Release der Distribution soll installiert werden. (Default=Distributionsabhängig)

* `setup_after_install`: +
Welche opsi Produkte sollen zum Abschluss der Betriebssysteminstallation auf setup gestellt werden. (Default='l-os-postinst')


[[firststeps-osinstall-netboot-special-ubuntu]]
=== Ubuntu

Die Basis Installation erfolgt per debootstrap direkt aus dem Netz.

Das Produkt hat produktiven Status.

Das Produkt ist UEFI/GPT kompatibel.

Es gibt für diese Produkt passende opsi-server Pakete, welche über 'install_opsi_server=true' installiert werden können.

[[firststeps-osinstall-netboot-special-debian]]
=== Debian

Die Basis Installation erfolgt per debootstrap direkt aus dem Netz.

Das Produkt hat produktiven Status.

Das Produkt ist UEFI/GPT kompatibel.

Es gibt für diese Produkt passende opsi-server Pakete, welche über 'install_opsi_server=true' installiert werden können.

[[firststeps-osinstall-linux-debproxy]]
=== Proxy für '.deb'-Pakete

 einrichten und verwenden

Anleitungen zur Erstellung eines eigenen Proxy zum Zwischenspeichern von '.deb'-Paketen finden Sie unter anderem hier:

* link:http://wiki.ubuntuusers.de/Lokale_Paketquellen/Apt-Cacher-ng[Ubuntusers Wiki: Apt-Cacher-NG]

* link:http://www.gambaru.de/blog/2011/10/26/apt-cacher-ng-ein-proxy-server-fur-debian-und-ubuntu/[Gambaru.de: Apt-Cacher-NG: Ein Proxy-Server für Debian und Ubuntu]


////
[[firststeps-osinstall-linux-netboot-clients]]
=== Linux Installation: Clients

Nachfolgend wird beschrieben, wie ein bisher nicht mit einem Betriebssystem ausgestatter Computer per opsi mit einem Linux-Betriebssystem ausgestattet wird.

Als Client-PC eignen sich reale oder virtuelle Rechner mit mindestens 2048 MB RAM, die über eine Netzwerkkarte mit Netzboot-Unterstützung verfügen:
D.h., sie unterstützen das PXE-Protokoll zum Laden von Boot-Systemen via Netzwerk.
Der Netzboot ist ggf. im BIOS-Menü zu aktivieren bzw. an die erste Stelle der Bootoptionen zu rücken.

Für die nachfolgenden Kapitel sollten Sie einen entsprechenden Client in opsi xref:adding-clients#firststeps-osinstall-create-client[aufgenommen haben].
Einfach geht dies xref:opsiconfiged#firststeps-osinstall-create-client[mittels opsi-configed].

////

