////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      28.09.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-winclient-softwintegration]]
= Eigene Software einbinden

Für die Installation von Software ist bei opsi der xref:clients:windows-client/windows-client-agent.adoc[Client-Agent] bzw. das Setup-Programm xref:opsi-script-manual:opsi-script-manual.adoc[*opsi-script*] zuständig. Wenn Sie also eigene Software paketieren, müssen Sie zu jedem Produkt auch ein `opsi-script`-Skript erstellen. Dieses packen Sie anschließend zusammen mit den Installationsdateien und den Metadaten zu einem opsi-Produkt, das Sie auf dem opsi-Server installieren (siehe Kapitel xref:clients:windows-client/minimal-products.adoc[Produkte auf opsi-Server bereitstellen]).

[[opsi-winclient-softwintegration-tutorial]]
== Tutorial: *opsi-script*-Skript erstellen

include::common:partial$softwintegration-tutorial-introduction.adoc[]

[[opsi-winclient-softwintegration-tutorial-general]]
=== Nicht-interaktive Software-Installation (Windows)

Grundsätzlich stehen Ihnen drei Methoden zur Verfügung, um ein Softwarepaket in die automatische Softwareverteilung für Windows-Betriebssysteme zu integrieren. Zusätzlich gibt es eine Variante, die den Dienst https://learn.microsoft.com/de-de/windows/win32/msi/windows-installer-portal[Windows Installer] verwendet:

. *Unattended*/*Silent Setup*: +
Bei dieser Methode verwenden Sie das Original-Setup-Programm und versetzen es mit Kommandozeilen-Parametern in einen nicht-interaktiven Modus. Der wichtigste Spezialfall ist der „stille“ Aufruf eines MSI-Paketes, das Sie mit der `/quiet`-Option des Tools https://learn.microsoft.com/de-de/windows-server/administration/windows-commands/msiexec[*msiexec*] installieren.

. *Interaktives Setup mit automatisierten Antworten*: +
Zur Vorbereitung führen Sie das ursprüngliche Setup-Programm einmal aus und notieren dabei, welche Fenstertitel es anzeigt und welche Fragen und Antworten während des Setups auftreten. Diese Informationen halten Sie in einem Skript fest. Im Softwareverteilungs-Prozess steuert ein Automatisierungs-Programm wie z.{nbsp}B. link:https://www.autoitscript.com/site/[AutoIt] oder link:https://www.autohotkey.com/[AutoHotkey] das Setup-Programm nach den Vorgaben des Skriptes.

. *Setup-Routine mit `opsi-script` nachbilden*: +
Während das Original-Setup-Programm läuft, protokolliert ein Tool wie link:https://learn.microsoft.com/de-de/sysinternals/downloads/procmon[Prozessmonitor/Procmon] sämtliche Systemänderungen. Basierend auf diesen Daten und den erfassten Änderungen erstellen Sie das `opsi-script`-Skript.

NOTE: opsi unterstützt alle drei Varianten. In der Praxis kommt häufig eine Kombination aus mehreren Methoden zum Einsatz.

include::common:partial$softwintegration-tutorial-script-structure-opsi-script-basics.adoc[]

[[opsi-winclient-softwintegration-tutorial-Windows-special-commands]]
===== Spezielle Windows-Kommandos

* `getOS : string`: Gibt das Betriebssystem aus, z.{nbsp}B. `Linux`, `Windows_NT` (Windows NT bis Windows 11) oder `macOS`.

* `getMsVersionInfo : string`: Gibt auf Windows-Systemen Informationen über die interne Version aus; z.{nbsp}B. produziert ein Windows 7 das Ergebnis "6.1", Windows 11 liefert "10.0" usw.

* `GetMsVersionName`: Gibt die Marketing-Version für ein Windows-System aus, z.{nbsp}B. produziert ein Windows 7 das Ergebnis "7.0", Windows 11 liefert "11.0" usw.

* `getMSVersionMap : stringlist`: Fragt die Betriebssystem-Informationen lokal ab und schreibt die Informationen in eine String-Liste.

TIP: Weiterführende Informationen zu diesen String-Funktionen lesen Sie im Abschnitt xref:opsi-script-manual:prim-section.adoc#opsi-script-string-functions-os[String-Funktionen (Betriebssystem ermitteln)].

[[opsi-winclient-softwintegration-tutorial-template]]
==== Beispiel: Windows-Template *opsi-template*

Dieses Template können Sie mit dem `opsi-setup-detector` erstellen (siehe Abschnitt <<opsi-winclient-softwintegration-tutorial-create-with-opsi-setup-detector>>).

include::{version}@opsi-docs-en:common:partial$firststeps-opsi-template-win.adoc[]

[[opsi-client-softwintegration-create-opsi-package]]
== opsi-Produkte erstellen

Die nächsten Abschnitte erklären, wie Sie Software paketieren, also opsi-Produkte erstellen. Der grundlegende Ablauf sieht so aus:

1. Den "Rohbau" eines Paketes erstellen Sie mit dem `opsi-setup-detector` (siehe Abschnitt <<opsi-winclient-softwintegration-tutorial-create-with-opsi-setup-detector>>).
2. Danach testen Sie das opsi-Script.
3. Mit dem opsi PackageBuilder (oPB) erstellen Sie aus der Rohform ein opsi-Paket und hinterlegen es auf dem opsi-Server.

// include docu: opsi-setup-detector installation
include::common:partial$setup-detector-installation.adoc[]

// include docu: opsi-logviewer installation
include::common:partial$opsi-logviewer-installation.adoc[]

//##hier
[[opsi-winclient-softwintegration-tutorial-create-with-opsi-setup-detector]]
== Das Programm opsi-setup-detector zum Erstellen eines Windows Scriptes

// include docu: opsi-setup-detector
//einfügen: (siehe Kapitel xref:opsi-modules:setup-detector.adoc[*opsi-setup-detector* (frei)]).
include::common:partial$setup-detector-use-start.adoc[leveloffset=0]

// include docu: Windows specific tasks in opsi-setup-detector
include::common:partial$osd-tasks-windows.adoc[]

// include docu: how to use the opsi-setup-detector
include::common:partial$osd-task-use-single-analyze-and-create.adoc[leveloffset=0]

Mehr Details zum `opsi-setup-detector` finden Sie im opsi-manual: +
https://docs.opsi.org/opsi-docs-de/4.2/manual/modules/setup-detector.html

// include docu: how to use the opsiPackagebuilder
include::common:partial$softwintegration-tutorial-packagebuilder-use.adoc[leveloffset=-1]

// include docu: The modify and test cycle
include::common:partial$softwintegration-tutorial-modify-test-cycle.adoc[]

[[opsi-winclient-softwintegration-tutorial-template-details]]
== Hinweise zu den Teilaufgaben in der Paketierung

// include docu: OSD Checkboxes for additional code
include::common:partial$osd-checkboxes-subtasks.adoc[]


[[opsi-winclient-softwintegration-tutorial-opsiadmin]]
== Installation mit angemeldetem Benutzer

Vereinzelt taucht das Problem auf, dass sich Installationen nur bei angemeldetem Benutzer durchführen lassen.
Ein Hinweis auf diese Problematik ist es, wenn ein opsi-script-Skript das eine unattended Installation enthält,
beim manuellen Aufruf durch einen administrativen Benutzer funktioniert, im Rahmen der automatischen Installation über opsi jedoch scheitert.

Eine mögliche Ursache ist dann, dass dieses Setup-Programm einen angemeldeten Benutzer bzw. den Zugriff auf ein Benutzer-Profil benötigt.

In einem solchen Fall können Sie Ihre Installation in ein opsi-Rahmenpaket einbinden das diese benötigten Voraussetzungen schafft. +
Dies können Sie über den opsi-setup-detector über die Windows Aufgabe _Analysiere Datei und erzeuge ein Paket 'with user'_ erledigen.


[[opsi-winclient-softwintegration-tutorial-customizing]]
== Customizing nach einer silent/unattended Installation

Häufig will man nach einer erfolgreichen Silent-Installation Anpassungen an der Installation vornehmen.
Hierzu bietet der opsi-script ein mächtiges Werkzeug.
Doch bevor dies eingesetzt werden kann muss oft ermittelt werden, welche in der graphischen Oberfläche getätigten Änderungen zu
welchen Veränderungen in Dateien und der Registry führen.


Hierzu können Werkzeuge verwendet werden wie z.B.: +

* link:http://www.sysinternals.com/[sysinternals]
* link:https://sourceforge.net/projects/regshot/[regshot]

[[opsi-winclient-softwintegration-tutorial-autoit]]
== Einbindung mittels interaktiven Setup-Programms und automatisierten Antworten

Eine weitere schnelle Möglichkeit zur Einbindung in die automatische Softwareverteilung ist das 'Setup mit automatisierten Antworten'.
Hierzu wird eine Steuerungs-Software verwendet, die über ein Skript die Interaktion eines Anwenders mit den erscheinenden Dialog-Fenstern automatisiert. +
Wir empfehlen hierfür den Einsatz der Software link:https://autohotkey.com[AutoHotkey] oder link:http://www.autoitscript.com[AutoIt].

'AutoIt' bietet eine ganze Reihe zusätzlicher Möglichkeiten, den Setup-Prozess zu steuern.
Auch eventuelle Fehlerzustände können (so vorher bekannt) mit dem Einsatz von +[ADLIB]+-Sektionen im Skript abgefangen werden.

Ein prinzipielles Problem bleibt bestehen: Nicht vorhergesehene (und im Skript berücksichtigte) Fenster können das Skript zum Stoppen bringen.

Außerdem kann der Anwender mittels Maus und Tastatur (wenn diese nicht gesperrt sind) in den automatisierten Prozess eingreifen und den Ablauf damit verändern.
Ein Unattended- oder Silent-Setup ist daher immer die bessere Lösung.

Sehr gut kann auch eine Kombination aus beiden Ansätzen funktionieren:
Das Silent-Setup übernimmt die eigentliche Installation und ein AutoIt-Skript fängt bekannte Sonderbedingungen ab.

Wenn das Ausführen von Installationen in der opsi-client-agent Konfiguration auf einen anderen Desktop verlegt wird oder der Desktop gesperrt wird, haben verschiedene autoit Funktionen Probleme.

Daher sollten in 'opsi-script' Skripten die folgenden Funktionen gemieden werden:

* winwait()

* winactivate()

* Send()

Das sind leider genau die 3 am meisten verwendeten.

Wir empfehlen zur Ersetzung dieser Befehle die Verwendung der mit dem opsi-script mit gelieferten autIt Library: `C:\Program Files (x86)\opsi.org\opsi-client-agent\opsi-script\lib\opsi-autoit-lib.au3`.
Diese bietet neben den hier vorgestellten erweiterten Funktionen auch noch ein logging. 
Sie können diese Datei in das Produktverzeichnis kopieren und dann in den AutoIT code einbinden mit: `#include "%scriptpath%\opsi-autoit-lib.au3"

*winwait()* +
kann ersetzt werden durch die Funktion +
`opsiwinwait($title, $text, $maxseconds, $logname)`

*Send()* +
kann ersetzt werden durch die Funktion +
`opsiControlClick($title, $text, $id, $maxseconds, $logname)` +
bzw. durch +
`opsiControlSetText($title, $text, $id,$sendtext, $maxseconds, $logname)`


Es empfiehlt sich zur Identifikation der Controls mit der `Au3info.exe` die 'ControlId' ermittelt werden. Bitte die numerische 'ControlId' verwenden, andere Varianten scheinen Probleme zu machen.

Beispiele finden sie in: `C:\Program Files (x86)\opsi.org\opsi-client-agent\opsi-script\lib\` in den Dateien `autoit_example_1.txt` und `autoit_example_1.txt`.

siehe auch: +
http://www.autoitscript.com/wiki/FAQ#Why_doesn.27t_my_script_work_on_a_locked_workstation.3F +
http://www.autoitscript.com/autoit3/docs/ +
http://www.autoitscript.com/autoit3/docs/intro/controls.htm +
http://www.autoitscript.com/autoit3/docs/functions.htm




[[opsi-winclient-softwintegration-tutorial-analyse-and-repackage]]
== Analyse und Neu-Paketieren

Wenn der Entwickler einer Anwendung ein Paket zur Auslieferung der Anwendung schnürt, kennt er die benötigten Komponenten.
Im Nachhinein, wenn schon ein Paket existiert, das mittels eines Setup-Programm zu installieren ist,
kann die Kenntnis, welche Komponenten installiert werden müssen, damit eine Anwendung wie gewünscht auf einem Arbeitsplatzrechner lauffähig ist,
aus der Studie der Effekte bei der Ausführung des vorhandenen Setup-Programms gewonnen werden.

Eine Reihe von Werkzeuge zum Analysieren von Setup-Programmen kommen hierbei in Frage. So z.B.:


* link:https://sourceforge.net/projects/regshot/files/regshot/[regshot]

* link:http://www.itninja.com/media/downloads/appdeploy-repackager.msi[appdeploy-repackager]

[[opsi-winclient-softwintegration-tutorial-deinstall]]
== Verfahren zur Deinstallation von Produkten

Um eine installierte Software von einem Rechner zu entfernen, kann ein Deinstallations-Skript erstellt werden.
Grundsätzlich besteht bei einer Deinstallation die Schwierigkeit, dass nicht immer klar ist,
wie das Produkt auf dem Rechner vorliegt und was alles entfernt werden muss.
Auch nach der Installation können neue Dateien oder Registry-Einträge, die die Software betreffen, hinzugekommen sein.
Weiterhin muss darauf geachtet werden nicht zu viel zu entfernen, um die Systemstabilität nicht zu gefährden.
Meist weiß nur der Hersteller genau, wie mit seinem Produkt bei der Deinstallation umzugehen ist.
Ähnlich wie bei der Installation, existieren zu diesem Zweck Deinstallations-Routinen, die dem Produkt beiliegen.
Wenn es die Möglichkeit gibt, diese ohne Benutzer-Interaktion auszuführen, kann dies schon ein entscheidender Schritt sein.
Ist eine solche Routine nicht vorhanden oder muss diese erweitert werden, so existieren viele opsi-script-Befehle, die zur Deinstallation nützlich sein können.
Im Folgenden soll nun ein Überblick über Möglichkeiten zur Deinstallation gegeben werden, die durch Beispiele verdeutlicht werden.

.Verwenden einer Deinstallations-Routine

Liefert der Hersteller des Produktes ein Programm (oder ein MSI-Paket) zur Deinstallation, so muss zunächst geprüft werden,
ob dies auch ohne Benutzer-Interaktion ausgeführt werden kann (silent-mode).
Sollte dies nicht von Hause aus möglich sein, kann der Einsatz eines AutoIt-Skriptes in Verbindung mit der Deinstallations-Routine hilfreich sein.
Der Aufruf der ausführbaren Datei kann im opsi-script-Skript in einer Winbatch-Sektion geschehen, z.B.:

[source,winst]
----
[WinBatch_start_ThunderbirdUninstall]
"%SystemRoot%\UninstallThunderbird.exe" /ma
----

Trotz dieser Unterstützung des Herstellers sollte man sich jedoch nicht auf die korrekte Beseitigung des Produktes verlassen
und auf einem Testsystem zusätzlich prüfen, ob das System nach der Deinstallation weiter stabil läuft und ob Dateien oder
Registry-Einträge zurückgeblieben sind.

Falls das Produkt als MSI-Paket bereitgestellt und mittels 'msiexec' installiert wurde,
ist es in der Regel auch eine Deinstallation mittels 'msiexec' möglich.
Dazu ruft man den `msiexec.exe` mit dem Parameter +/x+ auf und übergibt zusätzlich den MSI-Paket oder dessen 'GUID' an.
Um die Benutzer-Interaktion zu deaktivieren, kann zusätzlich der Parameter +/qb-!+ übergeben werden. +
Dies ergibt nun den folgenden Aufruf:

[source,winst]
----
msiexec.exe /x some.msi /qb-! REBOOT=ReallySuppress
----

Statt das MSI-Paket zu übergeben, gibt es auch die Möglichkeit die 'GUID' an `msiexec.exe` zu übergeben.
Diese ID ist eindeutig, Produkt-spezifisch und auf allen Systemen, auf denen das MSI-Paket installiert ist, gleich.
Sie findet sich zum Beispiel im Zweig
+HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall+ der Registry. +
Ein Beispiel einer Deinstallation mittels dieser GUID sieht folgendermaßen aus:

[source,winst]
----
msiexec.exe /x {003C5074-EB37-4A75-AC4B-F5394E08B4DD} /qb-!
----

Sollten diese Methoden nicht oder nicht vollständig funktionieren, so muss mit einem opsi-script-Skript nachgeholfen werden,
wie es im nächsten Abschnitt beschrieben ist.

.Nützliche opsi-script-Befehle zur Deinstallation

Wurde ein Produkt mit den opsi-script-Funktionen installiert oder gibt es keine Deinstallation vom Hersteller,
so muss ein eigenes opsi-script-Skript zu Deinstallation geschrieben werden.
Um den Programmierer bei dieser Arbeit zu unterstützen stellt der 'opsi-script' einige Funktionen bereit,
die speziell bei der Deinstallation notwendig oder hilfreich sind.
Es soll an dieser Stelle nur ein kurzer Überblick gegeben werden,
eine genaue Beschreibung der Befehle und deren Parameter findet sich im opsi-script-Handbuch.

Der einfachste Fall ist das Löschen einer oder mehrerer Dateien vom System. Dies geschieht in einer Files-Sektion mittels des Befehls

[source,winst]
----
delete -f Dateiname
----

oder für ein Verzeichnis mit Unterverzeichnissen

[source,winst]
----
delete -sf Verzeichnisname\
----

Der Parameter +f+ steht dabei für force, um die Datei wirklich zu löschen, auch wenn diese schreibgeschützt ist,
der Parameter +s+ für subdirectories (mit Unterverzeichnissen/rekursiv).
Soll eine Datei oder ein Verzeichnis aus allen Benutzer-Profilen gelöscht werden,
so kann diese Files-Sektion mit dem Parameter +/AllNTUserProfiles+ aufgerufen werden. (siehe opsi-script-Handbuch)

Möchte man einen Verzeichnisbaum löschen, in dem sich auch Dateien mit dem Attribut „versteckt“ oder „systemdatei“ befinden,
muss momentan ein Umweg über den Befehl `rmdir` gegangen werden, der über eine 'DosInAnIcon'-Sektion aufgerufen werden kann.

[source,winst]
----
[DosInAnIcon_deleteDir]
rmdir /S /Q "<Verzeichnis>"
----

Muss vor dem Löschen evtl. ein laufender Prozess beendet werden, so kann dies mit dem Namen des Prozesses (zu sehen im Task-Manager)
und dem opsi-script-Befehl +KillTask+ geschehen:

[source,winst]
----
KillTask "thunderbird.exe"
----

Sollte das Produkt – oder Teile davon – als Service laufen, so muss dieser vor der Deinstallation beendet werden.
Man kann dazu den Service in der Registry auf “inaktiv“ schalten und den Rechner neu starten oder aber man benutzt den System-Befehl
`net` mit dem Parameter +stop+, um den Service sofort zu stoppen und anschließend – ohne Neustart – die zugehörigen Dateien zu löschen.

[source,winst]
----
net stop <servicename>
----

Besondere Vorsicht ist beim Löschen von .dll-Dateien geboten, die noch von anderen Produkten verwendet werden könnten.
Sie müssen individuell behandelt werden, weshalb hier leider kein allgemein gültiges Rezept gegeben werden kann.

Um einzelne Einträge aus der Registry mittels opsi-script zu löschen, kommt der Befehl +DeleteVar+ zum Einsatz,
der innerhalb einer 'Registry'-Sektion eines opsi-script-Skriptes verwendet werden kann.
Er löscht Einträge aus dem momentan geöffneten Key:

[source,winst]
----
DeleteVar <VarName>
----

Möchte man einen Registry-Key samt seiner Unterschlüssel und Registry-Variablen löschen, so geschieht dies mittels des opsi-script-Befehls +DeleteKey+, z.B.:

[source,winst]
----
DeleteKey [HKLM\Software\Macromedia]
----

[[opsi-winclient-softwintegration-tutorial-deinstall-msi]]
==== Verfahren zur Deinstallation von MSI Produkten


Falls das Produkt als MSI-Paket bereitgestellt und mittels 'msiexec' installiert wurde, ist es in der Regel auch eine Deinstallation mittels 'msiexec' möglich.
Dazu ruft man den `msiexec.exe` mit dem Parameter `/x` auf.
Um die Benutzer-Interaktion zu deaktivieren, kann zusätzlich der Parameter +/qb-!+ übergeben werden. +
Um das MSI Paket zu identifizieren muß weiterhin noch die GUID (Global Unique ID) des Paketes übergeben werden. Die GUID identifiziert das MSI Paket und ist Bestandteil der MSI-Datei. Diese ID ist eindeutig, Produkt-spezifisch und auf allen Systemen, auf denen das MSI-Paket installiert ist, gleich. +
Sie findet sich zum Beispiel im Zweig
+HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall+ der Registry. +
Ein Beispiel einer Deinstallation mittels dieser GUID sieht folgendermaßen aus:

[source,winst]
----
msiexec.exe /x {003C5074-EB37-4A75-AC4B-F5394E08B4DD} /qb-!
----

Die GUID kann sich beim selben Produkt von Version zu Version ändern. Um vorhandene und evtl. ältere Installationen zu löschen, muss also ermittelt werden welche GUID diese Installationen haben. +
Eine Möglichkeit dies zu tun geht über den `MsiName` des Paketes welcher vom opsi-setup-detector aus der MSI-Datei ermittelt werden kann. Der `MsiName` wird im oben erwähnten Uninstalleintrag in der Registry als `DisplayName` verwendet. Daher kann der `MsiName` verwendet werden um die passenden GUID's in der Registry zu finden. +
Um das zu tun, müssen Informationen zu Architektur und Version vom Ende des `MsiName` abgeschnitten werden und das ganze in eine regular expression verpackt werden.

Dies ist der Code der vom opsi-setup-detector zu Deinstallation von MSI erzeugt wird:

[source,winst]
----
; Finding the MsiId by the Displayname from Registry:
; Be sure that the Displayname is set correctly:
Set $DisplayName$ = 'short msi name'
; escape all regex relevant chars with '\' : '\^$.|?*+()[{'
set $DisplayNameRegex$ = escapeRegexMetaChars($DisplayName$)
; '(?i)' = case insensitive ; '.*' = 0 or more of any thing
set $DisplayNameRegex$ = '(?i)'+$DisplayNameRegex$+'.*'
Set $UninstallList$ = getGuidListByDisplaynameRegex($DisplayNameRegex$)
;-----------------------------------------------------

; ---------------------------------------------------------------
comment "run the uninstallation "
; ----------------------------------------------------------------

if count($UninstallList$) int> "0"
	Comment "Uninstalling all found versions"
	for %uninstallEntry% in $UninstallList$ do Sub_Uninstallation_msi
endif

[Sub_Uninstallation_msi]
set $MsiVersion$ = TakeString(0, splitstring('%uninstallEntry%', "="))
set $MsiId$ = TakeString(1, splitstring('%uninstallEntry%', "="))

if stringtobool(checkForMsiProduct($MsiId$))
	Message "Uninstalling :"  + $ProductId$ + " " + $MsiVersion$+ "..."
	Winbatch_Uninstall_1
	Set $ExitCode$ = getlastexitcode
	if stringtobool(isMsiExitcodeFatal($ExitCode$, "true", $ErrorString$ ))
		LogError $ErrorString$
		isfatalerror $ErrorString$
	else
		Comment $ErrorString$
	endif
else
	Comment "No previously installed " + $ProductId$ + " version found"
endif
----

Kurze Beschreibung was in diesem Scriptteil passiert:

* `Set $DisplayName$ = 'short msi name'` +
Setzen der Variable $DisplayName$ auf den `MsiName` gekürzt um störende anhängende Informationen.

* Den $DisplayName$ als regular expression Suchstring präparieren: +
Alle regular expression Sonderzeichen verstecken (maskieren): +
`set $DisplayNameRegex$ = escapeRegexMetaChars($DisplayName$)` +
Angeben, das der Suchstring am Anfang der Zeile steht und 0 oder mehr beliebige Zeichen folgen dürfen: +
`set $DisplayNameRegex$ = '(?i)'+$DisplayNameRegex$+'.*'`

* Suchen in der Registry: +
`Set $UninstallList$ = getGuidListByDisplaynameRegex($DisplayNameRegex$)` +
Die Funktion getGuidListByDisplaynameRegex ist Bestandteil der Library osd-lib.opsiscript und erzeugt eine Liste von als passend gefundenen Einträgen in der Form: +
<MsiVersion> = <msi GUID> 

* Die Deinstallation durchführen:
Nun können wir die Liste durchgehen und die gefundenen GUIDs zur Deinstalltion verwenden. Die passiert in der Sektion: `[Sub_Uninstallation_msi]`


[[opsi-winclient-softwintegration-tutorial-64bit]]
== Bekannte Besonderheiten der 64 Bit-Unterstützung

Der {opsi-script} ist ein 32-Bit Programm.
Skripte zur Installation von 32-Bit Programmen funktionieren in der Regel auch auf 64-Bit Systemen korrekt. +
Für die Installation von 64-Bit Software mit {opsi-script} und allgemein
beim Arbeiten auf 64-Bit-Systemen beachten Sie bitte das entsprechende Kapitel im link:https://docs.opsi.org/opsi-docs-de/4.2/opsi-script-manual/64bit.html[opsi-script manual, 64 Bit-Unterstützung unter Windows].
