////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      12.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[firststeps-osinstall]]
= Linux mit opsi installieren

Dieses Kapitel beschreibt, wie Sie verschiedene Linux-Distributionen auf einem bisher nicht mit einem Betriebssystem ausgestatteten Computer per opsi installieren. Als Client-Rechner eignen sich physische Computer oder virtuelle Rechner mit den folgenden Voraussetzungen:

* 2{nbsp}GByte RAM; Ubuntu 22.04: mindestens 4{nbsp}GByte RAM 
* Netzwerkkarte mit Netzboot-Unterstützung (Unterstützung des PXE-Protokolls zum Laden von Bootmedien via Netzwerk)

NOTE: Überprüfen Sie die Einstellungen im BIOS. Netzboot muss aktiviert sein und an erster Stelle der Bootoptionen stehen, damit Sie Linux per opsi installieren können.

Grundsätzlich gibt es zwei verschiedene Wege:

* <<firststeps-osinstall-netboot-distro>>
* <<firststeps-osinstall-netboot-gen>> 

[[firststeps-osinstall-netboot-distro]]
== Netboot-Produkte (Installer der Distribution)

Zunächst geht es die distributionseigenen Installer. Ähnlich wie bei der Windows-Installation, stellt opsi für den Installer eine Antwortdatei bereit, die er dann für die nicht-interaktive Installation nutzt.

NOTE: Der distributionseigene Installer ist kein eigentliches Programm, das opsi dann aufruft. Stattdessen handelt es sich um eine Kombination aus Kernel und `initrd` der Distributionen.

Die grundsätzliche OS-Installation, inklusive Partitionierung, LVM, Basissoftware usw., liegt in der Hand des Installers und findet nach dem Start des opsi-Linux-Bootimages statt. Wie Sie die Installations-Quellen bereitstellen, hängt unter anderem von der Linux-Distribution ab bzw. von dem opsi-Netboot-Paket ab:

* Debian-basierte Distributionen (Debian, Ubuntu, Linux Mint usw.): Diese Distributionen verwenden die Installations-Quellen aus dem Netz. In der Depot-Freigabe liegen lediglich die Netboot-Versionen der Kernel und der dazugehörigen `initrd`-Dateien. Da diese Dateien nicht besonders viel Platz benötigen, sind sie Teil des opsi-Paketes. Ausnahmen sind:

  - Ubuntu 22.04: Das Paket `ubuntu22-04` erwartet ein ISO-Image im Produkt-Unterverzeichnis `iso`.
  - Linux Mint: Ab Version 4.2.0.2-1 erwarten die Netboot-Pakete ein ISO-Image im Produkt-Unterverzeichnis `iso`.
 
* SUSE- und Red-Hat-basierte Distributionen: Benutzer stellen die Installations-Quellen bereit und legen dazu ein ISO-Image auf dem Depot-Share ab.
 
TIP: Installieren Sie nicht nur das Betriebssystem, sondern auch gleich den xref:clients:linux-client/linux-client-agent.adoc[Linux-Client-Agent], um den neuen Client mit opsi zu verwalten.

=== Ablauf der Installation

So sehen die einzelnen Schritte bei der Installation mit dem distributionseigenen Installer und dem opsi-Netboot-Produkt aus:

. Sie booten das opsi-Linux-Bootimage; dieses löscht eventuell vorhandene Partitionstabellen und erstellt eine kleine, temporäre Hilfspartition.

. Das opsi-Linux-Bootimage holt sich das `initrd` der Distribution und entpackt es in der Hilfspartition.

. Das opsi-Linux-Bootimage holt sich die generische Vorlage für die Antwortdatei, passt diese an (personalisiert sie) und legt sie ins `initrd`-Verzeichnis.

. Danach erzeugt das Bootimage weitere Skripte und Konfigurationsdateien (z.{nbsp}B. zur Installation des Client-Agent) und speichert sie ebenfalls im `initrd`-Verzeichnis.

. Das angepasste `initrd`-Verzeichnis wird wieder zusammengepackt.

. Das opsi-Linux-Bootimage bootet den Distributions-Kernel mit dem gepatchten `initrd` per `kexec`.

. Das so geladene System installiert das Zielsystem unattended und installiert abschließend den `opsi-linux-client-agent`.

Die Vorteile dieses Vorgehens sind:

* Die Installation findet exakt gemäß den Distributions-Anforderungen statt. Besonders in Unternehmen mit Supportverträgen kann das besonders wichtig sein.

* Die Integration neuer Releases in opsi wird einfacher und dadurch schneller.

* Bei den SUSE- und Red-Hat-basierten Distributionen, bei Linux Mint und Ubuntu 22.04 findet die Installation aus Quellen statt, die auf dem opsi-Server liegen. Das ist schneller und unempfindlicher gegen Störungen als die Installation über Internet-Repositorys.

[[firststeps-osinstall-netboot-distro-prepare]]
=== Installations-Medien per WebDAV

Bereitstellung und der Installationsmedien auf dem Server per opsifond WebDAV

Dies betrifft die RedHar-artigen Distributionen ab Version 4.2.0.3-1, die SLES-artigen Distributionen ab Version 4.2.0.2-1 und Linux Mint ab 4.2.0.2-1.

Die RedHat- und SUSE-artigen Distributionen, sowie Linux Mint und Ubuntu22-04 nutzen seit den oben genannten Versionen keinen NFS-Server mehr zur Verteilung der Installationsmedien. Vielmehr gibt es in den jeweiligen Produktverzeichnissen ein Unterverzeichnis `iso` bzw. `isocontent`.

In das `iso` Verzeichnis wird das ISO Image abgelegt. Das `isocontent` Verzeichnis beinhaltet den Inhalt eines ISO Images, analog zum `installfiles` Verzeichnis eines Windows-Netboot-Paketes.

Hier ein Beispiel anhand des SLES15-3 Produktes.

[source,shell]
----
mount SLE-15-SP3-Full-x86_64-GM-Media1.iso /mnt
cp -r /mnt/* /var/lib/opsi/depot/sles15-3/isocontent/
cp /mnt/.treeinfo /var/lib/opsi/depot/sles15-3/isocontent/
cp /mnt/.discinfo /var/lib/opsi/depot/sles15-3/isocontent/
umount /mnt
----

Hinweis: Die Datei `.discinfo` ist nicht bei allen Distributionen vorhanden und kann dementsprechend fehlen.


[[firststeps-osinstall-netboot-distro-generalproperties]]
=== Allgemeine Propertys

der opsi Linux Netboot Produkte mit distributions Installer

Die folgenden Propertys finden Sie zur Steuerung der Linuxinstallation in allen v406 Netbootprodukten:

* `askbeforeinst`: +
Soll das Starten der Installation am Client bestätigt werden müssen?  (Default='true')

* `architecture`: +
Mit welcher Architektur soll das Zielsystem installiert werden? +
Beeinflusst außerdem das verwendete Bootimage.  (Default='64bit')

* `language` oder `locale`: +
Welche Sprache / locale soll installiert werden.  (Default=Distributionsabhängig / 'de')

* `console_keymap`: (nicht unter ubuntu22-04!) +
Zu installierendes Tastaturlayout.  (Default=Distributionsabhängig / 'de')

* `timezone`: +
Welche Zeitzone soll verwendet werden?. (Default='Europe/Berlin')

* `root_password`: +
Passwort für root.  (Default='linux123')

* `user_password`: +
Passwort für user.  (Default='linux123')

* `proxy`: +
Proxystring (wenn benötigt) in der Form: 'http://<ip>:<port>'. (Default=pass:[''])

* `install_opsi-client-agent`: +
Installiere den opsi-client-agent für Linux (Kofinanzierungsprojekt: Sie benötigen eine Aktivierung durch die /etc/opsi/modules). (Default='true')

* `setup_after_install`: +
Welche opsi-Produkte sollen zum Abschluss der Betriebssysteminstallation auf *setup* gestellt werden. (Default='')


[[firststeps-osinstall-netboot-distro-special-ubuntu14-04]]
=== Produkte: Debian, Ubuntu und Linux Mint

debian 12  debian10, debian11 und ubuntu18-04, ubuntu20-04, ubuntu22-04 und mint20-1, mint20-2, mint20-3, mint21, mint21-1

Die Basis-Installation erfolgt direkt aus dem Netz, mit Ausnahme vom Netboot Paket ubuntu22-04. Hier muss zusätzlich im Produktverzeichnis im Unterverzeichnis iso ein ISO abbild hinterlegt werden. 

Bedingt durch den Wechsel des verwendeten Installers sind nicht alle aufgeführten Propertys im Netboot Paket ubuntu22-04 (und neuer) enthalten. Die entsprechenden Propertys haben jeweils einen Hinweis auf das Fehlen im Netboot Paket ubunut22-04

Das Produkt hat produktiven Status.

Das Produkt hat folgende zusätzliche Propertys:

* `online_repository`: +
Repository der Distribution für die Installation. (Nur bei Debian/Ubuntu Produkten) (Default=Distributionsabhängig)

* `encrypt_password`: (nicht unter ubuntu22-04!) +
Passwort für die Festplattenverschlüsselung (nur verwendet wenn encrypt_logical_volumes=true) +
Example: `linux123` Default: `linux123`

* `installation_method`: +
Methode zur Installation des Installers. Funktioniert nur mit der UEFI Erweiterung: +
`reboot`: Es wird eine kleine Partition angelegt und nach einem Reboot wird der Installer von dieser Partition gestartet. / `kexec`: Das opsi-linux-bootimage startet den Installer direkt per kexec, es erfolg kein Reboot.
Possible: "reboot", "kexec" +
Default: `kexec`

* `partition_disk`: (nicht unter ubuntu22-04!) +
Zu verwendende Festplatte: `first` oder kompletter device path (nicht unter ubuntu22-04!)
Examples: "first", "/dev/sda", "/dev/sdb" +
Default: `first`

* `preseed`: (unter ubuntu20-04 `autoinstall`) +
Zu verwendende Autonstallationsdatei. Diese muss sich im Produktverzeichnis im Unterordner `custom` befinden.
Examples: "auto", "raid.cfg", "raid.yml" (ubuntu22-04 +
Default: `auto`

* `partition_method`: +
Methode zur Partitionierung der Festplatte: +
`regular`: Standard Partionierung (unter ubuntu22-04: `direct`)/ `lvm`: LVM's anlegen / `crypto`: In einer verschlüsselten Partition LVM's anlegen (nicht unter ubuntu22-04!) +
Possible: "regular" oder "direct", "lvm", "crypto" +
Default: `lvm`

* `partition_recipe`: (nicht unter ubuntu22-04!)+
Die Art der verwendeten Partitionierung: +
`atomic`: Alles in einer Partition / `home`: eigene /home Partition / `multi`: eigene /home, /usr, /var, und /tmp Partitionen
Possible: "atomic", "home", "multi" +
Default: `atomic`

* `desktop_package`: +
Zu installierendes desktop package (standard = kein desktop) (Nur bei Debian/Ubuntu Produkten).
Possible: "standard", "ubuntu-desktop", "kubuntu-desktop", "lubuntu-desktop", "xubuntu-desktop", "ubuntu-gnome-desktop" +
Default: `standard`

* `language_packs`: (nicht unter ubuntu22-04!)+
Possible: "ar", "bg", "by", "cf", "de", "dk", "en", "es", "et", "fa", "fi", "fr", "gr", "il", "it", "kg", "kk", "lt", "mk", "nl", "no", "pl", "ro", "ru", "sg","sr", "ua", "uk", "us", "wo" +
Default: `de`


.Videos (Zeitraffer)

Folgende Videos zeigen jeweils eine Installation. +
Sie sind mit einem Frame pro Sekunde aufgenommen und dadurch schneller anzusehen als die Installation eigentlich dauert.
//neues Video
* link:http://download.uib.de/press-infos/videos/opsi-linux/debian8_406_1fps.mp4[Debian 8]

[[firststeps-osinstall-netboot-distro-special-ucs]]
=== Produkte: Univention Corporate Server (UCS)

Die Basis-Installation bezieht ihre Pakete von den offiziellen UCS Repositories. 

Dieses Produkt hat einen produktiven Status.

//Hinweis: Primary, Secondary
Mit diesem Produkt ist es möglich, einen Master-, Slave-, Backup, und einen Member-Server zu installieren.
Wir empfehlen das l-opsi-server Produkt, um aus einer UCS Maschine auch einen opsi-Server zu machen.
Dieses Produkt ermöglicht es auch Clients über einen Member-Server zu installieren, hierfür werden einige Besonderheiten durchgeführt.

Das Produkt hat über die oben genannten Propertys eines z.B debian11 oder debian12 Produktes noch die folgenden zusätzlichen UCS spezifischen Propertys:

* `dns_domain`: +
Der DNS Domain Name: +
Example: `example.com` Default: `ucs.test`

* `ldap_base`: +
ldap base.
Example: `dc=example,dc=com` Default: `dc=ucs,dc=test`

* `ucs_code_name`: +
Der Codename der UCS-Version, welche im onlien Repository bereit gestellt wird. +
Example: `ucs414` Default: `ucs414`

* `organisation`: +
Der Name der Organisation der bei der UCS Installation verwendet wird. +
Example: `uib gmbh` Default: `uib gmbh`

* `windomain`: +
Der Name der Samba/Windows Domain. +
Example: `MYDOMAIN` Default: `MYDOMAIN`

* `external_nameserver`: +
Welcher externe Nameserver soll bei der Installation verwendet werden ? +
Example: `10.11.12.13` Default: `auto` = the name server given by dhcp

* `ucs_master_ip`: +
Die IP-Nummer des UCS Domain Controller (wird beim joinen von anderen Rollen verwendet) ? +
Example: `10.10.10.10` Default: `10.10.10.10`

* `ucs_master_admin_password`: +
Das Administrator Passwort des UCS Domain Controller (wird beim joinen von anderen Rollen verwendet) ? +
Example: `linux123` Default: `linux123`

//Rollen nicht angepasst, bleibt
* `ucs_role`: +
Welche UCS Rolle soll installiert werden ? +
Possible: "domaincontroller_master", "domaincontroller_backup", "domaincontroller_slave", "memberserver", "base" +
Default: `domaincontroller_master`


[[firststeps-osinstall-netboot-distro-special-sles]]
=== Die Produkte: SLES und opsnSUSE

//Liste überarbeiten
 sles12sp3, sles12sp4, sles12sp5, sles15-1, sles15-2, sles15-3, sles15-4 und  opensusel15-4

Das Produkt hat folgende zusätzliche Propertys:

----
name: productkey
multivalue: False
editable: True
description: email:regcode-sles for suse_register. Is only used if the  host parameter  `license-management.use` is set to  false . If it set to  True  the license key will be get from the license management module. / La clé de licence pour l'installation. Est utilisée uniquement si dans "Réseau et paramètres supplémentaires" `license-management.use` est défini à false (faux) . Si c'est réglé sur True (vrai) la clé de licence sera obtenue du module de gestion des licences.
values: ["", "myemail@example.com:xxxxxxxxxxxxxx"]
default: [""]

name: suse_register
description: set to false, if you don't want to register your system online, if you set this to false you have to give local repositories
default: True

name: local_repositories
multivalue: True
editable: True
description: list of local repositories to use. Syntax: "repository description", example entry: "http://sles.example.com/suse/repo NameForRepo"
values: [""]
default: [""]

name: install_unattended
description: If false then do interactive installation
default: True
----

.Installationsquelle
Zum herunterladen der Installations DVD brauchen Sie zwingend einen Account bei SUSE. 
ISO Inhalt kopieren nach `/var/lib/opsi/depot/sles15-3/isocontent/`
Ausführung von `opsi-set-rights` nicht vergessen.


.Videos (Zeitraffer)

Folgendes Video zeigt eine Installation. +
Es ist mit einem Frame pro Sekunde aufgenommen und dadurch schneller anzusehen als die Installation eigentlich dauert.

* link:http://download.uib.de/press-infos/videos/opsi-linux/sles12_406_1fps.mp4[Suse Linux Enterprise Server 12]


[[firststeps-osinstall-netboot-distro-special-redhat70]]
=== Die Produkte: RHEL, AlmaLinux und Rocky Linux

//Liste: oracle 8 und 9
 redhat8, redhat9 und rocky8, rocky9 und alma8, alma9

Das Produkt hat folgende zusätzliche Propertys:

----
name: install_unattended
description: If false then do interactive installation
default: True

name: selinux_mode
multivalue: False
editable: False
description: In which mode should SELinux run ?
values: ["enforcing", "permissive", "disabled"]
default: ["permissive"]

name: partition_method
multivalue: False
editable: False
description: plain: Regular partitions with no LVM or Btrfs. / lvm: The LVM partitioning scheme. / btrfs: The Btrfs partitioning scheme. / thinp: The LVM Thin Provisioning partitioning scheme.
values: ["plain", "lvm", "btrfs", "thinp"]
default: ["lvm"]

name: productkey
multivalue: False
editable: True
description: email:regcode for subscription_register. Is only used if the  host parameter  `license-management.use` is set to  false . If it set to  True  the license key will be get from the license management module. / La clé de licence pour l'installation. Est utilisée uniquement si dans "Réseau et paramètres supplémentaires" `license-management.use` est défini à false (faux) . Si c'est réglé sur True (vrai) la clé de licence sera obtenue du module de gestion des licences.
values: ["", "myemail@example.com:xxxxxxxxxxxxxx"]
default: [""]

name: subscription_register
description: set to false, if you don't want to register your system online, if you set this to false you have to give local repositories
default: True
----

.Installationsquelle von AlmaLinux
Laden sie das ISO Image bitte herunter, z.B. hier link:https://repo.almalinux.org/almalinux/8/isos/x86_64/[here].
Den Inhalt der ISO kopieren nach `/var/lib/opsi/depot/alma8/isocontent/`
Bitte nicht vergessen `opsi-set-rights` auszuführen.

.Installationsquelle von RedHat
Zum Download der ISO benötigen sie einen RedHat Account.
Den Inhalt der ISO kopieren nach `/var/lib/opsi/depot/redhat8/isocontent/`
Bitte nicht vergessen `opsi-set-rights` auszuführen.

.Instalaltionsquelle von RockyLinux
Laden sie das ISO Image bitte herunter, z.B. hier link:https://rockylinux.org/download/[here].
Den Inhalt der ISO kopieren nach `/var/lib/opsi/depot/rocky8/isocontent/`
Bitte nicht vergessen `opsi-set-rights` auszuführen.


.Videos (Zeitraffer)

Folgende Videos zeigen eine Installation. +
Sie sind mit einem Frame pro Sekunde aufgenommen und dadurch schneller anzusehen als die Installation eigentlich dauert.

* link:http://download.uib.de/press-infos/videos/opsi-linux/centos70_406_1fps.mp4[CentOS 7]

* link:http://download.uib.de/press-infos/videos/opsi-linux/redhat70_406_1fps.mp4[RedHat 7]


[[firststeps-osinstall-netboot-gen]]
== Netboot-Produkte (generischer Installer)

*Basis-Installation des OS per Netboot*

Für die Installation eines Linux Basissystems wird zunächst per Netboot das Standard opsi-linux-bootimage gebootet (welches auch für die Windows-Installationen zum Einsatz kommt). +
Von diesem Bootimage aus wird die Ziel-Festplatte partitioniert (/ und swap) und formatiert. Nun folgt die Installation des Grundsystems (mit Netzwerkkonfiguration und ssh aber ohne X11). Die Abläufe dieser Grundinstallation unterscheiden sich naturgemäß zwischen den unterschiedlichen Distributionen erheblich. Gemeinsam ist, dass die Installation direkt aus den Originalpaketen der Distribution erfolgt.

Optional kann nun der opsi-client-agent für Linux installiert werden. Dieser ist dann für die Installation und Konfiguration weiterer Software zuständig.

Die opsi-Netboot-Produkte zur Linuxinstallation sind bereits als Open Source freigegeben.

Bedingt dadurch, dass die Basisinstallation aus dem Standard opsi-linux-bootimage erfolgt, gibt es distributionsabhängig unterschiedlich bestimmte Dinge, welche sich erst in der Umgebung nach dem ersten Boot des Systems konfigurieren bzw. installieren lassen. Beispiele hierfür sind die SELinux-Installation bei den 'RedHat artigen' bzw. die Konfiguration der Tastatur bei den 'Debian artigen'. Hierfür gibt es ein Standard Localbootprodukt `l-os-postinst` welches diese Aufgaben übernimmt.

[[firststeps-osinstall-netboot-generalproperties-gen]]
=== Allgemeine Propertys

der Linux Netboot Produkte mit generic Installer

Die folgenden Propertys finden Sie zur Steuerung der Linuxinstallation in allen Netbootprodukten:

* `askbeforeinst`: +
Soll das Starten der Installation am Client bestätigt werden müssen?  (Default='true')

* `architecture`: +
Mit welcher Architektur soll das Zielsystem installiert werden? +
Beeinflusst die Auswahl des bootimages und die Installationsarchitektur.  (Default='64bit')

* `system_partition_size`: +
Größe der Systempartition. Die Größe kann in Prozent der Festplattengröße oder als absoluter Wert (G=Gigabyte) angegeben werden. Wenn Sie einen kleineren Wert als 100% angeben, wird der verbleibende Rest als Datenpartition verwendet (wenn das Property data_partion_create = true).  (Default='100%')

* `swap_partition_size`: +
Größe der Swappartition.  (Default='2000M')

* `data_partition_create`: +
Verwende freien Plattenplatz zur Erstellung einer Datenpartition. (true/false).  (Default='true')

* `data_partition_preserve`: +
Soll eine existierende Datenpartition erhalten werden ? +
*always* = Installation abbrechen wenn der Erhalt einer gefundenen Partition mit dem Label 'data' mit den angegebenen Partitionierungsdaten nicht möglich ist. +
*if_possible* = Wird eine Partition mit dem Label 'data' gefunden und der Erhalt dieser Partition ist gemäß der angegebenen Partionierungsdaten nicht möglich, so wird die Partition gelöscht. +
*never* = Die gesamte Partitionstabelle wird immer neu geschrieben.  (Default='never')

* `language`: +
Welche Sprache / locale soll installiert werden.  (Default='de')

* `console_keymap`: +
Zu installierendes Tastaturlayout.  (Default=Distributionsabhängig / 'de')

* `timezone`: +
Welche Zeitzone soll verwendet werden?. (Default='Europe/Berlin')

* `root_password`: +
Passwort für root.  (Default='linux123')

* `user_password`: +
Passwort für user.  (Default='linux123')

* `online_repository`: +
Repository der Distribution für die Installation. (Nicht bei SLES) (Default=Distributionsabhängig)

* `proxy`: +
Proxystring (wenn benötigt) in der Form: 'http://<ip>:<port>'. (Default=pass:[''])

* `additional_packages`: +
Welche zusätzlichen Pakete sollen installiert werden? Angabe der Pakete Leerzeichen separiert. (Default=pass:[''])

* `wget_and_execute`: +
Url (http) einer Datei welche am Ende der Installation geholt und ausgeführt wird. (Default=pass:[''])

* `install_opsi-client-agent`: +
Installiere den Linux opsi-client-agent (Kofinanzierungsprojekt: Sie benötigen eine Aktivierung durch die /etc/opsi/modules) . (Default='false')

* `release`: +
(nur Debian und Ubuntu) +
Welches Release der Distribution soll installiert werden. (Default=Distributionsabhängig)

* `setup_after_install`: +
Welche opsi Produkte sollen zum Abschluss der Betriebssysteminstallation auf setup gestellt werden. (Default='l-os-postinst')


[[firststeps-osinstall-netboot-special-ubuntu]]
=== Ubuntu

Die Basis Installation erfolgt per debootstrap direkt aus dem Netz.

Das Produkt hat produktiven Status.

Das Produkt ist UEFI/GPT kompatibel.

Es gibt für diese Produkt passende opsi-server Pakete, welche über 'install_opsi_server=true' installiert werden können.

[[firststeps-osinstall-netboot-special-debian]]
=== Debian

Die Basis Installation erfolgt per debootstrap direkt aus dem Netz.

Das Produkt hat produktiven Status.

Das Produkt ist UEFI/GPT kompatibel.

Es gibt für diese Produkt passende opsi-server Pakete, welche über 'install_opsi_server=true' installiert werden können.

[[firststeps-osinstall-linux-debproxy]]
=== Proxy für '.deb'-Pakete

//kein Mirror, der Proxy hat Caching-Funktion, Teilmenge des Repos gespiegelt
 einrichten und verwenden

Anleitungen zur Erstellung eines eigenen Proxy zum Zwischenspeichern von '.deb'-Paketen finden Sie unter anderem hier:

* link:http://wiki.ubuntuusers.de/Lokale_Paketquellen/Apt-Cacher-ng[Ubuntusers Wiki: Apt-Cacher-NG]

* link:http://www.gambaru.de/blog/2011/10/26/apt-cacher-ng-ein-proxy-server-fur-debian-und-ubuntu/[Gambaru.de: Apt-Cacher-NG: Ein Proxy-Server für Debian und Ubuntu]


////
[[firststeps-osinstall-linux-netboot-clients]]
=== Linux Installation: Clients

Nachfolgend wird beschrieben, wie ein bisher nicht mit einem Betriebssystem ausgestatter Computer per opsi mit einem Linux-Betriebssystem ausgestattet wird.

Als Client-PC eignen sich reale oder virtuelle Rechner mit mindestens 2048 MB RAM, die über eine Netzwerkkarte mit Netzboot-Unterstützung verfügen:
D.h., sie unterstützen das PXE-Protokoll zum Laden von Boot-Systemen via Netzwerk.
Der Netzboot ist ggf. im BIOS-Menü zu aktivieren bzw. an die erste Stelle der Bootoptionen zu rücken.

Für die nachfolgenden Kapitel sollten Sie einen entsprechenden Client in opsi xref:adding-clients#firststeps-osinstall-create-client[aufgenommen haben].
Einfach geht dies xref:opsiconfiged#firststeps-osinstall-create-client[mittels opsi-configed].

////

