[[firststeps-software-deployment-client-integration]]
== Vorhandene Clients integrieren

Um vorhandene Clients mit bereits installiertem Betriebssystem in opsi aufzunehmen, installieren Sie auf dem jeweiligen Rechner den Client-Agent. Danach erscheint der Client auch in der Client-Liste der Management-Oberfläche, sofern Sie ihn dort noch nicht hinzugefügt hatten.

Grundsätzlich gibt es zwei verschiedene Möglichkeiten, den Client-Agent zu installieren:

* <<firststeps-software-deployment-client-integration-installer>> (Installation auf dem Client, eignet sich für einzelne Rechner)
* <<firststeps-software-deployment-client-integration-opsi-deploy>> (Installation auf Server anstoßen, Massen-Rollout)

TIP: Nachdem der Client-Agent installiert ist, können Sie opsi-Produkte auf dem Client einspielen (siehe Kapitel xref:clients:windows-client/rollout-products.adoc[Rollout existierender Produkte]).


[[firststeps-software-deployment-client-integration-installer]]
=== Installer auf dem Client verwenden

Diese Variante eignet sich besonders für einzelne Rechner, die Sie als Client in eine opsi-Umgebung integrieren möchten. So gehen Sie vor:

. Loggen Sie sich auf dem Client ein.
. Laden Sie den Installer von Ihrem opsi-Config-Server herunter. Sie finden ihn unter https://<fqdn_oder_ip_des_configservers>:4447/public/opsi-client-agent/; das Windows-Programm heißt `opsi-client-agent-installer.exe`.
. Führen Sie den Installer aus; er entpackt sich in ein temporäres lokales Verzeichnis und startet den enthaltenen `oca-installation-helper`. Tragen Sie im Dialogfenster die Werte für die Client-ID, die opsi-Service-URL, den Benutzernamen und das Passwort ein. Soweit möglich, sind die Felder bereits ausgefüllt; passen Sie die Werte gegebenenfalls an Ihre Umgebung an:
* Die Client-ID entspricht in der Regel dem FQDN des Clients.
* Die opsi-Service-URL muss das Format https://<fqdn_oder_ip_des_configservers>:4447 haben.
* Bei einer Erstinstallation des Clients gehören Benutzername und Passwort zu einem Account, der Mitglied der Gruppe `{opsi-admin}`; bei einer erneuten Installation können Sie auch die Client-ID und den PC-Key verwenden.
. Der Installer nimmt per {opsi-webservice} Kontakt zum Server auf, um den Client beim Server zu registrieren. Anschließend ruft er das enthaltene {opsi-script} auf, um das `setup.opsiscript` des Client-Agents auszuführen.

Beim Aufruf des Installers können Parameter mitgegeben werden, welche eine Voll-Automatisierung des Vorgangs ermöglichen. Details dazu finden Sie im
ifeval::["{mode}" == "antora"]
xref:manual:client/opsi-client-agent.adoc#opsi-manual-clientagent-manual-installation[opsi-Handbuch]
endif::[]
ifeval::["{mode}"!= "antora"]
link:https://download.uib.de/4.2/documentation/html/opsi-manual-v4.2/opsi-manual-v4.2.html#opsi-manual-clientagent-subsequent-installation[opsi-Handbuch]
endif::[]
.

[[firststeps-software-deployment-client-integration-opsi-deploy]]
=== `opsi-deploy-client-agent` verwenden

Falls bereits eine andere Möglichkeit existiert Software zu verteilen, so bietet es sich an, den initialen Rollout über den opsi-client-agent-installer oder das {opsi-client-agent} MSI-Paket durchzuführen.

Das `opsi-deploy-client-agent` Programm verteilt den {opsi-client-agent} (bzw opsi-linux-client-agent oder opsi-mac-client-agent) direkt vom {opsi-server} auf die Clients.
Es ist hiermit einfach möglich eine große Menge an Clients vom Server aus in eine opsi-Umgebung zu integrieren.

Voraussetzungen für Windows-Clients:

* ein offener c$ share
* ein offener admin$ share
* ein administrativer account
* laufende Dienste RpcSs und RpcEptMapper (standardmäßig aktiv ab win8)
* Firewall, die "Datei-und-Druckerfreigabe" und "Windows-Verwaltungsinstrumentalisierung (WMI)" zulässt
* der Registry-Schlüssel HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\LocalAccountTokenFilterPolicy sollte den Wert 1 haben

Voraussetzungen für Linux- und MacOS-Clients:

* ssh-Zugang mit einem user, der "sudo" ausführen darf oder selbst root ist.

Das `opsi-deploy-client-agent` Programm findet sich unter `/var/lib/opsi/depot/opsi-client-agent` (analog opsi-linux-client-agent, opsi-mac-client-agent) +
Führen Sie das Programm mit 'root' Rechten aus oder als ein user, der Teil der Gruppe "opsifileadmins" ist.

Das Program erzeugt serverseitig den Client, kopiert die Installations-Dateien und Konfigurationsinformationen, wie bspw. den pckey, auf den Client
und startet dort die Installation über den oca-installation-helper (nicht-interaktiv).

Mit dem `opsi-deploy-client-agent` kann auch eine ganze Liste von Clients bearbeitet werden.
Dazu können entweder beliebig viele Clients als letzter Parameter übergeben werden oder mit der Option '-f' die Clients aus einer Datei eingelesen werden.
Bei der Verwendung einer Datei, muss in jeder Zeile ein Client stehen.

Das Program kann mit IP-Adressen, Hostnamen und FQDNs arbeiten. Es wird versuchen automatisch zu erkennen welche Art von Adresse übergeben wurde.

Mögliche Parameter können Sie mit dem Parameter `--help` in Erfahrung bringen:
[source,shell]
----
usage: opsi-deploy-client-agent [-h] [--version] [--verbose] [--debug-file DEBUG_FILE] [--username USERNAME]
                                [--password PASSWORD] [--use-fqdn | --use-hostname | --use-ip-address]
                                [--ignore-failed-ping]
                                [--reboot | --shutdown | --start-opsiclientd | --no-start-opsiclientd]
                                [--hosts-from-file HOST_FILE] [--skip-existing-clients] [--threads MAX_THREADS]
                                [--install-timeout INSTALL_TIMEOUT] [--depot DEPOT] [--group GROUP] [--smbclient | --mount]
                                [--keep-client-on-failure | --remove-client-on-failure]
                                [--failed-clients-file FAILED_CLIENTS_FILE]
                                [host [host ...]]

Deploy opsi client agent to the specified clients. The c$ and admin$ must be accessible on every client. Simple File Sharing
(Folder Options) should be disabled on the Windows machine.

positional arguments:
  host                  The hosts to deploy the {opsi-client-agent} to.

optional arguments:
  -h, --help            show this help message and exit
  --version, -V         show program's version number and exit
  --verbose, -v         increase verbosity (can be used multiple times)
  --debug-file DEBUG_FILE
                        Write debug output to given file.
  --username USERNAME, -u USERNAME
                        username for authentication (default: Administrator).Example for a domain account: -u
                        <DOMAIN>\\<username>
  --password PASSWORD, -p PASSWORD
                        password for authentication
  --use-fqdn, -c        Use FQDN to connect to client.
  --use-hostname        Use hostname to connect to client.
  --use-ip-address      Use IP address to connect to client.
  --ignore-failed-ping, -x
                        try installation even if ping fails
  --reboot, -r          reboot computer after installation
  --shutdown, -s        shutdown computer after installation
  --start-opsiclientd, -o
                        Start {opsiclientd} service after installation without performing Events (default).
  --no-start-opsiclientd
                        Do not start {opsiclientd} service after installation (deprecated).
  --hosts-from-file HOST_FILE, -f HOST_FILE
                        File containing addresses of hosts (one per line). If there is a space followed by text after the
                        address this will be used as client description for new clients.
  --skip-existing-clients, -S
                        skip known opsi clients
  --threads MAX_THREADS, -t MAX_THREADS
                        number of concurrent deployment threads
  --install-timeout INSTALL_TIMEOUT
                        timeout for single threads (default is unlimited)
  --depot DEPOT         Assign new clients to the given depot.
  --group GROUP         Assign fresh clients to an already existing group.
  --smbclient           Mount the client's C$-share via smbclient.
  --mount               Mount the client's C$-share via normal mount on the server for copying the files.This imitates the
                        behaviour of the 'old' script.
  --keep-client-on-failure
                        If the client was created in opsi through this script it will not be removed in case of failure.
                        (DEFAULT)
  --remove-client-on-failure
                        If the client was created in opsi through this script it will be removed in case of failure.
  --failed-clients-file FAILED_CLIENTS_FILE
                        filename to store list of failed clients in
----
