////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      04.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-winclient-softwintegration]]
= Eigene Software einbinden

Für die Installation von Software ist bei opsi der xref:clients:windows-client/windows-client-agent.adoc[Client-Agent] bzw. das Setup-Programm xref:opsi-script-manual:opsi-script-manual.adoc[*opsi-script*] zuständig. Wenn Sie also eigene Software paketieren, müssen Sie zu jedem Produkt auch ein `opsi-script`-Skript erstellen. Dieses packen Sie anschließend zusammen mit den Installationsdateien und den Metadaten zu einem opsi-Produkt, das Sie auf dem opsi-Server installieren (siehe Kapitel xref:clients:windows-client/minimal-products.adoc[Produkte auf opsi-Server bereitstellen]).

[[opsi-winclient-softwintegration-tutorial]]
== Tutorial: *opsi-script*-Skript erstellen

include::common:partial$softwintegration-tutorial-introduction.adoc[]

[[opsi-winclient-softwintegration-tutorial-general]]
=== Nicht-interaktive Software-Installation (Windows)

Grundsätzlich stehen Ihnen drei Methoden zur Verfügung, um ein Softwarepaket in die automatische Softwareverteilung für Windows-Betriebssysteme zu integrieren. Zusätzlich gibt es eine Variante, die den Dienst link:https://learn.microsoft.com/de-de/windows/win32/msi/windows-installer-portal[Windows Installer] verwendet:

* *Unattended*/*Silent Setup*: +
Bei dieser Methode verwenden Sie das Original-Setup-Programm und versetzen es mit Kommandozeilen-Parametern in einen nicht-interaktiven Modus. Der wichtigste Spezialfall ist der „stille“ Aufruf eines MSI-Paketes, das Sie mit der `/quiet`-Option des Tools https://learn.microsoft.com/de-de/windows-server/administration/windows-commands/msiexec[*msiexec*] installieren.

* *Interaktives Setup mit automatisierten Antworten*: +
Zur Vorbereitung führen Sie das ursprüngliche Setup-Programm einmal aus und notieren dabei, welche Fenstertitel es anzeigt und welche Fragen und Antworten während des Setups auftreten. Diese Informationen halten Sie in einem Skript fest. Im Softwareverteilungs-Prozess steuert ein Automatisierungs-Programm wie z.{nbsp}B. link:https://www.autoitscript.com/site/[AutoIt] oder link:https://www.autohotkey.com/[AutoHotkey] das Setup-Programm nach den Vorgaben des Skriptes.

* *Setup-Routine mit `opsi-script` nachbilden*: +
Während das Original-Setup-Programm läuft, protokolliert ein Tool wie link:https://learn.microsoft.com/de-de/sysinternals/downloads/procmon[Prozessmonitor/Procmon] sämtliche Systemänderungen. Basierend auf diesen Daten und den erfassten Änderungen erstellen Sie das `opsi-script`-Skript.

NOTE: opsi unterstützt alle drei Varianten. In der Praxis kommt häufig eine Kombination aus mehreren Methoden zum Einsatz.

include::common:partial$softwintegration-tutorial-script-structure-opsi-script-basics.adoc[]

[[opsi-winclient-softwintegration-tutorial-Windows-special-commands]]
===== Spezielle Windows-Kommandos

* `GetOS`: Gibt das Betriebssystem aus, z.{nbsp}B. `Linux`, `Windows_NT` (Windows NT bis Windows 11) oder `macOS`.

* `GetMsVersionInfo`: Gibt auf Windows-Systemen Informationen über die interne Version aus; z.{nbsp}B. produziert ein Windows 7 das Ergebnis "6.1", Windows 11 liefert "10.0" usw.

* `GetMsVersionName`: Gibt die Marketing-Version für ein Windows-System aus, z.{nbsp}B. produziert ein Windows 7 das Ergebnis "7.0", Windows 11 liefert "11.0" usw.

* `getMSVersionMap`: Fragt die Betriebssystem-Informationen lokal ab und schreibt die Informationen in eine String-Liste.

TIP: Weiterführende Informationen zu diesen String-Funktionen lesen Sie im Abschnitt xref:opsi-script-manual:prim-section.adoc#opsi-script-string-functions-os[String-Funktionen (Betriebssystem ermitteln)].

[[opsi-winclient-softwintegration-tutorial-template]]
== Beispiel: Windows-Template *opsi-template*

Dieses Template können Sie mit dem `opsi-setup-detector` erstellen (siehe Abschnitt <<opsi-winclient-softwintegration-tutorial-create-with-opsi-setup-detector>>).

include::{version}@opsi-docs-en:common:partial$firststeps-opsi-template-win.adoc[]

[[opsi-client-softwintegration-create-opsi-package]]
== opsi-Produkte erstellen

Die nächsten Abschnitte erklären, wie Sie Software paketieren, also opsi-Produkte erstellen. Der grundlegende Ablauf sieht so aus:

1. Den "Rohbau" eines Paketes erstellen Sie mit dem `opsi-setup-detector` (siehe Abschnitt <<opsi-winclient-softwintegration-tutorial-create-with-opsi-setup-detector>>).
2. Danach testen Sie das `opsi-script`-Skript (siehe Abschnitt <<opsi-softwintegration-tutorial-create-and-test-script>>).
3. Mit dem opsi PackageBuilder (oPB) erstellen Sie aus der Rohform ein opsi-Paket und hinterlegen es auf dem opsi-Server.

// include docu: opsi-setup-detector installation
include::common:partial$setup-detector-installation.adoc[]

// include docu: opsi-logviewer installation
include::common:partial$opsi-logviewer-installation.adoc[]

[[opsi-winclient-softwintegration-tutorial-create-with-opsi-setup-detector]]
== *opsi-setup-detector*: Skript erstellen

Die folgenden Abschnitte erklären detailliert, wie Sie mit dem `opsi-setup-detector` ein opsi-Produkt eine Setup-Datei analysieren und ein opsi-Produkt erstellen. 

// include docu: opsi-setup-detector
include::common:partial$setup-detector-use-start.adoc[]

// include docu: Windows specific tasks in opsi-setup-detector
include::common:partial$osd-tasks-windows.adoc[]

// include docu: how to use the opsi-setup-detector
include::common:partial$osd-task-use-single-analyze-and-create.adoc[]

// include docu: The modify and test cycle
include::common:partial$softwintegration-tutorial-modify-test-cycle.adoc[]


[[opsi-winclient-softwintegration-tutorial-template-details]]
== Paketierung: Hinweise zu Teilaufgaben

Die folgenden Abschnitte zeigen weitere Konfigurationsmöglichkeiten des `opsi-setup-detector`. Sie behandeln die Verwendung eines benutzerdefinierten Verzeichnisses, die Installation aus einem lokalen temporären Verzeichnis, die Verwaltung von Lizenzschlüsseln und die Anpassung von Benutzerprofilen und Desktopsymbolen.

// include docu: OSD Checkboxes for additional code
include::common:partial$osd-checkboxes-subtasks.adoc[]

[[opsi-winclient-softwintegration-tutorial-opsiadmin]]
== Installation mit angemeldetem Benutzer

Vereinzelt taucht das Problem auf, dass sich Installationen nur bei angemeldetem Benutzer durchführen lassen. Ein möglicher Hinweis auf dieses Problem ist, dass der manuelle Aufruf eines `opsi-script`-Skriptes mit Anweisungen zu einem Unattended- oder Silent-Setup funktioniert, im Rahmen der automatischen Installation über opsi jedoch scheitert.

Eine mögliche Ursache kann sein, dass dieses Setup-Programm einen angemeldeten Benutzer bzw. den Zugriff auf ein Benutzer-Profil benötigt.

In einem solchen Fall können Sie Ihre Installation in ein opsi-Rahmenpaket einbinden, das diese benötigten Voraussetzungen schafft. Sie erstellen ein solches Paket beispielsweise im `opsi-setup-detector` über die Windows-Aufgabe _Analysiere Datei und erzeuge ein Paket 'with user'_.

[[opsi-winclient-softwintegration-tutorial-customizing]]
== Unattended-/Silent-Setup anpassen

Häufig will man nach einer erfolgreichen Silent-Installation Anpassungen an der Installation vornehmen, was mit `opsi-script` kein Problem ist. Vorher müssen Sie allerdings ermitteln, welche der in der grafischen Oberfläche gemachten Änderungen zu welchen Veränderungen in Dateien und in der Windows Registry führen.

Dazu benötigen Sie Werkzeuge wie beispielsweise diese hier:

* link:https://learn.microsoft.com/de-de/sysinternals/[Sysinternals]
* link:https://sourceforge.net/projects/regshot/[Regshot]

[[opsi-winclient-softwintegration-tutorial-autoit]]
== Automatische Einbindung mit Skript-Steuerung

Eine weitere schnelle Möglichkeit zur Einbindung in die automatische Softwareverteilung ist das _Setup mit automatisierten Antworten_. Dazu automatisiert eine Steuerungs-Software über ein Skript die Interaktion eines Anwenders mit den erscheinenden Dialog-Fenstern. 

Wir empfehlen dazu diese beiden Werkzeuge:

* link:https://autohotkey.com[AutoHotkey]
* link:http://www.autoitscript.com[AutoIt]

=== AutoIt: Setup-Prozess steuern

AutoIt bietet viele Möglichkeiten, um den Setup-Prozess zu steuern. Außerdem kann das Programm eventuelle Fehlerzustände (sofern vorher bekannt) mit `[ADLIB]`-Sektionen im Skript abfangen.

Ein grundsätzliches Problem bleibt aber bestehen: Nicht vorhergesehene (und im Skript berücksichtigte) Fenster können das Skript zum Stoppen bringen. Außerdem kann der Anwender mittels Maus und Tastatur (wenn diese nicht gesperrt sind) in den automatisierten Prozess eingreifen und den Ablauf damit verändern.  

TIP: Ein Unattended- oder Silent-Setup ist daher immer die bessere Lösung!

Eine Kombination aus beiden Ansätzen funktioniert ebenfalls gut. Das Silent-Setup übernimmt die eigentliche Installation, und ein AutoIt-Skript fängt bekannte Sonderbedingungen ab.

=== AutoIt: Bekannte Probleme

Wenn Sie in der Client-Agent-Konfiguration das Ausführen von Installationen auf einen anderen Desktop verlegen oder der Desktop gesperrt wird, haben verschiedene AutoIt-Funktionen Probleme.

NOTE: Meiden Sie nach Möglichkeit in `opsi-script`-Skripten die folgenden Funktionen:

* `winwait()`

* `winactivate()`

* `Send()`

Leider sind das die drei am meisten verwendeten Funktionen. Wir empfehlen daher, die Befehle durch die mit `opsi-script` ausgelieferten Bibliothek `C:\Program Files (x86)\opsi.org\opsi-client-agent\opsi-script\lib\opsi-autoit-lib.au3` zu ersetzen. Sie bietet neben den hier vorgestellten erweiterten Funktionen auch noch eine Logfunktion. Sie können die Datei `opsi-autoit-lib.au3` ins Produktverzeichnis kopieren und dann über die folgende Anweisung in den AutoIt-Code einbinden:

[source]
----
#include "%scriptpath%\opsi-autoit-lib.au3
----

Anschließend können Sie folgende Ersetzungen vornehmen:

* `winwait()` können Sie durch die Funktion `opsiwinwait($title, $text, $maxseconds, $logname)` ersetzen.
* `Send()` können Sie durch die Funktion `opsiControlClick($title, $text, $id, $maxseconds, $logname)` bzw. durch `opsiControlSetText($title, $text, $id,$sendtext, $maxseconds, $logname)`.

TIP: Es empfiehlt sich, die ControlID mit `Au3info.exe` zu ermitteln. Verwenden Sie unbedingt die numerische ControlID, da andere Varianten anscheinend Probleme machen.

=== AutoIT: Beispiele und weiterführende Links

* Beispiele: +
`C:\Program Files (x86)\opsi.org\opsi-client-agent\opsi-script\lib\` in den Dateien
  - `autoit_example_1.txt`
  - `autoit_example_1.txt`

* http://www.autoitscript.com/wiki/FAQ#Why_doesn.27t_my_script_work_on_a_locked_workstation.3F
* http://www.autoitscript.com/autoit3/docs/
* http://www.autoitscript.com/autoit3/docs/intro/controls.htm
* http://www.autoitscript.com/autoit3/docs/functions.htm

[[opsi-winclient-softwintegration-tutorial-analyse-and-repackage]]
== Analyse und Neu-Paketieren

Ein Entwickler, der ein Anwendungspaket erstellt, weiß, welche Teile benötigt werden. Wenn bereits ein Installationspaket vorhanden ist, kann man durch das Ausführen des Setup-Programms herausfinden, welche Teile für die gewünschte Funktionalität auf einem Arbeitsplatzrechner installiert werden müssen.

Es gibt eine Reihe von Werkzeugen zur Analyse von Setup-Programmen, z.{nbsp}B.:

* link:https://sourceforge.net/projects/regshot/files/regshot/[Regshot]
* link:https://www.itninja.com/community/appdeploy-repackager[AppDeploy Repackager]

== Produkte deinstallieren

Um Software von einem Computer zu entfernen, erstellt man oft ein Deinstallations-Skript. Das Problem dabei ist, dass nicht immer klar ist, wie die Software installiert wurde und was entfernt werden muss. Man darf auch nicht zu viel entfernen, um das System nicht zu beschädigen. Normalerweise weiß nur der Hersteller genau, wie mit seinem Produkt bei der Deinstallation umzugehen ist.

Oft gibt es Deinstallations-Routinen, die dem Produkt beiliegen und automatisch arbeiten. Gibt es die Möglichkeit, diese ohne Benutzer-Interaktion auszuführen, ist das der bevorzugte Weg. Ist eine solche Routine nicht vorhanden, oder muss diese erweitert werden, können Sie `opsi-script` dazu nutzen. Hier geben wir einen Überblick über die Möglichkeiten.

=== Deinstallations-Routine verwenden

Liefert der Hersteller des Produktes ein Programm (oder ein MSI-Paket) zur Deinstallation, dann prüfen Sie zunächst, ob dieses ohne Benutzer-Interaktion läuft (Silent-Modus). Ist das nicht der Fall, können Sie ein AutoIt-Skript zu Hilfe nehmen und mit der Deinstallations-Routine verbinden. 

Der Aufruf der ausführbaren Datei kann im `opsi-script`-Skript in einer `[WinBatch]`-Sektion stehen:

[source,ini]
----
[WinBatch_start_ThunderbirdUninstall]
"%SystemRoot%\UninstallThunderbird.exe" /ma
----

NOTE: Auch wenn der Hersteller ein eigenes Programm zur Deinstallation ausliefert, sollten Sie sich nicht darauf verlassen, dass das Produkt danach korrekt beseitigt ist. Prüfen Sie zusätzlich auf einem Testsystem, ob es der Rechner nach der Deinstallation weiter stabil läuft und ob Dateien oder
Registry-Einträge zurückgeblieben sind.

[[opsi-winclient-softwintegration-tutorial-deinstall-msi]]
=== Deinstallation von MSI Producten


Falls das Produkt als MSI-Paket bereitgestellt und mittels `msiexec` installiert wurde, ist in der Regel auch eine Deinstallation mittels `msiexec` möglich. Dazu rufen Sie `msiexec.exe` mit dem Parameter `/x` auf und übergeben dahinter den Namen des MSI-Paketes oder dessen GUID.

NOTE: Diese ID ist eindeutig, produktspezifisch und auf allen Systemen gleich, auf denen das MSI-Paket installiert ist. Sie finden Sie in der Registry unter `HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall`.

Um die Benutzer-Interaktion zu deaktivieren, verwenden Sie zusätzlich den Parameter `/qb-!`:

[source,ini]
----
msiexec.exe /x some.msi /qb-! REBOOT=ReallySuppress
----

So sieht die Deinstallation unter Angabe einer GUID aus:

[source,ini]
----
msiexec.exe /x {003C5074-EB37-4A75-AC4B-F5394E08B4DD} /qb-!
----

Die GUID kann sich bei demselben Produkt von Version zu Version ändern. Um vorhandene und eventuell ältere Installationen zu löschen, müssen Sie also ermitteln, welche GUID diese Installationen haben. Eine Möglichkeit ist über den `MsiName` des Paketes, den der `opsi-setup-detector` aus der MSI-Datei ermittelt. 

Der `MsiName` taucht im `Uninstall`-Eintrag der Registry als `DisplayName` auf. So können Sie also den `MsiName` verwenden, um die passenden `GUID` zu finden. Schneiden Sie dazu Informationen zur Architektur und Version vom Ende des `MsiName` ab und verpacken das Ganze in reguläre Ausdrücke:

[source,ini]
----
; Finding the MsiId by the Displayname from Registry:
; Be sure that the Displayname is set correctly:
Set $DisplayName$ = 'short msi name'
; escape all regex relevant chars with '\' : '\^$.|?*+()[{'
set $DisplayNameRegex$ = escapeRegexMetaChars($DisplayName$)
; '(?i)' = case insensitive ; '.*' = 0 or more of any thing
set $DisplayNameRegex$ = '(?i)'+$DisplayNameRegex$+'.*'
Set $UninstallList$ = getGuidListByDisplaynameRegex($DisplayNameRegex$)
;-----------------------------------------------------

; ---------------------------------------------------------------
comment "run the uninstallation "
; ----------------------------------------------------------------

if count($UninstallList$) int> "0"
	Comment "Uninstalling all found versions"
	for %uninstallEntry% in $UninstallList$ do Sub_Uninstallation_msi
endif

[Sub_Uninstallation_msi]
set $MsiVersion$ = TakeString(0, splitstring('%uninstallEntry%', "="))
set $MsiId$ = TakeString(1, splitstring('%uninstallEntry%', "="))

if stringtobool(checkForMsiProduct($MsiId$))
	Message "Uninstalling :"  + $ProductId$ + " " + $MsiVersion$+ "..."
	Winbatch_Uninstall_1
	Set $ExitCode$ = getlastexitcode
	if stringtobool(isMsiExitcodeFatal($ExitCode$, "true", $ErrorString$ ))
		LogError $ErrorString$
		isfatalerror $ErrorString$
	else
		Comment $ErrorString$
	endif
else
	Comment "No previously installed " + $ProductId$ + " version found"
endif
----

In diesem Skript-Teil passiert Folgendea:

* `Set $DisplayName$ = 'short msi name'`: Setzt die Variable `$DisplayName$` auf den `MsiName`, kürzt nicht benötigte anhängende Informationen. 

* `set $DisplayNameRegex$ = escapeRegexMetaChars($DisplayName$)`: Präpariert den `$DisplayName$` als Suche mit regulären Ausdrücken, versteckt (maskiert) alle Sonderzeichen.

* `set $DisplayNameRegex$ = '(?i)'+$DisplayNameRegex$+'.*'`: Bestimmt, dass der zu suchende String am Anfang der Zeile steht und keines oder beliebige Zeichen folgen dürfen.

* `Set $UninstallList$ = getGuidListByDisplaynameRegex($DisplayNameRegex$)`: Sucht in der Registry; die Funktion `getGuidListByDisplaynameRegex` ist Bestandteil der Bibliothek `osd-lib.opsiscript` und erzeugt eine Liste von als passend gefundenen Einträgen in der Form `<MsiVersion> = <msi GUID>`.

* `[Sub_Uninstallation_msi]`: Die Sektion verwendet die gefundenen GUID zur Deinstallation.

Sollten diese Methoden nicht oder nicht vollständig funktionieren, helfen Sie mit einem `opsi-script`-Skript nach, wie es der nächste Abschnitt beschreibt.

=== *opsi-script* Nützliche Befehle zur Deinstallation

Haben Sie ein Produkt mit den `opsi-script`-Funktionen installiert oder fehlt die Deinstallations-Routine des Herstellers, schreiben Sie ein eigenes Skript zur Deinstallation.

`opsi-script` bietet einige Funktionen, um Programmierer bei der Deinstallation zu unterstützen. Hier erhalten Sie einen kurzen Überblick, während eine ausführliche Beschreibung der Befehle und ihrer Parameter im xref:opsi-script-manual:opsi-script-manual.adoc[*opsi-script*-Handbuch] verfügbar ist. 

Der einfachste Fall ist das Löschen einer oder mehrerer Dateien in einer `Files`-Sektion mit diesem Befehl:

[source,ini]
----
delete -f Dateiname
----

Um ein Verzeichnis mit Unterverzeichnissen zu löschen, verwenden Sie dieses Kommando:

[source,ini]
----
delete -sf Verzeichnisname\
----

Der Parameter `f` steht dabei für „force“, um die Datei wirklich zu löschen, auch wenn diese schreibgeschützt ist. Der Parameter `s` schließt Unterverzeichnisse mit ein und arbeitet rekursiv.

Um eine Datei oder ein Verzeichnis aus allen Benutzer-Profilen zu löschen, verwenden Sie den Parameter `/AllNTUserProfiles`.

Wenn Sie einen Verzeichnisbaum löschen möchten, in dem sich Dateien mit dem Attribut „versteckt“ oder „Systemdatei“ befinden, gehen Sie einen Umweg über den Befehl `rmdir`. Diesen können Sie über eine `ShellScript`-Sektion aufrufen:

[source,ini]
----
[ShellScript_deleteDir]
rmdir /S /Q "<Verzeichnis>"
----

Manchmal muss vor dem Löschen ein laufender Prozess beendet werden. In dem Fall finden Sie den Namen heraus (etwa über den Task-Manager) und übergeben diesen an den `opsi-script`-Befehl `KillTask`:

[source,ini]
----
KillTask "thunderbird.exe"
----

Sollte das Produkt (oder Teile davon) als Service laufen, dann müssen Sie diesen Dienst vor der Deinstallation beenden. Dazu schalten Sie den Service in der Registry auf “inaktiv“ und starten den Rechner neu, oder Sie rufen den System-Befehl `net` mit dem Parameter `stop` auf. Er stoppt den Dienst sofort und löscht anschließend (ohne Neustart) die dazugehörigen Dateien:

[source,ini]
----
net stop <servicename>
----

CAUTION: Besondere Vorsicht ist beim Löschen von `.dll`-Dateien geboten, die noch von anderen Produkten verwendet werden könnten. Sie müssen diese individuell behandeln, daher können wir hier keinen allgemeingültigen Rat geben.

Um mit `opsi-script` einzelne Einträge aus der Registry zu löschen, verwenden Sie den Befehl `DeleteVar`. Er stehe innerhalb einer `Registry`-Sektion eines `opsi-script`-Skriptes und löscht Einträge aus dem momentan geöffneten Key: 

[source,ini]
----
DeleteVar <VarName>
----

Einen Registry-Key mitsamt seiner Unterschlüssel und Registry-Variablen löschen Sie mit `DeleteKey`:

[source,ini]
----
DeleteKey [HKLM\Software\Macromedia]
----

[[opsi-winclient-softwintegration-tutorial-64bit]]
== 64-Bit-Unterstützung

`opsi-script` ist ein 32-Bit-Programm. Skripte zur Installation von 32-Bit-Programmen funktionieren in der Regel auch auf 64-Bit-Systemen korrekt. Für die Installation von 64-Bit-Software mit `opsi-script` und generell für das Arbeiten auf 64-Bit-Systemen beachten Sie das Kapitel xref:opsi-script-manual:64bit.adoc[64-Bit-Unterstützung unter Windows].
