////
; Copyright (c) uib GmbH (uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      05.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



[[opsi-client-more-info]]
= Weitere Informationen

// cspell: ignore mode, antora, ifeval

Unser Handbuch enthält eine Fülle von Informationen, die für den produktiven Betrieb wichtig sind. Wir empfehlen besonders, sich mit den Kapiteln im Teil xref:server:overview.adoc[OPSI-Server] vertraut zu machen und eine gute Backup-Strategie für Ihre Umgebung zu entwickeln (siehe Kapitel xref:server:components/backup.adoc[Backup des OPSI-Servers]).

Besuchen Sie auch unser link:https://forum.opsi.org/[OPSI-Forum] und tauschen sich mit anderen Mitgliedern der Community aus. Hier finden Sie auch wichtige Ankündigungen und News.

TIP: Für Produktivumgebungen empfehlen wir professionelle Unterstützung durch die Firma uib im Rahmen eines link:https://opsi.org/de/services/support/[Pflege- und Supportvertrages].
