////
; Copyright (c) uib GmbH (uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      30.09.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



Unter Windows stehen folgende Funktionen zur Verfügung:

* _Analysiere Datei und erzeuge ein OPSI Paket_: Ausgehend von einer Setup-Datei wird hier der gesamte Prozess durchlaufen bis zum Erzeugen eines opsi-Paketes (siehe Abschnitt xref:clients:windows-client/softwareintegration.adoc#opsi-setup-detector-use-single-analyze-and-create[Datei analysieren und Paket erzeugen]).

* _Analysiere 2 Dateien (32 / 64 Bit) und erzeuge ein O. Paket_: Verläuft ähnlich, allerdings werden hier zwei Setup-Programme für die beiden Architekturen (32{nbsp}Bit und 64{nbsp}Bit) abgefragt und analysiert. Das Produkt bekommt ein zusätzliches Property: `install_architecture` (mögliche Werte: `32bitonly`, `64bitonly`, `both` und `systemspecific`).

* _Eine OPSI Paketvorlage (Template) erzeugen_: Fragt nicht nach einer Setup-Datei, sondern erstellt ein opsi-Template-Produkt für Windows und übernimmt dazu die Angaben aus der Produkt-Konfiguration.

* _Analysiere Datei und erzeuge ein Paket 'with user'_: Ähnlich wie _Analysiere Datei und erzeuge ein OPSI Paket_, erstellt das Paket für eine Installation bei angemeldetem Benutzer (siehe Abschnitt xref:opsi-script-manual:cook-book.adoc#_opsi_template_with_userlogin[opsi_template_with_userlogin]). Das Produkt bekommt zusätzliche Properties: +
  - `execution_method`, mögliche Werte: `loginOpsiSetupUser`, `runAsOpsiSetupUser` und `runOpsiScriptAsOpsiSetupUser`
  - boolesche Properties: `uninstall_before_install`, `copy_files_locally` und `debug`

* _Erzeuge ein OPSI Paket Template 'with user'_: Fragt nicht nach einer Setup-Datei, sondern erstellt ein opsi-Template-Produkt für eine Installation bei angemeldetem Benutzer und übernimmt dazu die Angaben aus der Produkt-Konfiguration.

* _Erzeuge ein OPSI winget Paket_: Fragt nicht nach einer Setup-Datei, sondern springt zur 'winget' Maske. Dort müssen die `wingetId` und die `wingetSource` eingetragen werden. +
(siehe Abschnitt xref:clients:windows-client/softwareintegration.adoc#opsi-setup-detector-create-winget[Erzeuge ein OPSI winget Paket]).

* _Erzeuge Background Info Datei_: +
(Nur Sichtbar, wenn in der Konfiguration `EnableBackgroundMetaData=true` gesetzt ist). +
Dient dazu um zu einem bestehenden Produkt die Metadaten für die Backgroundinstallation hinzuzufügen.
(siehe Abschnitt xref:opsi-modules:background-install.adoc#opsi-manual-background-install-old-products[Altprodukte mit Background Metadaten versorgen]).