////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      30.09.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

Unter Windows stehen folgende Funktionen zur Verfügung:

* _Analysiere Datei und erzeuge ein opsi Paket_: Ausgehend von einer Setup-Datei wird hier der gesamte Prozess durchlaufen bis zum Erzeugen eines opsi-Paketes (siehe Abschnitt xref:clients:windows-client/softwareintegration.adoc#opsi-setup-detector-use-single-analyze-and-create[]).

* _Analysiere 2 Dateien (32 / 64 Bit) und erzeuge ein O. Paket_: Verläuft ähnlich, allerdings werden hier zwei Setup-Programme für die beiden Architekturen (32{nbsp}Bit und 64{nbsp}Bit) abgefragt und analysiert. Das Produkt bekommt ein zusätzliches Property: `install_architecture` (mögliche Werte: `32bitonly`, `64bitonly`, `both` und `systemspecific`).

* _Eine opsi Paketvorlage (Template) erzeugen_: Fragt nicht nach einer Setup-Datei, sondern erstellt ein opsi-Template-Produkt für Windows und übernimmt dazu die Angaben aus der Produkt-Konfiguration.

* _Analysiere Datei und erzeuge ein Paket 'with user'_: Ähnlich wie _Analysiere Datei und erzeuge ein opsi Paket_, erstellt das Paket für eine Installation bei angemeldetem Benutzer (siehe Abschnitt xref:opsi-script-manual:cook-book.adoc#_opsi_template_with_userlogin[opsi_template_with_userlogin]). Das Produkt bekommt zusätzliche Propertys: +
  - `execution_method`, mögliche Werte: `loginOpsiSetupUser`, `runAsOpsiSetupUser` und `runOpsiScriptAsOpsiSetupUser`
  - boolesche Propertys: `uninstall_before_install`, `copy_files_locally` und `debug`

* _Eine Datei nur analysieren_: Verläuft ähnlich wie _Analysiere Datei und erzeuge ein opsi Paket_, allerdings wird nach der Analyse der Vorgang unterbrochen und kein Paket gebaut.
