[[opsi-setup-detector-tasks-os-independent]]

==== Die angebotenen Aufgaben für OS unabhängig:

. _Ein opsi Meta Produkt erzeugen_ +
Ein _Meta Produkt_ ist ein opsi Produkt, welches nichts installiert aber eine ganze Reihe von Abhängigkeiten enthalten kann. Wird bei einem solchen Produkt die Anforderung auf _setup_ gestellt, so werden die Abhängigkeiten aufgelöst. Daher kann ein _Meta Produkt_ verwendet werden um den Zielzustand einer Installation zu beschreiben. +
_Meta Produkte_ können auch geschachtelt werden, d.h. ein _Meta Produkt_ kann eine Abhängigkeit auf ein anderes haben. +
Der Ablauf ist analog dem für Windows im nächsten Kapitel beschrieben, nur das sie nach keiner Datei zum Analysieren gefragt werden. +
Alle Informationen welche eingegeben wurden werden bei der Produkterzeugung auch in die Datei `opsi-project.osd` im Basisverzeichnis des Produktes geschrieben. Diese Datei kann zu einem späteren Zeitpunkt wieder mit dem _opsi-setup-detector_ geöffnet werden um das Produkt zu modifizieren.
