////
; Copyright (c) uib GmbH (uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      10.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



Unter macOS stehen folgende Funktionen zur Verfügung:

* _Analysiere Datei und erzeuge ein OPSI Paket_: Ausgehend von einer macOS-Installer-Datei wird hier der gesamte Prozess durchlaufen bis zum Erzeugen eines OPSI-Paketes. Das funktioniert genauso, wie für Windows beschrieben (siehe Abschnitt xref:clients:windows-client/softwareintegration.adoc#opsi-setup-detector-use-single-analyze-and-create[]).

* _Eine OPSI Paketvorlage (Template) erzeugen_: Fragt nicht nach einer Setup-Datei, sondern erstellt ein OPSI-Template-Produkt für macOS und übernimmt dazu die Angaben aus der Produkt-Konfiguration.
