////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      05.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

Es gibt zwei Wege, wie Sie die opsi-Produkte einspielen können:

* <<automatic-package-installation>>
* <<manual-package-installation>>

TIP: Wir empfehlen die erste Variante und das automatische Einspielen der opsi-Produkte.

[[automatic-package-installation]]
== Produkte automatisch einspielen

// cspell: ignore updater
Zur automatischen Installation der opsi-Produkte verwenden Sie das Kommandozeilentool `opsi-package-updater` (siehe auch Abschnitt xref:server:components/commandline.adoc#server-components-opsi-package-updater[*opsi-package-updater*]), das automatisch die aktuellen Pakete aus dem opsi-Repository herunterlädt und auf dem Server installiert. 

So konfigurieren Sie das Tool:

* `/etc/opsi/opsi-package-updater.conf`: Konfigurationsdatei mit allgemeinen Einstellungen, z.{nbsp}B. Ort für die heruntergeladenen Pakete, Log-Datei, Loglevel, Timeout, Verzeichnis für die Repositorys usw.
* `/etc/opsi/package-updater.repos.d/`: Verzeichnis für die Repositorys; zum Aktivieren eines Repository setzen Sie in der jeweiligen `.repo`-Datei den Eintrag `active = true`.

Die `.repo`-Dateien definieren unter anderem die URL und Verzeichnisse der Paketquelle, optional Benutzername und Passwort zur Authentifzierung, automatisches Update und Installation usw.

NOTE: Wenn der Internetzugriff über einen Proxy erfolgt, tragen Sie diesen in den `.repo`-Konfigurationsdateien im Verzeichnis `/etc/opsi/package-updater.repos.d/` als Wert für `proxy` ein. Sie können einen globalen Proxy in der Datei `/etc/opsi/opsi-package-updater.conf` konfigurieren.

Um mit dem `opsi-package-updater` die Pakete aus dem Repository `uib-windows.repo` zu installieren, führen Sie als Benutzer `root` den folgenden Befehl aus:

[source,console]
----
opsi-package-updater -v --repo uib_windows install
----

Für Linux-Anwender heißt das Repository `uib-linux.repo` und für macOS-Anwender entsprechend `uib-mac.repo`.

TIP: Nach erfolgreicher Installation laden Sie alle Daten in der xref:gui:configed.adoc[Management-Oberfläche `opsi-configed`] neu, damit die neuen Produkte dort sichtbar werden.

Sie können das Tool auch dazu verwenden, um installierte Pakete zu aktualisieren:

[source,console]
----
opsi-package-updater -v update
----

CAUTION: Beachten Sie, dass Produkte zur Betriebssystem-Installation nach dem Einspielen nicht sofort einsatzbereit sind. Sie müssen noch durch die Installationsdateien des entsprechenden Installationsmediums ergänzt werden.

[[manual-package-installation]]
== Produkte von Hand einspielen

Alternativ laden Sie die Pakete von Hand herunter und installieren Sie mit dem Tool `opsi-package-manager` (siehe Abschnitt xref:server:components/commandline.adoc#server-components-opsi-package-manager[*opsi-package-manager*]). opsi-Pakete tragen die Dateiendung `.opsi`; Sie finden sie unter https://opsipackages.43.opsi.org/stable im Ordner des jeweiligen Betriebssystems. Wir empfehlen, die `.opsi`-Pakete im Verzeichnis `/var/lib/opsi/repository` zu speichern.

NOTE: Um sicherzustellen, dass der Dienst `opsiconfd` auf die Dateien zugreifen kann, führen Sie nach dem Download als Benutzer `root` das folgende Kommando aus: `opsi-set-rights /var/lib/opsi/repository`

Sie installieren ein Paket auf dem opsi-Server als `root` mit diesem Befehl:

[source,console]
----
opsi-package-manager -i <paket>.opsi
----
