////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      30.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[package-installation]]
== Minimale opsi-Produkte einspielen

Es gibt zwei Wege, wie Sie die opsi-Produkte einspielen können:

* <<automatic-package-installation>>
* <<manual-package-installation>>

TIP: Wir empfehlen die erste Variante und das automatische Einspielen der opsi-Produkte.

[[automatic-package-installation]]
=== opsi-Produkte automatisch einspielen

// cspell: ignore updater
Zur automatischen Installation der opsi-Produkte verwenden Sie das Werkzeug *opsi-package-updater*, das automatisch die aktuellen Pakete aus dem opsi-Repository herunterlädt und auf dem Server installiert. Den *opsi-package-updater* konfigurieren Sie über die folgenden Dateien:

* `/etc/opsi/opsi-package-updater.conf`: allgemeine Einstellungen, z.{nbsp}B. Ort für die heruntergeladenen Pakete, Log-Datei, Log-Level, Timeout, Verzeichnis für die Repositories usw.
* `/etc/opsi/package-updater.repos.d/`: Verzeichnis für die Repositories; zum Aktivieren eines Repository setzen Sie in der jeweiligen `.repo`-Datei den Eintrag `active = true` setzen.

Die `.repo`-Dateien enthalten Angaben zu URL und Verzeichnissen der Paketquelle, sowie weitere Einstellungen, die das Verhalten des *opsi-package-updater* in Bezug auf das spezifische Repository beeinflussen.

NOTE: Wenn der Internetzugriff über einen Proxy erfolgt, tragen Sie diesen in den `.repo`-Konfigurationsdateien im Verzeichnis `/etc/opsi/package-updater.repos.d/` als Wert für `proxy` ein. Sie können einen globalen Proxy in der Datei `/etc/opsi/opsi-package-updater.conf` konfigurieren.

Wenn Sie z.B. die Pakete aus dem Repository zu der Datei `uib_windows.repo` installieren wollen, führen Sie mit `root`-Rechten folgenden Befehl aus (Analog für die anderen Repositories):

[source,shell]
----
opsi-package-updater -v --repo uib_windows install
----

TIP: Nach erfolgreicher Installation laden Sie alle Daten in der xref:configed:configed.adoc[Management-Oberfläche `opsi-configed`] neu, damit die neuen Produkte dort sichtbar werden.

Sie können das Tool *opsi-package-updater* auch dazu verwenden, um installierte Pakete zu aktualisieren:

[source,shell]
----
opsi-package-updater -v update
----

Weitere Informationen zum *opsi-package-updater* finden Sie im Kapitel xref:server:components/opsi-package-updater.adoc[Das Tool `opsi-package-updater`].

WARNING: Beachten Sie, dass Produkte zur Betriebssystem-Installation nach dem Einspielen nicht sofort einsatzbereit sind. Sie müssen noch durch die Installationsdateien des entsprechenden Installationsmediums ergänzt werden.

[[manual-package-installation]]
=== opsi-Produkte von Hand einspielen

Es gibt auch die Möglichkeit manuell die Pakete herunter zu laden und zu installieren.

Holen Sie sich die aktuellen opsi-Pakete im `.opsi`-Paketformat.
Die Pakete finden Sie unter `https://opsipackages.43.opsi.org/stable` im Ordner des jeweiligen Betriebssystems.

Wir empfehlen die .opsi-Dateien unter `/var/lib/opsi/repository` zu speichern.

NOTE: Um sicherzustellen, dass der Dienst *opsiconfd* auf die Dateien zugreifen kann, führen Sie nach dem Download als Benutzer `root` das folgende Kommando aus: 
`opsi-set-rights /var/lib/opsi/repository`

Sie installieren ein Paket auf dem opsi-Server als `root` mit diesem Befehl:

[source,shell]
----
opsi-package-manager -i <paketname>.opsi
----
