////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      26.09.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

=== Vorbereitungen

Zum Erstellen von opsi-Paketen benötigen Sie die folgenden Werkzeuge:

* <<opsi-setup-detector-installation_opb,opsi PackageBuilder>>
* <<opsi-setup-detector-installation_osd,`opsi-setup-detector`>>
* xref:common:partial$opsi-logviewer-installation.adoc[`opsi-logviewer`]


[[opsi-setup-detector-installation_opb]]
=== opsi PackageBuilder installieren

Der link:https://github.com/pandel/opsiPackageBuilder[opsi PackageBuilder (oPB)] ...

Den _opsi PackageBuilder_ gibt es derzeit für Windows, Linux und MacOS.

Die Installations-Dateien / Pakete des _opsi PackageBuilder_ finden Sie hier: +
https://forum.opsi.org/viewtopic.php?p=32473#p32473 +
Dort findet sich im oberen Teil die Links auf die Installationspakete für Windows, Linux und MacOS. +
Der _opsi PackageBuilder_ kommt nicht von 'uib' sondern aus der opsi-community von Holger Pandel (Danke!). +

Der _opsi PackageBuilder_ unterliegt einer OpenSource Lizenz: +
https://github.com/pandel/opsiPackageBuilder/blob/master/LICENSE_DE

Der _opsi PackageBuilder_ hat eine eigene Dokumentation welche mit installiert wird.

Sie können den _opsi PackageBuilder_ auch per opsi installieren:

Das Paket _opsipackagebuilder_wlm_ gehört zu den opsi Standardprodukten und sollte auf Ihrem opsi-server installiert sein. Falls nicht, mit:

[source,shell]
----
opsi-package-updater install opsipackagebuilder_wlm
----

können Sie es auf dem opsi-server installieren.

[[opsi-setup-detector-installation_osd]]
=== *opsi-setup-detector* installieren

Den opsi-setup-detector gibt es derzeit für Windows, Linux und MacOS.

Sie können den opsi-setup-detector per opsi installieren:

Das Paket _opsi-setup-detector_ gehört zu den opsi Standardprodukten und sollte auf Ihrem opsi-server installiert sein. Falls nicht, mit:

[source,shell]
----
opsi-package-updater install opsi-setup-detector
----

können Sie es auf dem opsi-server installieren.

Ein Setup-Programm um den opsi-setup-detector auf Windows auch ohne opsi zu installieren, finden sie unter : +
https://download.uib.de/opsi4.2/misc/helper/

Die Basis Funktionalität des _opsi-setup-detector_ auf den unterschiedlichen Betriebssystemen ist gleich. Bei der Analyse einer Installationsdatei werden aber eventuell Hilfprogramme aufgerufen, welche nicht überall verfügbar bzw. lauffähig sind.

* Genauere Analyse von Inno-Setups verwendet innounpack.exe unter Windows.

* Genauere Analyse von wix-setups verwendet dark.exe unter Windows.

* `.deb` bzw. `.rpm` Dateien werden mit den entsprechenden Linux Werkzeugen analysiert.

Das opsi-Produkt _opsi-setup-detector_ hat eine Abhängigkeit zu dem opsi-Produkt _opsipackagebuilder_wlm_.
Der _opsi-setup-detector_ verwendet den _opsi PackageBuilder_ wenn vorhanden, funktioniert in weiten Teilen aber auch ohne.
Die Installation des _opsi PackageBuilder_ ist aber empfohlen.
