
[[opsi-setup-detector-installation_opb]]
=== Installation des opsi-package-builder

Den opsi-package-builder gibt es derzeit für Windows, Linux und MacOS.

Die Installations-Dateien / Pakete des _opsi-package-builder_ finden Sie hier: +
https://forum.opsi.org/viewtopic.php?p=32473#p32473 +
Dort findet sich im oberen Teil die Links auf die Installationspakete für Windows, Linux und MacOS. +
Der _opsi-package-builder_ kommt nicht von 'uib' sondern aus der opsi-community von Holger Pandel (Danke!). +

Der _opsi-package-builder_ unterliegt einer OpenSource Lizenz: +
https://github.com/pandel/opsiPackageBuilder/blob/master/LICENSE_DE

Der _opsi-package-builder_ hat eine eigene Dokumentation welche mit installiert wird.

Sie können den _opsi-package-builder_ auch per opsi installieren:

Das Paket _opsipackagebuilder_wlm_ gehört zu den opsi Standardprodukten und sollte auf Ihrem opsi-server installiert sein. Falls nicht, mit:

[source,prompt]
----
opsi-package-updater install opsipackagebuilder_wlm
----

können Sie es auf dem opsi-server installieren.

[[opsi-setup-detector-installation_osd]]
=== Installation des opsi-setup-detector

Den opsi-setup-detector gibt es derzeit für Windows, Linux und MacOS.

Sie können den opsi-setup-detector per opsi installieren:

Das Paket _opsi-setup-detector_ gehört zu den opsi Standardprodukten und sollte auf Ihrem opsi-server installiert sein. Falls nicht, mit:

[source,prompt]
----
opsi-package-updater install opsi-setup-detector
----

können Sie es auf dem opsi-server installieren.

Ein Setup-Programm um den opsi-setup-detector auf Windows auch ohne opsi zu installieren, finden sie unter : +
https://download.uib.de/opsi4.2/misc/helper/ 

Die Basis Funktionalität des _opsi-setup-detector_ auf den unterschiedlichen Betriebssystemen ist gleich. Bei der Analyse einer Installationsdatei werden aber eventuell Hilfprogramme aufgerufen, welche nicht überall verfügbar bzw. lauffähig sind.

* Genauere Analyse von Inno-Setups verwendet innounpack.exe unter Windows.

* Genauere Analyse von wix-setups verwendet dark.exe unter Windows.

* `.deb` bzw. `.rpm` Dateien werden mit den entsprechenden Linux Werkzeugen analysiert.

Das opsi-Produkt _opsi-setup-detector_ hat eine Abhängigkeit zu dem opsi-Produkt _opsi-package-builder_wlm_.
Der _opsi-setup-detector_ verwendet den _opsi-package-builder_ wenn vorhanden, funktioniert in weiten Teilen aber auch ohne.
Die Installation des _opsi-package-builder_ ist aber empfohlen.
