////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      29.09.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

=== Vorbereitungen

Zum Erstellen von opsi-Paketen benötigen Sie die folgenden Werkzeuge:

* <<opsi-setup-detector-installation_osd,`opsi-setup-detector`>>
* <<opsi-setup-detector-installation_opb,opsi PackageBuilder>>
* xref:modules/common/partials/opsi-logviewer-installation.adoc[`opsi-logviewer`]

[[opsi-setup-detector-installation_osd]]
=== *opsi-setup-detector* installieren

Den `opsi-setup-detector` gibt es derzeit für Windows, Linux und macOS. Sie können das Programm direkt über opsi installieren. Es gehört zu den Standard-Localboot-Produkten und sollte bereits auf dem opsi-Server vorhanden sein. Ist das nicht der Fall, stellen Sie es über den folgenden Befehl bereit:

[source,console]
----
opsi-package-updater install opsi-setup-detector
----

NOTE: Das Localboot-Produkt `opsi-setup-detector` erfordert ebenfalls die Installation des Produktes `opsipackagebuilder_wlm`, denn der Setup-Detector verwendet den PackageBuilder (sofern dieser vorhanden ist). 

Installieren Sie daher ebenfalls das Produkt `opsipackagebuilder_wlm`:

[source,console]
----
opsi-package-updater install opsipackagebuilder_wlm
----

Anschließend rollen Sie die beiden Produkte auf den gewünschten Clients aus, beispielsweise über die Management-Oberfläche `opsi-configed`.

TIP: Für Windows-Rechner bieten wir den Setup-Detector auch als eigenständiges Paket an, das Sie unabhängig von opsi installieren können: https://download.uib.de/opsi4.2/misc/helper/

==== Zusatzprogramme

Grundsätzlich funktioniert der `opsi-setup-detector` auf allen drei Betriebssystemen ähnlich. Zur Analyse einer Installationsdatei ruft das Programm aber unterschiedliche Hilfsprogramme auf:

* Genaue Analysen von Inno Setups unter Windows erfordern ein Tool wie `innounpack.exe`.

* Zur Arbeit mit dem Windows Installer XML (kurz WiX Toolset) ist ein Werkzeug wie Dark unter Windows erforderlich.

* `.deb`- bzw. `.rpm`-Pakete analysieren die entsprechenden Paketverwaltungstools unter Linux.

[[opsi-setup-detector-installation_opb]]
=== opsi PackageBuilder installieren

Der link:https://github.com/pandel/opsiPackageBuilder[opsi PackageBuilder (oPB)] ...

Den _opsi PackageBuilder_ gibt es derzeit für Windows, Linux und MacOS.

Die Installations-Dateien / Pakete des _opsi PackageBuilder_ finden Sie hier: +
https://forum.opsi.org/viewtopic.php?p=32473#p32473 +
Dort findet sich im oberen Teil die Links auf die Installationspakete für Windows, Linux und MacOS. +
Der _opsi PackageBuilder_ kommt nicht von 'uib' sondern aus der opsi-community von Holger Pandel (Danke!). +

Der _opsi PackageBuilder_ unterliegt einer OpenSource Lizenz: +
https://github.com/pandel/opsiPackageBuilder/blob/master/LICENSE_DE

Der _opsi PackageBuilder_ hat eine eigene Dokumentation welche mit installiert wird.

Sie können den _opsi PackageBuilder_ auch per opsi installieren:

Das Paket _opsipackagebuilder_wlm_ gehört zu den opsi Standardprodukten und sollte auf Ihrem opsi-server installiert sein. Falls nicht, mit:

[source,shell]
----
opsi-package-updater install opsipackagebuilder_wlm
----

können Sie es auf dem opsi-server installieren.

