
[[opsi-setup-detector-installation_opb]]
==== Installation des {opsi-package-builder}

Den {opsi-package-builder} gibt es derzeit für Windows, Linux und MacOS.

Die Installations-Dateien / Pakete des `{opsi-package-builder}` finden Sie hier: +
https://forum.opsi.org/viewtopic.php?p=32473#p32473 +
Dort findet sich im oberen Teil die Links auf die Installationspakete für Windows, Linux und MacOS. +
Der `{opsi-package-builder}` kommt nicht von 'uib' sondern aus der opsi-community von Holger Pandel (Danke!). +

Der `{opsi-package-builder}` unterliegt einer OpenSource Lizenz: +
https://github.com/pandel/opsiPackageBuilder/blob/master/LICENSE_DE

Der `{opsi-package-builder}` hat eine eigene Dokumentation welche mit installiert wird.

[[opsi-setup-detector-installation_osd]]
==== Installation des opsi-setup-detector

Den opsi-setup-detector gibt es derzeit für Windows und Linux.

Sie können den opsi-setup-detector per opsi installieren:

Das Paket `opsi-setup-detector` gehört zu den opsi Standardprodukten und sollte auf Ihrem opsi-server installiert sein. Falls nicht, mit:

[source,prompt]
----
opsi-package-updater install opsi-setup-detector
----

können Sie es auf dem opsi-server installieren.

Ein Setup-Programm um den opsi-setup-detector auf Windows auch ohne opsi zu installieren, finden sie unter : +
https://download.uib.de/opsi4.1/misc/helper/ 

Die Funktionalität der Linux-Version ist in folgen Features eingeschränkt,
da bestimmte Programm zur Analyse von Setup-Programmen aus bestimmten Frameworks nicht für Linux zur Verfügung stehen:

* Genauere Analyse von Inno-Setups mangels innounpack.exe für Linux

* Genauere Analyse von wix-setups mangels dark.exe für Linux

Das opsi-Produkt `opsi-setup-detector` hat eine Abhängigkeit zu dem opsi-Produkt `{opsi-package-builder}`.
Der `opsi-setup-detector` verwendet den `{opsi-package-builder}` wenn vorhanden, funktioniert in weiten Teilen aber auch ohne.
Die Installation des `{opsi-package-builder}` ist aber empfohlen.
