////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      22.09.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-softwintegration-tutorial-introduction]]
== Einführung

Dieses Tutorial kann eine Schulung oder das Studium der Handbücher nicht vollständig ersetzen. Es soll lediglich eine Einführung bieten. Daher verweisen wir zuerst auf weiterführende Quellen:

=== Schulungen

Die uib GmbH bietet opsi-Schulungen in Mainz, bei Ihnen vor Ort und online an: +
https://uib.de/de/support-schulung/schulung/

=== Handbücher

* Wir stellen mehrere Handbücher für unterschiedliche opsi-Versionen auf Deutsch und auf Englisch bereit: +
https://docs.opsi.org/

* Für dieses Tutorial empfehlen wir besonders das xref:opsi-script-manual:opsi-script-manual.adoc[`opsi-script`-Kapitel].

* Links zu unseren Handbüchern in verschiedenen Formaten, zu Release Notes und mehr finden Sie auch hier: +
https://uib.de/de/opsi-dokumentation/dokumentationen/ +

=== Wiki 

Unser opsi-Wiki finden Sie hier: +
https://wiki.opsi.org/

=== Support-Forum

Das opsi-Forum (Community-Support, Ankündigungen und News) finden Sie hier: +
https://forum.opsi.org
