////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      18.04.2023
:Revision:  4.2
:toclevels: 5
:icons: font
:xrefstyle: full
:doctype:   book

include::common:partial$opsi_terms.adoc[]

[[opsi-4.2-releasenotes]]
= Version 4.2

TIP: A list of currently supported Linux distributions for the opsi server as well as for the opsi client (Windows, Linux, and macOS) can be found in chapter xref:supportmatrix:supportmatrix.adoc[opsi Support Matrix].

[[opsi-4.2-releasenotes-overview]]
= New Features (Main Focus)

* Switch to Python 3
* All Python applications are distributed as executable binaries.
* opsi-python interpreter for your own scripts
* opsi server:
** Complete re-implementation of `opsiconfd` with focus on performance and scalability
** `opsiconfd` can now run in a Docker container.
** New dependency on Redis Server >= 5i, including the RedisTimeSeries module
** Grafana for visualization of performance data
** New default ACLs for API access

[[opsi-4.2-releasenotes-important]]
== Important Information

opsi 4.2 is an independent release and has its own repositories.
You have to add the new repositories to the system and remove the the repositories of the previous version.
Only after that you can install/upgrade opsi.

For an upgrade from opsi 4.1 the installed packages need to be the latest opsi 4.1 stable versions.
Other packages - such as MySQL server - should also be up-to-date.
Otherwise errors in the upgrade process may occur.

It is also strongly recommended to update the packages 'opsi-winst', 'opsi-client-agent' or 'opsi-linux-client-agent' on all clients to the latest opsi 4.1 versions before upgrading.

[[opsi-releasenotes-4.2-changes-python]]
=== Python 3

opsi 4.2 is completely based on Python 3. All Python applications in opsi (`opsiconfd`, `opsipxeconfd`, `opsiclientd`, `opsi-utils`, etc.) are now distributed as executable binaries with PyInstaller.
The `python-opsi` package is no longer available as an installable package.

Therefore, it is important to note the following things:

[[opsi-4.2-releasenotes-important-reinstall-opsi-packages]]
==== opsi Packages containing server-side Python Scripts

After upgrading the opsi server to opsi 4.2, use the `opsi-package-manager` tool to reinstall the opsi packages that contain Python scripts to run on the server:

* opsi client agent: `opsi-deploy-client-agent`.
* windows: `create_driver_links.py`, `show_drivers.py`

The `postinst` script automatically corrects these scripts and sets the new interpreter `opsi-python`.

Alternatively, you can correct the Python scripts by hand.
To do this, enter the `opsi-python` interpreter as a shebang on the first line of the script:

[source,shell]
----
#!/usr/bin/opsi-python
----

==== Custom Python Scripts that use `python-opsi`.

If you have scripts in your environment which use the old interpreter `python-opsi`, perform the following steps:

* Convert the scripts to Python 3 (e.g. using the `2to3` Python tool).
* Enter the new interpreter `opsi-python` as shebang in the first line of the script:

[source,shell]
----
#!/usr/bin/opsi-python
----

==== Backend Extensions

If you have modified the configuration files in `/etc/opsi/backendManager/extend.d` or added new ones, check if they're compatible with Python 3. If necessary, adjust them.

=== Group `pcpatch` => `opsifileadmins`

opsi 4.2 introduces a new default name for the file admin group. This is no longer called `pcpatch` but `opsifileadmins`.
If you update opsi from version 4.1 to 4.2, the previously used name remains.
You can change it in the `/etc/opsi/opsi.conf` configuration file in the `groups` section, option `fileadmingroup`.

NOTE: Keep in mind that if you change groups, the `pcpatch` user must be added to the `opsifileadmins` group.

=== `opsiconfd`: Configuration and Logs

There are some changes in the configuration and log files of `opsiconfd`:

* All configuration options are documented in the online help, which you can display via `opsiconfd --help`.
* The parameters listed in the online help can also be used without `--` in the `opsiconfd.conf` configuration file.
* The `opsiconfd` rotates its logs from now on. You can configure this using the `max-log-size` and `keep-rotated-logs` options.
* The `package.log` log is now part of `opsiconfd.log`.
* The logs introduce a context that you can use for filtering. For example, use the `grep` tool or call `opsiconfd` with the `--log-filter LOG_FILTER` option:

[source,shell]
----
opsiconfd --log-filter instance=package_install
[...]
[6] [2020-09-07 14:41:17.864] [package_install] Running postinst script   (Depotserver.py:235)
[5] [2020-09-07 14:41:17.865] [package_install] Running package script 'postinst'   (Product.py:477)
[...]
----

[source,shell]
----
opsiconfd --log-filter client_addr=10.100.7.5
[...]
[6] [2020-09-07 14:25:16.966] [10.100.7.5     ] Filtering objects by acls   (AccessControl.py:475)
[...]
----

=== Verification of the Server Identity

Since opsi 4.2, the trustworthiness of the opsi-Server can be ensured using standard TLS methods.
Each opsi config server maintains a Certificate Authority (CA), the opsi CA. Every opsi server (config or depot server) receives a TLS certificate from the opsi config server which is signed by the opsi CA. The certificates are automatically created, distributed and updated if necessary.
Any client which trusts the opsi CA also trusts these server certificates.

TIP: You can control this behavior via the `verify_server_cert` and `verify_server_cert_by_ca` options in the `opsiclientd.conf` file (see section xref:manual:security.adoc#opsi-manual-security-server2client[Security]).

[[opsi-4.2-releasenotes-installation]]
== opsi Upgrade

WARNING: We strongly suggest to create backups of all backends before upgrading. For more information, see the chapter xref:manual:server/opsi-backup.adoc[The `opsi-backup` Tool].

All opsi components in this release depend on each other.
Therefore you should always upgrade all components.

We recommend to upgrade the server first and then the opsi packages (products).

In a multi-depot environment it is recommended to start the upgrade on the config server and upgrade the depots afterwards.

TIP: After the upgrade run the command `opsi-setup --set-rights`. It checks and corrects the access permissions. The execution of the command may take several minutes.

[[opsi-4.2-releasenotes-installation-systempackages]]
=== Operating System Packages

Please make sure that you are using the latest opsi 4.1 packages from the stable branch at the time of the upgrade.


[[opsi-4.2-releasenotes-installation-opsipackages]]
=== opsi Packages

Usually, opsi packages are compatible with both opsi 4.1 and opsi 4.2. This also applies to the packages offered in the 4.2 repository at link:https://download.uib.de/[download.uib.de].

NOTE: Please note that the packages in our download area do not necessarily have to have `4.2` as version number to be compatible.

[[opsi-4.2-releasenotes-installation-migration]]
=== Migrating an opsi 4.1 Server

To upgrade an opsi server from version 4.1 to 4.2, first make sure that you use the latest packages of opsi 4.1 from the stable branch. Other packages, like the MySQL/MariaDB server, should be up-to-date as well. Otherwise you may experience problems during the upgrade process.

NOTE: Update the `opsi-winst`, `opsi-client-agent` ( respectively `opsi-linux-client-agent` and `opsi-mac-client-agent`) packages on all clients before upgrading the opsi server.

Upgrading from opsi 4.1 to version 4.2 is possible on all operating systems supported by opsi (see chapter xref:supportmatrix:supportmatrix.adoc[opsi Support Matrix]).

If opsi manages the opsi servers, you can perform the migration with the package `l-opsi-server-migrate`.

WARNING: It's not possible to upgrade from opsi 4.0 directly to opsi 4.2. You have to upgrade to opsi 4.1 first and then to 4.2 afterwards.

[[opsi-4.2-releasenotes-installation-migration-prerequired]]
==== Prerequisites

Starting with version 4.2 the opsi server needs access to a Redis and a Grafana instance. Assuming these services and the opsi server are running on the same machine, you can install the package `opsi-server-full`. It will automatically install and configure all necessary applications. The following sections refer to this as Single Server Setup.

NOTE: Use the official Grafana repositories to install Grafana. If you are running a Debian-based distribution, note that the repositories moved from `packages.grafana.com` to `apt.grafana.com` in November 2022. The old addresses still work, but there may be warnings on the system when installing or updating.

Execute the commands as user `root`.

===== *Debian/Ubuntu/UCS*

[source,shell]
----
sudo apt-get install -y apt-transport-https software-properties-common wget gpg
wget -q -O - https://apt.grafana.com/gpg.key | sudo apt-key add -
echo "deb https://apt.grafana.com/oss/deb stable main" > /etc/apt/sources.list.d/grafana.list
----

===== *SLES/openSUSE*

[source,shell]
----
zypper install wget
cd /etc/zypp/repos.d
cat <<EOF > grafana.repo
[grafana]
name=grafana
baseurl=https://rpm.grafana.com
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://rpm.grafana.com/gpg.key
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
EOF
----

===== *RHEL/AlmaLinux/Rocky Linux*

[source,shell]
----
yum install wget
cd /etc/yum.repos.d
cat <<EOF > grafana.repo
[grafana]
name=grafana
baseurl=https://rpm.grafana.com/
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://rpm.grafana.com/gpg.key
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
EOF
----


[[opsi-4.2-releasenotes-installation-migration-repositories]]
==== Adding the new Repository

Now add the repository for opsi 4.2. Also download the GnuPG key if necessary.

===== *Debian 11 _Bullseye_*

[source,shell]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Debian_11/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Debian_11/Release.key | sudo apt-key add -
----

===== *Debian 10 _Buster_*

[source,shell]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Debian_10/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Debian_10/Release.key | sudo apt-key add -
----

===== *Ubuntu 22.04 LTS _Jammy Jellyfish_*

[source,shell]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_22.04/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_22.04/Release.key | sudo apt-key add -
----

===== *Ubuntu 20.04 LTS _Focal Fossa_*

[source,shell]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_20.04/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_20.04/Release.key | sudo apt-key add -
----

===== *Ubuntu 18.04 LTS _Bionic Beaver_*

[source,shell]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_18.04/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_18.04/Release.key | sudo apt-key add -
----

===== *UCS 4.4*

[source,shell]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Univention_4.4/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Univention_4.4/Release.key | sudo apt-key add -
----

===== *UCS 5.0*

[source,shell]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Univention_5.0/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Univention_5.0/Release.key | sudo apt-key add -
----

===== *openSUSE Leap 15.4:*

[source,shell]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/openSUSE_Leap_15.4/home:uibmz:opsi:4.2:{release}.repo
zypper refresh
----

===== *SLES 15 SP 1:*

[source,shell]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/SLE_15_SP1/home:uibmz:opsi:4.2:{release}.repo
zypper refresh
----

===== *SLES 15 SP 2:*

[source,shell]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/SLE_15_SP2/home:uibmz:opsi:4.2:{release}.repo
zypper refresh
----

===== *SLES 15 SP 3:*

[source,shell]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/SLE_15_SP3/home:uibmz:opsi:4.2:{release}.repo
zypper refresh
----

===== *SLES 15 SP 4:*

[source,shell]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/SLE_15_SP4/home:uibmz:opsi:4.2:{release}.repo
zypper refresh
----

===== *AlmaLinux 8:*

[source,shell]
[subs="attributes"]
----
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/AlmaLinux_8/home:uibmz:opsi:4.2:{release}.repo
yum makecache
----

===== *AlmaLinux 9:*

[source,shell]
[subs="attributes"]
----
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/AlmaLinux_9/home:uibmz:opsi:4.2:{release}.repo
yum makecache
----

===== *Rocky Linux 8:*

[source,shell]
[subs="attributes"]
----
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/RockyLinux_8/home:uibmz:opsi:4.2:{release}.repo
yum makecache
----

===== *Rocky Linux 9:*

[source,shell]
[subs="attributes"]
----
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/RockyLinux_9/home:uibmz:opsi:4.2:{release}.repo
yum makecache
----

===== *RHEL 8:*

[source,shell]
[subs="attributes"]
----
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/RHEL_8/home:uibmz:opsi:4.2:{release}.repo
yum makecache
----

===== *RHEL 9:*

[source,shell]
[subs="attributes"]
----
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/RHEL_9/home:uibmz:opsi:4.2:{release}.repo
yum makecache
----

[[opsi-4.2-releasenotes-installation-migration-migrate]]
==== Upgrading the Operating System

After you have added the repository, you can now start the upgrade. On RPM-based distributions, the package manager replaces existing configuration files with new ones. Refer to the corresponding distribution's documentation for more information.

IMPORTANT: For security reasons we have changed the default ACLs (`/etc/opsi/backendManager/acl.conf`) for opsi 4.2. Therefore we recommend to use the new version of the configuration file.

On Debian and Ubuntu upgrade to opsi 4.2 with the following commands:

*Single-Server-Setup:*
[source,shell]
----
apt update
apt install opsi-server-full
----

*Manual Setup:*
[source,shell]
----
apt update
apt install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
apt dist-upgrade
----

On Univention Corporate Server (UCS) upgrade to opsi 4.2 with the following commands:

*Single-Server-Setup:*
[source,shell]
----
univention-install opsi-server-full
----

*Manuelles Setup:*
[source,shell]
----
univention-install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
univention-install opsi-Server
----

On openSUSE and SUSE Linux Enterprise Server (SLES) upgrade to opsi 4.2 with the following commands:

*Single-Server-Setup:*
[source,shell]
----
zypper refresh
zypper install opsi-server-full
----

*Manuelles Setup:*
[source,shell]
----
zypper refresh
zypper install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
zypper dup --from home_uibmz_opsi_4.2_{release}
----

On RedHat Enterprise Linux (RHEL), AlmaLinux, and Rocky Linux upgrade to opsi 4.2 with the following commands:

*Single-Server-Setup:*
[source,shell]
----
yum makecache
yum install opsi-server-full
yum upgrade
----

*Manuelles Setup:*
[source,shell]
----
yum makecache
yum install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
yum upgrade
----

[[opsi-4.2-releasenotes-installation-migration-opsi-packages]]
==== Upgrading the opsi Packages

The last step is to upgrade to the latest opsi packages.

[[opsi-4.2-releasenotes-installation-migration-opsi-packages-standard]]
===== Using the Default Configuration

If you have not made any changes to the standard configuration in `/etc/opsi/package-updater.repos.d/`, you can update the opsi packages with this command:

[source, shell]
----
opsi-package-updater -v update
----

NOTE: opsi packages that run Python scripts on the server should be re-installed. Usually these are `opsi-client-agent`, `opsi-linux-client-agent` and all packages that install Windows operating systems (`win*`). Read more about this in the section <<opsi-4.2-releasenotes-important-reinstall-opsi-packages>>.

[[opsi-4.2-releasenotes-eol]]
== End of Support

The next sections show which packages, operating systems etc. opsi 4.2 no longer supports.

=== Package `opsi4ucs`

With the release of opsi 4.2 we have adapted the UCS support to the other distributions. The function of `opsi4ucs` is taken over by the package for the opsi server and its variants. The package `opsi4ucs` is still included in opsi 4.2 as a transition package to simplify the migration from opsi 4.1. During the upgrade from opsi 4.1 to 4.2 the package management tool automatically replaces `opsi4ucs` with `opsi-server`.

[[opsi-4.2-releasenotes-eol_opsi41]]
=== End of Life: opsi 4.1 Q4/2021

So far we have supported the respective opsi predecessor (oldstable) for at least one year parallel to the current version. But in this case we decided to shorten the time and discontinue opsi 4.1 for Q4 2021 (November 30, 2021). The main reason for the shortened EOL period: not all current operating systems support opsi 4.1, including Ubuntu 20.04.
opsi 4.1 is completely based on Python 2, and this version has already reached EOL in April 2020 and will no longer receive updates.

TIP: Our professional https://www.uib.de/en/support-training/support[opsi support] will be happy to help you with the switch to the new opsi version. Even after the EOL of opsi 4.1 we are at your side and can assist with migrations--we strongly recommend, though, to use the time until the end of Q4/2021 and upgrade to opsi 4.2.

[[opsi-4.2-releasenotes-eol_server]]
=== Linux Distributions

From version 4.2 on we no longer offer packages for the opsi server for the following systems:

* CentOS 7.x
* Debian 8.x
* RedHat Enterprise Linux 7.x
* Suse Linux Enterprise Server 12

[[opsi-releasenotes-4.2-changes-changed-defaults]]
== New Default Settings

With opsi 4.2 we have changed some default settings to reflect experiences from operating opsi.

This is especially important if you install new opsi servers in an existing environment, as this may lead to a change in expected behavior.

NOTE: Please note: for security reasons we have changed the default ACLs (`/etc/opsi/backendManager/acl.conf`) for opsi 4.2.

[[opsi-releasenotes-4.2-changes-mysql-config]]
== MySQL Backend: `connection lifetime`

To avoid the error message `mysql server has gone away`, we have changed the default configuration of the MySQL backend. The `connectionPoolRecycling` option now has `_28800` as default value.

The `connectionPoolRecycling` setting is an option in the configuration of the MySQL/MariaDB database system. When enabled, MySQL releases connections in the pool after a certain amount of time, even if they haven't been closed yet. This can help to make the connection pool more efficient.

[[opsi-4.2-releasenotes-api-changes]]
== API Changes

The API has undergone some changes in opsi 4.2 as well. Affected are, among other things, the API of the web service, `opsi-admin` and calls made by `opsiServiceCall` in `opsi-script`.

[[opsi-4.2-releasenotes-deprecated-api-methods]]
=== Deprecated API Methods

The following methods are considered deprecated. They will be removed with the next major or minor release:

* `getClients_listOfHashes`: This method was marked as deprecated in opsi 4.1. When called without parameters, this method returns the output of `getClients`. In all other cases an error is returned.
* `getClientIds_list`: This method was marked as deprecated in opsi 4.1. When called without parameters, this method returns the output of `getClientIDs`. If called with the parameter `depotIds`, the result of `getClientsOnDepot` will be returned. If called with parameters `productId` and optionally `installationStatus`, the result of `getClientsWithProducts` will be returned.

[[opsi-4.2-releasenotes-removed-api-methods]]
=== Removed API Methods

The following API method has been removed:

* `backend_searchIdents`

[[opsi-4.2-releasenotes-knownbugs]]
== Known Issues and Bugs

* `opsi-admin`: The interactive mode doesn't work with non-ASCII characters such as ö, ä, ü.
* `opsiwebservice` doesn't support deflate compression.

[[opsi-4.2-releasenotes-packages]]
== List of Packages

* `opsi4ucs` 4.2...
* `opsiconfd` 4.2...
* `opsipxeconfd` 4.2...
* `opsi-server` 4.2...
* `opsi-utils` 4.2...
* `opsi-linux-bootimage`

NOTE: We have also released the updated opsi packages for opsi 4.1. Excluded are `l-opsi-server` and `l-opsi-server-migrate`.

// Changelogs
include::changelogs.adoc[]
