////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      18.04.2023
:Revision:  4.2
:toclevels: 5
:icons: font
:xrefstyle: full
:doctype:   book

include::common:partial$opsi_terms.adoc[]

[[opsi-4.2-releasenotes]]
= Version 4.2 

TIP: A list of currently supported Linux distributions for the opsi server as well as for the opsi client (Windows, Linux, and macOS) can be found in chapter xref:supportmatrix:supportmatrix.adoc[opsi Support Matrix].

[[opsi-4.2-releasenotes-overview]]
== New Features (Main Focus)

* Switch to Python 3
* All Python applications are distributed as executable binaries.
* opsi-python interpreter for your own scripts
* opsi server:
** Complete re-implementation of `opsiconfd` with focus on performance and scalability
** `opsiconfd` can now run in a Docker container.
** New dependency on Redis Server >= 5i, including the RedisTimeSeries module
** Grafana for visualization of performance data
** New default ACLs for API access

[[opsi-4.2-releasenotes-important]]
== Important Information

opsi 4.2 is an independent release and has its own repositories.
You have to add the new repositories to the system and remove the the repositories of the previous version.
Only after that you can install/upgrade opsi.

For an upgrade from opsi 4.1 the installed packages need to be the latest opsi 4.1 stable versions.
Other packages - such as MySQL server - should also be up-to-date.
Otherwise errors in the upgrade process may occur.

It is also strongly recommended to update the packages 'opsi-winst', 'opsi-client-agent' or 'opsi-linux-client-agent' on all clients to the latest opsi 4.1 versions before upgrading.

=== Python 3

opsi 4.2 is completely based on Python 3.
Furthermore, all Python-based packages are distributed as executable binaries.
The `python-opsi` package is no longer available as an installable package.
Therefore, it is important to note the following things:

[[opsi-4.2-releasenotes-important-reinstall-opsi-packages]]
==== opsi Packages containing server-side Python Scripts

After upgrading the opsi server to opsi 4.2, use the `opsi-package-manager` tool to reinstall the opsi packages that contain Python scripts to run on the server:

* opsi client agent: `opsi-deploy-client-agent`.
* windows: `create_driver_links.py`, `show_drivers.py`

The `postinst` script automatically corrects these scripts and sets the new interpreter `opsi-python`.

Alternatively, you can correct the Python scripts by hand.
To do this, enter the `opsi-python` interpreter as a shebang on the first line of the script:

[source,prompt]
----
#!/usr/bin/opsi-python
----

==== Custom Python Scripts that use `python-opsi`.

If you have scripts in your environment which use the old interpreter `python-opsi`, perform the following steps:

* Convert the scripts to Python 3 (e.g. using the `2to3` Python tool).
* Enter the new interpreter `opsi-python` as shebang in the first line of the script:

[source,prompt]
----
#!/usr/bin/opsi-python
----

==== Backend Extensions

If you have modified the configuration files in `/etc/opsi/backendManager/extend.d` or added new ones, check if they're compatible with Python 3. If necessary, adjust them.

=== Group `pcpatch` => `opsifileadmins`

opsi 4.2 introduces a new default name for the file admin group. This is no longer called `pcpatch` but `opsifileadmins`. 
If you update opsi from version 4.1 to 4.2, the previously used name remains.
You can change it in the `/etc/opsi/opsi.conf` configuration file in the `groups` section, option `fileadmingroup`.

NOTE: Keep in mind that if you change groups, the `pcpatch` user must be added to the `opsifileadmins` group.

=== `opsiconfd`: Configuration and Logs

There are some changes in the configuration and log files of `opsiconfd`:

* All configuration options are documented in the online help, which you can display via `opsiconfd --help`.
* The parameters listed in the online help can also be used without `--` in the `opsiconfd.conf` configuration file.
* The `opsiconfd` rotates its logs from now on. You can configure this using the `max-log-size` and `keep-rotated-logs` options.
* The `package.log` log is now part of `opsiconfd.log`.
* The logs introduce a context that you can use for filtering. For example, use the `grep` tool or call `opsiconfd` with the `--log-filter LOG_FILTER` option:

[source,prompt]
----
opsiconfd --log-filter instance=package_install
[...]
[6] [2020-09-07 14:41:17.864] [package_install] Running postinst script   (Depotserver.py:235)
[5] [2020-09-07 14:41:17.865] [package_install] Running package script 'postinst'   (Product.py:477)
[...]
----

[source,prompt]
----
opsiconfd --log-filter client_addr=10.100.7.5
[...]
[6] [2020-09-07 14:25:16.966] [10.100.7.5     ] Filtering objects by acls   (AccessControl.py:475)
[...]
----

=== Verification of the Server Identity

Since opsi 4.2, the trustworthiness of the opsi-server can be ensured using standard TLS methods.
Each opsi config server maintains a Certificate Authority (CA), the opsi CA. Every opsi server (config or depot server) receives a TLS certificate from the opsi config server which is signed by the opsi CA. The certificates are automatically created, distributed and updated if necessary.
Any client which trusts the opsi CA also trusts these server certificates.

TIP: You can control this behavior via the `verify_server_cert` and `verify_server_cert_by_ca` options in the `opsiclientd.conf` file (see section xref:manual:security.adoc#opsi-manual-security-server2client[Security]).

[[opsi-4.2-releasenotes-installation]]
== opsi Upgrade

CAUTION: We strongly suggest to create backups of all backends before upgrading. For more information, see the chapter xref:manual:server/opsi-backup.adoc[The `opsi-backup` Tool].

All opsi components in this release depend on each other.
Therefore you should always upgrade all components.

We recommend to upgrade the server first and then the opsi packages (products).

In a multi-depot environment it is recommended to start the upgrade on the config server and upgrade the depots afterwards.

TIP: After the upgrade run the command `opsi-setup --set-rights`. It checks and corrects the access permissions. The execution of the command may take several minutes.

[[opsi-4.2-releasenotes-installation-systempackages]]
=== Operating System Packages

Please make sure that you are using the latest opsi 4.1 packages from the stable branch at the time of the upgrade.


[[opsi-4.2-releasenotes-installation-opsipackages]]
=== opsi Packages

Usually, opsi packages are compatible with both opsi 4.1 and opsi 4.2. This also applies to the packages offered in the 4.2 repository at link:https://download.uib.de/[download.uib.de].

NOTE: Please note that the packages in our download area do not necessarily have to have `4.2` as version number to be compatible.

[[opsi-4.2-releasenotes-installation-migration]]
=== Upgrading an opsi 4.1 Server

To upgrade an opsi server from version 4.1 to 4.2, first make sure that you use the latest packages of opsi 4.1 from the stable branch. Other packages, like the MySQL/MariaDB server, should be up-to-date as well. Otherwise you may experience problems during the upgrade process.

NOTE: Update the `opsi-winst`, `opsi-client-agent` ( respectively `opsi-linux-client-agent` and `opsi-mac-client-agent`) packages on all clients before upgrading the opsi server.

Upgrading from opsi 4.1 to version 4.2 is possible on all operating systems supported by opsi (see chapter xref:supportmatrix:supportmatrix.adoc[opsi Support Matrix]).

If opsi manages the opsi servers, you can perform the migration with the package `l-opsi-server-migrate`.

CAUTION: It's not possible to upgrade from opsi 4.0 directly to opsi 4.2. You have to upgrade to opsi 4.1 first and then to 4.2 afterwards.

[[opsi-4.2-releasenotes-installation-migration-prerequired]]
==== Prerequisites

Starting with version 4.2 the opsi server needs access to a Redis and a Grafana instance. Assuming these services and the opsi server are running on the same machine, you can install the package `opsi-server-full`. It will automatically install and configure all necessary applications. The following sections refer to this as Single Server Setup. 

NOTE: Use the official Grafana repositories to install Grafana. If you are running a Debian-based distribution, note that the repositories moved from `packages.grafana.com` to `apt.grafana.com` in November 2022. The old addresses still work, but there may be warnings on the system when installing or updating.

===== *Debian/Ubuntu/UCS*

[source,prompt]
----
sudo apt-get install -y apt-transport-https software-properties-common wget gpg
wget -q -O - https://apt.grafana.com/gpg.key | sudo apt-key add -
echo "deb https://apt.grafana.com/oss/deb stable main" > /etc/apt/sources.list.d/grafana.list
----

===== *SLES/openSUSE*

[source,prompt]
----
zypper install wget
cd /etc/zypp/repos.d
cat <<EOF > grafana.repo
[grafana]
name=grafana
baseurl=https://rpm.grafana.com
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://rpm.grafana.com/gpg.key
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
EOF
----

===== *RHEL/Alma Linux/Rocky Linux*

[source,prompt]
----
yum install wget
cd /etc/yum.repos.d
cat <<EOF > grafana.repo
[grafana]
name=grafana
baseurl=https://rpm.grafana.com/
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://rpm.grafana.com/gpg.key
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
EOF
----


[[opsi-4.2-releasenotes-installation-migration-repositories]]
==== Adding the new Repository

Now add the repository for opsi 4.2. Also download the GnuPG key if necessary. Execute the commands as user `root`.

===== *Debian 11 _Bullseye_*

[source,prompt]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Debian_11/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Debian_11/Release.key | sudo apt-key add -
----

===== *Debian 10 _Buster_*

[source,prompt]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Debian_10/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Debian_10/Release.key | sudo apt-key add -
----

===== *Ubuntu 22.04 LTS _Jammy Jellyfish_*

[source,prompt]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_22.04/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_22.04/Release.key | sudo apt-key add -
----

===== *Ubuntu 20.04 LTS _Focal Fossa_*

[source,prompt]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_20.04/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_20.04/Release.key | sudo apt-key add -
----

===== *Ubuntu 18.04 LTS _Bionic Beaver_*

[source,prompt]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_18.04/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/xUbuntu_18.04/Release.key | sudo apt-key add -
----

===== *UCS 4.4*

[source,prompt]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Univention_4.4/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Univention_4.4/Release.key | sudo apt-key add -
----

===== *UCS 5.0*

[source,prompt]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Univention_5.0/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/{release}/Univention_5.0/Release.key | sudo apt-key add -
----

===== *openSUSE Leap 15.4:*

[source,prompt]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/openSUSE_Leap_15.4/home:uibmz:opsi:4.2:{release}.repo
zypper refresh
----

===== *SLES 15 SP 1:*

[source,prompt]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/SLE_15_SP1/home:uibmz:opsi:4.2:{release}.repo
zypper refresh
----

===== *SLES 15 SP 2:*

[source,prompt]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/SLE_15_SP2/home:uibmz:opsi:4.2:{release}.repo
zypper refresh
----

===== *SLES 15 SP 3:*

[source,prompt]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/SLE_15_SP3/home:uibmz:opsi:4.2:{release}.repo
zypper refresh
----

===== *SLES 15 SP 4:*

[source,prompt]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/SLE_15_SP4/home:uibmz:opsi:4.2:{release}.repo
zypper refresh
----

===== *Alma Linux 8:*

[source,prompt]
[subs="attributes"]
----
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/AlmaLinux_8/home:uibmz:opsi:4.2:{release}.repo
yum makecache
----

===== *Alma Linux 9:*

[source,prompt]
[subs="attributes"]
----
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/AlmaLinux_9/home:uibmz:opsi:4.2:{release}.repo
yum makecache
----

===== *Rocky Linux 8:*

[source,prompt]
[subs="attributes"]
----
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/RockyLinux_8/home:uibmz:opsi:4.2:{release}.repo
yum makecache
----

===== *Rocky Linux 9:*

[source,prompt]
[subs="attributes"]
----
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/RockyLinux_9/home:uibmz:opsi:4.2:{release}.repo
yum makecache
----

===== *RHEL 8:*

[source,prompt]
[subs="attributes"]
----
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/RHEL_8/home:uibmz:opsi:4.2:{release}.repo
yum makecache
----

===== *RHEL 9:*

[source,prompt]
[subs="attributes"]
----
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.2:{release}/RHEL_9/home:uibmz:opsi:4.2:{release}.repo
yum makecache
----

[[opsi-4.2-releasenotes-installation-migration-migrate]]
==== Upgrading the operating system packages

After adding the new package sources, the system can be migrated.

IMPORTANT: The default ACLs (`/etc/opsi/backendManager/acl.conf`) were changed in opsi 4.2 for security reasons.
We therefore urgently recommend using the new version of the configuration file.

IMPORTANT: With RPM-based distributions, existing configuration files are replaced with new ones as part of the migration. Please refer to the information for the relevant distributions.

Debian and Ubuntu are upgraded to opsi 4.2 with the following commands:

*Single-Server-Setup:*
[source,prompt]
----
apt update
apt install opsi-server-full
----

*Manual Setup:*
[source,prompt]
----
apt update
apt install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
apt dist-upgrade
----

RedHat and CentOS are updated to opsi 4.2 with the following commands:

*Single-Server-Setup:*
[source,prompt]
----
yum makecache
yum install opsi-server-full
yum upgrade
----

*Manual Setup:*
[source,prompt]
----
yum makecache
yum install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
yum upgrade
----

OpenSUSE is ans SUSE Linux Enterprise Server (SLES) updated to opsi 4.2 with the following commands:

*Single-Server-Setup:*
[source,prompt]
----
zypper refresh
zypper install opsi-server-full
----

*Manual Setup:*
[source,prompt]
----
zypper refresh
zypper install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
zypper dup --from home_uibmz_opsi_4.2_{release}
----

Univention UCS is updated to opsi 4.2 with the following commands:

*Single-Server-Setup:*
[source,prompt]
----
univention-install opsi-server-full
----

*Manuelles Setup:*
[source,prompt]
----
univention-install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
univention-install opsi-server
----

[[opsi-4.2-releasenotes-installation-migration-opsi-packages]]
==== Updating the opsi packages

The last step is to update to the latest opsi packages.

[[opsi-4.2-releasenotes-installation-migration-opsi-packages-standard]]
===== Using the default configuration

If you have not made any changes to the standard configuration in `/etc/opsi/package-updater.repos.d/`, you can update the opsi packages directly using this command:

[source, prompt]
----
opsi-package-updater -v update
----

==== Opsi packages that contain server-side Python scripts
Please reinstall opsi packages that contain Python scripts that are executed on the server.
These are usually `opsi-client-agent`, `opsi-linux-client-agent` and all packages that install Windows operating systems (`win *`).
Details can be found at: <<opsi-4.2-releasenotes-important-reinstall-opsi-packages>>.

After these steps your opsi 4.1 server is migrated to release 4.2 and ready for use.

////
[[opsi-4.2-releasenotes-installation-migration-cleanup]]
==== Optionale Aufräumarbeiten

After a migration it can be that some unrequired files still exist on the server.
The reason for this is that they either have been altered manually or that restoring a backup has brought these files back to the system.

The following files resp. folders can be removed:

* TBD
////

[[opsi-4.2-releasenotes-installation-migration-4.0.7]]
===== Upgrading from opsi 4.0.7
If you are coming from an opsi 4.0.7, you should skip opsi 4.1 and upgrade directly to opsi 4.2.
* First update your server operating system to a version supported by opsi 4.0.7 and 4.2 (e.g. Ubuntu 18.04).
* Then update your opsi server to opsi 4.2 as described above.
* Finally update the opsi-client-agent to the latest stable version 4.2.

[[opsi-4.2-releasenotes-knownbugs]]
== Known bugs / known problems

.KNOWN BUGS:

* opsi-admin: The interactive mode does not work with non-ASCII characters such as ö, ä, ü.


[[opsi-4.2-releasenotes-eol]]
== End of support

Discontinuations are listed in this chapter.

=== opsi4ucs package

With opsi 4.2 the ucs support was adepted to the opsi-standard like on other supported distibutions. The function of opsi4ucs was implemented in opsi-server package and its variants.
The opsi4ucs package exists in opsi 4.2 as a transitionpackage to make the migration easier. This package will automatically removed during the upgrade process.


[[opsi-4.2-releasenotes-eol_opsi41]]
=== EOL: opsi 4.1 Q4/2021

So far we have supported the respective opsi version (oldstable) for at least one year parallel to the current version. But in this case we decided to shorten the time to half and to discontinue opsi 4.1 for Q4 2021 (11/30/2021). The main reason for the shortened EOL time: Not all current operating systems support opsi 4.1, including e.g. Ubuntu 20.04.
opsi 4.1 is completely based on Python 2, and this version has already reached EOL in April 2020 and will no longer receive updates.

Via the https://www.uib.de/de/support-schulung/support[opsi support contracts] we are happy to support you to update to the new opsi version. Also after the EOL of opsi 4.1 we are there for you and help with migrations - but we strongly recommend to use the time until the end of Q4/2021 and update to opsi 4.2.

[[opsi-4.2-releasenotes-eol_server]]
=== End of support: Distributions for opsi-server

These distributions will not be supported anymore by opsi for various reasons.

* CentOS 7.x
* Debian 8.x
* RedHat Enterprise Linux 7.x
* Suse Linux Enterprise Server 12


[[opsi-releasenotes-4.2-changes-changed-defaults]]
== Changes in default settings

With opsi 4.2 some default settings have been changed to reflect experiences from running opsi.

This is especially important if new opsi servers are installed in an existing environment, as this may lead to a change in expected behavior.

* Note the changed acl.conf.


[[opsi-releasenotes-4.2-changes-python]]
== Switch to Python 3 and PyInstaller

This version is based on Python 3.
All opsi Python applications (opsiconfd, opsipxeconfd, opsiclientd, opsi-utils, ...) are now distributed as binaries built with PyInstaller.
Please use the `opsi-python` interpreter for your own scripts that need access to the python-opsi library.

[[opsi-releasenotes-4.2-changes-mysql-config]]
== MySQL backend: Limiting connection lifetime

To avoid the error messages: "mysql server has gone away", the default configuration of the MySQL backend was changed. The `connectionPoolRecycling` option now has been set to _28800_ as the default value.
This setting limits the lifetime of the connections in the connection pool, which is used for the connections to MySQL (or MariaDB) server.

[[opsi-4.2-releasenotes-api-changes]]
== API changes

The API has been changed in opsi 4.2.

Affected by this are among others the API of the web service, opsi-admin and calls made with opsiServiceCall in opsi-script.


[[opsi-4.2-releasenotes-changed-api-methods]]
=== Changed API methods

* `getClients_listOfHashes`: This method was marked as deprecated in opsi 4.1. When called without parameters, this method returns the output of `getClients`. In all other cases an error is returned.
* `getClientIds_list`: This method was marked as deprecated in opsi 4.1. When called without parameters, this method returns the output of `getClientIDs`. If called with parameter `depotIds` then the result of `getClientsOnDepot` will be returned. If called with parameters `productId` and optionally `installationStatus` the result of `getClientsWithProducts` will be returned.


[[opsi-4.2-releasenotes-deprecated-api-methods]]
=== Deprecated API methods

The following methods are considered deprecated. They will be removed with the next major or minor release.

* `getClients_listOfHashes`
* `getClientIds_list`


[[opsi-4.2-releasenotes-removed-api-methods]]
=== Removal of API methods

The following API methods have been removed:

* `backend_searchIdents`

These methods are no longer available.


[[opsi-4.2-releasenotes-misc]]
== Miscellaneous

* opsiwebservice does not support "deflate" encoded data as a compression method anymore.


[[opsi-4.2-releasenotes-packages]]
== List of packages

.Server packages:
* opsi4ucs 4.2...
* opsiconfd 4.2...
* opsipxeconfd 4.2...
* opsi-server 4.2...
* opsi-utils 4.2...
* opsi-linux-bootimage

NOTE: The updated opsi packages have already been released for opsi 4.1. The only exceptions are `l-opsi-server` and `l-opsi-server-migrate`.

// Changelogs
include::changelogs.adoc[]
