////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      30.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

= Quick Start

This chapter offers a quick introduction to opsi. First, it explains how to set up an opsi server with the help of docker or the pre-configured virtual machine. After that, further subchapters describe how to create new opsi clients, integrate existing machines into the environment as opsi clients and distribute products on the clients.


1. Install an opsi server. Either with xref:server/server-installation-docker.adoc[docker] or the ready-made xref:server/server-installation-vm.adoc[VM].
2. Download the user interface xref:gui/configed.adoc[opsi-configed].
3. Install products to the server: xref:products/products.adoc[install products].
4. Register one or more clients on the server. See xref:clients/client-installation.adoc[Add clients].
5. xref:rollout/rollout.adoc[Rollout] products to the clients.


NOTE: A detailed description of the server installation with all variants can be found in the chapter xref:server:overview.adoc[opsi-Server]. The complete client manuals can be found in chapter xref:clients:opsi-clients.adoc[opsi-Clients]. The client manuals for xref:clients:windows-client/windows-client-manual.adoc[Windows], xref:clients:linux-client/linux-client-manual.adoc[Linux], and xref:clients:macos-client/mac-client-manual.adoc[macOS] are also located there.

TIP: Interested in opsi extensions? With the xref:opsi-modules:modules.adoc#opsi-basic-license[opsi Basic License] you can test and use (almost) all opsi extensions on up to 30 clients for free. Find out more in the xref:opsi-modules:modules.adoc#opsi-basic-license[opsi extensions] chapter.
