////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      11.12.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[quick-start-intro]]
= Quick Start

This chapter offers a quick introduction to opsi, starting with the setup of an opsi server through Docker or a preconfigured virtual machine. Subsequent chapters will guide you through creating new opsi clients, integrating existing computers as opsi clients, and distributing products to these clients.

1. Install an opsi server, either with xref:server/server-installation-docker.adoc[Docker] or the ready-to-use xref:server/server-installation-vm.adoc[virtual machine].
2. Download the user interface xref:gui/configed.adoc[*opsi-configed*].
3. Deploy products on your server by installing xref:products/products.adoc[opsi products].
4. Register one or more clients with the server (see chapter xref:clients/client-installation.adoc[Adding Clients].
5. xref:rollout/rollout.adoc[Roll out] the previously installed products to your clients.

NOTE: For an extensive description of server installation, including all variants, refer to the chapter xref:server:overview.adoc[opsi Server]. Detailed manuals for clients are available in the chapter xref:clients:opsi-clients.adoc[opsi Clients], including specific guides for xref:clients:windows-client/windows-client-manual.adoc[Windows], xref:clients:linux-client/linux-client-manual.adoc[Linux], and xref:clients:macos-client/mac-client-manual.adoc[macOS] clients.

TIP: Interested in exploring opsi extensions? With the xref:opsi-modules:modules.adoc#opsi-basic-license[opsi Basic License], you can test and use (almost) all opsi extensions on up to 30 clients free of charge. Discover more in the chapter xref:opsi-modules:modules.adoc[opsi Extensions].
