////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      28.03.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



[[opsi-winclient-softwintegration]]
= Integrating custom Software

The installation of software using opsi is managed either by the xref:clients:windows-client/windows-client-agent.adoc[Client Agent] or the setup program xref:opsi-script-manual:opsi-script-manual.adoc[*opsi-script*]. When packaging your own software for deployment through opsi, it's necessary to create an `opsi-script` script for each product. This script, along with the installation files and metadata, should be packed. As a result, you'll get an opsi product which is then installed on the opsi server (see the chapter xref:clients:windows-client/minimal-products.adoc[Adding Products (opsi Server)]).

[[opsi-winclient-softwintegration-tutorial]]
== Tutorial: Creating an *opsi-script* Script

include::common:partial$softwintegration-tutorial-introduction.adoc[]

[[opsi-winclient-softwintegration-tutorial-general]]
=== Non-interactive software installation (Windows)

Basically, there are three different ways to integrate a software package into the automatic software distribution for Windows operating systems. Additionally, there's a variant that uses the link:https://learn.microsoft.com/en-us/windows/win32/msi/windows-installer-portal[Windows Installer] service:

* *Unattended*/*Silent Setup*: +
This approach involves using the original setup program and configuring it for non-interactive mode via command line parameters. A notable example is the silent installation of an MSI package using the `/quiet` option of the link:https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/msiexec[*msiexec*] tool.

* *Interactive Setup with recorded Answers*: +
Begin by running the original setup program once to observe the window titles and the sequence of questions and responses during the setup. Record these details in a script. During software distribution, an automation tool such as link:https://www.autoitscript.com/site/[AutoIt] or link:https://www.autohotkey.com/[AutoHotkey] interacts with the setup program as dictated by the script.

* *Recreate Setup Routine with `opsi-script`*: +
While the original setup program is active, use a tool like link:https://learn.microsoft.com/en-us/sysinternals/downloads/procmon[Process Monitor/Procmon] to log all system changes. You then craft the `opsi-script` script based on the logged data and the changes you’ve recorded.

NOTE: opsi supports all three variants. In practice, a combination of several methods is often used.

include::common:partial$softwintegration-tutorial-script-structure-opsi-script-basics.adoc[]

[[opsi-winclient-softwintegration-tutorial-windows-special-commands]]
===== Special Commands for Windows

* `GetOS`: This function retrieves the operating system type. It returns values such as `Linux`, `Windows_NT` (covering Windows NT through Windows 11), or `macOS`.

* `GetMsVersionInfo`: This function provides detailed information about the internal Windows version. For instance, Windows 7 is identified as "6.1", while Windows 11 is recognized as "10.0", etc.

* `GetMsVersionName`: This function returns the commercial version name of a Windows system. For example, Windows 7 returns "7.0", and Windows 11 returns "11.0", and so on.

* `getMSVersionMap`: This function locally queries the operating system information and records it into a string list.

TIP: For more comprehensive details about these string functions, refer to the section xref:opsi-script-manual:prim-section.adoc#opsi-script-string-functions-os[String Functions which return the OS Type].

[[opsi-winclient-softwintegration-tutorial-template]]
== Example: Windows Template *opsi-template*

You can create this template with the `opsi-setup-detector` tool (see the section <<opsi-winclient-softwintegration-tutorial-create-with-opsi-setup-detector>>).

// include docu: actual template for windows
include::common:partial$firststeps-opsi-template-win.adoc[]

[[opsi-client-softwintegration-create-opsi-package]]
== Creating opsi Products

The following sections outline the steps for packaging software, specifically for creating opsi products. The fundamental process involves:

1. Creating the basic framework of a package using the `opsi-setup-detector` (refer to section <<opsi-winclient-softwintegration-tutorial-create-with-opsi-setup-detector>>).
2. Testing the `opsi-script` script (see section <<opsi-softwintegration-tutorial-create-and-test-script>>).
3. Using the opsi PackageBuilder (oPB) to transform the initial form into a complete opsi package, which is then stored on the opsi server.

// include docu: opsi-setup-detector installation
include::common:partial$setup-detector-installation.adoc[]

// include docu: opsi-logviewer installation
include::common:partial$opsi-logviewer-installation.adoc[]

[[opsi-winclient-softwintegration-tutorial-create-with-opsi-setup-detector]]
== *opsi-setup-detector*: Creating a Script

The following sections explain in detail how to use the `opsi-setup-detector` to analyze a setup file and create an opsi product.

// include docu: opsi-setup-detector
include::common:partial$setup-detector-use-start.adoc[]

// include docu: Windows specific tasks in opsi-setup-detector
include::common:partial$osd-tasks-windows.adoc[]

// include docu: how to use the opsi-setup-detector
include::common:partial$osd-task-use-single-analyze-and-create.adoc[]

// include docu: The modify and test cycle
include::common:partial$softwintegration-tutorial-modify-test-cycle.adoc[]

[[opsi-winclient-softwintegration-tutorial-template-details]]
== Advanced Configuration with *opsi-setup-detector*

In the upcoming sections, we'll explore additional configuration features of the `opsi-setup-detector`. These include using a custom directory, installing from a local temporary directory, managing license keys, and personalizing user profiles and desktop icons.

// include docu: OSD Checkboxes for additional code
include::common:partial$osd-checkboxes-subtasks.adoc[]

[[opsi-winclient-softwintegration-tutorial-opsiadmin]]
== Installation with Logged-in User

There are times when software installations require a logged-in user. An indication of this is when a manual execution of an `opsi-script` script with commands for unattended or silent installation works, but the same installation fails when executed automatically through opsi.

This could be because the installation program requires a logged-in user or needs access to a user profile.
In such scenarios, you can integrate your installation into an opsi package that establishes these necessary conditions. You can create such a package using the `opsi-setup-detector` by selecting the Windows task _Analyze File and Create Package 'with user'_.

[[opsi-winclient-softwintegration-tutorial-customizing]]
== Customizing the Unattended/Silent Setup

Following a successful silent installation, there's often a need for additional customizations. Using `opsi-script` makes these adjustments manageable, but first, it's essential to understand which changes in the graphical user interface correspond to specific alterations in files and the Windows registry.

For this task, consider using tools such as:

* link:https://learn.microsoft.com/en-us/sysinternals/[Sysinternals]
* link:https://sourceforge.net/projects/regshot/[Regshot]

[[opsi-winclient-softwintegration-tutorial-autoit]]
== Setup with Automated Responses

An alternative and swift method for integration into automatic software distribution is the setup with automated responses. This approach uses a control program to automate user interactions with dialog windows that appear during setup.

For this, we recommend this tool:

* link:http://www.autoitscript.com[AutoIt]

=== AutoIt: Managing the Setup Process

AutoIt provides various functionalities for managing the setup process, including the capability to address potential error conditions with `[ADLIB]` script sections.

One critical issue, however, remains unaddressed: unexpected windows, not previously incorporated into the script, can halt the script's execution. Additionally, user interventions through mouse and keyboard (unless disabled) can unpredictably alter the scripted sequence of events.

TIP: For these reasons, an unattended or silent setup is typically the better solution! A hybrid method can also be effective: use a silent setup for the main installation, with an AutoIt script intercepting and managing known exceptions or special conditions.

=== AutoIt: Known Issues

When installations are transferred to a different desktop in the client agent configuration, or if the desktop is locked, certain AutoIt functions have problems.

NOTE: It is advisable to steer clear of these functions in `opsi-script` scripts, if possible:

* `winwait()`

* `winactivate()`

* `Send()`

Unfortunately, these are the three most frequently used functions. We recommend replacing the commands with those included in the `opsi-script` library `C:\Program Files (x86)\opsi.org\opsi-client-agent\opsi-script\lib\opsi-autoit-lib.au3`. This library not only includes the extended functions outlined here but also encompasses a logging function. Simply copy the `opsi-autoit-lib.au3` file into the product directory and then include it in the AutoIt code like this:

[source]
----
#include "%scriptpath%\opsi-autoit-lib.au3
----

After that, you can replace the following items:

* You can replace `winwait()` with the function `opsiwinwait($title, $text, $maxseconds, $logname)`.
* `Send()` can be replaced by the function `opsiControlClick($title, $text, $id, $maxseconds, $logname)` or by `opsiControlSetText($title, $text, $id,$sendtext, $maxseconds, $logname)`.

TIP: It is recommended to determine the ControlID with `Au3info.exe`. Be sure to use the numeric ControlID, as other variants seem to cause problems.

=== AutoIT: Examples and additional Links

* You can find examples in the directory `C:\Program Files (x86)\opsi.org\opsi-client-agent\opsi-script\lib\` in the files: +

  - `autoit_example_1.txt`
  - `autoit_example_2.txt`
  - `autoit_example_3.txt`

See also: +
http://www.autoitscript.com/wiki/FAQ#Why_doesn.27t_my_script_work_on_a_locked_workstation.3F +
http://www.autoitscript.com/autoit3/docs/ +
http://www.autoitscript.com/autoit3/docs/intro/controls.htm +
http://www.autoitscript.com/autoit3/docs/functions.htm

[[opsi-winclient-softwintegration-tutorial-analyse-and-repackage]]
== Analyzing and Repackaging

When developers build an application package, they are aware of the essential components needed for its functionality. In cases where an installation package already exists, running the setup program can reveal which parts must be installed on a workstation to achieve the desired functionality.

Several tools are available for analyzing setup programs, including:

* link:https://sourceforge.net/projects/regshot/files/regshot/[Regshot]
* link:https://www.itninja.com/community/appdeploy-repackager[AppDeploy Repackager]

[[opsi-winclient-softwintegration-tutorial-deinstall]]
== Uninstalling Products

Removing software from a computer typically involves creating an uninstall script. However, the challenge lies in determining the specifics of the installation process and ensuring that only the necessary components are removed to avoid system damage. Ideally, the software manufacturer is best equipped to know the exact uninstallation process.

Products often come with automated uninstall routines. When these can operate without user intervention, they are the preferred choice. In scenarios where an automated routine isn’t available or needs augmentation, `opsi-script` can be used. This section provides an overview of the available options.

=== Using the Uninstallation Routine

If the product’s manufacturer supplies a program (or an MSI package) for uninstallation, first check whether it operates silently, without user interaction. If this is not the case, an AutoIt script can be used in combination with the uninstallation routine.

The call to the executable file can be placed in a `[WinBatch]` section within the `opsi-script` script:

[source,ini]
----
[WinBatch_start_ThunderbirdUninstall]
"%SystemRoot%\UninstallThunderbird.exe" /ma
----

NOTE: Even when a manufacturer provides a dedicated program for uninstalling their product, don’t assume it completely removes all components. Always verify on a test system to ensure the computer remains stable post-uninstallation and to check if any files or registry entries persist.

[[opsi-winclient-softwintegration-tutorial-deinstall-msi]]
=== Uninstalling MSI Products

When a product is distributed as an MSI package and installed via `msiexec`, it can typically be uninstalled using the same tool. Use `msiexec.exe` with the `/x` parameter, followed by the name of the MSI package or its GUID.

NOTE: Each MSI package has a unique, product-specific GUID that remains consistent across all installations. This ID can be found in the registry at `HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall`.

For silent uninstallation without user interaction, include the `/qb-!` parameter in your command:

[source,ini]
----
msiexec.exe /x some.msi /qb-! REBOOT=ReallySuppress
----

This is what the uninstallation looks like with a GUID:

[source,ini]
----
msiexec.exe /x {003C5074-EB37-4A75-AC4B-F5394E08B4DD} /qb-!
----

Each version of a product might have a unique GUID. To remove older versions, it’s important to pinpoint their respective GUIDs. A practical method involves using the `MsiName`, extracted by `opsi-setup-detector` from the MSI file.

This `MsiName` is listed as `DisplayName` in the registry's `Uninstall` section. Use the `MsiName` to search for the right GUID. Start by removing any details about the architecture and version at the end of `MsiName`. Then, encapsulate it with regular expressions:

[source,ini]
----
; Finding the MsiId by the Displayname from Registry:
; Be sure that the Displayname is set correctly:
Set $DisplayName$ = 'short msi name'
; escape all regex relevant chars with '\' : '\^$.|?*+()[{'
set $DisplayNameRegex$ = escapeRegexMetaChars($DisplayName$)
; '(?i)' = case insensitive ; '.*' = 0 or more of any thing
set $DisplayNameRegex$ = '(?i)'+$DisplayNameRegex$+'.*'
Set $UninstallList$ = getGuidListByDisplaynameRegex($DisplayNameRegex$)
;-----------------------------------------------------

; ---------------------------------------------------------------
comment "run the uninstallation "
; ----------------------------------------------------------------

if count($UninstallList$) int> "0"
	Comment "Uninstalling all found versions"
	for %uninstallEntry% in $UninstallList$ do Sub_Uninstallation_msi
endif

[Sub_Uninstallation_msi]
set $MsiVersion$ = TakeString(0, splitstring('%uninstallEntry%', "="))
set $MsiId$ = TakeString(1, splitstring('%uninstallEntry%', "="))

if stringtobool(checkForMsiProduct($MsiId$))
	Message "Uninstalling :"  + $ProductId$ + " " + $MsiVersion$+ "..."
	Winbatch_Uninstall_1
	Set $ExitCode$ = getlastexitcode
	if stringtobool(isMsiExitcodeFatal($ExitCode$, "true", $ErrorString$ ))
		LogError $ErrorString$
		isfatalerror $ErrorString$
	else
		Comment $ErrorString$
	endif
else
	Comment "No previously installed " + $ProductId$ + " version found"
endif
----

In this script segment, the following actions are performed:

* `Set $DisplayName$ = 'short msi name'`: The variable `$DisplayName$` is assigned the truncated `MsiName`, omitting any additional details like version or architecture.

* `set $DisplayNameRegex$ = escapeRegexMetaChars($DisplayName$)`: This line prepares `$DisplayName$` for a regex search, effectively escaping any special characters in the string.

* `set $DisplayNameRegex$ = '(?i)'+$DisplayNameRegex$+'.*'`: This regex pattern is set to be case-insensitive (`?i`) and designed to match the beginning of a string, followed by any sequence of characters, essentially accommodating any additional details following the base name.

* `Set $UninstallList$ = getGuidListByDisplaynameRegex($DisplayNameRegex$)`: The script then uses the `getGuidListByDisplaynameRegex` function, part of the `osd-lib.opsiscript` library, to scour the registry. It compiles a list matching the criteria, formatted as `<MsiVersion> = <msi GUID>`.

* `[Sub_Uninstallation_msi]`: Finally, this section utilizes the retrieved GUID for the uninstallation process.

If these techniques fall short or are partially successful, the next section discusses an alternative approach using an `opsi-script` script.

=== *opsi-script* Useful Commands for Uninstalling

When uninstalling a product that was installed using `opsi-script` functions or if a manufacturer's uninstall routine isn't available, creating a custom uninstall script is a viable solution.

`opsi-script` provides a variety of functions to aid in creating an effective uninstallation process. A comprehensive explanation of these functions and their parameters can be found in the xref:opsi-script-manual:opsi-script-manual.adoc[opsi-script Reference].

For basic scenarios, you can use a `Files` section to remove specific files with the following command:

[source,ini]
----
delete -f <file>
----

To delete a directory with subdirectories, use this command:

[source,ini]
----
delete -sf <directory>\
----

The parameter `f` indicates a forced deletion of the file, even if it is write-protected. The `s` parameter includes subdirectories and operates recursively.

Use the `/AllNTUserProfiles` parameter if you need to delete a file or directory from all user profiles.

When you need to remove a directory tree containing files marked as "hidden" or as "system files", consider using the `rmdir` command. This can be executed via a `ShellScript` section:

[source,ini]
----
[ShellScript_deleteDir]
rmdir /S /Q "<directory>"
----

Sometimes a running process must be terminated before deletion. In this case, find out the name (e.g. via the task manager) and pass it to the `opsi-script` command `KillTask`:

[source,ini]
----
KillTask "thunderbird.exe"
----

If a product (or parts of it) operates as a service, you need to stop this service before uninstallation. You can deactivate the service in the registry and restart the computer, or use the system command `net` with the `stop` parameter. This stops the service instantly, deleting the associated files without a restart:

[source,ini]
----
net stop <service>
----

WARNING: Extra caution is necessary when removing `.dll` files that may still be in use by other programs. These files need to be dealt with on a case-by-case basis, and unfortunately, we can't offer universal guidance for this situation.

To remove specific entries from the registry using `opsi-script`, use the `DeleteVar` command. This command is placed within a `Registry` section of an `opsi-script` and it removes entries from the currently open key:

[source,ini]
----
DeleteVar <VarName>
----

To delete a registry key with all subkeys and registry variables, you can use the command `DeleteKey`:

[source,ini]
----
DeleteKey [HKLM\Software\Macromedia]
----

[[opsi-winclient-softwintegration-tutorial-64bit]]
== 64 Bit Support

`opsi-script` is a 32 bit application. Scripts designed for installing 32 bit software typically function properly on 64 bit systems as well. However, when it comes to installing 64 bit software using `opsi-script` or working with 64 bit systems in general, please consult the chapter xref:opsi-script-manual:64bit.adoc[64 Bit Support].
