



[[firststeps-software-deployment-product-tests-configed]]
=== Deploying opsi standard products: opsi-configed

One of the opsi standard products is the product _opsi-configed_, which installs the opsi Management Interface. This Application is a Java application, therefore a Java Runtime Engine is bundled with the product.

Using _opsi-configed_, in the mode _Configuration of clients_, choose the appropriate client in the tab _Clients_.

If you have not already done so, update the data of _opsi-configed_ by using _File / Reload all data_ or click the reload icon.

Switch to the tab _Product configuration_, look for the line with the product `opsi-configed`. Click in the column _Requested Action_, and select the action _setup_.

The check mark in the icon menu bar should change its color to red. If you click on it, the new settings will be transmitted to the {opsi-Server}, afterwards its color will be green again.

Reboot the client.
The opsi-client-agent should start and install the product _opsi-configed_.
After the installation you can find _opsi-configed_ in the _start menu_.
