////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      21.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-getting-started-firststeps-software-deployment-client-integration-installer]]
==== Using the installer

. Logon to the client.
. Download the installer from your configserver. It is located at https://<fqdn_or_ip_of_the_configserver>:4447/public/opsi-client-agent/ and has the file name
opsi-client-agent-installer.exe (or opsi-linux-client-agent-installer.run/opsi-mac-client-agent-installer.command)
. Execute the installer (for linux and macos this must be done with root-rights, on windows a UAC-Request may be displayed)
. The installer will extract itself into a temporary local directory and start the oca-installation-helper, which shows a user interface with input fields for
Client-ID, Opsi Service URL, Username and Password. The fields are pre-filled, but you may need to add or change some of the data.
. Client-Id should be the fqdn of the Client. Opsi Service url should have the format https://<fqdn_or_ip_of_the_configserver>:4447. Username and Password should correspond
to a user of the group opsiadmin in case of a first installation. For reinstallation it is also possible to use Client-Id and pckey for authentication.
. The installer connects to the server to register the client at the server. Afterwards the installer calls the included opsi-script to execute the setup.opsiscript of the opsi-[linux-|mac-]client-agent.

When calling the installer, you can supply parameters which enable a fully automatic execution of the installation. Details can be found in
ifeval::["{mode}" == "antora"]
xref:clients:windows-client/windows-client-agent.adoc#opsi-manual-clientagent-manual-installation[opsi manual]
endif::[]
ifeval::["{mode}"!= "antora"]
link:https://download.uib.de/4.2/documentation/html/en/opsi-manual-v4.2/opsi-manual-v4.2.html#opsi-manual-clientagent-subsequent-installation[opsi manual]
endif::[]