[[opsi-getting-started-firststeps-software-deployment-client-integration]]
=== Integration of existing clients

To include existing clients in opsi, the {opsi-client-agent} (or opsi-linux-client-agent/opsi-mac-client-agent) must be installed on them.
This can be realised in several ways. After you have installed the {opsi-client-agent} as described below, the client will also appear in the client list of {opsi-configed}, unless you have already added the client there.

[[opsi-getting-started-firststeps-software-deployment-client-integration-installer]]
Basically there is the possibility to install the agent <<opsi-getting-started-firststeps-software-deployment-client-integration-installer,on the client>> or <<opsi-getting-started-firststeps-software-deployment-client-integration-opsi-deploy,to start the installation from the server>>.

Executing the installation directly on the client is suitable for individual computers.
For a mass rollout of the agent, have a look at <<opsi-getting-started-firststeps-software-deployment-client-integration-opsi-deploy,opsi-deploy-client-agent>>.
If there is already another way to distribute software available, then it is also possible to distribute the opsi-client-agent through it and execute the script `silent_setup.cmd` included in the package.

Once the agent is installed, available opsi products can be xref:rollout-products.adoc#opsi-getting-started-firststeps-software-deployment-product-tests[installed] on these clients.


[[opsi-getting-started-firststeps-software-deployment-client-integration-installer]]
=== Using the installer

. Logon to the client.
. Download the installer from your configserver. It is located at https://<fqdn_or_ip_of_the_configserver>:4447/public/opsi-client-agent/ and has the file name +
opsi-client-agent-installer.exe (or opsi-linux-client-agent-installer.sh/opsi-mac-client-agent-installer.sh)
. Execute the installer (for linux and macos this must be done with root-rights, on windows a UAC-Request may be displayed)
. The installer will extract itself into a temporary local directory and start the oca-installation-helper, which shows a user interface with input fields for +
client-Id, Opsi Service url, Username and Password. The fields are pre-filled, but you may need to add or change some of the data.
. Client-Id should be the fqdn of the Client. Opsi Service url should have the format https://<fqdn_or_ip_of_the_configserver>:4447. Username and Password should correspond +
to a user of the group opsiadmin in case of a first installation. For reinstallation it is also possible to use client-Id and pckey for authentication.
. The installer connects to the server to create the client in the backend and to retrieve the pckey. Afterwards the installer calls the included opsi-script to execute the setup.opsiscript of the opsi-[linux-|mac-]client-agent.

When calling the installer, you can supply parameters which enable a fully automatic execution of the installation. Details can be found in the Manual.

[[opsi-getting-started-firststeps-software-deployment-client-integration-opsi-deploy]]
=== Using opsi-deploy-client-agent

The `opsi-deploy-client-agent` program installs the {opsi-client-agent} (or opsi-linux-client-agent/opsi-mac-client-agent) directly from the {opsi-server} on the clients.
This makes it easy to integrate a large number of clients from a server into an opsi environment.

Requirements for Windows clients:

* an open C$ share
* an open admin$ share
* an administrative account
* `winexe` must not be blocked by an antivirus program.
* The program `winexe` must be available on the server. It is part of the `opsi-windows-support` package.

Requirements for Linux clients:

* ssh-access with a user that can perform "sudo" or is root itself.

The `opsi-deploy-client-agent` program can be found at `/var/lib/opsi/depot/opsi-client-agent` (or opsi-linux-client-agent, opsi-mac-client-agent). +
Execute the script with 'root' privileges.

The program creates the client on the server, then copies the installation files and the configuration information, including the pckey, to the client. After copying the necessary information, `opsi-deploy-client-agent` starts the installation on the client by calling oca-installation-helper (non-interactive).

There are two ways to copy the installation files for windows clients.
The first method will use the 'mount'-command on the server to mount the C$ share of the client, and copy the files to the share for installation.
The second variant will use 'smbclient'-command on the server for mounting C$ share of the client, and copy the files to the share for installation.

With the `opsi-deploy-client-agent` you can also install to a list of clients.
To do this, either any number of clients can be passed as the last parameter or the clients can be read from a file using the '-f' option.
When using a file, there must be a client on every line.

The program can work with IP addresses, hostnames or FQDNs. It will try to automatically detect what type of address it is processing.

Possible parameters can be found by using `--help`:
[source,prompt]
----
usage: opsi-deploy-client-agent [-h] [--version] [--verbose] [--debug-file DEBUG_FILE] [--username USERNAME]
                                [--password PASSWORD] [--use-fqdn | --use-hostname | --use-ip-address]
                                [--ignore-failed-ping]
                                [--reboot | --shutdown | --start-opsiclientd | --no-start-opsiclientd]
                                [--hosts-from-file HOST_FILE] [--skip-existing-clients] [--threads MAX_THREADS]
                                [--install-timeout INSTALL_TIMEOUT] [--depot DEPOT] [--group GROUP] [--smbclient | --mount]
                                [--keep-client-on-failure | --remove-client-on-failure]
                                [--failed-clients-file FAILED_CLIENTS_FILE]
                                [host [host ...]]

Deploy opsi client agent to the specified clients. The c$ and admin$ must be accessible on every client. Simple File Sharing
(Folder Options) should be disabled on the Windows machine.

positional arguments:
  host                  The hosts to deploy the opsi-client-agent to.

optional arguments:
  -h, --help            show this help message and exit
  --version, -V         show program's version number and exit
  --verbose, -v         increase verbosity (can be used multiple times)
  --debug-file DEBUG_FILE
                        Write debug output to given file.
  --username USERNAME, -u USERNAME
                        username for authentication (default: Administrator).Example for a domain account: -u
                        <DOMAIN>\\<username>
  --password PASSWORD, -p PASSWORD
                        password for authentication
  --use-fqdn, -c        Use FQDN to connect to client.
  --use-hostname        Use hostname to connect to client.
  --use-ip-address      Use IP address to connect to client.
  --ignore-failed-ping, -x
                        try installation even if ping fails
  --reboot, -r          reboot computer after installation
  --shutdown, -s        shutdown computer after installation
  --start-opsiclientd, -o
                        Start opsiclientd service after installation without performing Events (default).
  --no-start-opsiclientd
                        Do not start opsiclientd service after installation (deprecated).
  --hosts-from-file HOST_FILE, -f HOST_FILE
                        File containing addresses of hosts (one per line). If there is a space followed by text after the
                        address this will be used as client description for new clients.
  --skip-existing-clients, -S
                        skip known opsi clients
  --threads MAX_THREADS, -t MAX_THREADS
                        number of concurrent deployment threads
  --install-timeout INSTALL_TIMEOUT
                        timeout for single threads (default is unlimited)
  --depot DEPOT         Assign new clients to the given depot.
  --group GROUP         Assign fresh clients to an already existing group.
  --smbclient           Mount the client's C$-share via smbclient.
  --mount               Mount the client's C$-share via normal mount on the server for copying the files.This imitates the
                        behaviour of the 'old' script.
  --keep-client-on-failure
                        If the client was created in opsi through this script it will not be removed in case of failure.
                        (DEFAULT)
  --remove-client-on-failure
                        If the client was created in opsi through this script it will be removed in case of failure.
  --failed-clients-file FAILED_CLIENTS_FILE
                        filename to store list of failed clients in
----
