////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the German creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype:   book
:icons: font
:xrefstyle: full
:chapter-label:
:gstarted:  getting started
:release:   stable


[[firststeps-software-deployment-configed]]
== Management interface opsi-configed

Opsi offers with the opsi-configed a comfortable management interface.
It communicates via HTTPS with the opsi server and can therefore be used on any computer that can establish a corresponding connection.


TIP: When using a virtual machine, make sure that the virtual screen has a large enough resolution.
For opsi-configed a minimum resolution of 1024x768 pixels is required.
To improve the graphics and mouse driver integration at a higher resolution, it is helpful to install the 'VMware Tools' on a VMware machine or the virtual guest additions on a VirtualBox machine.


[[firststeps-software-deployment-configed-installation]]
=== Installation of the management interface opsi-configed

The management interface is installed as a local application on the administration PCs.
In your web browser, go to the address `https://<opsidepotserver>:4447/`.
There you will find links to installers for different operating systems.

Alternatively, you can find corresponding installers under link:https://download.uib.de/opsi4.2/misc/helper/[].

IMPORTANT: The Windows installer must be executed with administrative rights.
To do this, right click to open the context menu of the installer and then select 'Run as administrator'.

Once one PC is equipped with the management interface, further PCs can have easily have the interface xref:clients:windows-client/rollout-products.adoc#firststeps-software-deployment-product-tests-configed[] installed with the localboot product *opsi-configed*, as long as the xref:clients:windows-client/windows-client-agent.adoc#firststeps-adding-clients[opsi agent] is already installed on the PC.


[[firststeps-software-deployment-configed-start]]
=== Start of the management interface opsi-configed

Start opsi-configed via the shortcut in your Start menu.

Log in as a user who is a member of the group opsiadmin.

The operation of the management interface is pretty much self explanatory.
You will find detailed instructions in the opsi manual.

NOTE: Changes in the opsi management interface must be saved before they take effect and changes in the data must be retrieved from the server via the 'Reload data' button.
