////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      28.03.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-winclient-softwintegration]]
= Integrating custom Software

The installation of software using opsi is managed either by the xref:clients:windows-client/windows-client-agent.adoc[Client Agent] or the setup program xref:opsi-script-manual:opsi-script-manual.adoc[*opsi-script*]. When packaging your own software for deployment through opsi, it's necessary to create an `opsi-script` script for each product. This script, along with the installation files and metadata, should be packed. As a result, you'll get an opsi product which is then installed on the opsi server (see the chapter xref:clients:windows-client/minimal-products.adoc[Adding Products (opsi Server)]).

[[opsi-winclient-softwintegration-tutorial]]
== Tutorial: Creating an *opsi-script* Script

include::common:partial$softwintegration-tutorial-introduction.adoc[]

[[opsi-winclient-softwintegration-tutorial-general]]
=== Non-interactive software installation (Windows)

Basically, there are three different ways to integrate a software package into the automatic software distribution for Windows operating systems. Additionally, there's a variant that uses the link:https://learn.microsoft.com/en-us/windows/win32/msi/windows-installer-portal[Windows Installer] service:

* *Unattended*/*Silent Setup*: +
This approach involves using the original setup program and configuring it for non-interactive mode via command line parameters. A notable example is the silent installation of an MSI package using the `/quiet` option of the link:https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/msiexec[*msiexec*] tool.

* *Interactive Setup with recorded Answers*: +
Begin by running the original setup program once to observe the window titles and the sequence of questions and responses during the setup. Record these details in a script. During software distribution, an automation tool such as link:https://www.autoitscript.com/site/[AutoIt] or link:https://www.autohotkey.com/[AutoHotkey] interacts with the setup program as dictated by the script.

* *Recreate Setup Routine with `opsi-script`*: +
While the original setup program is active, use a tool like link:https://learn.microsoft.com/en-us/sysinternals/downloads/procmon[Process Monitor/Procmon] to log all system changes. You then craft the `opsi-script` script based on the logged data and the changes you’ve recorded.

NOTE: opsi supports all three variants. In practice, a combination of several methods is often used.

include::common:partial$softwintegration-tutorial-script-structure-opsi-script-basics.adoc[]

[[opsi-winclient-softwintegration-tutorial-windows-special-commands]]
===== Special Commands for Windows

* `GetOS`: This function retrieves the operating system type. It returns values such as `Linux`, `Windows_NT` (covering Windows NT through Windows 11), or `macOS`.

* `GetMsVersionInfo`: This function provides detailed information about the internal Windows version. For instance, Windows 7 is identified as "6.1", while Windows 11 is recognized as "10.0", etc.

* `GetMsVersionName`: This function returns the commercial version name of a Windows system. For example, Windows 7 returns "7.0", and Windows 11 returns "11.0", and so on.

* `getMSVersionMap`: This function locally queries the operating system information and records it into a string list.

TIP: For more comprehensive details about these string functions, refer to the section xref:opsi-script-manual:prim-section.adoc#opsi-script-string-functions-os[String Functions which return the OS Type].

[[opsi-winclient-softwintegration-tutorial-template]]
== Example: Windows Template *opsi-template*

You can create this template with the `opsi-setup-detector` tool (see the section <<opsi-winclient-softwintegration-tutorial-create-with-opsi-setup-detector>>).

// include docu: actual template for windows
include::common:partial$firststeps-opsi-template-win.adoc[]

[[opsi-client-softwintegration-create-opsi-package]]
== Creating opsi Products

The following sections outline the steps for packaging software, specifically for creating opsi products. The fundamental process involves:

1. Creating the basic framework of a package using the `opsi-setup-detector` (refer to section <<opsi-winclient-softwintegration-tutorial-create-with-opsi-setup-detector>>).
2. Testing the `opsi-script` script (see section <<opsi-softwintegration-tutorial-create-and-test-script>>).
3. Using the opsi PackageBuilder (oPB) to transform the initial form into a complete opsi package, which is then stored on the opsi server.

// include docu: opsi-setup-detector installation
include::common:partial$setup-detector-installation.adoc[]

// include docu: opsi-logviewer installation
include::common:partial$opsi-logviewer-installation.adoc[]

[[opsi-winclient-softwintegration-tutorial-create-with-opsi-setup-detector]]
== *opsi-setup-detector*: Creating a Script

The following sections explain in detail how to use the `opsi-setup-detector` to analyze a setup file and create an opsi product.

// include docu: opsi-setup-detector
include::common:partial$setup-detector-use-start.adoc[]

// include docu: Windows specific tasks in opsi-setup-detector
include::common:partial$osd-tasks-windows.adoc[]

// include docu: how to use the opsi-setup-detector
include::common:partial$osd-task-use-single-analyze-and-create.adoc[]

// include docu: The modify and test cycle
include::common:partial$softwintegration-tutorial-modify-test-cycle.adoc[]

[[opsi-winclient-softwintegration-tutorial-template-details]]
== Advanced Configuration with *opsi-setup-detector*

In the upcoming sections, we'll explore additional configuration features of the `opsi-setup-detector`. These include using a custom directory, installing from a local temporary directory, managing license keys, and personalizing user profiles and desktop icons.

// include docu: OSD Checkboxes for additional code
include::common:partial$osd-checkboxes-subtasks.adoc[]

[[opsi-winclient-softwintegration-tutorial-opsiadmin]]
== Installation When the User is Logged on

Before we begin, we assume that you have tried an unattended installation using an opsi-script script, and the installation worked OK when the user had administrative privileges.
However with some software products, you will see that the installation fails when started from within the opsi deployment software (opsi-client-agent). A possible reason for that difference might be that the installation process requires knowledge about the user environment or profile.


[[opsi-winclient-softwintegration-tutorial-customizing]]
== Customization after a silent/unattended Installation

After a successful silent installation, some customizing might be useful. The opsi-script is a powerful tool to do that job. First, find out what patches have to be applied. For example, that could mean analyzing which registry settings are affected by the GUI customizing tools.


You may use the tools like: +

* link:http://www.sysinternals.com/[sysinternals]
* link:https://sourceforge.net/projects/regshot/[regshot]


[[opsi-winclient-softwintegration-tutorial-autoit]]
== Integration with Automated Answers for the setup Program

Another fast way of integration is to provide an automated answer file for the setup process. The answer file contains pre-defined answers.  To be more precise, the answer file is used by a control tool, which waits for the setup to come up with the interactive windows.  The control tool then passes input to these windows as defined in the answer file. As a control tool we recommend 'AutoIt'. The AutoIt program and the documentation can be found at: +

* link:http://www.autoitscript.com[AutoIt]

=== AutoIt: Control the setup process

AutoIt provides a lot of commands to control the setup process. Also, several error states can be handled (if known in advance) with the '[ADLIB]' section in the script.

There is, however, a fundamental challenge in using AutoIt: +
The AutoIt script must provide input for every window that might pop up during installation. So if any unexpected window pops up, which isn't handled in the [ADLIB] section, AutoIt provides no input for this window and the installation stops at that point while waiting for input. This input could be done interactively by a user, and then the script can take over again and handle the next windows.

Another situation that may cause failure of an AutoIt installation: +
The user can interfere with the installation if the mouse and keyboard are not disabled. Therefore we regard 'unattended' or 'silent' setup as a more stable solution.

A combination of both might do a good job: +
The 'silent'-setup does the main installation and the AutoIt script handles special conditions that might occur.

=== AutoIt: Known problems

If you use the opsi option of running the installation on another desktop than the current desktop, or if the current desktop is locked, then you will find that some autoit functions do not work properly under these conditions.

Therefore you should avoid using the following autoit commands in 'opsi-script' scripts:

* winwait()

* winactivate()

* Send()

These are the most widly used commands.

We recommend to use  the `opsi-autoit-lib.au3` library, that provides replacements for this commands. You will find this file at  `C:\Program Files (x86)\opsi.org\opsi-client-agent\opsi-script\lib\opsi-autoit-lib.au3`. Copy this file to the scriptdirectory of your opsi product. Now you may include this file by using the following autoit code line:

[source]
----
#include "%scriptpath%\opsi-autoit-lib.au3
----


This library provide substitutes:

*winwait()* +
should be replaced by the function +
`opsiwinwait($title, $text, $maxseconds, $logname)` +


*Send()* +
should be replaced by the function +
`opsiControlClick($title, $text, $id, $maxseconds, $logname)` +
respectively by +
`opsiControlSetText($title, $text, $id,$sendtext, $maxseconds, $logname)` +


TIP: It is always a good idea for the identification of controls to use the program `Au3info.exe` to get the 'ControlId' needed by these commands. Please use the numerical 'ControlId', because the other variants do not seem to work properly.

=== AutoIT: Examples and additional Links

Examples you will find in the directory: `C:\Program Files (x86)\opsi.org\opsi-client-agent\opsi-script\lib\` in the files: + 

  - `autoit_example_1.txt`

  - `autoit_example_2.txt`
  
  - `autoit_example_3.txt`


see also: +
http://www.autoitscript.com/wiki/FAQ#Why_doesn.27t_my_script_work_on_a_locked_workstation.3F +
http://www.autoitscript.com/autoit3/docs/ +
http://www.autoitscript.com/autoit3/docs/intro/controls.htm +
http://www.autoitscript.com/autoit3/docs/functions.htm


[[opsi-winclient-softwintegration-tutorial-analyse-and-repackage]]
== Analyze and Repackage

When a software developer builds a setup for deployment, the developer usually knows about the required components of the software that have to be installed. But if somebody has a black box as a setup, then they need first to analyze what the setup does. This can be done by monitoring the setup activities with the appropriate tools (e.g. monitoring files and registry access) or by comparing the system states before and after installation.

To analyze the before or after states, there are several tools. For Example:


* link:https://sourceforge.net/projects/regshot/files/regshot/[regshot]

* link:http://www.itninja.com/media/downloads/appdeploy-repackager.msi[appdeploy-repackager]


[[opsi-winclient-softwintegration-tutorial-deinstall]]
== How to uninstall Products

To uninstall a software product from a computer, you need an 'uninstall' script to perform the deletion. The fundamental difficulty in software deletion is deciding what exactly has to be removed. Not all of the files that came with a software package can be deleted afterwards. Sometimes a package comes with standard modules that are also referred to by other programs. Often only the software manufacturer himself knows what parts have to be removed. The manufacturer's setup might offer an unattended uninstall option which can be embedded in the opsi uninstall script. Otherwise opsi-script provides several commands for software deletion:

=== Using an uninstall routine
If the product manufacturer provides an option for software deletion, you must checked whether or not it can be run unattended (or in silent mode). If it requires some user interaction, an AutoIt script combined with the uninstall routine might do the job. The uninstall statement can be embedded in a [WinBatch] section of the opsi-script script:
[source,winst]
----
[WinBatch_start_ThunderbirdUninstall]
"%SystemRoot%\UninstallThunderbird.exe" /ma
----

When using an uninstall program, always run a test to see if all of the files have been deleted and the computer is still in a stable state.

If none of these methods are available or sufficient, the uninstall can be done using a opsi-script script as described below:


[[opsi-winclient-softwintegration-tutorial-deinstall-msi]]
==== How to uninstall MSI Products

Products that are installed by MSI normally come with an uninstall option, which is usually the program `msiexec.exe` combined with the parameter `/x`. The parameter `/qb-!` is for the unattended mode (or without user interaction). +
In order to identify the software ro uninstall, you have to use the GUID (Global Unique ID) with `msiexec.exe`. This GUID identifies the product in the system. It comes from the msi file and will used for the 'uninstall entry' in the registry:
'HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall'

A request using the GUID looks like this:
[source,winst]
----
msiexec.exe /x {003C5074-EB37-4A75-AC4B-F5394E08B4DD} /qb-!
----

The GUID may change from release to release. So the problem is to get the correct GUID of the software you want to uninstall. +
One way to solve this problem is to use the `MsiName` which the opsi-setup-detector can read from the msi file. This `MsiName` is used as `DisplayName` entry in the uninstall registry entry mentioned above.
The uninstall scripts produced by the opsi-setup-detector use this `MsiName` to get the GUIDs of the installed software we want to uninstall. +
Therefore you may have to cut trailing information about architecture or version from the `MsiName` before we use it for a regular expression search in the uninstall entries in the registry.

This is what the opsi-setup-detector produces as msi uninstall code for you:

[source,winst]
----
; Finding the MsiId by the Displayname from Registry:
; Be sure that the Displayname is set correctly:
Set $DisplayName$ = 'short msi name'
; escape all regex relevant chars with '\' : '\^$.|?*+()[{'
set $DisplayNameRegex$ = escapeRegexMetaChars($DisplayName$)
; '(?i)' = case insensitive ; '.*' = 0 or more of any thing
set $DisplayNameRegex$ = '(?i)'+$DisplayNameRegex$+'.*'
Set $UninstallList$ = getGuidListByDisplaynameRegex($DisplayNameRegex$)
;-----------------------------------------------------

; ---------------------------------------------------------------
comment "run the uninstallation "
; ----------------------------------------------------------------

if count($UninstallList$) int> "0"
	Comment "Uninstalling all found versions"
	for %uninstallEntry% in $UninstallList$ do Sub_Uninstallation_msi
endif

[Sub_Uninstallation_msi]
set $MsiVersion$ = TakeString(0, splitstring('%uninstallEntry%', "="))
set $MsiId$ = TakeString(1, splitstring('%uninstallEntry%', "="))

if stringtobool(checkForMsiProduct($MsiId$))
	Message "Uninstalling :"  + $ProductId$ + " " + $MsiVersion$+ "..."
	Winbatch_Uninstall_1
	Set $ExitCode$ = getlastexitcode
	if stringtobool(isMsiExitcodeFatal($ExitCode$, "true", $ErrorString$ ))
		LogError $ErrorString$
		isfatalerror $ErrorString$
	else
		Comment $ErrorString$
	endif
else
	Comment "No previously installed " + $ProductId$ + " version found"
endif
----

Short description about this script part:

* `Set $DisplayName$ = 'short msi name'` +
Set the displayname with cut trailing information.

* prepare the displayname as regular expression search string: +
Mask all regular expression relevant chars: +
`set $DisplayNameRegex$ = escapeRegexMetaChars($DisplayName$)` +
Tell that we search for search string at the start of the line with 0 or more of any chars behind the search string. +
`set $DisplayNameRegex$ = '(?i)'+$DisplayNameRegex$+'.*'`

* search in the registry: +
`Set $UninstallList$ = getGuidListByDisplaynameRegex($DisplayNameRegex$)` +
The function getGuidListByDisplaynameRegex comes from the osd-lib.opsiscript and creates a list of matching entries in the format: +
<MsiVersion> = <msi GUID> 

* do the uninstall:
Now we can iterate throug the list and use the found GUIDs to uninstall the software. This is done in the section `[Sub_Uninstallation_msi]`

=== Useful opsi-script commands for uninstall

If a product has been installed by opsi-script functions, or if there is no uninstall routine for the product, the complete uninstall has to be done by a opsi-script script. opsi-script comes with some powerful uninstall functions. This chapter provides a brief overview of the uninstall functions, and more detailed information can be found in the opsi-script handbook.

Basic uninstall means deleting one or more files from the file system. This command can be executed from a opsi-script files section:
[source,winst]
----
delete -f <file name>
----

or to delete a directory including sub directories:

[source,winst]
----
delete -sf <dir name>\
----

The parameter 'f' means 'force' or to delete the files even if they are marked as 'read only' and the parameter 's' means including the 'subdirectories'. A file or directory can be deleted from all user profiles using the option '/AllNTUserProfiles' (see opsi-script manual for details).

Directories containing files with the attribute 'hidden' or 'system' can be deleted by using a 'ShellScript'-section:

[source,winst]
----
[ShellScript_deleteDir]
rmdir /S /Q "<List>"
----

To stop a running process before deletion use the `killtask` command with the process' name (look at the task manager for process name):

[source,winst]
----
KillTask "thunderbird.exe"
----

If the product or part of it, runs as a service, you will have to stop the service before deleting the files. One way to do so, is to set the service state to inactive in the registry and restart the computer. Or to stop the service by using the command 'net stop', which doesn't need a reboot:
[source,winst]
----
net stop <servicename>
----

Deleting DLL files also requires special attention, since DLLs could also be used by other products. There is no general way of handling this.

To delete registry entries with opsi-script you can use the command DeleteVar. This command deletes entries from the currently open key:

[source,winst]
----
DeleteVar <VarName>
----

To delete a registry key with all sub keys and registry variables, you can use the opsi-script command DeleteKey:
[source,winst]
----
DeleteKey [HKLM\Software\Macromedia]
----


[[opsi-winclient-softwintegration-tutorial-64bit]]
== Known Issues with the 64 Bit Support

The opsi installer {opsi-script} is a 32 bit program. There are no known problems when installing 32 bit software on a 64 bit system using {opsi-script}. For the installation of 64 bit software with {opsi-script} and how to handle Windows 64-Bit please have a look at the special chapter in the link:https://docs.opsi.org/opsi-docs-en/stable/opsi-script-manual/64bit.html[opsi-script manual, 64 Bit Support on Windows].
