[[firststeps-software-deployment-client-integration]]
=== Integration of existing Windows clients

To include existing Windows clients in opsi, the {opsi-client-agent} must be installed on them.
This can be realised in several ways. After you have installed the {opsi-client-agent} as described below, the client will also appear in the client list of {opsi-configed}, unless you have already added the client there.

[[firststeps-software-deployment-client-integration-service-setup]]
Basically there is the possibility to install the agent <<firststeps-software-deployment-client-integration-oca-installer,on the client>> or <<firststeps-software-deployment-client-integration-opsi-deploy,to start the installation from the server>>.

Executing the installation directly on the client is suitable for individual computers.
For a mass rollout of the agent, have a look at <<firststeps-software-deployment-client-integration-opsi-deploy,opsi-deploy-client-agent>>.
If there is already another way to distribute software available, then it is also possible to distribute the {opsi-client-agent} through it and execute the script `silent_setup.cmd` included in the package.

Once the agent is installed, available opsi products can be <<firststeps-software-deployment-product-tests,installed>> on these clients.


[[firststeps-software-deployment-client-integration-oca-installer]]
==== Using the opsi-client-agent-installer


include::common:partial$firststeps-oca-installer.adoc[]

The subsequent described methods: service_setup / silent_setup are only for backward compatibility to
opsi 4.1 and the corresponding {opsi-client-agent} versions 4.1. Please use as possible
<<firststeps-software-deployment-client-integration-oca-installer,the {opsi-client-agent} Installer>>.

[[firststeps-software-deployment-client-integration-service-setup_nt6]]
==== Using service_setup.cmd on Windows NT6 (outdated)

The method described over here is only for backward compatibility to
opsi 4.1 and the corresponding {opsi-client-agent} versions 4.1. Please use as possible
<<firststeps-software-deployment-client-integration-oca-installer,the {opsi-client-agent} Installer>>.


. Logon to the Windows client with administrative privileges.
. Mount the share `\\<opsiserver>\opsi_depot` on a drive letter.
. On the drive from the previous step, start the script `opsi-client-agent\service_setup.cmd` +
Do not start the script elevated (via right mouse click: 'as Administrator') because an elevated script has no access to the network share.
. The script copies the needed files to a temporary local directory and starts from there the {opsi-script} (opsi-script.exe) elevated in order to do the installation. This may cause an UAC Message at this point.
. The script connects to the server via the opsi webservice in order to create the client on the serverside and to retrieve the pckey. This is tried first with the user and password provided in config.ini. If the connection fails, a login window will appear, with the Service-URL ({opsi-configserver}), and user and password. The user required here needs to be a member of the group 'opsiadmin'. It is also possible to use a user which only has rights to call the method `host_createOpsiClient`.

WARNING: After installation the client reboots without notice.

////
[[firststeps-software-deployment-client-integration-service-setup_nt5]]
==== Using service_setup_NT5.cmd on Windows NT5

. Logon to the Windows client with administrative privileges.
. Mount the share `\\<opsiserver>\opsi_depot` on a drive letter.
. On the drive from the previous step, start the script `opsi-client-agent\service_setup_NT5.cmd`
. The script copies the needed files to a temporary local directory and starts from there the {opsi-script} (winst32.exe) in order to do the installation.
. The script connects to the server via the opsi webservice in order to create the client on the serverside and to retrieve the pckey. This is tried first with the user and password provided in config.ini. If the connection fails, a login window will appear, with the Service-URL ({opsi-configserver}), and user and password. The user required here needs to be a member of the group 'opsiadmin'.

WARNING: After installation the client reboots without notice.
////



[[firststeps-software-deployment-client-integration-opsi-deploy]]
==== Using opsi-deploy-client-agent

The `opsi-deploy-client-agent` script installs the {opsi-client-agent} directly from the {opsi-server} on the clients. This makes it easy to integrate a large number of clients from a server into an opsi environment.

Requirements for the clients are:

* an open C$ share
* an open admin$ share
* an administrative account
* Running services RpcSs and RpcEptMapper (enabled for win8 and later by default)
* Firewall permitting "file and printer sharing" and "windows management instrumentation (WMI)"
* Registry key HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\LocalAccountTokenFilterPolicy should have value 1

The `opsi-deploy-client-agent` script can be found at `/var/lib/opsi/depot/opsi-client-agent` +
Execute the script with 'root' privileges or as a user being part of the "opsifileadmins" group.
If the script is not executable, you can solve this issue by executing the following command: +
`opsi-set-rights /var/lib/opsi/depot/opsi-client-agent/opsi-deploy-client-agent`.

The script creates the client on the server, then copies the installation files and the configuration information, including the pckey, to the client.  After copying the necessary information, `opsi-deploy-client-agent` starts the installation on the client.

There are two ways to copy the installation files.
The first method will use the 'mount'-command on the server to mount the C$ share of the client, and copy the files to the share for installation.
The second variant will use 'smbclient'-command on the server for mounting C$ share of the client, and copy the files to the share for installation.

With the `opsi-deploy-client-agent` script you can also install to a list of clients.
To do this, either any number of clients can be passed as the last parameter or the clients can be read from a file using the '-f' option.
When using a file, there must be a client on every line.

The script can work with IP addresses, hostnames or FQDNs. It will try to automatically detect what type of address it is processing.

Possible parameters can be found by using `--help`:

[source,prompt]
----
opsi_server:/home/user# cd /var/lib/opsi/depot/opsi-client-agent
opsi_server:/var/lib/opsi/depot/opsi-linux-client-agent# ./opsi-deploy-client-agent --help

usage: opsi-deploy-client-agent [-h] [--version] [--verbose]
                                [--debug-file DEBUGFILE] [--username USERNAME]
                                [--password PASSWORD]
                                [--use-fqdn | --use-hostname | --use-ip-address]
                                [--ignore-failed-ping]
                                [--reboot | --shutdown | --start-opsiclientd | --no-start-opsiclientd]
                                [--hosts-from-file HOSTFILE]
                                [--skip-existing-clients]
                                [--threads MAXTHREADS] [--depot DEPOT]
                                [--group GROUP] [--smbclient | --mount]
                                [--keep-client-on-failure | --remove-client-on-failure]
                                [host [host ...]]

Deploy opsi client agent to the specified clients. The c$ and admin$ must be
accessible on every client. Simple File Sharing (Folder Options) should be
disabled on the Windows machine.

positional arguments:
  host                  The hosts to deploy the {opsi-client-agent} to.

optional arguments:
  -h, --help            show this help message and exit
  --version, -V         show program's version number and exit
  --verbose, -v         increase verbosity (can be used multiple times)
  --debug-file DEBUGFILE
                        Write debug output to given file.
  --username USERNAME, -u USERNAME
                        username for authentication (default: Administrator).
                        Example for a domain account: -u
                        "<DOMAIN>\\<username>"
  --password PASSWORD, -p PASSWORD
                        password for authentication
  --use-fqdn, -c        Use FQDN to connect to client.
  --use-hostname        Use hostname to connect to client.
  --use-ip-address      Use IP address to connect to client.
  --ignore-failed-ping, -x
                        try installation even if ping fails
  --reboot, -r          reboot computer after installation
  --shutdown, -s        shutdown computer after installation
  --start-opsiclientd, -o
                        Start {opsiclientd} service after installation
                        (default).
  --no-start-opsiclientd
                        Do not start {opsiclientd} service after installation.
  --hosts-from-file HOSTFILE, -f HOSTFILE
                        File containing addresses of hosts (one per line).If
                        there is a space followed by text after the address
                        this will be used as client description for new
                        clients.
  --skip-existing-clients, -S
                        skip known opsi clients
  --threads MAXTHREADS, -t MAXTHREADS
                        number of concurrent deployment threads
  --depot DEPOT         Assign new clients to the given depot.
  --group GROUP         Assign fresh clients to an already existing group.
  --smbclient           Mount the client's C$-share via smbclient.
  --mount               Mount the client's C$-share via normal mount on the
                        server for copying the files. This imitates the
                        behaviour of the 'old' script.
  --keep-client-on-failure
                        If the client was created in opsi through this script
                        it will not be removed in case of failure. (DEFAULT)
  --remove-client-on-failure
                        If the client was created in opsi through this script
                        it will be removed in case of failure.
----

