



[[firststeps-software-deployment-product-tests-inventory]]
== Inventory with the localboot products hwaudit and swaudit.

In _opsi-configed_, _Client configuration_ mode, under the _Clients_ tab, select the client under consideration.

If not already performed, update the opsi-configed's dataset using _Reload File/Data_ or clicking the corresponding icon.

Go to the _Product configuration_ tab, click in the _Requested_ column for the _hwaudit_ product, this will open a list/dropdown menu and there select the _setup_ action. Repeat this for the _swaudit_ product.

The check mark in the icon menu bar should change its color to red. If you click it, the new settings will be transmitted to the opsi-Server, afterwards its color will be green again.

Then restart the client.
It should now start the _opsi-client-agent_ and install the _hwaudit_ and _swaudit_ products.
With _hwaudit_ and _swaudit_, hardware and software information, respectively, is collected and transmitted to the opsi-Server.
The collected information is displayed under the _Hardware Information_ and _Software Inventory_ tabs, respectively.

