[[firststeps-software-deployment-product-tests-hwinvent]]
[[firststeps-osinstall-tests-hwinvent]]
=== Hardware Inventory with the netboot product hwinvent

If the product 'hwinvent' is installed on your opsi server and you have added a client xref:clients:windows-client/adding-clients.adoc#firststeps-osinstall-create-client[] which is configured to boot over the network, you can do something else useful: Hardware inventory when there is no operating system installed.

Using 'opsi-configed', in the mode 'Configuration of clients', choose the appropriate client in the tab 'Clients'.
If you have not already done so, update the data of opsi-configed by using 'File / Reload all data' or click the reload icon.
Switch to the tab 'Netboot products', look for the line with the product +hwinvent+. Click in the column 'Requested Action', and select the action 'setup'.
The check mark in the icon menu bar should change its color to red.
If you click on it, the new settings will be transmitted to the opsi-Server, afterwards its color will be green again.

Then reboot the client. It should now pull a Linux image over the network (via PXE), to scan the hardware of the PC and then reboot it. If the computer was not otherwise already set up, afterwards the message appears that no operating system is installed on the disk.

The results of the hardware scan have been transmitted to the opsi-Server. The results can be viewed under the 'Hardware information' tab.

NOTE: In case the screen remains black after booting the boot image or if the network card does not work (correctly), the start parameters of the boot image may have to be adjusted for this specific hardware. +
This can be achieved using 'opsi-configed' in the 'Host parameters' tab by editing the entry 'opsi-linux-bootimage.append'. +
More information can be found in the opsi manual, in the chapter 'netboot products'.

