////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib gmbh
:Email:     info@uib.de
:Date:      17.09.2021
:Revision:  4.2
:toclevels: 6




[[opsi-manual-ci]]
== Adapting the opsi-client-agent to your Corporate Identity (CI)

Adjusting the appearance of the 'opsi-client-agent' can contribute significantly to acceptance, especially when it is introduced. For example, by inserting the company logo in the background graphics, users' uncertainty can be avoided.

=== Adapting Elements: opsi-script
The files that you can customize in opsi-script can be found in the directory `/var/lib/opsi/depot/opsi-client-agent/files/opsi-script/skin`:

* `bg.png` +
The background graphic of 'opsi-script' in which text messages and product logos are displayed at runtime.

* `skin.ini` +
The configuration file in which is specified in which font and color text messages are displayed.

=== Adapting Elements: opsiclientd
In the directory `/var/lib/opsi/depot/opsi-client-agent/files/opsi-notifier` you will find the files that determine the appearance of the different notifiers.
There is an image and a configuration file for each notifier:

* `block_login.bmp` +
Background image of the notifier that shows an active loginblocker.
* `block_login.ini` +
Configuration file of the loginblocker notifier.
* `event.bmp` +
Background image of the notifier that shows an active event with a connection to the opsi-server.
* `event.ini` +
Configuration file of the event notifier.
* `action.bmp` +
Background image of the notifier that shows a pending action (software installation).
* `action.ini` +
Configuration file of the action notifier.
* `shutdown.bmp` +
Background image of the notifier that shows a pending shutdown or reboot.
* `shutdown.ini` +
Configuration file of the shutdown notifier.
* `popup.bmp` +
Background image of the notifier that shows a popup message that was sent by the server.
* `popup.ini` +
Configuration file of the popup notifier.
* `userlogin.bmp` +
Background image of the notifier that shows an active userlogin event.
* `userlogin.ini` +
Configuration file of the userlogin notifier.

=== Protect your changes from updates: The custom directory

If you want to protect changes made to the files mentioned above from being overwritten when you install a new version of the opsi-Client agent, you can do this using the `custom` directory `/var/lib/opsi/depot/opsi-client-agent/files/custom` (previously `/var/lib/opsi/depot/opsi-client-agent/files/opsi/custom`). The complete `custom` directory is saved and restored when a new version of the opsi-Client agent is installed, so that the changes made here are not lost.

* `custom/opsi-script/skin/*.*` +
The contens are copied to `C:\Program Files (x86)\opsi.org\opsi-client-agent\opsi-script\skin` when installing the opsi-client-agent on the client.

* `custom/opsi-notifier/*.*` +
The contents are copied to `C:\Program Files (x86)\opsi.org\opsi-client-agent\opsi-notifier` when installing the opsi-client-agent on the client and overwrites the defaults with the server-side `files/opsi-notifier/` directory.

* `custom/opsiclientd/opsiclientd.conf` +
This is copied to `C:\Program Files (x86)\opsi.org\opsi-client-agent\opsiclientd` when installing the opsi-client-agent on the client and overwrites the defaults with the server-side `files/opsiclientd/` directory. +
*Attention:* +
Customizing opsiclientd.conf using this method is not recommended. To configure your clients, use host parameters/configs as described in the chapter on the opsi-client-agent. This method is only useful for extremely complex adjustments to opsiclientd.conf. If you use this method, you have to check every time a new opsi-client-agent version is installed on the server, whether changes have been made in the default file `files/opsiclientd/opsiclientd.conf` which you have to merge into your own version. So: +
*Stay away unless you really know what you are doing!*

