////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2.0
:toclevels: 3
:icons: font
:xrefstyle: full
:doctype:   book

include::common:partial$opsi_terms.adoc[]


// ifeval::["{mode}" == "antora"]
// :manual: opsi-script
// endif::[]


[[opsi-script-rc]]
= opsi-script reference card (4.12.7)

For Windows [W], Linux [L] and MacOS [M]



[[opsi-script-rc-const]]
== Global text constants

[[opsi-script-rc-const-system1]]
=== System directories

[[opsi-script-rc-const-system2]]
==== System directories [W]:

`%ProgramFilesDir%`:	'c:\program files'

`%ProgramFiles32Dir%`:	'c:\Program Files (x86)'	            //since 4.10.8

`%ProgramFiles64Dir%`:	'c:\program files'	                  //since 4.10.8

`%ProgramFilesSysnativeDir%` :	'c:\program files'	          //since 4.10.8

`%Systemroot%` :  	'c:\windows'

`%System%` :  	 	'c:\windows\system32'

`%Systemdrive%` :       	'c:'

`%ProfileDir%` :	        +
NT5: 'c:\Documents and Settings' +
NT6: 'C:\users\'

// {manual}

// ifeval::[{manual} == "opsi-script"]
// ifeval::[{lang} == "en"]
//   see also: <<opsi-script-global-const-list-system-base>>
// endif::[]
// ifeval::[{lang} == "de"]
//   siehe: <<opsi-script-global-const-list-system-base>>
// endif::[]
// endif::[]

ifdef::manual[see also: xref:var-const.adoc#opsi-script-global-const-list-system-base[opsi-script-global-const-list-system-base]]

[[opsi-script-rc-const-common]]
=== Common (AllUsers) directories [W]:

`%AllUsersProfileDir%` or `%CommonProfileDir%` : +
NT5: 'c:\Documents and Settings\All Users' +
NT6: 'C:\Users\Public'

`%CommonStartMenuPath%` or `%CommonStartmenuDir%` : +
NT5: 'c:\Documents and Settings\All Users\Startmenu' +
NT6: 'C:\ProgramData\Microsoft\Windows\Start Menu'

`%CommonAppdataDir%` : +
NT5: 'c:\Documents and Settings\All Users\Application Data' +
NT6: 'C:\ProgramData'

`%CommonDesktopDir%` +
NT5: 'c:\Documents and Settings\All Users\Desktop' +
NT6: 'C:\Users\Public\Desktop'

`%CommonStartupDir%` +
NT5: 'c:\Documents and Settings\All Users\Autostart' +
NT6: 'C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp'

`%CommonProgramsDir%`

ifdef::manual[see also : xref:var-const.adoc#opsi-script-global-const-list-commondir[Common (AllUsers) directories [W]]]

[[opsi-script-rc-const-default]]
=== Default User directories [W]:

`%DefaultUserProfileDir%`                          //since 4.11.1.1

ifdef::manual[see also : xref:var-const.adoc#opsi-script-global-const-list-defaultdir[Default User Directory [W]]]

[[opsi-script-rc-const-current]]
=== Current user directories  [W]:
User is the logged in user or given by /usercontext.

`%AppdataDir%` or `%CurrentAppdataDir%` : //since 4.10.8.13 +
NT5: 'c:\Documents and Settings\%USERNAME%\Application Data'
NT6: 'c:\users\%USERNAME%\Appdata\Roaming'

`%CurrentStartmenuDir%` //since 4.10.8.13

`%CurrentDesktopDir%` //since 4.10.8.13

`%CurrentStartupDir%`                               //since 4.10.8.13

`%CurrentProgramsDir%`                              //since 4.10.8.13

`%CurrentSendToDir%`	                              //since 4.10.8.13

`%CurrentProfileDir%`                               //since 4.11.2.1

ifdef::manual[see also : xref:var-const.adoc#opsi-script-global-const-list-currentuser[Current (logged in or usercontext) user directories [W]]]

[[opsi-script-rc-const-allntuser]]
=== /AllUserProfiles directory constants [W/L/M]:

`%UserProfileDir%`  +
or +
`%CurrentProfileDir%`                               // since 4.11.2.1 +
NT5: 'c:\Documents and Settings\%USERNAME%' +
NT6: 'c:\users\%USERNAME%'

ifdef::manual[see also : xref:var-const.adoc#opsi-script-global-const-list-allntuser[/AllUserProfiles (/AllNtUserProfiles) directory constants [W]]]

[[opsi-script-rc-const-oscript-path]]
=== opsi-script Path and Directories [W/L/M]:

`%ScriptPath% or %ScriptDir%`

`%RealScriptPath%` (since 4.12.4.21)

`%ScriptDrive%`

`%OpsiscriptDir%`  (since 4.12.3.6), `%WinstDir%`

`%OpsiscriptVersion%`  (since 4.12.3.6), `%WinstVersion%` (since 4.10.8.3)

`%opsiscriptProcname%`  (since 4.12.4.35)

`%Logfile%`

`%opsiScriptHelperPath%`  '%ProgramFiles32Dir%\opsi.org\opsiScriptHelper\lib' // since 4.11.3.2

`%opsiTmpDir%` : 'c:\opsi.org\tmp' // since 4.11.4.3

`%opsiUserTmpDir%` : 'c:\opsi.org\usertmp' // since 4.12.4.37

`%opsiLogDir%` : 'c:\opsi.org\log' // since 4.11.4.3

`%opsidata%` : 'c:\opsi.org\data' // since 4.12.0.12

`%opsiapplog%` : 'c:\opsi.org\applog' // since 4.12.0.12


ifdef::manual[see also : xref:var-const.adoc#opsi-script-global-const-list-oscript[_opsi-script_ Path and Directory [W/L/M]]]

[[opsi-script-rc-const-network]]
=== Network informations [W/L/M]:

`%Host%` :	value of environment variable HOST.

`%PCName%`:	value of environment variable PCNAME, or if absent of COMPUTERNAME.

`%Username%` :	Name of actual user.

`%IPName%` : The dns name of the pc. Usually identical with the netbios name and therefore with `%PCName%` besides that the netbios names uses to be uppercase.

`%IPAddress%` : may be the IP-Address of the machine. Use funktion `GetMyIpByTarget()` instead. +
ifdef::manual[see also : xref:prim-section.adoc#GetMyIpByTarget[GetMyIpByTarget]]

ifdef::manual[see also : xref:var-const.adoc#opsi-script-global-const-list-network[Network Information [W/L/M]]]

[[opsi-script-rc-const-service]]
=== Service Data [W/L/M]

`%HostID%` :	FQDN of the client in opsi service context, otherwise the computer name

`%FQDN%` :	FQDN in network context

`%opsiserviceURL%`

`%opsiServer%`

`%opsiDepotId%`     //since 4.11.4

`%opsiserviceUser%` FQDN used for the connection to the opsi-config-server

`%opsiserviceClientId%` : command line option `/clientid`

`%opsiservicePassword%`

`%installingProdName%`: 	productid	 //since 4.10.8

`%installingProdVersion%`:	product version	 //since 4.10.8

`%installingProduct%` :	productid (deprecated)

ifdef::manual[see also : xref:var-const.adoc#opsi-script-global-const-list-service[Data for and from opsi service [W/L/M]]]

[[opsi-script-rc-const-func]]
=== Functions to handle constants [W/L/M]

`replaceOpsiConstants(`<string list>`) : stringlist`  //since 4.12.3.6 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#replaceOpsiConstants_list[replaceOpsiConstants_list]]

`replaceOpsiConstants(`<string>`) : string`  //since 4.12.3.6 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#replaceOpsiConstants_string[replaceOpsiConstants_string]]

[[opsi-script-rc-primary-sections]]
== In Primary Sections

[[opsi-script-rc-primary-sections-kind]]
=== Kinds of Primary Sections [W/L/M]:

`[Initial]`

`[Actions]`

`[sub`<identifier>`]`

`sub` <file name>

`[ProfileActions]` [W]

ifdef::manual[see also : xref:prim-section.adoc#opsi-script-prim-section[Syntax and Meaning of Primary Sections of a _opsi-script_ Script [W/L/M]]]


[[opsi-script-rc-oscript-control]]
=== opsi-script control [W/L/M]:

`encoding=`<encoding> // (default is system encoding) since 4.11.4.2
ifdef::manual[see also : xref:configuration-options.adoc#encoding[encoding]]

`LogLevel`  (deprecated)
ifdef::manual[see also : xref:prim-section.adoc#opsi-script-params-loglevel[Specification of Logging Level [W/L/M]]]

`SetLogLevel` = <number> or `SetLogLevel` = <string> // (default=6)
ifdef::manual[see also : xref:prim-section.adoc#SetLogLevel[SetLogLevel]]
[source,opsiscript]
----
SetLogLevel = 7
SetLogLevel = "7"
----

`SetDebug_Lib` = <boolean value> // (default=false)
ifdef::manual[see also : xref:prim-section.adoc#SetDebugLib[SetDebugLib]]

`ExitOnError` = <boolean value> // (default=false)
ifdef::manual[see also : xref:prim-section.adoc#ExitOnError[ExitOnError]]

`ScriptErrorMessages =` <boolean value> // (default=true)
ifdef::manual[see also : xref:prim-section.adoc#ScriptErrorMessages[ScriptErrorMessages]]

ifdef::manual[see also : xref:cli-params.adoc#opsi-script-configs_ScriptErrorMessages[Central configuration via opsi Configs]]

`FatalOnSyntaxError =` <boolean value>  // (default=true) since 4.11.3.2
ifdef::manual[see also : xref:prim-section.adoc#FatalOnSyntaxError[FatalOnSyntaxError]]

`FatalOnRuntimeError =` <boolean value>  // (default=false) since 4.11.3.2
ifdef::manual[see also : xref:prim-section.adoc#FatalOnRuntimeError[FatalOnRuntimeError]]

`AutoActivityDisplay =` <boolean value>  // (default=false); if true shows a marquee (endless) progressbar while winbatch/dosbatch sections are . //since 4.11.4.7
ifdef::manual[see also : xref:prim-section.adoc#AutoActivityDisplay[AutoActivityDisplay]]
ifdef::manual[see also : xref:cli-params.adoc#opsi-script-configs_AutoActivityDisplay[Central configuration via opsi Configs]]

`forceLogInAppendMode =` <boolean value>  // (default=false); if true, log will be send in append mode . //since 4.12.3.6
ifdef::manual[see also : xref:prim-section.adoc#forceLogInAppendMode[forceLogInAppendMode]]

`Message` <string> or `Message` = <const string>
ifdef::manual[see also : xref:prim-section.adoc#Message[Message]]

`ShowMessageFile` <string>
ifdef::manual[see also : xref:prim-section.adoc#ShowMessageFile[ShowMessageFile]]

`ShowBitMap`  [<file name>] [<sub title>]
ifdef::manual[see also : xref:prim-section.adoc#ShowBitMap[ShowBitMap]]

`comment` <string> or `comment` = <const string>
ifdef::manual[see also : xref:prim-section.adoc#comment[comment]]

`LogError` <string> or `LogError` = <const string>
ifdef::manual[see also : xref:prim-section.adoc#LogError[LogError]]

`LogWarning` <string> or `LogWarning` = <const string>
ifdef::manual[see also : xref:prim-section.adoc#LogWarning[LogWarning]]

`includelog` <file name> <tail size>   //since 4.11.2.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#includelog[includelog]]

`includelog` <file name> <tail size> [<encoding>]  //since 4.11.4.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#includelog[includelog]]

[source,opsiscript]
----
includelog "%Scriptpath%\test-files\10lines.txt" "5"
----

`SetConfidential` <secret string> //since 4.11.3.5 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#SetConfidential[SetConfidential]]

`asConfidential(` <secret string expression> `) : string` //since 4.12.0.16 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#asConfidential_str[asConfidential_str]]

`asConfidential(` <secret stringlist expression> `) : stringlist` //since 4.12.4.15 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#asConfidential_list[asConfidential_list]]

`Pause` <string> or `Pause` = <const string>
ifdef::manual[see also : xref:prim-section.adoc#Pause[Pause]]

`Stop` <string> or `stop` = <const string>
ifdef::manual[see also : xref:prim-section.adoc#Stop[Stop]]

`include_insert` <file name> // since 4.11.3
ifdef::manual[see also : xref:prim-section.adoc#include_insert[include_insert]]

`include_append` <file name> // since 4.11.3
ifdef::manual[see also : xref:prim-section.adoc#include_append[include_append]]

`NormalizeWinst` // (set normal window state) since 4.11.3
ifdef::manual[see also : xref:prim-section.adoc#NormalizeWinst[NormalizeWinst]]

`IconizeWinst` // (set minimized window state)
ifdef::manual[see also : xref:prim-section.adoc#IconizeWinst[IconizeWinst]]

`MaximizeWinst` // (set maximized window state) // since 4.11.5.1
ifdef::manual[see also : xref:prim-section.adoc#MaximizeWinst[MaximizeWinst]]

`RestoreWinst` // (restore last window state)
ifdef::manual[see also : xref:prim-section.adoc#RestoreWinst[RestoreWinst]]

`SetSkinDirectory` <path to skin.ini> // since 4.11.3.5
ifdef::manual[see also : xref:prim-section.adoc#SetSkinDirectory[SetSkinDirectory]]

`runningInWanMode` : boolean //since 4.12.4.17 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#runningInWanMode[runningInWanMode]]

`reloadProductList` //since 4.12.6.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#reloadProductList[reloadProductList]]


[[opsi-script-rc-var]]
=== Variables [W/L/M]:

[[opsi-script-rc-var-strings]]
==== Strings

`DefVar` <variable name> +
; since 4.12.4.32 also possible: +
`DefVar` <variable name> [= <inital value>]

`Set` <variable name> `=` <value>

ifdef::manual[see also : xref:var-const.adoc#opsi-script-strvar[String (or Text) Variables [W/L/M]]]

[[opsi-script-rc-var-stringlists]]
==== Stringlists

`DefstringList`  <variable name>
; since 4.12.4.32 also possible: +
`DefstringList` <variable name> [= <inital value>]

ifdef::manual[see also : xref:var-const.adoc#opsi-script-lstvar[Stringlist Variables [W/L/M]]]

[[opsi-script-rc-func]]
=== Functions

[[opsi-script-rc-func-string]]
==== String functions

[[opsi-script-rc-important]]
===== Important

`GetOS`  // 'Linux' or 'Windows_NT'   [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetOS[GetOS]]

`getLinuxDistroType`  // 'debian' or 'redhat' or 'suse'  (see `getLinuxVersionMap`) [L]
ifdef::manual[see also : xref:prim-section.adoc#getLinuxDistroType[getLinuxDistroType]]


`GetMsVersionInfo` //Windows Version Information [W]
ifdef::manual[see also : xref:prim-section.adoc#GetMsVersionInfo[GetMsVersionInfo]]

`GetMsVersionName` //Windows Version Information [W]
ifdef::manual[see also : xref:prim-section.adoc#GetMsVersionName[GetMsVersionName]]

`GetSystemType`    //OS Architecture ("64 Bit System" or "x86 System") [W/L/M] +
ifdef::manual[see also : xref:prim-section.adoc#GetSystemType[GetSystemType]]

`getOSArchitecture` // OS Architecture (x86_32 / x86_64/ arm_64) //since 4.12.4.17 [W/L/M] +
ifdef::manual[see also : xref:prim-section.adoc#getOSArchitecture[getOSArchitecture]]

`getRegistryValue(`<keystr>, <varstr> [, <access str>]`)` : string //since 4.12.0.16 [W] +
<access str> = one of 32bit, 64bit, sysnative ; default sysnative
ifdef::manual[see also : xref:prim-section.adoc#getRegistryValue[getRegistryValue]]

`GetRegistrystringvalue (`"[key] var"`)` [W]
ifdef::manual[see also : xref:prim-section.adoc#GetRegistrystringvalue[GetRegistrystringvalue]]

`GetRegistryStringValue32 (`"[key] var"`)`   //since 4.10.8 [W]
ifdef::manual[see also : xref:prim-section.adoc#GetRegistryStringValue32[GetRegistryStringValue32]]

`GetRegistryStringValue64 (`"[key] var"`)`   //since 4.10.8 [W]
ifdef::manual[see also : xref:prim-section.adoc#GetRegistryStringValue64[GetRegistryStringValue64]]

`GetRegistryStringValueSysNative (`"[key] var"`)`    //since 4.10.8 [W]
ifdef::manual[see also : xref:prim-section.adoc#GetRegistryStringValueSysNative[GetRegistryStringValueSysNative]]

`GetValueFromInifile (`<file path>, <section>, <key>, <default value>, OPTIONAL <encoding>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetValueFromInifile[GetValueFromInifile]]

`GetProductProperty (`<PropertyName>, <DefaultValue> `)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetProductProperty[GetProductProperty]]

`GetConfidentialProductProperty (`<PropertyName>, <DefaultValue>`)` //since 4.11.5.2 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetConfidentialProductProperty[GetConfidentialProductProperty]]

`trim(`<string>`)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#trim[trim]]

`lower(`<string>`)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#lower[lower]]

`upper(`<string>`)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#upper[upper]]

`unquote(`<string>,<quote-string>`)`  //since 4.11.2.1  [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#unquote[unquote]]

`unquote2(`<string>,<quote-string>`)`  //since 4.11.5.2  [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#unquote2[unquote2]]

`stringReplace(`<string>, <oldPattern>, <newPattern>`)`  //since 4.11.3 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#stringReplace[stringReplace]]

`strLength(`<string>`)`  //since 4.11.3 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#strLength[strLength]]

`strPos(`<string>, <sub string>`)`  //since 4.11.3 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#strPos[strPos]]

`strPart(`<string>, <start pos>, <number of chars>`)`  //since 4.11.3 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#strPart[strPart]]

`getValue(`<key string>, <hash string list> `)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getValue[getValue]]

`getValueBySeparator(`<key string>,<separator string>,<hash string list> `)` //since 4.11.2.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getValueBySeparator[getValueBySeparator]]

`setValueByKey(`<key>, <value>, <targetlist> [, <separator (char)>]`)` [W/L/M]
ifdef::manual[see also : <<setValueByKey>>]

`getValueFromFile(`<key string>, <file name>`)` //since 4.11.4.4 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getValueFromFile[getValueFromFile]]

`getValueFromFileBySeparator(`<key string>,<separator string>,<file name>`)` //since 4.11.4.4 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getValueFromFileBySeparator[getValueFromFileBySeparator]]

`getLastExitCode : string (exitcode)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getLastExitCode[getLastExitCode]]

[[opsi-script-rc-spec-license-management]]
===== Special: License Management

`DemandLicenseKey(` poolId [, productId [,windowsSoftwareId]] `)`
[source,opsiscript]
----
set $mykey$ = DemandLicenseKey ("", "office2007")
----
ifdef::manual[see also : xref:prim-section.adoc#DemandLicenseKey[DemandLicenseKey]]

`FreeLicense (`poolId [, productId [,windowsSoftwareId]]`)`
[source,opsiscript]
----
set $result$ = FreeLicense("", "office2007")
----
ifdef::manual[see also : xref:prim-section.adoc#FreeLicense[FreeLicense]]

[[opsi-script-rc-spec-usercontext]]
===== Special: Usercontext / loginscripts [W]:

`GetUserSID(`<Windows Username>`)`
ifdef::manual[see also : xref:prim-section.adoc#GetUserSID[GetUserSID]]

`GetLoggedInUser`   //since 4.11.1.2
ifdef::manual[see also : xref:prim-section.adoc#GetLoggedInUser[GetLoggedInUser]]

`GetUsercontext`   //since 4.11.1.2
ifdef::manual[see also : xref:prim-section.adoc#getLastExitCode[getLastExitCode]]

`GetScriptMode`  possible values 'Machine','Login' //since 4.11.2.1
ifdef::manual[see also : xref:prim-section.adoc#GetUsercontext[GetUsercontext]]

`saveVersionToProfile` - save productversion-packageversion to local profile //since 4.11.2.1
ifdef::manual[see also : xref:prim-section.adoc#saveVersionToProfile[saveVersionToProfile]]

`readVersionFromProfile` : string - read productversion-packageversion from local profile //since 4.11.2.1
ifdef::manual[see also : xref:prim-section.adoc#readVersionFromProfile[readVersionFromProfile]]

`scriptWasExecutedBefore` : boolean - is true if saved and running productversion-packageversion are identical //since 4.11.2.1
ifdef::manual[see also : xref:prim-section.adoc#scriptWasExecutedBefore[scriptWasExecutedBefore]]



[[opsi-script-rc-other]]
===== Other

`GetHostsName (`<hostaddress> `)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetHostsName[GetHostsName]]

`GetHostsAddr (`<hostname> `)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetHostsAddr[GetHostsAddr]]

`ExtractFilePath (`<path>`)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#ExtractFilePath[ExtractFilePath]]

`calculate(`<arithmetic string expression>`)` // since 4.11.3.5 : knows: `+-*/()` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#calculate[calculate]]

`DecStrToHexStr (` <decstring>, <hexlength>`)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#DecStrToHexStr[DecStrToHexStr]]

`HexStrToDecStr (`<hexstring>`)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#HexStrToDecStr[HexStrToDecStr]]

`base64EncodeStr(`<string>`)`  [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#base64EncodeStr[base64EncodeStr]]

`base64DecodeStr(`<string>`)`  [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#base64DecodeStr[base64DecodeStr]]

`convert2Jsonstr(`<string>`)`  //since 4.10.8.3


`RandomStr` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#RandomStr[RandomStr]]

`RandomStrWithParameters` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#RandomStrWithParameters[RandomStrWithParameters]]

`RandomIntStr(`<number str>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#RandomIntStr[RandomIntStr]]


`CompareDotSeparatedStrings(`<string1>, <string2>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#CompareDotSeparatedStrings_str[CompareDotSeparatedStrings_str]]

`CompareDotSeparatedNumbers(`<string1>, <string2>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#CompareDotSeparatedNumbers_str[CompareDotSeparatedNumbers_str]]

`EnvVar (`<environment variable>`)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#EnvVar[EnvVar]]

`ParamStr` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#ParamStr[ParamStr]]

`getDiffTimeSec` (Time in seconds since last marktime) //since 4.11.3 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getDiffTimeSec[getDiffTimeSec]]

`SidToName(`<well known sid>`)` //since 4.11.3: gives localized name of the sid [W]
ifdef::manual[see also : xref:prim-section.adoc#SidToName[SidToName]]

`GetMyIpByTarget(`<target ip addr>`) : string` //since 4.11.3.2 /4.11.6 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetMyIpByTarget[GetMyIpByTarget]]

`GetIpByName(`<ip addr / ip name>`)` //since 4.11.3.2 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetIpByName[GetIpByName]]

`reencodestr(`<str>, <from>, <to>`)` //since 4.11.4.2 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#reencodestr[reencodestr]]

`strLoadTextFile (` <filename> `)` //since 4.11.4.6 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#strLoadTextFile[strLoadTextFile]]

`strLoadTextFileWithEncoding (` <filename> , <encoding>`)` //since 4.11.4.6 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#strLoadTextFileWithEncoding[strLoadTextFileWithEncoding]]

`GetShortWinPathName(<longpath string>)` //since 4.11.5.2 [W]
ifdef::manual[see also : xref:prim-section.adoc#GetShortWinPathName[GetShortWinPathName]]

`stringinput(`< message str>,< boolstr confidential>`) : string` //since 4.12.1.2 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#stringinput[stringinput]]

`which(`<command in path>`) : string` (command with path) //since 4.12.3.6 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#which[which]]

`replaceOpsiConstants(`<string>`) : string`  //since 4.12.3.6 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#replaceOpsiConstants_string[replaceOpsiConstants_string]]

`ReadTOMLFile(`<TOMLfilePath: String>`) : String`  //since 4.12.5.0 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#ReadTOMLFile[ReadTOMLFile]]

`GetTOMLAsString(`<TOMLcontents: String>`) : String`   //since 4.12.5.0 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetTOMLAsString[GetTOMLAsString]]

`GetTOMLTableAsString(`<TOMLcontents: String> , <table name : String>`) : String`   //since 4.12.5.0 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetTOMLTableAsString[GetTOMLTableAsString]]

`GetValueFromTOML(`<TOMLcontents: String> , <keyPath: String> , <defaultValue: String>`) : String`   //since 4.12.5.0 [W/L/M] 
ifdef::manual[see also : xref:prim-section.adoc#GetValueFromTOML[GetValueFromTOML]]

`ModifyTOML(`<TOMLcontents: String> , <command: String> , <keyPath: String> , <value: String>`) : String`   //since 4.12.5.0 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#ModifyTOML[ModifyTOML]]

`DeleteTableFromTOML(`<TOMLcontents: String> , <tablePath: String>`) : String`   //since 4.12.5 [W/L/M] 
ifdef::manual[see also : xref:prim-section.adoc#DeleteTableFromTOML[DeleteTableFromTOML]]

`ConvertTOMLtoJSON(`<TOMLcontents: String>`) : String`   //since 4.12.5.0 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#ConvertTOMLtoJSON[ConvertTOMLtoJSON]]


[[opsi-script-rc-deprecated]]
===== Deprecated

`GetNtVersion` Deprecated - please use `GetMsVersionInfo` [W]
ifdef::manual[see also : xref:prim-section.adoc#GetMsVersionInfo[GetMsVersionInfo]]

`IniVar (`<key>`)` :	(deprecated; use GetProductProperty) [W]
ifdef::manual[see also : xref:prim-section.adoc#GetProductProperty[GetProductProperty]]

`SubstringBefore (`<string1>, <string2>`)` (deprecated; use `splitString` / `takestring`) [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#splitString[splitString]]

[[opsi-script-rc-func-stringlist]]
==== String list functions

===== Important

`splitString (`<string1>, <string2>`)` [W/L/M]
[source,opsiscript]
----
set $list1$ = splitString ("\\server\share\dir","\")
----
ifdef::manual[see also : xref:prim-section.adoc#splitString[splitString]]

`splitStringOnWhiteSpace (`<string>`)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#splitStringOnWhiteSpace[splitStringOnWhiteSpace]]

`loadTextFile (`<file name>`)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#loadTextFile[loadTextFile]]

`loadUnicodeTextFile (`<file name>`)` [W]
ifdef::manual[see also : xref:prim-section.adoc#loadUnicodeTextFile[loadUnicodeTextFile]]

`loadTextFileWithEncoding(` <file name> `,` <encoding>`)` //since 4.11.5 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#loadTextFileWithEncoding[loadTextFileWithEncoding]]

`composeString (`<string list>, <Link>`)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#composeString[composeString]]

`takeString (`<index>, <list>`)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#takeString[takeString]]

`setStringInListAtIndex(`<newstring>,<list>,<indexstr>`) : stringlist`   //since 4.11.6 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#setStringInListAtIndex[setStringInListAtIndex]]

`takeFirstStringContaining(`<list>,<search string>`)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#takeFirstStringContaining[takeFirstStringContaining]]

`getOutStreamFromSection (`<dos section name>`)` [W/L/M]
[source,opsiscript]
----
set $list$= getOutStreamFromSection ('DosInAnIcon_try')
----
ifdef::manual[see also : xref:prim-section.adoc#getOutStreamFromSection[getOutStreamFromSection]]

`shellCall (`<command string>`) : stringlist (output)` //since 4.11.4.2 [W/L/M]
[source,opsiscript]
----
set $list$= shellCall('net start')
----
ifdef::manual[see also : xref:prim-section.adoc#shellCall_list[shellCall_list]]


`getReturnListFromSection (`<xml section name>`)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getReturnListFromSection[getReturnListFromSection]]

`getListContaining(`<list>,<search string>`)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getListContaining[getListContaining]]

`getListContainingList(`<list1>,<list2>`)`  //since 4.11.3.7 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getListContainingList[getListContainingList]]

`count (`<list>`)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#count[count]]

`emptylist (`<list>`)`  //since 4.11.3.7 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#emptylist[emptylist]]

`for %`<identifier>`% in` <list> `do` <one statement | sub section> [W/L/M]
[source,opsiscript]
----
for %s% in $list1$ do sub_test_string
----
ifdef::manual[see also : xref:prim-section.adoc#forInDo[forInDo]]

`GetProcessList`   //since 4.11.1.2; gives list of exename;pid;dom/user [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetProcessList[GetProcessList]]

`getProductPropertyList(`<propname>,<default value>`)`  //since 4.11.3 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getProductPropertyList[getProductPropertyList]]

`getRegistryKeyList32(`<regkey>`)` //since 4.11.3 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryKeyList32[getRegistryKeyList32]]

`getRegistryKeyList64(`<regkey>`)` //since 4.11.3 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryKeyList64[getRegistryKeyList64]]

`getRegistryKeyListSysnative(`<regkey>`)` //since 4.11.3 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryKeyListSysnative[getRegistryKeyListSysnative]]

`getRegistryKeyList(`<regkey>, <access str>`)` //since 4.12.5.0 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryKeyList[getRegistryKeyList]]

`getRegistryVarList32(`<regkey>`)`  //since 4.11.3 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryVarList32[getRegistryVarList32]]

`getRegistryVarList64(`<regkey>`)` //since 4.11.3 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryVarList64[getRegistryVarList64]]

`getRegistryVarListSysnative(`<regkey>`)` //since 4.11.3 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryVarListSysnative[getRegistryVarListSysnative]]

`getRegistryVarList(`<regkey>, <access str>`)` //since 4.12.5.0 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryVarList[getRegistryVarList]]

`getProfilesDirList` //since 4.11.3.2 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getProfilesDirList[getProfilesDirList]]

`listFiles (`<Path>, <Searchmask> , <SearchSubDirectories>, <[Redirection]>`) : stringlist` //since 4.12.3 [W/L/M]
[source,opsiscript]
----
Set $Filelist$ = listFiles("C:\windows\system32","*.ico;*.dll","False","64bit")
----
ifdef::manual[see also : xref:prim-section.adoc#listFiles[listFiles]]

`replaceOpsiConstants(`<string list>`) : stringlist`  //since 4.12.3.6 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#replaceOpsiConstants_list[replaceOpsiConstants_list]]

===== Infomaps

`GetLocaleInfoMap` [W]
ifdef::manual[see also : xref:prim-section.adoc#GetLocaleInfoMap[GetLocaleInfoMap]]

`GetMSVersionMap` [W]
ifdef::manual[see also : xref:prim-section.adoc#GetMSVersionMap[GetMSVersionMap]]

`getLinuxVersionMap`  //since 4.11.4  [L] +
keys are (example):
[source,ini]
----
Distributor ID=Ubuntu
Description=Ubuntu 12.04.2 LTS
Release=12.04
Codename=precise
kernel name=Linux
node name=detlefvm05
kernel release=3.2.0-40-generic-pae
kernel version=#64-Ubuntu SMP Mon Mar 25 21:44:41 UTC 2013
machine=i686
processor=athlon
hardware platform=i386
operating system=GNU/Linux
----
ifdef::manual[see also : xref:prim-section.adoc#getLinuxVersionMap[getLinuxVersionMap]]

`getFileInfoMap(` <file name> `)` [W]
ifdef::manual[see also : xref:prim-section.adoc#getFileInfoMap[getFileInfoMap]]

`getProductMap`  // since 4.11.2.4  [W/L/M] +
keys are: id, name, description, advice, productversion, packageversion, priority, installationstate, lastactionrequest, lastactionresult, installedversion, installedpackage, installedmodificationtime,actionrequest +
ifdef::manual[see also : xref:prim-section.adoc#getProductMap[getProductMap]]

`getRegistryVarMap32(`<regkey>`)`  //since 4.11.3 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryVarMap32[getRegistryVarMap32]]

`getRegistryVarMap64(`<regkey>`)` //since 4.11.3 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryVarMap64[getRegistryVarMap64]]

`getRegistryVarMapSysnative(`<regkey>`)` //since 4.11.3 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryVarMapSysnative[getRegistryVarMapSysnative]]

`getRegistryVarMap(`<regkey>, <access str>`)` //since 4.12.5.0 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryVarMap[getRegistryVarMap]]

`getHWBiosInfoMap`  //since 4.11.4  [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getHWBiosInfoMap[getHWBiosInfoMap]]

`editmap(`< strlist>`) : stringlist` //since 4.12.1.2 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#editmap[editmap]]


===== Other

`createStringList (`<string0>, <string1> ,... `)` [W/L/M]
[source,opsiscript]
----
set $list1$ = createStringList ('a','b')
----
ifdef::manual[see also : xref:prim-section.adoc#createStringList[createStringList]]

`reverse (`<list>`)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#reverse[reverse]]

`getSectionNames(`<ini-file>`)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getSectionNames[getSectionNames]]

`retrieveSection (`<section name>`)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#retrieveSection[retrieveSection]]

`getSubList (`<start index> : <end index>, <list>`)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getSubList[getSubList]]

`getSubListByMatch (`<search string>, <target list>`)` :stringlist //since 4.12.0.14 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getSubListByMatch_sl[getSubListByMatch_sl]]

`getSubListByMatch (`<search list>, <target list>`)` :stringlist //since 4.12.0.14 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getSubListByMatch_ll[getSubListByMatch_ll]]

`getSubListByContaining (` <search string>, <target list>`)` :stringlist //since 4.12.0.14 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getSubListByContaining_sl[getSubListByContaining_sl]]

`getSubListByContaining (`<search list>, <target list>`)` :stringlist //since 4.12.0.14 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getSubListByContaining_ll[getSubListByContaining_ll]]

`getSubListByKey (`<search string>, <target list>`)` :stringlist //since 4.12.0.14 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getSubListByKey_sl[getSubListByKey_sl]]

`getSubListByKey (`<search list>, <target list>`)` :stringlist //since 4.12.0.14 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getSubListByKey_ll[getSubListByKey_ll]]

`getKeyList (`<list>`)` :stringlist //since 4.12.0.14 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getKeyList[getKeyList]]

`addtolist(`<list>,<string>`)`	 //since 4.10.8 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#addtolist[addtolist]]

`addListToList(`<dest list>,<src list>`)`	 //since 4.10.8 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#addListToList[addListToList]]

`reencodestrlist(`<list>, <from>, <to>`)` //since 4.11.4.2 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#reencodestrlist[reencodestrlist]]

`removeFromListByContaining(`<search string>`,` <target list>`) : stringlist` //since 4.11.5.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#removeFromListByContaining_str[removeFromListByContaining_str]]

`removeFromListByContaining(`<search list>`,` <target list>`) : stringlist` //since 4.11.5.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#removeFromListByContaining_list[removeFromListByContaining_list]]

`removeFromListByMatch(`<searchstring>,<target list>`) : stringlist`   //since 4.11.6 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#removeFromListByMatch[removeFromListByMatch]]

`LoadTOMLFile(`<TOMLfilePath: String>`) : StringList` //since 4.12.5 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#LoadTOMLFile[LoadTOMLFile]]

`GetTOMLAsStringList(`<TOMLcontents: String>`) : StringList`   //since 4.12.5 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetTOMLAsStringList[GetTOMLAsStringList]]

`GetTOMLKeys(`<TOMLcontents: String>`) : StringList`   //since 4.12.5 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetTOMLKeys[GetTOMLKeys]]

`GetTOMLTableNames(`<TOMLcontents: String>`) : StringList`   //since 4.12.5 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetTOMLTableNames[GetTOMLTableNames]]

`GetTOMLTable(`<TOMLcontents: String> , <table name : String>`) : StringList`   //since 4.12.5 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetTOMLTable[GetTOMLTable]]


[[opsi-script-rc-func-bool]]
==== Boolean operators and functions

ifdef::manual[see also : xref:prim-section.adoc#opsi-script-commands-if-else-bool-functions[Boolean Expressions]]


<string1> `=` <string2> [W/L/M]

<bool1> `AND` <bool2> [W/L/M]

<bool1> `OR` <bool2> [W/L/M]

`NOT`(<bool3>) [W/L/M]

`FileExists (`<file name>`)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#FileExists[FileExists]]

`FileExists32 (`<file name>`)` [W]
ifdef::manual[see also : xref:prim-section.adoc#FileExists[FileExists]]

`FileExists64 (`<file name>`)` [W]
ifdef::manual[see also : xref:prim-section.adoc#FileExists[FileExists]]

`FileExistsSysNative (`<file name>`)` [W]
ifdef::manual[see also : xref:prim-section.adoc#FileExists[FileExists]]

`DirectoryExists` (<folder path> [,<access str>]) : boolean //since 4.12.1 [W/L/M] +
'sysnative' is the default for <access str>. Otherwise, it can be '32bit', '64bit' or 'sysnative'
ifdef::manual[see also : xref:prim-section.adoc#DirectoryExists[DirectoryExists]]

`FileOrFolderExists` (<file or folder path> [,<access str>]) : boolean [W/L/M]
'sysnative' is the default for <access str>. Otherwise, it can be '32bit', '64bit' or 'sysnative'
ifdef::manual[see also : xref:prim-section.adoc#FileOrFolderExists[FileOrFolderExists]]

`fileIsSymlink (`<file name>`)` // since 4.12.4.21 [W/L/M] +
ifdef::manual[see also : xref:prim-section.adoc#fileIsSymlink[fileIsSymlink]]

`LineExistsIn (`<string>, <file name>`)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#LineExistsIn[LineExistsIn]]

`LineBeginning_ExistsIn (`<string>, <file name>`)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#LineBeginning_ExistsIn[LineBeginning_ExistsIn]]

`LineContaining_ExistsIn(` <string>, <file name> `)` //since 4.11.4.10: true: if a in <file name> contains <string> [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#LineContaining_ExistsIn[LineContaining_ExistsIn]]

`XMLAddNamespace(`<XMLfilename>, <XMLelementname>, <XMLnamespace>`)` [W]
ifdef::manual[see also : xref:prim-section.adoc#XMLAddNamespace[XMLAddNamespace]]

`XMLRemoveNamespace(`<XMLfilename>, <XMLelementname>, <XMLnamespace>`)` [W]
ifdef::manual[see also : xref:prim-section.adoc#XMLRemoveNamespace[XMLRemoveNamespace]]

`HasMinimumSpace (`<drive letter>, <capacity>`)` [W]
ifdef::manual[see also : xref:prim-section.adoc#HasMinimumSpace[HasMinimumSpace]]

Example:
[source,opsiscript]
----
if not (HasMinimumSpace ("%SYSTEMDRIVE%", "500 MB"))
   LogError "Required free space of 500 MB not available on %SYSTEMDRIVE%"
   isFatalError
endif
----

`opsiLicenseManagementEnabled` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#opsiLicenseManagementEnabled[opsiLicenseManagementEnabled]]

`runningAsAdmin`    //since 4.11.1.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#runningAsAdmin[runningAsAdmin]]

`isLoginScript`    //since 4.11.2.1 [W]
ifdef::manual[see also : xref:prim-section.adoc#isLoginScript[isLoginScript]]

`contains(`<str>, <substr>`) : bool`   //since 4.11.3: true if <substr> in <str> [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#contains[contains]]

`isNumber(`<str>`)` //since 4.11.3: true if <str> represents an integer [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#isNumber[isNumber]]

`runningOnUefi` //since 4.11.4.3: true: if the running OS was booted in UEFI mode [W]
ifdef::manual[see also : xref:prim-section.adoc#runningOnUefi[runningOnUefi]]

`runningInPE` //since 4.12.0.13: true: if the running OS is a Windows PE [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#runningInPE[runningInPE]]

`runningInWAnMode` //since 4.12.4.16: true: if opsiserver = localhost [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#runningInWAnMode[runningInWAnMode]]

`isDriveReady(`<drive letter>`)` //since 4.11.4.4: true: if the drive can be accessed [W]
ifdef::manual[see also : xref:prim-section.adoc#isDriveReady[isDriveReady]]

`runningWithGui : bool`` //since 4.12.3.6: true: if the running OS has a GUI (at Win+Mac always true)[M/L/W]
ifdef::manual[see also : xref:prim-section.adoc#runningWithGui[runningWithGui]]

`saveTextFile(`<list>, < filename>`)` //since 4.11.4.4: true: if list is succesfully written to file [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#saveTextFile[saveTextFile]]

`saveTextFileWithEncoding(`<list>, < filename>, <encoding>`) : bool` //since 4.11.6.4: true: if list is succesfully written to file [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#saveTextFileWithEncoding[saveTextFileWithEncoding]]

`saveUnicodeTextFile(`<list>, < filename>, <encoding>`) : bool` //since 4.12.4.13: true: if list is succesfully written to unicode file [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#saveUnicodeTextFile[saveUnicodeTextFile]]

`CompareDotSeparatedNumbers(`<str1>,<relation str>,<str2>`)`  //since 4.11.5.2: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#CompareDotSeparatedNumbers_bool[CompareDotSeparatedNumbers_bool]]

`CompareDotSeparatedStrings(`<str1>,<relation str>,<str2>`)`  //since 4.11.5.2: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#CompareDotSeparatedStrings_bool[CompareDotSeparatedStrings_bool]]

`RegKeyExists(`<regkey>[,<access str>]`) : bool` //since 4.12.0.16 [W] +
<access str> = one of 32bit, 64bit, sysnative ; default sysnative
ifdef::manual[see also : xref:prim-section.adoc#RegKeyExists[RegKeyExists]]

`RegVarExists(`<regkey>, <var str> [,<access str>]`) : bool` //since 4.12.0.16 [W] +
<access str> = one of 32bit, 64bit, sysnative ; default sysnative
ifdef::manual[see also : xref:prim-section.adoc#RegVarExists[RegVarExists]]

`isPingReachable(<host>) : boolean`     //since 4.12.3.6   [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#isPingReachable[isPingReachable]]

`isValidFQDN(<domain name>) : boolean`     //since 4.12.4.4 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#isValidFQDN[isValidFQDN]]

`fileHasBom (`<file name>`) : boolean` //since 4.12.4.17 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#fileHasBom[fileHasBom]]

`SaveToTOMLFile(`<TOMLcontents: String> , <TOML file Path: String>`) : boolean`   //since 4.12.5 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#SaveToTOMLFile[SaveToTOMLFile]]

`ConvertTOMLfileToJSONfile(`<TOMLfilePath: String> , <JSONfilePath: String>`) : boolean`   //since 4.12.5 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#ConvertTOMLfileToJSONfile[ConvertTOMLfileToJSONfile]]


[[opsi-script-rc-func-misc]]
==== Misc functions

`Killtask` <process name> [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#Killtask[Killtask]]

`requiredOpsiscriptVersion` <relation operator> <version> //since 4.12.3.6 [W/L/M]
[source,opsiscript]
----
requiredOpsiscriptVersion >= "4.12.3.6"
----
ifdef::manual[see also : xref:prim-section.adoc#requiredOpsiscriptVersion[requiredOpsiscriptVersion]]

`requiredWinstVersion` <relation operator> <version> [W/L/M] +
outdatet - use `requiredOpsiscriptVersion`
ifdef::manual[see also : xref:prim-section.adoc#requiredOpsiscriptVersion[requiredOpsiscriptVersion]]

`UpdateEnvironment` //since 4.11.5 [W]: +
Subsequent calls of `winbatch` with the parameter `/RunElevated` will see the changed Environment (NT6 only).
ifdef::manual[see also : xref:prim-section.adoc#UpdateEnvironment[UpdateEnvironment]]


[[opsi-script-rc-flow-control]]
==== Flow control

'if - elseif - else - endif' [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#IfElseEndif[IfElseEndif]]

Syntax:

`if` <condition> +
  ;statement(s) +
[`elseif` <condition> +
  ;statement(s)] +
[`else` +
  ;statement(s)] +
`endif`

`elseif` //since 4.12.4.37

Example:
[source,opsiscript]
----
Set $NTVer$ = GetMsVersionInfo
if ( $NTVer$ >= "6" )
     sub_install_win7
else
  if ( $NTVer$ = "5.1" )
    sub_install_winXP
  else
    stop "not a supported OS-Version"
  endif
endif
----

'for - to - do' Statement //since 4.11.5 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#ForToDo[ForToDo]]

`for` %<temporary string variable>% `=` <start string> `to` <end string> `do` <one statement>


Example:
[source,opsiscript]
----
for %s% = "1" to "5" do sub_iteration_test
----

'Switch / Case' Statement //since 4.11.5 [W/L/M] +
ifdef::manual[see also : xref:prim-section.adoc#SwitchCase[SwitchCase]] +
Can not be nested. +
ifdef::manual[see also : <<IfElseEndif>>]

Syntax:
----
Switch <string expression>
  Case <string const>
    <statement(s)>
  EndCase
  [DefaultCase
    <statement(s)>
   EndCase]
EndSwitch
----


Example:

[source,opsiscript]
----
set $ConstTest$ = "5"
Switch $ConstTest$
	Case "1"
		set $CompValue$ = "1"
	EndCase
	Case "2"
		set $CompValue$ = "2"
	EndCase
	DefaultCase
		set $CompValue$ = "notexisting"
	EndCase
EndSwitch
----


`isFatalError` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#isFatalError[isFatalError]]

`isFatalError` <string>  //since 4.11.3.2 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#isFatalError[isFatalError]]

`isSuccess` //since 4.11.3.7 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#isSuccess[isSuccess]]

`isSuspended` //since 4.11.4.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#isSuspended[isSuspended]]

`noUpdateScript` //since 4.11.3.7 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#noUpdateScript[noUpdateScript]]

`ExitWindows /Reboot` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#Reboot[Reboot]]

`ExitWindows /ImmediateReboot` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#ImmediateReboot[ImmediateReboot]]

`ExitWindows /ImmediateLogout` [W]
ifdef::manual[see also : xref:prim-section.adoc#ImmediateLogout[ImmediateLogout]]

`ExitWindows /ShutdownWanted` [W]
ifdef::manual[see also : xref:prim-section.adoc#ShutdownWanted[ShutdownWanted]]

`ExitWindows /RebootWanted` (deprecated, acts like /Reboot) [W]
ifdef::manual[see also : xref:prim-section.adoc#Reboot[Reboot]]

`sleepSeconds` <Integer> or <string> : noresult [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#sleepSeconds[sleepSeconds]]

`ChangeDirectory` <directory>   //since 4.11.2.6 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#ChangeDirectory[ChangeDirectory]]

////
for to
isSuspenden
sub
include
err
opsiservicecall
////

[[opsi-script-rc-secondary-sections]]
== Secondary Sections

[[opsi-script-rc-winbatch]]
=== Winbatch [W/L/M]

ifdef::manual[see also : xref:sec-section.adoc#opsi-script-winbatch[WinBatch-Sections [W/L/M]]]

Function: execute programs via operating system API

`[WinBatch`<identifier>`]`

Modifier:

`/LetThemGo`

`/WaitForProcessEnding` "<program.exe>"

`/TimeOutSeconds` <seconds>

`/WaitForWindowAppearing` <window title> ('does not work with 64 Bit programs') [W]

`/WaitForWindowVanish` <window title> ('does not work with 64 Bit programs') [W]

`/RunElevated` // since 4.11.3: only at >= NT6 ; no network access [W]

`/RunAsLoggedOnUser` // since 4.11.3.5 ; works only inside 'userLoginScripts' [W]

`/32Bit`	 //since 4.11.3.5  [W]

`/64Bit`	 //since 4.11.3.5  [W]

`/SysNative`	 //since 4.11.3.5 [W]

[[opsi-script-rc-dosbatch]]
=== DosBatch and DosInAnIcon (ShellBatch and ShellInAnIcon) [W/L/M]

ifdef::manual[see also : xref:sec-section.adoc#opsi-script-dosbatch[DOSBatch/DosInAnIcon (ShellBatch/ShellInAnIcon) Sections]]

Function: Execute section via cmd.exe [W] or bash [L/M]

`[DosBatch`<identifier>`]` <optional parameters> <winst <modifier>>

`[DosInAnIcon`<identifier>`]` <optional parameters> <winst <modifier>>

`[ShellBatch`<identifier>`]` <optional parameters> <winst <modifier>>

`[ShellInAnIcon`<identifier>`]` <optional parameters> <winst <modifier>>

Modifier:  //since 4.11.1.1

`/32Bit`  [W]

`/64Bit`  [W]

`/SysNative` [W]

`/showoutput` [W/L/M] // since 4.11.4.7

`/WaitForProcessEnding` "<program.exe>" // since 4.12.4 [W/L/M]

`/TimeOutSeconds` <seconds> // since 4.12.4 [W/L/M]

`/RunElevated` // since 4.12.4: only at >= NT6 ; no network access [W]

`/RunAsLoggedOnUser` // since 4.12.4.31 ; works only inside 'userLoginScripts' [W]

The modifiers has to be seperated by 'winst' from the parameters.
[source,opsiscript]
----
DosInAnIcon_do_64bit_stuff winst /64Bit
----

Commands:
see manual

[[opsi-script-rc-execwith]]
=== ExecWith [W/L/M]

ifdef::manual[see also : xref:sec-section.adoc#opsi-script-execwith[ExecWith Sections]]

Function: Execute section via any interpreter

`[ExecWith`<identifier>`]` <path to interpreter>

Modifier:

`/LetThemGo`

`/EscapeStrings`

`/32Bit`	 //since 4.11.3.5  [W]

`/64Bit`	 //since 4.11.3.5  [W]

`/SysNative`	 //since 4.11.3.5 [W]

`/RunAsLoggedOnUser` // since 4.12.4.31 ; works only inside 'userLoginScripts' [W]

The modifiers has to be seperated by 'winst' from the parameters. The following example call the 64Bit version of the powershell.exe.
[source,opsiscript]
----
ExecWith_do_64bit_stuff "%System%\WindowsPowerShell\v1.0\powershell.exe" winst /64Bit
----

Commands:
see manual

[[opsi-script-rc-files]]
=== Files [W/L/M]

ifdef::manual[see also : xref:sec-section.adoc#opsi-script-files[Files]]

Function: File Operations

`[Files`<identifier>`]`

Modifier [W]:

`/AllNTUserProfiles`

`/AllNTUserSendTo` [W]

`/32Bit`	 //since 4.10.8 [W]

`/64Bit`	 //since 4.10.8  [W]

`/SysNative`	 //since 4.10.8 [W]

Commands:

`checkTargetPath =` <destination directory> [W/L/M]

`copy` [Options] <source file(s)> <destination directory> [W/L/M]

some options:

`-s` recursive [W/L/M]

`-e` empty Subdirectories

`-V` version control against targetdir [W]

`-v`  version control against targetdir, %systemroot% and %system% *(do not use it)*  [W]

`-c` continue without reboot even if it is needed [W]

`-d` date check [W]

`-u` update [W]

`-x` extract [W]

`-w` weak (do not overwrite protected files) [W]

`-n` no overwrite [W]

`-r` copy read only attribute [W]

`-h` follow symlinks [L]  //since 4.11.6.14


`delete` [Options] <path[/mask]]  //  [W/L/M]

options: 

`-s` recursive 

`-f` force

`r` -del on reboot

`c` continue with out reboot

`d [n]` date

Example (*do not forget the trailing Backslash*): +
`delete -sf c:\delete_this_dir\`

`del` [Options] <path[/mask]]   //since 4.11.2.1 [W/L/M]

Works like `delete` but on +
`del -s -f c:\not-exists` +
if +c:\not-exists+ not exists it do not search complete +c:\+ for +not-exits+

Example (*you may forget the trailing Backslash*): +
`del -sf c:\delete_this_dir`

`chmod` <mode> <path>   //since 4.11.4.1 [L]

`hardlink` <existing file> <new file> // since 4.11.5 [W/L/M]

`symlink` <existing file> <new file> // since 4.11.5 [W/L/M] +
At Windows `symlink` is only available at NT6 and up.

`rename` <old filename> <new filename> // since 4.11.5 [W/L/M]

`move` <old filename> <new filename> // since 4.11.5 [W/L/M]

`zipfile` <source dir> <zip file> // since 4.12.1 [W/L/M]

`unzipfile` <zip file> <target dir>  // since 4.12.1 [W/L/M]

[[opsi-script-rc-registry]]
=== Registry [W]

ifdef::manual[see also : xref:sec-section.adoc#opsi-script-registry[Registry]]

Function: edit Registry

Standard method call: +
`[Registry`<identifier>`]` +
works with the specified section.

Alternative method call: +
`Registry  loadUnicodeTextFile(`<.reg file>`) /regedit` +
import the specified <.reg file>.

Alternative method call (deprecated): +
`Registry  loadUnicodeTextFile(`<.addreg file>`) /addreg` +
import the specified <.addreg file>.

Modifier:

`/AllNTUserDats`

`/32Bit`	 //since 4.10.8

`/64Bit`	 //since 4.10.8

`/SysNative`	 //since 4.10.8

Commands:

`OpenKey` <Key>
[source,opsiscript]
----
openkey [HKLM\Software\opsi.org]
----

`Set` <varname> `=` <registry type>:<value>

`Add` <varname> `=` <registry type>:<value>

Examples for registry types:
[source,opsiscript]
----
set "var1" = "my string"
set "var2" = REG_SZ:"my string"
set "var3" = REG_EXPAND_SZ:"%ProgramFiles%"
set "var4" = REG_DWORD:123	; Decimal
set "var5" = REG_DWORD:0x7b	; Hexadecimal
; REG_QWORD is supported since 4.12.6
set "var6" = REG_QWORD:59049772908	; Decimal
set "var7" = REG_QWORD:0xDBFA4076C	; Hexadecimal
set "var8" = REG_BINARY:00 01 02 0F 10
set "var9" = REG_MULTI_SZ:"A|BC|de"
----

`Supp` <varname> <list char> <supplement>
[source,opsiscript]
----
supp "Path" ; "C:\utils; %JAVABIN%"
----

`GetMultiSZFromFile` <varname> <file name>

`SaveValueToFile` <varname> <file name>

`DeleteVar` <varname>

`DeleteKey` <registry key>  (does since 4.11.2.1 also work with /AllNTUserDats)

[[opsi-script-rc-patches]]
=== Patches [W/L/M]

ifdef::manual[see also : xref:sec-section.adoc#opsi-script-patches[Patches]]

Function: edit Ini-files

`[Patches`<identifier>`]` <file name>

Modifier:

`/AllNTUserProfiles`  //since 4.11.3  [W]

Commands:

`add [`<section name>`]` <variable1> `=` <value1>

`set [`<section name>`]`<variable1> `=` <value1>

`addnew [`<section name>`]`<variable1> `=` <value1>

`change [`<section name>`]`<variable1> `=` <value1>

`del [`<section name>`]` <variable1> `=` <value1>

`del [`<section name>`]` <variable1>

`delsec [`<section name>`]`

`replace` <variable1>`=`<value1> <variable2>`=`<value2>

[[opsi-script-rc-patchtextfile]]
=== PatchTextFile [W/L/M]

ifdef::manual[see also : xref:sec-section.adoc#opsi-script-patchtextfile[PatchTextFile]]

Function: edit text files

`[PatchTextFile`<identifier>`]` <file name>

Modifier:

`/AllNTUserProfiles`  //since 4.11.3.4 [W]

`/encoding <encoding>` //since 4.12.4.17 [W/L/M]

Commands:

`Set_Mozilla_Pref (`"<preference type>", "<preference key>", "<preference value>"`)` +
'preference type' takes any value. +
Some examples for preference types: `pref`, `user_pref`, `lock_pref` or `lockPref`.

`AddStringListElement_To_Mozilla_Pref (`"<preference type>", "<preference key>", "<add value>"`)`

`Set_Netscape_User_Pref (`"<key>", "<value>"`)`  ('deprecated')

`AddstringListElement_To_Netscape_User_Pref`  ('deprecated')

`FindLine` <search string>

`FindLine_StartingWith` <search string>

`FindLine_Containing` <search string>

`GoToTop`

`AdvanceLine` [<number of lines>]

`GoToBottom`

`DeleteTheLine`

`AddLine_` <line> 	or `Add_Line_` <line>

`InsertLine` <line>    	or `Insert_Line_` <line>

`AppendLine` <line> 	or `Append_Line` <line>

`Append_File` <file name>

`Subtract_File` <file name>

`SaveToFile` <file name>

`Sorted`

`setKeyValueSeparator` <separator char> //since 4.11.4.4 [W/L/M]

`setValueByKey` <keystr> <valuestr> //since 4.11.4.4 [W/L/M]

[[opsi-script-rc-LinkFolder]]
=== LinkFolder [W/L/M]

ifdef::manual[see also : xref:sec-section.adoc#opsi-script-linkfolder[LinkFolder]]

Function: Startmenue + Desktop Icons

`[LinkFolder`<identifier>`]`

Commands:

`set_basefolder` <system folder>

`set_subfolder` <folder path> (at Linux set always "")

----
set_link
  name:            <link name>
  target:          <path and name of the program>
  parameters:      [command line arguments]
  working_dir:     [working directory]
  icon_file:       [path and name of icon file, default=target]
  icon_index:      [number of icon in icon file, default=0] [W]
  shortcut:        [keyboard shortcut for calling the target] [W]
  window_state:    [initial show state of the window] [W]
  link_categories: [list of categories] [L]
end_link
----

`delete_element`   <link name>

`delete_subfolder` <folder path> [W]

The predefined virtual system folders which can be used are at Windows: +
`desktop, sendto, startmenu, startup, programs, desktopdirectory`, +
`common_startmenu, common_programs, common_startup, common_desktopdirectory` +
and at Linux: +
`common_programs`,`common_startup`,`desktop`, `startup`

Predefined `link_categories` for Linux: +
`AudioVideo`, `Audio`, `Video`, `Development`, `Education`, `Game`, `Graphics`, `Network`, `Office`, `Settings`, `System`, `Utility`

Examples
[source,opsiscript]
----
set_basefolder common_desktopdirectory
set_subfolder ""
set_link
  name: opsi-winst
  target: "%ProgramFiles32Dir%\opsi.org\opsi-client-agent\opsi-winst\winst32.exe"
end_link
----

[source,opsiscript]
----
[LinkFolder_configed_lin]
set_basefolder common_programs
set_subfolder ""

set_link
  name: opsi-configed-Local
  target: java
  parameters: $parameter$
  icon_file: "$InstallDir$/opsi.png"
  link_categories: System;Utility;
end_link
----

The predefined virtual system folders: +
`desktop, sendto, startmenu, startup, programs, desktopdirectory` +
are pointing to the folders of the user that the script is running.
If you use it in a userLoginScript with the opsi 'User Profile Management' extension these virtual folders point to the folder of the user that just had logged in.

'shortcut' defaults to empty. // since 4.11.6.7 +
`shortcut` may be a combination of ['shift','alt','ctrl'] (not case sensitiv) divided by ' ', '-','+' an a 'Key' or a 'Virtual Key Code'. +
The 'Key' is a letter ('A' - 'Z') or a numeral ('0' - '9'). All other Keys must be given by there 'Virtual Key Code' identifier. To get these identifier (as well as the allowed combinations) just use the following helper program: +
http://download.uib.de/opsi4.0/helper/showkeys.exe

[[opsi-script-rc-OpsiServiceCall]]
=== OpsiServiceCall [W/L/M]

ifdef::manual[see also : xref:sec-section.adoc#opsi-script-opsiservicecall[OpsiServiceCall]]

Function: opsi-Service access

`[OpsiServiceCall`<identifier>`]`

Commands:
see manual

[[opsi-script-rc-PatchHosts]]
=== PatchHosts [W/L/M]

ifdef::manual[see also : xref:sec-section.adoc#opsi-script-patchhosts[PatchHosts]]

Function: hosts-files bearbeiten

`[PatchHosts`<identifier>`]`

Commands:

`setaddr`  <hostname> <IPaddress>

`setname` <IPaddress> <hostname>

`setalias` <hostname> <alias>

`setalias` <IPadresse> <alias>

`delalias` <hostname> <alias>

`delalias` <IPaddress> <alias>

`delhost` <hostname>

`delhost` <ipadresse>

`setComment` <ident> <comment>

[[opsi-script-rc-XML2-sections]]
=== XML2 Sections [W/L/M]

ifdef::manual[see also : xref:sec-section.adoc#opsi-script-xml2-sections[XML2 Sections]]

Function: edit XML files +
since 4.12.1.0

`[XML2`<identifier>`]`

Commands:

* `strictMode =`  (true/false) ; Default: false

* `openNode` <xml2 path> +
Open the given path as actual node. If the path does not exist, it will be created.

* `SetAttribute` <attr name> <attr value> +
At the actual node set <attr value> as value of <attr name>. If <attr name> does not exist, it will be created.

* `AddAttribute` <attr name> <attr value> +
If the attribute <attr name> does not exist at the actual node, it will be created with <attr value> as value.
If <attr name> already exists, nothing will be changed.

* `DeleteAttribute` <attr name> +
If the attribute <attr name> exists at the actual node, it will be deleted.

* `addNewNode` <node name> +
Create at the actual node a new sub node <node name> and make this new node to the actual node.

* `setNodeText` <string>

* `DeleteNode` <xml2 path>

* `gotoParentNode` +
Make the parent node to the actual node.

* `rootNodeOnCreate` = <node name>  // since 4.12.4.27 +
If the file does not exist, it will be created with <node name> as root node name.

* `setNodePair` <keyNodeName> <keyNodeTextContent> <valueNodeName> <valueNodeTextContent>  // since 4.12.4.28 +
Creates a <dict> entry like it is used in the Apple info.plist files.

Some notes on the command parameters:

* <xml2 path> `strictMode =false`: +
A line of xml node names without any attributes seprated by '` // `'. +
Example: `node_level-1_number-1 // node_level-2_B color="green"`

* <xml2 path> `strictMode =true`: +
A line of xml node names with all existing attributes seprated by '` // `'. +
Example: `node_level-1_number-1 // node_level-2_B color="green" count="65"`

see also : xref:reference-card.adoc#opsi-script-rc-xml2-functions[]

ifdef::manual[see also : xref:prim-section.adoc#opsi-script-xml2-functions[XML2 Functions]]

[[opsi-script-rc-XMLPatch]]
=== XMLPatch [W]

ifdef::manual[see also : xref:sec-section.adoc#opsi-script-xmlpatch[XMLPatch]]

Function: edit XML files +
Deprecated: please use xml2 sections: xref:reference-card.adoc#opsi-script-rc-XML2-sections[] +
and xml2 functions: xref:reference-card.adoc#opsi-script-rc-xml2-functions[]

`[XMLPatch`<identifier>`]`

Commands:
see manual

[[opsi-script-rc-ExecPython]]
=== ExecPython [W/L/M]

ifdef::manual[see also : xref:sec-section.adoc#opsi-script-execpython[ExecPython]]

Function: Execute section via python interpreter

`[ExecPython`<identifier>`]`

Commands:
see manual

[[opsi-script-rc-LdapSearch]]
=== LdapSearch [WLM]

ifdef::manual[see also : xref:sec-section.adoc#opsi-script-ldapsearch[LdapSearch]]

Function: read from LDAP

`[LdapSearch`<identifier>`]`

Commands:
see manual

[[opsi-script-rc-topic]]
== By Topic

[[opsi-script-rc-compare]]
=== Compare related functions [W/L/M]

`CompareDotSeparatedStrings(`<string1>, <string2>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#CompareDotSeparatedStrings_str[CompareDotSeparatedStrings_str]]

`CompareDotSeparatedStrings(`<str1>,<relation str>,<str2>`) : bool`  //since 4.11.5.2: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#CompareDotSeparatedStrings_bool[CompareDotSeparatedStrings_bool]]

`CompareDotSeparatedNumbers(`<string1>, <string2>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#CompareDotSeparatedNumbers_str[CompareDotSeparatedNumbers_str]]

`CompareDotSeparatedNumbers(`<str1>,<relation str>,<str2>`) : bool`  //since 4.11.5.2: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#CompareDotSeparatedNumbers_bool[CompareDotSeparatedNumbers_bool]]

`boolToString(`<boolean expression>`)` : bool string (true/false) // since 4.12.0.0 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#boolToString[boolToString]]

`stringToBool(`<string expression: true/false>`)` : boolean // since 4.12.0.0 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#stringToBool[stringToBool]]

[[opsi-script-rc-cryptfunc]]
=== Crypt / Hash related functions [W/L/M]

`DecStrToHexStr (` <decstring>, <hexlength>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#DecStrToHexStr[DecStrToHexStr]]

`HexStrToDecStr (`<hexstring>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#HexStrToDecStr[HexStrToDecStr]]

`base64EncodeStr(`<string>`) : string`  [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#base64EncodeStr[base64EncodeStr]]

`base64DecodeStr(`<string>`) : string`  [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#base64DecodeStr[base64DecodeStr]]

`RandomStr : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#RandomStr[RandomStr]]

`RandomIntStr(`<number str>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#RandomIntStr[RandomIntStr]]

`encryptStringBlow(`<keystring>,<datastring>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#encryptStringBlow[encryptStringBlow]]

`decryptStringBlow(`<keystring>,<datastring>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#decryptStringBlow[decryptStringBlow]]

`md5sumFromFile(`<path to file>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#md5sumFromFile[md5sumFromFile]]

`hashFromFile(`<FileName>, <Hashing Algorithm>`) : string` [W/L/M]  //since 4.12.5
ifdef::manual[see also : xref:prim-section.adoc#hashFromFile[hashFromFile]]

`isCertInstalledInSystem(`<label>`) : boolstring` [W/L/M] //since 4.12.4.37 
ifdef::manual[see also : <<isCertInstalledInSystem>>]

`importCertToSystem(`<filename>`) : noresult` [W/L/M] //since 4.12.4.37 
ifdef::manual[see also : <<importCertToSystem>>]

`removeCertFromSystem(`<label>`) : noresult` [W/L/M] //since 4.12.4.37 
ifdef::manual[see also : <<removeCertFromSystem>>]

`listCertificatesFromSystem` : stringlist` [W/L/M] //since 4.12.4.37 
ifdef::manual[see also : <<listCertificatesFromSystem>>]

[[opsi-script-rc-localfunc_library]]
=== Defined Functions and Libraries [W/L/M]

since 4.12.0.0

*Definition*
----
DefFunc <func name>([calltype parameter ptype][,[calltype parameter ptype]]) : ftype
<function body>
endfunc
----

Where:


* `DefFunc` is the keyword used to start defining a local function.

* '<func name>' is the freely choosen name of the function.

* 'calltype' is the call type of the parameter [`val` | `ref`]. `val`='Call by Value', `ref`='Call by Reference'. Default: `val`

* 'parameter' is the freely selected name of the call parameter which is available as a local variable within the function under the aforementioned name.

* 'ptype' is the type of data of the parameter and either `string` or `stringlist`.

* 'ftype' is the type of data of the function and either `string` ,`stringlist` or `void`. `void` declares that no result is returned.

* '<function body>' is the body of the function which must conform to the opsi-script syntax.

* `endfunc` is the keyword used to end defining a local function.


ifdef::manual[see also : xref:prim-section.adoc#opsi-script-commands-localfunctions[localfunctions]]

`importLib` <string expr>  ; import library // since 4.12.0.0 +
<string expr> : <file name>[.<file extension>][`::`<function name>] +
If no '.<file extension>' is given `.opsiscript` is used as default. +
If no '::<function name>' is given, all function from the given file will be imported.

<file name> is: +

* A complete path to an existing file. [W/L/M]

* An existing file in `%ScriptPath%` [W/L/M]

* A file in `%opsiScriptHelperPath%\lib` [W] +
Is equivalent to: '%ProgramFiles32Dir%\opsi.org\opsiScriptHelper\lib'

* An existing file in `%ScriptPath%/../lib` [W/L/M]

* An existing file in `%WinstDir%\lib` [W] or `/usr/share/opsi-script/lib` [L]

The tests for the location of the <file name> are done in the order above. 'opsi-script' uses the first file it finds that has a matching name.


ifdef::manual[see also :  xref:prim-section.adoc#opsi-script-commands-libraryfunctions[]]


[[opsi-script-rc-encodingfunc]]
=== Encoding related functions [W/L/M]

`encoding=`<encoding> // (default is system encoding) since 4.11.4.2
ifdef::manual[see also :  xref:configuration-options.adoc#encoding[encoding]]

`GetLocaleInfoMap : stringlist` [W]
ifdef::manual[see also :  xref:prim-section.adoc#GetLocaleInfoMap[GetLocaleInfoMap]]

`reencodestr(`<str>, <from>, <to>`) : string` //since 4.11.4.2 [W/L/M]
ifdef::manual[see also :  xref:prim-section.adoc#reencodestr[reencodestr]]

`reencodestrlist(`<list>, <from>, <to>`) : stringlist` //since 4.11.4.2 [W/L/M]
ifdef::manual[see also :  xref:prim-section.adoc#reencodestrlist[reencodestrlist]]

`fileHasBom (`<file name>) : boolean` //since 4.12.4.17 [W/L/M]
ifdef::manual[see also :  xref:prim-section.adoc#fileHasBom[fileHasBom]]

`loadUnicodeTextFile (`<file name>`) : stringlist` [W/L/M]
ifdef::manual[see also :  xref:prim-section.adoc#loadUnicodeTextFile[loadUnicodeTextFile]]

`loadTextFileWithEncoding(` <file name> `,` <encoding>`) : stringlist` //since 4.11.5 [W/L/M]
ifdef::manual[see also :  xref:prim-section.adoc#loadTextFileWithEncoding[loadTextFileWithEncoding]]

`strLoadTextFileWithEncoding (` <filename> , <encoding>`) : string` //since 4.11.4.6 [W/L/M]
ifdef::manual[see also :  xref:prim-section.adoc#strLoadTextFileWithEncoding[strLoadTextFileWithEncoding]]

`saveTextFileWithEncoding(`<list>, < filename>`,` <encoding>`) : bool` //since 4.11.6.4: true: if list is succesfully written to file [W/L/M]
ifdef::manual[see also :  xref:prim-section.adoc#saveTextFileWithEncoding[saveTextFileWithEncoding]]

`includelog` <file name> <tail size> [<encoding>]  ` : noresult`//since 4.11.4.1 [W/L/M]
ifdef::manual[see also :  xref:prim-section.adoc#includelog[includelog]]

ifdef::manual[see also :  xref:prim-section.adoc#opsi-script-encoding, '{opsi-script}' encoding[]]


[[opsi-script-rc-err]]
=== Error / Warning related functions [W/L/M]

`ExitOnError` = <boolean value> // (default=false)
ifdef::manual[see also : xref:prim-section.adoc#ExitOnError[ExitOnError]]

`ScriptErrorMessages` = <boolean value> // (default=true)

ifdef::manual[see also : xref:prim-section.adoc#ScriptErrorMessages[ScriptErrorMessages]]

ifdef::manual[see also : xref:cli-params.adoc#opsi-script-configs_ScriptErrorMessages[Central configuration via opsi Configs]]

`FatalOnSyntaxError =` <boolean value>  // (default=true) since 4.11.3.2
ifdef::manual[see also : xref:prim-section.adoc#FatalOnSyntaxError[FatalOnSyntaxError]]

`FatalOnRuntimeError =` <boolean value>  // (default=false) since 4.11.3.2
ifdef::manual[see also : xref:prim-section.adoc#FatalOnRuntimeError[FatalOnRuntimeError]]

`LogError` <string> or `LogError` = <const string>
ifdef::manual[see also : xref:prim-section.adoc#LogError[LogError]]

`LogWarning` <string> or `LogWarning` = <const string>
ifdef::manual[see also : xref:prim-section.adoc#LogWarning[LogWarning]]

`isFatalError` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#isFatalError[isFatalError]]

`isFatalError` <string>  //since 4.11.3.2 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#isFatalError[isFatalError]]

`markErrorNumber`
ifdef::manual[see also : xref:prim-section.adoc#markErrorNumber[markErrorNumber]]

`errorsOccurredSinceMark` <relation> <integer> : boolean
ifdef::manual[see also : xref:prim-section.adoc#errorsOccurredSinceMark[errorsOccurredSinceMark]]

[source,opsiscript]
----
markErrorNumber
comment "log error and thereby increase the error counter"
if errorsOccurredSinceMark > 0
	comment "There was an error ..."
endif
----

`getLastExitCode : string (exitcode)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getLastExitCode[getLastExitCode]]

`shellCall (`<command string>`) : string (exitcode)` //since 4.11.6.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#shellCall_str[shellCall_str]]

`processCall(`<string>`) : string (exitcode)` //since 4.11.6.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#processCall[processCall]]

`getLastServiceErrorClass`  : string
ifdef::manual[see also : xref:prim-section.adoc#getLastServiceErrorClass[getLastServiceErrorClass]]

`getLastServiceErrorMessage`  : string
ifdef::manual[see also : xref:prim-section.adoc#getLastServiceErrorMessage[getLastServiceErrorMessage]]


[[opsi-script-rc-filefunc]]
=== File related functions [W/L/M]

`strLoadTextFile (`<file name>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#strLoadTextFile[strLoadTextFile]]

`strLoadTextFileWithEncoding (` <filename> , <encoding>`) : string` //since 4.11.4.6 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#strLoadTextFileWithEncoding[strLoadTextFileWithEncoding]]

`loadTextFile (`<file name>`) : stringlist` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#loadTextFile[loadTextFile]]

`loadUnicodeTextFile (`<file name>`) : stringlist` [W]
ifdef::manual[see also : xref:prim-section.adoc#loadUnicodeTextFile[loadUnicodeTextFile]]

`loadTextFileWithEncoding(` <file name> `,` <encoding>`) : stringlist` //since 4.11.5 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#loadTextFileWithEncoding[loadTextFileWithEncoding]]

`fileHasBom (`<file name>) : boolean` //since 4.12.4.17 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#fileHasBom[fileHasBom]]

`FileExists (`<file name>`) : bool` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#FileExists[FileExists]]

`FileExists32 (`<file name>`) : bool` [W]
ifdef::manual[see also : xref:prim-section.adoc#FileExists[FileExists]]

`FileExists64 (`<file name>`) : bool` [W]
ifdef::manual[see also : xref:prim-section.adoc#FileExists[FileExists]]

`FileExistsSysNative (`<file name>`) : bool` [W]
ifdef::manual[see also : xref:prim-section.adoc#FileExists[FileExists]]

`DirectoryExists` (<folder path> [,<access str>]) : boolean //since 4.12.1 [W/L/M] +
'sysnative' is the default for <access str>. Otherwise, it can be '32bit', '64bit' or 'sysnative'
ifdef::manual[see also : xref:prim-section.adoc#DirectoryExists[DirectoryExists]]

`FileOrFolderExists` (<file or folder path> [,<access str>]) : boolean [W/L/M]
'sysnative' is the default for <access str>. Otherwise, it can be '32bit', '64bit' or 'sysnative'
ifdef::manual[see also : xref:prim-section.adoc#FileOrFolderExists[FileOrFolderExists]]

`fileIsSymlink (`<file name>`) : bool` // since 4.12.4.21 [W/L/M] +
ifdef::manual[see also : xref:prim-section.adoc#fileIsSymlink[fileIsSymlink]]

`resolveSymlink (`<file name>`) : <file name>` // since 4.12.4.21 [W/L/M] +
ifdef::manual[see also : xref:prim-section.adoc#resolveSymlink[resolveSymlink]]

`listFiles (`<Path>, <Searchmask> , <SearchSubDirectories>, <[Redirection]>`) : stringlist` //since 4.12.3 [W/L/M]
[source,opsiscript]
----
Set $Filelist$ = listFiles("C:\windows\system32","*.ico;*.dll","False","64bit")
----
ifdef::manual[see also : xref:prim-section.adoc#listFiles[listFiles]]

`forcePathDelims (`<path string>`) : <path string>` // since 4.12.4.21 [W/L/M] +
ifdef::manual[see also : xref:prim-section.adoc#forcePathDelims[forcePathDelims]]

`LineExistsIn (`<string>, <file name>`) : bool` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#LineExistsIn[LineExistsIn]]

`LineBeginning_ExistsIn (`<string>, <file name>`) : bool` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#LineBeginning_ExistsIn[LineBeginning_ExistsIn]]

`LineContaining_ExistsIn(` <string>, <file name> `) : bool` //since 4.11.4.10 [W/L/M] +
true: if a in <file name> contains <string>
ifdef::manual[see also : xref:prim-section.adoc#LineContaining_ExistsIn[LineContaining_ExistsIn]]

`saveTextFile(`<list>, < filename>`) : bool` //since 4.11.4.4 [W/L/M] +
true: if list is succesfully written to file
ifdef::manual[see also : xref:prim-section.adoc#saveTextFile[saveTextFile]]

`saveTextFileWithEncoding(`<list>, < filename>`,` <encoding>`) : bool` //since 4.11.6.4 [W/L/M] +
true: if list is succesfully written to file
ifdef::manual[see also : xref:prim-section.adoc#saveTextFileWithEncoding[saveTextFileWithEncoding]]

`getFileInfoMap(` <file name> `) : stringlist` [W]
ifdef::manual[see also : xref:prim-section.adoc#getFileInfoMap[getFileInfoMap]]

`getFileInfoMap32(` <file name> `) : stringlist` //since 4.11.6.6 [W]
ifdef::manual[see also : xref:prim-section.adoc#getFileInfoMap[getFileInfoMap]]

`getFileInfoMap64(` <file name> `) : stringlist` //since 4.11.6.6 [W]
ifdef::manual[see also : xref:prim-section.adoc#getFileInfoMap[getFileInfoMap]]

`getFileInfoMapSysnative(` <file name> `) : stringlist` //since 4.11.6.6 [W]
ifdef::manual[see also : xref:prim-section.adoc#getFileInfoMap[getFileInfoMap]]

`ExtractFilePath (`<path>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#ExtractFilePath[ExtractFilePath]]

`ExtractFileExtension (`<path>`) : string` [W/L/M]  //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#ExtractFileExtension[ExtractFileExtension]]

`ExtractFileName (`<path>`) : string` [W/L/M]  //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#ExtractFileName[ExtractFileName]]

see also: xref:reference-card.adoc#opsi-script-rc-files[]

see also: xref:reference-card.adoc#opsi-script-rc-patchtextfile[]

[[opsi-script-rc-inifunc]]
=== Ini file related functions [W/L/M]

`GetValueFromInifile (`<file path>, <section>, <key>, <default value>, OPTIONAL <encoding>`) : string` [W/L/M] +
ifdef::manual[see also : xref:prim-section.adoc#GetValueFromInifile[GetValueFromInifile]]

`getSectionNames(`<ini-file>`) : stringlist` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getSectionNames[getSectionNames]]

`GetSectionFromInifile(`<ini-file>`) : stringlist` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetSectionFromInifile[GetSectionFromInifile]]

`getValue(`<key string>, <hash string list>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getValue[getValue]]

`getValueBySeparator(`<key string>,<separator string>,<hash string list>`) : string` //since 4.11.2.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getValueBySeparator[getValueBySeparator]]

`setValueByKey(`<key>, <value>, <targetlist> [, <separator (char)>]`)` : stringlist [W/L/M]
ifdef::manual[see also : <<setValueByKey>>]

`getValueFromFile(`<key string>, <file name>`) : string` //since 4.11.4.4 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getValueFromFile[getValueFromFile]]

`getValueFromFileBySeparator(`<key string>,<separator string>,<file name>`) : string` //since 4.11.4.4 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getValueFromFileBySeparator[getValueFromFileBySeparator]]

see also: <<opsi-script-rc-patches>>



[[opsi-script-rc-interaction]]
=== Interaction [W/L/M]

`Pause` <string> or `Pause` = <const string>
ifdef::manual[see also : xref:prim-section.adoc#Pause[Pause]]

`Stop` <string> or `stop` = <const string>
ifdef::manual[see also : xref:prim-section.adoc#Stop[Stop]]

`setActionProgress <string>` : noresult //since 4.11.3 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#setActionProgress[setActionProgress]]

`Message` <string> or `Message` = <const string>
ifdef::manual[see also : xref:prim-section.adoc#Message[Message]]

`ShowMessageFile` <string>
ifdef::manual[see also : xref:prim-section.adoc#ShowMessageFile[ShowMessageFile]]

`ShowBitMap`  [<file name>] [<sub title>]
ifdef::manual[see also : xref:prim-section.adoc#ShowBitMap[ShowBitMap]]

`stringinput(`< message str>,< boolstr confidential>`) : string` //since 4.12.1.2 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#stringinput[stringinput]]

`editmap(`< strlist>`) : stringlist` //since 4.12.1.2 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#editmap[editmap]]


[[opsi-script-rc-license-management]]
=== License Management related functions [W/L/M]

`DemandLicenseKey(` poolId [, productId [,windowsSoftwareId]] `) : string`
[source,opsiscript]
----
set $mykey$ = DemandLicenseKey ("", "office2007")
----
ifdef::manual[see also : xref:prim-section.adoc#DemandLicenseKey[DemandLicenseKey]]

`FreeLicense (`poolId [, productId [,windowsSoftwareId]]`) : string`
[source,opsiscript]
----
set $result$ = FreeLicense("", "office2007")
----
ifdef::manual[see also : xref:prim-section.adoc#FreeLicense[FreeLicense]]

`getLastServiceErrorClass`  : string
ifdef::manual[see also : xref:prim-section.adoc#getLastServiceErrorClass[getLastServiceErrorClass]]

`getLastServiceErrorMessage`  : string
ifdef::manual[see also : xref:prim-section.adoc#getLastServiceErrorMessage[getLastServiceErrorMessage]]

`opsiLicenseManagementEnabled` : bool
ifdef::manual[see also : xref:prim-section.adoc#opsiLicenseManagementEnabled[opsiLicenseManagementEnabled]]

[[opsi-script-rc-linux-specific]]
=== Linux specific functions [W/L/M]

`GetOS : string`  // 'Linux' or 'Windows_NT' or 'macos'  [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetOS[GetOS]]

`getLinuxDistroType : string`  // 'debian' or 'redhat' or 'suse'  (see `getLinuxVersionMap`) [L]
ifdef::manual[see also : xref:prim-section.adoc#getLinuxDistroType[getLinuxDistroType]]

`getLinuxVersionMap : stringlist`  //since 4.11.4  [L]
ifdef::manual[see also : xref:prim-section.adoc#getLinuxVersionMap[getLinuxVersionMap]]

`chmod` in Files sections [L/M]
ifdef::manual[see also : xref:sec-section.adoc#opsi-script-files-commands[Commands]]

`waitForPackageLock(`<wait_seconds>,<abort_on_timeout>`) : bool`  // since 4.11.6.1 [L]
ifdef::manual[see also : xref:prim-section.adoc#waitForPackageLock[waitForPackageLock]]

`importlib "uib_lin_install"`  :

`cleanupPackageSystem : void`  //since 4.13.4  [L]
ifdef::manual[see also : xref:libraries.adoc#cleanupPackageSystem[cleanupPackageSystem]]

`installupdates : string`  //since 4.13.4  [L]
ifdef::manual[see also : xref:libraries.adoc#installupdates[installupdates]]

`debinstall($packagelist$ : stringlist) : string`  //since 4.13.4  [L]
ifdef::manual[see also : xref:libraries.adoc#debinstall[debinstall]]

`redinstall($packagelist$ : stringlist) : string`  //since 4.13.4  [L]
ifdef::manual[see also : xref:libraries.adoc#redinstall[redinstall]]

`suseinstall($packagelist$ : stringlist) : string`  //since 4.13.4  [L]
ifdef::manual[see also : xref:libraries.adoc#suseinstall[suseinstall]]

`ucsinstall($packagelist$ : stringlist) : string`  //since 4.13.4  [L]
ifdef::manual[see also : xref:libraries.adoc#ucsinstall[ucsinstall]]

`genericLinInstall($packagelist$ : stringlist) : string` +
ifdef::manual[see also : xref:libraries.adoc#genericLinInstall[genericLinInstall]]

`linuxInstallOneOf($packagelist$ : stringlist) : string` +
ifdef::manual[see also : xref:libraries.adoc#genericLinInstall[genericLinInstall]]

`isOneInstalled($packagelist$ : stringlist) : string` +
ifdef::manual[see also : xref:libraries.adoc#linuxInstallOneOf[linuxInstallOneOf]]

`linuxInstallOneFile($packagefile$ : string) : string` +
ifdef::manual[see also : xref:libraries.adoc#linuxInstallOneFile[linuxInstallOneFile]]

`linuxRemoveOnePackage($packagename$ : string) : string` +
ifdef::manual[see also : xref:libraries.adoc#linuxRemoveOnePackage[linuxRemoveOnePackage]]

`linuxRemoveOneOf($packagelist$ : stringlist) : string` +
ifdef::manual[see also : xref:libraries.adoc#linuxRemoveOneOf[linuxRemoveOneOf]]


[[opsi-script-rc-logging]]
=== Logging related functions [W/L/M]

`SetLogLevel` = <number> or `SetLogLevel` = <string> // (default=6)
[source,opsiscript]
----
SetLogLevel = 7
SetLogLevel = "7"
----
ifdef::manual[see also : xref:prim-section.adoc#SetLogLevel[SetLogLevel]]
ifdef::manual[see also : xref:cli-params.adoc#opsi-script-configs_default_loglevel[]]
ifdef::manual[see also : xref:cli-params.adoc#opsi-script-configs_force_min_loglevel[]]

`SetDebug_Lib` = <boolean value> // (default=false)
ifdef::manual[see also : xref:prim-section.adoc#SetDebugLib[SetDebugLib]]

`Message` <string> or `Message` = <const string>
ifdef::manual[see also : xref:prim-section.adoc#Message[Message]]

`comment` <string> or `comment` = <const string>
ifdef::manual[see also : xref:prim-section.adoc#comment[comment]]

`LogError` <string> or `LogError` = <const string>
ifdef::manual[see also : xref:prim-section.adoc#scriptWasExecutedBefore[scriptWasExecutedBefore]]

`LogWarning` <string> or `LogWarning` = <const string>
ifdef::manual[see also : xref:prim-section.adoc#LogError[LogError]]

`includelog` <file name> <tail size>   //since 4.11.2.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#includelog[includelog]]

`includelog` <file name> <tail size> [<encoding>]  //since 4.11.4.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#includelog[includelog]]

[source,opsiscript]
----
includelog "%Scriptpath%\test-files\10lines.txt" "5"
----

`SetConfidential` <secret string> //since 4.11.3.5 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#setConfidential[setConfidential]]

`asConfidential(` <secret string expression> `) : string` //since 4.12.0.16 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#asConfidential_str[asConfidential_str]]

`asConfidential(` <secret stringlist expression> `) : stringlist` //since 4.12.4.15 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#asConfidential_list[asConfidential_list]]

`forceLogInAppendMode =` <boolean value>  // (default=false); if true, log will be send in append mode . //since 4.12.3.6
ifdef::manual[see also : xref:prim-section.adoc#forceLogInAppendMode[forceLogInAppendMode]]


*opsi-configs*

ifdef::manual[see also : xref:cli-params.adoc#opsi-script-configs[Central configuration via opsi Configs]]

`opsi-script.global.debug_prog` : boolean ; if false: only Warnings and Errors from program logging; default: false +
ifdef::manual[see also : xref:cli-params.adoc#opsi-script-configs_debug_prog[Central configuration via opsi Configs]]

`opsi-script.global.debug_lib` : boolean ; if false: only Warnings and Errors from library logging; default: false +
ifdef::manual[see also : xref:cli-params.adoc#opsi-script-configs_debug_lib[Central configuration via opsi Configs]]

`opsi-script.global.default_loglevel` : intstr ; set the default log level; default: '6' +
ifdef::manual[see also : xref:cli-params.adoc#opsi-script-configs_default_loglevel[Central configuration via opsi Configs]]

`opsi-script.global.force_min_loglevel` : intstr ; set the minimal loglevel; default: '0' +
ifdef::manual[see also : xref:cli-params.adoc#opsi-script-configs_force_min_loglevel[Central configuration via opsi Configs]]

`opsi-script.global.ScriptErrorMessages` : boolean ; overwrites the opsi-script internal default; default: false +
ifdef::manual[see also : xref:cli-params.adoc#opsi-script-configs_ScriptErrorMessages[ScriptErrorMessages]]

`opsi-script.global.AutoActivityDisplay` : boolean ; overwrites the opsi-script internal default; default: true +
ifdef::manual[see also : xref:cli-params.adoc#opsi-script-configs_AutoActivityDisplay[AutoActivityDisplay]]

`opsi-script.global.SupressSystemEncodingWarning` : boolean ; suppress some encoding warnings; default: false +
ifdef::manual[see also : xref:cli-params.adoc#opsi-script-configs_SupressSystemEncodingWarning[SupressSystemEncodingWarning]]

`opsi-script.global.ReverseProductOrderByUninstall` : boolean ; product list is reordered for uninstall; default: false +
ifdef::manual[see also : xref:cli-params.adoc#opsi-script-configs_ReverseProductOrderByUninstall[ReverseProductOrderByUninstall]]

`opsi-script.global.log_rotation_count` : boolean ; number of opsi-script.log backups; default: 8 +
ifdef::manual[see also : xref:cli-params.adoc#opsi-script-configs_log_rotation_count[log_rotation_count]]

`opsi-script.global.writeProductLogFile` : boolean ; logs for every single opsi product; default: false +
ifdef::manual[see also : xref:cli-params.adoc#opsi-script-configs_writeProductLogFile[writeProductLogFile]]

[[opsi-script-rc-macos-specific]]
=== macOS specific functions [W/L/M]

`GetOS : string`  // 'Linux' or 'Windows_NT' or 'macos'  [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetOS[GetOS]]

`getMacosVersionInfo : string` //macOS Version Information  //since 4.12.1.0 [M]
ifdef::manual[see also : xref:prim-section.adoc#getMacosVersionInfo[getMacosVersionInfo]]

`getMacosVersionMap : stringlist`  //macOS Version map  //since 4.12.1.0 [M]
ifdef::manual[see also : xref:prim-section.adoc#getMacosVersionMap[getMacosVersionMap]]

`GetSystemType : string`    //OS Architecture ("64 Bit System" or "x86 System") [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetSystemType[GetSystemType]]

`getOSArchitecture` // OS Architecture (x86_32 / x86_64/ arm_64) //since 4.12.4.17 [W/L/M] +
ifdef::manual[see also : xref:prim-section.adoc#getOSArchitecture[getOSArchitecture]]


`importlib "uib_macosinstalllib"`  :

`install_macos_app($myapp$ : string) : string`  [M] +
ifdef::manual[see also : xref:libraries.adoc#install_macos_app>>]

`install_macos_pkg($mypkg$ : string) : string`  [M] +
ifdef::manual[see also : xref:libraries.adoc#install_macos_pkg>>]

`install_macos_dmg($mydmg$ : string) : string`  [M] +
ifdef::manual[see also : xref:libraries.adoc#install_macos_dmg>>]

`install_macos_zip($myzip$ : string) : string`  [M] +
ifdef::manual[see also : xref:libraries.adoc#install_macos_zip>>]

`install_macos_generic($myfile$ : string) : string`  [M]
ifdef::manual[see also : xref:libraries.adoc#install_macos_generic[install_macos_generic]]

[[opsi-script-rc-networkfunc]]
=== Network related functions [W/L/M]

`GetHostsName (`<hostaddress> `) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetHostsName[GetHostsName]]

`GetHostsAddr (`<hostname> `) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetHostsAddr[GetHostsAddr]]

`GetMyIpByTarget(`<target ip addr>`) : string` //since 4.11.3.2 /4.11.6 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetMyIpByTarget[GetMyIpByTarget]]

`GetIpByName(`<ip addr / ip name>`) : string` //since 4.11.3.2 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetIpByName[GetIpByName]]

`isValidIP4 (<ip4adr>) : boolean`     //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#isValidIP4[isValidIP4]]

`isValidIP4Network (<ip4adr>, <netmask>) : boolean`     //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#isValidIP4Network[isValidIP4Network]]

`isValidIP4Host (<ip4adr>, <netmask>) : boolean`      //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#isValidIP4Host[isValidIP4Host]]

`getIP4NetworkByAdrAndMask (<ip4adr>, <netmask>) : string`     //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#getIP4NetworkByAdrAndMask[getIP4NetworkByAdrAndMask]]

`getDefaultNetmaskByIP4adr (<ip4adr>) : string`     //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#getDefaultNetmaskByIP4adr[getDefaultNetmaskByIP4adr]]

`parseUrl(<url string>) : stringlist`  //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#parseUrl[parseUrl]]

`createUrl(<urlcomponents list>) : string`  //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#createUrl[createUrl]]

`isPingReachable(<host>) : boolean`     //since 4.12.3.6
ifdef::manual[see also : xref:prim-section.adoc#isPingReachable[isPingReachable]]

`isValidFQDN(<domain name>) : boolean`     //since 4.12.4.4 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#isValidFQDN[isValidFQDN]]

`cidrToNetmask (<string>) : string`     //since 4.12.4.37
ifdef::manual[see also : <<cidrToNetmask>>]

`netmaskToCidr (<string>) : string`     //since 4.12.4.37
ifdef::manual[see also : <<netmaskToCidr>>]

`isCertInstalledInSystem(`<label>`) : boolstring` [W/L/M] //since 4.12.4.37 
ifdef::manual[see also : <<isCertInstalledInSystem>>]

`importCertToSystem(`<filename>`) : noresult` [W/L/M] //since 4.12.4.37 
ifdef::manual[see also : <<importCertToSystem>>]

`removeCertFromSystem(`<label>`) : noresult` [W/L/M] //since 4.12.4.37 
ifdef::manual[see also : <<removeCertFromSystem>>]

`listCertificatesFromSystem(`<label>`) : stringlist` [W/L/M] //since 4.12.4.37 
ifdef::manual[see also : <<listCertificatesFromSystem>>]

[[opsi-script-rc-numberfunc]]
=== Number related functions [W/L/M]

`isNumber(`<str>`) : bool` //since 4.11.3: true if <str> represents an integer [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#isNumber[isNumber]]

`CompareDotSeparatedNumbers(`<str1>,<relation str>,<str2>`) : bool`  //since 4.11.5.2: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#CompareDotSeparatedNumbers_bool[CompareDotSeparatedNumbers_bool]]

`CompareDotSeparatedNumbers(`<string1>, <string2>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#CompareDotSeparatedNumbers_str[CompareDotSeparatedNumbers_str]]

`calculate(`<arithmetic string expression>`) : string (number)` // since 4.11.3.5 [W/L/M] +
knows: `+-*/()`
ifdef::manual[see also : xref:prim-section.adoc#calculate[calculate]]

`DecStrToHexStr (` <decstring>, <hexlength>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#DecStrToHexStr[DecStrToHexStr]]

`HexStrToDecStr (`<hexstring>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#HexStrToDecStr[HexStrToDecStr]]

`RandomIntStr(`<number str>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#RandomIntStr[RandomIntStr]]

[[opsi-script-rc-OSfunc]]
=== Operating System related functions [W/L/M]

`GetOS : string`  // 'Linux' or 'Windows_NT' or 'macos'  [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetOS[GetOS]]

`GetMsVersionInfo : string` //Windows Version Information [W]
ifdef::manual[see also : xref:prim-section.adoc#GetMsVersionInfo[GetMsVersionInfo]]

`GetMSVersionMap : stringlist` [W]
ifdef::manual[see also : xref:prim-section.adoc#GetMSVersionMap[GetMSVersionMap]]

`getLinuxDistroType : string`  // 'debian' or 'redhat' or 'suse'  (see `getLinuxVersionMap`) [L]
ifdef::manual[see also : xref:prim-section.adoc#getLinuxDistroType[getLinuxDistroType]]

`getLinuxVersionMap : stringlist`  //since 4.11.4  [L]
ifdef::manual[see also : xref:prim-section.adoc#getLinuxVersionMap[getLinuxVersionMap]]

`getMacosVersionInfo : string` //macOS Version Information  //since 4.12.1.0 [M]
ifdef::manual[see also : xref:prim-section.adoc#getMacosVersionInfo[getMacosVersionInfo]]

`getMacosVersionMap : stringlist`  //macOS Version map  //since 4.12.1.0 [M]
ifdef::manual[see also : xref:prim-section.adoc#getMacosVersionMap[getMacosVersionMap]]

`GetSystemType : string`    //OS Architecture ("64 Bit System" or "x86 System") [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetSystemType[GetSystemType]]

`getOSArchitecture` // OS Architecture (x86_32 / x86_64/ arm_64) //since 4.12.4.17 [W/L/M] +
ifdef::manual[see also : xref:prim-section.adoc#getOSArchitecture[getOSArchitecture]]

`getListFromWMI(`<wmi namespace str>,<wmi class str>,<property list>,<condition str>`) : stringlist` //since 4.12.1.0 [W]
ifdef::manual[see also : xref:prim-section.adoc#getListFromWMI[getListFromWMI] and xref:prim-section.adoc#opsi-wmi-test.exe[opsi-wmi-test.exe] (small helper application works like getListFromWMI)]

`EnvVar (`<environment variable>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#EnvVar[EnvVar]]

`getProfilesDirList : stringlist` //since 4.11.3.2 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getProfilesDirList[getProfilesDirList]]

`listFiles (`<Path>, <Searchmask> , <SearchSubDirectories>, <[Redirection]>`) : stringlist` //since 4.12.3 [W/L/M]
[source,opsiscript]
----
Set $Filelist$ = listFiles("C:\windows\system32","*.ico;*.dll","False","64bit")
----
ifdef::manual[see also : xref:prim-section.adoc#listFiles[listFiles]]

`which(`<command in path>`) : string` (command with path) //since 4.12.3.6 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#which[which]]

`runningAsAdmin : bool`    //since 4.11.1.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#runningAsAdmin[runningAsAdmin]]

`runningOnUefi : bool`` //since 4.11.4.3: true: if the running OS was booted in UEFI mode [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#runningOnUefi[runningOnUefi]]

`runningInPE : bool`` //since 4.12.0.13: true: if the running OS is a Windows PE [W]
ifdef::manual[see also : xref:prim-section.adoc#runningInPE[runningInPE]]

`runningInWAnMode` //since 4.12.4.16: true: if opsiserver = localhost [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#runningInWAnMode[runningInWAnMode]]

`isDriveReady(`<drive letter>`) : bool`` //since 4.11.4.4: true: if the drive can be accessed [W]
ifdef::manual[see also : xref:prim-section.adoc#isDriveReady[isDriveReady]]

`runningWithGui : bool`` //since 4.12.3.6: true: if the running OS with GUI (at Win+Mac always true)[M/L/W]
ifdef::manual[see also : xref:prim-section.adoc#runningWithGui[runningWithGui]]

[[opsi-script-rc-json]]
=== opsiservicecall and json Related functions [W/L/M]

`jsonIsValid(`<jsonstr>`) : boolean`  //since 4.11.6: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#jsonIsValid[jsonIsValid]]

`jsonIsArray(`<jsonstr>`) : boolean`  //since 4.11.6: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#jsonIsArray[jsonIsArray]]

`jsonIsObject(`<jsonstr>`) : boolean`  //since 4.11.6: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#jsonIsObject[jsonIsObject]]

`jsonAsObjectHasKey(`<jsonstr>,<keystr>`) : boolean`  //since 4.11.6: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#jsonAsObjectHasKey[jsonAsObjectHasKey]]

`jsonAsArrayCountElements(`<jsonstr>`) : intstr`  //since 4.11.6: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#jsonAsArrayCountElements[jsonAsArrayCountElements]]

`jsonAsObjectCountElements(`<jsonstr>`) : intstr`  //since 4.11.6: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#jsonAsObjectCountElements[jsonAsObjectCountElements]]

`jsonAsArrayGetElementByIndex(`<jsonstr>, <indexstr>`) : jsonstring`  //since 4.11.6: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#jsonAsArrayGetElementByIndex[jsonAsArrayGetElementByIndex]]

`jsonAsObjectGetValueByKey(`<jsonstr>, <keystr>`) : valuestring`  //since 4.11.6: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#jsonAsObjectGetValueByKey[jsonAsObjectGetValueByKey]]

`jsonAsObjectSetValueByKey(`<jsonstr>, <keystr>,<valuestring>`) : jsonstring`  //since 4.11.6: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#jsonAsObjectSetValueByKey[jsonAsObjectSetValueByKey]]

`jsonAsObjectSetStringtypeValueByKey(`<jsonstr>, <keystr>,<valuestring>`) : jsonstring`  //since 4.11.6: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#jsonAsObjectSetStringtypeValueByKey[jsonAsObjectSetStringtypeValueByKey]]

`jsonAsObjectDeleteByKey(`<jsonstr>, <keystr>`) : jsonstring`  //since 4.11.6.4: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#jsonAsObjectDeleteByKey[jsonAsObjectDeleteByKey]]

`jsonAsArrayPutObjectByIndex(`<jsonstr>, <indexstr>, <objectstr>`) : jsonstring`  //since 4.11.6: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#jsonAsArrayPutObjectByIndex[jsonAsArrayPutObjectByIndex]]

`jsonAsArrayDeleteObjectByIndex(`<jsonstr>, <indexstr>`) : jsonstring`  //since 4.11.6.4: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#jsonAsArrayDeleteObjectByIndex[jsonAsArrayDeleteObjectByIndex]]

`jsonAsArrayToStringList(`<jsonstr>`) : stringlist`  //since 4.11.6: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#jsonAsArrayToStringList[jsonAsArrayToStringList]]

`jsonAsObjectGetKeyList(`<jsonstr>`) : stringlist`  //since 4.11.6: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#jsonIsArray[jsonIsArray]]

`jsonStringListToJsonArray(`<strlist>`) : jsonstr`  //since 4.11.6: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#jsonAsObjectGetKeyList[jsonAsObjectGetKeyList]]

`convert2Jsonstr(`<string>`)`  //since 4.10.8.3


see also: OpsiServiceCall  <<opsi-script-rc-OpsiServiceCall>>

ifdef::manual[see also : xref:prim-section.adoc#opsi-script-json[OpsiServiceCall and json Related functions]]

ifdef::manual[see also : xref:sec-section.adoc#opsi-script-opsiservicecall[OpsiServiceCall Sections]]

[[opsi-script-rc-opsifunc]]
=== opsi related functions [W/L/M]

`getProductMap : stringlist`  // since 4.11.2.4  [W/L/M] +
keys are: id, name, description, advice, productversion, packageversion, priority, installationstate, lastactionrequest, lastactionresult, installedversion, installedpackage, installedmodificationtime,actionrequest
ifdef::manual[see also : xref:prim-section.adoc#getProductMap[getProductMap]]

`getProductPropertyList(`<propname>,<default value>`) : stringlist`  //since 4.11.3 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getProductPropertyList[getProductPropertyList]]

`GetProductProperty (`<PropertyName>, <DefaultValue> `) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetProductProperty[GetProductProperty]]

`GetConfidentialProductProperty (` <PropertyName>, <DefaultValue>`) : string` //since 4.11.5.2 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetConfidentialProductProperty[GetConfidentialProductProperty]]

`setActionProgress <string>` : noresult //since 4.11.3 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#setActionProgress[setActionProgress]]

`retrieveSection (`<section name>`) : stringlist` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#retrieveSection[retrieveSection]]

`replaceOpsiConstants(`<string list>`) : stringlist`  //since 4.12.3.6 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#replaceOpsiConstants_list[replaceOpsiConstants_list]]

`replaceOpsiConstants(`<string>`) : string`  //since 4.12.3.6 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#replaceOpsiConstants_string[replaceOpsiConstants_string]]

`runningInWanMode` : boolean //since 4.12.4.17 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#runningInWanMode[runningInWanMode]]

`reloadProductList` //since 4.12.6.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#reloadProductList[reloadProductList]]


[[opsi-script-rc-process]]
=== Process and Script Related functions

`Killtask` <process name> ` : noresult` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#Killtask[Killtask]]

`ChangeDirectory` <directory>  ` : noresult`  //since 4.11.2.6 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#ChangeDirectory[ChangeDirectory]]

`GetProcessList : stringlist`  //since 4.11.1.2; gives list of exename;pid;dom/user [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetProcessList[GetProcessList]]

`processIsRunning(`<process name>`) : boolean`  //since 4.11.6.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#processIsRunning[processIsRunning]]

`isProcessChildOf(<searchprocstr>, <parentprocstr>): bool`  //since 4.12.4.35  [W/L/M] +
ifdef::manual[see also : <<isProcessChildOf>>]

`shellCall (`<command string>`) : stringlist (output)` //since 4.11.4.2 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#shellCall_list[shellCall_list]]

[source,opsiscript]
----
set $list$= shellCall('net start')
----


`shellCall (`<command string>`) : noresult` //since 4.11.6.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#shellCall[shellCall]]

`shellCall (`<command string>`) : string (exitcode)` //since 4.11.6.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#shellCall_str[shellCall_str]]

`powershellcall (`<commandstr> [,<access str>='sysnative' [,<policy bool str>='true']]`) : stringlist (output)` //since 4.12.0.16 [W] +
`powershellCall(`<commandstr> [,<access str>='sysnative' [,<policy bool str>='true'][, <optionstr> = '']]`) : stringlist (output)` //since 4.12.4.28 [W] +
ifdef::manual[see also : xref:prim-section.adoc#powershellCall_list[powershellCall_list]]

`powershellcall (`<commandstr> [,<access str>='sysnative' [,<policy bool str>='true']]`) : noresult` //since 4.12.0.16 [W]
`powershellCall(`<commandstr> [,<access str>='sysnative' [,<policy bool str>='true'][, <optionstr> = '']]`) : noresult` //since 4.12.4.28 [W] +
ifdef::manual[see also : xref:prim-section.adoc#powershellCall[powershellCall]]

`powershellcall (`<commandstr> [,<access str>='sysnative' [,<policy bool str>='true']]`) : string (exitcode)` //since 4.12.0.16 [W]
`powershellCall(`<commandstr> [,<access str>='sysnative' [,<policy bool str>='true'][, <optionstr> = '']]`) : string (exitcode)` //since 4.12.4.28 [W] +
ifdef::manual[see also : xref:prim-section.adoc#powershellCall_str[powershellCall_str]]


`getOutStreamFromSection (`<dos section name>`) : stringlist (output)` [W/L/M]
[source,opsiscript]
----
set $list$= getOutStreamFromSection ('DosInAnIcon_try')
----
ifdef::manual[see also : xref:prim-section.adoc#getOutStreamFromSection[getOutStreamFromSection]]
ifdef::manual[see also : xref:prim-section.adoc#opsi-script-dosbatch-catchout[opsi-script-dosbatch-catchout]]

`processCall(`<string>`) : string (exitcode)` //since 4.11.6.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#processCall[processCall]]

`getLastExitCode : string (exitcode)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getLastExitCode[getLastExitCode]]

`includelog` <file name> <tail size> `: noresult`  //since 4.11.2.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#includelog[includelog]]

`includelog` <file name> <tail size> [<encoding>] `: noresult` //since 4.11.4.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#includelog[includelog]]

`waitForPackageLock(`<seconds timeout string>,<bool should we kill>`) : bool` //since 4.11.6.1 [L]
ifdef::manual[see also : xref:prim-section.adoc#waitForPackageLock[waitForPackageLock]]

`which(`<command in path>`) : string` (command with path) //since 4.12.3.6 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#which[which]]

`executeSection(`<string expr with section call>`)` //since 4.12.3.9 [W/L/M]
ifdef::manual[see also : xref:sec-section.adoc#executeSection[executeSection]]

see also: ExecWith sections <<opsi-script-rc-execwith>>

see also: ShellBatch sections <<opsi-script-rc-dosbatch>>

see also: Winbatch sections <<opsi-script-rc-winbatch>>

[[opsi-script-rc-regularexpression]]
=== Regular expression related functions [W/L/M]:

ifdef::manual[General Info: : xref:prim-section.adoc#opsi-script-regularexpression[Regular expression related functions]]

`isRegexMatch(<string>, <pattern>) : boolean`  //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#isRegexMatch[isRegexMatch]]

`getSubListByContainingRegex(<pattern>, <target list>) : stringlist`  //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#getSubListByContainingRegex[getSubListByContainingRegex]]

`getSubListByContainingRegex(<pattern list>, <target list>) : stringlist`   //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#getSubListByContainingRegex[getSubListByContainingRegex]]

`getRegexMatchList(<pattern>, <target list>) : stringlist`  //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#getRegexMatchList[getRegexMatchList]]

`getRegexMatchList(<pattern list>, <target list>) : stringlist`   //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#getRegexMatchList[getRegexMatchList]]

`removeFromListByContainingRegex(<pattern>, <target list>) : stringlist`  //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#removeFromListByContainingRegex[removeFromListByContainingRegex]]

`removeFromListByContainingRegex(<pattern list>, <target list>) : stringlist`   //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#removeFromListByContainingRegex[removeFromListByContainingRegex]]

`stringReplaceRegex(<string>, <pattern>, <replacement string>) : string`  //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#stringReplaceRegex[stringReplaceRegex]]

`stringReplaceRegexInList(<target list>, <pattern>, <replacement string>) : stringlist`   //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#stringReplaceRegexInList[stringReplaceRegexInList]]


[[opsi-script-rc-regfunc]]
=== Registry related functions [W]

`getRegistryValue(`<keystr>, <varstr> [, <access str>]`)` : string //since 4.12.0.16 [W] +
<access str> = one of 32bit, 64bit, sysnative ; default sysnative
ifdef::manual[see also : xref:prim-section.adoc#getRegistryValue[getRegistryValue]]

`GetRegistrystringvalue(`"[key] var"`) : string` [W]
ifdef::manual[see also : xref:prim-section.adoc#GetRegistrystringvalue[GetRegistrystringvalue]]

`GetRegistryStringValue32 (`"[key] var"`) : string`   //since 4.10.8 [W]
ifdef::manual[see also : xref:prim-section.adoc#GetRegistryStringValue32[GetRegistryStringValue32]]

`GetRegistryStringValue64 (`"[key] var"`) : string`   //since 4.10.8 [W]
ifdef::manual[see also : xref:prim-section.adoc#GetRegistryStringValue64[GetRegistryStringValue64]]

`GetRegistryStringValueSysNative (`"[key] var"`) : string`    //since 4.10.8 [W]
ifdef::manual[see also : xref:prim-section.adoc#GetRegistryStringValueSysNative[GetRegistryStringValueSysNative]]

`getRegistryKeyList32(`<regkey>`) : stringlist` //since 4.11.3 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryKeyList32[getRegistryKeyList32]]

`getRegistryKeyList64(`<regkey>`) : stringlist` //since 4.11.3 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryKeyList64[getRegistryKeyList64]]

`getRegistryKeyListSysnative(`<regkey>`) : stringlist` //since 4.11.3 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryKeyListSysnative[getRegistryKeyListSysnative]]

`getRegistryKeyList(`<regkey>, <access str>`) : stringlist` //since 4.12.5.0 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryKeyList[getRegistryKeyList]]

`getRegistryVarList32(`<regkey>`) : stringlist`  //since 4.11.3 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryVarList32[getRegistryVarList32]]

`getRegistryVarList64(`<regkey>`) : stringlist` //since 4.11.3 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryVarList64[getRegistryVarList64]]

`getRegistryVarListSysnative(`<regkey>`) : stringlist` //since 4.11.3 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryVarListSysnative[getRegistryVarListSysnative]]

`getRegistryVarList(`<regkey>, <access str>`) : stringlist` //since 4.12.5.0 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryVarList[getRegistryVarList]]

`getRegistryVarMap32(`<regkey>`) : stringlist`  //since 4.11.3 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryVarMap32[getRegistryVarMap32]]

`getRegistryVarMap64(`<regkey>`) : stringlist` //since 4.11.3 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryVarMap64[getRegistryVarMap64]]

`getRegistryVarMapSysnative(`<regkey>`) : stringlist` //since 4.11.3 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryVarMapSysnative[getRegistryVarMapSysnative]]

`getRegistryVarMap(`<regkey>, <access str>`) : stringlist` //since 4.12.5.0 [W]
ifdef::manual[see also : xref:prim-section.adoc#getRegistryVarMap[getRegistryVarMap]]

`RegKeyExists(`<regkey>[,<access str>]`) : bool` //since 4.12.0.16 [W] +
<access str> = one of 32bit, 64bit, sysnative ; default sysnative
ifdef::manual[see also : xref:prim-section.adoc#RegKeyExists[RegKeyExists]]

`RegVarExists(`<regkey>, <var str> [,<access str>]`) : bool` //since 4.12.0.16 [W] +
<access str> = one of 32bit, 64bit, sysnative ; default sysnative
ifdef::manual[see also : xref:prim-section.adoc#RegVarExists[RegVarExists]]

see also: <<opsi-script-rc-registry>>

ifdef::manual[see also : xref:sec-section.adoc#opsi-script-registry[Registry-Sections]]

ifdef::manual[see also : xref:64bit.adoc#opsi-script-64bit[64 bit]]



[[opsi-script-rc-string-handling]]
=== String handling functions [W/L/M]

ifdef::manual[see also : xref:prim-section.adoc#opsi-script-string[string]]

`splitString (`<string1>, <string2>`) : stringlist` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#splitString[splitString]]
[source,opsiscript]
----
set $list1$ = splitString ("\\server\share\dir","\")
----

`splitStringOnWhiteSpace (`<string>`)  : stringlist` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#splitStringOnWhiteSpace[splitStringOnWhiteSpace]]

`composeString (`<string list>, <Link>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#composeString[composeString]]

`takeString (`<index>, <list>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#takeString[takeString]]

`setStringInListAtIndex(`<newstring>,<list>,<indexstr>`) : stringlist` //since 4.11.6  [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#setStringInListAtIndex[setStringInListAtIndex]]

`takeFirstStringContaining(`<list>,<search string>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#takeFirstStringContaining[takeFirstStringContaining]]

`getIndexFromListByContaining`(<list> : stringlist,<search string> : string`)` : <number> : string  //since 4.12.0.13 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getIndexFromListByContaining[getIndexFromListByContaining]]

`contains(`<str>, <substr>`) : bool`  //since 4.11.3: true if <substr> in <str> [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#contains[contains]]

`isNumber(`<str>`) : bool` //since 4.11.3: true if <str> represents an integer [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#isNumber[isNumber]]

`trim(`<string>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#trim[trim]]

`lower(`<string>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#lower[lower]]

`upper(`<string>`)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#upper[upper]]

`unquote(`<string>,<quote-string>`) : string`  //since 4.11.2.1  [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#unquote[unquote]]

`unquote2(`<string>,<quote-string>`) : string`  //since 4.11.5.2  [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#unquote2[unquote2]]

`stringReplace(`<string>, <oldPattern>, <newPattern>`) : string`  //since 4.11.3 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#stringReplace[stringReplace]]

`strLength(`<string>`) : string (number)`  //since 4.11.3 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#strLength[strLength]]

`strPos(`<string>, <sub string>`) : string (numner)`  //since 4.11.3 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#strPos[strPos]]

`strPart(`<string>, <start pos>, <number of chars>`) : string`  //since 4.11.3 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#strPart[strPart]]

`getValue(`<key string>, <hash string list> `) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getValue[getValue]]

`getValueBySeparator(`<key string>,<separator string>,<hash string list> `) : string` //since 4.11.2.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getValueBySeparator[getValueBySeparator]]

`getValueFromFile(`<key string>, <file name>`) : string` //since 4.11.4.4 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getValueFromFile[getValueFromFile]]

`getValueFromFileBySeparator(`<key string>,<separator string>,<file name>`) : string` //since 4.11.4.4 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getValueFromFileBySeparator[getValueFromFileBySeparator]]

`EscapeString:` <sequence of characters>  `: string`// [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#EscapeString[EscapeString]]

`stringReplaceRegex(<string>, <pattern>, <replacement string>) : string`  //since 4.12.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#stringReplaceRegex[stringReplaceRegex]]

`stringinput(`< message str>,< boolstr confidential>`) : string` //since 4.12.1.2 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#stringinput[stringinput]]
////
`ReadTOMLFile(`<TOMLfilePath: String>`) : String`  //since 4.12.4.37 
ifdef::manual[see also : <<>>

`GetTOMLAsString(`<TOMLcontents: String>`) : String`   //since 4.12.4.37 
ifdef::manual[see also : <<GetTOMLAsString>>]

`GetTOMLTableAsString(`<TOMLcontents: String> , <table name : String>`) : String`   //since 4.12.4.37 
ifdef::manual[see also : <<GetTOMLTableAsString>>]

`GetValueFromTOML(`<TOMLcontents: String> , <keyPath: String> , <defaultValue: String>`) : String`   //since 4.12.4.37 
ifdef::manual[see also : <<GetValueFromTOML>>]

`ModifyTOML(`<TOMLcontents: String> , <command: String> , <keyPath: String> , <value: String>`) : String`   //since 4.12.4.37 
ifdef::manual[see also : <<>>]

`DeleteTableFromTOML(`<TOMLcontents: String> , <tablePath: String>`) : String`   //since 4.12.4.37 
ifdef::manual[see also : <<ModifyTOML>>]

`ConvertTOMLtoJSON(`<TOMLcontents: String>`) : String`   //since 4.12.4.37 
ifdef::manual[see also : <<ConvertTOMLtoJSON>>]
////

[[opsi-script-rc-stringlist-handling]]
=== Stringlist handling functions [W/L/M]

ifdef::manual[see also : xref:prim-section.adoc#opsi-script-stringlist[stringlist]]

`getListContaining(`<list>,<search string>`) : stringlist` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getListContaining[getListContaining]]

`getListContainingList(`<list1>,<list2>`) : stringlist`  //since 4.11.3.7 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getListContainingList[getListContainingList]]

`getIndexFromListByContaining`(<list> : stringlist,<search string> : string`)` : <number> : string  //since 4.12.0.13 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getIndexFromListByContaining[getIndexFromListByContaining]]

`count (`<list>`) : string (number)` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#count[count]]

`emptylist (`<list>`)  : stringlist`  //since 4.11.3.7 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#emptylist[emptylist]]

`for %`<identifier>`% in` <list> `do` <one statement | sub section> [W/L/M]
[source,opsiscript]
----
for %s% in $list1$ do sub_test_string
----
ifdef::manual[see also : xref:prim-section.adoc#opsi-script-stringlist-iteration[opsi-script-stringlist-iteration]]

`createStringList (`<string0>, <string1> ,... `) : stringlist` [W/L/M]
[source,opsiscript]
----
set $list1$ = createStringList ('a','b')
----
ifdef::manual[see also : xref:prim-section.adoc#createStringList[createStringList]]

`reverse (`<list>`) : stringlist` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#reverse[reverse]]

`getSubList (`<start index> : <end index>, <list>`) : stringlist` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getSubList[getSubList]]

`getSubListByMatch (`<search string>, <target list>`)` :stringlist //since 4.12.0.14 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getSubListByMatch_sl[getSubListByMatch_sl]]

`getSubListByMatch (`<search list>, <target list>`)` :stringlist //since 4.12.0.14 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getSubListByMatch_ll[getSubListByMatch_ll]]

`getSubListByContaining (` <search string>, <target list>`)` :stringlist //since 4.12.0.14 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getSubListByContaining_sl[getSubListByContaining_sl]]

`getSubListByContaining (`<search list>, <target list>`)` :stringlist //since 4.12.0.14 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getSubListByContaining_ll[getSubListByContaining_ll]]

`getSubListByKey (`<search string>, <target list>`)` :stringlist //since 4.12.0.14 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getSubListByKey_sl[getSubListByKey_sl]]

`getSubListByKey (`<search list>, <target list>`)` :stringlist //since 4.12.0.14 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getSubListByKey_ll[getSubListByKey_ll]]

`getKeyList (`<list>`)` :stringlist //since 4.12.0.14 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getKeyList[getKeyList]]

`addtolist(`<list>,<string>`) : stringlist`	 //since 4.10.8 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#addtolist[addtolist]]

`addListToList(`<dest list>,<src list>`) : stringlist`	 //since 4.10.8 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#addListToList[addListToList]]

`reencodestrlist(`<list>, <from>, <to>`) : stringlist` //since 4.11.4.2 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#reencodestrlist[reencodestrlist]]

`removeFromListByContaining(`<search string>`,` <target list>`) : stringlist` //since 4.11.5.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#removeFromListByContaining_str[removeFromListByContaining_str]]

`removeFromListByContaining(`<search list>`,` <target list>`) : stringlist` //since 4.11.5.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#removeFromListByContaining_list[removeFromListByContaining_list]]

`removeFromListByMatch(`<searchstring>,<target list>`) : stringlist`   //since 4.11.6 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#removeFromListByMatch[removeFromListByMatch]]

`takeString (`<index>, <list>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#takeString[takeString]]

`takeFirstStringContaining(`<list>,<search string>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#takeFirstStringContaining[takeFirstStringContaining]]

`setStringInListAtIndex(`<newstring>,<list>,<indexstr>`) : stringlist`   //since 4.11.6 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#setStringInListAtIndex[setStringInListAtIndex]]

`jsonAsArrayToStringList(`<jsonstr>`) : stringlist`  //since 4.11.6: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#jsonAsArrayToStringList[jsonAsArrayToStringList]]

`jsonStringListToJsonArray(`<strlist>`) : jsonstr`  //since 4.11.6: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#jsonStringListToJsonArray[jsonStringListToJsonArray]]

`jsonAsObjectGetKeyList(`<jsonstr>`) : stringlist`  //since 4.11.6: [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#jsonAsObjectGetKeyList[jsonAsObjectGetKeyList]]

`splitString(`<string1>, <string2>`)` : stringlist [W/L/M]
[source,opsiscript]
----
set $list1$ = splitString ("\\server\share\dir","\")
----
ifdef::manual[see also : xref:prim-section.adoc#splitString[splitString]]

`splitStringOnWhiteSpace (`<string>`)  : stringlist` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#splitStringOnWhiteSpace[splitStringOnWhiteSpace]]

`composeString(`<string list>, <Link>`) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#composeString[composeString]]

`getValue(`<key string>, <hash string list> `) : string` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getValue[getValue]]

`getValueBySeparator(`<key string>,<separator string>,<hash string list> `) : string` //since 4.11.2.1 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getValueBySeparator[getValueBySeparator]]

`setValueByKey(`<key>, <value>, <targetlist> [, <separator (char)>]`)` : stringlist [W/L/M]
ifdef::manual[see also : <<setValueByKey>>]

`getSubListByContainingRegex(<pattern>, <target list>) : stringlist`  //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#getSubListByContainingRegex[getSubListByContainingRegex]]

`getSubListByContainingRegex(<pattern list>, <target list>) : stringlist`   //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#getSubListByContainingRegex[getSubListByContainingRegex]]

`getRegexMatchList(<pattern>, <target list>) : stringlist`  //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#getRegexMatchList[getRegexMatchList]]

`getRegexMatchList(<pattern list>, <target list>) : stringlist`   //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#getRegexMatchList[getRegexMatchList]]

`removeFromListByContainingRegex(<pattern>, <target list>) : stringlist`  //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#removeFromListByContainingRegex[removeFromListByContainingRegex]]

`removeFromListByContainingRegex(<pattern list>, <target list>) : stringlist`   //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#removeFromListByContainingRegex[removeFromListByContainingRegex]]

`stringReplaceRegexInList(<target list>, <pattern>, <replacement string>) : stringlist`   //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#stringReplaceRegexInList[stringReplaceRegexInList]]

`editmap(`< strlist>`) : stringlist` //since 4.12.1.2 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#editmap[editmap]]

`areListsEqual(`< strlist1>, <strlist2>, <flag>`) : boolean`
ifdef::manual[see also : xref:prim-section.adoc#areListsEqual[areListsEqual]]

`GetSectionFromInifile(`<ini-file>`) : stringlist` [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#GetSectionFromInifile[GetSectionFromInifile]]

////
`LoadTOMLFile(`<TOMLfilePath: String>`) : StringList` //since 4.12.4.37 
ifdef::manual[see also : <<LoadTOMLFile>>]

`GetTOMLAsStringList(`<TOMLcontents: String>`) : StringList`   //since 4.12.4.37 
ifdef::manual[see also : <<ReadTOMLFile>>]

`GetTOMLKeys(`<TOMLcontents: String>`) : StringList`   //since 4.12.4.37 
ifdef::manual[see also : <<GetTOMLKeys>>]

`GetTOMLTableNames(`<TOMLcontents: String>`) : StringList`   //since 4.12.4.37 
ifdef::manual[see also : <<GetTOMLTableNames>>]

`GetTOMLTable(`<TOMLcontents: String> , <table name : String>`) : StringList`   //since 4.12.4.37 
ifdef::manual[see also : <<GetTOMLTable>>]
////

[[opsi-script-rc-timefunc]]
=== Time / Date related functions [W/L/M]

`sleepSeconds` <Integer> or <string> : noresult [W/L/M] +
breaks the program execution for <string> seconds. <string> has to represent an Integer Value +
ifdef::manual[see also : xref:prim-section.adoc#sleepSeconds[sleepSeconds]]

`markTime` : noresult  [W/L/M] +
sets a time stamp for the current system time and logs it.
ifdef::manual[see also : xref:prim-section.adoc#markTime[markTime]]

`getDiffTimeSec : string` (Time in seconds since last marktime) //since 4.11.3 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#getDiffTimeSec[getDiffTimeSec]]

`timeStampAsFloatStr : string` (Floating Number - format: 'days.decimal days') //since 4.11.6 [W/L/M]
ifdef::manual[see also : xref:prim-section.adoc#timeStampAsFloatStr[timeStampAsFloatStr]]

[[opsi-script-rc-usercontext]]
=== Usercontext / loginscripts related functions [W]:

`GetUserSID(`<Windows Username>`) : string`
ifdef::manual[see also : xref:prim-section.adoc#GetUserSID[GetUserSID]]

`GetLoggedInUser : string`   //since 4.11.1.2
ifdef::manual[see also : xref:prim-section.adoc#GetLoggedInUser[GetLoggedInUser]]

`GetUsercontext : string`   //since 4.11.1.2
ifdef::manual[see also : xref:prim-section.adoc#GetUsercontext[GetUsercontext]]

`GetScriptMode : string`  possible values 'Machine','Login' //since 4.11.2.1
ifdef::manual[see also : xref:prim-section.adoc#GetScriptMode[GetScriptMode]]

`saveVersionToProfile : noresult` - save productversion-packageversion to local profile //since 4.11.2.1
ifdef::manual[see also : xref:prim-section.adoc#saveVersionToProfile[saveVersionToProfile]]

`readVersionFromProfile : string` - read productversion-packageversion from local profile //since 4.11.2.1
ifdef::manual[see also : xref:prim-section.adoc#readVersionFromProfile[readVersionFromProfile]]

`scriptWasExecutedBefore : boolean` - is true if saved and running productversion-packageversion are identical //since 4.11.2.1
ifdef::manual[see also : xref:prim-section.adoc#scriptWasExecutedBefore[scriptWasExecutedBefore]]

[[opsi-script-rc-xml2-functions]]
=== XML related functions (XML2) [W/L/M]:

ifdef::manual[see also : xref:prim-section.adoc#opsi-script-xml2-functions[opsi-script-xml2-functions]]

`getXml2DocumentFromFile(`<path to xml file>`) : xml2stringlist`  //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#getXml2DocumentFromFile[getXml2DocumentFromFile]]

`getXml2Document(`<stringlist wit xml>`) : xml2stringlist`  //since 4.12.1
ifdef::manual[see also : xref:prim-section.adoc#getXml2DocumentFromFile[getXml2DocumentFromFile]]

`xml2GetFirstChildNodeByName(`<xml2stringlist>, <node name str>`) : xml2stringlist`   //since 4.12.1.
ifdef::manual[see also : xref:prim-section.adoc#xml2GetFirstChildNodeByName[xml2GetFirstChildNodeByName]]

`getXml2UniqueChildnodeByName(`<xml2stringlist>, <node name str>`) : xml2stringlist`   //since 4.12.1.
ifdef::manual[see also : xref:prim-section.adoc#getXml2UniqueChildnodeByName[getXml2UniqueChildnodeByName]]

`getXml2AttributeValueByKey(`<xml2stringlist>, <attr name str>`) : string`   //since 4.12.1.
ifdef::manual[see also : xref:prim-section.adoc#getXml2AttributeValueByKey[getXml2AttributeValueByKey]]

`getXml2Text(`<xml2stringlist>`) : string`   //since 4.12.1.
ifdef::manual[see also : xref:prim-section.adoc#getXml2Text[getXml2Text]]


see also : <<opsi-script-rc-XML2-sections>>

ifdef::manual[see also : xref:sec-section.adoc#opsi-script-xml2-sections[XML2 Section]]

[[opsi-script-toml-functions]]
=== TOML files related functions [W/L/M]:

ifdef::manual[see also : xref:prim-section.adoc#opsi-script-toml-functions[opsi-script-toml-functions]]

`LoadTOMLFile(`<TOMLfilePath: String>`) : StringList` //since 4.12.5 
ifdef::manual[see also : xref:prim-section.adoc#LoadTOMLFile[LoadTOMLFile]]

`ReadTOMLFile(`<TOMLfilePath: String>`) : String`  //since 4.12.5 
ifdef::manual[see also : xref:prim-section.adoc#ReadTOMLFile[ReadTOMLFile]]

`GetTOMLAsStringList(`<TOMLcontents: String>`) : StringList`   //since 4.12.5 
ifdef::manual[see also : xref:prim-section.adoc#GetTOMLAsStringList[GetTOMLAsStringList]]

`GetTOMLAsString(`<TOMLcontents: String>`) : String`   //since 4.12.5 
ifdef::manual[see also : xref:prim-section.adoc#GetTOMLAsString[GetTOMLAsString]]

`GetTOMLKeys(`<TOMLcontents: String>`) : StringList`   //since 4.12.5 
ifdef::manual[see also : xref:prim-section.adoc#GetTOMLKeys[GetTOMLKeys]]

`GetTOMLTableNames(`<TOMLcontents: String>`) : StringList`   //since 4.12.5 
ifdef::manual[see also : xref:prim-section.adoc#GetTOMLTableNames[GetTOMLTableNames]]

`GetTOMLTable(`<TOMLcontents: String> , <table name : String>`) : StringList`   //since 4.12.5 
ifdef::manual[see also : xref:prim-section.adoc#GetTOMLTable[GetTOMLTable]]

`GetTOMLTableAsString(`<TOMLcontents: String> , <table name : String>`) : String`   //since 4.12.5 
ifdef::manual[see also : xref:prim-section.adoc#GetTOMLTableAsString[GetTOMLTableAsString]]

`GetValueFromTOML(`<TOMLcontents: String> , <keyPath: String> , <defaultValue: String>`) : String`   //since 4.12.5 
ifdef::manual[see also : xref:prim-section.adoc#GetValueFromTOML[GetValueFromTOML]]

`ModifyTOML(`<TOMLcontents: String> , <command: String> , <keyPath: String> , <value: String>`) : String`   //since 4.12.5 
ifdef::manual[see also : xref:prim-section.adoc#ModifyTOML[ModifyTOML]]

`DeleteTableFromTOML(`<TOMLcontents: String> , <tablePath: String>`) : String`   //since 4.12.5 
ifdef::manual[see also : xref:prim-section.adoc#DeleteTableFromTOML[DeleteTableFromTOML]]

`SaveToTOMLFile(`<TOMLcontents: String> , <TOML file Path: String>`) : boolean`   //since 4.12.5 
ifdef::manual[see also : xref:prim-section.adoc#SaveToTOMLFile[SaveToTOMLFile]]

`ConvertTOMLtoJSON(`<TOMLcontents: String>`) : String`   //since 4.12.5 
ifdef::manual[see also : xref:prim-section.adoc#ConvertTOMLtoJSON[ConvertTOMLtoJSON]]

`ConvertTOMLfileToJSONfile(`<TOMLfilePath: String> , <JSONfilePath: String>`) : boolean`   //since 4.12.5 +
ifdef::manual[see also : xref:prim-section.adoc#ConvertTOMLfileToJSONfile[ConvertTOMLfileToJSONfile]]
