////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      29.03.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



[[opsi-client-more-info]]
= Further Information

// cspell: ignore mode, antora, ifeval

Our manual is a comprehensive resource vital for productive operations. It's especially important to become familiar with the chapters in xref:server:overview.adoc[opsi Server] and to develop a robust backup strategy for your environment, as outlined in xref:server:components/backup.adoc[Backup of the opsi Server].

For community interaction and staying updated with important announcements and news, please visit and participate in our link:https://forum.opsi.org/[opsi Forum].

TIP: In a productive environment, consider obtaining professional support from uib (link:https://www.uib.de/en/support[Maintenance and Support Contracts]).
