////                                                            
; Copyright (c) uib gmbh (www.uib.de)                           
; This documentation is owned by uib                            
; and published under the german creative commons by-sa license 
; see:                                                          
; http://creativecommons.org/licenses/by-sa/3.0/de/             
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode    
; english:                                                      
; http://creativecommons.org/licenses/by-sa/3.0/                
; http://creativecommons.org/licenses/by-sa/3.0/legalcode       
;                                                               
;                          
////                                                            
                                                                
:Revision:                                                 
:doctype: book                                               
:Author:    detlef oertel
:Email:    d.oertel@uib.de
:toc:
   
   
   

[[Doc_fileuib_driver_install.opsiscript]]
= Documentation of opsi library: `uib_driver_install.opsiscript`



* Email:     d.oertel@uib.de
* Version:  1.0
* Copyright:  AGPLv3





anchor:install_driver_recursive_from_dir[]

[[Doc_func_install_driver_recursive_from_dir]]
== Documentation of local function `install_driver_recursive_from_dir`


Definition::
`install_driver_recursive_from_dir($driverdir$ : string, ref $errorstrings$ : stringlist) : string`

Description::
Sets for the given list of opsi productIds the action request
to 'setup' (also resolving the dependencies)

* Parameter: `$driverdir$`
** Type: `String`  -  Calltype: `CallByValue`

* Parameter: `$errorstrings$`
** Type: `Stringlist`  -  Calltype: `CallByReference`

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"
* SpecialCase:     Works only in opsi service mode (not in interactive or batch mode)
* Author:     detlef oertel
* Date:     17.5.2018
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
[actions]
DefStringlist $productlist$

set $productlist$ = CreateStringList("opsi-logviewer","opsi-configed")
if not(stringtobool(setProductsToSetup($productlist$)))
  comment "call of setProductsToSetup failed"
endif
----



anchor:setFirewallExceptionsTcpUdp4product4profile[]

[[Doc_func_setFirewallExceptionsTcpUdp4product4profile]]
== Documentation of local function `setFirewallExceptionsTcpUdp4product4profile`


Definition::
`setFirewallExceptionsTcpUdp4product4profile($rulename$ : string, $fwprofile$ : string, $path2product$ : string) : void`

Description::


* Parameter: `$rulename$`
** Type: `String`  -  Calltype: `CallByValue`

* Parameter: `$fwprofile$`
** Type: `String`  -  Calltype: `CallByValue`

* Parameter: `$path2product$`
** Type: `String`  -  Calltype: `CallByValue`

* Author:     detlef oertel
* Date:     27.08.2013
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


