////                                                            
; Copyright (c) uib gmbh (www.uib.de)                           
; This documentation is owned by uib                            
; and published under the german creative commons by-sa license 
; see:                                                          
; http://creativecommons.org/licenses/by-sa/3.0/de/             
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode    
; english:                                                      
; http://creativecommons.org/licenses/by-sa/3.0/                
; http://creativecommons.org/licenses/by-sa/3.0/legalcode       
;                                                               
;                          
////                                                            
                                                                
:Revision:                                                 
:doctype: book                                               
:Author:    detlef oertel
:Email:    d.oertel@uib.de
:toc:
      

[[Doc_fileuib_reboot_lib.opsiscript]]
= Documentation of opsi library: `uib_reboot_lib.opsiscript`


anchor:prepare_uefi_boot_to[]

[[Doc_func_prepare_uefi_boot_to]]
== Documentation of local function `prepare_uefi_boot_to`


Definition::
`prepare_uefi_boot_to($prefer_boot_option$ : string) : void`

Description::
if this is an uefi OS, then prepare the uefi nextboot to
the stored uefi bootlabel that belongs to the boot target $prefer_boot_option$

* Parameter: `$prefer_boot_option$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$prefer_boot_option$` Description: +
'network' or "local-stored-bootimage"  defaults to 'network' if empty

* Returns:     Returns string "void"
* OnError:     nothing
* Author:     detlef oertel
* Date:     27.10.2023


Example:
[source,winst]
----
[actions]
prepare_uefi_boot_to('network')
ExitWindows /Reboot
----


