////                                                            
; Copyright (c) uib gmbh (www.uib.de)                           
; This documentation is owned by uib                            
; and published under the german creative commons by-sa license 
; see:                                                          
; https://creativecommons.org/licenses/by-sa/3.0/de/             
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode    
; english:                                                      
; https://creativecommons.org/licenses/by-sa/3.0/                
; https://creativecommons.org/licenses/by-sa/3.0/legalcode       
;                                                               
;                          
////                                                            
                                                                
:Revision:                                                 
:doctype: book                                               
:Author:    detlef oertel
:Email:    d.oertel@uib.de
:toc:
   


[[Doc_fileuib_bootutils.opsiscript]]
= Documentation of opsi library: `uib_bootutils.opsiscript`



* Email:     d.oertel@uib.de
* Version:  1.0
* Copyright:  AGPLv3


anchor:escapeRegexMetaChars[]
[Doc_func_escapeRegexMetaChars]
== escapeRegexMetaChars
Definition::
`escapeRegexMetaChars($instring$ : string) : string`

Description::
Returns the given string with all regex relevant chars '\^$.|?*+()[{' escaped

* Parameter: `$instring$`
** Type: `String`  -  Calltype: `CallByValue`
** Description: String to escape

* Returns: Returns the escaped string
* OnError: Returns the escaped string
* Links: https://www.regextutorial.org/regular-expression-metacharacters.php
* Author:     detlef oertel
* Date:    19.06.2023


anchor:delFromWindowsBootmanager[]

[[Doc_func_delFromWindowsBootmanager]]
== Documentation of local function `delFromWindowsBootmanager`


Definition::
`delFromWindowsBootmanager($bootlabel$ : string) : string`

Description::
Deletes the boot entry given given by the parameter $bootlabel$ from Windows boot manager
by using bcdedit

* Parameter: `$bootlabel$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$bootlabel$` Description: +
Windows boot manager entry label found in 'bcdedit /v'

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"
* SpecialCase:     Winows only
* References:     <<getWinBcdbootGuid>> +
<<bootNextToWinLabel>> +
<<bootNextToUefiLabel>> +
<<getUefiBcdbootGuid>> 
* Author:     detlef oertel
* Date:     18.01.2022


Example:
[source,winst]
----
[actions]
DefStringlist $productlist$

set $productlist$ = CreateStringList("opsi-logviewer","opsi-configed")
if not(stringtobool(setProductsToSetup($productlist$)))
  comment "call of setProductsToSetup failed"
endif
----



anchor:getWinBcdbootGuid[]

[[Doc_func_getWinBcdbootGuid]]
== Documentation of local function `getWinBcdbootGuid`


Definition::
`getWinBcdbootGuid($bootlabel$ : string) : string`

Description::
Get the boot entry GUID for the label given by the parameter $bootlabel$
from Windows boot manager
by using bcdedit

* Parameter: `$bootlabel$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$bootlabel$` Description: +
Windows boot manager entry label found in 'bcdedit /v'

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"
* SpecialCase:     Winows only
* References:     <<delFromWindowsBootmanager>> +
<<bootNextToWinLabel>> +
<<bootNextToUefiLabel>> +
<<getUefiBcdbootGuid>> 
* Author:     detlef oertel
* Date:     18.01.2022

Example:
[source,winst]
----
Message "get windows boot guid ...."
set $windows_bcd_guid$ = getWinBcdbootGuid("WINDOWS.vhdx")
----



anchor:getUefiBcdbootGuid[]

[[Doc_func_getUefiBcdbootGuid]]
== Documentation of local function `getUefiBcdbootGuid`


Definition::
`getUefiBcdbootGuid($bootlabel$ : string) : string`

Description::
Get the boot entry GUID for the label given by the parameter $bootlabel$ from Windows boot manager
by using bcdedit

* Parameter: `$bootlabel$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$bootlabel$` Description: +
UEFI boot manager entry label found in 'bcdedit /enum firmware'

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"
* SpecialCase:     Winows only
* References:     <<delFromWindowsBootmanager>> +
<<bootNextToWinLabel>> +
<<bootNextToUefiLabel>> +
<<getUefiBcdbootGuid>> 
* Author:     detlef oertel
* Date:     27.10.2023

Example:
[source,winst]
----
if runningonUefi
	set $peuefiguid$ = getUefiBcdbootGuid("opsitempwinpe")
	set $exitcode$ = getlastexitcode
	if $exitcode$ = "0"
		if not ($peuefiguid$ = "")
			shellCall("bcdedit /delete "+$peuefiguid$)
		endif
	endif
endif
----



anchor:bootNextToWinLabel[]

[[Doc_func_bootNextToWinLabel]]
== Documentation of local function `bootNextToWinLabel`

Definition::
`bootNextToWinLabel($bootlabel$ : string) : string`

Description::
Sets the Windows bootmanager to boot next to the label
given by the parameter $bootlabel$ from Windows boot manager
by using bcdedit

* Parameter: `$bootlabel$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$bootlabel$` Description: +
Windows boot manager entry label found in 'bcdedit /v'

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"
* SpecialCase:     Winows only
* References:     <<delFromWindowsBootmanager>> +
<<getUefiBcdbootGuid>> +
<<bootNextToUefiLabel>> 
* Author:     detlef oertel
* Date:     17.5.2018

Example:
[source,winst]
----
See bootNextToUefiLabel
----



anchor:bootNextToUefiLabel[]

[[Doc_func_bootNextToUefiLabel]]
== Documentation of local function `bootNextToUefiLabel`

Definition::
`bootNextToUefiLabel($bootlabel$ : string) : string`

Description::
Sets the uefi bootmanager to boot next to the label
given by the parameter $bootlabel$ from uefi boot manager
by using bcdedit

* Parameter: `$bootlabel$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$bootlabel$` Description: +
UEFI boot manager entry label found in 'bcdedit /enum firmware'

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"
* SpecialCase:     Winows only
* References:     <<delFromWindowsBootmanager>> +
<<getUefiBcdbootGuid>> +
<<bootNextToUefiLabel>> 
* Author:     detlef oertel
* Date:     17.5.2018

Example:
[source,winst]
----
Message "Enable PE boot...."
if runningonuefi
	set $bootLabel$ = "opsitempwinpe"
	if not(stringToBool(bootNextToUefiLabel($bootLabel$)))
		logerror "Activating peboot is failed"
		isFatalError "failed peboot"
	endif
else
	set $bootLabel$ = "ramdisk=[boot]\sources\boot.wim"
	if not(stringToBool(bootNextToWinLabel($bootLabel$)))
		logerror "Activating peboot is failed"
		;isFatalError "failed peboot"
	endif
endif
----

anchor:delUefiBootNextByLabel[]
[Doc_func_delUefiBootNextByLabel]
== delUefiBootNextByLabel

Definition::
`delUefiBootNextByLabel($bootlabel$ : string) : string`

Description::
Remove the uefi bootmanager boot next entry if it has the label
given by the parameter $bootlabel$
by using bcdedit

* Parameter: `$bootlabel$`
** Type: `String`  -  Calltype: `CallByValue`
** Description: UEFI boot manager entry label found in 'bcdedit /enum firmware'

* Returns: Returns string "true" if all is ok
* OnError: Returns string "false"
* SpecialCase: Winows only
* References: <<delFromWindowsBootmanager>> +
<<getUefiBcdbootGuid>> +
<<bootNextToUefiLabel>> 
* Author:     detlef oertel
* Date:     28.1.2022


Example:
[source,winst]
----
Message "Enable PE boot...."
if runningonuefi
	set $bootLabel$ = "opsitempwinpe"
	if not(stringToBool(delUefiBootNextByLabel($bootLabel$)))
		logerror "Removing nextboot for winpe is failed"
		isFatalError "failed peboot"
	endif
endif
----

anchor:delUefiBootNext[]
[Doc_func_delUefiBootNext]
== delUefiBootNext

Definition::
`delUefiBootNext() : string`

Description::
Remove the uefi bootmanager boot next entry
by using bcdedit

* Returns: Returns string "true" if all is ok
* OnError: Returns string "false"
* SpecialCase: Winows only
* References: <<delFromWindowsBootmanager>> +
<<getUefiBcdbootGuid>> +
<<bootNextToUefiLabel>> 
* Author:     detlef oertel
* Date:     28.1.2022

anchor:getUefiBootOrder[]
[Doc_func_getUefiBootOrder]
== getUefiBootOrder

Definition::
`getUefiBootOrder() : stringlist`

Description::
get the displayorder from the uefi bootmanager
by using bcdedit

* Returns: Returns string "true" if all is ok
* OnError: Returns string "false"
* SpecialCase: Winows only
* References: <<delFromWindowsBootmanager>> +
<<getUefiBcdbootGuid>> +
<<bootNextToUefiLabel>> 
* Author:     detlef oertel
* Date:     26.1.2022



anchor:setUefiLabelToFirstBootOrder[]
[Doc_func_setUefiLabelToFirstBootOrder]
== setUefiLabelToFirstBootOrder

Definition::
`setUefiLabelToFirstBootOrder($bootlabel$ : string) : string`

Description::
Sets the uefi bootmanager to add the label $bootlabel$
to the first place in the uefi boot order
by using bcdedit

* Parameter: `$bootlabel$`
** Type: `String`  -  Calltype: `CallByValue`
** Description: UEFI boot manager entry label found in 'bcdedit /enum firmware'

* Returns: Returns string "true" if all is ok
* OnError: Returns string "false"
* SpecialCase: Winows only
* References: <<delFromWindowsBootmanager>> +
<<getUefiBcdbootGuid>> +
<<bootNextToUefiLabel>> 
* Author:     detlef oertel
* Date:     28.1.2022

Example:
[source,winst]
----
Message "Enable PE boot...."
if runningonuefi
	set $bootLabel$ = "opsitempwinpe"
	if not(stringToBool(setUefiLabelToFirstBootOrder($bootLabel$)))
		logerror "Activating peboot is failed"
		isFatalError "failed peboot"
	endif
endif
----

anchor:bootnextToPePartition[]
[Doc_func_bootnextToPePartition]
== bootnextToPePartition
Definition::
`bootnextToPePartition() : string`

anchor:getDiskUuid[]

[[Doc_func_getDiskUuid]]
== Documentation of local function `getDiskUuid`

Definition::
`getDiskUuid($disknumber$ : string , $tmpdir$ : string ) : string`

Description::
Gets the disk uuid for the disk with the number $disknumber$
by using diskpart or powershell
The temporary diskpart script is written to $tmpdir$

* Parameter: `$disknumber$`
** Type: `String`  -  Calltype: `CallByValue`
** Description: UEFI boot manager entry label found in 'bcdeit /enum firmware'

* Parameter: `$tmpdir$`
** Type: `String`  -  Calltype: `CallByValue`
** Description: Temporary directory to use
** Advice: Directory must exist

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"
* SpecialCase:     Winows only
* References:     <<enablePEPartition>> 
* Author:     detlef oertel
* Date:     27.5.2022

Example:
[source,winst]
----
for %disk% = "0" to calculate($diskcount1$+" -1") do set $aktdisklist$ = addtolist($aktdisklist$,getDiskUuid("%disk%", "x:")+"=%disk%")
set $disk$ = getvalue($diskuuid$,$aktdisklist$)
----



anchor:enablePEPartition[]

[[Doc_func_enablePEPartition]]
== Documentation of local function `enablePEPartition`

Definition::
`enablePEPartition($disknumber$ : string , $partitionNumber$ : string, $pepartletter$ : string, $useGpt$ : string) : string`

Description::
Try to make the partition $partitionNumber$ on the disk $disknumber$ visible, bootable 
and give it the Windows disk letter $pepartletter$
by using diskpart or powershell

* Parameter: `$disknumber$`
** Type: `String`  -  Calltype: `CallByValue`
** Description: Number of the disk where we look for the partition
** Advice: First disk = 0

* Parameter: `$partitionnumber$`
** Type: `String`  -  Calltype: `CallByValue`
** Description: Number of the partition on the given disk
** Advice: First partition = 1

* Parameter: `$pepartletter$`
** Type: `String`  -  Calltype: `CallByValue`
** Description: Windows disk letter that the given partition should have

* Parameter: `$usegpt$`
** Type: `String`  -  Calltype: `CallByValue`
** Description: Should we expect GPT or MBR partitions ('true' or 'false')

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"
* SpecialCase:     Winows only, works in PE
* References:     <<getDiskUuid>> 
* Author:     detlef oertel
* Date:     17.5.2022


Example:
[source,winst]
----
Message "Enable PE partition...."
if not(stringToBool(enablePEPartition($disknumber$, $swapPartitionNumber$, $pepartletter$, $useGpt$)))
	LogError "Could not activate PE partition ..."
	isFatalError "failed not activate PE partition"
endif

if not (isDriveReady($pePartLetter$))
	logerror "PE drive "+$pePartLetter$+": not ready"
	isFatalError "PE drive "+$pePartLetter$+": not ready"
	set $errorList$ = addtolist($errorList$, " failed pe_drive_ready")
	set $fatal_error$ = "true"
endif
----

anchor:hidePartition2[]
[Doc_func_hidePartition2]
== hidePartition2
Definition::
`hidePartition2($disknumber$ : string , $partitionNumber$ : string, $partLetter$ : string, $useGpt$ : string, $onlyNoAutomount$ : string) : string`

Description::
Try to make the partition $partitionNumber$ on the disk $disknumber$ hidden
by using diskpart or powershell

* Parameter: `$disknumber$`
** Type: `String`  -  Calltype: `CallByValue`
** Description: Number of the disk where we look for the partition
** Advice: First disk = 0

* Parameter: `$partitionnumber$`
** Type: `String`  -  Calltype: `CallByValue`
** Description: Number of the partition on the given disk
** Advice: First partition = 1

* Parameter: `$partletter$`
** Type: `String`  -  Calltype: `CallByValue`

* Parameter: `$usegpt$`
** Type: `String`  -  Calltype: `CallByValue`
** Description: Should we expect GPT or MBR partitions ('true' or 'false')

* Parameter: `$onlynoautomount$`
** Type: `String`  -  Calltype: `CallByValue`

* Returns: Returns string "true" if all is ok
* OnError: Returns string "false"
* SpecialCase: Winows only, works in PE
* References: <<enablePEPartition>> 
* Author:     detlef oertel
* Date:     27.5.2022


Example:
[source,winst]
----
Message "Hide PE partition...."
if not(stringToBool(hidePartition($disknumber$, $swapPartitionNumber$, $pepartletter$, $useGpt$)))
	LogError "Could not hide PE partition ..."
	isFatalError "failed hide PE partition"
endif

if isDriveReady($pePartLetter$)
	logerror "PE drive "+$pePartLetter$+": is still ready"
	isFatalError "PE drive "+$pePartLetter$+": is still ready"
	set $errorList$ = addtolist($errorList$, " failed pe_drive_still_ready")
	set $fatal_error$ = "true"
endif
----

anchor:hidePartition[]
[Doc_func_hidePartition]
== hidePartition
Definition::
`hidePartition($disknumber$ : string , $partitionNumber$ : string, $partLetter$ : string, $useGpt$ : string) : string`

Description::
Calls hidepartition2 with Parameter: `$onlynoautomount$` = `false`


* Parameter: `$disknumber$`
** Type: `String`  -  Calltype: `CallByValue`

* Parameter: `$partitionnumber$`
** Type: `String`  -  Calltype: `CallByValue`

* Parameter: `$partletter$`
** Type: `String`  -  Calltype: `CallByValue`

* Parameter: `$usegpt$`
** Type: `String`  -  Calltype: `CallByValue`


anchor:noAutomountPartition[]
[Doc_func_noAutomountPartition]
== noAutomountPartition
Definition::
`noAutomountPartition($disknumber$ : string , $partitionNumber$ : string, $partLetter$ : string, $useGpt$ : string) : string`

Description::
Calls hidepartition2 with Parameter: `$onlynoautomount$` = `true`


* Parameter: `$disknumber$`
** Type: `String`  -  Calltype: `CallByValue`

* Parameter: `$partitionnumber$`
** Type: `String`  -  Calltype: `CallByValue`

* Parameter: `$partletter$`
** Type: `String`  -  Calltype: `CallByValue`

* Parameter: `$usegpt$`
** Type: `String`  -  Calltype: `CallByValue`


