////
; Copyright (c) uib gmbh (www.uib.de)                           
; This documentation is owned by uib                            
; and published under the german creative commons by-sa license 
; see:                                                          
; http://creativecommons.org/licenses/by-sa/3.0/de/             
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode    
; english:                                                      
; http://creativecommons.org/licenses/by-sa/3.0/                
; http://creativecommons.org/licenses/by-sa/3.0/legalcode       
;                                                               
;                          
////
                                                                
:Revision:                                                 
:doctype: book                                               
:Author:    detlef oertel
:Email:    d.oertel@uib.de
:toc:
   
   

[[Doc_fileuib_state_and_condition.opsiscript]]
= Documentation of opsi library: `uib_state_and_condition.opsiscript`



* Email:     d.oertel@uib.de
* Version:  1.0
* Copyright:  AGPLv3





anchor:isRebootPending[]

[[Doc_func_isRebootPending]]
== Documentation of local function `isRebootPending`


Definition::
`isRebootPending() : string`

Description::
Checks if a Windows or Linux client needs a reboot

* Returns:     Returns string "true" if reboot is required
* OnError:     Returns string "false"
* Links:     https://ilovepowershell.com/2015/09/10/how-to-check-if-a-server-needs-a-reboot/ +
https://www.windowspro.de/script/ausstehende-reboots-nach-updates-pruefen-powershell-regexe +
https://serverfault.com/questions/122178/how-can-i-check-from-the-command-line-if-a-reboot-is-required-on-rhel-or-centos +
https://askubuntu.com/questions/164/how-can-i-tell-from-the-command-line-whether-the-machine-requires-a-reboot +
https://megamorf.gitlab.io/2019/06/10/check-if-reboot-is-required-after-installing-linux-updates.html

* Author:     detlef oertel
* Date:     21.05.2020


Example:
[source,winst]
----
[actions]
if stringToBool(isRebootPending())
	comment "we need a reboot"
else
	comment "we do not need a reboot"
endif
----



anchor:get_dotnet4_version[]

[[Doc_func_get_dotnet4_version]]
== Documentation of local function `get_dotnet4_version`


Definition::
`get_dotnet4_version() : string`

Description::
Checks which dotnet 4.x is installed

* Returns:     Returns string with the version number (aka "4.6") or empty string if no dotnet 4 is installed
* OnError:     Returns string ""
* Author:     detlef oertel
* Date:     27.08.2019


Example:
[source,winst]
----
[actions]
if ("" = get_dotnet4_version()) or CompareDotSeparatedNumbers(get_dotnet4_version(), "<","4.6")
	comment "No dotnet 4 >= 4.6 installed"
else
	comment "dotnet 4 >= 4.6 installed"
endif
----



anchor:isdotnet_3_5_installed[]

[[Doc_func_isdotnet_3_5_installed]]
== Documentation of local function `isdotnet_3_5_installed`


Definition::
`isdotnet_3_5_installed() : string`

Description::
Checks if a dotnet 3.5 is installed

* Returns:     Returns string "true" dotnet 3.5 is installed
* OnError:     Returns string "false"
* Author:     detlef oertel
* Date:     27.08.2019

Example:
[source,winst]
----
[actions]
if stringToBool(isdotnet_3_5_installed())
	comment "dotnet 3.5 is installed"
else
	comment "No dotnet 3.5 found"
endif
----



anchor:getOpsiNetworkMedium[]

[[Doc_func_getOpsiNetworkMedium]]
== Documentation of local function `getOpsiNetworkMedium`


Definition::
`getOpsiNetworkMedium() : string`

Description::
Try to detect the network medium (cable / wifi)
which is used for the connection to the opsi server

* Returns: Returns string "cable" if cable connection is detected
* Returns string "wifi" if wifi connection is detected
* Returns string "unknown" in any other case
* OnError: Returns string "unknown"
* SpecialCase: Works only in opsi service mode (not in interactive or batch mode)
* Author:     detlef oertel
* Date:     27.08.2019

Example:
[source,winst]
----
[actions]
comment "opsi-server: %opsiserver% is connected by: " + getOpsiNetworkMedium()
----


anchor:isVhdMode[]

[[Doc_func_isVhdMode]]
== Documentation of local function `isVhdMode`


Definition::
`isVhdMode() : string`

Description::
check if this installation is a 'vhd-reset' installation

* Returns:     Returns string "true" if vhd is detected
* OnError:     Returns string "false"
* Author:     detlef oertel
* Date:     22.08.2019

Example:
[source,winst]
----
[actions]
if stringtobool(isVhdMode())
  comment "vhd mode detected"
endif
----



anchor:isOliMode[]

[[Doc_func_isOliMode]]
== Documentation of local function `isOliMode`


Definition::
`isOliMode() : string`

Description::
check if this installation is a 'opsi local image' (oli) installation

* Returns:     Returns string "true" if oli is detected
* OnError:     Returns string "false"
* Author:     detlef oertel
* Date:     22.08.2019


Example:
[source,winst]
----
[actions]
if stringtobool(isOliMode())
  comment "oli mode detected"
endif
----


