////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      18.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[Doc_fileuib_lin_install.opsiscript]]
= opsi Library *uib_lin_install.opsiscript*

[[Doc_func_cleanupPackageSystem]]
== Local Function *cleanupPackageSystem*

Definition::
`cleanupPackageSystem() : void`

Description::
reads repo list und try to repair well known problems
should be called after modifying the repo list or after failed installs

* Returns:     nothing
* OnError:     error counter increased ; Error messages in the log
* Author:     Detlef Oertel
* Date:     19.08.2020

Example:
[source,ini]
----
[Actions]
importlib "uib_lin_install"

DefStringlist $packages$
DefVar $installresult$
DefStringlist $errorList$
DefVar $fatal_error$
DefVar $result_string$

comment "update and clean package system"
cleanupPackageSystem()
comment "install pending updates"
set $result_string$ = installupdates()
comment "install new needed packages"
set $packages$ = CreateStringlist("lsb-release","cifs-utils","xterm", "dnsutils","lsof","openssl","pkg-config","desktop-file-utils","libnotify-bin","libgtk2.0-0")
comment "if we are on debian / ubuntu we can use debinstall()"
set $installresult$ = debinstall($packages$)
if not(stringtobool($installresult$))
	if waitForPackageLock("300", "false")
		comment "we got the package lock."
	else
		LogError "could not get Package Lock"
	endif
	cleanupPackageSystem()
	set $installresult$ = debinstall($packages$)
	if not(stringtobool($installresult$))
		LogError "failed dependent packages"
		Message "failed dependent packages"
		;isFatalError "failed dependent packages"
		set $fatal_error$ = "true"
		setloglevel = 6
		set $errorList$ = addtolist($errorList$, " failed dependent_packages")
	endif
endif
----

[[Doc_func_installupdates]]
== Local Function *installupdates*

Definition::
`installupdates() : string`

Description::
try to install pending updates from the known repsitories
should be called after modifying the repo list or after failed installs

* Returns:     nothing
* OnError:     Returns string "false"; error counter increased ; Error messages in the log
* Author:     Detlef Oertel
* Date:     19.08.2020

Example:
[source,ini]
----
see: cleanupPackageSystem()
----

[[Doc_func_runCommandWithList]]
== Local Function *runCommandWithList*

Definition::
`runCommandWithList($command$ : string, $list$ : stringlist) : string`

Description::


* Parameter: `$command$`
** Type: `String`  -  Calltype: `CallByValue`

* Parameter: `$list$`
** Type: `Stringlist`  -  Calltype: `CallByValue`


[[Doc_func_debinstall]]
== Local Function *debinstall*

Definition::
`debinstall($packagelist$ : stringlist) : string`

Description::
try to install the packages given by $packagelist$

* Parameter: `$packagelist$`
** Type: `Stringlist`  -  Calltype: `CallByValue`
** Parameter `$packagelist$` Description: +
stringlist with packages to install

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"; error counter increased ; Error messages in the log
* References:     <<Doc_func_cleanupPackageSystem>>, +
<<Doc_func_installupdates>>, +
<<Doc_func_redinstall>>, +
<<Doc_func_suseinstall>>, +
<<Doc_func_ucsinstall>> 
* Author:     Detlef Oertel
* Date:     09.02.2022


Example:
[source,ini]
----
see: cleanupPackageSystem()
----

[[Doc_func_redinstall]]
== Local Function *redinstall*

Definition::
`redinstall($packagelist$ : stringlist) : string`

Description::
try to install the packages given by $packagelist$

* Parameter: `$packagelist$`
** Type: `Stringlist`  -  Calltype: `CallByValue`
** Parameter `$packagelist$` Description: +
stringlist with packages to install

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"; error counter increased ; Error messages in the log
* References:     <<Doc_func_cleanupPackageSystem>>, +
<<Doc_func_installupdates>>, +
<<Doc_func_debinstall>>, +
<<Doc_func_suseinstall>>, +
<<Doc_func_ucsinstall>> 
* Author:     Detlef Oertel
* Date:     19.08.2020

Example:
[source,ini]
----
see: cleanupPackageSystem()
----

[[Doc_func_suseinstall]]
== Local Function *suseinstall*

Definition::
`suseinstall($packagelist$ : stringlist) : string`

Description::
try to install the packages given by $packagelist$

* Parameter: `$packagelist$`
** Type: `Stringlist`  -  Calltype: `CallByValue`
** Parameter `$packagelist$` Description: +
stringlist with packages to install

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"; error counter increased ; Error messages in the log
* References:     <<Doc_func_cleanupPackageSystem>>, +
<<Doc_func_installupdates>>, +
<<Doc_func_debinstall>>, +
<<Doc_func_redinstall>>, +
<<Doc_func_ucsinstall>> 
* Author:     Detlef Oertel
* Date:     19.08.2020

Example:
[source,ini]
----
see: cleanupPackageSystem()
----


[[Doc_func_ucsinstall]]
== Local Function *ucsinstall*

Definition::
`ucsinstall($packagelist$ : stringlist) : string`

Description::
try to install the packages given by $packagelist$

* Parameter: `$packagelist$`
** Type: `Stringlist`  -  Calltype: `CallByValue`
** Parameter `$packagelist$` Description: +
stringlist with packages to install

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"; error counter increased ; Error messages in the log
* References:     <<Doc_func_cleanupPackageSystem>>, +
<<Doc_func_installupdates>>,+
<<Doc_func_debinstall>>, +
<<Doc_func_redinstall>>, +
<<Doc_func_suseinstall>> 
* Author:     Detlef Oertel
* Date:     19.08.2020

Example:
[source,ini]
----
see: cleanupPackageSystem()
----

[[Doc_func_genericLinInstall]]
== Local Function *genericLinInstall*

Definition::
`genericLinInstall($packagelist$ : stringlist) : string`

Description::
try to determine the Linux familily and
try to install the packages given by $packagelist$

* Parameter: `$packagelist$`
** Type: `Stringlist`  -  Calltype: `CallByValue`
** Parameter `$packagelist$` Description: +
stringlist with packages to install

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"; error counter increased ; Error messages in the log
* References:     <<Doc_func_cleanupPackageSystem>>, +
<<Doc_func_installupdates>>, +
<<Doc_func_debinstall>>, +
<<Doc_func_redinstall>>, +
<<Doc_func_suseinstall>> 
* Author:     Detlef Oertel
* Date:     08.03.2021

Example:
[source,ini]
----
see: cleanupPackageSystem()
----

[[Doc_func_linuxInstallOneOf]]
== Local Function *linuxInstallOneOf*

Definition::
`linuxInstallOneOf($packagelist$ : stringlist) : string`

Description::
try to install any package given by $packagelist$
This can be used specifying a package with different names for different linux distributions.

* Parameter: `$packagelist$`
** Type: `Stringlist`  -  Calltype: `CallByValue`
** Parameter `$packagelist$` Description: +
stringlist with packages to install

* Returns:     Returns string 'True' if one package was successfully installed
* OnError:     Returns string 'False'
* References:     <<Doc_func_isOneInstalled>>, +
<<Doc_func_getLinuxCommand>> 
* Author:     Nils Doerrer
* Date:     16.11.2020

Example:
[source,ini]
----
[Actions]
importlib "uib_lin_install"
if isOneInstalled(createStringList("lsusb", "usbutils")) = "False"
	message "installing lsusb or usbutils"
	set $success$ = linuxInstallOneOf(createStringList("lsusb", "usbutils"))
endif
----

[[Doc_func_isOneInstalled]]
== Local Function *isOneInstalled*

Definition::
`isOneInstalled($packagelist$ : stringlist) : string`

Description::
check for installation status and return if any of $packagelist$ exists
This can be used to check a package with different names for different linux distributions.

* Parameter: `$packagelist$`
** Type: `Stringlist`  -  Calltype: `CallByValue`
** Parameter `$packagelist$` Description: +
stringlist with packages to check

* Returns:     Returns string 'True' if one specified package is installed
* OnError:     Returns string 'False'
* References:     <<Doc_func_linuxInstallOneOf>>, +
<<Doc_func_getLinuxCommand>> 
* Author:     Nils Doerrer
* Date:     16.11.2020

[[Doc_func_getLinuxCommand]]
== Local Function *getLinuxCommand*

Definition::
`getLinuxCommand($type$ : string) : string`

Description::
Determine package manager and return command.

* Parameter: `$type$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$type$` Description: +
type of desired command 'install','check', 'localpackage'

* Returns:     Package manager command according to type
* OnError:     Returns string 'False'
* References:     <<Doc_func_linuxInstallOneOf>>, +
<<Doc_func_isOneInstalled>> 
* Author:     Nils Doerrer, Detlef Oertel
* Date:     14.01.2021

[[Doc_func_getLinuxCommandAgnostic]]
== Local Function *getLinuxCommandAgnostic*

Definition::
`getLinuxCommandAgnostic($type$ : string) : string`

Description::
Determine package manager and return command.

* Parameter: `$type$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$type$` Description: +
type of desired command 'install' or 'check'

* Returns:     Package manager command according to type
* OnError:     Returns string 'False'
* References:     <<Doc_func_linuxInstallOneOf>>, +
<<Doc_func_isOneInstalled>>, +
<<Doc_func_getLinuxCommand>> 
* Author:     Nils Doerrer
* Date:     16.11.2020

[[Doc_func_linuxInstallOneFile]]
== Local Function *linuxInstallOneFile*

Definition::
`linuxInstallOneFile($packagefile$ : string) : string`

Description::
try to install the local file package given by $packagefile$
This can be used specifying a package with different names for different linux distributions.

* Parameter: `$packagefile$`
** Type: `String`  -  Calltype: `CallByValue`

* Returns:     Returns string '0' if one package was successfully installed
* OnError:     Returns string '-1'
* References:     <<Doc_func_isOneInstalled>>, +
<<Doc_func_getLinuxCommand>> 
* Author:     Detlef Oertel
* Date:     08.02.2021

Example:
[source,ini]
----
[Actions]
importlib "uib_lin_install"
if if "0" = linuxInstallOneFile("/tmp/dummy.deb")
	comment "success"
endif
----

[[Doc_func_linuxRemoveOnePackage]]
== Local Function *linuxRemoveOnePackage*

Definition::
`linuxRemoveOnePackage($packagename$ : string) : string`

Description::
try to remove the  package given by $packagename$
This can be used specifying a package with different names for different linux distributions.

* Parameter: `$packagename$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$packagename$` Description: +
string with the name of a package to remove

* Returns:     Returns string '0' if package was successfully removed or was not installed
* OnError:     Returns string '-1'
* References:     <<Doc_func_isOneInstalled>>, +
<<Doc_func_getLinuxCommand>> 
* Author:     Detlef Oertel
* Date:     08.02.2021

Example:
[source,ini]
----
[Actions]
importlib "uib_lin_install"
if "0" = linuxRemoveOnePackage("dummy")
	comment "success"
endif
----

[[Doc_func_linuxRemoveOneOf]]
== Local Function *linuxRemoveOneOf*

Definition::
`linuxRemoveOneOf($packagelist$ : stringlist) : string`

Description::
try to remove any package given by $packagelist$
This can be used specifying a package with different names for different linux distributions.

* Parameter: `$packagelist$`
** Type: `Stringlist`  -  Calltype: `CallByValue`
** Parameter `$packagelist$` Description: +
stringlist with packages to install

* Returns:     Returns string 'True' if one package was successfully installed
* OnError:     Returns string 'False'
* References:     <<Doc_func_isOneInstalled>>, +
<<Doc_func_getLinuxCommand>> 
* Author:     Nils Doerrer, Detlef Oertel
* Date:     16.11.2020

Example:
[source,ini]
----
[Actions]
importlib "uib_lin_install"
if isOneInstalled(createStringList("lsusb", "usbutils")) = "True"
	message "installing lsusb or usbutils"
	set $success$ = linuxRemoveOneOf(createStringList("lsusb", "usbutils"))
endif
----
