[[opsi-setup-detector-tasks-win]]

==== The offered tasks for Windows:

. _Analyze file and create opsi package_ +
Here, a setup file is analyzed and the entire process is run until an opsi package is created. This process is described in the next chapter.

. _Analyze 2 files (32 / 64 bit) and create opsi package_ +
The procedure is the same as in point 1 above with the following differences: +
Two setup programs for the 32 and 64 bit architectures are queried and analyzed. The product gets an additional property: _install_architecture_ with the possible values: _32bitonly_, _64bitonly_, _both_, _systemspecific_.

. _Analyze file and create package 'with user'_ +
Runs, similarly to point 1 above. The package is build based on the template for installation with logged on user. +
The product gets the following additional properties:  The property _execution_method_ with the possible values: (loginOpsiSetupUser, runAsOpsiSetupUser, runOpsiScriptAsOpsiSetupUser), and the boolean properties: _uninstall_before_install_,  _copy_files_locally_, _debug_. +. +
For more Details see : link:https://docs.opsi.org/opsi-docs-en/4.2/opsi-script-manual/cook-book.html#_opsi_template_with_userlogin[opsi_template_with_userlogin]

. _Create an opsi package template_ +
This point does not ask for a installer file, but creates a opsi template product for Windows with the information from the product configuration is already taken over.

. _Only analyze single file_ +
runs, similarly to point 1 above, only that is aborted after the analysis of the setup program.
