////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      20.02.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

The following tasks are available for Windows:

* _Analyze File and create Opsi Package_: Starting from a setup file, the entire process is executed until an opsi package is created (see the section xref:clients:windows-client/softwareintegration.adoc#opsi-setup-detector-use-single-analyze-and-create[Analyze File and Create a Package]). 

* _Analyze 2 Files (32 / 64 bit) and create O. Package_: The procedure is similar, but here two setup programs for the two architectures (32{nbsp}bit and 64{nbsp}bit) are queried and analyzed. The product receives an additional property: `install_architecture` (possible values: `32bitonly`, `64bitonly`, `both`, and `systemspecific`).

* _Create an opsi Package Template_: Doesn't ask for a setup file, but creates an opsi template product for Windows and takes the information from the product configuration.

* _Analyze File and Create Package 'with user'_: Similar to _Analyze File and create Opsi Package_, creates the package for an installation with a logged in user (see section xref:opsi-script-manual:cook-book.adoc#_opsi_template_with_userlogin[opsi_template_with_userlogin]). The product receives additional properties: +
  - `execution_method`, possible values: `loginOpsiSetupUser`, `runAsOpsiSetupUser`, and `runOpsiScriptAsOpsiSetupUser`.
  - boolean properties: `uninstall_before_install`, `copy_files_locally`, and `debug`

* _Only analyze a single File_: Similar to _Analyze File and create Opsi Package_, but the process is interrupted after the analysis, and no package is built.
