////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      28.03.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-setup-detector-support_custom_directory]]
=== *opsi-setup-detector*: Custom Directory

When you activate the _Support custom directory_ checkbox on the _Product Configuration 1_ tab, the product gets supplemented with an extra directory named `custom`. This directory is ideal for storing client-specific customizations. Importantly, when you upgrade to a new version of the package, the `custom` directory remains untouched. The script includes templates for integrating files from this directory into the installation process.

Here's what gets added to the `setup.opsiscript` file:

[source,ini]
----
; copy custom files to install dir
Files_copy_from_custom_dir
----

This calls a `Files` section to copy files from a `custom` directory to the client. The corresponding section looks like this:

[source,ini]
----
[Files_copy_from_custom_dir]
copy -s "%scriptPath%\custom\*" "$installdir$"
----

In this example, the contents of the `custom` directory are transferred to the installation directory, and the `custom` directory itself is created. It contains the two files `OPSI\preinst` and `OPSI\postinst`. These files ensure that the contents of the `custom` directory remain intact on the depot, even when updates occur.

[[opsi-setup-detector-install_from_local_temp_dir]]
=== *opsi-setup-detector*: Local, temporary Directory

When you activate the _Install from local temp dir_ checkbox on the _Product Configuration 1_ tab in `opsi-setup-detector`, it adjusts the installation process such that the installation files are initially copied to a local, temporary directory, and the installation is carried out from there. This method is particularly beneficial in scenarios where the installation might disrupt the network connection, a common situation with driver installations.

As a result, `opsi-setup-detector` creates a new boolean property named `install_from_local_tmpdir`, which defaults to `false` and has this description: _Determines whether the installation files are copied to a local directory_.

To accommodate this feature, modifications are made to the `setup.opsiscript` file as follows:

[source,ini]
----
set $Install_from_local_tmpdir$ = GetProductProperty("Install_from_local_tmpdir","False")

; before the installation:
if $Install_from_local_tmpdir$ = "true"
	; copy installer files to tempdirectory
	Files_copy_installer_to_temp
	; set $installerSourceDir$ to tmpdir
	set $installerSourceDir$ = forcePathDelims("%opsiTmpDir%\"+$ProductId$)
endif

; do the installation

; after the installation
if $Install_from_local_tmpdir$ = "true"
	; cleanup installer tempdirectory
	Files_del_installer_from_temp
endif
----

Now the installation files are temporarily moved to a temporary directory and deleted after the installation if the condition `Install_from_local_tmpdir` is set to `true`.

The corresponding sections look like this:

[source,ini]
----
; copy installer files to tempdirectory
[Files_copy_installer_to_temp]
copy -s "$installerSourceDir$\*.*" "%opsiTmpDir%\$ProductId$"

; cleanup installer tempdirectory
[Files_del_installer_from_temp]
del -sf "%opsiTmpDir%\$ProductId$\"
----

[[opsi-setup-detector-handle_license_key]]
=== *opsi-setup-detector*: License Key

Activating the _Handle License Key_ checkbox on the _Product Configuration 1_ tab within the `opsi-setup-detector` adds the necessary property and code for managing license keys.

This action creates an additional property named `secretlicense_or_pool`. By default, this property is left blank and carries the description _license key or opsi licensepool_. The inclusion of `secret` in the property name signifies that the value of this property will be masked in `opsi-configed`, meaning it won't be displayed in plain text.

This code is inserted into the `setup.opsiscript` file:

[source,ini]
----
DefVar $LicenseHandledByScript$ = "true"

set $LicenseOrPool$ = GetConfidentialProductProperty("SecretLicense_or_Pool","")

; before the installation:
; ---------------------------------------------------------------
comment "handle license "
; ----------------------------------------------------------------
if $LicenseHandledByScript$ = "true"
	comment "we should handle license"
	;reserve license and get license key
	set $LicenseKey$ = get_licensekey_byPoolOrKey($LicenseOrPool$)
	; here the section or function calls should follow which
	; make use of the license key resp the license reservation
endif
----

`get_licensekey_byPoolOrKey` checks if the value entered in the `secretlicense_or_pool` property corresponds to the name of a license pool as defined in the opsi extension xref:opsi-modules:licensemanagement.adoc[License Management]. If it matches, a license key is retrieved from this specified pool. Otherwise, the content of the property is treated and used directly as the license key.

This code is inserted into the `uninstall.opsiscript`:

[source,ini]
----
DefVar $LicenseHandledByScript$ = "true"

set $LicenseOrPool$ = GetConfidentialProductProperty("SecretLicense_or_Pool","")

; after the uninstallation

; ---------------------------------------------------------------
comment "handle license "
; ----------------------------------------------------------------
if $LicenseHandledByScript$ = "true"
	comment "we should free license used"
	Set $tmpstr$ = FreeLicense($LicenseOrPool$)
endif
----

[[opsi-setup-detector-desktopicon]]
==== *opsi-setup-detector*: Desktop Icon

Activate the checkbox _DesktopIcon_ on the _Product Configuration 1_ tab to add a property and corresponding code for managing desktop icons.

A new boolean property named `desktopicon` is then created, set to `false` by default, and described as `Should there be a desktop icon?`

The corresponding code snippet is then integrated into the `setup.opsiscript` file:

[source,ini]
----
set $desktopicon$ = GetProductProperty("desktopicon", "False")

; after the installation
; handle desktop icon
if $DesktopIcon$ = "true"
	comment "Create Desktop Icon"
	Linkfolder_create_desktop_icon
else
	comment "Remove Desktop Icon"
	Linkfolder_remove_desktop_icon
endif
----

If `desktopicon` is set to `true`, a section `Linkfolder` is called. The corresponding code (which is also inserted in the `uninstall.opsiscript` file) looks like this:

[source,ini]
----
[Linkfolder_remove_desktop_icon]
; check delete_element
set_basefolder common_desktopdirectory
set_subfolder ""
delete_element $productId$

[Linkfolder_create_desktop_icon]
; check name, target and working_dir
set_basefolder common_desktopdirectory
set_subfolder ""
set_link
	name: $productId$
	target: $Installdir$\$targetprogram$
	parameters:
	working_dir: $Installdir$
	icon_file:
	icon_index:
end_link
----

Additionally, these two lines are added to the `delinc.opsiinc` file:

[source,ini]
----
comment "Start Remove Desktop Icon Handling :"
Linkfolder_remove_desktop_icon
----

[[opsi-setup-detector-customize_profile]]
=== *opsi-setup-detector*: Customize local User Profiles

The _Product Configuration 1_ tab includes a checkbox named _Customize Profile_. When selected, a section `Profileactions` is added to the code which facilitates modifications to local user profiles. This feature also extends to _Roaming Profiles_ through a login script.

In the `OPSI/control` file, the `setup.opsiscript` is designated not only as a `setupScript` but also as a `userLoginScript`.

The following segment is added to the `setup.opsiscript` file:

[source,ini]
----
; Run the customization for user profiles
ProfileActions
----

The code triggers the execution of a section named `ProfileActions`. Depending on the context in which it's invoked, this section is executed for all local profiles or specifically for the profile of the currently logged-in user (see the chapter xref:opsi-modules:user-profile.adoc[User Profile Management]).

The sections relevant to this process, which serve as templates for modifying user profiles, are structured as follows:

[source,ini]
----
[ProfileActions]
; all section that called from [ProfileActions]
; will be executed for all user profiles
;
; if this script runs as loginscript
; only the [ProfileActions] will be executed

; copy some files to every user profile
Files_copy_to_user_profiles

; make entries in every currentuser hive
Registry_current_user

; modify or create ini files in all user profiles
;Patches_in_user_profiles  "%UserProfileDir%\Appdata\Roaming\<path_to_ini_file>"
Patches_in_user_profiles  "%UserProfileDir%\Appdata\Roaming\osd_profile_example\osd_profile_example.ini"

[Files_copy_to_user_profiles]
; example structure:
;copy "%Scriptpath%\profile_files\*.*" "%UserProfileDir%\Appdata\Roaming\<path_to_application_dir>"
; example:
;copy "%Scriptpath%\profile_files\*.*" "%UserProfileDir%\Appdata\Roaming\osd_profile_example"

[Registry_current_user]
; example structure:
;openkey [HKCU\Software\<application key>]
;set "<var name>" = "<var value>"
; example:
;openkey [HKCU\Software\osd_profile_example]
;set "osd_profile_example_entry" = "example_value"

[Patches_in_user_profiles]
; example structure:
; set [<section name>] <key name>=<value>
; example:
;set [example_section] example_key=example_value
----
