////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      23.01.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

There are two ways to add opsi products:

* <<automatic-package-installation>>
* <<manual-package-installation>>

TIP: We recommend the first variant, which involves the automatic import of opsi products.

[[automatic-package-installation]]
== Installing Products automatically

To install opsi products automatically, use the command line tool `opsi-package-updater` (refer to section xref:server:components/commandline.adoc#server-components-opsi-package-updater[*opsi-package-updater*]). This tool automatically downloads the current packages from the opsi repository and installs them on the server.

To configure the tool:

* `/etc/opsi/opsi-package-updater.conf`: This is the configuration file with general settings, such as the location for downloaded packages, logfile, log level, timeout, directory for the repositories, etc.
* `/etc/opsi/package-updater.repos.d/`: This directory is for the repositories. To activate a repository, set the entry `active = true` in the respective `.repo` file.

The `.repo` files define, among other things, the URL and directories of the package source, optional username and password for authentication, automatic update and installation, etc.

NOTE: If internet access is via a proxy, specify this in the `.repo` configuration files in the `/etc/opsi/package-updater.repos.d/` directory as the value for `proxy`. A global proxy can be configured in the file `/etc/opsi/opsi-package-updater.conf`.

To install the packages from the repository `uib-windows.repo` using the `opsi-package-updater`, execute the following command as the user `root`:

[source,console]
----
opsi-package-updater -v --repo uib_windows install
----

The repository is named `uib-linux.repo` for Linux users and `uib-mac.repo` for macOS users.

TIP: After successful installation, reload all data in the xref:gui:configed.adoc[Management Interface `opsi-configed`] to make the new products visible there.

You can also use the tool to update installed packages:

[source,console]
----
opsi-package-updater -v update
----

CAUTION: Please be aware that products for operating system installation are not immediately ready for use after installation. They must still be supplemented with the installation files of the corresponding installation medium.

[[manual-package-installation]]
== Installing Products manually

Alternatively, manually download the packages and install them using the `opsi-package-manager` tool (see section xref:server:components/commandline.adoc#server-components-opsi-package-manager[*opsi-package-manager*]). opsi packages have the file extension `.opsi`; you can find them at https://opsipackages.43.opsi.org/stable in the folder for the respective operating system. We recommend to save the `.opsi` packages in the `/var/lib/opsi/repository` directory.

NOTE: To ensure that the `opsiconfd` service can access the files, execute the following command as user `root` after the download: `opsi-set-rights /var/lib/opsi/repository`.

You can install a package on the opsi server as `root` with this command:

[source,console]
----
opsi-package-manager -i <package>.opsi
----
