
[[opsi-setup-detector-installation_opb]]
=== Installation of the opsi-package-builder

The opsi-package-builder is currently available for Windows and Linux and MacOS.

The installation files / packages of the _{opsi-package-builder}_ can be found here: +
https://forum.opsi.org/viewtopic.php?p=32473#p32473 +
There you will find in the first lines of the post links to the installation files for Windows and Linux and MacOS. +
The _{opsi-package-builder}_  is not made by 'uib' but by Holger Pandel from the opsi-community (thank you!).. +

The _{opsi-package-builder}_ open source license: +
https://github.com/pandel/opsiPackageBuilder/blob/master/LICENSE_DE

The _{opsi-package-builder}_ has its own documentation, that is part of the installation.

You can install the _{opsi-package-builder}_ also via opsi:

The package _opsipackagebuilder_wlm_ belongs to the opsi standard products and should be installed on your opsi-server. If not, use:

[source,shell]
----
opsi-package-updater install opsipackagebuilder_wlm
----

to install it on the opsi-server.


[[opsi-setup-detector-installation_osd]]
=== Installation of the opsi-setup-detector

The opsi-setup-detector is currently available for Windows and Linux and MacOS.

You can install the opsi-setup-detector via opsi:

The package _opsi-setup-detector_ belongs to the opsi standard products and should be installed on your opsi-server. If not, use:

[source,shell]
----
opsi-package-updater install opsi-setup-detector
----

to install it on the opsi-server.

A setup program to install the opsi-setup-detector without opsi can be found at : +
https://download.uib.de/opsi4.2/misc/helper/

The base functionality of the _opsi-setup-detector_ is the same on all suppoted platforms. While analyzing a installer file some helper programs will be called, that may not availiable or runable.

* Inno-Setups will be analyzed with innounpack.exe at Windows.

* wix-setups will be analyzed with dark.exe at Windows.

* `.deb` or. `.rpm` files will be analyzed with the Linux command line tools.

The opsi product _opsi-setup-detector_ has a dependency on the opsi product _opsipackagebuilder_wlm_.
The _opsi-setup-detector_ uses the _{opsi-package-builder}_ if available, but can for the most part also work without it.
The installation of the _{opsi-package-builder}_ is recommended.
