
[[opsi-setup-detector-installation_opb]]
===== Installation des {opsi-package-builder}

The {opsi-package-builder} is currently available for Windows and Linux and MacOS.

The installation files / packages of the `opsi-package-builder` can be found here: +
https://forum.opsi.org/viewtopic.php?p=32473#p32473 +
Dort findet sich im oberen Teil die Links auf die Installationspakete für Windows, Linux und MacOS. +
The `{opsi-package-builder}`  is not made by 'uib' but by Holger Pandel from the opsi-community (thank you!).. +

Der `{opsi-package-builder}` unterliegt einer OpenSource Lizenz: +
https://github.com/pandel/opsiPackageBuilder/blob/master/LICENSE_DE

Der `{opsi-package-builder}` hat eine eigene Dokumentation welche mit installiert wird.

[[opsi-setup-detector-installation_osd]]
===== Installation of the opsi-setup-detector

The opsi-setup-detector is currently available for Windows and Linux.

You can install the opsi-setup-detector via opsi:

The package `opsi-setup-detector` belongs to the opsi standard products and should be installed on your opsi-server. If not, use:

[source,prompt]
----
opsi-package-updater install opsi-setup-detector
----

to install it on the opsi-server.

A setup program to install the opsi-setup-detector without opsi can be found at : +
https://download.uib.de/opsi4.1/misc/helper/ 

The functionality of the Linux version is limited,
since certain programs for analyzing setup programs from certain frameworks are not available for Linux:

* Detailed analysis of Inno-Setups due to the lack of innounpack.exe for Linux

* Detailed analysis of wix-setups due to the lack of dark.exe for Linux

The opsi product `opsi-setup-detector` has a dependency on the opsi product `opsi-package-builder`.
The `opsi-setup-detector` uses the `opsi-package-builder` if available, but can for the most part also work without it.
The installation of the `opsi-package-builder` is recommended. 
