////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      15.02.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



This tutorial serves as an introductory guide and should not be considered a complete substitute for formal training or a thorough study of the manuals. For more in-depth learning and resources, we recommend the following:

* *Training*: +
uib GmbH offers comprehensive opsi training courses in Mainz, on-site at your location, or online: +
https://www.uib.de/en/training/opsi-training

* *Manuals*: +
  - We provide a range of manuals in both German and English for different versions of opsi: +
https://docs.opsi.org/
  - For this tutorial, the xref:opsi-script-manual:opsi-script-manual.adoc[*opsi-script*] chapter is particularly useful.

* *Blog*: +
Read the latest news about opsi, announcements, release notes, tips and tricks in our blog: +
https://opsi.org/en/blog/

* *Wiki*: +
You can find our opsi Wiki here: https://wiki.opsi.org/

* *Support Forum*: +
The opsi forum (community support, announcements and news) can be found here: https://forum.opsi.org

