////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      24.09.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]


////
[[opsi-softwintegration-tutorial-introduction]]
==== Introduction
////

This tutorial merely helps you getting started with opsi. It can't replace professional training (which you may order through uib), or thoroughly studying the complete opsi manuals (which might be time consuming and partially error prone if you lack background knowledge).
uib now offers training in English, too.

.Training and Support:

Get Training by uib gmbh in Europe or possibly Northern America: +
https://uib.de/en/support-training/support/

.Manuals:

The opsi Manuals can be found at:

https://docs.opsi.org/opsi-docs-en/4.2/index.html +
important for scripting: +
https://docs.opsi.org/opsi-docs-en/4.2/opsi-script-manual/opsi-script-manual.html

Can bee also found via: +
https://uib.de/en/opsi-documentation/documentation/ +
important for scripting: +
opsi-script reference card and opsi-script manual

.Wiki (Scripts, Tips, Links):

https://forum.opsi.org/wiki

.Support Forum (fast and free vendor support):
https://forum.opsi.org