////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      06.11.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-installation]]
= Installation and commissioning

This chapter introduces various options for installing an opsi server. Before starting, please note the following requirements for the server hardware.

[[server-installation-hardware-requirements]]
== Hardware requirements

You can run an opsi server directly on hardware, in a virtual machine or as a Docker container.
The hardware requirements vary greatly. Depending on the size of your environment, you should plan the equipment accordingly. To ensure smooth operation, the following minimum requirements should be met:

* x86-64 or ARM64 system
* 2{nbsp}GByte RAM
* 2 CPU cores

An opsi depot server is essentially a file server that makes files available to the clients.
Accordingly, high-performance mass storage and a sufficiently fast network connection are important.

The size of the required mass storage depends mainly on the number of opsi packages installed.
The following recommendation applies to production systems: In the directory `/var/lib/opsi` you need at least 60{nbsp}GByte storage space; the folder must be flexibly expandable.

Depending on the configuration and the daily processes, different numbers of opsi clients access one opsi server. In large environments with many simultaneous client connections, RAM and CPU requirements can increase significantly.

TIP: The central opsi service `opsiconfd` requires approx. 250{nbsp}MByte RAM per worker process. We recommend scheduling a worker process for 20 simultaneous connections. The number of CPU cores should be approximately half the number of worker processes. In the standard configuration, you should plan additional resources for Samba, MySQL and Redis.


[[server-installation-options]]
== Installing the opsi-server

Für die Installation eines opsi-Servers stehen Ihnen verschiedene Möglichkeiten zur Verfügung, die wir in verschiedenen Anleitungen beschreiben:

* xref:server:installation/preconfigured-vm.adoc[preconfigured virtual machine]
* xref:server:installation/docker.adoc[opsi as Docker-Container]
* xref:server:installation/deb.adoc[Installation on Debian/Ubuntu]
* xref:server:installation/redhat.adoc[Installation on RHEL/AlmaLinux/Rocky Linux]
* xref:server:installation/suse.adoc[Installation on SLES/openSUSE Leap]
* xref:server:installation/ucs.adoc[Installation on Univention Corporate Server (UCS)]
* xref:server:installation/quickinstall.adoc[Installation on Linux with opsi-QuickInstall]

[[server-installation-support]]
== Help and support

If you have any problems, you can find help link:https://forum.opsi.org[opsi-Forum].

TIP:  If you have a support contract, you can also contact link:https://www.uib.de/de/support-schulung/support[uib-Support] wenden.
