////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      15.12.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-installation]]
= Installation and Setup

This chapter outlines various options for installing an opsi server. Before beginning the installation process, please note the following server hardware requirements.

[[server-installation-hardware-requirements]]
== Hardware Requirements

You can run an opsi server directly on hardware, within a virtual machine, or as a Docker container. The hardware requirements can vary considerably depending on the size of your environment. For efficient and smooth operation, the following minimum specifications should be met:

* An x86-64 or ARM64 system
* 2{nbsp}GByte of RAM
* 2 CPU cores

An opsi depot server primarily functions as a file server, providing files to clients. Hence, high-performance mass storage and a robust network connection are crucial.

The required mass storage size largely depends on the number of opsi packages you intend to install. For production systems, the recommendation is to have at least 60{nbsp}GByte of storage space in the `/var/lib/opsi` directory, with flexibility for expansion.

Depending on the configuration and daily operations, varying numbers of opsi clients may access an opsi server. In larger environments, where there are many simultaneous client connections, the requirements for RAM and CPU can significantly increase.

TIP: The central opsi service `opsiconfd` typically requires about 250{nbsp}MByte of RAM per worker process. It is advisable to allocate one worker process for every 20 simultaneous connections. Additionally, the number of CPU cores should roughly be half the number of worker processes. In a standard configuration, you should also account for additional resources required by Samba, MySQL, and Redis.

[[server-installation-options]]
== Installing the opsi Server

There are a variety of options for installing an opsi server, each detailed in specific guides:

* xref:server:installation/preconfigured-vm.adoc[Preconfigured Virtual Machine]
* xref:server:installation/docker.adoc[opsi as Docker Container]
* xref:server:installation/deb.adoc[Installation on Debian/Ubuntu]
* xref:server:installation/redhat.adoc[Installation on RHEL/AlmaLinux/Rocky Linux]
* xref:server:installation/suse.adoc[Installation on SLES/openSUSE Leap]
* xref:server:installation/ucs.adoc[Installation on Univention Corporate Server (UCS)]
* xref:server:installation/quickinstall.adoc[Installation on Linux with opsi QuickInstall]

[[server-installation-support]]
== Help and Support

If you encounter any issues, assistance is available in the link:https://forum.opsi.org[opsi Forum].

TIP: If you have a support contract, you can also contact the link:https://www.uib.de/en/support-training/support[uib Support].
