////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      18.12.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



[[server-installation-next-steps]]
= Next Steps

Wich role is your new opsi server going to assume: config server or depot server? Your next actions in setting up and configuring the server will be guided by this choice.

== opsi Config Server

* If you plan to use paid xref:opsi-modules:modules.adoc[opsi extensions], now is the time to xref:opsi-modules:modules.adoc[import your license files].
* Configure the server and its components as detailed in the chapter xref:server:components/components.adoc[Tools & Settings].
* Install additional software, as described in the section xref:server:components/commandline.adoc#server-components-opsi-package-updater-install-default-products[Install Standard Products].
* Launch the xref:gui:configed.adoc[Management interface *opsi-configed*].
* Establish a xref:server:components/backup.adoc[backup plan] for the opsi server.

== opsi Depot Server

If the server is designated to function as an opsi depot server, it's essential to register it on the opsi config server. To accomplish this, execute the following command on the opsi depot server:

[source,console]
----
opsiconfd setup --register-depot
----

NOTE: If you are operating the opsi depot server as a Docker container, this step is not required. In such instances, environment variables automatically control this behavior.
