////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      06.11.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-installation-next-steps]]
= Next steps

Should the opsi-server take on the role of an opsi-Configserver or an opsi-Depotserver? The next steps depend on this.

== opsi-Configserver

* If you want to use paid xref:opsi-modules:modules.adoc[opsi extensions], xref:server:components/opsiconfd.adoc#server-components-opsiconfd-admin-page-licensing[import your license files now].
* Configure the server and its components (see chapter xref:server:components/components.adoc[Tools & Settings]).
* Install additional software (see section xref:server:components/commandline.adoc#server-components-opsi-package-updater-install-default-products).
* Start the xref:configed:configed.adoc[management interface *opsi-configed*].
* Set up a xref:server:components/backup.adoc[Backup of the opsi server].

== opsi-Depotserver

If the server is to take on the role of an opsi-Depotserver, then register it on the opsi config server.
To do this, execute the following command on the opsi depot server:

[source,console]
----
opsiconfd setup --register-depot
----

NOTE: If you operate the opsi-Depotserver as a Docker container, this step is not necessary. In this case, environment variables control this behavior.
