////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      18.12.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-installation-redhat]]
= Installation on RHEL/AlmaLinux/Rocky Linux

This chapter focuses on the package-based installation process of an opsi server on Red Hat Enterprise Linux (RHEL), AlmaLinux, and Rocky Linux.

include::server:partial$package-based-start.adoc[]

== Preparations

If you are using Red Hat Enterprise Linux, it's necessary to register with the Red Hat Network to access all the required packages:

[source,console]
----
sudo subscription-manager register
sudo subscription-manager attach --auto
----

Install Samba and MariaDB:

[source,console]
----
sudo yum install mariadb-server samba samba-client
----

Start and configure Samba and MariaDB:

[source,console]
----
sudo systemctl start smb.service
sudo systemctl start nmb.service
sudo systemctl start mariadb.service
sudo systemctl enable smb.service
sudo systemctl enable nmb.service
sudo systemctl enable mariadb.service
sudo mysql_secure_installation
----

NOTE: If the machine is also to be used as a DHCP server, the `dhcpd` daemon must be installed and configured.

== Configuring Repositories

Add the Grafana repository:

[source,console]
----
sudo cat <<EOF | sudo tee /etc/yum.repos.d/grafana.repo
[grafana]
name=grafana
baseurl=https://rpm.grafana.com
repo_gpgcheck=1
enabled=1
gpgcheck=1
exclude=*beta*
gpgkey=https://rpm.grafana.com/gpg.key
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
EOF
----

Add the opsi repository that matches your distribution:

*RHEL 9:*
[source,console]
[subs="attributes"]
----
sudo cd /etc/yum.repos.d/
sudo wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:stable/RHEL_9/home:uibmz:opsi:4.3:stable.repo
sudo yum makecache
----

*RHEL 8:*
[source,console]
[subs="attributes"]
----
sudo cd /etc/yum.repos.d/
sudo wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:stable/RHEL_8/home:uibmz:opsi:4.3:stable.repo
sudo yum makecache
----

*AlmaLinux 9:*
[source,console]
[subs="attributes"]
----
sudo cd /etc/yum.repos.d/
sudo wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:stable/AlmaLinux_9/home:uibmz:opsi:4.3:stable}.repo
sudo yum makecache
----

*AlmaLinux 8:*
[source,console]
[subs="attributes"]
----
sudo cd /etc/yum.repos.d/
sudo wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:stable}/AlmaLinux_8/home:uibmz:opsi:4.3:stable.repo
sudo yum makecache
----

*Rocky Linux 9:*
[source,console]
[subs="attributes"]
----
sudo cd /etc/yum.repos.d/
sudo wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:stable/RockyLinux_9/home:uibmz:opsi:4.3:stable.repo
sudo yum makecache
----

*Rocky Linux 8:*
[source,console]
[subs="attributes"]
----
sudo cd /etc/yum.repos.d/
sudo wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:stable/RockyLinux_8/home:uibmz:opsi:4.3:stable.repo
sudo yum makecache
----

*Oracle Linux 8:*
[source,console]
[subs="attributes"]
----
sudo cd /etc/yum.repos.d/
sudo wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:stable/OracleLinux_8/home:uibmz:opsi:4.3:stable.repo
sudo yum makecache
----


*Oracle Linux 9:*
[source,console]
[subs="attributes"]
----
sudo cd /etc/yum.repos.d/
sudo wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:stable/OracleLinux_9/home:uibmz:opsi:4.3:stable.repo
sudo yum makecache
----

== Installing the Packages

Install the package `opsi-server-full`:

[source,console]
----
sudo yum install opsi-server-full
----

If you encounter a message prompting for confirmation when importing the GnuPG key of the repository, simply type `y` and press [Enter] to confirm the addition of the key:

[source,console]
[subs="attributes"]
----
Importing GPG key 0xD8361F81 "home:uibmz OBS Project <home:uibmz@build.opensuse.org>" from http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/stable/distribution/repodata/repomd.xml.key
Is this ok [y/N]: y
----

include::server:partial$package-based-end.adoc[]

The opsi server is now set up and ready for the xref:server:installation/next-steps.adoc[next steps].
