////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      06.11.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]



[[server-installation-ucs]]
= Installation under UCS

There are two ways to install the opsi server under Univention Corporate Server (UCS):

* xref:server:installation/ucs.adoc#server-installation-ucs-appcenter[Installation via the Univention App Center]
* xref:server:installation/ucs.adoc#server-installation-ucs-manual[Manual installation via the uib repositories]

Both variants lead to a functioning opsi server, but should not run together on one server. Decide in advance which installation suits your environment. If you obtain opsi via the Univention App Center, you may have to wait longer for updates. Switching to a new UCS version is only possible once all installed apps are available under the new UCS version. If you decide to install via the uib repositories, you will receive updates promptly.

[[server-installation-ucs-appcenter]]
== Installation via the App Center

In the link:https://www.univention.de/produkte/univention-app-center/app-katalog/opsi/[Univention App Center catalog] you will find opsi for UCS version 5.0. During installation, the package manager automatically installs additional packages: `opsi-tftpd-hpa` and `univention-mariadb`.

NOTE: The first opsi server in a UCS environment configures an existing MariaDB server as the backend. All further opsi config servers register opsi as opsi depot server. If there is already an opsi config server in the UCS environment during installation, the `opsi-package-updater` tool is configured to obtain the packages from this server.

[[server-installation-ucs-manual]]
== Manual installation

Before you install the opsi server under Univention Corporate Server manually, make a few preparations.

=== Preparations

* Samba must be installed and configured. If the UCS server is a member of an AD domain, install `univention-samba`, which sets up and configures Samba as a member server without domain controller functionality. The package `univention-samba4`, on the other hand, sets up Samba as an AD domain controller.

* A MariaDB server must be installed and configured. To do this, install `univention-mariadb`; the package `univention-mysql` is a meta package since UCS 4.3 that installs the MariaDB server.

* If the UCS computer is also to be used as a DHCP server, configure the DHCP daemon before installing opsi and start it.

In principle, installation is possible on servers with the UCS roles Primary Directory Node, Backup Directory Node, Replica Directory Node and Managed Node.

CAUTION: If you do not install the opsi server on a Primary Directory Node, but on a computer with a different UCS system role, the UCS server must first join the domain.

The configuration file `/etc/opsi/opsi.conf` defines the group for Samba access to the shares; the name is `opsifileadmins`. All users who are to receive access rights for the shares of opsi (opsi packagers) must be members of the `opsifileadmins` group accordingly.

=== Configuration of the package sources

Make sure that the directory `/usr/local/share/keyrings` exists:

[source,console]
----
sudo mkdir -p /usr/local/share/keyrings
----

Add the opsi repository that matches your distribution to the package sources:

*Univention UCS 5.0:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/stable/Univention_5.0/
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" > /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----


Check whether the import of the GnuPG key was successful:

[source,console]
----
gpg /usr/local/share/keyrings/opsi.gpg 2>/dev/null
----

The following lines, among others, should appear in the output:

[source,console]
----
pub   rsa2048 2017-09-30 [SC] [expires: 2025-11-19]
      2E98F7B5A5B2C8FE7F609705D1F933E6D8361F81
uid           home:uibmz:opsi OBS Project <home:uibmz:opsi@build.opensuse.org>
----


=== Installing the packages

Install the package `opsi-server-full`:

[source,console]
----
sudo univention-install opsi-server-full
----

If the opsi server is to run on a UCS system role other than Primary Directory Node,
additionally execute the command `univention-run-join-scripts`.

Users must be members of the `opsiadmin` group in order to use the `opsi-configed` management interface. During installation, the user `administrator` is automatically added to this group. Other accounts are added via the UMC module _User management_, tab _Groups_.

include::server:partial$package-based-end.adoc[]

The opsi server is now ready for xref:server:installation/next-steps.adoc[next steps].
