//// 
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; Until we found a better license:
; All rights reserved.
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      05.05.2011
:Revision:  4.0.1
:toclevels: 6

include::../common/opsi_terms.asciidoc[]


[[opsi-manual-introduction]]
== Introduction

[[opsi-manual-introduction-who-should-read]]
=== Qui devrait lire ce manuel?

Ce manuel est écrit pour tous ceux qui veulent acquérir une meilleure compréhension des mécanismes et des outils du système de gestion client opsi ("open pc server integration"). 

Il présente un guide pratique complète pour l'utilisation de opsi en soulignant la compréhension des connaissances techniques. Le décideur qui décide d'utiliser opsi ainsi que l'administrateur système qui travaille avec lui obtiendront une base solide pour leurs tâches.

[[opsi-manual-introduction-conventions]]
=== Notations

Les chevrons '< >' marquent des noms abstraits. Dans un contexte concret tous qui est marqué '<nom abstrait>' doit être remplacé par un vrai nom. Exemple: Le partage de fichiers, où opsi place les paquets logiciels, peut être noté abstraitement comme '<opsi-depot-share>'. Si le partage de fichiers réel est `/opt/pcbin/install`, alors vous devez remplacer le nom abstrait par exactement cette chaîne de caractères. L'emplacement du paquet `<opsi-depot-share>/ooffice` devient
`/opt/pcbin/install/ooffice`.

Exemple d'extraits de code de programme ou de fichier de configuration utilisent une police Courier, avec une couleur de fond:
[source,prompt]
----
depoturl=smb://smbhost/sharename/path
----
