////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      26.10.2017
:Revision:  4.0.7
:toclevels: 6


include::../common/opsi_terms.asciidoc[]

[[opsi-manual-localization]]
== opsi localization

=== Most opsi parts

The localization of the opsi software is done through 'Transifex': +
https://www.transifex.com/ +

Transifex allows for an easy translation of software projects.

You can find the opsi.org translation project at link:
https://www.transifex.com/opsi-org/opsiorg/[transifex.com/opsi-org/opsiorg/].

Everyone interested in translating opsi can participate!

With this we hope to get not only improved translations but also be able
to integrate new languages that you are currently missing!

=== opsi configed

It is now possible to translate the opsi Configuration Editor - best know by its short name _Configed_ - in Transifex.
After logging in you will be able to access the resource link:https://www.transifex.com/opsi-org/opsiorg/configedproperties/[configed.properties].

We think that translating Configed poses a bit more of a challenge. For most messages the context in which they appear is important and therefore simple word-by-word translation often does not result in a good translation.

This is why we want to handle things different in this case.
In the past there were no reviews involved when we updated translations.
But as Configed is such a vital and important part for many users that we will change our way from here on.
To ensure the quality of translations for Configed that makes it of good and easy use for all opsi users we only want to publish translations that are reviewed.

To review a translation you need the role of a reviewer in Transifex.
If you login as a user with this role you get a button in the translation interface that says 'review'. Any reviewed string can not be further translated.
If you are a partner, customer or someone very active inside the opsi community and you are interested in doing reviews for opsi please do not hesitate to contact us through mail or at link:http://forum.opsi.org[the opsi forum].

[[opsi-manual-localization-contact]]
=== Localization contact

Please send any questions, hints or localization files to: 'locales@uib.de'
