////
; Copyright (c) uib gmbh (www.uib.de)
; Cette documentation appartient à uib
; et publié sous licence Creative Commons by-sa allemande
; voir:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; anglais:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; crédits: http://www.opsi.org/credits/
////


:Author:    OpenSides sprl
:Email:     opsi@opensides.be
:Date:      18.10.2012
:Revision:  4.0.1
:toc:
:numbered:
:website: http://opsi.org/fr


include::../common/opsi_terms.asciidoc[]


[[opsi-manual-backup]]
== Sauvegarde d'opsi

[[opsi-manual-backup_introduction]]
=== Introduction

Votre serveur opsi devrait être sauvegardés (comme tout autre système important). Ce chapitre montre ce qu'il faut sauvegarder et comment.

Et, bien sûr, comment restaurer.

[[opsi-manual-backup_prerequisits]]
=== Conditions préalables à la sauvegarde

Vous devez exécuter commande `opsi-backup` comme 'root'.

Vous devez installer le programme _mysqldump_ avant de pouvoir utiliser `opsi-backup` dans le cadre du 'backend mysql'. Habituellement, ce programme fait partie des paquets du client mysql.

[[opsi-manual-backup-quickstart]]
=== Mise en route rapide

Créer une sauvegarde:

[source, prompt]
----
opsi-backup create opsi_backup.tar.bz2
----
Crée une sauvegarde des backends utilisés et toutes les données de configuration dans le répertoire courant avec le nom `opsi_backup.tar.bz2`.

Restaurer une sauvegarde:
[source, prompt]
----
opsi-backup restore --backends=all --configuration opsi_backup.tar.bz2
----
Restaure les données à partir du fichier de sauvegarde `opsi_backup.tar.bz2`, qui est recherché dans le répertoire courant.

[[opsi-manual-backup_parts-of-opsi]]
=== Éléments de base d'opsi

OPSI peut être divisé en cinq parties différentes qui peuvent être sauvegardés ou pas. L'emplacement où se trouvent ces parties peut varier (selon la distribution Linux, la version et la configuration).

[[opsi-manual-backup_config-part]]
==== La configuration d'opsi

La partie la plus importante de OPSI est la configuration. Vous la trouverez dans `/etc/opsi`.

Cette partie sera sauvegardé par `opsi-backup`.

[[opsi-manual-backup_backend-parts]]
==== Les backends Opsi

Les données sur les clients gérés et les produits peuvent être stockées dans différents backends. Les backends les plus importants sont:

.backends opsi
[options="header"]
|==========================
|Backend|Description
|file-Backend|backend basé sur les fichiers (backend par défaut)
|mysql-Backend|backend basé sur MySQL (depuis opsi 4 pour toutes les données de configuration)
|ldap| Stocker les données de configuration dans l'annuaire ldap
|univention|backend LDAP spécial pour les serveurs d'entreprise Univention
|dhcp|Backend spécial qui est utilisé en combinaison avec un dhcpd du {opsi-server}
|==========================

Des backends différents peuvent être utilisés à des fins différentes en même temps. Donc, vous devriez jeter un oeil à `/etc/opsi/backendManager/dispatch.conf` pour voir quels backends vous utilisez.

Cette partie sera sauvegardé par `opsi-backup`.

[[opsi-manual-backup_depotfiles-parts]]
==== dépôt de partage opsi

Dans le 'dépôt de partage opsi' Vous trouverez les fichiers d'installation des logiciels à installer sur les clients par opsi. Les répertoires qui contiennent ces fichiers (produits Localboot et produits netboot) sont situés dans `/opt/pcbin/install` ou `/var/lib/opsi/depot`.

Selon le nombre des systèmes d'exploitation, pilotes, logiciels et ainsi de suite qui se trouvent ici, cette partie pourrait être de grande taille.

Cette partie *ne* sera *pas* sauvegardé par `opsi-backup`.

Donc, si vous voulez sauvegarder cette partie, vous pouvez utiliser 'rsnapshot' ou d'autres utilitaires de sauvegarde.

[[opsi-manual-backup_workbench-parts]]
==== opsi work bench

'opsi work bench' est le lieu qui est utilisé pour créer ses propres paquets. Il est généralement situé dans `/home/opsiproducts` et exportés comme partage Samba 'opsi_workbench'. Puisque ce répertoire contient votre propre travail, il doit être sauvegardé.

Cette partie *ne* sera *pas* sauvegardé par `opsi-backup`.

Donc, si vous voulez sauvegarder cette partie, vous pouvez utiliser 'rsnapshot' ou d'autres utilitaires de sauvegarde.

[[opsi-manual-backup_repository-parts]]
==== dépôt opsi

Le répertoire `/var/lib/opsi/repository` est utilisé pour stocker les paquets opsi, qui sont téléchargés via `opsi-product-updater` ou qui sont installés par `opsi-package-manager` lorsque vous utilisez l'option `-d`. 

Cette partie *ne* sera *pas* sauvegardé par `opsi-backup`.

Donc, si vous voulez sauvegarder cette partie, vous pouvez utiliser 'rsnapshot' ou d'autres utilitaires de sauvegarde.

[[opsi-manual-backup-cli]]
=== Le logiciel `opsi-backup`

`opsi-backup` est un programme en ligne de commande qui facilite la création et la restauration des sauvegardes de données opsi.

Les commandes de base sont +create+, +restore+ et +verify+. +
L'option +--help+ affiche des informations sur les options de ligne de commande. Utilisez aussi +<command> --help+ (ex. `opsi-backup create --help`) pour obtenir des informations sur les options de la commande.

[source, prompt]
----
opsi-backup --help
----

L'utilitaire `opsi-backup` stocke les données de configuration et le backend dans presque le même format auquel ils ont été trouvés sur le serveur. *Donc, vous ne pouvez pas restaurer ces données sur un serveur qui utilise d'autres backends, ou dispose d'autres versions d'opsi ou est d'une autre manière différente en ce qui concerne la structure des données opsi.*

`opsi-backup` crée toujours une sauvegarde complète. Il n'y a pas de support pour les sauvegardes incrémentielles ou différentiel.


CAUTION: Remarquez que `opsi-backup` *ne* crée *pas* de sauvegarde de: +
* <<opsi-manual-backup_depotfiles-parts,'opsi depot share'>> 
* <<opsi-manual-backup_workbench-parts,'opsi work bench'>>
* <<opsi-manual-backup_repository-parts, 'opsi repository'>>  


`opsi-backup` crée un fichier de sauvegarde, dans le format compressé tar. Donc vous pouvez accéder aux données à l'aide d'autres outils standard.

CAUTION: Un fichier de sauvegarde créé par `opsi-backup` peut contenir un mot de passe, touches de raccourci et d'autres données liées à la sécurité. Donc, assurez-vous de stocker les fichiers de sauvegarde dans un endroit sûr.

[[opsi-manual-backup-create]]
==== Créer une sauvegarde

Pour créer une sauvegarde utilisez `opsi-backup create`. +
Cette commande (sans options supplémentaires) créera une sauvegarde de toutes les données de configuration et de tous les backends utilisées. Le fichier de sauvegarde sera stocké dans le répertoire courant avec un nom généré automatiquement. +
Pour obtenir des informations sur les options possibles de +create+ appelez +
`opsi-backup create --help`

[source, prompt]
----
opsi-backup create
opsi-backup create --help
usage: opsi-backup create [-h] [--flush-logs]
                          [--backends {file,mysql,dhcp,auto,all}]
                          [--no-configuration] [-c [{gz,bz2,none}]]
                          [destination]

positional arguments:
  destination           Destination of the generated output file. (optional)

optional arguments:
  -h, --help            show this help message and exit
  --flush-logs          Causes mysql to flush table logs to disk before the
                        backup. (recommended)
  --backends {file,mysql,dhcp,auto,all}
                        Select a backend to backup or 'all' for all backends.
                        Can be given multiple times. (Default: auto)
  --no-configuration    Backup opsi configuration.
  -c [{gz,bz2,none}], --compression [{gz,bz2,none}]
                        Sets the compression format for the archive (Default:
                        bz2)
----

Vous pouvez donner le répertoire cible ou le chemin complet vers le fichier de sauvegarde en option pour `opsi-backup create`. Si l'option donnée est un nom de fichier, la sauvegarde sera créé dans ce fichier - les fichiers existants seront écrasés. Si l'option est un dossier, le fichier de sauvegarde sera créé dans ce répertoire avec un nom de fichier généré en utilisant le motif: +<nom d'hôte>_<version d'opsi>_<date>_<heure>+

[source, prompt]
----
opsi-backup create /mnt/backup/opsi_backup.tar.bz2
opsi-backup create /mnt/backup/
----

Les autres options pour +create+ sont:

* +--backends {file,mysql,dhcp,all,auto}+ +
is used to select the backends which shall be included to the backup. You may give this option multiple times. +
The option `--backends=all` includes all supported backends. +
The default is `--backends=auto`, which means that `opsi-backup` reads the configuration file `/etc/opsi/backendManager/dispatch.conf` and backups all supported backends used in this configuration.
The supported backends are: +mysql+, +file+, +dhcp+
[source, prompt]
----
opsi-backup create --backends=file --backends=mysql
opsi-backup create --backends=all
----
TIP: If you are using a not supported backend (like 'ldap'), you may use `opsi-convert` to convert your data to a backend, which is supported by backup.

* +--no-configuration+ +
Excludes the <<opsi-manual-backup_config-part,opsi configuration>> files from the backup.
[source, prompt]
----
opsi-backup create --no-configuration
----

* +-c [{gz,bz2,none}], --compression [{gz,bz2,none}]+ +
Specify the compression method. +none+ means 'no compression'. +
The default is +bz2+.

[source, prompt]
----
opsi-backup create -c bz2
----

* `--flush-log` +
The backup of the mysql backend uses the 'mysqldump' command. This means that all data known by the database are backed up, no matter if they are on disk or only in the memory yet. This means, that your backup may be more topical than your database files (which is really not a problem). +
If you want to make sure, that the database stores all data to the disk before starting the backup, you may use the `--flush-log` option. But before you may do this, you have to grant the required RELOAD-privileges to the opsi database user, or your backup will fail. Check: http://dev.mysql.com/doc/refman/5.5/en/privileges-provided.html#priv_reload[RELOAD]. +
So use this option only if you really know what you are doing.

[source, prompt]
----
opsi-backup create --backends=mysql --flush-log
----

*Example*
[source, prompt]
----
opsi-backup create --no-configuration --backends=all opsi_backup.tar.bz2
----

[[opsi-manual-backup-archive]]
==== Archive your backup files
`opsi-backup` has no features to archive the created backup files. So you have to do it by yourself (e.g. using a file backup tool). +
If you call `opsi-backup` with a target directory as option, please keep in mind that every call creates a new full backup file and no older files will be deleted.

[[opsi-manual-backup-verify]]
==== Verify a backup
The command `opsi-backup verify` is used to test the internal integrity of the created backup file. 
Special help for the `opsi-backup verify` command is available by the command option +--help+.

*Example*
[source, prompt]
----
opsi-backup verify opsi_backup.tar.bz2
opsi-backup verify --help
usage: opsi-backup verify [-h] file [file ...]

required arguments:
  file        The backup archive to verify.

optional arguments:
  -h, --help  shows this help message and then exits
----

TIP: If you are calling `opsi-backup verify` at the console, it may be useful to avtivate messages at standardout using `-v`: `opsi-backup -v verify opsi_backup.tar.bz2`

[[opsi-manual-backup-restore]]
==== Restore from a backup file
To restore data from a backup file, use the command `opsi-backup restore`.

You have to give the path to the backup file as parameter.

The command `opsi-backup restore --help` gives information about the options for the command `restore`.
[source, prompt]
----
opsi-backup restore --help
usage: opsi-backup restore [-h] [--backends {file,mysql,dhcp,auto,all}]
                           [--configuration] [-f]
                           file

required arguments:
  file                  The backup archive to restore data from.

optional arguments:
  -h, --help            show this help message and exit
  --backends {file,mysql,dhcp,auto,all}
                        Select a backend to restore or 'all' for all backends.
                        Can be given multiple times.
  --configuration       Restore opsi configuration.
  -f, --force           Ignore sanity checks and try to apply anyway. Use
                        with caution! (Default: false)
----

`opsi-backup restore` has the following options:

* +--backends {file,mysql,dhcp,auto,all}+ +
Specifies the backend to restore. This option may be used multiple times. +
The option `--backends=all` specifies that the data from all backends which are found in the backup file shall be restored. +
The default is `--backends=auto`. This restores the data from the backup file to the system using the actual configuration data from `/etc/opsi/backendManager/dispatch.conf`.

[source, prompt]
----
opsi-backup restore --backends=file --backends=mysql opsi_backup.tar.bz2
opsi-backup restore --backends=all opsi_backup.tar.bz2
----
CAUTION: If you changed your backend configuration since you have created the backup, no or not all data will be restored. In this case you have to use the `--backends=all` option and then to convert the restored data to the now used backend using `opsi-convert`.

* +--configuration+ +
Specifies that the <<opsi-manual-backup_config-part,opsi configuration>> has to be restored. +
This option is not default at +restore+ command.
[source, prompt]
----
opsi-backup restore --configuration opsi_backup.tar.bz2
----


* +-f, --force+ +
To avoid data damage `opsi-backup` makes a system compatibility check (opsi Version, OS-Version, Host- and Domain Name) before restoring data and aborts if the actual system differs from the system the backup file was created on. Using this option you may override this check. 

[source, prompt]
----
opsi-backup restore -f opsi_backup.tar.bz2
----

*Example*
[source, prompt]
----
opsi-backup restore --configuration --backends=all opsi_backup.tar.bz2
----


