////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype: book
:macosclientmanual: opsi-macos-client-manual

include::common:partial$opsi_terms.adoc[]



[[opsi-macclient-installation-config-get-essential-products]]

= Installing the minimal macOS opsi products.

For the distribution of software with opsi ready products are available for installation.
These contain among other things the agent ('opsi-client-agent'), which must be installed for the management on clients.

There is an automated and a manual way to perform this.
The automated way is recommended.

[[opsi-macclient-std-packages]]
== opsi standard software for macOS under opsi.

The following products are provided by opsi for macos as standard:

* `opsi-mac-client-agent`
* `swaudit`
* `hwaudit`
* `m-homebrew` (also check: xref:general-notes.adoc#opsi-macclient-hints-homebrew[the opsi product m-homebrew])
* `m-system-update`
* `opsi-configed`
* `opsi-logviewer`
* `opsi-auto-update`
* `m-javavm`
* `opsi-setup-detector`
* `windomain`


////
* `opsi-client-kiosk`

* ``
////

[[opsi-macclient-installation-config-get-essential-products-automatic]]

== Automatic installation of the minimal macOS opsi products.

For the automatic installation of the opsi products there is the tool `opsi-package-updater`, which is configured in `/etc/opsi/opsi-package-updater.conf` or `/etc/opsi/package-updater.repos.d/`. It also automatically fetches the current packages from the opsi repository and installs them on the server.

The configuration of the opsi repositories for macOS clients can be found in the directory `/etc/opsi/package-updater.repos.d/` in the files `uib-mac-testing.repo` and `uib-mac.repo`.

Activate the desired repos by setting the entry `active = true` in the choosen *.repo file.

.`/etc/opsi/package-updater.repos.d/uib-mac-testing.repo`

[source,configfile]
----
; This repository provides testing of opsi products to manage MacOS
; clients with opsi.

[repository_uib_macos_testing]
description = opsi macos packages in testing
active = true
baseUrl = http://download.uib.de
dirs = opsi4.2/testing/packages/macos/localboot/
autoInstall = false
autoUpdate = true
autoSetup = false
; Set Proxy handler like: http://10.10.10.1:8080
proxy =
----


.`/etc/opsi/package-updater.repos.d/uib-mac.repo`

[source,configfile]
----
; This repository provides table opsi roducts for managing MacOS
; clients with opsi.

[repository_uib_macos_stable]
description = opsi macos packages in stable
active = true
baseUrl = http://download.uib.de
dirs = opsi4.2/stable/packages/macos/localboot/
autoInstall = false
autoUpdate = true
autoSetup = false
; Set Proxy handler like: http://10.10.10.1:8080
proxy =
----
Install the packages on the server by running the command as root:

[source,prompt]
----
opsi-package-updater -v --repo uib_macos_stable install
----

or

[source,prompt]
----
opsi-package-updater -v --repo uib_macos_testing install
----

After a successful installation you have to reload all data on the _opsi-configed_ to make the new products become visible there.

If the connection has to be routed through a proxy to access the Internet, this must be entered as the value for `proxy` in the `.repo` configuration files under `/etc/opsi/package-updater.repos.d/`.
As of version 4.1.1.33 of opsi-utils, a global proxy can be configured in `/etc/opsi/opsi-package-updater.conf`.

[source,configfile]
----
[repository_uib_macos_stable]
…
proxy =
----

Should installed packages be updated later, this can be done with the following command:
[source,prompt]
----
opsi-package-updater -v update
----

More information about `opsi-package-updater` can be found in the manual.

[[opsi-macclient-installation-config-get-essential-products-manually]]
== Manual installation of the macOS opsi products.

It is also possible to manually download and install the packages.

Get the latest opsi packages in the `.opsi` package format.
You can find the packages at https://download.uib.de/opsi4.2/stable/packages/macos/localboot or at `https://download.uib.de/opsi4.2/testing/packages/macos/localboot`.

We recommend saving the .opsi files to `/var/lib/opsi/repository`.
To ensure that {opsiconfd} can access the files, `opsi-set-rights /var/lib/opsi/repository` should be run.

After downloading, you need to install the packages on the server using the command `opsi-package-manager -i <package-name>.opsi`.