////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:toc: left
:toclevels: 3
:numbered:
:icons: font
:xrefstyle: full
:doctype:   book
:date:      01.04.2022
:lang: en

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]


= opsi macOS client manual

// Include common opsi copyright
include::../common/opsi_manual_copyright.asciidoc[]


[[opsi-macclient-introduction]]
== Introduction macOS clients in opsi

This manual describes the operation of macOS clients in opsi.

It's assumed that the installation and startup of an {opsi-server} has already been performed.

Essential topics of this manual:

. Adding and integrating macOS computers in opsi
(Installation of the opsi-mac-client-agent)
. Deployment of opsi standard software for macOS on the {opsi-server} .
. Installation of standard software on macOS clients
. opsi standard software for macOS under opsi
. Packaging of own software
. Creation of opsi packages
. Notes about macOS clients
.. Special commands for macOS
.. Directories you may use
.. The pseudo user opsisetupadmin

[[opsi-macclient-convention]]
== Conventions of this document

Commands are highlighted separately:

[source,shell]
----
this is a command
----

As part of the installation and configuration process, you can copy and execute the commands from these fields in order by _copy & paste_ from this document.

Commands or file names will be highlighted as:  `opsi-set-rights` oder `/Applications/opsi-script`.

This is an {opsi-script} code:

[source,winst]
----
Message "Installing "+ $ProductId$ +" ..."
----

Chapters containing the name of a particular platform are specific to that platform. The supported platforms are:

* *Windows*

* *Linux*

* *macOS*


include::requirements.adoc[]

include::minimal-products.adoc[]

include::adding-clients.adoc[]

include::rollout-products.adoc[]

include::softwareintegration.adoc[]

include::general-notes.adoc[]

include::more.adoc[]
