////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype: book
:macosclientmanual: opsi-macos-client-manual

include::common:partial$opsi_terms.adoc[]




[[opsi-macclient-softwintegration]]
= Integration of own software into the software distribution of opsi.

The installation of software in opsi is performed by the opsi-client-agent and specially by the script controlled setup program {opsi-script}. Therefore an opsi-script script must be created for each opsi product. Afterwards this script, as well as the installation files and metadata are packed into an opsi product, which can finally be installed on the {opsi-server}.

[[opsi-macclient-softwintegration-tutorial]]
== A Brief Tutorial: How to write a opsi-script Script


include::common:partial$softwintegration-tutorial-introduction.adoc[leveloffset=-1]

[[opsi-macclient-softwintegration-tutorial-general]]
=== Methods of non-interactive software installation on macOS.

Apple (unlike Microsoft) standardized its software installation methods very early on. In essence, there are two methods:

* *application Directory*: +
This is a directory according to the pattern:
`<application name>.app` However, such a directory is not displayed in the _Finder_ as a directory, but as an 'application'. Inside this directory, according to a pattern, the files of the application must be located. A typical structure would be:

----
opsi-script.app
  |--Contents
       |-Info.plist
       |-PkgInfo
       |-MacOS
       |  |-opsi-script
       |  |-opsi-script-gui
       |
       |-Resources
          |- (....)
----

Such a directory must only be copied into the path `/Applications` for installation. Possible files in the directory `MacOS` must be made executable. +
Such *.app directories are usually offered packed for download.

* *PKG file*: +
These files contain software which need to be installed by a special command.

In both cases an _unattended_ (i.e. non-interactive) installation is not an issue.

Often macOS software is offered in packed formats like *.zip, *.dmg
or also *.tgz.

All variants mentioned so far can be installed directly by opsi-script, except *.tgz which must be unpacked before.

include::common:partial$softwintegration-tutorial-script-structure-opsi-script-basics.adoc[leveloffset=-1]


[[opsi-macclient-softwintegration-tutorial-macos-special-commands]]
==== Special commands for macOS

* GetOS // returns: Linux or Windows_NT or macos [W/L/M]

* getMacosVersionInfo [M]

* getMacosVersionMap [M]

See also: +
https://docs.opsi.org/opsi-docs-en/4.2/opsi-script-manual/reference-card.html#opsi-script-rc-macos-specific

In the following chapters special opsi MacOS commands to install software are presented, which come from the opsi-script library `uib_macosinstalllib`. This documentation was automatically generated directly from the source code.

// http://www.methods.co.nz/asciidoc/userguide.html#X90


// Include os-lib_uib_macosinstalllib.asciidoc

include::common:partial$os-lib-uib-macosinstalllib.adoc[leveloffset=4]


[[opsi-macclient-softwintegration-tutorial-template]]
=== Example: macOS template _m-opsi-template_

You can create this template with the _opsi-setup-detector_.

// include docu: actual template for macOS
include::common:partial$firststeps-opsi-template-mac.adoc[]



[[opsi-client-softwintegration-create-opsi-package]]
== Create an opsi product package

////
[[opsi-setup-detector-installation]]
=== Installation of the opsi-setup-detector, opsi PackageBuilder and opsi-logviewer
////

// include docu: opsi-setup-detector installation
include::common:partial$setup-detector-installation.adoc[]


// include docu: opsi-logviewer installation
include::common:partial$logviewer-installation.adoc[leveloffset=-1]



[[opsi-macclient-softwintegration-tutorial-create-with-opsi-setup-detector]]
=== The opsi-setup-detector program to create a macOS script.

// include docu: opsi-setup-detector
include::common:partial$setup-detector-use-start.adoc[]

// include docu: macos specific tasks in opsi-setup-detector
include::common:partial$osd-tasks-macos.adoc[]

The following screenshots show the use of Windows installer files,
but they look similar when using MacOS installer files like *.app, *.dmg, *.zip.

// include docu: how to use the opsi-setup-detector
include::common:partial$osd-task-use-single-analyze-and-create.adoc[]

More details about the _opsi-setup-detector_ can be found in the opsi-manual: +
https://docs.opsi.org/opsi-docs-en/4.2/manual/modules/setup-detector.html

// include docu: how to use the opsiPackagebuilder
include::common:partial$softwintegration-tutorial-packagebuilder-use.adoc[leveloffset=-1]

// include docu: The modify and test cycle
include::common:partial$softwintegration-tutorial-modify-test-cycle.adoc[leveloffset=-1]

[[opsi-winclient-softwintegration-tutorial-template-details]]
== Suggestions on How to Solve Problems with opsi-script Scripts

// include docu: OSD Checkboxes for additional code
include::common:partial$osd-checkboxes-subtasks.adoc[leveloffset=-1]

