////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      30.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

# Roll out products to the clients

Next, we run the **hwaudit** product on all clients, which creates a hardware inventory of each device.
This is done using one of the two opsi user interfaces.
In this guide we use the xref:gui:configed.adoc[opsi-configed]. A description of the {opsi-webgui} can be found in the chapter xref:gui:webgui.adoc[opsi-webgui].


NOTE: For a more detailed description, see chapter xref:clients:windows-client/rollout-products.adoc[opsi-clients].

## Distribute products

In the interface, first select one or more clients and then switch to the _Localboot Products_ tab.
Here, select the _hwaudit_ product from the list and click in the _Requested_ column. A context menu opens.
Here you select _setup_.

Open the context menu with the right mouse button and select the entry _Save and run now_.
The product will now be executed on the selected clients.
As soon as the status changes to _installed_ you can see the result of the inventory in the tab _Hardware Information_.

You can now install more products on the server and then deploy them to the clients.

NOTE: Instead of running products immediately, you can wait until the next system startup.
At system startup, clients automatically process pending actions before user login.

Translated with www.DeepL.com/Translator (free version)