////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      30.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

# Roll out products to the clients

Next, we run the **hwaudit** product on all clients. This is done using one of the two opsi user interfaces.
In this guide we use the xref:gui:configed.adoc[opsi-configed]. A description of the {opsi-webgui} can be found in the chapter xref:gui:webgui.adoc[opsi-webgui].


NOTE: For a more detailed description, see chapter xref:clients:windows-client/rollout-products.adoc[opsi-clients].

## Distribute products

In the interface, first select one or more clients and then switch to the **Localboot Products** tab. 
Here, select the **hwaudit** product from the list and click in the **Requested** column. A context menu opens.
Here you select **setup**. 

There is now a red tick in the upper left corner. The setting is saved by clicking the tick.
Now the product **hwaudit** will be installed at the next system start of the clients.

NOTE: You can also start the installation directly on running clients. To do this, click on the play button above the table. Alternatively, you can select 'Run now (on demand)' from the right-click menu.