////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

////
;***************************************************************************
; Subversion:
; $Revision:  $ $Author: oertel $
; $Date: $
;***************************************************************************
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.0.7
:doctype:   book

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]

[[opsi-407-releasenotes]]
= opsi Version 4.0.7 Release Notes

// Include common opsi copyright
include::../common/opsi_manual_copyright.asciidoc[]

[[opsi-407-releasenotes-supportmatrix]]
== opsi Support Matrix

This is an overview on which distributions and releases the opsi-server will run:

include::../common/opsi_manual_supportmatrix.asciidoc[]

If you are using an OS version which is not contained in the section above,
we recommend updating the OS before installing opsi v4.0.7.

[[opsi-407-releasenotes-overview]]
== Overview of the new features

The Highlights of this Release are:

* ######
* New opsi bootimage
* New opsi-linux netboot products

The opsi Service Release 4.0.7 comes with a whole bunch of new features and improvements.
Here is a summary:

* ######


* New opsi-bootimage
** Uses Ubuntu Xenial 16.04 as base
** Kernel 4


* opsi-configed:



* opsi-client-agent: +


* python-opsi:

** Many improvements, new features and bugfixes. +
See special chapter: <<opsi-407-releasenotes-python-opsi>>




* opsi-winst / opsi-script (4.11.6.1)


** Upgrade of the SSL libraries to 1.0.2h, update of the SSL protocol to TLS autonegotiation



* Linux netboot products:




////
For details please refer to the opsi-v405-releasenotes manual and the revised opsi manuals.
////

[[opsi-407-releasenotes-packages]]
== list of packages

.server packages:
* opsi-depotserver
* opsi-linux-support
* opsi-utils
* opsiconfd
* python-opsi
* opsi-linux-bootimage
* opsi-configed

.opsi packages (localboot):
* opsi-client-agent
* opsi-configed
* config-win10

.opsi packages (netboot):
* win* 
* opsi-clonezilla

.opsi packaages (opsi-linux):
* centos70_
* redhat70_
* debian7-
* debian8-
* Ubuntu14-04
* Ubuntu16-04
* opensuse13-2
* sles12

.opsi packages(opsi-local-image):
* opsi-local-image-win* 
* opsi-local-image-capture
* opsi-local-image-capture-prepare


[[opsi-407-releasenotes-missing]]
== What is still missing (and under progress)

* opsi-client-agent: +
To execute opsi-winst scripts as the current user during logon 'User Profile Management'.

* opsi-linux-client-agent: +
A real service, that also provides 'push installations'.

* opsi-linux 4.0.7 netboot products: uefi support

* opsi-clonezilla: uefi support



[[opsi-407-releasenotes-knownbugs]]
== Known Bugs / Known Problems

.KNOWN BUGS:

* ######

.KNOWN PROBLEMS:

* ######

[[opsi-407-releasenotes-eol]]
== Discontinuation

[[opsi-407-releasenotes-eol_server]]
=== Discontinuation: Distributions for opsi-server

This chapter lists distributions that for several reasons are not supported by opsi anymore.

* ######

See also the support matrix: <<opsi-407-releasenotes-supportmatrix>>.

[[opsi-407-releasenotes-eol_winclient]]
=== Discontinuation clients: Windows versions

With opsi v4.0.7 the netboot packages for

* ######

are not maintained anymore. +
Also in the near future the Update Abos will not support these Windows versions anymore. +
Please contact us in case of any questions or concerns.

See also the chapter: <<opsi-407-releasenotes-netboot-windows>>.

[[opsi-407-releasenotes-eol_linclient]]
=== Discontinuation clients: Linux versions

With opsi v4.0.7 the netboot packages for

* ######

will not be maintained anymore. Please contact us in case of any questions or concerns.


[[opsi-407-releasenotes-installation]]
== Installation notes

For safety reasons we recommend creating a backup of your backends with +
{opsi-backup} before updating:
[source,prompt]
----
opsi-backup create
----

The products contained in this release depend on each other in many cases. +
Do not try to install just parts of this update.

We recommend to first update the server and then the opsi products.


To make sure that permissions are applied correctly +
we recommend to run ``opsi-setup --set-rights`` after the installation. +
Please be aware that the execution of latter can last for many minutes.


[[opsi-407-releasenotes-installation-opsipackages]]
=== Notes for updating opsi-packets

////
Bitte nachstehenden Block bei release nicht löschen sondern auskommentieren
////


For installing the testing server packets the opsi repository has to be changed from `opsi40` to `opsi40-testing`.

In case of Ubuntu 14.04: +
`deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/opsi40/xUbuntu_14.04 ./` +
replace with: +
`deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/opsi40-testing/xUbuntu_14.04 ./`

Then the packages can be updated. +


For example Ubuntu / Debian:
[source,prompt]
----
aptitude update
aptitude full-upgrade
----
For installing the opsi products: +

For installing the testing opsi products you should add to the file: +
`/etc/opsi/opsi-product-updater.conf` +
the following section

[source,prompt]
----
[repository_opsi_406_testing]
baseUrl = http://download.uib.de
dirs = opsi4.0/testing/opsi-v406/products/localboot, opsi4.0/testing/opsi-v406/products/netboot
active = true
username =
password =
autoInstall = false
autoUpdate = true
autoSetup = false
onlyDownload = false
----

You may append the `dirs` line by:

* `, opsi4.0/testing/opsi-v406/opsi-linux`

* `, opsi4.0/testing/opsi-v406/opsi-local-image`


Set in the section `[repository_uib]` the following line:
[source,prompt]
----
active = false
----
Then execute the opsi-product-updater.


To install all packets:
[source,prompt]
----
opsi-product-updater -i -vv
----

To install updates only:
[source,prompt]
----
opsi-product-updater -vv
----

////
Bitte vorstehenden Block bei release nicht löschen sondern auskommentieren
////

////
The installation does not require any special action. It is performed within the normal updates of your server and opsi products.

First update the server according to the update command of your Linux distribution. +

We recommend to set in `/etc/opsi/opsi-product-updater.conf`
in the section `[repository_uib]` the following to get all products even if they start with win* :
[source,prompt]
----
excludes =
----

If you need the opsi-linux products you should append the `dirs` entry: +

[source,prompt]
----
dirs = opsi4.0/products/localboot, opsi4.0/products/netboot
----
by the path `opsi4.0/products/opsi-linux`

If you need the opsi-local-image products you should append the `dirs` entry
by the path `opsi4.0/products/opsi-local-image`

Then execute the opsi-product-updater.

[source,prompt]
----
opsi-product-updater -i -vv
----

To install updates only:
[source,prompt]
----
opsi-product-updater -vv
----

In case of a multi depot installation first upgrade the config-server before upgrading the depots.


If you want to use product-ids with a length of more than 32 characters and are using the MySQL-backend please update the table definition on your configserver with the following command:

[source,prompt]
----
opsi-setup --update-mysql
----
////

[[opsi-407-releasenotes-linux]]
== Linuxsupport

############
////
include::../common/opsi_manual_linux.asciidoc[]
////

[[opsi-script]]
== opsi-script / opsi-winst 4.11.6

* Security Upgrade zu Windows SSL Libraries 1.0.2h (libeay32.dll, ssleay32.dll) +
Update des SSL Protokolls auf TLS autonegotiation

[[opsi-winst-rc-json]]
=== opsiservicecall and json Related functions [W/L]

`jsonIsValid(`<jsonstr>`) : boolean`  //since 4.11.6: [W/L]

`jsonIsArray(`<jsonstr>`) : boolean`  //since 4.11.6: [W/L]

`jsonIsObject(`<jsonstr>`) : boolean`  //since 4.11.6: [W/L]

`jsonAsObjectHasKey(`<jsonstr>,<keystr>`) : boolean`  //since 4.11.6: [W/L]

`jsonAsArrayCountElements(`<jsonstr>`) : intstr`  //since 4.11.6: [W/L]

`jsonAsObjectCountElements(`<jsonstr>`) : intstr`  //since 4.11.6: [W/L]

`jsonAsArrayGetElementByIndex(`<jsonstr>, <indexstr>`) : jsonstring`  //since 4.11.6: [W/L]

`jsonAsObjectGetValueByKey(`<jsonstr>, <keystr>`) : valuestring`  //since 4.11.6: [W/L]

`jsonAsObjectSetValueByKey(`<jsonstr>, <keystr>,<valuestring>`) : jsonstring`  //since 4.11.6: [W/L]

`jsonAsObjectSetStringtypeValueByKey(`<jsonstr>, <keystr>,<valuestring>`) : jsonstring`  //since 4.11.6: [W/L]

`jsonAsArrayPutObjectByIndex(`<jsonstr>, <indexstr>, <objectstr>`) : jsonstring`  //since 4.11.6: [W/L]

`jsonAsArrayToStringList(`<jsonstr>`) : stringlist`  //since 4.11.6: [W/L]

`jsonAsObjectGetKeyList(`<jsonstr>`) : stringlist`  //since 4.11.6: [W/L]

`jsonStringListToJsonArray(`<strlist>`) : jsonstr`  //since 4.11.6: [W/L]



[[opsi-407-releasenotes-python-opsi]]
== python-opsi 4.0.7.

###################

[[opsi-407-releasenotes-netboot-windows]]
== opsi Support Matrix Windows Clients

Im folgenden finden Sie eine Übersicht auf welchen Windows Plattformen opsi
als Client läuft.

include::../common/opsi_manual_supportmatrix-winclient.asciidoc[]




[[opsi-407-releasenotes-misc]]
== Sonstiges

[[opsi-407-releasenotes-misc-changelogs]]
=== Changelogs:


[[opsi-407-releasenotes-misc-changelogs-opsi-configed]]
==== Changelog opsi-configed

#############

[[opsi-407-releasenotes-misc-changelogs-opsi-client-agent]]
==== Changelog opsi-client-agent

###############

[[opsi-407-releasenotes-misc-changelogs-config-win10]]
###############

[[opsi-407-releasenotes-misc-changelogs-opsi-script]]
==== Changelog opsi-script / opsi-winst
###############


[[opsi-407-releasenotes-misc-changelogs-windows-netboot]]
==== Changelog windows netboot products
###############

[[opsi-407-releasenotes-misc-changelogs-linux-netboot]]
==== Changelog linux netboot products

###############

.centos70

###############


.debian7

###############


.debian8

###############


.opensuse13-2
###############

.sles12
###############

.redhat70
###############

.Ubuntu14-04
###############


[[opsi-407-releasenotes-misc-changelogs-opsi-local-image]]
==== Changelog opsi-local-image

###############


[[opsi-407-releasenotes-misc-changelogs-misc-netboot]]
==== Changelog misc netboot products

###############

[[opsi-407-releasenotes-misc-changelogs-python-opsi]]
==== Changelog python-opsi

###############

[[opsi-407-releasenotes-misc-changelogs-opsiconfd]]
==== Changelog opsiconfd

###############
####################

[[opsi-407-releasenotes-misc-changelogs-opsi-utils]]
==== Changelog opsi-utils

###############

####################

[[opsi-407-releasenotes-misc-changelogs-opsi-linux-bootimage]]
==== Changelog opsi-linux-bootimage

###############

[[opsi-407-releasenotes-misc-changelogs-opsi-depotserver]]
==== Changelog opsi-depotserver

###############

####################

[[opsi-407-releasenotes-misc-changelogs-opsi-atftp]]
==== Changelog opsi-atftp


####################

[[opsi-407-releasenotes-misc-changelogs-opsipxeconfd]]
==== Changelog opsi-atftp


####################

[[opsi-407-releasenotes-misc-changelogs-opsi4ucs]]
==== Changelog opsi4ucs


####################

[[opsi-407-releasenotes-misc-changelogs-opsi-swaudit]]
==== Changelog opsi-swaudit
####################

 [[opsi-407-releasenotes-misc-changelogs-opsi-template]]
==== Changelog opsi-template
####################

