////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      06.11.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full


If access is to take place via an HTTP proxy, configure the proxy settings system-wide via environment variables.
Enter these environment variables in the file `/etc/environment`.

NOTE: Please note that the names of the environment variables consist exclusively of lower case letters.

* `http_proxy`: Configures the proxy for HTTP connections, requires a complete URL (not just host name and port); if authentication is required, this can be defined in the URL: +
`http_proxy=http://<user>:<password>@<proxy-address>:<port>`
* `https_proxy`: like `http_proxy`, only for HTTPS connections: +
`https_proxy=https://<proxy-address>:<port>`
* `no_proxy`: defines for which addresses no proxy should be used; multiple addresses are separated by commas: +
`no_proxy=127.0.0.1,localhost,mydomain.example,hostname.domain.com:8080` +
The following rules apply to the addresses:
** Use lower case letters only.
** Only make a note of IP addresses if access is made directly to the IP address. No name resolution takes place when evaluating the exceptions.
** IP address ranges (CIDR matching, such as `192.168.0.0/24`) are not permitted.
** You must also define exceptions for local addresses (`localhost`) and loopback addresses (`127.0.0.1`).
** Wildcards and regular expressions are not allowed.
** Each name is evaluated as a suffix, `domain.com` therefore defines an exception for all hostnames ending in `domain.com`.
** For each address, you can optionally specify a port after a colon for which the exception applies.


Example for the file `/etc/environment`:

[source,toml]
----
http_proxy=http://10.1.1.1:8080
https_proxy=https://10.1.1.1:8080
no_proxy=127.0.0.1,localhost,company.tld
----

Apply the changes to the running shell by executing the following commands:

[source,console]
----
set -a; source /etc/environment; set +a
----

NOTE: For Suse distributions, the parameter `NO_PROXY` in the file /etc/sysconfig/proxy must be adjusted.
Set `NO_PROXY=127.0.0.1,localhost,company.tld` here accordingly.

If opsiconfd is accessed via a proxy, the requests to opsiconfd originate from the IP address of the proxy.
All functions that work with the IP address of the client, such as `networks`, `admin-networks`, `update-ip`, `max-session-per-ip`, will then not work correctly.
The addresses of trusted proxies can be configured in the `trusted-proxies` parameter.
If the connection originates from a trusted proxy, the server evaluates the `X-Forwarded-For` header in order to obtain the original client address.

Example:

[source,toml]
----
admin-networks=[192.168.10.0/24]
trusted_proxies=[192.178.16.27]
----
