////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      18.12.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

If you require access through an HTTP proxy, you should configure the proxy settings on a system-wide level using environment variables. These environment variables should be entered into the `/etc/environment` file.

NOTE: It's important to remember that the names of these environment variables are composed exclusively of lowercase letters.

* `http_proxy`: This sets up the proxy for HTTP connections. It requires a complete URL (not just the host name and port). If authentication is required, include it in the URL: +
`\http_proxy=http://<user>:<password>@<proxy-address>:<port>`
* `https_proxy`: Similar to `http_proxy`, but for HTTPS connections: +
`\https_proxy=https://<proxy-address>:<port>`
* `no_proxy`: Specifies addresses that should bypass the proxy. List multiple addresses separated by commas:
`no_proxy=127.0.0.1,localhost,mydomain.example,hostname.domain.com:8080` +
Keep in mind the following rules for these addresses:
The following rules apply to the addresses:
** Use lowercase letters only.
** Include IP addresses only if direct access is through an IP address. No name resolution occurs when evaluating exceptions.
** CIDR matching for IP address ranges (like `192.168.0.0/24`) is not allowed.
** Always define exceptions for local addresses (`localhost`) and loopback addresses (`127.0.0.1`).
** Wildcards and regular expressions are not supported.
** Each name is treated as a suffix, meaning `domain.com` creates an exception for all hostnames ending in `domain.com`.
** Optionally, specify a port after a colon for each address to limit the exception to that port.

Example for the `/etc/environment` file:

[source,toml]
----
http_proxy=http://10.1.1.1:8080
https_proxy=https://10.1.1.1:8080
no_proxy=127.0.0.1,localhost,company.tld
----

To apply the changes to the running shell, execute the following commands:

[source,console]
----
set -a; source /etc/environment; set +a
----

NOTE: For Suse distributions, the parameter `NO_PROXY` in the file `/etc/sysconfig/proxy` must be adjusted. Set `NO_PROXY=127.0.0.1,localhost,company.tld` here accordingly.

If access to `opsiconfd` is routed through a proxy, the service requests will appear to come from the IP address of the proxy. Consequently, all functions relying on the client's IP address, such as `networks`, `admin-networks`, `update-ip`, or `max-session-per-ip`, may not function correctly. To address this, you can specify trusted proxy addresses using the `trusted-proxies` parameter. When a connection is made from a trusted proxy, the server will evaluate the `X-Forwarded-For` header to determine the original client's IP address.

Example:

[source,toml]
----
admin-networks=[192.168.10.0/24]
trusted_proxies=[192.178.16.27]
----
