////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      10.01.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



If you need to access through an HTTP proxy, it's recommended to set the proxy settings at a system-wide level using environment variables. These should be entered into the `/etc/environment` file.

NOTE: Keep in mind that the names of these environment variables consist only of lowercase letters.

* `http_proxy`: Configures the proxy for HTTP connections. It requires the full URL, including if authentication is needed: +
`http_proxy=http://<user>:<password>@<proxy-address>:<port>`
* `https_proxy`: Similar to `http_proxy` but for HTTPS connections: +
`https_proxy=https://<proxy-address>:<port>`
* `no_proxy`: Lists addresses that should bypass the proxy. Use commas to separate multiple addresses: +
`no_proxy=127.0.0.1,localhost,mydomain.example,hostname.domain.com:8080` +
Remember these rules for addresses:
  - Only use lowercase letters.
  - Include IP addresses only for direct access via IPs, as no name resolution occurs for exceptions.
  - CIDR notation for IP address ranges (like `192.168.0.0/24`) is not supported.
  - Always include exceptions for `localhost` and `127.0.0.1`.
  - Wildcards and regular expressions are not supported.
  - Treat each name as a suffix, so `domain.com` applies to all hostnames ending in `domain.com`.
  - Optionally, add a specific port after a colon for each address to confine the exception to that port.

Here's an example for setting up the `/etc/environment` file:

[source,toml]
----
http_proxy=http://10.1.1.1:8080
https_proxy=https://10.1.1.1:8080
no_proxy=127.0.0.1,localhost,company.tld
----

To apply the changes to the currently running shell, execute the following commands:

[source,console]
----
set -a; source /etc/environment; set +a
----

NOTE: For Suse distributions, the `NO_PROXY` parameter in the `/etc/sysconfig/proxy` file needs to be adjusted. Set `NO_PROXY=127.0.0.1,localhost,company.tld` as appropriate.

If the access to `opsiconfd` is channeled through a proxy, the service requests will appear to originate from the IP address of the proxy. As a result, all functionalities that rely on the client's IP address, such as `networks`, `admin-networks`, `update-ip`, or `max-session-per-ip`, might not operate correctly. To address this, you can define trusted proxy addresses using the `trusted-proxies` parameter. When a connection comes from a trusted proxy, the server will look at the `X-Forwarded-For` header to ascertain the real IP address of the client.

Example:

[source,toml]
----
admin-networks=[192.168.10.0/24]
trusted-proxies=[192.178.16.27]
----
