////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      10.01.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



Before the release of opsi 4.3, the `opsi-setup` tool played a central role in executing various configuration tasks on the opsi server.

NOTE: With opsi 4.3, many of these tasks have been automated. Other functionalities are now managed by xref:server:components/opsiconfd.adoc#server-components-opsiconfd-setup[*opsiconfd setup*].

[[server-components-opsi-set-rights]]
== *opsi-set-rights*

The command `opsi-set-rights`, which is essentially a script executing `opsi-setup --set-rights`, is used to correct the access rights of files and directories on an opsi server. When invoked without additional parameters, `opsi-set-rights` automatically adjusts the permissions for all files and directories relevant for opsi. Alternatively, you can specify a path when executing the command to modify the access rights of a specific directory only.
