////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

Each time `opsiconfd` is started, the service automatically makes adjustments to the opsi environment.
As a result, very little manual configuration and maintenance work is usually required.

Among other things, `opsiconfd setup` includes the following setup tasks:

* Automatically update configuration files
* Adjust system resource limits (`ulimit`)
* Create required users and groups
* Create required files and directories
* Configure the `/etc/sudoers` file
* Set permissions for files and directories
* Clean up log files
* Configure systemd
* Set up MySQL database, schema upgrades and cleanup
* Automatically migrate the file backend to the MySQL database
* Configure Redis and cleanup
* Customize Grafana configuration and install addons
* Create and renew opsi-CA and TLS server certificate
* Configure DHCP server
* Configure Samba and create shares

You can also start the setup run manually at any time using this command:

[source,console]
----
opsiconfd setup
----

A complete setup now begins; a reduced setup run takes place during the "normal" `opsiconfd` start in order to speed up the start of the service. 

TIP: You can use the `opsiconfd` parameter `skip-setup` to permanently disable setup tasks.

As a rule, `opsiconfd setup` works non-interactively. 
However, `opsiconfd setup` is also used interactively for the following tasks:

* Manual setup of a MySQL database connection (`--configure-mysql`), see chapter xref:server:components/mysql.adoc[MySQL]
* Manual registration of an opsi depot (`--register-depot`)
* Renaming an opsi config server (`--rename-server`)

NOTE: To completely exclude any interaction of `opsiconfd setup` with the user, for example when used in scripts, you can use the `--non-interactive` parameter.
