////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      07.11.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

You can use the command line tool `opsi-outdated-to-setup` to set action requests for clients on which there are localboot products for which a newer version is available in the depot.

[source,console]
----
opsi-outdated-to-setup --help
usage: opsi-outdated-to-setup [-h] [--version] [--log-level {0,1,2,3,4,5,6,7,8,9}] [--clients CLIENTS] [--dry-run]
                              [--client-groups CLIENT_GROUPS] [--exclude-products EXCLUDE_PRODUCTS]
                              [--include-products INCLUDE_PRODUCTS] [--add-failed] [--uninstall-where-only-uninstall]
                              [--exclude-client-groups EXCLUDE_CLIENT_GROUPS] [--include-product-groups INCLUDE_PRODUCT_GROUPS]
                              [--exclude-product-groups EXCLUDE_PRODUCT_GROUPS] [--setup-on-action SETUP_ON_ACTION]

Set outdated localboot Products to setup.
[…]
----

You can also use `opsi-outdated-to-setup` to set action requests to repeat failed installations. To do this, use the `--add-failed` option.

The parameters `--exclude-products`, `--include-products`, `--exclude-product-groups` and `--include-product-groups` define the products more precisely. You can define the clients more precisely using `--clients`, `--client-groups` and `--exclude-client-groups`.

The option `--uninstall-where-only-uninstall` sets all installed products to `uninstall` if they do not contain any registered script (`setup`, `always` etc.) apart from the `uninstall` script.

TIP: Use the `--dry-run` parameter to start a test run without actually changing anything.

`--setup-on-action` is a special option with which you can set a product to `setup` on all clients on which something has been changed (i.e. which do not have a current package installed). This is useful, for example, in combination with `shutdownwanted` to perform a shutdown after installation, or with `waudit` to update the audit data.
