////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      10.01.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

On the opsi config server, you can use cronjobs to schedule product installations and updates, allowing you to, for instance, shift critical administrative tasks to nighttime hours. For this to be effective, clients must either support Wake on LAN (WOL) or have a wake-up function in the BIOS that automatically powers the computer on from sleep or energy-saving mode at a pre-set time.

To facilitate this process, the command line tool `opsi-wakeup-clients` (previously known as `wake_clients_for_setup.py`) is available.

NOTE: Almost all parameters of `wake_clients_for_setup.py` have been retained in `opsi-wakeup-clients`. The only change is the renaming of the parameter `--depotId` to `--depot-id`.

To access the online help, use the command `opsi-wakeup-clients --help`:

[source,console]
----
opsi-wakeup-clients --help
usage: opsi-wakeup-clients [-h] [--version] [--verbose] [--log-file LOGFILE]
                           [--log-level {0,1,2,3,4,5,6,7,8,9}] [--wol-timeout WOLTIMEOUT]
                           [--ping-timeout PINGTIMEOUT] [--connect-timeout CONNECTTIMEOUT]
                           [--event-timeout EVENTTIMEOUT] [--reboot-timeout REBOOTTIMEOUT]
                           [--host-group-id HOSTGROUPID] [--depot-id DEPOTID] [--host-file INPUTFILE]
                           [--product-group-id PRODUCTGROUPID] [--event EVENTNAME] [--reboot]
                           [--shutdownwanted] [--no-auto-update] [--max-concurrent MAXCONCURRENT]

Wakeup clients for software installation.
[…]
----

`opsi-wakeup-clients` primarily carries out the following tasks:

. For a specified group of clients, it sets
. a certain group of products to the `setup` status.
. It then activates the chosen clients using Wake on LAN.

If a client is only woken up but not fully started, `opsi-wakeup-clients` has the capability to send a signal to trigger a specific event.

The clients to be selected are identified in several ways:

* Specify a host group that you have created, for example, using `opsi-configed` (refer to the section xref:gui:configed.adoc#opsi-manual-configed-treeview[Grouping Clients]): +
[source,console]
----
--host-group-id <HOSTGROUPID>
----

* Define an opsi depot, which automatically selects all clients associated with that depot: +
[source,console]
----
--depot-Id <DEPOTID>
----

* Specify a file that lists the desired clients: +
[source,console]
----
--host-file <DATEI>
----

* To set multiple products to `setup`, you can specify a product group that you have previously created using `opsi-configed`. For more information on this, see the section xref:opsi-modules:software-on-demand.adoc#software-on-demand_product-group-management[Managing Product Groups]. +
[source,console]
----
--product-group-id <PRODUCTGROUPID>
----

* Finally, enter the event that you want to trigger; the parameter `--event` is used for this: +
[source,console]
----
--event <EVENTNAME>
----

CAUTION: In opsi, the names of groups must be unique. This applies to both host groups (located in the _Directory_ or _Groups_ areas in `opsi-configed`) and product groups.

The following example illustrates how to set the products from the product group `nightly-cron-products` to `setup` for all clients in the host group `nightly-cron-group-0`:

[source,console]
----
opsi-wakeup-clients --event=gui_startup --product-group-id=nightly-cron-products --host-group-id=nightly-cron-group-0
----

The clients are then awakened via Wake on LAN, and after a brief pause, the command is issued to execute the `gui_startup` event.

=== Setting up the Cronjob

To schedule the operation at a specific time each day, you need to enter the command in the server's crontab. To do this, run the command `crontab -e` as the root user. In the standard editor that opens, you can enter the following:

[source,configfile]
----
# For more information see the manual pages of crontab(5) and cron(8)
#
# m h  dom mon dow   command

# Cronjobs zum Wecken und Installieren der PCs
5 0 * * * /usr/bin/opsi-wakeup-clients --log-level=5 --event=gui_startup --product-group-id=nightly-cron-prodcts --host-group-id=nightly-cron-group-1 --wol-timeout=120 --event-timeout=120
5 2 * * * /usr/bin/opsi-wakeup-clients --log-level=5 --event=gui_startup --product-group-id=nightly-cron-products --host-group-id=nightly-cron-group-2 --wol-timeout=120 --event-timeout=120
----

The command `opsi-wakeup-clients` is scheduled to run at 0:05 for the client group `nightly-cron-group-1` and again at 2:05 for the client group `nightly-cron-group-2`.

NOTE: When setting up such automation, it is important to ensure that installations do not inadvertently occur outside of the designated "maintenance window". This can be prevented by configuring the xref:clients:windows-client/windows-client-agent.adoc#opsi-manual-clientagent-working-window[Working Window] in the `opsi-client-agent` settings.
