////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      07.11.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

Before opsi 4.3 `opsi-setup` was a central tool for various configuration tasks on the opsi server.

NOTE: With opsi 4.3 many of these tasks have been automated. Other functionalities are handled by xref:server:components/opsiconfd.adoc#server-components-opsiconfd-setup[*opsiconfd setup*].

[[server-components-opsi-set-rights]]
== *opsi-set-rights*

The command `opsi-set-rights` (actually a script that executes the command `opsi-setup --set-rights`) corrects the access rights of files and directories on an opsi server. Called without further parameters, `opsi-set-rights` automatically processes all files and directories that are relevant for opsi. Alternatively, specify a path when calling it to modify only a specific directory.
