////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      21.12.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

The `opsiconfd` service performs automatic adjustments to the opsi environment each time it is started. As a result, manual configuration and maintenance efforts are typically minimal.

The setup tasks included in `opsiconfd setup` encompass various essential operations:

* Automatic updating of configuration files.
* Adjustment of system resource limits (`ulimit`).
* Creation of necessary users and groups.
* Generation of required files and directories.
* Configuration of the `/etc/sudoers` file.
* Setting permissions for files and directories.
* Cleanup of logfiles.
* Configuration of systemd.
* Setup and maintenance of the MySQL database, including schema upgrades and cleanups.
* Automatic migration from the file backend to the MySQL database.
* Configuration and cleanup of Redis.
* Customization of Grafana configuration and installation of addons.
* Creation and renewal of the opsi-CA and TLS server certificate.
* Configuration of the DHCP server.
* Configuration of Samba and creation of shares.

To manually initiate a setup run at any time, use the following command:

[source,console]
----
opsiconfd setup
----

A full setup is initiated now; however, to speed up the service start-up, a reduced setup run is executed during the "normal" `opsiconfd` start.

TIP: The `opsiconfd` parameter `skip-setup` can be used to permanently disable setup tasks.

Typically, `opsiconfd setup` operates non-interactively. Nevertheless, it also supports interactive tasks for specific purposes:

* Manual configuration of a MySQL database connection (`--configure-mysql`), detailed in chapter xref:server:components/mysql.adoc[MySQL].
* Manual registration of an opsi depot server (`--register-depot`).
* Renaming an opsi config server (`--rename-server`).

NOTE: To ensure `opsiconfd setup` runs without any user interaction, particularly useful in scripting contexts, you can use the `--non-interactive` parameter.
