////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      09.01.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



Use the `opsi-package-manager` tool to install and uninstall product packages on an opsi depot server.

NOTE: To install a package, it must be readable by the user `opsiconfd` (refer to the chapter xref:server:components/authorization.adoc[Authorizations] for more details). It is recommended to store product packages in `/var/lib/opsi`.

How to install an opsi package:

[source,console]
----
opsi-package-manager -i <opsi-package>
----

To install an opsi package and interactively set the default values for product properties:

[source,console]
----
opsi-package-manager -p ask -i <opsi-package>
----

To install an opsi package and set it to `setup` for all clients where it is installed:

[source,console]
----
opsi-package-manager -S -i <opsi-package>
----

To install an opsi package and set it to `setup` for all clients on which it is installed, including the packages that depend on it:

[source,console]
----
opsi-package-manager -s -i <opsi-package>
----

To uninstall an opsi package:

[source,console]
----
opsi-package-manager -r <opsi-package>
----

[source,console]
----
opsi-package-manager -x <opsi-package> --new-product-id <product-id>
----

For an overview of all options, use `opsi-package-manager --help`.
