////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      06.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

You use the `opsi-package-manager` tool to install and uninstall product packages on an opsi depot server.

NOTE: If you want to install a package, it must be readable for the user `opsiconfd` (see chapter xref:server:components/authorization.adoc[Authorizations]). We therefore recommend storing product packages under `/var/lib/opsi`.

How to install an opsi package:

[source,console]
----
opsi-package-manager -i <opsi-package>
----

To install an opsi package and interactively set the default values for product properties:

[source,console]
----
opsi-package-manager -p ask -i <opsi-package>
----

To install an opsi package and set it to 'setup' for all clients on which it is installed:

[source,console]
----
opsi-package-manager -S -i <opsi-package>
----

To install an opsi package and set it to `setup` for all clients on which it is installed; this also affects the packages that depend on it:

[source,console]
----
opsi-package-manager -s -i <opsi-package>
----

To uninstall an opsi package:

[source,console]
----
opsi-package-manager -r <opsi-package>
----

[source,console]
----
opsi-package-manager -x <opsi-package> --new-product-id <product-id>
----

An overview of all options is provided by `opsi-package-manager --help`.
