////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      09.01.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



You can use the command line tool `opsi-outdated-to-setup` to set action requests for clients that have localboot products for which a newer version is available in the depot.

[source,console]
----
opsi-outdated-to-setup --help
usage: opsi-outdated-to-setup [-h] [--version] [--log-level {0,1,2,3,4,5,6,7,8,9}] [--clients CLIENTS] [--dry-run]
                              [--client-groups CLIENT_GROUPS] [--exclude-products EXCLUDE_PRODUCTS]
                              [--include-products INCLUDE_PRODUCTS] [--add-failed] [--uninstall-where-only-uninstall]
                              [--exclude-client-groups EXCLUDE_CLIENT_GROUPS] [--include-product-groups INCLUDE_PRODUCT_GROUPS]
                              [--exclude-product-groups EXCLUDE_PRODUCT_GROUPS] [--setup-on-action SETUP_ON_ACTION]

Set outdated localboot Products to setup.
[…]
----

You can also use `opsi-outdated-to-setup` to set action requests for repeating failed installations by using the `--add-failed` option.

The parameters `--exclude-products`, `--include-products`, `--exclude-product-groups`, and `--include-product-groups` allow for more precise definition of the products. Similarly, you can specify the clients more accurately using `--clients`, `--client-groups`, and `--exclude-client-groups`.

The `--uninstall-where-only-uninstall` option is used to set all installed products to `uninstall` if they have no registered script (like `setup`, `always`, etc.) other than the `uninstall` script.

TIP: Employ the `--dry-run` parameter to initiate a trial run without making any actual changes.

The `--setup-on-action` is a unique option that enables setting a product to `setup` on all clients where any change has occurred (i.e., clients that do not have the current package installed). This is particularly useful in scenarios like using `shutdownwanted` for a shutdown post-installation, or with `waudit` to refresh the audit data.
