////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      06.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

Vor opsi 4.3 war `opsi-setup` ein zentrales Werkzeug für verschiedene Konfigurations-Aufgaben auf dem opsi-Server.

NOTE: Mit opsi 4.3 wurden viele dieser Aufgaben automatisiert. Andere Funktionalitäten übernimmt xref:server:components/opsiconfd.adoc#server-components-opsiconfd-setup[*opsiconfd setup*].

[[server-components-opsi-set-rights]]
== *opsi-set-rights*

Das Kommando `opsi-set-rights` (eigentlich ein Skript, das den Befehl `opsi-setup --set-rights` ausführt) korrigiert die Zugriffsrechte von Dateien und Verzeichnissen auf einem opsi-Server. Ohne weitere Parameter aufgerufen bearbeitet `opsi-set-rights` automatisch alle Dateien und Verzeichnisse, die für opsi relevant sind. Alternativ geben Sie einen Pfad beim Aufruf an, um nur ein bestimmtes Verzeichnis zu modifizieren.

