////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      07.11.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

On the opsi config server, you can use cronjobs to schedule product installations and updates and thus, for example, move important administration tasks to the night. For this to work, clients must support Wake on LAN (WOL) or have a wake-up function in the BIOS that automatically wakes the computer from sleep or energy-saving mode at a certain predefined time.

You can use the command line tool `opsi-wakeup-clients` (formerly: `wake_clients_for_setup.py`) to control this process.

NOTE: The parameters of `wake_clients_for_setup.py` have almost all been adopted for `opsi-wakeup-clients`; only the parameter `--depotId` is now called `--depot-id`.

Use `opsi-wakeup-clients --help` to display online help:

[source,console]
----
opsi-wakeup-clients --help
usage: opsi-wakeup-clients [-h] [--version] [--verbose] [--log-file LOGFILE]
                           [--log-level {0,1,2,3,4,5,6,7,8,9}] [--wol-timeout WOLTIMEOUT]
                           [--ping-timeout PINGTIMEOUT] [--connect-timeout CONNECTTIMEOUT]
                           [--event-timeout EVENTTIMEOUT] [--reboot-timeout REBOOTTIMEOUT]
                           [--host-group-id HOSTGROUPID] [--depot-id DEPOTID] [--host-file INPUTFILE]
                           [--product-group-id PRODUCTGROUPID] [--event EVENTNAME] [--reboot]
                           [--shutdownwanted] [--no-auto-update] [--max-concurrent MAXCONCURRENT]

Wakeup clients for software installation.
[…]
----

Essentially, `opsi-wakeup-clients` performs the following tasks:

. For a given group of clients, it sets
. a specific group of products to `setup`.
. It then wakes up the selected clients via Wake on LAN.

If a client has only been woken up and not started, `opsi-wakeup-clients` can send a signal to execute a specific event.

The selected clients are specified in various ways:

* Define a host group that you have created e.{nbsp}B. with `opsi-configed` (see section xref:gui:configed.adoc#opsi-manual-configed-treeview[treeview]): +
[source,console]
----
--host-group-id <HOSTGROUPID>
----

* Enter an opsi depot, which automatically selects all clients in the depot: +
[source,console]
----
--depot-Id <DEPOTID>
----

* Transfer a file that lists the desired clients: +
[source,console]
----
--host-file <DATEI>
----

To set several products to 'setup', specify a product group that you have created with 'opsi-configed', for example (see section xref:opsi-modules:software-on-demand.adoc#software-on-demand_product-group-management[Maintain product groups]).

[source,console]
----
--product-group-id <PRODUCTGROUPID>
----

Finally, enter the event that you want to trigger; the parameter `--event` is used for this:

[source,console]
----
--event <EVENTNAME>
----

CAUTION: The names of groups in opsi must be unique, regardless of whether it is a host group (area _Directory_ or _Groups_ in `opsi-configed`) or a product group. 

The next example shows how to set the products from the product group `nightly-cron-products` to `setup` for all clients of the host group `nightly-cron-group-0`:

[source,console]
----
opsi-wakeup-clients --event=gui_startup --product-group-id=nightly-cron-produkte --host-group-id=nightly-cron-gruppe-0
----

The clients are then woken up via Wake on LAN and after a short wait, the command is sent to execute the `gui_startup` event.

=== Cronjob set up

To run the whole thing at a specific time every day, enter the command in the server's crontab. To do this, call the command `crontab -e` as root, and you can now enter the following in the standard editor that opens:

[source,configfile]
----
# For more information see the manual pages of crontab(5) and cron(8)
#
# m h  dom mon dow   command

# Cronjobs zum Wecken und Installieren der PCs
5 0 * * * /usr/bin/opsi-wakeup-clients --log-level=5 --event=gui_startup --product-group-id=nightly-cron-produkte --host-group-id=nightly-cron-gruppe-1 --wol-timeout=120 --event-timeout=120
5 2 * * * /usr/bin/opsi-wakeup-clients --log-level=5 --event=gui_startup --product-group-id=nightly-cron-produkte --host-group-id=nightly-cron-gruppe-2 --wol-timeout=120 --event-timeout=120
----

The command `opsi-wakeup-clients` is called once at 0:05 for the client group `nightly-cron-group-1` and once at 2:05 for the client group `nightly-cron-group-2`. 

NOTE: If you set up such an automatism, you should prevent installations from accidentally taking place outside the scheduled "maintenance window". You prevent this via the xref:clients:windows-client/windows-client-agent.adoc#opsi-manual-clientagent-working-window[Working Window] in the `opsi-client-agent` configuration.
