////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      06.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

Das Tool `opsi-package-manager` nutzen Sie, um Produkt-Pakete auf einem opsi-Depotserver zu installieren und zu deinstallieren.

NOTE: Wenn Sie ein Paket installieren möchten, muss es für den Benutzer `opsiconfd` lesbar sein (siehe Kapitel xref:server:components/authorization.adoc[Berechtigungen]). Wir empfehlen daher, Produkt-Pakete unterhalb von `/var/lib/opsi` abzulegen.

So installieren Sie ein opsi-Paket:

[source,console]
----
opsi-package-manager -i <opsi-package>
----

So installieren Sie ein opsi-Paket und setzen interaktiv die Standardwerte für Produkteigenschaften:

[source,console]
----
opsi-package-manager -p ask -i <opsi-package>
----

So installieren Sie ein opsi-Paket und stellen es für alle Clients auf `setup`, auf denen es installiert ist:

[source,console]
----
opsi-package-manager -S -i <opsi-package>
----

So installieren Sie ein opsi-Paket und stellen es für alle Clients auf `setup`, auf denen es installiert ist; zusätzlich beeinflusst das die davon abhängenden Pakete:

[source,console]
----
opsi-package-manager -s -i <opsi-package>
----

So deinstallieren Sie ein opsi-Paket:

[source,console]
----
opsi-package-manager -r <opsi-package>
----

[source,console]
----
opsi-package-manager -x <opsi-package> --new-product-id <product-id>
----

Eine Übersicht über alle Optionen liefert `opsi-package-manager --help`.
