////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      06.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

Das Kommandozeilen-Werkzeug `opsi-outdated-to-setup` können Sie verwenden, um Action Requests für Clients zu setzen, auf denen es Localboot-Produkte gibt, für die im Depot eine neuere Version verfügbar ist.

[source,console]
----
opsi-outdated-to-setup --help
usage: opsi-outdated-to-setup [-h] [--version] [--log-level {0,1,2,3,4,5,6,7,8,9}] [--clients CLIENTS] [--dry-run]
                              [--client-groups CLIENT_GROUPS] [--exclude-products EXCLUDE_PRODUCTS]
                              [--include-products INCLUDE_PRODUCTS] [--add-failed] [--uninstall-where-only-uninstall]
                              [--exclude-client-groups EXCLUDE_CLIENT_GROUPS] [--include-product-groups INCLUDE_PRODUCT_GROUPS]
                              [--exclude-product-groups EXCLUDE_PRODUCT_GROUPS] [--setup-on-action SETUP_ON_ACTION]

Set outdated localboot Products to setup.
[…]
----

Außerdem können Sie mit `opsi-outdated-to-setup` Action Requests setzen, um fehlgeschlagene Installationen zu wiederholen. Dazu verwenden Sie die Option `--add-failed`.

Die Parameter `--exclude-products`, `--include-products`, `--exclude-product-groups` und `--include-product-groups` definieren die Produkte genauer. Die Clients können Sie genauer über `--clients`, `--client-groups` und `--exclude-client-groups` definieren.

Die Option `--uninstall-where-only-uninstall` setzt alle installierten Produkte auf `uninstall`, falls sie außer dem `uninstall`-Skript kein registriertes Skript (`setup`, `always` usw.) enthalten.

TIP: Verwenden Sie den Parameter `--dry-run`, um einen Testlauf zu starten, ohne tatsächlich etwas zu verändern.

`--setup-on-action` ist eine besondere Option, mit der Sie auf allen Clients, auf denen etwas geändrt wurde (also die ein nicht aktuelles Paket installiert haben), ein Produkt auf `setup` setzen. Das ist beispielsweise in Kombination mit `shutdownwanted` nützlich, um nach der Installation einen Shutdown auszuführen, oder auch bei `swaudit`, um die Audit-Daten zu aktualisieren.
