////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      22.01.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons: font
:xrefstyle: full

[[opsi-create-client-intro]]
= opsi Clients

For opsi to manage computers, these clients must be recognized by the system. Additionally, a xref:clients:windows-client/windows-client-agent.adoc[Client Agent (Windows)] must be running on the computers to allow communication between server and client. Depending on your environment, there are different methods to add clients:

* If clients already exist with an installed operating system that opsi should manage from now on, integrate them as described in the chapter xref:clients:windows-client/adding-clients.adoc#firststeps-software-deployment-client-integration[Integrating existing Clients].

* Alternatively, you can install a new operating system via opsi on a computer. The required agent is installed automatically as outlined in the chapter xref:clients:windows-client/adding-clients.adoc#add-new-clients[Adding new Clients].
