////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      07.11.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons: font
:xrefstyle: full

[[opsi-create-client-intro]]
= Introduction

In order for opsi to be able to manage computers, these clients must be known to the system. In addition, an xref:clients:client-agent/opsi-client-agent.adoc[client-agent] must be running on the computers so that communication between server and client is possible. Depending on how your environment is set up, there are different procedures for adding clients:

* If clients already exist with an installed operating system that opsi should manage from now on, integrate them (see chapter xref:clients:windows-client/adding-clients.adoc#firststeps-software-deployment-client-integration[Integrate existing clients]).

* Alternatively, you can first equip a computer with a new operating system via opsi. The required agent is installed automatically (see chapter xref:clients:windows-client/adding-clients.adoc#firststeps-osinstall-create-client[Add new clients]).
