////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype:   book

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]

[[opsi-4.2-releasenotes]]
= opsi Version 4.2 Release Notes

// Include common opsi copyright
include::../common/opsi_manual_copyright.asciidoc[]

[[opsi-4.2-releasenotes-overview]]
== Overview of the new features

*Main aspects of this release are:*

* opsi Server
** Switch to Python 3
** New services


[[opsi-4.2-releasenotes-important]]
== Important considerations - Please pay attention

opsi 4.2 is an independent release and thus has it's own package repositories.
These must be added into the system you want to update before installation.

For an update from opsi 4.1 the packages need to be the latest version available on the stable repositories.
Other packages - such as MySQL server - should also be up-to-date.
Otherwise problems are to be expected during the update.

It is also recommended that 'opsi-winst', 'opsi-client-agent' or 'opsi-linux-client-agent' be updated to the latest version of opsi 4.1 before updating on the clients.

[[opsi-4.2-releasenotes-installation]]
== Installation notice

For your own safety, we strongly suggest to create a backup of your backends with {opsi-backup} before updating:
[source,prompt]
----
opsi-backup create
----

The products contained in this release depend on each other in many cases.
Do not try to install just parts of this update.

We recommend to first update the server, and then update the opsi products.

In a multi-depot environment it is recommended to first update the configserver before updating the depots.

To make sure that permissions are applied correctly
we recommend to run `opsi-setup --set-rights` after the installation.
Please be aware that the execution of latter can take several minutes.


[[opsi-4.2-releasenotes-installation-systempackages]]
=== Advice for updating the operating system packages

Please make sure that at the time of the update you are using the latest packages from opsi 4.1 from the stable branch.


[[opsi-4.2-releasenotes-installation-opsipackages]]
=== Notes for updating opsi-packages

opsi-packages are usually compatible with opsi 4.1 and opsi 4.2.

The official opsi 4.1 repositories at _download.uib.de_ contain packages that are compatible with opsi 4.2.
Please note that these packages not necessarily have to contain `4.2` in the version to be compatible.


[[opsi-4.2-releasenotes-installation-migration]]
=== Migration of an opsi 4.2 server

It is possible to migrate an existing opsi 4.1 installation to opsi 4.2 on supported operating systems.

If you manage your opsi servers through opsi than the migration can be done with the package `l-opsi-server-migrate`.

NOTE: Upgrading from opsi 4.0 to opsi 4.2 directly is not supported. In such a case you have to upgrade to opsi 4.1 first before you can upgrade to opsi 4.2.


[[opsi-4.2-releasenotes-installation-migration-repositories]]
==== Changing to the new repositories

First the opsi 4.2 package repositories have to be added to the systems package manager.

The following commands will add the repositories and add the new repository key if required.
These commands require 'root' rights.


Will be filled in later - TBD


[[opsi-4.2-releasenotes-installation-migration-migrate]]
==== Upgrading OS packages

After adding the new package repositories the system can be migrated.

IMPORTANT: For RPM-based distributions, existing configuration files are replaced by new ones during the migration. Please refer to the notes under the corresponding distributions.

Debian and Ubuntu are updated to opsi 4.2 with the following steps:
[source,prompt]
----
apt update
apt dist-upgrade
----

RedHat and CentOS systems need these steps to upgrade to opsi 4.2:
[source,prompt]
----
yum makecache
yum upgrade
----

To migrate SLES and OpenSUSE please perform the following:
[source,prompt]
----
zypper refresh
zypper dup --from home_uibmz_opsi_4.2_stable
----

On UCS you can update with the following command:
[source,prompt]
----
univention-upgrade
----


[[opsi-4.2-releasenotes-installation-migration-opsi-packages]]
==== Updating opsi packages

The last step is to update to the latest opsi packages.

[[opsi-4.2-releasenotes-installation-migration-opsi-packages-standard]]
===== Use of the standard configuration

If you did not alter the configuration of your repositories you can simply run the following command:

[source, prompt]
----
opsi-package-updater -v update
----

After these steps, your opsi 4.1 server is migrated to 4.2 and ready to use.


[[opsi-4.2-releasenotes-installation-migration-cleanup]]
==== Optional cleanup

After a migration it can be that some unrequired files still exist on the server.
The reason for this is that they either have been altered manually or that restoring a backup has brought these files back to the system.

The following files resp. folders can be removed:

* TBD


[[opsi-4.2-releasenotes-knownbugs]]
== Known Bugs / Known Problems

.KNOWN BUGS:

* TBD

.KNOWN PROBLEMS:

* TBD


[[opsi-4.2-releasenotes-eol]]
== Discontinuation

This chapters lists discontinuations.


[[opsi-4.2-releasenotes-eol_server]]
=== Discontinued: Distributions for opsi-server

These distributions will not be supported anymore for different reasons.

* CentOS 7.x
* Debian 8.x
* Debian 9.x
* RedHat Enterprise Linux 7.x
* Suse Linux Enterprise Server 12

Also see separate chapter: <<opsi-4.2-releasenotes-supportmatrix>>.


[[opsi-4.2-releasenotes-supportmatrix]]
== opsi Support Matrix

An overview of the supported platforms for opsi 4.2 servers.

include::supportmatrix-server.asciidoc[]

If you are using an OS version which is not contained in the section above,
we recommend updating the OS before installing opsi v4.2.


[[opsi-releasenotes-4.2-changes-changed-defaults]]
== Changed Defaults

With opsi 4.2 some default settings have been changed to reflect experiences from opsi operations.

This is important if in an already existing environment new opsi servers are to be installed because this may lead to a change in expected behavior.

* For opsiconfd the setting of `update ip` is `yes` by default.
* In the file 'dispatch.conf' the usage of the mysql backend for keeping the inventory is the new default.


[[opsi-releasenotes-4.2-changes-python]]
== Switch to Python 3

This version is now based on Python 3.
The minimum required version is Python 3.6.
Older versions are not supported anymore. This does include any version of Python 2.


[[opsi-4.2-releasenotes-linux]]
== Linux Support

=== Support Matrix

include::supportmatrix-linclient.asciidoc[]

[[opsi-4.2-releasenotes-netboot-windows]]
== opsi Support Matrix Windows Clients

In the following graphic you will find on which Windows platforms opsi can be run as client.

include::supportmatrix-winclient.asciidoc[]


[[opsi-4.2-releasenotes-api-changes]]
== API changes

The API has received changes in opsi 4.2.

This affects the API of the webservice, `opsi-admin`, calls made through
`opsiServiceCall` in opsicript among others.


[[opsi-4.2-releasenotes-changed-api-methods]]
=== Changed API methods

 * `getClients_listOfHashes`: Method has been marked as deprecated during opsi 4.1. If called without parameters will return result from `getClients` in other cases an error will be returned.
 * `getClientIds_list`: Method has been marked as deprecated during opsi 4.1. If called without parameters will return result of `getClientIDs`. If called with parameter `depotIds` then the result of `getClientsOnDepot` will be returned. If called with parameters `productId` and optionally `installationStatus` the result of `getClientsWithProducts` will be returned.


[[opsi-4.2-releasenotes-deprecated-api-methods]]
=== Deprecation of API methods

The following methods are now considered deprecated.
This means they will be removed with the next major or minor release.

 * `getClients_listOfHashes`
 * `getClientIds_list`


[[opsi-4.2-releasenotes-removed-api-methods]]
=== Removal of API methods

The following API methods have been removed:

* `backend_searchIdents`

These methods aren't available anymore.


[[opsi-4.2-releasenotes-misc]]
== Miscellaneous

* TBD


[[opsi-4.2-releasenotes-packages]]
== List of packages

.Server packages:
* opsi4ucs 4.2...
* opsiconfd 4.2...
* opsigateway ...
* opsipxeconfd 4.2...
* opsiwebservice ...
* opsi-server 4.2...
* opsi-utils 4.2...
* python3-opsi 4.2...

NOTE: The updated opsi packages are also made available for opsi 4.1 with this release. The exception for this are `l-opsi-server` and `l-opsi-server-migrate`.

// Changelogs
include::./opsi-v4.1-changelogs.asciidoc[]
