////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype:   book

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]

[[opsi-4.2-releasenotes]]
= opsi Version 4.2 Release Notes

// Include common opsi copyright
include::../common/opsi_manual_copyright.asciidoc[]

[[opsi-4.2-releasenotes-overview]]
== Overview of the new features

*Main aspects of this release are:*

* Switch to Python 3
* All python applications are deployed as excutables
* opsi server
** Full rewrite of opsiconfd focusing on performance and scalability
** opsiconfd can now be run in a docker container
** Dependency to Redis Server >= 5 including RedisTimeSeries module
** Use of Grafana for performance data visualization
** python-opsi interpreter for custom scripts
** New default acl

[[opsi-4.2-releasenotes-important]]
== Important considerations - Please pay attention

opsi 4.2 is an independent release and thus has its own package repositories.
These must be added into the system you want to update before installation.

For an update from opsi 4.1 the packages need to be the latest version available on the stable repositories.
Other packages - such as MySQL server - should also be up-to-date.
Otherwise problems are to be expected during the update.

It is also recommended that 'opsi-winst', 'opsi-client-agent' or 'opsi-linux-client-agent' are updated to the latest version of opsi 4.1 before updating on the clients.

=== Python 3
opsi 4.2 is now based on Python 3.
Furthermore we now deploy all python based packages as binaries.
We do no longer provide `python-opsi` as an installable package.
Therefore it is important to check the following:

==== Opsi-packages containing server-side Python scripts
Please use opsi-package-manager to reinstall any opsi packages that contain Python scripts running on the server, such as:

* +opsi-client-agent+: `opsi-deploy-client-agent`
* +win*+: `create_driver_links.py`, `show_drivers.py`

The postinst script will automatically set the right interpreter.

Alternatively, the Python scripts can be corrected manually.
For this, the interpreter must be set to +opsi-python+ (use `#!/usr/bin/opsi-python` as shebang).

==== Own python script using python-opsi (import OPSI)
If you are using any python scripts which depend on python-opsi, you will need to do the following:
* Convert these scripts to Python 3 (you can use `2to3` to achieve that).
* Use `opsi-python`, which provides `python-opsi`, as interpreter (use `#!/usr/bin/opsi-python` as shebang).

=== opsiconfd config and logs
There are some changes in the 'opsiconfd' config and log files.

* All config options are documented in the opsiconfd help text ('opsiconfd --help').
* All options starting with '--' can be used in the config file (without '--').
* opsiconfd now uses its own log rotation. The log rotation can be configured by using the options 'max-log-size' and 'keep-rotated-logs'.
* The log file 'package.log' is now part of the 'opsiconfd.log'.
* The logs include a context by whitch you can filter. For example you can use 'grep' or start opsiconfd with the option '--log-filter LOG_FILTER':
** `opsiconfd --log-filter instance=package_install`
....
[6] [2020-09-07 14:41:17.864] [package_install] Running postinst script   (Depotserver.py:235)
[5] [2020-09-07 14:41:17.865] [package_install] Running package script 'postinst'   (Product.py:477)
...
....
** `opsiconfd --log-filter client_addr=10.100.7.5`
....
[6] [2020-09-07 14:25:16.966] [10.100.7.5     ] Filtering objects by acls   (AccessControl.py:475)
....

==== Backend extensions (/etc/opsi/backendManager/extend.d)
If you have modified or added any configuration files in `/etc/opsi/backendManager/extend.d` you will have to adapt these files to be compatible with Python 3.

[[opsi-4.2-releasenotes-installation]]
== Installation notice

We strongly suggest to create a backup of your backends with {opsi-backup} before updating:
[source,prompt]
----
opsi-backup create
----

The products contained in this release depend on each other in many cases.
Do not try to install just parts of this update.

We recommend to first update the server, and then update the opsi products.

In a multi-depot environment it is recommended to first update the configserver before updating the depots.

To make sure that permissions are applied correctly
we recommend to run `opsi-setup --set-rights` after the installation.
Please be aware that the execution of the latter can take several minutes.


[[opsi-4.2-releasenotes-installation-systempackages]]
=== Advice for updating the operating system packages

Please make sure that at the time of the update you are using the latest packages from opsi 4.1 from the stable branch.


[[opsi-4.2-releasenotes-installation-opsipackages]]
=== Notes for updating opsi-packages

opsi-packages are usually compatible with opsi 4.1 and opsi 4.2.

The official opsi 4.1 repositories at _download.uib.de_ contain packages that are compatible with opsi 4.2.
Please note that these packages not necessarily have to contain `4.2` in the version to be compatible.


[[opsi-4.2-releasenotes-installation-migration]]
=== Migration of an opsi 4.2 server

It is possible to migrate an existing opsi 4.1 installation to opsi 4.2 on supported operating systems.

If you manage your opsi servers through opsi than the migration can be done with the package `l-opsi-server-migrate`.

NOTE: Upgrading from opsi 4.0 to opsi 4.2 directly is not supported. In such a case you have to upgrade to opsi 4.1 first before you can upgrade to opsi 4.2.


[[opsi-4.2-releasenotes-installation-migration-repositories]]
==== Changing to the new repositories

First the opsi 4.2 package repositories have to be added to the systems package manager.

The following commands will add the repositories and add the new repository key if required.
These commands require 'root' rights.

[source,prompt]
----
sudo apt-get install -y apt-transport-https software-properties-common wget
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/testing/Debian_10/Release.key | sudo apt-key add -
sudo echo "deb https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.2:/testing/Debian_10/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
sudo echo "deb https://packages.grafana.com/oss/deb stable main" > /etc/apt/sources.list.d/grafana.list
----


[[opsi-4.2-releasenotes-installation-migration-migrate]]
==== Upgrading OS packages

After adding the new package repositories the system can be migrated.

IMPORTANT: Please note that the default acl `/etc/opsi/backendManager/acl.conf` has changed with opsi 4.2 for security reasons. Please use the new version of the configuration file unless you know exactly what you are doing.

IMPORTANT: For RPM-based distributions, existing configuration files are replaced by new ones during the migration. Please refer to the notes under the corresponding distributions.


Debian and Ubuntu are updated to opsi 4.2 with the following steps:
[source,prompt]
----
apt update
apt install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
apt dist-upgrade
----

RedHat and CentOS systems need these steps to upgrade to opsi 4.2:
[source,prompt]
----
yum makecache
yum install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
yum upgrade
----

To migrate SLES and OpenSUSE please perform the following:
[source,prompt]
----
zypper refresh
zypper install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
zypper dup --from home_uibmz_opsi_4.2_stable
----

On UCS you can update with the following command:
[source,prompt]
----
univention-upgrade
----

[[opsi-4.2-releasenotes-installation-migration-opsi-packages]]
==== Updating opsi packages

The last step is to update to the latest opsi packages.

[[opsi-4.2-releasenotes-installation-migration-opsi-packages-standard]]
===== Use of the standard configuration

If you did not alter the configuration of your repositories you can simply run the following command:

[source, prompt]
----
opsi-package-updater -v update
----

After these steps, your opsi 4.1 server is migrated to 4.2 and ready to use.


[[opsi-4.2-releasenotes-installation-migration-cleanup]]
==== Optional cleanup

After a migration it can be that some unrequired files still exist on the server.
The reason for this is that they either have been altered manually or that restoring a backup has brought these files back to the system.

The following files resp. folders can be removed:

* TBD


[[opsi-4.2-releasenotes-knownbugs]]
== Known Bugs / Known Problems

.KNOWN BUGS:

* opsi-admin: The interactive mode does not work with non-ASCII characters like special umlauts ö, ä, ü.

.KNOWN PROBLEMS:

* TBD


[[opsi-4.2-releasenotes-eol]]
== Discontinuation

This chapters lists discontinuations.


[[opsi-4.2-releasenotes-eol_server]]
=== Discontinued: Distributions for opsi-server

These distributions will not be supported anymore for various reasons.

* CentOS 7.x
* Debian 8.x
* Debian 9.x
* RedHat Enterprise Linux 7.x
* Suse Linux Enterprise Server 12

Also see separate chapter: <<opsi-4.2-releasenotes-supportmatrix>>.


[[opsi-4.2-releasenotes-supportmatrix]]
== opsi Support Matrix

An overview of the supported platforms for opsi 4.2 servers.

include::supportmatrix-server.asciidoc[]

If you are using an OS version which is not contained in the section above,
we recommend updating the OS before installing opsi v4.2.


[[opsi-releasenotes-4.2-changes-changed-defaults]]
== Changed Defaults

With opsi 4.2 some default settings have been changed to reflect experiences from opsi operations.

This is important if in an already existing environment new opsi servers are to be installed because this may lead to a change in expected behavior.

* For opsiconfd the setting of `update ip` is `yes` by default.
* In the file 'dispatch.conf' the usage of the mysql backend for keeping the inventory is the new default.
* The default loglevel for `opsi-admin` is now WARNING so that possible problems are easier to spot.


[[opsi-releasenotes-4.2-changes-python]]
== Switch to Python 3 and PyInstaller

This version is now based on Python 3.
All opsi Python applications (opsiconfd, opsipxeconfd, opsiclientd, opsi-utils, ...) are now distributed as binaries build with PyInstaller.
Please use the `opsi-python` interpreter for your own scripts which need access to the python-opsi library.

[[opsi-releasenotes-4.2-changes-mysql-config]]
== MySQL backend: Limiting connection lifetime

In order for a better user experience and less "mysql server has gone away" the default configuration for the MySQL backend is that `connectionPoolRecycling` has been set to _28800_ as default in the configuration file.
This limits the lifetime of connections in the connection pool used to connect to the MySQL (or MariaDB) server.


[[opsi-4.2-releasenotes-linux]]
== Linux Support

=== Support Matrix

include::supportmatrix-linclient.asciidoc[]

[[opsi-4.2-releasenotes-netboot-windows]]
== opsi Support Matrix Windows Clients

In the following graphic you will find on which Windows platforms opsi can be run as client.

include::supportmatrix-winclient.asciidoc[]


[[opsi-4.2-releasenotes-api-changes]]
== API changes

The API has received changes in opsi 4.2.

This affects the API of the webservice, `opsi-admin`, calls made through
`opsiServiceCall` in opsicript among others.


[[opsi-4.2-releasenotes-changed-api-methods]]
=== Changed API methods

 * `getClients_listOfHashes`: Method has been marked as deprecated during opsi 4.1. If called without parameters will return result from `getClients` in other cases an error will be returned.
 * `getClientIds_list`: Method has been marked as deprecated during opsi 4.1. If called without parameters will return result of `getClientIDs`. If called with parameter `depotIds` then the result of `getClientsOnDepot` will be returned. If called with parameters `productId` and optionally `installationStatus` the result of `getClientsWithProducts` will be returned.


[[opsi-4.2-releasenotes-deprecated-api-methods]]
=== Deprecation of API methods

The following methods are considered deprecated.
This means they will be removed with the next major or minor release.

 * `getClients_listOfHashes`
 * `getClientIds_list`


[[opsi-4.2-releasenotes-removed-api-methods]]
=== Removal of API methods

The following API methods have been removed:

* `backend_searchIdents`

These methods aren't available anymore.


[[opsi-4.2-releasenotes-misc]]
== Miscellaneous

* opsiwebservice does not support decompressing deflate-encoded data anymore.


[[opsi-4.2-releasenotes-packages]]
== List of packages

.Server packages:
* opsi4ucs 4.2...
* opsiconfd 4.2...
* opsipxeconfd 4.2...
* opsi-server 4.2...
* opsi-utils 4.2...
* opsi-linux-bootimage 

NOTE: The updated opsi packages are also made available for opsi 4.1 with this release. The exception for this are `l-opsi-server` and `l-opsi-server-migrate`.

// Changelogs
include::./opsi-v4.2-changelogs.asciidoc[]
