////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      30.03.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons: font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-linclient-introduction]]
= Linux Cients

This guide focuses on managing Linux clients in opsi environments, covering several key aspects:

* Automatic OS Installation
* Adding and integrating Linux computers into opsi (installation of the xref:clients:linux-client/linux-client-agent.adoc[Client Agent])
* Deploying standard software on the opsi server
* Deploying standard software on Linux clients
* Creating opsi packages and packaging your own software
* Notes on Linux clients
    ** Special commands for Linux
    ** Directories you may use

NOTE: To manage Linux clients, it’s essential to have an xref:server:overview.adoc[opsi Server] already installed and operational. 

[[opsi-linclient-convention]]
include::ROOT:partial$conventions.adoc[]
