////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      30.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-manual-lin-client-agent]]
= Client-Agent (Linux)

include::common:partial$opsi-client-agent.adoc[]

[[opsi-manual-client-agent-linux-directories]]
== Verzeichnisse des opsi-linux-client-agent

Die Bestandteile des opsi-client-agents liegen unter `/usr/lib`. Symlinks zu den Programmen *opsiclientd*, *opsi-notifier* und *opsi-script* werden unter `/usr/bin` abgelegt, wo sie im Standard-PATH enthalten sind. In `/etc/opsi-client-agent/` liegt die Konfigurationsdatei opsiclientd.conf, welche nur als user `root` zu lesen ist. Außerdem liegen hier weitere Dateien, die für den Betrieb des opsi-linux-client-agent notwendig sind.

Logdateien finden Sie unter `/var/log/`. `/var/log/opsi-client-agent` enthält die Logdateien des *opsiclientd* und *opsi-notifier*.
Die Logdateien des *opsi-script* sind in `/var/log/opsi-script`.
