////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      30.03.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



[[opsi-manual-lin-client-agent]]
= Client-Agent (Linux)

opsi enables the seamless and automatic distribution of software to client computers by facilitating installations and updates directly from the server. This process requires no user interaction, as it operates in the background, going unnoticed by users. This also ensures that insecure users cannot simply cancel installations.

For all automated processes, opsi relies on a specialized agent installed on client computers: it plays a crucial role in ensuring that installations and updates are executed efficiently and autonomously, without the need for any user intervention.

include::common:partial$opsi-client-agent.adoc[]

[[opsi-manual-client-agent-linux-directories]]
== Important directories

In a Linux environment, the components of the client agent are primarily located under `/usr/lib`. Symbolic links to the programs `opsiclientd`, `opsi-notifier`, and `opsi-script` are located under `/usr/bin`, ensuring their inclusion in the standard `PATH`. The configuration file `opsiclientd.conf` is located in `/etc/opsi-client-agent/` and can only be read and written by the user `root`. This directory also contains files that are necessary for the operation of the Linux client agent.

Logfiles can be found in the directory `/var/log/`. The logs for `opsiclientd` and `opsi-notifier` are located in `/var/log/opsi-client-agent`. The `opsi-script` logs are stored in `/var/log/opsi-script`.
