////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      30.03.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



[[opsi-linclient-requirements]]
= Prerequisites

In this chapter, you'll find the necessary details for managing Linux clients with opsi. First, there's a table that outlines the Linux versions supported by opsi 4.3, alongside the corresponding netboot products. Following this, another table presents the netboot products, categorized by installer type in opsi 4.3.

NOTE: The Linux client agent is a xref:opsi-modules:linux.adoc[paid extension]. This means that you need an activation file to unlock it. You will receive this file after you have purchased the extension. For evaluation purposes, we're happy to provide you with a temporary license free of charge. Please contact us via mailto:info@uib.de[email].

[[opsi-linclient-supportmatrix-clients-linux]]
== Supported Linux Distributions

include::{version}@opsi-docs-en:common:partial$supportmatrix-linclient-core.adoc[]
