////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype: book
:linclientmanual: opsi-linux-client-manual

// Include common opsi terms
include::common:partial$opsi_terms.adoc[]


[[firststeps-software-deployment-product-tests]]
= Rollout of existing products to Linux.

For the deployment of software to clients, the _opsi-client-agent_ must be installed on them.
This can be rolled out on xref:linux-client/adding-clients.adoc#firststeps-software-deployment-client-integration,existing-machines[].


Subsequently, the <<firststeps-software-deployment-product-tests-configed,opsi-configed>> management interface is used to deploy software to clients.


The following products are provided by opsi for Linux as standard:

* `opsi-linux-client-agent`
* `swaudit`
* `hwaudit`
* `l-system-update`
* `opsi-configed`
* `opsi-logviewer`
* `opsi-auto-update`
* `opsi-linux-client-kiosk`
* `opsi-setup-detector`
* ``


include::common:partial$firststeps-swdp-product-tests-configed.adoc[leveloffset=-1]

include::common:partial$firststeps-swdp-product-tests-inventory.adoc[leveloffset=-1]
