////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      04.04.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-linclient-softwintegration]]
= Integrating custom Software

Software installation in opsi is performed by the  xref:clients:linux-client/linux-client-agent.adoc[Client Agent] or rather the setup program xref:opsi-script-manual:opsi-script-manual.adoc[*opsi-script*].  When packaging your software, you have to create an `opsi-script` script for each product. This script, alongside the necessary installation files and metadata, forms an opsi product which is deployed on the opsi server (see the chapter xref:clients:linux-client/minimal-products.adoc[Adding Products (opsi Server)]).

[[opsi-linclient-softwintegration-tutorial]]
== Tutorial: Creating an *opsi-script* Script

include::common:partial$softwintegration-tutorial-introduction.adoc[]

[[opsi-linclient-softwintegration-tutorial-general]]
=== Methods of non-interactive software installation on Linux

Linux (unlike Microsoft) standardized its software installation methods very early on. The problem over here is that theses standards differ between the distributions. +
Here are the core variants to install software on Linux:

* Install a package from a repository
* Install a package from a file (*.rpm, *.deb)
* Install a package with a third party installer
* Install a package from the source code (make install)

In the first two cases a unattended installation is no problem.

Sometime you will get linux software in packed formats like *.zip, or *.tgz.

All variants mentioned so far can be installed directly by opsi-script, except *.tgz which must be unpacked before.


include::common:partial$softwintegration-tutorial-script-structure-opsi-script-basics.adoc[leveloffset=-1]


[[opsi-linclient-softwintegration-tutorial-Linux-special-commands]]
==== Special commands for Linux

* GetOS   // returns: Linux or Windows_NT or MacOS [W/L/M]

* getLinuxDistroType // returns: debian or redhat or suse [L] +
https://download.uib.de/opsi_stable/doc/html/en/opsi-script-manual/opsi-script-manual.html#getLinuxDistroType

* getLinuxVersionMap [L] +
https://download.uib.de/opsi_stable/doc/html/en/opsi-script-manual/opsi-script-manual.html#getLinuxVersionMap

Here you will find the collection of all linux specific opsi-script commands: +
https://download.uib.de/opsi_stable/doc/html/opsi-script-manual/opsi-script-manual.html#opsi-script-rc-linux-specific

In the following chapters special opsi Linux commands to install software are presented, which come from the opsi-script library `uib_lin_install`. This documentation was automatically generated directly from the source code.

Before we step into the documentation, some Remarks to the different approaches of the methods:

* Distribution independent methods:

** `cleanupPackageSystem`

** `installupdates`

* Installing one or more distribution specific packages from a repository: +
If you want to install only one package, you should use in the following methods instead of `$packagelist$` the following statement: `createStringList(<package name>)` +
The given package names have to match to the used distribution an version.

** debinstall($packagelist$ : stringlist) : string //since 4.12.4 [L]

** redinstall($packagelist$ : stringlist) : string //since 4.12.4 [L]

** suseinstall($packagelist$ : stringlist) : string //since 4.12.4 [L]

** ucsinstall($packagelist$ : stringlist) : string //since 4.12.4 [L]

* Install or remove one or more distribution specific packages from a repository. The given package names have to match to the used distribution an version. The distribution will be detected.

** genericLinInstall($packagelist$ : stringlist) : string

** linuxRemoveOnePackage($packagename$ : string) : string

** linuxInstallOneFile($packagefile$ : string) : string

* Install or check or remove one package for different distributions from a repository. The given package names have to match to the distribution specific names of the package.. The distribution will be detected.

** linuxInstallOneOf($packagelist$ : stringlist) : string

** isOneInstalled($packagelist$ : stringlist) : string

** linuxRemoveOneOf($packagelist$ : stringlist) : string

// http://www.methods.co.nz/asciidoc/userguide.html#X90


// Include os-lib_uib_Linuxinstalllib.asciidoc
include::opsi-docs-en:common:partial$os-lib-uib-lin-install.adoc[leveloffset=4]


[[opsi-linclient-softwintegration-tutorial-template]]
=== Example: Linux-Template _l-opsi-template_

You can create this template with the _opsi-setup-detector_.

// include docu: actual template for Linux
include::opsi-docs-en:common:partial$firststeps-opsi-template-lin.adoc[]


 

[[opsi-client-softwintegration-create-opsi-package]]
== Create an opsi product package

////
[[opsi-setup-detector-installation]]
=== Installation of the opsi-setup-detector, opsi PackageBuilder and opsi-logviewer
////

// include docu: opsi-setup-detector installation
include::common:partial$setup-detector-installation.adoc[]


// include docu: opsi-logviewer installation
include::common:partial$opsi-logviewer-installation.adoc[]


[[opsi-linclient-softwintegration-tutorial-create-with-opsi-setup-detector]]
=== The opsi-setup-detector program to create a Linux script.

// include docu: opsi-setup-detector
include::common:partial$setup-detector-use-start.adoc[]

// include docu: Linux specific tasks in opsi-setup-detector
include::common:partial$osd-tasks-linux.adoc[]

The following screenshots display the use of Windows installer files,
but the handling of linux installer files like *.deb, *.rpm is similar.

// include docu: how to use the opsi-setup-detector
include::common:partial$osd-task-use-single-analyze-and-create.adoc[]

More details about the _opsi-setup-detector_ can be found in the opsi-manual: +
https://docs.opsi.org/opsi-docs-en/4.2/manual/modules/setup-detector.html

// include docu: The modify and test cycle
include::common:partial$softwintegration-tutorial-modify-test-cycle.adoc[]

[[opsi-winclient-softwintegration-tutorial-template-details]]
== Suggestions on How to Solve Problems with opsi-script Scripts

// include docu: OSD Checkboxes for additional code
include::common:partial$osd-checkboxes-subtasks.adoc[]
