////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      15.04.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-linclient-softwintegration]]
= Integrating custom Software

Software installation in opsi is performed by the  xref:clients:linux-client/linux-client-agent.adoc[Client Agent] or rather the setup program xref:opsi-script-manual:opsi-script-manual.adoc[*opsi-script*].  When packaging your software, you have to create an `opsi-script` script for each product. This script, alongside the necessary installation files and metadata, forms an opsi product which is deployed on the opsi server (see the chapter xref:clients:linux-client/minimal-products.adoc[Adding Products (opsi Server)]).

[[opsi-linclient-softwintegration-tutorial]]
== Tutorial: Creating an *opsi-script* Script

include::common:partial$softwintegration-tutorial-introduction.adoc[]

[[opsi-linclient-softwintegration-tutorial-general]]
=== Non-interactive software installation (Linux)

Linux systems offer more consistency in package formats and installation methods than Windows, but the variety of Linux distributions introduces its own complexities. Each distribution tends to use distinct package formats and installation commands. Here’s a quick overview of the main types you’re likely to encounter:

* Installing a package from a repository
* Installing a package from a file (`.rpm`, `.deb`)
* Installation with a third-party installer
* Installation from the source code (`.tgz` or `.zip` archive) with the three steps `configure`, `make`, `make install`.

NOTE: All the variants we’ve talked about so far can be directly installed by `opsi-script`, except for `.tgz` archives, which need to be unpacked beforehand.

include::common:partial$softwintegration-tutorial-script-structure-opsi-script-basics.adoc[]

[[opsi-linclient-softwintegration-tutorial-Linux-special-commands]]
== Special Commands for Linux

// cspell: ignore Distro, debian, redhat, suse, card

* `GetOS`: Returns the operating system, e.g. `Linux`, `Windows_NT` (Windows NT to Windows 11) or `macOS`.

* `getLinuxDistroType`: Returns the Linux distribution, e.g. `debian`, `redhat` or `suse`.

* `getLinuxVersionMap`: Queries the operating system information locally and writes the information to a string list.

TIP: For further information on the Linux-specific `opsi-script` commands, please read the chapter xref:opsi-script-manual:linux-macos.adoc[*opsi-script* on Linux or macOS].

=== Linux Commands for Installation

NOTE: The following sections present special Linux commands for installing software. They are taken from the `opsi-script` library `uib_lin_install`. This part of the documentation is automatically generated from the source code.

To give you a clearer picture, let’s start with a rundown of the different strategies employed by each method:

// cspell: ignore cleanup, installupdates, packagelist

* Distribution-independent methods:

** `cleanupPackageSystem`

** `installupdates`

* Installation of one or more packages from the online repositories of a specific distribution, ensure the package names in the list correspond to the distribution/version. To install a single package, use the following syntax instead of `$packagelist$`: `createStringList(<package name>)` +
// cspell: ignore since, debinstall, redinstall, suseinstall, ucsinstall, linux, packagename, packagefile

** `debinstall($packagelist$ : stringlist) : string` (available from version 4.12.4 [L])

** `redinstall($packagelist$ : stringlist) : string` (available from version 4.12.4 [L])

** `suseinstall($packagelist$ : stringlist) : string` (available from version 4.12.4 [L])

** `ucsinstall($packagelist$ : stringlist) : string` (available from version 4.12.4 [L])

* Installation/uninstallation of one or more packages for a specific distribution/version; ensure the package names in the list correspond to the distribution/version. The appropriate command is automatically selected based on the distribution: +

** `genericLinInstall($packagelist$ : stringlist) : string`

** `linuxRemoveOnePackage($packagename$ : string) : string`

** `linuxInstallOneFile($packagefile$ : string) : string`

// cspell: ignore Installed, RemoveOnePackage, InstallOneOf, RemoveOneOf

* Installation, verification, or uninstallation of a package from online repositories, which may have different names across versions or distributions. (It is assumed that the package names in the list refer to the same software, but are specific to various distributions). The appropriate command is automatically determined based on the distribution: +

** `linuxInstallOneOf($packagelist$ : stringlist) : string`

** `isOneInstalled($packagelist$ : stringlist) : string`

** `linuxRemoveOneOf($packagelist$ : stringlist) : string`

// http://www.methods.co.nz/asciidoc/userguide.html#X90

:leveloffset: +2

include::{version}@opsi-docs-en:common:partial$os-lib-uib-lin-install.adoc[]

:leveloffset: -2

[[opsi-linclient-softwintegration-tutorial-template]]
== Example: Linux Template *l-opsi-template*

You can create this template using the `opsi-setup-detector` (see section <<opsi-linclient-softwintegration-tutorial-create-with-opsi-setup-detector>>).

// include docu: actual template for Linux
include::opsi-docs-en:common:partial$firststeps-opsi-template-lin.adoc[]

[[opsi-client-softwintegration-create-opsi-package]]
== Creating opsi Products

The following sections outline the steps for packaging software, specifically for creating opsi products. The fundamental process involves:

1. Creating the basic framework of a package using the `opsi-setup-detector` (refer to section <<opsi-linclient-softwintegration-tutorial-create-with-opsi-setup-detector>>).
2. Testing the `opsi-script` script (see the section <<opsi-softwintegration-tutorial-create-and-test-script>>).
3. Using the opsi PackageBuilder (oPB) to transform the initial form into a complete opsi package, which is then stored on the opsi server.

include::common:partial$setup-detector-installation.adoc[]

include::common:partial$opsi-logviewer-installation.adoc[]

[[opsi-linclient-softwintegration-tutorial-create-with-opsi-setup-detector]]
== *opsi-setup-detector*: Creating a Script

The following sections explain in detail how to use the `opsi-setup-detector` to analyze a setup file and create an opsi product.

// include docu: opsi-setup-detector
include::common:partial$setup-detector-use-start.adoc[]

// include docu: Linux specific tasks in opsi-setup-detector
include::common:partial$osd-tasks-linux.adoc[]

The following screenshots display the use of Windows installer files,
but the handling of linux installer files like *.deb, *.rpm is similar.

// include docu: how to use the opsi-setup-detector
include::common:partial$osd-task-use-single-analyze-and-create.adoc[]

More details about the _opsi-setup-detector_ can be found in the opsi-manual: +
https://docs.opsi.org/opsi-docs-en/4.2/manual/modules/setup-detector.html

// include docu: The modify and test cycle
include::common:partial$softwintegration-tutorial-modify-test-cycle.adoc[]

[[opsi-winclient-softwintegration-tutorial-template-details]]
== Suggestions on How to Solve Problems with opsi-script Scripts

// include docu: OSD Checkboxes for additional code
include::common:partial$osd-checkboxes-subtasks.adoc[]
