////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      25.04.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



= Installation

The latest version of the program is available at https://opsipackages.43.opsi.org/, provided as an opsi package for local installation on Windows, Linux, and macOS. This option is convenient if the client agent is already installed on your computer, allowing you to install the localboot product `opsi-configed`.

Alternatively, a portable application for all three operating systems can be found at link:https://tools.43.opsi.org/{release}/[]. These versions run without installation. Download `opsi-configed-windows.exe` for Windows, `opsi-configed-linux.run` for Linux, or `opsi-configed-macos` for macOS, depending on your operating system.

TIP: You can also download the version tailored to your operating system via a web browser. Enter the address `\https://<opsidepotserver>:4447/`, switch to the _Links_ tab, and click on the download link.

[[opsi-manual-configed-preconditions]]
== Prerequisites

The management interface `opsi-configed` requires `opsiconfd` 4.1 or newer (see the section xref:server:components/opsiconfd.adoc[*opsiconfd* Service]).) For those opting to use the portable Java application instead of the opsi package, it's important to have a current Java runtime environment installed.

NOTE: If your're using a virtual machine, make sure the virtual screen's resolution is adequate. `opsi-configed` demands a minimum screen resolution of 1024{nbsp}x{nbsp}768 pixels. For enhanced graphics, screen resolution, or improved mouse and keyboard integration, consider installing VMware Tools or the VirtualBox guest extensions.
