////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      11.12.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-installation-docker]]
= opsi as Docker Container

Since 2022, a link:https://github.com/opsi-org/opsi-docker[Docker image,window=_blank] has been available, enabling you to establish either an opsi config server or an opsi depot server. This setup utilizes Docker Compose, an orchestration tool that lets you define, interconnect, and execute multiple containers on a Docker host. To use this, you need Docker Compose version 1.17.0 or later and Docker Engine 17.09.0 or newer.

NOTE: Please note that exclusively WebDAV is used as the protocol for communication with the opsi depot in this setup; there is no Samba support in this variant.

== Docker Installation

Install Docker or Docker Desktop on Linux, Windows, or macOS:

* link:https://docs.docker.com/desktop/install/windows-install/[Install Docker Desktop on Windows,window=_blank]
* link:https://docs.docker.com/desktop/install/mac-install/[Install Docker Desktop on macOS,window=_blank]
* link:https://docs.docker.com/desktop/install/linux-install/[Install Docker Desktop on Linux,window=_blank]

TIP: On Linux, you can also work directly with the Docker Engine. Simply install the relevant packages for your Linux distribution.

To check that the installation was successful, run the following command in the terminal:

[source,console]
----
docker run --rm hello-world
----

NOTE: By default, the `docker` command requires root privileges, meaning that working with our helper scripts also requires root privileges. You can either prefix the commands shown in this chapter with `sudo`, or you can add a user account to the `docker` group. For more information, see the Docker manual, chapter link:https://docs.docker.com/engine/install/linux-postinstall/[Linux post-installation steps for Docker Engine].

You should expect to see an output similar to this:

[source,console]
----
Hello from Docker!
This message shows that your installation appears to be working correctly.
[...]
----
