[[server-installation-docker]]
= opsi as Docker container

Since 2022, there is a link:https://github.com/opsi-org/opsi-docker[Docker image] that you can use to set up a configserver or a depot server. It relies on the Docker Compose orchestration tool, which allows you to define multiple containers, connect them together and run them on a Docker host. You need at least Docker Compose 1.17.0 and Docker Engine 17.09.0 or later.

NOTE: Note that only WebDAV is used as the protocol to communicate with the opsi depot; there is no Samba support in this variant. You also need a license for the MySQL extension, because the file backend is not supported (see chapter xref:opsi-modules:modules.adoc[opsi-extensions]).

Install Docker or Docker Desktop on Linux, Windows or macOS. You can quickly check that the installation was successful with the following command in the terminal:

[source,console]
----
docker run --rm hello-world
----

In response, you should see this output:

[source,console]
----
Hello from Docker!
This message shows that your installation appears to be working correctly.
[...]
----