////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      18.12.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-installation-docker-compose-depot]]
=== opsi Depot Server

Make sure to verify the network and volume settings. For a depot server, you do not require the two services `mysql` and `grafana`, so you can either comment them out or delete them. It's important to also remove `mysql` from the `depends_on` attribute in the `opsi-server` section if you choose to exclude these services.

To configure the server as a depot server, set the `OPSI_HOST_ROLE` variable to `depotserver`:

[source,toml]
----
OPSI_HOST_ROLE: depotserver
----

For setting up a depot server, you also need to configure two additional variables: `OPSI_SERVICE_ADDRESS` (the service URL of the opsi config server) and `OPSI_HOST_KEY` (the host key of the depot). Once these variables are set, start all services using `./opsi-server.sh start` (Linux, macOS) or `.\opsi-server.ps1 start` (Windows).

NOTE: You can locate the host key of the opsi depot server in the admin interface of the opsi config server, specifically on the _Depots_ tab. Additionally, if necessary, you can create a new opsi depot server from there.
