[[server-installation-docker-compose]]
== Docker Compose

The configuration file `docker-compose.yml` defines networks, volumes and these four services (section `services`):

* `mysql`: installs the MariaDB database server.
* `redis`: installs the in-memory database Redis with the RedisTimeSeries module
* `grafana`: installs an up-to-date Grafana
* `opsi-server`: installs the packages `opsiconfd`, `opsipxeconfd`, `opsi-tftpd-hpa` and `opsi-utils` in their latest versions.

At the beginning of the file, some X properties (so-called extension fields) are defined, e.g. `x-restart-policy`, `x-common-variables` etc. These YAML anchors are used to exchange settings between services.

NOTE: For security reasons, you should change all passwords in the `docker-compose.yml` file: `MYSQL_ROOT_PASSWORD`, `MYSQL_PASSWORD`, `REDIS_PASSWORD`, `GF_SECURITY_ADMIN_PASSWORD` and `OPSI_ADMIN_PASSWORD`.

A password for the user `root` is not set. You can set this via `OPSI_ROOT_PASSWORD`:

[source,toml]
----
OPSI_ROOT_PASSWORD: <password>
----

TIP: If you do not need TFTP network boot (and thus `opsipxeconfd` and `opsi-tftp-hpa`), you can set the variable `OPSI_TFTPBOOT` to `"false"`.

The next two sections explain how to customise the `docker-compose.yml` configuration file to set up a config server or a depot server.
