////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      03.05.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



[[server-installation-docker-compose]]
== Docker Compose

The `docker-compose.yml` configuration file defines networks, volumes and the following four services (section `services`):

* `mysql`: Sets up the database server MariaDB.
* `redis`: Installs the in-memory database Redis with the RedisTimeSeries module.
* `grafana`: Deploys a current version of Grafana.
* `opsi-server`: Installs the latest versions of the packages `opsiconfd`, `opsipxeconfd`, `opsi-tftpd-hpa`, and `opsi-utils`.

At the beginning of the file, several X properties (extension fields) like `x-restart-policy`, `x-common-variables`, etc., are defined. These YAML anchors are used to exchange settings between services.

You will also find several environment variables for the containers. You can edit these directly in the `docker-compose.yml` file or set the variables in the provided `opsi-server.env` file, which is read at startup (defined in the `docker-compose-env.yml` file). The `.env` file then keeps the configuration in one central location, and you do not need to search for the variables in the `docker-compose.yml`. You can then start the stack with this command:

[source,console]
----
docker compose -f docker-compose-env.yml up
----

NOTE: For enhanced security, it's crucial to change all passwords in the `docker-compose.yml` file: `MYSQL_ROOT_PASSWORD`, `MYSQL_PASSWORD`, `REDIS_PASSWORD`, `GF_SECURITY_ADMIN_PASSWORD`, and `OPSI_ADMIN_PASSWORD`.

A password for the `root` user is not set by default. You can assign it using `OPSI_ROOT_PASSWORD`:

[source,toml]
----
OPSI_ROOT_PASSWORD: <password>
----

TIP: If you do not need TFTP network boot (thus excluding `opsipxeconfd` and `opsi-tftp-hpa`), you can disable it by setting the `OPSI_TFTPBOOT` variable to `"false"`.

The next two sections will guide you on customizing the `docker-compose.yml` configuration file to configure a config server or a depot server.
