////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      11.12.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-installation-docker-quick]]
== Quick Start

A helper script is provided for straightforward setup and management of an opsi Docker environment.

NOTE: Docker experts can ignore the helper script and access all information directly in our GitHub repository at link:https://github.com/opsi-org/opsi-docker[opsi-docker,window=_blank].

=== Windows

On Windows systems, follow these steps:

1. Create an `opsi-server` folder.
2. Download the script from link:https://raw.githubusercontent.com/opsi-org/opsi-docker/main/opsi-server/opsi-server.ps1[opsi-server.ps1,window=_blank] and save it in the `opsi-server` folder.
3. Open PowerShell with administrator privileges.
4. Run the following command in the terminal window: `PowerShell.exe -ExecutionPolicy Bypass`
5. Navigate to the `opsi-server` folder using the command `cd`.
6. Execute the script by typing `.\opsi-server.ps1 start`.

=== Linux and macOS

On Linux and macOS, follow these steps:

To set up under Linux, follow these steps:

1. Create an `opsi-server` folder.
2. Download the script from link:https://raw.githubusercontent.com/opsi-org/opsi-docker/main/opsi-server/opsi-server.sh[opsi-server.sh,window=_blank] and place it in the `opsi-server` folder.
3. Open a terminal with `root` privileges.
4. Navigate to the `opsi-server` folder using `cd`.
5. Make the script executable: `chmod +x opsi-server.sh`
6. Execute the script with the command `./opsi-server.sh start`.

This process will automatically download the required Docker images and start the containers.

* Use `.\opsi-server.ps1 status` or `./opsi-server.sh status` to check the status of the containers.
* View the container logs with `.\opsi-server.ps1 logs` or `./opsi-server.sh logs`.
* Update the containers to the latest versions using `.\opsi-server.ps1 upgrade` or `./opsi-server.sh upgrade`.

IMPORTANT: There is now a file `docker-compose.yml` in the `opsi-server` folder. Open this file with a text editor and look for the environment variable `OPSI_ADMIN_PASSWORD`. You will need the specified password for logging into the opsi server as the `opsiadmin` user in subsequent steps.

NOTE: We strongly recommend changing this password for security reasons.

If you modify the `docker-compose.yml` file, restart the containers to apply the changes. Do this by entering `.\opsi-server.ps1 recreate` or `./opsi-server.sh recreate`.
