////
; Copyright (c) uib GmbH (uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      18.12.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



[[security-selinux]]
= SELinux

"Security-Enhanced Linux (SELinux) ist eine Sicherheitsarchitektur für Linux-Systeme, die Administrationsteams noch mehr Kontrolle darüber bietet, wer auf das System zugreifen darf."
-- RedHat, Was ist SELinux? https://www.redhat.com/de/topics/linux/what-is-selinux

== Redis-Server

Wenn SELinux aktiviert ist, wird der Start von Redis verhindert.
Um Redis ordnungsgemäß zu betreiben, muss eine Ausnahme für SELinux eingerichtet werden.
Zu diesem Zweck wird die Datei redis-server.te mit den erforderlichen Ausnahmen erstellt.

[source,console]
----
module redis-server 1.0;

require {
    type init_t;
    type redis_t;
    class process2 nnp_transition;
}

#============= init_t ==============
allow init_t redis_t:process2 nnp_transition;
----

Als nächstes wird mit den folgenden Befehlen eine Policy Module Datei und darauf ein Policy Package erzeugt:

[source,console]
----
checkmodule -M -m -o redis-server.mod redis-server.te
semodule_package -o redis-server.pp -m redis-server.mod
----

Anschließend kann das Policy Package mit `semodule -i redis-server.pp` aktiviert werden.

== opsi-linux-client-agent

Einige Distributionen nutzen auch auf client-Seite selinux.
Für diese muss vom opsi-linux-client-agent eine selinux-Konfiguration installiert werden, um den normalen Betrieb zu gewährleisten.
Entsprechend sucht der opsi-linux-client-agent bei der Installation nach dem Kommando `semodule` und installiert,
falls dieses vorhanden ist, diese selinux-Konfiguration für den opsiclientd.
