////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      11.01.2021
:doctype: book

include::common:partial$opsi_terms.adoc[]


[[opsi-manual-glossary]]
= Glossary

////
Asciidoc supports creating glossary entries if they are written in the
following format.

term::
  Indented description

////


Action request::
  Next scheduled action for a client. Typical action requests are 'setup', 'uninstall' and 'update'.


Backend::
  opsi supports different types of data storage, i.e. in a file or database.
  These are called backends.


Client ID::
  Unique identifier for a client through an 'fully qualified hostname' (FQDN).


Config server::
  Server which is reponsible for providing management and configuration data in an opsi environment.


Depot server::
  Server which provides program data and scripts through a Samba or webdav share for clients to install from.


DHCP (Dynamic Host Configuration Protocol)::
  A protocol allowing dynamic IP address assignment.


FQDN (Fully Qualified Hostname)::
  Complete name of a computer in a network. It consists of the IP name and domain, i.e. 'client001.int.company.de'.


FTP (File Transfer Protocol)::
  A standard network protocol used for the transfer of files between a client and a server on a network


GUI::
  Graphical User Interface.


Host ID::
  Unique ID of a host (includes servers and clients) by using the 'fully qualified domain name' (FQDN).


JSON::
  JSON is short for JavaScript Object Notation, which is a compact data exchange format. The data is easy to read for people and for machines.


Last seen::
  Time stamp of the last time a client connected to the opsi service.


LDAP (Lightweight Directory Access Protocol)::
  Lightweight Directory Access Protocol is an protocol that allows programs to look up information from a directory service.


Localboot product::
  An opsi package which is installed on a running operating system.


MAC address (Media Access Control address)::
  An unique identifier attached to the network adapter, which is transferred with every data package.
  With this address the computer (respectively its network card) can be identified worldwide and can be mapped to an IP address.
  The MAC address is composed from 6 hexadecimal numbers separated by colon.


Netboot product::
  An opsi package which will be started when booting over the network.
  Usually used for installating operating systems on a computer.


opsi::
  open system integration


opsi-client-agent::
  The software component that runs on each opsi client, communicates with the opsi config server and executes requests.


opsi-server::
  A server providing services for an opsi environment.
  Usually 'config server' and 'depot server'.

opsiconfd::
  Server service which provides the opsi API and webdav shares.


Product properties::
  Additional parameters for an opsi product that can be set on a per-client basis and which are then evaluated during the installation.


Product ID::
  Unique name of an opsi-product.
  Consists of a-z, numbers and hyphen.
  Spaces or special characters (except hyphens) are not allowed.
  Example for a product Id: 'acroread'

product name::
  Full name of a product (allowing blanks).
  Example for a product name: 'Adobe Acrobat Reader'.


PXE (Preboot eXecution Environment)::
  Standard for runnig a software over the network on system startup.
  Commonly used with 'DHCP'.


SAMBA::
  Free software to provide data shares or authentication services to Microsoft clients from an Linux server using the 'SMB/CIFS' protocol.


SMB (Server Message Block)::
  Protocol by Microsoft to provide network shares and authentication.
  A dialect of SMB is 'CIFS' (Common Internet File System).


TFTP (Trivial File Transfer Protocol)::
  TFTP is a very simple UDP protocol for transferring files on a network.
  PXE usually uses TFTP for file transfer.