////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      25.02.2022
:Revision:  4.2

ifeval::["{mode}" == "antora"]
include::common:partial$opsi_terms.adoc[]
endif::[]

[[opsi-manual-introduction]]
= Introduction

[[opsi-manual-introduction-who-should-read]]
=== Who should read this manual?

This manual is aimed at everyone who is interested in automatic software distribution with 'opsi'. The focus of the documentation is the explanation of the technical background, in order to contribute to an understanding of the processes.

This manual should not only support the system administrator who works practically with opsi, but also give prospective users a concrete overview of opsi in advance.


[[opsi-manual-introduction-conventions]]
=== Conventions in text and graphics

Names which are shown in '<angle brackets>' have to be replaced by a real name.

Example: The file share on which the opsi software packages are located is called <opsi-depot-share> and is located on a real server on `/var/lib/opsi/depot`.

The software package: <opsi-depot-share>/ooffice is actually under `/var/lib/opsi/depot/ooffice`.

Examples from program code or configuration files use a Courier font and are highlighted in color.
[source,shell]
----
depoturl=smb://smbhost/sharename/path
----
