////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      11.01.2021
:doctype: book

include::common:partial$opsi_terms.adoc[]

[[opsi-manual-opsiwebgui]]
= {opsi-webgui}

The {opsi-webgui} is a web-based graphical user interface for managing the opsi system. 
It simplifies the deployment and management tasks, without installing an application on your device. 
With {opsi-webgui}, you can configure the opsi-servers, set up new opsi-clients, deploy products, inspect logs from any device with a web browser and more.

include::webgui/technology.adoc[leveloffset=+1]

include::webgui/installation.adoc[leveloffset=+1]

// include::webgui/userguide.adoc[leveloffset=+1]
// include::webgui/userguide-generalui.adoc[leveloffset=+2]
// include::webgui/userguide-server.adoc[leveloffset=+2]
// include::webgui/userguide-clients.adoc[leveloffset=+2]
// include::webgui/userguide-products.adoc[leveloffset=+2]
// include::webgui/userguide-settings.adoc[leveloffset=+2]
// include::webgui/userguide-tips.adoc[leveloffset=+2]
// include::webgui/userguide-troubleshooting.adoc[leveloffset=+2]
