////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      15.12.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



[[quick-start-osinstall-create-client]]
= Adding Clients


This chapter explains how to integrate Windows clients into the opsi environment. For detailed instructions, please refer to the chapter xref:clients:opsi-clients.adoc[opsi Clients].

TIP: opsi also supports the management of Linux and macOS clients. For more information, see the chapters xref:clients:linux-client/linux-client-manual.adoc[Linux Clients] and xref:clients:macos-client/mac-client-manual.adoc[macOS Clients].

[[firststeps-software-deployment-client-integration]]
== Integrating existing Clients

To add existing clients with an already installed operating system to opsi, you need to install the client agent on each respective computer. Once installed, the client will also appear in the `opsi-configed` management interface's client list, even if you haven't manually added it there:

xref:clients:windows-client/windows-client-agent.adoc[Instructions for Windows]
xref:clients:linux-client/linux-client-agent.adoc[Instructions for Linux]
xref:clients:macos-client/mac-client-agent.adoc[Instructions for macOS]

:leveloffset: +1

[[opsi-create-client-integrating-clients]]
include::common:partial$firststeps-client-installer.adoc[]

:leveloffset: -1

You should now see the new client(s) in `opsi-configed`. The next step involves deploying the `hwaudit` product to the clients.
