////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      21.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[firststeps-osinstall-create-client]]
= Add clients

This chapter explains how to integrate Windows clients into the opsi environment. For detailed instructions, see chapter xref:clients:opsi-clients.adoc[opsi-Clients].

TIP: With opsi you can also manage Linux and macOS clients. Details can be found in the two chapters xref:clients:linux-client/linux-client-manual.adoc[Linux-Clients] and xref:clients:macos-client/mac-client-manual.adoc[macOS-Client].

[[firststeps-software-deployment-client-integration]]
== Integrate existing clients

To include existing clients with already installed operating system in opsi, install the client agent on the respective computer. Afterwards the client will also appear in the client list of the management interface, if you had not already added it there.

NOTE: After the client agent is installed, you can roll out opsi products on the client (see chapter xref:clients:windows-client/rollout-products.adoc[Rollout of existing products]).

[[opsi-create-client-integrating-clients]]
include::common:partial$firststeps-client-installer.adoc[leveloffset+1]

Now you should see the added clients in the opsi-configed. In the xref:rollout/rollout.adoc[next step] we run the hwaudit product on the clients.