////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype: book
:macosclientmanual: opsi-macos-client-manual

include::common:partial$opsi_terms.adoc[]


[[opsi-macclient-requirements]]
= Voraussetzungen für MacOS Clients

Nachfolgend werden die Voraussetzungen für das Management von MacOS Clients unter opsi beschrieben.

Der opsi-mac-client-agent ist eine
http://uib.de/de/opsi-erweiterungen/erweiterungen/[kofinanzierte opsi Erweiterung]. +
Das bedeutet, dass Sie zum Einsatz eine Freischaltdatei benötigen. Diese Freischaltung erhalten Sie wenn Sie die Erweiterung kaufen. Zu Evaluierungszwecken stellen wir Ihnen auch eine zeitlich befristete Freischaltung kostenlos zur Verfügung ( -> mail an info@uib.de). +
Weitere Details hierzu finden Sie in +
https://download.uib.de/opsi_stable/doc/html/opsi-manual/opsi-manual.html#opsi-manual-modules

Technische Voraussetzungen ist ein opsi-server mit opsi 4.1.

Als Mac-Clients werden unterstützt:

* MacOS Versionen von 10.13 bis 11.0 +
(`High Sierra` bis `Big Sur`) in der intel x64 Architektur

* Bei Verwendung der arm64 Architektur (Apple Silicium, M1) ist derzeit die Installation des opsi-client-agent der 'Dynamic Binary Translators' namens `rosetta2` notwendig. Diesen können Sie Installieren mit: +
`softwareupdate --install-rosetta --agree-to-license`
Die erfolgreiche Installation können Sie Überprüfen mit: +
`pkgutil --pkgs | grep Rosetta` +
`com.apple.pkg.RosettaUpdateAuto`.

Die native Unterstützung der arm64 Architektur (Apple Silicium) ist in Planung. Hierzu sind die notwendigen Referenz Geräte bestellt. Aussagen wann die Bereitstellung für diese Plattform erfolgt können im Moment (Januar 2021) noch nicht getroffen werden.