////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      16.01.2024
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

= Important Notes

opsi 4.3, being a major release, has dedicated repositories. To upgrade, you need to add these new package sources to the respective configuration files on your systems and remove the repositories from the previous version. 

Ensure that all installed packages are updated to the latest opsi 4.2 version before proceeding with the upgrade to 4.3. Also, update other packages (such as the MySQL server), as outdated versions could hinder the upgrade process.

IMPORTANT: Prior to upgrading, make sure to update the `opsi-script`, `opsi-client-agent`, `opsi-linux-client-agent`, and `opsi-mac-client-agent` packages on all clients!

== opsi Linux Boot Image and DHCP Server

In the opsi Linux boot image for version 4.3, the bootloaders are now located in the path `<TFTP-ROOT>/opsi/opsi-linux-bootimage/loader`. *If you are using Netboot/PXE, you may need to manually adjust the DHCP server configuration, specifically option 67 (BootFile Name), to reflect these changes.*

* Legacy BIOS: `opsi/opsi-linux-bootimage/loader/opsi-netboot.bios`
* UEFI-BIOS: `opsi/opsi-linux-bootimage/loader/shimx64.efi.signed`


== Update operating system packages

Make sure that you use the latest packages of opsi 4.2 from the stable area at the time of the upgrade!

== update opsi packages

opsi packages are generally compatible with opsi 4.2 and opsi 4.3.

The official link:https://opsipackages.43.opsi.org[4.3 repositories] contain packages compatible with opsi 4.3.

NOTE: Please note that the packages offered there do not necessarily have to have the version number `4.3` in their name to be executable under opsi 4.3!


== Backend extensions

The extension methods previously stored in `/etc/opsi/backendManager/extend.d` are now permanently implemented in `opsiconfd`.
Therefore, the `/etc/opsi/backendManager/extend.d` directory is empty by default.
The files that were previously shipped by default will be moved during the upgrade.

However, you can still use the extend mechanism.
You can implement your own methods in custom .conf files below `/etc/opsi/backendManager/extend.d`.

== Workbench, depot and repository

opsi 4.3 now uses fixed directories for workbench, depot and repository below `/var/lib/opsi`.
Dynamic configurations via `depotLocalUrl`, `repositoryLocalUrl` and `workbenchLocalUrl` at the depots are ignored.

If the workbench, depot, and repository directories are located elsewhere, then move them to `/var/lib/opsi`.
Instead of moving the directories, you can also create a symlink.

== Sorting algorithm

There is only one (new) sorting algorithm for product actions; a distinction of `algorithm1/algorithm2` is omitted. The new algorithm produces largely the same results as the predecessor `algorithm1`.

== opsi packages

The new opsi packages are now located at https://opsipackages.43.opsi.org/.

== opsi-tools

The tools `opsi-configed`, `opsi-setup-detector-setup`, the WebGUI and others are now available at https://tools.43.opsi.org/.
