////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      02.10.2023
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

= opsi upgrade

This chapter describes how to upgrade opsi -- specifically, how to upgrade from opsi 4.2 to opsi 4.3.

NOTE: On the server side, Linux distribution support is almost the same as under opsi 4.2.

A detailed list of supported Linux distributions for the opsi server can be found in our xref:supportmatrix:supportmatrix.adoc[opsi-support-matrix].

The opsi components depend on each other in many places.
Therefore you should always update the complete system to the new version.

We recommend to upgrade the server first and then the opsi packages (products).
In a multi-depot environment the upgrade must be done first on the configserver and then on the depots.

opsi 4.3 uses only, the now free, MySQL backend.
The migration from a file backend is done automatically when upgrading the server packages.

== Preparations

Before you start upgrading your opsi environment, you should definitely make a backup:

[source,console]
----
opsi-backup create
----

TIP: Starting with opsi 4.3, the `opsiconfd` takes care of backup and restore (`opsiconfd backup` / `opsiconfd restore`). See also the chapter xref:server:components/backup.adoc[Backup of the opsi server].