////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      17.01.2024
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full


include::common:partial$opsi_terms.adoc[]

= Upgrade from opsi 4.2 to 4.3

On xref:supportmatrix:supportmatrix.adoc[supported operating systems], you can upgrade an existing opsi 4.2 installation to opsi 4.3.

NOTE: Directly upgrading from opsi 4.1 to opsi 4.3 is not supported. You must first upgrade to opsi 4.2 before proceeding to opsi 4.3.

TIP: If you are managing your opsi servers using opsi itself, you can do the upgrade using the localboot product `l-opsi-server-migrate`.

== Creating a Backup

Be sure to create a backup before upgrading:

[source,console]
----
opsi-backup create
----

TIP: From opsi 4.3 onwards, the `opsiconfd` service is responsible for backup and restore operations (`opsiconfd backup`/`opsiconfd restore`). For more detailed information, refer to the chapter xref:server:components/backup.adoc[Backup of the opsi Server].

== Adding new Repositories

First, add the opsi 4.3 repositories to your operating system's configuration files and include the GPG key of the repository. Remember, you'll need root privileges for this process.

For Debian, Ubuntu, or Univention Corporate Server (UCS) systems, ensure the directory `/usr/local/share/keyrings` is present:

[source,console]
----
sudo mkdir -p /usr/local/share/keyrings
----

Here are the commands for the supported operating systems:

*Debian 12 _Bookworm_:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_12
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" | sudo tee /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----

*Debian 11 _Bullseye_:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_11
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" | sudo tee /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----

*Debian 10 _Buster_:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_10
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" | sudo tee /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----


*Ubuntu 22.04 LTS, _Jammy Jellyfish_:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/xUbuntu_22.04
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" | sudo tee /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----

*Ubuntu 20.04 LTS _Focal Fossa_:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/xUbuntu_20.04
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" | sudo tee /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----

*RHEL 9:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/RHEL_9/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*RHEL 8:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/RHEL_8/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*AlmaLinux 9:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/AlmaLinux_9/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*AlmaLinux 8:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/AlmaLinux_8/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*Rocky Linux 9:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/RockyLinux_9/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*Rocky Linux 8:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/RockyLinux_8/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*SLES 15 SP 1:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3{release}/SLE_15_SP1/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*SLES 15 SP 2:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/SLE_15_SP1/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*SLES 15 SP 3:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/SLE_15_SP3/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*SLES 15 SP 4:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/SLE_15_SP3/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*openSUSE Leap 15.4:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/openSUSE_Leap_15.4/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*Univention UCS 5.0:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Univention_5.0
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" | sudo tee /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----

== Upgrading the OS Packages

Once you've added the new package sources, you're ready to begin the upgrade process. Remember, you will need root privileges for this as well.

IMPORTANT: For RPM-based distributions, be aware that existing configuration files will be replaced with new ones during the upgrade. Make sure to consult the specific instructions for your distribution to handle this properly.

=== Debian and Ubuntu

[source,console]
----
apt update
apt dist-upgrade
----


=== RHEL, AlmaLinux, and Rocky Linux

[source,console]
----
yum makecache
yum upgrade
----


=== SLES and openSUSE Leap

*Single-Server-Setup:*
[source,console]
----
zypper refresh
zypper update
----


=== Univention Corporate Server (UCS)


[source,console]
----
eval "$(ucr shell version/version)"
univention-upgrade  --updateto=$version_version-99
----

CAUTION: During the process, the system will prompt you to confirm whether you want to update to the next UCS (Univention Corporate Server) version. Please proceed with this update only if you intend to upgrade to the newer version.

== Adjusting the Configuration

These two adjustments are optional but recommended:

* Set `opsiclientd.config_service.permanent_connection = true` to enable client and server communication via the opsi message bus.

* Set `opsiclientd.global.verify_server_cert = true` to ensure that the opsi clients verify the SSL server
certificates of the servers.

[[opsi-4.3-releasenotes-installation-migration-opsi-packages-standard]]
== Updating the opsi Packages

The final step involves updating to the latest opsi packages.

If the default settings in `/etc/opsi/package-updater.repos.d/` have not been altered, you can upgrade the opsi packages using the following command:

[source,console]
----
opsi-package-updater -v update
----

Your opsi 4.2 server has now been successfully updated to version 4.3 and is ready for use.
