////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      02.10.2023
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full


include::common:partial$opsi_terms.adoc[]

= Upgrade from opsi 4.2 to 4.3

On xref:supportmatrix:supportmatrix.adoc[supported operating systems] it is possible to upgrade an existing opsi 4.2 installation to opsi 4.3.

NOTE: A change from opsi 4.1 directly to opsi 4.3 is not supported. You have to upgrade to opsi 4.2 first before you can upgrade to opsi 4.3.

TIP: If you manage your opsi servers with opsi itself, you can do the upgrade with the localboot product `l-opsi-server-migrate`.

== Create backup

Be sure to create a backup before upgrading:

[source,console]
----
opsi-backup create
----

TIP: Starting with opsi 4.3 the `opsiconfd` takes care of backup and restore (`opsiconfd backup` / `opsiconfd restore`). See also the chapter xref:server:components/backup.adoc[Backup of the opsi server].

== Enter new repositories

First enter the opsi-4.3 repositories into the configuration files of your operating system. Also add the GPG key of the repository. You will need root privileges to do this.

Make sure that the directory `/usr/local/share/keyrings` exists under Debian, Ubuntu or UCS:

[source,console]
----
sudo mkdir -p /usr/local/share/keyrings
----

This is what the commands look like for the supported operating systems:

*Debian 12 _Bookworm_:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_12
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" > /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----

*Debian 11 _Bullseye_:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_11
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" > /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----

*Debian 10 _Buster_:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_10
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" > /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----


*Ubuntu 22.04 LTS, _Jammy Jellyfish_:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/xUbuntu_22.04
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" > /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----

*Ubuntu 20.04 LTS _Focal Fossa_:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/xUbuntu_20.04
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" > /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----

*RHEL 9:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/RHEL_9/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*RHEL 8:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/RHEL_8/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*AlmaLinux 9:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/AlmaLinux_9/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*AlmaLinux 8:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/AlmaLinux_8/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*Rocky Linux 9:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/RockyLinux_9/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*Rocky Linux 8:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/RockyLinux_8/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*SLES 15 SP 1:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3{release}/SLE_15_SP1/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*SLES 15 SP 2:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/SLE_15_SP1/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*SLES 15 SP 3:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/SLE_15_SP3/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*SLES 15 SP 4:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/SLE_15_SP3/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*openSUSE Leap 15.4:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/openSUSE_Leap_15.4/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*Univention UCS 5.0:*
[source,console]
[subs="attributes"]
----
REPO_URL=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Univention_5.0
REPO_KEY=/usr/local/share/keyrings/opsi.gpg
sudo echo "deb [signed-by=${REPO_KEY}] ${REPO_URL}/ /" > /etc/apt/sources.list.d/opsi.list
curl -fsSL ${REPO_URL}/Release.key | gpg --dearmor | sudo tee ${REPO_KEY} > /dev/null
----

== Upgrade operating system packages

After you have entered the new package sources, you can now start the upgrade. You will also need root privileges to do this.

IMPORTANT: For RPM-based distributions, existing configuration files will be replaced with new ones during the upgrade. Please refer to the instructions for the corresponding distributions.

=== Debian und Ubuntu

[source,console]
----
apt update
apt dist-upgrade
----


=== RHEL, AlmaLinux und Rocky Linux

[source,console]
----
yum makecache
yum upgrade
----


=== SLES und openSUSE Leap

*Single-Server-Setup:*
[source,console]
----
zypper refresh
zypper update
----


=== Univention Corporate Server (UCS)


[source,console]
----
eval "$(ucr shell version/version)"
univention-upgrade  --updateto=$version_version-99
----

WARNING: The system will ask you whether you want to update to the next UCS version. Only confirm here if you wish to do so.

== Adjust configuration

These two changes are optional but recommended:

* Set `opsiclientd.config_service.permanent_connection = true` to enable client and server communication over the opsi message bus.

* Set `opsiclientd.global.verify_server_cert = true` to make the opsi clients verify the SSL server certificates of the servers.

[[opsi-4.3-releasenotes-installation-migration-opsi-packages-standard]]
== update opsi-packages

The last step is to update to the latest opsi packages.

If you have not changed the default settings in `/etc/opsi/package-updater.repos.d/`, upgrade the opsi packages with this command:

[source,console]
----
opsi-package-updater -v update
----

Your opsi-4.2 server is now updated to version 4.3 and ready to use.
