////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      16.01.2024
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

= opsi Upgrade

This chapter provides guidance on upgrading opsi, focusing specifically on the transition from opsi 4.2 to opsi 4.3.

NOTE: The range of Linux distributions supported on the server side in opsi 4.3 remains largely the same as in opsi 4.2. A comprehensive list of Linux distributions compatible with the opsi server is available in our xref:supportmatrix:supportmatrix.adoc[opsi Support Matrix].

Due to the interdependence of opsi components, it is crucial to update the entire system to the new version. 

It's advised to first upgrade the server, followed by the opsi packages (products). In environments with multiple depots, the upgrade should commence with the config server and then proceed to the depots.

With opsi 4.3, the system exclusively uses the now freely available MySQL backend. If you are migrating from a file backend, this transition will occur automatically during the server package upgrade process.

== Preparations

Before initiating the upgrade of your opsi environment, it's important to conduct an upgrade check. This process will provide valuable insights and highlight any potential issues that may arise during the upgrade:

[source,console]
----
opsiconfd health-check --upgrade-check
----

Ensure that you resolve all the problems highlighted by the upgrade check before proceeding with the upgrade.
