////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      02.10.2023
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

= Upgrade from opsi 4.2 to 4.3

On xref:supportmatrix:supportmatrix.adoc[supported operating systems] it is possible to upgrade an existing opsi 4.2 installation to opsi 4.3.

NOTE: A change from opsi 4.1 directly to opsi 4.3 is not supported. You have to upgrade to opsi 4.2 first before you can upgrade to opsi 4.3.

TIP: If you manage your opsi servers with opsi itself, you can do the upgrade with the localboot product `l-opsi-server-migrate`.

== Create backup

Be sure to create a backup before upgrading:

[source,console]
----
opsi-backup create
----

TIP: Starting with opsi 4.3 the `opsiconfd` takes care of backup and restore (`opsiconfd backup` / `opsiconfd restore`). See also the chapter xref:server:components/backup.adoc[Backup of the opsi server].

== Enter new repositories

First enter the opsi-4.3 repositories into the configuration files of your operating system. Also add the GPG key of the repository. You will need root privileges to do this.

This is what the commands look like for the supported operating systems:

*Debian 12 _Bookworm_:*
[source,console]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_12/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_12/Release.key | sudo apt-key add -
----

*Debian 11 _Bullseye_:*
[source,console]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_11/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_11/Release.key | sudo apt-key add -
----

*Debian 10 _Buster_:*
[source,console]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_10/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Debian_10/Release.key | sudo apt-key add -
----

*Ubuntu 22.10 LTS _Kinetic Kudu:*
[source,console]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/xUbuntu_22.10/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/xUbuntu_22.10/Release.key | sudo apt-key add -
----

*Ubuntu 22.04 LTS _Jammy Jellyfish_:*
[source,console]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/xUbuntu_22.04/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/xUbuntu_22.04/Release.key | sudo apt-key add -
----

*Ubuntu 20.04 LTS _Focal Fossa_:*
[source,console]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/xUbuntu_20.04/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/xUbuntu_20.04/Release.key | sudo apt-key add -
----

*RHEL 9:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/RHEL_9/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*RHEL 8:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/RHEL_8/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*AlmaLinux 9:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/AlmaLinux_9/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*AlmaLinux 8:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/AlmaLinux_8/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*Rocky Linux 9:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/RockyLinux_9/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*Rocky Linux 8:*
[source,console]
[subs="attributes"]
----
cd /etc/yum.repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/RockyLinux_8/home:uibmz:opsi:4.3:{release}.repo
yum makecache
----

*SLES 15 SP 1:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3{release}/SLE_15_SP1/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*SLES 15 SP 2:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/SLE_15_SP1/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*SLES 15 SP 3:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/SLE_15_SP3/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*SLES 15 SP 4:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/SLE_15_SP3/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*openSUSE Leap 15.4:*
[source,console]
[subs="attributes"]
----
cd /etc/zypp/repos.d
wget https://download.opensuse.org/repositories/home:uibmz:opsi:4.3:{release}/openSUSE_Leap_15.4/home:uibmz:opsi:4.3:{release}.repo
zypper refresh
----

*Univention UCS 5.0:*
[source,console]
[subs="attributes"]
----
echo "deb http://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Univention_5.0/ /" > /etc/apt/sources.list.d/opsi.list
wget -q -O - https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/{release}/Univention_5.0/Release.key | sudo apt-key add -
----

== Upgrade operating system packages

After you have entered the new package sources, you can now start the upgrade. You will also need root privileges to do this.

IMPORTANT: For RPM-based distributions, existing configuration files will be replaced with new ones during the upgrade. Please refer to the instructions for the corresponding distributions.

=== Debian and Ubuntu

*Single server setup:*
[source,console]
----
apt update
apt install opsi-server-full
----

*Manual setup:*
[source,console]
----
apt update
apt install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
apt dist-upgrade
----

=== RHEL, AlmaLinux and Rocky Linux

*Single server setup:*
[source,console]
----
yum makecache
yum install opsi-server-full
yum upgrade
----

*Manual setup:*
[source,console]
----
yum makecache
yum install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
yum upgrade
----

=== SLES and openSUSE Leap

*Single server setup:*
[source,console]
----
zypper refresh
zypper install opsi-server-full
----

*Manual setup:*
[source,console]
----
zypper refresh
zypper install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
zypper dup --from home_uibmz_opsi_4.3_{release}
----

=== Univention Corporate Server (UCS)

*Single server setup:*
[source,console]
----
univention-install opsi-server-full
----

*Manual setup:*
[source,console]
----
univention-install redis-server redis-timeseries grafana
systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server
univention-install opsi-server
----

== Adjust configuration

These two changes are optional but recommended:

* Set `opsiclientd.config_service.permanent_connection = true` to enable client and server communication over the opsi message bus.

* Set `opsiclientd.global.verify_server_cert = true` to make the opsi clients verify the SSL server certificates of the servers.

[[opsi-4.3-releasenotes-installation-migration-opsi-packages-standard]]
== update opsi-packages

The last step is to update to the latest opsi packages.

If you have not changed the default settings in `/etc/opsi/package-updater.repos.d/`, upgrade the opsi packages with this command:

[source,console]
----
opsi-package-updater -v update
----

Your opsi-4.2 server is now updated to version 4.3 and ready to use.
