////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      22.02.2019
:Revision:  4.1
:toclevels: 6


include::../common/opsi_terms.asciidoc[]


[[opsi-manual-troubleshooting]]
== Problembehebung

In der Regel sehen wir zuerst die Symptome des Problem, bevor wir feststellen, dass es falsch gelaufen ist.
Unser nächster Schritt sollte sein heraus zu finden wo das Problem liegt.
Sobald wir das wissen, können wir uns an die Behebung machen.

Bei der Suche nach dem Problem ist es eine gute Idee nochmal die entsprechenden
Kapitel zu lesen und die eigene Konfiguration zu überprüfen.
Stundenlang einen Fehler suchen und dann fest zu stellen, dass es ein Schreibfehler war, kann sehr frustrierend sein.

Wenn Sie durch die folgenden Vorschläge gehen, sollten Sie immer wieder versuchen
den Fehler nachzustellen, um zu prüfen, ob er dadurch bereits verschwunden ist.


[[opsi-manual-troubleshooting-general-updates]]
=== Updates Installieren

Normalerweise ist der einfachste erste Schritt bei der Fehlerbehebung sicher
zu stellen, dass die neueste Software-Version verwendet wird.
Mit dem Wechsel auf eine neuere Version erhöht sich die Chance,
dass ein bestehendes Problem in der Zwischenzeit bereits behoben wurde.

Wann immer Aktualisierungen für opsi veröffentlicht werden, wird die im link:https://forum.opsi.org/[Forum] bekannt gegeben.
Mit der Veröffentlichungsinformation gibt es außerdem Changelogs, welche
dabei helfen können mit welcher Version einer Komponente ein Fix für das eigene
Problem veröffentlicht wurde.

Auf einem Debian-basierten System können Betriebssytemupdates wie folgt eingespielt werden:
[source,prompt]
----
apt update
apt dist-upgrade
----

Anschließend sollten die opsi-Pakete aktualisiert werden	:
[source,prompt]
----
opsi-package-updater -v update
----


[[opsi-manual-troubleshooting-general-opsi]]
=== opsi-Konfiguration

Sie sollten sicherstellen, dass die aktuelle Konfiguration angewendet
und entsprechend Dateizugriffsrechte gesetzt sind.

[source,prompt]
----
opsi-setup --set-rights
opsi-setup --init-current-config
----

Falls Sie das MySQL-Backend verwenden, stellen Sie sicher, dass alle Migrationen
angewendet sind:
[source,prompt]
----
opsi-setup --update-mysql
----

Als letzter Schritt sollten die opsi-Dienste neu gestartet werden, damit diese
auf jeden Fall mit der neuen Konfiguration arbeiten:
[source,prompt]
----
systemctl restart opsiconfd.service
systemctl restart opsipxeconfd.service
----

In manchen Fällen kann auch ein Server-Neustart Wunder bewirken.


[[opsi-manual-troubleshooting-general-logging]]
=== Logging

Um heraus zu finden was falsch läuft, ist ein Blick in Logdateien oftmals der
zielführendste Weg.
Standardmäßig loggen opsi-Komponenten Informationen, welche zur Laufzeit nützlich sindm
aber für eine tiefergehende Fehleranalyse sollte das Loglevel erhöht werden.
Danach sollte versucht werden das gleiche Fehlverhalten reproduziert zu werden
und anschließend die Logs untersucht werden.

Nach der Lösung des Problems sollten Sie nicht vergessen das Loglevel wieder
auf den Standard zurück zu setzen, weil ein sehr hohes Loglevel Ihre Server
verlangsam und ungewollt eine große Menge Speicherplatz belegen könnte.
