////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////
:Author:    uib gmbh
:Email:     info@uib.de
:Date:      20.03.2023
:Revision:  4.2
:toclevels: 6
:doctype:   book
:icons: font
:xrefstyle: full
:chapter-label:
:getstarted:  getting started


ifeval::["{mode}" == "antora"]
include::common:partial$opsi_terms.adoc[]
endif::[]

// = opsi Getting Started opsi-Version 4.2

// Include common opsi copyright
// include::../common/opsi_manual_copyright.asciidoc[]

[[opsi-getting-started-introduction]]
= Einführung

Diese Anleitung beschreibt, wie Sie einen opsi-Server mit unseren Paketen installieren und in Betrieb nehmen. Die Anleitung erklärt auch, wie Sie opsi zu Testzwecken auf einem Client einrichten.

Die Inbetriebnahme eines opsi-Servers erfolgt in mehreren Schritten:

. Installation des Servers
. Konfiguration des Servers (Netzwerk, Benutzer und Passwörter, Produkte)
. Einrichtung von Clients 
. Einspielen vorhandener Produkte
. Paketierung und Verteilung eigener Software

TIP: Für eine ausführliche Beschreibung der Features sowie Erklärungen zu den kostenpflichtigen Erweiterungen lesen Sie bitte das xref:introduction.adoc[opsi-Handbuch].

NOTE: Für die ersten Versuche mit opsi empfehlen wir, in einer Testumgebung und in einem isolierten Netzwerk zu arbeiten -- u.{nbsp}a. ohne konkurrierende DHCP-Server. Das Testnetz benötigt Internetzugriff, um bei Bedarf Pakete aus entfernten Quellen und Aktualisierungen zu installieren. Falls Sie bei der Einbindung in bestehende Netze Hilfe benötigen, link:https://uib.de/de/support-schulung/support/[kontaktieren Sie uns].

[[opsi-getting-started-convention]]
== Konventionen und Schreibweisen

Wir verwenden in diesem Handbuch die folgenden Schreibweisen und Hervorhebungen:

* Datei- und Verzeichnisnamen erscheinen in `Proportionalschrift`.
* Längere Befehle und Listings stehen in eigenen Kästen; Sie können diese bequem per Copy{nbsp}&{nbsp}Paste übertragen: +
[source,prompt]
----
dies ist ein Befehl
----
* Menüeinträge und Beschriftungen von Schaltflächen erscheinen _kursiv_.
* Tasten und Tastenkombinationen stehen in eckigen Klammern, z.{nbsp}B. [C], [Strg]+[C] usw.
