////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      21.04.2023
:Revision:  4.2
:toclevels: 6
:doctype:   book
:icons: font
:xrefstyle: full


ifeval::["{mode}" == "antora"]
include::common:partial$opsi_terms.adoc[]
endif::[]

[[opsi-getting-started-introduction]]
= Einführung

Diese Anleitung beschreibt, wie Sie einen opsi-Server installieren. Die Inbetriebnahme eines opsi-Servers erfolgt in mehreren Schritten:

. Installation des Servers
. Konfiguration des Servers (Netzwerk, Benutzer und Passwörter, Produkte)
. Einrichtung von Clients 
. Einspielen vorhandener Produkte
. Paketierung und Verteilung eigener Software

TIP: Für eine ausführliche Beschreibung der Features sowie Erklärungen zu den kostenpflichtigen Erweiterungen lesen Sie bitte xref:manual:introduction.adoc[opsi-Komponenten im Detail].

NOTE: Für die ersten Versuche mit opsi empfehlen wir, in einer Testumgebung und in einem isolierten Netzwerk zu arbeiten -- u.{nbsp}a. ohne konkurrierende DHCP-Server. Das Testnetz benötigt Internetzugriff, um bei Bedarf Pakete aus entfernten Quellen und Aktualisierungen zu installieren. Falls Sie bei der Einbindung in bestehende Netze Hilfe benötigen, link:https://uib.de/de/support-schulung/support/[kontaktieren Sie uns].

