////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype: book 
:getstarted: getting started

include::common:partial$opsi_terms.adoc[]

[[firststeps-software-deployment-product-tests]]
= Rollout existierender Produkte

Für den Rollout von Software auf Clients muss auf diesen der _opsi-client-agent_ installiert sein.
Dieser kann auf xref:adding-clients.adoc#firststeps-software-deployment-client-integration[bestehende Rechner] ausgerollt werden.
Bei einer xref:os-installation.adoc#firststeps-osinstall[Betriebssysteminstallation] über opsi wird der _opsi-client-agent_ automatisch installiert.

Nachfolgend wird die Management-Oberfläche xref:opsiconfiged.adoc#firststeps-software-deployment-configed[{opsi-configed}]
verwendet, um Software auf Clients zu verteilen.


include::common:partial$firststeps-swdp-product-tests-configed.adoc[leveloffset=-1]

include::common:partial$firststeps-swdp-product-tests-inventory.adoc[leveloffset=-1]

////
[[opsi-getting-started-firststeps-software-deployment-product-tests-inventory]]
=== Inventarisierung mit dem localboot-Produkten hwaudit und swaudit

Wählen Sie im '{opsi-configed}', Modus 'Client-Konfiguration', unter dem Reiter 'Clients' den betreffenden Client aus.

Wenn noch nicht geschehen, aktualisieren Sie den Datenbestand des {opsi-configed}s mittels 'Datei/Daten neu laden' bzw. Anklicken des entsprechenden Icons.

Wechseln Sie zum Reiter 'Produktkonfiguration', klicken Sie in die Spalte 'Angefordert' für das Produkt +hwaudit+, daraufhin öffnet sich eine Liste/Dropdown-Menü und dort wählen Sie die Aktion 'setup'. Wiederholen Sie das für das Produkt +swaudit+.

Der Haken in der Icon-Menüleiste sollte seine Farbe auf Rot wechseln. Wenn Sie ihn anklicken, werden die neuen Einstellungen zum {opsi-Server} übermittelt, im Anschluss ist seine Farbe wieder grün.

Starten Sie dann den Client (neu).
Er sollte jetzt den +opsi-client-agent+ starten und die Produkte +hwaudit+ und +swaudit+ installieren.
Bei +hwaudit+ und +swaudit+ werden Hard- bzw. Softwareinformationen erhoben und zum {opsi-Server} übermittelt.
Die gesammelten Informationen werden unter den Tabs 'Hardwareinformationen' bzw. 'Software-Inventur' angezeigt.
////
