////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype: book 
:getstarted: getting started

include::common:partial$opsi_terms.adoc[]

[[firststeps-software-deployment-product-tests]]
= Rollout existierender Produkte

Für den Rollout von Software auf Clients muss auf diesen der _opsi-client-agent_ installiert sein.
Dieser kann auf xref:adding-clients.adoc#firststeps-software-deployment-client-integration[bestehende Rechner] ausgerollt werden.
Bei einer xref:os-installation.adoc#firststeps-osinstall[Betriebssysteminstallation] über opsi wird der _opsi-client-agent_ automatisch installiert.

Nachfolgend wird die Management-Oberfläche xref:opsiconfiged.adoc#firststeps-software-deployment-configed[{opsi-configed}]
verwendet, um Software auf Clients zu verteilen.


include::common:partial$firststeps-swdp-product-tests-configed.adoc[leveloffset=-1]

include::common:partial$firststeps-swdp-product-tests-inventory.adoc[leveloffset=-1]

////
[[opsi-getting-started-firststeps-software-deployment-product-tests-inventory]]
=== Inventarisierung mit dem localboot-Produkten hwaudit und swaudit

Wählen Sie im '{opsi-configed}', Modus 'Client-Konfiguration', unter dem Reiter 'Clients' den betreffenden Client aus.

Wenn noch nicht geschehen, aktualisieren Sie den Datenbestand des {opsi-configed}s mittels 'Datei/Daten neu laden' bzw. Anklicken des entsprechenden Icons.

Wechseln Sie zum Reiter 'Produktkonfiguration', klicken Sie in die Spalte 'Angefordert' für das Produkt +hwaudit+, daraufhin öffnet sich eine Liste/Dropdown-Menü und dort wählen Sie die Aktion 'setup'. Wiederholen Sie das für das Produkt +swaudit+.

Der Haken in der Icon-Menüleiste sollte seine Farbe auf Rot wechseln. Wenn Sie ihn anklicken, werden die neuen Einstellungen zum {opsi-Server} übermittelt, im Anschluss ist seine Farbe wieder grün.

Starten Sie dann den Client (neu).
Er sollte jetzt den +opsi-client-agent+ starten und die Produkte +hwaudit+ und +swaudit+ installieren.
Bei +hwaudit+ und +swaudit+ werden Hard- bzw. Softwareinformationen erhoben und zum {opsi-Server} übermittelt.
Die gesammelten Informationen werden unter den Tabs 'Hardwareinformationen' bzw. 'Software-Inventur' angezeigt.
////

[[firststeps-software-deployment-product-tests-hwinvent]]
[[firststeps-osinstall-tests-hwinvent]]
== Hardware-Inventarisierung mit dem netboot-Produkt hwinvent

Sofern auf Ihrem opsi-Server das Produkt 'hwinvent' bereits installiert ist und Sie einen Client <<firststeps-osinstall-create-client,aufgenommen>> haben, welcher für den Boot über das Netzwerk konfiguriert ist, können Sie etwas weiteres Nützliches tun: Hardware-Inventarisierung ohne installiertes Betriebssystem.

Wählen Sie im {opsi-configed}, Modus 'Client-Konfiguration', unter dem Reiter Client-Auswahl den betreffenden Client aus.
Wenn noch nicht geschehen, aktualisieren Sie den Datenbestand des {opsi-configed}s mittels +Datei/Daten neu laden+ bzw. Anklicken des entsprechenden Icons.
Wechseln Sie zum Reiter 'Netboot-Produkte', gehen Sie in das Feld +Anstehende Aktion+ des Produkts +hwinvent+ und wählen Sie in der dort angebotenen Liste die Aktion 'setup'.
Der Haken in der Icon-Menüleiste sollte seine Farbe auf Rot wechseln.
Wenn Sie ihn anklicken, werden die neuen Einstellungen zum {opsi-Server} übermittelt und die Farbe des Hakens wechselt im Anschluss wieder zu grün.

Starten Sie dann den Client (neu). Er sollte jetzt per PXE über das Netz ein Linux-Image ziehen, das die Hardware des PCs scannt und dann den Rechner rebootet. Wenn der Rechner nicht ansonsten schon eingerichtet war, kommt im Anschluss korrekterweise die Meldung, dass auf der Platte kein Betriebssystem installiert ist.

Das Ergebnis des Hardware-Scans hat der PC zum {opsi-Server} übermittelt. Es ist unter dem Reiter "Hardware-Informationen" einzusehen.

NOTE: Sollte nach dem Laden des bootimages der Bildschirm schwarz bleiben oder die Netzwerkkarte nicht (korrekt) funktionieren, so muss für diese konkrete Hardware evtl. die Startparameter des bootimages angepasst werden. +
Dies können Sie im '{opsi-configed}' im Tab 'Hostparameter' am Eintrag 'opsi-linux-bootimage.append' tun. +
Details hierzu finden Sie im opsi Handbuch im Kapitel 'Netboot Produkte'.