////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      20.01.2023
:Revision:  4.1
:toclevels: 6
:doctype: book

ifeval::["{mode}" == "antora"]
include::common:partial$opsi_terms.adoc[]
endif::[]

[[opsi-manual-secureboot]]
= opsi mit Secure Boot

Secure Boot, manchmal auch "Secureboot" geschrieben, ist eine von OEM-Herstellern bereitgestellte zusätzliche Sicherheitsfunktion.
Sie stellt sicher, dass autorisierte Software und Betriebssysteme auf dem Computer installiert werden können.
Diese Schutzmaßnahme, die in neueren Versionen von Windows und in einigen Linux-Distributionen enthalten ist, gewährleistet, dass die Software, die auf Ihrem Computer ausgeführt wird, von einer vertrauenswürdigen Stelle überprüft wird.
Secure Boot verwendet digitale Signaturen, um die Gültigkeit der Software, insbesondere der Dateien des Betriebssystems, zu bestätigen und sicherzustellen, dass sie nicht manipuliert wurde.
Die Software muss zunächst zur Überprüfung an eine Zertifizierungsstelle geschickt werden, die sie dann mit einer digitalen Signatur versieht.
Sobald sie signiert ist, kann sie auf einem Gerät ausgeführt werden, auf dem Secure Boot aktiviert ist.
In diesem Fall überprüft das Gerät die Signatur, bevor es die Software ausführt; stimmt die Signatur nicht überein, lässt das System die Software nicht zu.
Die Schlüssel im UEFI wurden vom Microsoft und meist dem OEM Hersteller erstellt und jedes geladene Binary im Secure Boot Modus muss auch von mit dem privaten Schlüssel des Schlüsselerstellers signiert werden.

[[opsi-manual-secureboot-requirements]]
== Voraussetzungen

NOTE: Dieses Modul ist momentan eine https://opsi.org/extensions/[kostenpflichtige Erweiterung]. Das heißt, dass Sie eine Freischaltdatei benötigen. Sie erhalten diese, nachdem Sie die Erweiterung gekauft haben. Zu Evaluierungszwecken stellen wir Ihnen kostenlos eine zeitlich befristete Freischaltung zur Verfügung. Bitte kontaktieren Sie uns dazu per mailto:info@uib.de[E-Mail].

Weitere Details hierzu finden Sie im Kapitel xref:modules/modules#opsi-manual-modules[opsi-Erweiterungen].

Die Erweiterung setzt opsi 4.1 oder neuer voraus. Die folgende Tabelle listet die benötigten opsi-Pakete auf:

.Benötigte Pakete
[options="header"]
|==========================
|opsi-Paket|Version
|`opsi-linux-bootimage`|>= 201900923-4
|`opsipxeconfd`|>= 4.1.1.15-1
|==========================

[[opsi-manual-secureboot-notes]]
=== Allgemeine Anforderungen

Die Firmware der Clients muss UEFI und Secure Boot unterstützen. Genau wie für die UEFI-Erweiterung gilt: Das Modul unterstützt nur 64{nbsp}Bit.

Für die Installation über PXE Boot (Preboot eXecution Environment) benötigen Sie ein UEFI-taugliches WinPE_UEFI (eine Variante von Windows PE, die speziell für den Start auf Systemen mit UEFI-Firmware konzipiert wurde). Oft enthält Windows PE (Windows Preinstallation Environment) bereits UEFI-Unterstützung (Ordner `EFI` und Datei `winpe/bootmgr.efi` des opsi-Netboot-Produkts). Andernfalls erstellen Sie mit DISM (Deployment Image Servicing and Management) ein aktuelles Windows PE (siehe Abschnitt xref:modules/common/partials/firststeps-osinstall_win.adoc#firststeps-osinstall-fill-base-packages-nt6-pe-manual[Manuelles Erstellen eines PE]). Ein UEFI-WinPE gehört in den Ordner `winpe_uefi` des opsi-Netboot-Produkts.

TIP: Sofern es ein Windows PE für beide Bootmodi gibt, können Sie `winpe_uefi` durch einen symbolischen Link auf `winpe` ersetzen.

[[opsi-manual-secureboot-server-configuration]]
== Konfiguration des opsi-Servers für Secure-Boot-Clients

Einen externen DHCP-Server müssen Sie so konfigurieren, dass er PXE Boot über den opsi-Server ermöglicht. Tragen Sie `linux/pxelinux.cfg/shimx64.efi.signed` als Bootdatei ein.

[source,prompt]
----
clientconfig.dhcpd.filename=linux/pxelinux.cfg/shimx64.efi.signed
----

In der Management-Oberfläche {opsi-configed} setzen Sie für UEFI-Clients ein Häkchen bei _UEFI-Boot_. Alternativ konfigurieren Sie den Hostparameter `clientconfig.dhcpd.filename` für die Clients und tragen dort die Bootdatei ein:

[source,prompt]
----
clientconfig.dhcpd.filename=linux/pxelinux.cfg/shimx64.efi.signed
----

Sie können die Einstellung auch über das folgende Kommando vornehmen:

[source,prompt]
----
opsi-admin method configState_create "clientconfig.dhcpd.filename" "<Host-ID>" "linux/pxelinux.cfg/elilo.efi"
----

CAUTION: Die Angabe der Datei `elilo.efi` dient lediglich zum Aktivieren der Option _UEFI-Boot_ in {opsi-configed}. Sie hat keinen Einfluss auf die Verwendung der DHCP-Bootdatei. In zukünftigen Versionen soll {opsi-configed} die korrekte Datei akzeptieren und eine Secure-Boot-Checkbox aktivieren.

Außerdem ändern Sie in der xref:server/important-files#opsi-manual-important-files-etc-opsi-opsipxeconfd[`opsipxeconfd`-Konfigurationsdatei] die Template-Dateien für die UEFI-Installation. Dazu ersetzen Sie

[source,prompt]
----
uefi netboot config template x64
----

durch diesen Eintrag:

[source,prompt]
----
/tftpboot/linux/pxelinux.cfg/install-grub-x64
----

TIP: Nach dem Speichern der Änderungen führen Sie am besten den Befehl `opsi-setup --init-current-config` aus.

Alle UEFI-Clients booten die vom `opsi-linux-bootimage` mitgelieferte und von Microsoft signierte Datei `shimx64.efi.signed`.
Clients mit aktiviertem Secure Boot verifizieren die Signatur und fahren dann fort.
Clients ohne Secure Boot scheitern bei der Verifikation, starten dann aber trotzdem den GRUB2-Bootloader und fahren mit der Installation fort.

Der Installationsvorgang sieht genau gleich aus.
Secure-Boot-Clients befinden sich nach der Installation im so genannten "sicheren Startzustand", gewöhnliche UEFI-Clients nicht.
Den Zustand können Sie unter Windows mit dem Befehl `msinfo32` prüfen.

[[opsi-manual-secureboot-client-configuration]]
== Konfiguration der Secure-Boot-Clients

Die Menüs der unterschiedlichen BIOS-Versionen verwenden unterschiedliche Begriffe und Bezeichnungen.
Wählen Sie im Zweifelsfall die Einstellung, die zu Ihrem Rechner passt:

* Secure Boot aktivieren: Die Einstellung finden Sie oft im Bereich _Boot_ oder _Startup_, manchmal auch im Bereich _Security_.

* BIOS im UEFI-Modus: Wenn Sie die Wahl haben zwischen _UEFI only_, _Legacy only_ oder _Both_, nehmen Sie _UEFI only_. Secure Boot funktioniert nur mit _UEFI only_. Gibt es den Eintrag _Legacy Support_, so deaktivieren sie diesen. _CSM Support_ in Verbindung mit _UEFI only_ kann aktiviert bleiben, wenn Sie keine andere Wahl haben. _UEFI Network Boot_ aktivieren Sie; der Eintrag kann auch _Network Stack_ heißen und unterhalb von _UEFI_ liegen. Haben Sie an dieser Stelle die Möglichkeit, die Einstellung gesondert für IPv4 und IPv6 zu setzen, ist _IPv4_ die richtige Wahl.
