////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.1
:doctype:   book

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]

[[opsi-4.1-releasenotes]]
= opsi Version 4.1 Release Notes

// Include common opsi copyright
include::../common/opsi_manual_copyright.asciidoc[]

[[opsi-4.1-releasenotes-overview]]
== Übersicht der Neuerungen

*Schwerpunkte dieser Freigabe sind:*

* Neuer TFTPD: opsi-tftp-hpa
* Neues Werkzeug: opsi-package-updater
* Neues Werkzeug: opsi-makepackage
* Konfigurierbarer Pfad der Workbench
* Python 2.7 als Minimum
* systemd als einziges unterstütztes Init-System

[[opsi-4.1-releasenotes-important]]
== Wichtige Hinweise - Unbedingt Beachten

opsi 4.1 ist ein eigenständiges Release, welches eigene Paketquellen mitbringt.
Diese müssen vor der Installationen in das zu aktualisierende System eingebunden werden.

Für ein Update von opsi 4.0 ist es notwendig, dass die Betriebsystem-Pakete auf dem Server den aktuellen stabilen Stand verwenden.
Andernfalls ist mit Problemen beim Update zu rechnen.

Es ist außerdem empfohlen, dass 'opsi-winst', 'opsi-client-agent' bzw. 'opsi-linux-client-agent' vor dem Update auf den Clients auf den aktuellsten Stand aus opsi 4.0 gebracht werden.

[[opsi-4.1-releasenotes-installation]]
== Hinweise zur Installation

Wir empfehlen vor der Installation des Updates eine Sicherung Ihres Backends +
mittels {opsi-backup} durchzuführen:
[source,prompt]
----
opsi-backup create
----

Die Produkte welche im Rahmen dieses Releases veröffentlicht werden, +
sind in etlichen Teilen voneinander abhängig. +
Sie sollten daher nicht versuchen, nur Teile zu installieren.

Wir empfehlen zuerst den Server und danach die opsi-Produkte zu aktualisieren.

Wir empfehlen nach dem Update die Ausführung von `opsi-setup --set-rights`, +
um sicher zu stellen, dass die Zugriffsberechtigungen korrekt gesetzt sind. +
Die Ausführung des Befehls kann mehrere Minuten in Anspruch nehmen.

[[opsi-4.1-releasenotes-installation-systempackages]]
=== Hinweise zum Aktualisieren der Betriebssystem-Pakete

Bitte stellen Sie sicher, dass Sie zum Zeitpunkt der Aktualisierung die
jeweils aktuellsten Pakete von opsi 4.0 aus dem Stable-Bereich verwenden!

Da dieses Update Änderungen der Datenstruktur im Backend mit sich bringt, ist es erforderlich als ersten Schritt nach dem Update die Backends zu migrieren.

[source,prompt]
----
# Bei der Verwendung des MySQL-Backends zur Datenhaltung
opsi-setup --update-mysql
# Bei der Verwendung des File-Backends zur Datenhaltung
opsi-setup --update-file
----

Im Rahmen dieser Veröffentlichung wurde *opsi-depotserver* zu *opsi-server* umbenannt.

Für Debian-basierte Maschinen existiert ein Übergangs-Paket.
Falls Sie nach der Installation dieses Paket entfernen wollen, müssen Sie zuerst `opsi-server` als manuell installiert markieren und dann das Übergangs-Paket entfernen.

Das ist möglich mit den folgenden Schritten:

[source,prompt]
----
apt-get install opsi-server
apt-get remove opsi-depotserver
----

[[opsi-4.1-releasenotes-installation-opsipackages]]
=== Hinweise zum Aktualisieren von opsi-Paketen

TBD

[[opsi-4.1-releasenotes-packages]]
== Paketliste

.Server-Pakete:
* opsi-utils 4.1.1.x
* opsiconfd 4.1.1.x
* opsipxeconfd 4.1.1.x
* python-opsi 4.1.1.x
* opsi-linux-bootimage 20160706-1
* opsi-configed 4.1.x

.opsi-Pakete (Localboot):
* opsi-client-agent 4.1.x
* opsi-configed
* opsi-winst
* opsi-winst-test
* jedit

.opsi-Pakete (netboot):
* win* (NT6)
* opsi-clonezilla

.opsi-Pakete (opsi-linux):
* TBD

[[opsi-4.1-releasenotes-knownbugs]]
== Known Bugs / Known Problems

.KNOWN BUGS:

Keine.

.KNOWN PROBLEMS:

Keine.

[[opsi-4.1-releasenotes-eol]]
== Abkündigung

[[opsi-4.1-releasenotes-eol-opsi3]]
=== Abkündigung: Support für opsi 3.

Mit opsi 4.1 wird es keine Unterstützung mehr für opsi 3 geben.
Das betrifft Pakete, deren Control-Datei eventuell noch die Syntax von opsi 3 verwendet.
Außerdem wurde einige in opsi 3 vorhandene, aber für opsi 4 nicht portierte
Methoden aus der Backend-Erweiterung 20_legacy.conf entfernt.
Diese Methoden waren in opsi 4.0 dadurch erkennbar, dass sie eine Fehlermeldung
_NotImplementedError_ zurückgaben, wenn ein Zugriff auf sie erfolgen sollte.

Betroffene Methoden können dem Changelog von python-opsi entnommen werden.

[[opsi-4.1-releasenotes-eol_server]]
=== Abkündigung: Distributionen für opsi-server

In diesem Kapitel werden die Abkündigungen aufgelistet.
Diese Distributionsversionen werden aus verschiedenen Gründen nicht weiter +
von opsi unterstützt.

* CentOS 6.x
* RedHat Enterprise Linux 6.x
* Suse Linux Enterprise Server 11
* Univention Corporate Server 3.x

Siehe auch gesondertes Kapitel: <<opsi-4.1-releasenotes-supportmatrix>>.

[[opsi-4.1-releasenotes-eol_winclient]]
=== Abkündigung Clients: Windows Versionen

Ab opsi v4.1 werden wir die Netbootpakete für

* TBD

nicht weiter pflegen. Ebenso planen wir für diese Windowsversionen die +
Unterstützung in den Update Abo’s einzustellen. +
Falls Sie hierzu Fragen oder Probleme haben, melden Sie sich bitte bei uns.

Siehe auch gesondertes Kapitel: <<opsi-4.1-releasenotes-netboot-windows>>.

[[opsi-4.1-releasenotes-eol_linclient]]
=== Abkündigung Clients: Linux Versionen

Ab opsi v4.1 werden wir die Netbootpakete für

* TBD

nicht weiter pflegen. +
Falls Sie hierzu Fragen oder Probleme haben, melden Sie sich bitte bei uns.

[[opsi-4.1-releasenotes-supportmatrix]]
== opsi Support Matrix

Im folgenden finden Sie eine Übersicht auf welchen Plattformen opsi
als Server läuft.

include::../common/opsi_manual_supportmatrix.asciidoc[]

Sollten Sie den opsi-server auf einer Betriebssystemversion einsetzen, +
welche im vorigen Abschnitt nicht als Unterstützt aufgeführt ist,
so empfehlen wir Ihnen ein Betriebssystem-Update bevor Sie opsi v4.0.7 einspielen.

[[opsi-releasenotes-4.1-changes-opsi-package-updater]]
== Neues Werkzeug 'opsi-package-updater'

In opsi 4.1 wird das aus vorherigen Versionen bekannten Werkzeug `opsi-product-updater` durch das Werkzeug `opsi-package-updater` ersetzt.

Die Aufgaben der Werkzeuge gleichen sich, allerdings haben sich die Aufrufparamter
geändert und es sind eine Reihe von neuen Optionen hinzugekommen.

Das neue Werkzeug liefert einfache Möglichkeiten die vorhandenen Updates
zu sehen oder neue Pakete einzuspielen.

Eine ausführliche Beschreibung des Werkzeugs findet sich im Handbuch.

[[opsi-releasenotes-4.1-changes-opsi-package-updater-quickstart]]
=== Schnelleinstieg 'opsi-package-updater'

Zum Anzeigen der vorhandenen Aktualisierungen kann der folgende Befehl verwendet werden:

[source,prompt]
----
opsi-package-updater list --updatable-products
----

Die Aktualisierungen für die Pakete 'firefox' und 'javavm' können wie folgt eingespielt werden:

[source,prompt]
----
opsi-package-updater -vv update firefox javavm
----

Eine Übersicht über die in allen Repositories zur Verfügung stehenden Pakete liefert der folgende Befehl:


[source,prompt]
----
opsi-package-updater list --products
----

Die Installation des Pakets 'ubuntu' aus dem Repository 'uib_linux' kann wie folgt durchgeführt werden:

[source,prompt]
----
opsi-package-updater -vv --repo uib_linux install ubuntu
----

[[opsi-releasenotes-4.1-changes-opsi-makepackage]]
== Neues Werkzeug 'opsi-makepackage'

In opsi 4.1 wird das aus vorherigen Versionen bekannten Werkzeug `opsi-makeproductfile` durch das Werkzeug `opsi-makepackage` ersetzt.

Der neue Name soll den Unterschied zwischen einem Produkt und einem Paket verdeutlichen.
Die aus opsi 4.0 bekannten Kommandozeilenparameter können wie zuvor verwendet werden.

`opsi-makepackage` wird nun standardmäßig bei der Erstellung eines Pakets Prüfsummendateien erstellen.
Über die Schalter `--no-md5` bzw. `--no-zsync` kann dieses Verhalten deaktiviert werden.

[[opsi-releasenotes-4.1-changes-workbench]]
== Neuer Pfad der Workbench

Das Workbench-Verzeichnis wird nun bei Neu-Installationen standardmäßig unter
`/var/lib/opsi/workbench` angelegt.
Dadurch ergibt sich ein einheitlicher Aufbau von opsi auf unterschiedlichen Systemen und das Backup einer kompletten opsi-Installation wird vereinfacht.

Es ist nun außerdem möglich über das Depot-Attribut `workbenchLocalUrl` den verwendeten Pfad anzupassen.

Bei dem Update einer bestehenden Installation wird im Rahmen des Backend-Updates der Wert dieses Attributs auf `/home/opsiproducts` für existierende Depotserver gesetzt.
Auf SUSE-artigen Betriebssystemen wird von `/var/lib/opsi/workbench` als Verzeichnis ausgegangen und dieses gesetzt.
Bei Misch-Installationen muss gegebenenfalls eine nachträgliche, manuelle Anpassung erfolgen.

Ein automatischer Umzug vorhandener Daten aus dem alten Workbench-Verzeichnis findet nicht statt.


[[opsi-releasenotes-4.1-changes-python-27]]
== Python 2.7 als Mindesvoraussetzung

Es wird die Verwendung von Python 2.7 vorausgesetzt.
Ältere Versionen werden nicht mehr unterstützt.


[[opsi-releasenotes-4.1-changes-systemd]]
== systemd als Init-System

opsi 4.1 wird auf systemd als Init-System setzen.
Andere Init-Systeme werden offiziell nicht mehr unterstützt.


[[opsi-4.1-releasenotes-opsi-configed]]
== Verbesserungen am  '{opsi-configed}'

TBD

[[opsi-4.1-releasenotes-linux]]
== Linuxsupport

=== Supportmatrix

include::../common/opsi_manual_supportmatrix-linclient.asciidoc[]

[[opsi-4.1-releasenotes-netboot-windows]]
== opsi Support Matrix Windows Clients

Im folgenden finden Sie eine Übersicht auf welchen Windows Plattformen opsi
als Client läuft.

include::../common/opsi_manual_supportmatrix-winclient.asciidoc[]

[[opsi-4.1-releasenotes-python-opsi]]
== Änderungen in python-opsi

=== Wegfall der Versions-Datei

Die Datei `/etc/opsi/version` wird nicht mehr verwendet.
Die Backend-Methode 'backend_info' gibt Auskunft über die Version der verwendeten Python-library.

[source,prompt]
----
$ opsi-admin -d method backend_info | grep opsiVersion
"opsiVersion" : "4.1.1.6",
----

Wird Python verwendet, so liefert `OPSI.__version__` die verwendete Version.

[[opsi-4.1-releasenotes-misc]]
== Sonstiges

* Aus `opsi-makeproductfile` wird `opsi-makepackage`.

* `opsi-makepackage` wird automatisch ergänzende .md5 und .zsync-Dateien bei der Erstellung eines Produkts erstellen. Die kann durch `--no-md5` bzw. `--no-zsync` unterdrückt werden.

* `opsi-newprod` wird die angegeben Dateinamen für die einzelnen Aktionen automatisch als leere Dateien erstellen.

[[opsi-4.1-releasenotes-misc-changelogs]]
=== Changelogs:

TBD
