////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.1
:doctype:   book

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]

[[opsi-4.1-releasenotes]]
= opsi Version 4.1 Release Notes

// Include common opsi copyright
include::../common/opsi_manual_copyright.asciidoc[]

[[opsi-4.1-releasenotes-overview]]
== Übersicht der Neuerungen

*Schwerpunkte dieser Freigabe sind:*

* opsi-tftp-hpa
* opsi-product-updater
* tbd...

[[opsi-4.1-releasenotes-important]]
== Wichtige Hinweise - Unbedingt Beachten

TODO: tbd

[[opsi-4.1-releasenotes-installation]]
== Hinweise zur Installation

Wir empfehlen vor der Installation des Updates eine Sicherung Ihres Backends +
mittels {opsi-backup} durchzuführen:
[source,prompt]
----
opsi-backup create
----

Die Produkte welche im Rahmen dieses Releases veröffentlicht werden, +
sind in etlichen Teilen voneinander abhängig. +
Sie sollten daher nicht versuchen, nur Teile zu installieren.

Wir empfehlen zuerst den Server und danach die opsi-Produkte zu aktualisieren.

Da bei diesem Update eine neue Konfigurationsdatei für Hardware-Inventur
eingespielt wird, empfehlen wir die Ausführung von
`opsi-setup --init-current-config` zur Übernahme dieser Felder.

Wir empfehlen nach dem Update die Ausführung von `opsi-setup --set-rights`, +
um sicher zu stellen, dass die Zugriffsberechtigungen korrekt gesetzt sind. +
Die Ausführung des Befehls kann mehrere Minuten in Anspruch nehmen.

[[opsi-4.1-releasenotes-installation-systempackages]]
=== Hinweise zum Aktualisieren der Betriebssystem-Pakete

Bitte stellen Sie sicher, dass Sie zum Zeitpunkt der Aktualisierung die
jeweils aktuellsten Pakete von opsi aus dem Stable-Bereich verwenden!

Das Schema der MySQL-Datenbank muss auf den aktuellsten Stand gebracht werden.
Führen Sie dazu `opsi-setup --update-mysql` aus!

Im Rahmen dieser Veröffentlichung wurde *opsi-depotserver* zu *opsi-server* umbenannt.

Für Debian-basierte Maschinen existiert ein Übergangs-Paket, welches allerdings durch die geänderten Abhängigkeiten im Rahmen eines `dist-upgrade` nicht automatisch aktualisiert wird und manuell aktualisiert werden muss.

Das ist möglich mit den folgenden Schritten:

[source,prompt]
----
apt-get install opsi-server
apt-get remove opsi-depotserver
----

Anschließend kann eine Aktualisierung der restlichen Pakete mittels `apt-get upgrade` durchgeführt werden.

[[opsi-4.1-releasenotes-installation-opsipackages]]
=== Hinweise zum Aktualisieren von opsi-Paketen

TBD

[[opsi-4.1-releasenotes-packages]]
== Paketliste

.Server-Pakete:
* opsi-utils 4.1.1.x
* opsiconfd 4.1.1.x
* opsipxeconfd 4.1.1.x
* python-opsi 4.1.1.x
* opsi-linux-bootimage 20160706-1
* opsi-configed 4.1.x

.opsi-Pakete (Localboot):
* opsi-client-agent 4.1.x
* opsi-configed
* opsi-winst
* opsi-winst-test
* jedit

.opsi-Pakete (netboot):
* win* (NT6)
* opsi-clonezilla

.opsi-Pakete (opsi-linux):
* TBD

[[opsi-4.1-releasenotes-knownbugs]]
== Known Bugs / Known Problems

.KNOWN BUGS:

Keine.

.KNOWN PROBLEMS:

Keine.

[[opsi-4.1-releasenotes-eol]]
== Abkündigung

[[opsi-4.1-releasenotes-eol_server]]
=== Abkündigung: Distributionen für opsi-server

In diesem Kapitel werden die Abkündigungen aufgelistet.
Diese Distributionsversionen werden aus verschiedenen Gründen nicht weiter +
von opsi unterstützt.

* CentOS 6.x
* RedHat Enterprise Linux 6.x
* Suse Linux Enterprise Server 11
* Univention Corporate Server 3.x

Siehe auch gesondertes Kapitel: <<opsi-4.1-releasenotes-supportmatrix>>.

[[opsi-4.1-releasenotes-eol_winclient]]
=== Abkündigung Clients: Windows Versionen

Ab opsi v4.1 werden wir die Netbootpakete für

* TBD

nicht weiter pflegen. Ebenso planen wir für diese Windowsversionen die +
Unterstützung in den Update Abo’s einzustellen. +
Falls Sie hierzu Fragen oder Probleme haben, melden Sie sich bitte bei uns.

Siehe auch gesondertes Kapitel: <<opsi-4.1-releasenotes-netboot-windows>>.

[[opsi-4.1-releasenotes-eol_linclient]]
=== Abkündigung Clients: Linux Versionen

Ab opsi v4.1 werden wir die Netbootpakete für

* TBD

nicht weiter pflegen. +
Falls Sie hierzu Fragen oder Probleme haben, melden Sie sich bitte bei uns.

[[opsi-4.1-releasenotes-supportmatrix]]
== opsi Support Matrix

Im folgenden finden Sie eine Übersicht auf welchen Plattformen opsi
als Server läuft.

include::../common/opsi_manual_supportmatrix.asciidoc[]

Sollten Sie den opsi-server auf einer Betriebssystemversion einsetzen, +
welche im vorigen Abschnitt nicht als Unterstützt aufgeführt ist,
so empfehlen wir Ihnen ein Betriebssystem-Update bevor Sie opsi v4.0.7 einspielen.

[[opsi-4.1-releasenotes-opsi-configed]]
== Verbesserungen am  '{opsi-configed}'

TBD

[[opsi-4.1-releasenotes-linux]]
== Linuxsupport

=== Supportmatrix

include::../common/opsi_manual_supportmatrix-linclient.asciidoc[]

[[opsi-4.1-releasenotes-netboot-windows]]
== opsi Support Matrix Windows Clients

Im folgenden finden Sie eine Übersicht auf welchen Windows Plattformen opsi
als Client läuft.

include::../common/opsi_manual_supportmatrix-winclient.asciidoc[]

[[opsi-4.1-releasenotes-python-opsi]]
== Änderungen in python-opsi

=== Python 2.7

Es wird die Verwendung von Python 2.7 vorausgesetzt. Ältere Versionen werden nicht mehr unterstützt.

=== Wegfall der Versions-Datei

Die Datei `/etc/opsi/version` wird nicht mehr verwendet.
Die Backend-Methode 'backend_info' gibt Auskunft über die Version der verwendeten Python-library.

[source,prompt]
----
$ opsi-admin -d method backend_info | grep opsiVersion
"opsiVersion" : "4.1.1.6",
----

Wird Python verwendet, so liefert `OPSI.__version__` die verwendete Version.

[[opsi-4.1-releasenotes-misc]]
== Sonstiges

* Aus `opsi-makeproductfile` wird mit opsi 4.1 `opsi-makepackage`.

* `opsi-makepackage` wird automatisch ergänzende .md5 und .zsync-Dateien bei der Erstellung eines Produkts erstellen. Die kann durch `--no-md5` bzw. `--no-zsync` unterdrückt werden.

* `opsi-newprod` wird die angegeben Dateinamen für die einzelnen Aktionen automatisch als leere Dateien erstellen.

[[opsi-4.1-releasenotes-misc-changelogs]]
=== Changelogs:

TBD
