[[server-installation-docker-quick]]
== Quick Start

Für eine einfache Inbetriebnahme und Verwaltung einer opsi-Docker-Umgebung steht ein Hilfs-Skript bereit.

NOTE: Docker-Profis können auf das Hilfs-Skript verzichten und finden alle relevanten Informationen im
link:https://github.com/opsi-org/opsi-docker[opsi-docker Repository auf GitHub,window=_blank]

Unter *Windows* gehen Sie folgendermaßen vor:

1. Legen Sie einen Ordner `opsi-server` an.
2. Laden Sie das Skript link:https://raw.githubusercontent.com/opsi-org/opsi-docker/main/opsi-server/opsi-server.ps1[opsi-server.ps1,window=_blank] herunter und legen es im Ordner `opsi-server` ab.
3. Starten Sie eine Powershell mit Administrator-Rechten.
4. Führen Sie in dem Terminal-Fenster den folgenden Befehl aus: `PowerShell.exe -ExecutionPolicy Bypass`
5. Wechseln Sie mittels `cd` in den Ordner `opsi-server`.
6. Führen Sie den Befehl `.\opsi-server.ps1 start` aus.

Unter *Linux* und *macOS* gehen Sie folgendermaßen vor:

1. Legen Sie einen Ordner `opsi-server` an.
2. Laden Sie das Skript link:https://raw.githubusercontent.com/opsi-org/opsi-docker/main/opsi-server/opsi-server.sh[opsi-server.sh,window=_blank] herunter und legen es im Ordner `opsi-server` ab.
3. Starten Sie ein Terminal mit root-Rechten.
4. Wechseln Sie mittels `cd` in den Ordner `opsi-server`.
5. Machen Sie das Skript ausführbar mittels `chmod +x opsi-server.sh`.
6. Führen Sie den Befehl `./opsi-server.sh start` aus.

Die benötigten Docker-Images werden jetzt automatisch heruntergeladen und die Container gestartet.

In dem Ordner `opsi-server` liegt nun eine Datei `docker-compose.yml`. Öffnen Sie diese Datei mit einem Text-Editor. Suchen Sie nach der Umgebungsvariable `OPSI_ADMIN_PASSWORD`. Das angegebene Passwort benötigen Sie in den folgenden Schritten zur Anmeldung am opsi-Server als Benutzer `opsiadmin`.

NOTE: Es ist zu empfehlen dieses Passwort zu ändern.
Nach Änderungen an der `docker-compose.yml` müssen die Container neu gestartet werden, damit die Änderungen übernommen werden. Das funktioniert mittels `.\opsi-server.ps1 recreate` bzw. `./opsi-server.sh recreate`
