[[server-installation-docker]]
= opsi als Docker-Container

Seit 2022 gibt es ein link:https://github.com/opsi-org/opsi-docker[Docker-Image], mit dem Sie einen Configserver oder einen Depotserver einrichten können. Es setzt auf das Orchestrierungswerkzeug Docker Compose, das es ermöglicht, mehrere Container zu definieren, diese miteinander zu verbinden und auf einem Docker-Host auszuführen. Sie benötigen mindestens Docker Compose 1.17.0 und die Docker-Engine 17.09.0 oder neuer.

NOTE: Beachten Sie, dass ausschließlich WebDAV als Protokoll zur Kommunikation mit dem opsi-Depot zum Einsatz kommt; eine Samba-Unterstützung gibt es in dieser Variante nicht. Außerdem benötigen Sie eine Lizenz für die MySQL-Erweiterung, denn das File Backend wird nicht unterstützt (siehe Kapitel xref:opsi-modules:modules.adoc[opsi-Erweiterungen]).

Installieren Sie Docker bzw. Docker Desktop unter Linux, Windows oder macOS. Dass die Installation erfolgreich war, können Sie schnell mit dem folgenden Befehl im Terminal überprüfen:

[source,console]
----
docker run --rm hello-world
----

Als Antwort sollten Sie diese Ausgabe sehen:

[source,console]
----
Hello from Docker!
This message shows that your installation appears to be working correctly.
[...]
----