////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      20.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-installation-docker]]
= opsi als Docker-Container

Seit 2022 gibt es ein link:https://github.com/opsi-org/opsi-docker[Docker-Image,window=_blank], mit dem Sie einen opsi-Configserver oder einen opsi-Depotserver einrichten können. Es setzt auf das Orchestrierungswerkzeug Docker Compose, das es ermöglicht, mehrere Container zu definieren, diese miteinander zu verbinden und auf einem Docker-Host auszuführen. Sie benötigen mindestens Docker Compose 1.17.0 und die Docker-Engine 17.09.0 oder neuer.

NOTE: Beachten Sie, dass ausschließlich WebDAV als Protokoll zur Kommunikation mit dem opsi-Depot zum Einsatz kommt; eine Samba-Unterstützung gibt es in dieser Variante nicht.

== Docker installieren

Installieren Sie Docker bzw. Docker Desktop unter Linux, Windows oder macOS:

* link:https://docs.docker.com/desktop/install/windows-install/[Docker Desktop unter Windows installieren,window=_blank]
* link:https://docs.docker.com/desktop/install/mac-install/[Docker Desktop unter macOS installieren,window=_blank]
* link:https://docs.docker.com/desktop/install/linux-install/[Docker Desktop unter Linux installieren,window=_blank]

TIP: Unter Linux können Sie auch ganz einfach direkt mit der Docker Engine arbeiten. Dazu installieren Sie die entsprechenden Pakete für Ihre Linux-Distribution.

Dass die Installation erfolgreich war, können Sie schnell mit dem folgenden Befehl im Terminal überprüfen:

[source,console]
----
docker run --rm hello-world
----

NOTE: In der Voreinstellung erfordert das `docker`-Kommando Root-Rechte, das heißt, auch die Arbeit mit unseren Hilfsskripten setzt Root-Rechte voraus. Sie können dazu entweder `sudo` vor die in diesem Kapitel gezeigten Befehle stellen, oder Sie fügen einen Benutzeraccount zur Gruppe `docker` hinzu. Weitere Informationen finden Sie im Docker-Handbuch, Kapitel link:https://docs.docker.com/engine/install/linux-postinstall/[Linux post-installation steps for Docker Engine].


Als Antwort sollten Sie diese Ausgabe sehen:

[source,console]
----
Hello from Docker!
This message shows that your installation appears to be working correctly.
[...]
----

