////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      03.05.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-installation-docker-compose]]
== Docker Compose

Die Konfigurationsdatei `docker-compose.yml` definiert Netzwerke, Volumes und diese vier Dienste (Abschnitt `services`):

* `mysql`: installiert den Datenbankserver MariaDB
* `redis`: installiert die In-Memory-Datenbank Redis mit dem RedisTimeSeries-Modul
* `grafana`: spielt ein aktuelles Grafana ein
* `opsi-server`: installiert die Pakete `opsiconfd`, `opsipxeconfd`, `opsi-tftpd-hpa` und `opsi-utils` in der jeweils aktuellsten Version

Am Anfang der Datei sind einige X Properties (sogenannte Extension fields) definiert, z.{nbsp}B. `x-restart-policy`, `x-common-variables` usw. Diese YAML-Anker kommen zum Einsatz, um Einstellungen zwischen den Diensten auszutauschen.

Im weiteren Verlauf finden Sie dort einige Umgebungsvariablen für die Container. Diese bearbeiten Sie entweder in der Datei `docker-compose.yml` direkt, oder Sie setzen die Variablen in der mitgelieferten Datei `opsi-server.env`, die beim Start eingelesen wird (definiert in sder Datei `docker-compose-env.yml`). Die `.env`-Datei hält dann die Konfiguration an einer zentralen Stelle vor, und Sie müssen die Variablen nicht in der `docker-compose.yml` heraussuchen. Sie können den Stack dann über dieses Kommando starten:

[source,console]
----
docker compose -f docker-compose-env.yml up
----

NOTE: Aus Sicherheitsgründen sollten Sie alle Passwörter in der Datei `docker-compose.yml` ändern: `MYSQL_ROOT_PASSWORD`, `MYSQL_PASSWORD`, `REDIS_PASSWORD`, `GF_SECURITY_ADMIN_PASSWORD` und `OPSI_ADMIN_PASSWORD`.

Ein Kennwort für den Benutzer `root` ist nicht gesetzt. Sie können dieses über `OPSI_ROOT_PASSWORD` festlegen:

[source,toml]
----
OPSI_ROOT_PASSWORD: <passwort>
----

TIP: Wenn Sie TFTP-Netzwerk-Boot (und damit `opsipxeconfd` und `opsi-tftp-hpa`) nicht benötigen, können Sie die Variable `OPSI_TFTPBOOT` auf `"false"` setzen.

Die nächsten beiden Abschnitte erklären, wie Sie die Konfigurationsdatei `docker-compose.yml` anpassen, um einen Configserver oder einen Depotserver aufzusetzen.
