////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      18.12.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-installation-docker-compose-depot]]
=== opsi-Depotserver

Kontrollieren Sie die Einstellungen für Netzwerk und Volumes. Die beiden Dienste `mysql` und `grafana` benötigen Sie für einen Depotserver nicht, daher können Sie diese auskommentieren oder löschen. Achten Sie darauf, `mysql` dann auch im Abschnitt `opsi-server` aus dem `depends_on`-Attribut zu entfernen.

Setzen Sie die Variable `OPSI_HOST_ROLE` auf `depotserver`:

[source,toml]
----
OPSI_HOST_ROLE: depotserver
----

Für einen Depotserver setzen Sie außerdem die beiden Variablen `OPSI_SERVICE_ADDRESS` (Service-URL des opsi-Configservers) und `OPSI_HOST_KEY` (Host-Key des Depots). Danach starten Sie alle Dienste über `./opsi-server.sh start` (Linux, macOS) bzw. `.\opsi-server.ps1 start` (Windows).

NOTE: Den Host-Key des opsi-Depotservers finden Sie z.{nbsp}B. im Admin-Interface des opsi-Configservers auf dem Reiter _Depots_. Dort können Sie bei Bedarf auch einen neuen opsi-Depotserver anlegen.
