////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      20.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[server-installation-docker-quick]]
== Quick Start

Für eine einfache Inbetriebnahme und Verwaltung einer opsi-Docker-Umgebung steht ein Hilfs-Skript bereit.

NOTE: Docker-Profis können auf das Hilfs-Skript verzichten und finden alle relevanten Informationen in unserem GitHub-Repository link:https://github.com/opsi-org/opsi-docker[opsi-docker,window=_blank].

=== Windows

Unter Windows gehen Sie folgendermaßen vor:

1. Legen Sie einen Ordner `opsi-server` an.
2. Laden Sie das Skript link:https://raw.githubusercontent.com/opsi-org/opsi-docker/main/opsi-server/opsi-server.ps1[opsi-server.ps1,window=_blank] herunter und legen es im Ordner `opsi-server` ab.
3. Starten Sie eine PowerShell mit Administrator-Rechten.
4. Führen Sie im Terminalfenster den folgenden Befehl aus: `PowerShell.exe -ExecutionPolicy Bypass`
5. Wechseln Sie mit `cd` in den Ordner `opsi-server`.
6. Führen Sie den Befehl `.\opsi-server.ps1 start` aus.

=== Linux und macOS

Unter Linux und macOS führen Sie diese Schritte aus:

1. Legen Sie einen Ordner `opsi-server` an.
2. Laden Sie das Skript link:https://raw.githubusercontent.com/opsi-org/opsi-docker/main/opsi-server/opsi-server.sh[opsi-server.sh,window=_blank] herunter und legen es im Ordner `opsi-server` ab.
3. Starten Sie ein Terminal mit `root`-Rechten.
4. Wechseln Sie mit `cd` in den Ordner `opsi-server`.
5. Machen Sie das Skript ausführbari: `chmod +x opsi-server.sh`
6. Führen Sie den Befehl `./opsi-server.sh start` aus.

Die benötigten Docker-Images werden jetzt automatisch heruntergeladen und die Container gestartet.

* Mit dem Befehl `.\opsi-server.ps1 status` bzw. `./opsi-server.sh status` können Sie den Status der Container ausgeben.
* Mit dem Befehl `.\opsi-server.ps1 logs` bzw. `./opsi-server.sh logs` können Sie die Logs der Container einsehen.
* Mit dem Befehl `.\opsi-server.ps1 upgrade` bzw. `./opsi-server.sh upgrade` können Sie die Container auf die aktuellsten Versionen aktualisieren.

IMPORTANT: In dem Ordner `opsi-server` liegt nun eine Datei `docker-compose.yml`. Öffnen Sie diese Datei mit einem Texteditor. Suchen Sie nach der Umgebungsvariable `OPSI_ADMIN_PASSWORD`. Das angegebene Passwort benötigen Sie in den folgenden Schritten zur Anmeldung am opsi-Server als Benutzer `opsiadmin`.

NOTE: Wir empfehlen dringend, dieses Passwort zu ändern.

Wenn Sie die Datei `docker-compose.yml` verändert haben, starten Sie die Container neu, um die Änderungen zu übernehmen. Dazu geben Sie `.\opsi-server.ps1 recreate` bzw. `./opsi-server.sh recreate` ein.
