////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      18.12.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



[[server-installation-docker-scripts]]
== Die Helfer-Skripte

Wir haben zwei Helfer-Skripte beigelegt, die den Umgang mit dem opsi-Docker-Container erleichtern. Unter Linux und macOS verwenden Sie das Skript `opsi-server.sh`. Machen Sie dieses zun채chst ausf체hrbar:

[source,console]
----
chmod +x opsi-server.sh
----

Danach rufen Sie es als normaler Benutzer ohne weitere Parameter oder Optionen auf, um eine Onlinehilfe einzublenden:

[source,console]
----
./opsi-server.sh
Usage: ./opsi-server.sh <command>

Commands:
  edit                      Edit docker-compose.yml.
  start                     Start all containers.
  status                    Show running containers.
  stop                      Stop all containers.
  logs [service]            Attach to container logs (all logs or supplied service).
  shell [service]           Exexute a shell in a running container (default service: opsi-server).
  update                    Update and restart all containers.
  open-volumes              Open volumes directory in explorer.
  inspect [service]         Show detailed container informations (default service: opsi-server).
  diff [service]            Show container's filesystem changes (default service: opsi-server).
  prune                     Delete all containers and unassociated volumes.
  export-images             Export images as archive.
  import-images [archive]   Import images from archive.
  build [--no-cache]        Build opsi-server image. Use --no-cache to build without cache.
  publish                   Publish opsi-server image.
----

Das zweite Skript `opsi-server.ps1` ist f체r Windows-Anwender und den Einsatz auf der Windows PowerShell gedacht. Es hat im Wesentlichen die gleichen Optionen und Parameter; lediglich die letzten beiden Kommandos (`build` und `publish`) sind nicht verf체gbar.
