////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////
:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype: book
:linclientmanual: opsi-linux-client-manual
include::common:partial$opsi_terms.adoc[]


[[opsi-linclient-softwintegration]]
= Einbindung eigener Software in die Softwareverteilung von opsi

Die Installation von Software erfolgt bei opsi durch den {opsi-client-agent} und insbesondere durch das Script gesteuerte Setup Programm {opsi-script}. Daher muss zu jedem {opsi-product} ein {opsi-script}-Script erstellt werden. Danach werden dieses Script, die Installationsdateien und die Metadaten zu einem {opsi-product} gepackt, welches sich schließlich auf dem {opsi-Server} installieren lässt.

[[opsi-linclient-softwintegration-tutorial]]
== Ein kleines Tutorial zur Erstellung eines {opsi-script} Scriptes


include::common:partial$softwintegration-tutorial-introduction.adoc[leveloffset=-1]

[[opsi-linclient-softwintegration-tutorial-general]]
=== Methoden der nicht interaktiven Softwareinstallation bei Linux

Linux hat (im Gegensatz zu Windows) vergleichsweise stark standadisierte Paketformate und Installationsmetoden. Die Problematik liegt bei Linux in der Vielzahl von Distributionen, die sich wiederum in den Paketformaten und Installationsbefehlen unterscheiden.
Im Kern gibt es folgende Varianten:

* Installation eines Paketes aus einem Repository
* Installation eines Paketes aus einer Datei (*.rpm, *.deb)
* Installation mit einem Third-Party Installer
* Installation aus dem Quellcode (make install)


In den ersten beiden Fällen ist eine `unattended` (also nicht interaktive) Installation kein Problem.

Häufig wird Linux Software in gepackten Formaten angeboten wie *.zip oder auch *.tgz.

Alle bisher genannten Varianten können per {opsi-script} direkt installiert werden, außer *.tgz welches vorher ausgepackt werden muß.

include::common:partial$softwintegration-tutorial-script-structure-opsi-script-basics.adoc[leveloffset=-1]
//
[[opsi-linclient-softwintegration-tutorial-Linux-special-commands]]
==== Spezielle Kommandos für Linux

* GetOS   // liefert: Linux or Windows_NT or MacOS [W/L/M]

* getLinuxDistroType // liefert: debian or redhat or suse [L] +
https://download.uib.de/opsi_stable/doc/html/opsi-script-manual/opsi-script-manual.html#getLinuxDistroType

* getLinuxVersionMap [L] +
https://download.uib.de/opsi_stable/doc/html/opsi-script-manual/opsi-script-manual.html#getLinuxVersionMap

Eine Übersicht linuxspezifischer Kommandos in {opsi-script} findet sich hier: +
https://download.uib.de/opsi_stable/doc/html/opsi-script-manual/opsi-script-manual.html#opsi-script-rc-linux-specific

In den folgenden Kapiteln werden spezielle opsi Linux Befehle zur Installation von Software vorgestellt welche aus der {opsi-script} Library `uib_lin_install` stammen. Diese Dokumentation ist in Englisch, da sie direkt aus dem Quellcode automatisch generiert wurde.

Zum Verständnis zunächst ein Überblick über die unterschiedlichen Ansätze der Methoden:

* Distributionsunabhängige Methoden:

** `cleanupPackageSystem`

** `installupdates`

* Installation von einem oder mehreren Paketen aus online Repos für eine spezifische Distribution +
Soll nur ein Paket installiert werden, so ist in dem Aufrufen statt $packagelist$, zu verwenden: `createStringList(<package name>)` +
Die Paketnamen in der Liste müssen zur Distribution / Version passen.

** debinstall($packagelist$ : stringlist) : string //since 4.12.4 [L]

** redinstall($packagelist$ : stringlist) : string //since 4.12.4 [L]

** suseinstall($packagelist$ : stringlist) : string //since 4.12.4 [L]

** ucsinstall($packagelist$ : stringlist) : string //since 4.12.4 [L]

* Installation / Deinstallation von einem oder mehren Paketen für eine bekannte Distribution / Version (d.h. Paketnamen müssen passen). +
Der notwendige Befehl wird anhand der Distribution ermittelt.

** genericLinInstall($packagelist$ : stringlist) : string

** linuxRemoveOnePackage($packagename$ : string) : string

** linuxInstallOneFile($packagefile$ : string) : string


* Installation / check / deinstallation von einem Paket aus online Repos für unterschiedliche Distributionen / Versionen, weswegen das Paket auch unterschiedliche Namen haben kann. +
D.h. es wird davon ausgegangen, das die Paketnamen in der Liste alles pseudonyme für das selbe Paket sind aber für unterschiedliche Versionen bzw. Distributionen.
Der notwendige Befehl wird anhand der Distribution ermittelt.

** linuxInstallOneOf($packagelist$ : stringlist) : string

** isOneInstalled($packagelist$ : stringlist) : string

** linuxRemoveOneOf($packagelist$ : stringlist) : string

// http://www.methods.co.nz/asciidoc/userguide.html#X90


// Include os-lib_uib_Linuxinstalllib.asciidoc
include::opsi-docs-en:common:partial$os-lib-uib-lin-install.adoc[leveloffset=4]



[[opsi-linclient-softwintegration-tutorial-template]]
=== Beispiel: Linux-Template _l-opsi-template_

Dieses Template können Sie sich mit dem `opsi-setup-detector` erstellen.

// include docu: actual template for Linux
include::opsi-docs-en:common:partial$firststeps-opsi-template-lin.adoc[]


 

[[opsi-client-softwintegration-create-opsi-package]]
== Erstellen eines opsi-Produkt-Pakets

////
[[opsi-setup-detector-installation]]
=== Installation des opsi-setup-detector, {opsi-package-builder} und opsi-logviewer
////

// include docu: opsi-setup-detector installation
include::common:partial$setup-detector-installation.adoc[]


// include docu: opsi-logviewer installation
include::common:partial$opsi-logviewer-installation.adoc[leveloffset=-1]



[[opsi-linclient-softwintegration-tutorial-create-with-opsi-setup-detector]]
=== Das Programm opsi-setup-detector zum Erstellen eines Linux Scriptes

// include docu: opsi-setup-detector
include::common:partial$setup-detector-use-start.adoc[]

// include docu: Linux specific tasks in opsi-setup-detector
include::common:partial$osd-task-linux.adoc[]

Die nun folgenden Screenshots zeigen zwar die Verwendung von Windows-Installer Dateien,
sie sehen aber analog aus bei der Verwendung von Linux Installer Dateien wie *.deb, *.rpm.

// include docu: how to use the opsi-setup-detector
include::common:partial$osd-task-use-single-analyze-and-create.adoc[]

Mehr Details zum `opsi-setup-detector` finden Sie im opsi-manual: +
https://docs.opsi.org/opsi-docs-de/4.2/manual/modules/setup-detector.html

// include docu: how to use the opsiPackagebuilder
include::common:partial$softwintegration-tutorial-packagebuilder-use.adoc[leveloffset=-1]

// include docu: The modify and test cycle
include::common:partial$softwintegration-tutorial-modify-test-cycle.adoc[leveloffset=-1]

[[opsi-winclient-softwintegration-tutorial-template-details]]
== Hinweise zu den Teilaufgaben in der Paketierung

// include docu: OSD Checkboxes for additional code
include::common:partial$osd-checkboxes-subtasks.adoc[leveloffset=-1]

