////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype:   book
:toc: left
:toclevels: 3
:numbered:
:icons: font
:xrefstyle: full
:chapter-label:
:gstarted:  getting started
:source-highlighter: rouge
:release: stable

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]


= opsi Getting Started opsi-Version 4.2

// Include common opsi copyright
include::../common/opsi_manual_copyright.asciidoc[]


[[opsi-getting-started-introduction]]
== Einführung

Diese Anleitung beschreibt detailliert die Installation und Inbetriebnahme eines {opsi-Server}s, ausgehend von den zur Verfügung gestellten Installationspaketen bis zur Testinstallation eines Clients.

Die Installation und Inbetriebnahme eines {opsi-Server}s erfolgt in mehreren Schritten:

. Grundinstallation des Servers
. Konfiguration des Servers (Anpassung an Netzwerkgegebenheiten, Einrichtung von Benutzern und Kennwörtern, Installation zu verteilender Produkte)
. Aufnahme und Einbindung von Rechnern in opsi
. Verteilung von Windows auf Clients
. Paketierung und Verteilung eigener Software

Danach kann auf einem Client automatisiert ein Betriebssystem mitsamt Software installiert und eine Hard- und Software-Inventur gemacht werden.

Weitere Features sind im opsi-Handbuch beschrieben.
Dort finden sich auch Erläuterungen und Erklärungen zu den kofinanzierten Erweiterungen und deren Einrichtung.

Die dargestellte Netzwerkkonfiguration ist exemplarisch und bezieht sich auf ein Netz u.a. ohne konkurrierende DHCP-Server (z.B. ein isoliertes Testnetz, in das der {opsi-Server} und seine Clients für die ersten Versuche gestellt werden können).

Wir empfehlen Ihnen dringend, erste Versuche mit opsi in einem Testnetz zu machen, das getrennt von anderen DHCP-Servern ist, welches Sie aber zeitweise an Ihr Hauptnetz ankoppeln können, um z.B. Aktualisierungen und Pakete aus dem Internet laden zu können

Für die Einbindung in bestehende Netze können Sie ggf. auf link:https://uib.de/de/support-schulung/support/[Beratungsleistungen durch uib] zurückgreifen.


[[opsi-getting-started-convention]]
=== Konventionen dieses Dokuments

Befehle werden gesondert hervorgehoben:

[source,prompt]
----
dies ist ein Befehl
----

Im Rahmen der Installation und Konfiguration können Sie die Befehle aus diesen Feldern in der Regel der Reihe nach per _copy & paste_ aus diesem Dokument kopieren und ausführen.

include::../common/getting_started_requirements.asciidoc[]

include::../common/getting_started_server-installation.asciidoc[]

include::../common/getting_started_base-installation.asciidoc[]

include::../common/getting_started_configuration.asciidoc[]

include::../common/getting_started_minimal-products.asciidoc[]

include::../common/getting_started_opsiconfiged.asciidoc[]


include::../common/firststeps-adding-clients.asciidoc[]

include::../common/firststeps-win-client-integration.asciidoc[]

[[firststeps-software-deployment-product-tests]]
== Rollout existierender Produkte

Für den Rollout von Software auf Clients muss auf diesen der 'opsi-client-agent' installiert sein.
Dieser kann auf <<firststeps-software-deployment-client-integration,bestehende Rechner>> ausgerollt werden.
Bei einer <<firststeps-osinstall,Betriebssysteminstallation>> über opsi wird der 'opsi-client-agent' automatisch installiert.

Nachfolgend wird die Management-Oberfläche <<firststeps-software-deployment-configed,{opsi-configed}>> verwendet, um Software auf Clients zu verteilen.


include::../common/firststeps-swdp-product-tests-configed.asciidoc[]

include::../common/firststeps-swdp-product-tests-inventory.asciidoc[]

////
[[opsi-getting-started-firststeps-software-deployment-product-tests-inventory]]
=== Inventarisierung mit dem localboot-Produkten hwaudit und swaudit

Wählen Sie im '{opsi-configed}', Modus 'Client-Konfiguration', unter dem Reiter 'Clients' den betreffenden Client aus.

Wenn noch nicht geschehen, aktualisieren Sie den Datenbestand des {opsi-configed}s mittels 'Datei/Daten neu laden' bzw. Anklicken des entsprechenden Icons.

Wechseln Sie zum Reiter 'Produktkonfiguration', klicken Sie in die Spalte 'Angefordert' für das Produkt +hwaudit+, daraufhin öffnet sich eine Liste/Dropdown-Menü und dort wählen Sie die Aktion 'setup'. Wiederholen Sie das für das Produkt +swaudit+.

Der Haken in der Icon-Menüleiste sollte seine Farbe auf Rot wechseln. Wenn Sie ihn anklicken, werden die neuen Einstellungen zum {opsi-Server} übermittelt, im Anschluss ist seine Farbe wieder grün.

Starten Sie dann den Client (neu).
Er sollte jetzt den +opsi-client-agent+ starten und die Produkte +hwaudit+ und +swaudit+ installieren.
Bei +hwaudit+ und +swaudit+ werden Hard- bzw. Softwareinformationen erhoben und zum {opsi-Server} übermittelt.
Die gesammelten Informationen werden unter den Tabs 'Hardwareinformationen' bzw. 'Software-Inventur' angezeigt.
////

[[firststeps-software-deployment-product-tests-hwinvent]]
[[firststeps-osinstall-tests-hwinvent]]
=== Hardware-Inventarisierung mit dem netboot-Produkt hwinvent

Sofern auf Ihrem opsi-Server das Produkt 'hwinvent' bereits installiert ist und Sie einen Client <<firststeps-osinstall-create-client,aufgenommen>> haben, welcher für den Boot über das Netzwerk konfiguriert ist, können Sie etwas weiteres Nützliches tun: Hardware-Inventarisierung ohne installiertes Betriebssystem.

Wählen Sie im {opsi-configed}, Modus 'Client-Konfiguration', unter dem Reiter Client-Auswahl den betreffenden Client aus.
Wenn noch nicht geschehen, aktualisieren Sie den Datenbestand des {opsi-configed}s mittels +Datei/Daten neu laden+ bzw. Anklicken des entsprechenden Icons.
Wechseln Sie zum Reiter 'Netboot-Produkte', gehen Sie in das Feld +Anstehende Aktion+ des Produkts +hwinvent+ und wählen Sie in der dort angebotenen Liste die Aktion 'setup'.
Der Haken in der Icon-Menüleiste sollte seine Farbe auf Rot wechseln.
Wenn Sie ihn anklicken, werden die neuen Einstellungen zum {opsi-Server} übermittelt und die Farbe des Hakens wechselt im Anschluss wieder zu grün.

Starten Sie dann den Client (neu). Er sollte jetzt per PXE über das Netz ein Linux-Image ziehen, das die Hardware des PCs scannt und dann den Rechner rebootet. Wenn der Rechner nicht ansonsten schon eingerichtet war, kommt im Anschluss korrekterweise die Meldung, dass auf der Platte kein Betriebssystem installiert ist.

Das Ergebnis des Hardware-Scans hat der PC zum {opsi-Server} übermittelt. Es ist unter dem Reiter "Hardware-Informationen" einzusehen.

NOTE: Sollte nach dem Laden des bootimages der Bildschirm schwarz bleiben oder die Netzwerkkarte nicht (korrekt) funktionieren, so muss für diese konkrete Hardware evtl. die Startparameter des bootimages angepasst werden. +
Dies können Sie im '{opsi-configed}' im Tab 'Hostparameter' am Eintrag 'opsi-linux-bootimage.append' tun. +
Details hierzu finden Sie im opsi Handbuch im Kapitel 'Netboot Produkte'.


include::../common/firststeps-osinstall_win.asciidoc[]

include::../common/opsi-packaging-tutorial-windows.asciidoc[]


[[opsi-getting-started-more-info]]
== Weitere Informationen

Das link:https://download.uib.de/opsi_stable/doc/opsi-handbuch-stable-de.pdf[opsi-Handbuch] enthält eine Fülle von weiteren Informationen, die für den produktiven Betrieb wichtig sind.
Wenn Sie ihren opsi-Server produktiv einsetzen empfehlen wir Ihnen besonders sich mit dem Werkzeug 'opsi-backup' vertraut zu machen, um eine Sicherung Ihrer Daten erstellen zu können.

Wenn Sie dort nicht fündig werden oder Hilfe benötigen, wenden Sie sich an link:https://forum.opsi.org[die opsi Community].

Für produktive Installationen empfehlen wir professionelle Unterstützung durch uib im Rahmen eines link:https://uib.de/de/support-schulung/support/[Pflege- und Supportvertrages].
