////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype:   book
:toc: left
:toclevels: 3
:numbered:
:icons: font
:xrefstyle: full
:chapter-label:
:gstarted:  getting started
:source-highlighter: rouge
:release: stable

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]


= opsi Getting Started opsi-Version 4.2

// Include common opsi copyright
include::../common/opsi_manual_copyright.asciidoc[]


[[opsi-getting-started-introduction]]
== Einführung

Diese Anleitung beschreibt detailliert die Installation und Inbetriebnahme eines {opsi-Server}s, ausgehend von den zur Verfügung gestellten Installationspaketen bis zur Testinstallation eines Clients.

Die Installation und Inbetriebnahme eines {opsi-Server}s erfolgt in mehreren Schritten:

. Grundinstallation des Servers
. Konfiguration des Servers (Anpassung an Netzwerkgegebenheiten, Einrichtung von Benutzern und Kennwörtern, Installation zu verteilender Produkte)
. Aufnahme und Einbindung von Rechnern in opsi
. Verteilung von Windows auf Clients
. Paketierung und Verteilung eigener Software

Danach kann auf einem Client automatisiert ein Betriebssystem mitsamt Software installiert und eine Hard- und Software-Inventur gemacht werden.

Weitere Features sind im opsi-Handbuch beschrieben.
Dort finden sich auch Erläuterungen und Erklärungen zu den kofinanzierten Erweiterungen und deren Einrichtung.

Die dargestellte Netzwerkkonfiguration ist exemplarisch und bezieht sich auf ein Netz u.a. ohne konkurrierende DHCP-Server (z.B. ein isoliertes Testnetz, in das der {opsi-Server} und seine Clients für die ersten Versuche gestellt werden können).

Wir empfehlen Ihnen dringend, erste Versuche mit opsi in einem Testnetz zu machen, das getrennt von anderen DHCP-Servern ist, welches Sie aber zeitweise an Ihr Hauptnetz ankoppeln können, um z.B. Aktualisierungen und Pakete aus dem Internet laden zu können

Für die Einbindung in bestehende Netze können Sie ggf. auf link:https://uib.de/de/support-schulung/support/[Beratungsleistungen durch uib] zurückgreifen.


[[opsi-getting-started-convention]]
=== Konventionen dieses Dokuments

Befehle werden gesondert hervorgehoben:

[source,prompt]
----
dies ist ein Befehl
----

Im Rahmen der Installation und Konfiguration können Sie die Befehle aus diesen Feldern in der Regel der Reihe nach per _copy & paste_ aus diesem Dokument kopieren und ausführen.

include::../common/getting_started_requirements.asciidoc[]

include::../common/getting_started_server-installation.asciidoc[]

include::../common/getting_started_base-installation.asciidoc[]

include::../common/getting_started_configuration.asciidoc[]

include::../common/getting_started_minimal-products.asciidoc[]

include::../common/getting_started_opsiconfiged.asciidoc[]

include::../common/getting_started_adding-clients.asciidoc[]

include::../common/getting_started_rollout-products.asciidoc[]

include::../common/getting_started_hwinvent.asciidoc[]

include::../common/getting_started_os-installation.asciidoc[]

include::../common/getting_started_packaging-tutorial.asciidoc[]

include::../common/getting_started_more.asciidoc[]