////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:toc: left
:toclevels: 3
:numbered:
:icons: font
:xrefstyle: full
:doctype:   book
:date:      26.05.2021

:winclientmanual: opsi-windows-client-manual

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]


= opsi Windows client manual

// Include common opsi copyright
include::../common/opsi_manual_copyright.asciidoc[]


[[opsi-winclient-introduction]]
== Introduction of Windows clients in opsi

This manual describes the operation of Windows clients in opsi.

It is assumed that the installation and commissioning of an {opsi-Server} has already been completed.

Main topics of this manual:

. Automatic Windows OS installation
. Enrollment and integration of Windows computers in opsi
(Installation of the opsi-client-agent)
. Provision of the standard opsi software for Windows on the opsi server
. Installation of standard software on the Windows clients
. standard opsi software for Windows under opsi
. Packaging your own software
. Creation of opsi packages
. Notes on Windows clients
.. Special commands for Windows
.. Directories that you can use


[[opsi-winclient-convention]]
== Conventions of this document

Commands are highlighted separately:

[source,shell]
----
This is a command
----

As part of the installation and configuration, you can usually copy the commands from these fields one after the other using _copy & paste_ from this document and execute them.

This is opsi-script code:

[source,winst]
----
Message "Installing "+ $ProductId$ +" ..."
----

Chapters that contain the name of a particular platform are specific to that platform. The supported platforms are:

* *Windows*

* *Linux*

* *macOS*


include::requirements.adoc[]

include::minimal-products.adoc[]

include::adding-clients.adoc[]

include::rollout-products.adoc[]

include::opsiconfiged.adoc[]

include::hwinvent.adoc[]

include::os-installation.adoc[]

include::softwareintegration.adoc[]

include::general-notes.adoc[]

include::more.adoc[]