////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      05.02.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



[[firststeps-software-deployment-product-tests]]
= Rolling out Existing Products

To deploy software to clients, the xref:clients:windows-client/windows-client-agent.adoc[Client Agent] must be installed on each client.

TIP: If you xref:clients:windows-client/os-installation.adoc[install Windows] through opsi, the client agent will be automatically installed.

This chapter describes the procedure for distributing software to clients via the xref:clients:windows-client/opsiconfiged.adoc[Management Interface *opsi-configed*]. The standard products available for Windows clients include the following:

// cspell: ignore swaudit, hwaudit

* `opsi-client-agent`
* `swaudit`
* `hwaudit`
* `opsi-configed`
* `opsi-auto-update`
* `opsi-client-kiosk`
* `opsi-setup-detector`


include::common:partial$firststeps-swdp-product-tests-configed.adoc[]

include::common:partial$firststeps-swdp-product-tests-inventory.adoc[]

