////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      22.01.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-winclient-introduction]]
= Windows Client

This guide focuses on managing Windows clients in opsi environments, covering several key aspects:

* Automatic OS Installation
* Adding and integrating Windows computers into opsi
(installation of the xref:clients:windows-client/windows-client-agent.adoc[Client Agent])
* Deploying standard software on the opsi server
* Deploying standard software on Windows clients
* Creating opsi packages and packaging your own software
* Notes on Windows clients
  ** Special commands for Windows
  ** Directories you may use

NOTE: To manage Windows clients, it's essential to have an xref:server:overview.adoc[opsi Server] already installed and operational.

[[opsi-winclient-convention]]
include::ROOT:partial$conventions.adoc[]
