////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      22.02.2019
:Revision:  4.1
:toclevels: 6


include::../common/opsi_terms.asciidoc[]


[[opsi-manual-troubleshooting]]
== Troubleshooting

Usually we first see the symptons of a problem and this is what
makes us realise something went wrong.
Our next step should be finding out where the problem lies.
Once we know what our problem is we can attempt to fix it.

While checking where the problem comes from it is a good idea to revisit
the relevant chapters and double check your configuration.
Spending hours debugging a problem to then find out you made a typo can
be frustrating.

When going through the following suggestions you should continously try
to reproduce the error.
With a little bit of luck it will disappear.


[[opsi-manual-troubleshooting-general-updates]]
=== Install updates

Usually an easy first step is to make sure that you are using the latest
versions when encountering problems.
By switching to a newer version you increase the chance that an existing
problem has been fixed in the meantime.

Whenever updates for opsi are released an information is posted on the link:https://forum.opsi.org/[forums].
Along with the release information changelogs are posted that can help you
identify what version of a component contains the fix relevant to your problem.

On a Debian-based system you can install updates for your OS with the following commands:
[source,prompt]
----
apt update
apt dist-upgrade
----

Afterwards you should update your opsi packages:
[source,prompt]
----
opsi-package-updater -v update
----


[[opsi-manual-troubleshooting-general-opsi]]
=== opsi configuration

You should make sure that your opsi server has the current configurations
applied and that access rights are set as expected.

[source,prompt]
----
opsi-setup --set-rights
opsi-setup --init-current-config
----


If you are using the MySQL backend make sure that all migrations are applied:
[source,prompt]
----
opsi-setup --update-mysql
----

As a last step you should restart the opsi service so that they use
the new configurations.
[source,prompt]
----
systemctl restart opsiconfd.service
systemctl restart opsipxeconfd.service
----

In some cases the restart of a server may also work wonders.


[[opsi-manual-troubleshooting-general-logging]]
=== Logging

To figure out what goes wrong a look into the logs is often the best route
to follow.
By default most opsi components log information that is useful during runtime
but for finding out the cause of a problem you often have to increase the loglevel.
After increasing the loglevel try to reproduce the previous behaviour and then look into the logs.

Once you finished solving your problem do not forget to reduce the loglevel
back to defaults because high loglevel may slow down your servers or result
in using up a lot of unwanted disk space.
