////
; Copyright (c) uib gmbh (www.uib.de)
; Cette documentation appartient à uib
; et publié sous licence Creative Commons by-sa allemande
; voir:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; anglais:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; crédits: http://www.opsi.org/credits/
////


:Author:    OpenSides sprl
:Email:     opsi@opensides.be
:Date:      18.10.2012
:Revision:  4.0.1
:toc:
:numbered:
:website: http://opsi.org/fr


include::../common/opsi_terms.asciidoc[]


[[opsi-manual-backup]]
== Sauvegarde d'opsi

[[opsi-manual-backup_introduction]]
=== Introduction

Votre serveur opsi devrait être sauvegardés (comme tout autre système important). Ce chapitre montre ce qu'il faut sauvegarder et comment.

Et, bien sûr, comment restaurer.

[[opsi-manual-backup_prerequisits]]
=== Conditions préalables à la sauvegarde

Vous devez exécuter commande `opsi-backup` comme 'root'.

Vous devez installer le programme _mysqldump_ avant de pouvoir utiliser `opsi-backup` dans le cadre du 'backend mysql'. Habituellement, ce programme fait partie des paquets du client mysql.

[[opsi-manual-backup-quickstart]]
=== Mise en route rapide

Créer une sauvegarde:

[source, shell]
----
opsi-backup create opsi_backup.tar.bz2
----
Crée une sauvegarde des backends utilisés et toutes les données de configuration dans le répertoire courant avec le nom `opsi_backup.tar.bz2`.

Restaurer une sauvegarde:
[source, shell]
----
opsi-backup restore --backends=all --configuration opsi_backup.tar.bz2
----
Restaure les données à partir du fichier de sauvegarde `opsi_backup.tar.bz2`, qui est recherché dans le répertoire courant.

[[opsi-manual-backup_parts-of-opsi]]
=== Éléments de base d'opsi

OPSI peut être divisé en cinq parties différentes qui peuvent être sauvegardés ou pas. L'emplacement où se trouvent ces parties peut varier (selon la distribution Linux, la version et la configuration).

[[opsi-manual-backup_config-part]]
==== La configuration d'opsi

La partie la plus importante de OPSI est la configuration. Vous la trouverez dans `/etc/opsi`.

Cette partie sera sauvegardé par `opsi-backup`.

[[opsi-manual-backup_backend-parts]]
==== Les backends Opsi

Les données sur les clients gérés et les produits peuvent être stockées dans différents backends. Les backends les plus importants sont:

.backends opsi
[options="header"]
|==========================
|Backend|Description
|file-Backend|backend basé sur les fichiers (backend par défaut)
|mysql-Backend|backend basé sur MySQL (depuis opsi 4 pour toutes les données de configuration)
|ldap| Stocker les données de configuration dans l'annuaire ldap
|univention|backend LDAP spécial pour les serveurs d'entreprise Univention
|dhcp|Backend spécial qui est utilisé en combinaison avec un dhcpd du {opsi-server}
|==========================

Des backends différents peuvent être utilisés à des fins différentes en même temps. Donc, vous devriez jeter un oeil à `/etc/opsi/backendManager/dispatch.conf` pour voir quels backends vous utilisez.

Cette partie sera sauvegardé par `opsi-backup`.

[[opsi-manual-backup_depotfiles-parts]]
==== dépôt de partage opsi

Dans le 'dépôt de partage opsi' Vous trouverez les fichiers d'installation des logiciels à installer sur les clients par opsi. Les répertoires qui contiennent ces fichiers (produits Localboot et produits netboot) sont situés dans `/opt/pcbin/install` ou `/var/lib/opsi/depot`.

Selon le nombre des systèmes d'exploitation, pilotes, logiciels et ainsi de suite qui se trouvent ici, cette partie pourrait être de grande taille.

Cette partie *ne* sera *pas* sauvegardé par `opsi-backup`.

Donc, si vous voulez sauvegarder cette partie, vous pouvez utiliser 'rsnapshot' ou d'autres utilitaires de sauvegarde.

[[opsi-manual-backup_workbench-parts]]
==== opsi work bench

'opsi work bench' est le lieu qui est utilisé pour créer ses propres paquets. Il est généralement situé dans `/home/opsiproducts` et exportés comme partage Samba 'opsi_workbench'. Puisque ce répertoire contient votre propre travail, il doit être sauvegardé.

Cette partie *ne* sera *pas* sauvegardé par `opsi-backup`.

Donc, si vous voulez sauvegarder cette partie, vous pouvez utiliser 'rsnapshot' ou d'autres utilitaires de sauvegarde.

[[opsi-manual-backup_repository-parts]]
==== dépôt opsi

Le répertoire `/var/lib/opsi/repository` est utilisé pour stocker les paquets opsi, qui sont téléchargés via `opsi-product-updater` ou qui sont installés par `opsi-package-manager` lorsque vous utilisez l'option `-d`.

Cette partie *ne* sera *pas* sauvegardé par `opsi-backup`.

Donc, si vous voulez sauvegarder cette partie, vous pouvez utiliser 'rsnapshot' ou d'autres utilitaires de sauvegarde.

[[opsi-manual-backup-cli]]
=== Le logiciel `opsi-backup`

`opsi-backup` est un programme en ligne de commande qui facilite la création et la restauration des sauvegardes de données opsi.

Les commandes de base sont +create+, +restore+ et +verify+. +
L'option +--help+ affiche des informations sur les options de ligne de commande. Utilisez aussi +<command> --help+ (ex. `opsi-backup create --help`) pour obtenir des informations sur les options de la commande.

[source, shell]
----
opsi-backup --help
----

L'utilitaire `opsi-backup` stocke les données de configuration et le backend dans presque le même format auquel ils ont été trouvés sur le serveur. *Donc, vous ne pouvez pas restaurer ces données sur un serveur qui utilise d'autres backends, ou dispose d'autres versions d'opsi ou est d'une autre manière différente en ce qui concerne la structure des données opsi.*

`opsi-backup` crée toujours une sauvegarde complète. Il n'y a pas de support pour les sauvegardes incrémentielles ou différentiel.


WARNING: Remarquez que `opsi-backup` *ne* crée *pas* de sauvegarde de: +
* <<opsi-manual-backup_depotfiles-parts,'opsi depot share'>>
* <<opsi-manual-backup_workbench-parts,'opsi work bench'>>
* <<opsi-manual-backup_repository-parts, 'opsi repository'>>


`opsi-backup` crée un fichier de sauvegarde, dans le format compressé tar. Donc vous pouvez accéder aux données à l'aide d'autres outils standard.

WARNING: Un fichier de sauvegarde créé par `opsi-backup` peut contenir un mot de passe, touches de raccourci et d'autres données liées à la sécurité. Donc, assurez-vous de stocker les fichiers de sauvegarde dans un endroit sûr.

[[opsi-manual-backup-create]]
==== Créer une sauvegarde

Pour créer une sauvegarde utilisez `opsi-backup create`. +
Cette commande (sans options supplémentaires) créera une sauvegarde de toutes les données de configuration et de tous les backends utilisées. Le fichier de sauvegarde sera stocké dans le répertoire courant avec un nom généré automatiquement. +
Pour obtenir des informations sur les options possibles de +create+ appelez +
`opsi-backup create --help`

[source, shell]
----
opsi-backup create
opsi-backup create --help
usage: opsi-backup create [-h] [--flush-logs]
                          [--backends {file,mysql,dhcp,auto,all}]
                          [--no-configuration] [-c [{gz,bz2,none}]]
                          [destination]

positional arguments:
  destination           Destination of the generated output file. (optional)

optional arguments:
  -h, --help            show this help message and exit
  --flush-logs          Causes mysql to flush table logs to disk before the
                        backup. (recommended)
  --backends {file,mysql,dhcp,auto,all}
                        Select a backend to backup or 'all' for all backends.
                        Can be given multiple times. (Default: auto)
  --no-configuration    Backup opsi configuration.
  -c [{gz,bz2,none}], --compression [{gz,bz2,none}]
                        Sets the compression format for the archive (Default:
                        bz2)
----

Vous pouvez donner le répertoire cible ou le chemin complet vers le fichier de sauvegarde en option pour `opsi-backup create`. Si l'option donnée est un nom de fichier, la sauvegarde sera créé dans ce fichier - les fichiers existants seront écrasés. Si l'option est un dossier, le fichier de sauvegarde sera créé dans ce répertoire avec un nom de fichier généré en utilisant le motif: +<nom d'hôte>_<version d'opsi>_<date>_<heure>+

[source, shell]
----
opsi-backup create /mnt/backup/opsi_backup.tar.bz2
opsi-backup create /mnt/backup/
----

Les autres options pour +create+ sont:

* +--backends {file,mysql,dhcp,all,auto}+ +
est utilisé pour sélectionner les backends qui doivent être inclus dans la sauvegarde. Vous pouvez donner cette option plusieurs fois. +
L'option `--backends=all` comprend tous les backends supportés. +
La valeur par défaut est `--backends=auto`, qui signifie que `opsi-backup` lit le fichier de configuration `/etc/opsi/backendManager/dispatch.conf` et sauvegarde tous les backends supportés utilisés dans cette configuration.
Les backends supportés sont: +mysql+, +file+, +dhcp+
[source, shell]
----
opsi-backup create --backends=file --backends=mysql
opsi-backup create --backends=all
----
TIP: Si vous utilisez un backend pas pris en charge (comme 'ldap'), vous pouvez utiliser `opsi-convert` pour convertir vos données vers un backend qui est pris en charge par la sauvegarde.

* +--no-configuration+ +
Exclut kes fichiers <<opsi-manual-backup_config-part,opsi configuration>> de la sauvegarde.
[source, shell]
----
opsi-backup create --no-configuration
----

* +-c [{gz,bz2,none}], --compression [{gz,bz2,none}]+ +
Spécifie la méthode de compression. +none+ signifie 'pas de compression'. +
La valeur par défaut est +bz2+.

[source, shell]
----
opsi-backup create -c bz2
----

* `--flush-logs` +
La sauvegarde du backend mysql utilise la commande 'mysqldump'. Cela signifie que toutes les données connues par la base de données sont sauvegardés, peu importe si elles sont sur le disque ou encore seulement dans la mémoire. Cela signifie, que votre sauvegarde peut être plus actuel que vos fichiers de base de données (ce qui n'est vraiment pas un problème). +
Si vous voulez vous assurer que la base de données stocke les données sur le disque avant de commencer la sauvegarde, vous pouvez utiliser l'option `--flush-logs`. Mais avant que vous pouvez le faire, vous devez accorder les privilèges nécessaires pour le RELOAD à l'utilisateur de la base de données opsi, ou votre sauvegarde échouera. Voir: http://dev.mysql.com/doc/refman/5.5/en/privileges-provided.html#priv_reload[RELOAD]. +
Il faut donc utiliser cette option que si vous savez vraiment ce que vous faites.

[source, shell]
----
opsi-backup create --backends=mysql --flush-logs
----

*Exemple*
[source, shell]
----
opsi-backup create --no-configuration --backends=all opsi_backup.tar.bz2
----

[[opsi-manual-backup-archive]]
==== Archivez vos fichiers de sauvegarde
`opsi-backup` n'a pas de fonctionnalités pour archiver les fichiers de sauvegarde créés. Donc, vous devez le faire par vous-même (ex. en utilisant un outil de sauvegarde de fichiers). +
Si vous faites appel à `opsi-backup` avec un répertoire cible en option, gardez à l'esprit que chaque appel crée un nouveau fichier de sauvegarde complète et aucun fichier plus ancien sera effacé.

[[opsi-manual-backup-verify]]
==== Vérifier une sauvegarde
La commande `opsi-backup verify` est utilisé pour tester l'intégrité du fichier de sauvegarde créé.
L'aide pour la commande `opsi-backup verify` est disponible par l'option de commande +--help+.

*Exemple*
[source, shell]
----
opsi-backup verify opsi_backup.tar.bz2
opsi-backup verify --help
usage: opsi-backup verify [-h] file [file ...]

required arguments:
  file        The backup archive to verify.

optional arguments:
  -h, --help  shows this help message and then exits
----

TIP: Si vous appelez `opsi-backup verify` depuis la console, il peut être utile d'activer les messages de sortie standard en utilisant l'option `-v`: `opsi-backup -v verify opsi_backup.tar.bz2`

[[opsi-manual-backup-restore]]
==== Restauration à partir d'un fichier de sauvegarde
Pour restaurer les données à partir d'un fichier de sauvegarde, utilisez la commande `opsi-backup restore`.

Vous devez donner le chemin vers le fichier de sauvegarde en tant que paramètre.

La commande `opsi-backup restore --help` donne des informations sur les options de la commande `restore`.
[source, shell]
----
opsi-backup restore --help
usage: opsi-backup restore [-h] [--backends {file,mysql,dhcp,auto,all}]
                           [--configuration] [-f]
                           file

required arguments:
  file                  The backup archive to restore data from.

optional arguments:
  -h, --help            show this help message and exit
  --backends {file,mysql,dhcp,auto,all}
                        Select a backend to restore or 'all' for all backends.
                        Can be given multiple times.
  --configuration       Restore opsi configuration.
  -f, --force           Ignore sanity checks and try to apply anyway. Use
                        with caution! (Default: false)
----

`opsi-backup restore` possède les options suivantes:

* +--backends {file,mysql,dhcp,auto,all}+ +
Spécifie le backend à restaurer. Cette option peut être utilisée plusieurs fois. +
L'option `--backends=all` spécifie que les données de tous les backends qui se trouvent dans le fichier de sauvegarde doivent être restaurés. +
La valeur par défaut est `--backends=auto`. Cela permet de restaurer les données à partir du fichier sauvegarde vers le système en utilisant les données de configuration actuelles de `/etc/opsi/backendManager/dispatch.conf`.

[source, shell]
----
opsi-backup restore --backends=file --backends=mysql opsi_backup.tar.bz2
opsi-backup restore --backends=all opsi_backup.tar.bz2
----
WARNING: Si vous avez modifié la configuration de votre backend depuis que vous avez créé la sauvegarde, pas ou pas toutes les données seront restaurés. Dans ce cas, vous devez utiliser l'option `--backends=all` et ensuite convertir les données restaurées dans le backend effectivement utilisés à l'aide de `opsi-convert`.

* +--configuration+ +
Indique que <<opsi-manual-backup_config-part,opsi configuration>> doit être restauré. +
Ce n'est pas l'option par défaut de la commande +restore+.
[source, shell]
----
opsi-backup restore --configuration opsi_backup.tar.bz2
----


* +-f, --force+ +
Pour éviter d'endommager les données `opsi-backup` fait une vérification de la compatibilité du système (version opsi, Version OS, nom de l'hôte et Nom de domaine) avant de restaurer les données et s'arrête si le système actuel diffère du système ou le fichier de sauvegarde a été créé. Grâce à cette option vous pouvez outrepasser cette vérification.

[source, shell]
----
opsi-backup restore -f opsi_backup.tar.bz2
----

*Exemple*
[source, shell]
----
opsi-backup restore --configuration --backends=all opsi_backup.tar.bz2
----


