////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; Until we found a better license:
; All rights reserved.
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      05.05.2011
:Revision:  4.0.1
:toclevels: 6

include::../common/opsi_terms.asciidoc[]


[[opsi-manual-overview]]
== Vue d'ensemble d'opsi

Les outils de distribution de logiciels automatisés et d'installation du système d'exploitation sont
des outils importants et nécessaires pour la normalisation, la maintenabilité et la réduction des coûts dans des grands réseaux de PC. Normalement, l'application de ces outils s'accompagne d'importantes redevances, alors que OPSI comme un logiciel open source permet l'économie explicite.  Les dépenses seront que pour les services rendus, comme conseil, formation et maintenance, et peut-être à faible taux de co-financement, si vous souhaitez utiliser certains de ces modules non libres.

Bien que le logiciel lui-même et les manuels sont gratuits, le processus d'introduction d'outil de distribution de logiciels est encore un investissement. Pour obtenir le bénéfice, sans retours en arrière, et sans une longue periode d'apprentissage, l'éducation des administrateurs système par un partenaire professionnel est recommandé. uib offre tous ces services autour d'opsi.

Le système opsi développé par uib dépend de serveurs linux. Ils sont utilisés pour
l'installation et la maintenance à distance du système d'exploitation client et des paquets logiciel client ("PC-Server-Integration"). Il est basé autant que possible sur des outils disponibles gratuitement (GNUtools, SAMBA etc.). Le système complet tous ensemble est nommé opsi (Open PC-Server-Integration) et avec sa configurabilité est une solution très intéressante pour les difficultés d'administration d'un parc informatique important.

[[opsi-manual-overview-experience]]
=== Expérience

opsi est dérivé d'un système, qui est en usage depuis le milieu des années 90 avec plus de 2000 clients-PC dans des endroits différents d'une autorité gouvernementale. Depuis ce temps il a été continuellement adaptée à l'évolution du système d'exploitation Microsoft. En tant que produit, opsi est désormais accessible pour un large éventail d'utilisateurs intéressés.

Vous pouvez trouver une vue d'ensemble géographique des installations OPSI sur link:http://www.opsi.org/fr/opsi-map[opsi map].


[[opsi-manual-overview-features]]
=== fonctionnalités d'opsi

Les principaux éléments de opsi sont :

* Distribution automatique des logiciels
* Installation automatique du système d'exploitation
* Inventaire hardware et software avec historique
* Contrôle confortable via l'interface de gestion opsi
* Prise en charge de multiples serveurs de dépôt


[[opsi-manual-overview-extensions]]
=== Extensions opsi

* Gestion des licences
* MySQL-Backend
* Utilisation de groupes de clients hiérarchique (Treeview)
* Sélection dynamiques du serveur de dépôt
* Logiciels sur demande
* Prise en charge de clients derrière des connexions lentes (WAN Extension)
