////
; Copyright (c) uib gmbh (www.uib.de)
; Cette documentation appartient à uib
; et publié sous licence Creative Commons by-sa allemande
; voir:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; anglais:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    OpenSides sprl
:Email:     opsi@opensides.be
:Date:      14.02.2013
:Revision:  4.0.3
:toclevels: 6


include::../common/opsi_terms.asciidoc[]

[[opsi-manual-silentinstall]]
== La fonctionnalité opsi 'SilentInstall'

La fonctionnalité opsi 'SilentInstall' fournit aux administrateurs la possibilité d'installer un logiciel sur un client sans que l'utilisateur connecté soit dérangé. Ce chapitre décrit les caractéristiques de cette fonctionnalité et propose des lignes directrices pour la configuration de cette nouvelle méthode d'installation.

[[opsi-manual-silentinstall-preconditions]]
=== Conditions préalables à l'installation en mode silencieux

Pour utiliser cette fonctionnalité, est requise la version opsi 4.0.3. ou au-dessus, et pour '{opsi-client-agent}' est requise la version 4.0.3.1 ou au-dessus.

[[opsi-manual-silentinstall-overview]]
=== Vue d'ensemble de la fonctionnalité SilentInstall

La méthode d'installation silencieuse offre la possibilité d'installer une liste prédéfinie de produits sur un client, sans que l'utilisateur ait à interrompre son travail.
Contrairement à l'installation onDemand (l'installation poussée), la méthode SilentInstall n'affiche rien sur le bureau de l'utilisateur.

Tous les affichages sont supprimées, et ne seront pas vus sous tous les bureaux. Bien sûr, cette fonctionnalité porte un certain risque. En cas de problème, ex. une erreur de syntaxe du script '{opsi-winst}', il n'y a aucun moyen d'interagir avec le processus d'installation, aucune boîte de dialogue sera présentés. Donc cela se traduirait par le fait que le traitement de l'événement par '{opsi-winst}' ne s'achève pas, et donc, aucun autre événement ne sera plus exécuté. Pour éviter ce "Scénario le plus défavorable", le temps d'installation maximale est limitée par un délai d'attente dans la configuration. Cette valeur de temporisation peut être adapté dans le cas d'une installation prolongée. Pour plus d'informations, voir le chapitre sur la configuration.

Une autre possibilité très importante de cette fonctionnalité est la liste prédéfinie de produits destinés à être installés en mode silencieux. Un contact avec le service est établi, mais différemment de la procédure habituelle, les ActionRequests proposée par le service sont ignorés. La liste des logiciels à installer est définie par une configuration de '{opsi-client-agent}' configuration. L'action "setup" sera exécutée pour tous les produits figurant sur cette liste sans qu'ils soient mis à setup. Comme d'habitude, après le traitement du script de configuration, le script de mise à jour également sera exécuté, si celui-ci existe. +Les dépendances de produits ne seront pas résolues.+ Donc, aucun produit contenant des dépendances d'autres produits doit être installé par la fonctionnalité SilentInstall, ou sinon tous les produits de la liste de dépendance doivent être ajoutés à la liste des produits SilentInstall. Comme d'habitude, le processus d'installation se termine en envoyant l'état d'installation et les fichiers de log de l'installation au service.
En résumé, il est recommandé d'utiliser le SilentInstall que pour les produits qui satisfont aux exigences suivantes:

* petits paquets ou installations singulières
* peu de charge du système: certaines installations de logiciels, donc la plupart par exemple des installations MSI, il demandent pendant l'installation la plupart des ressources client. Il pourrait en résulter un mauvais rendement du système pour l'utilisateur.
* installable dans un laps de temps fixe: le délai d'attente par défaut pour cet événement est de 300 secondes. Si le processus d'installation n'est pas terminée dans le délai, le processus '{opsi-winst}' sera terminé et donc l'événement pourra être complété.
* pas de redémarrage nécessaire: sde logiciels demandant un redémarrage ne devrait pas être installés à partir du SilentInstall. Avec la configuration par défaut, l'événement est configuré pour ne pas traiter toutes les demandes de redémarrage. Sans cette configuration de sécurité '{opsi-client-agent}' pourrait redémarrer le client sans aucun avertissement à l'utilisateur. Cela pourrait entraîner une perte de données si il y a un utilisateur connecté. Il pourrait en résulter un logiciel inutilisable installé par SilentInstall sans redémarrage.

Dans la configuration par défaut swaudit et hwaudit sont installés par ce procédé. Les produits d'inventaire de OPSI, il satisfont à toutes les exigences ci-dessus et sont donc applicables pour cette méthode. Avec la configuration par défaut, les inventaires matériels et logiciels OPSI sont générés à la demande, sans la nécessité d'établir la demande d'action d'installation avec '{opsi-configed}'. Avec cette méthode, les informations d'inventaire peuvent être générés en temps réel. Également applicable à tout produit de configuration, qui effectuent des réparations automatiques ou des restaurations de correctifs client.

[[opsi-manual-silentinstall-fireEvent]]
=== Exécution de l'installation silencieuse

Cet événement ne se déclenche pas automatiquement comme les autres événements. Il y a donc deux manières de réaliser cet événement.

La première voie est de déclencher l'événement à partir du webservice opsi, comme par exemple:

[source,shell]
----
opsi-admin -d method hostControl_fireEvent silent_install client.domain.local
----

Donc cette commande est scriptable, et peut être utilisé dans des scripts qui peut être combiné avec un 'at-job' pour planifier l'exécution de l'événement.

Comme alternative, l'événement peut être déclenché par un événement programmé, après un certain laps de temps. La configuration par défaut pour cet événement est de 6 heures. Cette valeur suppose qu'un poste de travail est habituellement utilisé pendant 8 heures. Donc l'événement sera exécuté une fois par jour au bout de six heures de temps de fonctionnement. Pour plus d'informations sur la configuration et l'activation de cet événement, voir le chapitre suivante.

[[opsi-manual-silentinstall-configuration]]
=== Configuration de la fonctionnalité opsi: 'SilentInstall'

Ce chapitre traite de la configuration par défaut de cette fonctionnalité. Par défaut 'opsiclientd.conf' possède événement SilentInstall. Cette liste indique uniquement les options importantes:

événement standard SilentInstall:
[source,ini]
----
[event_silent_install]
process_shutdown_requests = false
action_processor_productIds = swaudit,hwaudit
action_processor_command = %action_processor.command% /productlist %action_processor_productIds% /silent
action_processor_desktop = winlogon
action_processor_timeout = 300
----

* action_processor_productIds
    - Cette option est une nouvelle propriété importante pour le contrôle des événements. Pour tous les événements qui exécutent des actions de produits, cette option permet de définir une liste de produits. La liste des produits doit être donnée sous forme de liste séparée par des virgules.
* process_shutdown_request = false
    - Cette configuration supprime les demandes de redémarrage de '{opsi-winst}'.
* action_processor_command
    - Cette configuration prépare l'appel à '{opsi-winst}'.
* action_processor_desktop
    - Cette option définit le bureau pour afficher l'interface graphique '{opsi-winst}'.
* action_processor_timeout
    - Cette option définit le délai d'attente pour terminer le processus '{opsi-winst}'.

Le deuxième événement est l'événement de temporisation, qui déclenche l'événement après un certain laps de temps:

Événement de temporisation par défaut pour SilentInstall
[source,ini]
----
[event_timer_silentinstall]
super = silent_install
type = timer
active = false
interval = 21600
----

* super
    - Cette option définit à partir de quel événement hériter les propriétés. Par défaut il hérite de l'événement silent_install.
* type
    - Cette option définit que l'événement est un Timer-Event.
* active
    - par défaut cet événement n'est pas actif. Pour l'activer, réglez cette option sur 'true'.
* interval
    - Cette option définit l'intervalle pour déclencher l'événement. La valeur par défaut est 6 heures, donc au bout de six heures de temps de fonctionnement l'événement est déclenché pour la première fois, puis tous les six autres heures. Donc cet intervalle devrait (comme n'importe quel intervalle de temporisation) ne pas être trop court, autrement, l'événement sera effectué la plupart du temps, en bloquant ainsi l'exécution d'autres actions. D'autre part, l'intervalle ne devrait pas être trop long, pour que '{opsi-client-agent}' soit exécuté tout ce temps, jusqu'à ce que l'événement est déclenché. Si le client ou '{opsi-client-agent}' sont toujours redémarrés avant que l'intervalle est écoulé, cet événement ne sera jamais déclenché.

En outre, l'événement SilentInstall pourrait être déclenché par un autre événement système, détectée par une demande WMI. Donc une option 'wql' peut être spécifiée. Comment spécifier l'option 'wql' doit être vu dans la section event_net_connection. Si l'option 'wql' est utilisée, l'événement doit être réglé sur 'active = false' par défaut, de sorte qu'il peut être activé suite à la demande.

Pour déclencher l'événement par un temporisateur, en général il suffit de définir un paramètre hôte. Donc, une configuration par défaut doit être d'abord créée. Dans ce cas, il suffit d'activer la temporisation de l'événement.

Pour créer l'option standard, les suivants '{opsi-config-objects}' doivent être créées par '{opsi-admin}'. Cette configuration peut être créé aussi par '{opsi-configed}':

[source,shell]
----
opsi-admin -d method config_createBool opsiclientd.event_timer_silentinstall.active "event_timer_silentinstall active" false
----

Donc, dans un premier temps, cet événement est désactivée pour tous les clients. Ensuite, l'événement peut être activé pour les clients individuels:

[source,shell]
----
opsi-admin -d method configState_create opsiclientd.event_timer_silentinstall.active silentclient.domain.de true
----

Pour définir les produits à installer, l'entrée suivante doit être définie.
Si, par exemple, au lieu de 'swaudit' et 'hwaudit' doit être installé le produit 'firefox', les entrées devraient être créée tel que décrit ci-dessus:

[source,shell]
----
opsi-admin -d method config_createUnicode opsiclientd.event_silent_install.action_processor_productIds "event_silent_install productIds" "swaudit,hwaudit"
----

Avec cette option par défaut pour tous les clients la liste des produits pour l'événement SilentInstall est défini sur swaudit et hwaudit. Pour modifier la liste des produits pour un seul client en 'firefox' exécutez la commande suivante:

[source,shell]
----
opsi-admin -d method configState_create opsiclientd.event_silent_install.action_processor_productIds client.domain.de "firefox"
----

Comme vous pouvez le voir, la liste des produits peut être différente pour chaque client.
