////
; Copyright (c) uib gmbh (www.uib.de)
; Cette documentation appartient à uib
; et publié sous licence Creative Commons by-sa allemande
; voir:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; anglais:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; crédits: http://www.opsi.org/credits/
////

:Author:    OpenSides sprl
:Email:     opsi@opensides.be
:Date:      15.10.2012
:Revision:  4.0
:toclevels: 6

include::../common/opsi_terms.asciidoc[]


[[opsi-manual-server]]
== Serveur opsi

[[opsi-manual-server-overview]]
===  Présentation

Les fonctionnalités d'un '{opsi-server}' peuvent être installés sur différents types de distributions Linux.

Il y a deux rôles différents qu'un '{opsi-server}' peut avoir:

* '{opsi-configserver}' +
Le '{opsi-configserver}' a le stockage central de données et fournit l'accès à ces données via le 'service web opsi'. Un '{opsi-configserver}' a normalement en plus le rôle de '{opsi-depotserver}'.

* '{opsi-depotserver}' +
Le '{opsi-depotserver}' n'a pas de stockage de données de configuration. Un '{opsi-depotserver}' stocke les fichiers d'installation dans un partage et fournit les services PXE / tftpboot pour les produits netboot.

Les exigences matérielles sont faibles. Le serveur OPSI peut également fonctionner comme une instance virtuelle, ex. vmware® (www.vmware.com) ou virtualbox (www.virtualbox.org).


[[opsi-manual-server-installation]]
===  Installation et mise en service

L'installation et le démarrage d'un {opsi-server} sont décrites dans le manuel 'getting started'.

[[opsi-manual-server-samba]]
===  Configuration Samba

Le serveur de dépôt opsi vous offre les partages réseau qui détient les informations de configuration et les paquets logiciels. Ces partages peuvent être montés par les clients. Pour les clients Windows les partages sont fournies par SAMBA (version 3.x).

Pour configurer votre samba en fonction des besoins de opsi (ou pour réparer) exécutez:
[source,prompt]
----
opsi-setup --auto-configure-samba
----

Après chaque changement de configuration de samba, vous devez recharger votre samba  (`/etc/init.d/samba reload`).

[[opsi-manual-server-opsiconfd]]
===  Le démon opsiconfd
'opsiconfd' est le démon centrale opsi (service).
'opsiconfd' fournit le 'service web opsi' et fait beaucoup plus des choses.
'opsiconfd' est configuré dans `/etc/opsi/opsiconfd.conf`.

[[opsi-manual-server-accounts]]
===  Comptes d'utilisateurs et groupes administratifs nécessaires

* Utilisateur 'opsiconfd' +
Le démon 'opsiconfd' s'exécute en tant que cet utilisateur.

* Utilisateur 'pcpatch' +
Cet utilisateur est utilisé par '{opsi-client-agent}' pour monter le 'dépôt de partage'.
Vous pouvez définir le mot de passe pour cet utilisateur avec +
`opsi-admin -d task setPcpatchPassword`.

* Groupe 'pcpatch' +
Le groupe 'pcpatch' a l'autorisation d'écriture sur plusieurs fichiers et vous aurez besoin d'être dans ce groupe afin de construire et d'installer des 'produits opsi'.

* Groupe 'opsiadmin' +
Les membres du groupe 'opsiadmin' sont autorisés à se connecter au service web d'opsi et peuvent utiliser par exemple l'éditeur de configuration 'opsi-configed'. Par conséquent, tous les administrateurs d'opsi doivent être membres du groupe 'pcpatch'.

Un utilisateur peut rejoindre le groupe 'opsiadmin' avec: 'addgroup <utilisateur> opsiadmin'.

[[opsi-manual-server-shares]]
===  Répertoire de partage nécessaires

* 'Depotshare' avec les fichiers d'installation ('opt_pcbin') +
Le dépôt de partage fournit tous les paquets logiciels qui peuvent être installés par le logiciel 'opsi-winst'. Le répertoire par défaut pour les paquets logiciels est '/opt/pcbin/install'. Dans ce répertoire chaque paquet logiciel a son propre répertoire sous le nom du paquet logiciel. Ces sous-répertoires contiennent les scripts d'installation et les fichiers spécifiques des paquets.

TIP: Le répertoire `/opt/pcbin/install` sera remplacé par le répertoire (LSB conformes) `/var/lib/opsi/depot`. Le partage 'opt_pcbin' sera remplacé par le partage en lecture seule 'opsi_depot'.

* Le répertoire de construction des paquets ('opsi_workbench') +
Dans /home/opsiproducts vous y trouverez l'endroit idéal pour créer de nouveaux paquets et à partir de là vous devriez installer les paquets avec opsi-package-manager.

* Partage avec les fichiers de configuration des backends ('opsi_config') +
Dans /var/lib/opsi vous trouverez les fichiers de configuration des backends.

[[opsi-manual-server-problem_management]]
===  la gestion des problèmes

Si vous avez des incidents en utilisant opsi, vous devriez vérifier la liste suivante ou plutôt exécuter les commandes suivantes. L'expérience a montré que la combinaison des commandes dans ce chapitre fixe la plupart des incidents.

* Vérifiez l'accessibilité et la charge de 'opsi-webservice': +
Appelez avec votre navigateur l'adresse URL: https://<server-ip>:4447/info. Si ne pouvez pas vous connecter, passez à l'étape suivante. Si vous pouvez vous connecter: vérifier la charge de 'opsi-webservice' et vérifiez l'espace libre sur le disque (défiler vers le bas dans la page d'information).

* Vérifiez que les démons sont en marche et redémarrez-les:
[source,prompt]
----
ps -ef | grep opsiconfd
ps -ef | grep opsipxeconfd
/etc/init.d/opsiconfd restart
/etc/init.d/opsipxeconfd restart
----

* Initialiser la configuration
[source,prompt]
----
opsi-setup --init-current-config
----

* Définissez les droits pour les fichiers et les répertoires importants dans opsi:
[source,prompt]
----
opsi-setup --set-rights
----

* Nettoyez le backend
[source,prompt]
----
opsi-setup --cleanup-backend
----

* Vérifiez que samba est en marche:
[source,prompt]
----
ps -ef | grep mbd
----
Il doit exécuter au moins un processus nmbd et un processus smbd. +
Pour redémarrer samba:
[source,prompt]
----
/etc/init.d/samba restart
----
ou
[source,prompt]
----
service nmbd restart
service smbd restart
----

* Définissez le mot de passe pcpatch:
[source,prompt]
----
opsi-admin -d task setPcpatchPassword
----
