////
; Copyright (c) opensides sprl (www.opensides.be)
; Cette documentation appartient à opensides
; Until we found a better license:
; All rights reserved.
; credits: http://www.opsi.org/credits/
////

:Author:    opensides sprl
:Email:     opsi@opensides.be
:Date:      22.01.2013
:Revision:  1.0
:toclevels: 6


include::../common/opsi_terms.asciidoc[]

[[opsi-on-shutdown]]
== Installation d'opsi lors de l'arrêt

[[opsi-on-shutdown-introduction]]
=== Introduction

Habituellement, l'installation des paquets de logiciels opsi sur le client est lancé au démarrage du client. Ainsi, l'utilisateur doit attendre que l'installation se termine, avant que l'ouverture de session utilisateur soit autorisée. Il pourrait être utile de faire la plupart de l'installation du logiciel lorsque le client va arrêter.

Le module opsi pour l'installation lors de l'arrêt apporte cette fonctionnalité. Les clients sélectionnés peuvent être configurés pour faire l'installation à l'arrêt.

[[opsi-on-shutdown-prerequires]]
=== Conditions préalables à l'installation lors de l'arrêt

Le module opsi d'installation lors de l'arrêt peut être utilisé pour des clients à partir de *Windows XP*. Les composants nécessaires font partie du paquet opsi '{opsi-client-agent}'. Actuellement, ce module est en projet de cofinancement. Donc, il nécessite un fichier spécial des modules pour déverrouiller cette fonctionnalité. Pour plus de détails sur les projets en cofinancement voir <<opsi-manual-modules>> et le lien internet
link:https://www.opsi.org/fr/product/extensions-dopsi/[projets en co-financement].

Le paquet '{opsi-client-agent}' doit être à la version 4.0.2.3-2 ou supérieur et `opsiclientd` à la version 4.0.75 ou supérieur.

Les cas suivants sont des restrictions et contraintes techniques:

* Extension WAN: le module d'installation lors de l'arrêt, n'est actuellement pas disponible pour les clients fonctionnent avec l'extension WAN. L'utilisation de l'extension WAN pour un client, sous certaines conditions, nécessite d'utiliser les fichiers de configuration locaux, qui gênent la manipulation de l'état ​​de l'installation sur le mécanisme d'arrêt.

* Les stratégies de groupe: une partie du mécanisme d'installation lors de l'arrêt est basé sur des scripts d'arrêt par la stratégie de groupe locale. D'autres stratégies de groupe peuvent remplacer ces configurations locales. Dans ce cas, la configuration requise pour l'exécution de scripts d'arrêt devraient être inclus dans vos stratégies de groupe prise en charge. Voir <<opsi-on-shutdown-concept-shutdownscript>> pour les configurations requises.

* Windows Home Edition: Windows Home ne fournit pas le nécessaire mécanisme de script d'arrêt via la stratégie de groupe locale. Par conséquent, l'installation lors de l'arrêt ne peut pas être utilisé pour Windows Home Edition.

* Windows 2000: Pour les clients Windows 2000 le délai d'attente maximal pour les scripts d'arrêt est de 10 minutes. Après 10 minutes, l'installation est interrompue par le système Windows. Par conséquent, l'installation lors de l'arrêt ne peut pas être utilisé pour les clients Windows 2000.


[[opsi-on-shutdown-activate]]
=== Activation de l'installation lors de l'arrêt

Les composants requis pour l'installation lors de l'arrêt font partie de l'actuel paquet `opsi-client-agent`. Pour le déverrouiller, un fichier `modules` valide doit être obtenue et copié sur le serveur.

En suite, l'installation lors de l'arrêt peut être configuré pour les clients appropriés (voir <<opsi-on-shutdown-prerequires>>) en établissant pour `opsi-client-agent` la propriété du produit `on_shutdown_install=on` et en fixant `opsi-client-agent=setup`.

Ça y est. Tout le reste de la configuration est effectuée par le paquet `opsi-client-agent` lors de l'installation.

L'installation lors de l'arrêt se fait en plus de l'installation au démarrage. Habituellement, c'est le meilleur moyen de s'assurer que les clients ont toujours les mises à jour de sécurité actuels installé, même si le client était éteinte pendant une longue période (lorsque l'utilisateur est en vacances par exemple).
Si nécessaire, l'installation au démarrage par défaut peut être désactivée, voir <<opsi-on-shutdown-config>>. Les installations en cours se poursuivent tout de même, ce qui est commandé par la condition `installation_pending`.

Le système Windows lors de l'arrêt du système ne distingue pas l'arrêt du redémarrage. L'installation lors de l'arrêt est lancé dans les deux cas et il n'est pas possible de les distinguer lors de l'installation. En outre, il n'est pas possible de transformer un arrêt du système dans un redémarrage (ou vice versa). Ainsi, en cas d'un arrêt du système, toutes les autres installations sont poursuivies au prochain démarrage du système.


[[opsi-on-shutdown-concept]]
=== Concept technique

Les explications qui suivent sont pour la compréhension de la conception technique et les interactions entre les composants en cas de configurations particulières ou des états d'erreur. Habituellement toutes les configurations requises sont effectuées par le paquet `opsi-client-agent`.

[[opsi-on-shutdown-concept-overview]]
==== Vue d'ensemble

Le module d'installation lors de l'arrêt repose sur plusieurs éléments du système. Une partie importante est le mécanisme du script d'arrêt de Windows via la stratégie de groupe locale. Les scripts d'arrêt permettent d'exécuter des tâches à l'arrêt, lorsque l'utilisateur est déjà déconnecté, mais tous les services du système sont encore disponibles.

Le script d'arrêt effectue une tâche opsi, qui déclenche la fonction système opsi '{opsiclientd}' pour démarrer le processus d'installation et attendre la fin de la tâche. Ainsi, le système attend que le processus d'installation se termine puis s'arrête. Lors de la manipulation d'arrêt, le système Windows ne distingue pas l'arrêt du redémarrage, donc l'installation est déclenché dans les deux cas.

Le service client opsi '{opsiclientd}' est configuré pour traiter l'action `on_shutdown`, qui commence le processus d'installation. En cas de redémarrages requis, la condition préalable `installation_pending` permet le contrôle du processus. Si, lors de l'installation, un redémarrage est nécessaire avant de poursuivre l'installation, la condition préalable `installation_pending` mène à poursuivre l'installation au prochain démarrage du système (même si l'installation à `gui_startup` est désactivée). Pendant l'état de `installation_pending`, aucune autre installation à l'arrêt ne sera déclenché, sinon, il n'y aurait pas de redémarrage entre l'installation au démarrage et l'installation lors de l'arrêt. Donc, jusqu'à ce que l'installation actuelle soit terminée, l'installation lors de l'arrêt est supprimé par la mise en `event_on_shutdown{installation_pending}`.

Le chapitre suivant donne quelques détails supplémentaire sur l'installation lors de l'arrêt.

[[opsi-on-shutdown-concept-shutdownscript]]
==== Installation par script d'arrêt

Au travers de spéciales entrées de registre, la stratégie de groupe locale est configuré pour effectuer un script d'arrêt opsi, ce qui déclenche le processus d'installation. Les entrées du registre utilisées par `opsi-client-agent` sont les mêmes qu'en utilisant l'éditeur de stratégie de groupe `gpedit.msc`.

Ceci est la façon de configurer le script d'arrêt à l'aide de l'éditeur de stratégie de groupe `gpedit.msc`:

* Stratégie d'ordinateur local
* Configuration de l'ordinateur
* Paramètres Windows
* Scripts (Démarrage/Arrêt)
* Arrêt
* Scripts - Ajout - Parcourir
* C:\Programme\opsi.org\opsi-client-agent\on_shutdown\doinstall32.cmd (ou doinstall64.cmd pour 64Bit systems)

Pour configurer le système afin d'attendre la fin du processus d'installation, le temps d'attente maximum est réglée sur l'infini (0 secondes):

* Modèles d'administration
* Système - Scripts
* Temps d'attente maximal pour les scripts de stratégie de groupe
* Réglage - Activé - Secondes: 0

Le script d'arrêt opsi `doinstall32.cmd` / `doinstall64.cmd` change le répertoire de travail et déclenche l'événement 'on_shutdown':
[source,shell]
----
echo Start opsi product installation ...
cd "%ProgramFiles%\opsi.org\opsi-client-agent"
opsiclientd_shutdown_starter.exe on_shutdown
----

Pour les systèmes 64 bits:
[source,shell]
----
echo Start opsi product installation ...
cd "%ProgramFiles(x86)%\opsi.org\opsi-client-agent"
opsiclientd_shutdown_starter.exe on_shutdown
----

`opsiclientd_shutdown_starter` il déclenche l'installation et attend l'exécution, si l'arrêt du système est retardé pendant que la tâche `opsiclientd_shutdown_starter` est en cours d'exécution.

[[opsi-on-shutdown-concept-regedit]]
==== Entrées de Registre pour exécuter le script d'arrêt

Ces entrées de Registre est fixé par les paquets `opsi-client-agent` et démarrer l'exécution du script d'arrêt 'doinstall32.cmd' sous des clients WinXP / 32Bit. Pour les systèmes 64 bits, le nom du script est `doinstall64.cmd` (au lieu de `doinstall32.cmd`).

[source,shell]
----
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy\State\Machine\Scripts\Shutdown\0]
"GPO-ID"="LocalGPO"
"SOM-ID"="Local"
"FileSysPath"="C:\\WINDOWS\\System32\\GroupPolicy\\Machine"
"DisplayName"="opsi shutdown install policy"
"GPOName"="opsi shutdown install policy"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy\State\Machine\Scripts\Shutdown\0\0]
"Script"="C:\\Programme\\opsi.org\\opsi-client-agent\\on_shutdown\\doinstall32.cmd"
"Parameters"=""
"ExecTime"=hex(b):00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System\Scripts\Shutdown\0]
"GPO-ID"="LocalGPO"
"SOM-ID"="Local"
"FileSysPath"="C:\\WINDOWS\\System32\\GroupPolicy\\Machine"
"DisplayName"="opsi shutdown install policy"
"GPOName"="opsi shutdown install policy"

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System\Scripts\Shutdown\0\0]
"Script"="C:\\Programme\\opsi.org\\opsi-client-agent\\on_shutdown\\doinstall32.cmd"
"Parameters"=""
"ExecTime"=hex:00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\policies\system]
"MaxGPOScriptWait"=dword:00000000
----

Celles-ci sont les entrées de registre pour Win6 64Bit (Vista / Win7 / Win8):

[source,shell]
----
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy\State\Machine\Scripts\Shutdown\0]
"GPO-ID"="LocalGPO"
"SOM-ID"="Local"
"FileSysPath"="C:\\WINDOWS\\System32\\GroupPolicy\\Machine"
"DisplayName"="opsi shutdown install policy"
"GPOName"="opsi shutdown install policy"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy\State\Machine\Scripts\Shutdown\0\0]
"Script"="C:\\Programme\\opsi.org\\opsi-client-agent\\on_shutdown\\doinstall32.cmd"
"Parameters"=""
"ExecTime"=hex(b):00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy\Scripts\Shutdown\0]
"GPO-ID"="LocalGPO"
"SOM-ID"="Local"
"FileSysPath"="C:\\Windows\\System32\\GroupPolicy\\Machine"
"DisplayName"="opsi shutdown install policy"
"GPOName"="opsi shutdown install policy"
"PSScriptOrder"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy\Scripts\Shutdown\0\0]
"Script"="C:\\Program Files (x86)\\opsi.org\\opsi-client-agent\\on_shutdown\\doinstall64.cmd"
"Parameters"=""
"IsPowershell"=dword:00000000
"ExecTime"=hex:00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\policies\system]
"MaxGPOScriptWait"=dword:00000000
----

[[opsi-on-shutdown-concept-opsiclientd]]
==== Configuration de opsiclientd

Pour la gestion de l'installation lors de l'arrêt, le service client opsi 'opsiclientd' a besoin des entrées pour l'événement spécial 'on_shutdown' dans le fichier de configuration 'opsiclientd.conf'. Celles-ci sont les entrées correspondantes:

[source,shell]
----
[event_gui_startup]
active = True

[event_gui_startup{installation_pending}]
active = True

[event_on_shutdown]
active = False

[event_on_shutdown{installation_pending}]
active = False

[precondition_installation_pending]
installation_pending = true
----

La condition préalable `installation_pending` est réglée sur 'true' par 'opsiclientd' alors qu'une installation est en cours, et elle est réglée 'false' lorsque l'installation est terminée. Ainsi, une installation inachevée, qui doit procéder à l'installation après un redémarrage, peut être détectée par la condition `installation_pending` encore étant 'true' à la fin de l'exécution du script.
Lorsque la section `event_on_shutdown` est réglée sur `False` (qui est la valeur par défaut), l'installation lors de l'arrêt est désactivé.

Celle-ci est la configuration d'un client avec l'installation lors de l'arrêt activée:

[source,shell]
----
[event_gui_startup]
active = True

[event_gui_startup{installation_pending}]
active = True

[event_on_shutdown]
active = True

[event_on_shutdown{installation_pending}]
active = False

[precondition_installation_pending]
installation_pending = true
----

Donc, la seule différence est la section 'event_on_shutdown' étant à 'True':

[source,shell]
----
[event_on_shutdown]
active = True.
----

Le réglage de la section 'event_on_shutdown' est géré par le commutateur produit `on_shutdown_install` du paquet `opsi-client-agent`.

La condition préalable `precondition_installation_pending = true` indique que le processus d'installation en cours n'est pas encore terminé. Cette condition reste à 'true', même après plusieurs redémarrages, jusqu'à ce que l'installation actuelle est complété. Dans le cas d'un redémarrage nécessaire lors de l'installation, la configuration `[event_gui_startup{installation_pending}] active = True` provoque la poursuite de l'installation au prochain démarrage du système. Cette configuration ne peut pas être changé, parce que l'installation actuelle doit être complétée, avant que l'utilisateur soit autorisé à se connecter.

Également la configuration `[event_on_shutdown{installation_pending}] active = False` doit conserver sa valeur à 'False' en permanence, parce que l'installation doit se poursuivre APRÈS le prochain redémarrage. Sinon, il n'y aurait pas un redémarrage entre l'installation au démarrage et l'installation lors de l'arrêt.

Dès que le processus d'installation est terminé, la condition préalable est réglé sur `installation_pending = false`, de sorte que l'installation lors de l'arrêt est de nouveau active.

[[opsi-on-shutdown-config]]
==== Configuration spéciale d'Installation lors de l'Arrêt

Pour activer l'installation à l'arrêt, juste un fichier `modules` valide est nécessaire, comme décrit dans <<opsi-on-shutdown-activate>>. Ensuite, l'installation lors de l'arrêt, peut être activé en positionnant le commutateur de produit `on_shutdown_install` du paquet `opsi-client-agent`.

Par éfaut, l'installation au démarrage est également active. Donc il est assuré, que le client a toujours de logiciels mis à jour. Même s'il a été hors ligne pendant un certain temps (lorsque l'utilisateur rentre de vacances, par exemple).

L'installation au démarrage peut être désactivée, si on le désire. La configuration de '{opsi-client-agent} peut être effectuée par le service Web (voir: <<opsi-manual-clientagent-configuration-webservice>>),
therefore an '{opsi-config-object}' should be created:

* +opsiclientd.event_gui_startup.active+ (boolean, default: +true+)

Par ce '{opsi-config-object}' l'événement 'gui_startup' peut être configuré pour un client. '{opsi-config-objects}' peut être créée par '{opsi-configed}' ou '{opsi-admin}'.

Pour la création de '{opsi-config-object}' avec '{opsi-admin}', exécutez la commande suivante sur le '{opsi-configserver}':

[source,shell]
----
opsi-admin -d method config_createBool opsiclientd.event_gui_startup.active "gui_startup active" true
----

La valeur par défaut 'true' est la valeur par défaut dans `opsiclientd.conf`.

Pour désactiver l'installation au démarrage pour un client, '{opsi-config-object}' peut être configuré comme suit:

* +opsiclientd.event_gui_startup.active+: +false+

Soyez prudent avec la désactivation de l'installation au démarrage, car il y a un risque élevé d'avoir des logiciels obsolètes. Ne jamais modifier les paramètres des sections de la condition 'installation_pending'. Les paramètres par défaut sont nécessaires pour gérer le processus d'installation. +

Pour définir '{opsi-config-object}' avec '{opsi-admin}', exécutez la commande suivante sur le '{opsi-configserver}' (dans l'exemple, pour un client avec {opsi-host-id} +myclient.domain.de+):

[source,shell]
----
opsi-admin -d method configState_create opsiclientd.event_gui_startup.active myclient.domain.de false
----

Avec la configuration 'event_gui_startup=false' il n'y a pas de connexion à '{opsi-configserver}' et aucune installation de logiciel au démarrage. A l'exception des installations en cours, qui continuent au démarrage du système. Cela est géré par la configuration `event_on_shutdown{installation_pending}`. Donc, ne modifiez pas les paramètres pour les sections avec la condition 'installation_pending', car ils sont importants pour les produits qui demandent un redémarrage lors de l'installation.

[[opsi-on-shutdown-error]]
==== Fichier de log local

Au cours de l'installation lors de l'arrêt, un fichier de log est écrit:

* `C:\opsi.org\tmp\doinstall.log`

avec, en cas de succès, le contenu suivant:

[source,shell]
----
doinstall32.cmd started
The current date is: .Tue 02/012/2013
Enter the new date: (mm-dd-yy) Backend connected.
modules: passed first checkpoint.
Modules file signature verified (customer: my company)
Check completed.
Event fired
Task completed.
----

Ce fichier de log est réécrit à chaque fois et peut être vérifiée dans le cas d'un dysfonctionnement.
