//// 
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; Until we found a better license:
; All rights reserved.
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      04.07.2011
:Revision:  4.0.1
:toclevels: 6

include::../common/opsi_terms.asciidoc[]


[[opsi-manual-registryentries]]
== Registry Entries 

[[opsi-manual-registryentries-opsiclientd]]
=== Registry entries for the opsiclientd

[[opsi-manual-registryentries-opsiclientd-general]]
==== opsi.org/general
* `bootmode= <bkstd | reins>` +
Stores the information whether the client is new installed or not.

[[opsi-manual-registryentries-opsiclientd-preloginloader]]
==== opsi.org/opsi-client-agent and opsi.org/preloginloader
These both keys should be identical but the second one is deprecated and exists for backward compatibility.
Schlüssel [HKEY_LOCAL_MACHINE\SOFTWARE\opsi.org\opsi-client-agent]
Schlüssel [HKEY_LOCAL_MACHINE\SOFTWARE\opsi.org\preloginloader]

* `"RemoveMsginaOnDeinst"=dword:00000001`
		- on uninstall restore the default login handler
* `"WinstRegKey"="SOFTWARE\\opsi.org\\winst"`
		- where to look for '{opsi-winst}' registry reboot requests
* `"LoginBlockerStart"=dword:00000001`
		- opsigina waits for READY from the named pipe +
		 (if set to 0, the user is allowed to logon during software installation)
* `"LoginBlockerTimeoutConnect"=dword:00000005`
		- Timeout in minutes for pipe-connect
* `"LoginBlockerLogLevel"=reg_dword:006`
		- Log level of the loginblocker
* `"OpsiServiceType"=dword:00000002`
		- Should opsigina connect to prelogin (1) or opsiclientd (2)
* `"NextGina"="msgina.dll"`
		- The next gina.dll in the gina chain
		
[[opsi-manual-registryentries-opsiclientd-shareinfo]]		
==== opsi.org/shareinfo
* `depoturl` +
<URL for installation packets> +
depoturl pattern: <protocol:\\server\share\dir>
+
Example: + 
'smb:\\schleppi\opsi_depot'

* `depotdrive` +
drive letter the depoturl will be mounted to
+
Example: `P:` (including the colon)

[[opsi-manual-registryentries-winst]]
=== Registry entries of the {opsi-winst}

[[opsi-manual-registryentries-winst-winst]]
==== opsi.org/winst
This registry entries are controlled by opsi-winst and should not be edited.
[source,ini]
----
"LastLogFilename"="C:\\TMP\\syslogin.log"
"ContinueLogFile"=dword:00000000
"RebootRequested"=dword:00000000
"SendLogToService"=dword:00000001
"NumberOfErrors"=dword:00000000
"ShutdownRequested"=dword:00000000
----

[[opsi-manual-registryentries-winst-syslog]]
==== Controlling the logging via syslog protocol

The relevant registry section is [HKLM\Software\opsi.org\syslogd]
the value of 'RemoteErrorLogging' (DWORD) is evaluated: +
+RemoteErrorLogging = (0=trel_none, 1=trel_filesystem, 2=trel_syslog)+

If logging is set to syslog protocol ("remoteerrorlogging"=dword:00000002), the string variable 'sysloghost' gives the IP-name of the LogHost. +
The DWORD variable 'syslogfacility' defines the source of the syslog messages (default is ID_SYSLOG_FACILITY_LOCAL0).

The logging source can be:
[source,ini]
----
  ID_SYSLOG_FACILITY_KERNEL     = 0;  // kernel messages
  ID_SYSLOG_FACILITY_USER       = 1;  // user-level messages
  ID_SYSLOG_FACILITY_MAIL       = 2;  // mail system
  ID_SYSLOG_FACILITY_SYS_DAEMON = 3;  // system daemons
  ID_SYSLOG_FACILITY_SECURITY1  = 4;  // security/authorization messages (1)
  ID_SYSLOG_FACILITY_INTERNAL   = 5;  // messages generated internally by syslogd
  ID_SYSLOG_FACILITY_LPR        = 6;  // line printer subsystem
  ID_SYSLOG_FACILITY_NNTP       = 7;  // network news subsystem
  ID_SYSLOG_FACILITY_UUCP       = 8;  // UUCP subsystem
  ID_SYSLOG_FACILITY_CLOCK1     = 9;  // clock daemon (1)
  ID_SYSLOG_FACILITY_SECURITY2  = 10; // security/authorization messages (2)
  ID_SYSLOG_FACILITY_FTP        = 11; // FTP daemon
  ID_SYSLOG_FACILITY_NTP        = 12; // NTP subsystem
  ID_SYSLOG_FACILITY_AUDIT      = 13; // log audit
  ID_SYSLOG_FACILITY_ALERT      = 14; // log alert
  ID_SYSLOG_FACILITY_CLOCK2     = 15; // clock daemon (2)
  ID_SYSLOG_FACILITY_LOCAL0     = 16; // local use 0  (local0)
  ID_SYSLOG_FACILITY_LOCAL1     = 17; // local use 1  (local1)
  ID_SYSLOG_FACILITY_LOCAL2     = 18; // local use 2  (local2)
  ID_SYSLOG_FACILITY_LOCAL3     = 19; // local use 3  (local3)
  ID_SYSLOG_FACILITY_LOCAL4     = 20; // local use 4  (local4)
  ID_SYSLOG_FACILITY_LOCAL5     = 21; // local use 5  (local5)
  ID_SYSLOG_FACILITY_LOCAL6     = 22; // local use 6  (local6)
  ID_SYSLOG_FACILITY_LOCAL7     = 23; // local use 7  (local7)
----
