////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author: uib gmbh
:Email: info@uib.de
:Revision: 4.1
:website: http://opsi.org

include::../common/opsi_terms.asciidoc[]


[[opsi-manual-glossary]]
== Glossary

////
Asciidoc supports creating glossary entries if they are written in the
following format.

term::
  Indented description

////


action request::
  Next scheduled action for a client. Typical action requests are 'setup', 'uninstall' and 'update'.


backend::
  opsi supports different types of data storage, i.e. in a file or database.
  These are called backends.


client Id::
  Unique identifier for a client through an 'fully qualified hostname' (FQDN).


config server::
  Server which is reponsible for providing management and configuration data in an opsi environment.


depot server::
  Server which provides installation and process data through a Samba share for clients to install from.


DHCP (Dynamic Host Configuration Protocol)::
  A protocol allowing dynamic IP address assignment.


FQDN (Fully Qualified Hostname)::
  Complete name of a computer in a network. It consists of the IP name and domain, i.e. 'fritzlaptop.uib.local'.


FTP (File Transfer Protocol)::
  A standard network protocol used for the transfer of files between a client and a server on a network


GUI::
  Graphical User Interface.


host Id::
  Unique ID of a host (includes servers and clients) by using the 'fully qualified domain name' (FQDN).


JSON::
  JSON is short for JavaScript Object Notation, which is a compact data exchange format. The data is easy to read for people and for machines.


Last seen::
  Time stamp of the last time a client connected to the opsi service.


LDAP (Lightweight Directory Access Protocol)::
  Lightweight Directory Access Protocol is an protocol that allows programs to look up information from a directory service.


localboot product::
  An opsi product which is installed on a running operating system.


MAC address (Media Access Control address)::
  An unique identifier attached to the network adapter, which is transferred with every data package.
  With this address the computer (respectively its network card) can be identified worldwide and can be mapped to an IP address.
  The MAC address is composed from 6 hexadecimal numbers separated by colon.


netboot product::
  An opsi product which will be started when booting over the network.
  Usually used for installating operating systems on a computer.


opsi::
  open pc server integration


opsi-client-agent::
  Agent on a Windows client to install centrally managed software.


opsi-server::
  A server providing services for an opsi environment.
  Usually 'config server' and 'depot server'.
  Ein Server der im Rahmen von opsi benötigte Dienste bereitstellt. Üblicherweise 'Config-Server' und 'Depot-Server'.


opsiconfd::
  Server-Dienst, welcher die opsi-Konfigurations-API als Webservice zur Verfügung stellt.


opsiconfd::
  Service on a server which provides the opsi configuration API as a webservice.


product properties::
  Additional parameters for an opsi product that can be set on a per-client basis and which are then evaluated during the installation.


product ID::
  Unique name of an opsi-product.
  Consists of a-z, numbers and hyphen.
  Spaces or special characters (except hyphens) are not allowed.
  Example for a product Id: 'acroread'

product name::
  Full name of a product (allowing blanks).
  Example for a product name: 'Adobe Acrobat Reader'.


PXE (Preboot eXecution Environment)::
  Standard for booting a software over the network.
  Commonly used with 'DHCP'.


SAMBA::
  Free software to provide data shares or authentication services to Microsoft clients from an Linux server using the 'SMB' protocol.


SMB (Server Message Block)::
  Protocol by Microsoft to provide network shares and authentication.
  A dialect of SMB is 'CIFS' (Common Internet File System).


tftp (Trivial File Transfer Protocol)::
  A tftp daemon ('tftpd') allows for transmitting files from and to other computers on a network without requiring a login but with restricted access.
  Accessing files is limited to those who are readable or writable by all users and located in a special directory.
