//// 
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; Until we found a better license:
; All rights reserved.
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      05.05.2011
:Revision:  4.0.1
:toclevels: 6

include::../common/opsi_terms.asciidoc[]


[[opsi-manual-introduction]]
== Introduction

[[opsi-manual-introduction-who-should-read]]
=== Who should read this manual?

This manual is written for all who want to gain a deeper insight into the mechanisms and the tools of the client management system opsi ("open pc server integration"). 

It presents a complete HOWTO for the use of opsi while emphasizing the understanding of the technical background. The decision maker who decides on using opsi as well as the system administrator who works with it will get a solid foundation for their tasks.

[[opsi-manual-introduction-conventions]]
=== Notations

Angle brackets '< >' mark abstract names. In a concrete context any marked '<abstract name>' must be replaced by some real name. Example: The file share, where opsi places the software packets, may abstractly be noted as '<opsi-depot-share>'. If the real fileshare is `/var/lib/opsi/depot`, then you have to replace the abstract name by exactly this string. The location of the packet `<opsi-depot-share>/ooffice` becomes
`/var/lib/opsi/depot/ooffice`.

Example snippets from program code or configuration files use a Courier font, with a background color:
[source,prompt]
----
depoturl=smb://smbhost/sharename/path
----
