////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      05.04.2012
:Revision:  4.0.1
:toclevels: 6


include::../common/opsi_terms.asciidoc[]

[[opsi-manual-localization]]
== opsi localization

Get your localization code:

http://www.gnu.org/software/gettext/manual/html_node/Usual-Language-Codes.html

Example: +
en:: English
de:: German
fr:: French
it:: Italian
da:: Danish

[[opsi-manual-localization-pofiles]]
=== PO files

You may use the poedit application for editing for editing:
http://download.uib.de/opsi4.0/products/contribute/full-package/poedit_1.4.6-1.opsi
or
http://www.poedit.net/

[[opsi-manual-localization-pofiles-opsi-winst]]
=== PO files: opsi-winst

opsi-winst: at svn.opsi.org repo: opsi-winst branches/4.11.3/languages:

https://svn.opsi.org/listing.php?repname=opsi-winst&path=%2Fbranches%2F4.11.3%2Flanguages%2F&#a0658e5e6a7e3d75fca6bb75072dbadfc

[[opsi-manual-localization-pofiles-opsiclientd]]
=== PO files: opsiclientd

https://svn.opsi.org/listing.php?repname=opsiclientd&path=%2Ftrunk%2Fgettext%2F&#a4c4f8177ba88910762266205d8169980

[[opsi-manual-localization-pofiles-python-opsi]]
=== PO files: python-opsi

https://svn.opsi.org/listing.php?repname=python-opsi&path=%2Ftrunk%2Fgettext%2F&#a4c4f8177ba88910762266205d8169980

[[opsi-manual-localization-pofiles-opsi-utils]]
=== PO files: opsi-utils

https://svn.opsi.org/listing.php?repname=opsi-utils&path=%2Ftrunk%2Fgettext%2F&#a4c4f8177ba88910762266205d8169980

[[opsi-manual-localization-pofiles-opsi-utils]]
=== PO files: opsi-bootimage


Vorgehen:
- Ländercode über obigen Link ausfindig machen.
- ins gettext Verzeichnis wechseln
- update_po.sh anpassen: for lang in de fr da; do
- ./update_po.sh ausführen
- neue Datei anpassen

[[opsi-manual-localization-configed]]
=== configed

opsi-configed: at svn.opsi.org repo:
opsi-configed/trunk/classes/de/uib/messages

https://svn.opsi.org/listing.php?repname=opsi-configed&path=%2Ftrunk%2Fsrc%2Fde%2Fuib%2Fmessages%2F&#a0771766f6b075de75d6111ea7bd4bae0

The latest Version you will find at our experimental repositories.
For example:
http://download.opensuse.org/repositories/home:/uibmz:/opsi:/opsi40-experimental/Debian_6.0/all/opsi-configed_4.0.2.2-1_all.deb

If you unzip configed.jar you find the translation files in
de/uib/messages. There you can replace the file, pack (zip) again the
archive and retry the program.

You have to modify the valid_translations.conf
and add a new configed_da.properties and a da.png

Since we introduced some signing mechanisms the procedure to get a new 
working configed.jar has become a little bit more complicated.

One option that your really check out the configed code from 
svn.opsi.org (where you will find the last stable version), add a 
configed_da.properties, a da.png and a new valid_localisations.conf (as 
you provided). Then you may use the bash scripts compile.sh plus 
sign_jars.sh to produce new signed configed.jar and swingx.jar files. 
You may put the jars to /usr/lib/configed in order to see it in browser 
(after reopening the browser).

It is also possible just to put the additional needed files to a 
unpacked configed.jar, but then you have to rebuild it with the java 
packager jar. Since it is not signed it cannot be used via the browser.

So you may directly have a look at the result of your work.

[[opsi-manual-localization-opsiclientd-conf]]
=== opsiclientd.conf

One Part will be the localization of the message entries of the
opsiclientd.conf like for example:
# Message shown in the action notifier window (string)
action_message = Starting to process product actions. You are allowed to
cancel this event a total of %action_user_cancelable% time(s). The event
was already canceled %state.action_processing_cancel_counter% time(s).
# German translation (string)
action_message[de] = Starte die Bearbeitung von Produkt-Aktionen. Sie
können diese Aktion insgesamt %action_user_cancelable% mal abbrechen.
Die Aktion wurde bereits %state.action_processing_cancel_counter% mal
abgebrochen.

https://svn.opsi.org/filedetails.php?repname=opsiclientd&path=%2Ftrunk%2Fsrc%2Fwindows%2Fopsiclientd.conf

[[opsi-manual-localization-contact]]
=== Contact

Please send any Questions or localization files to: 'locales@uib.de'







