////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////
:Author:    uib gmbh
:Email:     info@uib.de
:Date:      23.06.2017
:Revision:  4.0.7
:toclevels: 6
:doctype:   book

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]

[[opsi-manual-abo-products-introduction]]
=== opsi subscriptions

[[opsi-manual-abo-products-introduction-firststeps]]
==== Initial Deployment of opsi subscriptons

Add the abo repositories to the '/etc/opsi/opsi-product-updater.conf'


[source,prompt]
----
[repository_abo_mshotfix]
baseUrl = http://download.uib.de
dirs = abo/mshotfix/opsi4/glb
active = false
username = <user>
password = <pass>
autoInstall = false
autoUpdate = true
autoSetup = false
onlyDownload = false

[repository_abo_standard]
baseUrl = http://download.uib.de
dirs = abo/standard/opsi4
active = false
username = <user>
password = <pass>
autoInstall = false
autoUpdate = true
autoSetup = false
onlyDownload = false

[repository_abo_msoffice]
baseUrl = http://download.uib.de
dirs = abo/msoffice/opsi4
active = false
username = <user>
password = <pass>
autoInstall = false
autoUpdate = true
autoSetup = false
onlyDownload = false
----

CAUTION: If needed you can add a proxy to each section!

[source,prompt]
----
; Set Proxy handler like: http://10.10.10.1:8080
proxy =
----



Since opsi Version 4.0.5 one can choose specific packages for example:

[source,prompt]
----
opsi-product-updater -p "mshotfix,mshotfix-win7-x86-glb,mshotfix-win7-win2008r2-x64-glb"
----

for the mshotfix-packages for Windows 7.

Prior to opsi 4.0.5 one could download the opsi-packages and install them via `opsi-package-manager -p ask -i <packagename>.opsi` and set the default properties for the '{opsi-configserver}'. (Without the option `-p ask` the package defaults would be the depot defaults)-

Since opsi 4.0.5 it's possible to set the product-property defaults per depot with the management interface '{opsi-Configed}'

An equivalent approach ist the usage of for example an `/etc/opsi/opsi-product-updater.conf.abo.standard` which can  encalled via `opsi-product-updater -c /etc/opsi/psi-product-updater.conf.abo.standard`

[[opsi-manual-abo-products-mshotfix]]
==== Subscription 'MS-Hotfixes'
Regular updates for the product MS-Hotfix (OS hotfixes for Windows 7 / 2008R2 /8.1 /2012 / 10 /2016).

The updates will be provided within 3 working days after Microsoft publication of important and critical patches.

This opsi-packages are delivered via download area (restricted access).

http://technet.microsoft.com/en-us/security/gg309177.aspx
[source,prompt]
----

Rating	Definition
Critical

A vulnerability whose exploitation could allow code execution without user interaction. These scenarios include self-propagating Malware (e.g. network worms), or unavoidable common use scenarios where code execution occurs without warnings or prompts. This could mean browsing to a web page or opening an email.

Microsoft recommends that customers apply Critical updates immediately.

Important

A vulnerability whose exploitation could result in compromise of the confidentiality, integrity, or availability of user data, or of the integrity or availability of processing resources. These scenarios include common use scenarios where client is compromised with warnings or prompts regardless of the provenance, quality, or usability. Sequences of user actions that do not generate prompts or warnings are also covered.

Microsoft recommends that customers apply Important updates at the earliest opportunity.

Moderate

Impact of the vulnerability is mitigated to a significant degree by factors such as authentication requirements or applicability only to non-default configurations.

Microsoft recommends that customers consider applying the security update.
Low	Impact of the vulnerability is comprehensively mitigated by the characteristics of the affected component. Microsoft recommends that customers evaluate whether to apply the security update to the affected systems.

----

The opsi-mshotfix package uses (like WSUS Offline Update http://forums.wsusoffline.net/viewtopic.php?f=7&t=172 Coverage of WSUS Offline Update) Microsoft's wsusscn2.cab.
wsusscn2.cab delivers all „critical“ and „important“ updates, but not all "optional" updates.

The base-package „mshotfix“ contains the  master-script for installing the patches contained in the other mshotfix-packages.

CAUTION: Wan/VPN-extension: mshotfix packages for Windows 8.1 / Windows 2012 R2 requires opsi-winst >= opsi-winst_4.11.3.11-1.opsi and opsi-client-agent >= 4.0.4.4-1.opsi

CAUTION: Wan/VPN-extension: mshotfix packages for Windows 10 / Windows 2016 requires opsi-client-agent >= 4.0.7.9-2


.mshotfix Client-Requirements
|===================================
|OS|
|Windows 7 / Windows 2008 R2|Servicepack 1
|Windows 8.1 / Windows 2012 R2|
|Windows 10  / Windows 2016 |
|====================================

Structure of the download area:


[source,configfile]
----
mshotfix
  !-opsi4/
     !-glb/	Base-package mshotfix  and global packages
     		mshotfix-win7-x86-glb,
     		mshotfix-win7-win2008r2-x64-glb
     		mshotfix-win81-x86-glb
		mshotfix-win81-win2012r2-x64-glb
		mshotfix-win10-win2016-x64-glb
		mshotfix-win10-x86-glb
     !-misc/ 
     		dotnetfx,
     		dotnetfx-hotfix,
     		mshotfix-uninstall,
     		ms-ie11,
     		silverlight
----

.mshotfix Client-OS
|=======================
|OS|Arch. Language|Patch-package
|Windows 7 | 32Bit | mshotfix-win7-x86-glb
|Windows 7 | 64Bit | mshotfix-win7-win2008r2-x64-glb
|Windows 8.1 | 32Bit | mshotfix-win81-x86-glb
|Windows 8.1 | 64Bit | mshotfix-win81-win2012r2-x64-glb
|Windows 2008 Server R2 | 64Bit | mshotfix-win7-win2008r2-x64-glb
|Windows 2012 R2 | 64Bit | mshotfix-win81-win2012r2-x64-glb
|Windows 10 | 32Bit | mshotfix-win10-x86-glb
|Windows 10 | 64Bit | mshotfix-win10-win2016-x64-glb
|Windows 2016 | 64Bit | mshotfix-win10-win2016-x64-glb
|=======================

Since mshotfix 201304-1 a list of installed patches is saved in file `C:\opsi.org\mshotfix\deployed.txt`.

noreboot:: noreboot=on: Don't Reboot.  Warning will be logged if a reboot     is required.  Should be "on" for Server.
values: ["off", "on"]
default: ["off"]


force:: force=on: All Hotfixes will be forced installed
values: ["off", "on"]
default: ["off"]

excludes::  Comma separated list with kb-numbers or ms-no, that will be excluded (Only Number without beginning kb and no spaces. Example: 123456,789011,2222)
 Browser Choice update? (KB976002)

severity:: choose the severity that will be installed. Possible Entries are Critical, Important, Moderate, all
values: ["Critical", "Important", "Moderate", "all"]
default: ["Critical", "Important"]

excludelist-superseded.txt:: Use File ExcludeList-superseded.txt
values: ["", "ExcludeList-superseded.txt"]
default: [""]

monthly-updates::  Handle windows-7-and-windows-8-1 : security Only Quality Update     vs Monthly Quality Rollup (see https://blogs.technet.microsoft.com/windowsi    tpro/2016/08/15/further-simplifying-servicing-model-for-windows-7-and-window    s-8-1/ https://blogs.technet.microsoft.com/windowsitpro/2016/10/07/more-on-w    indows-7-and-windows-8-1-servicing-changes/ https://blogs.msdn.microsoft.com    /dotnet/2016/10/11/net-framework-monthly-rollups-explained/
values: ["all", "monthly_quality_rollup", "security_only_quality_update"]
default: ["security_only_quality_update"]

installservicingstacks:: Install for instance Servicing stack updates and others where  catalog.update.microsoft.com Update Details say Must be installed exclusively Yes. Will immediate reboot after reboot ignoring property "noreboot"
 win7 /2008r2:"kb3177467" win10 1607 "kb4023834" win10 1511 "kb4015220" win10 1703 "kb4022405"
values: ["false", "true"]
default: ["false"]

===== misc mshotfix-uninstall

----
mshotfix-uninstall        201512-1                  MS Hotfix BasePackage
----

Removes removable patches via `wusa /uninstall  ...` if possible

excludes:: Commaseparated list with kb-numbers or ms-no, that will be excluded (Only Number without beginning kb and no spaces. Example: 2553154,ms14-082)

noreboot:: noreboot=on: Don't Reboot.  Warning will be logged if a reboot is required.
values: ["off", "on"]
default: ["off"]

removefromdeployed.txt:: Remove from deployed.txt
default: False

removekb:: Remove KBXXXXX, (Only Number without beginning kb and no spaces f.e. 3097877)
multivalue: True
default: [""]

===== misc dotnetfx

----
dotnetfx                  4.6.2-3                   .NET Framework
----

Installation of dotnet framework 4.5 and above especially for windows  7 /2008 R2 / 8.1 / 2012 R2

"The Microsoft .NET Framework 4.6.2 is a highly compatible, in-place update to the Microsoft .NET Framework 4, 4.5, 4.5.1, 4.5.2, 4.6, and 4.6.1."

(see https://support.microsoft.com/en-us/help/3151802/the-.net-framework-4.6.2-web-installer-for-windows)

As a consequence

a) One cant install the 4.x-versions side by side
b) Third-party setups might not recognize this issue and insist for
example on version 4.5.1

After a successfull dotnetfx-Installation on a windows client
dotnetfx-hotfix - if available on your opsi-server - will be set to setup.

version:: Here you can switch which Versions should be installed, 3.5 includes all other versions before. 4.7 includes all 4.x versions Note: Win7 has 3.5 by default. "all" means 4.6
values: ["3.5", "4.0", "4.5", "4.5.1", "4.5.2", "4.6", "4.6.1", "4.6.2","all"]
default: ["all"]
 
rerundotnethotfix::rerun dotnetfx-hotfix after installation if possible
values: ["false", "true"]
default: ["true"]

install_language_languagepack:: install_language_languagepack
values: ["auto", "de", "en", "fr"]
default: ["auto"]

===== misc dotnetfx-hotfix

----
dotnetfx-hotfix           201705-1                  dotnetfx-hotfix
----

at the moment our update subscription  'MS-Hotfixes' contains patches
for 'Microsoft .NET Framework' if the version belongs to the installed
operating system.

For instance comes "Microsoft .NET Framework 3.5.1" with Windows 7 .

We now provide an updated package dotnetfx-hotfix_201705-1.opsiunder

https://download.uib.de/abo/mshotfix/opsi4/misc/dotnetfx-hotfix_201705-1.opsi

This provides patches from Microsoft for

- Microsoft .NET Framework 4
- Microsoft .NET Framework 4.5
- Microsoft .NET Framework 4.5.1
- Microsoft .NET Framework 4.5.2
- Microsoft .NET Framework 4.6
- Microsoft .NET Framework 4.6.1
- Microsoft .NET Framework 4.6.2



"Microsoft .NET Framework – Security Only Release" December 2016
Microsoft .NET Framework 4.6.2 for Windows 7/Windows 2008R2  and Windows
8.1 /2012R2 (https://technet.microsoft.com/library/security/ms16-155)

(The monthly rollups are contained in the mshotfix-packages)

The dotnetfx-hotfix patches - if available - versions
4.0x, 4.5x, 4.6x.

We tested the package thoroughly under Windows 7. Version 4.0, 4.5x and 4.6x
Under Windows 8.1 we tested patching "Microsoft .NET
Framework 4.6.2"

Please have a look at https://support.microsoft.com/en-us/lifecycle?p1=14380

"Support for .NET Framework 4, 4.5, and 4.5.1 ended on January 12, 2016"

respectivly

https://support.microsoft.com/en-us/lifecycle#gp/Framework_FAQ

noreboot:: noreboot=on: Don't Reboot.  Warning will be logged if a reboot is required.
values: ["off", "on"]
default: ["off"]
 
force:: force=on: All Hotfixes will be installed forced
values: ["off", "on"]
default: ["off"]

severity:: choose the severity that will be installed.Possible Entries:Critical, Important, Moderate, all
values: ["Critical", "Important", "Moderate", "all"]
default: ["all"]

===== misc ms-ie11

----
ms-ie11                   11.0-11                   Internet Explorer 11
----

Win7 Internet Explorer 11

rerunmshotfix:: rerun mshotfix after installation
values: ["false", "true"]
default: ["true"]
 
client_language::
values: ["auto", "de", "en", "fr"]
default: ["auto"]

===== misc silverlight

----
silverlight               5.1.50907.0-1             Microsoft Silverlight
----

[[opsi-manual-abo-products-ms-Officehotfixes]]

====  Update subscription for 'MS-Office Hotfixes'

Regular updates for the product:

    Ms-Office 2010 (32 Bit International)

The updates will be provided within 3 working days after Microsoft's publication of important and critical patches.


[[opsi-manual-abo-products-office_2010_hotfix]]
===== Updates for MS Office 2010 32-bit international: office_2010_hotfix
----
office_2010_hotfix               201604-1                  Microsoft Office 2010 Hotfixes
----

Contains global Office 2010 patches (inclusive Visio and Project 2010) . Requires Service pack 2.

Since office_2010_hotfix 201305-2 a list of installed patches is saved in file

`C:\opsi.org\mshotfix\office_2010_hotfix_deployed`

Since office_2010_hotfix 201503-1:

excludes:: Comma separated list with kb-numbers or ms-no, that will be excluded (Only Number without beginning kb and no spaces. Example: 2553154,ms14-082)

[[opsi-manual-abo-products-office_2013_hotfix]]

===== Updates for MS Office 2013 32-bit international: office_2013_hotfix
----
office_2013_hotfix               201604-1                  Microsoft Office 2013 Hotfixes
----

Contains global Office 2013 patches (includes Visio 2013).
 Requires Service pack 1

A list of installed patches is saved in the file

`C:\opsi.org\mshotfix\office_2013_hotfix_deployed`


Since office_2013_hotfix 201503-1:

excludes:: Comma separated list with kb-numbers or ms-no, that will be excluded (Only Number without beginning kb and no spaces. Example: 2553154,ms14-082)

[[opsi-manual-abo-products-office_2016_hotfix]]
===== Updates for MS Office 2016 32-bit international: office_2016_hotfix
----
office_2016_hotfix               201604-1                  Microsoft Office 2016 Hotfixes
----

Contains global Office 2016 patches.

A list of installed patches is saved in the file

`C:\opsi.org\mshotfix\office_2016_hotfix_deployed`


excludes:: Comma separated list with kb-numbers or ms-no, that will be excluded (Only Number without beginning kb and no spaces. Example: 2553154,ms14-082)

[[opsi-manual-abo-products-standard]]
==== Update subscription for the opsi standard packages


    Adobe Acrobat Reader (german, english and french / 32 Bit)
    Adobe Flashplayer (international / 32 Bit / 64 Bit)
    Apache OpenOffice.org (german / 32 Bit)
    Google Chromium for business (international 32 Bit /64 Bit)
    LibreOffice (international / 32 Bit)
    Mozilla Firefox (dutch, german, english and french / 32 Bit) respectivle 32/64 Bit since 201706
    Mozilla Thunderbird (german, english and french / 32 Bit)
    Oracle Java VM (international / 32 Bit / 64 Bit)

    Depending on your contracts we offer the subscriptions with:

    Adobe Acrobat Reader XI (in addition danish, dutch, italian and spanish / 32 Bit)
    Mozilla Firefox (in addition czech, danish, italian, norwegian or spanish / 32 Bit)
    Mozilla Thunderbird (in addition italian / 32 Bit)

    further languages can be obtained upon request.

    The updates will be provided within 2 working weeks after manufacturers release. For critical security patches the opsi package will be provided within 1 working week after the patch release.

===== Customizing with central configuration files

For the opsi-packages
----
acroread11
adobe.reader.dc.classic
adobe.reader.dc.continuous
firefox
flashplayer
javavm
thunderbird
----

one can provide configuration files and populate them via product-properties (for details see the relevant chapters)

===== Customizing with preinst/postinst-scripts

For the opsi-packages
----
acroread11 	(since 11.0.3-1)
adobe.reader.dc.classic
firefox		(since 17.0.6esrorstandard-1)
flashplayer	(since 13.0.0.182or11.7.700.275-1)
google-chrome-for-business
javavm		(since 1.7.0.51-4 )
libreoffice	(since 4.3.5or4.4.0-2)
ooffice		(since 4.1.1-2)
thunderbird	(since 17.0.6esrorstandard-1)
----

one can use custom-scripts in directory `custom\scripts`

Simple templates can be found in directory `opsi\scripts`

[source,configfile]
----

custom.actions.post.setup
custom.actions.post.uninstall
custom.actions.pre.setup
custom.actions.pre.uninstall
custom.declarations
custom.sections

custom scripts will be included at
- setup-script
- uninstall-script

custom pre-scripts will be included in
- setup-script
- uninstall-script

custom post-scripts will be included in
- in setup-script
- uninstall-script

custom.declarations
; intended for declaration of custom Variables and Stringlist Variables
; will be included with "include_insert" at top of [actions]
; but after GetProductProperties

custom.sections
; intended for declaration of custom secondary sections
; will be included with "include_append" at top of [actions]
; but after GetProductProperties

custom.actions.pre.setup  (or custom.actions.pre.uninstall)
; will be included with "include_insert" at top of [actions]
; (but after GetProductProperties)

custom.actions.post.setup (or custom.actions.post.uninstall)
; will be included with "include_insert" in case of successful installation before "endof_"actions"
; in setup-script ( or uninstall-script)

----


===== Adobe Acrobat Document Cloud Classic : adobe.reader.dc.classic
----
adobe.reader.dc.classic	20151500630280-1          Adobe Acrobat Reader dc
----

The adobe.reader.dc.classic-Package contains Adobe Acrobat Document Cloud Classic (MUI-Version)

Adaptation in the transform file *.mst
[source,prompt]
----
cat transform.txt
Changes vs default the transform file *.mst

Personalization Options
Suppress Eula

Installation Options
acivated - Make Reader the default PDF viewer
IF REBOOT REQUIRED - suppress reboot


Shortcuts
deactivated - Destination Computer/Desktop/Adobe Reader XI (Icon)


Online and Acrobat.com Features
Online Features
activated - Disable product updates
Enable & Ask before Installing - Load trusted root certificates from Adobe

Online Services and Features
disable product updates
Load trusted root certificates from Adobe disable
DISABLE all Services
----

adobereader.mst::

The Adobe Reader package uses a default transform
build with the Adobe Customization Wizard.
Own mst-files can be placed in the share `opsi_depot` in
`/var/lib/opsi/depot/adobe.reader.dc.classic/custom`
During the installation via `opsi-package-manager -i <adobe.reader.dc.classic>` the directory custom will preserved by the preinst/postinst-scripts and the names of any mst-file in the custom-directory will be appear as a possible property entry.

CAUTION: opsi WAN/VPN extension: The synchronization process is based on the file `<product-id>.files`. So any change in the `custom` share requires new installation of the package via `opsi-package-manager`.

client_language::

The adobe.reader.dc.classic-package contains Adobe Acrobat Document Cloud Classic (MUI-Version)
"auto" tries to install the correct language. values: ["auto", "de", "en", "fr"] default: ["auto"]

noreboot::

description: noreboot=true: Don't Reboot.  Warning will be logged if a reboot is required.
values: ["false", "true"]
default: ["false"]




===== Adobe Acrobat Document Cloud Continuous : adobe.reader.dc.continuous
----
adobe.reader.dc.continuous	2015.023.20056-1          Adobe Acrobat Reader dc
----

The adobe.reader.dc.classic-Package contains Adobe Acrobat Document Cloud Continuous (MUI-Version)

Adaptation in the transform file *.mst
[source,prompt]
----
cat transform.txt
Changes vs default the transform file *.mst

Personalization Options
Suppress Eula

Installation Options
acivated - Make Reader the default PDF viewer
IF REBOOT REQUIRED - suppress reboot


Shortcuts
deactivated - Destination Computer/Desktop/Adobe Reader (Icon)


Online and Acrobat.com Features
Online Features
activated - Disable product updates
Enable & Ask before Installing - Load trusted root certificates from Adobe

Online Services and Features
disable product updates
Load trusted root certificates from Adobe disable
DISABLE all Services
----

adobereader.mst::

The Adobe Reader package uses a default transform
build with the Adobe Customization Wizard.
Own mst-files can be placed in the share `opsi_depot` in
`/var/lib/opsi/depot/adobe.reader.dc.continuous/custom`
During the installation via `opsi-package-manager -i <adobe.reader.dc.continuous>` the directory custom will preserved by the preinst/postinst-scripts and the names of any mst-file in the custom-directory will be appear as a possible property entry.

CAUTION: opsi WAN/VPN extension: The synchronization process is based on the file `<product-id>.files`. So any change in the `custom` share requires new installation of the package via `opsi-package-manager`.

client_language::

The adobe.reader.dc.classic-package contains Adobe Acrobat Document Cloud Classic (MUI-Version)
"auto" tries to install the correct language. values: ["auto", "de", "en", "fr"] default: ["auto"]

noreboot::

description: noreboot=true: Don't Reboot.  Warning will be logged if a reboot is required.
values: ["false", "true"]
default: ["false"]





===== Adobe Acrobat Reader XI : acroread11
----
acroread11                11.0.10-1                  Adobe Reader 11
----
End of core support (https://www.adobe.com/support/products/enterprise/eol/eol_matrix.html#864) 10/15/2017

The acroread-package contains Acrobat Reader XI in german, english and french.

Adaptation in the transform file *.mst
[source,prompt]
----
Installation Options
acivated - Make Reader the default PDF viewer


Shortcuts
deactivated - Destination Computer/Desktop/Adobe Reader XI (Icon)


Online and Acrobat.com Features
Online Features
activated - Disable product updates
Enable & Ask before Installing - Load trusted root certificates from Adobe

Adobe Online Service Integration
activated - Disable all Adobe online services based workflows an entry points
----

adobereader.mst::

The Adobe Reader package uses a default transform
build with the Adobe Customization Wizard.
Own mst-files could be placed in the share `opsi_depot` in
`/var/lib/opsi/depot/acroread11/custom`
During the installation via `opsi-package-manager -i <acroread11>` the custom directory will be preserved by the preinst/postinst-scripts and the names of any mst-file in the custom directory will be appear as a possible propertyentry.

CAUTION: opsi WAN/VPN extension: The synchronization process is based on the file `<product-id>.files`. So any change in the `custom` share requires new installation of the package via `opsi-package-manager`.

client_language::

The acroread11-package contains Acrobat Reader X in german, english and french.
"auto" tries to install the correct language. values: ["auto", "de", "en", "fr" ]  default: ["auto"]

protectedmode::

Enable Adobe Reader Protected Mode values: ["off", "on", "userchoice"] default: ["on"]

misc::
provides additional fonts

* AdbeRdrSD11000_all.msi : Adobe Reader XI Spelling Dictionary Pack

* FontPack11000_XtdAlf_Lang.msi: Adobe Reader XI Font Packs - Asian and Extended Language Pack

values: ["AdbeRdrSD11000_all.msi", "FontPack11000_XtdAlf_Lang.msi", "none"]
default: ["none"]

noreboot::

description: noreboot=true: Don't Reboot.  Warning will be logged if a reboot is required.
values: ["false", "true"]
default: ["false"]




[[opsi-manual-abo-products-standard-flashplayer]]
===== Adobe Flashplayer : flashplayer
----
flashplayer                      24.0.0.194-1 Adobe Flashplayer
----
The flashplayer-package contains Adobe Flashplayer standard or the Extended Support Release

flashplayer-version:: Flashplayer standard as default; Version esr (Extended Support Release http://blogs.adobe.com/flashplayer/2014/03/upcoming-changes-to-flash-players-extended-support-release.html)

values: esr, standard
default: standard

mms.cfg::

The configuration file mms.cfg

will be created during "setup" and patched according the properties below.

Since Version 13.0.0.250-2 one can use custom `mms.cfg` files in the share `opsi_depot` in
`/var/lib/opsi/depot/flashplayer/custom`

During the installation via `opsi-package-manager -i <flashplayer>` the directory custom will be preserved by the preinst/postinst-scripts and the names of any mms.cfg-file in the custom-directory will be appear as a possible property entry.

CAUTION: opsi WAN/VPN extension: The synchronization process is based on the file `<product-id>.files`. So any change in the `custom` share requires new installation of the package via `opsi-package-manager`.

mms.cfg::
`/var/lib/opsi/depot/flashplayer/custom` custom mms.cfg-files.

Only the property autoupdatedisable will be populated if custom `mms.cfg` are used


.Adobe Flashplayer Admin Guide:

[source,prompt]
----

flash_player_11_1_admin_guide.pdf (flash_player_admin_guide.pdf)

#####################################
Chapter 4: Administration

You can create and place files on the end user’s machine to manage
features related to security, privacy, use of disk
space, etc.

Privacy and security settings (mms.cfg)

As a network administrator, you can install Flash Player across the
environment while enforcing some common global
security and privacy settings (supported with installation-time
configuration choices). To do this, you need install a file
named mms.cfg on each client machine.

The mms.cfg file is a text file. When Flash Player starts, it reads its
settings from this file, and uses them to manage
functionality as described in the following sections.

mms.cfg file location

Assuming a default Windows installation, Flash Player looks for the
mms.cfg file in the following system directories:

32-bit Windows - %WINDIR%\System32\Macromed\Flash

64-bit Windows - %WINDIR%\SysWow64\Macromed\Flash

Note: The %WINDIR% location represents the Windows system directory,
such as C:\WINDOWS.

----

assetcachesize::
description: hard limit, in MB, on the amount of local storage that Flash Player uses for the storage of common Flash components
values: ["20"]
default: ["20"]

autoupdatedisable::
description: Lets you prevent Flash Player from automatically checking for and installing updated versions.
values: ["0", "1"]
default: ["1"]

autoupdateinterval::
description: (without meaning if AutoUpdateDisable=1) how often to check for an updated version of Flash Player

avhardwaredisable::
description: Lets you prevent SWF files from accessing webcams or microphones
values: ["0", "1"]
default: ["1"]

disabledevicefontenumeration::
description: Lets you prevent information on installed fonts from being displayed.
values: ["0", "1"]
default: ["1"]

fullscreendisable::
description: Lets you disable SWF files playing via a browser plug-in from being displayed in full-screen mode
values: ["0", "1"]
default: ["1"]

localfilereaddisable::
description: Lets you prevent local SWF files from having read access to files on local hard drives
values: ["0", "1"]
default: ["0"]

filedownloaddisable::
description: Lets you prevent the ActionScript FileReference API from performing file downloads
values: ["0", "1"]
default: ["0"]

fileuploaddisable::
description: Lets you prevent the ActionScript FileReference API from performing file uploads
values: ["0", "1"]
default: ["0"]

disableproductdownload::
description: Lets you prevent native code applications that are digitally signed and delivered by Adobe from being downloaded
values: ["0", "1"]
default: ["1"]

disablesockets::
description: enable or disable the use of the Socket.connect() and XMLSocket.connect() methods
values: ["0", "1"]
default: ["1"]

enablesocketsto::
description: Lets you create a whitelist of servers to which socket connections are allowed

enforcelocalsecurityinactivexhostapp::
description: Lets you enforce local security rules for a specified application.

legacydomainmatching::
description: Lets you specify whether SWF files produced for Flash Player 6 and earlier can execute an operation that has been restricted in a newer version of Flash Player
values: ["0", "1"]
default: ["0"]

localfilelegacyaction::
description: Lets you specify how Flash Player determines whether to execute certain local SWF files that were originally produced for Flash Player 7 and earlier
values: ["0", "1"]
default: ["0"]

allowuserlocaltrust::
description: Lets you prevent users from designating any files on local file systems
values: ["0", "1"]
default: ["0"]

localstoragelimit::
description: Lets you specify a hard limit on the amount of local storage that Flash Player uses (per domain) for persistent shared objects.
values: ["3"]
default: ["3"]

overridegpuvalidation::
description: Overrides validation of the requirements needed to implement GPU compositing
values: ["0", "1"]
default: ["0"]

rtmfpp2pdisable::
description: Specifies how the NetStream constructor connects to a server when a value is specified for peerID, the second parameter passed to the constructor
values: ["0", "1"]
default: ["1"]

disablenetworkandfilesysteminhostapp::
description: 1 (Acrobat.exe,Acroread.exe,WINWORD.EXE,EXCEL.EXE,POWERPNT.EXE,PPTVIEW.EXE,OUTLOOK.EXE,MSACCESS.EXE,VISIO.EXE,thunderbird.exe)
values: ["0", "1"]
default: ["1"]

* *Known problems:* +

- Installation "On Demand" may fail cause running browsers.

[[opsi-manual-abo-products-standard-google-chrome]]
===== Google Chromium for Business
----
google-chrome-for-business 56.0.2924.76-1
----

Uses the msi-installer (see Chrome for Business FAQ https://support.google.com/chrome/a/answer/188447?hl=en )

remarks:

Installing and uninstalling google-chrome.msi seems sometimes to hang.

There are several approaches working around this issue.

One customer reported  a quote of 100% successful Installations on 40 installations with the following property setting:

* `install_architecture`: 32
* `reboot_on_retry`: True
* `reboot_after_uninstall`: True
* `timeout`: 240

In our internal tests we work with:
* `install_architecture`: system specific
* `reboot_on_retry`: True
* `reboot_after_uninstall`: True
* `timeout`: notimeout


autoupdate:: !!! Will not work anymore!!!

https://support.google.com/chrome/a/answer/187207

ADM= use Policy based on Googles Template,
0=UpdatesDisabled,
1=UpdatesEnabled,
2=ManualUpdatesOnly,
3=AutomaticUpdatesOnly,
values: ["0", "1", "2", "3", "ADM"]
default: ["0"]

removeupdatehelper::
default: ["true"]

install_architecture::
description: which architecture (32/64 bit) has to be installed
values: ["32", "64", "system specific"]
default: ["system specific"]

reboot_on_retry::
description: If installation fails and (timeout > 0) then reboot before retry
default: False

reboot_after_uninstall::
description: reboot after uninstall old version
default: False

timeout::
description: TimeOutSeconds msi installs
values: ["240", "300", "600", "notimeout"]
default: ["notimeout"]

[[opsi-manual-abo-products-standard-openoffice]]
===== Apache OpenOffice : ooffice
----
ooffice                         4.1.3-1                   Apache OpenOffice
----

The ooffice-package contains Apache OpenOffice in german.

handle_excel_xls::

handle_powerpoint_ppt ::

handle_word_doc ::

remove_ooo2 ::

remove OpenOffice.org 2
 true  = OpenOffice.org 2 will be removed


[[opsi-manual-abo-products-standard-libreoffice]]
===== LibreOffice The Document Foundation  : libreoffice
----
libreoffice               5.1.6or5.2.5-1                   libreoffice
----

LibreOffice 5 international.

client_language ::

client_language - only for messages important, because libre office is international
values: ["auto", "de", "en", "fr"]

msoregister :: Open Microsoft Office documents with LibreOffice (true)
values: ["false", "true"]
default: ["false"]

libreoffice-version::
description: 'Stable' - is an Extended Support Release from LibreOffice for the conservative user - default version (5.1.6); 'Experimental' is a version for the experimental user from LibreOffice (5.2.5)
values: ["experimental", "stable"]
default: ["stable"]

hide_component::
description: Hide component base by removing desktoplink and exe file
values: ["base", "none"]
default: ["none"]

ui_languages::
description: which UI languages should be installed (comma separated), For example UI_LANGS=en_US,de,fr,hu will install English (US), German, French, and Hungarian.
default: ["auto"]

install_architecture:: which architecture (32/64 bit) has to be installed
values: ["32", "64", "system specific"]
default: ["32"]


[[opsi-manual-abo-products-standard-firefox]]
===== Mozilla Firefox : firefox
----
firefox                          45.7.0esror51.0.1-1
----
The firefox-package contains Mozilla Firefox german, englisch, french and dutch.

Customized configurations (see http://kb.mozillazine.org/Locking_preferences) can be edited in
[source,prompt]
----
/var/lib/opsi/depot/firefox/custom/
----

The entries for the property "mozillacfg" will be populated via preinst-/postinst-scripts when installing the opsi-package

- example
+
[source,prompt]
----
cat /var/lib/opsi/depot/firefox/custom/mozilla.cfg
//
lockPref("browser.startup.homepage", "http://www.uib.de");
lockPref("network.proxy.type", 1);
lockPref("network.proxy.http", "router.uib.local");
lockPref("network.proxy.http_port", 3128);
----

CAUTION: opsi WAN/VPN extension: The synchronization process is based on the file `<product-id>.files`. So any change in the `custom` share requires new installation of the package via `opsi-package-manager`.

client_language::
      values: ["auto", "de", "en", "fr", "nl"]
      default: ["auto"]

firefox-version :: Firefox 'esr' - is the Extended Support Release from Mozilla.org (45.7.0esr);  (51.0.1)     is the Mozilla.org standard version
values: ["esr", "esr", "standard"]
default: ["esr"]

pref_file:: (user/prefs)= use
user.js or prefs.js. values: ["prefs", "user"]
default: ["prefs"]

noautoupdate:: (on/off): disable auto update. default=on

setproxy:: (off/direct/manual/file) proxy settings
*  off= do nothing
*  direct = direct
*  manual = use proxy settings via property proxysetting
(<ip-numme>:<port>) and property noproxy_hosts (host1,host2)
*  file = use proxy settings via property proxysetting
(<path_to_proxyconf.pac>) and property noproxy_hosts (host1,host2)
* system
* default=off

proxysetting:: string for proxy setting (see: setproxy)

noproxy_hosts:: comma separated list of hosts

mozillacfg::
description: filename for mozilla.cfg in `%scriptpath%\custom`-directory, http://kb.mozillazine.org/Locking_preferences

profilemigrator:: enable or disable Profilemigrator on first run
values: ["off", "on"]
default: ["off"]

* *Known problems:* +
- Installation "On Demand" may fail cause running browsers.

[[opsi-manual-abo-products-standard-thunderbird]]
===== Mozilla Thunderbird : thunderbird
----
thunderbird               45.7.0-1
----
The thunderbird-package contains Mozilla Thunderbird in german, englisch and french.

Customized configurations (see http://kb.mozillazine.org/Locking_preferences) can provided analogous the firefox-Package and property "mozillacfg"


client_language::
values: ["auto", "de", "en", "fr"]
default: ["auto"]

thunderbird-version:: 45.7.0 - actual Thunderbird version
values: ["45.x"]
default: ["45.x"]

addonsactivation::
description: Enable/Disable AddOns (default = enable)
values: ["off", "on"]
default: ["on"]

https://developer.mozilla.org/en/Addons/Add-on_Manager/AddonManager

http://mike.kaply.com/2012/02/09/integrating-add-ons-into-firefox/

https://developer.mozilla.org/en/Thunderbird/Deploying_Thunderbird_in_the_Enterprise/Thunderbird_Preferences_Relevant_to_Enterprises
[source,prompt]
----
Set_Netscape_User_Pref ("extensions.autoDisableScopes", 11)
Set_Netscape_User_Pref ("extensions.shownSelectionUI", true)
----


enigmail::
description: Install GnuPG-Plugin
values: ["off", "on"]
default: ["off"]
----
Thunderbird 17.0. Enigmail 1.5.1
----

mozillacfg::
description: filename for mozilla.cfg in `%scriptpath%\custom`-directory, http://kb.mozillazine.org/Locking_preferences


noautoupdate::
description: disable automatic updates
values: ["off", "on"]
default: ["on"]

lightning::
description: Install calender plugin lightning
values: ["off", "on"]
default: ["off"]
----
Thunderbird 17.0.  Lightning 1.9.1
----

* *Known problems:* +
- Installation "On Demand" may fail if thunderbird is running.

[[opsi-manual-abo-products-standard-javavm]]
===== Oracle Jre : javavm
----
javavm              1.8.0.121-1        Oracle Java Run
----
The javavm-package contains Oracle Jre version 8.x ( cpu and psu, if available)
(see http://www.oracle.com/technetwork/java/javase/downloads/cpu-psu-explained-2331472.html)

(Oracle announced "End Of Public Updates Februar 2013"  http://www.oracle.com/technetwork/java/eol-135779.html)

http://www.oracle.com/technetwork/java/javase/jre-install-137694.html

Existing "Patch-in-place" Jre-versions 1.6.x, 7.x and 8.x will be uninstalled.
- Existing Oracle JRE with "Static configuration" will not be uninstalled
- Earlier Oracle JRE (version 1.6.0 - version 1.6.7) will be uninstalledby default. One can change this behavior using the property "keepversion".

Starting with 8u20 the jre8 will be installed in static mode

Customized configurations deployment.properties (see http://docs.oracle.com/javase/6/docs/technotes/guides/deployment/deployment-guide/properties.html
http://docs.oracle.com/javase/7/docs/technotes/guides/deployment/deployment-guide/properties.html) can be edited in
[source,prompt]
----
/var/lib/opsi/depot/javavm/custom/
----

The entries for the property "deployment.properties" will be populated via preinst-/postinst-scripts when installing the opsi-package
- example
 +
[source,prompt]
----
cat /var/lib/opsi/depot/javavm/custom/deployment.properties
//
#deployment.properties
#Tue Dec 18 12:36:01 CET 2012
deployment.javaws.autodownload=NEVER
deployment.javaws.autodownload.locked=
deployment.security.validation.ocsp=true
deployment.security.validation.ocsp.locked=
deployment.security.validation.crl=true
deployment.security.validation.crl.locked=

----


CAUTION: opsi WAN/VPN extension: The synchronization process is based on the file `<product-id>.files`. So any change in the `custom` share requires new installation of the package via `opsi-package-manager`.


install_architecture::
description: which architecture (32/64 bit) has to be installed
values: ["32 only", "64 only", "both", "system specific"]
default: ["both"]

javaversion::
description: which version has to be installed (JRE 8 = 1.8.x); jre8 1.8.0_121-b13 (CPU); jre8psu 1.8.0_12-b13 (CPU)
values: ["jre8", "jre8psu"]
default: ["jre8"]

keepversion::
description: Don't uninstall jre version
values: ["1.6.0_0", "1.6.0_1", "1.6.0_2", "1.6.0_3", "1.6.0_4", "1.6.0_5", "    1.6.0_6", "1.6.0_7", "none"]
default: ["none"]

webjava::
description: TESTING: http://java.com/en/download/help/silent_install.xml WEB_JAVA=0, if used, disables any Java application from running in the browser
values: ["0", "1", "none"]
default: ["none"]
 +
CAUTION: Setting WEB_JAVA=0 results in misleading browsermessages ("missing plugin")

uninstalljava16::
description: Uninstall Java 1.6 "Patch in Place" Installations
default: True

uninstalljava17::
description: Uninstall Java 1.7 "Patch in Place" Installations
default: True

deployment.properties::
description: filename for deployment.properties in %scriptpath%\custom-directory, http://docs.oracle.com/javase/7/docs/technotes/guides/deployment/deployment-guide/properties.html saved by pre- postinstscript

startmenuentry:: Create Entry for java in common startmenu aboutJava,CheckForUpdates,ConfigureJava,GetHelp,VisitJava.com
default: False

timeout:: TimeOutSeconds msi installs
values: ["180", "240", "300", "notimeout"]
default: ["300"]

copy.java.exe.to.system32:: Copy java.exe,javaw.exe, javaws.exe to system32
default: False

environment_set_java_home:: Set the environment variable JAVA_HOME
default: False



* *Known problems:* +

- Installation "On Demand" may fail due to running browsers.
