////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////
:Author:    uib gmbh
:Email:     info@uib.de
:Date:      12.05.2015
:Revision:  4.0.5
:toclevels: 6
:doctype:   book

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]

[[opsi-manual-abo-products-introduction]]
=== opsi subscriptions

[[opsi-manual-abo-products-introduction-firststeps]]
==== Initial Deployment of opsi subscriptons

Add the abo repositories to the '/etc/opsi/opsi-product-updater.conf'


[source,prompt]
----
[repository_abo_mshotfix]
baseUrl = http://download.uib.de
dirs = abo/mshotfix/opsi4/glb
active = false
username = <user>
password = <pass>
autoInstall = false
autoUpdate = true
autoSetup = false
onlyDownload = false 

[repository_abo_standard]
baseUrl = http://download.uib.de
dirs = abo/standard/opsi4
active = false
username = <user>
password = <pass>
autoInstall = false
autoUpdate = true
autoSetup = false
onlyDownload = false 

[repository_abo_msoffice]
baseUrl = http://download.uib.de
dirs = abo/msoffice/opsi4
active = false
username = <user>
password = <pass>
autoInstall = false
autoUpdate = true
autoSetup = false
onlyDownload = false 
----

Since opsi Version 4.0.5 one can choose specific packages via for instance

'opsi-product-updater -p "mshotfix,mshotfix-win7-x86-glb,mshotfix-win7-win2     008r2-x64-glb" -i '

for the mshotfix-packages for Windows 7.

Before opsi 4.0.5 one can download the opsi-packages and install them via `opsi-package-manager -p ask -i <paketname>.opsi` and set the default properties for the '{opsi-configserver}'. (Without the option `-p ask` the package defaults would be depot defaults)-  

Since opsi 4.0.5 it is possible to set the product-property defaults per depot with the managementinterface '{opsi-Configed}'

[[opsi-manual-abo-products-mshotfix]]
==== Subscription 'MS-Hotfixes'
Regular updates for the product MS-Hotfix (OS hotfixes for Windows XP to 2008R2).

The updates will be provided within 3 working days after Microsofts publication of important and critical patches.

This opsi-package is delivered via download area (restricted access).

http://technet.microsoft.com/en-us/security/gg309177.aspx
[source,prompt]
----

Rating	Definition
Critical	

A vulnerability whose exploitation could allow code execution without user interaction. These scenarios include self-propagating malware (e.g. network worms), or unavoidable common use scenarios where code execution occurs without warnings or prompts. This could mean browsing to a web page or opening email.

Microsoft recommends that customers apply Critical updates immediately.
Important	

A vulnerability whose exploitation could result in compromise of the confidentiality, integrity, or availability of user data, or of the integrity or availability of processing resources. These scenarios include common use scenarios where client is compromised with warnings or prompts regardless of the prompt's provenance, quality, or usability. Sequences of user actions that do not generate prompts or warnings are also covered.

Microsoft recommends that customers apply Important updates at the earliest opportunity.
Moderate	

Impact of the vulnerability is mitigated to a significant degree by factors such as authentication requirements or applicability only to non-default configurations.

Microsoft recommends that customers consider applying the security update.
Low	Impact of the vulnerability is comprehensively mitigated by the characteristics of the affected component. Microsoft recommends that customers evaluate whether to apply the security update to the affected systems.

----

The opsi-mshotfix package uses (like WSUS Offline Update http://forums.wsusoffline.net/viewtopic.php?f=7&t=172 Abdeckung des / Coverage of WSUS Offline Update ) Microsoft's wsusscn2.cab.
wsusscn2.cab delivers all „critical“ and „important“ updates, but not all "optional" updates.

The base-package „mshotfix“ contains the  master-script for installing the patches contained in the other mshotfix-packages.

CAUTION: mshotfix packages for on  Windows 8  / Window 2012 with Wan/VPN-extension opsi-client-agent >= 4.0.4.4-1.opsi

CAUTION: mshotfix packages for Windows 8.1 / Windows 2012 R2 requires opsi-winst >= opsi-winst_4.11.3.11-1.opsi and opsi-client-agent >= 4.0.4.4-1.opsi


.mshotfix Client-Requirements
|===================================
|OS|
|Windows XP|Service Pack 3
|Windows 2003 / Windows XP 64bit|Service Pack 2
|Windows Vista / Windows 2008 |Service Pack 2
|Windows 7 / Windows 2008 R2|Servicepack 1
|Windows 8 / Windows 2012|
|Windows 8.1 / Windows 2012 R2|
|====================================

Structure of the download area:


[source,configfile]
----
mshotfix
  !-opsi4/
     !-glb/	Base-package mshotfix  and global packages
     		mshotfix-vista-win2008-x86-glb, 
     		mshotfix-vista-win2008-x64-glb , 
     		mshotfix-win7-x86-glb, 
     		mshotfix-win7-win2008r2-x64-glb
     		mshotfix-win8-x86-glb
     		mshotfix-win81-x86-glb
     		mshotfix-win8-win2012-x64-glb
			mshotfix-win81-win2012r2-x64-glb
     !-deu/	
     		mshotfix-winxp-x86-deu , 
     		mshotfix-win2003-x86-deu
     !-enu/	
     !-fra/
     !-ita/
----

.mshotfix Client-OS
|=======================
|OS|Arch. Language|Patch-package
|Windows XP SP3 |  32Bit Deutsch | mshotfix-winxp-x86-deu
|Windows XP SP2 | 64Bit Englisch | mshotfix-win2003-winxp-x64-enu
|Windows 2003 SP2 | 32Bit Deutsch | mshotfix-win2003-x86-deu
|Windows 2003 SP2 | 64Bit Englisch | mshotfix-win2003-winxp-x64-enu
|Windows Vista SP2 | 32Bit | mshotfix-vista-win2008-x86-glb
|Windows Vista SP2 | 64Bit | mshotfix-vista-x64-glb
|Windows 7 | 32Bit | mshotfix-win7-x86-glb
|Windows 7 | 64Bit | mshotfix-win7-win2008r2-x64-glb
|Windows 8 | 32Bit | mshotfix-win8-x86-glb
|Windows 8 | 64Bit | mshotfix-win8-win2012-x64-glb
|Windows 8.1 | 32Bit | mshotfix-win81-x86-glb
|Windows 8.1 | 64Bit | mshotfix-win81-win2012r2-x64-glb
|Windows 2008 Server | 32Bit | mshotfix-vista-win2008-x86-glb
|Windows 2008 Server | 64Bit | mshotfix-vista-win2008-x64-glb
|Windows 2008 Server R2 | 64Bit | mshotfix-win7-win2008r2-x64-glb
|Windows 2012 | 64Bit | mshotfix-win8-win2012-x64-glb
|Windows 2012 R2 | 64Bit | mshotfix-win81-win2012r2-x64-glb
|=======================

Since mshotfix 201304-1 a list of installed patches is saved in file

`C:\opsi.org\mshotfix\deployed.txt`

noreboot:: noreboot=on: Don't Reboot.  Warning will be logged if a reboot     is required.  Should be "on" for Server.
values: ["off", "on"]
default: ["off"]


force:: force=on: All Hotfixes will be installed forced
values: ["off", "on"]
default: ["off"]

excludes::  Commaseparated list with kb-numbers or ms-no, that will be excluded (Only Number without beginning kb and no spaces. Example: 123456,789011,2222)
 Browser Choice update? (KB976002)

severity:: choose the severity that will be installed. Possible Entries are Critical, Important, Moderate, all
values: ["Critical", "Important", "Moderate", "all"]
default: ["Critical", "Important"]

[[opsi-manual-abo-products-ms-Officehotfixes]]

====  Update subscription for 'MS-Office Hotfixes'

Regular updates for the product:

    Ms-Office 2010 (32 Bit International)

The updates will be provided within 3 working days after Microsoft's publication of important and critical patches.


[[opsi-manual-abo-products-office_2010_hotfix]]
===== Updates for MS Office 2010 32-bit international: office_2010_hotfix
----
office_2010_hotfix               201210-2                  Microsoft Office 2010 Hotfixes
----

Containes global Office 2010 patches (inclusive Visio and Project 2010) . Requires Servicepack 1.

Since office_2010_hotfix 201305-2 a list of installed patches is saved in file

`C:\opsi.org\mshotfix\office_2010_hotfix_deployed`

SinceSeit office_2010_hotfix 201503-1:

excludes:: Commaseparated list with kb-numbers or ms-no, that will be excluded (Only Number without beginning kb and no spaces. Example: 2553154,ms14-082)

[[opsi-manual-abo-products-office_2013_hotfix]]
===== Updates for MS Office 2013 32-bit international: office_2013_hotfix
----
office_2013_hotfix               201401-1                  Microsoft Office 2013 Hotfixes
----

Containes global Office 2013 patches (inclusive Visio 2013) .

A list of installed patches is saved in file

`C:\opsi.org\mshotfix\office_2013_hotfix_deployed`


Since office_2010_hotfix 201503-1:

excludes:: Commaseparated list with kb-numbers or ms-no, that will be excluded (Only Number without beginning kb and no spaces. Example: 2553154,ms14-082)

[[opsi-manual-abo-products-standard]]
==== Update subscription for the opsi standard packets


    Adobe Acrobat Reader (german, english and french / 32 Bit)
    Adobe Flashplayer (international / 32 Bit / 64 Bit)
    Apache OpenOffice.org (german / 32 Bit)
    Google Chromium for business ( international 32 Bit /64 Bit )
    LibreOffice (international / 32 Bit)
    Mozilla Firefox (dutch, german, english and french / 32 Bit)
    Mozilla Thunderbird (german, english and french / 32 Bit)
    Oracle Java VM (international / 32 Bit / 64 Bit)
    
    Depending on your contracts we offer the subscriptions with:  
    
    Adobe Acrobat Reader (in addition dutch and italian / 32 Bit)
    Adobe Acrobat Reader XI (in addition danish, dutch, italian and spanish / 32 Bit)
    Mozilla Firefox (in addition danish, italian or spanish / 32 Bit)
    Mozilla Thunderbird (in addition italian / 32 Bit)

    further languages can be asked for.

    The updates will be provided within 2 working weeks after manufacturers release. For critical security patches the opsi packet will be provided within 1 working week after the patch release.

===== Customizing with central configuration files

For the opsi-packages
----
acroread
acroread11
adobe.reader.dc.classic
firefox
flashplayer 
javavm
thunderbird
----

one can provide configuration files and populate them via product-properties (for details see the relevant chapters)

===== Customizing with preinst/postinst-scripts

For the opsi-packages
----
acroread11 	(since 11.0.3-1)
adobe.reader.dc.classic
firefox		(since 17.0.6esrorstandard-1)
flashplayer	(since 13.0.0.182or11.7.700.275-1)
google-chrome-for-business
javavm		(since 1.7.0.51-4 )
libreoffice	(since 4.3.5or4.4.0-2)
ooffice		(since 4.1.1-2)
thunderbird	(since 17.0.6esrorstandard-1)
----

one can use custom-scripts in directory `custom\scripts`

Simple templates can be found in directory `opsi\scripts`

[source,configfile]
----

custom.actions.post.setup
custom.actions.post.uninstall
custom.actions.pre.setup
custom.actions.pre.uninstall
custom.declarations
custom.sections

custom scripts will be included at
- setup-script 
- uninstall-script

custom pre-scripts will be included in
- setup-script 
- uninstall-script

custom post-scripts will be included in
- in setup-script
- uninstall-script

custom.declarations
; intended for declaration of custom Variables and Stringlist Variables
; will be included with "include_insert" at top of [actions] 
; but after GetProductProperties

custom.sections
; intended for declaration of custom secondary sections
; will be included with "include_append" at top of [actions]
; but after GetProductProperties

custom.actions.pre.setup  (or custom.actions.pre.uninstall)
; will be included with "include_insert" at top of [actions]
; (but after GetProductProperties)

custom.actions.post.setup (or custom.actions.post.uninstall)
; will be included with "include_insert" in case of successfull installation before "endof_"actions"
; in setup-script ( or uninstall-script)

----


===== Adobe Acrobat Document Cloud Classic : adobe.reader.dc.classic
----
adobe.reader.dc.classic	20151500630033-3          Adobe Acrobat Reader dc
----

The adobe.reader.dc.classic-Paket contains Adobe Acrobat Document Cloud Classic ( MUI-Version )

Adaptation in the transform file *.mst
[source,prompt]
----
cat transform.txt
Changes vs default the transform file *.mst

Personalisation Options
Suppress Eula

Installation Options
acivated - Make Reader the default PDF viewer
IF REBOOT REQUIRED - suppress reboot


Shortcuts
deactivated - Destination Computer/Desktop/Adobe Reader XI (Icon)


Online and Acrobat.com Features
Online Features
activated - Disable product updates
Enable & Ask before Installing - Load trustet root certificates from Adobe

Online Services and Features
disable product updates
Load trusted root certificates from Adobe disable
DISABLE all Services
----

adobereader.mst::

The Adobe Reader package uses a default transform
build with the Adobe Customization Wizard.
Own mst-files could be placed in the share `opsi_depot` in
`/var/lib/opsi/depot/adobe.reader.dc.classic/custom`
During the installation via `opsi-package-manager -i <adobe.reader.dc.classic>` the directory custom ueber will preserved by the preinst/postinst-scripts and the names of any mst-file in the custom-directory will be appear as a possible propertyentry. 

CAUTION: opsi WAN/VPN extension: The synchronization process is based on the file `<product-id>.files`. 
So any change in the `custom` share requires new installation of the package via the opsi-package-manager

client_language::

The adobe.reader.dc.classic-package contains Adobe Acrobat Document Cloud Classic ( MUI-Version )
"auto" tries to install the correct language. values: ["auto", "de", "en", "fr" ]  default: ["auto"]

noreboot:: 

description: noreboot=true: Don't Reboot.  Warning will be logged if a reboot is required.
values: ["false", "true"]
default: ["false"]





===== Adobe Acrobat Reader XI : acroread11
----
acroread11                11.0.10-1                  Adobe Reader 11
----
End of core support (https://www.adobe.com/support/products/enterprise/eol/eol_matrix.html#864) 10/15/2017

The acroread-package contains Acrobat Reader XI in german, english and french.

Adaptation in the transform file *.mst
[source,prompt]
----
Installation Options
acivated - Make Reader the default PDF viewer


Shortcuts
deactivated - Destination Computer/Desktop/Adobe Reader XI (Icon)


Online and Acrobat.com Features
Online Features
activated - Disable product updates
Enable & Ask before Installing - Load trustet root certificates from Adobe

Adobe Online Service Integration
activated - Disable all Adobe online services based workflows an entry points
----

adobereader.mst::

The Adobe Reader package uses a default transform
build with the Adobe Customization Wizard.
Own mst-files could be placed in the share `opsi_depot` in
`/var/lib/opsi/depot/acroread11/custom`
During the installation via `opsi-package-manager -i <acroread11>` the directory custom ueber will preserved by the preinst/postinst-scripts and the names of any mst-file in the custom-directory will be appear as a possible propertyentry. 

CAUTION: opsi WAN/VPN extension: The synchronization process is based on the file `<product-id>.files`. 
So any change in the `custom` share requires new installation of the package via the opsi-package-manager

client_language::

The acroread11-package contains Acrobat Reader X in german, english and french.
"auto" tries to install the correct language. values: ["auto", "de", "en", "fr" ]  default: ["auto"]

protectedmode::

Enable Adobe Reader Protected Mode values: ["off", "on", "userchoice"] default: ["on"]

misc::
provides additional fonts

* AdbeRdrSD11000_all.msi : Adobe Reader XI Spelling Dictionary Pack

* FontPack11000_XtdAlf_Lang.msi: Adobe Reader XI Font Packs - Asian and Extended Language Pack

values: ["AdbeRdrSD11000_all.msi", "FontPack11000_XtdAlf_Lang.msi", "none"]
default: ["none"]

noreboot:: 

description: noreboot=true: Don't Reboot.  Warning will be logged if a reboot is required.
values: ["false", "true"]
default: ["false"]



[[opsi-manual-abo-products-standard-acroread]]
===== Adobe Acrobat Reader X : acroread
----
acroread                  10.1.13-1                  Adobe Reader 10
----
End of core support (https://www.adobe.com/support/products/enterprise/eol/eol_matrix.html#864
The acroread-package contains Acrobat Reader X in german, english and french.

Adaptation in the transform file *.mst
[source,prompt]
----
Installation Options
acivated - Make Reader the default PDF viewer

Shortcuts
deactivated - Destination Computer/Desktop/Adobe Reader X (Icon)

Online and Acrobat.com Features
Online features
activated - Disable all updates

Acrobat.com Features
activated - Disable only Upload and Share documents to Acrobat.com
----

adobereader.mst::

The Adobe Reader package uses a default transform
build with the Adobe Customization Wizard.
Own mst-files could be placed in the share `opsi_depot` in
`/var/lib/opsi/depot/acroread/custom`
During the installation via `opsi-package-manager -i <acroread>` the directory custom ueber will preserved by the preinst/postinst-scripts and the names of any mst-file in the custom-directory will be appear as a possible propertyentry.

CAUTION: opsi WAN/VPN extension: The synchronization process is based on the file `<product-id>.files`. 
So any change in the `custom` share requires new installation of the package via the opsi-package-manager

client_language::

The acroread-package contains Acrobat Reader X in german, english and french.
"auto" tries to install the correct language. values: ["auto", "de", "en", "fr" ]  default: ["auto"]

desctopicon::

Place  an icon on the desktop. values: ["off", "on"] default: ["off"]

protectedmode::

Enable Adobe Reader Protected Mode values: ["off", "on", "userchoice"] default: ["on"]

misc::

provides additional fonts
* AdbeRdrSD1000_all.msi : Adobe Reader X Spelling Dictionary Pack 
(http://www.adobe.com/support/downloads/detail.jsp?ftpID=4859)
* FontPack1000_Xtd_Lang.msi: Adobe Reader X Font Packs - extended 
languages (http://www.adobe.com/support/downloads/detail.jsp?ftpID=4885)
                This Font Pack supports Hebrew, Arabic, Thai, and 
Vietnamese as well as the Eastern and Central European languages 
(including Cyrillic and Greek scripts)
* FontPack1000_ja_JP.msi: Adobe Reader X Font Packs - Japanese 
(http://www.adobe.com/support/downloads/detail.jsp?ftpID=4881).

values: ["AdbeRdrSD1000_all.msi", "FontPack1000_Xtd_Lang.msi", 
"FontPack1000_ja_JP.msi", "FontPack1000_ko_KR.msi", 
"FontPack1000_zh_CN.msi", "FontPack1000_zh_TW.msi", "none"]
default: ["none"]

[[opsi-manual-abo-products-standard-flashplayer]]
===== Adobe Flashplayer : flashplayer
----
flashplayer                      13.0.0.277-1 Adobe Flashplayer
----
The flashplayer-package contains Adobe Flashplayer standard or the Extended Support Release

flashplayer-version:: Flashplayer standard as default; Version esr ( Extended Support Release http://blogs.adobe.com/flashplayer/2014/03/upcoming-changes-to-flash-players-extended-support-release.html )

values: esr, standard
default: standard

mms.cfg::

The configuration file mms.cfg

will be created during "setup" and patched according the properties below.

Since Version 13.0.0.250-2 one can use custom `mms.cfg` files in the share `opsi_depot` in
`/var/lib/opsi/depot/flashplayer/custom`
 
During the installation via `opsi-package-manager -i <flashplayer>` the directory custom ueber will preserved by the preinst/postinst-scripts and the names of any mms.cfg-file in the custom-directory will be appear as a possible propertyentry.

CAUTION: opsi WAN/VPN extension: The synchronization process is based on the file `<product-id>.files`.
So any change in the `custom` share requires new installation of the package via the opsi-package-manager

mms.cfg::
`/var/lib/opsi/depot/flashplayer/custom` custom mms.cfg-files.

Only the property autoupdatedisable will be populated if custom `mms.cfg` are used


.Adobe Flashplayer Admin Guide:

[source,prompt]
----

flash_player_11_1_admin_guide.pdf (flash_player_admin_guide.pdf)

#####################################
Chapter 4: Administration

You can create and place files on the end user’s machine to manage 
features related to security, privacy, use of disk
space, and so on.

Privacy and security settings (mms.cfg)

As a network administrator, you can install Flash Player across the 
enterprise while enforcing some common global
security and privacy settings (supported with installation-time 
configuration choices). To do this, you install a file
named mms.cfg on each client machine.

The mms.cfg file is a text file. When Flash Player starts, it reads its 
settings from this file, and uses them to manage
functionality as described in the following sections.

mms.cfg file location

Assuming a default Windows installation, Flash Player looks for the 
mms.cfg file in the following system directories:

32-bit Windows - %WINDIR%\System32\Macromed\Flash

64-bit Windows - %WINDIR%\SysWow64\Macromed\Flash

Note: The %WINDIR% location represents the Windows system directory, 
such as C:\WINDOWS.

----

assetcachesize::
description: hard limit, in MB, on the amount of local storage that Flash Player uses for the storage of common Flash components
values: ["20"]
default: ["20"]

autoupdatedisable::
description: Lets you prevent Flash Player from automatically checking for and installing updated versions.
values: ["0", "1"]
default: ["1"]

autoupdateinterval::
description: (without meaning if AutoUpdateDisable=1) how often to check for an updated version of Flash Player

avhardwaredisable::
description: Lets you prevent SWF files from accessing webcams or microphones
values: ["0", "1"]
default: ["1"]

disabledevicefontenumeration::
description: Lets you prevent information on installed fonts from being displayed.
values: ["0", "1"]
default: ["1"]

fullscreendisable::
description: Lets you disable SWF files playing via a browser plug-in from being displayed in full-screen mode
values: ["0", "1"]
default: ["1"]

localfilereaddisable::
description: Lets you prevent local SWF files from having read access to files on local hard drives
values: ["0", "1"]
default: ["0"]

filedownloaddisable::
description: Lets you prevent the ActionScript FileReference API from performing file downloads
values: ["0", "1"]
default: ["0"]

fileuploaddisable::
description: Lets you prevent the ActionScript FileReference API from performing file uploads
values: ["0", "1"]
default: ["0"]

disableproductdownload::
description: Lets you prevent native code applications that are digitally signed and delivered by Adobe from being downloaded
values: ["0", "1"]
default: ["1"]

disablesockets::
description: enable or disable the use of the Socket.connect() and XMLSocket.connect() methods
values: ["0", "1"]
default: ["1"]

enablesocketsto::
description: Lets you create a whitelist of servers to which socket connections are allowed

enforcelocalsecurityinactivexhostapp::
description: Lets you enforce local security rules for a specified application.

legacydomainmatching::
description: Lets you specify whether SWF files produced for Flash Player 6 and earlier can execute an operation that has been restricted in a newer version of Flash Player
values: ["0", "1"]
default: ["0"]

localfilelegacyaction::
description: Lets you specify how Flash Player determines whether to execute certain local SWF files that were originally produced for Flash Player 7 and earlier
values: ["0", "1"]
default: ["0"]

allowuserlocaltrust::
description: Lets you prevent users from designating any files on local file systems
values: ["0", "1"]
default: ["0"]

localstoragelimit::
description: Lets you specify a hard limit on the amount of local storage that Flash Player uses (per domain) for persistent shared objects.
values: ["3"]
default: ["3"]

overridegpuvalidation::
description: Overrides validation of the requirements needed to implement GPU compositing
values: ["0", "1"]
default: ["0"]

rtmfpp2pdisable::
description: Specifies how the NetStream constructor connects to a server when a value is specified for peerID, the second parameter passed to the constructor
values: ["0", "1"]
default: ["1"]

disablenetworkandfilesysteminhostapp::
description: 1 (Acrobat.exe,Acroread.exe,WINWORD.EXE,EXCEL.EXE,POWERPNT.EXE,PPTVIEW.EXE,OUTLOOK.EXE,MSACCESS.EXE,VISIO.EXE,thunderbird.exe)
values: ["0", "1"]
default: ["1"]

* *Known problems:* +

- Installation "On Demand" may fail cause running browsers.

[[opsi-manual-abo-products-standard-google-chrome]]
===== Google Chromium for Business
----
google-chrome-for-business 41.0.2272.89-1
----

Uses the msi-installer (see Chrome for Business FAQ https://support.google.com/chrome/a/answer/188447?hl=en )

remarks:

Installing and uninstalling google-chrome.msi seems sometimes to hang.

There are several approachs working around this issue.

One customer reported  a quote of 100% successfull Installations on 40 installations with the following property setting:

install_architecture: 32
reboot_on_retry: True
reboot_after_uninstall: True
timeout: 240

In our internal tests we work with:
install_architecture: system specific
reboot_on_retry: True
reboot_after_uninstall: True
timeout: notimeout


autoupdate:: !!! Will not work anymore!!!

https://support.google.com/chrome/a/answer/187207

ADM= use Policy based on Googles Template,
0=UpdatesDisabled,
1=UpdatesEnabled,
2=ManualUpdatesOnly,
3=AutomaticUpdatesOnly,
values: ["0", "1", "2", "3", "ADM"]
default: ["0"]

removeupdatehelper::
default: ["true"]

install_architecture::
description: which architecture (32/64 bit) has to be installed
values: ["32", "64", "system specific"]
default: ["system specific"]

reboot_on_retry::
description: If installation fails and (timeout > 0) then reboot before retry
default: False

reboot_after_uninstall::
description: reboot after uninstall old version
default: False

timeout::
description: TimeOutSeconds msi installs
values: ["240", "300", "600", "notimeout"]
default: ["notimeout"]

[[opsi-manual-abo-products-standard-openoffice]]
===== Apache OpenOffice : ooffice
----
ooffice                         4.1.1-2                   Apache OpenOffic
----

The ooffice-package contains Apache OpenOffice in german.

handle_excel_xls::

handle_powerpoint_ppt ::

handle_word_doc ::

remove_ooo2 ::

remove OpenOffice.org 2 
 true  = OpenOffice.org 2 will be removed 


[[opsi-manual-abo-products-standard-libreoffice]]
===== LibreOffice 3 The Document Foundation  : libreoffice
----
libreoffice               4.3.6or4.4.1-2                   libreoffice
----

LibreOffice 3 international.

client_language ::

client_language - only for messages important, cause libre office is international
values: ["auto", "de", "en", "fr"]

msoregister :: Open Microsoft Office documents with LibreOffice (true)
values: ["false", "true"]
default: ["false"]

libreoffice-version::
description: 'Stable' - is an Extended Support Release from LibreOffice for the conservative user - default version (4.2.6.6); 'Experimentell' is a version for the experimentell user from LibreOffice (4.3.1)
values: ["experimentell", "stable"]
default: ["stable"]

hide_component::
description: Hide component base by removing desctoplink and exe file
values: ["base", "none"]
default: ["none"]


[[opsi-manual-abo-products-standard-firefox]]
===== Mozilla Firefox : firefox
----
firefox                          31.5.0esrorstandard-2
---- 
The firefox-package contains Mozilla Firefox german, englisch, french and dutch.

Customized configurations (see http://kb.mozillazine.org/Locking_preferences) can provided in  
[source,prompt]
----
/var/lib/opsi/depot/firefox/custom/
----

The entries for the property "mozillacfg" will be populated via preinst-/postinst-scripts when installing the opsi-package 

- example

[source,prompt]
----
cat /var/lib/opsi/depot/firefox/custom/mozilla.cfg
//
lockPref("browser.startup.homepage", "http://www.uib.de");
lockPref("network.proxy.type", 1);
lockPref("network.proxy.http", "router.uib.local");
lockPref("network.proxy.http_port", 3128);
----

CAUTION: opsi WAN/VPN extension: The synchronization process is based on the file `<product-id>.files`. 
So any change in the `custom` share requires new installation of the package via the opsi-package-manager

client_language::
      values: ["auto", "de", "en", "fr", "nl"]
      default: ["auto"]

firefox-version :: Firefox '17.0esr' - is the Extended Support Release from Mozilla.org (17.0.9esr) as default version; Firefox '24.0esr' - is the new Extended Support Release from Mozilla.org (24.0esr); 'standard' (24.0) is the Mozilla.org standard version
values: ["17.0esr", "24.0esr", "standard"]
default: ["17.0esr"]

pref_file:: (user/prefs)= use
user.js or prefs.js. values: ["prefs", "user"]
default: ["prefs"]

noautoupdate:: (on/off): disable auto update. default=on

setproxy:: (off/direct/manual/file) proxy settings
*  off= do nothing
*  direct = direct 
*  manual = use proxy settings via property proxysetting
(<ip-numme>:<port>) and property noproxy_hosts (host1,host2)
*  file = use proxy settings via property proxysetting
(<path_to_proxyconf.pac>) and property noproxy_hosts (host1,host2)
* system
* default=off

proxysetting:: string for proxy setting (see: setproxy)

noproxy_hosts:: comma separated list of hosts

mozillacfg::
description: filename for mozilla.cfg in `%scriptpath%\custom`-directory, http://kb.mozillazine.org/Locking_preferences

profilemigrator:: enable or disable Profilemigrator on first run
values: ["off", "on"]
default: ["off"]

* *Known problems:* +
- Installation "On Demand" may fail cause running browsers.

[[opsi-manual-abo-products-standard-thunderbird]]
===== Mozilla Thunderbird : thunderbird
----
thunderbird               31.5.0-1
----
The thunderbird-package contains Mozilla Thunderbird in german, englisch and french.

Customized configurations (see http://kb.mozillazine.org/Locking_preferences) can provided analogous the firefox-Package and property "mozillacfg"


client_language::
values: ["auto", "de", "en", "fr"]
default: ["auto"]

thunderbird-version:: Thunderbird '17.0esr' - is the Extended Support Release from Mozilla.org (17.0.9esr)(default); 'standard' (24.0) is the Mozilla.org standard version
values: ["17.0esr", "standard"]
default: ["17.0esr"]

addonsactivation::
description: Enable/Disable AddOns (default = enable)
values: ["off", "on"]
default: ["on"]

https://developer.mozilla.org/en/Addons/Add-on_Manager/AddonManager

http://mike.kaply.com/2012/02/09/integrating-add-ons-into-firefox/

https://developer.mozilla.org/en/Thunderbird/Deploying_Thunderbird_in_the_Enterprise/Thunderbird_Preferences_Relevant_to_Enterprises
[source,prompt]
----
Set_Netscape_User_Pref ("extensions.autoDisableScopes", 11)
Set_Netscape_User_Pref ("extensions.shownSelectionUI", true)
----


enigmail::
description: Install GnuPG-Plugin
values: ["off", "on"]
default: ["off"]
----
Thunderbird 17.0. Enigmail 1.5.1
----

mozillacfg::
description: filename for mozilla.cfg in `%scriptpath%\custom`-directory, http://kb.mozillazine.org/Locking_preferences


noautoupdate::
description: disable automatic updates
values: ["off", "on"]
default: ["on"]

lightning::
description: Install calender plugin lightning
values: ["off", "on"]
default: ["off"]
----
Thunderbird 17.0.  Lightning 1.9.1
----

* *Known problems:* +
- Installation "On Demand" may fail cause running thunderbird.

[[opsi-manual-abo-products-standard-javavm]]
===== Oracle Jre : javavm
----
javavm              1.7.0.75-4        Oracle Java Run
----
The javavm-package contains Oracle Jre version 7.x ( cpu und psu) and 8.x
(see http://www.oracle.com/technetwork/java/javase/downloads/cpu-psu-explained-2331472.html)

( Oracle announced "End Of Public Updates Februar 2013"  http://www.oracle.com/technetwork/java/eol-135779.html )

The Oracle JRE will be installed with "Patch-in-place configuration" (since jre 1.6.0_10 ) 

http://www.oracle.com/technetwork/java/javase/jre-install-137694.html

Existing "Patch-in-place" Jre-versions 1.6.x, 7.x and 8.x will be uninstalled.
- Existing Oracle JRE with "Static configuration" will not be uninstalled
- Earlier Oracle JRE (version 1.6.0 - version 1.6.7) will be uninstalledby default. One can change this behaviour using the property "keepversion". 

Starting with 8u20 the jre8 will be installet in static mode

Customized configurations deployment.properties (see http://docs.oracle.com/javase/6/docs/technotes/guides/deployment/deployment-guide/properties.html
http://docs.oracle.com/javase/7/docs/technotes/guides/deployment/deployment-guide/properties.html) can provided in  
[source,prompt]
----
/var/lib/opsi/depot/javavm/custom/
----

The entries for the property "deployment.properties" will be populated via preinst-/postinst-scripts when installing the opsi-package 
- example

[source,prompt]
----
cat /var/lib/opsi/depot/javavm/custom/deployment.properties
//
#deployment.properties
#Tue Dec 18 12:36:01 CET 2012
deployment.javaws.autodownload=NEVER
deployment.javaws.autodownload.locked=
deployment.security.validation.ocsp=true
deployment.security.validation.ocsp.locked=
deployment.security.validation.crl=true
deployment.security.validation.crl.locked=

----


CAUTION: opsi WAN/VPN extension: The synchronization process is based on the file `<product-id>.files`. 
So any change in the `custom` share requires new installation of the package via the opsi-package-manager


install_architecture::
description: which architecture (32/64 bit) has to be installed
values: ["32 only", "64 only", "both", "system specific"]
default: ["both"]

javaversion::
description: which version has to be installed (JRE 1.8.x or JRE 7 = 1.7.x)
values: ["jre7", "jre7psu", "jre8"]
default: ["jre7"]

keepversion::
description: Dont uninstall jre version
values: ["1.6.0_0", "1.6.0_1", "1.6.0_2", "1.6.0_3", "1.6.0_4", "1.6.0_5", "    1.6.0_6", "1.6.0_7", "none"]
default: ["none"]

webjava::
description: TESTING: http://java.com/en/download/help/silent_install.xml WEB_JAVA=0, if used, disables any Java application from running in the browser
values: ["0", "1", "none"]
default: ["none"]

CAUTION: Setting WEB_JAVA=0 results in misleading browsermessages ("missing plugin")


deployment.properties::
description: filename for deployment.properties in %scriptpath%\custom-directory, http://docs.oracle.com/javase/7/docs/technotes/guides/deployment/deployment-guide/properties.html saved by pre- postinstscript

uninstalljava16:: Uninstall Java 1.6 "Patch in Place" Installations
default: True

startmenuentry:: Create Entry for java in common startmenu aboutJava,CheckForUpdates,ConfigureJava,GetHelp,VisitJava.com
default: False

timeout:: TimeOutSeconds msi installs 
values: ["180", "240", "300", "notimeout"]
default: ["300"]

copy.java.exe.to.system32:: Copy java.exe,javaw.exe, javaws.exe to system32
default: False


* *Known problems:* +

- Installation "On Demand" may fail cause running browsers.  


