////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib gmbh
:Email:     info@uib.de
:Date:      29.08.20185
:Revision:  4.0.7
:toc:
:numbered:
:website: http://opsi.org


include::../common/opsi_terms.asciidoc[]


[[opsi-manual-ucs]]
=== Notes on file structure on UCS 4.X systems

Compared to Ubuntu or Debian the files of the opsi-linux-bootimage are stored in another directory, namely:
[source,prompt]
----
/var/lib/univention-client-boot
----
Earlier versions of the opsi-linux-bootimage package had filesn stored in the directory `/tftpboot/linux` and linked the content to `/var/lib/univention-client-boot`. This changed with the release of opsi 4.1. the opsi-linux-bootimage of opsi 4.1 directley installs the files into `/var/lib/univention-client-boot`. After the `opsi-atftpd` received a patch to support files larger than 90MiB the opsi 4.1 opsi-linux-bootimage adapted to opsi 4.0.
The file structure looks like this:
[source,prompt]
----
 ls -l /var/lib/univention-client-boot/
insgesamt 224424
-rw-rw-r-- 1 997 OPSI Depot Servers     12372 Aug 13 13:13 chain.c32
lrwxrwxrwx 1 997 OPSI Depot Servers        15 Aug 13 13:13 install -> vmlinuz-4.17.13
lrwxrwxrwx 1 997 OPSI Depot Servers        11 Aug 13 13:13 install64 -> install-x64
lrwxrwxrwx 1 997 OPSI Depot Servers        19 Aug 13 13:13 install-x64 -> vmlinuz-x64-4.17.13
-rw-rw-r-- 1 997 OPSI Depot Servers     52272 Aug 13 13:13 menu.c32
-rw-rw-r-- 1 997 OPSI Depot Servers 105388996 Aug 13 13:13 miniroot-20180813.bz2
lrwxrwxrwx 1 997 OPSI Depot Servers        21 Aug 13 13:13 miniroot.bz2 -> miniroot-20180813.bz2
-rw-rw-r-- 1 997 OPSI Depot Servers 108394052 Aug 13 13:13 miniroot-x64-20180813.bz2
lrwxrwxrwx 1 997 OPSI Depot Servers        25 Aug 13 13:13 miniroot-x64.bz2 -> miniroot-x64-20180813.bz2
-rw-rw-r-- 1 997 OPSI Depot Servers     15710 Aug 13 13:13 pxelinux.0
drwxrwxr-x 2 997 OPSI Depot Servers      4096 Aug 28 19:19 pxelinux.cfg
-rw-rw-r-- 1 997 OPSI Depot Servers   7763664 Aug 13 13:13 vmlinuz-4.17.13
-rw-rw-r-- 1 997 OPSI Depot Servers   8166656 Aug 13 13:13 vmlinuz-x64-4.17.13
----

If the inetd service is used to control the `opsi-atftpd` the `tftp` line in the file `/etc/inetd.conf` has to look as follows:
[source,prompt]
----
tftp dgram udp wait nobody /usr/sbin/tcpd /usr/sbin/in.tftpd --tftpd-timeout 300 --retry-timeout 5 --verbose=5 /var/lib/univention-client-boot
----
On the other hand if the inetd service is not used, and the `opsi-atftpd` is used directly the configuration file `/etc/default/atftpd` need to have the following content:
[sourece,prompt]
----
USE_INETD=false
OPTIONS="--daemon --port 69 --tftpd-timeout 300 --retry-timeout 5     --mcast-port 1758 --mcast-addr 239.239.239.0-255 --mcast-ttl 1 --maxthread 100 --verbose=5  /var/lib/univention-client-boot"
----
In opsi 4.1 the `opsi-tftpd-hpa` obsoleted `opsi-atftpd` and directly patches the service file to have the correct 'TFTPROOT' directory.

In addition UCS 4.X needs a DHCP policy to support a PXE Boot. This policy can be found in the Policies section of the domain settings. Hereby the boot server need to be entered whereby the IP address represents the boot server and the file 'pxelinux.0' is the boot filename.
