////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib gmbh
:Email:     info@uib.de
:Date:      20.07.2015
:Revision:  4.0.6
:toc:
:numbered:
:website: http://opsi.org


include::../common/opsi_terms.asciidoc[]


[[opsi-manual-samba4]]
=== Remarks to Samba 4

With the stable state of Samba4, the development and maintenance for the Samba3 branch has been discontinued. Therefore most of the common Linux distributions (client and server) now contain Samba4 instead of Samba3. Samba shares are a basic component for the opsi system and there are some opsi relevant differences between Samba3 and Samba4, that are discussed in this chapter.

At first it has to be distinguished, in which operational mode Samba is executed. A special feature of Samba4 is the ability to run a fully-fledged Active Directory compatible domain controller. In this operational mode (which will be called `PDC mode` in the following chapters) there are some restrictions, that had to be adopted from Active Directory for compatibility reasons. Most of the current distributions are equipped with Samba4 in the common share mode, that does not provide the operation of a fully-fledged Active Directory domain. With the exception of the Univention Corporate Server, that has PDC-Mode integrated into their standard packages.

[[opsi-manual-samba4-opsifileadmins]]
==== The /etc/opsi/opsi.conf: pcpatch and opsifileadmins

TIP: the restrictions discussed in this chapter concern the PDC mode of Samba4 only.

The classic installation, with the user: 'pcpatch' in the group: 'pcpatch', does not work with Samba 4. Samba 4 has defined fundamental restrictions for the Active Directory, such as groups with the same name as a user (which is common in Unix/Linux) are no longer allowed. For this reason, a new configuration file has been introduced:  `/etc/opsi/opsi.conf`, that configures the groups for Samba access. To be more specific, for Samba 4 installations the group name 'pcpatch' is renamed as  'opsifileadmins'. So the user 'pcpatch', who was member of the group 'pcpatch' under Samba 3, must now be a member of the group 'opsifileadmins'.
So, to have access rights for opsi-packages under Samba 3, a user cannot be a member of the group 'pcpatch' anymore, but must be a member of the group 'opsifileadmins'. 

Furthermore, the user 'pcpatch' has to be created as a fully-fledged domain user and not as a system user anymore. 

These migration steps are performed automatically during opsi installation on a Univention Corporate Server, if the installation process detects Samba4 running in PDC mode.

Besides the UCS installations, currently there are no other default Active Directory configurations. So these steps have to be done manually for any other Samba4 Active Directory domain contoller installation. 
During future updates, the opsi system checks for the required user configuration and does not try to create users, that do already exist. 

For any questions please contact opsi support. In case you do not have an opsi support contract, please contact info(at)uib.de.

[[opsi-manual-samba4-share-configuration]]
==== Share Configuration

TIP: The changes discussed in this chapter ar relevant for all operational modes of Samba4.

With Samba 3 the default setting was, that every file or directory was executable on the share for the Samba clients. This behaviour changed with Samba 4. Now all files, that shall be executable from the share, must also have the executable bit set on the Unix side.

This results in a basic problem with running opsi. It is not possible to handle this behaviour from the opsi rights management, for it would require fundamental changes of the rights management of opsi, that can't be done with opsi{nbsp}4.

So for handling this problem with opsi{nbsp}4.0 there are two ways:

**Option 1:** for the affected shares this behaviour can be supressed by elevating the share privileges of each member of the pcpatch group from the share configuration by setting the following option: +
admin users = @pcpatch

This fix elevates the privileges of the Samba processes and has already been used by opsi for some time for UCS{nbsp}>={nbsp}3 with Samba{nbsp}4.

opsi installs per default for Samba{nbsp}4 distributions with opsi-setup --auto-configure-samba this option for the opsi_depot share. This share is mounted read only, so the safety and security risk can be estimated as low.

CAUTION: For all other shares, that are mounted as read/write, it has to be considered, that with this fix the samba process runs with elevated rights. This can be a potential risk. Although there are currently no known exploits for this vulnerability, there might be some in the future.  

CAUTION: The Linux smb daemon has a bug. On an existing opsi_depot share it is configured with oplocks. These options have to be removed in the share configuration within the smb.conf. On a new opsi installation and therefore share creation these options are not present anymore.

**Option 2:** the following global option can be set in the smb.conf: +
acl allow execute always = True

With this option all shares behave like Samba{nbsp}3 shares.

To restore the old Samba{nbsp}3 behaviour for all shares, the setting of this option can be done for every share manually, or alternalively the option can be set globally in the smb.conf. This changes the behaviour for all shares, not only for the opsi shares.

The global setting does not work with Univention Corporate Server, for its Samba{nbsp}4 installation is configured in a very special way.

[[opsi-manual-samba4-clientconfig-depot-user]]
==== Access to the shares: clientconfig.depot.user

When using Samba{nbsp}4 it might be necessary to configure the specific domain and user combination to be used for mounting the depot share. +
The default configuration is just the user `pcpatch` and nothing as domain. If this fails because the mount defaults to the wrong domain, you should configure the correct domain (in most cases: the hostname of the opsi-server).
The config parameter is named: `clientconfig.depot.user`.
The value of this config has the syntax: `<domain name>\<user name>`
An example config: +
`clientconfig.depot.user = opsiserver\pcpatch` +
specifies, that the opsi depot share is mounted as domain `opsiserver` and user `pcpatch`.
You may create such a configuration using the opsi-configed:
Server configuration / clientconfig / right mouse button: add standard configuration entry. +
You may also use the command line to create this configuration (replace 'pcpatch' by the string you need e.g. 'opsiserver\pcpatch':
[source,prompt]
----
opsi-admin -d method config_createUnicode clientconfig.depot.user "clientconfig.depot.user" pcpatch
----
This system wide configuration may be changed client specific (e.g with the opsi-configed) 
