//// 
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; Until we found a better license:
; All rights reserved.
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      05.05.2011
:Revision:  4.0.1
:toclevels: 6

include::../common/opsi_terms.asciidoc[]


[[opsi-manual-overview]]
== Overview of opsi

Tools for automated software distribution and operating system installation are
important and necessary tools for standardization, maintainability and cost saving of larger PC networks. Normally the application of such tools comes along with substantial royalties, whereas opsi as an open source tool affords explicit economics. Expenses thereby arise only from performed services like consulting, training and maintenance, and perhaps from low Co-funding rates if you like to use some of the non free modules.

Although the software itself and the handbooks are free of charge, the process of introducing any software distribution tool is still an investment. To get the benefit without throwbacks and without a long learning curve consulting and education of the system administrators by a professional partner is recommended. uib offers all these services around opsi.

The opsi system as developed by uib depends on Linux-servers. They are used for
remote installation and maintenance of the client OS and the client software packets ("PC-Server-Integration"). It is based as far as possible on free available tools (GNUtools, SAMBA etc.). The complete system all together is named opsi (Open PC-Server-Integration) and with its configurability is a very interesting solution for the administration challenges of a large computer park.

[[opsi-manual-overview-experience]]
=== Experience

opsi is derived from a system, which is in use since the middle of the 90's with more than 2000 Client-PCs in different locations of a state authority. Since that time it has continuously been adapted to the changing Microsoft operating system world. As a product opsi is now accessible for a broad range of interested users.

You can find an geographical overview of the registered opsi-installations at:
http://www.opsi.org/map/.

[[opsi-manual-overview-features]]
=== opsi features

The core features of opsi are:

* automatic software distribution
* automatic operating system installation
* hard- and software inventory
* comfortable control via the opsi management interface
* support of multiple depot-servers


[[opsi-manual-overview-extensions]]
=== opsi Extensions

* Management of licenses
* MySQL-Backend
* Nagios Connector
* Dynamical depot server selection
* User Profile Management (manipulation Profiles even with Roamin Profiles)
* WAN Extension (Support for clients behind slow connections)
* OTRS::ITSM Connection - via KIX4OTRS by cape IT gmbh

