////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      05.04.2012
:Revision:  4.0.1
:toclevels: 6


include::../common/opsi_terms.asciidoc[]

[[opsi-manual-localization]]
== opsi localization

Get your localization code:

http://www.gnu.org/software/gettext/manual/html_node/Usual-Language-Codes.html

Example: +
en:: English
de:: German
fr:: French
it:: Italian
da:: Danish

[[opsi-manual-localization-existing]]
=== Using existing localizations

opsi has localizations for:

* English
* German
* French
* Italian
* Danish

If it is possible for a localized part of opsi to detect what is your standard language it will switch automatically.
If ths is not possible in most cases 'English' is the fallback language and in some cases still 'German'.

Some Parts of opsi have no chance to detect the language to use, so you have to help a little:

* Bootimage:
Edit on your Server the file `/tftpboot/linux/pxelinux.cfg/install`. Append to the `append` line `lang=<code>` for example `lang=fr`.

[[opsi-manual-localization-create]]
=== Creating or changing localizations

We are always very happy if you like to make a new localization or correct a existing. Here some hints how to start.

[[opsi-manual-localization-pofiles]]
==== PO files

Many localizations are done in the standard GNU `*.po` files. +
You may use the poedit application for editing for editing:
http://download.uib.de/opsi4.0/products/contribute/full-package/poedit_1.4.6-1.opsi
or
http://www.poedit.net/

[[opsi-manual-localization-pofiles-opsi-winst]]
==== PO files: opsi-winst

You will find the po files for the opsi-winst here: +
opsi-winst: at svn.opsi.org repo: opsi-winst branches/4.11.3/languages:

https://svn.opsi.org/listing.php?repname=opsi-winst&path=%2Fbranches%2F4.11.3%2Flanguages%2F&#a0658e5e6a7e3d75fca6bb75072dbadfc

A modified new `opsi-winst.po` you may test by just store it in the `opsi-winst\languages` directory.

[[opsi-manual-localization-pofiles-opsiclientd]]
==== PO files: opsiclientd
You will find the po files for the opsiclientd here: 

https://svn.opsi.org/listing.php?repname=opsiclientd&path=%2Ftrunk%2Fgettext%2F&#a4c4f8177ba88910762266205d8169980

[[opsi-manual-localization-pofiles-python-opsi]]
==== PO files: python-opsi
You will find the po files for the python-opsi here: 

https://svn.opsi.org/listing.php?repname=python-opsi&path=%2Ftrunk%2Fgettext%2F&#a4c4f8177ba88910762266205d8169980

[[opsi-manual-localization-pofiles-opsi-utils]]
==== PO files: opsi-utils
You will find the po files for the opsi-utils here: 

https://svn.opsi.org/listing.php?repname=opsi-utils&path=%2Ftrunk%2Fgettext%2F&#a4c4f8177ba88910762266205d8169980

[[opsi-manual-localization-pofiles-opsi-bootimage]]
==== PO files: opsi-bootimage
You will find the po files for the opsi-bootimage here: 

Until we published the opsi-bootimage code at our svn, just send a mail to our localization contact mentioned at thend of this chapter.

[[opsi-manual-localization-configed]]
=== configed
You will find the po files for the opsi-configed here: +
opsi-configed (stable): at svn.opsi.org repo: opsi-configed/trunk/classes/de/uib/messages

https://svn.opsi.org/listing.php?repname=opsi-configed&path=%2Ftrunk%2Fsrc%2Fde%2Fuib%2Fmessages%2F&#a0771766f6b075de75d6111ea7bd4bae0

The latest (unstable) version you will find at our experimental repositories.
For example:
http://download.opensuse.org/repositories/home:/uibmz:/opsi:/opsi40-experimental/Debian_6.0/all/opsi-configed_4.0.2.2-1_all.deb

If you unzip configed.jar you find the translation files in
de/uib/messages. There you can replace the file, pack (zip) again the
archive and retry the program.

You have to modify the valid_translations.conf
and add a new configed_da.properties and a da.png

Since we introduced some signing mechanisms the procedure to get a new 
working configed.jar has become a little bit more complicated.

One option that your really check out the configed code from 
svn.opsi.org (where you will find the last stable version), add a 
configed_da.properties, a da.png and a new valid_localisations.conf (as 
you provided). Then you may use the bash scripts compile.sh plus 
sign_jars.sh to produce new signed configed.jar and swingx.jar files. 
You may put the jars to /usr/lib/configed in order to see it in browser 
(after reopening the browser).

It is also possible just to put the additional needed files to a 
unpacked configed.jar, but then you have to rebuild it with the java 
packager jar. Since it is not signed it cannot be used via the browser.

So you may directly have a look at the result of your work.

[[opsi-manual-localization-opsiclientd-conf]]
=== opsiclientd.conf

One part will be the localization of the message entries of the
opsiclientd.conf like for example:
[source,ini]
----
# Message shown in the action notifier window (string)
action_message = Starting to process product actions. You are allowed to
cancel this event a total of %action_user_cancelable% time(s). The event
was already canceled %state.action_processing_cancel_counter% time(s).
# German translation (string)
action_message[de] = Starte die Bearbeitung von Produkt-Aktionen. Sie
können diese Aktion insgesamt %action_user_cancelable% mal abbrechen.
Die Aktion wurde bereits %state.action_processing_cancel_counter% mal
abgebrochen.
----

You will find the opsiclientd.conf here: +

https://svn.opsi.org/filedetails.php?repname=opsiclientd&path=%2Ftrunk%2Fsrc%2Fwindows%2Fopsiclientd.conf

[[opsi-manual-localization-contact]]
=== Localization contact

Please send any questions, hints or localization files to: 'locales@uib.de'







