== FAQ setup and application of the WAN extension

[[opsi-faq-wan-manual-licenz]]
=== Do I need a license?

Yes the extension is still part of the cofinancing scheme and therefore subject of a fee.
Additionally for the operation of the WAN extension the MySQL backend is required which is also liable of a fee. You can test the extensions free of charge for a limited ammount of time. In order to do so please contact info@uib.de

[[opsi-faq-wan-manual-activate]]
=== How do I activate the WAN extension on a client?

The activation of the WAN extension can be perfomed per client via the checkbox on the management console. The client will received the specific configuration change the next time it connects to the opsi server, becoming active after the next restart.

[[opsi-faq-wan-manual-activate-oca]]
=== Must the opsi client agent be deployed once again for the activation?

No, that is not necessary since the client can get the configuration automatically at the next connection to the opsi server. That can be at the next boot process or after an "on_demand" event.

[[opsi-faq-wan-manual-activate-homeoffice]]
=== How can I activate clients that are already in Home Office?

If the clients can be reached by the opsi server in home office, the transfer of the configuration can be performed by triggering an "on_demand" event. (This only works if the data transfer is set to cifs)

This can be performed on the command line from the server with the following:

[source,prompt]
----
opsi-admin -a https://<ClientIp>:4441/opsiclientd -u <user> -p <pass> method fireEvent "on_demand"
----

Replace the corresponding entries:

.  <ClientIp> = IP address of the clients
.  <user> = local administrator on the client or member of the local administrator group
.  <pass> = password of the administrator

[[opsi-faq-wan-manual-cache]]
=== How big is the cache on the client?

The cache on the client is set to 20 GB by default. The programs and updates to be installed are stored here. During an update, only the changed data is copied to the cache directory via a sync process. The size of the cache should be chosen abundantly taking into account that even large packages can be stored.

[[opsi-faq-wan-manual-cachesize]]
=== How can I change the size of the cache on the client:

With this, the parameter can be entered as a config on the management console and then the value can be adjusted individually for each client:

[source,prompt]
----
opsi-admin -d method config_createUnicode "opsiclientd.cache_service.product_cache_max_size" "Maximum product cache size in bytes" "40000000000" "40000000000" "True" "False"
----

[[opsi-faq-wan-manual-time]]
=== How can the time the client waits for a response be extended before rebooting for an installation?

With this call, the parameter can be entered as a config on the management console and the value can then be adjusted individually for each client:

[source,prompt]
----
opsi-admin -d method config_createUnicode "opsiclientd.event_sync_completed{cache_ready_user_logged_in}.shutdown_warning_time" "Wie lange soll auf eine Antwort vor einem Reboot gewartet werden. Default 3600 Sekunden" "3600" "3600" "True" "False"
----

If you want to shift the time by 8 hours enter 28000 seconds here.


[[opsi-faq-wan-manual-ondemand]]
=== Rollout installations "on_demand" in WAN mode

The installations are deployed as if the client would be present locally.

. The config server receives a direct request.
. A Samba share is mounted via cifs. If webdav has been activated for data transfer, this will be ignored.
. The installation starts directly without the data being cached before.

[[opsi-faq-wan-manual-kiosk]]
=== Does the kiosk mode work in WAN mode?

The kiosk mode works only if the opsi config server is available. Also in WAN-mode the kiosk works directly on the opsi server.
If the request to install a package should not only be saved but also executed directly, the installation is performed the standard way and not on WAN mode, which means the packages are not cached. You can use the kiosk on a WAN client, but the actual WAN mode components are not used.

[[opsi-faq-wan-manual-byshutdown]]
=== Can the Install by shutdown mode be combined with the WAN mode?

No, Install by shutdown mode is not compatible with WAN extension.

[[opsi-faq-wan-manual-mshotfix]]
=== Subscription MSHotfix and WAN mode

Basically you can deploy the Mshotfix packages from your subscription on to your WAN clients. However, it should be noted that these standard packages are very large in size(e.g. Windwos10 64 bits is around 6GB).

For this reason "modular" Mshotfix packages are provided for Windows10 that only contain the patches for a certain ReleaseID, e.g. mshotfix-win10-1809-x64-glb. The size of these "modular" packages is currently about 1 GB). Therefore we strongly suggest to use this "modular" packages in WAN mode.
