////                                                            
; Copyright (c) uib gmbh (www.uib.de)                           
; This documentation is owned by uib                            
; and published under the german creative commons by-sa license 
; see:                                                          
; https://creativecommons.org/licenses/by-sa/3.0/de/             
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode    
; english:                                                      
; https://creativecommons.org/licenses/by-sa/3.0/                
; https://creativecommons.org/licenses/by-sa/3.0/legalcode       
;                                                               
;                          
////                                                            
                                                                
:Revision:                                                 
:doctype: book                                               
:Author:    detlef oertel
:Email:    d.oertel@uib.de
:toc:
   
   
   
:Author:    detlef oertel
:Email:    d.oertel@uib.de
:toc:
   
   
   
:Author:    detlef oertel
:Email:    d.oertel@uib.de
:toc:
   
   
   
:Author:    detlef oertel
:Email:    d.oertel@uib.de
:toc:
   
   
   

[[Doc_fileuib_strlistutils.opsiscript]]
= Documentation of opsi library: `uib_strlistutils.opsiscript`



* Email:     d.oertel@uib.de
* Version:  1.0
* Copyright:  AGPLv3





anchor:compareLists[]

[[Doc_func_compareLists]]
== Documentation of local function `compareLists`


Definition::
`compareLists($list1$ : stringlist, $list2$ : stringlist) : string`

Description::
Checks if to string lists are completely identic or not.
The check is not case sensitive.

* Parameter: `$list1$`
** Type: `Stringlist`  -  Calltype: `CallByValue`
** Parameter `$list1$` Description: +
First stringlist to compare

* Parameter: `$list2$`
** Type: `Stringlist`  -  Calltype: `CallByValue`
** Parameter `$list2$` Description: +
Second stringlist (to compare with first)

* Returns:     Returns string "true" if the given lists are identic.
Returns string "false" if the given lists are not identic
* OnError:     Returns string "false"
* Author:     detlef oertel
* Date:     17.5.2018
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
set $tmplist$ = getListContainingList($baseproducts$,$resultlist$)
if stringToBool(compareLists($tmplist$,$baseproducts$))
	comment "check installed products successful finished"
else
	LogError "check installed products failed"
	set $errorList$ = addtolist($errorList$, "check installed products failed")
	;set $fatal_error$ = "true"
endif
----


