////                                                            
; Copyright (c) uib gmbh (www.uib.de)                           
; This documentation is owned by uib                            
; and published under the german creative commons by-sa license 
; see:                                                          
; http://creativecommons.org/licenses/by-sa/3.0/de/             
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode    
; english:                                                      
; http://creativecommons.org/licenses/by-sa/3.0/                
; http://creativecommons.org/licenses/by-sa/3.0/legalcode       
;                                                               
;                          
////                                                            
                                                                
:Revision:                                                 
:doctype: book                                               
:Author:    detlef oertel
:Email:    d.oertel@uib.de
:toc:
   
   
   
:Author:    detlef oertel
:Email:    d.oertel@uib.de
:toc:
   
   
   
:Author:    detlef oertel
:Email:    d.oertel@uib.de
:toc:
   
   
   

[[Doc_fileuib_lin_install.opsiscript]]
= Documentation of opsi library: `uib_lin_install.opsiscript`



* Email:     d.oertel@uib.de
* Version:  1.0
* Copyright:  AGPLv3





anchor:cleanupPackageSystem[]

[[Doc_func_cleanupPackageSystem]]
== Documentation of local function `cleanupPackageSystem`


Definition::
`cleanupPackageSystem() : void`

Description::
reads repo list und try to repair well known problems
should be called after modifying the repo list or after failed installs

* Returns:     nothing
* OnError:     error counter increased ; Error messages in the log
* Author:     detlef oertel
* Date:     19.08.2020
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
[Actions]
importlib "uib_lin_install"

DefStringlist $packages$
DefVar $installresult$
DefStringlist $errorList$
DefVar $fatal_error$
DefVar $result_string$

comment "update and clean package system"
cleanupPackageSystem()
comment "install pending updates"
set $result_string$ = installupdates()
comment "install new needed packages"
set $packages$ = CreateStringlist("lsb-release","cifs-utils","xterm", "dnsutils","lsof","openssl","pkg-config","desktop-file-utils","libnotify-bin","libgtk2.0-0")
comment "if we are on debian / ubuntu we can use debinstall()"
set $installresult$ = debinstall($packages$)
if not(stringtobool($installresult$))
	if waitForPackageLock("300", "false")
		comment "we got the package lock."
	else
		LogError "could not get Package Lock"
	endif
	cleanupPackageSystem()
	set $installresult$ = debinstall($packages$)
	if not(stringtobool($installresult$))
		LogError "failed dependent packages"
		Message "failed dependent packages"
		;isFatalError "failed dependent packages"
		set $fatal_error$ = "true"
		setloglevel = 6
		set $errorList$ = addtolist($errorList$, " failed dependent_packages")
	endif
endif
----



anchor:installupdates[]

[[Doc_func_installupdates]]
== Documentation of local function `installupdates`


Definition::
`installupdates() : string`

Description::
try to install pending updates from the known repsitories
should be called after modifying the repo list or after failed installs

* Returns:     nothing
* OnError:     Returns string "false"; error counter increased ; Error messages in the log
* Author:     detlef oertel
* Date:     19.08.2020
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
see: cleanupPackageSystem()
----



anchor:runCommandWithList[]

[[Doc_func_runCommandWithList]]
== Documentation of local function `runCommandWithList`


Definition::
`runCommandWithList($command$ : string, $list$ : stringlist) : string`

Description::


* Parameter: `$command$`
** Type: `String`  -  Calltype: `CallByValue`

* Parameter: `$list$`
** Type: `Stringlist`  -  Calltype: `CallByValue`

* Author:     detlef oertel
* Date:     19.8.2020
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3



anchor:debinstall[]

[[Doc_func_debinstall]]
== Documentation of local function `debinstall`


Definition::
`debinstall($packagelist$ : stringlist) : string`

Description::
try to install the packages given by $packagelist$

* Parameter: `$packagelist$`
** Type: `Stringlist`  -  Calltype: `CallByValue`
** Parameter `$packagelist$` Description: +
stringlist with packages to install

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"; error counter increased ; Error messages in the log
* References:     <<cleanupPackageSystem>> 
<<installupdates>> 
<<redinstall>> 
<<suseinstall>> 
<<ucsinstall>> 
* Author:     detlef oertel
* Date:     19.08.2020
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
see: cleanupPackageSystem()
----



anchor:redinstall[]

[[Doc_func_redinstall]]
== Documentation of local function `redinstall`


Definition::
`redinstall($packagelist$ : stringlist) : string`

Description::
try to install the packages given by $packagelist$

* Parameter: `$packagelist$`
** Type: `Stringlist`  -  Calltype: `CallByValue`
** Parameter `$packagelist$` Description: +
stringlist with packages to install

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"; error counter increased ; Error messages in the log
* References:     <<cleanupPackageSystem>> 
<<installupdates>> 
<<debinstall>> 
<<suseinstall>> 
<<ucsinstall>> 
* Author:     detlef oertel
* Date:     19.08.2020
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
see: cleanupPackageSystem()
----



anchor:suseinstall[]

[[Doc_func_suseinstall]]
== Documentation of local function `suseinstall`


Definition::
`suseinstall($packagelist$ : stringlist) : string`

Description::
try to install the packages given by $packagelist$

* Parameter: `$packagelist$`
** Type: `Stringlist`  -  Calltype: `CallByValue`
** Parameter `$packagelist$` Description: +
stringlist with packages to install

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"; error counter increased ; Error messages in the log
* References:     <<cleanupPackageSystem>> 
<<installupdates>> 
<<debinstall>> 
<<redinstall>> 
<<ucsinstall>> 
* Author:     detlef oertel
* Date:     19.08.2020
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
see: cleanupPackageSystem()
----



anchor:ucsinstall[]

[[Doc_func_ucsinstall]]
== Documentation of local function `ucsinstall`


Definition::
`ucsinstall($packagelist$ : stringlist) : string`

Description::
try to install the packages given by $packagelist$

* Parameter: `$packagelist$`
** Type: `Stringlist`  -  Calltype: `CallByValue`
** Parameter `$packagelist$` Description: +
stringlist with packages to install

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"; error counter increased ; Error messages in the log
* References:     <<cleanupPackageSystem>> 
<<installupdates>> 
<<debinstall>> 
<<redinstall>> 
<<suseinstall>> 
* Author:     detlef oertel
* Date:     19.08.2020
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
see: cleanupPackageSystem()
----



anchor:genericLinInstall[]

[[Doc_func_genericLinInstall]]
== Documentation of local function `genericLinInstall`


Definition::
`genericLinInstall($packagelist$ : stringlist) : string`

Description::
try to determine the Linux familily and
try to install the packages given by $packagelist$

* Parameter: `$packagelist$`
** Type: `Stringlist`  -  Calltype: `CallByValue`
** Parameter `$packagelist$` Description: +
stringlist with packages to install

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"; error counter increased ; Error messages in the log
* References:     <<cleanupPackageSystem>> 
<<installupdates>> 
<<debinstall>> 
<<redinstall>> 
<<suseinstall>> 
* Author:     detlef oertel
* Date:     08.03.2021
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
see: cleanupPackageSystem()
----



anchor:linuxInstallOneOf[]

[[Doc_func_linuxInstallOneOf]]
== Documentation of local function `linuxInstallOneOf`


Definition::
`linuxInstallOneOf($packagelist$ : stringlist) : string`

Description::
try to install any package given by $packagelist$
This can be used specifying a package with different names for different linux distributions.

* Parameter: `$packagelist$`
** Type: `Stringlist`  -  Calltype: `CallByValue`
** Parameter `$packagelist$` Description: +
stringlist with packages to install

* Returns:     Returns string 'True' if one package was successfully installed
* OnError:     Returns string 'False'
* References:     <<isOneInstalled>> 
<<getLinuxCommand>> 
* Author:     nils doerrer
* Date:     16.11.2020
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
[Actions]
importlib "uib_lin_install"
if isOneInstalled(createStringList("lsusb", "usbutils")) = "False"
	message "installing lsusb or usbutils"
	set $success$ = linuxInstallOneOf(createStringList("lsusb", "usbutils"))
endif
----



anchor:isOneInstalled[]

[[Doc_func_isOneInstalled]]
== Documentation of local function `isOneInstalled`


Definition::
`isOneInstalled($packagelist$ : stringlist) : string`

Description::
check for installation status and return if any of $packagelist$ exists
This can be used to check a package with different names for different linux distributions.

* Parameter: `$packagelist$`
** Type: `Stringlist`  -  Calltype: `CallByValue`
** Parameter `$packagelist$` Description: +
stringlist with packages to check

* Returns:     Returns string 'True' if one specified package is installed
* OnError:     Returns string 'False'
* References:     <<linuxInstallOneOf>> 
<<getLinuxCommand>> 
* Author:     nils doerrer
* Date:     16.11.2020
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3



anchor:getLinuxCommand[]

[[Doc_func_getLinuxCommand]]
== Documentation of local function `getLinuxCommand`


Definition::
`getLinuxCommand($type$ : string) : string`

Description::
Determine package manager and return command.

* Parameter: `$type$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$type$` Description: +
type of desired command 'install','check', 'localpackage'

* Returns:     Package manager command according to type
* OnError:     Returns string 'False'
* References:     <<linuxInstallOneOf>> 
<<isOneInstalled>> 
* Author:     nils doerrer,  d.oertel
* Date:     14.01.2021
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3



anchor:getLinuxCommandAgnostic[]

[[Doc_func_getLinuxCommandAgnostic]]
== Documentation of local function `getLinuxCommandAgnostic`


Definition::
`getLinuxCommandAgnostic($type$ : string) : string`

Description::
Determine package manager and return command.

* Parameter: `$type$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$type$` Description: +
type of desired command 'install' or 'check'

* Returns:     Package manager command according to type
* OnError:     Returns string 'False'
* References:     <<linuxInstallOneOf>> 
<<isOneInstalled>> 
<<getLinuxCommand>> 
* Author:     nils doerrer
* Date:     16.11.2020
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3



anchor:linuxInstallOneFile[]

[[Doc_func_linuxInstallOneFile]]
== Documentation of local function `linuxInstallOneFile`


Definition::
`linuxInstallOneFile($packagefile$ : string) : string`

Description::
try to install the local file package given by $packagefile$
This can be used specifying a package with different names for different linux distributions.

* Parameter: `$packagefile$`
** Type: `String`  -  Calltype: `CallByValue`

* Returns:     Returns string '0' if one package was successfully installed
* OnError:     Returns string '-1'
* References:     <<isOneInstalled>> 
<<getLinuxCommand>> 
* Author:     d.oertel
* Date:     08.02.2021
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
[Actions]
importlib "uib_lin_install"
if stringToBool(linuxInstallOneFile("/tmp/dummy.deb")
	comment "success"
endif
----



anchor:linuxRemoveOnePackage[]

[[Doc_func_linuxRemoveOnePackage]]
== Documentation of local function `linuxRemoveOnePackage`


Definition::
`linuxRemoveOnePackage($packagename$ : string) : string`

Description::
try to remove the  package given by $packagename$
This can be used specifying a package with different names for different linux distributions.

* Parameter: `$packagename$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$packagename$` Description: +
string with the name of a package to remove

* Returns:     Returns string '0' if package was successfully removed or was not installed
* OnError:     Returns string '-1'
* References:     <<isOneInstalled>> 
<<getLinuxCommand>> 
* Author:     d.oertel
* Date:     08.02.2021
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
[Actions]
importlib "uib_lin_install"
if stringToBool(linuxRemoveOnePackage("dummy")
	comment "success"
endif
----



anchor:linuxRemoveOneOf[]

[[Doc_func_linuxRemoveOneOf]]
== Documentation of local function `linuxRemoveOneOf`


Definition::
`linuxRemoveOneOf($packagelist$ : stringlist) : string`

Description::
try to remove any package given by $packagelist$
This can be used specifying a package with different names for different linux distributions.

* Parameter: `$packagelist$`
** Type: `Stringlist`  -  Calltype: `CallByValue`
** Parameter `$packagelist$` Description: +
stringlist with packages to install

* Returns:     Returns string 'True' if one package was successfully installed
* OnError:     Returns string 'False'
* References:     <<isOneInstalled>> 
<<getLinuxCommand>> 
* Author:     nils doerrer / detlef oertel
* Date:     16.11.2020
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
[Actions]
importlib "uib_lin_install"
if isOneInstalled(createStringList("lsusb", "usbutils")) = "True"
	message "installing lsusb or usbutils"
	set $success$ = linuxRemoveOneOf(createStringList("lsusb", "usbutils"))
endif
----


