////                                                            
; Copyright (c) uib gmbh (www.uib.de)                           
; This documentation is owned by uib                            
; and published under the german creative commons by-sa license 
; see:                                                          
; http://creativecommons.org/licenses/by-sa/3.0/de/             
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode    
; english:                                                      
; http://creativecommons.org/licenses/by-sa/3.0/                
; http://creativecommons.org/licenses/by-sa/3.0/legalcode       
;                                                               
;                          
////                                                            
                                                                
:Revision:                                                 
:doctype: book                                               
:Author:    detlef oertel
:Email:    d.oertel@uib.de
:toc:
   
   
   
:Author:    detlef oertel
:Email:    d.oertel@uib.de
:toc:
   
   
   
[Doc_fileuib_bootutils.opsiscript]
= Documentation of opsi library: `uib_bootutils.opsiscript`



* Email:     d.oertel@uib.de
* Version:  1.0
* Copyright:  AGPLv3





anchor:delFromWindowsBootmanager[]
[Doc_func_delFromWindowsBootmanager]
== Documentation of local function `delFromWindowsBootmanager`


Definition::
`delFromWindowsBootmanager($bootlabel$ : string) : string`

Description::
Deletes the boot entry given given by the parameter $bootlabel$ from Windows boot manager
by using bcdedit

* Parameter: `$bootlabel$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$bootlabel$` Description: +
Windows boot manager entry label found in 'bcdedit /v'

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"
* SpecialCase:     Winows only
* References:     <<getWinBcdbootGuid>> 
<<bootNextToWinLabel>> 
<<bootNextToUefiLabel>> 
<<getUefiBcdbootGuid>> 
* Author:     detlef oertel
* Date:     17.5.2018
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
[actions]
DefStringlist $productlist$

set $productlist$ = CreateStringList("opsi-logviewer","opsi-configed")
if not(stringtobool(setProductsToSetup($productlist$)))
  comment "call of setProductsToSetup failed"
endif
----



anchor:getWinBcdbootGuid[]
[Doc_func_getWinBcdbootGuid]
== Documentation of local function `getWinBcdbootGuid`


Definition::
`getWinBcdbootGuid($bootlabel$ : string) : string`

Description::
Get the boot entry GUID for the label given by the parameter $bootlabel$
from Windows boot manager
by using bcdedit

* Parameter: `$bootlabel$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$bootlabel$` Description: +
Windows boot manager entry label found in 'bcdedit /v'

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"
* SpecialCase:     Winows only
* References:     <<delFromWindowsBootmanager>> 
<<bootNextToWinLabel>> 
<<bootNextToUefiLabel>> 
<<getUefiBcdbootGuid>> 
* Author:     detlef oertel
* Date:     17.5.2018
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
Message "get windows boot guid ...."
set $windows_bcd_guid$ = getWinBcdbootGuid("WINDOWS.vhdx")
----



anchor:getUefiBcdbootGuid[]
[Doc_func_getUefiBcdbootGuid]
== Documentation of local function `getUefiBcdbootGuid`


Definition::
`getUefiBcdbootGuid($bootlabel$ : string) : string`

Description::
Get the boot entry GUID for the label given by the parameter $bootlabel$ from Windows boot manager
by using bcdedit

* Parameter: `$bootlabel$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$bootlabel$` Description: +
UEFI boot manager entry label found in 'bcdedit /enum firmware'

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"
* SpecialCase:     Winows only
* References:     <<delFromWindowsBootmanager>> 
<<bootNextToWinLabel>> 
<<bootNextToUefiLabel>> 
<<getUefiBcdbootGuid>> 
* Author:     detlef oertel
* Date:     17.5.2018
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
if runningonUefi
	set $peuefiguid$ = getUefiBcdbootGuid("opsitempwinpe")
	set $exitcode$ = getlastexitcode
	if $exitcode$ = "0"
		if not ($peuefiguid$ = "")
			shellCall("bcdedit /delete "+$peuefiguid$)
		endif
	endif
endif
----



anchor:bootNextToWinLabel[]
[Doc_func_bootNextToWinLabel]
== Documentation of local function `bootNextToWinLabel`


Definition::
`bootNextToWinLabel($bootlabel$ : string) : string`

Description::
Sets the Windows bootmanager to boot next to the label
given by the parameter $bootlabel$ from Windows boot manager
by using bcdedit

* Parameter: `$bootlabel$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$bootlabel$` Description: +
Windows boot manager entry label found in 'bcdedit /v'

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"
* SpecialCase:     Winows only
* References:     <<delFromWindowsBootmanager>> 
<<getUefiBcdbootGuid>> 
<<bootNextToUefiLabel>> 
* Author:     detlef oertel
* Date:     17.5.2018
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
See bootNextToUefiLabel
----



anchor:bootNextToUefiLabel[]
[Doc_func_bootNextToUefiLabel]
== Documentation of local function `bootNextToUefiLabel`


Definition::
`bootNextToUefiLabel($bootlabel$ : string) : string`

Description::
Sets the uefi bootmanager to boot next to the label
given by the parameter $bootlabel$ from uefi boot manager
by using bcdedit

* Parameter: `$bootlabel$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$bootlabel$` Description: +
UEFI boot manager entry label found in 'bcdedit /enum firmware'

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"
* SpecialCase:     Winows only
* References:     <<delFromWindowsBootmanager>> 
<<getUefiBcdbootGuid>> 
<<bootNextToUefiLabel>> 
* Author:     detlef oertel
* Date:     17.5.2018
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
Message "Enable PE boot...."
if runningonuefi
	set $bootLabel$ = "opsitempwinpe"
	if not(stringToBool(bootNextToUefiLabel($bootLabel$)))
		logerror "Activating peboot is failed"
		isFatalError "failed peboot"
	endif
else
	set $bootLabel$ = "ramdisk=[boot]\sources\boot.wim"
	if not(stringToBool(bootNextToWinLabel($bootLabel$)))
		logerror "Activating peboot is failed"
		;isFatalError "failed peboot"
	endif
endif
----



anchor:getDiskUuid[]
[Doc_func_getDiskUuid]
== Documentation of local function `getDiskUuid`


Definition::
`getDiskUuid($disknumber$ : string , $tmpdir$ : string ) : string`

Description::
Gets the disk uuid for the disk with the number $disknumber$
by using diskpart.
The temporary diskpart script is written to $tmpdir$

* Parameter: `$disknumber$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$disknumber$` Description: +
UEFI boot manager entry label found in 'bcdeit /enum firmware'

* Parameter: `$tmpdir$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$tmpdir$` Description: +
Temporary directory to use
** Parameter `$tmpdir$` Advice: +
Directory must exist

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"
* SpecialCase:     Winows only
* References:     <<enablePEPartition>> 
* Author:     detlef oertel
* Date:     17.5.2018
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
for %disk% = "0" to calculate($diskcount1$+" -1") do set $aktdisklist$ = addtolist($aktdisklist$,getDiskUuid("%disk%", "x:")+"=%disk%")
set $disk$ = getvalue($diskuuid$,$aktdisklist$)
----



anchor:enablePEPartition[]
[Doc_func_enablePEPartition]
== Documentation of local function `enablePEPartition`


Definition::
`enablePEPartition($disknumber$ : string , $partitionNumber$ : string, $pepartletter$ : string, $useGpt$ : string) : string`

Description::
Try to make the partition $partitionNumber$ on the disk $disknumber$ visible, bootable and give
and give it the Windows disk letter $pepartletter$
by using diskpart or powershell

* Parameter: `$disknumber$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$disknumber$` Description: +
Number of the disk where we look for the partition
** Parameter `$disknumber$` Advice: +
First disk = 0

* Parameter: `$partitionnumber$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$partitionnumber$` Description: +
Number of the partition on the given disk
** Parameter `$partitionnumber$` Advice: +
First partition = 1

* Parameter: `$pepartletter$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$pepartletter$` Description: +
Windows disk letter that the given partition should have

* Parameter: `$usegpt$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$usegpt$` Description: +
Should we expect GPT or MBR partitions ('true' or 'false')

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"
* SpecialCase:     Winows only, works in PE
* References:     <<getDiskUuid>> 
* Author:     detlef oertel
* Date:     17.5.2018
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
Message "Enable PE partition...."
if not(stringToBool(enablePEPartition($disknumber$, $swapPartitionNumber$, $pepartletter$, $useGpt$)))
	LogError "Could not activate PE partition ..."
	isFatalError "failed not activate PE partition"
endif

if not (isDriveReady($pePartLetter$))
	logerror "PE drive "+$pePartLetter$+": not ready"
	isFatalError "PE drive "+$pePartLetter$+": not ready"
	set $errorList$ = addtolist($errorList$, " failed pe_drive_ready")
	set $fatal_error$ = "true"
endif
----


