////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
;
;
////

:Revision:
:doctype: book
:Author:    detlef oertel
:Email:    d.oertel@uib.de
:toc:



:Author:    detlef oertel
:Email:    d.oertel@uib.de
:toc:




[[Doc_fileuib_macosinstalllib.opsiscript]]
= Documentation of opsi library: `uib_macosinstalllib.opsiscript`



* Email:     d.oertel@uib.de
* Version:  1.0
* Copyright:  AGPLv3





anchor:install_macos_app[]

[[Doc_func_install_macos_app]]
== Documentation of local function `install_macos_app`


Definition::
`install_macos_app($myapp$ : string) : string`

Description::
try to install the app given by $myapp$

* Parameter: `$myapp$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$myapp$` Description: +
string with path to app to install

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"; error counter increased ; Error messages in the log
* References:     <<install_macos_pkg>>
<<install_macos_dmg>>
<<install_macos_zip>>
<<install_macos_generic>>
* Author:     detlef oertel
* Date:     28.12.2020
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
[Actions]
importlib "uib_macosinstalllib"

DefVar $installfile$
DefVar $installresult$

comment "we have a *.app (directory) and install with install_macos_app"
set $installfile$ = "%scriptpath%/files/my_macos_app.app"
set $installresult$ = install_macos_app($installfile$)
if stringtobool($installresult$)
	comment "installation succeeded"
else
	LogError "installation failed"
endif
----



anchor:install_macos_pkg[]

[[Doc_func_install_macos_pkg]]
== Documentation of local function `install_macos_pkg`


Definition::
`install_macos_pkg($mypkg$ : string) : string`

Description::
try to install the pkg file given by $mypkg$

* Parameter: `$mypkg$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$mypkg$` Description: +
string with path to pkg file to install

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"; error counter increased ; Error messages in the log
* References:     <<install_macos_app>>
<<install_macos_dmg>>
<<install_macos_zip>>
<<install_macos_generic>>
* Author:     detlef oertel
* Date:     28.12.2020
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
[Actions]
importlib "uib_macosinstalllib"

DefVar $installfile$
DefVar $installresult$

comment "we have a *.pkg and install with install_macos_pkg"
set $installfile$ = "%scriptpath%/files/my_macos_app.pkg"
set $installresult$ = install_macos_pkg($installfile$)
if stringtobool($installresult$)
	comment "installation succseeded"
else
	LogError "installation failed"
endif
----



anchor:install_macos_dmg[]

[[Doc_func_install_macos_dmg]]
== Documentation of local function `install_macos_dmg`


Definition::
`install_macos_dmg($mydmg$ : string) : string`

Description::
try to install the dmg file given by $mydmg$

* Parameter: `$mydmg$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$mydmg$` Description: +
string with path to dmg file to install

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"; error counter increased ; Error messages in the log
* References:     <<install_macos_app>>
<<install_macos_pkg>>
<<install_macos_zip>>
<<install_macos_generic>>
* Author:     detlef oertel
* Date:     28.12.2020
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
[Actions]
importlib "uib_macosinstalllib"

DefVar $installfile$
DefVar $installresult$

comment "we have a *.dmg and install with install_macos_dmg"
set $installfile$ = "%scriptpath%/files/my_macos_app.dmg"
set $installresult$ = install_macos_dmg($installfile$)
if stringtobool($installresult$)
	comment "installation succseeded"
else
	LogError "installation failed"
endif
----



anchor:install_macos_zip[]

[[Doc_func_install_macos_zip]]
== Documentation of local function `install_macos_zip`


Definition::
`install_macos_zip($myzip$ : string) : string`

Description::
try to install the zip file given by $myzip$
unzips the file and try to find a installable
part (*.app, *.pkg, *.dmg) and try to install this

* Parameter: `$myzip$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$myzip$` Description: +
string with path to zip file to install

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"; error counter increased ; Error messages in the log
* References:     <<install_macos_app>>
<<install_macos_dmg>>
<<install_macos_pkg>>
<<install_macos_generic>>
* Author:     detlef oertel
* Date:     28.12.2020
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
[Actions]
importlib "uib_macosinstalllib"

DefVar $installfile$
DefVar $installresult$

comment "we have a *.zip and install with install_macos_zip"
set $installfile$ = "%scriptpath%/files/my_macos_app.zip"
set $installresult$ = install_macos_zip($installfile$)
if stringtobool($installresult$)
	comment "installation succseeded"
else
	LogError "installation failed"
endif
----



anchor:install_macos_generic[]

[[Doc_func_install_macos_generic]]
== Documentation of local function `install_macos_generic`


Definition::
`install_macos_generic($myfile$ : string) : string`

Description::
try to install the file given by $myfile$
Checks if the file is a well known installable
(*.app, *.pkg, *.dmg, *.zip) and try to install this

* Parameter: `$myfile$`
** Type: `String`  -  Calltype: `CallByValue`
** Parameter `$myfile$` Description: +
string with path to pkg file to install

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"; error counter increased ; Error messages in the log
* References:     <<install_macos_app>>
<<install_macos_dmg>>
<<install_macos_zip>>
<<install_macos_pkg>>
* Author:     detlef oertel
* Date:     28.12.2020
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
see: install_macos_generic
ions]
rtlib "uib_macosinstalllib"

ar $installfile$
ar $installresult$

ent "we have a *.* and install with install_macos_generic"
$installfile$ = "%scriptpath%/files/opsi-script.app"
$installresult$ = install_macos_generic($installfile$)
tringtobool($installresult$)
ment "installation succseeded"

Error "installation failed"
f
----
