
[[opsi-setup-detector-installation_opb]]
===== Installation des {opsi-package-builder}

The {opsi-package-builder} is currently available for Windows and Linux and MacOS.

The installation files / packages of the `opsi-package-builder` can be found here: +
https://forum.opsi.org/viewtopic.php?p=32473#p32473 +
There you will find in the first lines of the post links to the installation files for Windows and Linux and MacOS. +
The `{opsi-package-builder}`  is not made by 'uib' but by Holger Pandel from the opsi-community (thank you!).. +

The `{opsi-package-builder}` open source license: +
https://github.com/pandel/opsiPackageBuilder/blob/master/LICENSE_DE

The `{opsi-package-builder}` has its own documentation, that is part of the installation.

You can install the `{opsi-package-builder}` also via opsi:

The package `opsipackagebuilder_wlm`` belongs to the opsi standard products and should be installed on your opsi-server. If not, use:

[source,prompt]
----
opsi-package-updater install opsipackagebuilder_wlm
----

to install it on the opsi-server.


[[opsi-setup-detector-installation_osd]]
===== Installation of the opsi-setup-detector

The opsi-setup-detector is currently available for Windows and Linux and MacOS.

You can install the opsi-setup-detector via opsi:

The package `opsi-setup-detector` belongs to the opsi standard products and should be installed on your opsi-server. If not, use:

[source,prompt]
----
opsi-package-updater install opsi-setup-detector
----

to install it on the opsi-server.

A setup program to install the opsi-setup-detector without opsi can be found at : +
https://download.uib.de/opsi4.2/misc/helper/ 

The base functionality of the `opsi-setup-detector` is the same on all suppoted platforms. While analyzing a installer file some helper programs will be called, that may not availiable or runable.

* Inno-Setups will be analyzed with innounpack.exe at Windows.

* wix-setups will be analyzed with dark.exe at Windows.

* `.deb` or. `.rpm` files will be analyzed with the Linux command line tools.

The opsi product `opsi-setup-detector` has a dependency on the opsi product `opsi-package-builder`.
The `opsi-setup-detector` uses the `opsi-package-builder` if available, but can for the most part also work without it.
The installation of the `opsi-package-builder` is recommended. 
