////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      28.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

= Willkommen bei opsi!

Das Client-Management-System link:https://www.opsi.org/[opsi (Open System Integration)] verwaltet Windows-, Linux- und macOS-Clients -- von einem Dutzend bis zu mehreren tausend Rechnern. Die Kernkomponente ist ein Linux-Server, der sich um die automatische Installation der Betriebssysteme (nur Windows und Linux), die Verteilung von Software, die Inventarisierung von Hard- und Software sowie um das Patch-Management auf den Clients kümmert. Dazu kommen Module, die den Funktionsumfang erweitern. Zusammengefasst hat opsi die folgenden Features:

* Automatische Softwareverteilung auf den PCs (opsi-Client-Agent)
* Automatische Betriebssystem-Installation (mithilfe des opsi-Servers)
* Hardware- und Software-Inventarisierung

In nur einem einzigen Administrations-Interface verwaltet opsi Clients an mehreren Standorten. Die Konfiguration wird an zentraler Stelle gespeichert: auf dem opsi-Server. Die Depot-Server für die Clients (Installations-Dateien der zu verteilenden Software und Betriebssysteme, Boot-Images usw.) können auch an mehreren Orten liegen.

Dieses Handbuch hat die folgende Struktur:

* xref:supportmatrix:supportmatrix.adoc[Unterstützte Systeme]
* xref:first-steps:first-steps.adoc[Quick Start]
* xref:server:overview.adoc[opsi-Server]
* xref:clients:opsi-clients.adoc[opsi-Clients]
* xref:gui:gui.adoc[Benutzeroberflächen]
* xref:opsi-products:products.adoc[opsi-Produkte]
* xref:opsi-modules:modules.adoc[opsi-Erweiterungen]
* xref:opsi-script-manual:opsi-script-manual.adoc[*opsi-script*-Referenz]
* xref:development:development.adoc[Entwicklung]
* xref:troubleshooting:troubleshooting.adoc[Problembehebung]
* xref:contribute:contribute.adoc[Bei opsi mitmachen]
* xref:copyright:copyright.adoc[Copyright]

Alle Handbücher stehen unter link:https://download.uib.de/4.2/stable/documentation/[download.uib.de] im PDF- und HTML-Format zum Download bereit. Darüber hinaus haben wir Handbücher zu den APIs link:https://docs.opsi.org/python-docs/python-opsi[python-opsi] und link:https://docs.opsi.org/python-docs/python-opsi-common[opsicommon] veröffentlicht.

TIP: Die opsi-Community trifft sich im link:https://forum.opsi.org/index.php[opsi-Forum]. Dort finden Sie auch den Link zum opsi-Wiki.

include::partial$conventions.adoc[]
