= Willkommen bei opsi! 

Das Client-Management-System link:https://www.opsi.org/[opsi (Open System Integration)] verwaltet Windows-, Linux- und macOS-Clients – von einem Dutzend bis zu mehreren tausend Rechnern. Die Kernkomponente ist ein Linux-Server, der sich um die automatische Installation der Betriebssysteme (nur Windows und Linux), die Verteilung von Software, die Inventarisierung von Hard- und Software sowie um das Patch-Management auf den Clients kümmert. Dazu kommen Module, die den Funktionsumfang erweitern. Zusammengefasst unterstützt opsi die folgenden Features:

* Automatische Softwareverteilung auf den PCs (opsi-Client-Agent)
* Automatische Betriebssystem-Installation (mithilfe des opsi-Servers)
* Hardware- und Software-Inventarisierung

In nur einem einzigen Administrations-Interface verwaltet opsi Clients an mehreren Standorten. Die Konfiguration wird an zentraler Stelle gespeichert: auf dem opsi-Server. Die Depot-Server für die Clients (Installations-Dateien der zu verteilenden Software und Betriebssysteme, Boot-Images) können auch an mehreren Orten liegen.

Dieses Handbuch hat die folgende Struktur:

* xref:releasenotes:releasenotes[Release Notes]
* xref:supportmatrix:supportmatrix[Unterstützte Systeme]
* xref:getting-started[opsi-Server]
* xref:windows-client-manual:windows-client-manual[Windows-Client]
* xref:linux-client-manual:linux-client-manual[Linux-Client]
* xref:macos-client-manual:mac-client-manual[macOS-Client]
* xref:manual:introduction[opsi-Komponenten im Detail]
* xref:opsi-script-manual:opsi-script-manual[opsi-script-Interpreter]
* xref:contribute:contribute[Bei opsi mitmachen]
* xref:copyright:copyright[Copyright]


Die opsi-Community trifft sich im link:https://forum.opsi.org/index.php[opsi-Forum]. Dort finden Sie auch den Link zum opsi-Wiki.

Alle Handbücher stehen unter link:https://download.uib.de/4.2/stable/documentation/[download.uib.de] als im PDF- und HTML-Format zum Download bereit. 

Eine API-Dokumentation zu link:https://docs.opsi.org/python-docs/python-opsi[python-opsi] und link:https://docs.opsi.org/python-docs/python-opsi-common[opsicommon] ist ebenfalls hier zu finden.
