////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:Date:      17.04.2023
:doctype: book

= Willkommen bei opsi!

Das Client-Management-System link:https://www.opsi.org/[opsi (Open System Integration)] verwaltet Windows-, Linux- und macOS-Clients -- von einem Dutzend bis zu mehreren tausend Rechnern. Die Kernkomponente ist ein Linux-Server, der sich um die automatische Installation der Betriebssysteme (nur Windows und Linux), die Verteilung von Software, die Inventarisierung von Hard- und Software sowie um das Patch-Management auf den Clients kümmert. Dazu kommen Module, die den Funktionsumfang erweitern. Zusammengefasst hat opsi die folgenden Features:

* Automatische Softwareverteilung auf den PCs (opsi-Client-Agent)
* Automatische Betriebssystem-Installation (mithilfe des {opsi-server}s)
* Hardware- und Software-Inventarisierung

In nur einem einzigen Administrations-Interface verwaltet opsi Clients an mehreren Standorten. Die Konfiguration wird an zentraler Stelle gespeichert: auf dem opsi-Server. Die Depot-Server für die Clients (Installations-Dateien der zu verteilenden Software und Betriebssysteme, Boot-Images usw.) können auch an mehreren Orten liegen.

Dieses Handbuch hat die folgende Struktur:

* xref:releasenotes:releasenotes.adoc[Release Notes]
* xref:supportmatrix:supportmatrix.adoc[Unterstützte Systeme]
* xref:opsi-server:overview.adoc[opsi-Server]
* xref:windows-client-manual:windows-client-manual.adoc[Windows-Client]
* xref:linux-client-manual:linux-client-manual.adoc[Linux-Client]
* xref:macos-client-manual:mac-client-manual.adoc[macOS-Client]
* xref:manual:introduction.adoc[opsi-Komponenten im Detail]
* xref:server:opsi-script-manual.adoc[opsi-script-Interpreter]
* xref:contribute:contribute.adoc[Bei opsi mitmachen]
* xref:copyright:copyright.adoc[Copyright]

Alle Handbücher stehen unter link:https://download.uib.de/4.2/stable/documentation/[download.uib.de] im PDF-, HTML- und Epub-Format zum Download bereit. Darüber hinaus haben wir Handbücher zu den APIs link:https://docs.opsi.org/python-docs/python-opsi[python-opsi] und link:https://docs.opsi.org/python-docs/python-opsi-common[opsicommon] veröffentlicht.

TIP: Die opsi-Community trifft sich im link:https://forum.opsi.org/index.php[opsi-Forum]. Dort finden Sie auch den Link zum opsi-Wiki.

[[opsi-intro-convention]]
== Konventionen und Schreibweisen

Wir verwenden in diesem Handbuch die folgenden Schreibweisen und Hervorhebungen:

* Datei- und Verzeichnisnamen erscheinen in `Proportionalschrift`.
* Längere Befehle und Listings stehen in eigenen Kästen; Sie können diese bequem per Copy{nbsp}&{nbsp}Paste übertragen: +
[source,prompt]
----
dies ist ein Befehl
----
* In `<spitzen Klammern>` stehen Bezeichnungen, die Sie durch ihre Bedeutung ersetzen müssen. So heißt die Dateifreigabe mit den opsi-Paketen z.{nbsp}B. `<opsi-depot-share>`. Auf einem realen Server liegt sie in der Regel in `/var/lib/opsi/depot`. Das Softwarepaket `<opsi-depot-share>/ooffice` befindet sich also unter `/var/lib/opsi/depot/ooffice`.
* Menüeinträge und Beschriftungen von Schaltflächen erscheinen _kursiv_.
* Tasten und Tastenkombinationen stehen in eckigen Klammern, z.{nbsp}B. [C], [Strg]+[C] usw.
