= Willkommen bei opsi! 

Das Client-Management-System link:https://www.opsi.org/[opsi (Open System Integration)] verwaltet Windows-, Linux- und macOS-Clients – von einem Dutzend bis zu mehreren tausend Rechnern. Die Kernkomponente ist ein Linux-Server, der sich um die automatische Installation der Betriebssysteme (nur Windows und Linux), die Verteilung von Software, die Inventarisierung von Hard- und Software sowie um das Patch-Management auf den Clients kümmert. Dazu kommen Module, die den Funktionsumfang erweitern. Zusammengefasst unterstützt opsi die folgenden Features:

* Automatische Softwareverteilung auf den PCs (opsi-Client-Agent)
* Automatische Betriebssystem-Installation (mithilfe des opsi-Servers)
* Hardware- und Software-Inventarisierung

In nur einem einzigen Administrations-Interface verwaltet opsi Clients an mehreren Standorten. Die Konfiguration wird an zentraler Stelle gespeichert: auf dem opsi-Server. Die Depot-Server für die Clients (Installations-Dateien der zu verteilenden Software und Betriebssysteme, Boot-Images) können auch an mehreren Orten liegen.

Dieses Handbuch hat die folgende Struktur:

* xref:releasenotes:releasenotes[Release Notes]
* xref:supportmatrix:supportmatrix[Unterstützte Systeme]
* xref:getting-started[opsi-Server]
* Windows-Client
* Linux-Client
* macOS-Client
* xref:manual:introduction[opsi-Komponenten im Detail]

1) Einführung/Introduction (ehemals: Willkommen)
2) Release Notes/Release Notes
3) Unterstützte Systeme/Supported Systems (ehem: Supportmatrix)
4) Installation opsi-Server/opsi Server Installation (ehem. Anfang von Getting Started)
5) Windows-Client/Windows Client
6) Linux-Client/Linux Client
7) macOS-Client/macOS Client
8) opsi-Komponenten im Detail/opsi Components in Detail (ehem.: opsi-Handbuch)
9) opsi-script-Interpreter/opsi-script Interpreter
10) Bei opsi mitmachen/How to Contribute to opsi
11) Copyright/Copyright



Wenn Sie neu bei opsi sind, hilft Ihnen das xref:getting-started:getting-started.adoc[Getting Started Handbuch] bei der Installation und Einrichtung.

Eine Virtuelle Maschine mit installiertem opsi-Server und einer kurzen Anleitung finden Sie auf link:https://www.uib.de/de/opsi/opsi-testen-download[uib.de].

Das allgemeine Handbuch finden Sie xref:manual:introduction.adoc[hier].

Die opsi-Community trifft sich im link:https://forum.opsi.org/index.php[opsi-Forum]. Dort finden Sie auch den Link zum opsi-Wiki.

Alle Handbücher stehen unter link:https://download.uib.de/4.2/stable/documentation/[download.uib.de] als PDF oder eigenständiges HTML zum Download bereit. 

Eine API-Dokumentation zu link:https://docs.opsi.org/python-docs/python-opsi[python-opsi] und link:https://docs.opsi.org/python-docs/python-opsi-common[opsicommon] ist ebenfalls hier zu finden.
