////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      25.01.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



[[opsi-manual-versioning-releases]]
= Versionierung und Release-Strategie

Die folgenden Abschnitte sollen einen Einblick geben über die Versionsbezeichnungen der Pakete, die von uns veröffentlicht werden und über das Verfahren dabei.

== Versionierung

Als Major-Version bezeichnen wir eine Menge von Versionen unserer Komponenten, die untereinander kompatibel sind. Die ersten zwei Stellen einer Versionsnummer
bilden dies ab, wie 4.2, 4.3, etc. Für jede Major-Version stellen wir Repositories zur Verfügung - jeweils eigene für die Kategorien `stable`, `testing` und
`experimental`. Mehr zu unseren öffentlichen Repositories siehe <<opsi-manual-versioning-releases-repositories,Repositories für opsi 4.3>>.

Die dritte Stelle einer Versionsnummer repräsentiert die Feature-Version. Wenn wir eine neue Funktionalität in eine Komponente einbauen,
erhöhen wir die dritte Stelle. Updates, die die Feature-Version verändern sind Rückwärts-kompatibel.

Die vierte und letzte Stelle ist die Patch-Version. Wenn Änderungen vorgenommen werden, die kein neues Feature beinhalten (z.B. Beheben von Fehlern)
wird diese erhöht. Kompatibilität bleibt über Patch-Versionen hinweg unverändert.

== Release-Strategie

Neue Pakete veröffentlichen wir in der Kategorie `experimental`.
Diese haben bereits grundlegende Tests durchlaufen.
Wir nutzen diese Pakete auch für weiterführende interne Integrations-Tests.
Diese Pakete sollten Sie normalerweise in keiner Produktiv-Umgebung nutzen, außer wenn diese zur Behebung eines Fehlers in Ihrer Umgebung unbedingt erforderlich sind.
Sind auch die weiteren Integrations-Tests erfolgreich, geben wir die Pakete nach `testing` frei.
Falls es Ihnen wichtig ist, frühzeitig neue Features, Effizienz-Verbesserungen und Ähnliches zu erhalten, nutzen Sie die Pakete aus `testing`.
Einmal monatlich, am letzten Mittwoch des Monats geben wir Pakete als `stable` frei. Falls der Fokus Ihrer Umgebung auf hoher Stabilität liegt,
nutzen Sie die Pakete aus `stable`.
Es gibt eine Ausnahme in dieser Release-Strategie. Wenn in `stable` ein Problem vorliegt, welches kritisch für das Funktionieren
der opsi-Umgebung oder die Sicherheit des Systems ist, gibt es ein so genanntes Hotfix-Release, bei dem Pakete, die das Problem beheben
nach `stable` freigegeben werden, ohne den normalen `stable`-Release-Zeitplan einzuhalten. Auf diese Weise können diese Fehler zeitnah
behoben werden.

[[opsi-manual-versioning-releases-repositories]]
== Repositories für opsi 4.3

Wir veröffentlichen Pakete in Repositories für jede unterstützte Major-Version für die Kategorien `stable`, `testing` und `experimental`.
Zusätzlich gibt es die Unterscheidung nach server-Paketen (.deb/.rpm-Format für opsi-Depotserver), opsi-Paketen (.opsi-Format für opsi-Clients)
und Werkzeugen (ausführbare Dateien für Windows, Linux und macOS).

`stable`-Repositories:

* server-Pakete: https://build.opensuse.org/project/show/home:uibmz:opsi:4.3:stable
* opsi-Pakete: https://opsipackages.43.opsi.org/stable/
* Werkzeuge: https://tools.43.opsi.org/stable/

`testing`-Repositories:

* server-Pakete: https://build.opensuse.org/project/show/home:uibmz:opsi:4.3:testing
* opsi-Pakete: https://opsipackages.43.opsi.org/testing/
* Werkzeuge: https://tools.43.opsi.org/testing/

Die Adressen der `experimental`-Repositories sind analog.

[[opsi-manual-versioning-releases-changelogs]]
== Changelogs

Zu den von uns veröffentlichten Paketen veröffentlichen wir zusammengefasste Beschreibungen der Änderungen (changelogs) unter https://changelog.opsi.org.
