////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////


:Author:    uib gmbh
:Email:     info@uib.de
:Date:      21.04.2014
:Revision:  4.0.5
:doctype:		book

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]

= opsi Version 4.0.5 Release Notes

// Include common opsi copyright
include::../common/opsi_manual_copyright.asciidoc[]

[[opsi-405-releasenotes-overview]]
== Übersicht der Neuerungen

Das opsi Service Releases 4.0.5 weist eine Fülle von Neuerungen und Detailverbesserungen auf. Hier eine Übersicht:

* Ab opsi 4.0.5 werden nun auch folgende Distributionen unterstützt: +
** 

* Keine Unterstützung mehr für: +
** 

Da auch die oben genannten Repositories geschlossen werden, sind die Pakete mit 4.0.5 nicht mehr verfügbar. Für den Fall, dass die letzten freigegebenen Pakete für diese Distributionen noch einmal benötigen werden, haben wir ein Archiv dieser Repositories abgelegt, dieses befindet sich unter:

http://download.uib.de/opsi4.0/archiv/discontinued_platforms/


* opsi-configed: +
** Umfangreich überarbeitete Version

* opsi Serverkomponenten: +
** 

* Neues opsi-bootimage basierend auf Kernel 

* Windows Netboot Produkte +
** 

* opsi-winst / opsi-script: +

** Neue Konstanten:

*** `%opsiTmpDir%` : `c:\opsi.org\tmp` // since 4.11.4.3

*** `%opsiLogDir%` : `c:\opsi.org\log` // since 4.11.4.3

** Neue Funktionen zum Umgang mit key/valu Paaren in Konfigurationsdateien:

*** Stringfunktion: `getValueFromFile(`<key string>, <file name>`)` //since 4.11.4.4 [W/L]

*** Stringfunktion: `getValueFromFileBySeparator(`<key string>,<separator string>,<file name>`)` //since 4.11.4.4 [W/L]

*** PatchTextFile Sektionskommandos:

*** `setKeyValueSeparator` <separator char> //since 4.11.4.4 [W/L]

*** `setValueByKey` <keystr> <valuestr> //since 4.11.4.4 [W/L]

** Encoding Funktionen (Handbuch lesen !):

*** string function `reencodestr(` <str> , <from>, <to> `)`

*** stringlist function `reencodestrlist(` <strlist> , <from>, <to> `)`

** Sonstiges:

*** `saveTextFile(`<list>, < filename>`)` //since 4.11.4.4 [W/L]

*** stringlist function `shellCall(` <cmd> `)` ; returns the output of (sysnative) shell with cmd

*** Befehl `IncludeLog` jetzt mit zusätzlichen encoding Parameter



* opsi Linux Unterstützung: +
Siehe gesondertes Kapitel.

* opsi uefi (Netboot) Unterstützung:
Siehe gesondertes Kapitel.

* opsi-client-agent: +
** Fixes für Windows 8.x (Loginblocker)

* opsi-setup-detector: +
**

////
Für Details lesen Sie bitte das opsi-v405-releasenotes Handbuch bzw. die überarbeiteten opsi Handbücher.
////


[[opsi-405-releasenotes-eol]]
== Abkündigung

In diesem Kapitel werden die Abkündigungen aufgelistet. Diese Distributionsversionen werden aus verschiedenen Gründen nicht mehr weiter von opsi unterstützt.

[[opsi-405-releasenotes-eol_python25]]
=== Abkündigung der Python 2.5 Unterstützung

dummy text

[[opsi-405-releasenotes-eol_distros]]
=== Abkündigung: Distributionsversionen

Folgende Systeme werden mangels Maintainance vom Hersteller abgekündigt:

** 

Auch die oben genannten Repositories wurden am 31.12.2013 geschlossen. Für betroffene Installationen empfehlen wir dringend ein OS-Upgrade durch zu führen. Allerdings sollten Sie vorher prüfen, ob die Version zu der Sie aktualisieren wollen auch von opsi unterstützt wird.



[[opsi-405-releasenotes-installation]]
== Hinweise zur Installation

Wir empfehlen vor der Installation des Updates (sicherheitshalber) mit opsi-backup eine Sicherung Ihres Backends durchzuführen:
[source,prompt]
----
opsi-backup create
----


Die Produkte welche im Rahmen dieses Releases veröffentlicht werden, sind in etlichen Teilen voneinander abhängig. Sie sollten daher nicht versuchen nur Teile zu installieren.

Sie sollten dabei zuerst den Server updaten und danach die opsi-Produkte.


[[opsi-405-releasenotes-installation-opsipackages]]
=== Hinweise zum aktualisieren von opsi-Paketen

Die Installation erfordert keine besonderen Arbeiten. Sie erfolgt im Rahmen der normalen Updates ihres Servers und der opsi-Produkte.

Sie sollten dabei zuerst den Server updaten. Benutzen Sie dazu die Befehle entsprechend Ihrer Linux-Distribution. +
Danach die opsi-Produkte. Dies erledigt der opsi-product-updater:

[source,prompt]
----
opsi-product-updater -i -vv
----

Sollten Sie eine Multidepot Umgebung haben, so machen Sie zunächst das Upgrade auf Ihrem config-server, bevor Sie die Depots upgraden.


// Include common opsi copyright
include::../common/opsi_manual_linux.asciidoc[]


[[opsi-configed]]
== opsi-configed 

dummy text

[[opsi-405-releasenotes-bootimage]]
== Opsi-linux-bootimage

dummy text

[[opsi-405-releasenotes-misc]]
== Sonstiges

[[opsi-405-releasenotes-misc-changelogs]]
=== Changelogs:

[[opsi-405-releasenotes-misc-changelogs-opsi-client-agent]]
==== Changelog opsi-client-agent

opsi-client-agent (4.0.4.5-4) stable; urgency=low

  * opsi-winst 4.11.4.4
  
 -- Detlef Oertel <d.oertel@uib.de>  Fri, 25 Apr 2014 15:00:00 +0100


opsi-client-agent (4.0.4.5-3) stable; urgency=low

  * new opsiloginblocker.dll V1.2.0.5/credential provider filter (no multiple timeouts)
  * new opsigina.dll 1.3.0.2 (no multiple timeouts) 
  * fix in lib directory of opsi-winst; https://forum.opsi.org/viewtopic.php?f=6&t=6142
  * sub_restore_productOnClient: restore productOnClient if found in c:\opsi.org\tmp (for capture image use)
  * opsi-winst 4.11.3.11
  
 -- Miriam Michaelis <m.michaelis@uib.de>  Tue, 18 Mar 2014 15:00:00 +0100

opsi-client-agent (4.0.4.5-2) stable; urgency=low

  * opsi-winst 4.11.4.3
  * use of isDriveReady to disable  critical-error-handler message box. (Drive not ready)  
  
 -- Detlef Oertel <d.oertel@uib.de>  Thu, 20 Mar 2014 15:00:00 +0100


opsi-client-agent (4.0.4.5-1) stable; urgency=low

  * new credential provider filter with fix for >= nt6.2 opsiloginblocker.dll V1.2.0.2
  * loginblocker logfile written to dir opsi.org\log
  
 -- Miriam Michaelis <m.michaelis@uib.de>  Tue, 18 Mar 2014 15:00:00 +0100


[[opsi-405-releasenotes-misc-changelogs-opsi-winst]]
==== Changelog opsi-winst

opsi-winst/opsi-script (4.11.4.4) stable; urgency=low

  * osfunclin: RunCommandAndCaptureOut: Log exitcode on Loglevel LLInfo
  * osparser: linkActionsMain: fix for index out of bound (while (i <= Sektion.count))  fixes: #958
  * osfunc: StartProcess_cp: log error if time out is reached (inc's error counter)  fixes #506
  * new commands in PatchTextFile (osparser:doTextpatchMain):
         'setKeyValueSeparator char' sets Separator for key value pairs (default is '=')
         'setValueByKey keystr valuestr' search exitsing key and sets the given value.
           If the key not exists, the key/value pair will be created below the line cursor.
  * osparser: scriptstopped := true on ExitWindows /ImmediateReboot and  /ImmediateLogout
  * new function: getValueFromFile (<key string>,<file name> ) : string
  * new function: getValueFromFileBySeparator (<key string>,<separator string>,<file name> ) : string
  * new function: saveTextFile(<list>, < filename>) : bool
  * osparser: TuibInstScript.doAktionen: output initalized (created) fixes #974
  * osfunc: enhanced: TXStringList.getStringValue
  * osparser: produceStringlist: fix in emptylist() function

-- Detlef Oertel <d.oertel@uib.de>  Thu,  20 Mar 2014:15:00:00 +0200


opsi-winst/opsi-script (4.11.4.3) stable; urgency=low

  * opsparser: doFileActions: fix for mixed File section modifiers
  * osfunc: TuibRegistry.WriteEntry: fix logging if regtype is changed: fixes #780
  * osfunc: wait for parent ending also if waitforprocessending is true
  * osfunc: FileCopyWin: use of windows.copyFile instead of fileutils.copyFile
  * osparser: Stingreplace with IgnoreCase for %userprofiledir%  fixes #877
  * osparser: new constant %opsiTmpDir% (c:\opsi.org\tmp ; /tmp )
  * osparser: new constant %opsiLogDir% (c:\opsi.org\log ; /var/log/opsi-client-agent/opsi-script )
  * osparser: new command: FatalOnRuntimeError (default = false)
  * osparser: takeString: LogError if index out of bounds; Fatal if FatalOnSyntaxError
  * oslog: escape control chars
  * osfunc: allcopy/execdelete: handle directories with additional attributes (e.g. hidden)
  * osparser: new function doRegistryNTUserDat
  * new Registry Parameter /NTuserDat: <path to ntuser.dat>
  * osmain: ProcessProduct: looks before processing a product if there is still a action request
  * osparser: for fileExists: replace GetFileInfo by  "FileExists() or DirectoryExists()"
  * fixes to really stop the script interpretation after isfatalerror, issuccess, issuspended
  * new unit opsihwbiosinfo based on tsmbios
  * new infomap getHWBiosInfoMap
  * new bool function runningOnUefi      fixes #908
  * new bool function isDriveReady(str)
  * doFileActions: disable windows critical Error Message boxes (SetErrorMode(SEM_FAILCRITICALERRORS))

-- Detlef Oertel <d.oertel@uib.de>  Mon,  9 Dec 2013:15:00:00 +0200



opsi-winst/opsi-script (4.11.4.2) stable; urgency=low

  * make 4.11.4 working under windows
  * osencoding: searchencoding: new methode to read encoding
  * osinteractivegui: opendialog knows now *.ins and *.opsiscript
  * new string function reencodestr(str, from, to)
  * new stringlist function reencodestrlist(strlist, from, to)
  * new stringlist function shellCall( cmd ) ; returns the output of (sysnative) shell with cmd
  * getipByName now uses resolveip at linux
  * manifest extended for win 8.1: <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>:
    http://msdn.microsoft.com/en-us/library/windows/desktop/dn302074%28v=vs.85%29.aspx
  * fix: use of sysnative with winbatch

-- Detlef Oertel <d.oertel@uib.de>  Mon,  23 Sep 2013:15:00:00 +0200

opsi-winst/opsi-script (4.11.4.1) stable; urgency=low

  * splitted project to opsi-script and opsi-script-nogui
  * splitted unit osmain to osmain and osinteractivegui
  * changed unit names:  * wi* -> os*
  * fixed: Feature  491 : real origin file and line number on syntax error (also on included parts)
  * new unit osencode which contain encoding functions
      known encodings are
        UTF-8      utf8
        UTF-8BOM   utf8bom
        Ansi       ansi
        CP1250     cp1250
        CP1251     cp1251
        CP1252     cp1252
        CP1253     cp1253
        CP1254     cp1254
        CP1255     cp1255
        CP1256     cp1256
        CP1257     cp1257
        CP1258     cp1258
        CP437      cp437
        CP850      cp850
        CP852      cp852
        CP866      cp866
        CP874      cp874
        CP932      cp932
        CP936      cp936
        CP949      cp949
        CP950      cp950
        ISO-8859-1 iso8859-1
        ISO-8859-2 iso8859-2
        KOI-8      koi8
        UCS-2LE    ucs2le
        UCS-2BE    ucs2be
  * fixed: Bug 554 : includelogtail calls reencode
  * command IncludeLog has now an optional 3rd parameter sourceEncoding which may be 'auto', 'system' or a valid encoding.
  * nearly all loadfromfile now with reencode
  * script encoding can now be given with for example
      encoding=utf8
  * loglevel of if/else/endif changed to LLinfo (6) fixes 539
  * loglevel of setLoglevel  changed to LLinfo (6) fixes 535
  * new command 'IsSuspended' interupts script execution and leave productOnClient unchanged   Feature #614
  * shellbatch output is now captured
  * fix in linux getprocesslist: output now: short binary name;pid;user;full command line


-- Detlef Oertel <d.oertel@uib.de>  Tue,  30 Jul 2013:15:00:00 +0200


opsi-winst/opsi-script (4.11.4) stable; urgency=low

  * port to Linux
  * removed logginig via syslog
  * %opsiDepotId%
  * changed unit names:
     * wisynth -> osparser
     * wibatch -> osbatchgui
     * wimain -> osmain
     * wifunc -> osfunc
     * wiwin32 -> osfuncwin2
  * new string function: getLinuxDistroType
  * new stringlist function: getLinuxVersionMap

-- Detlef Oertel <d.oertel@uib.de>  Tue,  30 Apr 2012:15:00:00 +0200


[[opsi-405-releasenotes-misc-changelogs-windows-netboot]]
==== Changelog windows netboot products

dummy text

[[opsi-405-releasenotes-misc-changelogs-python-opsi]]
==== Changelog python-opsi

dummy text
 
[[opsi-405-releasenotes-misc-changelogs-opsipxeconfd]]
==== Changelog opsipxeconfd

dummy text

[[opsi-405-releasenotes-misc-changelogs-opsiconfd]]
==== Changelog opsiconfd

dummy text

[[opsi-405-releasenotes-misc-changelogs-opsi-utils]]
==== Changelog opsi-utils

dummy text

[[opsi-405-releasenotes-misc-changelogs-opsi-linux-bootimage]]
==== Changelog opsi-linux-bootimage

dummy text

[[opsi-405-releasenotes-misc-changelogs-opsi-depotserver]]
==== Changelog opsi-depotserver

dummy text

[[opsi-405-releasenotes-misc-changelogs-opsi4ucs]]
==== Changelog opsi4ucs

dummy text

[[opsi-405-releasenotes-opsi-configed]]
==== Changelog opsi-configed

dummy text

[[opsi-405-releasenotes-opsi-swaudit]]
==== Changelog opsi-swaudit

dummy text
