////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; http://creativecommons.org/licenses/by-sa/3.0/de/
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; http://creativecommons.org/licenses/by-sa/3.0/
; http://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////


:Author:    uib gmbh
:Email:     info@uib.de
:Date:      21.04.2014
:Revision:  4.0.5
:doctype:		book

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]

= opsi Version 4.0.5 Release Notes

// Include common opsi copyright
include::../common/opsi_manual_copyright.asciidoc[]

[[opsi-405-releasenotes-overview]]
== Übersicht der Neuerungen

Das opsi Service Releases 4.0.5 weist eine Fülle von Neuerungen und Detailverbesserungen auf. Hier eine Übersicht:

* Ab opsi 4.0.5 werden nun auch folgende Distributionen unterstützt: +
** 

* Keine Unterstützung mehr für: +
** 

Da auch die oben genannten Repositories geschlossen werden, sind die Pakete mit 4.0.5 nicht mehr verfügbar. Für den Fall, dass die letzten freigegebenen Pakete für diese Distributionen noch einmal benötigen werden, haben wir ein Archiv dieser Repositories abgelegt, dieses befindet sich unter:

http://download.uib.de/opsi4.0/archiv/discontinued_platforms/


* opsi-configed: +
** Umfangreich überarbeitete Version

* opsi Serverkomponenten: +
** 

* Neues opsi-bootimage basierend auf Kernel 

* Windows Netboot Produkte +
** 

* opsi-winst: +
** 

* opsi-client-agent: +
** 

* opsi-setup-detector: +
**

////
Für Details lesen Sie bitte das opsi-v405-releasenotes Handbuch bzw. die überarbeiteten opsi Handbücher.
////


[[opsi-405-releasenotes-eol]]
== Abkündigung

In diesem Kapitel werden die Abkündigungen aufgelistet. Diese Distributionsversionen werden aus verschiedenen Gründen nicht mehr weiter von opsi unterstützt.

[[opsi-405-releasenotes-eol_python25]]
=== Abkündigung der Python 2.5 Unterstützung

dummy text

[[opsi-405-releasenotes-eol_distros]]
=== Abkündigung: Distributionsversionen

Folgende Systeme werden mangels Maintainance vom Hersteller abgekündigt:

** 

Auch die oben genannten Repositories wurden am 31.12.2013 geschlossen. Für betroffene Installationen empfehlen wir dringend ein OS-Upgrade durch zu führen. Allerdings sollten Sie vorher prüfen, ob die Version zu der Sie aktualisieren wollen auch von opsi unterstützt wird.



[[opsi-405-releasenotes-installation]]
== Hinweise zur Installation

Wir empfehlen vor der Installation des Updates (sicherheitshalber) mit opsi-backup eine Sicherung Ihres Backends durchzuführen:
[source,prompt]
----
opsi-backup create
----


Die Produkte welche im Rahmen dieses Releases veröffentlicht werden, sind in etlichen Teilen voneinander abhängig. Sie sollten daher nicht versuchen nur Teile zu installieren.

Sie sollten dabei zuerst den Server updaten und danach die opsi-Produkte.


[[opsi-405-releasenotes-installation-opsipackages]]
=== Hinweise zum aktualisieren von opsi-Paketen

Die Installation erfordert keine besonderen Arbeiten. Sie erfolgt im Rahmen der normalen Updates ihres Servers und der opsi-Produkte.

Sie sollten dabei zuerst den Server updaten. Benutzen Sie dazu die Befehle entsprechend Ihrer Linux-Distribution. +
Danach die opsi-Produkte. Dies erledigt der opsi-product-updater:

[source,prompt]
----
opsi-product-updater -i -vv
----

Sollten Sie eine Multidepot Umgebung haben, so machen Sie zunächst das Upgrade auf Ihrem config-server, bevor Sie die Depots upgraden.


// Include common opsi copyright
include::../common/opsi_manual_linux.asciidoc[]


[[opsi-configed]]
== opsi-configed 

dummy text

[[opsi-405-releasenotes-bootimage]]
== Opsi-linux-bootimage

dummy text

[[opsi-405-releasenotes-misc]]
== Sonstiges

[[opsi-405-releasenotes-misc-changelogs]]
=== Changelogs:

[[opsi-405-releasenotes-misc-changelogs-opsi-client-agent]]
==== Changelog opsi-client-agent

dummy text

[[opsi-405-releasenotes-misc-changelogs-opsi-winst]]
==== Changelog opsi-winst

dummy text

[[opsi-405-releasenotes-misc-changelogs-windows-netboot]]
==== Changelog windows netboot products

dummy text

[[opsi-405-releasenotes-misc-changelogs-python-opsi]]
==== Changelog python-opsi

dummy text
 
[[opsi-405-releasenotes-misc-changelogs-opsipxeconfd]]
==== Changelog opsipxeconfd

dummy text

[[opsi-405-releasenotes-misc-changelogs-opsiconfd]]
==== Changelog opsiconfd

dummy text

[[opsi-405-releasenotes-misc-changelogs-opsi-utils]]
==== Changelog opsi-utils

dummy text

[[opsi-405-releasenotes-misc-changelogs-opsi-linux-bootimage]]
==== Changelog opsi-linux-bootimage

dummy text

[[opsi-405-releasenotes-misc-changelogs-opsi-depotserver]]
==== Changelog opsi-depotserver

dummy text

[[opsi-405-releasenotes-misc-changelogs-opsi4ucs]]
==== Changelog opsi4ucs

dummy text

[[opsi-405-releasenotes-opsi-configed]]
==== Changelog opsi-configed

dummy text

[[opsi-405-releasenotes-opsi-swaudit]]
==== Changelog opsi-swaudit

dummy text