////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; Until we found a better license:
; All rights reserved.
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      01.05.2011
:Revision:  4.0.1
:toclevels: 6

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]

opsi-401-releasenotes-upgrade-manual
====================================


[[opsi-401-release-manual-introduction]]
== Introduction

Cette documentation n'est pas écrit pour commencer avec opsi, utilisez le manuel 'opsi-getting-started' (Mise en route d’opsi) au lieu.

Opsi 4.0.1 est une version mineure, respectivement une 'feature pack'. Cela signifie que rien ne change fondamentalment, et la plupart des choses sont des nouveaux add-ons.

*Cela signifie, qu'il ya rien de spécial à faire pour une mise à niveau.* Enfin il y a quelques tâches recommandées à faire après la mise à niveau.
 
Ce manuel devrait:

* vous donner des informations sur les nouvelles fonctionnalités opsi 4.0.1
* vous dire quoi faire après avoir terminé la mise à niveau
* donner des informations sur les bugs connus
* annoncer la 'fin de vie' de opsi 3



[[opsi-401-release-manual-whats-new]]
== Ce qui est nouveau dans opsi 4.0.1

[[opsi-401-release-manual-whats-new-overview]]
=== Aperçu

Voici un résumé des nouvelles fonctionnalités de opsi 4.0.1:


* opsi WAN/VPN Extension pour intégrer les clients situés derrière des connexions lentes.

** La mise en cache locale des fichiers d'installation.

** La mise en cache locale des méta-données d'installation.

** Télécharger les données d'installation en tant que processus d'arrière-plan avec une bande passante dynamique, afin que l'utilisateur ne sera pas perturbée.

** Le téléchargement de données peut être interrompu à n'importe quel moment et ne redémarrera pas, mais continuera dès que possible.

** Installation à l'aide de la mémoire cache locale - aucune connexion réseau n'est requise.

** L'utilisation alternative du protocole smb/cifs ou de https/webdav pour télécharger les fichiers requis pour le cache local.
** Possibilité d'utiliser https/webdav aussi pour l'installation de l'OS.
** {opsiclientd} page d'info pour la visualisation de l'activité de {opsiclientd}.
** C'est un projet de cofinancement, ce qui signifie que vous devez l'acheter jusqu'à ce que tous les coûts du projet sont gagnés.

* sélection dynamique de dépôt:

** Dans un endroit multi Environnement/multi Depot, un client est désormais capable de détecter quel depot est le meilleur pour charger le logiciel nécessaire.
** C'est un projet de cofinancement, ce qui signifie que vous devez l'acheter jusqu'à ce que tous les coûts du projet sont gagnés.

* Logiciels sur demande

** Vous pouvez assigner des produits à un groupe de produits 'Logiciels sur demande'.
** Les utilisateurs peuvent choisir le logiciel de ce groupe pour l'installation par OPSI sur leurs clients. Ceci est fait en utilisant un site Web local qui est produite par {opsiclientd}.

*  interface de gestion opsi ({opsi-configed}) améliorations 

** Éditeur de propriété depot.
** Sélection interactive de la langue GUI.
** Requête interactive et affichage des clients qui sont en ligne.
** Un pseudo groupe de clients qui contient automatiquement tous les clients avec un résultat d'installation: 'échoué'.
** Possibilité d'utiliser les groupes de produits.
** Les colonnes qui sont visibles dans {opsi-configed} peuvent désormais être stockés sur le serveur.
** Les clients peuvent désormais être sélectionné en utilisant un champ de recherche.
** Gestion des licences: A l'onglet 'Reconciliation' désormais seuls les clients qui ont une entrée dans la table sont présentés.
** Vous pouvez sélectionner des clients selon les critères, si un produit est d'une version inférieur à celle disponible sur le serveur.
** Vous pouvez changer le niveau de log pendant l'exécution de configed.
** La gestion des licences prend désormais de multiples occurrences de modèles d'inventaire logiciel, qui sont affectés à un pool de licences seulement comme une seule installation de ce logiciel. Cela signifie que si par exemple un groupe de licence 'Office2010' est attribué à 10 différents modèles de l'inventaire logiciel, une seule installation sera compté, même si nous trouvons tous les 10 modèles sur un seul client.

* Nouveau produits netboot Windows NT6 (Partition de démarrage, partition système, intégration des pilotes amélioré)
* Configuration de la résolution de noms dans le nouveau fichier de configuration  `/etc/opsi/backends/hostcontrol.conf`

* Configuration des des broadcasts dirigés dans le nouveau fichier de configuration `/etc/opsi/backends/hostcontrol.conf`

* Nouveau 'opsi-client-agent' avec la configuration améliorée et notifiant amélioré

* Le mot de passe de 'root' dans opsi-linux-bootimage peut maintenant être défini via 'opsi-linux-bootimage.append' paramètre host `pwh=<password-hash>`

* Une authentification de {opsi-server} au niveau du client est maintenant possible

[[opsi-401-release-manual-whats-new-mustread]]
=== Ce que vous devez lire

Dans le manuel-opsi les chapitres:

* Outil: Interface de gestion: {opsi-configed}
* opsi-client-agent
* Sélection de dépôt dynamiques
* WAN extension
* Logiciels sur demande
* HostControl-Backend
* Produits Netboot: Paramétrage de opsi-linux-bootimage

Dans ce manuel:
<<opsi-401-release-manual-recommended>>

[[opsi-401-release-manual-upgrade]]
== Mise à jour d'un environnement OPSI 4.0 vers OPSI 4.0.1

opsi 4.0.1 est plus un 'pack de fonctionnalités' q'une version mineure. La plupart des parties de cette version sont des extensions et il ya seulement quelques changements mineurs. Donc il n'y a rien de spécial à faire afin d'obtenir cette mise à niveau. Tous les nouveaux paquets iront au dépôt OPSI 4.0. Vous obtiendrez tous les nouveaux paquets par une mise à jour normale de votre serveur et un appel de 'opsi-product-updater'. 

[[opsi-401-release-manual-recommended]]
== Tâches recommandées après la mise à niveau

[[opsi-401-release-manual-recommended-customize-nt6unattendxml]]
=== NT6 netboot produits de personnalisation unattend.xml 

Opsi 4.0.1 Windows NT6 produits netboot nécessite un nouveau `custom/unattend.xml`. Sauvegardez et remplacez votre `custom/unattend.xml` avec le nouveau modèle `opsi/unattend.xml.template`.

Pour plus de détails voir la section 'Répertoire opsi / custom' dans le manuel 'opsi-getting-started'.

[[opsi-401-release-manual-recommended-depotreadonly]]
=== Sécurité: Dépôt partage en lecture seule
Pour des raisons de sécurité, le dépôt de partage, doit être en lecture seule. Un dépôt partage qui n'est pas en lecture seule, peut être infecté par un virus lors de l'installation du logiciel à un client infecté et transmettre le virus, peu après, par l'intermédiaire de opsi.

La méthode recommandée d'y parvenir est, depuis 4.0.1:

Exécutez sur tous les '{opsi-server}s' (aussi sur '{opsi-depotserver}s') les commandes suivantes:

[source,prompt]
----
opsi-setup --auto-configure-samba
----

Cette commande crée un nouveau partage samba 'opsi_depot' qui est en lecture seule. Ce partage pointe vers le répertoire `/var/lib/opsi/depot`. Dans une distribution Linux ce répertoire sera un lien symbolique vers le répertoire `/opt/pcbin/install`.

Pour dire à tous les clients d'utiliser le nouveau partage, vous devez exécuter le script suivant dans '{opsi-configserver}':

[source,prompt]
----
for depot in $(opsi-admin -dS method host_getIdents unicode "{\"type\":\"OpsiDepotserver\"}"); do
   echo "Depot: $depot"
   depot_remote=$(opsi-admin -dS method host_getObjects [] "{\"id\":\"$depot\"}" | grep "depotRemoteUrl=" | cut -d "=" -f2)
   depot_local=$(opsi-admin -dS method host_getObjects [] "{\"id\":\"$depot\"}" | grep "depotLocalUrl=" | cut -d "=" -f2)
   depot_remote_new=$(echo $depot_remote | sed "s|/opt_pcbin/install|/opsi_depot|")
   depot_local_new=$(echo $depot_local | sed "s|/opt/pcbin/install|/var/lib/opsi/depot|")
   servertype=$(opsi-admin -dS method host_getObjects [] "{\"id\":\"$depot\"}" | grep "type=" | cut -d "=" -f2)
   opsi-admin -d method host_updateObjects "{\"type\":\"$servertype\",\"id\":\"$depot\",\"depotLocalUrl\":\"$depot_local_new\",\"depotRemoteUrl\":\"$depot_remote_new\"}"
done
opsi-admin -d method config_createUnicode  opsiclientd.action_processor.remote_dir "path to action processor" "\\opsi-winst\\files\\opsi-winst" "\\opsi-winst\\files\\opsi-winst"
----

[[opsi-401-release-manual-recommended-deployclient]]
=== Déployer le nouveau opsi-client-agent
Vous devez installer le nouveau opsi-client-agent tôt sur tous vos clients. Ceci évite le risque de problèmes de communication entre le client et le serveur dans les mises à jour futures.

[[opsi-401-release-manual-known-bug]]
== Les bogues connus

* Pas de bugs connus pour le moment

[[opsi-401-release-manual-end-of-support]]
== Annonce de la fin du support pour opsi 3

Avec opsi 4.0.1 nous annonçons aujourd'hui neuf mois après la sortie de la nouvelle stable opsi 4, la fin du support pour opsi 3 pour le 1. Juillet 2011.

Concrètement:

* Nous n'allons pas vérifier tout nouveaux paquets pour la fonctionnalité dans un environnement opsi 3.

* Les nouveaux paquets peuvent avoir une actualité opsi 4 client-agent comme condition préalable.

* Il n'y aura plus de solution pour opsi 3.

* uib ne continuera pas à maintenir un environnement de test pour opsi 3. Ainsi tout appel de support pour opsi 3 prendra plus de temps et sera donc plus cher. 

* Nous vous recommandons fortement de mettre à niveau toutes les installations opsi 3 avant le 1. Juillet 2011 vers opsi 4.

