////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////
:Author:    uib gmbh
:Email:     info@uib.de
:Date:      18.12.2022
:Revision:  4.2
:toclevels: 6
:doctype:   book

// Include common opsi terms
ifeval::["{mode}" == "antora"]
include::common:partial$opsi_terms.adoc[]
endif::[]

[[opsi-manual-abo-products-introduction]]
= opsi Abo Produkte

[[opsi-manual-abo-products-introduction-firststeps]]
== Initiale Bereitstellung von Paketen aus dem Abobereich

Zur Bereitstellung der benötigten Pakete können Sie diese manuell herunterladen oder aber alle Pakete nach Anpassung der Konfiguration des `opsi-package-updater` über diesen installieren.


[[opsi-manual-abo-products-introduction-third]]
== Konfiguration des `opsi-package-updater` / Aktualisierung der Abo-Pakete

Für den weiteren Betrieb ist es empfohlen, die Repository-Konfiguration in '/etc/opsi/package-updater.repos.d/' abzulegen.
Eine entsprechende Konfigurationsdatei erhalten Sie mit Ihren Zugangsdaten.

WARNING: Bei Bedarf muss in diesen Dateien noch der Zugang über einen Proxy konfiguriert werden!

Es bietet sich anschließend an, gezielt nur die benötigten Pakete aus den neuen Repositories zu installieren:
[source,shell]
----
# Beispiel: Pakete für mshotfix, Plattform Windows 10 x64 2009-22h2 / Server 2016 / 2019 / 2022 / Windows 11 22H2 installieren
opsi-package-updater --repo uib_abo_mshotfix install mshotfix mshotfix-win10-2009-x64-glb mshotfix-win10-1607-x64-glb mshotfix-win10-1809-x64-glb mshotfix-win2022 mshotfix-win11-22h2
# Beispiel: Pakete für msoffice Office 2016 installieren
opsi-package-updater --repo uib_abo_msoffice install office_2016_hotfix
# Beispiel: Pakete für standard produkte firefox und libreoffice installieren
opsi-package-updater --repo uib_abo_standard install firefox libreoffice
----

Es ist möglich, gezielt benötigte Pakete zu installieren, bspw. nur die Pakete für das Update von Windows 10 22H2 und Windows 11 22H2:
[source,shell]
----
opsi-package-updater -v install mshotfix mshotfix-win10-2009-x64-glb mshotfix-win11-22h2
----

Für die Aktualisierung der Pakete wird der `opsi-package-updater` empfohlen.

Mittels Aufruf von `opsi-package-updater -v update` können dann z.B. per Cronjob die installierten Pakete aktualisiert werden.

Eine gleichwertige Variante ist, für jedes Repository die Pakete gezielt zu aktualisieren:
[source,shell]
----
# Pakete für mshotfix aktualisieren
opsi-package-updater --repo uib_abo_mshotfix update
# Pakete für msoffice aktualisieren
opsi-package-updater --repo uib_abo_msoffice update
# Pakete für standard produkte aktualisieren
opsi-package-updater --repo uib_abo_standard update
----


[[opsi-manual-abo-products-introduction-second]]
== Festlegung von Default-Properties

Bei der nichtinteraktiven Installation von opsi-Paketen werden auf einem _opsi-Configserver_ bzw. einem _{opsi-Server}_ die Paket default-Properties als default festgelegt.

Ab opsi Version 4.0.5 können die _{opsi-Server}_-default-Properties über das Managementinterface _{opsi-Configed}_ festgelegt werden.

Bei einer anschliessenden Installation einer neueren Paketversion mittels _opsi-package-manager_ oder `opsi-package-updater` bleiben die eingestellten depot default Properties erhalten.





[[opsi-manual-abo-products-mshotfix]]
== Update-Abo 'MS-Hotfixes'
Regelmäßige Updates des Produktes mshotfix (Hotfixes für Windows 2012, Windows 8.1 / 2012-R2, Windows 10 / Windows 2016 / Windows 2019 / Windows 2022 / Windows 11).

WARNING: Von Microsoft nicht mehr unterstützte Versionen werden als "failed" angezeigt: 1507 "non"-ltsb, 1511 und 1607 "non"-ltsb außer Education und
Enterprise

Das Update erscheint jeweils innerhalb von 3 Arbeitstagen nach dem Erscheinen eines von Microsoft als wichtig oder kritisch eingeschätzten Patches.

https://www.microsoft.com/de-de/msrc/security-update-severity-rating-system
[options="header"]
|==========================
| Bewertung | Beschreibung
| Kritisch | Hierbei handelt es sich um ein Sicherheitsrisiko, bei dessen Ausnutzung Code ohne Benutzerinteraktion ausgeführt werden könnte. Dieses ist beispielsweise in Fällen von sich selbstständig verbreitender Schadsoftware wie Netzwerkwürmer oder nicht vermeidbaren Nutzungsfällen gegeben, bei denen Code ohne Warnungen oder Eingabeaufforderungen ausgeführt werden kann. Darunter kann das Öffnen einer Webseite oder E-Mail fallen.
Microsoft empfiehlt Kunden, kritische Updates sofort anzuwenden.
| Wichtig | Hierbei handelt es sich um ein Sicherheitsrisiko, dessen Ausnutzung die Vertraulichkeit, Integrität oder Verfügbarkeit von Benutzerdaten oder die Integrität oder Verfügbarkeit von Verarbeitungsressourcen gefährden kann. Darunter können häufige Nutzungsfälle fallen, z. B., dass der Client mit Warnungen oder Eingabeaufforderungen kompromittiert wird (unabhängig von Herkunft, Qualität oder Nützlichkeit der Aufforderung). Auch sequenzielle Benutzeraktionen, die keine Eingabeaufforderungen oder Warnungen generieren, sind eingeschlossen.
Microsoft empfiehlt Kunden, wichtige Updates so früh wie möglich anzuwenden.
| Mittel | Die Auswirkung des Sicherheitsrisiko wird durch Faktoren wie Authentifizierungsanforderungen oder eine ausschließliche Anwendbarkeit auf nicht dem Standard entsprechende Konfigurationen erheblich verringert.
Microsoft empfiehlt Kunden dennoch, diese Sicherheitsupdates anzuwenden.
| Niedrig | Die Auswirkung des Sicherheitsrisikos wird durch die Eigenschaften der betroffenen Komponente erheblich verringert. Microsoft empfiehlt Kunden, zu evaluieren, ob das Sicherheitsupdate auf die betroffenen Systeme angewendet werden soll.
|==========================


Das opsi-mshotfix Paket verwendet (wie WSUS Offline Update http://forums.wsusoffline.net/viewtopic.php?f=7&t=172 Abdeckung des / Coverage of WSUS Offline Update ) für den Download Microsoft's Update-Katalogdatei wsusscn2.cab, um die erforderlichen Patches zu ermitteln.
Diese Katalogdatei enthält mindestens alle als „kritisch“ und „sicherheitsrelevant“ eingestuften Updates, aber nicht notwendigerweise alle „wichtigen“ und „optionalen“.

Die opsi mshotfix-Pakete sind modular aufgebaut.
Das Basis-Paket „mshotfix“ beinhaltet nur ein Skript zum Installieren der Patches. Die eigentlichen Patches sind gesondert in separaten Paketen enthalten.

.mshotfix Client-Betriebssystem Voraussetzung
|==========================================
|OS
|Windows 7 SP1 / Windows 2008 R2 SP1
|Windows 8 / Windows 2012
|Windows 8.1 / Windows 2012 R2
|Windows 10 / Windows 2016 / Windows 2019 / Windows 2022
|Windows 11
|==========================================


WARNING: Wan/VPN Modul Die modularen Pakete für Windows 11  / Windows Server 2022 benötigen  opsi-client-agent >= opsi-client-agent 4.2.0.43-1 bzw. opsiclientd  >= 4.2.0.132

Auf unserem Download-Server ist die Struktur des Abo verzeichnisses

[source,configfile]
----
mshotfix
  !-opsi4/
     !-glb/	Basis-Paket mshotfix sowie globale Patchpakete
     		mshotfix-win8-win2012-x64-glb
     		mshotfix-win81-x86-glb
     		mshotfix-win81-win2012r2-x64-glb
 		    mshotfix-win10-win2016-x64-glb
		    mshotfix-win10-x86-glb

		    mshotfix-win10-1507-x64-glb
		    mshotfix-win10-1507-x86-glb
		    mshotfix-win10-1607-x64-glb
		    mshotfix-win10-1607-x86-glb
		    mshotfix-win10-1809-x64-glb
		    mshotfix-win10-1809-x86-glb
		    mshotfix-win10-2009-x86-glb
		    mshotfix-win10-2009-x64-glb
			mshotfix-win2022
			mshotfix-win11-21h2
			mshotfix-win11-22h2
     !-misc/	diverse zusätzliche Pakete
     		dotnetfx
     		dotnetfx-hotfix
     		mshotfix-uninstall
     		ms-optional-fixes
----

Folgende Tabelle soll bei der Auswahl der richtigen Pakete helfen:

.mshotfix Client-Betriebssystem
|=======================
|OS | Arch | Patch-Paket
|Windows 7 | 32Bit | mshotfix-win7-x86-glb
|Windows 7 | 64Bit | mshotfix-win7-win2008r2-x64-glb
|Windows 2012 | 64Bit | mshotfix-win8-win2012-x64-glb
|Windows 8.1 | 32Bit | mshotfix-win81-x86-glb
|Windows 8.1 | 64Bit | mshotfix-win81-win2012r2-x64-glb
|Windows 2008 Server R2 | 64Bit | mshotfix-win7-win2008r2-x64-glb
|Windows 2012 R2 | 64Bit | mshotfix-win81-win2012r2-x64-glb
|Windows 10 | 32Bit | mshotfix-win10-x86-glb			oder das passende modulare Paket
|Windows 10 | 64Bit | mshotfix-win10-win2016-x64-glb 	oder das passende modulare Paket
|Windows 2016 | 64Bit | mshotfix-win10-win2016-x64-glb 	oder mshotfix-win10-1607-x64-glb
|Windows 2019 | 64Bit | mshotfix-win10-win2016-x64-glb 	oder mshotfix-win10-1809-x64-glb
|Windows 10 1507 LTSB | 32/64Bit | mshotfix-win10-1507-x86-glb mshotfix-win10-1507-x64-glb
|Windows 10 1607 LTSB / Windows Server 2016 | 32/64Bit | mshotfix-win10-1607-x86-glb mshotfix-win10-1607-x64-glb
|Windows 10 1809 LTSC / Windows Server 2019 | 32/64Bit | mshotfix-win10-1809-x86-glb mshotfix-win10-1809-x64-glb
|Windows 10 2009/21h2/22h2 | 32/64Bit | mshotfix-win10-2009-x86-glb mshotfix-win10-2009-x64-glb
|Windows Server 2022 | 64Bit | mshotfix-win2022
|Windows 11 21h2 | 64Bit | mshotfix-win11-21h2
|Windows 11 22h2 | 64Bit | mshotfix-win11-22h2
|=======================

Installation:
[source,shell]
----
opsi-package-manager -i mshotfix_201008-1.opsi
----
zum Scharfschalten (überall auf setup stellen, wo das Produkt auf installed steht):
[source,shell]
----
opsi-package-manager -iS mshotfix_201008-1.opsi
----

Zusätzlich zum Basis-Paket werden die Patch-Pakete auf die gleiche Weise installiert. Da diese Pakete aber keine Installationsskripte enthalten, sind sie nur zusammen mit dem Basis-Paket einzuspielen, d.h. man kann diese nicht separat auf setup stellen.
Für die Client-Installation ist komplett das mshotfix-Basispaket zuständig.

Seit Paket mshotfix 201304-1 werden sich durch mshotfix installierte Patches in der Datei `C:\opsi.org\mshotfix\deployed.txt` lokal gemerkt.

Caution:: Seit Paket mshotfix 201808-3 wird zuerst das aktuelle ServingStack installiert mit einem sofortigen Neustart.

noreboot:: noreboot=on: Don't Reboot if possible  Warning will be logged if a reboot is required. Will be ignored for Servicing stacks
values: ["off", "on"]
default: ["off"]

force:: force=on: All Hotfixes will be installed forced
values: ["off", "on"]
default: ["off"]

excludes:: Commaseparated list with kb-numbers or ms-no, that will be excluded (Only Number without beginning kb and no spaces. Example: 123456,789011,976002

severity:: choose the severity that will be installed. Possible Entries are Critical, Important, Moderate, all
values: ["Critical", "Important", "Moderate", "all"]
default: ["Critical", "Important"]

excludelist-superseded.txt:: Use File ExcludeList-superseded.txt
values: ["", "ExcludeList-superseded.txt"]
default: [""]

monthly-updates::  Handle windows-7-and-windows-8-1 : security Only Quality Update vs Monthly Quality Rollup (see link:https://blogs.technet.microsoft.com/windowsitpro/2016/08/15/further-simplifying-servicing-model-for-windows-7-and-windows-8-1/[Further simplifying servicing models for Windows 7 and Windows 8.1], link:https://blogs.technet.microsoft.com/windowsitpro/2016/10/07/more-on-windows-7-and-windows-8-1-servicing-changes/[More on Windows 7 and Windows 8.1 servicing changes], link:https://blogs.msdn.microsoft.com/dotnet/2016/10/11/net-framework-monthly-rollups-explained/[.NET Framework Monthly Rollups Explained])
values: ["all", "monthly_quality_rollup", "security_only_quality_update"]
default: ["security_only_quality_update"]

=== misc mshotfix-uninstall

----
mshotfix-uninstall        201512-1                  MS Hotfix BasePackage
----

Entfernt Patches mittels `wusa /uninstall  ...` die sich mit dieser Methode deinstallieren lassen.

excludes:: Commaseparated list with kb-numbers or ms-no, that will be excluded (Only Number without beginning kb and no spaces. Example: 2553154,ms14-082)

noreboot:: noreboot=on: Don't Reboot.  Warning will be logged if a reboot is required.
values: ["off", "on"]
default: ["off"]

removefromdeployed.txt:: Remove from deployed.txt
default: False

removekb:: Remove KBXXXXX, (Only Number without beginning kb and no spaces f.e. 3097877)
multivalue: True
default: [""]

=== misc dotnetfx

----
dotnetfx                  4.7.2-3                 .NET Framework
----

Paket zur Installation der Dotnet Framework Versionen 4.5 und höher insbesondere auf Windows 7 / 2008 R2 / 8.1 / 2012 R2 / 10
Auf Windows Versionen (neuer Windows 7) kann auch Dotnet 3.5 installiert werden.

version:: The Microsoft .NET Framework 4.8 is a highly compatible, in-place update to the Microsoft .NET Framework 4, 4.5, 4.5.1, 4.5.2, 4.6, 4.6.1, 4.6.2, 4.7 , 4.7.1 and 4.7.2 +
values: ["3.5", "4.0", "4.5", "4.5.1", "4.5.2", "4.6", "4.6.1", "4.6.2", "4.7", "4.7.1", "4.7.2", "latest", "latestAnd3.5"] +
default: ["latest"]

rerundotnethotfix:: rerun dotnetfx-hotfix after installation if possible +
values: ["false", "true"] +
default: ["true"]

install_language_languagepack:: install_language_languagepack
values: ["auto", "de", "en", "fr"]
default: ["auto"]

os-package:: Here you can switch from which OS-Version to be install Dotnet3.5,
auto=win10 or opsi-local-image-win10 (default); other ProductID for netboot-product
values: ["auto", ]
default: ["auto"]

=== misc dotnetfx-hotfix

----
dotnetfx-hotfix           201808-1                  dotnetfx-hotfix
----

Im Update-Abo _MS-Hotfixes_ sind die Hotfixes für _Microsoft .NET_
Framework' nur enthalten, falls es passend zum jeweiligen Betriebssystem
ist.

Also z.B. bei Windows 7 "Microsoft .NET Framework 3.5.1"

( Allerdings gibt es seit Oktober 2016 unter Umständen auch "Monthly Rollups"
für DotnetFramework, die im mshotfix-Paket enthalten sind.)

Das Paket dotnetfx-hotfix
beinhaltet die Hotfixes von Microsoft für

- Microsoft .NET Framework 4 und höher für Windows 7

Das Paket dotnetfx-hotfix patcht zur Zeit - so vorhanden - die Versionen
4.x auf den jeweils letzten Stand der Reihe.

Bitte beachten Sie:
"Support for .NET Framework 4, 4.5, and 4.5.1 ended on January 12, 2016"
(https://support.microsoft.com/en-us/lifecycle?p1=14380)

bzw.
https://support.microsoft.com/en-us/gp/framework_faq/de

noreboot:: noreboot=on: Don't Reboot.  Warning will be logged if a reboot is required.
values: ["off", "on"]
default: ["off"]

force:: force=on: All Hotfixes will be installed forced
values: ["off", "on"]
default: ["off"]

severity:: choose the severity that will be installed.Possible Entries:Critical, Important, Moderate, all
values: ["Critical", "Important", "Moderate", "all"]
default: ["all"]

=== misc ms-optional-fixes

----
ms-optional-fixes         201808-1                  MS optional fixes
----

Gedacht als Ergänzung zu mshotfix und basiert auf mshotfix.

Enthält:

kb2999226 für win7-win8.1

message_language:: Language for messages while installing
values: ["auto", "de", "en", "fr"]
default: ["auto"]

noreboot:: noreboot=on: Don't Reboot if possible  Warning will be logged if a reboot is required. Will be ignored for Servicing stacks
values: ["off", "on"]
default: ["off"]

excludes:: Commaseparated list with kb-numbers or ms-no, that will be excluded (Only Number without beginning kb and no spaces. Example: 123456,789011,2222)

rerunmshotfix:: rerun mshotfix after installation
values: ["false", "true"]
default: ["true"]

client_language::
values: ["auto", "de", "en", "fr"]
default: ["auto"]

[[opsi-manual-abo-products-ms-Officehotfixes]]

== Update-Abo 'MS-Office Hotfixes'
Regelmäßige Updates für MS-Office 2013/2016 32 Bit/64 Bit.

Das Update erscheint jeweils innerhalb von 3 Arbeitstagen nach dem Erscheinen eines von Microsoft als wichtig oder kritisch eingeschätzten Patches.

.Office hotfix  Voraussetzung
|===================================
|Office Version| required
|Office 2013 |Servicepack 1
|Office 2016 |
|===================================


[[opsi-manual-abo-products-office_2010_hotfix]]

=== Updates für MS Office 2013 32-bit international: office_2013_hotfix
----
office_2013_hotfix               201808-1                  Microsoft Office 2013 Hotfixes
----

Enthält sprachunabhängige monatliche Office 2013 Hotfixes (inclusive Visio 2013). Setzt Servicepack 1 voraus.

Wird getestet gegen Office 2013 Professional

Durch office_2013_hotfix installierte Patches in der Datei `C:\opsi.org\mshotfix\office_2013_hotfix_deployed.txt` lokal gemerkt.

Seit office_2013_hotfix 201503-1:

excludes:: Commaseparated list with kb-numbers or ms-no, that will be excluded (Only Number without beginning kb and no spaces. Example: 2553154,ms14-082)

[[opsi-manual-abo-products-office_2016_hotfix]]

=== Updates für MS Office 2016 32-bit international: office_2016_hotfix

----
office_2016_hotfix               201808-1                  Microsoft Office 2016 Hotfixes
----

Enthält sprachunabhängige monatliche Office 2016 Hotfixes (inclusive Visio 2016).

Wird getestet gegen Office 2016 Professional

Durch office_2016_hotfix installierte Patches in der Datei `C:\opsi.org\mshotfix\office_2016_hotfix_deployed.txt` lokal gemerkt.

excludes:: Commaseparated list with kb-numbers or ms-no, that will be excluded (Only Number without beginning kb and no spaces. Example: 2553154,ms14-082)

CAUTION:: Falls Sie Updates für MS Office 2016 32-bit und 64-Bit oder aber nur 64-Bit einsetzen wollen:

Passen Sie das repo uib_abo_msoffice update an: x3264 / x64

[[opsi-manual-abo-products-standard]]
== Update-Abo 'opsi Standardprodukte'
Regelmäßige Updates der Produkte:

    Adobe Reader DC Classic / Continuous (international, 32 Bit)
    Apache OpenOffice.org (deutsch, 32 Bit)
    Google Chromium for business (international, 32 Bit / 64 Bit)
    LibreOffice (international, 32 Bit / 64 Bit)
    Mozilla Firefox (deutsch, englisch, französisch und niederländisch, 32 Bit) bzw. 32/64-Bit Pakete seit 201706
    Mozilla Thunderbird (deutsch, englisch und französisch, 32 Bit / 64 Bit)
    Java VM (javavm) basierend auf Open JDK LTS 11 (international, 64 Bit)
    Java VM 8 (javavm8) basierend auf Open JDK LTS 8 (international, 32 Bit / 64 Bit)
    Java VM (javavm-oracle-jdk) OpenJDK basierend auf der aktuellen open jdk implementation (international, 64 Bit)

Je nach Vertrag stellen wir noch folgende Sprachen im Abo zur Verfügung:

    Mozilla Firefox (zusätzlich dänisch, italienisch, spanisch, tschechisch und norwegisch / 32 Bit / 64 Bit)
    Mozilla Thunderbird (zusätzlich italienisch / 32 Bit / 64 Bit)

weitere Sprachen auf Anfrage.

Das Update erscheint jeweils innerhalb von 2 Arbeitswochen nach dem Erscheinen eines Updates dieser Produkte; bei vom Hersteller als kritisch eingestuften Security-Updates innerhalb von 1 Arbeitswoche.

=== Customizing der Pakete durch zentrale Konfigurationen

Für die Pakete
----
adobe.reader.dc.classic
adobe.reader.dc.continuous
firefox
thunderbird
----

gibt es die Möglichkeit eigene Konfigurationen zu erstellen und im Verzeichnis `custom` zu hinterlegen,
die über Properties auswählbar sind. (Näheres siehe unten)

=== Customizing der Pakete durch preinst/postinst-scripts

Für die Pakete
----
adobe.reader.dc.classic
firefox		(ab 17.0.6esrorstandard-1)
google-chrome-for-business
javavm		(ab javavm_1.7.0.51-5 )
javavm8
javavm-oracle-jdk
libreoffice	(ab libreoffice_4.3.5or4.4.0-2)
ooffice		(ab ooffice_4.1.1-2)
thunderbird	(ab 17.0.6esrorstandard-1)
----

besteht die Möglichkeit, eigene custom-Scripte einzubauen im Verzeichnis `custom\scripts`.

Einfache Templates für die unterstützen Scripte finden sich im Verzeichnis `opsi\scripts`.

[source,configfile]
----

custom.actions.post.setup
custom.actions.post.uninstall
custom.actions.pre.setup
custom.actions.pre.uninstall
custom.declarations
custom.sections

custom scripts will be included in
- setup-script
- uninstall-script

custom pre-scripts will be included in
- setup-script
- uninstall-script

custom post-scripts will be included in
- in setup-script
- uninstall-script

custom.declarations
; intended for declaration of custom Variables and Stringlist Variables
; will be included with "include_insert" at top of [actions]
; but after GetProductProperties

custom.sections
; intended for declaration of custom secondary sections
; will be included with "include_append" at top of [actions]
; but after GetProductProperties

custom.actions.pre.setup  (or custom.actions.pre.uninstall)
; will be included with "include_insert" at at top of [actions]
; (but after GetProductProperties)

custom.actions.post.setup (or custom.actions.post.uninstall)
; will be included with "include_insert" in case of successful installation before "endof_"actions"
; in setup-script ( or uninstall-script)

----

=== Adobe Acrobat Document Cloud Classic : adobe.reader.dc.classic
----
adobe.reader.dc.classic		20202000530418-1		Adobe Acrobat Reader DC classic
----

Das adobe.reader.dc.classic-Paket beinhaltet Adobe Acrobat Document Cloud Classic (MUI-Version)

Adaptation in the transform file *.mst
[source,shell]
----
cat transform.txt
Changes vs default the transform file *.mst

Personalisation Options
Suppress Eula

Installation Options
acivated - Make Reader the default PDF viewer
IF REBOOT REQUIRED - suppress reboot

Shortcuts
deactivated - Destination Computer/Desktop/Adobe Reader XI (Icon)

Online and Acrobat.com Features
Online Features
activated - Disable product updates
Enable & Ask before Installing - Load trusted root certificates from Adobe

Online Services and Features
disable product updates
Load trusted root certificates from Adobe disable
DISABLE all Services
----

adobereader.mst::
Das Adobe Reader Paket von uib verwendet eine Standard-transform-Datei die mit dem Adobe Customization Wizard erstellt ist.
Abweichend davon können im Share `opsi_depot` im Verzeichnis `/var/lib/opsi/depot/adobe.reader.dc.classic/custom` eigene MST-Dateien abgelegt werden, die über dieses
Property ausgewählt werden können (nach erneutem Einspielen des Pakets mittels `opsi-package-manager -i <adobe-paket>`).

Beim Einspielen des adobe.reader.dc.classic-Pakets auf dem opsi-Server wird das Verzeichnis custom ueber ein preinst/postinst-Script gesichert.

WARNING: Bei Einsatz des Wan/VPN Moduls muss nach Änderungen im Verzeichnis `custom` das Paket neu eingespielt werden, damit die Datei `<productid>.files` neu erzeugt wird.

client_language::
Das adobe.reader.dc.classic-Paket als MUI
Ist der Wert auf "auto" gesetzt, so wird anhand der Systemsprache automatisch die Sprache erkannt. values: ["auto", "de", "en", "fr" ]  default: ["auto"]

classicversion::
siehe https://helpx.adobe.com/acrobat/release-note/release-notes-acrobat-reader.html Classic Track (2015 Release) or (2017 Release)
values: ["2020"]
default: ["2020"]

disableadobeacrobatupdateservice::
Disable Adobe Acrobat Update Service and remove Adobe Acrobat Update Task
values: ["false", "true"]
default: ["false"]

removebeforesetup::
remove target version of adobe reader before install
values: ["false", "true"]
default: ["false"]

noreboot::
description: noreboot=true: Don't Reboot.  Warning will be logged if a reboot is required.
values: ["false", "true"]
default: ["false"]


=== Adobe Acrobat Document Cloud Continuous : adobe.reader.dc.continuous
----
adobe.reader.dc.continuous	201901020099-1							Adobe Acrobat Reader DC Continuous
----

Das adobe.reader.dc.continuous-Paket beinhaltet Adobe Acrobat Document Cloud Continuous (MUI-Version)

Adaptation in the transform file *.mst
[source,shell]
----
cat transform.txt
Changes vs default the transform file *.mst

Personalisation Options
Suppress Eula

Installation Options
acivated - Make Reader the default PDF viewer
IF REBOOT REQUIRED - suppress reboot

Shortcuts
deactivated - Destination Computer/Desktop/Adobe Reader (Icon)

Online and Acrobat.com Features
Online Features
activated - Disable product updates
Enable & Ask before Installing - Load trusted root certificates from Adobe

Online Services and Features
disable product updates
Load trusted root certificates from Adobe disable
DISABLE all Services
----

adobereader.mst::
Das Adobe Reader Paket von uib verwendet eine Standard-transform-Datei die mit dem Adobe Customization Wizard erstellt ist.
Abweichend davon können im Share `opsi_depot` im Verzeichnis `/var/lib/opsi/depot/adobe.reader.dc.continuous/custom` eigene MST-Dateien abgelegt werden, die über diese
Property ausgewählt werden können (nach erneutem Einspielen des Pakets mittels  `opsi-package-manager -i <adobe-paket>`)

Beim Einspielen des adobe.reader.dc.continuous-Pakets auf dem opsi-Server wird das Verzeichnis custom ueber ein preinst/postinst-Script gesichert.

WARNING: Bei Einsatz des Wan/VPN Moduls muss nach Änderungen im Verzeichnis `custom` das Paket neu eingespielt werden, damit die Datei `<productid>.files` neu erzeugt wird.

client_language::
Das adobe.reader.dc.continuous-Paket als MUI
Ist der Wert auf "auto" gesetzt, so wird anhand der Systemsprache automatisch die Sprache erkannt. values: ["auto", "de", "en", "fr" ]  default: ["auto"]

disableadobeacrobatupdateservice::
Disable Adobe Acrobat Update Service and remove Adobe Acrobat Update Task
values: ["false", "true"]
default: ["false"]

removebeforesetup::
remove target version of adobe reader before install
values: ["false", "true"]
default: ["false"]

noreboot::
description: noreboot=true: Don't Reboot.  Warning will be logged if a reboot is required.
values: ["false", "true"]
default: ["false"]

[[opsi-manual-abo-products-standard-google-chrome]]
=== Google Chromium for Business
----
google-chrome-for-business	108.0.5359.125-1
----

Das Paket beinhaltet den msi-Installer von Google (Häufig gestellte Fragen Chrome for Business https://support.google.com/a/answer/188447).

Bemerkungen:

Die Deinstallation und Installation des google-chrome.msi schlägt manchmal fehl.

Daher gibt es verschiedene Ansätze im opsi-Paket, um die
Zuverlässigkeit der Installation zu erhöhen.

Ein Kunde berichtete von einer Erfolsquote von 100% bei 40 Installationen mit folgender Einstellung der Properties:

* `install_architecture`: 32
* `reboot_on_retry`: True
* `reboot_after_uninstall`: True
* `timeout`: 240

Intern verwenden wir für Tests:
* `install_architecture`: system specific
* `reboot_on_retry`: True
* `reboot_after_uninstall`: True
* `timeout`: notimeout


autoupdate:: !Property wirkt nicht mehr!
vgl. https://support.google.com/chrome/a/answer/187207

gibt es 0,1,2,3 als Wert für
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Update\UpdateDefault

bzw ADM falls Gruppenrichtlinien verwendet werden

ADM= use Policy based on Googles Template,
0=UpdatesDisabled,
1=UpdatesEnabled,
2=ManualUpdatesOnly,
3=AutomaticUpdatesOnly,
values: ["0", "1", "2", "3", "ADM"]
default: ["0"]

disablescheduledtaskgoogleupdatemachine::
Disable scheduled task GoogleUpdateTaskMachineCore and GoogleUpdateTaskMachineUA
values: ["false", "true"]
default: ["true"]

removeupdatehelper::
default: ["true"]

install_architecture::
description: which architecture (32/64 bit) has to be installed
values: ["32", "64", "system specific"]
default: ["system specific"]

reboot_on_retry::
description: If installation fails and (timeout > 0) then reboot before retry
default: False

reboot_after_uninstall::
description: reboot after uninstall old version
default: False

timeout::
description: TimeOutSeconds msi installs
values: ["240", "300", "600", "notimeout"]
default: ["notimeout"]

[[opsi-manual-abo-products-standard-openoffice]]
=== Apache OpenOffice : ooffice4
----
ooffice						4.1.13-1									Apache OpenOffice
----

Das ooffice-Paket beinhaltet Apache OpenOffice in deutsch.

handle_excel_xls::
Soll OpenOffice.org für MS-Excel-Dokumente registriert werden
 on  = OpenOffice.org wird für MS-Exceldokumente registriert
 off = OpenOffice.org wird nicht für MS-Exceldokumente registriert

handle_powerpoint_ppt ::
Soll OpenOffice.org für MS-PowerPoint-Dokumente registriert werden
 on  = OpenOffice.org wird für MS-PowerPointdokumente registriert
 off = OpenOffice.org wird nicht für MS-PowerPointdokumente registriert

handle_word_doc ::
Soll OpenOffice.org für MS-Word-Dokumente registriert werden
 on  = OpenOffice.org wird für MS-Worddokumente registriert
 off = OpenOffice.org wird nicht für MS-Worddokumente registriert

[[opsi-manual-abo-products-standard-libreoffice]]
=== LibreOffice The Document Foundation  : libreoffice
----
libreoffice					7.3.7or7.4.3-1							LibreOffice
----

Das libreoffice-Paket beinhaltet LibreOffice international.

client_language ::
client_language - only for messages important, cause libre office is international
values: ["auto", "de", "en", "fr"]

msoregister :: Open Microsoft Office documents with LibreOffice (true)
values: ["false", "true"]
default: ["false"]

libreoffice-version::
description: 'Stable' - is an Extended Support Release from LibreOffice for the conservative user - default version (7.3.7); 'Experimentell' is a version for the experimentell user from LibreOffice (7.4.3)
values: ["experimentell", "stable"]
default: ["stable"]

hide_component::
description: Hide component base by removing desktoplink and exe file
values: ["base", "none"]
default: ["none"]

ui_languages::
description: which UI languages should be installed (comma separated), For example UI_LANGS=en_US,de,fr,hu will install English (US), German, French, and Hungarian.
default: ["auto"]

install_architecture:: which architecture (32/64 bit) has to be installed
values: ["32", "64", "system specific"]
default: ["32"]


[[opsi-manual-abo-products-standard-firefox]]
=== Mozilla Firefox : firefox
----
firefox						102.6.0esror108.0-2
----
Das firefox-Paket beinhaltet Mozilla Firefox in den Sprachen deutsch, englisch, französisch und niederländisch.

Es werden alle von Mozilla unterstützten Versionen bereitgestellt.

Firefox kann zentral konfiguriert werden
a) entweder über eine zentrale Konfigurationsdatei `mozilla.cfg` (vgl. http://kb.mozillazine.org/Locking_preferences)
b) oder über eine `policies.json` (vgl. https://github.com/mozilla/policy-templates/blob/master/README.md)

die in folgendem Verzeichnis abzulegen ist:

[source,shell]
----
/var/lib/opsi/depot/firefox/custom/
----

Bei erneutem Einspielen des Pakets mittels  `opsi-package-manager -i <firefox-paket>` werden die gefundenen Konfigurationsdateien über preinst-/postinst-Mechanismus erhalten und dann über das Property "mozillacfg" auswählbar.

- Beispiel:
+
[source,shell]
----
cat /var/lib/opsi/depot/firefox/custom/mozilla.cfg
//
lockPref("browser.startup.homepage", "http://www.uib.de");
lockPref("network.proxy.type", 1);
lockPref("network.proxy.http", "router.uib.local");
lockPref("network.proxy.http_port", 3128);
----

Alternativ zu einer mozilla.cfg kann man auch eine mit dem CCK2 erstellte autoconfig.zip über das Property "mozillacfg" einbinden.

WARNING: Bei Einsatz des Wan/VPN Moduls muss nach Änderungen im Verzeichnis `custom` das Paket neu eingespielt werden, damit die Datei `<productid>.files` neu erzeugt wird.


client_language::
values: ["auto", "de", "en", "fr", "nl"]
default: ["auto"]

firefox-version :: Firefox 'esr' - Extended Support Release from Mozilla.org, standard ist die aktuelle Firefox-Version
values: ["esr", "standard"]
default: ["esr"]

commandlineoptions::
started Firefox mit den angegebenen Optionen. vgl.: https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options
values: ["", "-no-remote -Profile H:\\ProfileDir"]
default: [""]

pref_file::
in welcher Datei sollen die Einstellungen gemacht werden, user.js oder prefs.js.
values: ["prefs", "user"]
default: ["prefs"]

noautoupdate:: (on/off): auto update ausschalten. default=on

setproxy:: (off/direct/manual/file) proxy einstellungen verändern
* off= tue nichts
* direct = direkte Verbindung zum Internet
* manual = Proxyeinstellungen über property proxysetting
(<ip-numme>:<port>) und property noproxy_hosts (host1,host2)
* file = Proxyeinstellungen über property proxysetting
(<path_to_proxyconf.pac>) und property noproxy_hosts (host1,host2)
* system
* default=off

proxysetting:: string für proxy Einstellung (siehe: setproxy)

noproxy_hosts:: Komma separierte Liste von hosts

mozillacfg::
description: filename for mozilla.cfg in `%scriptpath%\custom`-directory, http://kb.mozillazine.org/Locking_preferences

profilemigrator:: enable or disable Profilemigrator on first run
values: ["off", "on"]
default: ["off"]

* *Bekannte Probleme* +
- Beim Einspielen "On Demand" kann die Installation aufgrund geöffneter Programme fehlschlagen!

[[opsi-manual-abo-products-standard-thunderbird]]
=== Mozilla Thunderbird : thunderbird
----
thunderbird					102.6.0-1
----
Das thunderbird-Paket beinhaltet Mozilla Thunderbird in den Sprachen deutsch, englisch und französisch.

Es werden alle von Mozilla unterstützten Versionen bereitgestellt.

Analog dem Firefox-Paket kann zentrale Konfigurationsdatei bereitgestellt werden.

client_language::
values: ["auto", "de", "en", "fr"]
default: ["auto"]

thunderbird-version::
values: ["60.x"]
default: ["60.x"]

commandlineoptions::
starte thunderbird mit den angegebenen Parametern, vgl.:  https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options
values: ["", "-no-remote -Profile H:\\ProfileDir"]
default: [""]

addonsactivation::
description: Enable/Disable AddOns (default = enable)
values: ["off", "on"]
default: ["on"]

https://developer.mozilla.org/en/Addons/Add-on_Manager/AddonManager

http://mike.kaply.com/2012/02/09/integrating-add-ons-into-firefox/

https://developer.mozilla.org/en/Thunderbird/Deploying_Thunderbird_in_the_Enterprise/Thunderbird_Preferences_Relevant_to_Enterprises
[source,shell]
----
Set_Netscape_User_Pref ("extensions.autoDisableScopes", 11)
Set_Netscape_User_Pref ("extensions.shownSelectionUI", true)
----

enigmail::
description: Install GnuPG-Plugin
values: ["off", "on"]
default: ["off"]

noautoupdate::
description: disable automatic updates
values: ["off", "on"]
default: ["on"]

mozillacfg::
description: filename for mozilla.cfg in `%scriptpath%\custom`-directory, http://kb.mozillazine.org/Locking_preferences

lightning::
description: Install calender plugin lightning
values: ["off", "on"]
default: ["off"]

* *Bekannte Probleme* +
- Beim Einspielen "On Demand" kann die Installation aufgrund geöffneter Thunderbird fehlschlagen!

[[opsi-manual-abo-products-standard-javavm]]
=== OpenJDK 11 LTS : javavm
----
javavm						11.0.17-1								JDK 11
----
Das javavm Paket enthält die Open JDK 11 LTS Implementationen von SAP (SapMachine) und Amazon (Amazon Corretto), da Oracle keine frei verfügbare JAVA-Runtime mehr zur Verfügung stellt (seit Anfang Januar 2019).

(Oracle announced "End Of Public Updates Februar 2019"  http://www.oracle.com/technetwork/java/eol-135779.html)


install_architecture::
description: which architecture (32/64 bit) has to be installed
values: ["64 only"]
default: ["64 only"]

javaversion::
which version has to be installed jdk Sapmachine or amazon corretto
values: ["jdkamazoncorretto", "jdksap"]
default: ["jdksap"]

keepversion::
description: Don't uninstall jre version
values: ["1.6.0_0", "1.6.0_1", "1.6.0_2", "1.6.0_3", "1.6.0_4", "1.6.0_5", "1.6.0_6", "1.6.0_7", "none"]
default: ["none"]

uninstalljava16::
description: Uninstall Java 1.6 "Patch in Place" Installations
default: True

uninstalljava17::
description: Uninstall Java 1.7 "Patch in Place" Installations
default: True

environment_set_java_home:: Set the environment variable JAVA_HOME
default: False


[[opsi-manual-abo-products-standard-javavm8]]
=== OpenJDK 8 LTS : javavm8
----
javavm8						1.8.0.352-1					JDK 8 LTS
----
Das javam8 Paket enthält die Open JDK 8 LTS Implementationen von Amazon (Amazon Corretto)

javaversion::
which version has to be installed amazon 352
values: ["jdkamazoncorretto"]
default: ["jdkamazoncorretto"]

install_architecture::
which architecture (32/64 bit) has to be installed
values: ["32 only", "64 only", "both", "system specific"]
default: ["system specific"]

keepversion::
description: Don't uninstall jre version
values: ["1.6.0_0", "1.6.0_1", "1.6.0_2", "1.6.0_3", "1.6.0_4", "1.6.0_5", "1.6.0_6", "1.6.0_7", "none"]
default: ["none"]

uninstalljava16::
description: Uninstall Java 1.6 "Patch in Place" Installations
default: True

uninstalljava17::
description: Uninstall Java 1.7 "Patch in Place" Installations
default: True

environment_set_java_home:: Set the environment variable JAVA_HOME
default: False

[[opsi-manual-abo-products-standard-javavm-oracle-jdk]]
=== OpenJDK : javavm-oracle-jdk
----
javavm-oracle-jdk			19.0.1-2								Open JDK
----
Das javavm-oracle-jdk Paket enthält die aktuelle Open JDK Implementation von Oracle http://jdk.java.net/

install_architecture::
description: which architecture (32/64 bit) has to be installed
values: ["64 only"]
default: ["64 only"]

keepversion::
description: Don't uninstall jre version
values: ["1.6.0_0", "1.6.0_1", "1.6.0_2", "1.6.0_3", "1.6.0_4", "1.6.0_5", "1.6.0_6", "1.6.0_7", "none"]
default: ["none"]

uninstalljava16::
description: Uninstall Java 1.6 "Patch in Place" Installations
default: True

uninstalljava17::
description: Uninstall Java 1.7 "Patch in Place" Installations
default: True

environment_set_java_home:: Set the environment variable JAVA_HOME
default: False

