////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      31.03.2011
:Revision:  4.0.1
:toclevels: 6


ifeval::["{mode}" == "antora"]
include::common:partial$opsi_terms.adoc[]
endif::[]

[[opsi-manual-localboot-products]]
= Localboot-Produkte: Automatische Softwareverteilung mit opsi

Als Localboot-Produkte werden alle Produkte bezeichnet, die nach einem lokalen
Boot des Rechners über den _opsi-client-agent_ installiert werden. Dies im Gegensatz
zu den weiter unten beschriebenen Netboot Produkten xref:netboot-products.adoc#opsi-manual-netboot-products[Netboot Produkte].


[[opsi-manual-localboot-standardprodukte]]
== opsi Standardprodukte

Die folgenden Localboot Produkte gehören zur Grundausstattung von opsi.

[[opsi-manual-localboot-opsi-client-agent]]
=== _opsi-client-agent_

Der _opsi-client-agent_ ist der Clientagent von opsi und weiter oben ausführlich
beschrieben: siehe Kapitel xref:clients:client-agent/opsi-client-agent.adoc#opsi-manual-clientagent[opsi-client-agent].

[[opsi-manual-localboot-opsi-script]]
=== _opsi-script_

Das Produkt _opsi-script_ ist ein Spezialfall. Es enthält den aktuellen _opsi-script_.
Dieser muss zur Aktualisierung nicht auf setup gestellt werden. Vielmehr prüft
ein Teil des _opsi-client-agent_ bei jedem Start, ob auf dem Server eine andere
Version des _opsi-script_ verfügbar ist und holt sich diese im Zweifelsfall.

[[opsi-manual-localboot-javavm]]
=== javavm: Java Runtime Environment

Das Produkt javavm stellt die für den _opsi-configed_ benötigte Java
Laufzeitumgebung für die Clients zur Verfügung.

[[opsi-manual-localboot-opsi-configed]]
=== opsi-configed

opsi Graphical Management Interface als Applikation
Für Windows und Linux.
Siehe auch Kapitel: xref:configed:configed.adoc[opsi-Management GUI: opsi-configed]

[[opsi-manual-localboot-jedit]]
=== jedit

Java basierter Editor mit Syntax Highlighting für _opsi-script_ Scripte.

[[opsi-manual-localboot-swaudit_hwaudit]]
=== swaudit + hwaudit: Produkte zur Hard- und Software-Inventarisierung

Die Produkte hwaudit und swaudit dienen der Hard- bzw. Software-Inventarisierung.
Bei der Hardware-Inventarisierung werden die Daten über WMI erhoben und über den
_opsi-Webservice_ an den Server zurück gemeldet.
Bei der Software-Inventarisierung werden die Daten aus der Registry
(HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall)
erhoben und über den _opsi-Webservice_ an den Server zurück gemeldet.

[[opsi-manual-localboot-opsi-template]]
=== opsi-template

Template zur Erstellung eigener opsi-Scripts.
Sie können das Template extrahieren mit
[source, shell]
----
opsi-package-manager -x opsi-template_<version>.opsi
----
oder auch dabei gleich umbenennen mit
[source, shell]
----
opsi-package-manager -x opsi-template_<version>.opsi --new-product-id myprod
----

Siehe auch opsi-getting-started Manual.

[[opsi-manual-localboot-opsi-template-with-admin]]
=== opsi-template-with-admin

Template zur Erstellung eigener opsi-Scripts.
Sie können das Template extrahieren mit
[source, shell]
----
opsi-package-manager -x opsi-template_<version>.opsi
----
oder auch dabei gleich umbenennen mit
[source, shell]
----
opsi-package-manager -x opsi-template_<version>.opsi --new-product-id myprod
----

Siehe auch opsi-script-manual +
Kapitel: 'Skript für Installationen im Kontext eines lokalen Administrators'

[[opsi-manual-localboot-shutdownwanted]]
=== shutdownwanted

Fährt den Rechner herunter, wenn keine weiteren Aktionen mehr gesetzt sind.

[[opsi-manual-localboot-opsi-script-test]]
=== opsi-script-test

Große Sammlung von opsi-script Selbsttests. Diese kann als Beispielsammlung für
funktionierende Aufrufe von opsi-script Befehlen verwendet werden.


[[opsi-manual-localboot-opsi-wim-capture]]
=== opsi-wim-capture

Siehe auch Kapitel: xref:opsi-modules:wim-capture.adoc#opsi-manual-wimcap[opsi WIM Capture]

[[opsi-manual-localboot-opsi-winpe]]
=== opsi-winpe

Produkt zur einfachen Erzeugung eine opsi-winpe
Siehe auch opsi-getting-started Manual, Kapitel 'Erstellen eines PE'.

[[opsi-manual-localboot-opsi-uefi-netboot]]
=== opsi-uefi-netboot

Siehe auch Kapitel: xref:opsi-modules:uefi.adoc#opsi-manual-uefi[opsi mit UEFI / GPT]


[[opsi-manual-localboot-opsi-set-win-uac]]
=== opsi-set-win-uac

Setzt den UAC-Level via opsi.

[[opsi-manual-localboot-opsi-setup-detector]]
=== opsi-setup-detector

Siehe auch Kapitel: xref:opsi-modules:setup-detector.adoc#opsi-setup-detector[opsi Setup Detector]

[[opsi-manual-localboot-opsi-logviewer]]
=== opsi-logviewer

Text viewer mit Filter nach Loglevel und Events. +
Für Windows und Linux.

* Das von uib erstellte Tool opsi-logviewer öffnet jetzt auch Dateien,
die u.a. in den Archivformaten zip oder gzip komprimiert wurden.
Damit können dann Logdateien, die platzsparend als Archiv zugeschickt werden,
direkt betrachtet werden. (Enthält ein Archiv mehrere Dateien, werden die Inhalte aneinandergehängt.)

* Das Setup.Skript ist um eine Linux-Unterstützung erweitert,
so dass der opsi-logviewer auch auf einem Linux-Client automatisiert installiert werden kann.

* Die neue before-Abhängigkeit zu javavm sichert die Funktion des Startaufrufs (weil javavm die javaw.exe ins Systemverzeichnis kopiert)




[[opsi-manual-localboot-config-win10]]
=== config-win10

Konfiguriert verschiedene Windows 10 Einstellungen wie z.B.
Sperrbildschirm, Hibernationboot, Telemetrie und Update-Verhalten.

In der Version 4.0.7 kamen neue Deaktivierungsmöglichkeiten hinzu.

* *allow_useractivity_publishing* Erlaubt es Benutzeraktivitäten an Microsoft zu senden.

* *change_power_plan* Energieeinstellungen ändern.

* *config-updates* erlaubt es die Quelle der Updates zu ändern. Die Updates werden dann entweder direkt von Microsoft Servern, einem lokalen Peer-To-Peer Netz oder einem Peer-To-Peer Netz aus dem Internet geladen. Die Option 'disable' ist derweil über ein eigenes Property namens 'disable_updates' ermöglicht.

* *defer_upgrade* verschiebt Updates und Upgrades. Updates können um vier Wochen und Upgrades um acht Monate verschoben werden. Hierbei ist zu beachten, dass sicherheitsrelevante Updates trotz 'defer' Option installiert werden. Featureupdates hingegen werden nicht installiert.

* *deferfeatureupdatesperiodindays* Gibt an wie viele Tage Feature Updates, also Windows System Updates, zurückgehalten werden sollen. Der Maximalwert liegt bei 365 Tagen.

* *deferqualityupdatesperiodindays* Gibt an wie viele Tage Quality Updates, also gewöhnliche Windows Updates, zurückgehalten werden sollen. Der Maximalwert liegt bei 29 Tagen.

* *disable_advertising_id* deaktiviert die sogenannte Advertising ID. Diese speichert Daten über den Browserverlauf um benutzerspezifische Werbung einzublenden.

* *disable_app_suggestion_in_startmenu* deaktiviert vorgeschlagene Apps im Startmenü.

* *disable_automatic_logon_on_reboot*: Deaktiviert einen atuomatischen Winlogon bei automatischem Neustart, sofern es 'true' gesetzt ist.

* *disable_cortana* deaktiviert den Cortana Sprachassistenten. Dieser sammelt diverse Daten über Eingaben und überträgt diese Daten an Server von Microsoft.

* *disable_customer_experience* deaktiviert das Sammeln von Daten im Bezug auf Daten zur Anwendungsverwendung.

* *disable_defender* deaktiviert den mit Windows 10 mitgelieferten Antivirenschutz namens 'Defender'.

* *disable_dosvc* deaktiviert den Dienst für die Übermittlungsoptimierung von Telemtriedaten.

* *disable_error_report* deaktiviert die Übermittlung von Fehlern an Microsoft. Dies betrifft die Fehlerdaten von Drittanbieterapplikationen.

* *disable_fast_boot* deaktiviert den Schnellstart und sorgt damit dafür, dass das Standard opsi-event gui_startup sauber funktioniert.

* *disable_font_streaming* sorgt dafür, dass nicht auf dem System installierte Fonts über das Internet nachgeladen werden.

* *disable_handwriting_share* Eine Besonderheit ist die Verwendung von Windows 10 auf Tablet-PCs. Hierbei werden Daten über Handschriften gesammelt und an einen Microsoft Server gesendet.

* *disable_location_sensors* deaktiviert das Sammeln von Daten über die aktuelle Geoposition des Geräts.

* *disable_lock_screen* Sperrbildschirm deaktivieren.

* *disable_mrt* deaktiviert die Verwendung des 'Malware Removal Tool', kurz MRT. Dieser Dienst scannt in regelmäßigen Abständen vorhandene Dateien auf der Festplatte des Rechners und vergleicht diese mit einer Liste von potenziell gefährlicher Software.

* *disable_news_and_interest* deaktiviert die Nachrichten und Interessen Einblendungen in der Taskleiste.

* *disable_onedrive_sync* deaktiviert die OneDrive Dateisynchronisation.

* *disable_push_install* deaktiviert die Möglichkeit Apps aus dem Microsoft Store auf diesem Gerät per push Installation zu installieren.

* *disable_recent_apps* deaktiviert die Anzeige der zuletzt verwendeten Apps im Startmenü.

* *disable_sending_feedback* ermöglicht es die Übertragung von Daten an Microsoft bei Fehlverhalten von Anwendungen zu beeinflussen.

* *disable_smbv1* deaktiviere Protokoll smbv1.

* *disable_suggested_silent_app_installion* deaktiviert die stille Installation von vorgeschlagenen Apps und Spielen im Hintergrund ohne Benutzerinteraktion.

* Mit *disable_telemetry* ist es möglich die Menge der gesammelten Daten zu limitieren. Standardmäßig werden sehr viele Daten übertragen. Wenn das Property auf 'true' gesetzt wird, wird Windows so eingestellt, das nur noch sicherheitsrelevante Daten übertragen werden. Dies ist die niedrigste Stufe. Diese Security Stufe kann nur in der Windows 10 Enterprise und LTSB Version eingestellt werden. In den anderen Versionen von Windows 10 wird die nächst niedrige Stufe angewendet, Basic.

* *disable_update_button* kann den Update Knopf in den Updateeinstellungen ausgrauen und somit unbenutzbar machen. Es kann mitunter Stunden dauern bis der Knopf wieder benutzbar wird, falls die Option von true auf false gestellt wird.

* *disable_update_service* deaktiviert den Windows Update Dienst und bietet somit eine weitere Möglichkeit Updates zu verhindern.

* *disable_updates* kappt bei der Option 'true' die Verbindung zu Update Informationsquellen. Somit werden keine Updates gefunden per Updater. 'false' ermöglicht die Verbindung zu Updatequellen.

* *disable_wifi_sense* ermöglich es den 'Wifi Sense' genannten Dienst zu deaktivieren. Dieser Dienst ermöglicht es, gespeicherte WLAN Konfigurationen mit Kontakten zu teilen. +

* *flashplayer_autorun* Es gibt in Verbindung von Windows 10 mit dem Adobe Flashplayer eine Sicherheitslücke. Es wird empfohlen das Autorun-Feature des Flashplayers zu deaktivieren. Mit 'false' wird der Flashplayer nicht mehr gestartet

* *hide_known_file_extensions* deaktiviert die Darstellung von üblichen Dateiendungen, wie .txt.

* *local_wsus_available* (Dieses Property greift nur wenn disable_updates auf 'true' gesetzt ist.) Falls 'true' gesetzt, ermöglicht es die Verbindung zu einem localen WSUS Server. Betrifft nur Windows Updates.

* *minimize_recommendations* deaktiviert die verwendung von gespeicherten Daten um Vorschläge auf dem Lockscreen einzublenden.

* *no_new_app_install_notification* Ermöglicht es, eine Benachrichtigung für neue Apps zu deaktivieren. Zum Deaktivieren der Benachrichtigung muss das Property den Wert 'true' haben.

* *online_search* Bei jeder Suche über die integrierte Suchleiste in der Taskleiste werden auch Online-Ergebnisse geliefert. 'true' ermöglich eine solche online Suche, 'false' verweigert diese.

* *oobedisableprivacyexperience* Betrifft nur Windows 10 1809 und neuer. Deaktiviert die OOBE DIsablePrivacyExperience, falls 'true' gesetzt.

* *remove_edge_from_desktop* entfernt den Desktop Shortcut des alten Edge Browsers.

* *show_all_folder_in_navbar* zeigt alle Ordner in der Navigationsleiste des Windows Explorers an.

* *show_drive_letter_first* zeigt den Laufwerksbuchstaben als erstes in der Übersicht an.

* *show_this_pc_instead_of_quicklaunch* öffnet dieser PC anstatt eines Schnellstart Fensters.

* *sync_settings* Wenn man Windows 10 in Kombination mit einem Microsoft Account nutzt, ist es möglich seine Einstellungen mit dem aktuellen Microsoft Konto zu synchronisieren. Setzt man das property 'sync_settings' auf 'false' wird dies deaktiviert.

* *wlid_service* steuert das Verhalten des Windows Live ID Dienstes.




[source, shell]
----
[ProductProperty]
type: bool
name: disable_fast_boot
description: Disable Fastboot for proper opsi startup
default: True

[ProductProperty]
type: bool
name: disable_lock_screen
default: True

[ProductProperty]
type: bool
name: disable_telemetry
description: Disable telemetry data transmission
default: True

[ProductProperty]
type: bool
name: disable_cortana
description: Disable Cortana assistant
default: True

[ProductProperty]
type: bool
name: disable_customer_experience
description: Disable customer experience program
default: True

[ProductProperty]
type: bool
name: disable_mrt
description: Disable Malicious Software Removal Tool
default: True

[ProductProperty]
type: unicode
name: config_updates
multivalue: False
editable: False
description: Set Windows-Update behavior
values: ["AllowPeerToPeer", "LocalPeerToPeer", "MicrosoftOnly"]
default: ["MicrosoftOnly"]

[ProductProperty]
type: bool
name: disable_mac
description: Disable Microsoft Account communication
default: False

[ProductProperty]
type: bool
name: disable_advertising_id
description: Disable Microsoft Advertising ID
default: False

[ProductProperty]
type: bool
name: disable_updates
description: Disable Windows Updates
default: False

[ProductProperty]
type: bool
name: disable_defender
description: Disable Microsoft Windows Defender
default: False

[ProductProperty]
type: bool
name: disable_wifi_sense
description: Disable Wi-Fi Sense
default: False

[ProductProperty]
type: bool
name: disable_sending_feedback
description: Disable sending feedback and diagnostics
default: False

[ProductProperty]
type: bool
name: disable_font_streaming
description: Disable font streaming of not installed fonts
default: False

[ProductProperty]
type: bool
name: defer_upgrade
description: Defer Windows 10 Upgrade
default: True

[ProductProperty]
type: bool
name: flashplayer_autorun
description: Adobe Flashplayer: allow autorun?
default: False

[ProductProperty]
type: bool
name: location_sensors
description: Disable location and sensor detection
default: True

[ProductProperty]
type: bool
name: online_search
description: Disable online search during file or command search
default: True

[ProductProperty]
type: bool
name: disable_handwrite_sharing
description: Tablet-PC: Disable sharing of handriting information
default: True

[ProductProperty]
type: bool
name: sync_settings
description: Sync settings with AccountID
default: False
----
[[opsi-manual-localboot-config-winbase]]
=== config-winbase

Paket zum Customizing der Grundeinstellungen von Oberfläche, Explorer usw..

[[opsi-manual-localboot-opsi-auto-update]]
=== opsi-auto-update

opsi-auto-update ist ein Produkt, um die Pflege der Clients zu vereinfachen.

WARNING: opsi-auto-update ist nicht geeignet für Clients mit der WAN-Erweiterung

Im Kern ist es die Aufgabe des Produktes, dafür zu sorgen, die installierten Produkte aktuell zu halten. +
Das Produkt setzt alle installierten Produkte,
deren Version nicht identisch mit der auf dem Server ist,
für den Client auf setup.

Properties zur Behandlung von Ausnahmen:

* name: `products_to_exclude`
** description: (Blacklist) Which opsi product(s) should be excluded from update ? +
Liste von Produkten, die nicht installiert werden sollten auch wenn es ein Update gibt (wie z.B. windomain)

* name: `products_to_exclude_by_regex`
** description: (Blacklist) Which opsi product(s) should be excluded from update (by regular expressions)? +
Liste von regular expressions, die auf Produkte passen, welche nicht installiert werden sollten auch wenn es ein Update gibt (wie z.B. windomain)

* name: `products_to_include`
** description: (Whitelist) Which opsi product(s) should be checked for update ? ; If empty = all products +
Hier kann man eine Liste von Produkten angeben, auf die die Updateprüfung beschränkt werden soll.
Produkte, welche nicht in dieser Liste sind, werden auch nicht bei der Prüfung auf Updates berücksichtigt.
Ausnahme: Wenn die Liste leer ist, wird gegen alle Produkte geprüft.



Properties zur Behandlung von Ergänzungen:

* name: `products_to_run_always`
** description: Which opsi product(s) should be installed via every update ? (List will not be cleared after run) +
Liste von Produkten, welche bei jedem Lauf von opsi-auto-update auf setup gestellt werden.

* name: `setup_after_install`
** description: Which opsi product(s) should we switch to setup after update is done ? +
Liste von Produkten, welche nach jedem Lauf von opsi-auto-update auf setup gestellt werden. (z.B. shutdownwanted)

* name: `failed_products_to_setup`
** description: if true this also sets all failed products to setup on all clients +
Wenn auf True, werden alle Produkte, die auf failed stehen, erneut auf setup gesetzt.

Properties zur Ablaufsteuerung:

* name: `shutdown_on_finish`
** description: if true we have a final shutdown
if false we have no reboot / shutdown
default: False +
Soll nach Abschluß des Produktes heruntergefahren werden ?

////
* name: `setup_after_install`
** description: Which opsi product(s) should we switch to setup after update is done ? +
Liste von Produkten, welche nach jedem Lauf von opsi-auto-update auf setup gestellt werden. (z.B. shutdownwanted)
////

Special Properties für _local-image / vhd-reset_: +
siehe auch: xref:opsi-modules:vhd.adoc#opsi-manual-vhd[opsi vhd reset] +
siehe auch: xref:opsi-modules:local-image.adoc#opsi-manual-localimage[opsi local image]

* name: `do_cleanup`
** description: If false: skip restore before update +
Diese Property wird ignoriert, wenn es sich nicht um eine vhd oder local.image Installation handelt. +
Bei einer vhd Installation wird bei do_cleanup=true vor den Updates `opsi-vhd-control` aufgerufen und dadurch werden alle Änderungen verworfen und der gespeicherte Zustand wieder hergestellt. +
Bei einer local-image Installation wird bei do_cleanup=true vor den Updates `opsi-local-image-restore` aufgerufen und dadurch werden alle Änderungen verworfen und der gespeicherte Zustand wieder hergestellt. +
In beiden Fällen werden dabei auch die Informationen über Actionrequests verworfen. Um trotzdem während eines Laufs von `opsi-auto-update` Produkte hinzuzufügen oder entfernen zu können, gibt es die folgenden beiden Properties.


* name: `products_to_install`
** description: Which opsi product(s) should be installed via update ? (List will be cleared after run) +
Liste von Produkten, welche beim Lauf von opsi-auto-update auf setup gestellt werden. Wenn die Produkte erfolgreich abgearbeitet wurden, werden sie aus dieser Liste gelöscht.

* name: `products_to_uninstall`
** description: Which opsi product(s) should be uninstalled via update ? (List will be cleared after run) +
Liste von Produkten, welche beim Lauf von opsi-auto-update auf uninstall gestellt werden. Wenn die Produkte erfolgreich abgearbeitet wurden, werden sie aus dieser Liste gelöscht.

* name: `do_merge`
** description: If false: skip backup after update +
Diese Property wird ignoriert, wenn es sich nicht um eine vhd oder local.image Installation handelt. +
Bei einer vhd Installation wird bei do_cleanup=true nach den Updates `opsi-vhd-control` mit `upgrade=true` aufgerufen und dadurch werden alle Änderungen gespeichert. +
Bei einer local-image Installation wird bei do_cleanup=true nach den Updates `opsi-local-image-backup` aufgerufen und dadurch werden alle Änderungen gespeichert.

Properties zu Debug-Zwecken (Finger weg): +

* name: `disabled` +
Diese Property dient zu Debug-Zwecken. +
Wenn 'true', dann führt das Produkt keine Aktionen aus. +
Default = 'false'

* name: `rebootflag` +
Bitte während des Laufes nicht ändern. Sollte vor dem Start '0' sein.

* name: `stop_after_step` +
Diese Property dient zu Debug-Zwecken. +
Wenn nicht '0', dann Anzahl der Reboots, nach denen gestoppt wird.
Default = '0'


Das Produkt `opsi-auto-update` hat eine sehr niedrige Priorität (-97),
welche noch geringer ist als die von opsi-vhd-control.

Das opsi-Produkt `opsi-auto-update`
kann gut mit einem cron-job, der das `opsi-wakeup-clients` ausführt, kombiniert werden. +
(opsi-wakeup-clients ist Bestandteil des opsi-utils Paketes) +
Zur Dokumentation siehe hier: xref:server:temporal-job-control.adoc#opsi-manual-temporal-job-control-cron-opsi-auto-update[opsi-auto-update]


[[opsi-manual-localboot-product-order]]
== Abhängigkeiten und Reihenfolge

Für Produkt-Aktionen können Sie einerseits die Priorität und andererseits Abhängigkeiten definieren.

=== Produktprioritäten
Produktprioritäten dienen dazu, bestimmte Pakete in der Reihenfolge nach vorne oder nach hinten zu schieben.
So ist es z.B. sinnvoll Servicepacks und Patches an den Anfang einer Installation zu legen und eine Softwareinventarisierung an das Ende. +
Produktprioritäten sind Zahlen zwischen 100 (höchste) und -100 (niedrigste).
Keine Priorität (0) ist der Standardwert.

=== Produktabhängigkeiten
Es können Abhängigkeiten zwischen Produkt-Paketen definiert werden.
Diese Abhängigkeiten gelten immer für eine bestimmte Aktion (z.B. `setup`).
Für unterschiedliche Aktionen können unterschiedliche Abhängigkeiten definiert werden.

Produktabhängigkeiten besitzen die folgenden Attribute:

productId:: Das Produkt für das die Abhängigkeit gilt.
productAction:: Die Aktion für die die Abhängigkeit gilt (z.B.: `setup`, `uninstall`)
requiredProductId:: Das Produkt zu dem die Abhängigkeit besteht.
requiredProductVersion:: Eine genaue Produkt-Version des abhängigen Produktes (optional).
requiredPackageVersion:: Eine genaue Paket-Version des abhängigen Produktes (optional).
requiredInstallationStatus:: Der Installations-Status, den das abhängige Produkt erfüllen muss.
requiredAction:: Eine Aktion, die für das abhängige Produkt gesetzt werden soll.
requirementType:: Typ der Abhängigkeit (`before`, `after` oder undefiniert).


Mit Produktabhängigkeiten ist es möglich einen Installations-Status eines anderen Produktes (`requiredInstallationStatus`) als Bedingung zu setzen.
Beim Setzen einer Aktion, die eine solche Abhängigkeit definiert, wird dann auch eine Aktion für das abhängige Produkt gesetzt, wenn diese notwendig ist um die Bedingung zu erfüllen.

*Hierzu ein Beispiel*: +
Die Software *LibreOffice* (Produkt: `libreoffice`) benötigt für gewisse Features ein installiertes *Java Runtime Enviroment* (Produkt: `jre`). +
Das kann mit der folgenden Produktabhängigkeit abgebildet werden: +
`productId`: `libreoffice` +
`requiredProductId`: `jre` +
`requiredInstallationStatus`: `installed` +

Wenn die Bedingung zwingend vor (`before`) oder nach (`after`) der Aktion erfüllt sein muss, kann der Typ der Abhängigkeit entsprechend gesetzt werden.

*Hierzu ein Beispiel*: +
Das Firefox-Addon *Kee Password Manager* (Produkt: firefox-addon-kee) benötigt bei der Installation einen installierten *Firefox Browser* (Produkt: firefox). +
Das kann mit der folgenden Produktabhängigkeit abgebildet werden: +
`productId`: `firefox-addon-kee` +
`requiredProductId`: `firefox` +
`requiredInstallationStatus`: `installed` +
`requirementType`: `before` +

IMPORTANT: Die Abhängigkeits-Typen `before` und `after` sollten nur dann verwendet werden, wenn eine Reihenfolge tatsächlich zwingend benötigt wird. Ansonsten reicht eine Abhängigkeit ohne Angabe eines `requirementType` aus. Eine weniger strikte Steuerung von Reihenfolgen kann auch über die Produktprioritäten erreicht werden.


=== Reihenfolge von Produkt-Aktionen
Die Reihenfolge der Produkt-Aktionen wird unter Berücksichtigung von Produktabhängigkeiten und Produktprioritäten berechnet.

Die auszuführenden Produkt-Aktionen werden zuerst gruppiert.
Hierbei werden alle Aktionen von Produkten in einer Gruppe zusammengefasst, die untereinander Abhängigkeiten vom Typ `after` oder `before` haben.

Innerhalb dieser Gruppen werden die Aktionen nach den Produkt-Prioritäten sortiert (höchste zuerst) und dann aufgrund der, über `before` und `after` definierten Abhängigkeiten, nochmals umsortiert.
Die Gruppe übernimmt dabei die Priorität der enthaltenen Produkt-Prioritäten.
Hierbei wird die niedrigste Priorität verwendet wenn alle enthaltenen Produkt-Prioritäten negativ sind.
In jedem anderen Fall übernimmt die Gruppe die höchste enthaltene Priorität.

Die Aktionen werden dann nach der Priorität der Gruppe (höchste zuerst) und dann nach der Sortierung innerhalb der Gruppe ausgeführt.

NOTE: Ein Produkt mit niedriger Priorität kann in der Reihenfolge weit nach vorne geschoben werden wenn es von einem anderen Produkt mit hoher Priorität als Abhängigkeit mit dem Typ `before` benötigt wird.


[[opsi-manual-localboot-product-order-create]]
=== Erstellung von Prioritäten und Produktabhängigkeiten

Prioritäten und Produktabhängigkeiten gehören zu den Meta-Daten eines opsi-Produktes. Diese werden bei der Erstellung eines Produktes mit dem Befehl `opsi-newprod` abgefragt.

Diese Metadaten werden im control file des Produktes abgelegt und können dort editiert werden. Nach einer Veränderung im control file muss das Produkt neu gepackt und installiert werden.

////
TODO:
Siehe hierzu auch das Kapitel _Erstellen eines opsi-Product-Paketes_ im opsi-getting-started Handbuch.
////

[[opsi-manual-localboot-own_software]]
== Einbindung eigener Software in die Softwareverteilung von opsi

Die Anleitung zur Einbindung eigener Software finden Sie im Handbuch opsi-getting-started.


