////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype: book
:macosclientmanual: opsi-macos-client-manual

// Include common opsi terms
include::../common/opsi_terms.asciidoc[]


[[opsi-macclient-softwintegration]]
== Einbindung eigener Software in die Softwareverteilung von opsi

Die Installation von Software erfolgt bei opsi durch den {opsi-client-agent} und insbesondere durch das Script gesteuerte Setup Programm {opsi-script}. Daher muss zu jedem opsi-Produkt ein {opsi-script}-Script erstellt werden. Danach werden dieses Script, die Installationsdateien und die Metadaten zu einem opsi-Produkt gepackt, welches sich schließlich auf dem {opsi-Server} installieren lässt.

[[opsi-macclient-softwintegration-tutorial]]
=== Ein kleines Tutorial zur Erstellung eines {opsi-script} Scriptes


include::../common/softwintegration-tutorial-introduction.asciidoc[]

[[opsi-macclient-softwintegration-tutorial-general]]
==== Methoden der nicht interaktiven Softwareinstallation bei macOS

Apple hat (im Gegensatz zu Microsoft) sehr früh die Methoden zur Software Installation standardisiert. Im Kern gibt es zwei Methoden:

* *application Directory*: +
Es handelt sich um ein Verzeichnis nach dem Muster:
`<Application name>.app` Ein solches Verzeichnis wird aber im _Finder_ nicht als Verzeichnis angezeigt, sondern als 'Anwendung'. Innerhalb dieses Verzeichnisses müssen sich nach einem bestimmten Muster die Dateien der Anwendung befinden. Ein typischer Aufbau wäre:

----
opsi-script.app
  |--Contents
       |-Info.plist
       |-PkgInfo
       |-MacOS
       |  |-opsi-script
	     |  |-opsi-script-gui
       |
       |-Resources
          |- (....)
----

Ein solches Verzeichnis muß zur Installation nur in das Verzeichnis `/Applications` kopiert werden. Evtl. müssen noch Dateien im Verzeichnis `MacOS` ausführbar gemacht werden. +
Solche *.app Verzeichnisse werden zum Download zumeist gepackt angeboten.

* *PKG file*: +
Diese Dateien enthalten Software die über einen speziellen Befehl installiert werden müssen.

In beiden Fällen ist eine _unattended_ (also nicht interaktive) Installation kein Problem.

Häufig wird macOS Software in gepackten Formaten angeboten wie *.zip, *.dmg
oder auch *.tgz.

Alle bisher genannten Varianten können per opsi-script direkt installiert werden, außer *.tgz welches vorher ausgepackt werden muß.

include::../common/softwintegration-tutorial-script-structure-opsi-script-basics.asciidoc[]
//
[[opsi-macclient-softwintegration-tutorial-macos-special-commands]]
===== Spezielle Kommandos für macOS

* GetOS   // liefert: Linux or Windows_NT or macOS [W/L/M]

* getMacosVersionInfo [M]

* getMacosVersionMap [M]

Siehe auch: +
https://download.uib.de/opsi_stable/doc/html/opsi-script-manual/opsi-script-manual.html#opsi-winst-macos-functions

In den folgenden Kapiteln werden spezielle opsi macOS Befehle zur Installation von Software vorgestellt welche aus der opsi-script Library `uib_macosinstalllib` stammen. Diese Dokumentation ist in Englisch, da sie direkt aus dem Quellcode automatisch generiert wurde.

// http://www.methods.co.nz/asciidoc/userguide.html#X90
:leveloffset: 4

// Include os-lib_uib_macosinstalllib.asciidoc
include::../../en/common/os-lib_uib_macosinstalllib.asciidoc[]

:leveloffset: 0

[[opsi-macclient-softwintegration-tutorial-template]]
==== Drittes Beispiel: macOS-Template _m-opsi-template_

Dieses Template können Sie sich mit dem _opsi-setup-detector_ erstellen.

// include docu: actual template for macOS
include::../../en/common/firststeps_opsi-template-mac.asciidoc[]




[[opsi-client-softwintegration-create-opsi-package]]
=== Erstellen eines opsi-Produkt-Pakets

[[opsi-setup-detector-installation]]
==== Installation des opsi-setup-detector, {opsi-package-builder} und opsi-logviewer

// include docu: opsi-setup-detector installation
include::../common/setup-detector-installation.asciidoc[]


// include docu: opsi-logviewer installation
include::../common/opsi-logviewer-installation.asciidoc[]



[[opsi-macclient-softwintegration-tutorial-create-with-opsi-setup-detector]]
==== Das Programm opsi-setup-detector zum Erstellen eines macOS Scriptes

// include docu: opsi-setup-detector
include::../common/setup-detector-use-start.asciidoc[]

// include docu: macOS specific tasks in opsi-setup-detector
include::../common/osd_tasks_macos.asciidoc[]

Die nun folgenden Screenshots zeigen zwar die Verwendung von Windows-Installer Dateien,
sie sehen aber analog aus bei der Verwendung von macOS Installer Dateien wie *.app, *.dmg, *.zip.

// include docu: how to use the opsi-setup-detector
include::../common/osd-task-use-single-analyze-and-create.asciidoc[]

Mehr Details zum _opsi-setup-detector_ finden Sie im opsi-manual: +
https://download.uib.de/opsi4.2/documentation/html/opsi-manual-v4.2/opsi-manual-v4.2.html#opsi-setup-detector

// include docu: how to use the opsiPackagebuilder
include::../common/softwintegration-tutorial-packagebuilder-use.asciidoc[]

// include docu: The modify and test cycle
include::../common/softwintegration-tutorial-modify-test-cycle.asciidoc[]