////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author: uib gmbh
:Email: info@uib.de
:Revision: 4.2
:website: http://opsi.org

include::common:partial$opsi_terms.adoc[]


[[opsi-manual-glossary]]
= Glossar

////
Asciidoc unterstützt die Erstellung von Glossar-Einträgen, wenn sie im
folgenden Format geschrieben werden:

Begriff::
  Eingerückte Beschreibung

////


Action-Request::
  Die nächste geplante Aktion auf einem Client. Typische Actionrequests sind 'setup', 'uninstall' oder 'update'.


Backend::
  opsi unterstützt unterschiedliche Arten der Datenhaltung, bspw. Dateibasiert oder in einer Datenbank. Diese werden als Backends bezeichnet.


Client-ID::
  Eindeutige Bezeichnung eines Clients durch Verwendung des 'fully qualified domain name' (FQDN).


Config-Server::
  Server, welcher für die Bereitstellung von Management- und Konfigurationsdaten in einer opsi-Umgebung zuständig ist.


Depot-Server::
  Server, welcher Installationsdateien und -Skripte über einen Samba-/Webdav-Share für Clients zur Installation bereit stellt.


DHCP (Dynamic Host Configuration Protocol)::
  Ein Protokoll, welches die dynamische Vergabe von IP-Adressen ermöglicht.


FQDN (Fully Qualified Domain Name)::
  Vollständiger Name eines Computers in einem Netzwerk, welcher aus IP-Name und Domain besteht,
  z.B. 'client001.int.company.de'.


FTP (File Transfer Protocol)::
  Ein Netzwerk-Protokoll für die Dateiübertragung zwischen Client und Server in einem Netzwerk.


GUI (Graphical User Interface)::
  Grafische Schnittstelle zum Anwender.


Host-ID::
  Eindeutige Bezeichnung eines Hosts (umfasst sowohl Client als auch Server) durch Verwendung des 'fully qualified domain name' (FQDN).


JSON (JavaScript Object Notation)::
  JSON ist ein kompaktes Computer-Format in für Mensch und Maschine einfach lesbarer Textform zum Zweck des Datenaustauschs zwischen Anwendungen.


Last seen::
  Zeitstempel wann ein Client sich zuletzt am {opsi-server} gemeldet hat.


LDAP (Lightweight Directory Access Protocol)::
  LDAP ist ein Protokoll, welches Programmen erlaubt Informationen in einem Verzeichnisdienst nachzuschlagen.


Localboot-Produkt::
  Ein opsi-Paket, welches bei laufendem Betriebssystem auf diesem installiert wird.


MAC-Adresse (Media Access Control-Adresse)::
  Mit der MAC-Adresse bezeichnet man eine weltweit eindeutige Nummer der Netzwerk­karte, die bei jeder Datenübertragung mitgesendet wird. Anhand dieser Adresse kann man einen Computer (genauer: dessen Netzwerkkarte) eindeutig identifizieren, um bspw. eine IP-Nummer automatisch zu verteilen o.ä..
  Die Nummer setzt sich aus 6 zweistelligen Hexadezimalzahlen zusammen, die durch einen Doppelpunkt voneinander getrennt sind.


Netboot-Produkt::
  Ein opsi-Paket, welches beim Start über das Netzwerk gestartet wird.
  Oftmals verwendet zur Betriebssysteminstallation auf einem Computer.


opsi::
  open system intergration


opsi-client-agent::
  Die Software-Komponenete die auf jedem opsi-Client läuft, mit dem opsi-Configserver kommuniziert und Anforderungen ausführt.


opsi-server::
  Ein Server der im Rahmen von opsi benötigte Dienste bereitstellt. Üblicherweise 'Config-Server' und 'Depot-Server'.


opsiconfd::
  Server-Dienst, welcher die opsi-API und webdav-Freigaben zur Verfügung stellt.


Product Properties::
  Zusätzliche Einstellungen zu einem {opsi-product} die clientspezifisch gesetzt werden können und bei der Installation ausgewertet werden.


Produkt-ID::
  Eindeutiger Bezeichner eines opsi-Produkts.
  Kann aus a-z, Zahlen und Bindestrichen bestehen.
  Darf keine Leerzeichen oder Sonderzeichen (außer Bindestrich enthalten).
  Beispiel für eine Product-ID: 'acroread'


Produktname::
  Klartextname eines Produktes. Beispiel für einen Produktnamen: 'Adobe Acrobat Reader'


PXE (Preboot eXecution Environment)::
  Standard für das Laden einer Software beim Systemstart über das Netzwerk. Wird in der Regel im Zusammenspiel mit 'DHCP' eingesetzt.


SAMBA::
  Freie Software, um unter Linux Dienste für das von Microsoft-Clients verwendet Protokoll 'SMB/CIFS' anzubieten.


SMB	(Server Message Block)::
  Protokoll von Microsoft, um Netzwerklaufwerke und Authentifizierung anzubieten.
  Ein Dialekt von SMB ist 'CIFS' (Common Internet File System).


TFTP (Trivial File Transfer Protocol)::
  TFTP ist ein sehr einfaches UDP-Protokoll zum Übertragen von Dateien in einem Netzwerk.
  PXE verwendet in der Regel TFTP zur Dateiübertragung.