////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////


:Author:    uib gmbh
:Email:     info@uib.de
:Date:      13.04.2011
:Revision:  4.0
:toclevels: 6

ifeval::["{mode}" == "antora"]
include::common:partial$opsi_terms.adoc[]
endif::[]


[[opsi-manual-introduction]]
== Einführung

[[opsi-manual-introduction-who-should-read]]
=== Für wen ist dieses Handbuch?

Diese Handbuch richtet sich an alle, die sich näher für die automatische Softwareverteilung 'opsi' interessieren. Der Schwerpunkt der Dokumentation ist die Erläuterung der technischen Hintergründe, um so zu einem Verständnis der Abläufe beizutragen.

Damit soll dieses Handbuch nicht nur den praktisch mit opsi arbeitenden Systemadministrator unterstützen sondern auch im Vorfeld den Interessenten einen konkreten Überblick über opsi geben.

[[opsi-manual-introduction-conventions]]
=== Konventionen zu Schrift und Grafiken

In '<spitzen Klammern>' werden Namen dargestellt, die im realen Einsatz durch ihre Bedeutung ersetzt werden müssen.

Beispiel: Der Fileshare, auf dem die opsi Softwarepakete liegen, wird <opsi-depot-share> genannt und liegt auf einem realen Server z.B. auf `/var/lib/opsi/depot`. 

Das Softwarepaket: <opsi-depot-share>/ooffice liegt dann tatsächlich unter `/var/lib/opsi/depot/ooffice`.

Beispiele aus Programmcode oder Konfigurationsdateien stehen in Courier-Schrift und sind farbig hinterlegt.
[source,prompt]
----
depoturl=smb://smbhost/sharename/path
----
