////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      24.05.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



Wenn der Zugriff über einen HTTP-Proxy erfolgen soll, konfigurieren Sie die Proxy-Einstellungen systemweit über Umgebungsvariablen.
Diese Umgebungsvariablen tragen Sie in die Datei `/etc/environment` ein.

NOTE: Beachten Sie, dass die Namen der Umgebungsvariablen ausschließlich aus Kleinbuchstaben bestehen.

* `http_proxy`: Konfiguriert den Proxy für HTTP-Verbindungen, setzt eine vollständige URL voraus (nicht nur Hostname und Port); falls Authentifizierung erforderlich ist, kann diese in der URL definiert werden: +
`http_proxy=http://<user>:<password>@<proxy-address>:<port>`
* `https_proxy`: wie `http_proxy`, nur für HTTPS-Verbindungen: +
`https_proxy=https://<proxy-address>:<port>`
* `no_proxy`: definiert, für welche Adressen kein Proxy verwendet werden soll; mehrere Adressen werden durch Kommata getrennt: +
`no_proxy=127.0.0.1,localhost,mydomain.example,hostname.domain.com:8080` +
Für die Adressen gelten die folgenden Regeln:
** Verwenden Sie nur Kleinbuchstaben.
** Notieren Sie nur IP-Adressen, wenn auch der Zugriff direkt auf die IP-Adresse erfolgt. Bei der Auswertung der Ausnahmen findet keine Namensauflösung statt.
** IP-Adressbereiche (CIDR-Matching, wie z.{nbsp}B. `192.168.0.0/24`) sind nicht zulässig.
** Sie müssen auch für lokale Adressen (`localhost`) und Loopback-Adressen (`127.0.0.1`) Ausnahmen definieren.
** Wildcards und reguläre Ausdrücke sind nicht erlaubt.
** Jeder Name wird als Suffix ausgewertet, `domain.com` definiert daher eine Ausnahme für alle Hostnamen die auf `domain.com` enden.
** Sie können für jede Adresse optional einen Port hinter einem Doppelpunkt angeben, für den die Ausnahme gilt.

Beispiel für die Datei `/etc/environment`:

[source,toml]
----
http_proxy=http://10.1.1.1:8080
https_proxy=https://10.1.1.1:8080
no_proxy=127.0.0.1,localhost,company.tld
----

Übernehmen Sie die Änderungen in die laufende Shell, indem Sie die folgenden Befehle ausführen:

[source,console]
----
set -a; source /etc/environment; set +a
----

NOTE: Bei Suse-Distributionen passen Sie den Parameter `NO_PROXY` in der Datei `/etc/sysconfig/proxy` an. Tragen Sie dazu `NO_PROXY=127.0.0.1,localhost,company.tld` ein.

Erfolgt der `opsiconfd`-Zugriff über einen Proxy, erfolgen die Anfragen an den Dienst von der IP-Adresse des Proxys aus. Alle Funktionen, die mit der IP-Adresse des Clients arbeiten, wie zum Beispiel `networks`, `admin-networks`, `update-ip` oder `max-session-per-ip`, funktionieren dann nicht richtig. Die Adressen von vertrauenswürdigen Proxys können Sie über den Parameter `trusted-proxies` definieren. Stammt die Verbindung von einem vertrauenswürdigen Proxy, wertet der Server den `X-Forwarded-For`-Header aus, um die ursprüngliche Client-Adresse zu erhalten.

Beispiel:

[source,toml]
----
admin-networks=[192.168.10.0/24]
trusted-proxies=[192.178.16.27]
----
