////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      08.05.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

Den Befehl `opsi-makepackage` nutzen Sie, um aus einer Paketquelle (Workbench) ein opsi-Paket mit der Endung `.opsi` zu erstellen. Dazu wechseln Sie ins Quellverzeichnis und rufen dann den Befehl `opsi-makepackage` auf.

`opsi-makepackage` kennt einige Optionen, die das Verhalten beeinflussen.
Die Liste der verfügbaren Parameter kann mittels `opsi-makepackage --help` angezeigt werden.

NOTE: Ein opsi-Paket können Sie auf beliebigen opsi-Depotservern installieren; dazu verwenden Sie das Kommando xref:server:components/commandline.adoc#server-components-opsi-package-manager[*opsi-package-manager*].
