////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

Bei jedem Start des opsiconfd, nimmt dieser automatisch Anpassungen an der opsi-Umgebung vor.
Dank dieses Automatismus sind in der Regel nur wenige manuelle Konfigurations- und Wartungsarbeiten erforderlich.

Der opsiconfd-Setup-Lauf umfasst unter anderem die folgenden Setup-Tasks:

* Automatisches Upgrade von Konfigurations-Dateien
* Anpassen der System-Ressourcen-Limits (ulimit)
* Automatisches Erstellen von benötigten Benutzern und Gruppen
* Anlegen von benötigten Verzeichnissen und Dateien
* Konfiguration der sudoers
* Setzen von Berechtigungen auf Verzeichnissen und Dateien
* Cleanup von Log-Dateien
* Konfiguration von systemd
* Einrichtung der MySQL-Datenbank, Schema-Upgrades und Cleanup
* Automatische Migration eines File-Backends in die MySQL-Datenbank
* Konfiguration und Cleanup von Redis
* Anpassung der Grafana-Konfiguration und Installation von Addons
* Erstellung und Erneuerung der opsi CA und TLS-Server-Zertifikats
* Konfiguration des DHCP-Servers
* Konfiguration von Samba und Anlegen von Freigaben

Dieser Setup-Lauf kann auch jederzeit über den folgenden Befehl ausgeführt werden:

[source,shell]
----
sudo opsiconfd setup
----

Nur beim expliziten Aufruf findet ein voller Setup-Lauf statt.
Beim normalen Start des opsiconfd wird nur ein reduzierter Setup-Lauf vorgenommen,
um den Start des opsiconfd nicht zu stark zu verzögern.

NOTE: Über den opsiconfd-Konfigurations-Parameter `skip-setup` können einzelne dieser Setup-Tasks permanent abgeschaltet werden.

In der Regel arbeitet `opsiconfd setup` nicht-interaktiv.

Für die folgenden Aufgaben wird opsiconfd setup jedoch auch interaktiv verwendet:

* Manuelle Einrichtung einer MySQL-Datenbank-Verbindung (`--configure-mysql`), siehe: xref:server:configuration/mysql.adoc[MySQL]
* Manuelle Registrierung eines {opsi-depot}s (`--register-depot`)
* Umbenennung eines {opsi-configserver}s (`--rename-server`)

NOTE: Um eine Interaktion von `opsiconfd setup` mit dem Benutzer vollständig auszuschließen,
etwa bei der Verwendung in Skripten, kann der Parameter `--non-interactive` verwendet werden.
