////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

Bei jedem `opsiconfd`-Start nimmt dieser automatisch Anpassungen an der opsi-Umgebung vor.
Daher sind in der Regel nur wenig manuelle Konfigurations- und Wartungsarbeiten erforderlich.

`opsiconfd setup` umfasst unter anderem die folgenden Setup-Tasks:

* Konfigurationsdateien automatisch aktualisieren
* System-Ressourcen-Limits (`ulimit`) anpassen
* Benötigte Benutzer und Gruppen erstellen
* Benötigte Dateien und Verzeichnisse anlegen
* Datei `/etc/sudoers` konfigurieren
* Berechtigungen für Dateien und Verzeichnisse setzen
* Log-Dateien aufräumen
* systemd konfigurieren
* MySQL-Datenbank einrichten, Schema-Upgrades und Cleanup
* File-Backend automatisch in die MySQL-Datenbank migrieren
* Redis konfigurieren und Cleanup
* Grafana-Konfiguration anpassen und Addons installieren
* opsi-CA und TLS-Server-Zertifikat erstellen und erneuern
* DHCP-Server konfigurieren
* Samba konfigurieren und Freigaben anlegen

Sie können den Setup-Lauf aber auch jederzeit von Hand über diesen Befehl starten:

[source,console]
----
sudo opsiconfd setup
----

Jetzt beginnt ein vollständiges Setup; beim "normalen" `opsiconfd`-Start findet ein reduzierter Setup-Lauf statt, um den Start des Dienstes zu beschleunigen. 

TIP: Über den `opsiconfd`-Konfigurations-Parameter `skip-setup` können Sie Setup-Tasks permanent abschalten.

In der Regel arbeitet `opsiconfd setup` nicht-interaktiv. 
Für die folgenden Aufgaben wird `opsiconfd setup` jedoch auch interaktiv verwendet:

* Manuelle Einrichtung einer MySQL-Datenbank-Verbindung (`--configure-mysql`), siehe: xref:server:components/mysql.adoc[MySQL]
* Manuelle Registrierung eines opsi-Depots (`--register-depot`)
* Umbenennung eines opsi-Configservers (`--rename-server`)

NOTE: Um eine Interaktion von `opsiconfd setup` mit dem Benutzer vollständig auszuschließen,
etwa bei der Verwendung in Skripten, können Sie den Parameter `--non-interactive` verwenden.
