////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      08.05.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

Den Befehl `opsi-makepackage` nutzen Sie, um aus einer Paketquelle (*workbench*) ein opsi-Paket mit der Endung `.opsi` zu erstellen. Dazu wechseln Sie ins Quellverzeichnis und rufen dann den Befehl `opsi-makepackage` auf.

`opsi-makepackage` kennt einige Optionen, die das Verhalten beeinflussen. So zeigen Sie eine Liste der verfügbaren Parameter und ihrer Bedeutung an:

[source,console]
----
opsi-makepackage --help
usage: opsi-makepackage [--help] [--version] [--quiet] [--verbose] [--log-level {0,1,2,3,4,5,6,7,8,9}] [--no-compression]
                        [--compression {gzip,zstd}] [--archive-format {cpio,tar}] [--no-pigz] [--no-set-rights]
                        [--follow-symlinks] [--custom-name custom name | --custom-only custom name] [--temp-directory directory]
                        [--control-to-toml] [--md5 | --no-md5] [--zsync | --no-zsync] [--keep-versions]
                        [--package-version packageversion] [--product-version productversion]
                        [source directory]

Provides an opsi package from a package source directory. If no source directory is supplied, the current directory will be used.
[…]
----

NOTE: Ein solches opsi-Paket können Sie auf beliebigen opsi-Depotservern installieren; dazu verwenden Sie das Kommando xref:server:components/commandline.adoc#server-components-opsi-package-manager[*opsi-package-manager*].
