////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      06.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

Der *opsi-package-manager* dient zur Installation und Deinstallation von Produkt-Paketen auf einem opsi-Depotserver.

Beim Aufruf von  zur Installation muss das zu installierende Paket für den Benutzer *opsiconfd* lesbar sein.
Es wird daher dringend empfohlen, Produkt-Pakete einem Unterverzeichnis `/var/lib/opsi` zu installieren.

Es folgen einige Beiepiele für die Verwendung.

Ein opsi-Paket installieren:

[source,shell]
----
opsi-package-manager -i opsi-package_1.0-5.opsi
----

Ein opsi-Paket installieren und interaktives Setzen von Standardwerten für Produkteigenschaften:

[source,shell]
----
opsi-package-manager -p ask -i opsi-package_1.0-5.opsi
----

Paket installieren und für alle Clients auf *setup* stellen, bei denen es installiert ist:

[source,shell]
----
opsi-package-manager -S -i opsi-package_1.0-5.opsi
----

Paket installieren und für alle Clients, inklusive abhängigen Paketen, auf *setup* stellen, bei denen es installiert ist:

[source,shell]
----
opsi-package-manager -s -i opsi-package_1.0-5.opsi
----

Ein opsi-Paket deinstallieren:

[source,shell]
----
opsi-package-manager -r opsi-package
----

Ein opsi-Paket entpacken und dabei umbenennen:

[source,shell]
----
opsi-package-manager -x opsi-template.opsi --new-product-id new-product
----

Eine Übersicht über alle Optionen liefert `opsi-package-manager --help`.
