////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      18.12.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

TIP: Anstelle des Paketes `opsi-server-full` können Sie auch `opsi-server` oder `opsi-server-expert` installieren. Die Pakete haben andere Abhängigkeiten und sind für den Fall gedacht, dass Sie MySQL, Redis oder Grafana auf einem anderen Server betreiben wollen. `opsi-server` und `opsi-server-expert` bieten mehr Fexibilität, sollten jedoch nur von erfahrenen Linux-Administratoren verwendet werden.

NOTE: Stellen Sie sicher, dass Ihre Firewall und die SELinux-Konfiguration Verbindungen zu den Ports 69/UDP (TFTP) sowie 4447/TCP und 4441/TCP (opsi) zulassen. Weitere Hinweise zu SELinux finden Sie unter xref:server:installation/selinux.adoc#server-installation-selinux[SELinux].
