////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      05.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

= Clients hinzufügen (Linux)

Dieses Kapitel erklärt, wie Sie Linux-Clients in die opsi-Umgebung integrieren. Als Erstes geht es um die Aufnahme vorhandener Clients, danach zeigen wir, wie Sie neue Clients hinzufügen.

TIP: Mit opsi können Sie auch Windows- und macOS-Clients verwalten. Details dazu finden Sie in den beiden Kapiteln xref:clients:windows-client/windows-client-manual.adoc[Windows-Clients] und xref:clients:macos-client/mac-client-manual.adoc[macOS-Clients].

[[firststeps-software-deployment-client-integration]]
== Vorhandene Clients integrieren



Um vorhandene Clients mit bereits installiertem Betriebssystem in opsi aufzunehmen, installieren Sie auf dem jeweiligen Rechner den Client-Agent. Danach erscheint der Client auch in der Client-Liste der Management-Oberfläche, sofern Sie ihn dort noch nicht hinzugefügt hatten.

Grundsätzlich gibt es zwei verschiedene Möglichkeiten, den Client-Agent zu installieren:

* <<firststeps-software-deployment-client-integration-oca-installer>> (Installation auf dem Client, eignet sich für einzelne Rechner)
* <<firststeps-software-deployment-client-integration-opsi-deploy>> (Installation auf Server anstoßen, Massen-Rollout, wenn die dazu nötigen Freischaltungen auf den Linux-Clients vorhanden sind)

NOTE: Nachdem der Client-Agent installiert ist, können Sie opsi-Produkte auf dem Client einspielen (siehe Kapitel xref:clients:linux-client/rollout-products.adoc[Rollout existierender Produkte]).

// cspell: ignore installer

[[firststeps-software-deployment-client-integration-oca-installer]]
=== Installer auf dem Client verwenden

include::common:partial$firststeps-oca-installer.adoc[]


[[firststeps-software-deployment-client-integration-opsi-deploy]]
=== opsi-deploy-client-agent verwenden

Das `opsi-deploy-client-agent` Programm verteilt den *opsi-linux-client-agent* direkt vom opsi-Server auf die Clients.
Es ist hiermit einfach möglich eine große Menge an Clients vom Server aus in eine opsi-Umgebung zu integrieren.
Voraussetzung hierfür sind bei den Clients:

* ein aktivierter ssh Zugang
* Administrativer User mit Passwort

// cspell: ignore depot, help

Das `opsi-deploy-client-agent` Programm findet sich unter `/var/lib/opsi/depot/opsi-linux-client-agent`
Führen Sie das Script mit 'root' Rechten aus oder als ein user, der Teil der Gruppe "opsifileadmins" ist.
Falls das Script nicht ausführbar ist, so können Sie dieses Problem mit dem folgenden Befehl beheben:
`opsi-set-rights /var/lib/opsi/depot/opsi-linux-client-agent/opsi-deploy-client-agent`

Das Programm erzeugt serverseitig den Client, kopiert die Installations-Dateien und Konfigurationsinformationen, wie bspw. den `opsi-host-key`, auf den Client und startet dort die Installation.
Die Installation läuft im Hintergrund ohne, dass ein User davon etwas bemerken muss.

Der Befehl `opsi-deploy-client-agent` hat eine Fülle von Aufrufparametern.
Bei allen nachfolgenden Beispielen wird davon ausgegangen, das Sie in das Stammverzeichnis des *opsi-linux-client-agent* Produktes gewechselt sind:

[source,shell]
----
cd /var/lib/opsi/depot/opsi-linux-client-agent
----

Typische Aufrufe sind:

* Für einen einzelnen Client:

// cspell: ignore linux

[source,shell]
----
./opsi-deploy-client-agent -v --user=root linux-client
----

* Für eine Liste von Clients:

// cspell: ignore skip, help, existing, HOSTFILE

[source,shell]
----
./opsi-deploy-client-agent -v --user=root --hosts-from-file HOSTFILE.TXT  --skip-existing-clients
----

Hier ist HOSTFILE.TXT eine Datei mit einem Client-Namen (FQDN) pro Zeile. Soweit die Clients dem opsi-server noch nicht bekannt sind, wird versucht den `opsi-linux-client-agent` auf dieser Maschine zu installieren

* Anzeigen alle Kommandozeilen Parameter:

[source,shell]
----
./opsi-deploy-client-agent --help
----

:leveloffset: +1

[[opsi-create-client-adding-clients]]
include::common:partial$firststeps-adding-clients.adoc[]

:leveloffset: -1

