////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      16.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons: font
:xrefstyle: full
:lang: de


[[opsi-linclient-introduction]]
= Linux-Clients

Diese Anleitung beschreibt den Betrieb von Linux-Clients in opsi.

NOTE: Voraussetzung ist, dass ein xref:server:overview.adoc[opsi-Server] bereits installiert und betriebsbereit ist.

Wesentliche Themen dieser Anleitung:

// cspell: ignore paketieren

. Automatische OS-Installation
. Linux-Rechner in opsi aufnehmen und einbinden
(Installation des xref:clients:client-agent/opsi-client-agent.adoc[Client-Agent])
. opsi-Standardsoftware für Linux auf dem opsi-Server bereitstellen
. Standardsoftware auf den Linux-Clients installieren
. opsi-Pakete erstellen und eigene Software paketieren
. Hinweise zu Linux-Clients
.. Spezielle Befehle für Linux
.. Verzeichnisse, die Sie verwenden dürfen

[[opsi-winclient-convention]]
include::ROOT:partial$conventions.adoc[]
