////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      30.03.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



[[opsi-manual-lin-client-agent]]
= Client-Agent (Linux)

Mit opsi verteilen Sie Software ganz automatisch auf den Clients, indem Sie Installationen oder Updates direkt auf dem Server anfordern. Dabei ist keinerlei Benutzer-Interaktion erforderlich. Ohne dass Anwender etwas davon mitbekommen, läuft die Installation im Hintergrund ab. Damit ist auch sichergestellt, dass verunsicherte Benutzer Installationen nicht einfach abbrechen können.

Um diese automatischen Vorgänge zu ermöglichen, nutzt opsi einen speziellen Agenten auf den Client-Computern: Der Client-Agent sorgt dafür, dass Installationen und Aktualisierungen reibungslos und ohne jegliche Benutzerbeteiligung ablaufen.

include::common:partial$opsi-client-agent.adoc[]

[[opsi-manual-client-agent-linux-directories]]
== Wichtige Verzeichnisse

Auf Linux-Systemen finden Sie Bestandteile des Client-Agent hauptsächlich im Verzeichnis `/usr/lib`. Symbolische Links zu den Programmen `opsiclientd`, `opsi-notifier` und `opsi-script` liegen unter `/usr/bin` und sind daher im Standard-`PATH` enthalten. In `/etc/opsi-client-agent/` liegt die Konfigurationsdatei `opsiclientd.conf`, die nur für den Benutzer `root` les- und schreibbar ist. Hier gibt es weitere Dateien, die für den Betrieb des Linux-Client-Agent notwendig sind.

Logdateien finden Sie im Verzeichnis `/var/log/`. `/var/log/opsi-client-agent` enthält die `opsiclientd`- und `opsi-notifier`-Logs. Die `opsi-script`-Protokolle finden Sie in `/var/log/opsi-script`.
