////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      05.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-manual-lin-client-agent]]
= Client-Agent (Linux)

Mit opsi verteilen Sie Software ganz automatisch auf den Clients, indem Sie Installationen oder Updates direkt auf dem Server anfordern. Dabei ist keinerlei Benutzer-Interaktion erforderlich. Ohne dass Anwender etwas davon mitbekommen, läuft die Installation im Hintergrund ab. Damit ist auch sichergestellt, dass verunsicherte Benutzer eine Installation abbrechen können.

Um diese automatischen Vorgänge zu ermöglichen, nutzt opsi einen speziellen Agenten auf den Client-Computern: Der Client-Agent sorgt dafür, dass Installationen und Aktualisierungen reibungslos und ohne jegliche Benutzerbeteiligung ablaufen.

include::common:partial$opsi-client-agent.adoc[]

[[opsi-manual-client-agent-linux-directories]]
== Wichtige Verzeichnisse 

Die Bestandteile des opsi-client-agents liegen unter `/usr/lib`. Symlinks zu den Programmen *opsiclientd*, *opsi-notifier* und *opsi-script* werden unter `/usr/bin` abgelegt, wo sie im Standard-PATH enthalten sind. In `/etc/opsi-client-agent/` liegt die Konfigurationsdatei opsiclientd.conf, welche nur als user `root` zu lesen ist. Außerdem liegen hier weitere Dateien, die für den Betrieb des opsi-linux-client-agent notwendig sind.

Logdateien finden Sie unter `/var/log/`. `/var/log/opsi-client-agent` enthält die Logdateien des *opsiclientd* und *opsi-notifier*.
Die Logdateien des *opsi-script* sind in `/var/log/opsi-script`.
