////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      05.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons: font
:xrefstyle: full



// cspell: ignore paketieren

[[opsi-linclient-introduction]]
= Linux-Clients

Diese Anleitung beschreibt den Betrieb von Linux-Clients in opsi-Umgebungen. Dabei geht es im Wesentlichen um die folgenden Themen:

* automatische OS-Installation
* Linux-Rechner in opsi aufnehmen und einbinden
(Installation des xref:clients:linux-client/linux-client-agent.adoc[Client-Agent])
* Standardsoftware auf dem opsi-Server bereitstellen
* Standardsoftware auf den Linux-Clients installieren
* opsi-Pakete erstellen und eigene Software paketieren
* Hinweise zu Linux-Clients
    ** spezielle Befehle für Linux
    ** Verzeichnisse, die Sie verwenden dürfen

NOTE: Voraussetzung für die Verwaltung von Linux-Clients ist, dass ein xref:server:overview.adoc[opsi-Server] bereits installiert und betriebsbereit ist.

[[opsi-winclient-convention]]
include::ROOT:partial$conventions.adoc[]
