////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////
:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:toc: left
:toclevels: 3
:numbered:
:icons: font
:xrefstyle: full
:doctype:   book
:date:      26.05.2021
:linclientmanual: opsi-linux-client-manual
:lang: de

include::../common/opsi_terms.asciidoc[]


= opsi Linux client manual

// Include common opsi copyright
include::../common/opsi_manual_copyright.asciidoc[]


[[opsi-linclient-introduction]]
== Einführung Linux Clients in opsi

Diese Anleitung beschreibt den Betrieb von Linux Clients in opsi.

Es wird voraus gesetzt, das die Installation und Inbetriebnahme eines {opsi-Server}s bereits erfolgt ist.

Wesentliche Themen dieser Anleitung:

. Automatische Linux OS-Installation
. Aufnahme und Einbindung von Linux-Rechnern in opsi
(Installation des opsi-linux-client-agent)
. Bereitstellung von opsi Standardsoftware für Linux auf dem opsi-server
. Installation von Standard Software auf den Linux-Clients
. opsi-Standardsoftware für Linux unter opsi
. Paketierung eigener Software
. Erstellung von opsi-Paketen
. Hinweise zu Linux Clients
.. Spezielle Befehle für Linux
.. Directories die Sie verwenden dürfen


[[opsi-linclient-convention]]
== Konventionen dieses Dokuments

Befehle werden gesondert hervorgehoben:

[source,shell]
----
dies ist ein Befehl
----

Im Rahmen der Installation und Konfiguration können Sie die Befehle aus diesen Feldern in der Regel der Reihe nach per _copy & paste_ aus diesem Dokument kopieren und ausführen.

Das ist ein opsi-script Code:

[source,winst]
----
Message "Installing "+ $ProductId$ +" ..."
----

Kapitel welche den Namen einer bestimmten Plattform enthalten sind spezifisch für diese Plattform. Die unterstützen Plattformen sind:

* *Windows*

* *Linux*

* *macOS*


include::requirements.adoc[]

include::minimal-products.adoc[]

include::adding-clients.adoc[]

include::rollout-products.adoc[]

include::opsiconfiged.adoc[]

include::hwinvent.adoc[]

include::os-installation.adoc[]

include::softwareintegration.adoc[]

include::general-notes.adoc[]

include::more.adoc[]

