////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      16.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons: font
:xrefstyle: full
:lang: de

[[opsi-linclient-requirements]]
= Voraussetzungen für Linux Clients

Nachfolgend werden die Voraussetzungen für das Management von Linux Clients unter opsi beschrieben.

Der opsi-linux-client-agent ist eine
http://uib.de/de/opsi-erweiterungen/erweiterungen/[kofinanzierte opsi Erweiterung].
Das bedeutet, dass Sie zum Einsatz eine Freischaltdatei benötigen. Diese Freischaltung erhalten Sie wenn Sie die Erweiterung kaufen. Zu Evaluierungszwecken stellen wir Ihnen auch eine zeitlich befristete Freischaltung kostenlos zur Verfügung ( -> mail an info@uib.de).
Weitere Details hierzu finden Sie in xref:opsi-modules:linux.adoc[opsi-modules Linux]

[[opsi-linclient-supportmatrix-clients-linux]]
== Von opsi unterstützte Linux Distributionen / Versionen

include::opsi-docs-en:common:partial$supportmatrix-linclient-core.adoc[]
