////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      05.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



[[opsi-linclient-requirements]]
= Voraussetzungen

Dieses Kapitel beschreibt die Voraussetzungen für das Management von Linux-Clients unter opsi. Als Erstes listet eine Tabelle die unterstützten Linux-Versionen für opsi 4.3 und die Namen der Netboot-Produkte auf. Die nächste Tabelle zeigt die Netboot-Produkte nach Installer-Typ in opsi 4.3.

NOTE: Der Linux-Client-Agent ist eine xref:opsi-modules:linux.adoc[kostenpflichtige Erweiterung]. Das heißt, dass Sie eine Freischaltdatei benötigen. Sie erhalten diese, nachdem Sie die Erweiterung gekauft haben. Zu Evaluierungszwecken stellen wir Ihnen kostenlos eine zeitlich befristete Freischaltung zur Verfügung. Bitte kontaktieren Sie uns dazu per mailto:info@uib.de[E-Mail].

[[opsi-linclient-supportmatrix-clients-linux]]
== Unterstützte Linux-Distributionen

include::{version}@opsi-docs-en:common:partial$supportmatrix-linclient-core.adoc[]
