////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      05.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[firststeps-software-deployment-product-tests]]
= Rollout existierender Produkte

Um Software auf Clients bereitzustellen, muss auf den Clients der xref:clients:linux-client/linux-client-agent.adoc[Client-Agent] installiert sein.

TIP: Bei einer xref:clients:windows-client/os-installation.adoc[OS-Installation] über opsi wird der Client-Agent automatisch installiert.

Dieses Kapitel erklärt, wie Sie Software über die xref:clients:windows-client/opsiconfiged.adoc[Management-Oberfläche *opsi-configed*] auf Clients verteilen. Zu den Standard-Produkten für Linux-Clients gehören unter anderem diese:

// cspell: ignore swaudit, hwaudit

* `opsi-linux-client-agent`
* `swaudit`
* `hwaudit`
* `l-system-update`
* `opsi-configed`
* `opsi-auto-update`
* `l-opsi-client-kiosk`
* `opsi-setup-detector`

:leveloffset: +1

include::common:partial$firststeps-swdp-product-tests-configed.adoc[]

include::common:partial$firststeps-swdp-product-tests-inventory.adoc[]

:leveloffset: -1


