////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      16.06.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons: font
:xrefstyle: full
:lang: de


[[firststeps-software-deployment-product-tests]]
= Rollout existierender Produkte auf Linux

F체r den Rollout von Software auf Clients muss auf diesen der *opsi-linux-client-agent* installiert sein.
Dieser kann auf xref:linux-client:adding-clients.adoc#firststeps-software-deployment-client-integration[bestehende Rechner] ausgerollt werden.


Nachfolgend wird die Management-Oberfl채che <<firststeps-software-deployment-product-tests-configed,opsi-configed>> verwendet, um Software auf Clients zu verteilen.

// cspell: ignore swaudit, hwaudit

Folgende Produkte werden von opsi f체r Linux als Standard zur Verf체gung gestellt:

* `opsi-linux-client-agent`
* `swaudit`
* `hwaudit`
* `l-system-update`
* `opsi-configed`
* `opsi-auto-update`
* `l-opsi-client-kiosk`
* `opsi-setup-detector`
* ``


include::common:partial$firststeps-swdp-product-tests-configed.adoc[leveloffset=-1]

include::common:partial$firststeps-swdp-product-tests-inventory.adoc[leveloffset=-1]


