////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype: book
:linclientmanual: opsi-linux-client-manual

include::common:partial$opsi_terms.adoc[]


[[firststeps-software-deployment-product-tests]]
= Rollout existierender Produkte auf Linux

F체r den Rollout von Software auf Clients muss auf diesen der _opsi-client-agent_ installiert sein.
Dieser kann auf xref:adding-clients.adoc#firststeps-software-deployment-client-integration[bestehende Rechner] ausgerollt werden.


Nachfolgend wird die Management-Oberfl채che <<firststeps-software-deployment-product-tests-configed,opsi-configed>> verwendet, um Software auf Clients zu verteilen.


Folgende Produkte werden von opsi f체r Linux als Standard zur Verf체gung gestellt:

* `opsi-linux-client-agent`
* `swaudit`
* `hwaudit`
* `l-system-update`
* `opsi-configed`
* `opsi-logviewer`
* `opsi-auto-update`
* `opsi-linux-client-kiosk`
* `opsi-setup-detector`
* ``



include::common:partial$firststeps-swdp-product-tests-configed.adoc[leveloffset=-1]

include::common:partial$firststeps-swdp-product-tests-inventory.adoc[leveloffset=-1]


