////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      15.10.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-linclient-softwintegration]]
= Eigene Software einbinden

Für die Installation von Software ist bei opsi der xref:clients:windows-client/windows-client-agent.adoc[Client-Agent] bzw. das Setup-Programm xref:opsi-script-manual:opsi-script-manual.adoc[*opsi-script*] zuständig. Wenn Sie also eigene Software paketieren, müssen Sie zu jedem Produkt auch ein `opsi-script`-Skript erstellen. Dieses packen Sie anschließend zusammen mit den Installationsdateien und den Metadaten zu einem opsi-Produkt, das Sie auf dem opsi-Server installieren (siehe Kapitel xref:clients:windows-client/minimal-products.adoc[Produkte auf opsi-Server bereitstellen]).

[[opsi-linclient-softwintegration-tutorial]]
== Tutorial: *opsi-script*-Skript erstellen

include::common:partial$softwintegration-tutorial-introduction.adoc[]

[[opsi-linclient-softwintegration-tutorial-general]]
=== Nicht-interaktive Software-Installation (Linux)

Im Vergleich zu Windows gibt es auf Linux-Systemen eine gewisse Einheitlichkeit bei den Paketformaten und Installationsmethoden. Die Herausforderung bei Linux ergibt sich aus der Vielzahl von Distributionen, die jeweils unterschiedliche Paketformate und Installationsbefehle verwenden. Hier sind die grundlegenden Varianten:

// cspell: ignore Installer

* Installation eines Paketes aus einem Repository
* Installation eines Paketes aus einer Datei (`.rpm`, `.deb`)
* Installation mit einem Third-Party-Installer
* Installation aus dem Quellcode (`.tgz`- oder `.zip`-Archiv) mit dem Dreischritt `configure`, `make`, `make install`

NOTE: Bis auf `.tgz`-Archive, die Sie vorher entpacken müssen, können Sie alle Varianten direkt per `opsi-script` installieren.

include::common:partial$softwintegration-tutorial-script-structure-opsi-script-basics.adoc[]

[[opsi-linclient-softwintegration-tutorial-Linux-special-commands]]
==== Spezielle Linux-Kommandos

// cspell: ignore Distro, debian, redhat, suse, card

* `GetOS`: Gibt das Betriebssystem aus, z.{nbsp}B. `Linux`, `Windows_NT` (Windows NT bis Windows 11) oder `macOS`.

* `getLinuxDistroType`: Liefert die laufende Linux-Distribution, z.{nbsp}B. `debian`, `redhat` oder `suse` 

* `getLinuxVersionMap`: Fragt die Betriebssystem-Informationen lokal ab und schreibt die Informationen in eine String-Liste.

TIP: Weiterführende Informationen zu den Linux-spezifischen `opsi-script`-Kommandos finden Sie im Kapitel xref:opsi-script-manual:linux-macos.adoc[*opsi-script* unter Linux und macOS].

===== Linux-Befehle zur Installation

NOTE: Die nächsten Abschnitte stellen spezielle macOS-Befehle zur Installation von Software vor. Sie stammen aus der `opsi-script`-Bibliothek `uib_lin_install`. Dieser Teil der Dokumentation ist in Englisch, da er automatisch aus dem Quellcode generiert wurde.

//hier
Zum Verständnis zunächst ein Überblick über die unterschiedlichen Ansätze der Methoden:

// cspell: ignore distributionsunabhängige, cleanup, installupdates, packagelist

* Distributionsunabhängige Methoden:

** `cleanupPackageSystem`

** `installupdates`

* Installation von einem oder mehreren Paketen aus online Repos für eine spezifische Distribution +
Soll nur ein Paket installiert werden, so ist in dem Aufrufen statt $packagelist$, zu verwenden: `createStringList(<package name>)` +
Die Paketnamen in der Liste müssen zur Distribution / Version passen.

// cspell: ignore since, debinstall, redinstall, suseinstall, ucsinstall, linux, packagename, packagefile

** debinstall($packagelist$ : stringlist) : string //since 4.12.4 [L]

** redinstall($packagelist$ : stringlist) : string //since 4.12.4 [L]

** suseinstall($packagelist$ : stringlist) : string //since 4.12.4 [L]

** ucsinstall($packagelist$ : stringlist) : string //since 4.12.4 [L]

* Installation / Deinstallation von einem oder mehren Paketen für eine bekannte Distribution / Version (d.h. Paketnamen müssen passen). +
Der notwendige Befehl wird anhand der Distribution ermittelt.

** genericLinInstall($packagelist$ : stringlist) : string

** linuxRemoveOnePackage($packagename$ : string) : string

** linuxInstallOneFile($packagefile$ : string) : string

// cspell: ignore Installed, Paketierung

* Installation / check / Deinstallation eines Paketes aus online Repos für unterschiedliche Distributionen / Versionen, weswegen das Paket auch unterschiedliche Namen haben kann. +
D.h. es wird davon ausgegangen, das die Paketnamen in der Liste alles pseudonyme für das selbe Paket sind aber für unterschiedliche Versionen bzw. Distributionen.
Der notwendige Befehl wird anhand der Distribution ermittelt.

** linuxInstallOneOf($packagelist$ : stringlist) : string

** isOneInstalled($packagelist$ : stringlist) : string

** linuxRemoveOneOf($packagelist$ : stringlist) : string

// http://www.methods.co.nz/asciidoc/userguide.html#X90

:leveloffset: +5

include::{version}@opsi-docs-en:common:partial$os-lib-uib-lin-install.adoc[]

:leveloffset: -5


[[opsi-linclient-softwintegration-tutorial-template]]
=== Beispiel: Linux-Template _l-opsi-template_

Dieses Template können Sie sich mit dem `opsi-setup-detector` erstellen.

include::{version}@opsi-docs-en:common:partial$firststeps-opsi-template-lin.adoc[]


 

[[opsi-client-softwintegration-create-opsi-package]]
== Erstellen eines opsi-Produkt-Paketes


include::common:partial$setup-detector-installation.adoc[]

include::common:partial$opsi-logviewer-installation.adoc[leveloffset=-1]



[[opsi-linclient-softwintegration-tutorial-create-with-opsi-setup-detector]]
=== Das Programm opsi-setup-detector zum Erstellen eines Linux Scripts

include::common:partial$setup-detector-use-start.adoc[]

include::common:partial$osd-task-linux.adoc[]

Die nun folgenden Screenshots zeigen zwar die Verwendung von Windows-Installer Dateien,
sie sehen aber analog aus bei der Verwendung von Linux Installer Dateien wie *.deb, *.rpm.

include::common:partial$osd-task-use-single-analyze-and-create.adoc[]

Mehr Details zum `opsi-setup-detector` finden Sie im opsi-manual: +
https://docs.opsi.org/opsi-docs-de/4.2/manual/modules/setup-detector.html

include::common:partial$softwintegration-tutorial-packagebuilder-use.adoc[leveloffset=-1]

include::common:partial$softwintegration-tutorial-modify-test-cycle.adoc[leveloffset=-1]

[[opsi-winclient-softwintegration-tutorial-template-details]]
== Hinweise zu den Teilaufgaben in der Paketierung

include::common:partial$osd-checkboxes-subtasks.adoc[leveloffset=-1]

