////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////


:Author:    uib GmbH
:Email:     info@uib.de
:Date:      15.04.2024
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-linclient-softwintegration]]
= Eigene Software einbinden

Für die Installation von Software ist bei opsi der xref:clients:linux-client/linux-client-agent.adoc[Client-Agent] bzw. das Setup-Programm xref:opsi-script-manual:opsi-script-manual.adoc[*opsi-script*] zuständig. Wenn Sie also eigene Software paketieren, müssen Sie zu jedem Produkt auch ein `opsi-script`-Skript erstellen. Dieses packen Sie anschließend zusammen mit den Installationsdateien und den Metadaten zu einem opsi-Produkt, das Sie auf dem opsi-Server installieren (siehe Kapitel xref:clients:linux-client/minimal-products.adoc[Produkte auf opsi-Server bereitstellen]).

[[opsi-linclient-softwintegration-tutorial]]
== Tutorial: *opsi-script*-Skript erstellen

include::common:partial$softwintegration-tutorial-introduction.adoc[]

[[opsi-linclient-softwintegration-tutorial-general]]
=== Nicht-interaktive Software-Installation (Linux)

Im Vergleich zu Windows gibt es auf Linux-Systemen eine gewisse Einheitlichkeit bei den Paketformaten und Installationsmethoden. Die Herausforderung bei Linux ergibt sich aus der Vielzahl von Distributionen, die jeweils unterschiedliche Paketformate und Installationsbefehle verwenden. Hier sind die grundlegenden Varianten:

// cspell: ignore Installer

* Installation eines Paketes aus einem Repository
* Installation eines Paketes aus einer Datei (`.rpm`, `.deb`)
* Installation mit einem Third-Party-Installer
* Installation aus dem Quellcode (`.tgz`- oder `.zip`-Archiv) mit dem Dreischritt `configure`, `make`, `make install`

NOTE: Bis auf `.tgz`-Archive, die Sie vorher entpacken müssen, können Sie alle Varianten direkt per `opsi-script` installieren.

include::common:partial$softwintegration-tutorial-script-structure-opsi-script-basics.adoc[]

[[opsi-linclient-softwintegration-tutorial-Linux-special-commands]]
== Spezielle Linux-Kommandos

// cspell: ignore Distro, debian, redhat, suse, card

* `GetOS`: Gibt das Betriebssystem aus, z.{nbsp}B. `Linux`, `Windows_NT` (Windows NT bis Windows 11) oder `macOS`.

* `getLinuxDistroType`: Liefert die laufende Linux-Distribution, z.{nbsp}B. `debian`, `redhat` oder `suse` 

* `getLinuxVersionMap`: Fragt die Betriebssystem-Informationen lokal ab und schreibt die Informationen in eine String-Liste.

TIP: Weiterführende Informationen zu den Linux-spezifischen `opsi-script`-Kommandos finden Sie im Kapitel xref:opsi-script-manual:linux-macos.adoc[*opsi-script* unter Linux und macOS].

=== Linux-Befehle zur Installation

NOTE: Die nächsten Abschnitte stellen spezielle Linux-Befehle zur Installation von Software vor. Sie stammen aus der `opsi-script`-Bibliothek `uib_lin_install`. Dieser Teil der Dokumentation ist in Englisch, da er automatisch aus dem Quellcode generiert wurde.

Zum besseren Verständnis geben wir zunächst einen Überblick über die unterschiedlichen Ansätze der Methoden:

// cspell: ignore distributionsunabhängige, cleanup, installupdates, packagelist

* Distributionsunabhängige Methoden:

** `cleanupPackageSystem`

** `installupdates`

* Installation von einem oder mehreren Paketen aus Online-Repositorys einer bestimmten Distribution; die Paketnamen in der Liste müssen zur Distribution/Version passen. Um ein einzelnes Paket zu installieren, geben Sie im Aufruf anstelle von `$packagelist$` Folgendes an: `createStringList(<package name>)` +
// cspell: ignore since, debinstall, redinstall, suseinstall, ucsinstall, linux, packagename, packagefile

** `debinstall($packagelist$ : stringlist) : string` (ab Version 4.12.4 [L])

** `redinstall($packagelist$ : stringlist) : string` (ab Version 4.12.4 [L])

** `suseinstall($packagelist$ : stringlist) : string` (ab Version 4.12.4 [L])

** `ucsinstall($packagelist$ : stringlist) : string` (ab Version 4.12.4 [L])

* Installation/Deinstallation von einem oder mehren Paketen für eine bekannte Distribution/Version; die Paketnamen in der Liste müssen zur Distribution/Version passen. Der notwendige Befehl wird anhand der Distribution ermittelt: +

** `genericLinInstall($packagelist$ : stringlist) : string`

** `linuxRemoveOnePackage($packagename$ : string) : string`

** `linuxInstallOneFile($packagefile$ : string) : string`

// cspell: ignore Installed, Paketierung

* Installation, Check oder Deinstallation eines Paketes aus Online-Repositorys, daher kann das Paket unterschiedliche Namen haben. (Es wird davon ausgegangen, dass die Paketnamen in der Liste alle das gleiche Paket meinen, aber für unterschiedliche Versionen bzw. Distributionen gelten.) Der notwendige Befehl wird anhand der Distribution ermittelt: +

** `linuxInstallOneOf($packagelist$ : stringlist) : string`

** `isOneInstalled($packagelist$ : stringlist) : string`

** `linuxRemoveOneOf($packagelist$ : stringlist) : string`

// http://www.methods.co.nz/asciidoc/userguide.html#X90

:leveloffset: +2

include::{version}@opsi-docs-en:common:partial$os-lib-uib-lin-install.adoc[]

:leveloffset: -2

[[opsi-linclient-softwintegration-tutorial-template]]
== Beispiel: Linux-Template *l-opsi-template*

Dieses Template können Sie mit dem `opsi-setup-detector` erstellen (siehe Abschnitt <<opsi-linclient-softwintegration-tutorial-create-with-opsi-setup-detector>>).

include::{version}@opsi-docs-en:common:partial$firststeps-opsi-template-lin.adoc[]

[[opsi-client-softwintegration-create-opsi-package]]
== opsi-Produkte erstellen

Die nächsten Abschnitte erklären, wie Sie Software paketieren, also opsi-Produkte erstellen. Der grundlegende Ablauf sieht so aus:

1. Den "Rohbau" eines Paketes erstellen Sie mit dem `opsi-setup-detector` (siehe Abschnitt <<opsi-linclient-softwintegration-tutorial-create-with-opsi-setup-detector>>).
2. Danach testen Sie das `opsi-script`-Skript (siehe Abschnitt <<opsi-softwintegration-tutorial-create-and-test-script>>).
3. Mit dem opsi PackageBuilder (oPB) erstellen Sie aus der Rohform ein opsi-Paket und hinterlegen es auf dem opsi-Server.

include::common:partial$setup-detector-installation.adoc[]

include::common:partial$opsi-logviewer-installation.adoc[]

[[opsi-linclient-softwintegration-tutorial-create-with-opsi-setup-detector]]
== *opsi-setup-detector*: Skript erstellen

Die folgenden Abschnitte erklären detailliert, wie Sie mit dem `opsi-setup-detector` ein opsi-Produkt eine Setup-Datei analysieren und ein opsi-Produkt erstellen.

include::common:partial$setup-detector-use-start.adoc[]

include::common:partial$osd-tasks-linux.adoc[]

NOTE: Die folgenden Screenshots zeigen die Abläufe für Windows-Installer Dateien, sie sehen unter Linux aber ähnlich aus, wenn Sie Paketformate wie `.deb` oder `.rpm` verwenden.

// include docu: how to use the opsi-setup-detector
include::common:partial$osd-task-use-single-analyze-and-create.adoc[]

// include docu: The modify and test cycle
include::common:partial$softwintegration-tutorial-modify-test-cycle.adoc[]

[[opsi-winclient-softwintegration-tutorial-template-details]]
== Erweiterte Konfiguration mit *opsi-setup-detector*

Die folgenden Abschnitte zeigen weitere Konfigurationsmöglichkeiten des `opsi-setup-detector`. Sie behandeln die Verwendung eines benutzerdefinierten Verzeichnisses, die Installation aus einem lokalen temporären Verzeichnis, die Verwaltung von Lizenzschlüsseln und die Anpassung von Benutzerprofilen und Desktopsymbolen.

include::common:partial$osd-checkboxes-subtasks.adoc[]

