////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the German creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      11.01.2021
:doctype: book
:getstarted:  getting started

include::common:partial$opsi_terms.adoc[]


[[opsi-getting-started-installation-config-get-essential-products]]
= Importing the minimal opsi products

For deploying software with opsi ready-made packages are available.
One of these contains the agent ('opsi-client-agent'), which must be installed on the clients to enable management.

It is possible to install the packages in automated or manual fashion.
The automated way is recommended.

[[opsi-getting-started-installation-config-get-essential-products-automatic]]
== Automatic import of the minimal opsi products

For the automatic installation of opsi products the `opsi-package-updater` tool is available, which as configured as in '/etc/opsi/opsi-package-updater.conf', automatically fetches the current packages from the opsi repository and installs them on the server.

[source,shell]
----
opsi-package-updater -v install
----

If a proxy is needed to access the internet, this may be entered in the `.repo` configuration files in `/etc/opsi/package-updater.repos.d/` as the value for `proxy`.
Since opsi-utils version 4.1.1.33 a global proxy can be configured in `/etc/opsi/opsi-package-updater.conf`.

[source,configfile]
----
[repository_uib_windows]
...
proxy =
----

To later update the installed packages, this can be done with the following command:
[source,shell]
----
opsi-package-updater -v update
----

More information on `opsi-package-updater` can be found in the manual.

NOTE: Please note that OS installation products like win10-x64, are not immediately ready for use after installation. The installation has to be supplemented by the installation files from the corresponding installation media (i.e. DVD, see xref:os-installation.adoc#opsi-getting-started-firststeps-osinstall-fill-base-packages[OS-Installation: Complete the Base Package for Windows]).


[[opsi-getting-started-installation-config-get-essential-products-manually]]
== Manual import of opsi products

There is also the option of manually downloading and installing the packages.

Download the current opsi packages in the `.opsi` package format.
The packages can be found at https://download.uib.de/opsi4.2/stable/packages/windows in the directories `netboot/`, `localboot/` and for Linux-clients also in `https://download.uib.de/opsi4.2/stable/packages/linux`.

We recommend to save these .opsi-files in `/var/lib/opsi/repository`.
To make sure opsiconfd is allowed to access these files run `opsi-set-rights /var/lib/opsi/repository`.

After the download you have to install the packages on your server with the command `opsi-package-manager -i <packagename>.opsi`.
If the packages are stored under `/var/lib/opsi/repository`, the following command can be used for the initial installation:
[source,shell]
----
opsi-package-manager --install /var/lib/opsi/repository/*.opsi
----
