////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the German creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      24.04.2023
:Revision:  4.2
:toclevels: 6
:doctype:   book
:icons: font
:xrefstyle: full

ifeval::["{mode}" == "antora"]
include::common:partial$opsi_terms.adoc[]
endif::[]

[[opsi-getting-started-requirements]]
= Prerequisites

This chapter describes the requirements for the installation of the opsi server on Linux. A list of supported distributions can be found in chapter xref:supportmatrix:supportmatrix.adoc[Supported Systems].

[[opsi-getting-started-requirements-hardware]]
== Hardware

These are the prerequisites for an opsi server on real hardware:

* x86-64 or ARM64 system.
* 2{}GB RAM or more
* 2 CPU cores or more

How much hard disk space the server needs depends, among other things, on the number of installed opsi packages. For productive systems the following recommendations apply:

* Make sure that there is always at least 15{nbsp}GB of free space available in the `/tmp` directory.
* In the `/var/lib/opsi` directory, you need at least 60{nbsp}GB; the folder must be flexibly expandable.

Depending on the configuration and the daily routines, varying numbers of opsi clients will access an opsi server. RAM and CPU requirements can increase significantly in large environments with many simultaneous client connections.

TIP: The central opsi service `opsiconfd` requires approx. 250{nbsp}MB RAM per worker process. We recommend to allocate one worker process for 20 simultaneous connections. The number of CPU cores should be about half the number of worker processes. In the default configuration, you should plan for additional resources for Samba, MySQL and Redis.

[[opsi-getting-started-introduction-software-and-configuration-preconditions]]
== Configuration

To install opsi, certain network and language settings are required. The next sections explain necessary DNS (Domain Name System) and localization settings.

[[opsi-getting-started-requirements-software-dns-domainname]]
=== Valid Domain Name

The domain name must consist of at least a domain and a top-level domain (TLD), i.e. must consist of at least the host name, a dot and a top-level domain (two characters):

* For example, `domain.local`, `uib.de`, `subdomain.domain.de` are valid.
* *Not* allowed are `mydomain.d` (TLD has only one character) or `mydomain` (TLD is missing).

TIP: For more information, visit https://en.wikipedia.org/wiki/Domain_name.

[[opsi-getting-started-requirements-software-dns-hostname]]
=== Valid Hostname

iThe opsi server and also the opsi clients must have a valid hostname. Letters (a to z, A to Z), numbers and the hyphen are allowed. The underscore and other special characters are not allowed.

On Linux, check the settings with the `hostname` command. Use the `-f` parameter to display the Fully Qualified Domain Name (FQDN):

[source,prompt]
----
hostname -f
----

The output should return an FQDN with at least two dots in it, e.g. `opsiserver.domain.local`. If the result looks different and you get something like `127.0.0.1` or `localhost` as response, first correct the `/etc/hosts` file or your name resolution (see the next section).

TIP: Further information on valid hostnames can be found here: https://en.wikipedia.org/wiki/Hostname

[[opsi-getting-started-requirements-software-dns-resolving]]
=== Correct Name Resolution for the Server

Check the entry for the opsi server in the `/etc/hosts` file or enter the following command on the command line:

[source,prompt]
----
getent hosts $(hostname -f)
----

For example, the result should look like this:

[source,prompt]
----
192.168.1.1 server.domain.tld server
----

This should list the IP address of the network interface to which the clients will later connect. If you see only entries for `localhost`, `127.0.0.1`, or `127.0.0.2` in the `/etc/hosts` file, then correct the name resolution before you proceed.

NOTE: Even if the names have to comply with the defaults of a DNS system, you don't need a DNS server to run opsi. opsi doesn't require an Active Directory or similar either, even if an integration into a directory service is possible.

[[opsi-getting-started-requirements-software-lang]]
=== Language Settings (`locale`)

opsi needs the language to be set on the server via `locale`. To check the language settings, you can enter the following command, for example:

[source,prompt]
----
test -e /etc/default/locale && echo "ok" || (echo "Check locales:" && locale)
----

If you see `ok` as a response, everything is fine. If, on the other hand, `check locales:` appears, then set the settings via the `LANG` or `LC_ALL` environment variables.

TIP: We recommend a localization with UTF-8 support, e.g. `en_GB.UTF-8` or `en_US.UTF-8`.

The following commands show how these settings can be changed if nothing or an unwanted value is set:

[source,prompt]
----
sudo locale-gen en_GB.UTF-8
update-locale LANG=en_GB.UTF-8
----

For more information, please consult the documentation of your Linux distribution.

[[opsi-getting-started-installation-config-ports]]
== Network Protocols and Ports used

opsi and its services use the following network protocols and ports:

* opsi server, web service: 4447/tcp +.
client to config and depot server, depot server to config server, also connections via `localhost`
* opsi client, web service: 4441/tcp +
config server to client, connection from client to itself via `localhost`
* opsi client, notifier: 45000/tcp to 45099/tcp +
connection from client to itself via `localhost`, selection of a random port from the given range
* TFTP: 69/udp +
connection from client to depot server
* TFTP: 1024/udp to 65535/udp +
connection from depot server to client
* CIFS/SMB: 445/tcp + 
connection from client to depot server
* CIFS/SMB: 445/tcp + 
connection from depot server to client (only necessary if `opsi-deploy-client-agent` (`winexe`, `smbclient`) is used for Windows clients)
* Grafana, web service: 3000/tcp +
connection from client to config server (only when client accesses config server management website)
* SSH: 22/tcp +
connection from client to config server and depot server
* SSH: 22/tcp + connection from
connection from depot server to client (only when using `opsi-deploy-client-agent` on Linux and macOS)
* DNS: 53/tcp, 53/udp +
All servers and clients must be able to reach your DNS service.
* Wake-on-LAN (WoL): 7/udp, 9/udp, 12287/udp +
connection from config server to client; ports are configurable
* HTTP: 80/tcp +
config and depot server to the Internet, e.g. to load server updates from http://download.opensuse.org
* HTTPS: 443/tcp + 
config and depot server to the internet, for example to load packages from https://download.uib.de (`opsi-package-updater`)

NOTE: The config server is the central opsi server to manage all clients. The depot server is the server that holds the installation packages of the deployed software. If there is only one opsi server, it assumes both roles.

[[opsi-getting-started-installation-config-proxy]]
== Proxy Settings

If you are using an HTTP proxy, then configure the system-wide proxy settings with environment variables (`/etc/environment` file).

NOTE: Please note that the names of the environment variables use lowercase letters only.

* `http_proxy`: configures the proxy for HTTP connections, requires a full URL (not just hostname and port); if authentication is required, it can be defined in the URL: +
`http_proxy=http://<user>:<password>@<proxy-address>:<port>`
* `https_proxy`: like `http_proxy`, but for HTTPS connections: +
`https_proxy=https://<proxy-address>:<port>` 
* `no_proxy`: defines for which addresses no proxy should be used; multiple addresses are separated by commas: +
`no_proxy=127.0.0.1,localhost,mydomain.example,hostname.domain.com:8080` +
The following rules apply to the addresses:
** Use lowercase letters only. 
** Only note IP addresses if the IP address is also accessed directly. No name resolution takes place when evaluating exceptions.
** IP address ranges (CIDR matching, such as `192.168.0.0/24`) are not allowed.
** You must also define exceptions for local addresses (`localhost`) and loopback addresses (`127.0.0.1`).
** Wildcards and regular expressions are not allowed. 
** Each name is evaluated as a suffix, so `domain.com` defines an exception for all hostnames ending in `domain.com`.
** For each address, you can optionally specify a port after a colon for which the exception applies.
