////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
////

:Author:    uib gmbh
:Email:     info@uib.de
:Revision:  4.2
:doctype: book
:macosclientmanual: opsi-macos-client-manual

include::common:partial$opsi_terms.adoc[]


[[firststeps-software-deployment-product-tests]]
= Rollout existierender Produkte auf macOS

Für den Rollout von Software auf Clients muss auf diesen der _opsi-client-agent_ installiert sein.
Dieser kann auf  xref:adding-clients.adoc#firststeps-software-deployment-client-integration[bestehende Rechner] ausgerollt werden.


Nachfolgend wird die Management-Oberfläche <<firststeps-software-deployment-product-tests-configed,{opsi-configed}>> verwendet, um Software auf Clients zu verteilen.


include::common:partial$firststeps-swdp-product-tests-inventory.adoc[leveloffset=-1]

[[opsi-macclient-firststeps-software-deployment-product-tests-homebrew]]
== Verteilung von opsi Standard Produkten: m-homebrew

Dieses Produkt installiert das Paketverwaltungsprogramm `homebrew` welches von verschiedenen anderen opsi-Produkten für macOS verwendet wird, z.B. zur Installation von Java.

Siehe auch: xref:general-notes.adoc#opsi-macclient-hints-homebrew[Das opsi Produkt m-homebrew]

Wählen Sie im _opsi-configed_, Modus _Client-Konfiguration_, unter dem Reiter _Clients_ den betreffenden Client aus.

Wechseln Sie zum Reiter _Produktkonfiguration_, klicken Sie in die Spalte _Angefordert_ für das Produkt _m-homebrew_, daraufhin öffnet sich eine Liste/Dropdown-Menü und dort wählen Sie die Aktion _setup_.

Der Haken in der Icon-Menüleiste sollte seine Farbe auf Rot wechseln. Wenn Sie ihn anklicken, werden die neuen Einstellungen zum {opsi-Server} übermittelt, im Anschluss ist seine Farbe wieder grün.

Starten Sie dann den Client (neu) oder pushen Sie die Installation per _on_demand_
Er sollte jetzt den _opsi-client-agent_ starten und das Produkt _m-homebrew_ installieren.

[[opsi-macclient-firststeps-software-deployment-product-tests-java]]
== Verteilung von opsi Standard Produkten: m-javavm

Dieses Produkt installiert die Java Runtime Umgebung welche von verschiedenen anderen opsi-Produkten für macOS verwendet wird, z.B. opsi-configed, opsi-logviewer

Wählen Sie im _{opsi-configed}_, Modus _Client-Konfiguration_, unter dem Reiter _Clients_ den betreffenden Client aus.

Wechseln Sie zum Reiter _Produktkonfiguration_, klicken Sie in die Spalte _Angefordert_ für das Produkt _m-javavm_, daraufhin öffnet sich eine Liste/Dropdown-Menü und dort wählen Sie die Aktion _setup_.

Der Haken in der Icon-Menüleiste sollte seine Farbe auf Rot wechseln. Wenn Sie ihn anklicken, werden die neuen Einstellungen zum {opsi-Server} übermittelt, im Anschluss ist seine Farbe wieder grün.

Starten Sie dann den Client (neu) oder pushen Sie die Installation per _on_demand_
Er sollte jetzt den _opsi-client-agent starten und das Produkt _m-javavm_ installieren.


[[firststeps-software-deployment-product-tests-configed]]
== Verteilung von opsi Standard Produkten: {opsi-configed}

Achtung: m-homebrew und m-javavm müssen bereits installiert sein!

Zu den Standard-Produkten gehört das Produkt _opsi-configed_ welches das opsi Management Interface als Anwendung auf einem Rechner installiert.
Da diese Anwendung eine Java-Anwendung ist, wird ein JavaRE mitgeliefert.

Wählen Sie im _{opsi-configed}_, Modus _Client-Konfiguration_, unter dem Reiter _Clients_ den betreffenden Client aus.

Wenn noch nicht geschehen, aktualisieren Sie den Datenbestand des {opsi-configed}s mittels _Datei/Daten neu laden_ bzw. Anklicken des entsprechenden Icons.

Wechseln Sie zum Reiter _Produktkonfiguration_, klicken Sie in die Spalte _Angefordert_ für das Produkt +opsi-configed+, daraufhin öffnet sich eine Liste/Dropdown-Menü und dort wählen Sie die Aktion _setup_.

Der Haken in der Icon-Menüleiste sollte seine Farbe auf Rot wechseln. Wenn Sie ihn anklicken, werden die neuen Einstellungen zum {opsi-Server} übermittelt, im Anschluss ist seine Farbe wieder grün.

Starten Sie dann den Client (neu).
Er sollte jetzt den _opsi-client-agent_ starten und das Produkt _opsi-configed_ installieren.
Nach Abschluß der Installation sollten Sie unter `Applications` den Punkt `opsi-configed` finden.
