////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      11.01.2023
:doctype: book

include::common:partial$opsi_terms.adoc[]

[[opsi-manual-opsiwebgui-instguide]]
= Installation

Dieses Kapitel zeigt zwei Möglichkeiten die {opsi-webgui} auf dem Config-Server zu installieren: Die Installation über das opsi-Repository und über das Admininterface. 
Dabei empfehlen wir die erste Variante, da dadurch bei jedem update der installierten Systempakete, auch die webgui geupdated wird. 

== Installation aus dem opsi-Repository

Für die Installation der {opsi-webgui} aus dem opsi-Repository muss sichergestellt werden, dass der korrekte Zweig in den Repositories eingetragen ist. 
Danach kann die Installation mittels des Paketmanagers des Systems durchgeführt werden. 
Anschließend ist die {opsi-webgui} unter https://<configserver-address>:4447/addons/webgui/app erreichbar.

NOTE: Derzeit ist {opsi-webgui} zur Zeit nur im {release} Zweig verfügbar.

*Beispiel für Debian / Ubuntu* +
Wir empfehlen eine Außnahme für die {opsi-webgui} einzurichten (sofern Sie nicht den {release} Zweig als Hauptzweig in der `/etc/apt/sources.list.d/opsi.list` eingetragen haben). +

. Optional: Legen Sie eine Datei in den Order `/etc/apt/preferences.d/` bspw. `10-opsi-webexp`, die den folgenden Inhalt hat: 
+
--
[source]
----
# /etc/apt/preferences.d/10-opsi-webexp
Package: *
Pin: release l=home:uibmz:opsi:4.3:stable
Pin-Priority: 501

Package: opsi-webgui
Pin: release l=home:uibmz:opsi:4.3:experimental
Pin-Priority: 502
---- 

Der Inhalt sagt dem System, dass alle Pakete sofern verfügbar aus dem stable Repository bezogen werden sollen. 
Für die {opsi-webgui} gilt zusätzlich das experimental Repository.
--


. Installieren Sie die {opsi-webgui} mittels
+
--
[source, prompt]
----
sudo apt update
sudo apt install opsi-webgui
sudo opsiconfd restart
---- 

Um die {opsi-webgui} zu updaten kann folgender Befehl verwendet werden:

[source, prompt]
----
sudo apt update
sudo apt upgrade opsi-webgui
----
--

[[opsiwebgui-installation-admininterface]]
== Installation über das Admininterface mittels ZIP-Datei
Die Installation über das Admininterface funktioniert unabhängig des verwendeten Systems. 
Da aber lediglich _eine_ Installation durchführt wird, müssen Updates üblicherweise (sofern das korrekte Repository nicht eingerichtet ist) manuell eingespielt werden. 
Deswegen wird diese Variante nur empfohlen, wenn spezielle Versionen der webgui (beispielsweise zu Testzwecken) zur Verfügung gestellt werden. 

Um eine Installation mittels der opsi-webgui.zip durchzuführen, folgen Sie folgenden Schritten: +

. Laden Sie die neuste Version der Webgui (ZIP-Datei) von https://tools.43.opsi.org/{release}/ herunter. 

. Öffnen Sie https://<configserver-address>:4447/admin/#addons, laden Sie die Datei hoch und installieren Sie diese.

