////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      20.11.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

[[opsi-manual-opsiwebgui-instguide]]
= Installation

Dieses Kapitel stellt zwei Methoden vor, um das opsi-WebGUI auf dem Config-Server zu installieren: über das opsi-Repository und über das Admin-Seite. Wir empfehlen Ihnen die Installation über das opsi-Repository, da diese Methode sicherstellt, dass das WebGUI bei jedem Update der Systempakete automatisch aktualisiert wird.

== Installation aus dem opsi-Repository

Stellen Sie zuerst sicher, dass Sie den richtigen Branch in den Repositorys eintragen, um das WebGUI zu installieren. Danach installieren Sie die Anwendung mit dem Paketmanager der Distribution. Anschließend erreichen Sie das WebGUI unter `\https://<opsi-server>:4447/addons/webgui/app` im Browser.

== Beispiel für Debian/Ubuntu

Wir empfehlen eine Außnahme für die {opsi-webgui} einzurichten (sofern Sie nicht den {release} Zweig als Hauptzweig in der `/etc/apt/sources.list.d/opsi.list` eingetragen haben). +

. Optional: Legen Sie eine Datei in den Order `/etc/apt/preferences.d/` bspw. `10-opsi-webexp`, die den folgenden Inhalt hat: 
+
--
[source]
----
# /etc/apt/preferences.d/10-opsi-webexp
Package: *
Pin: release l=home:uibmz:opsi:4.3:stable
Pin-Priority: 501

Package: opsi-webgui
Pin: release l=home:uibmz:opsi:4.3:experimental
Pin-Priority: 502
---- 

Der Inhalt sagt dem System, dass alle Pakete sofern verfügbar aus dem stable Repository bezogen werden sollen. 
Für die {opsi-webgui} gilt zusätzlich das experimental Repository.
--


. Installieren Sie die {opsi-webgui} mittels
+
--
[source, prompt]
----
sudo apt update
sudo apt install opsi-webgui
sudo opsiconfd restart
---- 

Um die {opsi-webgui} zu updaten kann folgender Befehl verwendet werden:

[source, prompt]
----
sudo apt update
sudo apt upgrade opsi-webgui
----
--

[[opsiwebgui-installation-admininterface]]
== Installation über das Admin-Seite

Die Installation über die xref:server:components/opsiconfd.adoc#server-components-opsiconfd-admin-page[Admin-Seite] funktioniert unabhängig des verwendeten Systems. 
Da aber lediglich _eine_ Installation durchführt wird, müssen Updates üblicherweise (sofern das korrekte Repository nicht eingerichtet ist) manuell eingespielt werden. 
Deswegen wird diese Variante nur empfohlen, wenn spezielle Versionen der webgui (beispielsweise zu Testzwecken) zur Verfügung gestellt werden. 

Um eine Installation mittels der opsi-webgui.zip durchzuführen, folgen Sie folgenden Schritten: +

. Laden Sie die neuste Version der {opsi-webgui} (ZIP-Datei) von https://tools.43.opsi.org/{release}/ herunter. 

. Öffnen Sie https://<configserver-address>:4447/admin/#addons, laden Sie die Datei hoch und installieren Sie diese.

