////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      11.01.2021
:doctype: book

include::common:partial$opsi_terms.adoc[]

[[opsi-manual-opsiwebgui-technology]]
= Technologie-Stack
Die opsi-webgui ist als {opsiconfd}-Addon aufgebaut und befindet sich im Verzeichnis `/var/lib/opsiconfd/addons/webgui` auf dem Config-Server.

Das Backend der webgui ist mit FastAPI, einem Python-Framework, erstellt und für das Lesen und Schreiben von Daten aus der MySQL-Datenbank verantwortlich.
Um die Performance erheblich zu verbessern, interagiert das Backend direkt mit der Datenbank, wodurch die MySQL-Erweiterung notwendig ist.
Zusätzlich findet auch eine Kommunikation mit dem {opsiconfd} für das Session-Handling und Logging statt.

Das Frontend ist mit Nuxt, einem Vue.js-Framework, entwickelt. Es stellt Anfragen an das Backend, ruft Daten ab und zeigt diese in geeigneten Formaten an.
