////
; Copyright (c) uib GmbH (uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      21.07.2026
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



[[opsi-manual-opsiwebgui-userguide]]
= Benutzerhandbuch

Dieses Kapitel beschreibt die Arbeit mit dem OPSI-WebGUI: die Anmeldung, die Benutzeroberfläche sowie die Verwaltung von Servern, Clients, Produkten und Gruppen.

[[opsi-manual-opsiwebgui-user-requirements]]
== Voraussetzungen

Um das OPSI-WebGUI nutzen zu können, benötigen Sie:

* Einen aktuellen Browser (Chrome/Chromium, Firefox, Safari oder Edge) mit aktiviertem JavaScript. Falls Sie ein Addon wie NoScript nutzen, erlauben Sie die OPSI-WebGUI-Seite.
* Netzwerkzugriff auf den OPSI-Configserver (`opsiconfd`, Port 4447). Eine Internetverbindung ist nicht erforderlich.
* Einen Benutzeraccount in der Gruppe `opsiadmin` (siehe xref:server:components/authorization.adoc[Berechtigungen]).

[[opsi-manual-opsiwebgui-login]]
== Erste Schritte

Öffnen Sie `\https://<opsi-server>:4447/addons/webgui/app` im Browser und melden Sie sich an.
Die Anmeldeseite, die Authentifizierungsmethoden, SAML Single Sign-on und was nach der Anmeldung passiert, beschreibt das Kapitel xref:gui:webgui/userguide-login.adoc[Anmeldung und Routing].

Die folgenden Kapitel sind wie eine typische Arbeitssitzung aufgebaut: zuerst die Anmeldung und die Benutzeroberfläche, danach die Seiten in derselben Reihenfolge wie in der Navigationsleiste der OPSI-WebGUI.
