////
; Copyright (c) uib GmbH (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib GmbH
:Email:     info@uib.de
:Date:      06.12.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full



[[opsi-manual-opsiwebgui-troubleshooting]]
= Problembehebung

Dieses Kapitel beschreibt mögliche Probleme mit dem WebGUI und gibt Tipps zur Lösung.

[[opsi-manual-opsiwebgui-troubleshooting-emptyconfigserver]]
== Leere opsi-Configserver ID

Bleibt das oberste Feld leer und zeigt nicht die ID des opsi-Configservers an, kann es sein, dass Sie den Zugriff auf den opsi-Configserver bzw. auf den Dienst `opsiconfd` verloren haben.

Mögliche Lösungsvorschläge:

* Öffnen Sie die Admin-Seite `\https://<opsi-server>:4447/admin` im Browser, melden sich an und verifizieren/akzeptieren Sie das SSL-Zertifikat, falls erforderlich.

* Starten Sie den Dienst `opsiconfd` neu, z.{nbsp}B. mit diesem Kommando:

[source,console]
----
systemctl restart opsiconfd.service
----

TIP: Weitere Informationen zum Dienst `opsiconfd`, zu seinem Kommandozeilen-Interface und der Admin-Seite finden Sie im Kapitel xref:server:components/opsiconfd.adoc[Der Dienst *opsiconfd*].


[[opsi-manual-opsiwebgui-troubleshooting-blankpage]]
== Leerer Seiteninhalt

Sind die Navigationsleiste am linken und am oberen Rand sichtbar, bleibt die Anzeige ansonsten aber leer, kann es sein, dass Ihre Session abgelaufen ist. Laden Sie die Seite neu, z.{nbsp}B. mit der Tastenkombination [Strg]{plus}[F5]; das leert auch gleichzeitig den Seiten-Cache. Alternativ öffnen Sie einen neuen Reiter im Browser und öffnen das WebGUI dort.
