////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
; 
; credits: http://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      11.08.2023
:doctype: book

include::common:partial$opsi_terms.adoc[]

Dieses Kapitel enthält Hinweise zum Finden und Beheben von Problemen.


[[opsi-manual-opsiwebgui-troubleshooting]]
= Troubleshooting
Dieser Abschnitt enthält Hinweise zum Finden und Beheben von Problemen.

[[opsi-manual-opsiwebgui-troubleshooting-emptyconfigserver]]
== Leere {opsi-configserver} ID
_Leeres {opsi-configserver} ID-Feld in der Login-Seite_: Dies kann passieren, wenn Sie den Zugriff auf den {opsi-configserver} bzw. {opsiconfd} verlieren. +
Mögliche Lösungsvorschläge: +

  * Greifen Sie auf https://<configserver-address>:4447/admin zu und verifizieren und akzeptieren sie das Zertifikat falls nötig.
  * Starten Sie den {opsiconfd} neu bspw. mittels dem Befehl `systemctl restart opsiconfd.service`

[[opsi-manual-opsiwebgui-troubleshooting-blankpage]]
== Leerer Seiteninhalt
_Leerer Seiteninhalt mit sichtbarem oberen und Navigationsmenü_: Dies kann passieren, wenn Ihre Session abgelaufen ist. +
Laden Sie die Seite neu. Eine Möglichkeit dafür ist die Tastenkombination "Strg+F5", dadurch wird auch der Browser Cache neu geladen. Alternativ können Sie auch einen neuen Browser-Tab öffnen.
