
////
; Copyright (c) uib gmbh (www.uib.de)
; This documentation is owned by uib
; and published under the german creative commons by-sa license
; see:
; https://creativecommons.org/licenses/by-sa/3.0/de/
; https://creativecommons.org/licenses/by-sa/3.0/de/legalcode
; english:
; https://creativecommons.org/licenses/by-sa/3.0/
; https://creativecommons.org/licenses/by-sa/3.0/legalcode
;
; credits: https://www.opsi.org/credits/
////

:Author:    uib gmbh
:Email:     info@uib.de
:Date:      08.05.2023
:Revision:  4.3
:toclevels: 6
:doctype:   book
:icons:     font
:xrefstyle: full

include::common:partial$opsi_terms.adoc[]

= Interfaces

The opsi-server has several interfaces that fulfil different functions.
As an admin user, all endpoints can be viewed and even executed via https://<opsi-server>:4447/docs.

== JSON RPC

The server data can be manipulated via the JSON RPC interface. 
A detailed description of the JSON RPC API can be found in the next chapter xref:interfaces/jsonrpc-api.adoc[JSON RPC API].

== Webgui interface

If the opsiconfd addon opsi-WebGui is installed, a REST API is added to the server. 
This API is specially adapted to the needs of the opsi-WebGui.


== Other API endpoints

- */status* : Can be used without logging in and provides simple status output for monitoring tools.
[source,console]
----
status: ok
version: 4.3.0.104 [python-opsi-common=4.3.0.73]
date: 2023-11-10T15:50:48+01:00
node: opsi-acme-43_opsi-server_1
fqdn: opsi.acme.corp
redis-status: ok
redis-error: 
redis-mem: 32911240
redis-mem-total: 36806536
ssl-ca-valid-days: 713
ssl-cert-valid-days: 73
----
- */monitoring*: Endpoint for the opsi-nagios-connector extension. Further information can be found xref:opsi-modules:nagios-connector.adoc[here].

